### ISSUE TITLE
Sync issue when installing a game for Steam on Windows and Linux

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#1001]
See: https://forums.lutris.net/t/lutris-changing-custom-wine-game-options-to-stock-linux-steam-options/2780/4

**Comment by duhow** [comment]
* Install CS from Wine Steam (Lutris installer not available for Windows Steam).
* Sync Lutris, the game appears.
* Add a custom argument `-windowed +var1`
* Install CS from [Lutris script](https://lutris.net/games/counter-strike/) (Linux Steam)
* Add custom argument. `-fullscreen +var2`

Both games appear on the list, no configuration/arguments lost. **Can't reproduce**, or does the game need to have both Lutris installers?

![image](https://user-images.githubusercontent.com/1145001/43674924-2f1283ec-97db-11e8-9a28-593192c4d4e5.png)
```
DEBUG    2018-08-04 11:38:29,353 [config]:Saving config LutrisConfig(level=game, game_config_id=counter-strike-steam-1533375087, runner=steam)
DEBUG    2018-08-04 11:38:36,830 [config]:Saving config LutrisConfig(level=game, game_config_id=counter-strike-1533372339, runner=winesteam)
```

**Comment by duhow** [comment]
Config file is `game-timestamp`, so there shouldn't be any conflict between both games, even if the name is the same.
