### ISSUE TITLE
PPA won't get signed on Ubuntu 18.04

### ISSUE THREAD

**Issue by nanangarsyad** [lutris/lutris#1005]
I'd tried to install lutris package by following these steps mentioned here:
https://lutris.net/downloads/
But, it always gave me this error message, when I do `sudo apt update`.
```
E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

I'd even tried using this [method](https://askubuntu.com/questions/291035/how-to-add-a-gpg-key-to-the-apt-sources-keyring/865494#865494), and sadly gave me this error message:

```
Executing: /tmp/apt-key-gpghome.P8dhqkhWQi/gpg.1.sh --fetch http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/Release.key
gpg: requesting key from 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/Release.key'
gpg: key 2F7F0DA5FD5B64B9: 1 signature not checked due to a missing key
gpg: key 2F7F0DA5FD5B64B9: "home:strycore OBS Project <home:strycore@build.opensuse.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
At first, I thought it'll be fine if I installed lutris through this repository, But this warning, make me think twice.

> _Warning: If Lutris isn't installed from your package manager already, some features such as browser integration or xboxdrv support will be missing. We recommended you keep the latest version installed, even if you're going to run the development branch._ 

Please help. Thank you.

**Comment by luthub** [comment]
Hello, are you sure you ran the third command of the download instructions?
`wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -`

After that you should be able to apt update and install
Also, that warning is related to running the development version of Lutris. You shouldn't be affected by it

**Comment by strycore** [comment]
Yes, it seem you didn't import the key. ("1 signature not checked due to a missing key")

**Comment by thamerbelfkihthamer** [comment]
> Hello, are you sure you ran the third command of the download instructions (If you run it from a new terminal window, you'll have to run the first command again for it to work)?
> `wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -`
> 
> After that you should be able to apt update and install
> Also, that warning is related to running the development version of Lutris. You shouldn't be affected by it

when I run this, I get this message from the console: 

> gpg: no valid OpenPGP data found.

**Comment by strycore** [comment]
I'm deleting the OBS repository, it doesn't serve a purpose and confuses people

**Comment by trentchilders** [comment]
Hey there. I'm also getting
```
gpg: no valid OpenPGP data found
```
When I try to update the keys. Has anyone solved this issue yet?

**Comment by strycore** [comment]
> I'm deleting the OBS repository, it doesn't serve a purpose and confuses people

**Comment by taj0023** [comment]
I have been with this error for a year.......... Couldnt find a solution.
If OP already solved this, please share.
