### ISSUE TITLE
Libretro ignoring runtime?

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1008]
Libretro/Retroarch wasn't launching because of missing libCg and libCgGL even though the files are present in the runtime.

    /home/cxf/.local/share/lutris/runners/retroarch/retroarch: error while loading shared libraries: libCg.so: cannot open shared object file: No such file or directory.

    /home/cxf/.local/share/lutris/runners/retroarch/retroarch: error while loading shared libraries: libCgGL.so: cannot open shared object file: No such file or directory

Only after installing them on my PC did it launch.

**Comment by RobLoach** [comment]
Is the following a valid configure option???

```
https://github.com/lutris/buildbot/blob/master/runners/libretro/build.sh#L46

**Comment by AccountOneOff** [comment]
Searching `--disable-cg` on Google does look like a valid option. However, I'm not sure what to do with the build script. Running it directly is obviously not gonna work...

    cxf@PC:~$ ./build.sh 
    + lib_path=../../lib/
    + source ../../lib/path.sh
    ./build.sh: line 6: ../../lib/path.sh: No such file or directory

**Comment by RobLoach** [comment]
Could see the options with.....

```
git clone https://github.com/libretro/RetroArch.git
cd RetroArch
./configure --help
```

**Comment by strycore** [comment]
shouldn't we figure out why it's ignoring the runtime before remove the dependency? I don't think we require Cg shaders, the GLSL ones should provide the same thing but it's just for the sake of debugging the issue.

**Comment by strycore** [comment]
@AccountOneOff can you uninstall libCg to reproduce the issue and then run:
```
cd ~/.local/share/lutris/runtime
ldd ./steam/amd64/usr/lib/x86_64-linux-gnu/libCg.so
```

**Comment by AccountOneOff** [comment]
```
cxf@PC:~/.local/share/lutris/runtime$ ldd steam/amd64/usr/lib/x86_64-linux-gnu/libCg.so 
	linux-vdso.so.1 (0x00007ffe586d2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76d9705000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f76d94e6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76d90f5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f76daa0b000)

**Comment by strycore** [comment]
same with the 32bit one?

**Comment by AccountOneOff** [comment]
```
cxf@PC:~/.local/share/lutris/runtime$ ldd steam/i386/usr/lib/i386-linux-gnu/libCg.so 
	linux-gate.so.1 (0xf7f83000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf756a000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf754b000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf736f000)
	/lib/ld-linux.so.2 (0xf7f85000)
