### ISSUE TITLE
“Restore default gamma....” doesn’t restore gamma after game quits

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1010]
For some reason, with "Restore default gamma..." option enabled, default screen gamma is not restored after a game that changes it quits (even after Lutris kills processes in the prefix)
When running Lutris in debug mode (-d) I get this Warning:
"WARNING  2018-08-08 18:46:47,323 [display.restore_gamma:168]:xgamma is not available on your system"
Would be nice to fix this, as changing screen gamma back manually is a bit annoying.

**Comment by strycore** [comment]
If xgamma isn't installed I don't how we can possibly resotore gamma....

What would be more reasonable would be to gray out that option when xgamma isn't available

**Comment by CitrusAlex** [comment]
Oh I am sorry I was in a hurry and completely forgot to mention that I do have xgamma installed and it works if I run “xgamma -gamma 1”, which restores gamma to default.

**Comment by CitrusAlex** [comment]
That’s the thing, it shouldn’t... but it does.
The distro I am using is Arch with XFCE running in Xorg and I got Lutris
from aur, but I get the same thing with lutris-next and I think I had this
same issue on Ubuntu using Xorg though I will have to install it in a VM
and test it to be sure.

**Comment by CitrusAlex** [comment]
Oh also if you google “lutris xgamma not installer” there will be quite a few issues linked to this projects witht the same Warning message, though I can be certain those users have xgamma installed, but it’s very likely as pretty much all distros still have Xorg and Wayland adoption rates are still low.

**Comment by strycore** [comment]
I'm pretty sure most of those results are misdiagnosis of issues, when xgamma isn't installed, we don't run xgamma, that's it. It's not going to cause crashes or anything. It's like that winemenubuilder message, people are reading too much into it.

**Comment by CitrusAlex** [comment]
I wouldn’t have any issues with that message,  but when a game I play (Sims
3) exists Lutris doesn’t restore the gamma to default, even if I stop the
processes in the prefix by pressing the stop button or letting it do that
by itself. I can’t be 100% that warning and xgamma restoration not working
are related but it’s just very likely.
Perhaps the way Lutris detects that xgamma is installed got borked by
whatever reasons?

**Comment by CitrusAlex** [comment]
Oh and those issues I mentioned didn’t complain about the xgamma really, they just contained that warning.

**Comment by luthub** [comment]
I just had a quick look at this, and it happens on my Solus install as well despite xgamma being installed.
The code in display.py checks the variable XGAMMA_FOUND, which is plainly set to false at the very beginning of the script and never changed again. I don't see how this could work for anyone

**Comment by strycore** [comment]
Fixed in master
