### ISSUE TITLE
Re-enabling of desktop effects takes too long

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1012]
After trying new "Disable Desktop Effects" option I have experienced quite a big nuance with it - it takes a lot of time for it to re-enable the compositor, and sometimes it actually never happens and I have to do that manually.
I assume it's because the option waits for the prefix to completely shutdown (as I can manually force it re-enable compositor by pressing the stop button), which can take a while or never even happen for whatever reasons. 
So maybe it should re-enable the compositor after only monitored processes exit instead to make it do that faster?
Or do whatever "Restore Gamma..." (that got fixed in #1011 ) does as it restores default gamma immediately after one of my games that changes gamma exits.

**Comment by strycore** [comment]
I don't know what to say...

I don't use either of those options and the fact that xgamma is called **after** restoring the compositor when the game quits makes the issue even more difficult to work on.

You might have to dive in the code a bit and add some log statements if you want to provide a ticket I can solve.

**Comment by strycore** [comment]
post launch actions will now be executed as soon as the game quits
