### ISSUE TITLE
make downloading and using lutris provided wine optional

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#1014]
![11-08-2018_08 37 55](https://user-images.githubusercontent.com/5204968/43988605-f9f3a508-9d41-11e8-8ce7-4ede36f5b1fa.png)
Downloading is pretty slow sometimes, and i'm using system version anyway.

**Comment by duhow** [comment]
When you install a game using a Lutris install script, it will download its wine package required, although you can change your Wine settings after completing the install.

You can also download the script and change it locally.
(btw, download is not that slow, and it's only done once)

**Comment by strycore** [comment]
The wine builds are moving to Amazon S3 eventually so that we solve the download speed issue. 

Also, what version do you currently have installed on your system?

**Comment by soredake** [comment]
git version, as always
I just want to have an option that will allow me not to download versions from Lutris and not use them, that is, I always use the system version, every time I change the version to the system one in the settings and update the prefix after the change to the system one, rather annoying.

**Comment by duhow** [comment]
You can set the default Wine version in Runner settings, so all the games
that you add manually will have that version. But as I said, the installer
will download and use the Wine version set, as the game might require that
version, or it may have better performance (for old games?)

**Comment by soredake** [comment]
>You can set the default Wine version in Runner settings, so all the games

I know how to use lutris, thanks.

>as the game might require that version, or it may have better performance (for old games?)

I can have build with all fixes i need, so there's no need for lutris-provided versions.

**Comment by duhow** [comment]
No problem. So... Requesting:

`Advanced options for install > Choose Wine version > System Wine`

**Comment by strycore** [comment]
> I can have build with all fixes i need, so there's no need for lutris-provided versions.

Yes, but that's only you. I agree that we should not try downloading wine if no explicit version is set but if there is one, we're not going to make it optional. That just plain wouldn't work and it's too risky.

**Comment by strycore** [comment]
Wine builds are now hosted on DigitalOcean and are downloading fast, marking this as closed

**Comment by tannisroot** [comment]
They are not fast, at least for me, specifically the versions that are over 100 megs. The downloading is actually super slow.
And even then, this is still an issue for people with slow or limited connections. Please re-open and maybe add as a goal for 0.5 instead.

**Comment by strycore** [comment]
This needs to be further designed to provide a proper solution.
I'm mark that for the 0.5 cycle since this is where we'll start letting the user customize the install process.
