### ISSUE TITLE
Disable or ignore a runner

### ISSUE THREAD

**Issue by KonomiKitten** [lutris/lutris#1015]
Hi would it be possible or is it currently possible to ignore a runner? I have Steam installed and when I launch Steam games they automatically get added to Lutris. I'd like to turn off this feature, or if that is not possible request a change so it is.

**Comment by duhow** [comment]
`Lutris > Import games`
Disable sync with Steam.

**Comment by KonomiKitten** [comment]
@duhow thank you that did it, closing issue.
