### ISSUE TITLE
fail install battle.net

### ISSUE THREAD

**Issue by LapotinVal** [lutris/lutris#1018]
INFO     2018-08-12 12:23:29,860 [lutriswindow]:Installing world-of-warcraft-dox-july-2018-update
INFO     2018-08-12 12:23:31,458 [runner]:Getting runner information for wine(version: pba-firerat-3.11-x86_64)
INFO     2018-08-12 12:26:59,553 [interpreter]:Downloading file 1 of 1
INFO     2018-08-12 12:27:07,586 [wine]:win64 Prefix created in /home/valera/Games/world-of-warcraft
------------------------------------------------------
ERROR    2018-08-12 12:27:43,231 [thread]:Failed to execute /home/valera/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine /home/valera/.cache/lutris/installer/world-of-warcraft/Battle.net-Setup.exe: [Errno 2] No such file or directory: '/home/valera/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine': '/home/valera/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/thread.py", line 191, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/valera/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine': '/home/valera/.local/share/lutris/runners/wine/pba-firerat-3.11-x86_64/bin/wine'
WARNING  2018-08-12 12:27:43,234 [thread]:No game process available
![2018-08-12 12-39-49](https://user-images.githubusercontent.com/2952972/44000659-db0f1d8e-9e2c-11e8-91c4-50890a6fcd03.png)

**Comment by duhow** [comment]
Try deleting the Wine version downloaded from
`Tree runners > Wine > right click > Manage versions`
And run installer again.

Also check if executable permission is set in the **mount** point (it should by default but... strange)

**Comment by LapotinVal** [comment]
(it should by default but... strange)...
fedora 28
just do: sudo dnf install wine
now all work
why it doesnt work without install wine in system, just install lutris & run game?(

**Comment by duhow** [comment]
#845
