### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by vinylourson** [lutris/lutris#102]
Lutris doesn't take into account environment settings regarding proxy settings. It doesn't have any option in the preferences either to set it manually.
This is a problem just to connect to your account and do all the things needed to be done through an internet connection with Lutris.
I know this is a feature mostly useful on corporate networks, but sometimes you do get bored at work and even 5 minutes of playing video games can save your day.

Lutris Version : 0.3.4
my proxy settings are set in /etc/environment

**Comment by strycore** [comment]
with $http_proxy and $https_proxy correctly set, there are no more issues (even for downloading icons)
