### ISSUE TITLE
Have logger scroll automatically only when at the bottom

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1021]
Currently the logger scrolls whenever it outputs which makes scrolling up useless unless the game is stopped. This behavior is annoying.

**Comment by duhow** [comment]
Which `logger`? If you mean the terminal, each terminal will have its options to stop this.

**Comment by AccountOneOff** [comment]
The builtin one. https://github.com/lutris/lutris/blob/master/lutris/gui/logwindow.py
