### ISSUE TITLE
[Suggestion] Add code quality analysis service to Lutris repo

### ISSUE THREAD

**Issue by NicoVIII** [lutris/lutris#1022]
Afaik Lutris does not use a tool for code quality analysis atm. For my personal projects I find that kind of tool always very helpful.
Maybe this is an option for Lutris as well? I would suggest including Codefactor. It supports python and is free for open-source projects.
If you want to you can have a look at https://codefactor.io and test it. It is easy to integrate with a GitHub repo and provides a nice badge for code quality :yum: 

If you don't have time for such nonsense that is also okay of course :see_no_evil:

**Comment by strycore** [comment]
I'd be up for at least trying! There are some code quality tools on a private jenkins instance I have, which also runs the unit tests (haven't managed to set up TravisCI with their old version of Ubuntu)

I also use Pylint locally in my editor but it would be nice to have something that can check style on PRs.

**Comment by NicoVIII** [comment]
Just to be complete:
Another option would be https://www.codacy.com/ as far as I can see.
I found it recently and it is also free for open source and easy to setup with GitHub.

**Comment by PythonicChemist** [comment]
It would also be a great low hanging fruit for new contributors to fix style/code quality issues. (In general a contribution section in the github wiki would be a great addition.)

**Comment by RobLoach** [comment]
[Pylint](https://www.pylint.org/) or similar local open source tooling may be good first step. Then you could run the tests locally without having to wait for the CI to kick in.

**Comment by strycore** [comment]
Now available here: https://www.codefactor.io/repository/github/lutris/lutris
