### ISSUE TITLE
PCSX2 runner crashed at launch: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#1023]
Hello,
if I launch a PS2 game in Lutris, nothing happened.

If I try to launch manually PCSX2:

~/.local/share/lutris/runners/pcsx2/$ ./PCSX2
Instruction non permise (core dumped)

~/.local/share/lutris/runners/pcsx2/$ ./PCSX2-linux.sh
Illegal instruction (core dumped)

~/.local/share/lutris/runners/pcsx2$ bash PCSX2-linux.sh PCSX2-linux.sh : ligne 75 : 4112 Instruction non permise (core dumped) GDK_BACKEND=x11 LD_LIBRARY_PATH="$MY_LD_LIBRARY_PATH" __GL_THREADED_OPTIMIZATIONS=1 mesa_glthread=true MESA_NO_ERROR=1 $DIR/PCSX2 “$@”

Thank you for your help

config:
Ubuntu 18.04
Nvidia

**Comment by strycore** [comment]
You have to run PCSX2 from Lutris if you want to use the Lutris build (or use the Lutris runtime like the client would). Check for errors when launching the game from Lutris in the terminal. Also, you should be able to launch the PCSX2 UI by right clicking on its name in the side bar.

**Comment by legluondunet** [comment]
I launched Lutris from terminal with debug option, I joined you the log.
[lutris.log](https://github.com/lutris/lutris/files/2293266/lutris.log)

**Comment by AlexanderRavenheart** [comment]
The lutris log file does not contain any relevant error information. 
Please provide the log file generated by PCSX2.

**Comment by legluondunet** [comment]
@AlexanderRavenheart "Please provide the log file generated by PCSX2." Could you say me where to find this log file?

I just installed PCSX2 from the official PPA: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily
I replaced PCSX2 lutris excutable by one from PPA, now it works. It's a workaround, but what's wrong with PCSX Lutris executable? How could I debug that issue?

**Comment by strycore** [comment]
I've updated the PCSX2 build and updated the runtime with some WX widgets dependencies
