### ISSUE TITLE
Do not change configuration with mouse wheel scrolling.

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1024]
There is no need to change options in 'Configure" menu with mouse wheel scrolling.
Current behavior creates situations when user can mess up their configuration just by scrolling through options and not realize it because UI doesn't make it very obvious.
Plus this duality of the scrolling action is just annoying because you have to dodge the selection boxes to just navigate through the menu.

**Comment by strycore** [comment]
This is annoying because it's a default behavior of Gtk and patching it out is not obvious. We plan to re-organize the UI to make this less of an issue, we'll see if this is something we want to implement on the new UI.

**Comment by nonchip** [comment]
just connecting the combobox's `scroll-event` signal to a `return true` callback should do the trick: https://mail.gnome.org/archives/gtk-app-devel-list/2016-May/msg00066.html
