### ISSUE TITLE
Avoid dots (.) in Steam Wine library path

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1034]
Because right now Lutris installs the game in one prefix, and actually launches it with another one, it results in Steam Wine library being on drive "Z:" and inside winesteam prefix, which is located in ~/.local/share/lutris .
But because that path contains ".local" directory, which has a dot in its name, it results in some games not launching due to that dot in ".local" . The examples of that are The Sims 3 and I think Fallout 3 (the installer for it was made by @daniel-j ).
Currently the installers for these games have a workaround that basically creates a new drive (G: in the Sims one) that symlinks to ~.local/share/lutris in prefix that launches the game to avoid the ./local directory in the path.
This relies on some magical feature of Steam that automatically picks up the game library on a new drive and makes it default, which I don't think is documented and may be some bug that can disappear in the future.
So it would be nice if this symlinking could be the default behavior to make the process of creating installers easier and not relying on weird features, plus other installer creators might not be aware of this issue with certain games and never add mentioned workaround.

**Comment by strycore** [comment]
I changed the letter to S: and symlinked the drive_c folder inside the default prefix
