### ISSUE TITLE
Disallow to launch Lutris as root

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1036]
Please?

**Comment by RobLoach** [comment]
Any reason why?

**Comment by tannisroot** [comment]
It results in Lutris's files and folders being owned by root and the users not being able to launch Lutris as a normal user. (example: https://forums.lutris.net/t/lutris-client-only-opens-when-opened-as-root-from-terminal/3020/8)
Plus it's just not safe.

**Comment by TingPing** [comment]
Graphical applications are never designed to run as another user, the fact it ever works is luck.

**Comment by strycore** [comment]
No, we are **not** adding a `--force-root` flag ever :rofl: 

We'll display a warning message and if the user ignores it, well, too bad for them.

**Comment by TingPing** [comment]
Just as a comparable story. HexChat has had a warning before startup on root users for like a decade now. Only Puppy linux users complain and honestly that distro should just feel bad about itself.

**Comment by AccountOneOff** [comment]
Maybe something similar to what Kate does when trying to run as root?

https://github.com/KDE/kate/blob/f20eec26a535c45f5eb7c0948862d690cdbf44e1/kate/main.cpp#L62

```
sudo kate
[sudo] password for cxf:                     
Executing Kate as root is not possible. To edit files as root use:
SUDO_EDITOR=kate sudoedit <file>
