### ISSUE TITLE
Have Lutris log the user's Lutris game settings (game, runner, system options)

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1037]
Having to go back and forth asking people what settings they have enabled or disabled gets tiring. It would be good to have Lutris log this and would make helping others much easier.

**Comment by romulasry** [comment]
Sounds like a good idea!

**Comment by RobLoach** [comment]
Like a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/#adding-a-contributing-file)?

**Comment by AccountOneOff** [comment]
No, have Lutris log settings with `lutris -d` or something to that effect.
