### ISSUE TITLE
Have Lutris check if Vulkan is present on system

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1038]
Automatically check if vulkan drivers are installed in the system
    or if vulkan even just plain works(edited)
    and if it doesn't, just grey out DXVK option

Per @tannisroot on Discord

**Comment by duhow** [comment]
The `vulkaninfo` command may help - outputs a lot of info + current version.
Other ways would be checking if lib files exist `/usr/lib/x86_64-linux-gnu/libvulkan.so` ?

**Comment by tannisroot** [comment]
vulkaninfo is only available from vulkan-utils, and not having the latter doesn't mean the user won't be able to launch a vulkan application.
Also, for me libvulkan.so is not in /usr/lib/x86_64-linux-gnu/libvulkan.so, but in just /usr/lib

**Comment by RobLoach** [comment]
Would this work?
```
which vulkaninfo
```

**Comment by tannisroot** [comment]
Wouldn't check for 64-bit Vulkan either because vulkaninfo is from vulkan-utils, which is an optional package.

**Comment by BloodyIron** [comment]
So how is this going to impact scripts that call for DXVK then?

**Comment by tannisroot** [comment]
If Lutris won’t find vulkan loader present on the system, the user won’t be able to launch a game with DXVK enabled.

**Comment by BloodyIron** [comment]
@tannisroot okay but I'm trying to point out the UX for clicking on the install script link on the website, to then have it (not work?) because Vulkan isn't available. How do we account for that?

**Comment by tannisroot** [comment]
All installers that I maintain have a link to the How-To:-DXVK page. All others should too.

**Comment by tannisroot** [comment]
And if some don't, the warning with include a link to that page too.
