### ISSUE TITLE
Restore monitor refresh rate

### ISSUE THREAD

**Issue by mtrp12** [lutris/lutris#1039]
My monitor's default refresh rate is 60Hz, but I set it to 72Hz. When game exits, lutris does not restore monitor refresh rate to 72Hz. Is this feature available? If not can it be added?

**Comment by duhow** [comment]
Does it happen with all games? What games are you trying to run? Wine Steam, Linux Steam...?

**Comment by mtrp12** [comment]
@duhow 
Yes, with all games. Wine steam, linux steam and non steam wine games have been tried and faced with this problem. I don't know if this is relevant, the screen resolution is updated even for games whose resolution update settings have been disabled. Also, they are updating for situation when the resolution after game exit is alright and does not need any change. I am using lutris version 0.4.18.1.

**Comment by duhow** [comment]
In `Lutris > System preferences` did you made any changes for Resolution / Xephyr settings?

**Comment by mtrp12** [comment]
I unchecked resolution and gamma options. I don't understand what xephyr is, so i left it as it is.
