### ISSUE TITLE
Wine-ge 3.x > 3.6

### ISSUE THREAD

**Issue by Ilphrin** [lutris/lutris#1041]
Hi,

First thank you all for this awesome project! (That makes me able to play Path Of Exile without having to compile manually wine, which I failed to do until now)

I am using wine-ge 3.6 with DXVK, but I am stuck in the DXVK version because there is some DirectX11 directives supported only from 3.11.

I would like to use wine-ge 3.11 (or even 3.13 the latest) but I can't find where are located the wine packages and scripts for Lutris. Is there any way to make wine-ge 3.11 available in Lutris?

**Comment by duhow** [comment]
[Path of Exile](https://lutris.net/games/path-of-exile/) has an updated installer which uses another Wine version - `esync-3.13`. Try it! :wink:

**Comment by Ilphrin** [comment]
Thanks @duhow ! It this version using Wine-PBA? :o I didn't know about esync until now.
Just tried, it seems to be working fine!
