### ISSUE TITLE
New interface like XMB or Big Picture

### ISSUE THREAD

**Issue by scorninpc** [lutris/lutris#1044]
First thank you for great project

I'm working in some tests with new interfaces like PS3 xmb and steam big picture and I have done some progress

![captura de tela em 2018-08-19 00-00-45](https://user-images.githubusercontent.com/2607849/44304994-f944ba00-a342-11e8-9774-64f6e62f1262.png)

![2018-08-18_23-13](https://user-images.githubusercontent.com/2607849/44304961-70c61980-a342-11e8-9ae1-82f04e0554bf.png)

![2018-08-18_23-14_1](https://user-images.githubusercontent.com/2607849/44304962-77549100-a342-11e8-80df-2e2fa9b7c0a9.png)

![2018-08-18_23-14](https://user-images.githubusercontent.com/2607849/44304963-7ae81800-a342-11e8-9356-71e3d8105d59.png)

![2018-08-18_23-15](https://user-images.githubusercontent.com/2607849/44304964-7de30880-a342-11e8-8bb6-23e8010fcd9e.png)

I work with ciencies, so my job are look better tecnology, methodology for each system and users. So my python is not a good one. I start this work thinking about easy customization and new themes, so I embed a webkit inside python, and port some lists and methods to javascript, where I can render and launch game with HTML and Javascript, who is so disseminated for alot users, not only for programmers. And we can easy work with themes without alot work

Anyway, I'm posting here to know what you guys think, if I can continue the job and do some new, or I'm losing my time

I have forked the project, and preffer not do a pull request on the main to write better code before that

If anyone wanna do a test, can clone my fork. Work with keyboard arrows, and mouse click on game to run. 

**DO NOT INSTALL** that, use the main instructions for run without install

**Comment by duhow** [comment]
#303

**Comment by scorninpc** [comment]
Nice to know @duhow. Alot dependencies and not flexible. So i'll start another project for this, I think's better

Thank you

**Comment by strycore** [comment]
I think it looks neat for a start and I like the idea of using HTML / CSS. 

The other option is using Gtk Scene Kit but that's not readily available as a technology. For the time being, the best option is using a GtkWebkit widget

**Comment by scorninpc** [comment]
Thank you @strycore. But I think the ideia to create a separated project is nice for now. I'll implement joystick methods, and organize the folders for themes, and than people can anything usable to start work

**Comment by duhow** [comment]
Having fullscreen interface with HTML, JS and CSS (Sass) rendering will make it visually better than doing just GTK, and of course there are many things to do:
* Controlling via keyboard and joystick (mapping keyboard keys)
* Responsive (with minimal size?)
* Sounds with GUI movement/actions (also turn off if the user wants)
* Background animations _can be_ with HTML+CSS custom code (waves, sparkle, static, picture/video)
* Try to use libs/frameworks to keep code clean, readable and extensible.

Of course this requires a lot of time and patience.

Also and some important, calling actions _should_ be done via Lutris API o similar, for not coding the same actions twice (in normal / fullscreen).
And I think imo that's why the original issue was marked for a long version.

But anyway it seems you did a good progress so far :slightly_smiling_face:

**Comment by TingPing** [comment]
> The other option is using Gtk Scene Kit but that's not readily available as a technology.

For what its worth Gtk4 is kinda stable and they would like people to use it.

**Comment by strycore** [comment]
>> The other option is using Gtk Scene Kit but that's not readily available as a technology.
> For what its worth Gtk4 is kinda stable and they would like people to use it.

No doubt about that but the systems we target are far from receiving Gtk4, we couldn't ship such a feature as long as we have to support Ubuntu 18.04 or other distro that don't have Gtk4 at the moment  (all of them?). That's unless Flatpak makes it possible to run Gtk4 applications on older distros, of course.

I would see nothing wrong in starting the development of such a feature, with GSK, right now. It's big enough that by the time we're finished with it, Gtk4 will be readily available everywhere.

**Comment by strycore** [comment]
Also, can't we build something based off RetroArch? @RobLoach has a neat plugin already to launch lutris games in retroarch: https://github.com/RobLoach/love-lutris

**Comment by TingPing** [comment]
> No doubt about that but the systems we target are far from receiving Gtk4, we couldn't ship such a feature as long as we have to support Ubuntu 18.04 or other distro that don't have Gtk4 at the moment (all of them?). That's unless Flatpak makes it possible to run Gtk4 applications on older distros, of course.

You already know my opinion on that. =)

**Comment by strycore** [comment]
> You already know my opinion on that. =)

Yes, but we can't drop support for still widely used distros, especially since we don't maintain any of the old branches. I really hope Flatpak works out ok for shipping new Gtk features to older systems.

**Comment by TingPing** [comment]
> Yes, but we can't drop support for still widely used distros, especially since we don't maintain any of the old branches.

If you dropped 14.04 then Flatpak should cover what you need.
