### ISSUE TITLE
[Feature Request] Add BSD Support

### ISSUE THREAD

**Issue by asdedhj** [lutris/lutris#1048]
WineHQ has supported BSD for a while already[1](https://wiki.winehq.org/FreeBSD) and lots Linux compatibility[2](https://www.freebsd.org/doc/handbook/linuxemu.html). I believe that it would help with Lutris's adoption if it worked on both Linux and BSD systems.

**Comment by RobLoach** [comment]
Add ARM to the list of desired architectures too: https://github.com/lutris/lutris/issues/418

**Comment by strycore** [comment]
I don't think I've ever seen any BSD developer show any desire to port the code to their OS.

**Comment by asdedhj** [comment]
@strycore My understanding is that Linux Tar Balls tend to work on BSD as well. The main thing that I believe would help Lutrix is allowing users to search by Linux supported games and/or BSD supported games. Plus adding the home page to say "GNU/Linux and BSD". 

Then Lutrix would have to open up Beta testing for OpenBSD, FreeBSD, NetBSD, and DragonflyBSD. Even if it the client doesn't work BSD users could download the apps from the web.

**Comment by usijkl** [comment]
@strycore To clarify, is Lutris open to adding OpenBSD Support if the client was to be ported? Perhaps if a BSD porting group were to enable to client to work on OpenBSD?

**Comment by strycore** [comment]
I don't think anyone is interested in a BSD version of lutris, it's been almost 10 years, people would have shown up. 
Closing.
I am not interested about BSD based OSes.

**Comment by benrob0329** [comment]
There wasn't interest sooner, so therefore all BSD devs passed you up? Clearly people are interested, otherwise this issue wouldn't have been made.

There are Linux users who have never even heard of Lutris, let alone the majority of the BSD community. At least leave it on a "I'm not going to port it, but PRs are welcome" note.

**Comment by Alexander88207** [comment]
I'm also interested

**Comment by strycore** [comment]
The project is Open Source, it's built in such a way that if people want to make a BSD build of lutris, they can easily. A Github ticket doesn't change any of that, Open Source is not about tickets. I would like to keep the bug tracker for things that are on the roadmap and I am pretty sure that this very ticket won't have an influence over the existence of a potential BSD port.

On a side note, I have given an OSX version a thought, not that I care about OSX at all but I hear that their users have money and they are greater in numbers than Linux users.

**Comment by AccountOneOff** [comment]
You should consider an Android port now that there are Wine builds for it. There's a big market and potential money there as well.
