### ISSUE TITLE
add CONTRIBUTING.rst

### ISSUE THREAD

**Issue by keturn** [lutris/lutris#1053]
It's taking me a few tries to figure out how to get a development build up and running.

I created a new virtual environment out of habit, but maybe I shouldn't have, if it's intended to run against the system Python?

It's also taking some trial-and-error to install the dependencies for all the Gtk+ stuff, though I suspect there's some debhelper command I could point at the control file and it would install all the build-deps for me?

This is the sort of thing we could write up in a CONTRIBUTING file to help onboard developers.

**Comment by AlexanderRavenheart** [comment]
It sure took a bit of trial and error to get all the right packages installed.
Always a good idea to run projects in virtual environments because it makes it easier to get the proper versions of packages installed and to not mess up everything else.

**Comment by strycore** [comment]
Added relevant information in CONTRIBUTING.md
