### ISSUE TITLE
Integrate Lutris with SteamPlay (Steam)

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#1055]
https://www.phoronix.com/scan.php?page=news_item&px=Valve-Steam-Play-Proton-Linux

It would be nice to be able to use/integrate Lutris from the command line, so it could be used as a compatibility tool in steam:

![](https://i.imgur.com/wyB8kQw.png)

**Comment by strycore** [comment]
As far as this ticket is concerned, this is fixed, Proton is now available in the Wine version.

**Comment by romulasry** [comment]
Can we have an actual runner?
