### ISSUE TITLE
Integrate Proton as runner (alternative to Steam?)

### ISSUE THREAD

**Issue by tcarrio** [lutris/lutris#1056]
https://www.phoronix.com/scan.php?page=news_item&px=Valve-Steam-Play-Proton-Linux

The Proton project provides a fork of the Wine project and integration of several other libraries as a bundle. 

It might be worthing looking into this further in regards to how we could utilize this as an alternative Wine runner. Since it does include its own fork of Wine among other projects that Valve is working on, it could provide more functionality for gaming compatibility than upstream. Figured I would throw the idea out there at least :+1:

**Comment by duhow** [comment]
#1055 also mentions Proton.

**Comment by tcarrio** [comment]
They both seem like good use cases, but it feels like utilizing a Valve supported fork of several libraries that Lutris handles manually could be an easy way to setup a well-supported Wine-based environment. It may also be particularly easy to use since Proton is developed with Python as well, although their codebase needs to update to 3

**Comment by tcarrio** [comment]
To clarify the purpose of this versus #1055:

#1056 allows Lutris to reap the benefits of Valve's development of a Wine fork. This would not have any relation to Steam, but rather provide an alternative to the current Wine runner in Lutris. Since they are maintaining custom patches to their codebase that the Wine team may not be receiving/accepting from Valve, this option would allow users the option to use whichever works best for a particular game. Since Valve has obviously committed to this plan, this could guarantee users sane defaults for a plethora of games in their library, while targeting any Windows program (on Steam or not, the Proton compatibility tool could be used).

#1055 allows Lutris to be used as a runner within Steam, effectively. This could be particularly interesting in the case that users want to work with a refined GUI that handles configuration of multiple Wine prefixes and their configurations, libraries, and more. Lutris would have to implement a CLI usage that conforms to the standard Proton has set, but would allow management of Wine configurations in the same manner we have handled with Lutris all the while. This could allow Steam users to customize the Wine prefix their games would launch under significantly more, and may alleviate the need for an extra Steam installation within the prefix, something which has been required historically for Steam games through Wine.

These are vastly different cases but nonetheless center around Proton.

**Comment by Dade88** [comment]
Probably most people already knows, but found this https://www.reddit.com/r/wine_gaming/comments/99fr3y/will_lutris_get_a_proton_wine_runner/

Testing it soon :)

**Comment by strycore** [comment]
Proton is now detected in the Wine versions.

**Comment by jarrard** [comment]
Unfortunately custom proton versions are not detected after initial install first run phase.

**Comment by AndyHoang** [comment]
> Unfortunately custom proton versions are not detected after initial install first run phase.

I tried remove/reinstall it, but I didn't regconize, anyway to "purge" and force it recognize?
