### ISSUE TITLE
Allow deleting Runners from the UI

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#1057]
I need to because of a bug in the version of steam I am using.

**Comment by duhow** [comment]
Menu Lutris > Manage runners > Bottom left, `Open Runners Folder`
Delete `winesteam` folder.

**Comment by romulasry** [comment]
The file or folder /home/ryan/'/home/ryan/.local/share/lutris/runners' does not exist.

**Comment by RobLoach** [comment]
Would be nice to have a "Delete" or "Remove" button directly in the UI.

![delete](https://user-images.githubusercontent.com/25086/44474049-b2371d00-a5ff-11e8-8371-6ca8394ec892.png)

**Comment by romulasry** [comment]
Great idea Rob!
