### ISSUE TITLE
Add copy command as an alias for merge

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1061]
There's no way to copy a single downloaded file to two directories currently. So I end up having to do this:

```
- move:
    dst: $GAMEDIR/Tools/Windows/x64/discord-rpc.dll
    src: $rpc
- execute:
    command: cp "$GAMEDIR/Tools/Windows/x64/discord-rpc.dll" "$GAMEDIR/Tools/Windows/x86"

**Comment by Medath** [comment]
As far as I know the [merge](https://github.com/lutris/lutris/blob/master/docs/installers.rst#copying-and-merging-directories) command copies files.

**Comment by AccountOneOff** [comment]
Oh, I thought merge was like `move` but without having to worry about file names. Good to know.

**Comment by Medath** [comment]
Should we really make an alias for that? Having two commands do the same thing might cause some confusion.

**Comment by strycore** [comment]
it just need to be documented, it's a pretty common thing to do

**Comment by duhow** [comment]
https://github.com/lutris/lutris/blob/master/docs/installers.rst#copying-and-merging-directories ?
