### ISSUE TITLE
check driver versions

### ISSUE THREAD

**Issue by keturn** [lutris/lutris#1062]
I put a lot of time into trying to debug problems that ended up being due to not using recent enough nvidia drivers.

(I did make sure I was using the nvidia drivers, and my distro is less than six months old, I assumed that should be good enough for a game from 2013!)

It would be great if we could have runners define prerequisites and check to see if the system meets them. The case I ran into was specifically wine+DXVK and NVidia drivers, but maybe there are other runners that would want to check too.

The ideal user experience would probably to have lutris manage the drivers, but I think that is Out Of Scope.

Instead, I think it would be sufficient for it to show a warning next to the DXVK checkbox and/or a notice during installation time that said "your drivers are not compatible; this probably won't work, see <link> for details."

**Comment by tannisroot** [comment]
`modinfo nvidia_current | grep -e ^version: | cut -d' ' -f2-  | tr -d ' ' ` doesn't work with `nvidia_current` but does work with `nvidia`

**Comment by strycore** [comment]
Driver information is now displayed on startup, there will be some checks added to require games to have a particular version but that's out of scope for this ticket
