### ISSUE TITLE
[Suggestion] Deploy Lutris via AppImages

### ISSUE THREAD

**Issue by asdedhj** [lutris/lutris#1066]
Feature: Enable users to install and launch Lutris via an [AppImage](https://appimage.org/).

**Comment by probonopd** [comment]
Why was this closed? I second this. Please re-open.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Why was this closed? People on Reddit are asking, too:
https://www.reddit.com/r/linux_gaming/comments/d1amb5/gamehub_and_luxtorpeda_developers_are_discussing/

**Comment by MasterionX** [comment]
> Why was this closed? People on Reddit are asking, too:
> [reddit.com/r/linux_gaming/comments/d1amb5/gamehub_and_luxtorpeda_developers_are_discussing](https://www.reddit.com/r/linux_gaming/comments/d1amb5/gamehub_and_luxtorpeda_developers_are_discussing/)

Compare the overall interest for AppImage vs Flatpak/Snap, and you will see.

**Comment by probonopd** [comment]
Think [twice](https://trends.google.com/trends/explore?cat=32&date=today%2012-m,today%2012-m,today%2012-m&geo=,,&q=%2Fm%2F0814ps,%2Fg%2F11cky713kp,%2Fg%2F11bwn4n_5b&hl=en-US&tz=-60) @MasterionX
