### ISSUE TITLE
pyGObject and Slackware 14.1

### ISSUE THREAD

**Issue by Xylemon** [lutris/lutris#107]
Hello, I'm on Slackware 14.1 64-bit and I can't launch Lutris due to a common error that is spat out when pyGObject isn't installed:

Traceback (most recent call last):
  File "/usr/bin/lutris", line 25, in <module>
    from gi.repository import Gtk, GObject
ImportError: No module named gi.repository

However I do have pyGObject installed, yet this still happens. Any ideas?

**Comment by Ralvke** [comment]
In ArchLinux i will get same error (ImportError: No module named gi.repository)
But gobject installed.

```
17 extra/pygobject-devel 3.16.2-1 [installed]
    Development files for the pygobject bindings

18 extra/pygobject2-devel 2.28.6-11 [installed]
    Development files for the pygobject bindings

19 extra/python-gobject 3.16.2-1 [installed]
    Python 3 bindings for GObject

20 extra/python-gobject2 2.28.6-11 [installed]
    Python 3 bindings for GObject2

21 extra/python2-gobject 3.16.2-1 [installed]
    Python 2 bindings for GObject

22 extra/python2-gobject2 2.28.6-11 [installed]
    Python 2 bindings for GObject2
```

**Comment by TingPing** [comment]
@Ralvke python2-gobject should be all you need, try out the package: https://aur.archlinux.org/packages/lutris/

**Comment by Ralvke** [comment]
@TingPing I installed lutris with the repository
