### ISSUE TITLE
object has no attribute 'appmanifest_data'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1072]
Got a new game on steam and installed it, and got this on the terminal: 

```
Traceback (most recent call last):
  File "/src/lutris/lutris/util/steam.py", line 164, in _on_directory_changed
    self.callback(event_type, path)
  File "/src/lutris/lutris/gui/lutriswindow.py", line 264, in on_steam_game_changed
    if not appmanifest.is_installed():
  File "/src/lutris/lutris/services/steam.py", line 87, in is_installed
    return 'Fully Installed' in self.states
  File "/src/lutris/lutris/services/steam.py", line 79, in states
    state_flags = self.app_state.get('StateFlags', 0)
  File "/src/lutris/lutris/services/steam.py", line 54, in app_state
    return self.appmanifest_data.get('AppState') or {}
AttributeError: 'AppManifest' object has no attribute 'appmanifest_data'
```

**Comment by duhow** [comment]
How did you install the game, directly through Steam and then Lutris synced and it appeared, or did you use any Lutris script installer?
Does it happen with another game doing the same install steps?

**Comment by telanus** [comment]
> How did you install the game, directly through Steam and then Lutris synced and it appeared, or did you use any Lutris script installer?

I got the game code from humble, entered the code into steam and at the end when steam asked to install the game I said yes (as it was small enough to download while I enter the other codes I got).

normally I enter all the codes first before then proceeding to download via steam,so I never seen this happen, maybe because I wait between entering the code and downloading the game

**Comment by duhow** [comment]
Ok, so you installed the game directly via Steam and then it was added to Lutris.
(It doesn't matter if you redeem the steam code or not for installing the game, that process keeps the same way)

> Does it happen with another game doing the same install steps?

Also try `Lutris > Synchronize library` option.

**Comment by telanus** [comment]
> Ok, so you installed the game directly via Steam and then it was added to Lutris.

Installed a new game in lutris, one that doesn't have an entry in my lutris install (and thus lutris' library) and think that lutris "freaked" out when not only found a "new" game when it checked steam, but that it's already installed

**Comment by duhow** [comment]
![image](https://user-images.githubusercontent.com/1145001/44677091-63411b80-aa35-11e8-808e-7380f2376a69.png)

(Can you attach game config/s of that game, located in `~/.config/lutris/games` ?)

**Comment by telanus** [comment]
[deep-dungeons-of-doom-1535280095.zip](https://github.com/lutris/lutris/files/2325331/deep-dungeons-of-doom-1535280095.zip)

**Comment by duhow** [comment]
You have setup this game as **Steam**, but it is **Wine Steam**.
This game isn't supported on Linux platform.

**Comment by basxto** [comment]
* Install that game with native steam.
* Lutris doesn’t import it.
* Add manually. (steam runner + 325090)
* Run game.
* Get same traceback on console. (6 times)

But that only happened the first time, I run it.
After closing and opening lutris again, I have the game now listed twice.
