### ISSUE TITLE
[Suggestion] Add a favorite games filter

### ISSUE THREAD

**Issue by Christophe31** [lutris/lutris#1075]
Hi, thx for lutris, I love it (it gave me my dose of Magic the gathering without reboot).

As steam have quickly tons of games, I often search the logo in games when on a given month my current games or favorite games are a limited subset of my installed games (all runners wide).

A home page with starred games would be a nice quality of life improvement feature.

**Comment by tannisroot** [comment]
This is sort of implemented by https://github.com/lutris/lutris/pull/1452

**Comment by tannisroot** [comment]
The fuck? This is a valid request and there is a PR for this and everything: https://github.com/lutris/lutris/pull/1452
