### ISSUE TITLE
Windows command line in Lutris

### ISSUE THREAD

**Issue by kgudalov** [lutris/lutris#1078]
Can I add the ability to run in the prefix of the game windows shell, as in PlayOnLinux.

**Comment by duhow** [comment]
![image](https://user-images.githubusercontent.com/1145001/44977876-91f54f80-af69-11e8-8632-a29a62cd87f2.png)

**Comment by monyarm** [comment]
if you want to run a game in the windows cmd you can use wine's cmd.exe
