### ISSUE TITLE
Lutris Installation guide is incorrect

### ISSUE THREAD

**Issue by swawif** [lutris/lutris#1081]
I was following the guide posted on how to install lutris for ubuntu in the https://lutris.net/downloads/
at the beginning it told me to add the repo by doing
1. `ver=$(lsb_release -sr); if [ $ver != "18.04" -a $ver != "17.10" -a $ver != "17.04" -a $ver != "16.04" ]; then ver=18.04; fi //get ubuntu version`
2. `echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list //get repo`
3. `wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add - //add repo`

then the usual `sudo apt-get update && install lutris`
however this always return `E: Unable to locate package lutris`

after that, I followed the guide posted [here instead](https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris) and got lutris working
I guess this is due to a typo on the second command where it should be using
`sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:strycore.list"`

cheers

**Comment by duhow** [comment]
Not a typo, just that `$ver` maybe didn't replace with your current version.
In my case, using Debian 9 returns `18.04` (fallback).
Check the content of `/etc/apt/sources.list.d/lutris.list` to be sure.

**Comment by swawif** [comment]
@duhow 
The `$ver` did work correctly and it did write to `/etc/apt/sources.list.d/lutris.list` the command `deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/ ./` correctly as well.

but after that, it still  won't add the repo. everytime i tried to do `sudo apt-get update`, it always return with 
`E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ Release' does not have a Release file.`

I don't really know what's the problem is here as I'm not that literate in computer. but seems like the guide on lutris.net/download is incorrect.

**Comment by duhow** [comment]
Are you having any issue when doing `apt update`, showing something like "certificate problem with the repo"?

**Comment by strycore** [comment]
this will eventually going to be changed, the current solution is working well enough for basically anybody
