### ISSUE TITLE
Change "Import Games" to something more clear (like "Configure library importing")

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1082]
I personally feel like the current name for that menu is confusing, misleading and does't represent its actual purpose. I personally think something like "Configure library importing" will describe the menu much better, but if you disagree, any suggestions are appreciated.

**Comment by RobLoach** [comment]
"Runner synchronization"?

**Comment by tannisroot** [comment]
The menu is for configuring syncing of libraries from Steam and other stuff like that, runners are not really relevant here.
