### ISSUE TITLE
Better control over fetching of banners.

### ISSUE THREAD

**Issue by RobertZenz** [lutris/lutris#1088]
Currently banners are being fetched from *somewhere* whenever the Lutris is started. It would be nice if we would be able to control that behavior, for example if we only use Lutris for offline management (and fancier starter) for games.

For example the ability to disable any automatic fetching and instead having a button by the banner option to fetch it now from the server.

**Comment by tannisroot** [comment]
This is sort of like https://github.com/lutris/lutris/issues/1146
I am going to close this as a duplicate I suppose, even though this issue is older.

**Comment by atahanacar** [comment]
I don't understand how this is "sort of like #1146". This issue is still relevant today so I think this issue should be re-opened.

I will look into adding an option to stop auto-fetch once I have enough free time.

**Comment by strycore** [comment]
> I will look into adding an option to stop auto-fetch once I have enough free time.

Maybe ask us if we would accept merging such a feature before spending time on it.
