### ISSUE TITLE
xrandr is now required to use Lutris

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1091]
Fails to launch since the 0.4.19:
`Traceback (most recent call last):   File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 645, in on_add_game_button_clicked     callback=lambda: self.add_game_to_view(dialog.game.id)   File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 446, in __init__     self.build_tabs('game')   File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 40, in build_tabs     self._build_system_tab(config_level)   File "/usr/lib/python3.7/site-packages/lutris/gui/config_dialogs.py", line 246, in _build_system_tab     self.system_box = SystemBox(self.lutris_config)   File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 587, in __init__     self.generate_widgets('system')   File "/usr/lib/python3.7/site-packages/lutris/gui/config_boxes.py", line 67, in generate_widgets     option['condition'] = option['condition']()   File "/usr/lib/python3.7/site-packages/lutris/sysoptions.py", line 45, in get_dri_prime     return len(display.get_providers()) > 1   File "/usr/lib/python3.7/site-packages/lutris/util/display.py", line 176, in get_providers     version = get_xrandr_version()   File "/usr/lib/python3.7/site-packages/lutris/util/display.py", line 162, in get_xrandr_version     stdout=subprocess.PIPE).communicate()[0].decode()   File "/usr/lib/python3.7/subprocess.py", line 756, in __init__     restore_signals, start_new_session)   File "/usr/lib/python3.7/subprocess.py", line 1499, in _execute_child     raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'xrandr': 'xrandr'`

**Comment by Zebouski** [comment]
getting the same, had to install Arch package `xorg-xrandr` to get game launching and preferences page working for now.

**Comment by DerMauch** [comment]
Can confirm this issue. There should be a dependency added to the lutris Arch package or at the very least documented somewhere.

**Comment by FFY00** [comment]
Fixed in `lutris 0.4.20-2`.

**Comment by Medath** [comment]
Can this be closed?

**Comment by FFY00** [comment]
Yes, it was fixed.
