### ISSUE TITLE
Installation process doesnt work

### ISSUE THREAD

**Issue by edoantonioco** [lutris/lutris#1092]
So on Manjaro, normal wine, I 
downloaded dxvk-master, 
openterminal here and run "export WINEPREFIX=/home/<USER>/.wine/drive_c/" (with <USER> my username.
then "winetricks --force setup_dxvk.verb" on that same terminal. And this says

> /usr/bin/winetricks: línea 20281: ./setup_dxvk.verb: No existe el fichero o el directorio

so setup_dxvk.verb isnt there, so I cant install this.

**Comment by tannisroot** [comment]
Lutris has built-in functionality for enabling DXVK. 
I don't understand why you are doing this.

**Comment by tannisroot** [comment]
![peek 2018-09-06 19-32](https://user-images.githubusercontent.com/10602045/45171658-a0629600-b20b-11e8-8a06-217a85f57f41.gif)

**Comment by edoantonioco** [comment]
Thanks, will do that.

**Comment by tannisroot** [comment]
lovely ❤️
