### ISSUE TITLE
FreeType issue with wine after update to 0.4.19 and above

### ISSUE THREAD

**Issue by VortexAcherontic** [lutris/lutris#1096]
Hi I'm not a 100% sure if this error is caused by lutris or by my distro but I trried a lot and think this is caused by lutris somehow.

Here is the problem:
If I launch wine via lutris I get this error message:
`Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
`

I tried the following to check if this problem persists even with my system side installed wine (3.7)

env WINEPREFIX=~/.wine32 WINEARCH=win32 notepad
and
env WINEPREFIX=~/.wine64 WINEARCH=win64 notepad

To make wine create completely fresh and new prefixes and launches notepad.
No font issues here.

Also I tried with a fresh new lutris config folder (~/.local/share/lutris) with no success.
After this I wasn't even able to run any Lutris installer every installer stopped at "Installing game data".

Further on I tried different Lutris installers with different wine versions all causing the same problem.
Winesteam has no fonts most installers quit with errors because of missing fonts eg.
With the previous Lutris version 0.4.18 I had no such issues at all whether with 32bit wine nor with 64bit wine.

My distro is:
openSUSE Leap 15.0
Kernel: 4.12.14-lp150.12.16-default

Also I checked if I have also 32bit libraries installed such as:
libfreetype6
libfreetype6-32bit
libXft2
libXft-32bit

If you need any additional infos please let me know.

**Comment by Veelhiem** [comment]
I'm also getting this issue, but I am on openSUSE Tumbleweed.

**Comment by Dawiddym** [comment]
Dunno if I should write about it here, but after the last battle.net client update i can't see the fonts in the battle.net client which is mildly annoying. I seem to have all the dependencies. I'm running Lutris on Arch. Any suggestions?
![screenshot_2018-09-12_20-49-24](https://user-images.githubusercontent.com/37812576/45446649-bec60700-b6cd-11e8-9bcc-8a4a445c2109.png)

**Comment by tannisroot** [comment]
@Dawiddym try installing Arial verb from Winetricks

**Comment by VortexAcherontic** [comment]
I can not launch winetricks in any prefix trough lutris.
But if I run `env WINEPREFIX=<path-to-lutris.winesteam-game-prefix> WINEARCH=win64 winetricks` winetricks is starting properly in that prefix.

Even if I run notepad in that prefix the same way there are no messages about missing FreeType libraries.

So it looks like the font issue only appears if lutris is launching any wine application.

**Comment by Dawiddym** [comment]
After the recent update I can launch winetricks through Lutris. Also - after using the new install script from the Lutris website I no longer have the font issues.
Thanks to everyone who helped :)

**Comment by VortexAcherontic** [comment]
Issue still persist on my system.
Clean lutris config folder and still no fonts and the same message in the terminal. =/
I'm not sure if I miss something but maybe anybody of you can help me.
If I search for freetype2 as rpm for my system I find some repos but after running One Click Install or just adding the wanted repo I still can not find any freetype2 package in YaST.

OS: openSUSE Leap 15.0 (Kernel: 4.12.14-lp150.12.16-default)

**Comment by VortexAcherontic** [comment]
I also asked at the official opensuse forum to receive any help, might be something with the libfreetype6-32bit rather than lutris. Not quite sure read the thread here: https://forums.opensuse.org/showthread.php/533391-Lutris-Wine-and-Freetype2

**Comment by kaosstar** [comment]
I'm having the same problem. I'm also on OpenSuse Leap 15.

**Comment by tannisroot** [comment]
I have a feeling that this is caused by the fact that Lutris wine is built under Ubuntu 16.04, which has a quite old version of freetype that may be incompatible with newer freetype on modern systems.

**Comment by Dawiddym** [comment]
I don't think new version of Lutris fixed the problem. I have the same version as you do and the problem persists unless I enable DXVK.
![screenshot_20181105_164302](https://user-images.githubusercontent.com/37812576/48009097-4010a780-e11b-11e8-8bee-5c1078ed03d8.png)

**Comment by VortexAcherontic** [comment]
No, DXVK didn't fixed the issue for me earlier.
I tried this for an already installed game (I had first discovered this issue with an game using DXVK and it had DXVK enabled) and also for the winesteam runner where also is an DXVK option.
But both didn't fixed it for me back then.

**Comment by Dawiddym** [comment]
Yeah, I agree now. Being curious and all I reinstalled Hearthstone yesterday and everything started working again. Admittedly I did it somewhat differently (different DXVK package) and I increased my limits in Systemd for esync, but I don't think these actions helped in anyway. Yet it works now ¯\_(ツ)_/¯

**Comment by VortexAcherontic** [comment]
Hm, today I tested Lutris (Version 0.4.23) on my Notebook.

OS: openSUSE Leap 15.0 (4.12.14-lp150.12.25-default)
CPU: Intel i5-3230M
GPU: Intel HD 4000 and GT 730M (Bumblebee installed with NVidia driver: 410.73)
RAM: 8 GB

And got all issues again, even with a clean Lutris config folder.
Battle.Net dose not have any fonts (Same message in terminal as posted several times here)
And winesteam games do not even install.

But I'm not sure if this is caused with the latest lutris updates or the software/hardware configuration on my Notebook.
Further on I can currently not test it on my main rig to confirm if it is broken again there.

I tested Lutris with and with out optimus/primus with no difference.
(Optimus/Primus is setup correctly and fully working).

Need to check later on my main PC

**Comment by VortexAcherontic** [comment]
Nope, everything seems to be broken again.
Fresh new Lutris config folder:

- can not install new winesteam games (how ever, thise who was installed got fonts and where working)
- On battle.net setup all fonts are missing and my desktop sometimes freezes during the installation so that I was supposed to recover my session form another terminal session and htop by killing the Battle.net installer

**Comment by VortexAcherontic** [comment]
I tested something else, while I was investigating another issue with lutris if I ran lutris wines manually through the terminal like:

```
export WINEPREFIX="/home/<user>/.local/share/lutris/runners/winesteam/prefix64/"                                                                
export WINEPATH="/home/<user>/.local/share/lutris/runners/wine/tkg-3.19-x86_64/bin/wine" 
cd "/home/<user>/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/"     
wine Steam.exe    
```

There are no complains about any font issues nor missing TrueType Fontns 2.0.5

**Comment by strycore** [comment]
I have set the "prefer system libs" to false as default as it was causing a whole bunch of issues across distros. With that behavior I was able to install Battle.net on Leap 15 without any issue

**Comment by VortexAcherontic** [comment]
@strycore looking good, just installed Heroes of The Storm and of course Battle net, no TrueType messages in the terminal and fonts in the Battle.Net client (y) Thanks a lot!
