### ISSUE TITLE
Can't download runners and game

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#110]
**Edit:** If you don't want to read the whole discussion, the solution to this issue was to install the ```gvfs-backends``` and ```glib-networking``` packages (names may differ depending on your distro). Upstream and downstream packages should have been updated with the missing dependencies as of version 0.3.6.2.

Hi there,

I packaged Lutris for Mageia 5, but now I'm making sure it's working properly before I push it to the mirrors. I've noticed that I can't download anything using Lutris, neither runners on lutris.net or e.g. desura.com, nor games.

The debug output is not particularly useful, for example here when trying to install desura:
```
DEBUG    2014-09-22 20:51:45,518 [desura]:Installing desura
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:537: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "title" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
/usr/lib/python2.7/site-packages/lutris/gui/widgets.py:395: PyGTKDeprecationWarning: Stock items are deprecated. Please use: Gtk.Button.new_with_mnemonic(label)
  self.cancel_button = Gtk.Button(stock=Gtk.STOCK_CANCEL)
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:1390: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  Gtk.Button.__init__(self, **new_kwargs)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
DEBUG    2014-09-22 20:51:45,533 [downloader]:Mounting remote volume
```

Here are the versions of the python modules I'm using Lutris with:
- Python 2.7.8
- Python-GI (GObjects3) 3.13.92
- PyXDG 0.25
- PyYAML 3.10

**Comment by Qazerowl** [comment]
I am experiancing this bug again. I have gvfs installed, but all downloads of any kind never start.

**Comment by strycore** [comment]
The problem seems to be that even with the dependencies installed, gvfs has to be launched by dbus. Display managers such as GDM will do this by themselves but startx or other display mangers won't
There is more info there: http://superuser.com/questions/228261/how-to-properly-start-gvfs-without-gnome

At this point, there's nothing much we can do in Lutris itself but detect that gvfs hasn't been started and display a warning message with the relevant info.

**Comment by orbea** [comment]
I had this issue in slackware-current and use a minimal tiling wm (spectrwm) with just startx.  I was able to fix it by adding these two lines to my ~/.xinitrc

eval `dbus-launch --sh-syntax --exit-with-session`
/usr/libexec/gvfsd &

**Comment by Xodetaetl** [comment]
Downloader rewritten without the gvfs / D-bus / Glib or whatever dependencies.

**Comment by akien-mga** [comment]
Nice!

**Comment by strycore** [comment]
it's nice that this is fixed but now we've lost support for FTP, SFTP, Samba shares, local drives and any other protocol gfvs can interact with. Not a big issue now but I was planning to use that for the game archives and game saves repositories. The deleted code will remain useful at some point in the future, it just need to be extracted from its current location and kept somewhere safe.

**Comment by Xodetaetl** [comment]
Ah, well the code can be found by browsing the file history and looking for the commit with "rewrite", easy enough.

**Comment by strycore** [comment]
I should extract this code and put it in my PyGObject demos project, I still remember the hours spent pulling my hair and trying to get it right :p

**Comment by Xodetaetl** [comment]
> the hours spent pulling my hair

Oh that's why it looks a bit hairy ! :D
