### ISSUE TITLE
Error installing Overwatch

### ISSUE THREAD

**Issue by CorruptComputer** [lutris/lutris#1103]
I followed [the guide](https://github.com/lutris/lutris/wiki/Game:-Overwatch), and I cannot install the game. Running from the official script:

![image](https://user-images.githubusercontent.com/5573038/45332225-05342e00-b535-11e8-9c4b-7bbd6f1c2250.png)

**Comment by tannisroot** [comment]
Please provide more information.
What is your system (distro, version).
Do you have wine from WineHQ installed?

**Comment by CorruptComputer** [comment]
Arch Linux, Lutris 4.19, Wine-Staging 3.15

Sorry, I should have included those.

**Comment by CorruptComputer** [comment]
I looked at the support article here: https://us.battle.net/support/en/article/161075

And this seems to be related to requiring a certificate installed, however I haven't found a way to install it to Wine.

**Comment by tannisroot** [comment]
Do you have `wine-staging` package installed on your system?

**Comment by tannisroot** [comment]
@CorruptComputer did this help you with your issue?

**Comment by CorruptComputer** [comment]
> @CorruptComputer did this help you with your issue?

Honestly haven't had a chance to check, I got frustrated and just went back to using Windows on my gaming PC.

**Comment by tannisroot** [comment]
Oh, ok. Do you think you can close it now then?

**Comment by CorruptComputer** [comment]
This might still be an issue for someone else, but if that's the case they can always open a new one. For me at least, no longer an issue.
