### ISSUE TITLE
[Feature] ZDoom command options

### ISSUE THREAD

**Issue by bebop350** [lutris/lutris#1104]
I'm on Lutris v0.4.18.1 and notice it seems Lutris can't accommodate command options for ZDoom like specifying the save or config directory. 

For example I run this to launch Brutal Doom:
gzdoom -iwad doom -file bd21testApr25.pk3 DoomMetalVol4.wad -config /Gaming/Linux/Installers/Doom/wads/BrutalDoom/brutaldoom.ini -savedir /Gaming/Linux/Installers/Doom/wads/BrutalDoom

One could use .sh files for the games and add as Linux native titles, but it's not ideal.

Something to consider. Thank you.

**Comment by RobLoach** [comment]
Great idea... The needed changes would go over at:
https://github.com/lutris/lutris/blob/master/lutris/runners/zdoom.py

**Comment by SenileAnimal** [comment]
My apologizes if I gave the wrong impression or tagged this inappropriately, I have only a (very) basic familiarity with Python (and code in general) and Github. In retrospect a [Suggestion] tag would be more fitting?

Regardless, I'll see if it's feasible for me to do. Maybe the args section from the Linux runner can be used.

**Comment by RobLoach** [comment]
No worries! Always looking to improve it, just trying to encourage you to get your hands dirty :wink: 

If you copy some of the options, you'll see how the Lutris Runner API works. You would...

1. You'd copy an options like this:
https://github.com/lutris/lutris/blob/master/lutris/runners/zdoom.py#L46-L51

2. Add it to the command later on:
https://github.com/lutris/lutris/blob/master/lutris/runners/zdoom.py#L104-L107

**Comment by SenileAnimal** [comment]
Thank you.

I'd like to try to add save and config fields where the user browses to the desired directories, plus an arguments field. If I can't manage it, just an arguments field.

I guess the thing to do is get Lutris updated then see about forking zdoom.py.

**Comment by bebop350** [comment]
Resolved with 1113 merge into master
