### ISSUE TITLE
DXVK versions not updating when dxvk directory is missing

### ISSUE THREAD

**Issue by Medath** [lutris/lutris#1106]
When `~/.local/share/lutris/runtime/dxvk/` is not present (because a user never used dxvk before), Lutris fails to create `dxvk_versions.json` because the parent directory does not exist, which leads to Lutris showing the (outdated) fallback DXVK versions. A workaround is to create the missing directory manually and to restart Lutris.

![Missing DXVK versions](https://user-images.githubusercontent.com/40150792/45500181-5c790f00-b77e-11e8-9f09-2cbf351ae5eb.png)

**Comment by elovin** [comment]
1107 does not fix the missing directory, Lutris should create this directory during installation.

**Comment by Medath** [comment]
No, #1107 does not fix this. It just fixed a typo.
I personally think that creating dxvk_versions.json in the the runtime directory rather than the dxvk directory would be easier.

**Comment by tannisroot** [comment]
can you reopen this? it was not solved by that PR

**Comment by Tom-Todd** [comment]
Original fix assumed that lutris and lutris/runtime in local were present.
Changed call time of dxvk version check to ensure lutris has created the folders.
Call to get dxvk versions was occuring prior to application init function.
