### ISSUE TITLE
Sync does not work

### ISSUE THREAD

**Issue by notklaatu** [lutris/lutris#1108]
When signed into lutris.net, I do this:

1. find a game that I own
2. click on the **Add to my library** button

In the desktop client, I do this:
1. Go to File > Synchronize Library

The result:
No games are added to my client.

Expected:
Games that I added to my library on lutris.net should appear in desktop client when synchronized.

Systems tested:
Slackware 14.2 running Lutris 0.4.19
Fedora 27 running Lutris 0.4.19

**Comment by strycore** [comment]
Probably related to the cloudflare migration, should be solved now.
