### ISSUE TITLE
XBMC/Kodi Lutris Addon

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#111]
An addon for [XBMC/Kodi](http://xbmc.org/) to allow you to browse and launch games installed via Lutris directly from XBMC. Would be a new user interface for Lutris.

**Comment by RobLoach** [comment]
Got the initial addon working:
https://github.com/RobLoach/script.lutris

**Comment by ProfessorKaos64** [comment]
@RobLoach , this will rock when complete. If this then works instead Kodi for SteamOS, even more great :). Good job.

**Comment by RobLoach** [comment]
This has been working great! Been using it off and on to launch games from Kodi. Before I close this issue, is there a nice Integrations list in the wiki where I could stick a link this?

**Comment by ProfessorKaos64** [comment]
@RobLoach , have you considered having this included in something like SuperRepo?

**Comment by RobLoach** [comment]
> @RobLoach , have you considered having this included in something like SuperRepo?

Apparently I did!
https://superrepo.org/kodi/addon/script.lutris/
