### ISSUE TITLE
[Feature Request] Game Config Versioning

### ISSUE THREAD

**Issue by isugimpy** [lutris/lutris#1116]
It'd be extremely helpful to be able to have basic change tracking for Lutris configs.  This would allow users to modify their config themselves, and be able to quickly revert to a known working config, without having to write down all of the previous values of fields and hand-restore them.  An alternative which might be simpler to implement is to allow copying of a given game's configs to a new instance of it so you could do your testing on that one and still retain the working copy.

**Comment by isugimpy** [comment]
Not intended at all to be rude, but is this being closed because the work is being deemed not worth doing, or for some other reason?  I ask because I was thinking about starting to work on it myself and offering up the PR, but if it'll be rejected I don't want to waste the time.

**Comment by strycore** [comment]
I'm closing this because I don't have the time or resources to work on this but I'll gladly accept any PR that is valuable to the project!

**Comment by isugimpy** [comment]
Awesome.  Much appreciated on the followup!  I'll see what I can throw together then!
