### ISSUE TITLE
Installation of Battle.net fails

### ISSUE THREAD

**Issue by KleinMuffin** [lutris/lutris#1120]
Hi,

Unfortunately, I'm experiencing some issues with the installation of Battle.net.
I'm using Ubuntu 18.04, Lutris 0.4.19 and wine 3.16 (staging).

It seems like some packages are missing when Battle.net tries to install. I think the download of Battle.net won't finish correctly, so the installation fails. Sometimes the download also won't even start, so the Program Files (x86) directory won't include Battle.net but Lutris says that the installation was successful. 

Here you find the Lutris log: https://paste.ubuntu.com/p/wJbDYQtvYG/
https://imgur.com/NeYvjaQ

**Comment by Sethox** [comment]
Have you tried to install from a clean wineprefix?
It does not seem to be related to the dependencies to what Lutris mention in their wiki.

I usually get this problem when Battle.net's Agent.exe gets an update (which is often). I managed to reinstall battle.net app normally (uninstalling battle.net with the Wine uninstaller) but did not work for my brothers computer so he reinstalled the whole wineprefix (removing it all and resetting it up with the runner/installer).

**Comment by AccountOneOff** [comment]
Two errors:

```
1. 004a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

2. X Error of failed request:  BadValue (integer parameter out of range for operation)
   Major opcode of failed request:  154 (GLX)
   Minor opcode of failed request:  3 (X_GLXCreateContext)
   Value in failed request:  0x0
   Serial number of failed request:  169
   Current serial number in output stream:  170
```
1. [Install Wine-Staging](https://github.com/lutris/lutris/wiki/Wine)
```
sudo dpkg --add-architecture i386
wget -nc https://dl.winehq.org/wine-builds/Release.key
sudo apt-key add Release.key
sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
sudo apt-get update
sudo apt-get install --install-recommends winehq-staging
```
2. This a driver issue. Was this after a driver update? What GPU/driver do you have?

**Comment by VortexAcherontic** [comment]
Nearly same issue here, fresh wineprefix and even fresh Lutris config folder (/home/<user>/.local/share/lutris)
Battle.net fails to install and I've got this message in the console:
`004a:err:ntdll:RtlpWaitForCriticalSection section 0x164e1c "?" wait timed out in thread 004a, blocked by 0044, retrying (60 sec)`

**Comment by KleinMuffin** [comment]
> Install Wine-Staging
Is already installed

> Was this after a driver update? What GPU/driver do you have?
I tried to use the nvidia-driver-396 but also if I change it back to 390 it won't work.

**Comment by Alkaris** [comment]
@KleinMuffin + @VortexAcherontic Please check out my answer to a similar issue and see if this works for you in [Issue #1103](https://github.com/lutris/lutris/issues/1103#issuecomment-423557511).
