### ISSUE TITLE
League Of Legends will not install

### ISSUE THREAD

**Issue by CorruptComputer** [lutris/lutris#1121]
Running Arch, lutris 0.4.19, wine-staging 3.16

I get this error from the installer when trying: 
![image](https://user-images.githubusercontent.com/5573038/45727850-1a3f3b80-bb8b-11e8-861f-6a2d90c10628.png)

Lutris then says it successfully installed, however trying to launch says leagueclient.exe could not be found.

**Comment by elovin** [comment]
That's a wine error, does the game work with wine without Lutris? Is there any output from Lutris e.G some python error?

**Comment by Kreyren** [comment]
@CorruptComputer League Of Legends working on gentoo. Is your issue resolved?

**Comment by CorruptComputer** [comment]
I'll say the same thing said here: #1103

Honestly haven't had a chance to check, I got frustrated and just went back to using Windows on my gaming PC. This might still be an issue for someone else, but if that's the case they can always open a new one. For me at least, no longer an issue.

**Comment by Kreyren** [comment]
wow defeated.. We will hold a minute of silence for you :D
