### ISSUE TITLE
[Feature Request] Add a Logging Options (like System Options, etc)

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#1127]
With the ability to add more logging options (for wine) for example.

**Comment by Kreyren** [comment]
What do you mean?

**Comment by romulasry** [comment]
A one click solution to logging basically.

**Comment by Kreyren** [comment]
I still don't understand you? 

`Right-click the game > Configure > Runner options > Output debugging info > Enabled.` not sufficient?

**Comment by AlexanderRavenheart** [comment]
The output that is generated is hardcoded behind that single enable toggle. One should be able to choose what type of information to output to the log file.

**Comment by Kreyren** [comment]
@AlexanderRavenheart There is a drop-down which allows to output FPS, default or FULL, but agreed with better customization for logging.
