### ISSUE TITLE
[Feature Request] Add Esync toggle + check and warn low limits

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1131]
It would be nice to have a Esync toggle that allows to easily change the value of `WINEESYNC` envar (1 for on and 0 for off) if an esync build (they all have esync in their name) is in use. But to avoid issues on distributions that still use low file descriptor limit, Lutris should check it with `ulimit -r' and if that returns a value that it lower than 1048576, turning the toggle on will display a warning message that will deny turning it on and suggest to increase the limits value (and link https://github.com/lutris/lutris/wiki/How-to:-Esync).

**Comment by Kreyren** [comment]
Agreed
