### ISSUE TITLE
Problems with server connection for multiple users

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1134]
- https://forums.lutris.net/t/i-cant-login-lutris-app/3593/3?u=cxf

- https://forums.lutris.net/t/how-to-fix-runner-not-available-on-the-x86-64-architecture-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c-841/3420/6?u=cxf

- https://discordapp.com/channels/277857463384932353/277857463384932353/495282535711113226

**Comment by strycore** [comment]
closing this one since there is an ongoing discussion on the other ticket https://github.com/lutris/lutris/issues/1140
