### ISSUE TITLE
Required DLL missing error upon initial installation, current WoW installer

### ISSUE THREAD

**Issue by sunderkeenin** [lutris/lutris#1137]
Using https://lutris.net/games/world-of-warcraft/
Output of inxi -b
System:    Host: jerodpc Kernel: 4.17.0-8.1-liquorix-amd64 x86_64 bits: 64 Desktop: i3 4.15.0.1-202-g6d2d6322
           Distro: Ubuntu 18.04.1 LTS
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B250-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 1001 date: 12/11/2017
CPU:       Quad core Intel Core i5-7500 (-MCP-) speed/max: 3601/3401 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480]
           Display Server: X.Org 1.19.6 driver: amdgpu Resolution: 1920x1080@144.00hz, 1920x1080@60.00hz
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10, DRM 3.25.0, 4.17.0-8.1-liquorix-amd64, LLVM 8.0.0)
           version: 4.5 Mesa 18.3.0-devel - padoka PPA
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
Drives:    HDD Total Size: 2174.6GB (42.5% used)
Info:      Processes: 230 Uptime: 21:20 Memory: 5648.9/15988.2MB Client: Shell (bash) inxi: 2.3.56 

sudo apt update && sudo apt upgrade currently has no packages left to upgrade.

Steps to replicate:
1) Start a fresh WoW installation via Lutris
2) Launch the game
3) Get the error

Workaround:
1) Change the DXVK version from 0.80, the current default
2) Launch the game
3) Change the DXVK version back to 0.80
4) Launch the game again

**Comment by tannisroot** [comment]
Please provide “lutris -d” output when you install the game.

**Comment by sunderkeenin** [comment]
Thanks for the reminder.

[wowlutrisdoutput.txt](https://github.com/lutris/lutris/files/2431668/wowlutrisdoutput.txt)
[wowfirstlaunch_generates_error.txt](https://github.com/lutris/lutris/files/2431673/wowfirstlaunch_generates_error.txt)
There are no visible errors after changing DXVK version at least once(and launching the game) so I just change it back to 0.80 afterwards to maximize the benefit I get from dxvk.
