### ISSUE TITLE
[Feature Request] Ask for virtual desktop resolution during installer phase

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1139]
Installers only take one resolution given and it's up to the user to adjust post-install. I set my installers to 1280x720 because there are still people out there without 1080p monitors. I would like for this to be an option if an installer calls for it.

**Comment by tannisroot** [comment]
Are there any installers like this in particular?

**Comment by AccountOneOff** [comment]
https://lutris.net/games/?q=winedesktop&search-installers=on

Need for Speed Payback with out a doubt needs a virtual desktop. https://github.com/doitsujin/dxvk/issues/277

**Comment by Medath** [comment]
I think having some kind of auto option where Lutris detects the currently set resolution and applies that to the winedesktop would be better than asking to enter a resolution.
Until something like that would be implemented you could probably hack some [dropdown menu](https://github.com/lutris/lutris/blob/master/docs/installers.rst#displaying-a-drop-down-menu-with-options) with some standard resolutions together and use that in your installer.
