### ISSUE TITLE
[Feature Request] Show or copy full wine command of a game from config window or context menu

### ISSUE THREAD

**Issue by mtrp12** [lutris/lutris#1141]
I changed the wine version of one of my games and it stopped starting. It later started after 7/8 attempts. But before that was resolved, I wanted to check the wine output by running it in console. Run in console option did not output anything. So, i wanted to run the full wine command manually on terminal. But this game had many environment variables and long paths along with game exe arguments. It is very cumbersome to reconstruct the command from the configuration window. So, a button or context menu option to copy full command or text box showing it would be a quality of life improvement. Please, add such feature, if it is feasible. Thank you.

**Comment by strycore** [comment]
use `lutris -d` and it will output everything on the terminal.
