### ISSUE TITLE
Unable to install lutris using provided instructions (Ubuntu 18.04)

### ISSUE THREAD

**Issue by dafluf** [lutris/lutris#1145]
I've just performed a clean install of Ubuntu 18.04, but for the life of me, I cannot get Lutris installed.
I followed the steps on your installation page:
`ver=$(lsb_release -sr); if [ $ver != "18.04" -a $ver != "16.04" ]; then ver=18.04; fi echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -`
All of which completed without error.
However, when I now run sudo apt-get update, I get the following output:
`sudo apt-get update
Hit:1 http://be.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://be.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]
Get:3 http://be.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]
Hit:4 http://ppa.launchpad.net/jtaylor/keepass/ubuntu bionic InRelease
Hit:5 http://ppa.launchpad.net/seafile/seafile-client/ubuntu bionic InRelease  
Hit:6 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease    
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Err:8 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ InRelease
  Cannot initiate the connection to download.opensuse.org:80 (2620:113:80c0:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out
Fetched 247 kB in 32s (7.819 B/s)                             
Reading package lists... Done
W: Failed to fetch http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/./InRelease  Cannot initiate the connection to download.opensuse.org:80 (2620:113:80c0:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

If I interpret this correctly, apt is trying to download an InRelease file from the lutris repository, but that file does not exist. A Release file does exist, but I have no idea on how to force apt to use that instead...

For good measure, below the content of /etc/apt/sources.list.d/lutris.list
`deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/ ./`

Any idea on how to fix / work around this issue?

**Comment by dafluf** [comment]
For now I've grabbed the .deb package from an external source and installed it via dpkg.
However, I'd still like to find a way to resolve this. I've already spent hours googling the issue, but I can't seem to figure this one out.
From what I've read apt is supposed to try InRelease first and if not found go for the Release file. However, it doesn't appear to be doing that for some reason.

I've tried looking around if there maybe is a config option for apt to change this, but came up empty.

Other than that, my installation is a clean install of Ubuntu 18.04. So there shouldn't be anything special about it.

**Comment by dafluf** [comment]
I also tried to disable IPv6 on my adapter, to see if that's causing issues.
Now it doesn't time out anymore, but I still get a connection error.

`Err:15 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ InRelease
  Connection failed [IP: 130.57.72.10 80]
Hit:16 http://security.ubuntu.com/ubuntu bionic-security InRelease             
Fetched 1.113 kB in 10s (108 kB/s)                                             
Reading package lists... Done
W: Failed to fetch http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/./InRelease  Connection failed [IP: 130.57.72.10 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by Medath** [comment]
It seems like you've had some unfortunate timing. At the time you were trying to install Lutris, the download servers [seemed to be down](http://status.opensuse.org/incidents/170).

Does re-running the installation instructions on the website now resolve the issue?

**Comment by dafluf** [comment]
Yes, now it works. Thanks!

Just my luck... :-)

**Comment by tannisroot** [comment]
If this is resolved, you close issue then please? :)

**Comment by dafluf** [comment]
Bad timing. Download servers were down at time of installation.
