### ISSUE TITLE
Disabling Lutris runtime still downloads hundreds of megs of libraries to ~/.local/share/lutris/runtime

### ISSUE THREAD

**Issue by moll** [lutris/lutris#1146]
Hey,

I'm using Lutris as a simple WINE prefix manager and it seems perfect for that. However, I have no interest in running anything through Lutris' runtime libraries and have them disabled through Preferences. However, I'm still seeing Lutris fill its runtime folders in `~/.local/share/lutris/runtime` with a few hundred megs of code. I know there's `LUTRIS_RUNTIME=0`, but shouldn't the preference be equivalent? I'm worried things that may invoke `lutris` won't have that env var set and having a similarly named preference is confusing.

Thanks!

**Comment by tannisroot** [comment]
person from https://github.com/lutris/lutris/issues/1088 wants to disable fetching of banners too with such option

**Comment by strycore** [comment]
If you don't want the runtime at all then the official method is to export LUTRIS_RUNTIME=0
