### ISSUE TITLE
Executable path should also be an editable text field

### ISSUE THREAD

**Issue by moll** [lutris/lutris#1149]
Hey,

I noticed the **executable path** in "Game options" isn't an editable path like "Working directory" or WINE prefix are. I propose it be made editable with the standard "Browse" button next to it. I for one often pick an .exe through the file picker and then want to copy parts of the path for the WINE picker. Right now I can't. Equally, when renaming or moving the game folder, updating the executable path without editing capability is cumbersome.

Cheers

**Comment by Kreyren** [comment]
@moll in `GAME > Configure > Game options` there is none `executable path` ? afaik all paths in `GAME > Configure` are editable.

Sent a screenshot if not solved.

**Comment by moll** [comment]
I'm talking about it being also a *text input* control, not a a full-width button:

![screenshot from 2018-10-07 09-30-06](https://user-images.githubusercontent.com/156837/46580395-ae2a5780-ca13-11e8-9e7c-221e1e4d641a.png)

You're telling me you're seeing "executable" look like "Working directory"?

**Comment by strycore** [comment]
No, they are different types of widgets and I agree that a text field would be better here.

**Comment by moll** [comment]
Super! Thank you!
