### ISSUE TITLE
Hide Proton, Proton Beta, and GameHub

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#1155]
Lutris falsely detects those as "Games" while they are tools. Perhaps they should be added to a blacklist.

**Comment by Kreyren** [comment]
> Lutris falsely detects those as "Games"

meaning?

**Comment by AlexanderRavenheart** [comment]
Meaning they are added into the user's library when they should not be.

**Comment by Kreyren** [comment]
@AlexanderRavenheart Not present on gentoo using live lutris. Proton provided via steam.

**Comment by duhow** [comment]
Extends / Duplicates #1077

**Comment by Saroufim** [comment]
Thank you for pointing that out. I will close this one.
