### ISSUE TITLE
Sniper Elite 4 works fine but no sound

### ISSUE THREAD

**Issue by Toasti6** [lutris/lutris#1159]
Run in terminal pastebin

https://pastebin.com/mDsXmq2G

Lutris -d then running the game

https://pastebin.com/7fPiQsAF

Neofetch

![image](https://user-images.githubusercontent.com/43922038/46582302-66570080-ca12-11e8-928d-bbf702466cf5.png)

**Comment by tannisroot** [comment]
Does it work with regular Wine? It it doesn’t, I suggest creating a bug on WineHQ instead and closing this.

**Comment by strycore** [comment]
have you tried setting xaudio2_7 to native,builtin?
