### ISSUE TITLE
@Krey no it's not broken, works fine here

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1161]
> @strycore : @Krey no it's not broken, works fine here
> @strycore  works fine on every one's setup actually
> @strycore  except for those highly customized gentoo systems of course, but we don't support those

![image](https://user-images.githubusercontent.com/11302521/46584703-0124fe80-ca56-11e8-8560-4f624c32daca.png)

Solved on highly customized gentoo systems of course! <3

Don't worry we support EVERYTHING! Feel free to grab working libs here:
https://bugs.gentoo.org/651556 
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/fontconfig/fontconfig-2.13.1-r2.ebuild

Issue appear only if **lutris runtime is enabled** without preference for systemlibs. 

proof: https://pastebin.com/reNV2yKK

Note line 36

**Comment by Kreyren** [comment]
@Medath

> Choose a proper title for your bug reports. This title says nothing about your problem and is not helpful at all.

It proper title he knows what am i talking about.

> Also, while it's useful to know the distribution you're using, nobody cares about its alleged superiority.

No shit, written in this format since strider bashed me yesterday if it's not obvious from first 3 lines of description.

> You call it solved, but don't explain how you solved it (Disabling Lutris runtime is not a solution).
> And giving examples of people not having this problem is utterly useless as well.
> You also forgot to properly debug the runtime.

I'm calling is solved because those libs are fixed on gentoo and debian to be used for lutris. 

> Not a valid bug report until those issues are fixed.

Fixed, valid.

**Comment by RobLoach** [comment]
Fixed? Can we close it then? Thanks!

**Comment by Kreyren** [comment]
@RobLoach No we can't since it prevents some games to work?

**Comment by strycore** [comment]
what the fuck is this issue?

**Comment by Kreyren** [comment]
Seems strait forward to me, but fine i remake it into normal report...

.. i also overdid it _a bit_ to be honest
