### ISSUE TITLE
SUGGESTION - Runner selector

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1162]
![winesteam](https://user-images.githubusercontent.com/11302521/46585148-75fb3700-ca5c-11e8-910c-23c75643b68b.png)

Recommends changing `Steam (Windows)` on `Winesteam` which would make it more emergefull.

**Comment by RobLoach** [comment]
Not sure I understand your request. "Steam (Windows)" is the same as Winesteam.

**Comment by Kreyren** [comment]
> Not sure I understand your request. "Steam (Windows)" is the same as Winesteam.

I know i suggest to rename `Steam (Windows)` to `Winesteam` to make it differenciate it more from `Steam`.
