### ISSUE TITLE
MAJOR - DLL overide winemenubuilder.exe hide annoying err.

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1164]
DLL overide with value `winemenubuilder.exe` and key `d` outputs:
`ERROR    2018-10-07 19:02:00,369 [wine]:Invalid override value d`

based on:
https://wiki.winehq.org/FAQ#How_can_I_prevent_Wine_from_changing_the_filetype_associations_on_my_system_or_adding_unwanted_menu_entries.2Fdesktop_links.3F

It should disable winemenubuilder.exe and not output error above.

**Comment by AccountOneOff** [comment]
Disabling winemenubuilder is default behavior. It would be better for Lutris to suppress that message.

How and where did you enter the dll override?

**Comment by Kreyren** [comment]
@AccountOneOff in Game Configuration on lutris. Suppressing that error message is effective solution.
