### ISSUE TITLE
MAJOR - League Of Legends on Steam!?

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1165]
![lol](https://user-images.githubusercontent.com/11302521/46586281-ca59e300-ca6b-11e8-8b7a-3fb78c2eb47b.png)

League of legends is not available on steam.

**Comment by RobLoach** [comment]
https://steamdb.info/app/20590/

We'll keep the entry since it matches what's in steamdb.

**Comment by Kreyren** [comment]
@RobLoach It can't even be downloaded from steam, but since its on SteamDB well whatever.
