### ISSUE TITLE
Broken libs fontconfig in lutris's runtime.

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1167]
If fontconfig libs are used, lutris outputs errors like:

`Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'`

which makes games (which depends on a fonts) crash on startup. This issue wasn't present on `0.4.14` and is present on `aa75690`. 

LOG: https://pastebin.com/reNV2yKK (note line 36).

Sending files from `lutris/lib*` for verification.

This issue is patched on gentoo's [media-libs/fontconfig](https://packages.gentoo.org/packages/media-libs/fontconfig) 2.13.1-r2+ source: https://bugs.gentoo.org/show_bug.cgi?id=651556

Or in debian afaik.

Issue is not present if local libs are used.

Recommends replacing libs in lutris's runtime with fixed.

**Comment by strycore** [comment]
This is an issue with Gentoo

**Comment by Kreyren** [comment]
Sharing is here: https://github.com/RXT067/Research/blob/master/WINE-Dishonored2/README.md#lutris

Not a gentoo issue
