### ISSUE TITLE
DEBUG - GTA V 

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1170]

**Comment by Kreyren** [comment]
@strycore Can you move it to `Not Part Of a release` ? Want to work on it with the help of the community.

**Comment by strycore** [comment]
sure, Not part of a release is where issues go to die and I don't look at that milestone

**Comment by Kreyren** [comment]
Ideall for my intended use. 

Please move any other github issue from me labeled as `DEBUG - <GAME>` as **Not Part of a release**.

Thanks.

**Comment by strycore** [comment]
Any issue with a nonsensical title, got it :ok_hand:

**Comment by Kreyren** [comment]
@strycore 👌

**Comment by Kreyren** [comment]
Development moved on CancerlessLutris.

**Comment by strycore** [comment]
No it's not Gentoo users, it's just you, you behave like an ass.

**Comment by alkaris2** [comment]
Anybody have this issue where GTAV just breaks so badly it hangs?

![image](https://user-images.githubusercontent.com/73155407/230715370-47970dfb-69cd-40d6-a89d-9e20c79113ac.png)


Other issues include failing to load the map, textures and objects properly until the game eventually crashes in an unplayable state.
