### ISSUE TITLE
Shutting down the prefix closes Lutris too

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1171]
If you launch a game (in my case, a Wine game) through a shortcut, then open Lutris and click "Stop", it not only shut downs the game's prefix, but also closes Lutris, which I don't think is intentional behavior.

**Comment by tannisroot** [comment]
Here's me running `lutris -d lutris:rungameid/24` (to launch Overwatch) and then opening Lutris from application menu and pressing Stop: https://paste.ubuntu.com/p/JgSSMxvMDY/

**Comment by strycore** [comment]
can you confirm this is still happening with this PR merged? https://github.com/lutris/lutris/pull/1147

**Comment by tannisroot** [comment]
Nope it doesn't now.
