### ISSUE TITLE
Depend on wine-core instead of wine on Fedora

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#1173]
Lutris depends on the full `wine` package (that includes desktop files and other desktop-related things) on Fedora. This does not seem to be needed and all the games that I tried in Lutris work well without having the full Wine installed. Please, consider depending on the `wine-core` package instead.

**Comment by AlexanderRavenheart** [comment]
This should be related to the Fedora package maintainer. Lutris does not maintain packages for the different distributions.

**Comment by AlexanderRavenheart** [comment]
@strycore Can you clarify this? Are the different distribution packages maintained by us?

**Comment by strycore** [comment]
the lutris.spec file used to build the Fedora packages is version controlled in the project.
I updated the recommended package to wine-core
