### ISSUE TITLE
I have to delete dxvk_versions.json to get the latest version(s) of dxvk

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#1188]
Anyone else having this issue?

**Comment by tannisroot** [comment]
The list of available DXVK versions gets updated every 24h. This is not a bug.

**Comment by Medath** [comment]
I think this behaviour can be improved though. Adding a refresh button next to the dxvk version selector or some other gui way of manually refreshing the listed versions would be a good feature in my opinion.

**Comment by tannisroot** [comment]
@Medath I made #1189
