### ISSUE TITLE
[Feature Request] Add a refresh button to manually update the list of DXVK versions

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1189]
Currently, the user has to wait 24 hours to get it updated or manually remove `dxvk_versions.json` file to get an up to date list. This is not very user friendly and should be improved.

**Comment by strycore** [comment]
The versions should get refresh without the user having to click on a button, this is not a correct solution.

**Comment by tannisroot** [comment]
But they don't. You said it does the check only every 24 hours.
Maybe make it update it every time the user open config menu?
