### ISSUE TITLE
NXEngine not on libretro core list (Cave Story)

### ISSUE THREAD

**Issue by Aicaya** [lutris/lutris#1193]
One of libretro's runners is NXEngine, the open-source engine for the original Cave Story. Because it's not on the core list when installing a game with Lutris, however, I can't actually make a working menu item. Instead, the only way to play the game with libretro is to load up another game that uses it, then switch to Cave Story via the menu (works fine from there).

Since the libretro version allows for easier joystick remaps and overall works better than the other installation options on a multi-monitor setup (in my experience, at least), I'd like the NXEngine core to be added to the list.

**Comment by RobLoach** [comment]
If you install the core, and scan the files for the game, the menu item should show up....
https://github.com/libretro/libretro-database/blob/master/dat/Cave%20Story.dat

**Comment by RobLoach** [comment]
Ah, it's because we haven't build and deployed the nxengine core.

**Comment by Aicaya** [comment]
A question regarding a possible installer: The way libretro handles it (which is the way I installed it), it gives the option to download both NXEngine as well as the zip file for Cave Story, which it then extracts within its own download folder ready to be played immediately (the option's under Online Updater - Content Downloader - NXEngine - Cave Story(en).zip). If a Lutris installer for Cave Story on libretro is added, can it be made to do the same?

**Comment by strycore** [comment]
if this is possible to run natively on Linux without retroarch, all we need is a build script in the lutris/buildbot repository then we can host some binaries for the game.
