### ISSUE TITLE
[Feature] Add BountySource to Github Repo

### ISSUE THREAD

**Issue by asddsaz** [lutris/lutris#1198]
**Feature**: Add BountySource Widget to Github Issues Layout
**What is this**?: [Widget Instructions](https://webapps.stackexchange.com/questions/84152/how-to-enable-bountysource-plugin-on-github-to-have-integration-with-issues), [BountySource URL](https://www.bountysource.com/)
**Why?** Bountysource is a wonderfully Open Source project for adding bounties to issues. Since Lutris is still in Beta and in active development it may help entertain user attention and speed up the development of certain features.

**Comment by TingPing** [comment]
Just my two cents: Lutris is not large enough of a project to bring in meaningful bounties.

**Comment by strycore** [comment]
I don't think we want to add yet another means of donations right now
