### ISSUE TITLE
[Feature Request] Add a `Latest` DXVK option

### ISSUE THREAD

**Issue by A6GibKm** [lutris/lutris#1207]
Having to manually update the DXVK version every release shouldn't be necessary, a `Latest` option under Runner Options > DXVK version would solve this issue.

**Comment by Bumbadawg** [comment]
Same would go for a latest "Wine-staging-esync-pba" and a "latest normal release Wine".

**Comment by strycore** [comment]
Lutris automatically uses the latest DXVK version when no version is specified. Just don't put a version.
