### ISSUE TITLE
Can't change game's identifier

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1210]
![peek 2018-10-18 02-47](https://user-images.githubusercontent.com/10602045/47122669-6e1f6c00-d280-11e8-88a2-3c86c8e4e9f3.gif)
When I change it, only this appears in the debug output:
`DEBUG    2018-10-18 02:46:01,789 [config]:Saving config LutrisConfig(level=game, game_config_id=overwatch-dxvk-october-16th-20-1539741800, runner=wine)`

**Comment by strycore** [comment]
that's because the identifier field is weird and you have to click "Change" to save the new one. It's not very good UI, we should probably block the rest of the UI until the identifier is saved or cancelled.

**Comment by tannisroot** [comment]
That still won't be very good UI. I think the "Change" button should change to "Apply" when editing the identifier.
