### ISSUE TITLE
Gtk tree model assertion fails when selecting runner with 0 games.

### ISSUE THREAD

**Issue by Wcubed** [lutris/lutris#1219]
In branch next: when selecting a runner that does not have any games, the terminal gives the following warning:
`(lutris:7824): Gtk-CRITICAL **: 12:50:29.826: gtk_tree_model_sort_real_unref_node: assertion 'elt->ref_count > 0' failed`

Lutris keeps running fine afterwards, so it does not seem as critical as the warning says.

**Comment by strycore** [comment]
I've tried to understand the issue here a while back but couldn't find the cause. 

@TingPing do you have an idea what's going on here?
