### ISSUE TITLE
Vulkan check will not work on certain distributions

### ISSUE THREAD

**Issue by Tom-Todd** [lutris/lutris#1226]
Note that this probably won't work on certain distributions, where this file, for instance, is actually called `/usr/lib/x86_64-linux-gnu/libvulkan.so.1` or similar. Confirmed not working on Linux Mint 19.

_Originally posted by @Vexatos in https://github.com/lutris/lutris/pull/1186_

**Comment by Medath** [comment]
Also not working on Solus. My file is called `/usr/lib/libvulkan.so.1`
