### ISSUE TITLE
[INSTALLER PARSING] input_menu fails on parsing integer key/value if not stringified

### ISSUE THREAD

**Issue by Bumbadawg** [lutris/lutris#1228]
### ISSUE

> input_menu fails on integer key/value if it's not stringified
* this will work
```
input_menu:
  - "60": "60"
  - "59": 59 hz
```
* BUT this won't work
```
input_menu:
  - 60: 60
  - 144: 144 hz
  - "90": 90
```
### Solution
- [ ] EITHER **Update** documentation [since it is not clear about it](https://github.com/lutris/lutris/blob/master/docs/installers.rst#displaying-a-drop-down-menu-with-options)
- [ ] EITHER **make the parser stringify keys/values being integer** only to avoid parsing errors in the future.

**Comment by strycore** [comment]
I've pushed a change to the website that I will deploy tomorrow. It will disable all conversion and render everything as string. This will avoid this sort of problem. I'll add a patch to the client as well but that should be less important.

**Comment by Bumbadawg** [comment]
Awesome work @strycore ! Thank you
