### ISSUE TITLE
latest version 0.4.21 thinks i don't have a vulkan loader

### ISSUE THREAD

**Issue by LiamDawe** [lutris/lutris#1231]
Got the new message pop up to say I don't have a Vulkan loader installed. This is on an Ubuntu 18.10 fresh upgrade.

I do:

> liam@liam-main:~$ sudo apt install libvulkan1 libvulkan1:i386 
[sudo] password for liam: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvulkan1 is already the newest version (1.1.82.0-0ubuntu1).
libvulkan1:i386 is already the newest version (1.1.82.0-0ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 5 not to upgrade.

Need more details? Let me know.

**Comment by sigmaSd** [comment]
issue resolved on master https://github.com/lutris/lutris/pull/1227

**Comment by tannisroot** [comment]
@simgaSd seems like it’s actually not

**Comment by strycore** [comment]
PR #1232 improves on the implementation by providing better quality code but PR #1227 does resolve the issue. Marking solved in 0.4.22

**Comment by tainium** [comment]
Issue is still present for me in 0.4.23.
