### ISSUE TITLE
Incorrect documentation about Esync?

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#1233]
I think [Esync documentation](https://github.com/lutris/lutris/wiki/How-to:-Esync) is not 100% correct:

I've edited [/etc/security/limits.conf](https://i.imgur.com/7zCPmqj.png) in Xubuntu 18.04 and Antergos (arch based distro) and after rebooting, when I run "ulimit -Hn", shows the right value on both OS (1048576). So the Non-systemd works for both debian and arch based distros.

Could you check it out please? (if I'm wrong feel free to close this issue).

(Optional) If this is correct, it should be possible for Lutris to setup esync limits when installed, by creating a user named 'lutris', and running the games inside of Lutris as this new user. This way newbye users wouldn't need to write any console command in order to have esync working.

**Comment by tannisroot** [comment]
That would require root permissions (I think) and strider does not want to include root actions in Lutris ever.

**Comment by strycore** [comment]
This would only require root permission during the install phase, which we have and use. But I don't think this improvement has big enough of a value to justify created a dedicated user on the system.
That, plus I don't think Lutris has the responsibility to fix broken default, it should be the distribution's role to provide sane default. (I've complained about the low limit of inotify watches about 10 years ago and it has not improved one bit).

It is true that the esync documentation is not 100% correct though, on systemd systems you need to make *both* changes for the limits to become effective. I'll go and fix that.

**Comment by Zeioth** [comment]
Honestly, I agree with you, it shouldn't be Lutris responsability. But beign reallistic, I don't think we can rely on the distros to fix that.  It's not a high priority feature but... Think about it for the future. If people is going to use esync consistently, maybe it would be a good idea to make it fool proof.

Thank you for taking the time to respond.
