### ISSUE TITLE
Add option to disable game number counters, disable by default

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1238]
Although these may be useful for some people, they look really ugly and out of place.
I suggest to add a toggle to disable these and make disabled a default configuration until the look of this feature is improved in 0.5, maybe?
![screenshot from 2018-10-24 05-58-48](https://user-images.githubusercontent.com/10602045/47403541-8137ad80-d752-11e8-86a8-70ce92bda238.png)

**Comment by strycore** [comment]
This is no longer relevant, we'll have to display those numbers differently now.
