### ISSUE TITLE
[Suggestion] Move the sidebar runners list to the titlebar and right-click menu to sidebar

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1247]
Suggestion for the Next branch.

I've heard from some people that the right-click menu is too hidden so to help with that I think the right click menu should be moved to the sidebar and the runners list to the titlebar.

Like how Steam does it maybe?

![screenshot from 2018-10-24 21-39-22](https://user-images.githubusercontent.com/15083452/47476447-5c384e80-d7d5-11e8-8cab-647e074ae514.png)

**Comment by strycore** [comment]
This is old and based on the previous UI so I'm going to close this and we'll make changes on the current UI
