### ISSUE TITLE
[Origin] Battlefield 3 fails to launch outside of WineDesktop

### ISSUE THREAD

**Issue by irreleph4nt** [lutris/lutris#1252]
With the install script ptovided on the lutris website, BF3 can only be launched within a WineDesktop. When "Windowed (virtual desktop)" is unselected in Runner options and one tries to join a game, this is what one ends up with:

![bildschirmfoto von 2018-10-25 21-45-44](https://user-images.githubusercontent.com/29428359/47592073-149af980-d972-11e8-9749-b66e786b7430.png)

As it turns out, you have to disable both "Allow window manager to decorate window" and "Emulate virtual desktop" in WineCFG for the game to work outside of a virtual desktop and be able to set monitor refresh rates higher than 60Hz (I am on a 144Hz monitor). This however makes interacting with Origin and the BF3.exe difficult as things will now look like this:

![bildschirmfoto von 2018-10-26 23-00-15](https://user-images.githubusercontent.com/29428359/47592303-07cad580-d973-11e8-98d4-52d4ce624576.png)

**Comment by halvors** [comment]
@strycore This is still a problem on the latest version of lutris, can we reopen this issue?
