### ISSUE TITLE
Library sorting behavior

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1254]
Instead of "The Witcher:" coming first it comes last due to the numbers present in Witcher 2 and 3. Numbers taking precedence?

Reported by mishugashu on the forums.

![](https://forums.lutris.net/uploads/default/original/2X/c/c240c6108d5fcaeb7ae5f21022b71d4439ce632f.png)

https://forums.lutris.net/t/weird-sorting/3974

**Comment by sigmaSd** [comment]
I'm curious how to fix that, right now sorting uses simple python string comparison not sure how to go about edge cases like this

**Comment by manuelVo** [comment]
From a technical perspective the sorting in Lutris is correct. `:` comes before the space in ASCII, which is the reason why the the Witcher 1 ended up behind 2 and 3. Steam implements some heuristics in an attempt to Sort things more intuitively. Maybe we could implement something similar for Lutris.

**Comment by strycore** [comment]
we could eventually fiddle with the game slugs to change them so the sort order is correct but that would require implementing game aliases since changing the game slugs of some games will cause some breakage.

**Comment by strycore** [comment]
this is fixed now
