### ISSUE TITLE
Can’t sort games by runner/platform

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1265]
In latest master, if I click on a certain runner or a platform (Wine, Windows), it no longer sorts out games based on the runner/platform I selected.
In `lutris -d` I get this when I click:
`Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 868, in on_sidebar_changed
    self.set_selected_filter(selected_runner, selected_platform)
AttributeError: 'LutrisWindow' object has no attribute 'set_selected_filter'
`

**Comment by Medath** [comment]
Yup. Clicking any runner in the sidebar has absolutely no effect. I get the same output as above.

**Comment by strycore** [comment]
fixed the typo
