### ISSUE TITLE
Lutris doesn't preserve the setting for tray icon on relaunching

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1266]
While changing it when Lutris is running has an effect, it doesn't last after a restart of the app:
https://youtu.be/W7J7ZkxN_XM

**Comment by Medath** [comment]
So Lutris shows a tray icon at start despite it being turned off?

**Comment by tannisroot** [comment]
Exactly.

**Comment by strycore** [comment]
Fixed by PR
