### ISSUE TITLE
Support for Fedora 29

### ISSUE THREAD

**Issue by toni0491** [lutris/lutris#1272]
Fedora 29 has been released and there isn't Lutris repo. Can you add support for this version?
Thanks

**Comment by Minkiu** [comment]
I think the repo si "fine", but there are missing dependencies?

```
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.6 needed by lutris-0.4.21.1-6.1.noarch
```

**Comment by toni0491** [comment]
I refer to this https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris
I was trying to update to Fedora 29 from 28 and it show me an advertise telling me that Lutris will be removed because there aren't compatible versions

**Comment by tannisroot** [comment]
Lutris is now in official Fedora repositories. Get it from there.

**Comment by strycore** [comment]
I will be removing the Fedora repositories in OBS in the following days. They can now safely be removed on the user end.
