### ISSUE TITLE
Option to run in a read only mode

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [lutris/lutris#1278]
I want to be able to run lutris in a read only mode, so my kid won't be able change anything, only to launch all the games. 
Is there some argument or configuration I can use to achieve this behaviour?

**Comment by tannisroot** [comment]
There is no option, but you could change the mode of Lutris’s controlled folders to read-only and that would do the trick.
I suggest doing that to everything inside .local/share/lutris (except for runtime folder, that should probably stay writable), .config/lutris and Games folder.

**Comment by a-l-e-x-d-s-9** [comment]
Don't you think it could be a useful option for some people to be able to lock changes with password in gui, for people with kids or old folks? I think it's something worth considering adding in a future version.

**Comment by tannisroot** [comment]
Parental control is planned for future versions.

**Comment by strycore** [comment]
this is not at all related to lutris

**Comment by strycore** [comment]
oh wait, this is about parental control? yeah, it's tracked somewhere else, it's a duplicate then
