### ISSUE TITLE
[Process Monitor] Wait for new processes to appear before shutting down the prefix

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1281]
Some people experience an issue with the installers that use Battle.Net that is caused by the process monitor (see https://github.com/lutris/lutris/issues/973)
By default, Battle.Net installers have a default behavior to close the client after pressing "Play" button and start of the game. Presumably due to slow read speeds, there is a time window when Battle.Net client is closed, but the game hasn't opened yet and there is no process associated with it. In this of this time window, Process Monitor detects that there are no process running in the prefix, and proceeds to shut down the prefix when it shouldn't.
It has been reported to happen with Battle.Net, but it can affect various applications.
To fix this, Process Monitor shouldn't instantly start to shut down the prefix as soon as it detects that there are no processes running. Instead, it should wait a few seconds (default to 3 seconds and make it adjustable in the config) for new process to launch, and if that doesn't happen, only then to start shutting it all down.

**Comment by tannisroot** [comment]
For Overwatch installer, I changed the installer to make Battle.net have a countdown before closing itself. This workaround should do the trick while the issue is not fixed yet.

**Comment by strycore** [comment]
> To fix this, Process Monitor shouldn't instantly start to shut down the prefix as soon as it detects that there are no processes running. 

it doesn't

> Instead, it should wait a few seconds (default to 3 seconds and make it adjustable in the config) for new process to launch, and if that doesn't happen, only then to start shutting it all down.

That's what it does already.

I'm sure there is a valid issue behind all of this but the diagnostic is wrong, I can't start working on this long lasting issue with this material, especially with all the changes I intend to make to the monitor
