### ISSUE TITLE
Bug in /lutris/migrations/__init__.py

### ISSUE THREAD

**Issue by cenoks** [lutris/lutris#1282]
When launching Lutris (on arch linux) it throws `ModuleNotFoundError: No module named 'lutris.migrations.%s'`
the cause is line 29 in `migrations/__init__.py`:
`return importlib.import_module('lutris.migrations.%s', migration_name)`
changing it to the following seemed to fix it
`return importlib.import_module('lutris.migrations.%s' % migration_name)`

Didn't want to open a pull request, just in case it's a bug with Arch

**Comment by strycore** [comment]
Thanks for catching that.

@PythonicChemist wth!
