### ISSUE TITLE
Lutris Desktop/Application Launcher does not work with Steam Overlay

### ISSUE THREAD

**Issue by natemonster321** [lutris/lutris#1283]
I am using the native Steam client on Linux, and am trying to run a game installed in a wine prefix through Lutris. When adding the game through the generated desktop or application menu file, the game launches, but the steam overlay does not show. 
After a bit of searching, I found this reddit post: https://www.reddit.com/r/linux_gaming/comments/9lcoly/getting_steam_overlay_to_work_with_lutris_wine/, which launches the wine application by bypassing Lutris entirely, and the steam overlay works. Perhaps it might be good to revamp how Lutris launches apps through the desktop/application entries, as the steam overlay is pretty nice to have for the steam configurator and such.

**Comment by fazo96** [comment]
Without the steam overlay it is not possible to stream a game using Steam In Home Streaming, which is making it hard for me to play Windows GOG games with steam streaming.

**Comment by strycore** [comment]
I do have Steam overlay in Steam games so I guess it is.
