### ISSUE TITLE
Installing an already installed game is not possible with closed Lutris

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1285]
How to reproduce:
1) Have an already installed game
2) Close Lutris completely by pressing "Quit"
3) Open the webpage of the installer that was used to install the already installed game
4) Click 'Install'

What happens: a "THE GAME is already installed" window appears (just that window), promts user to either Launch the game or install it again. Selecting either of the options and clicking OK **doesn't do anything**. Nothing happens.

What's expected to happen: A main menu of Lutris should open in the background (like it does if you install a new game and not already installed one) and both options in the "THE GAME is already installed" window should work and do something.
This happens both with 0.4.21.1 and latest master.

**Comment by sigmaSd** [comment]
the commit fixed "play" but choosing the install option results in a SIGSEGV and the backtrace shows it happens on libgio-2.0.so.0 `g_menu_model_get_n_items` I'm on arch could be recent library issue, just posted to ask should I open a bug upstream?

**Comment by sigmaSd** [comment]
Nvm its not an upstream issue without the commit i get the same error for play, its weird that it fixed play for me but not install

**Comment by sigmaSd** [comment]
hmm but its not that if weird if one realizes that install shouldn't be affected in the first place by this bug ( the callback must happen)

**Comment by sigmaSd** [comment]
moving `self.activate()` https://github.com/lutris/lutris/blob/master/lutris/gui/application.py#L267 after the if block  that creates the playorinstall dialog fix the issue not sure why,
I'll ping u @strycore cause I'm not sure u get msg in closed issues

**Comment by tannisroot** [comment]
Ok, seems like it's still not fixed with that patch

**Comment by tannisroot** [comment]
@strycore please reopen

**Comment by strycore** [comment]
Does not happen in next
