### ISSUE TITLE
Update list of DXVK versions when config menu is opened

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1287]
Currently, the user has to wait 24 hours to get it updated or manually remove dxvk_versions.json file to get an up to date list. This is not very user friendly and should be improved by making it update the list every time the configuration menu is opened instead, for example.
Opened to replace https://github.com/lutris/lutris/issues/1189

**Comment by strycore** [comment]
I agree, it could be reloaded once per lutris instance, when the config dialog is first accessed
