### ISSUE TITLE
"Wine not installed" even though it is - Solus

### ISSUE THREAD

**Issue by QEDeD** [lutris/lutris#1293]
When I open any game via Lutris, I get a warning that Wine is not currently installed, despite the fact that Wine is installed as a Solus eopkg package.

Logs and system info: https://paste.ubuntu.com/p/F38fwcz535/

**Comment by Medath** [comment]
Can you provide the full log of `lutris -d`?
What is the output of `sudo eopkg it wine wine-32bit`?
I'm on Solus as well and didn't encounter this issue yet.

**Comment by QEDeD** [comment]
This should be the full log from `lutris -d`: https://paste.ubuntu.com/p/FhH5zhrtjM/
Output of sudo eopkg it wine: wine-32bit https://paste.ubuntu.com/p/Y6gCZyXMrM/

I'm guessing not having the 32-bit package could be the issue?

**Comment by tannisroot** [comment]
can this be closed then?

**Comment by QEDeD** [comment]
It can, thanks.

**Comment by tannisroot** [comment]
Can you close it?
