### ISSUE TITLE
Scripts are run from /tmp

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1299]
When using the new script feature, it seems that the scripts launched by lutris operate from `/tmp` and not in the `$GAMEDIR`.
To test that, I made a simple bash script that creates a directory named `test` in the current working directory:
```
#!/bin/bash
mkdir ./test
```
If I specify that script for On-Demand execution and launch it from the context menu, it creates a `test` directory not in the `$GAMEDIR` as expected, bur rather in `/tmp`.
This makes the scripts quite pointless as they will require you to specify a full path to function, which won't work if you distribute it with an installer.

**Comment by sigmaSd** [comment]
btw its the same for post and pre scripts , not sure if it matters where they're executed though so what do you think?

**Comment by sigmaSd** [comment]
Nvm I just changed pre post and ondemand  to default to $GAMEDIR felt more logical

**Comment by tannisroot** [comment]
Thanks!
