### ISSUE TITLE
Integrate Libstrangle into Lutris

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#1302]
There are some wine games that run too fast, or too slow, because the pace is bound to the game's FPS. An option to limit the FPS of a game from the installer, would help to prevent this.

**All this games are fixed by using strangle:**

* [Deltarune](https://lutris.net/games/deltarune/) (The pace is bound to FPS)
* [The Sims 3](https://lutris.net/games/the-sims-3/) (Very bad performance due to unlimited FPS)
* [Crash Bandicoot N Sane Trilogy](https://lutris.net/games/crash-bandicoot-n-sane-trilogy/) (Severe stuttering due to poor ingame FPS limiter implementation)
* [Doom 2016](https://lutris.net/games/doom/) (Severe stuttering due to poor ingame VSync implementation)

**URL of the library:** https://gitlab.com/torkel104/libstrangle

**Comment by Zeioth** [comment]
This issue only affect a few games, so it's probably low priority.

**Comment by strycore** [comment]
That is very cool! I was looking for something like that to fix No One Lives Forever and couldn't find one. (Game runs fine now, so I won't need it for that but still cool)

**Comment by Zeioth** [comment]
Crash Bandicoot running without "strangle 60"
![nostrangle](https://user-images.githubusercontent.com/3357792/48173538-765d4b00-e304-11e8-8ac5-838ed74a5283.png)

Crash Bandicoot running with "strangle 60"
![withstrangle](https://user-images.githubusercontent.com/3357792/48173539-765d4b00-e304-11e8-83ac-97d3305c38d8.png)

Fixes stuttering completely.

**Comment by Zeioth** [comment]
Support for FPS limit implemented

**Comment by Medath** [comment]
As @sigmaSd already said, you'll be able to use
```
system:
  fps_limit: "60"
```
to set the fps in an installer
