### ISSUE TITLE
libasound2 still causing issues in the runtime

### ISSUE THREAD

**Issue by Isakku** [lutris/lutris#1303]
Just updated to Lutris 4.22
All the games I have are Blizzard games. None of them launch since 4.19.
https://github.com/lutris/lutris/issues/1007
Before the devs fixed that issue, all my troubles were simply only one game lacking sound, but after that fix, nothing works, nothing has worked since 4.19, 4.20 nothing , 4.21 nothing now same result with the latest 4.22 version.

Game log says:
`ALSA lib conf.c:3357:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
`

I don't understand why. Maybe the logging system needs an improvement (at least it could tell where it expects the libraries to be). Maybe we need a beta testing branch so users can try the next lutris version and go back to the main branch if the update breaks everything for them. According to this https://github.com/lutris/lutris/issues/1093, all sound library references are supposed to be removed, my system has sound and everything works, but Lutris doesn't work at all for me. I guess I'll go back to PlayOnLinux.

**Comment by strycore** [comment]
do you have libasound2:i386 installed on your system?

**Comment by Isakku** [comment]
> do you have libasound2:i386 installed on your system?

Yes, I do have it. Searching for it in Synaptics package manager shows it installed, when I right click it gives the "reinstall" option, so it's installed. Maybe the installed version (I think it's my distro's default) is not matching? When looking at properties the version number says 1.1.0-0ubuntu1

**Comment by strycore** [comment]
What about about when you disable "prefer system libraries" in the Lutris system options?

**Comment by Isakku** [comment]
Hmm... 

> What about about when you disable "prefer system libraries" in the Lutris system options?

I had never seen that option. I never got that suggested when I asked for help at Lutris forums.
https://forums.lutris.net/t/starcraft-remastered-no-sound/2931

I'm testing it anyways. Oh for some reason, whenever I launch a game Baloo Indexing crashes! (that happens always, even when games worked well. I'm on Linux Mint 18.3 KDE)
Whatever, changing that option helps, now games (Blizzard's Battle.net app) at least launch... it's updating... Oh, I will have to update Battle.Net three times one for each game now!  let's test if actual games work... finished updating, closing...  Nope.
`
For some reason I was able to launch it only once, after that 

`ALSA lib conf.c:3357:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so

This is still a problem. Now none of the games run again!

**Comment by strycore** [comment]
I'll try to install Mint KDE and reproduce the issue.

**Comment by strycore** [comment]
if that happened after 0.4.19 then it was caused by the prioritization of system libs over the lutris runtime.
This has been reverted and you should not experience the libasound_module_conf_pulse errors.

Please reopen if that's not the case.
