### ISSUE TITLE
[Feature Request] Add 'Fullboot' option to PSX2 runner

### ISSUE THREAD

**Issue by krotax01** [lutris/lutris#1309]
Reason: some games need '--fullboot' launch option to get the right language (configured the first time you run the emulator with certain BIOS).

Should be an option as the existing 'Fullscreen' for this runner.

**Comment by RobLoach** [comment]
Merged https://github.com/lutris/lutris/pull/1311 ... Nicely done! In `next`, should be part of the next release.
