### ISSUE TITLE
Disallow to install/run games on NTFS partition

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1313]
Since using Wine prefixed located on NTFS partitions very often causes problems, Lutris should check if either
- the game directory (when installing the game)
- the game’s executable (that can be chosen manually in the config menu) 

are located on an NTFS partition, and if they are, display an error popup that explains the issue and prompts user to select a different location.

**Comment by robstolarz** [comment]
Is this still an issue when the disk is mounted with `defaults,exec,uid=1000,gid=1000`? This list of options makes Steam Play and Overwatch work, I haven't tried anything else on NTFS

**Comment by JanGalek** [comment]
I have automounted ([HowTo](https://gist.github.com/JanGalek/a531d094025480afc03a6b995f804a50#automatic-mount-disc)), and I havent a problem.
