### ISSUE TITLE
Unable to use dark theme on MATE

### ISSUE THREAD

**Issue by Nezchan** [lutris/lutris#1314]
I'm currently running Ubuntu MATE 18.04 LTS with Lutris 0.4.21.1, and when I select "Use dark theme" in the view menu, it does nothing.

I've been told that it's somehow dependent on having a theme with a dark version set as my system theme. But after trying every single theme that comes with MATE, the option in the View menu does absolutely nothing. If I'm using a light theme (because I want Lutris to be dark, not _every_ app), clicking "Use dark theme" does nothing, and the opposite is true if I use a light theme, unclicking it has no effect.  

Restarting the app doesn't help, nor does retstarting the system as a whole.

**Comment by strycore** [comment]
This is an issue with your theme which does not have a dark variant. Complete themes (such as Adwaita, Yaru, Pop!_OS, ...) support a dark variation of the base theme.

This is def not an issue with lutris
