### ISSUE TITLE
Feral Gamemode not Detected on Fedora 29

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#1322]
The option to enable gamemode on Fedora 29 remains greyed out despite the fact that gamemode is installed.

**Comment by tannisroot** [comment]
Can you provide info on the location of gamemode libraries in your system?

**Comment by Saroufim** [comment]
/usr/lib /usr/lib64 and /usr/bin

**Comment by sigmaSd** [comment]
@Saroufim would you test this pr https://github.com/lutris/lutris/pull/1323 ?

**Comment by sigmaSd** [comment]
be sure to have also the 32bit build of gamemode installed for it to actually function properly

**Comment by strycore** [comment]
this is because you don't have the 32 bit installed
