### ISSUE TITLE
Winbind error when installing on Fedora 29

### ISSUE THREAD

**Issue by SenPalpaMemes** [lutris/lutris#1326]
I have wine and winbind installed but i seem to be getting the following:

000b:fixme:winediag:start_process Wine Staging 3.19 is a testing version containing experimental patches.

000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.

wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)

002a:fixme:kernelbase:AppPolicyGetThreadInitializationType 0xfffffffa, 0xaefea0

0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

0009:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform

0009:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported

004a:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

004a:fixme:wbemprox:client_security_SetBlanket 0x7d084938, 0x147fc0, 10, 0, (null), 3, 3, (nil), 0x00000000

004a:fixme:wbemprox:client_security_Release 0x7d084938

004a:fixme:wbemprox:enum_class_object_Next timeout not supported

004a:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

004a:fixme:ver:GetCurrentPackageId (0x33fe14 (nil)): stub

004c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

004c:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

004c:fixme:wbemprox:client_security_SetBlanket 0x7c44c938, 0x164a10, 10, 0, (null), 3, 3, (nil), 0x00000000

004c:fixme:wbemprox:client_security_Release 0x7c44c938

004c:fixme:wbemprox:enum_class_object_Next timeout not supported

004c:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

0051:fixme:ver:GetCurrentPackageId (0x1c6fe9c (nil)): stub

0048:err:ntdll:RtlpWaitForCriticalSection section 0x1878ec "?" wait timed out in thread 0048, blocked by 0031, retrying (60 sec)

0055:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

0055:fixme:wbemprox:client_security_SetBlanket 0x7d056938, 0x147fc0, 10, 0, (null), 3, 3, (nil), 0x00000000

0055:fixme:wbemprox:client_security_Release 0x7d056938

0055:fixme:wbemprox:enum_class_object_Next timeout not supported

0055:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

0055:fixme:ver:GetCurrentPackageId (0x33fe14 (nil)): stub

0057:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

0057:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

0057:fixme:wbemprox:client_security_SetBlanket 0x7c373938, 0x164a10, 10, 0, (null), 3, 3, (nil), 0x00000000

0057:fixme:wbemprox:client_security_Release 0x7c373938

0057:fixme:wbemprox:enum_class_object_Next timeout not supported

0057:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

005c:fixme:ver:GetCurrentPackageId (0x1c6fe9c (nil)): stub

0060:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

0060:fixme:wbemprox:client_security_SetBlanket 0x7d042938, 0x147fc0, 10, 0, (null), 3, 3, (nil), 0x00000000

0060:fixme:wbemprox:client_security_Release 0x7d042938

0060:fixme:wbemprox:enum_class_object_Next timeout not supported

0060:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

0060:fixme:ver:GetCurrentPackageId (0x33fe14 (nil)): stub

0063:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

0063:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags

0063:fixme:wbemprox:client_security_SetBlanket 0x7c447938, 0x164a10, 10, 0, (null), 3, 3, (nil), 0x00000000

0063:fixme:wbemprox:client_security_Release 0x7c447938

0063:fixme:wbemprox:enum_class_object_Next timeout not supported

0063:err:ntdll:NtQueryInformationToken Unhandled Token Information class 24!

0069:fixme:ver:GetCurrentPackageId (0x1c6fe9c (nil)): stub

**Comment by tannisroot** [comment]
https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info

**Comment by tannisroot** [comment]
i suggest asking for help on LGG Discord server

**Comment by tannisroot** [comment]
And close this issue please if that’s ok.

**Comment by SenPalpaMemes** [comment]
i have tried on discord and i get ignored

**Comment by tannisroot** [comment]
Ping Tannis Root there.
