### ISSUE TITLE
Proton shows up as game again

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#1327]
In lutris 0.4.23 Proton shows up in my library again and therefore also in the right click menu of the tray icon.
Related to #1077

**Comment by basxto** [comment]
![2018-11-10_10 32_786x749](https://user-images.githubusercontent.com/1314450/48299888-04d3f700-e4d4-11e8-8809-100281809422.png)

Proton 3.7 and 3.7 Beta still have the same appid
Proton 3.16 has 961940

**Comment by basxto** [comment]
Okay it appears to work when I completely remove them from my library, I just deleted them,

**Comment by tannisroot** [comment]
I suppose this should be closed then?

**Comment by basxto** [comment]
No, they reappeared.
But only 3.7 and 3.16 now.

**Comment by tannisroot** [comment]
I can't reproduce this.
If you want this to get fixed, please describe step by step how you cam reliably get these to show up in your library.

**Comment by basxto** [comment]
I can’t reproduce it myself, I will look for a pattern, though.
Deleting it from my library and importing from steam does not result in this behavior.
Steam updated this morning, but I don’t see how that could be related to that.

**Comment by strycore** [comment]
Proton versions are now excluded by a regex
