### ISSUE TITLE
Port to RHEL/CentOS

### ISSUE THREAD

**Issue by jatin-newacc** [lutris/lutris#1329]
On Fedora Lutris runs fine but its having error on installing on CentOS/ RHEL 7. Please port to CentOS7/RHEL7 as most of the enterprise softwares like Autodesk Maya are only available on those platforms and most of my softwares. Its more used than Slackware. Please Strycore (Strider), Request to port Lutris. Because that is the only reason i am using Fedora. Thanks :) :+1:

**Comment by tannisroot** [comment]
It’s up to the maintainers of repositories for these distributions to package Lutris.
Plus, I highly doubt Lutris will work on such outdated distributions.

**Comment by jatin-newacc** [comment]
I agree, but there are many ways to solve this... Unreal Engine was not compatible with the dependencies on Cent OS the similar way, what they did to solve this was to include bundled dependencies in thier package.

Or else Provide a flatpak would also be a great solution. Outdated distribution is no problem these days not just becuase of flatpak or snaps but also providing bundled dependencies. Many modern softwares like Autodesk Maya and Davinci Resolve only support CentOS/RHEL not even Ubuntu they provide bundled dependencies instead of using system dependencies.

**Comment by tannisroot** [comment]
There is a Flatpak version in active development. I guess that could work for you.

**Comment by jatin-newacc** [comment]
when flatpak Version would come (as stable) because i talked with strider (strycore) and he said that back in 2017. And if the development version works fine still it not contain all the dependencies specially DXVK related stuff it only contains python stuff, and flatpak dont use system dependencies so that will mostly be a problem. Snaps use system dependencies and is alot better but not supported on many distros yet. For Flatpak you need to include all dependencies i guess and there are many particular game dependent dependencies so ... im not sure.

**Comment by TingPing** [comment]
> and flatpak dont use system dependencies so that will mostly be a problem. Snaps use system dependencies and is alot better but not supported on many distros yet.

Well uh. Yes you are either portable (and contain dependencies) or you are not portable (and use host dependencies). There is nothing in between that is sane or reasonable.

**Comment by tannisroot** [comment]
There are no game specific dependencies. I am not sure but I think the WIP flatpak will just package every possible dependency for wine + some extra stuff and stuff for other emulators.

**Comment by jatin-newacc** [comment]
Game specific dependencies like Battle Net dependencies like https://github.com/lutris/lutris/wiki/Game:-Blizzard-App and others like maybe origin client. They do have some dependencies like libsqlite, gnutls and msttf core fonts and few more.

**Comment by jatin-newacc** [comment]
Also can you send me the link of active development package so that i can test it ?

**Comment by TingPing** [comment]
https://github.com/robloach/lutris-flatpak

**Comment by Zeioth** [comment]
This issue is been answered and can be closed.

**Comment by jatin-newacc** [comment]
When flatpak version is expected to be stable there are many issues still.. I just copied Blizzard net from my games folder on fedora to the RHEL and ran it using Lutris flatpak. I will either start a new issue when I get the problem (if any because im not sure as i have not installed few dependencies) this can be closed.
