### ISSUE TITLE
Lutris is not passsing resolution setting to Xephyr

### ISSUE THREAD

**Issue by throwaway2242** [lutris/lutris#1333]
I can write any value including an invalid value in the xephyr resolution option, but Lutris does not appear to pass it to Xephyr. This means the window is always running at native resolution (for me, 1920x1080). Specifying 640x480 or any other value has no effect.

**Comment by strycore** [comment]
That's not entirely true, Xephyr is passed the correct resolution and uses it but it also defaults to fullscreen which does not handle resolution switching. 
To make this clearer, I added a fullscreen option.
Xephyr does not handle resolution switching, you have to use the "Switch resolution to" option
