### ISSUE TITLE
Lutris DXVK error

### ISSUE THREAD

**Issue by GottaSlay** [lutris/lutris#1339]
Upon trying to launch a game with DXVK enabled, me and many other users are getting an error saying: 
[https://i.imgur.com/vpTcUdk.png](url) Someone mentioned that the older launchers work perfectly.

**Comment by sigmaSd** [comment]
That can happen if you have WINEPREFIX not set and started a game without a configured prefix,
Be aware that if you used lutris from git, you'll have to remove user.reg in the lutris root folder, if you used lutris from your package manger it wont have the permission to write on /usr/bin so just set the WINEPREFIX var for it to work,
We probably should throw an error when WINEPREFIX='' or default to somewhere

**Comment by strycore** [comment]
Lutris now defaults to ~/.wine when no prefix is provided.
