### ISSUE TITLE
Lutris wont start

### ISSUE THREAD

**Issue by CrackedCrafterz** [lutris/lutris#1344]
raceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 27, in <module>
    gi.require_version('Gdk', '3.0')  # NOQA # isort:skip
AttributeError: module 'gi' has no attribute 'require_version'

**Comment by strycore** [comment]
Your PyGObject installation seems to be completely borked, this is a totally new one, I have no idea how you reached that point.

**Comment by strycore** [comment]
No one can work with that little info.

**Comment by CrackedCrafterz** [comment]
fixed by a re-installation

**Comment by ndbellew** [comment]
Might I also reccomend https://stackoverflow.com/questions/49492345/python3-6-error-importing-gi-module
