### ISSUE TITLE
Does not work on Debian

### ISSUE THREAD

**Issue by asddsaz** [lutris/lutris#1349]
The package `python3-evdev` is not available for a stable version of Debian (stretch)[1](http://archive.is/iNcLA)
Log: 
```
root@LINUX:/home/usr# apt-get install lutris
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lutris : Depends: unrar but it is not installable
          Recommends: python3-evdev but it is not installable
E: Unable to correct problems, you have held broken packages.
root@LINUX:/home/usr# 
```

All other dependencies can be installed with packages 
  `lib32gcc1` `libc6-i386`

**Comment by asddsaz** [comment]
What I have tried:
- I have reinstalled my OS and retrying
- Installing via `python-pip` with `pip install evdev`

**Comment by Zeioth** [comment]
Debian stable is meant to run on servers, and because of this, it lacks many basic dependencies Ubuntu has. Lutris is compatible with Debian, but you'll have to install manually from the internet the dependencies which are not available in Debian's repositories.

If you want to make your life easier, I'd recommend you to try one of the flavours of Ubuntu (Which is basically Debian with normal repositories, desktop ready).

If you wanna make your life even easier, try one of the flavours of Manjaro (Which is basically the same, but with more complete repositories, and a different package manager)

**Comment by QEDeD** [comment]
You might also want to take a look at this Reddit thread: https://www.reddit.com/r/linux_gaming/comments/9oqq3w/guide_migrating_to_linux_in_2019/ Personally I'd recommend looking into Solus (https://getsol.us/)

**Comment by asddsaz** [comment]
No offense, but the issue is that it doesn't work with Debian. Not what OS I should switch from. Lutris officially supports Debian. 

I prefer Debian over Ubuntu on many philosophical and usability stances like free software and privacy. As for Solus, I will look into this.

To be clear, I'm fine downloading from the internet. I just don't know where to find them. If this is needed it should be included in the installation steps for Debian.

**Comment by strycore** [comment]
there may be a way to make this package optional, it is not critical in order to use the client (but it is used for joystick detection features). I have to find the syntax that will install a package if it's here but ignore it if not in the debian/control file.

**Comment by AaronOpfer** [comment]
The problem is that you don't have `non-free` packages available in your sources which is where `unrar` is listed. Lutris works fine for Debian stable here.

**Comment by AaronOpfer** [comment]
Apparently `unrar` is already removed as a dependency in `next`.  81b9b629df2c564b3766b547fd7de9e49e149c2d
