### ISSUE TITLE
Finish port to GZDoom

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#135]
There are a few engines out there that we could use to run Doom games (`.wad` files).
- [Doomsday Engine](http://dengine.net/)
- [Doom Legacy](http://doomlegacy.sourceforge.net/legacy.shtml)
- [PrBoom Plus](http://prboom-plus.sourceforge.net/)
- [... and more](http://www.doomworld.com/classicdoom/ports/?platform=3)

This would cover games like Doom, Doom 2, Hexen, Heretic, etc.

**Comment by RobLoach** [comment]
I saw you use [ZDoom](http://zdoom.org) in https://lutris.net/games/hexen-beyond-heretic/

**Comment by strycore** [comment]
Yes, zdoom is used in all Doom based games, I updated the build script yesterday on buildbot so it's up to date now and I used this build for all the games that can support it on Steam (Ultimate Doom, Doom II, Final Doom, Heretic, Hexen, ...)

**Comment by RobLoach** [comment]
This is done.

**Comment by dmsun** [comment]
Hi team, not sure if this is the place to mention such a thing, but could this be re-opened if favour of adding GZDoom, and/or Zandronum? They're both based on ZDoom, but are still being supported and developed. ZDoom isn't being worked on anymore - discontinued in 2016.02 according to [ZDoom.org.](https://zdoom.org/downloads). This could lead to support issues down the road. 

GZDoom uses OpenGL and has better textures, lighting etc., whilst Zandronum allows Multiplayer.

**Comment by strycore** [comment]
We have GZDoom builds, not sure why we're relying on ZDoom still… I think I tried giving Zandronum a go and it might be one of those engines with a messed up build system that doesn't produce a relocatable executable (but I'm maybe mistaking with DoomsDay)

**Comment by strycore** [comment]
The default version is now GZDoom 3.6.0
