### ISSUE TITLE
Watching Steam folder when sync configuration disabled

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [lutris/lutris#1355]
I see this debug messages when starting lutris: "[steam]:Watching Steam folder", for steam folder I've installed and lutris internal steam folders, although I disabled synchronization of steam (and anything else):
![image](https://user-images.githubusercontent.com/6518064/48661080-46851480-ea75-11e8-8e32-65598d1143aa.png)
Is it an unintended behaviour?

**Comment by Medath** [comment]
It checks if an existing Steam game gets uninstalled and removes it from the Lutris library. It's to prevent Lutris from potentially showing not installed games as installed.

**Comment by strycore** [comment]
this is all redone now
