### ISSUE TITLE
When Launching Warframe: get_dll_overrides(): wine.py:628:get_dll_overrides:AttributeError: 'str' object has no attribute 'update'

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#1356]
Heyo, got another bug report on Fedora, now for 0.4.23!

Here's the BZ with more info, as always: https://bugzilla.redhat.com/show_bug.cgi?id=1650910

**Comment by werman** [comment]
Doesn't look distro specific, got similar error on Arch when tried to install warframe for the first time. Was able to bypass it by removing `overrides: None` from the game config which resides in `~/.config/lutris/games/ `

After looking into install script I saw  `overrides: null` which looks obviously suspicious.

**Comment by waylon531** [comment]
I got a different error that appears to be caused by the same line, the config menu won't open for Warframe until you move that line of code. I'm on Arch Linux as well.
