### ISSUE TITLE
Cannot download wine-esync-staging-pba-3.16-x86_64.tar.gz - file broken?

### ISSUE THREAD

**Issue by cars10** [lutris/lutris#1359]
Hi, right now i am trying to install some games and the installer then tries to download the following file:

https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-esync-staging-pba-3.16-x86_64.tar.gz

Sadly the download does not work, it seems that the files is broken.

**Comment by strycore** [comment]
@cars10 indeed, there were some issues on the NY Digital Ocean datacenter a few days ago which resulted in some corrupt files.

Instead of re-uploading that build, I've updated all installer using it to use a more updated build, they should be working now.

**Comment by rizzini** [comment]
Still can't download it.
This shows up:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<BucketName>lutris</BucketName>
<RequestId>tx0000000000000131ff50d-005e5928ff-340a218-nyc3a</RequestId>
<HostId>340a218-nyc3a-nyc</HostId>
</Error>
```
