### ISSUE TITLE
I created binary package for CentOS

### ISSUE THREAD

**Issue by jatin-cbs** [lutris/lutris#1364]
Hi devs,

I just created a binary package myself for lutris to run it on CentOS 7/RHEL 7
![screenshot from 2018-11-23 04-21-38](https://user-images.githubusercontent.com/40650341/48923816-cda01580-eed7-11e8-938b-9d27ada04684.png)
![screenshot from 2018-11-23 04-22-25](https://user-images.githubusercontent.com/40650341/48923818-d395f680-eed7-11e8-8592-cc474d84931f.png)

These are packages and others i myself downloaded and i would love to maintain the repo for future releases, if you guys give me permission i can create a CentOS/RHEL repo on github.

There are few changes i needed to make like creating python symlink and just few other tweaks but i managed to run it on RHEL 7.6.

**Comment by jatin-cbs** [comment]
I also did a change in python version 3.6 to 3.4 in python site packages as lutris was finding it in 3.4. But its working i will test and show the results of few games tommorow. Can i have permission to create github package repo for CentOS/RHEL 7 ?

**Comment by jatin-cbs** [comment]
https://forums.lutris.net/t/progress-on-centos-build/4285 here is the forum post where i asked strider.

**Comment by jatin-cbs** [comment]
https://github.com/jatin-cbs/Lutris-RHEL-CentOS7 here is the repo :) +1

**Comment by strycore** [comment]
I'd like to host the packages on OBS if possible, did you have to make a lot of changes in the lutris.spec file?

**Comment by jatin-cbs** [comment]
i had to do- 

sudo mv /usr/lib/python3.6/site-packages/lutris /usr/lib/python3.4/site-packages/

because lutris was finding it in 3.4 python site packages but it was installed in python 3.4

other steps i have mentioned here https://github.com/jatin-cbs/Lutris-RHEL-CentOS7 in the readme, some standard dependencies and few extras which I provided in the repo.

**Comment by jatin-cbs** [comment]
This is just 1 extra step step i had to do, next is to install some dependecies from system repo and few others which are not provided in the official centOS repo i provided it in my repo.

**Comment by strycore** [comment]
I don't see anything that specifies Python 3.6 in the spec file.

Please submit necessary changes in a pull request. **Make sure the change do not break ANY other build**

**Comment by jatin-cbs** [comment]
It may actually break other builds, Lutris is finding itself in python 3.4 but that was installed in python 3.6 site packages, so i had to move it 

sudo mv /usr/lib/python3.6/site-packages/lutris /usr/lib/python3.4/site-packages/ 

Otherwise it shows the no module found error.

**Comment by jatin-cbs** [comment]
its specific to CentOS/RHEL as still python 3.6 is not default.

What can be a solution to this is if you make python 3.4 package including PyYAML 3.4 and Gobject 3.4 the dependency for CentOS/RHEL instead of python 3.6 or 3.7 that would solve the problem.

**Comment by strycore** [comment]
It seems strange that the package would be built against a python version that is unavailable on the system.

@BunnyApocalypse  you got any input on that? I'm not familiar with RPM packaging at all…

**Comment by BunnyApocalypse** [comment]
Yeah, I'm by no means a master of rpm packaging, but to my understanding everything is very distro python3 generic in my spec, so it should be installing to whatever %{python3_sitelib} resolves to in your specific rpm configuration. You could check that by running `rpm --eval %{python3_sitelib}`.

**Comment by jatin-cbs** [comment]
Here is the problem 
![screenshot from 2018-12-10 00-01-24](https://user-images.githubusercontent.com/40650341/49701179-eb2aea00-fc0e-11e8-9f0f-2bec307fe5fa.png)

This is inside the RPM spec file. It says it to put itself in python 3.6 folder please change it to python 3.4

**Comment by jatin-cbs** [comment]
provide cache and everything for python 3.4.

**Comment by jatin-cbs** [comment]
I fixed the bug and i have updated my repository now it can be moved to OBS strycore.

**Comment by jatin-cbs** [comment]
I updated RPM (created a single centOS rpm with all dependencies including wine and vulkan)
I have put this issue so far in known issues) and solution for now is to manually move the package to 3.4 folder. See read me https://github.com/jatin-cbs/Lutris-RHEL-CentOS7

**Comment by strycore** [comment]
hm, that's only the rpm, would be great if could you put the .spec file as well. The goal would be to have something we can ship with the other packages and keeping the differences with the Fedora package at a minimum.

**Comment by jatin-cbs** [comment]
you can edit the spec file by using 
rpmrebuild -e -p lutris-0.4.21-1.el7.noarch.rpm
assuming you have installed rpmrebuild on any distro.

But I have edited the spec file adding el7 string for centOS/RHEL7 and also changed distribution name in the spec file. So I don't think there should be a problem differentiating it with other packages.

**Comment by jatin-cbs** [comment]
for fedora package its lutris-0.4.21-1.fc28.noarch.rpm
and for CentOS package its lutris-0.4.21-1.el7.noarch.rpm
and have different distribution name in the spec file too !

**Comment by jatin-cbs** [comment]
I created and added Lutris 4.23 :)  
https://github.com/jatin-cbs/Lutris-RHEL-CentOS7

**Comment by BackOrder** [comment]
> For current state if anyone can prepare a lutris RPM with dependency python34 python34 PyYAML and python34-Gobject and others will fix this issue. On centOS 7 and RHEL 7 we need an rpm with python 3.4 dependency not python 3.6 or 3.7.

`yum install python34-PyYAML` works just as well. :)

**Comment by jatin-cbs** [comment]
I included PyYAML as a dependency that is not the issue anymore :)

**Comment by jatin-cbs** [comment]
@strycore I have sent you 4.21 and 4.23 lutris CentOS RPM packages on the Build Service already they are tested and working.

**Comment by strycore** [comment]
wat? 0.4.23 is deprecated now.

**Comment by strycore** [comment]
I don't know what going on with this ticket. Please just open a PR when you feel ready.
