### ISSUE TITLE
Add support for custom builds of DXVK

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1365]
To avoid breakage in case something happens to Github/DXVK/DXVK's page on Github, Lutris should fetch DXVK releases from its github repo and provide them through on its own.
Also, allowing moderators to upload and use custom DXVK builds with game-specific fixes in installers would be nice, I am particularly interested in uploading an Async build.

**Comment by strycore** [comment]
we're not going to implement this exactly like this.

* The default DXVK builds will stay on github.
* We will remove the Github API call in the client and replace it to a call to `/api/runtime/dxvk`
* The API endoint exposes `url` and `version` fields.
* It is possible to override the URL with one pointing to a custom DXVK build
* In case Github catches on fire or whatever unlikely catastrophe, it would be possible to switch all URLs to self hosted ones.

**Comment by tannisroot** [comment]
Why... did this valid feature request got closed?

**Comment by strycore** [comment]
now tracked on #2007
