### ISSUE TITLE
DXVK versions not updating (git)

### ISSUE THREAD

**Issue by clapbr** [lutris/lutris#1370]
![screenshot_20181124_233328](https://user-images.githubusercontent.com/6379485/48974484-5b980f80-f042-11e8-8d26-963cca6f1a70.png)

Tried to delete dxvk_versions.json manually but it doesnt get recreated.

**Comment by tannisroot** [comment]
I can't reproduce this.
Please provide more information.

**Comment by clapbr** [comment]
Really nothing much besides default everything. Tried and reproduced in a clean user, video https://www.youtube.com/watch?v=aiz05PMA1ws&feature=youtu.be - sorry for potato quality, I sent 1080p but youtube encoder butchered it.

**Comment by clapbr** [comment]
Ok, figured it out. get/init_dxvk_versions only triggers if I install a game on steam wine and then change it's configuration. This behavior could change to also trigger when you open Wine and Wine Steam configs without any game.

**Comment by strycore** [comment]
Makes sense, that should give me enough info to start working on a fix.
