### ISSUE TITLE
Integrate IPF plugin to FS-UAE runner

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#1372]
Hello,
when I try to launch the Another World game, I have this error message:
IPF support plugin is not installed
I know where to downoad this plugin:
https://fs-uae.net/download#plugins
But where to store this plugin for the Lutris FS-UAE runner use it?

**Comment by strycore** [comment]
I'm not 100% sure about that but it's likely to be in the FS-UAE folder in ~/.local/share/lutris/runners

I know I did that at least once in the past and it worked pretty well. Maybe this is something that's worth integrating in the client.

**Comment by legluondunet** [comment]
I just created a "Plugins" folder in "~/.local/share/lutris/runners/fs-uae", put the "CAPSImg" plugin folder inside, but it doesn't work.
I'm using the fs-uae portable development version too: https://fs-uae.net/download-devel#linux
and this method works!
You don't use the portable version in Lutris?
The portable version has another advantage: it does not store config and others user  folders/files in "Documents", but in its current program folder.

**Comment by strycore** [comment]
Not sure we'd want to use the portable version since the runner folder in ~/.local/share/lutris is likely to get deleted while updating to newer versions of fs-uae.

**Comment by legluondunet** [comment]
I moved put the "Plugins/CAPSImg" plugin folder to "/home/legluondunet/Documents/FS-UAE/" folder and it works now. Thank you for your help.

**Comment by strycore** [comment]
Please note that our FS-UAE build was quite old.
I just updated it to the latest version, you can remove the old one and re-download it.
