### ISSUE TITLE
Game added twice. One with empty configuration

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1374]
I was testing an installer that I had to keep removing/reinstalling, because of other things not related to this bug, and somehow after 3-4 tries Lutris ended up adding two entries. One that has the correct information and one that is just empty but still acts as the installed game.

These two screens are from the same empty game entry:

<details>

![screenshot from 2018-11-25 02-07-21](https://user-images.githubusercontent.com/15083452/48984544-a604a500-f0b1-11e8-8de6-6a2af72f6516.png)

If I try removing it:

![screenshot from 2018-11-25 02-07-34](https://user-images.githubusercontent.com/15083452/48984545-a866ff00-f0b1-11e8-999e-45346f21cce8.png)
![screenshot from 2018-11-25 02-07-27](https://user-images.githubusercontent.com/15083452/48984546-ab61ef80-f0b1-11e8-935d-ee56eaf27327.png)

</details>
<br>

The first Mogeko shown is the empty one. Here's the log I saved from my last install.

[mogeko-double-entry.txt](https://github.com/lutris/lutris/files/2613506/mogeko-double-entry.txt)

I also had this happen that I think might be related but wasn't able to reproduce:

Game acts like it's installed when there is no entry, game folder (\~/Games) or config file (~/.config/lutris/games). Again after removing/reinstalling several times:

![screenshot from 2018-11-22 23-56-25](https://user-images.githubusercontent.com/15083452/48984611-85891a80-f0b2-11e8-8baa-b5b9feaeea0a.png)

**Comment by strycore** [comment]
Removing from this release since there doesn't seem to be reproduction steps

**Comment by AccountOneOff** [comment]
It's happened again. Installed game via local script yesterday, launched once, removed, shutdown, and today it's back. I did change the name in the script. I don't know if that matters. No double entry this time though.

![screenshot from 2018-12-21 22-05-31](https://user-images.githubusercontent.com/15083452/50371286-953e3680-056c-11e9-97e6-125cb21600b7.png)

**Comment by strycore** [comment]
This has been fixed
