### ISSUE TITLE
0.4.23 thinks i don't have a vulkan loader 

### ISSUE THREAD

**Issue by tainium** [lutris/lutris#1377]
Issue since 0.4.21:
https://github.com/lutris/lutris/issues/1231

@LiamDawe
> Got the new message pop up to say I don't have a Vulkan loader installed. This is on an Ubuntu 18.10 fresh upgrade.
> 
> I do:
> 
> > liam@liam-main:~$ sudo apt install libvulkan1 libvulkan1:i386
> > [sudo] password for liam:
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > libvulkan1 is already the newest version (1.1.82.0-0ubuntu1).
> > libvulkan1:i386 is already the newest version (1.1.82.0-0ubuntu1).
> > 0 to upgrade, 0 to newly install, 0 to remove and 5 not to upgrade.
> 
> Need more details? Let me know.

**Comment by tainium** [comment]
Here's the debug output.


tainium@host:~$ lutris -d
DEBUG    2018-11-27 14:11:56,712 [http]:GET https://lutris.net/api/runtime
DEBUG    2018-11-27 14:11:57,305 [runtime]:Runtime winetricks is already up to date (locally updated on Tue 27 Nov 2018 06:35:15 PM GMT, remote created on Sun 25 Nov 2018 08:25:58 PM )
DEBUG    2018-11-27 14:11:57,305 [runtime]:Runtime steam is already up to date (locally updated on Sat 10 Nov 2018 05:13:21 PM GMT, remote created on Sat 03 Nov 2018 03:11:04 AM )
DEBUG    2018-11-27 14:11:57,305 [runtime]:Runtime lib64 is already up to date (locally updated on Sat 10 Nov 2018 05:13:05 PM GMT, remote created on Mon 08 Oct 2018 03:29:56 AM )
DEBUG    2018-11-27 14:11:57,306 [runtime]:Runtime lib32 is already up to date (locally updated on Sat 10 Nov 2018 05:13:10 PM GMT, remote created on Mon 08 Oct 2018 03:29:40 AM )
DEBUG    2018-11-27 14:11:57,306 [runtime]:Runtime p7zip is already up to date (locally updated on Sat 10 Nov 2018 05:13:00 PM GMT, remote created on Tue 25 Oct 2016 02:34:44 AM )
DEBUG    2018-11-27 14:11:57,307 [api]:Fetching game library
DEBUG    2018-11-27 14:11:57,378 [steam]:Watching Steam folder /home/tainium/.steam/steam/steamapps
DEBUG    2018-11-27 14:11:57,378 [steam]:Watching Steam folder /usr/games/NativeLinuxGames/SteamNativeLinux/steamapps
INFO     2018-11-27 14:11:57,506 [lutriswindow]:Setting up view for first run
DEBUG    2018-11-27 14:11:57,506 [lutriswindow]:Syncing 42 icons
DEBUG    2018-11-27 14:11:57,507 [resources]:Requesting missing icons from API for 10 games
DEBUG    2018-11-27 14:11:57,507 [http]:GET https://lutris.net/api/games
INFO     2018-11-27 14:11:57,914 [api]:Loaded 2 games from page 1
DEBUG    2018-11-27 14:12:01,677 [wineprefix]:Virtual desktop: None
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/system32/dxgi with DXVK version
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/system32/d3d11 with DXVK version
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/system32/d3d10core with DXVK version
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/system32/d3d10 with DXVK version
INFO     2018-11-27 14:12:01,689 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2018-11-27 14:12:01,690 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2018-11-27 14:12:01,690 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2018-11-27 14:12:01,690 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2018-11-27 14:12:01,690 [dxvk]:Replacing /usr/games/NativeLinuxGames/lutris/PoE64DXVK_ESYNC/drive_c/windows/syswow64/d3d10 with DXVK version
Gtk-Message: 14:12:01.737: GtkDialog mapped without a transient parent. This is discouraged.
DEBUG    2018-11-27 14:12:03,110 [game]:Launching Path of Exile: {'error': 'VULKAN_NOT_FOUND'}

Vulkan and DXVK had been working fine for me but I've had this issue pop up periodically.  It has been resolved in the past by tinkering with the Runner settings until it worked...nothing seemed to stand out as the obvious solution.  The problem does seem loosely correlated to system, perhaps specifically nvidia, updates.

**Comment by tainium** [comment]
Looks like an update tinkered with my system video drivers.  Updating from nvidia open source 410 to 415 resolved this issue.

**Comment by Zeioth** [comment]
Happy to hear that. Please close the issue if you were able to solvde it.
