### ISSUE TITLE
Lutris not showing games

### ISSUE THREAD

**Issue by betam4x** [lutris/lutris#1380]
I can see them on the website, privacy settings are set correctly, but still nothing.  I've tried hitting the synchronize button and it instantly finishes.  I've tried restarting the app without success.  The last time I installed Lutris (2 days ago, I did a distro reinstall because I'm mucking with some KVM/libvirt stuff) it worked fine.  Any idea what might be going on?  Debian based distro, Deepin OS (although I'm about to switch to Ubuntu)

EDIT:  I DO have around 800 games, but once again, it was working before.

EDIT #2:  It may be worth creating a new process when synchronizing games.  I've noticed that the UI can freeze sometimes.

Nevermind, found the issue, my steam runner was somehow corrupt.

**Comment by Zeioth** [comment]
I'm glad you were able to fix it. Please, close the issue if it's solved.

**Comment by strycore** [comment]
If you have a large library of games, lutris can take quite a while to sync and show them. I'll close this ticket since we're working on this issue on another one.

**Comment by betam4x** [comment]
I had to restart lutris to get the games to show up Maybe consider adding a
'refreshing library' in a separate thread that doesn't freeze the UI.

**Comment by Medath** [comment]
This is now done on current master. So it should be fixed with the next version.
