### ISSUE TITLE
Steam is overriding the value of DXVK_STATE_CACHE_PATH

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#1384]
**PROBLEM**
The env var DXVK_STATE_CACHE_PATH is beign ignored in all Steam games. This happens because Steam defines its own value for the env variable DXVK_STATE_CACHE_PATH.

This bug has been confirmed in Steam for Windows running over wine. It might also affect Steam native and Steam runtime.

**HOW TO REPRODUCE IT**

1. Install [Quake Champions](https://lutris.net/games/quake-champions/) (or any other dx11 game) and in [Lutris > System options > Environment variables] set a value for DXVK_STATE_CACHE_PATH and launch the game. 
2. You will be able to check that the state cache is not beign created in that location.
3. Instead, steam will create it in the next path
 `   ~/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps/shadercache/611500/DXVK_state_cache/QuakeChampions.dxvk-cache`

**POSSIBLE SOLUTION**
The env var could be defined after steam's defines its own, in order to override it.

**WORKAROUND**
Every time you want to install an external cache in a Steam game, do it in the directory 

`/Steam/steamapps/shadercache/id_of_your_game/DXVK_state_cache`

**DO WE NEED TO FIX IT?**

* Steam might distribute its own dxvk state caches in the future. if that's the case, this bug wouldn't need to be fixed. 
* But if Lutris is planning to integrate dxvk-cache-pool in the future, then this behaviour needs to be changed.

**Comment by Zeioth** [comment]
This is not set on stone but Steam might release a fix for this issue soon
![fix](https://user-images.githubusercontent.com/3357792/49343591-cd88de00-f66c-11e8-94b0-d31e4d258c4d.png)

**Comment by Zeioth** [comment]
This is still beign discussed, but this bug could be fixed by Steam.
![fix](https://user-images.githubusercontent.com/3357792/49343714-d2e72800-f66e-11e8-99bb-b12d38cd835a.png)

**Comment by Joshua-Ashton** [comment]
Although this seems a bit hacky, perhaps an _STEAM variant of the env var would suffice, and anything that sets the main env var would override it 😄

**Comment by AccountOneOff** [comment]
This also affects DXVK_CONFIG_FILE. https://old.reddit.com/r/wine_gaming/comments/ahpz04/dxvklutris_winesteam_issues/
