### ISSUE TITLE
Game title change resetting

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1387]
Installed Rocket League through winesteam to test Alpha Console, changed the duplicate to "Rocket League Winesteam", removed it, and now the native one is named that. I remove "Winesteam" from it, save, close Lutris, relaunch, and "Winesteam" gets added back.

Deleted all Rocket League yaml files in `~/.config/lutris/games/`

![screenshot from 2018-12-02 12-56-47](https://user-images.githubusercontent.com/15083452/49344949-da88db80-f632-11e8-9a54-79b0ba268d4e.png)

**Comment by AccountOneOff** [comment]
I tried again and this time "Winesteam" stayed removed.

**Comment by strycore** [comment]
Went through the same process and I couldn't even reproduce first part, closing.
