### ISSUE TITLE
VBA / VBAm Support

### ISSUE THREAD

**Issue by Zer0t3ch** [lutris/lutris#139]
Add VisualBoyAdvance (and/or it's successor, VBAm) to the supported runners.

I don't know enough about the codebase otherwise I'd do it myself.

**Comment by RobLoach** [comment]
There's also RetroArch coming over at https://github.com/lutris/lutris/issues/209 , which has support for VBA-M and VBA-Next (which has some libretro-specific optimizations). Recommend just closing this, and focusing efforts on the RetroArch support.

**Comment by strycore** [comment]
Leave this open so it reminds me to build this runner (we won't provide all libretro cores)
