### ISSUE TITLE
Esync + tkg

### ISSUE THREAD

**Issue by concatime** [lutris/lutris#1391]
From wiki:
> Use our `esync` or `tkg` wine versions (it's recommended to use latest versions)

Should I submit a PR to add `or 'tkg' in version` in
https://github.com/lutris/lutris/blob/5033bcfc916c7947888109ee4a97a10182854cb6/lutris/util/wine.py#L213
??

**Comment by Medath** [comment]
Looks like a performance improvement to me, so I guess you can do that. Make sure to submit your change to the `next` branch because that's where the development happens.

**Comment by strycore** [comment]
Merged
