### ISSUE TITLE
Add search to logwindow.py

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1395]
Instead of scrolling endlessly I want to be able to find errors fast with searching. Like ctrl+f in a browser.

**Comment by strycore** [comment]
you that's not shipping in the next release, right?

**Comment by AccountOneOff** [comment]
No, no I didn't. What is?

**Comment by strycore** [comment]
That's just a small test program I coded to get the GOG API working. Eventually, all the features in that file will be moved to the import games window (which *will* have search!)

**Comment by AccountOneOff** [comment]
I'm talking about https://github.com/lutris/lutris/blob/master/lutris/gui/logwindow.py which is called logdialog.py now I guess.

**Comment by strycore** [comment]
I totally misread that as gogwindow (because the request also made sense for it)

**Comment by strycore** [comment]
The PR implements the feature very nicely, it would be nice to add a search icon in the title bar because not everyone will know about the ctrl + f shortcut but the search itself is good now!
