### ISSUE TITLE
Add dgvoodoo2's D3D1-9 implementation as an option

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1400]
- Introduce a dgvodoo2 option in the Configuration menu
- Allow to choose from multiple versions, host them on Lutris servers
- Copy and replace Wine's `ddraw.dll`,`d3d8.dll` and `d3d9.dll` (also copy dgvoodoo2's `d3dimm.dll` for 3d support in DX1-7 games) if the option is activated, override with `WINEDLLOVERRIDES=`
- Force activate DXVK as Wined3d does not function correctly with dgvoodoo2
- Create dgVoodoo.conf file to disable dgvoodoo watermark by default, maybe provide an option to modify other dgvoodoo settings (through dgvoodoo's own tool?).

Code from DXVK option could be reused. May need to ask permission from Dege, the developer, since dgvoodoo2 is proprietary.

**Comment by strycore** [comment]
I need more time to test this. A lutris installer demonstrating a dgvoodoo2 setup would be VERY helpful!

**Comment by AccountOneOff** [comment]
Made one for Rocket League. Plays like shit though.

https://lutris.net/games/install/12232/view

https://lutris.net/games/?q=dgvoodoo&search-installers=on

**Comment by tannisroot** [comment]
LoL: https://lutris.net/games/league-of-legends/
The Sims: https://lutris.net/games/the-sims/

**Comment by legluondunet** [comment]
Hello @Strider, dgvoodoo2 does not work with all games and you have to set different config per game. For example if the game is a directx8 games it will not use the same dll override than a directx4-5-6-7- game.For this reasons doubt it will be a good idea to put dgvoodoo2 as a global option in Lutris interface. It will be better to let scripters to manage this addon in  game scripts. In final this feature will generate more issues by users than it will resolve, it's more secure to not implement this option in Lutris.

**Comment by strycore** [comment]
I agree, I don't really see how a dgvoodoo option would work anyway, except maybe maintaining an up to date version in the runtime.

**Comment by tannisroot** [comment]
> Hello @strycore, dgvoodoo2 does not work with all games and you need to set a different configuration per game. For example, if the game is a directx8 game, it will not use the same configuration as a directx4-5-6 game -7- ?, not the same dll override, requires other options if the game needs dgvoodo card emulation. For these reasons, I doubt it is a good idea to put dgvoodoo2 as a global option in the Lutris interface. It will be better to let the writers handle this addon in the in the game scripts. Ultimately this feature will generate more problems for users than it will solve, it is safer not to implement this option in Lutris and to close this feature request, a lot of complexity that can confuse users without any real gain in use.

I've implemented this without D3D8 since we should instead aim for d3d8to9 support

**Comment by odziom91** [comment]
I've tested dgVoodoo and it starts without problems, but how to edit dgVoodoo.conf? I found this file in ~/.local/share/lutris/runtime/dgvoodoo2/v2.64/ but editing does nothing. By default it should be in game catalog (exact with .exe file maybe) but it is not available here.

Thanks in advance!

**Comment by tannisroot** [comment]
The file must be copied to prefix' \AppData\Roaming\dgVoodoo\. We are yet to implement the functionality to do so automagically.

**Comment by odziom91** [comment]
@tannisroot thanks a lot! For me it works okay and for now is enough - it is not a big deal to copy config.
