### ISSUE TITLE
Lutris cannot add any dolphin games.

### ISSUE THREAD

**Issue by Nilot352** [lutris/lutris#1402]
Here is the output of `lutris -d` when adding games.

> DEBUG    2018-12-09 17:35:09,704 [http]:GET https://lutris.net/api/runtime
DEBUG    2018-12-09 17:35:10,897 [runtime]:Runtime winetricks is already up to date (locally updated on Tue 27 Nov 2018 04:28:37 AM GMT, remote created on Sun 25 Nov 2018 08:25:58 PM )
DEBUG    2018-12-09 17:35:10,897 [runtime]:Runtime steam is already up to date (locally updated on Thu 22 Nov 2018 02:24:31 PM GMT, remote created on Sat 03 Nov 2018 03:11:04 AM )
DEBUG    2018-12-09 17:35:10,897 [runtime]:Runtime lib64 is already up to date (locally updated on Thu 22 Nov 2018 02:23:59 PM GMT, remote created on Mon 08 Oct 2018 03:29:56 AM )
DEBUG    2018-12-09 17:35:10,897 [runtime]:Runtime lib32 is already up to date (locally updated on Thu 22 Nov 2018 02:23:57 PM GMT, remote created on Mon 08 Oct 2018 03:29:40 AM )
DEBUG    2018-12-09 17:35:10,897 [runtime]:Runtime p7zip is already up to date (locally updated on Thu 22 Nov 2018 01:18:28 PM GMT, remote created on Tue 25 Oct 2016 02:34:44 AM )
DEBUG    2018-12-09 17:35:10,899 [api]:Fetching game library
INFO     2018-12-09 17:35:11,195 [lutriswindow]:Setting up view for first run
DEBUG    2018-12-09 17:35:11,195 [lutriswindow]:Syncing 26 icons
DEBUG    2018-12-09 17:35:11,196 [resources]:Requesting missing icons from API for 15 games
DEBUG    2018-12-09 17:35:11,197 [http]:GET https://lutris.net/api/games
INFO     2018-12-09 17:35:12,421 [api]:Loaded 10 games from page 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/sidebar.py", line 194, in on_configure_runner
    RunnerConfigDialog(self.runner, parent=self.parent_window)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 497, in __init__
    self.build_tabs('runner')
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 40, in build_tabs
    self._build_system_tab(config_level)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_dialogs.py", line 248, in _build_system_tab
    self.system_box = SystemBox(self.lutris_config)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 621, in __init__
    self.generate_widgets('system')
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 89, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 178, in call_widget_generator
    self.generate_file_chooser(option, value)
  File "/usr/lib/python3/dist-packages/lutris/gui/config_boxes.py", line 361, in generate_file_chooser
    path = os.path.join(self.game.directory, path)
AttributeError: 'NoneType' object has no attribute 'directory'

**Comment by Medath** [comment]
What exactly have you tried to do? Can you tell us what to do to get that output?

**Comment by Nilot352** [comment]
Try to run lutris with -d option. Install the dolphin runner and then try tk configure it.

**Comment by strycore** [comment]
https://www.youtube.com/watch?v=X7iBakLOrjA

It is also possible to import the GOG library to Lutris but this is still a bit buggy.

**Comment by Medath** [comment]
Are you sure you posted this in the correct thread @strycore?

**Comment by strycore** [comment]
Ah thanks, I knew I posted that in the wrong ticket but couldn't find which :laughing:

**Comment by strycore** [comment]
fixed in a recent commit
