### ISSUE TITLE
Battlefield V doesnt open after new installation script

### ISSUE THREAD

**Issue by beyimanman** [lutris/lutris#1405]
Hi,
A few weeks ago i was able to install and run battlefield v and battlefield 1 trough the installation script for lutris but with the new scripte (released yesterday  (published one or two days ago) i can install Origin but the game doesnt start, with no error on debug and no aparently reason.
Plis can you upload the previous version of the bfv installation script?

**Comment by v3Monsta** [comment]
I can confirm that this is the same issue I am having, however I didn't use the install script for bf5. Instead I installed origin as a game in lutris and downloaded bf5 after. This method worked fine up until yesterday.

Lutris: 0.4.23
WIne: 4.0-rc1
Dxvk: 0.93

**Comment by strycore** [comment]
this is not related to the client, the script should be updated to 0.94 since this apparently fixes the issue.
