### ISSUE TITLE
Installer hangs if exe is not defined

### ISSUE THREAD

**Issue by ttpcodes** [lutris/lutris#1406]
When running the Stepmania installer a bit ago, the `exe` directive was placed under `game` in the YAML rather than serving as a top-level directive. Rather than warning about there being no exe or warning about a failing installation, Lutris hangs as it attempts to generate the completed installation menu. These are the logs outputted into a terminal:
```
INFO     2018-12-11 01:28:57,838 [lutriswindow]:Connected to lutris.net as ttpcodes
INFO     2018-12-11 01:28:58,102 [lutriswindow]:Installing /home/ttpcodes/Downloads/stepmania-5012.json
INFO     2018-12-11 01:29:02,140 [interpreter]:Downloading file 1 of 1
INFO     2018-12-11 01:29:16,363 [lutriswindow]:Setting up view for first run
INFO     2018-12-11 01:29:16,904 [api]:Loaded 2 games from page 1
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 38, in <lambda>
    GLib.idle_add(lambda: self.callback(result, error))
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 531, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 574, in _finish_install
    self._write_config()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 650, in _write_config
    config['game'].update(self.script['game'])
ValueError: dictionary update sequence element #0 has length 1; 2 is require
```
While this is partly the fault of a poorly written installer, it is also worth considering that this error should be handled in a better way than just the installer hanging.

**Comment by strycore** [comment]
The reason was probably not the exe being in the game section since this is supported and actually preferred. The stacktrace was enough to provide info for a fix, whatever the actual problem was.
