### ISSUE TITLE
Game count in main window does not resize well covering runner names

### ISSUE THREAD

**Issue by 7oxicshadow** [lutris/lutris#1407]
As per the title. The game count in the main window does not scale well when the runner pane is dragged to make the text fit.

Version 0.4.23

Note: I am running a slightly modified version of Lutris that uses my own custom runners but I have not changed anything in the UI code.

![image](https://user-images.githubusercontent.com/10350138/49833361-2bb27100-fd91-11e8-8c19-310a63f6e21b.png)

**Comment by strycore** [comment]
we don't have the game count anymore
