### ISSUE TITLE
[Patreon Goal] Integrate Origin updater

### ISSUE THREAD

**Issue by YamiYukiSenpai** [lutris/lutris#1409]
I tried both the using the WINEPREFIX method that was downloaded from the original repo and the one that came with Lutris.  Both didn't work.  Origin still thinks it's outdated.

**Comment by dafluf** [comment]
Saw the same thing. Decided to let Origin update itself rather than using the script and it worked in my case.

**Comment by strycore** [comment]
I used the recommended script (https://github.com/DrDoctor13/wine-origin-updater) and Origin updated without issue. We should integrate that into lutris itself.

**Comment by Medath** [comment]
#808 
The update script could be added to every installer (with the ondemand_command option) that utilizes Origin until a proper Origin runner is made.

**Comment by strycore** [comment]
this updater script is no longer needed
