### ISSUE TITLE
Lutris treats user-made DXVK folders as releases. Which causes error

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1412]
Deleted my "latest" folder from `~/.local/share/lutris/runtime/dxvk` because it was outdated which resulted in the following:

![screenshot from 2018-12-12 13-20-18](https://user-images.githubusercontent.com/15083452/50040468-c5c82280-fff8-11e8-8840-ad1732a149c5.png)

**Comment by tannisroot** [comment]
I can't reproduce this in 0.4.23.
Selecting user-made dxvk version does not result in any errors, tried both with a custom name and `latest`.

**Comment by strycore** [comment]
yes, this is correctly handled in next and shows an error message
