### ISSUE TITLE
Desura runners installs a binary in $(pwd)/bin/desura

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#142]
When installing the desura runner, it installs its desura binary in $(pwd)/bin/desura, i.e. if lutris is launched from the command line in e.g. /home/akien/Documents, the binary will end up in /home/akien/Documents/bin/desura.

Note that the same binary is also installed in ~/.local/share/lutris/runners/desura/bin/desura, which seems to be a more proper location.

**Comment by Xodetaetl** [comment]
Desura is dead, but still alive in our (PC) hearts... fixed !
