### ISSUE TITLE
Respect the specified architecture when creating a prefix

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1425]
If the installer has `arch:` specified as `win32` in the `game:` section, for example:
```
game:
  arch: win32
  exe: foo/bar.exe
  prefix: $GAMEDIR
```
but the task that creates the prefix does not specify `arch:`, then the command will create a 64 bit prefix, which will result in a failure after attempting to launch the game due to mismatching architecture.
What Lutris should do is inherit the value of `arch:` from the `game:` section when creating a prefix if it's not specified in the task, and do the same in case it's the other way around (`game:` section doesn't specify the architecture but the task to create a prefix does).

**Comment by strycore** [comment]
> do the same in case it's the other way around (game: section doesn't specify the architecture but the task to create a prefix does).

no.

**Comment by tannisroot** [comment]
> no.

ok, then I guess this should be fixed through validator
