### ISSUE TITLE
Overwatch: No Compatible Graphics Hardware Found

### ISSUE THREAD

**Issue by Alkaris** [lutris/lutris#1434]
So I went to start up Overwatch today in such a long time, I got the game fully updated, and I go to hit play and I'm then greeted with an error saying No Compatible Graphics Hardware found when starting Overwatch.

![shutter__2018-12-22__05_14_47_pm](https://user-images.githubusercontent.com/6682988/50371568-544a2e80-060d-11e9-9800-b4270ea2d46d.png)

I did recently just update my graphics drivers here on Linux Mint 19, and I have no issues when I run other games from Steam (Linux), and I have a compatible graphics card installed in my machine, I'm running an ASUS GTX 1070 OC Snow Edition, and running current latest available graphic drivers for my distribution 410.78.

```
$ inxi -Gx
Graphics:  Card: NVIDIA GP104 [GeForce GTX 1070] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.19.6 ) driver: nvidia Resolution: 1920x1080@119.98hz
           OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 version: 4.6.0 NVIDIA 410.78 Direct Render: Yes
```

I see that error is quite common on Windows just from a brief search on that error code, and it just basically has people saying to update your graphics drivers and such, which I already have. Not sure if the recent update to Blizzard's client app and Overwatch might of broken something for Lutris.

**Comment by RobLoach** [comment]
What does `vulkaninfo` give you?

**Comment by Alkaris** [comment]
just gives me this;

```
Vulkan Instance Version: 1.1.82

/build/vulkan-tools-WIuZIg/vulkan-tools-1.1.82.0+dfsg1/vulkaninfo/vulkaninfo.c:3339: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by tannisroot** [comment]
@Alkaris you have misconfigured vulkan/graphics drivers

**Comment by Alkaris** [comment]
@tannisroot It's not misconfigured, it worked just fine the last time when I last started up the game and hasn't been touched since.

**Comment by tannisroot** [comment]
@Alkaris vulkaninfo says it is. What's your distro and graphics card?

**Comment by Alkaris** [comment]
@tannisroot it's as exactly as I said in my first post of what graphics card I have if you read it. This is on Linux Mint 19 64-bit

**Comment by tannisroot** [comment]
@Alkaris I just have this message as a macro. 
Install nvidia-driver-415 to fix your issue.

**Comment by shanness** [comment]
In case this helps anyone, I'm on ubuntu 16.04, and this broke after a nvidia version upgrade.
my vulkaninfo was giving

```
$ vulkaninfo
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.73

ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD libGL.so.1 failed.
Cannot create Vulkan instance.
/build/vulkan-ZsgAIG/vulkan-1.1.73+dfsg/demos/vulkaninfo.c:812: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```
Installing `mesa-vulkan-drivers` (which wasn't installed) fixed it.
