### ISSUE TITLE
Import Games GOG: "Connect" changes to "Disconnect" even if log-in was aborted

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1437]
How to reproduce:
1. Open Import Games menu, select GOG
2. Click `Connect"
3. Close the log-in windows box that just appeared
Observed behavior: `Connect` button changes to `Disconnect`, pressing `Disconnect` bring up the same log-in window.
Expected behavior: `Connect` button should stay the same.

**Comment by strycore** [comment]
Confirmed that this now works as expected
