### ISSUE TITLE
Pressing "Import Games" in the GOG tab imports all games from Lutris.net

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1439]
How to reproduce:
1. Connect to GOG
2. Restart Lutris
3. Press "Import Games" without selecting any from the list.
Observed behavior: Lutris starts fetching data for a bunch of games
Expected behavior: do not import all the games from lutris.net? Maybe grey out the button if no games are selected.

**Comment by Medath** [comment]
I think the best behavior when clicking Import without selecting a game would be to just import all owned gog games (as if you selected every game in the list).

**Comment by tannisroot** [comment]
But that wouldn't be very obvious to the user, there is very little connection between these actions.
If you want the import to default to importing all games, Lutris should introduce select all checkbox and select it by default, allowing user to unselect it and only choose games they want to import.

**Comment by Medath** [comment]
That might be a better idea, yes.

**Comment by Medath** [comment]
Small addition: This also happens when sync at startup is enabled.
