### ISSUE TITLE
Use steamcmd to download steam games

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#144]
Rather than using WineSteam to download game contents, we might be able to use [Steam AppManifest Generator](https://github.com/dotfloat/steam-appmanifest) to build a manifest file for us to trick Steam for Linux to download the Windows games.

Are we already doing something like this? Could we leverage that Python code?

**Comment by neuromancer** [comment]
You can use [steamcmd](https://developer.valvesoftware.com/wiki/SteamCMD) to download and manage games using the command line. You can even force the download of games from another platform (e.g., win32)

**Comment by strycore** [comment]
@neuromancer yes, steamcmd is a very interesting option and we should look into that as it could serve as a steam runner we can ship and use to download steam games without requiring the steam client.

**Comment by strycore** [comment]
So I've toyed with Steamcmd a bit and while it's a good tool to download games, the whole authentication process  (with SteamGuard and all) would be quite complicated to handle in Lutris (requiring the use of Pexpect or something similar). Meanwhile, I've implemented monitoring of installation of steam games during the install process in steam which works with Steam for Linux, Wine Steam and Steam data games. This finally allows to run extra installation steps after a steam game has been installed, which was a really important missing feature. The only missing part would be showing progress of the game installation but the appmanifest doesn't update itself until the game has finished installing so we can't use the BytesToDownload / BytesDownloaded info. We could calculate the folder size of SteamApps/downloading/[appid] every x seconds and compare it to BytesToDownload.

**Comment by newroser** [comment]
Thanks for your suggestions

**Comment by TheFloatingBrain** [comment]
Hey its been 6 years, can I bring this up again? I am running steamcmd in an OCI container with podman and the nvidia-container-runtime, I would love to have a GUI since Steam regular GUI is giving me a hard time and Bottle's Steam running with WINE crashes
