### ISSUE TITLE
Indicate that search box is for searching in "Import Games", improve the looks and add "select all"

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1440]
Currenly the search box in Import games is empty and gives no indication to the user that it is meant for search. To fix that, "Search" text should be displayed by default.
Also, they way it looks now is pretty ugly. I think it should be made a little narrower and a "select all" box added.
How it currently looks:
![screenshot from 2018-12-22 17-22-24](https://user-images.githubusercontent.com/10602045/50375506-6c22b200-060f-11e9-8391-146309d4cb54.png)
How (I think) it should look, very messy draft of that:
![screenshot from 2018-12-22 17-22-2465654654](https://user-images.githubusercontent.com/10602045/50375658-287d7780-0612-11e9-8120-1b6330e11d5f.png)

**Comment by strycore** [comment]
Fixed
