### ISSUE TITLE
List of games is not shown after logging-in to GOG

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1441]
How to reproduce:
1. Open "Import Games", select GOG tab
2. Successfully log-in.

Observed behavior: Get this screen:
![image](https://user-images.githubusercontent.com/10602045/50375725-56af8700-0613-11e9-9837-97b96ef17c8c.png)

Expected behavior: Get **this** screen:
![screenshot from 2018-12-22 17-40-36](https://user-images.githubusercontent.com/10602045/50375721-40093000-0613-11e9-9392-20b78848d0be.png)

**Comment by AlexanderRavenheart** [comment]
Also, where is the disconnect button after switching to the list of games to import?

**Comment by AlexanderRavenheart** [comment]
I think we can group issues together if they belong to the same window/dialog/feature and is spotted by the same user so that we don't over populate the tracker with lots of small issues and avoid many small PRs.

**Comment by strycore** [comment]
Fixed
