### ISSUE TITLE
Do not show "rom directory" if Wine runner is used (next)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1442]
I don't think it should be showed in configuration if Wine runner is used, looks kind of out of place:
![peek 2018-12-22 18-14](https://user-images.githubusercontent.com/10602045/50375917-54026100-0616-11e9-8447-ed89dc4d22b0.gif)

**Comment by duhow** [comment]
What version of Lutris are you running?

**Comment by tannisroot** [comment]
You need to use `next` branch, which is Lutris 0.5.
