### ISSUE TITLE
Improve UI of configuration menu (next)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1443]
I think the input boxes should be much wider, and banner should have description too, maybe moved back to where it was in 0.4.23.
Next:
![screenshot from 2018-12-22 18-15-41](https://user-images.githubusercontent.com/10602045/50375997-721c9100-0617-11e9-8a0d-6eb3616c1482.png)
0.4.23:
![image](https://user-images.githubusercontent.com/10602045/50376000-82cd0700-0617-11e9-8f78-58a545f260e2.png)

**Comment by TingPing** [comment]
This is the HIG for dialgos like that:

![](https://developer.gnome.org/hig/stable/figures/label-alignment.svg)
![](https://developer.gnome.org/hig/stable/figures/visual-alignment-spacing.svg)

So the left labels should be right aligned and take up the same amount of space.

**Comment by strycore** [comment]
@TingPing thanks for the input, I've right aligned the labels and adjusted the margins to align to the recommendations
