### ISSUE TITLE
Center text descriptions properly

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1444]
Currently, the text descriptions of input boxes in `next` are aligned to the upper left:
![image](https://user-images.githubusercontent.com/10602045/50376123-e7896100-0619-11e9-8895-73d1075d8bf7.png)
In 0.4.23, text descriptions are aligned to middle left:
![screenshot from 2018-12-22 18-45-12](https://user-images.githubusercontent.com/10602045/50376130-fa9c3100-0619-11e9-9360-3239789380da.png)
This change should be reverted as the upper right aliment looks worse and probably goes against Gnome HID.

**Comment by strycore** [comment]
fixed
