### ISSUE TITLE
[Wine Steam] Far Cry 2 immediately quits

### ISSUE THREAD

**Issue by lukas-wolf** [lutris/lutris#1450]
I'm having this issue where i try to start Far Cry 2 (installed on Wine Steam) and the Game closes after displaying the window for under 1 second. This is always happening, it doesn't make a difference if i try starting from the Lutris window, from Wine Steam or directly with the desktop icon. 
I already tried fixing dependency errors (https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/) and disabling the Lutris runtime. 
I've added the terminal output of Lutris when trying to start the game. If you need any logs or any other information, just tell me and i'll post it. 

`DEBUG    2018-12-23 21:41:16,939 [http]:GET https://lutris.net/api/runtime
DEBUG    2018-12-23 21:41:17,213 [runtime]:Runtime x360ce is already up to date (locally updated on So 23 Dez 2018 17:32:48 GMT, remote created on Sa 15 Dez 2018 11:33:12 )
DEBUG    2018-12-23 21:41:17,214 [runtime]:Runtime dumbxinputemu is already up to date (locally updated on So 23 Dez 2018 17:32:56 GMT, remote created on Sa 15 Dez 2018 11:32:50 )
DEBUG    2018-12-23 21:41:17,215 [runtime]:Runtime gamecontrollerdb is already up to date (locally updated on So 23 Dez 2018 17:32:53 GMT, remote created on Sa 15 Dez 2018 09:35:14 )
DEBUG    2018-12-23 21:41:17,215 [runtime]:Runtime winetricks is already up to date (locally updated on So 23 Dez 2018 17:32:49 GMT, remote created on So 25 Nov 2018 20:25:58 )
DEBUG    2018-12-23 21:41:17,216 [runtime]:Runtime steam is already up to date (locally updated on So 23 Dez 2018 17:47:15 GMT, remote created on Sa 03 Nov 2018 03:11:04 )
DEBUG    2018-12-23 21:41:17,216 [runtime]:Runtime lib64 is already up to date (locally updated on So 23 Dez 2018 17:43:37 GMT, remote created on Mo 08 Okt 2018 03:29:56 )
DEBUG    2018-12-23 21:41:17,217 [runtime]:Runtime lib32 is already up to date (locally updated on So 23 Dez 2018 17:41:06 GMT, remote created on Mo 08 Okt 2018 03:29:40 )
DEBUG    2018-12-23 21:41:17,217 [runtime]:Runtime p7zip is already up to date (locally updated on So 23 Dez 2018 17:32:43 GMT, remote created on Di 25 Okt 2016 02:34:44 )
DEBUG    2018-12-23 21:41:17,221 [api]:Fetching game library
DEBUG    2018-12-23 21:41:17,351 [steam]:Watching Steam folder /home/lw/.local/share/Steam/steamapps
DEBUG    2018-12-23 21:41:17,351 [steam]:Watching Steam folder /home/lw/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps
INFO     2018-12-23 21:41:17,443 [lutriswindow]:Setting up view for first run
DEBUG    2018-12-23 21:41:17,444 [lutriswindow]:Syncing 2 icons
DEBUG    2018-12-23 21:41:17,444 [resources]:No icon are missing
INFO     2018-12-23 21:41:22,141 [runner]:Runtime disabled by system configuration
DEBUG    2018-12-23 21:41:22,206 [wineprefix]:Virtual desktop: None
DEBUG    2018-12-23 21:41:22,218 [system]:Executing pgrep Steam.exe$
INFO     2018-12-23 21:41:22,245 [runner]:Runtime disabled by system configuration
DEBUG    2018-12-23 21:41:22,245 [game]:Launching Far Cry 2: {'env': {'DRI_PRIME': '0', 'WINEDEBUG': '-all', 'WINEARCH': 'win32', 'WINE': '/home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine', 'WINEPREFIX': '/home/lw/.local/share/lutris/runners/winesteam/prefix', 'WINEESYNC': '0'}, 'command': ['/home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine', '/home/lw/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe', '-no-cef-sandbox', '-console', 'steam://rungameid/19900']}
DEBUG    2018-12-23 21:41:22,246 [thread]:Command env: SDL_VIDEO_FULLSCREEN_DISPLAY="off" DRI_PRIME="0" WINEDEBUG="-all" WINEARCH="win32" WINE="/home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine" WINEPREFIX="/home/lw/.local/share/lutris/runners/winesteam/prefix" WINEESYNC="0" 
DEBUG    2018-12-23 21:41:22,246 [thread]:Running command: "/home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine" "/home/lw/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe" "-no-cef-sandbox" "-console" "steam://rungameid/19900"
DEBUG    2018-12-23 21:41:22,246 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to off
DEBUG    2018-12-23 21:41:22,246 [thread]:Storing environment variable DRI_PRIME to 0
DEBUG    2018-12-23 21:41:22,246 [thread]:Storing environment variable WINEDEBUG to -all
DEBUG    2018-12-23 21:41:22,247 [thread]:Storing environment variable WINEARCH to win32
DEBUG    2018-12-23 21:41:22,247 [thread]:Storing environment variable WINE to /home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wine
DEBUG    2018-12-23 21:41:22,247 [thread]:Storing environment variable WINEPREFIX to /home/lw/.local/share/lutris/runners/winesteam/prefix
DEBUG    2018-12-23 21:41:22,247 [thread]:Storing environment variable WINEESYNC to 0
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
DEBUG    2018-12-23 21:41:24,334 [thread]:Start process monitoring
DEBUG    2018-12-23 21:41:24,334 [thread]:Processes excluded: Steam.exe (4952:S), Steam.exe (4952:S), PnkBstrA.exe (4977:S), wineserver (4955:S)
DEBUG    2018-12-23 21:41:24,334 [thread]:Processes monitored: PnkBstrB.exe (4982:S)
wine: Fehlerhaftes EXE-Format für Z:\home\lw\.local\share\lutris\runners\winesteam\prefix64\drive_c\Program Files (x86)\Steam\bin\gldriverquery64.exe.
DEBUG    2018-12-23 21:41:52,369 [thread]:Processes excluded: Steam.exe (4952:S), Steam.exe (4952:R), PnkBstrA.exe (4977:S), wineserver (4955:S)
DEBUG    2018-12-23 21:41:54,365 [thread]:Processes excluded: Steam.exe (4952:S), Steam.exe (4952:S), PnkBstrA.exe (4977:S), wineserver (4955:S)
DEBUG    2018-12-23 21:41:58,358 [thread]:Processes monitored: FarCry2.exe (5140:R), PnkBstrB.exe (4982:S)
DEBUG    2018-12-23 21:42:00,340 [thread]:Processes excluded: Steam.exe (4952:S), Steam.exe (4952:S), PnkBstrA.exe (4977:S), wineserver (4955:R)
This platform has logs enabled.  Don't use it for shipping.
This platform has traces enabled.  Don't use it for shipping.
(Info) Tracking create with access key = Sas85%$5
DEBUG    2018-12-23 21:42:02,346 [thread]:Processes excluded: Steam.exe (4952:S), Steam.exe (4952:S), PnkBstrA.exe (4977:S), wineserver (4955:S)
(Info) Tracking::Initialize without address, port, service Id
(Warning) OnlineConfigClient module not initialized

> **This is the moment the window closes**

DEBUG    2018-12-23 21:42:04,374 [thread]:Processes monitored: PnkBstrB.exe (4982:S)
DEBUG    2018-12-23 21:42:10,211 [thread]:Detaching logger
DEBUG    2018-12-23 21:42:10,213 [winesteam]:Game configured to stop Steam on exit
DEBUG    2018-12-23 21:42:10,214 [winesteam]:Stopping all winesteam processes
INFO     2018-12-23 21:42:10,214 [runner]:Runtime disabled by system configuration
DEBUG    2018-12-23 21:42:10,332 [wine]:Killing all wine processes: ['/home/lw/.local/share/lutris/runners/wine/esync-staging-pba-3.18-x86_64/bin/wineserver', '-k']
DEBUG    2018-12-23 21:42:10,333 [wine]:	Wine prefix: /home/lw/.local/share/lutris/runners/winesteam/prefix
DEBUG    2018-12-23 21:42:10,333 [wine]:	Wine arch: win32
DEBUG    2018-12-23 21:42:10,333 [wine]:	Initial pids: {'4987', '4952', '4961', '4977', '4972', '4955', '4964', '4993', '4982'}
DEBUG    2018-12-23 21:42:10,357 [thread]:Processes excluded: Steam.exe (4952:Z), Steam.exe (4952:Z), wineserver (4955:R)
DEBUG    2018-12-23 21:42:10,357 [thread]:Processes monitored: None (5724:None), None (4987:None), None (4961:None), None (4977:None), None (4972:None), None (4964:None), None (4993:None), None (4982:None)
DEBUG    2018-12-23 21:42:10,387 [wine]:Waiting for wine processes to terminate
DEBUG    2018-12-23 21:42:12,340 [thread]:Processes excluded: Steam.exe (4952:Z)
DEBUG    2018-12-23 21:42:12,340 [thread]:Processes monitored: none
WARNING  2018-12-23 21:42:12,399 [wine]:Some wine processes are still running: 4952
DEBUG    2018-12-23 21:42:12,400 [thread]:Restoring environment
DEBUG    2018-12-23 21:42:12,400 [thread]:Killing all remaining processes
DEBUG    2018-12-23 21:42:12,477 [thread]:Killed processes: Steam.exe (4952:Z)
DEBUG    2018-12-23 21:42:14,264 [game]:Game thread stopped
DEBUG    2018-12-23 21:42:14,265 [game]:Far Cry 2 stopped at So, 23 Dez 2018 21:42:14
ERROR    2018-12-23 21:42:14,289 [thread]:Game is not running
INFO     2018-12-23 21:42:17,899 [application]:Shutting down Lutris
INFO     2018-12-23 21:42:17,906 [application]:Shutting down Lutris
`

**Comment by EsdrasTarsis** [comment]
Run this game on Steam Play Proton

**Comment by lukas-wolf** [comment]
Oh, that's working. I didn't even think of using Proton, thanks for the tip.

**Comment by EsdrasTarsis** [comment]
Now you can close this issue, good game!
