### ISSUE TITLE
0.5.0-beta Namespace GnomeDesktop not available on Xubuntu 18.04

### ISSUE THREAD

**Issue by Alexmitter** [lutris/lutris#1454]
#915 did not help me in this context.
Running the /bin/lutris from the 0.5.0-beta result in this:

Traceback (most recent call last):
  File "./bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/tmp/lutris-0.5.0-beta/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available

**Comment by EsdrasTarsis** [comment]
I just managed to run Lutris 0.5.0 on Gnome Desktop

**Comment by DarkJarris** [comment]
adding a Me Too, Ubuntu MATE 18.0401

```
Traceback (most recent call last):
  File "./lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/home/jarris/Downloads/lutris-0.5.0-beta/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```

**Comment by jamon** [comment]
try this:
```
sudo apt install gir1.2-gnomedesktop-3.0 gir1.2-webkit2-4.0
```
worked for me on debian/plasma

**Comment by EsdrasTarsis** [comment]
Thanks @jamon

**Comment by strycore** [comment]
install the dependencies listed by @jamon 
when in doubt look up the dependency list in debian/control

**Comment by daniel-j** [comment]
For Arch the package name is `gnome-desktop`

**Comment by strycore** [comment]
no it's not

**Comment by strycore** [comment]
wait

**Comment by strycore** [comment]
I remember there was something fucky about Arch

**Comment by strycore** [comment]
does the gnome-desktop package provide the GIR binding for gnomedesktop?

**Comment by alexws54tk** [comment]
Same issue on Gentoo Plasma 5.14.5

**Comment by scottchiefbaker** [comment]
Still running in to this issue on Plasma, is there a fix for this?

**Comment by strycore** [comment]
Please install Lutris with the official pacages.

**Comment by alexws54tk** [comment]
@strycore 
> Please install Lutris with the official packages.

I just emerge `lurtis-9999` [ebuild](https://packages.gentoo.org/packages/games-util/lutris) from Gentoo repo, and I not use Gnome on my PC.

**Comment by strycore** [comment]
Yeah, that was before I realized the Gentoo ebuild is outdated.

This is what I wrote on another ticket: 
This ebuild is outdated, please update it with the latest dependencies. You can find them in debian/control in the sources of the project. (In this case you'll need the Python GObject bindings for GnomeDesktop and Webkit2, and also install the python3 packages Pillow and requests)

I'm not sure there's a current maintainer for Gentoo, the package page says the last maintainer retired in 2018 so I'm not sure how to get the ebuild updated, maybe you can ask around in the Gentoo community.
