### ISSUE TITLE
esync's how to doesn't work on fedora 29

### ISSUE THREAD

**Issue by v21cesc** [lutris/lutris#1462]
I've added the line 
DefaultLimitNOFILE=1048576('#' removed) in both 
/etc/systemd/user.conf 
and 
/etc/systemd/system.conf. 

Also, I've add 
* soft nofile 1048576
* hard nofile 1048576
in /etc/security/limits.conf

After running systemctl daemon-reexec, 
the command ulimit -Hn still returns 262144 rather than 1048576.
Anyone could help?

Distro: Fedora 29 
kernel :4.19.10-300

**Comment by tannisroot** [comment]
Can you take a look at "A note about RHEL/CentOS/Fedora/Scientific Linux users" section here? https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by v21cesc** [comment]
cat /proc/sys/fs/file-max returns  810474
I changed the value fs.file-max to 1048576 in /etc/sysctl.conf but it got back to 810474 after rebooting.
Also, I tried to add session required pam_limits.so in /etc/pam.d/login. It doesn't help anything either.

**Comment by truboxl** [comment]
Hi, I also have this issue. I have followed the instructions from
https://github.com/lutris/lutris/wiki/How-to:-Esync
https://github.com/zfigura/wine/blob/esync/README.esync

For some weird reason, I get `262144` from `ulimit -Hn` from `gnome-terminal` instead of `1048576`
but I can get it through `tty` and `xterm`
Something definitely bugged `gnome-terminal`

**Comment by truboxl** [comment]
Relevant bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1628297

**Comment by v21cesc** [comment]
> Relevant bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1628297

Alright, the new version of howto change the nofile value to 524288. Now the gnome-terminal can correctly output this value.
BUT, Lutris still returns "Your limits are not set correctly" and the esync's switch box still cannot be checked or saved :-P

**Comment by Medath** [comment]
Lutris 0.4.23 still requires the old limit of 1048576. The next release will only require a limit of 524288.

**Comment by v21cesc** [comment]
> Lutris 0.4.23 still requires the old limit of 1048576. The next release will only require a limit of 524288.

Thanks, this issue can be closed now
