### ISSUE TITLE
Excessive space before options

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1468]
IMO this is way too much:
![screenshot from 2019-01-03 02-41-37](https://user-images.githubusercontent.com/10602045/50618016-362fd880-0f01-11e9-8d88-4859dd8984ff.png)

![screenshot from 2019-01-03 02-41-30](https://user-images.githubusercontent.com/10602045/50618009-3203bb00-0f01-11e9-9d31-c82d8f5af63e.png)

**Comment by strycore** [comment]
Fixed that in a previous commit

**Comment by tannisroot** [comment]
What commit? It's still present in `next`.

**Comment by strycore** [comment]
it's good now

**Comment by tannisroot** [comment]
This still looks like an ugly mess though.

**Comment by strycore** [comment]
I'm starting to wonder if we should right align the labels. Most config dialogs use left aligned labels. 
![screenshot from 2019-01-07 18-21-03](https://user-images.githubusercontent.com/280336/50805843-0c800400-12a9-11e9-846c-263b34998b49.png)

**Comment by tannisroot** [comment]
That actually looks much nicer IMO.

**Comment by tannisroot** [comment]
This does look quite better.
Also, in the examples you showed toggles are right allighed. Maybe Lutris should do the same.
![image](https://user-images.githubusercontent.com/10602045/50806262-eee18780-1306-11e9-8fe3-2a413507f333.png)
![image](https://user-images.githubusercontent.com/10602045/50806268-f86aef80-1306-11e9-8b9e-118add8d871e.png)
