### ISSUE TITLE
The space between lines is too small in installation window

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1477]
It used to look like this:
![image](https://user-images.githubusercontent.com/10602045/50624297-d56bc480-0f2f-11e9-84e2-14bf86130e4c.png)
But now, it looks like this:
![image](https://user-images.githubusercontent.com/10602045/50624300-e74d6780-0f2f-11e9-9c75-a89d97ab66e5.png)
It obviously looks quite uglier and should probably get changed.

**Comment by AlexanderRavenheart** [comment]
Spacing between lines should be 6 pixels, not whatever ridiculous amount was there before. I agree with the changes.

**Comment by tannisroot** [comment]
Agree. I think the current spacing is a nice compromise. 6 imo was too little.
