### ISSUE TITLE
"Install" button has non-standard font color and size

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1478]
It's different compared to other buttons and looks pretty bad with Adwaita theme:
![image](https://user-images.githubusercontent.com/10602045/50624573-b6bafd00-0f32-11e9-8537-79a96dd9d9d3.png)

**Comment by tannisroot** [comment]
It seems that @strycore hardcoded it from his system theme: 
![image](https://user-images.githubusercontent.com/10602045/50624702-c5ee7a80-0f33-11e9-8233-ec79d5a0c625.png)

**Comment by strycore** [comment]
this is a standard Gtk ListBox widget, I made no other customization than removing the orange background.

**Comment by tannisroot** [comment]
Weird, now it looks fine: 
![image](https://user-images.githubusercontent.com/10602045/50715900-40341180-1090-11e9-8ccf-0c3e50634ec9.png)

**Comment by strycore** [comment]
The background change must have fixed it
