### ISSUE TITLE
Wasted space in installer window when showing description

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1480]
A lot of space that could be use to show the installer description is wasted (between cancel/continue button and the description):
![image](https://user-images.githubusercontent.com/10602045/50624652-6001f300-0f33-11e9-9247-0536fe476e34.png)

**Comment by strycore** [comment]
This is as intended

**Comment by strycore** [comment]
Because the labels have a fixed width, look at the other tabs

**Comment by AlexanderRavenheart** [comment]
This is not about the width, it's about the height. There is too much empty space between the Install panel and the separator line that could very well be used to show more of the installer text displayed in the scrollable area.

**Comment by strycore** [comment]
This is not how GTK works

**Comment by strycore** [comment]
If you click the installer section to display the notes, the window will grow as well
