### ISSUE TITLE
Replace 5-star system in installer windows with Wine rating system

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1481]
There seems to be an irregularity between the website and client (next).
On the website, Wine rating system is used (garbage, bronze, silver, gold, platinum):
![image](https://user-images.githubusercontent.com/10602045/50624803-7f4d5000-0f34-11e9-892b-10cc346e6172.png)
In the new client, 5-star rating system is used:
![image](https://user-images.githubusercontent.com/10602045/50624807-8e340280-0f34-11e9-8d93-f8e45433c607.png)
The problem is that these the former does to translate well to the latter. An installer with `Gold` rating can work just fine but require certain tricks which are automated by the installer, but in the client it will show up as 4 star installer, which is not accurate.

**Comment by strycore** [comment]
We're getting rid of the wine rating system, it doesn't make sense in the lutris context.

**Comment by tannisroot** [comment]
Ok. Then when the transition happens, I highly suggest to convert Gold ratings to 5 stars.

**Comment by strycore** [comment]
No, that's platinum
