### ISSUE TITLE
Introduce "Enable SteamPlay" option to native Steam installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1482]
Currently, Lutris has install Windows games through Native Steam, as they are technically treated as native games, and many installers utilize that. However, there are ones that do this for non-whitlisted games, and these will fail unless the user manually enables SteamPlay for unsupported titles (it's off by default).
I suggest to introduce a feature that will automatically enable SteamPlay for all unsupported titles if the installer requests that. For example:
```
game:
  appid: 47890
system:
 enable_steamplay: true
```
When it comes to how to actually change the value of "Enable Steam Play for all titles"  I observed the behavior of Steam when changing its SteamPlay settings, and it's actually pretty easy to do. Lutris will just need to modify `~/.local/share/Steam/config/config.vdf` file, and in it, change around this section:
```
	"Tools"
				{
					"enable"		"1"
				}
				"ToolMapping"
				{
					"0"
					{
						"name"		""
						"config"		""
						"Priority"		"75"
					}
				}
				"SurveyID"		"4b37d46b3068e920"
				"NCTF"		"1"

```
Apparently, there is no separate variable for "Enable Steam Play for all titles", you can just insert a valid proton version as a value of `"name"`, for example:
```
						"name"		"proton_316"
```
Which will check ""Enable Steam Play for all titles" option and set Proton 3.16-4 as the version for them.
Other valid values are: `proton_37` `proton_37_beta` and `proton_316_beta`.
But I think it would be best to set `proton_316` as a default version, since Proton 3.7 does not work as well as 3.16-4, and Beta 3.16 may get broken with updates.

**Comment by basxto** [comment]
Steam Client Beta now allows to enable proton on a per game basis, even for games who have a Linux repository.
Instead of `"0"` you just use the game’s ID.

**Comment by strycore** [comment]
I'd rather not depend on beta features, we can add support for that when the feature is in the stable client. I don't even know if there's a way to detect if the client is in beta (and it doesn't make sense to write code depending on that condition anyway)

Being able to enable Steam Play globally is a good workaround for the time being.

**Comment by basxto** [comment]
This is part of the stable client by now.

**Comment by strycore** [comment]
I am closing this issue for the following reasons:

* introduces a new installer directive while the change affects all games
* Writing Steam config files can be a dangerous operation

By doing read-only stuff we can detect that Steam play isn't enabled and show a message to the user.

**Comment by Devorlon** [comment]
@strycore So I'm trying to write a installer that would:

- Install the windows version of the game
- Download and extract files to the directory
- Run an exe
- Change files' names

Ideally the game would be installed under SteamLinux with SteamPlay enabled for the title, to make things convenient. But I'm assuming that since this issue has been closed I'd have to use WineSteam?
