### ISSUE TITLE
Larger Banners

### ISSUE THREAD

**Issue by marxjohnson** [lutris/lutris#149]
Steam's grid view uses banners ~460x215px, but in Lutris the banners are ~185x70px.  As I'm using it on a TV across the room, it would be nice to be able to have larger banners.

**Comment by dennisjj4** [comment]
This would be nice...and there is plenty of websites (i.e. http://steambanners.booru.org/) for finding banners for games. The problem with covers is what about true indie games (no retail disk version) or stand-alone games based on an open-sourced game engine (i.e. Harmony)? No covers were ever made for these, and I never seen fan-sites for making covers for games (mostly because physical copies of games are fast-going obsolete)

**Comment by telanus** [comment]
From the Above linked issue: 
> A larger banner size and the ability to use banners from sites like [SteamGridDB](https://www.steamgriddb.com/) and [Jinx's SGVI](https://steam.cryotank.net/) would go a long ways in making lutris look a bit more pretty.
> Gamehub does this with outstanding results
> ![image](https://user-images.githubusercontent.com/52518103/62011179-8e972380-b13a-11e9-8fb0-71f20bed9356.png)
> Compared to lutris:
> ![image](https://user-images.githubusercontent.com/52518103/62011212-d5851900-b13a-11e9-8b3c-87b09b8faffe.png)

**Comment by telanus** [comment]
From the above issue:

> **Description**
> 
> On high DPI displays, the game artwork in the library view is very blurry.
> 
> **Expected behavior**
> 
> The image is scaled properly and rendered at native resolution.
> 
> **Current behavior**
> 
> It appears the image is scaled to half the proper resolution, and then scaled back _up_ before being displayed.
> 
> **Steps to reproduce**
> 
>     * Set up your desktop with a 2x scaling factor.
> 
>     * Install a game.
> 
>     * Look at the header image.
> 
> 
> **Screenshots**
> 
> The Okami HD header image, downscaled to match the Lutris display size (this is how it should look):
> 
> ![okami-header_368linear](https://user-images.githubusercontent.com/43831298/60368869-fb928e80-99bf-11e9-8fe4-73c3600a40e5.png)
> 
> The image as displayed by Lutris:
> 
> ![Screenshot from 2019-06-28 14 26 50@2x_headercrop](https://user-images.githubusercontent.com/43831298/60368894-0a794100-99c0-11e9-90ba-4d71a9f01e1c.png)
> 
> And the image scaled down to half the proper resolution, then back up (using linear interpolation):
> 
> ![okami-header_368downup](https://user-images.githubusercontent.com/43831298/60368955-2c72c380-99c0-11e9-9f38-19c1f312b20b.png)

**Comment by barolo** [comment]
Also, for the love of everything that's decent use Steam's standard sizes

**Comment by strycore** [comment]
![Screenshot from 2020-10-07 21-20-00](https://user-images.githubusercontent.com/280336/95414699-4ef1cd00-08e3-11eb-9de3-6a7aaa450776.png)

![Screenshot from 2020-10-07 21-20-45](https://user-images.githubusercontent.com/280336/95414713-531dea80-08e3-11eb-9cb5-fa1214c60ed5.png)

This is now implemented

**Comment by barolo** [comment]
@strycore is this only for GOG. Steam? my local stuff still has smaller ones and it doesn't seems to be possible to change that.
Also, disabled/not installed games look horrid with dark themes

**Comment by N0tJust1n** [comment]
@strycore As @barolo pointed out over a year ago this is still an issue with manually added games.

**Comment by ppwwyyxx** [comment]
Same, I'm still unable to use larger banners for games I manually added. After selecting a banner, it gets downscaled automatically. Using lutris 0.5.10 beta.

**Comment by barolo** [comment]
> Same, I'm still unable to use larger banners for games I manually added. After selecting a banner, it gets downscaled automatically. Using lutris 0.5.10 beta.

Someone needs to open a new issue, otherwise it will get no attention.
