### ISSUE TITLE
Inconsistent spacing between options in 'Configuration"

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1496]
Observed in Lutris Beta 2.
I will use this portion of configuration menu as an example, but please note that this occurs throughout whole configuration menu:
![screenshot from 2019-01-05 00-18-42](https://user-images.githubusercontent.com/10602045/50712226-c006af80-1081-11e9-935f-c0de3446edce.png)

**Comment by tannisroot** [comment]
Personally, I think bigger spacing between options is more appealing.

**Comment by TingPing** [comment]
6 is the recommended spacing between elements and 18 between sections:

![](https://developer.gnome.org/hig/stable/figures/visual-alignment-spacing.svg)

**Comment by strycore** [comment]
This is caused by the labels going over 2 lines, I've reduced this by increasing the label width but it still happens in some case an cannot really be avoided.
