### ISSUE TITLE
Can't kill native games

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1497]
Observed in Lutris Beta 2.
Reproduction:
1. Install SuperTuxKart from Flathub using Flatpak: https://flathub.org/apps/details/net.supertuxkart.SuperTuxKart
2. Open Import Games menu, select the Tux icon for native games.
3. Select SuperTuxKart, click 'Import Games".
4. Select SuperTuxKart, click "Play".
5. When the game opens, press "Stop" button.
Observed behavior: "Stop" button does nothing and the game window is still opened and running.
Expected behavior: "Stop" button should kill the game.

Note that Wine games are unaffected by this.

**Comment by AsciiWolf** [comment]
Is this happening only when using Flatpak'ed games?

**Comment by tannisroot** [comment]
I am pretty sure it will affect all non-wine games.

**Comment by strycore** [comment]
@AaronOpfer can you have a look at this and see if there's anything we can do about it? in such cases the game is started by Flatpak and not by the lutris wrapper so when killing the game, only the wrapper script gets killed. Would there be a way to attach external processes to the monitor?

**Comment by strycore** [comment]
uh, there may be a problem with the current code, I know I had the stop button working yesterday but now it's not killing anything

**Comment by AaronOpfer** [comment]
Hmm... I haven't tested anything, but this is probably caused by the fact I
changed the monitor to avoid killing any "excluded" processes as a way to
avoid killing the wineserver. If the game itself is counted as an excluded
process we'd never kill it.

**Comment by AaronOpfer** [comment]
Looks like it was introduced here: 2945e1198319e8516b2ceb15ba39dbdd82f60aa8 sending `SIGKILL` to the wrapper process will prevent it from executing its signal handler which cleans up the correct processes.

**Comment by strycore** [comment]
SuperTuxKart is killed correctly now
