### ISSUE TITLE
Battle.Net agent goes "to sleep" because of fontconfig errors

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1498]
Observed in Lutris Beta 2
Reproduction:
1. Use Overwatch installer to install Battle.Net
2. After the installation has finished, launch Battle.Net and log in.
Observed behavior: Battle.Net shows a message about Agent going to sleep, terminal output is spammed with fontconfig erros
Expected behavior: Battle.Net launches normally, no fontconfig errors.

Note: removing libfontconfig.so.1 from both lib32 and lib64 resolves this, so Lutris should either remove that from runtime or update the library.

**Comment by strycore** [comment]
This should get fixed by updating the runtime to 18.04

**Comment by strycore** [comment]
Try with the tkg-4.0 build. This will use the 18.04 runtime and you shouldn't have the issues.
