### ISSUE TITLE
Do not duplicate "Connect" button

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1503]
Right now, if you are not logged in to GOG, you will see 2 connect buttons in the GOG import window that do the exact same thing. That is not really good UI, so one of them (the small one) should be removed, and should only be shown as a disconnect button once the user has logged in.
![image](https://user-images.githubusercontent.com/10602045/50722166-05f06180-10dc-11e9-950e-b46c8052a037.png)

**Comment by strycore** [comment]
I don't really see that as a big problem.

**Comment by tannisroot** [comment]
Ok, but it's still bad UI.

**Comment by strycore** [comment]
Not really, it's consistent at least.
