### ISSUE TITLE
[0.5-beta] Crashes on Run: ValueError: Namespace GnomeDesktop not available

### ISSUE THREAD

**Issue by joeknock90** [lutris/lutris#1505]
Arch Linux
KDE
Lutris git built from the AUR

`lutris -d` 

returns 

    Traceback (most recent call last):
    File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
    File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
    File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace GnomeDesktop not available

**Comment by strycore** [comment]
do NOT add the gnome-desktop package to the lutris package. this is the WRONG dependency

**Comment by joeknock90** [comment]
What is the dependency?

**Comment by strycore** [comment]
it's the one providing the GIR bindings for lignome-desktop

btw, I don't use arch

**Comment by strycore** [comment]
yeah, and I don't want the AUR maintainer to add that package if it's going the whole gnome desktop.

**Comment by strycore** [comment]
there is a difference between the gnome desktop and libgnome-desktop. For lutris, only the GObject Introspection files are needed.

**Comment by joeknock90** [comment]
https://www.archlinux.org/packages/extra/x86_64/gnome-desktop/

As the package says 

"Library with common API for various GNOME modules"

**Comment by joeknock90** [comment]
I will correct the AUR request for gobject-introspection.

**Comment by joeknock90** [comment]
Just adding gobject-introspection does not work on arch linux. The gnome-desktop package is required. 

As here, the arch linux package, the gnome-desktop package is not the full gnome desktop it is 

"Library with common API for various GNOME modules"

https://www.archlinux.org/packages/extra/x86_64/gnome-desktop/

**Comment by strycore** [comment]
Yes, the arch naming is confusing me. On other distros, gnome desktop installs the whole gnome desktop. This the correct dependency

**Comment by joeknock90** [comment]
That's arch Linux for you ¯\_(ツ)_/¯
