### ISSUE TITLE
Removal of a game that is missing an installation directory fails

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1511]
I needed to remove a Steam Wine game from Lutris to reproduce another bug, but I did not want to lose my installation files as the game is pretty big and I did not need to fully reinstall it, so I just renamed the game folder that is located in `~/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps/common` and tried to remove the game from Lutris library with both "Remove game data" and "Remove from my library" flags checked.
However, Lutris just froze for a while and failed to remove the game.
Log:
https://paste.ubuntu.com/p/pWYmFFHnrm/
I should note that it's a valid usercase since some user may want to delete game files to free up some space and than try to reinstall later (which will result running into this issue), and that the installer I used for the game creates a separate prefix for it (Steam installer for Sims 3 https://lutris.net/games/the-sims-3/).

**Comment by AlexanderRavenheart** [comment]
Why does it try to create a new prefix upon removing a game?
Also, what would you expect to happen if you check Remove game data option but already removed/moved the game data manually? Perhaps there should be a check to see if game data is still available and either disable or hide that option if data is missing.

**Comment by strycore** [comment]
It's not creating a prefix, that the issue. Lutris assumes that the prefix is still here and crashes because it has been removed. Lutris uses Steam to remove the game so it goes through the whole prelaunch step.

There is no need for the game removal to use the game specific prefix instead of the default one and doing so would provide a resolution to this bug.
