### ISSUE TITLE
Allow vertical boxarts to be used.

### ISSUE THREAD

**Issue by Nilot352** [lutris/lutris#1512]
Some games do not have grid boxarts; this will help in maintaining consistency.

**Comment by Nilot352** [comment]
[I meant boxarts like these](https://gonintendo.com/system/stories/promo_images/000/320/994/original/RONDO_FC_1024x1024_3b9ae297-38b9-4a96-a6dc-748ecba5befa_1024x1024.jpg?1540243218)

**Comment by tannisroot** [comment]
I am sure this can be cropped without making it look bad.
Inconsistent banner size will look like a mess.

**Comment by Nilot352** [comment]
Still it is nice to have options.

**Comment by Nilot352** [comment]
Besides the banner size will be incosistent even with grid boxarts since many games do not yet have them.

**Comment by AlexanderRavenheart** [comment]
It would really be cool to be able to use full sized box arts and not just have a custom sized banner.

**Comment by Merrit** [comment]
I would specifically like to have posters as an option. For a beautiful UI example see [GOG Galaxy 2.0](https://i.imgur.com/tXrWfZC.jpg)

**Comment by raulcraveiro** [comment]
I would love to see support for vertical covers too. Steam and Gog Galaxy 2.0 is doing this and looks SO beautiful.

It would be nice to see support for animated covers too ;)

**Comment by telanus** [comment]
@strycore this could be closed as lutris now hath vertical banners?
