### ISSUE TITLE
Update DXVK versions on launch

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1513]
For some reason, the list of DXVK versions only gets updated when a user opens a configuration **of a game**. The versions do not get updated when you open configuration of a runner, for example.
I think the best approach here would be to just update DXVK version when Lutris starts (but keep the existing behavior too since Lutris now stays opened in background, so the update on launch may end up getting triggered too rarely).

**Comment by moll** [comment]
While on the topic of DXVK versions, is there a environment variable to disable them akin to disabling Lutris' runtimes via `LUTRIS_RUNTIME=0` for those who prefer to not download precompiled code off the net?

**Comment by tannisroot** [comment]
Nope. Can you open a separate issue about it?

**Comment by tannisroot** [comment]
By default it does not download DXVK on launch. It just generates a file with available DXVK versions, that's it.

**Comment by tannisroot** [comment]
I don't know when it was fixed but it is now so closing!
