### ISSUE TITLE
[Steam Wine] steamwebhelper.exe crashes in a loop, clogs up memory

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1514]
Doesn't matter what Wine version I use, every time I open either Steam Wine itself or a Steam Wine game, terminal output gets spammed with crashes of steamwebhelper.exe.
These crashes happen over an over, creating several instances of steamwebhelper.exe that stick in the memory and clog it up.
This is very bad as it may cause worse performance in games, so Lutris needs to do something about it.
One of the solutions that worked for me was disabling steamwebhelper.exe through Wine overrides.
```
000000fc steamwebhelper.exe
	["C:\Program Files (x86)\Steam\bin\cef\cef.win7x64\steamwebhelper.exe" --type=renderer --no-sandbox --force-device-scale-factor=1 --disable-features=AsyncWheelEvents,TouchpadAndWheelScrollLatching --disable-gpu-compositing --service-pipe-token=B879162D32D8A8DF04FC70C551A53957 --enable-blink-features=ResizeObserver,Worklet,AudioWorklet --lang=en-US --log-file="C:\Program Files (x86)\Steam\logs\cef_log.txt" --product-version="Valve Steam Client" --webview-urls=http://localhost/*,http://steamloopback.host/*,https://steamloopback.host/*,https://localhost/* --disable-spell-checking --force-device-scale-factor=1 --disablehighdpi --buildid=1543346820 --steamid=0 --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=B879162D32D8A8DF04FC70C551A53957 --renderer-client-id=5 --mojo-platform-channel-handle=888 /prefetch:1 --no-sandbox]
	00000120    0
	0000011f   -2
	0000011e    0
	0000011d    0
	0000011c    0
	0000011b    0
	0000011a    0
	00000119    0
	00000118    0
	00000117    0
	00000116    0
	00000115    0
	00000114    0
	00000113   -2
	00000112   -2
	00000111    0
	00000110    0
	000000fd    0
System information:
    Wine build: wine-3.3-2137-g3110fff ( Staging Esync PBA )
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 4.20.0-1-tkg-pds

```

**Comment by strycore** [comment]
pretty sure this isn't true anymore

**Comment by tannisroot** [comment]
It still is.

**Comment by strycore** [comment]
this is a bug with wine, not lutris

**Comment by tannisroot** [comment]
Yes. But it's a very nasty one and Lutris can easily workaround it and therefore absolutely should.
Let me just describe how bad the crashing is and how easy and non problematic it is to workaround it:
1) Just a few minutes into the game can create zombie `steamwebhelper.exe` processes that can take up at least 5 gigs of RAM.
2) The constant crashing and relaunching of steamwebhelper.exe also slows down the game itself (with LIS2 I lost something like 10% of FPS) and makes my PC fans spin like crazy
3) It is still an issue with wine 4.4 tkg
3) To get rid of all of these issues, you just have to disable `steamwebhelper.exe` through WINE overrides. And it has 0 impact on functionality because it doesn't work anyway.
