### ISSUE TITLE
Feral gamemode listed twice

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1517]
https://github.com/lutris/lutris/blob/master/lutris/sysoptions.py#L56-L92

First on line 56 and then on 86.

![screenshot from 2019-01-06 02-24-30](https://user-images.githubusercontent.com/15083452/50734859-4a224700-115a-11e9-91b4-f59fb5db00c4.png)

**Comment by tannisroot** [comment]
Weird how one is greyed-out but the other isn't 🤔

**Comment by AccountOneOff** [comment]
It's because the second option looks for `libgameautomode.so.0` except mine is without the `.0`.

@sigmaSd

**Comment by AccountOneOff** [comment]
So that fixed the dupe issue but now I can't access gamemode because of what I explained earlier.

**Comment by tannisroot** [comment]
That probably needs a separate issue.
