### ISSUE TITLE
Gamemode disabled as it looks for libgamemodeauto.so.0 instead of libgamemodeauto.so

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1522]
https://github.com/lutris/lutris/blob/master/lutris/sysoptions.py#L77-L84

![screenshot from 2019-01-07 17-44-53](https://user-images.githubusercontent.com/15083452/50804682-fe7bb480-12a3-11e9-8898-3b5ad28c6478.png)

**Comment by strycore** [comment]
I move the gamemode detection to the LinuxSystem class and updated the lib name
