### ISSUE TITLE
Newer DXVK versions aren't displayed in runner configuration

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1525]
Despite there being an up-to-date `dxvk_versions.json` file, DXVK version menu in `Steam Wine` runner lacks newer DXVK versions and instead only shows outdated fallback versions.
Same is true for regular Wine runner.
![screenshot from 2019-01-08 05-25-10](https://user-images.githubusercontent.com/10602045/50806052-2439a580-1306-11e9-9595-7e293b6d152f.png)

**Comment by strycore** [comment]
Deleted the dxvk cache file, restarted lutris and all the dxvk versions showed up when I opened a config dialog

**Comment by tannisroot** [comment]
Ok, then Lutris 0.5.0 release will need to remove it too when migrating, I guess.
