### ISSUE TITLE
Do not show message about missing gamemode in terminal output

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1526]
This may confuse users and make them believe it's some kind of essential library.
```
2019-01-08 05:39:36,869: i386 libgamemodeauto.so missing (needed by gamemode)
2019-01-08 05:39:36,869: x86_64 libgamemodeauto.so missing (needed by gamemode)
```

**Comment by strycore** [comment]
it's not related

**Comment by tannisroot** [comment]
Uhhh, can you explain? The issue is about gamemode messages, and they are still present.

**Comment by tannisroot** [comment]
Reopened because of https://github.com/lutris/lutris/pull/1538
