### ISSUE TITLE
Do not show "winemenubuilder.exe not found" error message

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1529]
This exact message:
```wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"```
confuses people and makes them believe it's the cause of their issues, which is not true.
Since Lutris disables winemenubuilder.exe by default, I think the message should be hidden by default too.

**Comment by strycore** [comment]
It should already be disabled, there's a condition for that in the code so if you still see it, open another bug because that's not normal.

**Comment by tannisroot** [comment]
My apologies, I assumed the behavior about it was the same as in 0.4.23.

**Comment by strycore** [comment]
I  think this change is older than 0.4.23? Or maybe it was only in next?

**Comment by tannisroot** [comment]
I still see people with 0.4.23 complain about it on Discord.
