### ISSUE TITLE
Support for Adventure Game Studio

### ISSUE THREAD

**Issue by neuromancer** [lutris/lutris#153]
Please, provide support for running adventure games using [AGS](https://en.wikipedia.org/wiki/Adventure_Game_Studio). There are hundreds of free adventures (and some paid ones as well)

**Comment by dennisjj4** [comment]
Yeah, this would me nice for (for example) the Chizo Mythos games (5 Days a Stranger, 6 Days a Sacrifice, 7 Days a Skeptic, and Trilby's Notes)

**Comment by strycore** [comment]
I have build the latest version of AGS which is available here : https://lutris.net/files/runners/ags-3.3.3.0-x86_64.tar.gz (in the future I'll probably upload a multiarch runner).

There's also a build script here: https://github.com/lutris/buildbot/blob/master/ags/build.sh

AGS will probably get its own runner in 0.3.7, but the current build can already be used for installer using the linux runner (which will duplicate the AGS runner for every game, but it's really lightweight so it's not really a problem).

**Comment by Ferk** [comment]
I believe http://scummvm.org/ has support for AGS games.
