### ISSUE TITLE
Do not allow to install games until runtime was fully downloaded

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1530]
Some installers depend on components in runtime and will fail if they are not present. For example, installers that depend on winetricks will not work if winetricks is not yet downloaded.
Same thing with `lib32` and `lib64` (I could not get the installer for Overwatch to work properly while `lib64` was still being fetched), and other components as well I presume.

**Comment by strycore** [comment]
We now wait for the runtime to be full downloaded before opening lutris.
