### ISSUE TITLE
Mismatching tips in configuration

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1537]
Up top, you can see that the tip at the top of the window in "System Options" is different than 
in 'Runner Options", even though they describe the same thing.
In my opinion, it should be unified (either use short version for both to make the menu look more appealing, or use longer one to make it more informative).
![screenshot from 2019-01-09 13-02-53](https://user-images.githubusercontent.com/10602045/50892394-70244180-140f-11e9-8e88-beeb5a433693.png)
![screenshot from 2019-01-09 13-02-44](https://user-images.githubusercontent.com/10602045/50892399-75818c00-140f-11e9-95bb-af13c2390728.png)

**Comment by strycore** [comment]
They don't describe the same thing. The system options can be overridden at 2 different levels.
