### ISSUE TITLE
Install lib32 and lib64 manually

### ISSUE THREAD

**Issue by PirateofPC** [lutris/lutris#1539]
Everytime I run Lutris it try to download `lib32` and `lib64` runtimes, but nothing happens, so it redownload and redownload and redownload, and I have slow internet connection and limit data bandwidth, so I can't access my internet unless I close Lutris, this is the log I get from `lutris -d`:
> DEBUG    2019-01-09 22:42:05,819 [http]:GET https://lutris.net/api/runtime
DEBUG    2019-01-09 22:42:07,255 [runtime]:Runtime x360ce is already up to date (locally updated on Sat 05 Jan 2019 01:58:35 AM GMT, remote created on Sat 15 Dec 2018 11:33:12 AM )
DEBUG    2019-01-09 22:42:07,256 [runtime]:Runtime dumbxinputemu is already up to date (locally updated on Sat 05 Jan 2019 01:59:08 AM GMT, remote created on Sat 15 Dec 2018 11:32:50 AM )
DEBUG    2019-01-09 22:42:07,257 [runtime]:Runtime gamecontrollerdb is already up to date (locally updated on Sat 05 Jan 2019 01:58:27 AM GMT, remote created on Sat 15 Dec 2018 09:35:14 AM )
DEBUG    2019-01-09 22:42:07,257 [runtime]:Runtime winetricks is already up to date (locally updated on Sat 05 Jan 2019 01:58:35 AM GMT, remote created on Sun 25 Nov 2018 08:25:58 PM )
DEBUG    2019-01-09 22:42:07,257 [runtime]:Runtime steam is already up to date (locally updated on Mon 07 Jan 2019 10:36:34 AM GMT, remote created on Sat 03 Nov 2018 03:11:04 AM )
WARNING  2019-01-09 22:42:07,258 [runtime]:Runtime lib64 is not available locally
DEBUG    2019-01-09 22:42:07,258 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2
WARNING  2019-01-09 22:42:07,260 [runtime]:Runtime lib32 is not available locally
DEBUG    2019-01-09 22:42:07,261 [downloader]:Starting download of:
 https://lutris.nyc3.digitaloceanspaces.com/runtime/lib32.tar.bz2
DEBUG    2019-01-09 22:42:07,261 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runtime/lib64.tar.bz2
DEBUG    2019-01-09 22:42:07,263 [runtime]:Runtime p7zip is already up to date (locally updated on Sat 05 Jan 2019 01:59:17 AM GMT, remote created on Tue 25 Oct 2016 02:34:44 AM )
DEBUG    2019-01-09 22:42:07,263 [http]:GET https://lutris.nyc3.digitaloceanspaces.com/runtime/lib32.tar.bz2
INFO     2019-01-09 22:42:07,265 [lutriswindow]:Connected to lutris.net as PirateofPC
DEBUG    2019-01-09 22:42:07,279 [api]:Fetching game library
DEBUG    2019-01-09 22:42:07,284 [http]:GET https://lutris.net/api/games/library/PirateofPC
DEBUG    2019-01-09 22:42:07,886 [steam]:Watching Steam folder /home/pirateofpc/.steam/steam/steamapps
INFO     2019-01-09 22:42:10,652 [lutriswindow]:Setting up view for first run
DEBUG    2019-01-09 22:42:10,653 [lutriswindow]:Syncing 144 icons
DEBUG    2019-01-09 22:42:10,663 [resources]:Requesting missing icons from API for 6 games
DEBUG    2019-01-09 22:42:10,664 [http]:GET https://lutris.net/api/games

So I downloaded them manually from the links on the log, but I don't know where to put them, I tried to put them here `/home/pirateofpc/.local/share/lutris/lib`, also tried to extract them, but nothing happens, so please help.

**Comment by strycore** [comment]
you're using the wrong destination, it should be  /home/pirateofpc/.local/share/lutris/runtime

**Comment by PirateofPC** [comment]
Thanks 😁
