### ISSUE TITLE
Glade corupts the Lutris UI file

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#1541]
Some non standard (or non supported by Glade) attributes get removed from the .ui file when saved with Glade.
This makes Glade unusable for the project and very hard to edit UI files.
Either the incriminated attributes have to be removed from the Glade ui file or a solution needs to be found so that Glade stop destroying parts of the document, making it useless.

Incriminated commits:
https://github.com/lutris/lutris/commit/e188175049b3daf5c8de4df1ca710bb5b934394c

https://github.com/lutris/lutris/commit/f2b7670ead18928c44b873e0084dabeca84b0024

**Comment by TingPing** [comment]
Glade doesn't understand GtkBuilder very well. I know its not what you want to hear but just don't use glade.

**Comment by strycore** [comment]
That's too bad but there may be a way to bring this issue upstream?

**Comment by TingPing** [comment]
Glade does have a maintainer now, so maybe make a diff between before and after glade saves it, see whats missing and report it upstream: https://gitlab.gnome.org/GNOME/glade

**Comment by strycore** [comment]
this is not up to lutris to fix glade's shit
