### ISSUE TITLE
Continue download

### ISSUE THREAD

**Issue by theArhar** [lutris/lutris#1545]
Today I am trying to install twitch-app (https://lutris.net/games/twitch-app/) all day. I dont know why, but download stucks randomly, maybe my internet is terrible. BUT! Every time I need to start downloading process from 0%. I think I will never install this app, because I simply can not download 
https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-esync-staging-pba-3.18-x86_64.tar.gz

Is there a way to maybe download it manually and put into some folder? Or continue downloading from where it hangs?

**Comment by tannisroot** [comment]
Yeah sorry, our host is pretty trash and this can cause such issues.
>Is there a way to maybe download it manually and put into some folder?

Yes you can do that! Just download it through that link in your browser, extract the file and copy the output folder into `~/.local/share/lutris/runners/wine`.
For example:
![image](https://user-images.githubusercontent.com/10602045/53687842-e2980a80-3d4a-11e9-95f6-95e956a7af29.png)
I hope this resolves it for you :)
