### ISSUE TITLE
Use GTK Flowbox for Icon View

### ISSUE THREAD

**Issue by remggo** [lutris/lutris#1546]
Is it planned to migrate back to a GTK Flowbox? In the current lutris-next branch, when resizing the window, there is ugly whitespace that could be fixed by using a Flowbox (see: [GTK Flowbox Example](https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html?highlight=flowbox#id5))

![screenshot-flowbox](https://user-images.githubusercontent.com/3630154/50986793-0d62a100-1508-11e9-813b-7872c917d76b.png)

I found Issue #452 which states, that Flowbox was used and is removed. What was the reasoning behind this decision?

**Comment by TingPing** [comment]
Was just slow, but everything is slow due to how we load everything up front. I did fiddle around with more async loading which kinda helps.

**Comment by TingPing** [comment]
In my opinion the future of Lutris views should be a ListBox and a FlowBox both backed by the same ListStore. Somebody just needs to put in the work to ensure its fast and fluid. I personally don't believe it makes sense to support both the legacy style views and the new views at the same time.

**Comment by strycore** [comment]
yeah there is still FlowBox code in there that needs to be updated, there's a lot of refactoring to do on the views so it doesn't make sense to update it right now but it will be done at some point. For some smaller game libraries, FlowBox is an acceptable solution.

**Comment by strycore** [comment]
I don't think this is going to work unless proven otherwise
