### ISSUE TITLE
Always show "Log" button in the right panel

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1550]
It would make more sense to not hide it when the game isn't running since the user might get confused looking for the button but not finding it.
![screenshot from 2019-01-11 06-49-37](https://user-images.githubusercontent.com/10602045/51013175-2142ed00-1572-11e9-8845-7bfe3852fd1b.png)

**Comment by strycore** [comment]
We show it as long as there's a log to display. When the game has quit but the panel is this open, the button stays and it's still possible to view the logs
