### ISSUE TITLE
Make "Play" button bigger in right panel

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1551]
It doesn't make sense that the most used button in UI takes so little space, while way less useful buttons (Remove, View in Lutris.Net, Install Another Version) are given so much of it.
Additionally, it can be easily misclicked due to its small size.
Instead, I propose to take a little bit more inspiration from Origin and make it way bigger:
![screenshot from 2019-01-11 13-23-18](https://user-images.githubusercontent.com/10602045/51029006-2883ee00-15a6-11e9-84bd-a008eba05ef9.png)
![screenshot from 2019-01-11 13-23-09](https://user-images.githubusercontent.com/10602045/51028999-2588fd80-15a6-11e9-8a4e-b45ffa6abb67.png)

**Comment by strycore** [comment]
That's fixed now
