### ISSUE TITLE
[possible bug] playtime

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1556]
See with the latest git that it reset time played.

Play FIFA 14 (psp) on and off, and yesterday lutris claimed I played it for about 4.65hrs,

![screenshot_20190110_184342](https://user-images.githubusercontent.com/19357986/51061344-a45c5580-15fb-11e9-8aaf-401f2d560b27.png)

Today after playing another league game, Lutris now claim I only played for 0.42 hrs,

![screenshot_20190111_233528](https://user-images.githubusercontent.com/19357986/51061379-cce44f80-15fb-11e9-92cc-b7ada8984389.png)

**Comment by telanus** [comment]
Something I noticed this morning, play time doesn't seem to be updated, played a couple of games. If the game has no recorded play time it'll update the play time to what you played in that session, yet a game you played previously it won't. 

Played Metal Slug 6 for about 15 minutes and it updated the time, yet FIFA 14 I played about 30minutes, and it is still stuck at 0.42 hrs.

**Comment by strycore** [comment]
the playtime was stored as text in the database (with the "hrs" extension), this is not sustainable and was bound to cause some issue at some point, the feature was advertised as experimental anyway (and will remain kind of experimental until it can sync with the website)
