### ISSUE TITLE
Indicate that the game has never been played in playtime

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1563]
Right now playtime just plain disappears in such situation:
![screenshot from 2019-01-12 08-06-17](https://user-images.githubusercontent.com/10602045/51069512-916c7400-1641-11e9-93af-c0651037e09b.png)

**Comment by strycore** [comment]
It contradicts the last played label just below.

**Comment by tannisroot** [comment]
Oops, totally missed it. I guess this is just a result of https://github.com/lutris/lutris/issues/1556 then
