### ISSUE TITLE
Move contextual menu to right panel

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1573]
I think it would be nice to move existing contextual menu that opens with a right click on a game in library to right panel, and show it when a button is pressed. (and remove all entries from it that are already implemented in the right panel, and leave stuff like `Winetricks`and `Wine configuration`).
In Origin it looks alright:
![screenshot from 2019-01-11 13-24-03](https://user-images.githubusercontent.com/10602045/51071918-ee7c2000-1669-11e9-915b-afcfb9f489fb.png)

**Comment by strycore** [comment]
I'll see later if I can find a suitable way to implement this. I don't want anything hidden under a contextual menu. This is a big no-no now.

**Comment by strycore** [comment]
it's done
