### ISSUE TITLE
Show that a game is running when a different one is selected

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1575]
Currently, you can only check if the game is running by clicking on it and checking its status in the right panel.
If you select a different game in your library, you won't know if another is still running or not (or which one).
I suggest to handle this by showing a status bar above game library (kind of like the one that was in 0.5 before right panel happened) that displays "`Game` is running" and a stop button if that game is not the one that is currently selected and shown in right panel.

**Comment by AlexanderRavenheart** [comment]
I suggest we handle this by adding a running icon on the game banner for the running game(s). We could also highlight it by displaying a border around the banner (suggest orange or green).

**Comment by tannisroot** [comment]
That's actually a much better idea.

**Comment by tannisroot** [comment]
On the other hand, with such implementation, if the user has a big library, they would have scroll through it and look for a game or games that are still running.

**Comment by strycore** [comment]
That seems complicated. There is already a way to quickly jump back to running games and I think highlighting the current banner should be enough.

**Comment by isugimpy** [comment]
Alternative idea from a UX perspective might be to hijack the categories feature to do this once it's completed.  Just make a virtual category of "Running Games" that anything currently running gets added to, and removed from, automatically.

**Comment by Tallicia** [comment]
Additionally, with the running game clearly known, it can be pushed with discord integration to display there as well if an optional selection is marked as enabled.

**Comment by tannisroot** [comment]
No longer applies with the new UI.
