### ISSUE TITLE
Dynamically update information (like playtime) in right panel

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1578]
After playing a game, you need to select a different game to update information in the right panel.
This should be changed:
![peek 2019-01-12 14-02](https://user-images.githubusercontent.com/10602045/51072506-d5c43800-1672-11e9-9670-809c7ddd1e8b.gif)

**Comment by telanus** [comment]
Something I seen if you install a game (I only tried via add game and add installed game) the panel don't update the info, you need to close lutris and reopen it to get the data to show

![screenshot_20190113_104325](https://user-images.githubusercontent.com/19357986/51083544-bab20080-1724-11e9-8dea-61b3087cafd0.png)

**Comment by tannisroot** [comment]
This has regressed

**Comment by tannisroot** [comment]
![peek 2019-02-13 21-09](https://user-images.githubusercontent.com/10602045/52733433-c3238280-2fd3-11e9-9906-3f03cdfa5591.gif)

**Comment by strycore** [comment]
the side banner should now update correctly
