### ISSUE TITLE
[0.5.0] Segmentation error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1579]
Something I noticed today. 

If one go click on random games one after the other, at around 20 games Lutris will crash with a "Segmentation fault (core dumped)" no other info is given by Lutris.

**Comment by tannisroot** [comment]
Can this be reliably reproduced? Do games have to be installed?

**Comment by telanus** [comment]
@tannisroot Ya happens every time I try. It happens with both games installed and mixed of installed and unstalled

**Comment by strycore** [comment]
I could reproduce that on the first try on a old Core2 computer.

**Comment by AccountOneOff** [comment]
Can't reproduce. I clicked around 100 times no segfault.

**Comment by strycore** [comment]
@telanus what's your hardware config?

**Comment by strycore** [comment]
jeez, the shittier the computer, the faster it segfaults, 1 click on the Thinkpad T60 and bam. (No crash on i7 or Ryzen of course). I think it has something to do with the background image.
@telanus  also, what's your screen resolution?

**Comment by strycore** [comment]
@telanus try commenting out line 21 of game_panel.py: `self.put(self.get_background(), 0, 0)`

**Comment by telanus** [comment]
@strycore commenting out that line makes it no longer crash.

> also, what's your screen resolution?
1360x768

> what's your hardware config?
A [dual core e5300](https://ark.intel.com/products/35300/Intel-Pentium-Processor-E5300-2M-Cache-2-60-GHz-800-MHz-FSB-)

**Comment by strycore** [comment]
I finally figured out how to set the image in a CSS background. It no longer crashes but backgrounds aren't compatible with some themes like Pop :(
