### ISSUE TITLE
Lutris does not remember that winesteam games are installed

### ISSUE THREAD

**Issue by orbea** [lutris/lutris#158]
Whenever I close lutris it will forget that the winesteam games are installed and I will have to install them through lutris again for them to launch.  This is only a minor inconvenience as it takes a few moments, but ideally it should remember.  This may be because I am using a custom install location for my steam games?  Games installed with the linux version of wine have no issues.

I have lutris installed on slackware-current via the slackbuild here - http://slackbuilds.org/repository/14.1/games/lutris/?search=lutris

Edit:  The issue also present itself whenever the library is synchronized, native linux games outside of steam also don't have this issue.

**Comment by Xodetaetl** [comment]
>  Games installed with the linux version of **wine** have no issues.

With the Linux version of **Steam**, you meant ?

Steam's custom folders are normally supported. What's the path of your install folder ?

**Comment by orbea** [comment]
Yes, typo, the linux version of steam has no issues.  The install location for the wine version of steam is: Z:\media\data\home\games\Lutris\

**Comment by Xodetaetl** [comment]
Ok, nothing special with that path. Can you install in lutris one of these games that get removed then restart lutris with `lutris -d` in a terminal and paste here the terminal output ?

**Comment by orbea** [comment]
$ lutris -d                                                                               
DEBUG    2015-03-02 08:28:21,252 [lutris]:Welcome to Lutris

(lutris:22936): Gtk-WARNING **: Unknown property: GtkLabel.lines

(lutris:22936): Gtk-WARNING **: Unknown property: GtkLabel.lines
DEBUG    2015-03-02 08:28:21,922 [lutriswindow]:Getting game list
DEBUG    2015-03-02 08:28:22,121 [lutriswindow]:Switching view
DEBUG    2015-03-02 08:28:22,448 [lutriswindow]:Connecting signals
INFO     2015-03-02 08:28:22,644 [lutriswindow]:Connected as orbea
DEBUG    2015-03-02 08:28:22,645 [jobs]:Async call: sync_all
DEBUG    2015-03-02 08:28:22,645 [sync]:Syncing game library
DEBUG    2015-03-02 08:28:22,645 [jobs]:Async call: update_runtime
DEBUG    2015-03-02 08:28:22,645 [sync]:50 games in local library
DEBUG    2015-03-02 08:28:22,648 [api]:Fetching game library
DEBUG    2015-03-02 08:28:24,014 [sync]:50 games in remote library (inc. unpublished)
DEBUG    2015-03-02 08:28:24,024 [sync]:0 games updated
DEBUG    2015-03-02 08:28:24,024 [sync]:Syncing local steam games
DEBUG    2015-03-02 08:28:24,131 [sync]:Setting Deus Ex as uninstalled
DEBUG    2015-03-02 08:28:24,282 [jobs]:Async call: sync_icons
DEBUG    2015-03-02 08:28:24,283 [resources]:Fetching icons

**Comment by orbea** [comment]
$ lutris -d                                                                               
DEBUG    2015-03-02 08:28:21,252 [lutris]:Welcome to Lutris

(lutris:22936): Gtk-WARNING **: Unknown property: GtkLabel.lines

(lutris:22936): Gtk-WARNING **: Unknown property: GtkLabel.lines
DEBUG    2015-03-02 08:28:21,922 [lutriswindow]:Getting game list
DEBUG    2015-03-02 08:28:22,121 [lutriswindow]:Switching view
DEBUG    2015-03-02 08:28:22,448 [lutriswindow]:Connecting signals
INFO     2015-03-02 08:28:22,644 [lutriswindow]:Connected as orbea
DEBUG    2015-03-02 08:28:22,645 [jobs]:Async call: sync_all
DEBUG    2015-03-02 08:28:22,645 [sync]:Syncing game library
DEBUG    2015-03-02 08:28:22,645 [jobs]:Async call: update_runtime
DEBUG    2015-03-02 08:28:22,645 [sync]:50 games in local library
DEBUG    2015-03-02 08:28:22,648 [api]:Fetching game library
DEBUG    2015-03-02 08:28:24,014 [sync]:50 games in remote library (inc. unpublished)
DEBUG    2015-03-02 08:28:24,024 [sync]:0 games updated
DEBUG    2015-03-02 08:28:24,024 [sync]:Syncing local steam games
DEBUG    2015-03-02 08:28:24,131 [sync]:Setting Deus Ex as uninstalled
DEBUG    2015-03-02 08:28:24,282 [jobs]:Async call: sync_icons
DEBUG    2015-03-02 08:28:24,283 [resources]:Fetching icons

(I accidentally deleted the comment once...it affects both of the wine steam games I have installed, deus ex and torchlight II.)

**Comment by Xodetaetl** [comment]
Thanks. That debug log wasn't very helpful so we'll have to try a few things to locate the bug. Can you start with installing a steam game in the default folder and see if that one get's removed on Lutris restart ?

**Comment by Xodetaetl** [comment]
Actually I can reproduce the bug, so I don't need any more input from you. :)

**Comment by Xodetaetl** [comment]
Fixed in adf8440. It was a path case issue.

**Comment by orbea** [comment]
Great!  I was able to fix the issue locally by going into source, adding the new lines and then reinstalling the slackbuild as usual with the new source.  Thanks on the speedy fix. :)
