### ISSUE TITLE
I don't see DXVK0.95 in the menu.

### ISSUE THREAD

**Issue by laichiaheng** [lutris/lutris#1592]
The latest version of DXVK is 0.95, but I can't see it in Lutris.

**Comment by tannisroot** [comment]
I could see it the moment it appeared.
Please state your version of Lutris.

**Comment by laichiaheng** [comment]
@tannisroot I only see 0.90

**Comment by tannisroot** [comment]
Try deleting `~/.local/share/lutris/runtime/dxvk/dxvk_versions.json`

**Comment by laichiaheng** [comment]
@tannisroot There is no dxvk in the runtime folder.

**Comment by tannisroot** [comment]
Launch Lutris with `lutris -d` and paste output here.

**Comment by laichiaheng** [comment]
How to open Resident Evil 2 "1-Shot Demo" in Lutris?

**Comment by laichiaheng** [comment]
(lutris:3632): Gtk-WARNING **: 17:58:45.344: Locale not supported by C library.
	Using the fallback 'C' locale.
DEBUG    2019-01-14 17:58:45,761 [lutriswindow]:Showing splash screen
DEBUG    2019-01-14 17:58:45,762 [http]:GET https://lutris.net/api/runtime
DEBUG    2019-01-14 17:58:46,302 [runtime]:Runtime x360ce is already up to date (locally updated on Mon Jan 14 08:42:24 2019, remote created on Sat Dec 15 11:33:12 2018)
DEBUG    2019-01-14 17:58:46,303 [runtime]:Runtime dumbxinputemu is already up to date (locally updated on Mon Jan 14 08:42:24 2019, remote created on Sat Dec 15 11:32:50 2018)
DEBUG    2019-01-14 17:58:46,303 [runtime]:Runtime gamecontrollerdb is already up to date (locally updated on Mon Jan 14 08:42:23 2019, remote created on Sat Dec 15 09:35:14 2018)
DEBUG    2019-01-14 17:58:46,304 [runtime]:Runtime winetricks is already up to date (locally updated on Mon Jan 14 08:42:24 2019, remote created on Sun Nov 25 20:25:58 2018)
DEBUG    2019-01-14 17:58:46,304 [runtime]:Runtime steam is already up to date (locally updated on Mon Jan 14 08:44:25 2019, remote created on Sat Nov  3 03:11:04 2018)
DEBUG    2019-01-14 17:58:46,305 [runtime]:Runtime lib64 is already up to date (locally updated on Mon Jan 14 08:43:53 2019, remote created on Mon Oct  8 03:29:56 2018)
DEBUG    2019-01-14 17:58:46,305 [runtime]:Runtime lib32 is already up to date (locally updated on Mon Jan 14 08:43:53 2019, remote created on Mon Oct  8 03:29:40 2018)
DEBUG    2019-01-14 17:58:46,306 [runtime]:Runtime p7zip is already up to date (locally updated on Mon Jan 14 08:42:23 2019, remote created on Tue Oct 25 02:34:44 2016)
DEBUG    2019-01-14 17:58:46,307 [api]:Fetching game library
DEBUG    2019-01-14 17:58:46,417 [steam]:Watching Steam folder /home/user/.steam/steam/steamapps
DEBUG    2019-01-14 17:58:46,440 [lutriswindow]:Showing splash screen
INFO     2019-01-14 17:58:46,441 [lutriswindow]:Setting up view for first run
INFO     2019-01-14 17:59:04,360 [application]:Shutting down Lutris
INFO     2019-01-14 17:59:04,400 [application]:Shutting down Lutris

**Comment by laichiaheng** [comment]
I need to type in 0.95 myself.
