### ISSUE TITLE
Allow to pass arguments to MAME

### ISSUE THREAD

**Issue by libookami** [lutris/lutris#1593]
Hi. By default i'm having a terrible tearing on MAME. I wasn't able to find an option in the GUI to fix this. while messing with the options i noticed that enabling "run in a terminal" generates a .sh in ~/.cache/lutris/. I modified the generated script and added "-waitvsync" into the arguments when MAME is called and that fixed the problem completely, no more tearing. Also, i didn't found any way to pass arguments to the MAME's command and because passing that custom argument was my only way to fix the tearing my petition is to allow to pass arguments to MAME from the GUI as an advanced option.

I don't know if other people experiences heavy tearing on MAME too, i tested with two laptops using Mesa in both cases, one was intel and the other was AMD. I tried to enable various options that supposedly get rid of tearing both in the compositor (kwin) and the driver, but for some reason it didn't work for MAME. I haven't tested with an Nvidia GPU, so i don't know if it would be good to open another bug about the tearing in particular or to only add a gui option that activates the "-waitvsync" in particular. 
Thanks for all the hard work!

*An small note: If someone else experiences the same as me, generate the "run_in_term.sh" script and put it somewhere else (because lutris overwrites the one in ~/.cache/lutris). Modify the command to add the arguments that suits you and replace the name of the rom with a variable that allows to pass an argument (for example romname=$1). When adding a MAME game to lutris choose linux native instead of MAME as runner. When selecting the linux executable choose the script that was modified (you need to make it executable) and in the arguments on the lutris GUI you can give the name of the rom file. Hope this helps someone.

**Comment by tannisroot** [comment]
Lutris allows to launch scripts before the launch of the game, after and on demand. Check configuration.

**Comment by libookami** [comment]
> Lutris allows to launch scripts before the launch of the game, after and on demand. Check configuration.

Hi, thanks a lot for your reply. I found this on system options but because it seems to be other commands rather than for passing arguments to the emulator i didn't use those. I looked on google for "lutris on-demand command" because the command i'm trying to modify is the one for the emulator itself, but i don't find a lot of examples or documentation. Would you mind giving me an example of how can i use those features to pass the argument "-waitvsync" to the MAME runner please? Thanks!

**Comment by RobLoach** [comment]
Like this? https://github.com/lutris/lutris/pull/1602

**Comment by libookami** [comment]
Ok, i already tested. I downloaded the master and applied the changes your provided in the mame.py file. Lutris didn't run at fisrt until i installed these [packages](https://github.com/lutris/lutris/issues/1454):
`sudo apt install gir1.2-gnomedesktop-3.0 gir1.2-webkit2-4.0`
Then i ran fine and i was able to test the new option and it worked very well for me. Thanks a lot for everything!, i hope with this all people can have a tear-free experience with MAME on lutris! :smiley:

**Comment by RobLoach** [comment]
There's a lot more options that MAME provides. If you find anything useful, feel free to add them in! The codezorz are pretty easy to follow:
https://github.com/lutris/lutris/pull/1602/files

**Comment by libookami** [comment]
Thanks a lot, i will!

**Comment by strycore** [comment]
Closed in PR #1602
