### ISSUE TITLE
Process management issues

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#161]
- [x] Takes 15s to take into account that the process was terminated, a bit long to wait for my resolution to be reset. :)
- [x] Error messages about missing libs are nowhere to be found, won't appear in the last game's log.
- [x] Uninstalling (wine)steam games won't work.

**Comment by strycore** [comment]
I have reduced the heartbeat's delay which will make things more reactive and fixed the uninstall command.
The game log issue on the other hand should not be happening, is it just the missing libs that aren't there or there not game log at all?

**Comment by Xodetaetl** [comment]
New delay is fine. Steam uninstall command is fixed but it still doesn't work, steam won't launch, no error msg

> The game log issue on the other hand should not be happening, is it just the missing libs that aren't there or there not game log at all?

No log at all

**Comment by strycore** [comment]
I'll take a closer look at the uninstall command later. For the game log, it can happen that the log gets overwritten when 2 threads are launched. I you get the message "game has quit" twice in the terminal?

**Comment by Xodetaetl** [comment]
Oh now I'm seeing the error, it's likely that I never waited the 15s  for the game to quit, I thought the log filled up while the process was running. :)

**Comment by strycore** [comment]
That's something I want to do but hasn't been implemented yet

**Comment by Xodetaetl** [comment]
Last issue fixed with 77a1c70dd416ad95db1229ad3e5027d4345fa77f and 8eea4cd0f10306c2506846c43a85bfe7a8b3fec3
