### ISSUE TITLE
[master][regression] UI locks up for a few seconds on some launches of Lutris

### ISSUE THREAD

**Issue by Medath** [lutris/lutris#1611]
Introduced in 9ff3d219a78d9f91903314ad7be3b45b0e3e7e9d.

More specifically this line seems to be at fault: https://github.com/lutris/lutris/blob/c1de7a345eea1bb236bd2619abeca134f9fe513e/lutris/gui/views/store.py#L124

**Comment by strycore** [comment]
Would probably be wiser to launch the missing media download in a thread
