### ISSUE TITLE
esync how-to is wrong/outdated

### ISSUE THREAD

**Issue by Wuestengecko** [lutris/lutris#1612]
Previously discussed in Tk-Glitch/PKGBUILDS#82  
Related: #1233

The esync how-to in the Wiki contains wrong or outdated information:

- [ ] It is not necessary to manually raise the soft limit on file descriptors at all. Wine-esync will automatically increase its processes' soft limits, provided the hard limit is high enough. The [esync documentation](https://github.com/zfigura/wine/blob/esync/README.esync#L9..L30) (indirectly) confirms this.
- [ ] On Arch Linux, it is not necessary to touch systemd config at all, since `/etc/security/limits.conf` [is applied by pam_limits](https://wiki.archlinux.org/index.php/Limits.conf) and thus works for user login sessions. This [also applies to Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=754285) and probably a lot of other distros.
- [ ] With systemd v240, the global file descriptor hard limit [was raised to 512K](https://github.com/systemd/systemd/blob/v240/NEWS#L60..L94). Esync still recommends 1M, and systemd v240 will take a while to be adopted by all distros, but it might still be worth adding a note to the page.

**Comment by strycore** [comment]
I updated the Esync documentation to reflect those. Let me know if there are any other adjustments that can be made.

**Comment by DanMan** [comment]
@strycore  https://github.com/lutris/lutris/wiki/How-to:-Esync suggests to raise the hard limit to 524288, which I have done, but Lutris 0.5 still won't let me enable it.

I think it should simply warn about it, and not flat out refuse to run the program. I don't appreciate this paternalism at all.

**Comment by Medath** [comment]
What does `ulimit -Hn` output for you?

**Comment by DanMan** [comment]
> What does `ulimit -Hn` output for you?

524288

**Comment by Medath** [comment]
Ok, can you run `python3`, then enter the following commands
`import resource`
`resource.getrlimit(resource.RLIMIT_NOFILE)`
and tell us the output?

**Comment by DanMan** [comment]
It says `(1024, 524288)` and I'm on Ubuntu 18.04 w/ kernel 4.15.0-45.
