### ISSUE TITLE
"Show Logs" button becomes greyed-out after stopping the game

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1616]
I am pretty sure the intended behavior is to keep it active after stopping the game until Lutris is closed:
![peek 2019-01-16 20-54](https://user-images.githubusercontent.com/10602045/51268378-0983c280-19d1-11e9-82f2-17ae590853c5.gif)

**Comment by strycore** [comment]
Yes. That's because the whole panel gets re-drawn on exit to update the info and resets the log button
