### ISSUE TITLE
Steam in-home streaming support

### ISSUE THREAD

**Issue by cazzoo** [lutris/lutris#162]
Hi there.
I would like to thank the initiative to do such a good idea to have an centralized app to manage and help us to play to our favorites (or not) games on our favorite (for sure) OS.

Recently I used to discover the in-home steaming feature built-in steam and I'm now wondering if we would be able to implement and use it into Lutris.

Actually if we have a game installed on a PC platform and not on our linux platform, it's not possible to launch the game through Lutris. Otherwise, it's fully available from steam linux client (and maybe also wine steam client).

Do you think it's a feature we could have in Lutris? Maybe steamcmd could handle that but I didn't look at it yet.

Cheers and keep going on

**Comment by Xodetaetl** [comment]
Hi, thanks for the thanks. :)
I don't think we'd be able to use the Steam streaming feature through Lutris (lack of external access to the feature). But there are a small number of libre alternatives to explore. Maybe we could setup a local cloud gaming server with [GamingAnywhere](http://gaminganywhere.org/) ?
If none of the 3rd party solutions are suitable though, we're doomed :D. At least for a few years.

**Comment by strycore** [comment]
It seems possible using the streaming_client executable (see: http://steamcommunity.com/groups/homestream/discussions/0/540731690719879426/ )
I doubt that using that will provide a better experience than what Steam already provides.

**Comment by Xodetaetl** [comment]
> I doubt that using that will provide a better experience than what Steam already provides.

Were you talking about GamingAnywhere ? I've tested it and the streaming performance isn't there yet, I had a lot more delay than with Steam. But it's promising

**Comment by cazzoo** [comment]
Thanks for feedback.
I digged a bit over the internet and what about the Limelight solution (http://limelight-stream.com/) ?

**Comment by Xodetaetl** [comment]
I don't think Limelight is a good candidate: Nvidia-only, Steam-only (apparently), and Nvidia could cut short the project whenever they think it's harming their business.

**Comment by strycore** [comment]
I'll leave this open for the time being so I can try to play with streaming once I've moved and got the Steam Link.
Marking this for 0.5, so it's pretty far away in the future.

**Comment by daniel-j** [comment]
I played a bit with GStreamer (gst-launch), and managed to stream my desktop (video only) with almost no latency.

```
Sender:
$ gst-launch-1.0 ximagesrc use-damage=0 ! videoscale ! video/x-raw,width=1280,height=720,framerate=30/1 ! videoconvert ! x264enc bitrate=6000 speed-preset=veryfast tune=zerolatency byte-stream=true key-int-max=5 intra-refresh=true ! video/x-h264,profile=high ! rtph264pay ! udpsink host=127.0.0.1 port=1234 sync=false

Reciever:
$ gst-launch-1.0 udpsrc port=1234 ! application/x-rtp,payload=96 ! rtph264depay ! decodebin ! xvimagesink
```
This could be controlled programmatically by Python using `gi.repository.Gst`.
A native application would probably be better (maybe using SDL2), but this is a good first step.

**Comment by RobLoach** [comment]
[Moonlight Streaming](http://moonlight-stream.com) is another solution. Available in LibreELEC and Linux. Never tested it myself.

**Comment by daniel-j** [comment]
> Moonlight Streaming is another solution. Available in LibreELEC and Linux. Never tested it myself.

Requires a Windows PC, Nvidia GameStream is only for Windows.

**Comment by daniel-j** [comment]
Video and audio streaming with Pulseaudio and OPUS. Do not run these commands on the same machine, you will probably get audio feedback! After you run the sender command, open pavucontrol, go to Recording and choose a Monitor sink.
```
Sender:
$ gst-launch-1.0 ximagesrc use-damage=0 ! video/x-raw,width=1280,height=720,framerate=60/1 ! videoconvert ! x264enc bitrate=4000 speed-preset=ultrafast tune=zerolatency byte-stream=true intra-refresh=true sliced-threads=true ! video/x-h264,profile=high,stream-format=byte-stream ! rtph264pay ! udpsink host=<reciever> port=1234 sync=false pulsesrc ! audio/x-raw,channels=2,depth=16,rate=48000 ! opusenc frame-size=10 bitrate-type=vbr bitrate=96000 ! rtpopuspay ! udpsink host=<reciever> port=1235 sync=false

Reciever:
$ gst-launch-1.0 udpsrc port=1234 caps="application/x-rtp" ! rtpjitterbuffer latency=0 ! rtph264depay ! decodebin ! xvimagesink udpsrc port=1235 caps="application/x-rtp" ! rtpopusdepay ! opusdec ! audioconvert ! pulsesink
```

**Comment by daniel-j** [comment]
Found http://parsec.tv/ which seems promising, Windows only for now but saw some hints at Linux support in the future. Also, they only support hardware accelerated codecs, which is nice!

**Comment by rainecheck** [comment]
Some thoughts here. If all that you're wanting to do is help in-home streaming, could there be a variant of running Steam/WineSteam through Lutris that booted up Steam one a specific account in a headless mode? If I'm understanding how it works right, that would make it functionally available.

**Comment by strycore** [comment]
this is not part of the scope of the project
