### ISSUE TITLE
Saving configuration switches right panel to a different game/no game

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1621]
Does not happen if you press cancel. Seems to always switch to the 4th game after the selected one in the library, and if the selected game is one of the last 4 in the game library, it just shows blank right panel instead.
Doesn't seem like anything useful appears in terminal output when it happens.
![peek 2019-01-17 21-55](https://user-images.githubusercontent.com/10602045/51342447-01955280-1aa5-11e9-81bd-881edc2f59fb.gif)
![peek 2019-01-17 22-13](https://user-images.githubusercontent.com/10602045/51342482-1a9e0380-1aa5-11e9-8fee-33d3b6976342.gif)

**Comment by Riesi** [comment]
For me its not consistently 4 games, instead it seems to increase the further you go down.
![lutris_configwindow_save_bug](https://user-images.githubusercontent.com/27691485/51342692-d30f7b80-1a94-11e9-9ea9-de0c51dea634.gif)
