### ISSUE TITLE
Inform that DXVK version does not exist on launch, do not show the game as running afterwards

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1623]
0.4.23 used to inform the user that DXVK they typed in into the text box is incorrect and cannot be fetched in a little window, however this is no longer the case in current master. Instead Lutris just spews out some errors and tracebacks in the terminal, and then treats the game as running if you reselect the game.
Log: https://paste.ubuntu.com/p/byJtP9X6vP/
![peek 2019-01-18 01-33](https://user-images.githubusercontent.com/10602045/51353592-1d5b2180-1ac2-11e9-8cdc-e560757d4c52.gif)

**Comment by strycore** [comment]
Fixed
