### ISSUE TITLE
The installer has no GOG ID

### ISSUE THREAD

**Issue by kalanihelekunihi** [lutris/lutris#1627]
When attempting to install titles that have since been removed from the GOG store for sale, existing installers fail citing "The installer has no GOG ID!" and does not allow the selection of the local install files.

Example: [https://lutris.net/games/install/2483/view](Duke Nukem) 
After reaching the screen: Select installation directory, a pop-up is presented stating "The installer has no GOG ID!"

One does not need the install files to reproduce this issue.

**Comment by kalanihelekunihi** [comment]
Issue appears in: /lutris/installer/interpreter.py Line: 326 - 331
Specifically, there is an evaluation of version to see if it starts with the string "GOG", and if so attempt to do the filename / path substitution. I'd suggest updating line 329 with an "and self.gogid is not null".

**Comment by strycore** [comment]
@ whoever put a GOG ID on the Duke Nukem Lutris page, stop messing with issue repro data. This is not helpful.

**Comment by strycore** [comment]
At least it created another bug, I can fix both now.
