### ISSUE TITLE
Syncing with steam misses a few games.

### ISSUE THREAD

**Issue by orbea** [lutris/lutris#163]
Logging in through steam misses a few games even if installed through steam, this is not really an big issue since manually adding them sorts it rather easily, but I figured it was worth noting.  For me its only these two (Not including a few beta versions).

https://lutris.net/games/synergy/
https://lutris.net/games/team-fortress-2/

**Comment by strycore** [comment]
Here's what the Steam API says regarding free to play games:

By default, free games like Team Fortress 2 are excluded (as technically everyone owns them). If include_played_free_games is set, they will be returned if the player has played them at some point. This is the same behavior as the games list on the Steam Community. 

Have you played Team Fortress 2 or Synergy lately? If not, then it's normal that they don't show up in your library.

**Comment by orbea** [comment]
Ah, yeah, that makes sense, thanks for the explanation.  Why do other free to play games show up then even if I haven't played them lately either?  Like the various other Half-Life/Portal based games?

**Comment by strycore** [comment]
Could you provide example of such games? Are you refering to mods? I'm not sure how mods are handled in the library, I'll have to check this out.

**Comment by orbea** [comment]
Yea, here are the few others I know.

Counter Strike Condition Zero (Also the deleted scenes package)
Dota 2 (The test game doesn't show up, not that I am complaining)
No More Room in Hell
Only If
Rexaura (Is the banner link broken or just missing?)

**Comment by strycore** [comment]
There seems to be a difference between some free to play games and others. Anyway, there's not really anything we can do about it since we're dependant on what the Steam API returns so if you're ok with that I'll close this issue.

**Comment by dennisjj4** [comment]
In response to Orbea, I had No More Room In Hell show up in Lutris, it's probably another game you needed to have played to get listed.  Same should be true for Only If and Rexaura.
