### ISSUE TITLE
Global environment variables in Lutris settings should be completely independent of per game environment variables

### ISSUE THREAD

**Issue by Nocifer** [lutris/lutris#1639]
OS: Arch Linux
Lutris version: 0.4.23

1) I have the variable "DXVK_HUD=fps" set in Lutris global settings.
2) I want to play, say, a Japanese game that needs to be run with "LC_ALL=ja_JP.UTF-8", so I add that variable to its configuration.
3) I then decide to also enable PBA globally, so I also set "PBA_ENABLE=1" in Lutris global settings.

I expect to then have the following variables for the Japanese game:

- DXVK_HUD=fps
- LC_ALL=ja_JP.UTF-8
- PBA_ENABLE=1

Instead I only have:

- DXVK_HUD=fps
- LC_ALL=ja_JP.UTF-8

**EDIT:** Global variables are also not updated locally when their global values change. For example, if I globally change DXVK_HUD's value from 'fps' to 'devinfo', that Japanese game will still have DXVK_HUD=fps.

**Comment by strycore** [comment]
I've changed the way the system configuration is read so that system and runner environment variables get inherited by the game. 
There is still an issue with those values being displayed in the option and becoming game specific when saved but that requires deeper changes.
