### ISSUE TITLE
Please remove non-free dependencies like unrar

### ISSUE THREAD

**Issue by 94b42c29dd** [lutris/lutris#1651]
I really like this project but i can't even install it without also installing non-free proprietary software like unrar. Why not use unar? Why is it not installable at all without also installing unrar? The user is literally being forced to install proprietary software to use this "open-source" product, which seems unethical to me.

**Comment by strycore** [comment]
We have removed unrar as a dependency already and next release won't need it.Hopefully, this will help with the inclusion in the Debian repositories.

**Comment by strycore** [comment]
There's a deb for the beta on the releases page btw if you want to install that instead.

**Comment by 94b42c29dd** [comment]
Thanks! Had not seen that it was removed already in beta. Keep up the good work!
