### ISSUE TITLE
Ability to add a wine runner

### ISSUE THREAD

**Issue by cazzoo** [lutris/lutris#166]
Hi there,

Trying to get Lutris as my main game launcher, I'm just wondering if we would be able to add wine / POL (PlayOnLinux) runner to the app so we can launch our game directly from Lutris.
I did not found any other way to do it with Linux (native) runner.

Any advices?

**Comment by Xodetaetl** [comment]
There's a Wine runner, you have to install it first from the Manage Runners window before it appears in the runners list when adding a game manually.

As for PoL, we've planned an auto-import tool of some sort.

**Comment by cazzoo** [comment]
Oh! I completely missed that part. And I discover much more runners that I missed too. Thanks!
