### ISSUE TITLE
Lutris duplicated Linux games

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1661]
![screenshot from 2019-01-23 20-06-16](https://user-images.githubusercontent.com/15083452/51653910-5aa03300-1f4a-11e9-9955-b9295648a5cd.png)

It didn't do it for all of them though.

```
DEBUG    2019-01-23 20:01:15,565 [pga_game.platform:67]:Setting platform for Euro Truck Simulator 2: Linux
DEBUG    2019-01-23 20:01:15,569 [pga_game.platform:67]:Setting platform for CS:GO: Linux
DEBUG    2019-01-23 20:01:15,573 [pga_game.platform:67]:Setting platform for Aragami: Linux
DEBUG    2019-01-23 20:01:15,577 [pga_game.platform:67]:Setting platform for Deus Ex: Human Revolution: Linux

**Comment by basxto** [comment]
For me that happened for games I’ve “installed” multiple times, once with winesteam and once via Steam Play

**Comment by AccountOneOff** [comment]
Aragami, CSGO, and Euro Sim 2 are native installs and have been installed since before Steam Play. Deus Ex HR is the only Steam Play game I have installed.

I removed them and this hasn't happened again. Closing.
