### ISSUE TITLE
Default profile icon is too large in UI

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1670]
![screenshot from 2019-01-27 03-14-32](https://user-images.githubusercontent.com/10602045/51794352-f39cab80-21e1-11e9-8bc6-7547c96b41c0.png)

**Comment by Medath** [comment]
I think the issue is with the default profile picture. It's probably larger than a custom one

**Comment by AccountOneOff** [comment]
@Medath Yup. Pic is 1080x1080

![screenshot from 2019-01-29 19-04-01](https://user-images.githubusercontent.com/15083452/51955401-a8101a80-23f8-11e9-9a75-707b150034f8.png)
