### ISSUE TITLE
Put profile pictures in a square with rounded corners

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1671]
This is what gnome settings does, for example:
![screenshot from 2019-01-27 03-18-03](https://user-images.githubusercontent.com/10602045/51794448-a5d57280-21e4-11e9-8676-fad32fb91a41.png)
Lutris does not do that:
![screenshot from 2019-01-27 03-14-32](https://user-images.githubusercontent.com/10602045/51794449-b38af800-21e4-11e9-963c-52b089eb15e7.png)

**Comment by strycore** [comment]
Because one is a button
The other is not
