### ISSUE TITLE
[Origin] Mouse Sensitivity Issue

### ISSUE THREAD

**Issue by JusttDan** [lutris/lutris#1672]
I've looked around for any information on this issue for a little while now but I've been unable to find a solution.

I installed Origin via lutris and then downloaded the games from within Origin as recommended; the problem I'm facing is that what ever game I download through Origin, be it Battlefield V, Battlefield 1 and even the new Anthem game which is running pretty smoothly apart from this mouse sensitivity issue.

This issue doesn't happen to any other game installed on my machine via steam or lutris so maybe it's something to do with the origin installation?

[Here](https://www.youtube.com/watch?v=Rm4LkIl1yPU) is a link to a video showing what the problem is, basically the left and up axis are more sensitive than the right and down axis, in the video I'm moving the mouse the exact same motion in each direction.

I'm running Manjaro Linux 18.02, Latest Nvidia Drivers (415.27). Any help would be awesome!

**Comment by strycore** [comment]
This has nothing to do with Lutris

**Comment by strycore** [comment]
Please use the forums or discord for that kind of support request
