### ISSUE TITLE
KDEInit could not launch 'lutris'

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1673]
Tried to set a desktop shortcut via the launcher yesterday (while setting up Word for my dad). And on KDE it won't launch, plasma will come up with this error:

```
KDEInit could not launch 'lutris':
Could not open library 'libkdeinit5_lutris'.
Cannot load library libkdeinit5_lutris: (libkdeinit5_lutris: cannot open shared object file: No such file or directory)
```

**Comment by telanus** [comment]
Not sure if we can close this. Seems only to happen on Kubuntu 18.04. I've upgraded to 20.04 and it no longer happens @tannisroot @strycore

**Comment by tannisroot** [comment]
Then it is most likely not our issue. Since bionic is quite old now I'm going to close it.
