### ISSUE TITLE
Have a home button

### ISSUE THREAD

**Issue by MrCraigen** [lutris/lutris#1675]
I tried out the v0.5.0rc1 release and i did a quick search for a game. Works perfect! But there is no way to get back to the main screen without using the left panel option that i rarely use. Maybe add a Home button on the right side for ease of use?

**Comment by Zeioth** [comment]
I also suggested this on Discord:

> Feature: Add a 'X' button on the search bar to go back to your installed games + clear the box.

**Comment by LiamDawe** [comment]
Yup, highly needed. I can't seem to get my normal list to appear after searching so I would appreciate this too.
