### ISSUE TITLE
[Feature Request] Make WebKit2 optional

### ISSUE THREAD

**Issue by pchome** [lutris/lutris#1679]
Disable GOG integration support if `WebKit2` isn't available.

Same for `GnomeDesktop`, maybe others.

_Otherwise lutris will turn into LutrisOS.
I had to install 0.1k dependencies just to see what lutris is, and another 0.1k to run 0.5 RC._

**Comment by strycore** [comment]
those are thin and necessary components.

(GnomeDesktop is a library, it's not the Gnome desktop)

**Comment by trite2k3** [comment]
omg thank you, I spent like three or four hours compiling all kinds of gnome-stuff that I dont even want before just going into the python files and removing the import lines for GnomeDesktop and Webkit2 and then changed it to first try LegacyDisplayManager and now it runs

thank god

**Comment by strycore** [comment]
How can you not install 2 simple dependencies? Why do have to make this super complicated.

**Comment by pchome** [comment]
@strycore 
> How can you not install 2 simple dependencies? Why do have to make this super complicated.

It's not "2 simple dependencies" for e.g. Gentoo.

It was the free built-in "Escape from The Python" game:
1. Installing available version (0.4.x) to make sure all dependencies are present -- compiling tons of dependencies, reinstalling some packages w/ `introspection` support -- OK
2. Trying to run -- it runs, OK, lets try `5.0` ...
3. Error: `GnomeDesktop` -- where it from? `gnome-base/gnome-desktop` -- OK,
  another ton of new dependencies, but ok
4. Error: `requests` -- is there an python package? -- `dev-python/requests` -- OK,
  new dependencies, but ok
5. Error: `PIL` -- wtf is `PIL`? -- `dev-python/pillow` likely, ...
6. Error: `Webkit2` ... hell, requires **Ruby** to be built, another ton of new dependencies, ...

I gave up on this step, this quest really pissed me off. Such a big difference between versions, for what? For GOG? But I don't even have an GOG account.

<hr/>

https://packages.gentoo.org/packages/games-util/lutris
> Changelog
> games-util/lutris: Maintainer retired

:thinking:

**Comment by TingPing** [comment]
Mostly a Gentoo problem. A maintainer would have solved the quest and well the fact it requires building from source will always suck.

I believe @strycore wanted more website integration in the future which will pull in WebKitGTK anyway.

**Comment by strycore** [comment]
This is Gentoo's fault and not my problem. I won't satisfy this request. As @TingPing pointed out, I plan to use those dependencies a lot more in the future.

You cannot just come here and ask me to remove components of my software. Respect my work.
