### ISSUE TITLE
FS-UAE hdf and CD

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1683]
Hi, Is there a way to get the fs-uae runner to auto-detect anything other than floppy in the "additional floppies" input window.
I know this is an corner problem that isn't that needed, but amigacd titles seem to need it.
something like http://hol.abime.net/2894 needs to be installed on a hdf and still have the cd in the drive to be "usable"

**Comment by strycore** [comment]
@telanus can you please test it? I don't know what games I can use to test.
