### ISSUE TITLE
On Ubuntu 16.04, with Lutris 0.5.0, a crash report appears when I try to open the Runners config.

### ISSUE THREAD

**Issue by Guy1524** [lutris/lutris#1690]
The error I get is
 `lutris crashed with GLib.GError in __init__(): gtk-builder-error-quark: /usr/share/lutris/ui/runners-dialog.ui:5:1 Required gtk+ version 3.20, current version is 3.18 (7)`

**Comment by strycore** [comment]
Ubuntu 16.04? Seriously? Fine... it's still supported, I guess.

**Comment by Aisyk** [comment]
Same error here with Xubuntu 16.04

**Comment by strycore** [comment]
that should be solved in 0.5.0.1
