### ISSUE TITLE
Replace tray icon implementation with StatusNotifier

### ISSUE THREAD

**Issue by TingPing** [lutris/lutris#1692]
Here is a snippet of how to check:

https://github.com/pithos/pithos/blob/6bf437ef59a057e90476bfe9464fdf9306c449da/pithos/plugins/notification_icon.py#L46-L66

Really since this was a new feature you should never have used `Gtk.StatusIcon` in the first place and only used a statusnotifier.

**Comment by strycore** [comment]
I didn't put the tray in place, I never wanted one.

**Comment by TingPing** [comment]
> I didn't put the tray in place, I never wanted one.

You are the maintainer you can and should say no sometimes.

**Comment by strycore** [comment]
People keep asking for one, as long as it's not enabled by default, I'm ok with having it. If there is a better implementation, I'm open to that. The tray code is really simple so it wouldn't be hard to replace it with something else

**Comment by strycore** [comment]
I've removed the current implementation of the tray icon using a StatusIcon.
If someone can submit a PR using a StatusNotifier that reliably works across desktop environments, I'll merge it.
Status Notifier on FreeDesktop: https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/

**Comment by strycore** [comment]
So far, our implementation works ok. We can close this until a more widely accepted standard comes along.
