### ISSUE TITLE
[GOG] Can't connect account due to reCaptcha error

### ISSUE THREAD

**Issue by poVoq** [lutris/lutris#1696]
When trying to connect to a GOG account I can't get pass the reCaptcha on the log in screen as there is always after a while a error that it can not connect.
In a regular browser it works without issues to log into GOG on the same connection.

**Comment by tannisroot** [comment]
Can you try reproducing it again? I am just unable to.

**Comment by tannisroot** [comment]
I will reopen if this is still an issue.
