### ISSUE TITLE
Do not show "Remove" for games that aren't installed

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1701]
During search, if you click on the game that isn't installed, in the right panel you will see "remove" button:
![screenshot from 2019-02-02 13-28-37](https://user-images.githubusercontent.com/10602045/52163196-f0c51d80-26ef-11e9-9dfb-d0c8a52587e6.png)
This should not be there because the game isn't installed.

**Comment by strycore** [comment]
no, this is normal. The Sims 4 is in your lutris library, thus the game can be removed from your library. There should be some better way to convey that information
