### ISSUE TITLE
Merge Steam and Winesteam services

### ISSUE THREAD

**Issue by nahsiy** [lutris/lutris#1710]
When you want to import games already installed on steam linux, it doesn't work.
the selection and button work but the games do not integrate / display.

![import_games](https://user-images.githubusercontent.com/6117458/52174479-7e5a4900-2794-11e9-84b8-5d51e80e298f.png)

**Comment by strycore** [comment]
what the fuck Yishan

**Comment by nahsiy** [comment]
it works for some games (ex: Darwin Project) but not for others (ex: mafia III, life is strange).
NB : life is strange has an installer for its steam linux version unlike mafia III.

**Comment by nahsiy** [comment]
Error on my part, the game is not natively supported on linux. I close.

**Comment by strycore** [comment]
your issue is perfectly valid.

**Comment by strycore** [comment]
We're getting rid of winesteam so this is no longer relevant.
