### ISSUE TITLE
Allow to select mutliple games

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#1711]
It would be great if you could select multiple games with help of shift and control key.
`Remove` is the most crucial action for multiple games. (e.g. delete all steam games and reimport)
But `Create desktop shortcut`/`Delete desktop shortcut`, `Create application menu  shortcut`/`Delete application menu  shortcut`, `Browse files` and `View on lutris.com` could also be useful for multiple games.

**Comment by ShayBox** [comment]
This needs to happen, it's so annoying having to remove every kde game from the list one at a time.
