### ISSUE TITLE
GOG: Add option to install game from local installer

### ISSUE THREAD

**Issue by sonicpp** [lutris/lutris#1714]
Lutris is downloading game installer from GOG website, but it would be nice to add option to install GOG game from local installer - especially for users with slow connection or if they downloaded installer from website before.

**Comment by sonicpp** [comment]
Bug #474  looks related, but it would be nice to bring this feature before version 0.6. I appreciate downloading installers from GOG server, but I also used to install GOG titles from my backup directory of installers.

**Comment by strycore** [comment]
This is already possible in Lutris 0.5.0.1, provide a location for the installer cache then create a folder with the same game identifier as used in lutris and put your GOG install files in a folder called gog (or whatever the installer is called). The lutris installer will pick up the local files.

**Comment by Medath** [comment]
This can be more intuitive though.

**Comment by piegamesde** [comment]
Hm, the workaround doesn't work for me, it just ignores and overwrites the existing files
