### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by bless-9** [lutris/lutris#1717]
after update getting this error.

Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available

using xfce4

**Comment by aqeeliz** [comment]
Same error, using archlinux, with plasma / KDE.

**Comment by omid3098** [comment]
At first, I thought I have the same problem but my python error is a bit different:
after last update, I can't open Lutris.
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 34, in <module>
    from lutris.game import Game
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 10, in <module>
    from lutris.gui.dialogs import FileDialog
  File "/usr/lib/python3.7/site-packages/lutris/gui/dialogs/__init__.py", line 6, in <module>
    from lutris.gui.widgets.utils import open_uri
  File "/usr/lib/python3.7/site-packages/lutris/gui/widgets/utils.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Arch x64
XFCE4

I guess my problem is somehow related to this one. If not, I can open a new issue.

**Comment by aqeeliz** [comment]
> At first, I thought I have the same problem but my python error is a bit different:
> after last update, I can't open Lutris.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/lutris", line 31, in <module>
>     from lutris.gui.application import Application
>   File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 34, in <module>
>     from lutris.game import Game
>   File "/usr/lib/python3.7/site-packages/lutris/game.py", line 14, in <module>
>     from lutris.runners import import_runner, InvalidRunner, wine
>   File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 10, in <module>
>     from lutris.gui.dialogs import FileDialog
>   File "/usr/lib/python3.7/site-packages/lutris/gui/dialogs/__init__.py", line 6, in <module>
>     from lutris.gui.widgets.utils import open_uri
>   File "/usr/lib/python3.7/site-packages/lutris/gui/widgets/utils.py", line 4, in <module>
>     from PIL import Image
> ModuleNotFoundError: No module named 'PIL'
> ```
> 
> Arch x64
> XFCE4
> 
> I guess my problem is somehow related to this one. If not, I can open a new issue.

Your problem appears to be different, it seems you need to install ```python-pillow```, but it all seems to arch package issue, new package not updating latest dependencies.

That being said, I don't think it should require Gnome Desktop, that won't be so good for us non-gnome users.

**Comment by omid3098** [comment]
> Your problem appears to be different, it seems you need to install python-pillow, but it all seems to arch package issue, new package not updating latest dependencies.
> 
> That being said, I don't think it should require Gnome Desktop, that won't be so good for us non-gnome users.

Thank you, however I Could not make it work, for now I rather roll back to 4.23

**Comment by strycore** [comment]
install Lutris as described on the downloads page
