### ISSUE TITLE
Found a few bugs with the spec file regarding fedora

### ISSUE THREAD

**Issue by andrewschott** [lutris/lutris#1725]
As I was getting ansy about the Fedora maintainer being "slow", I decided to roll a package up myself. 
 Found a few bugs with the spec file regarding Fedora.  Here are the offenders with the corrected line.  The corrected spec is in the SRPMS (linked below).  I used mock to generate them using the mock profiles of fedora-28-x86_64 and fedora-28-x86_64, should anyone care.

* Line 26 -- gnome-desktop3 is borked on f28 at least with regards to its provides.  Moved it to recommends and the package is installable.

```
%if 0%{?fedora}
BuildRequires:  python3-gobject, python3-wheel, python3-setuptools, python3-gobject
Requires:       python3-gobject, python3-PyYAML, cabextract
Requires:       gtk3, psmisc, xorg-x11-server-Xephyr, xorg-x11-server-utils
Requires:       python3-requests
Recommends:     wine-core, gnome-deskop3
```

* Line 93 -- variable %{name} is wrong, %{appid} needed instead.

```
%if 0%{?fedora} || 0%{?rhel} || 0%{?centos}
desktop-file-install --dir=%{buildroot}%{_datadir}/applications share/applications/%{appid}.desktop
desktop-file-validate %{buildroot}%{_datadir}/applications/%{appid}.desktop
%endif
```

Here are my repoview links to F28 & F29 repos with the built SRPM & RPM files for each
* https://schotty.com/yum/fedora/28/repoview/lutris.html
* https://schotty.com/yum/fedora/29/repoview/lutris.html

**Comment by strycore** [comment]
@andrewschott can you submit a PR with the fixes?
@BunnyApocalypse can you review that PR once it's submitted?

**Comment by andrewschott** [comment]
> @andrewschott can you submit a PR with the fixes?
> @BunnyApocalypse can you review that PR once it's submitted?

I am retarded when it comes to git PRs.  No joke.  I am not sure how to do that.

**Comment by strycore** [comment]
Fork the repo, clone it locally, create a new branch, change the lutris.spec file, commit, push ,create PR on github. That's it

**Comment by andrewschott** [comment]
Done, thanks for the handholding.  Got it sorted out.  Didn't think I needed to fork.

**Comment by BunnyApocalypse** [comment]
I have not been pushing changes in my spec file to this repository, should I be? The current Fedora package is in Fedora git.

Sorry for being "slow", but I can't respond quickly to something I don't know about, and I had heard no complaints about these things until just now.

I am able to install the current fedora testing repo build of Lutris (which has gnome-desktop3 as a requires) in a Fedora 28 mock session, so perhaps the borked provides are something local?

As to line 93, what is the difference between %{appid} and %{name}, it is very difficult to find documentation on rpm macros. The equivalent of that line is however different in Fedora's current spec which you can view here: https://src.fedoraproject.org/rpms/lutris/blob/master/f/lutris.spec

**Comment by andrewschott** [comment]
@bunnyapocalypse No, 2 days isn't slow.  That was a joke.  And who knows when the spec for the appid changed.  The build wasn't working and that was something that fixed the rpm build errors in mock.  This used to build just fine.  I know this, because I used it a few years back just fine.
Let me know if you want to just do the fix, and I can PR if not.

@strycore will fix when I get off work and will amend the PR if bunny wishes me to.

**Comment by andrewschott** [comment]
Oh, @bunny apocalypse, forgot, yes mock is happy on my end too with gnome-desktop3, dnf is not.  Three systems.

**Comment by BunnyApocalypse** [comment]
Hey @andrewschott, I just changed gnome-desktop3 to a recommends in the f28 branch for Lutris. As I am not on f28, and it is not borked in mock, could you tell me when that package starts working again for you?

**Comment by BunnyApocalypse** [comment]
As to the appid fix, I have not been pushing the Fedora spec changes to this repository, so if that's what this version of the spec file needs in order to function, the change lgtm. I was more asking what %{appid} evaluates to in this case, would that be `net.lutris.Lutris`?

**Comment by andrewschott** [comment]
> Hey @andrewschott, I just changed gnome-desktop3 to a recommends in the f28 branch for Lutris. As I am not on f28, and it is not borked in mock, could you tell me when that package starts working again for you?

Sorry for the delay, I have been stupid busy with work.  Apologies.

As for the changes, I made those to my rpms which are linked above, and the F28 one works fine on my two systems that can do games.  My one F29 rig is not for gaming as its a work unit, dual booting RHEL and Fedora.

I may have stated earlier or on the PR page, forget, that although my system has both the meta-packages of gnome-desktop and gnome-desktop3 installed, there is neither being "provided" on either of my two systems that I tried this on.

Perhaps its just me, but when things go wrong or hinkey, I think "What did I do wrong here?" rather than point the finger.  I couldn't figure out what (if) I did wrong.  So I am going to presume since your spec did work a few years back when I made a RHEL package with it, that its a bug somewhere in the metapackage from God knows when it was introduced.

As for the appid thing -- yes.  I played with this the most actually.  The .desktop file is there and happy everwhere else and is referenced with appid, not name.  I changed it, and it worked.   I figured this is alot easier than dealing with file renames and soforth.  Fixing the spec seemed easier to make a package of it.

And sorry again if I pissed you off with my joke.  Thought wrong here I guess :( Anyway, I like Fedora and RHEL because that extra day or three is taken to make sure stuff works correctly.  I was in no way trying to rush or insult you, rather just saying I was getting that twitch for the upgrade to play around with the new UI and features.  Which are awesome BTW.  I was also just chiming in with a minor bug for those that may have been interested in a self build too.  Glad you are willing to work with me to iron it out -- even with the still alive possibility that its all me.

**Comment by andrewschott** [comment]
@strycore OK, I made the fixes you and asciiwolf requested/demanded and they are live on my branch now and yield working (S)rpms.  How do I resolve them in github?

**Comment by strycore** [comment]
There's just one change needed and it will be good to merge

**Comment by andrewschott** [comment]
@strycore Cool.  Thanks.  As aforementioned, new to this :D  And I presume the remaining one is the appid one?  And that would be @BunnyApocalypse 's call, correct?

**Comment by strycore** [comment]
no, it's moving the gnome-desktop3 to Requires, also fix the appid thing if that's needed.

**Comment by andrewschott** [comment]
> no, it's moving the gnome-desktop3 to Requires, also fix the appid thing if that's needed.

You mean recomends?  OK.  Didnt see it on the PR changes list, everything else besides the appid thing was marked as resolved.

**Comment by strycore** [comment]
Yes, I closed it by mistake then re-opened it. It's at the bottom.

**Comment by andrewschott** [comment]
I feel stupid.  Look at the current spec in your repo : gnome-desktop3 is misspelled there too.  I apparently didnt notice and copied it around not seeing that it was the misspelling that was at fault.  Fixing the spelling removes the problem.  So aside from what else was recommended to fix suse issues, its just the appid thing thats actually left.  

I noticed it when going over the PR changes, and the original had the typo.  Looked and facepalmed hard.  That saying about you assume .... 

I pushed a fixed spec file that builds perfect and installs perfect.  Will update my repo in a moment.

**Comment by BunnyApocalypse** [comment]
It's no problem, I wasn't insulted or anything and probably shouldn't have been snarky in my response. It's just hard to tell what's a joke and what's someone being an asshat/having unreasonable expectations, especially when I've interacted with people who would complain about that being slow unironically.

Unfortunately, %{appid} doesn't seem to evaluate that way in my rawhide mock at least, in fact it doesn't seem to evaluate at all :( Is it perhaps a nonstandard macro?

**Comment by andrewschott** [comment]
Not sure -- first time I can recall seeing it.  It was there in the spec prior to me touching things.  But since my interest has most certainly been piqued, I tryed adding in an echo prior to the desktop file installation commands (the spot that I changed things), and here is what I did:
```
%if 0%{?fedora} || 0%{?rhel} || 0%{?centos}
echo LOOK HERE --- appid --- %{appid}
echo LOOK HERE --- name --- %{name}
desktop-file-install --dir=%{buildroot}%{_datadir}/applications share/applications/%{appid}.desktop
desktop-file-validate %{buildroot}%{_datadir}/applications/%{appid}.desktop
%endif
```
And this is what was spat out:
```
+ continue
+ read _file
LOOK HERE --- appid --- net.lutris.Lutris
LOOK HERE --- name --- lutris
+ echo LOOK HERE --- appid --- net.lutris.Lutris
+ echo LOOK HERE --- name --- lutris
+ desktop-file-install --dir=/builddir/build/BUILDROOT/lutris-0.5.0.1-7.fc28.x86_64/usr/share/applications share/applications/net.lutris.Lutris.desktop
+ desktop-file-validate /builddir/build/BUILDROOT/lutris-0.5.0.1-7.fc28.x86_64/usr/share/applications/net.lutris.Lutris.desktop
```

And of course, this is what happens if I try to figure out what the hell this macro does:
```
[andrew@schotty-tower-wired rpmbuild]$ rpm --eval "%{appid}"
%{appid}
[andrew@schotty-tower-wired rpmbuild]$ 
```

I am still working on googling the macro, but everything that turns up is stale/dead links to github pages that mostly just no longer exist.  I will be hitting up reddit and some of my chums at Red Hat and see if anyone is able to say WTF this does.  My recollection was there were some things that needed to be done for the GNOME app store (or whatever its called) for the display images and description and soforth.   Was hoping that the Fedora pages would have some useful details.  But I haven't found much more than you.

**Comment by BunnyApocalypse** [comment]
Yeah, in my mock environment, even when adding things like that echo, it still stays un-evaluated.

**Comment by andrewschott** [comment]
F me.

Its defined in the spec.  Line 6, up top above the package name declaration.

**Comment by duckartes** [comment]
Broken in Gentoo, unsure what package is needed.

https://gitweb.gentoo.org/repo/gentoo.git/tree/games-util/lutris/lutris-9999.ebuild

**Comment by scottchiefbaker** [comment]
I installed `gnome-desktop3` as suggested on Fedora running Plasma and now I get:

    ValueError: Namespace WebKit2 not available

Must be another dependency I'm missing?

**Comment by BunnyApocalypse** [comment]
@strycore, what dependency could this be?

**Comment by andrewschott** [comment]
@scottchiefbaker : the package would be *webkit2gtk3* if I can tell correctly.  But from what I can tell here it is something that is stock in a GNOME3 install of Fedora.  But I could be wrong.  Alot of GNOME3 apps need this dependency.  Try an install of *webkit2gtk3* and see if that resolves things.  A simple addition if so.  The evidence I have at hand is below.  And also why I am not going to try removing it and seeing if things break for Lutris.  Moot point -- my whole system will shit itself I think lol

		[andrew@schotty-tower-wired ~]$ dnf repoquery --available --alldeps --whatrequires webkit2gtk3
		Last metadata expiration check: 0:13:23 ago on Sat 16 Feb 2019 08:49:07 PM CST.
		anjuta-1:3.28.0-1.fc28.i686
		anjuta-1:3.28.0-1.fc28.x86_64
		atril-0:1.20.1-1.fc28.x86_64
		atril-0:1.20.3-1.fc28.x86_64
		atril-libs-0:1.20.1-1.fc28.i686
		atril-libs-0:1.20.1-1.fc28.x86_64
		atril-libs-0:1.20.3-1.fc28.i686
		atril-libs-0:1.20.3-1.fc28.x86_64
		balsa-0:2.5.3-7.fc28.x86_64
		balsa-0:2.5.6-3.fc28.x86_64
		bijiben-0:3.28.1-1.fc28.x86_64
		bijiben-0:3.28.4.1-1.fc28.x86_64
		cairo-dock-plug-ins-webkit-0:3.4.1-21.fc28.x86_64
		capnet-assist-0:0.2.1-6.fc28.x86_64
		cinnamon-screensaver-unsupported-0:3.6.1-4.fc28.noarch
		devhelp-1:3.28.1-1.fc28.i686
		devhelp-1:3.28.1-1.fc28.x86_64
		devhelp-libs-1:3.28.1-1.fc28.i686
		devhelp-libs-1:3.28.1-1.fc28.x86_64
		eclipse-swt-1:4.7.3a-4.fc28.x86_64
		eclipse-swt-1:4.7.3a-5.fc28.x86_64
		elementary-capnet-assist-0:2.2.3-1.fc28.x86_64
		emacs-1:25.3-5.fc28.x86_64
		emacs-1:26.1-3.fc28.x86_64
		empathy-1:3.12.14-5.fc28.x86_64
		epiphany-runtime-1:3.28.1-1.fc28.x86_64
		epiphany-runtime-1:3.28.5-1.fc28.x86_64
		evolution-0:3.28.1-2.fc28.x86_64
		evolution-0:3.28.5-2.fc28.x86_64
		evolution-bogofilter-0:3.28.1-2.fc28.x86_64
		evolution-bogofilter-0:3.28.5-2.fc28.x86_64
		evolution-data-server-0:3.28.1-2.fc28.i686
		evolution-data-server-0:3.28.1-2.fc28.x86_64
		evolution-data-server-0:3.28.5-1.fc28.i686
		evolution-data-server-0:3.28.5-1.fc28.x86_64
		evolution-data-server-tests-0:3.28.1-2.fc28.i686
		evolution-data-server-tests-0:3.28.1-2.fc28.x86_64
		evolution-ews-0:3.28.1-1.fc28.x86_64
		evolution-ews-0:3.28.5-2.fc28.x86_64
		evolution-mapi-0:3.28.1-1.fc28.x86_64
		evolution-mapi-0:3.28.3-2.fc28.x86_64
		evolution-pst-0:3.28.1-2.fc28.x86_64
		evolution-pst-0:3.28.5-2.fc28.x86_64
		evolution-rspam-0:0.6.0-21.fc28.x86_64
		evolution-rss-1:0.3.95-17.fc28.x86_64
		evolution-rss-1:0.3.95-18.fc28.x86_64
		evolution-spamassassin-0:3.28.1-2.fc28.x86_64
		evolution-spamassassin-0:3.28.5-2.fc28.x86_64
		exfalso-0:4.0.2-3.fc28.noarch
		exfalso-0:4.2.1-1.fc28.noarch
		feedreader-0:2.0.2-1.fc26.x86_64
		feedreader-0:2.6.2-1.fc28.x86_64
		geany-plugins-markdown-0:1.34-1.fc28.x86_64
		geary-0:0.12.1-1.fc28.x86_64
		geary-0:0.12.4-1.fc28.x86_64
		glade-libs-0:3.22.1-1.fc28.i686
		glade-libs-0:3.22.1-1.fc28.x86_64
		gnome-boxes-0:3.28.2-1.fc28.x86_64
		gnome-boxes-0:3.28.5-1.fc28.x86_64
		gnome-builder-0:3.28.1-1.fc28.i686
		gnome-builder-0:3.28.1-1.fc28.x86_64
		gnome-builder-0:3.28.4-1.fc28.i686
		gnome-builder-0:3.28.4-1.fc28.x86_64
		gnome-initial-setup-0:3.28.0-6.fc28.x86_64
		gnome-online-accounts-0:3.28.0-1.fc28.i686
		gnome-online-accounts-0:3.28.0-1.fc28.x86_64
		gnome-online-accounts-0:3.28.1-1.fc28.i686
		gnome-online-accounts-0:3.28.1-1.fc28.x86_64
		gnucash-0:3.0-1.fc28.x86_64
		gnucash-0:3.4-1.fc28.x86_64
		gphotoframe-0:2.0.2-3.hg2084299dffb6.fc28.4.noarch
		gthumb-1:3.6.1-1.fc28.i686
		gthumb-1:3.6.1-1.fc28.x86_64
		gthumb-1:3.6.2-1.fc28.i686
		gthumb-1:3.6.2-1.fc28.x86_64
		libgepub-0:0.6.0-1.fc28.i686
		libgepub-0:0.6.0-1.fc28.x86_64
		liferea-1:1.12.2-1.fc28.x86_64
		liferea-1:1.12.4-1.fc28.x86_64
		midori-0:0.5.12-0.2.fc26.i686
		midori-0:0.5.12-0.2.fc26.x86_64
		nemo-preview-0:3.6.0-4.fc28.x86_64
		nemo-preview-0:4.0.0-2.fc28.x86_64
		nuvolaruntime-0:4.11.0-1.fc28.i686
		nuvolaruntime-0:4.11.0-1.fc28.x86_64
		nuvolaruntime-0:4.9.0-1.fc28.i686
		nuvolaruntime-0:4.9.0-1.fc28.x86_64
		osmo-0:0.4.2-2.fc28.x86_64
		pantheon-online-accounts-0:0.3.0.1-7.20170417.git5a0270a.fc28.x86_64
		pantheon-online-accounts-0:0.3.1-1.fc28.x86_64
		pantheon-online-accounts-libs-0:0.3.0.1-7.20170417.git5a0270a.fc28.i686
		pantheon-online-accounts-libs-0:0.3.0.1-7.20170417.git5a0270a.fc28.x86_64
		pantheon-online-accounts-libs-0:0.3.1-1.fc28.i686
		pantheon-online-accounts-libs-0:0.3.1-1.fc28.x86_64
		pantheon-photos-0:0.2.4-5.fc28.x86_64
		perl-Gtk3-WebKit-0:0.06-12.fc28.noarch
		pix-0:1.6.1-4.fc28.i686
		pix-0:1.6.1-4.fc28.x86_64
		pix-0:1.8.2-1.fc28.i686
		pix-0:1.8.2-1.fc28.x86_64
		rednotebook-0:2.4-1.fc28.noarch
		rednotebook-0:2.8-1.fc28.noarch
		rubygem-webkit2-gtk-0:3.2.1-2.fc28.noarch
		rubygem-webkit2-gtk-0:3.3.1-1.fc28.noarch
		scratch-text-editor-0:2.4.1-9.fc28.i686
		scratch-text-editor-0:2.4.1-9.fc28.x86_64
		shotwell-0:0.28.2-1.fc28.i686
		shotwell-0:0.28.2-1.fc28.x86_64
		shotwell-0:0.28.4-1.fc28.i686
		shotwell-0:0.28.4-1.fc28.x86_64
		sugar-0:0.112-2.fc28.noarch
		sugar-browse-0:201.2-3.fc28.noarch
		sugar-toolkit-gtk3-0:0.112-4.fc28.i686
		sugar-toolkit-gtk3-0:0.112-4.fc28.x86_64
		surf-0:2.0-4.fc28.x86_64
		sushi-0:3.24.0-4.fc28.x86_64
		sushi-0:3.28.3-1.fc28.x86_64
		switchboard-plug-onlineaccounts-0:0.3.0.1-7.20170417.git5a0270a.fc28.x86_64
		switchboard-plug-onlineaccounts-0:0.3.1-1.fc28.x86_64
		vfrnav-0:20180129-2.fc28.i686
		vfrnav-0:20180129-2.fc28.x86_64
		vocal-0:2.1.6-2.fc28.x86_64
		vocal-0:2.3.0-1.fc28.x86_64
		webkit2-sharp-0:0-0.6.20170219gita59fd76.fc28.x86_64
		webkit2-sharp-0:0-0.7.20170219gita59fd76.fc28.x86_64
		webkit2gtk3-devel-0:2.20.1-1.fc28.i686
		webkit2gtk3-devel-0:2.20.1-1.fc28.x86_64
		webkit2gtk3-devel-0:2.22.5-1.fc28.i686
		webkit2gtk3-devel-0:2.22.5-1.fc28.x86_64
		webkit2gtk3-doc-0:2.20.1-1.fc28.noarch
		webkit2gtk3-doc-0:2.22.5-1.fc28.noarch
		wxGTK3-webview-0:3.0.4-1.fc28.i686
		wxGTK3-webview-0:3.0.4-1.fc28.x86_64
		xiphos-0:4.0.7-5.fc28.x86_64
		xiphos-0:4.1.0-2.fc28.x86_64
		xreader-0:1.6.2-2.fc28.i686
		xreader-0:1.6.2-2.fc28.x86_64
		xreader-0:2.0.2-1.fc28.i686
		xreader-0:2.0.2-1.fc28.x86_64
		yelp-2:3.28.1-1.fc28.x86_64
		yelp-libs-2:3.28.1-1.fc28.i686
		yelp-libs-2:3.28.1-1.fc28.x86_64
		[andrew@schotty-tower-wired ~]$ 

		[andrew@schotty-tower-wired ~]$ dnf repoquery --available --alldeps --whatrequires gnome-desktop3
		Last metadata expiration check: 0:13:54 ago on Sat 16 Feb 2019 08:49:07 PM CST.
		cheese-2:3.28.0-1.fc28.x86_64
		cheese-libs-2:3.28.0-1.fc28.i686
		cheese-libs-2:3.28.0-1.fc28.x86_64
		eog-0:3.28.1-2.fc28.i686
		eog-0:3.28.1-2.fc28.x86_64
		eog-0:3.28.4-1.fc28.i686
		eog-0:3.28.4-1.fc28.x86_64
		evince-0:3.28.2-1.fc28.x86_64
		evince-0:3.28.5-1.fc28.x86_64
		evolution-0:3.28.1-2.fc28.x86_64
		evolution-0:3.28.5-2.fc28.x86_64
		evolution-bogofilter-0:3.28.1-2.fc28.x86_64
		evolution-bogofilter-0:3.28.5-2.fc28.x86_64
		evolution-pst-0:3.28.1-2.fc28.x86_64
		evolution-pst-0:3.28.5-2.fc28.x86_64
		evolution-spamassassin-0:3.28.1-2.fc28.x86_64
		evolution-spamassassin-0:3.28.5-2.fc28.x86_64
		gala-0:0.3.1-0.1.20180318.gita71e8c1.fc28.x86_64
		gala-0:0.3.1-0.7.20180910.git2995cd6.fc28.x86_64
		gnome-clocks-0:3.28.0-1.fc28.x86_64
		gnome-contacts-0:3.28.1-1.fc28.x86_64
		gnome-contacts-0:3.28.2-1.fc28.x86_64
		gnome-control-center-0:3.28.1-2.fc28.x86_64
		gnome-control-center-0:3.28.2-1.fc28.x86_64
		gnome-desktop3-devel-0:3.28.1-1.fc28.i686
		gnome-desktop3-devel-0:3.28.1-1.fc28.x86_64
		gnome-desktop3-devel-0:3.28.2-1.fc28.i686
		gnome-desktop3-devel-0:3.28.2-1.fc28.x86_64
		gnome-desktop3-tests-0:3.28.1-1.fc28.x86_64
		gnome-desktop3-tests-0:3.28.2-1.fc28.x86_64
		gnome-directory-thumbnailer-0:0.1.10-1.fc28.x86_64
		gnome-documents-libs-0:3.28.0-1.fc28.x86_64
		gnome-documents-libs-0:3.28.2-1.fc28.x86_64
		gnome-font-viewer-0:3.28.0-1.fc28.x86_64
		gnome-initial-setup-0:3.28.0-6.fc28.x86_64
		gnome-screensaver-0:3.6.1-20.fc28.x86_64
		gnome-session-0:3.28.1-1.fc28.x86_64
		gnome-settings-daemon-0:3.28.1-1.fc28.i686
		gnome-settings-daemon-0:3.28.1-1.fc28.x86_64
		gnome-shell-0:3.28.1-2.fc28.x86_64
		gnome-shell-0:3.28.3-1.fc28.x86_64
		gnome-software-0:3.28.1-1.fc28.i686
		gnome-software-0:3.28.1-1.fc28.x86_64
		gnome-software-0:3.28.2-4.fc28.i686
		gnome-software-0:3.28.2-4.fc28.x86_64
		gnome-tweaks-0:3.28.1-1.fc28.noarch
		lutris-0:0.5.0.1-6.fc28.noarch
		mutter-0:3.28.1-1.fc28.i686
		mutter-0:3.28.1-1.fc28.x86_64
		mutter-0:3.28.3-4.fc28.i686
		mutter-0:3.28.3-4.fc28.x86_64
		mutter-tests-0:3.28.1-1.fc28.x86_64
		mutter-tests-0:3.28.3-4.fc28.x86_64
		nautilus-0:3.28.1-1.fc28.i686
		nautilus-0:3.28.1-1.fc28.x86_64
		pitivi-0:0.99-3.fc28.x86_64
		switchboard-plug-display-0:0.1.3-6.fc28.x86_64
		switchboard-plug-pantheon-shell-0:0.2.6-7.fc28.x86_64
		switchboard-plug-pantheon-shell-0:2.8.0-1.fc28.x86_64
		totem-1:3.26.0-7.fc28.i686
		totem-1:3.26.0-7.fc28.x86_64
		totem-1:3.26.2-1.fc28.i686
		totem-1:3.26.2-1.fc28.x86_64
		[andrew@schotty-tower-wired ~]$

**Comment by scottchiefbaker** [comment]
I'm running KDE/Plasma so it would make sense I don't have Gnome stuff installed.

**Comment by strycore** [comment]
Please note that I have updated the INSTALL file in the repo to list the currently needed PYGObject bindings and other required python3 packages.

**Comment by scottchiefbaker** [comment]
Just so it's written down...

`yum gnome-desktop3 webkit2gtk3`

was require for me to get lutris 0.5.x running on Fedora running Plasma

**Comment by strycore** [comment]
Please re-open if there is still stuff to be done.
