### ISSUE TITLE
Lutris crash on nvidia driver info check

### ISSUE THREAD

**Issue by TheEdward162** [lutris/lutris#1729]
Hello,

today I updated lutris and now it won't launch
```
$ lutris -d
INFO     2019-02-05 21:47:28,538 [application.do_command_line:222]:Running Lutris 0.5.0
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 223, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.6/site-packages/lutris/startup.py", line 106, in run_all_checks
    check_driver()
  File "/usr/lib/python3.6/site-packages/lutris/startup.py", line 41, in check_driver
    driver_info = drivers.get_nvidia_driver_info()
  File "/usr/lib/python3.6/site-packages/lutris/util/graphics/drivers.py", line 26, in get_nvidia_driver_info
    'version': gcc_version[2],
IndexError: list index out of range
INFO     2019-02-05 21:47:28,540 [application.do_shutdown:439]:Shutting down Lutris
```

My /proc/driver/nvidia/version file
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  410.93  Thu Dec 20 17:01:16 CST 2018
GCC version:  Selected multilib: .;@m64
```
Seems like it doesn't have the expected format (GCC version is missing). I am running on Void Linux and had to install the drivers through nvidia driver installer from their site because void nvidia package conflicts with void mesa package and I have a hybrid laptop.

Anyway it would be great if the driver check failed a little more gracefully than this. Thanks.

**Comment by AlexanderRavenheart** [comment]
This was fixed in commit `ce16279`. Try the latest version from master branch.

**Comment by TheEdward162** [comment]
Not working. If you look at the stacktrace I have, it's throwing an error on line 41 of startup.py, the fix only touches the `get_nvidia_driver_info` on line 62.

**Comment by strycore** [comment]
We don't use that GCC stuff so I removed it
