### ISSUE TITLE
Insufficient detection of DRI_PRIME

### ISSUE THREAD

**Issue by petr666** [lutris/lutris#1732]
Hi,
I've found problem with detection of DRI_PRIME. Implementation counts occurences of "VGA" in lspci output, however on my notebook (Thinkpad with discrete AMD GPU) output of lspci looks like this:

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
05:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Jet XT [Radeon R5 M240]

therefore should also look for occurence of "Display" string.

**Comment by sonicpp** [comment]
Hi, should be fixed by commit https://github.com/lutris/lutris/commit/f448d1bf4033850f6c78dfae4ac4d47e2a501b77 (has been just merge an hour ago :) )

**Comment by sonicpp** [comment]
[petr666](/petr666): is that fix working for you? My testing notebook has similar setup as yours, your cards should be catch by "VGA" and "Display controller" strings.

**Comment by petr666** [comment]
Sorry for late reply, but yes, this fix is working for me. Thanks.

**Comment by tannisroot** [comment]
Closing as it's now fixed.
