### ISSUE TITLE
lsof is not always in the user's $PATH

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#174]
On my system (Mageia 5, 64bit), I get this kind of errors when running lutris from a terminal:
```
ERROR    2015-04-04 16:51:10,104 [system]:Could run command ['lsof', '-t', '/home/akien/.local/share/lutris/runners/wine/1.7.39-i386/bin/wine']: [Errno 2] No such file or directory
```

It seems indeed that on my distro, the lsof binary is located in /usr/sbin/lsof, i.e. it's not in the user's $PATH but it's meant to be used by root. I can't tell if it's a packaging mistake in Mageia, but at least Fedora also has lsof in /usr/sbin instead of /usr/bin.

Even if it's not in the $PATH, you should be able to call explicitly /usr/sbin/lsof with user privileges though, but then you need to find a way that would work both on distros with lsof in /usr/bin or in /usr/sbin (maybe use a ```try``` block to check the PATH first and if not fallback to /usr/sbin?).

**Comment by Xodetaetl** [comment]
I replaced lsof with fuser but it too is in /sbin/ in Mageia, so I made Lutris fall back on it.

**Comment by akien-mga** [comment]
I do have /usr/bin/fuser on Mageia 5, and /usr/sbin/fuser is a symlink to the /usr/bin one.

But I guess the fallback does not hurt :)

**Comment by Xodetaetl** [comment]
Fair enough, I looked on Mageia 4. ;)
