### ISSUE TITLE
How to run multiple instance on 0.5.0.1?

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1740]
>Hello, prior to 0.5.0 the right click menu had a “Play” option even if an instance was running, at least for wine apps.
On 0.5.0 the “Play” option turns into “Stop” if an instance is running.
How can I have multiple instances of same install running now?

https://forums.lutris.net/t/how-to-run-multiple-instance-on-0-5-0/4980

**Comment by strycore** [comment]
this is no longer possible

**Comment by elijahrj1** [comment]
Worked on pop!_os by making a desktop icon, switching to a new workspace, then running it. Can also move window up to starting workspace.

**Comment by strycore** [comment]
> Worked on pop!_os by making a desktop icon, switching to a new workspace, then running it. Can also move window up to starting workspace.

 
![922593062050476052](https://github.com/lutris/lutris/assets/280336/a3d1d076-4747-4dbd-9b0a-59863ec30d71)
