### ISSUE TITLE
Update banner and icon when they're updated on the site

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1741]
If a banner is updated on the site it doesn't update for a game already installed. This also applies to the game icon even when there is none.

E.g. Maniaplanet uses the old banner and has no icon despite me adding one.

https://lutris.net/games/maniaplanet/

![screenshot from 2019-02-08 22-50-23](https://user-images.githubusercontent.com/15083452/52517702-03f65280-2bf4-11e9-87fe-a6e97b389f1a.png)

**Comment by strycore** [comment]
it should update. the problem I'm facing right now is that the banner get updated even when other stuff like published state gets changed.
