### ISSUE TITLE
Move "Use PRIME" out of advanced options

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1749]
This is not really an advanced feature and many people will look for it to use dedicated graphics in their games instead of relying on integrated graphics.

**Comment by strycore** [comment]
It is an advanced feature. Can we default to enabling prime by default instead?

**Comment by tannisroot** [comment]
Yeah but I don't get why something like DLL overrides is not an advanced feature while such commonly used and needed feature as PRIME is.

**Comment by sonicpp** [comment]
There should be no side effects when setting DRI_PRIME=1 environment even for GPUs not supporting this feature or for single GPU setup as far as I know. But it may confuse players with single GPU - it will show PRIME enabled with no option to disable it...

**Comment by tannisroot** [comment]
PRIME is currently greyed out if you don't have a second GPU, so it's not an issue,

**Comment by sonicpp** [comment]
I know, but my point was that if we enable it by default, it will be shown as enabled (even though you have single GPU system).

**Comment by tannisroot** [comment]
Despite "Enable Feral Gamemode" being enabled by default when it's present on the system, it's disabled when it's not present.

**Comment by sonicpp** [comment]
Yes, that is what I meant. In that case I vote for enabling it by default too :)

**Comment by strycore** [comment]
I still don't understand why this is an advanced feature, you should need to set this one, in the system options and be done with it.

**Comment by tannisroot** [comment]
> you should need to set this once

Well, this can be applied to pretty much any option in Lutris.
From **my perspective**, advanced options are those options that are not essential and meant to not be tampered with (as that may cause issues) if you are just a regular user and don't really know what you're doing, which is why they are hidden by default. 
I don't consider PRIME option something that can mess up your games (if you don't have Hybrid graphics you won't even be able to enable it) and it's **quite essential** as enabling the use of dedicated GPU can bring massive performance boost. So in a way, it's in the same category as Feral's Gamemode.

**Comment by strycore** [comment]
so it's just a matter of having it enabled by default.

**Comment by tannisroot** [comment]
Well yeah, that would be nice too. But PRIME option is really something the user will look for after they install Lutris for the first so it would be nice to show the user that it's already enabled, as they might try and do it manually through envar menu.

**Comment by strycore** [comment]
Prime should now be enabled by default.
