### ISSUE TITLE
Installation procedures should continue when downloaded file is already in cache

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#175]
When trying to patch Age of Empires II: Age of Kings (with an edited installer to remove the "requires" field because of #172), I get the following error if I already have the required patch in my cache:
```
Error("Destination path '/home/akien/.cache/lutris/aokpatch2a-crk.exe' already exists",)
```

Lutris should be able to handle this without throwing an error, and continue the installation (maybe by forcing the overwrite of the cached file, since the new one is downloaded anyway).

**Comment by Xodetaetl** [comment]
I can't reproduce this. The old file gets overwritten for me. Did @strycore stealth fixed it ?
