### ISSUE TITLE
Lutris give error when trying to lunch a game

### ISSUE THREAD

**Issue by in1t3r** [lutris/lutris#1750]
Lutris show modular window with error when try to run hearthstone. 
It was working few days. 

this is a paste of error when started with lutris -d
snippet on the dpaste.de will last only 7 days I include here the output as its not long 
https://dpaste.de/37Ka

lutris -d

(lutris:24455): Gtk-WARNING **: 01:32:27.702: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:24455): Gtk-WARNING **: 01:32:27.702: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:24455): Gtk-WARNING **: 01:32:27.702: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO     2019-02-12 01:32:27,737 [application.do_command_line:222]:Running Lutris 0.5.0.1
INFO     2019-02-12 01:32:27,740 [startup.check_driver:43]:Using NVIDIA drivers 410.93 for x86_64
INFO     2019-02-12 01:32:27,741 [startup.check_driver:47]:GPU: GeForce GT 710
INFO     2019-02-12 01:32:27,741 [startup.check_driver:64]:GPU: 10DE:128B 1462:8C93 using nvidia drivers
INFO     2019-02-12 01:32:27,784 [startup.check_vulkan:87]:Vulkan is supported
INFO     2019-02-12 01:32:27,785 [dxvk.get_dxvk_versions:24]:Updating DXVK versions

(lutris:24455): Gtk-WARNING **: 01:32:27.898: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:24455): Gtk-WARNING **: 01:32:27.898: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:24455): Gtk-WARNING **: 01:32:27.898: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
DEBUG    2019-02-12 01:32:28,177 [http.get:64]:GET https://lutris.net/api/runtime
DEBUG    2019-02-12 01:32:31,244 [application.launch:339]:Adding game Hearthstone (wine) (139813812943104) to running games
DEBUG    2019-02-12 01:32:31,252 [game.play:257]:Prelaunching <lutris.runners.wine.wine object at 0x7f28f053a6d8>
ERROR    2019-02-12 01:32:31,377 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f28f053a6d8>>: [Errno 117] Structure needs cleaning: '/media/in1t3r/storage/Games/hearthstone/drive_c/users/in1t3r/My Documents'
<class 'OSError'> [Errno 117] Structure needs cleaning: '/media/in1t3r/storage/Games/hearthstone/drive_c/users/in1t3r/My Documents'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 675, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 805, in sandbox
    desktop_dir=self.runner_config.get("sandbox_dir")
  File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 100, in desktop_integration
    os.makedirs(path, exist_ok=True)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
ERROR    2019-02-12 01:32:31,378 [game.configure_game:274]:[Errno 117] Structure needs cleaning: '/media/in1t3r/storage/Games/hearthstone/drive_c/users/in1t3r/My Documents'
ERROR    2019-02-12 01:33:19,976 [game.configure_game:277]:Game prelaunch unsuccessful

**Comment by strycore** [comment]
> [Errno 117] Structure needs cleaning

That's a weird error you have here, make sure the path /media/in1t3r/storage/Games/hearthstone/drive_c/users/in1t3r/My Documents is ok and also make sure you're not using a NTFS drive.
