### ISSUE TITLE
Broken on Gentoo.

### ISSUE THREAD

**Issue by duckartes** [lutris/lutris#1751]
```
$ lutris

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib64/python3.6/site-packages/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
```

https://gitweb.gentoo.org/repo/gentoo.git/tree/games-util/lutris/lutris-9999.ebuild

**Comment by strycore** [comment]
This ebuild is outdated, please update it with the latest dependencies. You can find them in debian/control in the sources of the project. (In this case you'll need the Python GObject bindings for GnomeDesktop and Webkit2, and also install the python3 packages Pillow and requests)

I'm not sure there's a current maintainer for Gentoo, the package page says the last maintainer retired in 2018 so I'm not sure how to get the ebuild updated, maybe you can ask around in the Gentoo community.

**Comment by strycore** [comment]
Also the ebuild still uses tar.gz archives, we don't ship those anymore and the Python version has to be updated to Python 3.7

**Comment by PythonicChemist** [comment]
@strycore maybe we should request gentoo wiki to take down its Lutris page since it was completely written by you-know-who.

**Comment by strycore** [comment]
I would but I have no idea who to talk to when it comes to Gentoo. It's even worse than trying to reach SUSE.

**Comment by cnd** [comment]
There is some pull request for Lutris on Gentoo: https://github.com/gentoo/gentoo/pull/10749
(I'd suggest taking ebuild from that PR into local overlay for testing and cooperate with that request and people around it to finish it faster)

Wiki is open for editing for anyone, you can find package maintainer with email inside metadata.xml file near actual ebuild.

**Comment by hanetzer** [comment]
@strycore Yo. Dude working on the lutris fixup; you say there are no longer *.tar.gz archives
but I still see them under code->releases here, or am I missing something? Would have had
this done sooner but I nuked my machine on accident.

**Comment by strycore** [comment]
@hanetzer the only archive you need to package lutris should be https://lutris.net/releases/lutris_0.5.0.1.tar.xz 
where are you seeing tar.gz archives?

**Comment by hanetzer** [comment]
Here. https://github.com/lutris/lutris/releases

**Comment by strycore** [comment]
I've never used those for packaging, I push the archives to lutris.net

**Comment by hanetzer** [comment]
Gotcha.  I can change the location we use easily enough for [gentoo/gentoo#10749](https://github.com/gentoo/gentoo/pull/10749)

**Comment by hanetzer** [comment]
Oof. On second thought, I didn't realize lutris_0.5.0.1.tar.xz unpacks to lutris instead of
lutris-0.5.0.1 like the github ones do. Unsure if gentoo folks would want that.

**Comment by strycore** [comment]
you can use whichever release is the best fit for you
