### ISSUE TITLE
GOG Login Window Completely Grey

### ISSUE THREAD

**Issue by nephitejnf** [lutris/lutris#1753]
The GOG Login window for importing games is not loading the site for me, or whatever is supposed to load. This is the output I get:
```
Unable to init server: Could not connect: Connection refused

(WebKitWebProcess:30177): Gtk-WARNING **: 03:06:59.368: cannot open display:
```

**Comment by tannisroot** [comment]
I personally can't reproduce it? Possibly an issue with optimus (on Discord this person has Hybrid Graphics and Nvidia roles).

**Comment by strycore** [comment]
this report is incomplete.
