### ISSUE TITLE
Do not set DRI_PRIME to 0 if hybrid graphics are not detected

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1758]
Currently, Lutris will set DRI_PRIME to 0 if it can't detect dedicated GPU, which is pretty bad as a bug in the detection of hybrid graphics (like https://github.com/lutris/lutris/issues/1732) will make it impossible to set DRI_PRIME envar to 1 manually through envar menu (Lutris will override manually set value and set it to 0 anyway) and workaround such bug in Lutris, thus making it impossible to use dedicated GPU for games installed through Lutris.
What Lutris should do instead is just not set DRI_PRIME to anything if it can't detect hybrid graphics.

**Comment by sonicpp** [comment]
Agree. Do you have any example of bug in detection of hybrid graphics? (bug #1732 is already fixed).

**Comment by tannisroot** [comment]
Well, not at the moment, but in case a similar bug appears, it would be nice if we had a workaround option available.

**Comment by ririen** [comment]
I confirm as another person that there is such an error. In earlier versions, `DRI_PRIME` worked correctly. I've tried to use Lutris 0.5 lately and the game does not see/work the variable `DRI_PRIME=1` at all.
