### ISSUE TITLE
Download and use Lutris' default Wine version if it's not specified in installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1760]
Currently, if wine version is not specified in the installer (which is now pretty much all of the popular ones), Lutris will either use wine that is installed in the system or any Lutris build that is already downloaded.
This may create very serious issues as wine that is installed on the system may not be compatible with the game or the Lutris build that got autopicked is a special one that should not be used with other games (for example, sims 2 wine build).
Instead, Lutris should always download and use its default Wine build (currently it's tkg-4.1) for installers that don't specify any particular version.

**Comment by sonicpp** [comment]
I don't like this solution. If the game needs special Wine version, it should be specified by the installer. Lutris default Wine will not help you - there might be games which will work better with system Wine than with Lutris Wine.

I prefer current behavior where Lutris tries to use as much as possible of system installed software.

**Comment by Medath** [comment]
I think being able to specify something like `tkg-latest`, `latest`, `tkg-sims2-latest`, etc would be better.

Not specifying wine versions should be avoided unless the game in question has been running perfectly for years already (at which point using some old system wine version would not be problematic).

**Comment by sonicpp** [comment]
Running perfectly for years does not mean it is not broken in current release. Development versions suffer from regressions and for staging releases it is even worse (if you dont have good reason to take staging - ie for specific patch or performance - keep away from it). I would take stable release in that case.

But still, keeping distribution version is better option in my opinion.

**Comment by tannisroot** [comment]
>here might be games which will work better with system Wine than with Lutris Wine
Well then we need to figure out what is the reason for that and implement it in a separate Lutris build. Would be nice if you could give examples?
> I prefer current behavior where Lutris tries to use as much as possible of system installed software
Thing is, some installer just may not work if the user is using gallium-nine build of Wine or wine without staging patches.

**Comment by strycore** [comment]
We are going to make Lutris default to the build specified by the API. (currently tkg-4.1)
I'm also going to make sure that if the system wine is set as the default version then this won't be overridden but this won't be the default behavior. You'll have to go in the wine and winesteam options and set the build to system.

**Comment by strycore** [comment]
> I think being able to specify something like `tkg-latest`, `latest`, `tkg-sims2-latest`, etc would be better.

I will reject anything that goes in that direction.

**Comment by strycore** [comment]
Wait, that may have come out wrong. What I'm against is this idea that you need to assign a particular Wine version for games to run. Wine TkG 4.1 runs 99% of all Windows games, period. We'll figure out the necessary of the remaining 1% of games and specify the version on their installers. Yes, it *will* be possible to just specify a build type like "tkg" or "protonified" and in those cases, Lutris will automatically get whatever is the latest build of that type. We are NOT going to use a "latest" tag because latest IS the default (well not really, the default is whatever I set it to in the API but I'm supposed to keep it up to date with the current Wine version)
