### ISSUE TITLE
Packaging: OpenSUSE tumbleweed issue

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1761]
Sharing https://github.com/PhoenicisOrg/scripts/pull/783#issuecomment-463306885

Abadoning issue, additional info won't be provided for reasons on https://github.com/RXT067/Research/tree/master/WINE-Dishonored2#lutris + previous conflict

**Comment by tannisroot** [comment]
From what I understand, openSUSE package is missing `gtk` and `gnomedesktop` as dependencies?
Not really much we can do, you should notify downstream about it.

**Comment by tannisroot** [comment]
Would be nice if the maintainer of the openSUSE package joined our Discord like Arch maintainer did. It's easier to communicate this way.

**Comment by strycore** [comment]
These dependencies are already present in the spec file:

```
Requires:       (python3-gobject-Gdk or python3-gobject)
Requires:       python3-PyYAML, cabextract, typelib-1_0-Gtk-3_0
Requires:       typelib-1_0-GnomeDesktop-3_0, typelib-1_0-WebKit2-4_0, typelib-1_0-Notify-0_7
```
