### ISSUE TITLE
Reccomended wine config for games

### ISSUE THREAD

**Issue by fjsaezm** [lutris/lutris#1764]
Hey there
I'm having trouble to play games using lutris. I suspect that it must be a problem with my packages/libraries that I have installed in my system. 
Can anybody give me a tutorial of the packages that I must have installed to play games?
I am running the latest version of antergos, and I'm trying to play MTG Arena and Hearthstone, to be more specific.
Thank you!

**Comment by tannisroot** [comment]
This page has some good tips: https://github.com/lutris/lutris/wiki/Wine-Dependencies

**Comment by strycore** [comment]
Install Wine with the method described on WineHQ and you'll be fine.
