### ISSUE TITLE
Cache mismatch

### ISSUE THREAD

**Issue by loaderini** [lutris/lutris#1766]
So far, I found that this error affects the following games:
**_King's Quest I: Quest for the Crown [ADG Remake]
King's Quest II: Romancing the Stones (2002)_**

I've tried to install the game again and again, but it's always the same error: 

> Source does not exist
[https://i.imgur.com/8p3maHY.png](url)

I did _not_ change the install path. It's also not possible to ignore the error, as the installation instructions say, because the only available buttons are 'close' and 'cancel' and they both remove the game. At the time of the error, the game is downloaded in the `.cache/lutris/installer` folder but there is no _AGD Interactive_ folder neither in Program Files nor in Program Files (86).

I used `lutris -d` and this is what I got during installation: https://pastebin.com/5D3PU8As

My computer:
Ubuntu 18.04 x64 (I also have enabled x32 and x64 architecture for Lutris)
CPU AMD FX 6350
RAM 16 GBytes
GPU Nvidia Geforce 1050 Ti
WineHQ staging 4.1 installed

**Comment by strycore** [comment]
Those games used create_prefix without the arch being set to win32, which was later expected. The prefixes were initially 32 bit by default and got migrated automatically but since those are AGS games and not wine game,we missed those.

**Comment by loaderini** [comment]
I just discovered that this same problem also exists for King's Quest III: To Heir is Human (2011), Same message: "`Source does not exist: /home/loaderini/.cache/lutris/installer/kings-quest-iii-to-heir-is-human-2011/drive_c/Program Files/AGD Interactive/King's Quest III Redux`"

I used Lutris 5.1.3
