### ISSUE TITLE
gzdoom command-line

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1769]
I'm trying to get [Doom: The Golden Souls 2](https://www.moddb.com/mods/doom-the-golden-souls-2) to run.

I have it running via terminal, but trying to launch it from Lutris normally end with gzdoom saying it can't find the palette. Tracked down the problem down on how Lutris is sending gzdoom the command-line. 

On the terminal I have it running via: 

`gzdoom -iwad doom2.wad -file GoldenSouls2_1.3.pk3`

but in lutris it uses:

```
  "command": [
    "/usr/games/gzdoom",
    "-iwad",
    "/Games/Linux/GoldenSouls2_1.3/GoldenSouls2_1.3.pk3"
  ]
```

Specifying the '-iwad doom2.wad' as an argument doesn't solve it as lutris sends it as:

```
  "command": [
    "/usr/games/gzdoom",
    "-iwad",
    "/Games/Linux/GoldenSouls2_1.3/GoldenSouls2_1.3.pk3",
    "-iwad",
    "doom2.wad"
  ]
```

the way I "fixed" i is to select Doom.wad and add `-file /Games/Linux/GoldenSouls2_1.3/GoldenSouls2_1.3.pk3` as an argument, but it's not intuitive, and there is no real way a user will know this.

**Comment by RobLoach** [comment]
Isn't there an option in the UI Game options on gzdoom to change the file argument? 


Thought we added that....

**Comment by RobLoach** [comment]
![screenshot at 2019-02-16 11-13-53](https://user-images.githubusercontent.com/25086/52902208-f6d0f900-31db-11e9-9b47-07893cb05167.png)

**Comment by strycore** [comment]
is it good now? seems so
