### ISSUE TITLE
Double click on an installed game launches the game twice

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#177]
But a single click does not launch the game :-)

**Comment by strycore** [comment]
Does this happen on all of your installed games? I had the same issue and wrote a fix for it, but it may not be robust enough so i'll check it again.

**Comment by akien-mga** [comment]
Ah you are right, in only happens with one game actually, Warcraft III: Reign of Chaos. If I double click on it the game starts, but it also brings a second window in the background that complains that the game is already started.

I've tried Warcraft III: The Frozen Throne, StarCraft Anthology, Age of Empires II: The Age of Kings and Age of Empires II: The Conquerors, and those behave fine when double clicked.

**Comment by akien-mga** [comment]
I've compared the settings I was using for Warcraft III: Reign of Chaos and the other games, and it looks like I was running RoC in a virtual desktop with the resolution forced to 1920x1080. Changing that back to no virtual desktop and no resolution change seems to fix the issue.

**Comment by Xodetaetl** [comment]
Well, that wasn't (just) it. I'm experiencing the bug randomly with wine games at least.

**Comment by strycore** [comment]
This is weird, I have also experienced this bug and, at this time, have no idea how it happens. Needs deeper inspection.

**Comment by DafabHoid** [comment]
I'm experiencing this bug now also with version 0.4.18, on Kubuntu 18.04.
Steps to reproduce: Choose a game, go to "Configure", tab "System Options" and set "Switch resolution to" to something different from "keep current". After that, start the application either by double-click or right-click -> play. It starts twice (the second starts after the resolution has changed).
Reverting the resolution switch setting fixes the problem.
