### ISSUE TITLE
Don't remove installation files after cancelling installation if another installer is open

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1773]
How to reproduce:
1. Use an installer that downloads files (like https://lutris.net/games/the-sims/)
2. Start the installation, continue until installer downloads installation files (which happens after selecting installation directory)
3. After that, without cancelling existing installation, use the same installer and repeat step 2
4. Cancel the first installation and close the window.

As a result, Lutris removes installation files in `~./cache/lutris/installer/`, and the other installer doesn't execute correctly and errors out due to missing files.

In the log, I see:
```Removing folder /home/alex/.cache/lutris/installer/the-sims```
So perhaps, the issue could be resolved by giving each installer instance a unique name for the cache folder. So instead of just `the-sims`, it could be `the-sims-654656654`.

**Comment by strycore** [comment]
don't install the same game twice at the same time.

**Comment by Medath** [comment]
This bug was found because a streamer accidentally had the same installer opened twice (one of which he closed again after noticing it), which caused the installer to fail due to missing files at a later point.
I know you closed this issue already, but I submitted a fix for it anyway.

**Comment by tannisroot** [comment]
@strycore really? It's clearly a bug.

**Comment by tannisroot** [comment]
No. That's not the right way to do this. A user (The Linux Gamer) was hella pissed of because of this and couldn't install a game properly, and that's very bad.
This needs to be fixed (https://github.com/lutris/lutris/pull/1786 should do it).

**Comment by tannisroot** [comment]
I think the priority of this bug was somewhat misjudged as I've found that quite a few users have suffered from it and got very frustrated (including someone I know well from VKx). I am going to change the milestone to 0.5.1, and if you still think it's _that_ low priority, just change it back to what it was.

**Comment by strycore** [comment]
This is handled by #1908
