### ISSUE TITLE
Weird white artifacting around the Lutris icon in the installer window

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1777]
You can see it at the upper left corner here:
![image](https://user-images.githubusercontent.com/10602045/52911233-23574480-32b2-11e9-994c-234c29d4ddd7.png)
Honestly, not sure if this is some sort of a GTK bug (as Arch got updated to the new version) or something is borked on my installation.

**Comment by txtsd** [comment]
Works for me on Arch on a dark theme.
Did you install from git or from AUR?

**Comment by legluondunet** [comment]
is this problem still relevant today?

**Comment by strycore** [comment]
this seems to be some theme issue, closing

**Comment by strycore** [comment]
Actually no, not a theme issue. But we have redone the icon since then.
