### ISSUE TITLE
Add "rename" task

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1778]
Would be very useful as it would allow to avoid issues in case sensitive filesystems.

**Comment by Medath** [comment]
Is the [move command](https://github.com/lutris/lutris/blob/master/docs/installers.rst#moving-files-and-directories) not able to do that?

**Comment by strycore** [comment]
Yes, move is used for renaming

**Comment by tannisroot** [comment]
Oh, so it's like Unix' mv, ok.
