### ISSUE TITLE
0.94 DXVK only version available.

### ISSUE THREAD

**Issue by duckartes** [lutris/lutris#1785]
lutris -d

> INFO     2019-02-19 07:43:42,844 [application.do_command_line:222]:Running Lutris 0.5.0.1
> INFO     2019-02-19 07:43:42,845 [startup.check_driver:43]:Using NVIDIA drivers 415.27 for x86_64
> INFO     2019-02-19 07:43:42,845 [startup.check_driver:47]:GPU: GeForce GTX 1060
> INFO     2019-02-19 07:43:42,846 [startup.check_driver:64]:GPU: 10DE:1C60 1043:1800 using nvidia drivers
> INFO     2019-02-19 07:43:42,865 [startup.check_vulkan:87]:Vulkan is supported
> INFO     2019-02-19 07:43:42,866 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
> DEBUG    2019-02-19 07:43:42,988 [http.get:64]:GET https://lutris.net/api/runtime
> ERROR    2019-02-19 07:43:51,444 [dxvk.init_dxvk_versions:46]:HTTP Error 403: Forbidden

![image](https://user-images.githubusercontent.com/31091259/53019622-c4610f00-341a-11e9-8f9f-4c559aca5d5f.png)

I manually downloaded 0.96 and placed it in ~/.local/share/lutris/runtime/dxvk but it still doesn't show up.

**Comment by duckartes** [comment]
I did set it to manual and from the console I see a:

> info:  DXVK: v0.96

It would be nice to have some visual information about what is selected though.

**Comment by Alexander88207** [comment]
I can't reproduce this error using lutris 0.5.0.1
![unknown](https://user-images.githubusercontent.com/37543796/53037662-1043a080-347b-11e9-8a8d-13112b354a79.png)

**Comment by strycore** [comment]
you probably have some networking issue because the DXVK version didn't load

**Comment by strycore** [comment]
oh wait, I noticed the HTTP Error 403: Forbidden
yeah, no clue but it's not on our side.

**Comment by duckartes** [comment]
Just checked again. It resolved and a list of versions are available.
