### ISSUE TITLE
Add the option to choose between multiple exe files when launching a game

### ISSUE THREAD

**Issue by skyace65** [lutris/lutris#1795]
Some games come with multiple exe files and I think it's important to be able to choose which to launch. For example Civilization 4 The Complete Edition from GOG has 4 exe files, one for the base game, one for the the Warlords expansion, one for the Beyond the Sword expansion, and one for the standalone game Civ 4 Colonization. Another game with multiple exe files is Alpha Centauri, and while I can't confirm this I'd guess Quake: The Offering and Quake II: Quad Damage from GOG are the same.

**Comment by tannisroot** [comment]
This is also true for Sims 2. The game has bajilion expansions and all have a different path.

**Comment by skyace65** [comment]
Good idea. I think for games like the sims 2 where there's a lot of exe files you should be able to prompt the user to choose which they want. But for games like Civ where we're only talking about 4 exe files you should be able to write a installer that gives the user a list to choose from.

**Comment by strycore** [comment]
This is basically what that "Execute script" functionality was supposed to be except that the patches I received were not at all thought with that in mind. 

Guess I'm up to delete and cleanup that feature and re-implement the whole thing......

**Comment by strycore** [comment]
This is implemented although there is no UI for it (it might be added at a later stage)
This is currently used with GOG installers that provide multiple launch configurations. 
It's also possible to add `launch_configs` in the `game` section of an installer.
