### ISSUE TITLE
Lutris sometimes displays the game 2 times after installation

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1799]
I can't reliably reproduce this but this happened to other users as well (but when importing games).
Restarting Lutris gets rid of the duplicate.
Some terminal output I got when that happened: https://paste.ubuntu.com/p/hcqYrhcYrg/

**Comment by tannisroot** [comment]
I am going to move this to website issues as started after some changes to the website were done and it was not happening when 0.5.0.1 launched.

**Comment by strycore** [comment]
is this still happening on master?

**Comment by tannisroot** [comment]
Yes.

**Comment by tannisroot** [comment]
Honestly, I am not even sure this is a client issue, as the issue wasn't present during 0.5.0.1 launch and it only started happening after some work on the website was done when Dashboard was launched.

**Comment by strycore** [comment]
ok, so this ticket some repro steps before it can be fixed.

**Comment by tannisroot** [comment]
It can't be reliably reproduced. You just have to keep installing games in a same client instance until you encounter it. It should not take a lot of installation though.

**Comment by tannisroot** [comment]
I can't reliably reproduce this. You just have to open a new instance of Lutris and keep installing games by clicking "Install" on the website until you encounter it.
For example, I was lucky to encounter it on the first try:
![peek 2019-03-03 13-02](https://user-images.githubusercontent.com/10602045/53693730-81f1e780-3db5-11e9-9eea-1cbe6e683dab.gif)

**Comment by strycore** [comment]
ok then so you and @AccountOneOff are going to have to fight because you want incompatible things. :laughing: 

(see cemu ticket)

**Comment by tannisroot** [comment]
But it's not related at all?
The issue is that when I install any game (doesn't matter if I have it installed already or not) instead of adding 1 entry into the library, it adds 2 identical ones. And the duplicate actually disappears if I relaunch Lutris.

**Comment by tannisroot** [comment]
Also I am pretty sure @AccountOneOff encountered this bug and doesn't like it either.

**Comment by AccountOneOff** [comment]
I know what file it is I just don't know how the fuck to edit it.

**Comment by nephitejnf** [comment]
I have multiple duplicates of native linux games that pop up when I run lutris, It grows at some times and stays the same at other, this is with the games I installed using pacman or just downloading the GOG installers and installing them myself. I first noticed this after updating some of my other packages, which included games.
In some cases for me it seems to double the icons. Again, steam games or games installed via lutris don't show this same behavior.
https://paste.ee/p/3MK98

**Comment by legluondunet** [comment]
Hello, I can confirm this bug. I updated Lutris from today's github version and my list games, installed or not, showed two or more thumbs. And if I try to remove another thumb appearing..

![Capture d’écran de 2019-03-13 09-17-05](https://user-images.githubusercontent.com/325405/54263388-03453900-4571-11e9-92f9-4a27bcadb635.png)

**Comment by legluondunet** [comment]
my lutris log
[lutris.log](https://github.com/lutris/lutris/files/2960562/lutris.log)

**Comment by mbc3** [comment]
This has happened to me as well, but the duplicates remain unless I manually delete them. If I do that and restart, the duplicate entries return, and sometimes with one or two more entries.

![lutris_dups](https://user-images.githubusercontent.com/48695249/54560592-e7ca9b80-497f-11e9-9360-2d710524f4fc.png)

**Comment by tannisroot** [comment]
If somebody could find the cause of this, I would really appreciate it.

**Comment by mbc3** [comment]
looking at my lutris.log,  I believe this bug has something to do with the following line:

 [ERROR:2019-03-18 23:08:26,370:startup]: Providing missing platorm for game sunless-skies

also, I'm assuming that "platorm" is a typo and it should be "platform."

**Comment by erikwatson** [comment]
This is still an issue for me, many of the games I have installed are being displayed twice. 
I'm running 0.5.7.1, which certainly has the 8aa7251 fix applied - I checked.

**Comment by AlexanderRavenheart** [comment]
@erikwatson Confirming an issue is still present and should be reopened using an older release of Lutris is not valid.
If the issue is present in the latest release (https://github.com/lutris/lutris/releases/tag/0.5.8) then it should be reopened, otherwise not.

**Comment by strycore** [comment]
0.5.7.1 is now unsupported
