### ISSUE TITLE
GOG HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by daretmavi** [lutris/lutris#1801]
I wanted to import witcher 3 from my gog account into lutris, but it didn't work.
Installation script (GOTY Version) asked for game data, so I downloaded them manually.

Then the script stopped working (No ask for data). I found out it suddenly has HTTP Error 400: Bad Request error (in konsole). "Import Games ..." menu stopped working (window is not opening) as well (with the same error).

Error from console:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 70, in get
>     request = urllib.request.urlopen(req, timeout=self.timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 179, in <lambda>
>     "sync-local": Action(lambda *x: self.open_sync_dialog()),
>   File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 493, in open_sync_dialog
>     SyncServiceWindow(application=self.application)
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 329, in __init__
>     sync_row = ServiceSyncBox(service, self)
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 53, in __init__
>     self._connect_button_toggle()
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 144, in _connect_button_toggle
>     if self.service.is_connected():
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 238, in is_connected
>     return GOG_SERVICE.is_available()
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 70, in is_available
>     user_data = self.get_user_data()
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 151, in get_user_data
>     return self.make_api_request(url)
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 141, in make_api_request
>     self.request_token(refresh_token=token["refresh_token"])
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 99, in request_token
>     request.get()
>   File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 72, in get
>     raise HTTPError("Unavailable url %s: %s" % (self.url, error))
> lutris.util.http.HTTPError: Unavailable url https://auth.gog.com/token?client_id=46899977096215655&client_secret=9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9&grant_type=refresh_token&refresh_token=Eg4P0FUtiI5u4Q3MRkPuycpVcQXhXOszruFPpeRl5UCyXI8SaTwi1DpTj5gO3rDv: HTTP Error 400: Bad Request
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> FileNotFoundError: [Errno 2] Adresár alebo súbor neexistuje: '/var/crash/_usr_bin_lutris.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 70, in get
>     request = urllib.request.urlopen(req, timeout=self.timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 179, in <lambda>
>     "sync-local": Action(lambda *x: self.open_sync_dialog()),
>   File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 493, in open_sync_dialog
>     SyncServiceWindow(application=self.application)
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 329, in __init__
>     sync_row = ServiceSyncBox(service, self)
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 53, in __init__
>     self._connect_button_toggle()
>   File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 144, in _connect_button_toggle
>     if self.service.is_connected():
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 238, in is_connected
>     return GOG_SERVICE.is_available()
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 70, in is_available
>     user_data = self.get_user_data()
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 151, in get_user_data
>     return self.make_api_request(url)
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 141, in make_api_request
>     self.request_token(refresh_token=token["refresh_token"])
>   File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 99, in request_token
>     request.get()
>   File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 72, in get
>     raise HTTPError("Unavailable url %s: %s" % (self.url, error))
> lutris.util.http.HTTPError: Unavailable url https://auth.gog.com

> /token?client_id=46899977096215655&client_secret=9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9&grant_type=refresh_token&refresh_token=Eg4P0FUtiI5u4Q3MRkPuycpVcQXhXOszruFPpeRl5UCyXI8SaTwi1DpTj5gO3rDv: HTTP Error 400: Bad Request

Removing ~/.cache/lutris/ helped.

**Comment by tannisroot** [comment]
Seems like a result of regional blocking or GOG's website just derped out.
Let me know if this happens again.

**Comment by JeanFred** [comment]
I ran into a similar issue:
* GOG integration had been configured (and working) months ago.
* Recently, clicking the “Import Games” was resulting in nothing apparent
* With `lutris -d` was the following:
```
DEBUG    2019-08-08 17:09:03,810 [http.get:64]:GET https://auth.gog.com/token?client_id=<XXX>&client_secret=YYY&grant_type=refresh_token&refresh_token=ZZZZ
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 70, in get
    request = urllib.request.urlopen(req, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 179, in <lambda>
    "sync-local": Action(lambda *x: self.open_sync_dialog()),
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 493, in open_sync_dialog
    SyncServiceWindow(application=self.application)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 329, in __init__
    sync_row = ServiceSyncBox(service, self)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 53, in __init__
    self._connect_button_toggle()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/services.py", line 144, in _connect_button_toggle
    if self.service.is_connected():
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 238, in is_connected
    return GOG_SERVICE.is_available()
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 70, in is_available
    user_data = self.get_user_data()
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 151, in get_user_data
    return self.make_api_request(url)
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 141, in make_api_request
    self.request_token(refresh_token=token["refresh_token"])
  File "/usr/lib/python3/dist-packages/lutris/services/gog.py", line 99, in request_token
    request.get()
  File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 72, in get
    raise HTTPError("Unavailable url %s: %s" % (self.url, error))
lutris.util.http.HTTPError: Unavailable url https://auth.gog.com/token?client_id=XXXX&client_secret=YYY&grant_type=refresh_token&refresh_token=ZZZZ: HTTP Error 400: Bad Request
```

Based on the above post, I deleted `~/.cache/lutris/.gog.token`, and it solved the issue.

**Comment by tannisroot** [comment]
Perhaps we need to autoresolve these issues with .gog.token somehow.
