### ISSUE TITLE
Inconsistent Sorting

### ISSUE THREAD

**Issue by hikaricore** [lutris/lutris#1805]
Lutris: 0.5.0.1
Linux Kernel: 4.18.0-15-generic
Distro: Ubuntu 18.10

To whom it may concern,

I've found an odd inconsistency in the ordering of game titles which is only corrected by switching the view mode from banner/icons to list. The corrected ordering is retained after switching back from list to banner/icon view, but is lost upon restarting Lutris. If Lutris is started in list mode instead of banner/icon mode, the sorting inconsistency does not occur. Attached are screenshots showing the behavior. We can see that all titles with "A " (A then a space) are sorted as if the article itself is part of the first word. So the ordering goes as follows:

A Boy and His Blob (ABoy and His Blob)
A Hat in Time (AHat in Time)
Alice: Madness Returns

A Story About My Uncle (AStory About My Uncle) appears after Armello which based on the prior ordering due to the inconsistency is completely logical.

[https://i.imgur.com/oHYgdg7.png](https://i.imgur.com/oHYgdg7.png)

If we toggle to list view (and optionally back) we can see the ordering is as follow:

A Boy and His Blob
A Hat in Time
A Story About My Uncle
Alice: Madness Returns

[https://i.imgur.com/AUQWJYO.png](https://i.imgur.com/AUQWJYO.png)

After the toggle the ordering function respects the space following the article "A" and does not discard it when sorting game titles. Again if I start Lutris up IN list mode already, the inconsistency doesn't occur.

[https://i.imgur.com/nBAHTJo.png](https://i.imgur.com/nBAHTJo.png)

This matter aside, one wonders if sorting should be done by ignoring the articles (A, An, The) entirely as is standard across nearly all forms of media, but it would be nice to see this fixed if nothing else.  :)

Thank you kindly for your time,

--hikaricore

**Comment by 7HEPOW** [comment]
Just found a similar problem with the play time:
![190304 012948](https://user-images.githubusercontent.com/35022098/53704455-12afde00-3e1d-11e9-9b53-d6d9a814fcad.png)

**Comment by strycore** [comment]
Bug with playtime is now fixed, still working on the name sorting problem in the grid view

**Comment by matoro** [comment]
The bug in playtime seems to have regressed at some point:

![2019-05-18-224459_389x637_scrot](https://user-images.githubusercontent.com/12038583/57977104-b5104400-79be-11e9-9007-a9bd232251ec.png)

Could this be re-addressed?
