### ISSUE TITLE
cant play any games

### ISSUE THREAD

**Issue by rezad1393** [lutris/lutris#181]
Hi
I have installed lutris in archlinux (tried both normal and git version)
When I open any game added to lutris the window that opens ,closes very fast after opening.
and in lutris it says the game is running.

I see in the Ksysguard that the game runner is running in zommbie mode.

how do I fix this?

**Comment by Xodetaetl** [comment]
Hi, can you run the normal version with `lutris -d` in a terminal, start a game and copy-paste the terminal output here ?

**Comment by rezad1393** [comment]
[me@mypc ~]$ lutris -d 
DEBUG    2015-04-16 19:54:08,321 [lutris]:Welcome to Lutris
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkImageMenuItem:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkImageMenuItem:image is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.                                                   
  self.builder.add_from_file(ui_filename)                                                                                 
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.                                                   
  self.builder.add_from_file(ui_filename)                                                                                 
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkEntry:primary-icon-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.                                              
  self.builder.add_from_file(ui_filename)                                                                                 
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkEntry:secondary-icon-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.                                            
  self.builder.add_from_file(ui_filename)                                                                                 
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkContainer:resize-mode is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
/usr/lib/python2.7/site-packages/lutris/gui/lutriswindow.py:66: Warning: The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(ui_filename)
DEBUG    2015-04-16 19:54:08,391 [lutriswindow]:Getting game list
DEBUG    2015-04-16 19:54:08,414 [lutriswindow]:Switching view
DEBUG    2015-04-16 19:54:08,426 [lutriswindow]:Connecting signals
INFO     2015-04-16 19:54:08,535 [lutriswindow]:Connected as reza
DEBUG    2015-04-16 19:54:08,536 [jobs]:Async call: sync_all
DEBUG    2015-04-16 19:54:08,537 [sync]:Syncing game library
DEBUG    2015-04-16 19:54:08,537 [jobs]:Async call: update_runtime
DEBUG    2015-04-16 19:54:08,537 [sync]:4 games in local library
DEBUG    2015-04-16 19:54:08,539 [api]:Fetching game library
DEBUG    2015-04-16 19:54:10,978 [sync]:2 games in remote library (inc. unpublished)
DEBUG    2015-04-16 19:54:10,980 [sync]:0 games updated
DEBUG    2015-04-16 19:54:10,980 [sync]:Syncing local steam games
DEBUG    2015-04-16 19:54:11,027 [jobs]:Async call: sync_icons
DEBUG    2015-04-16 19:54:11,027 [resources]:Fetching icons
DEBUG    2015-04-16 19:54:12,102 [game]:Launching sor: {'command': ['/home/me/.local/share/lutris/runners/gens/gens', '--window', '--game', '/media/shared/downloads/Streets of Rage 3.zip']}
DEBUG    2015-04-16 19:54:12,103 [thread]:Thread running: ['/home/me/.local/share/lutris/runners/gens/gens', '--window', '--game', '/media/shared/downloads/Streets of Rage 3.zip']
DEBUG    2015-04-16 19:54:22,107 [game]:game has quit at Thu, 16 Apr 2015 19:54:22
DEBUG    2015-04-16 19:54:28,451 [lutriswindow]:Quitting lutris
[me@mypc ~]$

**Comment by Xodetaetl** [comment]
Ok, it's a problem with our runtime, which is currently in a half-broken state, depending on your system environment. Gens won't work as well as some other emulators and Linux games. It's a bit involving to work around this manually (especially for Gens due to the way we packaged it) so you'd better wait for the next version of the client which will be much more stable overall.

**Comment by rezad1393** [comment]
just so we are clear this issue happens on any game (not just emulators). like civ5 too.
I like this lutris overall idea, so when can I expect a usable one?

**Comment by Xodetaetl** [comment]
> just so we are clear this issue happens on any game (not just emulators). like civ5 too.

Hm. The Git version has an option to turn disable the runtime, you can try that, it should help with Steam and Wine games. `Lutris > Preferences > Disable Lutris Runtime`
You'll have to enable it again when the runtime is fixed.

> I like this lutris overall idea, so when can I expect a usable one?

A few days to a couple weeks if you're using the git version.

**Comment by rezad1393** [comment]
thanks 
that helped.
I  eagerly await the better versions.

**Comment by Xodetaetl** [comment]
Alright, the new runtime is in place ! You can ask the AUR package's maintainer to update if you want to try it out now.
Let me know how it works for you.

**Comment by rezad1393** [comment]
my internet connection is really shitty. can you tell me how can I update the runtime manually?(with url )
I get timeout when updating it.

**Comment by Xodetaetl** [comment]
Yes, download the [32](http://ovocean.com/partage/lutris/runtime/steam-runtime_32.tar.gz) and [64-bit](http://ovocean.com/partage/lutris/runtime/steam-runtime_64.tar.gz) archives and extract them in `~/.local/share/lutris/runtime`
Then create a text file named `VERSION` in this same folder with `1429566475` as contents.

**Comment by rezad1393** [comment]
that folder ~/.local/share/lutris/runtime/ should be like this?:
"lib32  lib64  steam  VERSION"
if so then this update doesn't solve my issue

**Comment by Xodetaetl** [comment]
lib32 and lib64 should be gone after you've launched Lutris. If they are still here, you don't have the last version. The AUR hasn't been updated, did you use that or updated with git directly ?

**Comment by rezad1393** [comment]
i use this https://aur.archlinux.org/packages/lutris-git/

**Comment by Xodetaetl** [comment]
> i use this https://aur.archlinux.org/packages/lutris-git/

Yep, and it's nearly up to date, but not enough to make use of the new runtime. :)

**Comment by rezad1393** [comment]
what do you mean ? isn't git the most updated version?

**Comment by Xodetaetl** [comment]
No, this lutris-git package for Arch, despite what its name may imply, is not updated automatically whenever we add code here. It's updated by the maintainer frequently but as we can see on the page, the last update was last monday so he's got some lag. :)

**Comment by strycore** [comment]
@Xodetaetl I believed that at first but lutris-git does pull the source from the master at any given point in time and is not restrained to the revision in AUR

**Comment by Xodetaetl** [comment]
Ah, right, the package is just a build script pointing to the git repo. So when you install it, you get the last version. But is it kept up to date automatically once installed ? What triggers the update ?

Btw @rezad1393, did you re-enabled the runtime in the preferences ?

**Comment by strycore** [comment]
I don't know how the package is kept up to date, maybe that's when the PKGBUILD's version is used.

**Comment by Luke-Nukem** [comment]
Usually a PKGBUILD script will get/set the version from (I think) an md5 of the source.
So I should usually be kept up to date it you just rebuild the package periodically.

**Comment by rezad1393** [comment]
@Luke-Nukem  that is just for package that are NOT git or svn.
git and svn and hg (and any other if they exist) get the the source from git that is defined in the PKGBUILD script and usually (because git source can change a lot) its MD5 is "SKIP"ed in the script.

@strycore , the packages that are in aur repository and are git based can and will have versions but usually they are only changed by mainteiner of that aur package (if he is competent) at the point that the a new git commit causes the need of modification of PKGBUILD script in any way , e.g. a new needed dependency. or it could be that the new git commit is a necessary update ( like a security update) then the maintainer of that package changes the version.

but after all this user can trigger the git update with "yaourt -Syu --devel" command so that the "devel" packages which i think means in active development( e.g. git source) get updated. but in my experience does not always work, because after getting the new git source some aur packages don't compute the version of git source correctly and so the package manager thinks that the package is up to date.

the safest way is to re-install them as in (yaourt -S lutris-git). this way they get updated and don't get skipped.

**Comment by Xodetaetl** [comment]
Gens and the rest should work with the last version of the runtime.

**Comment by strycore** [comment]
Delete /home/ritwik/.local/share/lutris/runtime/dxvk/0.51/ and relaunch lutris

**Comment by ezioronaldo** [comment]
NOTHING HAPPENED

wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: Bad EXE format for Z:\home\ritwik\Desktop\Tombraider.desktop.
 THIS IS STILL GOING ON

**Comment by strycore** [comment]
Stop shouting.
Stop asking for support on 3 year old closed issues.
Stop putting a .desktop shortcut as your Wine executable.
