### ISSUE TITLE
Esync setup not working in Solus

### ISSUE THREAD

**Issue by coreybruce** [lutris/lutris#1810]
Hey I have an issue, I have Warframe installed and it says I haven't got esync installed but it says I haven't set it up yet.

 I changed /etc/systemd/system.conf and /etc/systemd/user.conf and rebooted and get the value 524288 when I do the command ulimit -Hn as you can see

https://i.imgur.com/38vPsxK.png

Not sure what the issue is or if I did something wrong.

**Comment by mikejkeen** [comment]
What wine version are you using to launch warframe?

**Comment by coreybruce** [comment]
esync-staging-pba-3.18.x86_64

I figured out the issue tho and wrote how I got it working on this reddit post
