### ISSUE TITLE
Do not overwrite file by another one with the same name in cache (with default cache path one in .cache)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1812]
So for example, if I make an installer that downloasd 2 versions of the same file with the same name (32 and 64 bit):
```files:
- mfplat_dll_64: https://lutris.net/files/tools/dll/mfplat/x64/mfplat.dll
- mfplat_dll_32: https://lutris.net/files/tools/dll/mfplat/x32/mfplat.dll```
Lutris overwrite the first file  (mfplat_dll_64) with the second one (mfplat_dll_32), as they have the same name, instead of keeping both. As a result, the script will be borked.

**Comment by strycore** [comment]
no it shouldn't, should go in mfplat_dll_64 and mfplat_dll_32 folders

**Comment by tannisroot** [comment]
Just tested by adding:
```
 files:
- mfplat_dll_64: https://lutris.net/files/tools/dll/mfplat/x64/mfplat.dll
- mfplat_dll_32: https://lutris.net/files/tools/dll/mfplat/x32/mfplat.dll 
```


>should go in mfplat_dll_64 and mfplat_dll_32 folders


It does not. Only single mfplat.dll gets stored, so yeah it gets overwritten.

**Comment by strycore** [comment]
![2019-03-02_16-13](https://user-images.githubusercontent.com/280336/53689238-2583bf00-3d06-11e9-9dd3-e7a96e8b4c8d.png)

Tested and wasn't able to reproduce. Please provide a link to an installer I can test with and reliable repro steps to reopen

**Comment by tannisroot** [comment]
Mfplat installer on this page: https://lutris.net/games/test/ (https://lutris.net/games/a-test-mfplat/installer/edit)
Video as a proof that it'a real bug: https://www.youtube.com/watch?v=YqqUr1BXraY&feature=youtu.be
Sorry for reopening this again btw.

**Comment by tannisroot** [comment]
Ok, it seems like this only happens if cache path is not manually selected in the preferences.
So if I select it, it does create folders like you showed.

**Comment by strycore** [comment]
it makes much more sense if it's specific to the legacy cache!
