### ISSUE TITLE
Wrong dependency on openSUSE Leap 15

### ISSUE THREAD

**Issue by jatin-cbs** [lutris/lutris#1813]
![screenshot from 2019-02-26 16-55-03](https://user-images.githubusercontent.com/40650341/53409615-5f438580-39e7-11e9-8c74-e807abc36ea1.png)

there is no such dependency "mesa-libGL" on openSUSE, it works by ignoring the dependency but just felt important to fix this :) This is from the openSUSE leap 15 OBS repo.

**Comment by guoyunhe** [comment]
Same error in openSUSE Tumbleweed. I use KDE.

**Comment by jubalh** [comment]
@jatin-cbs if you are aware of a distro specific issue, then create an issue in that distros bugtracker and not downstream.

**Comment by guoyunhe** [comment]
@jatin-cbs I can help to fix the OBS package. Will let you know if I can find a solution.

**Comment by guoyunhe** [comment]
@jatin-cbs I have tried on openSUSE Leap 15.0 and it can be installed with no issues.

What I did:
1. go to https://software.opensuse.org/package/lutris?search_term=lutris
2. choose openSUSE Leap 15.0
3. click Experimental packages
4. choose the first package from games:tools
5. click "1-click install".

It will automatically add **games** and **games:tools** to your system, which provides the package dependencies you missed.

Next release, Leap 15.1 will add Lutris and all its dependencies in official repository. Then this problem should not happen anymore.

**Comment by romulasry** [comment]
"Please use bugzilla to report bugs"
https://build.opensuse.org/package/show/openSUSE%3AFactory/lutris

**Comment by jubalh** [comment]
I'm the lutris maintainer in openSUSE.
There is no lutris in official Leap 15.0 repos only in Tumbleweed.

You have the possibillity to add the games and games:tools devel repositories, like mentioned above.
You do this on your own risk and it's not supported.

**Comment by jatin-cbs** [comment]
Not onw click install or official repo its from OBS repo 

https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris

**Comment by jatin-cbs** [comment]
zypper addrepo https://download.opensuse.org/repositories/home:strycore/openSUSE_Leap_15.0/home:strycore.repo

This specific repo

**Comment by guoyunhe** [comment]
@jatin-cbs You shouldn't use that repo... Personal repos, begin with `home:`, usually have a lot of problems and nobody support it. You should use development repos if available:

https://software.opensuse.org//download.html?project=games%3Atools&package=lutris

**Comment by jubalh** [comment]
> This specific repo

Ah okay, then this is the right place to ask such questions. Thanks for clarifying!

> @jatin-cbs You shouldn't use that repo... Personal repos, begin with `home:`, usually have a lot of problems and nobody support it.

@guoyunhe That's wrong. strycore who maintains this home project is one of the Lutris devs. It was the first repo of Lutris available and when I created the one in `games` devel repo I copied the spec file from his home.

**Comment by jatin-cbs** [comment]
Yeah the repo is fine its just one wrong dependency it is maintained by strycore. And it works and is updated every release :)

**Comment by strycore** [comment]
I have no idea what the current status of Lutris in SUSE is. SUSE is weird. It's the only distribution which I don't know who the maintainer is or what versions are actually in the repos, so I'm still building packages for SUSE since SUSE people themselves are so bad at communicating what they do.

**Comment by jubalh** [comment]
@strycore whats confusing about it? If you want to know something about it did you try to reach out to somebody or are you just claiming nobody is coming to you and reporting to you what they do?

If you go to software.opensuse.org and type in lutris you come to this site: https://software.opensuse.org/package/lutris

You clearly lists different kind of repos it finds. Among them 'official release'. Note the 'official'.
games:tools is the devel project, where everything has to go through regarding lutris before it gets to the official repos.

https://build.opensuse.org/package/show/games%3Atools/lutris

On that page you could check the .changes file to see who did changes to it. On the same page there is a tab at the top named 'users'. There you see users with access to this repository and you also see who the maintainer is. All this is described in openSUSE wiki.

As stated in the issue before I'm the maintainer of lutris in openSUSE.

Does this answer your questions? Also SUSE != openSUSE.

**Comment by guoyunhe** [comment]
The best way to know who is maintaining the openSUSE package is to look into the packaging changelog: https://build.opensuse.org/package/view_file/games:tools/lutris/lutris.changes?expand=1

You can find all names and emails of maintainers.

**Comment by strycore** [comment]
OMG thank you @jubalh !!! 
I know about the differences about SUSE and all, I just wanted to know who was maintaining what.
There's a big difference now that I know who I can reach out to!

**Comment by strycore** [comment]
@guoyunhe sure but that's some deep dark SUSE stuff. I use Ubuntu, there's no way I would know that.

I kinda expect maintainers from various distros to reach out to me, it does not amuse me to go hunting on the internet for people I don't know if they even exist.

**Comment by jatin-cbs** [comment]
@strycore the package is working fine and this package is from OBS which is maintained by you not the official repo for tumbleweed.. Its working just the name of dependency is wrong remove mesa-libGL from dependency thats all..

**Comment by jatin-cbs** [comment]
https://download.opensuse.org/repositories/home:strycore/openSUSE_Leap_15.0/home:strycore.repo   its this repo @strycore for leap not the official one for tumbleweed.. The error is in the OBS repo.. The package is working fine just a small mistake.
