### ISSUE TITLE
Optional: Gnome Dependencies

### ISSUE THREAD

**Issue by waltercool** [lutris/lutris#1816]
Hi <maintainer?>,

Can you please avoid making Gnome 3 Python libraries as Mandatory?

I know you are tired of people reporting same issue of crashing by WebKitGTK or GnomeDesktop, but you basically made a non-desktop specific application to a mandatory Gnome Application. This is not only going to annoy Lutris users, but also make lot of crashes and reports of problem every day.

Most applications has their interface layer and implementations abstracted from core logic, then use the one supported (-gtk -qt or fallback with wxwidgets? tk?, or try: except: rule)

Thanks! Version 0.4 is great by the way! Good work! But I'm not going to switch to Gnome just for this.

**Comment by guoyunhe** [comment]
You don't need to install GNOME. The library is a small package of some GNOME API. Most Linux distribution already installed a lot of GNOME packages even the DE is KDE or Xfce...

**Comment by strycore** [comment]
Lutris does not depend on Gnome.
