### ISSUE TITLE
The appdata doesn't have an OARS rating

### ISSUE THREAD

**Issue by LeandroStanger** [lutris/lutris#1819]
You can use https://github.com/flathub/flathub/wiki/AppData-Guidelines to help make sure you get everything.

**Comment by strycore** [comment]
I don't even know what OARS rating is, I doubt we need it

**Comment by TingPing** [comment]
Some software stores require it. You can generate the contents here: https://hughsie.github.io/oars/generate.html

The questions are kinda vague for an app launcher admittedly.

(Hopefully you don't mind me reopening since it really should be added)
