### ISSUE TITLE
g_menu_model_get_n_items(): python3.6 killed by SIGSEGV when installing Gecko

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#1820]
Another BR from Fedora, again with permissions so ask me if you need more info.

Description of problem:
try install gecko in prefix

Version-Release number of selected component:
lutris-0.5.0.1-4.fc28

Additional info:
reporter:       libreport-2.9.5
backtrace_rating: 4
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: g_menu_model_get_n_items
executable:     /usr/bin/python3.6
journald_cursor: s=f9caa6edb8a549b4b577f17e56c85387;i=ff65;b=dd1af187a1594d709104f464f77d869a;m=c56ec5dd;t=582fa041b8555;x=13e13e31c730130f
kernel:         4.20.11-100.fc28.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (10 frames)
 0 g_menu_model_get_n_items at gmenumodel.c:493
 1 gtk_application_window_update_shell_shows_app_menu at gtkapplicationwindow.c:322
 2 gtk_application_window_real_realize at gtkapplicationwindow.c:683
 3 _g_closure_invoke_va at gclosure.c:867
 6 gtk_widget_realize at gtkwidget.c:5471
 7 gtk_window_show at gtkwindow.c:6174
 12 gtk_widget_show at gtkwidget.c:4800
 13 ffi_call_unix64 at ../src/x86/unix64.S:76
 14 ffi_call at ../src/x86/ffi64.c:525

**Comment by BunnyApocalypse** [comment]
Oof, the innitial BZ report I copied in had lots of # numbers, sorry for any pingspam that may have caused to really old bugs haha.

**Comment by TingPing** [comment]
Put them in code blocks: \`\`\`

**Comment by strycore** [comment]
Gosh, those Fedora bugs are rather hard to work with…

**Comment by BunnyApocalypse** [comment]
Yeah, I know they can be a bit obtuse, but they're generated by a tool that automatically gathers information on an application whenever it crashes, if that gives you any context for why it's kinda shitty. Users can make reports that add as much context as they want to the crash as they want to in addition to whatever it automatically gathers. In this case, all that they said was that it happened when they tried to install gecko in a wineprefix.

**Comment by strycore** [comment]
This once is indeed the same stacktrace as #2006, I'm going to close this one as well because I remember making fixes regarding running_games.get_n_items()
