### ISSUE TITLE
Can't open file browser when config window is open

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1821]
Pressing the file button returns this when the config window is open.

![screenshot from 2019-02-28 19-32-38](https://user-images.githubusercontent.com/15083452/53614703-a3718a00-3b8f-11e9-8793-742dc0cd98cf.png)

**Comment by strycore** [comment]
I've fixed this in the latest commit, I think this might also solve other tickets with the same error message. Please close other tickets as well if appropriate.
