### ISSUE TITLE
Lutris duplicates native Games

### ISSUE THREAD

**Issue by jrtberlin** [lutris/lutris#1822]
After closing and reopening Lutris, native games have an additional entry when they were launched through Lutris. 

This happens for me with:
- 0 A.D. (installed after Lutris via apt)
- SteamVR (installed via Steam)
- SuperTuxKart (installed via apt)

Maybe #1661 is related, however, I'm not able to resolve the issue and every game was installed after Lutris.

![image](https://user-images.githubusercontent.com/14153182/53622372-d3ee0e00-3bf9-11e9-960b-a06215aeb00e.png)

First run of Lutris:
> DEBUG    2019-03-01 08:05:47,869 [application.launch:339]:Adding game 0 A.D. (linux) (139879837540928) to running games

The second run of Lutris:

> DEBUG    2019-03-01 08:05:58,198 [pga_game.platform:67]:Setting platform for 0 A.D.: Linux

In "~/.config/lutris/games" is only one file called "0-ad-desktopapp.yml".

**Comment by strycore** [comment]
this is fixed in master
