### ISSUE TITLE
Launchers added to ZDoom runner not working as of 0.5

### ISSUE THREAD

**Issue by 7HEPOW** [lutris/lutris#1823]
As the title suggests gzdoom games added after the 0.5 update don't work. Launchers added in version 0.4 keep on working as intended.

I use the gzdoom version installed in my system and configured the runner to use /usr/bin/gzdoom accordingly instead of the download version from Lutris. My config files for it are also properly configured and launching any game/mod from any folder in a terminal works. As I do use quite a bunch of mods while playing Doom, I prefer using the command line arguments field instead of the other separate available fields to load multiple mods at a time. For example my Doom II commanline field looks like this:
`-iwad doom2.wad -file Maps.of.Chaos.1.27.Overkill.pk3 Bolognese.2.0.pk3 Bolognese.2.0.VM.pk3`
I have made that entry on 0.4 and it works perfectly fine.

After trying to add new entries, the games won't launch. When trying to launch with the side bars active, the play button turns inactive reading "Launching...". I made a new entry to simply launch gzdoom without arguments and the lutris -d output is the following:

```
DEBUG    2019-03-01 23:42:08,973 [game.play:257]:Prelaunching <lutris.runners.zdoom.zdoom object at 0x7f400f8479b0>
WARNING  2019-03-01 23:42:08,974 [zdoom.prelaunch:101]:FluidSynth is not installed, you might not have any music
DEBUG    2019-03-01 23:42:08,980 [display._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2019-03-01 23:42:09,070 [game.configure_game:293]:Launching Doom Test: {'command': ['/usr/bin/gzdoom']}
DEBUG    2019-03-01 23:42:09,070 [game.configure_game:294]:Game info: {
  "command": [
    "/usr/bin/gzdoom"
  ]
}
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 490, in configure_game
    self.start_game()
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 500, in start_game
    exclude_processes=self.game_runtime_config["exclude_processes"],
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 67, in __init__
    self.cwd = self.get_cwd(cwd)
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 91, in get_cwd
    return os.path.expanduser(cwd)
  File "/usr/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If I deselect the game, the sidebar tells me, that I'm playing the game. Reselecting the game changes the sidebar button from "Launching..." to "Stop". Pressing the Stop button returns:
`WARNING  2019-03-01 23:27:03,719 [game_actions.on_stop:169]:738 not in running game list`
...although it is still listed in the sidebar as running when no entry is selected. Closing Lutris regularly prompts correctly, if I'm sure as it thinks a game is running and then closes without errors.

**Comment by 7HEPOW** [comment]
Looks like it's related to this: https://github.com/lutris/lutris/issues/1817

**Comment by e-user** [comment]
Please re-open this issue. It's not related to #1817 and I can reproduce it.

**Comment by strycore** [comment]
ok, I'll take a look

**Comment by strycore** [comment]
I pushed a fix for the backtrace posted here but it's not specific to gzdoom so let me know if there's something left to fix.
