### ISSUE TITLE
Add checkbox to clean install over an existing prefix

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1827]
Disclaimer: I didn't find any other issue in lutris's repo that is relevant and i've consulted this issue on discord with lutris's team on which i'm filing this issue.

This error should be handled better -> recommends prompting the user if he/she want's to nuke present wineprefix before installation of new one to prevent conflicts -> Warning is not sufficient.
![image](https://user-images.githubusercontent.com/11302521/53683695-2c113700-3d04-11e9-8034-9e622be39d0a.png)

### Steps to reproduce
- make a new directory in $GAMEDIR of installer
- Install game via lutris.

**Comment by tannisroot** [comment]
This could be solved by introducing a 'Clean install" checkbox during that step when a conflicting prefix is detected.

**Comment by Kreyren** [comment]
got banned again.. i tried, closing

**Comment by Kreyren** [comment]
Just to clarify: willing to resolve if such contribution is helpful

**Comment by tannisroot** [comment]
Clear and professionally written bug reports are more than welcomed.

**Comment by strycore** [comment]
I disagree with the overall solution presented in this ticket. Not saying that this won't get fixed in the future but not in the way that is suggested here.
