### ISSUE TITLE
Discord runner

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1837]
Someone on the Discord server asked if it were possible so I'm looking to see if I can meet the criteria.

Installing games doesn't work on Wine so I'm using a virtualbox to figure this out.

- [x] Launch: `discord:///library/460940655984771072/launch`
- [ ] Install
- [x] Uninstall: `cmd /c start discord:///library/460940655984771072/uninstall`

**Comment by strycore** [comment]
Installing is the most critical part and I don't want to encourage the multiplication of stores. Discord doesn't provide any additonal value in that regard. Maybe this can be re-opened once Humble, Battle.net, Uplay and Origin are supported.
