### ISSUE TITLE
Apply envars (including esync) when opening Wine Configuration/Registry/Winetricks/Joystick Panel/Run as Exe

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1839]
Wineserver process of the same prefix can't be opened with WINESYNC envar set to 0 and 1 at the same time or in other words, esync both turned on and turned off. As Lutris doesn't set that envar when opening Wine Configuration/Registry/Winetricks/Joystick Panel/Run EXE, launching a game at the same time will fail if Esync option is enabled as in that case, that envar *is* passed.
So to avoid this issue, it must apply envars when opening these menus too, including the ones that are passed when DXVK option is enabled and the ones that are stored in the configuration.

**Comment by strycore** [comment]
What does that even mean "WINESYNC envar set to 0 and 1 at the same time". Is it schrodinger's environment variable?

**Comment by tannisroot** [comment]
> What does that even mean "WINESYNC envar set to 0 and 1 at the same time". Is it schrodinger's environment variable?
No. It's just if you launch these option before starting the game itself by pressing "Play", these envars like WINEESYNC will not be passed and default to turned off (0), so when you do launch the game through "Play" with WINEESYNC envar passed on and set to 1,  it will conflict as wineserver can't run both with esync off and on.

**Comment by tannisroot** [comment]
Should be fixed by https://github.com/lutris/lutris/commit/b043071eee248f19ad3c1761bab932daebb29738.

**Comment by tannisroot** [comment]
Apparently it was not fixed by that.
