### ISSUE TITLE
Add flag for downloadable files that will prevent their caching

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1843]
For example, Overwatch installer downloads state cache for DXVK, which I update frequently when the game updates occur as they change shaders around, making old state cache useless.
However, if the user has an option that stores these files permamently enabled, Lutris will not redownload newer state cache file and will use the old one instead.
So what I want is to have some sort of a flag for files in `files:` section that will prevent Lutris from storing them even with the cache option enabled and redownload them each time.

**Comment by strycore** [comment]
This is not how I want to design the cache. 
Yes, this issue will be handled.
