### ISSUE TITLE
'No file provided' after installing battle.net

### ISSUE THREAD

**Issue by gituser823** [lutris/lutris#1844]
See https://github.com/lutris/lutris/issues/1770

I have re-installed Mint now and I am getting the same Error again.

How can I fix this?

Yes, of course I read through the Blizzard App Wiki Page.

There is no folder called "Battle.net" under ~/Games/overwatch/drive_c/Program Files (x86) where it should be.

I also did get an Error message from battle.net, when the installation was finished.

How can I send you the Logs or what do you need?

Edit:
I removed the game and folder and re-installed again with the same Issue.
I made a screenshot of the Error:

![auswahl_001](https://user-images.githubusercontent.com/32219087/54047331-15248600-41d7-11e9-828d-a066718970f5.png)

Edi2:

I just installed Battlefield V /Origin and I get the samme Error there now.

**Comment by tannisroot** [comment]
**X error of failed request**
the driver was not installed properly. Please follow instructions on this page: https://github.com/lutris/lutris/wiki/Installing-drivers
If you will experience issues after that, feel free to join Lutris' Discord server, I can help you there.
