### ISSUE TITLE
install_cab_component does not install 64-bit Media Foundation components

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1850]
It only installs 32-bit ones. So if the prefix is 64-bit, the components will only be installed into Syswow64, but not into system32.
The use case for 64 bit MF components would be for RE Engine games like Resident Evil 7,  Resident Evil 2 Remake and Devil May Cry 5.

**Comment by tannisroot** [comment]
tested using this installer: https://lutris.net/games/devil-may-cry-5-change-me/installer/edit

**Comment by AccountOneOff** [comment]
Use `$HOME/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe`

**Comment by tannisroot** [comment]
Oh, lol, I completely missed that. Thanks.
