### ISSUE TITLE
Unable to locate libGL or libpthread.

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#1852]
Unable to locate libGL or libpthread.
Gentoo - No DE- DWM

ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ATTENTION: default value of option mesa_glthread overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  49
  Current serial number in output stream:  48
2019-03-12 01:26:07,253: glxinfo call failed: Command '['glxinfo', '-B']' returned non-zero exit status 1.
2019-03-12 01:26:07,254: No available glxinfo output
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '"libpthread.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libGL.so.1"' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ATTENTION: default value of option mesa_glthread overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  172
  Current serial number in output stream:  171
Running /home/user/.local/share/lutris/runners/wine/esync-staging-pba-3.16-x86_64/bin/wine /mnt/internal/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/GW2-64.exe -autologin
2019-03-12 01:26:11,147: Game still running (state: running)
2019-03-12 01:26:11,147: Stopping Guild Wars 2 (wine)
/usr/lib64/python3.6/site-packages/lutris/command.py:256: Warning: Source ID 4904 was not found when attempting to remove it
  GLib.source_remove(self.stdout_monitor)

**Comment by aTosser** [comment]
If I go to LD_PRELOAD and manually enter the WHOLE patch to libGL.so.1 it works. There is some issue with the library location mechanism.

**Comment by strycore** [comment]
A no DE setup is not supported, you have to install ine

**Comment by aTosser** [comment]
This is not a DE specific issue it happens in KDE as well.

**Comment by openglfreak** [comment]
Also no DE does not necessarily mean no desktop.
