### ISSUE TITLE
Messed up layout on i3 WM

### ISSUE THREAD

**Issue by Jipok** [lutris/lutris#1854]
Everything can be seen in the picture.
![image](https://user-images.githubusercontent.com/25588359/54383189-52938280-46b3-11e9-9668-dfccba20a1f9.png)

**Comment by tannisroot** [comment]
Is this i3? It probably ignores that Lutris can't be squished to this window size.

**Comment by Medath** [comment]
It's more of a problem with i3wm than with Lutris. Lutris usually can't be resized like that, but i3wm doesn't care.

I'd recommend configuring i3 to always open Lutris as a floating window. To do that you have to add `for_window [class="Lutris"] floating enable` to your i3 config. In case you also encounter issues with Wine, I'd recommend you to enable Winedesktop globally and set Wine applications to always open as a floating window (`for_window [class="Wine"] floating enable`)

**Comment by Riesi** [comment]
This cant really be fixed on the Lutris side, since i3 does not respect the minimum window size in docked mode. You can make the windows as small as you want. It is only respected in floating mode, as Medath already mentioned.

**Comment by tannisroot** [comment]
Closing for above mentioned reasons.
