### ISSUE TITLE
Pre-launch command is using system wine

### ISSUE THREAD

**Issue by BackOrder** [lutris/lutris#1855]
Lutris 0.4.23 reports `wine client error:0: version mismatch 571/572.` on a pre-launch command because it is using the system's wine instead of the wine configured with the game.

**Comment by tannisroot** [comment]
0.4.23 is an outdated version.

**Comment by BackOrder** [comment]
Lutris 5.0 doesn't run on CentOS just yet. See https://github.com/jatin-cbs/Lutris-RHEL-CentOS7

**Comment by tannisroot** [comment]
Perhaps you could try using something more modern, like Fedora?
