### ISSUE TITLE
GTK warning with Gnome 3.32

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1856]
>(lutris:27403): Gtk-WARNING **: 06:52:00.156: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown

**Comment by TingPing** [comment]
This can be ignored, the warning wasn't intended to make it into the stable release.
