### ISSUE TITLE
Running Winetricks shuts down Steam Wine prefix, but "Stop" doesn't

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1865]
Just noticed recently that when you have Steam opened, opening Winetricks from menu can shut it down. 
It would be nice if Lutris would use the same thing to shut Steam down when pressing "Stop", as it currently cannot do that.

**Comment by strycore** [comment]
I'm closing this because it's not specific enough work with and I'm pretty sure it will get fixed as a side effect of other changes.
