### ISSUE TITLE
Browse for exectuable in `WINEPREFIX/drive_c/Program Files` by default

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#1867]
choose a game > Configure > Game Options > Executable

This field is blank by default on a new game. Clicking Browse leads to the user's home directory.

I propose that if a Wine Prefix has been specified for this game and an executable has not yet been chosen, Browse should start in the `drive_c/Program Files` directory in that prefix.

**Comment by strycore** [comment]
This does not make any sense.

**Comment by sparr** [comment]
I'm not sure which part doesn't make sense.

I have a game with a configured wine prefix. In my experience the odds are really good that the .exe that I want to launch is under `$WINEPREFIX/drive_c/Program Files/` in the game's folder. Making the user browse to find that seems counterproductive.
