### ISSUE TITLE
allow Wine Prefix relative to Default Installation Folder

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#1868]
choose a game > Configure > Game Options > Wine prefix

This field currently seems to want an absolute path. I would like to be able to specify a relative path (which would often be just a single directory name) that will be interpreted relative to the global or runner-specific or game-specific System options > Default installation folder

**Comment by strycore** [comment]
no.

**Comment by sparr** [comment]
Why not? Would it break something? Is the value to the user in question?

**Comment by sparr** [comment]
the last 40+ games I have installed I've had to either browse or copy/paste the install path into the wine prefix setting. this is tedious and annoying and entirely unnecessary.
