### ISSUE TITLE
Option to use xdg-open instead of Gtk.show_uri to browse folders

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#1869]
I don't have Gnome installed or any gnome-specific management packages, so my gio mime settings are unmanaged, leaving a random `inode/directory` handler as the "default" for the "Browse Files" functionality for games in Lutris.

I would like to see an option to use the `xdg-open` script instead, which has its own logic for resolving handlers across different desktop environments and otherwise.

**Comment by strycore** [comment]
Open a bug against show_uri in Gtk since it's not doing the right thing.

**Comment by sparr** [comment]
What "right thing" would you expect it to do in this situation? The freedesktop standards say that if a DE hasn't installed any default defaults that the default should be chosen effectively at random (actually the first on the list, and the list is randomized when the cache is regenerated). show_uri seems to be behaving exactly as the spec requires.

**Comment by TingPing** [comment]
> show_uri seems to be behaving exactly as the spec requires.

Indeed, no bug here IMO.

Just run `gio mime inode/directory foo.desktop` if you want to change it.

**Comment by sparr** [comment]
My motivation here is to not need to manage mime associations in two different places. Very few non-Gnome-specific applications gnome/gtk/gio-only systems like `show_uri`; most of them honor settings from other desktop environments by using xdg tools.

**Comment by TingPing** [comment]
Gio is not gnome-specific in any way. GLib is a cross-platform project and the freedesktop spec is a cross-desktop standard.

**Comment by sparr** [comment]
While gio is not gnome-specific, most users have no idea what gio is, and won't know how to configure it without having tools installed from Gnome (or another DE).

**Comment by strycore** [comment]
I've never had to "configure" Gio since 1996.
