### ISSUE TITLE
Playing around with a GOG Galaxy runner

### ISSUE THREAD

**Issue by lukas2005** [lutris/lutris#1876]
So i forked this repo and created a new runner for GOG Galaxy (https://github.com/lukas2005/lutris/tree/winegog-runner) and installation + running games works so far. But i wonder why hasn't this been done already and there is only a way to import the GOG library? (also i'd like some tips on how would i add the ability to install a game thru the gog galaxy client because the steam code is a bit confusing to me)

**Comment by telanus** [comment]
AFAIK GOG Galaxy is still Windows Only, thus it'll fall under the Wine Runner, and AFAIK GOG games can be imported from the release of 0.5.0, it's under the import games drop down thingy

**Comment by lukas2005** [comment]
well steam was windows only for quite a while and there is a runner for it + if you want to use GOG Galaxy with lutris (to get updates and so on) you have to install it and set games prefixes to the same one as GOG + with some games some more manual config.

**Comment by strycore** [comment]
We don't need a runner for the Windows version of GOG Galaxy, Lutris itself is enough.

**Comment by lukas2005** [comment]
Well some games require GOG Galaxy for online features

**Comment by strycore** [comment]
There is a GOG Galaxy installer on the website.

**Comment by lukas2005** [comment]
Well then what's the point of the steam runner if there's a steam installer too?

**Comment by strycore** [comment]
WineSteam was needed to run 1000s of games back when Proton wasn't around (and is still needed for dozens of games).
GOG Galaxy is needed by a couple games a most, it's not worth the effort.
