### ISSUE TITLE
Add @LutrisGaming Twitter feed to right panel?

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1881]
Now that "Search on Lutris.net" was removed from right panel, it's looking kind of empty.
As a community manager, I personally would love to see Twitter feed of @LutrisGaming integrated there as a widget.
Pros:
1. Allows delivering project news to all users in an easy and highly effective way.
Cons:
1. Privacy-concerned users might freak out.
2. Potentially might consume quite a lot of resources.

**Comment by strycore** [comment]
that's not the right place to put a twitter feed
