### ISSUE TITLE
Lutris show a new launcher each time I launch or configure a game.

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#1882]
Hello,

I have this issue on Lutris: each time I launch or configure a game, Lutris shows a new launcher icon. As you can see on this screen capture, I launched Splinter Cell 7 times and configured it one time. So Lutris shows 9 launcher icon.

![Capture d’écran de 2019-03-20 07-35-53](https://user-images.githubusercontent.com/325405/54663886-04331900-4ae3-11e9-900d-4a68b2c61415.png)
Same issue if I try to remove a launcher icon.
After Lutris restart, there was only one launcher icon again.

I joined you the Lutris log.
[lutris.log](https://github.com/lutris/lutris/files/2986814/lutris.log)

Lutris version: today's git.
Config: Ubuntu 18.04 Nividia GPU

**Comment by tannisroot** [comment]
This should be fixed in master. Tell me if it still happens after release of 0.5.1 and I will reopen the issue.

**Comment by legluondunet** [comment]
I just updated my git version  and the bug is still here.

**Comment by tannisroot** [comment]
@legluondunet just to be sure: did you close older instance of Lutris after updating it to git version?

**Comment by tannisroot** [comment]
Yeah, this is clearly a bug:
```Traceback (most recent call last):
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/gui/views/store.py", line 403, in add_game
    if not self.has_icon(game.slug):
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/gui/views/store.py", line 155, in has_icon
    return system.path_exists(get_icon_path(game_slug, media_type))
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/util/resources.py", line 20, in get_icon_path
    raise ValueError("Invalid icon type %s" % icon_type)
ValueError: Invalid icon type banner_small```

**Comment by strycore** [comment]
this bug report is missing the necessary information to handle it.

**Comment by legluondunet** [comment]
What necessary information do you need? And why do you close a bug that is not fixed?

**Comment by strycore** [comment]
Right, I missed a part of the report, it's fixed now

**Comment by legluondunet** [comment]
Works great now, thank you.
