### ISSUE TITLE
Change "Search on Lutris.Net" button

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1883]
It's really not obvious what this button does:
![image](https://user-images.githubusercontent.com/10602045/54675409-905b3580-4b0f-11e9-9fea-751f3d2564b5.png)
I propose either:

- Change it to a text button (content could be something like "Lutris.Net")
- Change the icon to something web-themed (like this web-emblem from Papirus icon set: https://yadi.sk/i/Gchzrx1iw6rYYw)
- Do both above mentioned things.
- Do something else. Just lets's not leave it like this for 0.5.1.

**Comment by strycore** [comment]
yeah, no I don't like those solutions either

**Comment by tannisroot** [comment]
That did not the problem. The user still doesn't know what this button does until they press it.
Also, the icon is incorrect (i suggest using `folder-download-symbolic` instead): 
![image](https://user-images.githubusercontent.com/10602045/54740521-bc88bc00-4bcc-11e9-8aef-70437dcc9250.png)
