### ISSUE TITLE
Dinput over Xinput.

### ISSUE THREAD

**Issue by artivision** [lutris/lutris#1886]
Hello, if the Gamepad is Dinput and the Game Xinput, is there an option to emulate Dinput?

**Comment by strycore** [comment]
yes, there is. Use the x360ce option and it should work fine (this should work as on Windows).

**Comment by artivision** [comment]
Hello, i am on Linux DXVK. Which of all x360ce options.

**Comment by strycore** [comment]
on the runners tab of the game options

**Comment by artivision** [comment]
Hi, the Dinput8 option gives cannot load dinpu8 dll. The Xinput9 does nothing.

**Comment by strycore** [comment]
The dinput8 option shouldn't be needed, it's only for a few games.
