### ISSUE TITLE
lutris 0.5.0.1 '~' in cache dir interpeted as literal '~'

### ISSUE THREAD

**Issue by mynamewastaken** [lutris/lutris#1888]
This is on Fedora 29 and was working prior to today - unsure when I last installed a game to know when it broke. I fixed it by hardcoding /home/me instead of `~`

**Comment by strycore** [comment]
That's fixed in Lutris 0.5.1, it should be released very soon

**Comment by mynamewastaken** [comment]
Cheers - thanks for the quick followup.
