### ISSUE TITLE
Game library (lutriswindow.py) no longer opens when installing games if Lutris isn't already opened

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1895]
How to reproduce:
1. Completely close Lutris
2. Click "Install" on the website

Observed behavior: Only the installation window opens, nothing else.
Expected behavior: Installer windows opens _along_ with the main window with the game library.

It's probably caused by https://github.com/lutris/lutris/pull/1885

**Comment by strycore** [comment]
meeeeeeeeeeeeeh
I'm gonna say this is the expected behavior now. People just want conflicting things. You can still open the lutris client while the install is going on, it's not absurd to have the install link only open the install window.

**Comment by strycore** [comment]
ok, no, it's not possible to open the client while the install is going on, it just focuses the install window so there's a bug here.
