### ISSUE TITLE
Feature request: skip locating downloaded files if they are in a predictable location

### ISSUE THREAD

**Issue by sparr** [lutris/lutris#1900]
I always download things to the same directory. I would like to either be able to tell lutris where that directory is, or it tell me what directory I should download to, and then it automatically find files needed by installers if they are in that directory without me having to browse for them.

Right now I would use this for ~/Downloads/setup_nwn_diamond_2.1.0.21.exe which I've had to select six times in a row so far.

This would require installers having a way to specify the expected filename.

**Comment by strycore** [comment]
![2019-03-21_15-40](https://user-images.githubusercontent.com/280336/54789426-ac360880-4bef-11e9-862b-e723cd360480.png)
