### ISSUE TITLE
debian: lintian: package-section-games-but-contains-no-game

### ISSUE THREAD

**Issue by mmstick** [lutris/lutris#1907]
https://lintian.debian.org/tags/package-section-games-but-contains-no-game.html

> This package is marked as part of the section games, but doesn't contain files in /usr/games. Binaries of games must be installed in /usr/games.

**Comment by strycore** [comment]
I believe that a symlink, has to be placed in games, Steam is doing that. (Not sure how to proceed for this on the Debian package, I'll let someone else take care of that)

**Comment by mmstick** [comment]
It doesn't have to be a symlink. Actually, our steam package is not using a symlink there (nor is Ubuntu's).

**Comment by strycore** [comment]
is there a command to copy the executable in both /usr/games and /usr/bin needed in one of the debian files?

**Comment by mmstick** [comment]
You can create a `debian/links` file to specify a symlink, though it only needs to exist in `/usr/games`.
