### ISSUE TITLE
lutris crashes when configuring runner > Library default folder

### ISSUE THREAD

**Issue by rasb23** [lutris/lutris#191]
Just installed lutris and sync's my steam account. When I try to set the runners library default folder it crashes everytime. Running on Kubuntu 14.04

(lutris:8385): Gdk-CRITICAL **: gdk_device_ungrab: assertion 'GDK_IS_DEVICE (device)' failed 
(lutris:8385): Gtk-CRITICAL **: gtk_device_grab_remove: assertion 'GDK_IS_DEVICE (device)' failed
(lutris:8385): Gdk-CRITICAL **: gdk_device_ungrab: assertion 'GDK_IS_DEVICE (device)' failed
(lutris:8385): Gtk-CRITICAL **: gtk_device_grab_remove: assertion 'GDK_IS_DEVICE (device)' failed
(lutris:8385): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed                                                                       
/usr/lib/pymodules/python2.7/lutris/gui/config_dialogs.py:294: Warning: /build/buildd/glib2.0-2.40.2/./gobject/gtype.c:4210: type id '0' is invalid                                                                 
  self.run()                                                                                              
/usr/lib/pymodules/python2.7/lutris/gui/config_dialogs.py:294: Warning: can't peek value table for type '<invalid>' which is not currently referenced
  self.run()
Segmentation fault (core dumped)

**Comment by strycore** [comment]
Thanks for the report, I couldn't exactly reproduce the issue but I noticed some problems when setting the game library folder on Lutris 0.3.6. I'll let you know when we release Release Candidates builds of Lutris 0.3.7 so you can test it and confirm the problem has gone away.

**Comment by rasb23** [comment]
switched to ubuntu-mate 14.04 and the crash no longer happens. So far running fine.

**Comment by strycore** [comment]
I'm closing this issue then, let me know if there are any issues when 0.3.7 is released.
