### ISSUE TITLE
side panel inconsistencies

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#1915]
There seems to be inconsistency between the dark theme and the normal theme

the art shows better in the dark theme: 

![Screenshot_20190323_115606](https://user-images.githubusercontent.com/19357986/54865040-fb9f4480-4d67-11e9-9e34-e6ba54779de0.png)

While it hardly shows in the normal theme:

![Screenshot_20190323_115551](https://user-images.githubusercontent.com/19357986/54865067-48831b00-4d68-11e9-81f0-35fc78a89f6c.png)

Just a thought, have the normal theme use the dark theme's side panel

**Comment by Zeioth** [comment]
Possibly strider wanted to make sure that the text is visible.

**Comment by Zeioth** [comment]
BTW there's actually a low priority side panel inconsistency. I wrote about it some time ago in Discord:

**If "Show side panel" is disabled, Lutris will look like this:**

![1](https://user-images.githubusercontent.com/3357792/54889099-17f3cc00-4ea3-11e9-90f2-d37e9746b221.png)

**But after you restart Lutris it will look like this:**
![2](https://user-images.githubusercontent.com/3357792/54889088-fabefd80-4ea2-11e9-86f0-ba1b15c491b7.png)

**Comment by strycore** [comment]
There is a transparent background in the source files, you can play around with the opacity or different gradients in Gimp to see what shows the best

**Comment by strycore** [comment]
I believe this is correctly balanced between light and dark theme. Anyway, if anyone has a better implementation, it's just a matter of changing the png and sendig a PR.
