### ISSUE TITLE
Feature: Import system-installed games into the Lutris library by scanning /usr/share/applications

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#192]
Most distro package managers will install games in /usr/bin or /usr/games, and put a .desktop entry in /usr/share/applications, which typically looks like that:

```
[Desktop Entry]
Name=OpenDungeons
Comment=RTS game inspired by Dungeon Keeper
Exec=opendungeons
Icon=opendungeons
Terminal=false
Type=Application
Categories=Game;StrategyGame;
```

The idea would be to have a feature that would:
- Scan all .desktop files in /usr/share/applications and retrieve the ones with `Categories=*Game*` (e.g. `grep "Categories=.*Game.*" /usr/share/applications/*`)
- Add one entry per game in the user's Lutris library, using the `Exec` field to find the executable in the $PATH (/usr/games, /usr/bin), and using the `Icon` field to retrieve the game icon (in /usr/share/icons, /usr/share/icons/hicolor/*/apps, /usr/share/pixmaps). For some games, there can even be a `Path` field that gives the needed runtime directory (see [1] for more details).
- Optionally, we could even try to match the `Name` or `Exec` to existing library games from lutris.net, so that we can use the nice banners from the website and avoid duplicates. That might require to add an optional tag in the installer scripts to name the "usual binary name" when packaged by distro maintainers.

The feature would not be automatic in my opinion, but there should be something like "Scan for system-installed games".

[1] http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by akien-mga** [comment]
All this logic could also be declined in /usr/local too instead of only /usr btw, but most users would not have games installed in /usr/local, or only a couple of them.

**Comment by TingPing** [comment]
There is already a script to scan for apps with the Game category it is just unused: [xdgmeu.py](https://github.com/lutris/lutris/blob/8879d405b403113a141b445ef00fc9ae61c2471a/lutris/xdgmenu.py)

**Comment by rdft4e** [comment]
@TingPing 
hi, how can i use the xdgmenu.py script?
I have just installed lutris but it does not find the system games already installed (Debian 8, the installed games become from official debian repositories)

**Comment by strycore** [comment]
@rdft4e Lutris menu > Import games.

**Comment by rdft4e** [comment]
@strycore 
I forget to say that I ran before Lutris menu > Import games > Desktop games. In principle nothing happened but today when I restarted Lutris now I can see the ~ 200 system games installed. Lutris did not capture correctly the thumbnail or icon for each game. It is a minor problem of course.

The point is that when one has installed so many games ( I did  it installing a dummy package called arcade-games), lutris takes time to fetch all games and I probably quit the program before lutris finished the task.

Thank you anyway

**Comment by strycore** [comment]
No, you did it right, the import games feature is not quite complete yet and requires a restart to be able to see the imported games.

I'll improve the process by letting users select with games they want to import and of course updating the client with the new games without requiring a restart.
