### ISSUE TITLE
Lutris fails to open for some users

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1923]
Lutris opens the donation page https://lutris.net/donate but doesn't open the donation message window.

>Clicking "install" on the WINE GOG version results in an error window popping up after I select "open with Lutris" and instantly closes, then the "become a patreon supporter, etc" page shows up in a new browser tab

Issue reported on: https://lutris.net/games/assassins-creed/

>Nice. Running Lutris now just takes me to the donate page for Lutris.net. Can't load any games :P
>
>>it was a glitch. It was loading the donation web page, not the donation popup with the option to do not show again. I rebooted and that finally came up instead of opening a new firefox tab. Also donated :P 

https://old.reddit.com/r/linux_gaming/comments/b4cuui/lutris_051_released/ej8beaw/?context=3

**Comment by tannisroot** [comment]
Can you check if it's the same issue as https://github.com/lutris/lutris/issues/1918 ?

**Comment by ardydo** [comment]
Just got this and seems the same as #1918 . Installed gvfs-backends and it opened up just fine!

**Comment by tannisroot** [comment]
Ok, I will close this is a duplicate for now and if you think it's not, just reopen it.

**Comment by lounick** [comment]
@tannisroot  Still exists in Ubuntu 16.04 

`lutris --version
2019-03-29 19:33:42,300: GLib.set_option_context_summary missing, was added in GLib 2.56 (Released 2018-03-12)
lutris-0.5.1.3`
