### ISSUE TITLE
.pot file don't have lot strings

### ISSUE THREAD

**Issue by bigbruno** [lutris/lutris#1924]
Hello, i'm from Brazil and lot people in my country don't know how use Lutris because this app don't really have translation to pt-br.

I'm checked in /po folder, but .pot file don't have lot strings, and is impossible make a translation, please solve problem with .pot and we make translation to pt-br.

**Comment by TingPing** [comment]
The pot file shouldn't even be in git, its a dynamically generated file..

**Comment by strycore** [comment]
I removed the pot file as recommended by @TingPing 
Full support for i18n is on the roadmap and will be implemented soon.
