### ISSUE TITLE
Can not find libGL.... But can find drivers?

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#1926]
(lutris:20743): Gtk-WARNING **: 02:03:12.124: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.124: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.124: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
**2019-03-24 02:03:12,447: Running Lutris 0.5.1
2019-03-24 02:03:12,447: Using NVIDIA drivers 418.43 for x86_64
2019-03-24 02:03:12,447: GPU: GeForce GTX 670
2019-03-24 02:03:12,447: GPU: 10DE:1189 10DE:097A using nvidia drivers
2019-03-24 02:03:12,463: Vulkan is supported
2019-03-24 02:03:12,464: Updating DXVK versions**

(lutris:20743): Gtk-WARNING **: 02:03:12.500: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.500: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.500: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.500: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.500: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:20743): Gtk-WARNING **: 02:03:12.819: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown
**libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  49
  Current serial number in output stream:  48
2019-03-24 02:03:16,719: glxinfo call failed: Command '['glxinfo', '-B']' returned non-zero exit status 1.
2019-03-24 02:03:16,720: No available glxinfo output**
Running /home/user/.local/share/lutris/runners/wine/tkg-protonified-3.21-x86_64/bin/wine /mnt/internal/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/GW2-64.exe -autologin
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  168
  Current serial number in output stream:  167
Waiting on children
All children gone
Exit with returncode 1
2019-03-24 02:03:18,597: Game still running (state: running)
2019-03-24 02:03:18,597: Stopping Guild Wars 2 (wine)

How is this that lutris can detect that i indeed have drivers and 3daccel but can not find libGL.......

**Comment by tannisroot** [comment]
Did you try rebooting?

**Comment by strycore** [comment]
Oh, I had the same thing when I installed the Nvidia 418 drivers from the CUDA 10 repository. I think those drivers didn't ship the 32bit version and reverting to the 415 driver from the PPA solved the issue (but I lost support for Cuda 10 / NVenc...)
Not a Lutris issue anyway.

**Comment by aTosser** [comment]
I disagree, I have the 32bit drivers on my system. All of my other applications can locate the drivers.


/usr/lib32/opengl/nvidia/lib/libGL.so
/usr/lib32/opengl/nvidia/lib/libGL.so.1
/usr/lib32/opengl/nvidia/lib/libGL.so.1.7.0
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM.so
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM.so.1
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM.so.1.2.0
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM_nvidia.so
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM_nvidia.so.1
/usr/lib32/opengl/nvidia/lib/libGLESv1_CM_nvidia.so.418.56
/usr/lib32/opengl/nvidia/lib/libGLESv2.so
/usr/lib32/opengl/nvidia/lib/libGLESv2.so.2
/usr/lib32/opengl/nvidia/lib/libGLESv2.so.2.1.0
/usr/lib32/opengl/nvidia/lib/libGLESv2_nvidia.so
/usr/lib32/opengl/nvidia/lib/libGLESv2_nvidia.so.2
/usr/lib32/opengl/nvidia/lib/libGLESv2_nvidia.so.418.56
/usr/lib32/opengl/nvidia/lib/libGLX.so
/usr/lib32/opengl/nvidia/lib/libGLX.so.0
/usr/lib32/opengl/nvidia/lib/libGLX_nvidia.so
/usr/lib32/opengl/nvidia/lib/libGLX_nvidia.so.0
/usr/lib32/opengl/nvidia/lib/libGLX_nvidia.so.418.56
/usr/lib32/opengl/nvidia/lib/libGLdispatch.so
/usr/lib32/opengl/nvidia/lib/libGLdispatch.so.0
/usr/lib64/opengl/nvidia/lib/libGL.so
/usr/lib64/opengl/nvidia/lib/libGL.so.1
/usr/lib64/opengl/nvidia/lib/libGL.so.1.7.0
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM.so
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM.so.1
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM.so.1.2.0
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM_nvidia.so
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM_nvidia.so.1
/usr/lib64/opengl/nvidia/lib/libGLESv1_CM_nvidia.so.418.56
/usr/lib64/opengl/nvidia/lib/libGLESv2.so
/usr/lib64/opengl/nvidia/lib/libGLESv2.so.2
/usr/lib64/opengl/nvidia/lib/libGLESv2.so.2.1.0
/usr/lib64/opengl/nvidia/lib/libGLESv2_nvidia.so
/usr/lib64/opengl/nvidia/lib/libGLESv2_nvidia.so.2
/usr/lib64/opengl/nvidia/lib/libGLESv2_nvidia.so.418.56
/usr/lib64/opengl/nvidia/lib/libGLX.so
/usr/lib64/opengl/nvidia/lib/libGLX.so.0
/usr/lib64/opengl/nvidia/lib/libGLX_nvidia.so
/usr/lib64/opengl/nvidia/lib/libGLX_nvidia.so.0
/usr/lib64/opengl/nvidia/lib/libGLX_nvidia.so.418.56
/usr/lib64/opengl/nvidia/lib/libGLdispatch.so
/usr/lib64/opengl/nvidia/lib/libGLdispatch.so.0

**Comment by aTosser** [comment]
Clear example, I can run EVE Online from the CLI with wine with no problems, however if I run it from lutris:

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  51
  Current serial number in output stream:  50
2019-03-25 01:51:59,746: glxinfo call failed: Command '['glxinfo', '-B']' returned non-zero exit status 1.
2019-03-25 01:51:59,747: No available glxinfo output
Running /home/ren/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine /mnt/internal/Games/eve-online/drive_c/EVE/eve.exe
Waiting on children
All children gone
Exit with returncode 0

This is EXCLUSIVELY a lutris isue.

**Comment by tannisroot** [comment]
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request: GLXBadContext
Major opcode of failed request: 150 (GLX)
Minor opcode of failed request: 6 (X_GLXIsDirect)
Serial number of failed request: 51
```
Lutris is incapable of producing this. This error is produced by mesa, which means there is something wrong with your system, and not Lutris.

**Comment by strycore** [comment]
Does it make a difference to disable the runtime in the system options? also could you submit a file generated with `lutris --submit-issue`?

**Comment by aTosser** [comment]
The underlying issue is that lutris expects libGL.so.1 to be in one of the predefined library folders that are hard coded in linux.py. Unfortunately, not all distros (gentoo) symlink the nvidia proprietary drivers to that location, instead they instruct the linker to look in the correct directory. In gentoo the nvidia drivers are located in the directories that I have posted above.

@tannisroot The reason that message is displayed is because lutris incorrectly uses the libGL.so.1 that is provided by mesa. Gentoo allows for more that one implementation of various applications and libraries to be installed simultaneously on the system. It has a tool for the user to select an implementation to use on the system that then edits /etc/ld.so.conf* to instruct the linker to look for files in directories in a specific order. Every program respects this process except for lutris.

I spent all of last night talking to gentoo folks and pouring through the lutris code.
I even spent some time looking to see if I could write some code that would query ldconfig for the paths for the libraries (they show up in the correct order from /etc/ld.so.cache) I think that would be a valid way to locate the libraries and their respective directories.

**Comment by aTosser** [comment]
@strycore 
[lutris-issue-report.json.gz](https://github.com/lutris/lutris/files/3003982/lutris-issue-report.json.gz)

**Comment by aTosser** [comment]
Please compare:

https://github.com/aTosser/lutris/blob/master/lutris/util/linux.py

**Comment by anders-larsson** [comment]
Hi,

I'm also using Gentoo and I can confirm the issue mentioned by @aTosser. The provided file in the previous post does solve this issue and the library can be found successfully.

Would someone mind having another look at this?

**Comment by opncow** [comment]
Yup, same issue here on my Gentoo system.

**Comment by mati865** [comment]
@strycore this still doesn't work on gentoo. Could you at least reopen this issue until it's fixed?

**Comment by strycore** [comment]
Sure!

**Comment by aTosser** [comment]
To the gentoo users around I have a fork that has a patch to work on gentoo systems. I would love to have some testers and if everything works out well with it I will submit a PR for merge.

**Comment by xelibrion** [comment]
@aTosser installed lutris from a custom ebuild pointing to your fork, was able to launch Steam.

**Comment by opncow** [comment]
@aTosser I do not have Lutris/Wine installed anymore and therefore unfortunately cannot help with testing.

**Comment by anders-larsson** [comment]
I can confirm in my case replacing lutris/lutris/util/linux.py with the file in @aTosser's repository fixes it for me, again.

**Comment by zovt** [comment]
Another confirmation, using @aTosser 's fork fixes this issue.

**Comment by strycore** [comment]
I've combined @aTosser 's implementation with our current one, can someone on Gentoo confirm that this fixes the issue?

**Comment by aTosser** [comment]
Firstly, I would like to say thank you for looking into this.

I did a fresh clone from current master as soon as I got the email notification. ( My fork is only synced up to commit:  2a85712e

If I run with the system wine I have to manually disable the lutris runtime (which I had to do with my fork as well) and things run as expected. 

If I try to run overwatch with the lutris provided wine (lutris-4.13-x86_64) with the runtime enable (which I do almost every day with my fork) The battle.net app dies shortly after login. The main application window does not display. I assume this is because it is the first directX part of the application.

I am also getting some interesting callback, seemingly related to the new autohide option, on stdout: [http://dpaste.com/11T4FVK](http://dpaste.com/11T4FVK)

Comparison debug output of my fork: http://dpaste.com/3CDEMY6

Let me know if you need anything. My system and I are at your disposal.

**Comment by strycore** [comment]
@aTosser thanks for the feedback! I fixed the error for the autohide option. Can you comment out lines 280 to 288 of linux.py, making this similar to your implementation and see if that fixes the crash.

**Comment by aTosser** [comment]
WIth those lines commented out overwatch runs!

I would like to point out that these debug/info messages appear before the application actually exits (this also occurs in my fork and I was unsure if it was an issue or not. So I did not look into it.) :

`All children gone`
`Exit with returncode 0`
`DEBUG    2019-08-31 21:07:45,471 [command.on_stop:161]:The process has terminated with code 0`
`DEBUG    2019-08-31 21:07:45,471 [command.stop:241]:Management process looks dead already.`
`DEBUG    2019-08-31 21:07:45,471 [command.stop:249]:Detaching logger`
`DEBUG    2019-08-31 21:07:47,186 [game.beat:596]:Game thread stopped`
`WARNING  2019-08-31 21:07:47,186 [game.on_game_quit:628]:Game still running (state: running)`
`INFO     2019-08-31 21:07:47,186 [game.stop:611]:Stopping Overwatch (wine)`
`DEBUG    2019-08-31 21:07:47,187 [command.stop:241]:Management process looks dead already.`
`DEBUG    2019-08-31 21:07:47,187 [command.stop:253]:logger already detached`
`DEBUG    2019-08-31 21:07:47,194 [discord.ensure_discord_connected:39]:Ensuring connected.`
`DEBUG    2019-08-31 21:07:47,194 [discord.ensure_discord_connected:41]:Already connected!`
`INFO     2019-08-31 21:07:47,195 [discord.clear_discord_rich_presence:111]:Attempting to clear Discord status.`
`DEBUG    2019-08-31 21:07:47,196 [game.on_game_quit:647]:Overwatch stopped at Sat, 31 Aug 2019 21:07:47`
`DEBUG    2019-08-31 21:07:47,196 [game.save:221]:Saving Overwatch (wine)`
`DEBUG    2019-08-31 21:07:47,202 [lutriswindow.on_game_updated:730]:Updating game Overwatch (wine)`
