### ISSUE TITLE
Manual installation of GOG games does not progress

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1927]
How to reproduce:
1. Log out of GOG if not already
2. Try installing a GOG game (i used https://lutris.net/games/mirrors-edge/)
3. Refuse to login and select the installer EXE manually.
4. Refuse to login again (caused by https://github.com/lutris/lutris/issues/1925), proceed installation

Observed behavior: the installer installs files and Lutris reports that it exited gracefully:
```Waiting on children
Waiting on children
All children gone
```
but it will not progress to the next installation step after that and will be stuck on current one.
Expected behavior: the installation progresses normally

I should note that this does not happen (with the same installer) when you are logged in.

**Comment by strycore** [comment]
Fixed by the fix for #1925
