### ISSUE TITLE
Failed to extract to wine-tkg-4.0-x86_64.tar.gz

### ISSUE THREAD

**Issue by LibertSin** [lutris/lutris#1929]
install overwatch in "https://lutris.net/games/overwatch/"

that script download wine and extract this file 
https://lutris.nyc3.digitaloceanspaces.com/runners/wine/wine-tkg-4.0-x86_64.tar.gz

but extract fail with this  masage. 
Failed to extract /wine-tkg-4.0-x86_64.tar.gz: Error-3 while decompressing data: invalid stored block lengths

**Comment by tannisroot** [comment]
Should be fixed by https://github.com/lutris/lutris/commit/cff571e0f0b7686a88b3ed1e7a9e29d9d24b8e4e
