### ISSUE TITLE
GOG Galaxy support

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#193]
https://www.gog.com/galaxy

I'm not entirely sure how this would or should work, but perhaps some people would like to have Lutris install games from GOG via GOG Galaxy? They should have their Linux client out "soon" and by then, it may make sense to have a split akin to how we currently handle Steam.

**Comment by strycore** [comment]
This is indeed on the roadmap, there are a couple GOG downloaders on Linux that we can use to achieve this.

**Comment by RobLoach** [comment]
https://github.com/lutris/lutris/issues/154 is another issue on this.

**Comment by RobLoach** [comment]
Lutris could go the route of an API, like suggested in #154, but until that comes, you could use the clients themselves:
- https://lutris.net/games/gog-galaxy/
- https://lutris.net/games/gog-downloader/

Until then, suggest closing this issue.

**Comment by strycore** [comment]
GOG Galaxy support is unlikely to ever happen since the goal of Lutris is to become a fully usable alternative to Galaxy. I'm closing this issue and the rest of the development will be tracked on #154

**Comment by basxto** [comment]
So are there plans for lutris to support achievements and such?

**Comment by PopeRigby** [comment]
Supporting achievements would be great.

**Comment by CartoonFan** [comment]
+1 for achievements.

**Comment by ErickTucto** [comment]
Plssssss achievements
