### ISSUE TITLE
Give "app already running" message when Lutris is already running

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1934]
>I had the idea to bring up the task list and search for lutris… Found it… killed it and retried. It’s working now. Aparently it must have gotten a fluke and didn’t display the first time and went zombie. Since it was still running then futher attempts to run it got ignored. I wish it would give an app already running error like steam does. That way the user would know right away to check the task list.

https://forums.lutris.net/t/lutris-gaming-app-will-not-run-after-updating-nvidia-driver/5338/5?u=cxf

**Comment by strycore** [comment]
This is going to be addressed in #1953
