### ISSUE TITLE
Fifa 19 won't launch

### ISSUE THREAD

**Issue by gros319** [lutris/lutris#1935]
Origin starts allright, the game downloaded properly. When I hit play I got the the blue screen with 3 option : PLAY / OPTIONS / EXIT and when I hit play nothing happens. Any ideas?  Here are screenshots of my config

![Screenshot-20190325190303-840x625](https://user-images.githubusercontent.com/34762947/54903801-d7db2a80-4f30-11e9-86b6-1f7e713a0752.png)
![Screenshot-20190325190342-885x943](https://user-images.githubusercontent.com/34762947/54903809-dad61b00-4f30-11e9-88c4-0405f68a846f.png)
![Screenshot-20190325190357-892x364](https://user-images.githubusercontent.com/34762947/54903817-df9acf00-4f30-11e9-93c0-e5ab1d6d54c3.png)
![Screenshot-20190325190409-872x907](https://user-images.githubusercontent.com/34762947/54903819-e295bf80-4f30-11e9-8b53-3dab13d3a410.png)
![Screenshot-20190325190422-901x660](https://user-images.githubusercontent.com/34762947/54903820-e45f8300-4f30-11e9-8c06-027a7ded0cfb.png)

**Comment by telans** [comment]
This doesn't seem like a lutris issue but more of a game issue. Try the lutris forums.

**Comment by gros319** [comment]
Yes sorry I understood my mistake too late.

Thanks for your time.
