### ISSUE TITLE
Wine prefix not creating properly due to package update

### ISSUE THREAD

**Issue by duerrwlu** [lutris/lutris#1942]
First of all "--submit-issue" is an "unknown option" apparently, so I cannot send useful output thereof. "uname -a" outputs "Linux LC-Lukas 5.0.3-1-MANJARO #1 SMP PREEMPT Tue Mar 19 18:26:12 UTC 2019 x86_64 GNU/Linux". I already installed Manjaro onto another drive, which did **NOT** fix or alter the issue in any way.
**The issue:** WINE prefix creation fails every time (debug logs of Lutris and manual creation attached), however WINE itself still can do the process - so it may be related to Lutris (the reason I asked here). The issue arises after the first reboot when said 95 packages are updated. Many of them seem unrelated, but I am almost certain that one is causing this problem as kernel version 5.0.3 does work fine until they are updated (restored via Timeshift several times). I may find out which package(s) cause(s) the issue by trial and error. Lutris worked flawlessly before and never had this problem. I consider myself and intermediate user, but might need assistance here if the problem isn't just temporary. Kind regards...
The full list of updated packages: https://paste.ubuntu.com/p/Bhvq3gSxcK/
The reduced list with unlikely candidates omitted: https://paste.ubuntu.com/p/XRXtvXMQyx/
The Lutris log of installing Overwatch as an example: https://paste.ubuntu.com/p/T8q3cyCT22/
The (verbose) log from manual creation: https://paste.ubuntu.com/p/zKQdXrXdfN/
Just in case, a list of all installed packages: https://paste.ubuntu.com/p/MdqS57kM5g/

**Comment by strycore** [comment]
can you update to 0.5.1 and see if you still experience the issue?
If you're still using the OBS repositiory, please consider removing it and migrating to the PPA as described in https://lutris.net/downloads/ ?

**Comment by duerrwlu** [comment]
Nice thinking. I lost you at the OBS repository (I think that does not exist on Arch and derivatives thereof like Manjaro), but I installed the latest version of Lutris through downgrade (double checked that it is the latest version according to Arch Wiki) and it still had the same issue. Also, please note that this issue does not affect the function of already populated prefixes and is therefore "only" hindering me from installing new games.

**Comment by strycore** [comment]
yeah, I missed the manjaro part! 
looks like the Battle.net process is exiting with exit code 512 which seems to be an error related to directory creation.

**Comment by duerrwlu** [comment]
...which is exactly what I expected as the manual creation explicitly says that ("0010:err:setupapi:create_dest_file failed to create"...). The problem is not related to access rights or anything similar, since chown'ing the folder to my user and group did not fix it and the problem does not occur without the latest packages. So, I am almost sure that one of those packages creates an issue that can only be fixed by its or the Lutris creators and can be bypassed by using an outdated version of said package unless there is some easy workaround. However, I of course do not want to use outdated packages long-term.
Thanks for your assistance though. If everything's falling apart, I will go back to that Timeshift backup on my "old" installation and IgnorePkg every package that could cause the issue and update all remaining, to see if the problematic package was updated alongside. That should take me a few hours at worst. Is that a good idea?

**Comment by duerrwlu** [comment]
--submit-issue now works under the current version.
file:///home/lukasd/lutris-issue-report.json

**Comment by duerrwlu** [comment]
"--submit-issue" now works with the latest version.
[lutris-issue-report.zip](https://github.com/lutris/lutris/files/3006396/lutris-issue-report.zip)

**Comment by duerrwlu** [comment]
I just did a "grep -f" of the packages that were updated with direct dependencies of wine-staging and got no correlation (no output). However with Lutris dependencies the output is:
glib2-2.60.0-1-x86_64.pkg.tar.xz
gtk3-3.24.7-1-x86_64.pkg.tar.xz
lib32-glib2-2.60.0-1-x86_64.pkg.tar.xz
webkit2gtk-2.24.0-1-x86_64.pkg.tar.xz
So all of these four are direct candidates of creating the issue, so I will update all other packages and see if the issue arises anyway. If not, it is easy to rule out or confirm one package at a time.

**Comment by duerrwlu** [comment]
I found the package that caused all this. It was **udisks2 version 2.8.2-1**, version 2.8.1-1 is unproblematic. I could fix the issue on my new installation just by downgrading the package manually and ignoring it. Since there is no newer version right now, I will use this package outdated for now and probably inform the developers of that issue. Thanks for your help and maybe also look into the bug stated above.
