### ISSUE TITLE
How can I open wine control?

### ISSUE THREAD

**Issue by FrontMage** [lutris/lutris#1944]
I have to install a cert file using wine control, but I can't find a place to launch wine control in lutris.

Plz help!

**Comment by strycore** [comment]
![2019-03-26_10-38](https://user-images.githubusercontent.com/280336/55020100-63959b00-4fb3-11e9-8d7c-3f3ff0e4c6b9.png)

**Comment by FrontMage** [comment]
@strycore this won't open the control panel like this.
![image](https://user-images.githubusercontent.com/17007026/55143645-1adc0e80-517a-11e9-819d-1fb9ff364808.png)

**Comment by strycore** [comment]
I've never seen that, I don't know the command to open such a window.

**Comment by telanus** [comment]
https://wiki.winehq.org/Control

I tried what it states there and I was able to open the control panel, But I'm not sure we need to add a shortcut for it as it might only be useful in 0.004%, and a wiki entry might be more useful

@FrontMage Use the "Run EXE inside wine prefix" go to the prefix's drive_c/windows/system32/ then select control.exe and run that, it'll open the prefix' Control Panel

**Comment by strycore** [comment]
Well there we go 
![2019-03-28_11-13](https://user-images.githubusercontent.com/280336/55182265-8b6b3700-514a-11e9-8a98-85b781c64398.png)

**Comment by strycore** [comment]
I guess we can substitute the Joystick panel button with a Wine panel button

**Comment by FrontMage** [comment]
@telanus That works! Thank you!
