### ISSUE TITLE
New filter: only list (uninstalled?) games that have a Lutris installer

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#195]
Having all of my not-installed Steam games (and then some) shown in the Lutris interface is all well and good, but it's frustrating to then try and install one. It would be great if Lutris would have an option to only show games that it can actually install.

**Comment by Xodetaetl** [comment]
Aye, a way to differentiate the (uninstalled) games that don't have installers would be useful. On the website it's done by having a darker background on the game's row in the list.
