### ISSUE TITLE
Add required libs to wine runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1951]
Now that Lutris has moved away from OBS to Launchpad which should have support for 32 bit dependencies, it would be nice to finally get rid of stupid requirment to have Wine installed on the system separately to satisfy Wine dependencies and add them as Lutris' own.
Basically, we want to add *every* not optional and optional dependency of winehq-staging plus some additional stuff like 
`libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libsqlite3-0:i386`
for apps like Origin and Battle.net and also both 64 and 32 bit vulkan loaders.

**Comment by strycore** [comment]
The same spec file is still used to build Debian on OBS so it wouldn't work

**Comment by tannisroot** [comment]
So what about making a separate spec file for Debian that won't include those wine dependencies?

**Comment by strycore** [comment]
I'm going to create a lutris staging PPA and see if we can have an automated deploy setup for both the PPAs and OBS

**Comment by strycore** [comment]
What if we install those dependencies at runtime, like Steam does? I'm sure that we could provide a better experience than their xterm window. That way, people who don't use wine don't have to install extra dependencies.

**Comment by strycore** [comment]
Better yet. What if we have a window with every feature we support and we detect which libs are installed to see if the feature is available or not. If the feature is not available we can propose to install a predetermined set of packages that will provide full support. We can have features like "Basic wine support" with just the lutris runner installed, "Full Wine support" which would install every Wine dependency. "Vulkan and DXVK support" with all the Vulkan stuff. We can even add non-packaging related features like "Esync support".

**Comment by strycore** [comment]
We have some of this implemented already for Citra already. We can also set the require_libs attribute for the wine runner

**Comment by tannisroot** [comment]
Added the libs to runtime
