### ISSUE TITLE
[Patreon goal] StatusNotifierItem based tray + better window handling

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#1953]
This ticket is a follow up to #1692. 
Re-introduce a StatusNotifierItem based tray icon (the same type Steam and Discord use)
Lutris should not run in the background, unless an option is explicitly enabled.

The initial implementation can re-use code from Pithos, https://github.com/pithos/pithos/blob/6bf437ef59a057e90476bfe9464fdf9306c449da/pithos/plugins/notification_icon.py#L46-L66
Although, this implementation uses AppIndicator to provide the KStatusNotifier item and I'm not sure if AppIndicator is going to stay relevant in the long run. 
A solution is to hook up https://github.com/TingPing/statusnotifier to some Python code. The statusnotifier bindings will likely have to be packaged and distributed as well since those are not widely available in current distributions.

Specifications:

A list of windows should be kept at the application level (See #1908)

When the game is run with rungame / rungameid, the main window should not be created.

If a D-Bus timeout can be detected (or the application doesn't respond and we somehow have a way to detect it) then display a message to the user, possibly offering to kill the application (See #1934)

**Comment by TingPing** [comment]
Clarification https://github.com/jjk-jacky/statusnotifier is the upstream repo and its bindings work out of the box. Indeed the problem is nothing packages it.

AppIndicator is indeed unmaintained but its packaged everywhere.

**Comment by strycore** [comment]
Implemented a basic version using AppIndicator, the StatusNotifier implementation isn't widely distributed.
