### ISSUE TITLE
Add support for d9vk 

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1957]
Obviously it's not ready yet but it's getting closer and closer to rendering games properly.

https://github.com/Joshua-Ashton/d9vk

![](https://cdn.discordapp.com/attachments/545938151739228191/560608763548139528/unknown.png)

![](https://cdn.discordapp.com/attachments/545938151739228191/560609567201820682/unknown.png)

Builds: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by Zeioth** [comment]
It might be functional before we expect:
https://www.youtube.com/watch?v=HNpBncAs0Ek

**Comment by VortexAcherontic** [comment]
I tried to fiddle around with pre-launch scripts to achieve d9vk in a winesteam game to check out the differences and hopped for performance gain. But had no luck in running the game with d9vk at all maybe I was just to dumb to use the pre-launch command section by adding a custm shell script to be executed before lutris launches steam.exe or maybe the d9vk dlls just got rested by lutris afterwards. Not sure =/
I would love to see this feature included into Lutris :D
(When d9vk is ready it seems)

**Comment by Zeioth** [comment]
On a second thought, D9VK will probably be integrated inside of DXVK once it is mature enough, as DXUP did.

**Comment by strycore** [comment]
a PR adding support for vk9 has been merged already. For proving custom DXVK builds, see #2007
