### ISSUE TITLE
"lutris -i" don't create wineprefix correctly

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#1958]
When I install a game using

    lutris -i ./myscript.yaml

**What is working:**
The dependencies of the scripts are installed correctly.

**What is not working:**
The directories of wineprefix are empty (dosdevices and drive_c).

**How to reproduce:**

* Run "lutris -i" with any of the next 3 scripts.

**How to debug**

* Under "Configure  > Game options" make sure that the wineprefix string is not empty (it was on my end).
* "Right click on the game > wine configuration" and check the output of the lutris debug console.

[scripts.tar.gz](https://github.com/lutris/lutris/files/3015847/scripts.tar.gz)

**Comment by AccountOneOff** [comment]
Can't reproduce. Works for me.

**Comment by strycore** [comment]
yeah, scripts look standard. There are other issues related to prefix failing to create. This is lacking too much info.
If there is a problem with the installation of MediaFoundation then be more specific about it. I have only tested the feature on Darksiders. Also, MediaFoundation happens way after the prefix has been created so probably unrelated.

**Comment by Zeioth** [comment]
I've created a more basic example:
    
    lutris -i ./basic-example.yaml

No wineprefix directory is created, and the game settings show None/prefix.
![00](https://user-images.githubusercontent.com/3357792/55123225-02301200-5102-11e9-9492-4bf32aeb895a.png)

Now If I indicate manually the path where I want it to create the wineprefix, using the GUI, and then I go to "wine configuration":
![11](https://user-images.githubusercontent.com/3357792/55123360-7e2a5a00-5102-11e9-9ce7-7ca516fbfa16.png)

I get the next error
![22](https://user-images.githubusercontent.com/3357792/55123395-b0d45280-5102-11e9-85dc-3a0dbb7b9f4f.png)

And if I disable dxvk, I get the final error:
![33](https://user-images.githubusercontent.com/3357792/55123458-f8f37500-5102-11e9-838a-84d30e602c2e.png)

Setup:

* Lutris master
* Antergos + XFCE


Anyway, if it work on both your ends, I'll asumme it's a problem on my side. Thank you.

[basic-example.yaml.tar.gz](https://github.com/lutris/lutris/files/3015870/basic-example.yaml.tar.gz)

**Comment by strycore** [comment]
what kind of drive are you installing the game on, what file system?

**Comment by strycore** [comment]
if you really want to fix it you have to reproduce it outside of lutris (by using the same parameters, same wine build, with lutris runtime)

**Comment by Zeioth** [comment]
The file system might be the cause, actually.

**NTFS:**
The error I described in my previous post.

**EXT4:**

Still doesn't create the wineprefix during the installation, and it shows the value "None/prefix" under "game options > wineprefix", but after I indicate the correct path using the GUI, and go to wineconfig, the prefix is created correctly.

**Comment:**
If this is actually a bug, it is a slippery one. I'll keep researching tomorrow and I'll try to express it in an easier to understand way. Maybe a video.

**Comment by strycore** [comment]
yeah there's going to be a warning about installing games on NTFS drives. That doesn't work. Don't install games on NTFS drives. Are you sure the error on ext4 is not a side effect on the previous NTFS install?

**Comment by Zeioth** [comment]
I've performed the next tests:

    WINEPREFIX="/my_ext4_hd/prefix/" winecfg
    WINEPREFIX="/my_ntfs_hd/prefix/" winecfg

**Results:**
Ext4: Creates the wineprefix correctly.
Ntfs: Fails to create the wineprefix

**Conclussion:**
It is not Lutris fault.

**Comments:**
Since I've always been able to create prefixes on both units until now, my best guess is that some new tkg wine patch is doing something weird. I apologize for the inconvenience. Thank you for your time.

**Comment by strycore** [comment]
As I said previously there will be in a warning in the future about that (See #1313 and #1809 )

**Comment by Zeioth** [comment]
Confirmed: [They don't support NTFS anymore](https://forum.winehq.org/viewtopic.php?f=2&t=32188&e=0)

**Comment by Zeioth** [comment]
**SOLVED**
After I mounted the NTFS-3G disk with the next permissions on fstab, winecfg works fine again.

    UUID=53B3871A016FD97A /run/media/zeioth/datos/ ntfs-3g uid=1000,gid=1000,umask=077,fmask=177

The last update of XFCE seems to have broken the way the desktop environment mount NTFS-3G disks by default.

**Comment by strycore** [comment]
Good to know there's a workaround! 
We should probably include this information in the FAQ, PRs welcome!
