### ISSUE TITLE
Add cache config link to installer window

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1960]
Instead of being an option that gets activated only after you manually select the location for cache folder in the path field that is empty by default, it should be a enabled/disabled toggle _**and**_ a path field that already has default location filled in (with the ability to change it) somewhere in `~/.cache/lutris/`.

**Comment by strycore** [comment]
That will be handled with #474 and and #1905

**Comment by strycore** [comment]
The file picker branch is merged but this still needs more work.
