### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by pctekmcs** [lutris/lutris#1962]
Linux Mint Slyvia. Ex gaming PC.
Tried 3 games, already had Wine installed and Minecraft worked, as well as a couple of other things not from Lutris.
All 3 games I tried sat for ages and ages saying either downloading, or wine wanted some additional thing, gecko or some such and never started never mind completed.
Internet connection fine, on fibre, no issues anywhere with anything at all except trying to install something from Lutris.
Oh and have a Steam account too, installed. 
Thought this thing was meant to make it all easier?

**Comment by strycore** [comment]
You're very likely encountering a bug with Lutris blocking the installation. Sadly this report does not provide enough information to help us resolve it. Please see with the support team on Discord https://discordapp.com/invite/Pnt5CuY or the forums https://forums.lutris.net/ to help you troubleshoot the issue you're having.

You can also try the instructions given here https://lutris.net/faq#game-crash
