### ISSUE TITLE
Wine Steam system tray icon no longer appears

### ISSUE THREAD

**Issue by jttheninja** [lutris/lutris#1964]
A while back, I tried installing the Proton version of a game (honestly cannot remember which one), and it said that I didn't have the proper 32-bit packages. So I quit the installation and decided to try later, maybe with the non-Proton option. But now whenever I launch Wine Steam (or launch a Wine Steam game), the system tray icon does not appear, so if I ever close the main Steam window, I can't re-open it.

I'm running Xubuntu 18.04 64-bit.

**Comment by strycore** [comment]
that's not a lutris bug but I would be interested in having the solution because I have lost the Steam tray as well on my main rig

**Comment by strycore** [comment]
so I don't  know about you but on my end, the Steam tray icon is back with Wine Steam. Might have been a regression in Wine itself. Please try with the latest wine-tkg.

**Comment by tannisroot** [comment]
Make sure you are not using tkg-4.2 because it had a patch that causes this (it's no longer present in newer versions).

**Comment by jttheninja** [comment]
What's the latest version of tkg? 4.2 looks like the latest version I can select.

**Comment by strycore** [comment]
We have tkg-4.5 available in the wine download dialog.
