### ISSUE TITLE
GOG games download .sh file even when runner is set to Wine

### ISSUE THREAD

**Issue by tournierjc** [lutris/lutris#1971]
Hello,

When I try to install the GOG Windows version of The Witcher II : Enhanced Edition, the Lutris installer keep downloading the .sh file instead of the setup.exe and all .bin files.

After installation, I then have the same issue #1745 (file not found) as the game hasn't been installed.

**Comment by AccountOneOff** [comment]
I changed the installer so Lutris doesn't download anything and you have to provide the exe and bin files yourself. This doesn't fix the problem but works around it. Maybe strider can comment on this.

**Comment by strycore** [comment]
yes, we have to improve support for that, currently there is some code that will automatically get the Linux version if one is available.
