### ISSUE TITLE
lutris takes so much time to open after updating

### ISSUE THREAD

**Issue by yurisuki** [lutris/lutris#1973]
so, i use the newest lutris version on arch and it takes so long to open.

debug doesn't show any errors and looks completely fine.

**Comment by Zeioth** [comment]
It's a new problem or it's been always like that? It only take 4 seconds to open on my end.

**Comment by yurisuki** [comment]
im using lutris-0.5.1.2 on 4.20 linux-zen
im using arch linux
hdd (ext4)

just writing `lutris -v ` took about 30 secs to show the version.

**Comment by strycore** [comment]
30 seconds is not normal, there is something blocking lutris.
Try disconnecting from your Lutris account in the client and see if this improves startup times. Likely to be a library sync issue

**Comment by yurisuki** [comment]
On 19/03/31 12:23, Mathieu Comandon wrote:
> 30 seconds is not normal, there is something blocking lutris.
> Try disconnecting from your Lutris account in the client and see if this improves startup times. Likely to be a library sync issue
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lutris/lutris/issues/1973#issuecomment-478372259
i mean, i don't even have lutris account and if this changes anything, i
have a game that has over 100 gb in lutris.

**Comment by strycore** [comment]
no, the size of games have no effect on startup times, we don't scan anything.
can you open lutris from a console with lutris -d and paste the output and point to where it's blocking?

**Comment by yurisuki** [comment]
[yuri@WEEBzone ~]$ date && lutris # Using date, so you can see when i
executed that command
Ne bře 31 21:33:26 CEST 2019
2019-03-31 21:33:51,576: Running Lutris 0.5.1.2
2019-03-31 21:33:51,576: Using Intel Open Source Technology Center
2019-03-31 21:33:51,576: Running Mesa driver 19.0.1 on Mesa DRI Intel(R) Haswell Mobile  (0x416)
2019-03-31 21:33:51,576: GPU: 8086:0416 103C:1942 using i915 drivers
2019-03-31 21:33:51,578: Vulkan is not available or your system isn't Vulkan capable
2019-03-31 21:33:51,579: Updating DXVK versions
2019-03-31 21:33:55,956: Shutting down Lutris
[yuri@WEEBzone ~]$

**Comment by strycore** [comment]
Oh, so it's blocking *before* the version even shows up the version, that's weird.... 
I guess that trouble shooting this would involve getting the source code and commenting some lines in lutris/startup.py, are you comfortable doing that?

**Comment by yurisuki** [comment]
no, i'm free to do it.

**Comment by strycore** [comment]
alright, cool. 
open the lutris/startup.py and go to the end where run_all_checks is defined. Then comment all the function calls out with `#` (not the docstring, it's needed here to keep the python syntax valid once we've commented everything)
Once you have confirmed that this slowdown is caused by the checks, comment them one by one and find which one is slow.
Let me know what you find out.

**Comment by yurisuki** [comment]
So, I think the cause is completely different. it shows, it took only one second, but it took lutris to show ~26 seconds, so that's pretty much the same.

```
[yuri@WEEBzone lutris]$ date && bin/lutris
Út dub  2 20:51:39 CEST 2019
2019-04-02 20:52:04,685: Running Lutris 0.5.1.3
2019-04-02 20:52:04,685: Updating DXVK versions
```

**Comment by strycore** [comment]
please comment the line that runs the DXVK update and see if that solves the issue

**Comment by strycore** [comment]
I'll postpone this ticket to 0.5.3 to leave you time to locate the issue.

**Comment by yurisuki** [comment]
> please comment the line that runs the DXVK update and see if that solves the issue

which one does that?

**Comment by strycore** [comment]
in lutris/application.py line 224. But I realized it's using AsyncCall so that's not it. Just comment the run_all_checks above and see if it's resolved.

**Comment by yurisuki** [comment]
i did so, but it still says Updating DXVK versions
```
2019-04-06 10:34:01,981: Running Lutris 0.5.1.3
2019-04-06 10:34:02,018: Updating DXVK versions
```

**Comment by yurisuki** [comment]
> in lutris/application.py line 224. But I realized it's using AsyncCall so that's not it. Just comment the run_all_checks above and see if it's resolved.

so, i've downgraded to lutris-0.4.23 and the same issue still happens, so i dont know what should i remove now.

**Comment by strycore** [comment]
Don't downgrade to 0.4.23. It does not help at all.
Go back to the current master and keep commenting lines out until you find the cause of the issue.
I cannot give you further assistance with the info I have.

**Comment by AaronOpfer** [comment]
Can you please try the following:

```
$ python -m cProfile -o profile $(which lutris) -v
```
This should output the same version string as before and should also create a `profile` file in the working directory.  Then upload this file somewhere and send it to us.

I warn that this file may contain your personal information such as file paths.

**Comment by yurisuki** [comment]
I'm sorry, I found a way to get rid of Lutris, and I currently don't have time to take a look at it. Once I'll have time I'll look at it.

Thank you.

**Comment by DeltaTimo** [comment]
It's been quite some time since the closing of this issue but even now I've still had this issue.
For me `Gtk.Application.do_startup(self)` in gui/application.py was the cause of the long loading times, approximately 25 seconds, which according to https://bbs.archlinux.org/viewtopic.php?id=243737 is the timeout for dbus.
https://www.reddit.com/r/archlinux/comments/a5d0sd/gtk_apps_taking_miserably_long_to_open_up/ebmramk suggested to add environment variables `DBUS_SESSION_BUS_ADRESS`, `DISPLAY` and `XAUTHORITY` to dbus and systemd using the following command (and adding it to `.xinitrc` for persistence), which has since solved the issue for me:
```dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY```
