### ISSUE TITLE
Wine cannot find the FreeType font library

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1981]
Origin doesn't render when "Prefer system libraries" is enabled.

![Screenshot from 2019-04-01 18-02-29](https://user-images.githubusercontent.com/15083452/55368762-7d9a1680-54a8-11e9-8633-dbd25e25fd48.png)

[lutris-origin-log.txt](https://github.com/lutris/lutris/files/3031911/lutris-origin-log.txt)

@aTosser

**Comment by BeholdersEye** [comment]
"closed this as completed". What a relief to others with the exact same problem. :|

**Comment by strycore** [comment]
This issue was closed 4 years ago and has received a fix.
Open a new issue if you have a bug.
