### ISSUE TITLE
Lutris does not import games all from Steam

### ISSUE THREAD

**Issue by testman42** [lutris/lutris#1983]
While importing games worked well in 0.4.23, I am encountering issues with importing games that are installed in Steam.
I'm not talking about synchonising the library, I'm talking about making games that are already installed in Steam also appear as installed in Lutris.

In :heavy_plus_sign: -> Import Games... under section for native Steam games selecting games and clicking "Import Games" button does not import all games.
Importing games that are installed directly in system works fine.
Example of entry that *does* get imported from Steam is Unreal Development Kit (available for free under Tools in Steam library. It's a 0 MB download that I assume serves only as a shortcut for manually installed UDK)
So even if I have all games selected, I will get notification that only one "game" was imported.

I'm using Fedora 29 x86_64 and Steam client beta.

Workaround for a single game is to find that game, clicking "Add installed game", selecting Steam as runner, finding it's Steam APPID on internet and pasting that into the "Application ID" field and then clicking Save.

Workaround to import all installed games is to download Lutris 0.4.23, enabling the automatic import of games from Steam, restarting Lutris 0.4.23 so that all games get imported, closing it and starting new version of Lutris again.

**Comment by tannisroot** [comment]
the issue is not described correctly. i will open one myself later

**Comment by zone1135** [comment]
I'm getting the exact same issue. 
I'm using Manjaro and have tried both the version of Lutris that is installed by my package manager and downloading the latest version from here.

I only get two tools appearing (dedicated servers for Starbound and Don't Stave Together) and one game (N++), for contrast I have 52 games installed.

Here is the debug output from the version that came with my package manager:
https://paste.ubuntu.com/p/NcJ7QFSnZJ/

(I know @tannisroot said they would open a new issue themselves but there didn't appear to be any posted yet so I thought I would at least put my log here and it can be copied to the new issue once it is made.)

**Comment by codeman101** [comment]
@tannisroot 

Where is the issue you opened for this. I'm having the same problem as well. The import section of lutris shows all my games but when I click select all and import they don't all show up on the launcher list. I personally don't care whether or not this gets resolved as I don't mind launching steam games from the steam client but you should know it is an issue.

**Comment by tannisroot** [comment]
https://github.com/lutris/lutris/issues/1999
