### ISSUE TITLE
Display a thing when the game library is empty

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1984]
In 0.4.x we had a welcoming screen with some instructions after launch Lutris for the first time, but in 0.5.x that kinda of disappeared now the user is greeted with the whole lot of nothing.
I think it might be a good idea to bring that back and show a tip about, for example, how you need to click on the search button to start installing games.
As a reference, this is how Gamehub does it:
![image](https://user-images.githubusercontent.com/10602045/55419029-9bd14680-557c-11e9-8fdf-27c30f00def6.png)

**Comment by AccountOneOff** [comment]
Something like Glade's interactive intro would be good.

**Comment by strycore** [comment]
![Screenshot from 2022-02-21 16-08-14](https://user-images.githubusercontent.com/280336/155041661-1674b439-5d0c-4526-bb98-d051a5b660be.png)

There's now a splash.svg image file that can be used to display any info we want

**Comment by strycore** [comment]
Thanks! For the font, you could go with Cantarell since it's the default for Gnome: https://wiki.gnome.org/Projects/CantarellFonts
Maybe the inclusion of Montserrat as well could be nice.

**Comment by hazelnot** [comment]
![splash-dark](https://user-images.githubusercontent.com/10992973/171192086-8c93be38-398c-405d-86fe-c7d350daf844.svg)
![splash-light](https://user-images.githubusercontent.com/10992973/171192093-36ac8ae9-cd8e-441e-9426-9f0aeb3b1fe1.svg)

Sorry for the delay, I legitimately didn't see your reply. How are these for starters?

**Comment by hazelnot** [comment]
That would be ideal, I just didn't know that was a possibility :sweat_smile:

**Comment by strycore** [comment]
Everything is possible!

**Comment by strycore** [comment]
Thanks, I've integrated those into the UI!
The main image is not centered like I'd like it to be but I'm not going to fight Gtk over this.

**Comment by danieljohnson2** [comment]
I'll fight GTK. And win!

The thing that keeps GTK from centering the graphics is the way blank_overlay is set to xscale=.1 and yscale=.1. I do not know why this would set this way; this is in the lutris-window.ui file.

PR #4393 resets the scale factors to 1, and then sets the bits of the splash to appropriate settings.

I used set_center_widget, which appears to require GTK 3.12. Is that okay? A more complex layout could probably be made without it.
