### ISSUE TITLE
Add a warning if 32 bit vulkan loader is not present

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1987]
This is a very very common problem that new users experience and it's really not obvious because everything in Lutris says that they have Vulkan working (but only with 64 bit apps)

**Comment by strycore** [comment]
what's the best way to detect that the loader is not present?

**Comment by tannisroot** [comment]
I think it's sufficient to just check for a 32 bit libvulkan library (libvulkan.so.1).

**Comment by strycore** [comment]
We already have detection of libvulkan.so.1, it's printed in the logs at startup. If you can provide some text for a "don't show again" dialog, I can include that in the next release.

**Comment by tannisroot** [comment]
"Vulkan library for 32-bit applications has not been found. This will make a lot games non-functional. To install it, please follow the instructions on this page: https://github.com/lutris/lutris/wiki/Installing-drivers"

**Comment by strycore** [comment]
why do we need a message for 32bit and not for 64? I don't understand why we have to mention the architecture

**Comment by tannisroot** [comment]
64-bit already has a warning message that pops up if you try to activate DXVK without installing Vulkan libs first or having unsupported graphics/card.
And we have to mention the architecture because it's very common for some to have pretty much completely working Vulkan setup with 64-bit libvulkan and all but missing 32-bit libvulkan.

**Comment by AccountOneOff** [comment]
Someone's complaining about the message being misleading.

>So only 32-bit games wouldn’t work with DXVK enabled when I only have the 64bit version?
>
>This makes the warning message Lutris gives quite misleading, it makes it sound as if DXVK would not work at all.

https://forums.lutris.net/t/why-do-we-have-to-have-32bit-dxvk-installed/5503/3?u=cxf
