### ISSUE TITLE
Allow to save logs straight into files

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1988]
It's very very useful when you are debugging a game and the produced logs are huge.

**Comment by mihawk90** [comment]
I was actually playing around with this a few days ago and I thought I could make it work via an action in the desktop file, but it doesn't seem to be as easy.

In the terminal we can already do `lutris -d > /path/to/file.log`, so I thought I could adapt that to a desktop file, but this doesn't seem to actually capture the output :/ any hints on that or do you want this as an option in the client?

**Comment by strycore** [comment]
make sure to redirect stdout and stderr to your file if you want to use this as a workaround. Implementing the feature in the client shouldn't take too long.
