### ISSUE TITLE
[Suggestion] Add wine-compholio/staging as runner

### ISSUE THREAD

**Issue by malkavi** [lutris/lutris#199]
I have been trying to play Child of Light with wine without success. But with patches from wine-compholio I can launch Uplay and Child of light.

Repository:
https://github.com/wine-compholio/wine-staging

**Comment by strycore** [comment]
yes, we plan to ship wine-staging builds soon, they should become available for the next release or even before

**Comment by strycore** [comment]
The build script for wine has been modified to optionally build wine-staging and there is now a build available for the latest version: https://lutris.net/files/runners/wine-staging-1.7.48-i686.tar.gz
