### ISSUE TITLE
Lutris fails to set executable, wine prefix, etc properly

### ISSUE THREAD

**Issue by steamp0rt** [lutris/lutris#1992]
Arch Linux, Lutris from Arch Linux repo. /home is XFS-formatted.

Games install properly, but lutris fails to set the executable/working dir/wine prefix. Setting them manually works. Has happened with Overwatch and BYOND.

**Comment by AccountOneOff** [comment]
Report needs logs

https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info

**Comment by steamp0rt** [comment]
Oh thanks, I'm kind of used to a template that shows up when you make an issue

**Comment by steamp0rt** [comment]
Ooook that's weird, as soon as I tried running it in `lutris -d`. problem fixed itself.
