### ISSUE TITLE
Multiple Proton versions all show as the same version in Lutris

### ISSUE THREAD

**Issue by BaronKrause** [lutris/lutris#1993]
On my Ubuntu machine I just installed the newest Lutris from the ppa/repo on the Lutris site, I had both Proton 3.16 and 4.2 installed in Stream but in Lutris they both showed as "Proton 3.16 (default)". It was actually listed twice, and when I added Proton 3.7 in steam it just made a third Proton 3.16 (default) in lutris.

After removing all but 4.2, then finally it showed as Proton 4.2 in lutris, but after re installing 3.16, the same issue came back, except this time it is showing a double "Proton 4.2 (default)"

Just figured I would report it!

**Comment by tannisroot** [comment]
I can reproduce this. For me, all Proton versions show up as 'Proton 3.16 (Beta)".

**Comment by tannisroot** [comment]
Still unresolved. Now the same versions get display 4 times.
