### ISSUE TITLE
If Steam game updates before launch, game is detected as stopped.

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#200]
Run a Steam game with a fat update, Steam's update window will pop up  and start downloading but since there is no child process other than steam, Lutris takes it the game was stopped.

**Comment by strycore** [comment]
Commit 9389aa2bf2d3722479 should fix the issue, does it look good for you?

**Comment by Xodetaetl** [comment]
Well, I was going to use precise detection of updating state with the "Update Running" Steam flag within the custom watch_game_process() function I've added to winesteam.

**Comment by strycore** [comment]
Oh, that would work too! What I've but in place was mainly to deal with Steam client updates (which are not reflected in a flag as far as I know). Anyway, when can have both so if you have something underway, go for it.

**Comment by AaronOpfer** [comment]
I think this is fixed, is it not?

**Comment by strycore** [comment]
yeah, I think it is
