### ISSUE TITLE
Add a "Success" pop-up dialog after importing games

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2000]
Right now, it's not exactly obvious for a new user what is supposed to happen after the importing process.
A small dialog with something like "n Game(s) were/was succesfully imported. They/It should now appear in the library" after the fact would greatly improve UX.

**Comment by null-von-sushi** [comment]
Would this interfere with the 'sync all games at startup' feature ?
Also, wouldn't using a notification be better suited for this then a dialog box?

**Comment by tannisroot** [comment]
@null-von-sushi if `sync all games at startup` is enabled, this message won't be showed.
And I think a notification is not really suitable for this when as you are interacting with the application in real time and didn't just leave it doing something in background.

**Comment by null-von-sushi** [comment]
Fair enough, I cannot see any issues with that then. I was just worried about dialog boxes I have to click away every time I start the application :D

**Comment by strycore** [comment]
I've changed the code so that a notification popup will always show up but I'm not sure if our notification system works on most installs so we might have to replace the notification with a message box.

Please test and send feedback if a message box seems more appropriate here.
