### ISSUE TITLE
Do something about the conflict of GOG importing and "Installed Games Only"

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2001]
Issue: if the user has "Installed Games Only" option enabled and then tries to import a GOG game, the user might get confused because the game won't be immediately visible in the library. And they probably won't immediately (or ever) link two things together and turn off the option to install the game as they might now know that GOG games will appear uninstalled and greyed out if they just started using Lutris, for example, or they might just not remember they ever even turned on the option in the first place. I can go on and make up a lot of reasons for this, but the point is that they will think the process failed, which is very bad.
Solution (perhaps not the most elegant one): turn off the "Installed Games Only" option after the importing of GOG games. And to not make old users annoyed that they have to re-enable the option each time after the importing process, an checkbox to retain the value of "Installed Games Only" called be added to the GOG importing menu.

**Comment by GregPK** [comment]
+1 on this. Was confused about this until I found this topic.

**Comment by strycore** [comment]
I think a good way to handle it would be to handle this like Shotwell, which has a "last import" filter in the sidebar.

**Comment by strycore** [comment]
Fixed by #3089

**Comment by strycore** [comment]
This is solved, all Humble Bundle and GOG games will now install. The concept of importing games has been removed.
