### ISSUE TITLE
 g_menu_model_get_n_items(): python3.7 killed by SIGSEGV

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#2006]
New Fedora report, seems to be related to #1820 maybe?

Version-Release number of selected component:
lutris-0.5.0.1-5.fc29

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: g_menu_model_get_n_items
executable:     /usr/bin/python3.7
journald_cursor: s=79043a942fa6440689b56d8e580869d4;i=3d42;b=32cf587541464057af1ff93d762cc54b;m=badf02289;t=585abac792b91;x=7390919c8c5242c3
kernel:         5.0.5-200.fc29.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 0 (10 frames)
 0 g_menu_model_get_n_items at gmenumodel.c:493
 1 gtk_application_window_update_shell_shows_app_menu at gtkapplicationwindow.c:316
 2 gtk_application_window_real_realize at gtkapplicationwindow.c:683
 3 _g_closure_invoke_va at gclosure.c:873
 6 gtk_widget_realize at gtkwidget.c:5471
 7 gtk_window_show at gtkwindow.c:6175
 12 gtk_widget_show at gtkwidget.c:4800
 14 ffi_call_unix64 at ../src/x86/unix64.S:76
 15 ffi_call at ../src/x86/ffi64.c:525
 16 pygi_invoke_c_callable at ../gi/pygi-invoke.c:690

**Comment by strycore** [comment]
I believe that one was fixed already, this is for lutris 0.5.0.
