### ISSUE TITLE
League of Legends fails to Launch on Mint 19

### ISSUE THREAD

**Issue by Ryu945** [lutris/lutris#2024]
At least 80% or more of the times I try to launch League of Legends, it launches but it doesn't show anything.  I can see the process running.   I can literally spend over half an hour trying to get League of Legends to launch correctly.

**Comment by strycore** [comment]
I've shipped wine-tkg 4.6 which should fix some issues with LoL. Also please test on a system that isn't Mint or Ubuntu 18.04 based. You should get more reliable results on Ubuntu 19.04 which is to be released in a few days.
