### ISSUE TITLE
lutris.runners.linux has no attribute create_prefix

### ISSUE THREAD

**Issue by dreamer** [lutris/lutris#2026]
After screen "Please select the GOG installer" (to point to `setup_diablo_1.09_v6_(28378).exe`) Lutris displays error:

    AttributeError("module 'lutris.runners.linux' has no attribute 'create_prefix'")

The bug appears when I try to install Diablo using diablo-devilutionx-gog-32-b installer: https://lutris.net/games/install/12418/view

Tested in:

  * lutris-0.5.1.2 (fedora rpm)
  * lutris-0.5.2.1 (git)

**Comment by strycore** [comment]
Not a bug, the linux runner has no create_prefix task indeed. If you want to call create_prefix in a non wine installer, you have to prefix it with wine like `wine.create_prefix`.

I noted that the runner used in the Devilution script changed from Linux to Wine so that should solve the issue.
