### ISSUE TITLE
Setting environment variables for Witcher 3 hangs system 

### ISSUE THREAD

**Issue by null-von-sushi** [lutris/lutris#2027]
I made a witcher 3 wineprefix and added it to lutris (manually since the installer assumes I have the installation files I think, however I don't have those anymore and my internet is bad. I just copied the Witcher 3 folder from Windows over and added it to a new prefix). So far so good, it works.

Since I was curious, I looked at [the install script](https://lutris.net/games/install/12494/view), and noticed that there are a few variables being set. 

Setting the cache for each game seems like a good idea, so I added 
```
    __GL_SHADER_DISK_CACHE: 1
    __GL_SHADER_DISK_CACHE_PATH: $GAMEDIR
```
to the environment variables section, but using these variables makes my computer hang. 
 
I tried running various things (the game, `dmesg -w`, `journalctl --follow`) in a terminal to get useful output, but the computer freezes before I get anything.

Any reason this happens?

**Comment by strycore** [comment]
Pretty sure those variables shouldn't be used since the game used Vulkan. I'd like someone else to confirm.

**Comment by strycore** [comment]
So I tried to reproduce that locally but couldn't get the game to crash. Please note that $GAMEDIR is for installers, you have to put the full path when entering environment variables in Lutris.

As I said earlier, those variables should be OpenGL specific so you can just remove them and you'll be fine.

**Comment by null-von-sushi** [comment]
Oh I see, I thought $GAMEDIR is dynamically set to the install path of each game (that would have been useful). And yeah, running it without said variables works fine.
