### ISSUE TITLE
Provide installer access via REST API

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#203]
I've found it very difficult to scan and curate scripts on the website. While I understand the desire to have a Lutris database as an online resource for all Lutris-enabled games, it would be much easier to edit the scripts if they were hosted in a GitHub repository.

Is this something that's feasable? Have the website download and import the database from a github repository of all the scripts.

**Comment by strycore** [comment]
While I don't think the script repository fits the model of a git repo, I do like the idea of being able to download all scripts available.
Would you be ok with a tar.gz containing every script available? Or would you prefer a web ui to browse through the scripts?

**Comment by RobLoach** [comment]
First is downloading, another is sending up changes easily. Was seeing if there could be a better way of editing.

**Comment by strycore** [comment]
Right. At some point it will be possible to read and interact with the installers from the REST API so it will open a range of new possibilities.

**Comment by RobLoach** [comment]
Mmm, interesting idea. Feel free to re-work this issue to be appropriate to these needs. :+1:

**Comment by RobLoach** [comment]
Imma close this... There are other ways too get listings of scripts and such in the admin UI.

**Comment by strycore** [comment]
Yeah but I'm still going to do it, plus it's really simple  :D

**Comment by strycore** [comment]
All installers: 
https://lutris.net/api/installers

Installers for a given game:
https://lutris.net/api/games/quake/installers
