### ISSUE TITLE
Lutris no longer exits after game exits.

### ISSUE THREAD

**Issue by foresto** [lutris/lutris#2030]
When launching a game directly with a command line like `lutris lutris:rungame/gamename`, and the game completes and exits, the lutris process is supposed to exit. This worked in version 0.5.1.3, but since upgrading to 0.5.2, the lutris process never exits. The last console output is:

2019-04-12 00:00:00,104: Stopping Battle.net (wine)

**Comment by strycore** [comment]
yes, this is a know bug that should get sorted out in the next release

**Comment by manuelVo** [comment]
This should be fixed in 6babc49

**Comment by tannisroot** [comment]
I've checked myself, indeed it is.
