### ISSUE TITLE
Lutris can't run ioquake3 X11 installer

### ISSUE THREAD

**Issue by dacobi** [lutris/lutris#2032]
When trying to install ioquake3 on Manjaro the ioquake3 X11 installer window fails to appear.
When the installer tries to launch xterm nothing happens. 

In the Lutris installer windows it says: 
Running /path/to/ioquake3/ioquaqke3-1.36-7.1.x86_64.run
Waiting on children
Exit with return code 0

**Comment by strycore** [comment]
Someone ordered the SSD from the Amazon wish list so I get to install Manjaro now :laughing:

**Comment by dacobi** [comment]
I tried modifying the Lutris installer.
If I set terminal: true
the ioquake3 installer runs as it should, 
but in text mode.

**Comment by strycore** [comment]
The scripts are now modified to extract the ioquake3 binaries from the installer files.
