### ISSUE TITLE
Unusual behaviour when downloading additional files

### ISSUE THREAD

**Issue by IroAlexis** [lutris/lutris#2035]
Description :
When the user starts the installation of a game (requiring the download of an additional file, example of uplay) and there is no Wine installation (runner).  Lutris will download Wine well but it will not display the download window for additional files (tested only on uplay games). The download is done in the background !?
On the other hand, if the user already has the version of Wine, we will have the download window indicating that he is downloading the additional file.

Lutris version : 0.5.2.1
[Log with a local installation](https://github.com/lutris/lutris/files/3077287/installation-process-local.txt) `lutris -d -i Projects/lutris-installer/assassins-creed/assassins-creed-iv_wine-uplay.yaml`
[Log with a "online" installation](https://github.com/lutris/lutris/files/3077289/installation-process-online.txt) `lutris -d`

PS : Sorry already for my english which could be approximate.

**Comment by strycore** [comment]
Wasn't able to reproduce that, might have been fixed already. Please re-open if you still experience issues.
