### ISSUE TITLE
Request user for optional files

### ISSUE THREAD

**Issue by mihawk90** [lutris/lutris#2037]
Currently any file we request via the file picker with something like `N/A:Select the game's setup file` seems to be a required file. It would be nice to have the ability to make the picker optional in certain cases.

Use-cases would be DLCs, patches, or files to optionally copy. For a specific case look at Witcher 3.
Not everyone owns the DLCs (tho they should :) ), and some people may or may not want to install the 1.32 patch for one reason or another.
Currently there seems to be no way of specifying either of them as optional. As a consequence, for a Lutris installer to also install one or both DLCs we would have to write 3 additional installers (DLC1, DLC2, DLC1&2), which would cause additional work for no real reason.

Another use case in Witcher 3 (though yes, very few games do this), it supports importing save files from Witcher 2. They can be copied by hand of course if you know the path, but using the file picker and a copy afterwards would be welcome.

If this is already possible, then I couldn't find anything on it

**Comment by strycore** [comment]
That request is valid but I wonder how we handle that in the script itself when a file might or might not exist.

The solution I've been thinking of for a while is introducing "sub scripts", those script could be plugged into a main installer and would have their own set of files and instructions. So at the end (or the start) of the install we can show a bunch of different optional steps to be applied during the install.

This is quite important for full GOG integration as we don't support DLCs currently and this would be a proper way to implement that.

**Comment by mihawk90** [comment]
That would be one way, I was thinking about just adding a flag in the selector, so II behead of using `N/A:xyz` we could have `optional` or `O/F` (optional file) and make the installer skip the step wherever that file reference is used.

Not sure what would be the better/easier way to implement, i.e. if those subscripts could be used for something else.

**Comment by strycore** [comment]
But your approach does not work.

From the moment files are populated, Lutris is not aware of their origin. It can be a file downloaded from the web,  a Steam folder, a user provided files, the installer doesn't know where a file comes from, it just knows how to associate a file ID with a local path. Just to make things clear, I do not want to make Lutris aware of file origins because it would make the whole thing extremely convoluted.

You dismissed subscripts too quickly but you have to see that this is the only approach that will work.

**Comment by mihawk90** [comment]
So you're also thinking of remote files, OK
What I was referring to was only local files (hence why I mentioned the file picker dialogue). But yeah if we're also talking about downloaded files then subscripts make more sense

**Comment by strycore** [comment]
this can be closed when the `file-picker` branch is merged/

**Comment by strycore** [comment]
`file-picker` has been merged. There are also some further fixes in #3089

**Comment by Singond** [comment]
Is the request resolved, then? I am also looking for a way to prompt the user for optional files, but I haven't been able to find anything in the documentation. Could you point me in the right direction, please?
