### ISSUE TITLE
Please add sentence in docs about 32-bit Arch explanation 

### ISSUE THREAD

**Issue by jleaders** [lutris/lutris#2038]
[In the installation guide](https://github.com/lutris/lutris/wiki/Installing-drivers), it requests I add i386 arch to my 64-bit machine. A quick sentence explaining why would be nice because as I understand it, 64-bit drivers can run 32-bit C++ compiled code just fine, so it seems unintuitive

**Comment by strycore** [comment]
Quite frankly, if it's that line: `sudo dpkg --add-architecture i386` you're talking about then I'd rather remove it. 

I have installed x64 Debian and Ubuntu a number of times over the years and not once have I ever needed to run this command. I have absolutely no idea where this comes from but I think it's just a relic of the past that people kept copying and pasting "just in case".

**Comment by strycore** [comment]
There, removed.

**Comment by jleaders** [comment]
That makes more sense, thanks.
