### ISSUE TITLE
Lutris unable to load library if letter cases in username wrong

### ISSUE THREAD

**Issue by HengiFettlich** [lutris/lutris#2042]
`2019-04-15 23:22:36,220 [api.get_library:90]:Unable to load library: Request to https://lutris.net/api/games/library/stahl170 failed: HTTP Error 404: Not Found `

This happens if the cases of the letters of the username logged into do not match up with the original username. You can still login to Lutris, but the Launcher can't sync the library, if the cases are not matching up.

**Comment by strycore** [comment]
Oh, I believe I haven't deployed the fix for that yet, I just wrote it a few days ago!

**Comment by strycore** [comment]
Deploying now, should work, please test
