### ISSUE TITLE
Game listed last if it starts with a lowercase

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2046]
```
cxf@PC:~/.lutris$ git bisect bad
284ee18c2f506aee524926c1b089112568c56e4b is the first bad commit
commit 284ee18c2f506aee524926c1b089112568c56e4b
Author: Mathieu Comandon <strycore@gmail.com>
Date:   Mon Mar 18 19:48:21 2019 -0700

    Apply sort_func to modelsort on creation (Closes: #1805)

:040000 040000 4f22545a5217a6111c1e20c6533cebe49aa535fb e6af73dfe5f4932c1e6b60e5e7a104fb394101c9 M	lutris
```

![Screenshot from 2019-04-15 22-15-36](https://user-images.githubusercontent.com/15083452/56184013-7d803780-5fcd-11e9-9850-e18304e143df.png)
![Screenshot from 2019-04-15 22-33-40](https://user-images.githubusercontent.com/15083452/56184408-c1277100-5fce-11e9-9de8-c131dbf6556d.png)

**Comment by isugimpy** [comment]
This looks like a really trivial fix, I'll take a crack at it tonight.
