### ISSUE TITLE
Make DXVK enabled by default

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2051]
It's superior to Wined3d in accuracy, support of applications and performance. There's simply no reason not to use it except if you have very outdated hardware that lacks support for Vulkan. But then again, on that hardware, Wined3d will have such low performance that the app will be completely unusable.

**Comment by soredake** [comment]
Maybe d9vk too? And install `d3dx9 d3dx10_43 d3dcompiler_43 d3dcompiler_47` by default
