### ISSUE TITLE
Request: Add Support for using Crossover (commerical WINE) 

### ISSUE THREAD

**Issue by aproposnix** [lutris/lutris#2059]
One of the requirements for using Lutris is to have a version of WINE running for Windows games. Could you possibly add support for Crossover bottles? Crossover is a commercial version of WINE created by the Proton developers (Codeweavers).

**Comment by strycore** [comment]
I'll grab a license next time it goes on sale.

**Comment by aproposnix** [comment]
> I'll grab a license next time it goes on sale.

I'm pretty sure if you approached the developers and tell them why you need the license (esp., to make Lutris compatible) they'll work out of deal with you.  They are really an awesome group of people.

**Comment by PopeRigby** [comment]
Why would you want the commercial version?

**Comment by aproposnix** [comment]
@PopeRigby 

Because Codeweavers, the makers of Crossover, contribute tremendously to WINE. Dare I say, WINE would not be where it is today without Codeweavers.

**Comment by PopeRigby** [comment]
So you're trying to support them by paying for it?

**Comment by aproposnix** [comment]
@PopeRigby I've been using it for years, so yeah, I support them and the development of WINE (which they contribute heavily to). 

Unfortunately Lutris does not support the Crossover WINE bottles. I'm sure it wouldn't take much to support it - if I could code it myself I would, but I can't so that is not an option.
