### ISSUE TITLE
I want to further translate this app to Spanish. Where to start?

### ISSUE THREAD

**Issue by JORGETECH** [lutris/lutris#2062]
I am interested in contributing to the Spanish translation of this app since in it's current form it's quite lacking (and here in Ubuntu the app is completely in English).

The problem is that the contributing documentation does not mention anything about translations so I wanted to know what are the first steps to localize this kind of app.

Thanks in advance.

**Comment by strycore** [comment]
Support for full internationalization is not complete, you can follow its progress on ticket #1489 

Closing this since I want to keep i18n tasks grouped there.
