### ISSUE TITLE
Exit with returncode 53 or Exit with returncode 0

### ISSUE THREAD

**Issue by warriormaster12** [lutris/lutris#2063]
Hi so I have tried to run some games using lutris runner managers wine like for example tkg-4.6-x86_64 and most of don't launch and either say Exit with returncode 53 or Exit with returncode 0. Shadow warrior 2 is an exception to this rule because that runs just fine with  tkg-faudio-protonified 4.5-x86_64 or tkg-4.6-x86_64. Is there a solution or a temporary fix that can make these versions of wine work again? 

Distro: Kde Neon Ubuntu 18.04 

Here is what I get when I run something:

```
(lutris:5219): Gtk-WARNING **: 15:28:21.545: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:5219): Gtk-WARNING **: 15:28:21.545: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:5219): Gtk-WARNING **: 15:28:21.545: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO     2019-04-19 15:28:21,563 [application.do_command_line:225]:Running Lutris 0.5.2
INFO     2019-04-19 15:28:21,564 [startup.check_driver:54]:Using NVIDIA drivers 418.56 for x86_64
INFO     2019-04-19 15:28:21,564 [startup.check_driver:58]:GPU: GeForce GTX 1060 6GB
INFO     2019-04-19 15:28:21,564 [startup.check_driver:75]:GPU: 10DE:1C03 1043:85AB using nvidia drivers
INFO     2019-04-19 15:28:21,614 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-04-19 15:28:21,615 [dxvk.get_dxvk_versions:24]:Updating DXVK versions

(lutris:5219): Gtk-WARNING **: 15:28:21.651: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:5219): Gtk-WARNING **: 15:28:21.651: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:5219): Gtk-WARNING **: 15:28:21.651: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
DEBUG    2019-04-19 15:28:21,744 [http.get:68]:GET https://lutris.net/api/runtime
INFO     2019-04-19 15:28:21,744 [lutriswindow.toggle_connection:561]:Connected to lutris.net as Warriormaster
DEBUG    2019-04-19 15:28:21,745 [store.get_missing_media:182]:Requesting missing icons from API for flight-simulator-x, guardians-call, blade, skeleton-dash
DEBUG    2019-04-19 15:28:21,746 [http.get:68]:GET https://lutris.net/api/games/library/Warriormaster
DEBUG    2019-04-19 15:28:21,746 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-04-19 15:28:22,040 [api.get_game_api_page:132]:Loaded 1 games from page 1
DEBUG    2019-04-19 15:28:24,388 [application.launch:339]:Launching Guardians Call (wine) (140187757560168)
DEBUG    2019-04-19 15:28:24,401 [game.play:269]:Prelaunching <lutris.runners.wine.wine object at 0x7f800006f748>
WARNING  2019-04-19 15:28:24,402 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,402 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,452 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,479 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,479 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
INFO     2019-04-19 15:28:24,479 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-04-19 15:28:24,479 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-04-19 15:28:24,479 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/system32/d3d9 with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2019-04-19 15:28:24,480 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2019-04-19 15:28:24,481 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/d3d10 with DXVK version
INFO     2019-04-19 15:28:24,481 [dxvk.enable_dxvk_dll:128]:Replacing /home/alexander/.wine/drive_c/windows/syswow64/d3d9 with DXVK version
DEBUG    2019-04-19 15:28:24,481 [display._get_vidmodes:15]:Retrieving video modes from XrandR
WARNING  2019-04-19 15:28:24,539 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,539 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING  2019-04-19 15:28:24,539 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
DEBUG    2019-04-19 15:28:24,539 [game.configure_game:305]:Launching Guardians Call: {'env': {'STEAM_RUNTIME': '/home/alexander/.local/share/lutris/runtime/steam', 'LD_LIBRARY_PATH': '/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/alexander/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/lib:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib:/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH', 'WINEDEBUG': '-all', 'WINEARCH': 'win64', 'WINE': '/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine', 'WINEPREFIX': '/home/alexander/.wine', 'WINEESYNC': '0', 'WINEDLLOVERRIDES': 'd3d10,d3d10_1,d3d10core,d3d11,dxgi=n'}, 'command': ['/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine', '/media/GamesAndPrograms/Games/GameOfTheMonth/GuardiansCall/GuardiansCall.exe']}
DEBUG    2019-04-19 15:28:24,539 [game.configure_game:306]:Game info: {
  "env": {
    "STEAM_RUNTIME": "/home/alexander/.local/share/lutris/runtime/steam",
    "LD_LIBRARY_PATH": "/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/alexander/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/lib:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib:/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH",
    "WINEDEBUG": "-all",
    "WINEARCH": "win64",
    "WINE": "/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine",
    "WINEPREFIX": "/home/alexander/.wine",
    "WINEESYNC": "0",
    "WINEDLLOVERRIDES": "d3d10,d3d10_1,d3d10core,d3d11,dxgi=n"
  },
  "command": [
    "/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine",
    "/media/GamesAndPrograms/Games/GameOfTheMonth/GuardiansCall/GuardiansCall.exe"
  ]
}
DEBUG    2019-04-19 15:28:24,540 [command.start:111]:Running /usr/bin/lutris-wrapper 0 0 /home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /media/GamesAndPrograms/Games/GameOfTheMonth/GuardiansCall/GuardiansCall.exe
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: STEAM_RUNTIME="/home/alexander/.local/share/lutris/runtime/steam"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: LD_LIBRARY_PATH="/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/alexander/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/lib:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib:/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINEDEBUG="-all"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINEARCH="win64"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINE="/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINEPREFIX="/home/alexander/.wine"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINEESYNC="0"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: WINEDLLOVERRIDES="d3d10,d3d10_1,d3d10core,d3d11,dxgi=n"
DEBUG    2019-04-19 15:28:24,540 [command.start:113]:ENV: PYTHONPATH="/usr/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2019-04-19 15:28:24,543 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7f8000099b38>> to 5241
Running /home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /media/GamesAndPrograms/Games/GameOfTheMonth/GuardiansCall/GuardiansCall.exe
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Waiting on children
All children gone
Exit with returncode 53
DEBUG    2019-04-19 15:28:26,258 [command.on_stop:158]:The process has terminated with code 13568
DEBUG    2019-04-19 15:28:26,259 [command.stop:241]:Management process looks dead already.
DEBUG    2019-04-19 15:28:26,259 [command.stop:249]:Detaching logger
DEBUG    2019-04-19 15:28:26,545 [game.beat:585]:Game thread stopped
WARNING  2019-04-19 15:28:26,545 [game.on_game_quit:613]:Game still running (state: running)
INFO     2019-04-19 15:28:26,546 [game.stop:596]:Stopping Guardians Call (wine)
DEBUG    2019-04-19 15:28:26,547 [command.stop:241]:Management process looks dead already.
DEBUG    2019-04-19 15:28:26,548 [command.stop:253]:logger already detached
DEBUG    2019-04-19 15:28:26,562 [game.on_game_quit:628]:Guardians Call stopped at pe, 19 huhti 2019 15:28:26
DEBUG    2019-04-19 15:28:26,562 [game.save:212]:Saving Guardians Call (wine)
DEBUG    2019-04-19 15:28:26,572 [lutriswindow.on_game_updated:697]:Updating game Guardians Call (wine)
```

**Comment by strycore** [comment]
someone please reformulate this bug report.

**Comment by moopoop** [comment]
I was getting error 53 and fixed it by installing lib32-libldap because I had only the 64 bit version.

`Running /home/mikem/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /mnt/LinuxHDD/Litrus/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -SkipBuildPatchPrereq -opengl
000b:fixme:winediag:start_process Wine Staging 4.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WLDAP32.dll": libgcrypt.so.11: cannot open shared object file: No such file or directory
0009:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe") failed (error c000007a).
0009:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe" failed, status c0000135
Waiting on children
All children gone
Exit with returncode 53`

**Comment by warriormaster12** [comment]
@moopoop could you tell me how to install it? I'm not sure if I have done it right.

**Comment by moopoop** [comment]
For you it should just be sudo apt install lib32-libldap through the terminal. 
Anything I've found pertaining to this error is wine complaining that WLDAP32.dll is missing and needs to be there.

**Comment by warriormaster12** [comment]
@moopoop It can't find the package with "sudo apt install lib32-libldap" command.

**Comment by moopoop** [comment]
> @moopoop It can't find the package with "sudo apt install lib32-libldap" command.

Sorry about that, thought it would be the same across distro's run `apt-get install libldap-2.4-2:i386` and see if that helps you

**Comment by warriormaster12** [comment]
@moopoop the package is already installed I tried to launch an ue 4  game tkg wine and still I get the same error.

**Comment by AccountOneOff** [comment]
Do what moopoop did and enable wine debugging. https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info#obtaining-log-output-for-games

**Comment by warriormaster12** [comment]
Do I have to do this?
`DEBUG    2019-04-26 08:49:53,924 [command.start:111]:Running /usr/bin/lutris-wrapper 0 0 /home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/alexander/Games/Skeleton Dash/SkeletonDash.exe
DEBUG    2019-04-26 08:49:53,924 [command.start:113]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2019-04-26 08:49:53,924 [command.start:113]:ENV: STEAM_RUNTIME="/home/alexander/.local/share/lutris/runtime/steam"
DEBUG    2019-04-26 08:49:53,924 [command.start:113]:ENV: LD_LIBRARY_PATH="/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/alexander/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/lib:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/i386/usr/lib:/home/alexander/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/lib:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/alexander/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINEDEBUG="-all"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINEARCH="win64"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINE="/home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINEPREFIX="/home/alexander/.wine"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINEESYNC="0"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: WINEDLLOVERRIDES="d3d10,d3d10_1,d3d10core,d3d11,dxgi=n"
DEBUG    2019-04-26 08:49:53,925 [command.start:113]:ENV: PYTHONPATH="/usr/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2019-04-26 08:49:53,931 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7fdb9b530588>> to 4543
Running /home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/alexander/Games/Skeleton Dash/SkeletonDash.exe
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Waiting on children
Waiting on children
2019-04-26 08:49:55,503: Unable to read stat for process 4552
2019-04-26 08:49:55,504: Unable to read stat for process 4552
All children gone
Exit with returncode 53
DEBUG    2019-04-26 08:49:55,935 [command.on_stop:158]:The process has terminated with code 13568
DEBUG    2019-04-26 08:49:55,936 [command.stop:241]:Management process looks dead already.
DEBUG    2019-04-26 08:49:55,936 [command.stop:249]:Detaching logger
DEBUG    2019-04-26 08:49:57,937 [game.beat:585]:Game thread stopped
WARNING  2019-04-26 08:49:57,937 [game.on_game_quit:613]:Game still running (state: running)
INFO     2019-04-26 08:49:57,937 [game.stop:596]:Stopping Skeleton Dash (wine)
DEBUG    2019-04-26 08:49:57,938 [command.stop:241]:Management process looks dead already.
DEBUG    2019-04-26 08:49:57,939 [command.stop:253]:logger already detached
DEBUG    2019-04-26 08:49:57,951 [game.on_game_quit:628]:Skeleton Dash stopped at pe, 26 huhti 2019 08:49:57
DEBUG    2019-04-26 08:49:57,951 [game.save:212]:Saving Skeleton Dash (wine)
DEBUG    2019-04-26 08:49:57,965 [lutriswindow.on_game_updated:697]:Updating game Skeleton Dash (wine)
`

**Comment by AccountOneOff** [comment]
>Do I have to do this?

You want help right?

You still didn't enable output debugging info.

![](https://cdn.discordapp.com/attachments/540589766811451392/558481590687236096/Peek_2019-03-22_05-43.gif)

**Comment by warriormaster12** [comment]
@AccountOneOff ok I have enabled wine debugging and I got this `Running /home/alexander/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/alexander/Games/Skeleton Dash/SkeletonDash.exe
000b:fixme:winediag:start_process Wine Staging 4.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
002c:err:module:load_builtin_dll failed to load .so lib for builtin L"WLDAP32.dll": libgcrypt.so.11: cannot open shared object file: No such file or directory
002c:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"Z:\\home\\alexander\\Games\\Skeleton Dash\\FPRogueLike\\Binaries\\Win64\\FPRogueLike-Win64-Shipping.exe") failed (error c000007a).
002c:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\alexander\\Games\\Skeleton Dash\\FPRogueLike\\Binaries\\Win64\\FPRogueLike-Win64-Shipping.exe" failed, status c0000135
002a:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffffffffffa, 0x5ffd00
Waiting on children
Waiting on children
2019-04-26 10:16:30,560: Unable to read stat for process 4677
2019-04-26 10:16:30,561: Unable to read stat for process 4677
All children gone
Exit with returncode 53`

**Comment by AccountOneOff** [comment]
`libgcrypt.so.11` is in the runtime. Do you have it disabled under System options? Check `~/.local/share/lutris/runtime/lib32` and `lib64`.

![Screenshot from 2019-04-26 17-20-21](https://user-images.githubusercontent.com/15083452/56842156-95667f80-6847-11e9-8efb-fa21784083de.png)

**Comment by warriormaster12** [comment]
Okay I enabled "Prefer system libraries" and tkg-4.6 started to work but for some reason tkg-faudio-protonified 4.5 and 4.4 are still broken and Proton 4.2 worked at first but when I disabled and enabled "Prefer system libraries" it also stopped working. Why?

**Comment by arnoldkol** [comment]
hey guys am trying to run civilization 6 but i get a grey screen on start up and nothing after the log i have attached here
[myK0DkP6.txt](https://github.com/lutris/lutris/files/3803293/myK0DkP6.txt)

**Comment by DjSapsan** [comment]
> hey guys am trying to run civilization 6 but i get a grey screen on start up and nothing after the log i have attached here
> [myK0DkP6.txt](https://github.com/lutris/lutris/files/3803293/myK0DkP6.txt)

I run perfectly fine with the proton in steam
