### ISSUE TITLE
Citra fails to open on Ubuntu 19.04

### ISSUE THREAD

**Issue by MrTheSoulz** [lutris/lutris#2065]
Fixed by manualy installing:
libqt5opengl5
libqt5multimedia5

maybe should be added to the dependencies?

**Comment by tannisroot** [comment]
19.10? Do you mean 19.04 or 18.10 maybe?

**Comment by MrTheSoulz** [comment]
sorry, 19.10

**Comment by tannisroot** [comment]
Are you from the future? 😂

**Comment by MrTheSoulz** [comment]
crap, 19.04 :laughing:

**Comment by tannisroot** [comment]
Can you make some logs regarding this with `lutris -d`?

**Comment by MrTheSoulz** [comment]
`DEBUG    2019-05-17 21:44:13,333 [application.launch:339]:Launching Pokémon X (citra) (139807852831224)
DEBUG    2019-05-17 21:44:13,339 [display._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2019-05-17 21:44:13,383 [game.configure_game:305]:Launching Pokémon X: {'command': ['/home/jaime/.local/share/lutris/runners/citra/citra-qt', '/home/jaime/3DS GAMES/0450 - Pokemon X (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds']}
DEBUG    2019-05-17 21:44:13,384 [game.configure_game:306]:Game info: {
  "command": [
    "/home/jaime/.local/share/lutris/runners/citra/citra-qt",
    "/home/jaime/3DS GAMES/0450 - Pokemon X (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds"
  ]
}
DEBUG    2019-05-17 21:44:13,385 [command.start:111]:Running /usr/bin/lutris-wrapper 0 0 /home/jaime/.local/share/lutris/runners/citra/citra-qt /home/jaime/3DS GAMES/0450 - Pokemon X (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds
DEBUG    2019-05-17 21:44:13,385 [command.start:113]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2019-05-17 21:44:13,385 [command.start:113]:ENV: DRI_PRIME="1"
DEBUG    2019-05-17 21:44:13,386 [command.start:113]:ENV: STEAM_RUNTIME="/home/jaime/.local/share/lutris/runtime/steam"
DEBUG    2019-05-17 21:44:13,386 [command.start:113]:ENV: LD_LIBRARY_PATH="/lib:/lib64:/lib32:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/jaime/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/jaime/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/jaime/.local/share/lutris/runtime/steam/i386/lib:/home/jaime/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/jaime/.local/share/lutris/runtime/steam/i386/usr/lib:/home/jaime/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/jaime/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/jaime/.local/share/lutris/runtime/steam/amd64/lib:/home/jaime/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/jaime/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2019-05-17 21:44:13,386 [command.start:113]:ENV: PYTHONPATH="/usr/bin:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2019-05-17 21:44:13,405 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7f278d6dac18>> to 12692
Running /home/jaime/.local/share/lutris/runners/citra/citra-qt /home/jaime/3DS GAMES/0450 - Pokemon X (Europe) (En,Ja,Fr,De,Es,It,Ko) Decrypted.3ds
/home/jaime/.local/share/lutris/runners/citra/citra-qt: error while loading shared libraries: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory
`

Lutris was installed using the ppa provided on a clean install.
Adding:
`libqt5opengl5
libqt5multimedia5`
to the deb dependencies should fix this as it does if they're installed manualy.
