### ISSUE TITLE
Starcraft Anthology install don't finish

### ISSUE THREAD

**Issue by castrogne** [lutris/lutris#2073]
Hi,

I have trouble with Starcraft Anthology. I install with 3.6 staging (cause 64 bits isn't supported by 2.0.1).

While "Creating wine prefix" I have sometimes an error, or the installer never finish the step. Battle.net start and i can download and play. But after, the window "Creating wine prefix" is still there and i only can kill her. The game isn't installed for Lutris and i must install it again to play. (But without downloading again, so i can access to play fast).

What can i do to have "Wine prefix" created? I can try to add manually the game, as it's well installed for wine, but i don't know how to do that.

Thanks

**Comment by tannisroot** [comment]
>(cause 64 bits isn't supported by 2.0.1)
What do you mean by that?

**Comment by castrogne** [comment]
Hi,

When I select 2.0.1 I get the message "Wine is not available for the x86_64 architecture". I don't have this message on 3.6 staging. 

In 3.6, the install is ok, i can play but the install never finish and is stuck with "Creating wine prefix". 

Maybe if i create manualy this prefix, that could do the job?

**Comment by tannisroot** [comment]
These are very ancient Wine versions, you should not use them. Instead, you should use the available scripts and if they don't work, try getting help on our Discord.
