### ISSUE TITLE
ValueError: Invalid sort key for col 9

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2078]
Got this on the terminal tonight:

```
Traceback (most recent call last):
  File "/home/batapete/src/lutris/lutris/gui/views/store.py", line 237, in on_sort_column_changed
    raise ValueError("Invalid sort key for col %s" % col)
ValueError: Invalid sort key for col 9
```

**Comment by strycore** [comment]
Lacks repro steps

**Comment by strycore** [comment]
Since it wasn't clear how to reproduce this, I've changed the sort column to a non existent one in the lutris config file and defaulted to sorting by name if the sort column isn't found.
