### ISSUE TITLE
Returncode 53

### ISSUE THREAD

**Issue by pessoaneto** [lutris/lutris#2079]
Greetings,
I've tried to run Lutris on Manjaro KDE but all games i tried to run end up on the same error.

```
Running /home/pessoaneto/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/pessoaneto/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -SkipBuildPatchPrereq -opengl
Waiting on children
All children gone
Exit with returncode 53
```
What can i do?

**Comment by warriormaster12** [comment]
I have the same exact issue and for now at least you need to use winehq wine if you want to play games or launch a launcher. If I understood correctly, right now lutris runner managers wine is busted and in most cases gives you this exitcode error.

**Comment by warriormaster12** [comment]
@AccountOneOff I know it works on my system as well but I have tried to run some games like fsx, unreal 4 games and spider-man shattered dimensions using tkg-4.6 or  tkg-protonified-faudio-4.5 and it gave me exitcode 53.

**Comment by tannisroot** [comment]
This seems very similar to https://github.com/lutris/lutris/issues/2063 so I will close it for now.
