### ISSUE TITLE
Sync removes Steam games installed in secondary game folder

### ISSUE THREAD

**Issue by huyderman** [lutris/lutris#208]
I've got my Steam games installed in two folders, one is the default steam folder (`/home/huyderman/.local/share/Steam`), and the other is on an SSD disk (`/opt/games`). However, every time Lutris synces my installed Steam games, it doesn't detect any of the games on the SSD, and actually marks them as uninstalled.

```
DEBUG    2015-10-21 18:50:33,519 [installer]:game:
  appid: '203770'

DEBUG    2015-10-21 18:50:41,328 [sync]:Syncing game library
DEBUG    2015-10-21 18:50:41,328 [sync]:593 games in local library
DEBUG    2015-10-21 18:50:41,328 [api]:Fetching game library
DEBUG    2015-10-21 18:50:42,252 [sync]:593 games in remote library (inc. unpublished)
DEBUG    2015-10-21 18:50:42,354 [sync]:0 games updated
DEBUG    2015-10-21 18:50:42,354 [sync]:Syncing local steam games
DEBUG    2015-10-21 18:50:42,409 [sync]:Setting Crusader Kings II as uninstalled
```

I'm using Lutris 0.3.6.3 on Arch Linux.

**Comment by strycore** [comment]
This is fixed in the current master branch and will be released in 0.3.7
