### ISSUE TITLE
Do not remove install folder after cancelling installer if it existed before the installation

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2080]
I recently had a very unpleasant experience of running an installer over existing prefix to update stuff, cancelling by mistake and losing all my precious save files and 34GB of game data :( Would be nice to avoid such situations.

**Comment by DevilishSpirits** [comment]
Hello,

I made a patch which allow explicit user consent [in this branch](https://github.com/DevilishSpirits/lutris/tree/bug-2080), it's a checkbox which reuse `interpreter.game_dir_created` in the cancel box.

I also slightly edited `QuestionDialog()` which now accept a list of widgets to pack in the dialog (maybe useful for more dialogs)

Are you interested ?

**Comment by tannisroot** [comment]
@DevilishSpirits sure, just submit it as a PR and we will see if strider likes the implementation.

**Comment by strycore** [comment]
It's not because I merged it that I like it.
