### ISSUE TITLE
Can't unselect a game in right panel by clicking on empty space in the library if it's no longer installed

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2082]
Clicking [X] works however (mouse cursor for some reason didn't get captured, but you get the idea):
![Peek 2019-04-24 14-22](https://user-images.githubusercontent.com/10602045/56655864-99a26980-669c-11e9-9c88-1073cb0d6567.gif)

**Comment by vahtos** [comment]
I sent a PR. This should be resolved by simply clearing the Game Panel when a game is uninstalled. As it currently is, the Game Panel does not get updated until it is told to switch games (clicking on another game) or the close button is pressed.

I think that resetting the Game Panel after an uninstall is a reasonable change, what do you think?
