### ISSUE TITLE
Lutris doesn't completely kill Wine processes in the prefix after cancellation of the installation

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2084]
It's not uncommon for me to get "creating prefix" messages just after cancellation of the game installation and see active processes that were launched during installation process in System Monitor (which are what triggering prefix re-creation after Lutris deletes it).
And same happens if the installation is not cancelled (which might caused issues with WINEESYNC option).
Perhaps Lutris should use `wineserver -k9` for this.

**Comment by tannisroot** [comment]
The issue was not resolved by the PR (it doesn't work), reopening.

**Comment by strycore** [comment]
Can someone please QA this?

**Comment by tannisroot** [comment]
@strycore it doesn't work properly, I checked it with "Origin Test" installer from here https://lutris.net/games/test/.
The normal installer calls winekill at the end but this one I made does not.
I installed latest lutris-git and after it completes the installation, origin opens its login window which then becomes unresponsive zombie-window, when it doesn't do that with a regular installer (https://lutris.net/games/origin/).
This usually happens when you use `wineserver -k9` and not `wineserver -k`, as the latter shuts down processes gracefully but the former does not.
Also, the fact that Origin manages to open that login window before it's called shows that it's way slower than calling `winekill` in the installer itself.

**Comment by tannisroot** [comment]
Doesn't work, prints this in the terminal ```Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 500, in cancel_installation
    self.interpreter.revert()
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 733, in revert
    if self.runner_name.startswith("wine"):
AttributeError: 'ScriptInterpreter' object has no attribute 'runner_name'
```

**Comment by tannisroot** [comment]
Also, I suggest using `wineserver -k` instead, not `k9` like before , as the latter creates zombie windows.

**Comment by strycore** [comment]
Silly typo, please test again.

**Comment by tannisroot** [comment]
Yep works now.
