### ISSUE TITLE
Lutris doesn't remove prefix when uninstalling Wine Steam game

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2087]

**Comment by tannisroot** [comment]
Can you check whether it's a dupe of https://github.com/lutris/lutris/issues/2084 ?

**Comment by strycore** [comment]
No, this is unrelated. When uninstalling a game through steam, it doesn't delete extra folders that could have been created.

**Comment by strycore** [comment]
Closing this as we're deprecating the WineSteam runner at some point in the near future.
