### ISSUE TITLE
Add pcgamingwiki to game panel

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2088]

**Comment by tannisroot** [comment]
Which game panel?

**Comment by AccountOneOff** [comment]
The one named game panel.

https://github.com/lutris/lutris/blob/master/lutris/gui/views/game_panel.py

**Comment by tannisroot** [comment]
So the right panel, ok.
How do you want it to be displayed exactly? Only when no game is selected, or when there is one selected too? And in that case, should it open just the main page of that wiki or open the page of the currently selected game? 
Also, where do you think it would be best to place the button that leads to that website?

**Comment by strycore** [comment]
Nope.

**Comment by PopeRigby** [comment]
Why not?

**Comment by strycore** [comment]
Because I don't have the bandwidth to do it and it's out of scope for the project.

**Comment by PopeRigby** [comment]
Oh ok. Fair enough.
