### ISSUE TITLE
Planetbase - Steam version crash

### ISSUE THREAD

**Issue by Kattnienika** [lutris/lutris#2090]
Hello,
I have a game Planetbase from Steam. When I try launch, game crash.
[error.log](https://github.com/lutris/lutris/files/3116230/error.log)
[output_log.txt](https://github.com/lutris/lutris/files/3116231/output_log.txt)

**Comment by tannisroot** [comment]
Hi! Unfortunately this is a bugtracker of the Lutris client. Try getting help on our Discord server.
