### ISSUE TITLE
Overwatch - Double-clicking doesn't send second click

### ISSUE THREAD

**Issue by Tony556** [lutris/lutris#2091]
Specs/OS:
Pop_OS 19.04 with kubuntu-desktop (also tested in GNOME)

Intel i7 4790K
Nvidia GTX 980

144hz monitor with a 60hz secondary

Logitech G502 mouse

---

I've noticed that when playing Overwatch, whenever I double click (or just click quickly, as can happen in a fast-paced shooter), the second click will either 

A. Get sent then immediately "unclicked"
B. Not sent at all (But I assume it's just A happening very fast)

I also tested this in Titanfall 2, but no such issue occurred! 

The info on the side is from `xinput test-xi2 --root`

Titanfall 2:
https://streamable.com/a5pbt

Overwatch:
https://streamable.com/7hrx9

**Comment by isugimpy** [comment]
I can validate that this occurs on Overwatch, but it doesn't really appear to be a Lutris issue in any way.  Will see if I can duplicate on a Windows machine I have access to, but I think at best this could be a Wine issue, and at worst it's a game bug that we're hitting.

**Comment by tannisroot** [comment]
I have this issue too and you are correct, it's not a Lutris bug.
I might open a bug report on Winehq about this.
