### ISSUE TITLE
Add Dosbox-X as a runner

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2093]
Suggested by legluondunet on the forums.

>Hello,
could you add dosbox-x from Jon Campbell?
This Dosbox version have:
>
>  -  better sound
>  - better contrast
>  - support / and \ in relative path (no need to change dosbox config file for Linux)
>  - support 3DFX
>  - Releases are available here:
>    https://github.com/joncampbell123/dosbox-x

https://forums.lutris.net/t/runner-dosbox-x/5709?u=cxf

**Comment by strycore** [comment]
We already have that plus wrong repo
