### ISSUE TITLE
Old wine 3.16 staging esync pba build not showing in wine installer menu?

### ISSUE THREAD

**Issue by yusdacra** [lutris/lutris#2096]
So, i just installed lutris on my Xubuntu install. It looks like there is no wine 3.16 staging esync pba build anymore?

![screenshot](https://user-images.githubusercontent.com/19897088/56986614-d9cd8480-6b93-11e9-9f7d-2b14b04bb05d.png)

**Comment by strycore** [comment]
Yeah, i removed a bunch wine builds to declutter. I'm going to close this issue since no reason for keeping this version was given.

**Comment by AccountOneOff** [comment]
It's the last working PBA build. 3.17 and up don't work. @TK-Glitch should know more about that. I have the build on my drive if you don't feel like rebuilding. https://drive.google.com/file/d/1Vah19nvXO7H_2RY9dksJS_Cn2AJek5aZ/view

**Comment by Tk-Glitch** [comment]
I have made the legacy branch for that purpose though : https://github.com/lutris/wine/tree/tkg-legacy
3.18 based, with all the usual proton patches and fixed/working PBA. But yeah it was never built afaik.

That being said, with the swift evolution of D9VK and the (enhanced) PBA mainlining being worked on, it *will* get deprecated. The only unknown is the delay before that happens.
