### ISSUE TITLE
Difficulty to install Dosbox windows prepackaged games with Lutris

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2097]
Hello,

I tried to write a Lutris script for a Gog Dosbox game for several days but I'm blocked with this difficulty:
Gog wrote Dosbox config file for Windows and on Windows, path in dosbox config file written with antislash --> \
For example, to mount an iso on D drive, you have to write to the Dosbox config file:
imgmount D "..\game.iso" -t iso
But this config file will not be correctly interpreted by Dosbox Linux version, on Linux Dosbox understand only path with slash --> /
For example to mount an iso on D drive, on Dosbox for Linux, you have to write to the Dosbox config file:
imgmount D "../game.iso" -t iso

Now if you want to write a Lutris script for a Dos games with Dosbox runner, you have to find a way to modify the existing Dosbox config file and replace antislash from relative path with slash.

Or to use Dosbox-x which interpreting both slash and antislash on all platform.

I joined you the non modified dosbox config file from Gog version of "Alone in the Dark" I blocked on.
I tried to use write_file or write_config with no success.
Please help me to resolve this issue, we need to resolve it if we want to distribute more Lutris dos games scripts.

[dosboxAlone1.zip](https://github.com/lutris/lutris/files/3133226/dosboxAlone1.zip)

**Comment by legluondunet** [comment]
you can refer to this discussions for more details about this issue:
https://forums.lutris.net/t/script-how-to-modify-or-write-a-dosbox-config-file/5692
https://forums.lutris.net/t/runner-dosbox-x/5709/3

**Comment by telanus** [comment]
@legluondunet I posted in one of those threads, but the basics is you need to manually linuxfy Windows-based dosbox config files, to work with linux dosbox. Since the File System isn't compatible, Dosbox-x (even with it accepting / or \) will not work with windows Dosbox Config files, as C:\games\dosbox doesn't exist with a linux File System.

My dosbox used to live on e:\games\dos (when I used windows "ice ages" ago), but now lives in /games/dos so linux dosbox won't know what to do with e:\games\dos

**Comment by legluondunet** [comment]
@telanus, for the moment I only seen relative path in Gog dosbox config file, so if Lutris would use Dosbox, we will have nothing to rewrite.
I asked Dosbox dev to add this feature (\=/) too, but this could take times.

**Comment by legluondunet** [comment]
More than resolve this issue, if Lutris would officially add Dosbox-x to the available runners, we could write script for Dos 3DFX games.

**Comment by strycore** [comment]
There is no proper documentation on how to build or use dosbox x, the whole thing is a huge hack

**Comment by strycore** [comment]
I never managed to use dosbox x to run 3dfx games, it's most likely a hoax

**Comment by telanus** [comment]
AFAIK the 3dfx side only work on Windows. Can't find the quote atm where it was stated

**Comment by legluondunet** [comment]
> There is no proper documentation on how to build

```
git clone https://github.com/joncampbell123/dosbox-x.git
./build-debug
```

**Comment by strycore** [comment]
Thanks for the build instructions, it's good to have a github repo. last time I check the project was referenced on Vogons only or something like that.

Our current Dosbox build is the ECE one (https://yesterplay.net/dosbox-ece-en/). It's supposed to have some of the same enhancements as Dosbox-x but I've never had any luck with any of that.

**Comment by legluondunet** [comment]
I just tested Screamer Rally (3DFX DOS game) with both Dosbox-x and Dosbox-ce, it's unplayable on my computer.
I will forget this idea for the moment.
And for the / and \ compatibility, I found a workaround.
Thank you all, have a nice day.

**Comment by strycore** [comment]
Let me know if you find a way to reliably run dos games with 3dfx, that would be really helpful!
