### ISSUE TITLE
how to install custom runner on lutris

### ISSUE THREAD

**Issue by ludo77** [lutris/lutris#2098]
402/5000
Hello,
I would like to know how to install a custom runner in lutris (linux version) as mgba.
I do not want to use a cross platform emulator like libretro (retroarch).
I looked at where the emulators were stored (~ / .local / share / lutris / runners /): I created a mgba file to put mgba-qt
But I do not see the custom runner (mgba) in the list.
Thank you for your help.

**Comment by RobLoach** [comment]
mgba is in RetroArch...
https://github.com/lutris/lutris/blob/master/lutris/runners/libretro.py#L46

Use the libretro runner.

**Comment by telanus** [comment]
@ludo77 For a custom Runner you need to create a python script that Lutris can use to use mgba standalone as a runner, and as @RobLoach said, mgba is already part of Libretro

**Comment by ludo77** [comment]
in the directory runners, I create a file mgba.py:
`from lutris.runners.runner import Runner
from lutris.util import system


class mgba(Runner):
    human_name = "mgba"
    platforms = ["Nintendo gba"]
    description = "Nintendo gba emulator"
    runner_executable = "mgba/mgba-qt"
    game_options = [
        {
            "option": "main_file",
            "type": "file",
            "label": "ROM file",
            "help": "The game data, commonly called a ROM image.",
        }
    ]

    def play(self):
        """Run the game."""
        arguments = [self.get_executable()]
        rom = self.game_config.get("main_file") or ""
        if not system.path_exists(rom):
            return {"error": "FILE_NOT_FOUND", "file": rom}
        arguments.append(rom)
        return {"command": arguments}`

and after in file _init_.py:
`...
# Nintendo
    "snes9x",
    "mupen64plus",
    "dolphin",
    "desmume",
    "citra",
    "melonds",
    "mgba",
...`

but to install, I can not use the command:
sudo python3 setup.py install

**Comment by telanus** [comment]
@ludo77 try this: https://paste.ubuntu.com/p/q7N5yMX2hv/

and then go to the base of your lutris git clone and do this from the terminal: ./bin/lutris -d

Should start lutris, and paste any errors to paste.ubuntu.com and link here. I didn't  really tested the script as I don't have the time, just checked ti for errors.

**Comment by ludo77** [comment]
I managed by putting the files: mgba.py and _init_.py
in the folder:  /usr/lib/python3/dist-packages/lutris/runners
