### ISSUE TITLE
Lutris config not loaded yet when looking at wine versions

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#2100]
Here's a new Fedora report (https://bugzilla.redhat.com/show_bug.cgi?id=1704997):
The report was in Spanish, but here's what google translate plopped out: "was analyzing the wine versions within the manager by lutris when this message appeared"

Version-Release number of selected component:
lutris-0.5.2.1-1.fc30

Additional info:
reporter:       libreport-2.10.0
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: _build_system_tab
exception_type: RuntimeError
executable:     /usr/bin/lutris
interpreter:    python3-3.7.3-1.fc30.x86_64
kernel:         5.0.9-301.fc30.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
common.py:328:_build_system_tab:RuntimeError: Lutris config not loaded yet

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 400, in on_runner_changed
    self._switch_runner(widget)
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 414, in _switch_runner
    self._rebuild_tabs()
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 422, in _rebuild_tabs
    self._build_system_tab("game")
  File "/usr/lib/python3.7/site-packages/lutris/gui/config/common.py", line 328, in _build_system_tab
    raise RuntimeError("Lutris config not loaded yet")
RuntimeError: Lutris config not loaded yet

Local variables in innermost frame:
self: <add_game.AddGameDialog object at 0x7fad20ed7af8 (lutris+gui+config+add_game+AddGameDialog at 0x5650defc9100)>
_config_level: 'game'

**Comment by strycore** [comment]
Can't figure out how to reproduce this one, I just know it has something to do with changing the runner in the config dialog.

**Comment by strycore** [comment]
That's been fixed I believe. Reopen if that's not the case.

**Comment by danieljohnson2** [comment]
@Victornovikov, that information doesn't really help. And it's quite likely that you have a new issue anyway; this one is quite old.

You should run Lutris in debug mode, via "lutris -d" on the command line, and then do whatever you need to to experience your issue. Then, open a new issue and include the output that you get from "lutris -d".
