### ISSUE TITLE
mega.nz links in installers shown wrong

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2105]
"#" and further is not the part of the url
![Screenshot_20190504_092321](https://user-images.githubusercontent.com/5204968/57174941-a407f480-6e4e-11e9-8b13-bb17a7e7b006.png)
Installer to test https://lutris.net/games/mugen/

**Comment by tannisroot** [comment]
I don't think this can be fixed in the Lutris client itself. Try opening a gtk bug about this.

**Comment by tannisroot** [comment]
As a workaround, try shortening such links with something like bitly: 
![image](https://user-images.githubusercontent.com/10602045/57928079-6e382680-78b8-11e9-8276-a158b12cef2f.png)
