### ISSUE TITLE
Update Xonotic

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#211]
https://lutris.net/games/xonotic/

0.8.1 is out.
http://xonotic.org/download/

**Comment by Xodetaetl** [comment]
Updated.

PS: The prefered way to report installer issues is now from the game's page on lutris.net, there is a submenu to each installer's install button where you'll see Report issue. (We should probably find a more visible place for it.)

**Comment by RobLoach** [comment]
Ah, very cool :+1: ... Didn't see that before.
