### ISSUE TITLE
Games fails to start when the unit is unmounted

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#2111]
**Right now:**

* Lutris show a generic non informative error.

**How it should be:**

* Offer the user the option to mount the unit, then open the game.

**Comment by tannisroot** [comment]
Uhhh, what do you mean by `unit`???

**Comment by Zeioth** [comment]
Uhhh, this this the error I get when I try to run a game installed in a hard drive which is not mounted

![screen](https://user-images.githubusercontent.com/3357792/57870467-708e7800-7807-11e9-807c-7f0d78b7affb.png)

Would be nice to offer the user the option to mount the disk for him. For the sake of user experience.

**Comment by PythonicChemist** [comment]
I don't think this should be in the scope of Lutris. Have you tried using:

> ,x-systemd.automount

in your /etc/fstab to mount your disks lazily?

**Comment by tannisroot** [comment]
Indeed this is an issue that should be handled upstream and not by Lutris.
However Lutris can make the warning a bit more clear. I will open a new issue about this.

**Comment by Zeioth** [comment]
@PythonicChemist the issue is that the default config of udisks (which is used by most distros) will produce this scenario. But I agree with you guys, it doesn't need to be Lutris responsibility.
