### ISSUE TITLE
Dauntless install error

### ISSUE THREAD

**Issue by MadMagnetic** [lutris/lutris#2112]
Hi! Got this error while trying to install Duantless (OB 0.7.1 (esync-3.15) version) via Lutris 0.5.2.1. My system -
`System:
  Host: manjaro Kernel: 5.1.0-1-MANJARO x86_64 bits: 64 
  Desktop: KDE Plasma 5.15.4 Distro: Manjaro Linux 
Machine:
  Type: Laptop System: ASUSTeK product: TUF Gaming FX705DY_FX705DY v: 1.0 
  serial: <root required> 
  Mobo: ASUSTeK model: FX705DY v: 1.0 serial: <root required> 
  UEFI: American Megatrends v: FX705DY.306 date: 02/13/2019 
Battery:
  ID-1: BAT0 charge: 59.3 Wh condition: 62.1/64.0 Wh (97%) 
CPU:
  Topology: Quad Core model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 
  bits: 64 type: MT MCP L2 cache: 2048 KiB 
  Speed: 2125 MHz min/max: 1400/2100 MHz Core speeds (MHz): 1: 2125 2: 1957 
  3: 1420 4: 1610 5: 1827 6: 1742 7: 2523 8: 2026 
Graphics:
  Device-1: AMD Baffin [Radeon RX 460/560D / Pro 
  450/455/460/555/555X/560/560X] 
  driver: amdgpu v: kernel 
  Device-2: AMD Picasso driver: amdgpu v: kernel 
  Display: x11 server: X.org 1.20.4 driver: amdgpu FAILED: ati 
  unloaded: modesetting resolution: <xdpyinfo missing> 
  OpenGL: renderer: AMD RAVEN (DRM 3.30.0 5.1.0-1-MANJARO LLVM 8.0.0) 
  v: 4.5 Mesa 19.0.3 
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio driver: snd_hda_intel 
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.1.0-1-MANJARO 
Network:
  Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter 
  driver: rtl8821ce 
  IF: wlp2s0 state: down mac: 76:a6:65:79:2b:d1 
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  driver: r8169 
  IF: enp3s0 state: down mac: 04:92:26:1b:7b:46 
  Device-3: Gemtek WLTUBA-107 [Yota 4G LTE] type: USB driver: cdc_ether 
  IF: enp4s0f4u2 state: unknown speed: N/A duplex: N/A 
  mac: 1c:49:7b:01:22:71 
Drives:
  Local Storage: total: 931.51 GiB used: 47.38 GiB (5.1%) 
  ID-1: /dev/sda vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB 
Partition:
  ID-1: / size: 915.40 GiB used: 47.38 GiB (5.2%) fs: ext4 dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 42.2 C mobo: N/A 
  Fan Speeds (RPM): N/A 
  GPU: device: amdgpu temp: 42 C device: amdgpu temp: 42 C 
Info:
  Processes: 275 Uptime: 1h 13m Memory: 7.54 GiB used: 3.59 GiB (47.6%) 
  Shell: fish inxi: 3.0.33 
`
![изображение](https://user-images.githubusercontent.com/34352955/57201232-da548980-6f9e-11e9-9033-b4ac9e6bc1c5.png)

**Comment by AccountOneOff** [comment]
Wine version was readded.
