### ISSUE TITLE
Suggestion: Automatically Sandbox games

### ISSUE THREAD

**Issue by retiform** [lutris/lutris#2113]
Games should be sandboxed to their install folder by defualt, unless specified otherwise in the installer script.

This would prevent games from slurping up a user's files for spyware purposes or accidentally deleting files they were not supposed to. Would also be good for games whose upstream had been hacked, replacing the games with malware of some sort.

**Comment by RobLoach** [comment]
For spyware purposes? What? What games are you installing?

**Comment by RobLoach** [comment]
Possibly use the Flatpak? https://github.com/RobLoach/net.lutris.Lutris

**Comment by tannisroot** [comment]
Unfortunately unlinking Z (which is what I assume you mean by sandboxing, as Lutris already sandboxes folders like `My Documents`) drive will break a lot of things.
Just try to be cautious and unlink Z drive for apps that you don't trust,
