### ISSUE TITLE
sand box option does not work

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2114]
Hello,

in my global wine runner tab, sand box option is enable, it is enabled for all my games but it doesn't work: all the games leave their config, saves and other files on my home personal folders.

Thank you for your help.

**Comment by tannisroot** [comment]
Would you mind sharing what OS you use?

**Comment by legluondunet** [comment]
Ubuntu 19.04

**Comment by legluondunet** [comment]
When Lutris create a new WIne prefix, it makes  links inside wine bottle to my personal folders (Documents, Desktop etc...). I have the Lutris sandbox option turn on:

![Capture-20190518164103-763x584](https://user-images.githubusercontent.com/325405/57971257-ed4a5f00-798b-11e9-990c-d0c53cbd124b.jpg)

**Comment by telans** [comment]
You need to specify the sandbox directory i.e /home/user/Documents/sandbox/

**Comment by Faalagorn** [comment]
Really? I always had impression this will just use the wineprefix to store all these files and skip the links, but I have to admit I never actually checked it.

**Comment by legluondunet** [comment]
If the option is checked without folder specified, then like @Faalagorn  said it should " this will just use the wineprefix to store all these files and skip the links"?

**Comment by telans** [comment]
That's not sandboxing though is it? That's just default wine functionality?

**Comment by legluondunet** [comment]
seems to be resolved in Lutris 5.2.3
 * Fixed wine sandboxing on non-english systems.
