### ISSUE TITLE
Change Ubuntu 18.10 refrences to 19.04

### ISSUE THREAD

**Issue by Devorlon** [lutris/lutris#2115]
Ubuntu 18.10 will supported until July 2019, and the download link on [ubuntu.com](https://www.ubuntu.com/download/desktop) is replaced with 19.04.

I think the documentation should be changed accordingly. The pages affected are:
- Installing Drivers
- Wine
- Wine Dependencies

I would change the pages but I can't figure out how / don't have permission.

Thanks.

**Comment by AccountOneOff** [comment]
I added 19.04 to the Wine pages. Won't remove 18.10 until it is EOL as people might still be using it.
