### ISSUE TITLE
Wizard for manual game installation

### ISSUE THREAD

**Issue by hollunder** [lutris/lutris#2118]
Similar to PoL -> Install a Program -> Install a non-listed program

The background is that whether it's PoL or Lutris, the scripts are going to be out of date. So some people, me included, prefer to do manual installs, starting with plain WINE, rather than rely on scripts.
That is currently possible, but you have to know how (this is how I currently do it: https://tube.tchncs.de/videos/watch/0bfc1ce7-f6c8-4623-8195-fc33dd9e8da7)
As you can see, it's a bit awkward, you have to know how to do it and hunting down the executable(s) in the end can be a bit bothersome. I wish there was a wizard-type thing similar to how PoL provides it.

**Comment by carlinux** [comment]
THAT would be great. I install manually a lot of stuff because the scripts aren't updated and/or fail and do it manually it's cumbersome to say the least.

**Comment by tannisroot** [comment]
That's a nice idea but unfortunately this is not suitable for Lutris as it goes against its idea of having a big database of easy to write scripts that just make games work out of the box.
Hopefully a solution https://github.com/lutris/lutris/issues/1754 will improve the situation a bit for games that don't have installers at the moment.

**Comment by hollunder** [comment]
Riddle me this: How do you create a script to automatically install a game when you don't know what a game needs in order to run successfully?
A button on the website is not going to help you there.

How about a mode that assists in the creation of a working prefix and in the creation of a script that reflects that prefix? It could just log the actions taken for starters. Ideally it would help to find a minimal working configuration.

**Comment by tannisroot** [comment]
@hollunder a beginner's guide to writing scripts is in the plans.
