### ISSUE TITLE
Use inotify to watch steam library changes

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#212]
The current implementation of steam local sync library will read through all appmanifest files every 5 seconds for both steam and winesteam. While this shouldn't have any noticeable performance impact on modern hardware, there's still something that feels very wrong about doing this. 
Filesystem monitoring is usually done with the help of inotify on Linux (used by dropbox, rhythmbox or banshee), this is what we should be using too. 

There's some code example for inotify I've written years ago here: https://github.com/strycore/scripts/blob/master/lesswatch
This code sample uses pyinotify which some people seem to dislike but there are alternatives available such as inotifyx (https://launchpad.net/inotifyx) that seem to perform better. We aren't going to watch thousands of files anyway so both options should be perfectly viable.

**Comment by Xodetaetl** [comment]
:+1:

**Comment by Xodetaetl** [comment]
It can be pushed back to the next update though, I've optimized the sync code enough so it shouldn't be too heavy even on older systems. It doesn't make a visible dent on my CPU monitor.

**Comment by strycore** [comment]
Marking this for 0.4.x since it's not critical. I've increased the time interval to 30 seconds, is it ok or is there a specific reason that the interval was so small to begin with?

**Comment by Xodetaetl** [comment]
I felt 5s was the maximum for a reasonable reactivity. If you install or remove a game directly from Steam, you want to see it quickly reflected in Lutris. 30s is way too much.
Also, as it is now, when you uninstall a Steam game from Lutris,  it will be marked as uninstalled before the uninstallation effectively happens in Steam. If the timer sync happens inbetween, the game will be shown as installed again, then you'd have to wait  30s for it finally be switched to uninstalled state. Which is too long, it looks like a bug. Well, actually, it is a bug (first marking as uninstalled before it's actually uninstalled) and I should see if it can be fixed.

But the feature isn't critical, we can keep it at 30s until inotify is implemented.

**Comment by strycore** [comment]
done!
