### ISSUE TITLE
"prelaunch command" system option for install script

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2123]
Hello, I need to do some operations before each time a game launches. It's an old game and it always changes his config with incorrect values. I would like to launch a bash script before each time game launch to clean the config, it is necessary for the game to run correctly. 
I saw you made available some system command for scripting, like this one:

```
system:
prefix_command: script to execute
```
but I didn't find an equivalent for "prelaunch command" system option?

**Comment by legluondunet** [comment]
Same problem for dumbxinput plugin, I didn't find a system option to enable it during script install.

**Comment by tannisroot** [comment]
Such functionality is already a thing. See "Pre-launch command" here: 
![Screenshot from 2019-05-16 11-41-45](https://user-images.githubusercontent.com/10602045/57839576-a9aaf600-77cf-11e9-9fd6-32bbb72140e1.png)
To specify it in a game script, use this:
```
system:
  prelaunch_command: 
```
