### ISSUE TITLE
runner options should affect the install phase

### ISSUE THREAD

**Issue by Francesco149** [lutris/lutris#2126]
because of my storage setup (16TB zfs array over nfs) i need to have a LD_PRELOAD hack to prevent the free space checks from overflowing on 32-bit wine. usually I can just add LD_PRELOAD to the environment vars in the runner's system settings or as a command prefix and it'll work, but when installing, for example, a game that uses the steam wine runner, steam will refuse to update because the LD_PRELOAD hack is not applied even though it's set in the runner options. my current solution is to run lutris itself with LD_PRELOAD, but it would be nice if it just worked with the runner options. this also applies to any other kind of tweak other people need

**Comment by tannisroot** [comment]
Might be a good idea to fix https://github.com/lutris/lutris/issues/1814 along with this one, as they seem very related.
