### ISSUE TITLE
Disabling DXVK-d9vk-0.10 makes d3d9 games unplayable

### ISSUE THREAD

**Issue by vlakam** [lutris/lutris#2129]
Steps to reproduce:
1. Enable dxvk with d9vk-0.10 setting
2. Play game
3. Disable dxvk

Expected: next launch goes with default wined3d renderer or gallium-nine if present
Actual: Game cannot launch reports that d3d9.dll is missing

**Comment by Riesi** [comment]
Can you try master instead of the 0.5.2.1 release? This should be fixed by #2023.

**Comment by tannisroot** [comment]
Indeed it should be fixed in the next release.
