### ISSUE TITLE
add game cant work 

### ISSUE THREAD

**Issue by compaq2** [lutris/lutris#2136]
I have just installed lutris and add game manualy , then it crash and the add game button dont work anymore
this is debug for lutris :

_get_can_default (widget)' failed
DEBUG    2019-05-16 12:51:32,741 [display._get_vidmodes:15]:Retrieving video modes from XrandR
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 754, in on_add_game_button_clicked
    AddGameDialog(self, runner=self.selected_runner)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/add_game.py", line 28, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 73, in build_tabs
    self._build_system_tab(config_level)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 329, in _build_system_tab
    self.system_box = SystemBox(self.lutris_config)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 661, in __init__
    self.generate_widgets("system")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 76, in generate_widgets
    option["choices"] = option["choices"]()
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 298, in get_output_list
    displays = DISPLAY_MANAGER.get_display_names()
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 207, in get_display_names
    return [output.name for output in get_outputs()]
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 47, in get_outputs
    name, _, geometry, rotate, *_ = line.split()
ValueError: not enough values to unpack (expected at least 4, got 2)

**Comment by telanus** [comment]
What OS, and version of Lutris (and from where) do you use.

I've tried it a lot today and didn't run into that

**Comment by compaq2** [comment]
i'm in MX linux 18.2 , lutris 0.5.2.1 , i use it from launch menu and terminal

**Comment by isugimpy** [comment]
Can you provide the output of both `xrandr --version` and `xrandr`, please?  Also, are you possibly running under Wayland instead of Xorg?

**Comment by compaq2** [comment]
Output of :
xrandr --version
xrandr program version       1.5.0
Server reports RandR version 1.5
Output of :
xrandr
Screen 0: minimum 320 x 200, current 1680 x 1050, maximum 16384 x 16384
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DVI-0 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 433mm x 270mm
   1680x1050     59.88*+
DVI-1 disconnected (normal left inverted right x axis y axis)

i'm running under Xorg X11

**Comment by isugimpy** [comment]
https://github.com/lutris/lutris/commit/1fbcdbe15cb09ab28edba74c39582d3c78d82ee9#diff-cd673cf5fbc141e8e2706d0eac05a925 has a fix for this issue.  At least a partial one.  It's already in master, but hasn't yet been released.  It might be wise to change the if on it to check for `" connected " in line`, rather than `"connected" in line`, so it drops all the lines that contain disconnected, unless reading those is actually desired.

**Comment by shofixti-scout** [comment]
Reproducible when running lutris in appvms in Qubes OS and trying to launch the preferences menu (or most other menus).

Reproduced in both debian 9 appvm and a fedora 29 appvm.

Manually modifying display.py to match the previously linked commit fixed the issue in the fedora 29 appvm. Did not try that fix in the debian 9 appvm.

[qubes-os-4.txt](https://github.com/lutris/lutris/files/3194499/qubes-os-4.txt)
[qubes-os-4-debian-9.txt](https://github.com/lutris/lutris/files/3194500/qubes-os-4-debian-9.txt)
[qubes-os-4-fedora-29.txt](https://github.com/lutris/lutris/files/3194501/qubes-os-4-fedora-29.txt)

**Comment by isugimpy** [comment]
Are you reproducing this on master, or a specifically versioned release?
