### ISSUE TITLE
Osmose wants a more recent version of libstdc++ than Ubuntu 14.04 has

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#214]
The best would be to have another build made against Ubuntu 14.04 or older.

**Comment by strycore** [comment]
All the runners are built on Ubuntu 14.04 containers (32 and 64bit) so I find this weird that it wouldn't run on the same system. I had no problem running it on Ubuntu 15.10 and on a 14.04 virtual machine, are you sure your build is up to date?

**Comment by strycore** [comment]
Also, you can report runner related bugs directly in lutris/buildbot

**Comment by Xodetaetl** [comment]
It was an old build indeed, the current one works fine.
But then it means we need automated update, preferably for 0.3.7.

> Also, you can report runner related bugs directly in lutris/buildbot

Hm, milestones don't work cross-repository, so I assume it's going to be a pain to manage, as we'll have to manually create the same milestones in every repo and then manually check every repo's milestone when we approach release... plus the risk to forget tagging...

**Comment by strycore** [comment]
>But then it means we need automated update
Yes, that's a top priority feature
>preferably for 0.3.7.
Too late, I consider 0.3.7 done and we're just fixing bugs at this point, not adding new features.

> milestones don't work cross-repository
but runners aren't tied to milestones, that's the whole point, they are separate projects with their own life cycle.

**Comment by Xodetaetl** [comment]
Alright. :)
