### ISSUE TITLE
Allow enabling Esync for Wine-Staging 4.6 and higher.

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2141]
Esync is now included in staging since 4.6 release, so we should add a check to let users enable the option for wine-staging 4.6 and higher.

**Comment by telans** [comment]
I agree that lutris should detect if v>4.5, however you can leave esync on even when the warning shows, as a checkbox to leave active. Works for now at least

**Comment by Zeioth** [comment]
This issue is related with #2270

**Comment by tannisroot** [comment]
@strycore  This issue was not fixed by 03bec00. 
Also, Esync was added to staging in 4.6, not 4.16.
How to reproduce:
1) Switch wine to System (Staging) version that is older than 4.6 (in my case, it was 4.18).
2) Try to enable Esync option

Lutris will give a warning on how selected Wine version doesn't support Esync even though it does.
