### ISSUE TITLE
Full memory dump (League of Legends)

### ISSUE THREAD

**Issue by Mfurrakama** [lutris/lutris#2145]
https://drive.google.com/uc?id=1M9ht_vmyZhiR2tkrv9KpW0hK9I6HmD3W&export=download
This problem generate this file and ask to share this.

**Comment by isugimpy** [comment]
Can you be more clear about the message you received and what it was from?  This looks like a crash dump from League itself, and isn't something Lutris would have requested.

**Comment by tannisroot** [comment]
Unfortunately this issue is not related to Lutris client, but to Wine. You can track the bug on its Bugzilla: https://bugs.winehq.org/show_bug.cgi?id=47198
