### ISSUE TITLE
Deleted menu shortcut manually, now "Create Application Menu Shortcut" won't work

### ISSUE THREAD

**Issue by WittyNameHere** [lutris/lutris#2146]
**What I did:**
Used "Create Application Menu shortcut" to create a shortcut item for a game
Deleted the item with KDE Menu Editor

**What Happened:**
Lutris maintains a "Delete Application Menu shortcut" link. It naturally does nothing when clicked, but then "Create Application menu shortcut" no longer works.

**What went wrong:**
It won't create another application menu shortcut.

**Comment by tannisroot** [comment]
Can you add this info to your issue?
```
**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.
```

**Comment by tannisroot** [comment]
I've tried reproducing this by just removing the .desktop file itself but couldn't, but I also Gnome. Would be nice if someone on KDE could reproduce this.

**Comment by telanus** [comment]
I can't reproduce this, @WittyNameHere What version of KDE are you using? I'm on 5.12.7 on Kubuntu 18.04.2

**Comment by WittyNameHere** [comment]
I'm new to KDE in general, so I'm not sure which version number you want. The framework is 5.58.0. The distro is Fedora 30. Delete/Create app menu shortcuts works on other games just fine, but since I went into Menu Editor and removed it there before realizing there was a button to do this in Lutris the function for the Battle.Net app just sort of died.
I eventually discovered a shortcut still existing in ~/.local/share/applications called `net.lutris.battlenet-50.desktop` that comes and goes as I click the Create/Delete Application Shortcut link, but KDE doesn't put it in the menu. Possibly because it's logged itself as having deleted that shortcut before? Not sure.

**Comment by WittyNameHere** [comment]
Here's the terminal output. I've removed my username for privacy. Attached the JSON as text.
[lutris-json.txt](https://github.com/lutris/lutris/files/3195531/lutris-json.txt)


`(lutris:11417): Gtk-WARNING **: 12:23:07.911: Theme parsing error: gtk.css:1:108: Failed to import: Error opening file /home/[x]/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-left.css: No such file or directory
Gtk-Message: 12:23:07.954: Failed to load module "appmenu-gtk-module"
INFO     2019-05-19 12:23:07,955 [application.do_command_line:225]:Running Lutris 0.5.2.1
INFO     2019-05-19 12:23:07,956 [startup.check_driver:54]:Using NVIDIA drivers 418.74 for x86_64
INFO     2019-05-19 12:23:07,956 [startup.check_driver:58]:GPU: GeForce GTX 1070
INFO     2019-05-19 12:23:07,956 [startup.check_driver:75]:GPU: 10DE:1B81 3842:6573 using nvidia drivers
INFO     2019-05-19 12:23:08,030 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-05-19 12:23:08,031 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG    2019-05-19 12:23:08,221 [store.get_missing_media:178]:Requesting missing icons from API for 23 games
DEBUG    2019-05-19 12:23:08,222 [gog.get_library:167]:Returning cached GOG library
DEBUG    2019-05-19 12:23:08,227 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-05-19 12:23:08,233 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-05-19 12:23:08,239 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-05-19 12:23:08,660 [pga_game.platform:68]:Game Spider-Man 2 has no platform
DEBUG    2019-05-19 12:23:08,996 [api.get_game_api_page:132]:Loaded 9 games from page 1
DEBUG    2019-05-19 12:23:09,265 [api.get_game_api_page:132]:Loaded 22 games from page 1
INFO     2019-05-19 12:23:23,281 [application.do_shutdown:440]:Shutting down Lutris
`

**Comment by strycore** [comment]
I believe this has been fixed already
