### ISSUE TITLE
libatk missing in the runtime prevents Dwarf Fortress to run

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#215]
That's on Ubuntu 14.04.

I think libatk is some secondary dependency to GTK3 or Glib, I don't remember well. What I do remember is that I spent a lot of time on that lib, it was kind of the last piece of the GTK3 / Glib puzzle but it didn't have the right shape... if I added it, some games and emulators complained, if I removed it, some other games and emulators complained. 

I believe the only way to fix this would be to patch the libs from the GTK3 / Glib chain that have hardcoded dependencies. Like Valve did with GTK2 and their older version of Glib.

**Comment by strycore** [comment]
libatk is part of the gtk libraries indeed, if you want to include it in the runtime, you'll probably have to include the whole gtk libraries.

**Comment by Xodetaetl** [comment]
Alright, to be comprehensive about the issue: 
libatk is a dependency of gtk2 and gtk3. 
We have a working gtk2 patched by Valve in the runtime, so gtk2 apps like Dwarf Fortress just need libatk in the runtime from at least Ubuntu 12.04.
But since we don't have gtk3 in the runtime, when we run gtk3 apps like pcsxr or snes9x, we feed gtk3 with potentially an older, incompatible version of libatk.

The best thing would be to add gtk3 to the runtime, but that's for the future.
Solution 2 is to add the most recent version of libatk to the runtime. It seems to be retro compatible for now, gtk3 from Ubuntu 14.04 works fine with libatk from 16.04.
Solution 3 is to add libatk selectively to gtk2 games.

I'd go for solution 2. What's your opinion ?

**Comment by strycore** [comment]
I'll go for option 2 as well except I see no reason of using another version than Ubuntu 14.04's. The runtime is built upon this release, I'm not creating a special case for one lib.

**Comment by strycore** [comment]
libatk added and deployed

**Comment by Xodetaetl** [comment]
> I see no reason of using another version than Ubuntu 14.04's

The reason is that if you're running, for example, Ubuntu 15.10, you're feeding gtk3 from 15.10 with libatk from 14.04 and it will likely not cooperate. Try pcsxr and snes9x on 15.10, they probably won't launch.
That's the case if I try to run pcsxr on 14.04 with libatk from 12.04.

> I'm not creating a special case for one lib.

There's an "extra" folder already, no need for a special case.

**Comment by strycore** [comment]
I've receive feedback that snes9x-gtk wasn't working properly on Ubuntu 14.04 and reproduced the problem. I've reverted libatk to trusty's version and snes9x work in both Ubuntu 14.04 and 15.10.
