### ISSUE TITLE
[Feature Proposal] Configurable Logging Level

### ISSUE THREAD

**Issue by isugimpy** [lutris/lutris#2150]
Currently, we only provide `-d,--debug` as a logging toggle.  I'd like to suggest that we change it to accept an optional argument for either a numeric log level, or the strings `debug` and `trace`, to allow for more granularity than the current CLI gives.  If there is no arg, just set to the debug level as we currently do.  This would then allow us to define a TRACE log level (set to either 5 or 9), and log more detailed things than the average user needs to see for debugging purposes.  Alternatively, we could add a secondary CLI option for the log level, rather than overloading the existing flag.

**Comment by strycore** [comment]
out of scope
