### ISSUE TITLE
Prelaunch and exit commands fail to run if they take a argument.

### ISSUE THREAD

**Issue by Roxxers** [lutris/lutris#2151]
This is because the code checks if the input is a file and then runs the result. it doesn't expect the file to have an argument. It would be nice to have the functionality to run the scripts with arguments but I can't come up with a airtight solution to pr with.

**Comment by isugimpy** [comment]
A simple workaround for this in the short term is to write a wrapper shell script around whatever you're trying to run which contains the arguments, and making that the prelaunch/exit command.

**Comment by tannisroot** [comment]
> it would be nice to have the functionality to run the scripts with arguments
Can you provide an example with a real game of when this could be useful?

**Comment by Roxxers** [comment]
The reason I opened up the pr was to do with overwatch. It has the issue with the left control not working. So I have a script when passed with x argument switches the right and left controls. And then when passed y argument reverts it. Now this is very simple and i just split the two scripts which is a lot messier and less clean of a solution. 

Even if you find the example not enough of a reason to change how it works, then you should consider this is something that needs documentation. I shouldn't have to be running a debugger to figure out why my script isn't working as that's not something the common user will be doing. Though that might be an update for another time.

**Comment by tannisroot** [comment]
Absolutely, but I just don't quite understand your issue. Can you paste what you exactly passed to prelaunch/exit option fields and the contents of the scripts and with what lutris failed exactly?

**Comment by Roxxers** [comment]
The fail doesn't show up in the logger, hence why I used the debugger. 

In the field, if you input a command with an argument like `/path/to/file -e` then this gets sent off to the [`path_exists` function in lutris.util.system](https://github.com/lutris/lutris/blob/master/lutris/util/system.py#L299). It will then fail all if statements and return false because with the argument it isn't a path to a file.

Because it returns false, nothing is shown in the logger as it just continues with launching the game. There is no error if the check returns false and the user is never alerted.

**Comment by isugimpy** [comment]
This looks like possibly a two-fold problem.  We're also not parsing the field with shlex, and instead just taking the whole string in as the first item of the list to pass to popen.  Could probably solve this one by parsing it to a proper list and then checking if the first item of the list exists.

**Comment by isugimpy** [comment]
@Roxxers Another workaround, if you don't want to have split scripts, until there's a proper solution:

```
#!/bin/bash

if [[ "${0}" =~ .*scriptstart.* ]]
then
    echo "Doing the thing I do at start"
elif [[ "${0}" =~ .*scriptstop.* ]]
then
    echo "Doing the thing I do at stop"
fi```

Create one script, symlink to it, and depending on the name of the script that gets called do either the prelaunc or exit behavior.  It's two filesystem entries, but at least a little cleaner to maintain.

**Comment by mad-ady** [comment]
Regarding why arguments are necessary - I use pre-run command to apply a specific profile for the gamepad when I play some DOS games. E.g. /usr/bin/qjoystick Pre2. This fails to run currently and I need to wrap it around a script, which is harder to maintain.

**Comment by foresto** [comment]
> big problem if you're passing environment variables on the command line. Probably need to parse through and extract those, and then use the first non-envvar value as the path.

I don't think this is necessary. The `var=foo command arg` syntax is a shell construct, not a linux command, and it's not even supported by all shells. There's no reason Lutris should be expected to support that syntax. If someone really needs it, they can use `env var=foo command arg`.

Anyway, Lutris already has a place to define environment variables for each runner. Perhaps applying those to prelaunch and postexit commands would make sense.

**Comment by Anarch157a** [comment]
> This looks like possibly a two-fold problem. We're also not parsing the field with shlex, and instead just taking the whole string in as the first item of the list to pass to popen. Could probably solve this one by parsing it to a proper list and then checking if the first item of the list exists. Though, that solution does end up with a big problem if you're passing environment variables on the command line. Probably need to parse through and extract those, and then use the first non-envvar value as the path.

I tried using shlex on my fork and it seems to work, as long as I don't set variables before the executable. I agree with @foresto, there already a place to set up an environment, supporting this feature on the pre/post lines is unnecessary.

I can submit a PR with my fix if it interests you all.

**Comment by strycore** [comment]
Closing this as out of scope unless someone can justify spending development effort to fix it.
