### ISSUE TITLE
Suggestion for new menus since app menu retirement in Gnome 3.32.

### ISSUE THREAD

**Issue by pedrofleck** [lutris/lutris#2154]
Since Gnome 3.32, app menu is [deprecated](https://gitlab.gnome.org/GNOME/gnome-shell/issues/624) and a legacy menu like [this](https://i.imgur.com/k1uzKky.png) in Lutris is automatically added to CSD bar. My suggestion is based on Nautilus appearance: move the old app menu (screenshot above) to the current "hamburger" menu on the left and include the options "Lutris forums", "Discord" and "Support Lutris!" there. And the current options shown in the hamburger menu can be moved to a new dropdown menu next to "toggle view" like [this](https://i.imgur.com/J15pyXc.png). In my opinion, it would help consistency throughout the Gnome apps (I know Lutris isn't affiliated to Gnome, but anyway) since I'm always opening the wrong menus searching for the option I want.

**Comment by strycore** [comment]
Fixed in master
