### ISSUE TITLE
Allow to customize the name of "Execute script"

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2161]
I know the option isn't meant to stay forever and will be eventually replaced with something else, but since that hasn't happened yet, it would be really nice if "Execute Script" could be improved by allowing script creators to modify its name in UI.
Particularly, this could be very useful for Overwatch, one of the Lutris' flagship games. As the game has a massive amount of shaders, Lutris installer has to ship a state cache to ensure users won't have to suffer hours from annoying shader compilation stutters. The issue is - that state cache often becomes useless after game updates, and needs to be updated with a newer one to ensure stutter-less gameplay. 
I plan to write a script that will do that automatically after user presses "Execute script", but I fear that many won't even know what the option does due to how vague the name of it is. Which is why I want to be able to name it differently: something like "Update shader cache". That way, the user will know exactly what the option is for and will be much more likely to notice and use it.

**Comment by strycore** [comment]
This the exact reason why this option wasnt meant to stay. The next implementation will be the proper one.
