### ISSUE TITLE
Namespace GnomeDesktop not available

### ISSUE THREAD

**Issue by YasirRehman2017** [lutris/lutris#2162]
I installed Lutris on my Manjaro (Xfce) but when clicked on the Lutris icon it didn't opened so I tried to open it in Terminal and here what I get.

```
[yasirr@Markhor ~]$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.7/site-packages/lutris/gui/application.py", line 30, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available

```

**Comment by PythonicChemist** [comment]
Do you have gnome-desktop installed?

> Depends On      : python-gobject  python-yaml  python-evdev  gtk3  glib2  psmisc  cabextract  unzip  p7zip  curl  xorg-xrandr  python-pillow  python-requests
                  gnome-desktop  webkit2gtk  gvfs  mesa-demos

**Comment by YasirRehman2017** [comment]
> Do you have gnome-desktop installed?
> 
> > Depends On      : python-gobject  python-yaml  python-evdev  gtk3  glib2  psmisc  cabextract  unzip  p7zip  curl  xorg-xrandr  python-pillow  python-requests
> > gnome-desktop  webkit2gtk  gvfs  mesa-demos

No
Do I Have to install that?

**Comment by PythonicChemist** [comment]
Yes. It is a dependency of Lutris and Manjaro doesn't include it in their PKGBUILD. If it fixes your problem, please consider filing a bug report with Manjaro to prevent future issues regarding this missing dependency.

**Comment by YasirRehman2017** [comment]
I installed Gnome DE And It broke the installtion the it started to boot into a black now after 6 Hours I manage to Download and Install Manjaro Gnome Hope it works on this.

**Comment by PythonicChemist** [comment]
There is a package called gnome-desktop. It isn't the full desktop environment of Gnome just some libraries. It is only half an MB in size. I checked with Manjaro's package repo and it is has the same name as on arch: gnome-desktop
