### ISSUE TITLE
Battle.net and Diablo 3

### ISSUE THREAD

**Issue by MadMagnetic** [lutris/lutris#2165]
Hi! It`s my inxi -F
`System:    Host: manjaro Kernel: 5.1.4-1-MANJARO x86_64 bits: 64 Desktop: MATE 1.22.1 Distro: Manjaro Linux 
Machine:   Type: Laptop System: ASUSTeK product: TUF Gaming FX705DY_FX705DY v: 1.0 serial: <root required> 
           Mobo: ASUSTeK model: FX705DY v: 1.0 serial: <root required> UEFI: American Megatrends v: FX705DY.306 
           date: 02/13/2019 
Battery:   ID-1: BAT0 charge: 61.3 Wh condition: 61.3/64.0 Wh (96%) 
CPU:       Topology: Quad Core model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx bits: 64 type: MT MCP L2 cache: 2048 KiB 
           Speed: 399 MHz min/max: 1400/2100 MHz Core speeds (MHz): 1: 399 2: 399 3: 399 4: 399 5: 399 6: 399 7: 399 8: 399 
Graphics:  Device-1: AMD Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X] driver: amdgpu v: kernel 
           Device-2: Advanced Micro Devices [AMD/ATI] Picasso driver: amdgpu v: kernel 
           Display: x11 server: X.org 1.20.4 driver: amdgpu FAILED: ati unloaded: modesetting resolution: <xdpyinfo missing> 
           OpenGL: renderer: AMD RAVEN (DRM 3.30.0 5.1.4-1-MANJARO LLVM 8.0.0) v: 4.5 Mesa 19.0.4 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Raven/Raven2/Fenghuang HDMI/DP Audio driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.1.4-1-MANJARO 
Network:   Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter driver: rtl8821ce 
           IF: wlp2s0 state: up mac: dc:f5:05:01:73:d5 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp3s0 state: down mac: 04:92:26:1b:7b:46 
Drives:    Local Storage: total: 931.51 GiB used: 366.08 GiB (39.3%) 
           ID-1: /dev/sda vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB 
Partition: ID-1: / size: 915.40 GiB used: 366.08 GiB (40.0%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 42.1 C mobo: N/A 
           Fan Speeds (RPM): N/A 
           GPU: device: amdgpu temp: 42 C device: amdgpu temp: 46 C 
Info:      Processes: 293 Uptime: 3h 13m Memory: 7.54 GiB used: 3.33 GiB (44.1%) Shell: fish inxi: 3.0.34 
`
So, this is what I see after I`m running Battle.net with DXVK enabled 
![Снимок экрана в 2019-05-26 22-57-04](https://user-images.githubusercontent.com/34352955/58386532-cafab600-8009-11e9-8cff-aad5dcdcef2c.png)
And this  is what I see when I running Battle.net without DXVK
![Снимок экрана в 2019-05-26 22-59-18](https://user-images.githubusercontent.com/34352955/58386617-05188780-800b-11e9-9af4-2fade6e6c787.png)
I was trying several combinations of wine\dxvk, but Diablo does not start anyway. What can be the problem with it?

**Comment by AccountOneOff** [comment]
Please don't open tickets for games or Wine. We have places you can ask for help on like the forums, Discord, or IRC. The github repo isn't one of them.

**Comment by MadMagnetic** [comment]
Sorry, my bad.
