### ISSUE TITLE
feature request: personnalize default install game folder name and game name

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2166]
Hello,
it would be interesting for scripter to add the possibility to personnalize:
- default folder game
- default game name
To be more clear, this is an example:
for Diablo game, you have several scripts and different game version: belzebut script, tchernobog script, gog script...Actually if I install Gog Diablo version, lutris will install it in games/diablo folder and name it "diablo". Then if I want to install Diablo Belzebut, Lutris will install it in Diablo folder and name it diablo. Last time I didn't take attention at that and Lutris installed the Belzebuth version in the same folder as the Gog version. It will be more clean to install Belzebuth version in a "diablo-belzebuth" folder and name it "Diablo Belzebuth" in the Lutris interface. Sorry for my poor english, I hope I explain enough clearly why this feature is necessary.
In a script we could precise install folder and interface name this way:

- installer:
 folder: $FOLDERINSTALL=diablo-belzebuth
 guiname: "Diablo Belzebuth"

Thank you for the interest you will give to my request.

**Comment by soredake** [comment]
https://github.com/lutris/lutris/blob/master/docs/installers.rst#customizing-the-games-name

**Comment by legluondunet** [comment]
thank you @soredake

**Comment by legluondunet** [comment]
I tested this script option:
custom-name: Diablo-Tchernobog
but when I launch the script it purposed me to install the game in diablo folder, not diablo-tchernobog...
Where do I have to put this option? Is it really personalize the folder install?

**Comment by tannisroot** [comment]
Perhaps it would be better to instead add installer version name at the end of the game slug when generating default game folder name?
So for example, by default, instead of installing `GOG Version` installer for `Any Game" into
`Games/any-game`
it would get installed into
`Games/any-game-gog`.
And if you prefer this approach, would mind closing this issue and creating a new one with what I just described?

**Comment by legluondunet** [comment]
I like your approach, but what about the game name showed in the gui?

**Comment by soredake** [comment]
https://github.com/lutris/lutris/issues/2166#issuecomment-496145883

**Comment by legluondunet** [comment]
https://github.com/lutris/lutris/issues/2166#issuecomment-497460925

**Comment by legluondunet** [comment]
Please @soredake be more precise

**Comment by tannisroot** [comment]
@soredake 
>Use this only if the installer provides a significantly different game from the base one.

This is not what this feature is for.
@legluondunet That should be a different issue in my opinion and done by adding a little mark on the banner that differentiates different launchers.

**Comment by legluondunet** [comment]
Ok @tannisroot , I will close this issue and open a new one with your approach, even if it's not fully answer to this issue, but I understand it could be better to go step by step.
