### ISSUE TITLE
[Proposal] Move to newer minimum version of Python

### ISSUE THREAD

**Issue by isugimpy** [lutris/lutris#2167]
Python 3.4 is officially end of life as of a few weeks ago.  Given this, I would propose that it would make sense to move Lutris up to a newer minimum version.  3.5 will be supported for at least another year, and is available on the overwhelming majority of distros.  Debian Stretch does not have 3.6, but Buster will be leapfrogging it and going to 3.7.  I'm not sure it makes sense to go all the way to 3.6 or 3.7 because of that.

**Comment by strycore** [comment]
We support Debian stable. Enough said.
