### ISSUE TITLE
Feature Request: Support non-gnome desktops

### ISSUE THREAD

**Issue by traverseda** [lutris/lutris#2168]
It would be nice of there was a pure GTK option that didn't depend on gnome-desktop. A KDE option would also be nice.

**Comment by isugimpy** [comment]
Can you clarify this a bit more?  I'm pretty certain I don't have GNOME installed on my desktop at home, and am running under KDE, and Lutris works just fine.

**Comment by TingPing** [comment]
gnome-desktop is a small library it has no dependency to gnome-shell or any DE level components.
