### ISSUE TITLE
Installing a browser game will set the `directory` DB param to default path instead of null

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#217]
I tried to install both versions of [The Hitchhiker's Guide](https://lutris.net/games/the-hitchhikers-guide-to-the-galaxy/), one of them being a browser version. Then when trying to remove the browser version, I get the possibility to remove the game's folder of the other version, while it should be greyed out. 

If it's not clear what happens, try it out for yourself. You should see the problem. :)

**Comment by strycore** [comment]
Fixed by e09a906
