### ISSUE TITLE
Have install intructions for Opensuse

### ISSUE THREAD

**Issue by aRealCyborg** [lutris/lutris#2170]
I am looking though the page and I notice there is no instruction for installing drivers or needed packages on this page.

(sorry if this is not needed i am new to github and linux)

**Comment by AccountOneOff** [comment]
I don't think any of us use Opensuse to know how. If you, or anyone else for that matter, find out how, I'll be happy to add it to the wiki.

**Comment by romulasry** [comment]
You need to install 32bit libs such as vulkan and mesa dri. I believe.

**Comment by strycore** [comment]
Lutris is the SUSE repos
