### ISSUE TITLE
"Enable Feral gamemmode" Greyed Out

### ISSUE THREAD

**Issue by Iron-E** [lutris/lutris#2172]
**Describe the bug**

I have installed [`gamemode`](https://github.com/FeralInteractive/gamemode) using their [bootstrap.sh](https://github.com/FeralInteractive/gamemode/blob/master/bootstrap.sh) file. To ensure that it was installed, `gamemoded` and `gamemoderun` were tested (both yield output from the console). Lutris greys out the option to enable `gamemode`, however.

**Expected behavior**

Lutris will detect `gamemode` and allow me to toggle the `gamemode` setting on and off.

**Current behavior**

The `gamemode` setting is greyed out even though Lutris has detected it (see the [attached JSON](https://github.com/lutris/lutris/files/3243406/lutris-issue-report.json.gz)).

**Steps to reproduce**

1. Install `gamemode` using [bootstrap.sh](https://github.com/FeralInteractive/gamemode/blob/master/bootstrap.sh)
2. Install Lutris
3. Navigate to the Lutris settings and see that _Enable Feral gamemode_ is greyed out.

* Steps __1__ and __2__ are performable in any order.

**Lutris debugging output**

```
INFO	 2019-06-01 00:16:28,440 [application.do_command_line:225]:Running Lutris 0.5.2
INFO	 2019-06-01 00:16:28,441 [startup.check_driver:54]:Using NVIDIA drivers 418.56 for x86_64
INFO	 2019-06-01 00:16:28,441 [startup.check_driver:58]:GPU: GeForce GT 650M
INFO	 2019-06-01 00:16:28,441 [startup.check_driver:75]:GPU: 10DE:0FD1 1028:0578 using nvidia drivers
INFO	 2019-06-01 00:16:28,441 [startup.check_driver:75]:GPU: 8086:0166 1028:0578 using i915 drivers
INFO	 2019-06-01 00:16:28,472 [startup.check_vulkan:129]:Vulkan is supported
INFO	 2019-06-01 00:16:28,473 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG	2019-06-01 00:16:28,663 [http.get:68]:GET https://lutris.net/api/runtime
INFO	 2019-06-01 00:16:37,741 [application.do_shutdown:440]:Shutting down Lutris
```

**System information**

[lutris-issue-report.json.gz](https://github.com/lutris/lutris/files/3243406/lutris-issue-report.json.gz)

**Screenshots**

![Screenshotfrom2019-06-0100-42-58](https://user-images.githubusercontent.com/36409591/58743854-0988da00-8429-11e9-851e-b26a5460eb28.png)

**Comment by inkubux** [comment]
I have the same issue
I even compiled game mode for 

> /usr/lib32$ ls -al libgame*
lrwxrwxrwx 1 root root    20 Jun  3 23:01 libgamemodeauto.so -> libgamemodeauto.so.0
lrwxrwxrwx 1 root root    24 Jun  3 23:01 libgamemodeauto.so.0 -> libgamemodeauto.so.0.0.0
-rwxr-xr-x 1 root root 27352 Jun  3 22:48 libgamemodeauto.so.0.0.0
lrwxrwxrwx 1 root root    16 Jun  3 23:01 libgamemode.so -> libgamemode.so.0
lrwxrwxrwx 1 root root    20 Jun  3 23:01 libgamemode.so.0 -> libgamemode.so.0.0.0
-rwxr-xr-x 1 root root 24840 Jun  3 22:48 libgamemode.so.0.0.0

**Comment by Iron-E** [comment]
> I have the same issue
> I even compiled game mode for 32 bits
> 
> > /usr/lib32$ ls -al libgame*
> > lrwxrwxrwx 1 root root    20 Jun  3 23:01 libgamemodeauto.so -> libgamemodeauto.so.0
> > lrwxrwxrwx 1 root root    24 Jun  3 23:01 libgamemodeauto.so.0 -> libgamemodeauto.so.0.0.0
> > -rwxr-xr-x 1 root root 27352 Jun  3 22:48 libgamemodeauto.so.0.0.0
> > lrwxrwxrwx 1 root root    16 Jun  3 23:01 libgamemode.so -> libgamemode.so.0
> > lrwxrwxrwx 1 root root    20 Jun  3 23:01 libgamemode.so.0 -> libgamemode.so.0.0.0
> > -rwxr-xr-x 1 root root 24840 Jun  3 22:48 libgamemode.so.0.0.0

Have you managed to solve this issue?

**Comment by inkubux** [comment]
Yes I did manage to get it working. What happened is that my build (meson) was cached and I was always building the x64 version but in the lib32 folder.. :/. 

There was not a lot of documentation about the process in the gamemode github about building it for 32bit.

Also for some reason even if the source code seems to be looking into the 
        ('/lib/i386-linux-gnu', '/lib/x86_64-linux-gnu'), folder

What actually ended up working was to install both in the
         ('/usr/lib32', '/usr/lib64')


Thanks :)

**Comment by Iron-E** [comment]
@inkubux thank you for the help! Unfortunately, the option is still greyed out for me (although I suspect I would have had to do this anyway).

**Comment by dinotheextinct** [comment]
I have the same problem.

**Comment by snapfreeze** [comment]
Hey, I was having the same issue.

If you take a quick peek at the source code, Lutris looks for the existence of `libgamemodeauto.so` in *both* your 64 and 32-bit libraries.

For me the issue was that I only had `libgamemodeauto.so.0` and `libgamemodeauto.so.0.0.0` so Lutris wasn't picking up on them.

```bash
$ find /usr -name "libgamemodeauto*"

/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0.0.0
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0.0.0
```

I resolved the issue by doing:

```bash
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libgamemodeauto.so.0 libgamemodeauto.so

cd /usr/lib/i386-linux-gnu
sudo ln -s libgamemodeauto.so.0 libgamemodeauto.so
```

And now my Feral Gamemode toggle works :)

**Comment by Sanaki** [comment]
Sadly, mine's not playing so nice. Still greyed out, yet:
```
$  find /usr -name "libgamemodeauto*"
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0.0.0
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0
/usr/lib/i386-linux-gnu/libgamemodeauto.so
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0.0.0
```

Tried adding them to /usr/lib32 as well, no dice. Not sure why it's ignoring me. Just adding gamemoderun as a command prefix has worked in the meantime, but I'd still like a proper solution.

**Comment by tuxutku** [comment]
@snapfreeze but wouldn't that cause 32bit games to fail or not work with gamemode at all? I don't know if gamemode works with 32bit applications (it should work tbh because it doesn't do anything with the application)

**Comment by antimech** [comment]
Can't use it too on Linux Mint 19.2

**Comment by Sanaki** [comment]
On Mint 19.2, you should have the following files to make it work:
```
/usr/lib/i386-linux-gnu/libgamemodeauto.so
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0
/usr/lib/i386-linux-gnu/libgamemodeauto.so.0.0.0
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0
/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0.0.0
```

If you lack the 32-bit ones, you'll need to compile them yourself. This is the bootstrap32.sh I used to do so:
```
#!/bin/bash
# Simple bootstrap script to build and run the daemon

if [ "$EUID" -eq 0 ]
  then echo "Please don't run bootstrap.sh as root."
  exit
fi

set -e

# Check for scaling governor support and warn about it
if [ ! -f "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" ]; then
	echo "WARNING: CPUFreq scaling governor device file was not found at \"/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor\"."
	echo "This probably means that you have disabled processor scheduling features in your BIOS. See README.md (or GitHub issue #44) for more information."
	echo "This means GameMode's CPU governor control feature will not work (other features will still work)."

	if [ "$TRAVIS" != "true" ]; then
		# Allow to continue the install, as gamemode has other useful features
		read -p "Would you like to continue anyway [Y/N]? " -r
		[[ $REPLY =~ ^[Yy]$ ]]
	fi
fi

# accept a prefix value as: prefix=/path ./bootstrap.sh
: ${prefix:=/usr}

export CFLAGS='-m32'
export PKG_CONFIG_PATH='/usr/lib/i386-linux-gnu/pkgconfig'

# Echo the rest so it's obvious
set -x
meson --prefix=$prefix build --buildtype debugoptimized -Dwith-systemd-user-unit-dir=/etc/systemd/user "$@"
meson build32 -Dwith-daemon=false -Dwith-examples=false -Dwith-systemd=false --prefix=/usr --libdir lib/i386-linux-gnu
cd build32
ninja

# Verify user wants to install
set +x
if [ "$TRAVIS" != "true" ]; then
	read -p "Install to $prefix? [y/N] " -r
	[[ $REPLY =~ ^[Yy]$ ]]
fi
set -x

sudo ninja install

# Reload systemd configuration so that it picks up the new service.
systemctl --user daemon-reload
```

That was self-generated using the file from earlier alongside changes to the repo's bootstrap found using diff.

**Comment by mihaly044** [comment]
I have got it working on Pop! OS 19.10 this way:

- First I have built and installed the 64 bit version using `./bootstrap.sh`
- Then I have set the following env variables:
```
export CFLAGS='-m32'
export PKG_CONFIG_PATH='/usr/lib32/pkgconfig'
```
- After that I have installed the 32 bit version of libdbus1-3 using apt-get:
`sudo apt-get install libdbus-1-3:i386`

- And then I've built the project with meson:
`meson build32 -Dwith-daemon=false -Dwith-examples=false -Dwith-systemd=false --prefix=/usr --libdir lib32`

- For some reason, ninja will attempt to link with the 64 bit version of libdbus1-3, so I have fixed that up manually, here's how:
cd into the newly created `build32` directory, and open `build.ninja` with your editor of choice, and change all occurrences of /usr/lib/x86_64-linux-gnu/libdbus-1.so to /usr/lib/**i386**-linux-gnu/libdbus-1.so.

- After that you should be good to go and able to call `ninja`, then `sudo ninja install` while still inside the build32 directory.

- As the last step, you need to execute `sudo ldconfig` to rebuild the search path for libraries.

Voila! After you've restarted Lutris you should have the feral gamemode switch enabled.

**Comment by mihaly044** [comment]
I haven't been able to make it work without tinkering a lot either.
Don't forget to execute `ldconfig` as root after you have compiled and installed the 32 bit libraries.
In case it still doesn't work for you, here's my hacky workaround I use to setup both 32 and 64 bit versions of gamemode on a clean system:

```
sudo apt-get install libsystemd-dev:i386 meson libsystemd-dev pkg-config ninja-build git libdbus-1-dev libdbus-1-dev:i386 gcc-multilib
git clone https://github.com/FeralInteractive/gamemode
cd gamemode
./bootstrap.sh
systemctl --user start gamemoded.service 
export CFLAGS='-m32'
export PKG_CONFIG_PATH='/usr/lib32/pkgconfig'
meson build32 -Dwith-daemon=false -Dwith-examples=false -Dwith-systemd=false --prefix=/usr --libdir lib32
sed -i 's/x86_64-linux-gnu\/libdbus/i386-linux-gnu\/libdbus/g' build32/build.ninja
ninja -C build32 
ninja -C build32 install
sudo ldconfig
```

Note: remove the calls to `./bootstrap.sh` and `systemctl --user start gamemoded.service` if you have the 64 bit version set up already.
Ninja tries to link with the 64-bit version of libdbus and fails. There certainly must be a more elegant way of fixing this, but sed did do the job for now.

After executing this, your gamemode switch should work as expected.

**Comment by RickAndTired** [comment]
This https://github.com/lutris/lutris/issues/2418#issuecomment-546881778 fixed it for me. The toggle now works.
In `lutris/sysoptions.py` under `"option": "gamemode",` edit the `"condition"` line to:
`"condition": bool(system.find_executable("gamemoded")),`


You can also change the default line to `True` and even if you leave the toggle grayed out - gamemode will still run fine.

I only have the 64bit gamemode installed, but it works fine and provides performance improvements for both 32bit and 64bit games

**Comment by Iron-E** [comment]
@RickAndTired that fixed it for me too. I'm tempted to close the issue, although it seems like some people still have trouble getting it open.

**Comment by itaranto** [comment]
This is still not fixed in 5.6.
I'm testing this in openSUSE Tumbleweed with gamemode versions installed (32bit and 64 bit) and the button is still greyed out.

**Comment by toluschr** [comment]
@itaranto It's because lutris tries to preload `libgamemode.so`, which is included in the development package of gamemode. I will open a new issue for this with an included patch.

**Comment by regulator-g** [comment]
I'm on Pop_OS 20.04 and the option is still greyed out, gamemode comes preinstalled on 20.04

**Comment by dikdust** [comment]
> I'm on Pop_OS 20.04 and the option is still greyed out, gamemode comes preinstalled on 20.04

same on ubuntu 20.04, just greyed out

**Comment by tgharib** [comment]
Still an issue for me on tumbleweed. Even installed `libgamemode-devel` but no dice.
