### ISSUE TITLE
Does not have a Release file

### ISSUE THREAD

**Issue by Kartereo** [lutris/lutris#2175]
**Issue**

Ign:6 http://ppa.launchpad.net/paulo-miguel-dias/pkppa/ubuntu disco InRelease
Err:7 http://ppa.launchpad.net/paulo-miguel-dias/pkppa/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/paulo-miguel-dias/pkppa/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Steps to reproduce**

-Follow wiki to install drivers for ubuntu
-sudo add-apt-repository ppa:paulo-miguel-dias/pkppa
-sudo add-apt-repository ppa:paulo-miguel-dias/pkppa

**Lutris debugging output**

Not sure how to do this. I haven't even open the application yet.

**System information**

Kubuntu 19.04

**Comment by Citiroller** [comment]
It's clearly stated this is needed for Ubuntu 18.04 and not anymore for Ubuntu 18.10. And therefore I guess it's not needed for 19.04 as well. 19.04 already ships with llvm 7.0!
