### ISSUE TITLE
403 via tor connection

### ISSUE THREAD

**Issue by mrAndersen** [lutris/lutris#2176]
**Describe the bug**

Lutris URLs return 403, when accessing via tor

**Expected behavior**

200 HTTP ok

**Current behavior**

403 on lutris api via tor

**Lutris debugging output**

[https://pastebin.com/CvfrX4XE](https://pastebin.com/CvfrX4XE)

**Screenshots**

![image](https://user-images.githubusercontent.com/2115147/58788524-b8c5dc80-85f4-11e9-9b59-4ec82ab3afb2.png)

**Comment by mrAndersen** [comment]
UP

Actually accessing https://lutris.net/api/runtime via firefox is ok, but doing
`curl https://lutris.net/api/runtime` results in 403 from your cloudflare server, and from lutris client too, as mentioned above

**Comment by aTosser** [comment]
Cloudflare required captcha when accessing any of their sites via tor. https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

Recommend close: not-our-bug

**Comment by mrAndersen** [comment]
What do you mean, "not-our-bug"? 

YOUR api is calling YOUR web backend from YOUR application, and because of YOUR cloudflare settings configured incorrectly - users, who use lutris via tor cannot access almost all application functions. As i see this is clearly a bug.

Tor is used here not because i, or someone else like anonymity very much, but because lutris is blocked in my country somehow.

I like lutris, and not only i do, and i want to use it without proxy-tor-pain-in-ass dances) Thx

**Comment by tannisroot** [comment]
Need opinion from @strycore regarding this.

**Comment by strycore** [comment]
Is there any way to configure Cloudflare to accept Tor connection? I'm not opposed to accepting Tor usage, I just need to know how to do it.

**Comment by strycore** [comment]
Also, I can upgrade the Cloudflare account if that's needed.

**Comment by mrAndersen** [comment]
According to [https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-](this)
link you can override CF logic, when tor client accesses web service.

**Comment by strycore** [comment]
closing, haven't heard about this in a while
