### ISSUE TITLE
JSON Error after logging in on client

### ISSUE THREAD

**Issue by redmoogle** [lutris/lutris#2180]
**Special Note:**
This issue happened with Ubuntu 18.10 too

Describe the bug

Lutris fully refuses to startup. Even when doing sudo python3 or sudo lutris

Expected behavior

Lutris to pop up so I can play games.

Current behavior

Creates a blank resourceless process

Steps to reproduce
Click on lutris icon
or 
type "sudo lutris"

Lutris debugging output

dakotamew@dakotamew-MS-7641:~/Desktop$ sudo lutris -d
INFO     2019-06-04 18:02:04,707 [application.do_command_line:225]:Running Lutris 0.5.2
INFO     2019-06-04 18:02:04,707 [startup.check_driver:54]:Using NVIDIA drivers 418.56 for x86_64
INFO     2019-06-04 18:02:04,707 [startup.check_driver:58]:GPU: GeForce GTX 980 Ti
INFO     2019-06-04 18:02:04,708 [startup.check_driver:75]:GPU: 10DE:17C8 3842:4995 using nvidia drivers
INFO     2019-06-04 18:02:04,785 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-06-04 18:02:04,786 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
ERROR    2019-06-04 18:02:04,985 [utils.get_pixbuf:55]:Unable to load icon from image /home/dakotamew/.cache/lutris/user.png
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 133, in __init__
    self.game_panel = GenericPanel(application=self.application)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/generic_panel.py", line 44, in __init__
    self.place_content()
  File "/usr/lib/python3/dist-packages/lutris/gui/views/generic_panel.py", line 71, in place_content
    self.put(self.get_user_info_box(), 48, 16)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/generic_panel.py", line 126, in get_user_info_box
    user_info = json.load(user_info_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

System information

[lutris-issue-report.txt](https://github.com/lutris/lutris/files/3254661/lutris-issue-report.txt)

Screenshots
N/A

**Comment by redmoogle** [comment]
Issue resolved by doing some research into the code and reversing my way into the file directory causing errors. As it turns out the user.json file was fully empty and I just placed
{
}
to resolve the error

**Comment by Drek282** [comment]
Thank you for posting this redmoogle.  Lutris wouldn't start after a lockup and in my case the file with the problem was ~/.local/share/lutrus/runtime/dxvk/dxvk_versions.json.  I'm assuming the file was corrupted.

**Comment by drlamb** [comment]
> Thank you for posting this redmoogle. Lutris wouldn't start after a lockup and in my case the file with the problem was ~/.local/share/lutrus/runtime/dxvk/dxvk_versions.json. I'm assuming the file was corrupted.

This was my issue on Fedora 34 as well. Resolved by adding brackets to that file and retrying.
