### ISSUE TITLE
Change default aspect ratio value to "Integer scale" for Mednafen runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2185]
If the user wishes to play the game in Fullscreen, they would rather to straight away launch the game like this (Multiple of 2 scale):
![Screenshot from 2019-06-07 07-11-16](https://user-images.githubusercontent.com/10602045/59080891-d5635c80-88f3-11e9-9354-5c5b9b99fec5.png)
Rather than like this (current default, Disabled):
![Screenshot from 2019-06-07 07-11-43](https://user-images.githubusercontent.com/10602045/59080914-eb711d00-88f3-11e9-8427-d110c05090b5.png)

**Comment by 7HEPOW** [comment]
Good suggetion! :) Though `aspect_int` should maybe preferred over `aspect_mult2`. On some systems on a 1080p screen aspect_mult2 will scale to 4x instead 5x because 6x doesn't fit. Using aspect_int will also scale to 3x, 5x, 7x resolutions, filling more of the screen with less black around. :)
