### ISSUE TITLE
Can't open "Import Games" after changing password on GOG

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2186]
Reported by a user on Discord:
>I changed my GOG.com password, and now nothing happens when I try to open the "Import Games" menu, even after reverting the password.
https://paste.ubuntu.com/p/vZpKVzrT7W/

**Comment by LaserPanzerWal** [comment]
I had the same issue. To solve this and be able to import games again, i removed .gog.auth and .gog.token in ~/.cache/lutris.
I noticed this when I also removed the whole directory and ~/.config/llutris, so maybe try deleting all of them, but the above mentioned files did the trick for me in the end.

**Comment by dkasak** [comment]
ac5a498 fixed the crash but this is still rather user unfriendly since there's no option to rectify the problem from Lutris and you have to be running it from a terminal to even learn about the problem.

Is handling this in the scope of this issue or should a new issue be opened?

**Comment by AlexanderPlaza** [comment]
This issue should be reopened - it should prompt to re-enter your password. Just ran into the issue and luckily found this page.

**Comment by tannisroot** [comment]
Can you open a new issue about this? thanks
