### ISSUE TITLE
feature: use custom-name script function as folder install name

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2187]
Hello, could you add this feature? When I will install a game with Lutris, it will install it by default in a folder base on **custom-name** if precised in script.
So for example, by default, if you install Diablo, actually whatever the script Lutris will install it in diablo folder. If you test another Diablo script, you may overwrite the previous installation of Diablo, as there are installed in the same default folder.
But if the Lutris install script for Diablo Tchernobog contains `custom-name: Diablo Tchernobog`, Lutris could install this version in diablo-tchernobog folder by default and avoid overwriting a precedent Diablo install.

**Comment by AccountOneOff** [comment]
This seems unnecessary. Why not just change the name here?

![stardew](https://user-images.githubusercontent.com/15083452/59472567-b97c2100-8df3-11e9-9328-1eb32ac5c077.png)

**Comment by legluondunet** [comment]
@AccountOneOff Please read this closed issue https://github.com/lutris/lutris/issues/2166#event-2398923184 to have a better explanation about what we would obtain.

**Comment by legluondunet** [comment]
Hello @AccountOneOff , I updated my request, it is more precise now, the idea is to use "custom-name: " from script as default install folder.
