### ISSUE TITLE
Inconsistent game search behaviour

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2189]
Some titles are not displayed when searching the Lutris DB from the official website.

Reproduction steps:
1. Search 'Kindle' from the application and you'll get the following result: **Kindle for PC**
2. Search 'Kindle' from the lutris.net website and you won't get any results.

**Comment by AccountOneOff** [comment]
https://lutris.net/games/?q=kindle&unpublished-filter=on

Game pages without installers don't show up as published.
