### ISSUE TITLE
Inability to report duplicate game entries

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2190]
It's not possible to report duplicate game entries from the lutris website. As an example, you can search **Battle for Wesnoth**:
![wesnoth](https://user-images.githubusercontent.com/4029937/59154467-54cf6800-8a7b-11e9-90de-7782bcb18d1d.png)

**Comment by Faalagorn** [comment]
Should probably belong to https://github.com/lutris/website/issues unless you want to be able to report it from client, otherwise I agree.

**Comment by telanus** [comment]
Copied it here: https://github.com/lutris/website/issues/364 as it's a website bug
