### ISSUE TITLE
[Runner dosbox] `Command arguments` setting will be ignored when multiple arguments are specified

### ISSUE THREAD

**Issue by jp7677** [lutris/lutris#2195]
**Describe the bug**

The dosbox runner has a Game option `Command arguments` which just adds arguments to the dosbox command. This works fine for single arguments like 
```-version```
, but does not work when several arguments (separated by space) are stated, e.g. 
```-c pause```
or
```-c "imgmount d someimage.iso" -c "cd path"```
.

**Expected behavior**

All command arguments should be honored when dosbox gets started. Note that the extra arguments will be correctly executed when directly copying the full command from the lutris logs into a console. Thus the dosbox command is correctly build.
Looking at the source https://github.com/lutris/lutris/blob/master/lutris/runners/dosbox.py#L152 all arguments are just appended as a single string. I'm no python expert but I think each argument should be added separately, similar like here  https://github.com/lutris/lutris/blob/master/lutris/runners/commands/dosbox.py#L33

**Current behavior**

Command arguments will be ignored when multiple arguments separated by space are specified.

**Steps to reproduce**

- Enter 
```-c pause```
as Command arguments in a dosbox runner
- Observe that the `pause` is ignored during startup.

**Comment by strycore** [comment]
we have fixed this in the current dosbox runner.

**Comment by jp7677** [comment]
Very cool, thanks a lot!
