### ISSUE TITLE
Need a way for users to discover/locate runner source code

### ISSUE THREAD

**Issue by foresto** [lutris/lutris#2196]
I've been trying for half an hour to figure out where the *ge-protonified* wine builds come from and what patches they include, and I still don't know.

This is a larger issue, though. Users are currently expected to install and run mystery binaries. It would be helpful if Lutris would disclose to the user where to find the source code for each runner version. Perhaps even include a little blurb naming the maintainer and describing how it differs from other versions.

In the shorter term, does anyone have a link to this info for the *ge* wine builds? I don't see them on the Wine-Builds wiki page.

**Comment by telanus** [comment]
Wine builds are build from here: https://github.com/lutris/wine afaik

The ge in the name is to state the current maintainer IE @GloriousEggroll  atm

**Comment by tannisroot** [comment]
Wine sources are fully available on Github. I will add a link to them on Wiki.

**Comment by foresto** [comment]
Thanks, @tannisroot.

**Comment by foresto** [comment]
I now see a brief explanation of the *tkg* and *ge* wine builds, along with links that hint at how to find the upstream repositories for those patch sets. Nice.

I don't see any mention of ffmpeg-enabled FAudio in GloriousEggroll's builds, though. Is that included in lutris' *ge* builds? If so, perhaps that should me mentioned as well, since it would be very helpful for certain games.
