### ISSUE TITLE
Lutris removes "DXVK" dlls even when they're not from DXVK

### ISSUE THREAD

**Issue by bjoern-tantau** [lutris/lutris#2198]
**Describe the bug**

It is currently not possible to use Gallium Nine, when DXVK is disabled in the settings (which would be what I thought would be necessary to run Gallium Nine). When I enable Gallium Nine and then run a game I get these messages in the console:

```
2019-06-17 10:21:30,859: Removing DXVK dll /home/bjoern/Games/starcraft-ii/drive_c/windows/system32/d3d9
2019-06-17 10:21:30,859: Removing DXVK dll /home/bjoern/Games/starcraft-ii/drive_c/windows/syswow64/d3d9
```

Afterwards the game complains about a missiing d3d9.dll
Enabling DXVK and setting the version to manual makes it work.

**Expected behavior**

Game runs with Gallium Nine.

**Current behavior**

Game complains about a missiing d3d9.dll

**Steps to reproduce**

* Install Gallium Nine via winetricks.
* Enable Gallium Nine by running drive_c/windows/syswo64/ninewinecfg.exe
* Disable DXVK.
* Run game.

**Workarounds**

Any of these should work:

* Set DXVK-version to manual and enable DXVK.
* Run the game manually from the console and not via lutris.
* It would probably work to run the game exe manually via "Run EXE inside wine prefix".

**Comment by AccountOneOff** [comment]
Is this with Lutris 0.5.2 or with master?

**Comment by bjoern-tantau** [comment]
0.5.2
I'll try to find some time to test it with master. Probably not today, though.

**Comment by tannisroot** [comment]
I have this with master too @AccountOneOff
