### ISSUE TITLE
feature: add "open wineconsole.exe" in Lutris popup menu

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2199]
Hello,
for some games, I need to open a terminal to execute some tests.
Each time I did: right click on the game banner, execute an EXE, search for windows/system32/wineconsole.exe or windows/system64/wineconsole.exe, depend the wineprefix I use.
It will be very useful to add to the popmenu "Open console" which will launch wineconsole.exe from wineprefix game.
PlayOnLinux have this feature and for I migrated to Lutris, this feature misses me a lot.
Thank you for the attention you will give to this issue.

**Comment by strycore** [comment]
FIxed by #2213
