### ISSUE TITLE
league of legends file not found

### ISSUE THREAD

**Issue by didentifier** [lutris/lutris#2200]
Hello, I m trying to instal League of Legends over lutris. I keep getting the message file not found after downloading is done. Has anyone had this error before?
![Screenshot from 2019-06-18 15-42-53](https://user-images.githubusercontent.com/26007336/59683089-27538e80-91e0-11e9-910d-418cf4cdc4c3.png)

**Comment by tannisroot** [comment]
Can you hop in on our Discord and mention me (I have the same nickname there) to get this resolved?
It's not really a bug.

**Comment by AccountOneOff** [comment]
Tested both published installers and they work fine here. Please, follow this page: https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info
