### ISSUE TITLE
Epic Games Store "Self Update Failed"

### ISSUE THREAD

**Issue by maraaaa** [lutris/lutris#2201]
**Describe the bug**

When launching Epic Games Store, EGS fails to launch with "Self Update Failed, the necessary prerequisites have failed to install.  Please contact support.  Error Code: [SU-PQR1603](https://epicgames.helpshift.com/a/epic-games-store-and-launcher/?s=error-codes&f=su-pqr1603&p=all)

**Expected behavior**

EGS should launch and self update.

**Current behavior**

EGS launches and is unable to self update.

**Steps to reproduce**

- Install Epic Games Store
- Attempt to launch

**Lutris debugging output**

https://gist.github.com/maraaaa/1c3ff094612a1dbca695efea8c73a086

In `/home/<username>/Games/epic-games-store2/drive_c/users/<username>/Local Settings/Application Data/EpicGamesLauncher/Saved/Logs`

`EpicGamesLauncher.log` seems to indicate it's a prerequisite failing?

```
[2019.06.18-23.47.09:315][477]LogPrerequisites: Running prerequisites installer C:/Program Files (x86)/Epic Games/Launcher/Portal/SelfUpdateStaging/Install/Portal/Extras/Redist/LauncherPrereqSetup_x64.exe /quiet /log "C:/users/maraaaa/Local Settings/Application Data/EpicGamesLauncher/Saved/Logs/SelfUpdatePrereqInstall.log"
[2019.06.18-23.47.10:832][568]LogPrerequisites: Error: Prerequisites executable failed with code 1603
[2019.06.18-23.47.10:832][568]LogBuildPatchServices: Error: EBuildPatchInstallError::PrerequisiteError PQR1603
```

Full log bundle here:  https://gist.github.com/maraaaa/9fbea5f07095bbae948974a1e50c4e0d

Is it DirectX that's failing to install?

```
Action start 5:06:03: CAInstallDirectX.
SFXCA: Extracting custom action to temporary directory: C:\users\<username>\Temp\msie76d.tmp-\
SFXCA: Binding to CLR version v4.0.30319
SFXCA: Failed to create app domain. Error code 0x80131515
Action ended 5:06:04: CAInstallDirectX. Return value 0.
```

Have tried with `ge-protonified-4.9-x86_64` and `ge-protonified-4.10-x86_64`

**System information**

Happy to share this `.json` file privately.

FC29.

**Screenshots**

https://i.imgur.com/fpwwi8V.png

I don't seem to be able to link directly to the comment, but [others appear to be having issues on lutris.net](https://lutris.net/games/epic-games-store/)

Thanks!

**Comment by AccountOneOff** [comment]
Thanks for the report. Unfortunately, we only accept reports for the Lutris client and its installers. Please, consider opening a bug report on https://bugs.winehq.org instead.

**Comment by Dertosh** [comment]
I found solution 
add argument -SkipBuildPatchPrereq in game options 

https://answers.unrealengine.com/questions/437175/view.html

**Comment by gardotd426** [comment]
Please reopen this issue, as the World War Z lutris installer does not work because the EGS installation fails.

**Comment by strycore** [comment]
No. Github is not a place to solve game installation issues. It is meant for the development of our client.

**Comment by gardotd426** [comment]
> we only accept reports for the Lutris client and its installers.

What do "Lutris client installers" mean if not installers from the Lutris client? 

The install scripts are supposed to be moderated, this is where issues with the installers are supposed to be reported, according to that quote. A Lutris installer is broken. When you try and install EGS with the Lutris installer through the Lutris client, it doesn't work. Where is it supposed to be reported then?

**Comment by strycore** [comment]
I means that's it's not an accurate statement.

Lutris installer issues are merely tolerated on github because users don't know any better.
It actually causes noise on the bug tracker and slows down the development of lutris quite a bit.

There are several places where installer issues can be discussed:

- The lutris forums
- Discord
- Installer issues on the game page itself
