### ISSUE TITLE
Runner Dosbox wasn't compiled with SDL2_net or SDL2_sound

### ISSUE THREAD

**Issue by JoshuaPettus** [lutris/lutris#2203]
This is with Lutris 0.5.2

Not a bug per-se, but definitely an oversight.  The built-in dosbox runner doesn't have the ipxnet command, and when I try to mount an .cue file from a redbook style cd, fails with the error "MSCDEX: Failure: Invalid file or unable to open."  A little research points to the most likely culprit that dosbox was compiled without SDL2_net and SDL2_sound libraries.  I wouldn't be surprised if there were others. Please distribute a copy of dosbox with all optional features enabled.

Thank-you!

**Comment by telanus** [comment]
I just tried it. redownloaded the runner, and used pga tour 486, that runs of a cd, and it worked. ipxnet should have no influence in mounting CD's as ipxnet is used to browse the internet: https://www.dosbox.com/wiki/Connectivity.

@JoshuaPettus how are you loading the cd? Yiour error reads more like dosbox is not finding the cd, which could point to wrong mounting commands.

For reference here is how I mounted the game: 
`imgmount d "/Games/Romz/IBM/CD/p/PGA Tour Golf 486/PGA Tour Golf 486 (1994)(Electronic Arts).iso" -t iso -fs iso`

**Comment by JoshuaPettus** [comment]
The IPX net part is separate, but it is definitely left out.   IPX is an old protocol used for networking, particularly old multiplayer games.

As for your test, I'm afraid it is wrong.  An ISO cant not hold the audio track data alone.   This is normally done with .BIN/CUE format.  Second you need to use a game that has audio tracks, on the CD.  Heroes of might or magic comes to mind.  I myself was hitting my head against the GOG release of Shadow Warrior which uses the .CUE  file to point the audio tracks to ogg files. (They relabeled it .DAT and .BIN is the .GOG)  This works just fine on my own compiled version of dosbox, but yours gets the error mentioned.

**Comment by telanus** [comment]
> imgmount d "whatever/CD.BIN" -t iso (the -fs iso is assumed normally but same thing either way)

There is your problem. it should be
`imgmount d "whatever/CD.cue" -t iso`

if you load the bin file you'll end up with an error, or without any music.

I run Tomb Raider 1 of a redbook cd and it still works using the followith to mount the CD.
`imgmount d /Games/Dos/tomb/TOMBENG.cue -t iso`

my cue file: https://paste.ubuntu.com/p/bHd8C6bGMv/

**Comment by JoshuaPettus** [comment]
Gah! Sorry typo, my fault,  I had meant "CD.CUE."  "CD.BIN" would work but of course there would be no music.  Certainly no error in that instance.

I'm wondering if it's the way that GOG uses the CUE sheet to point to external ogg files that is tripping up the runner's dosbox.   I'll send problem ones to this thread when i get a moment.

**Comment by JoshuaPettus** [comment]
Here is the CUE I mentioned
https://www.dropbox.com/s/iqp5ftrsxqled4v/shadow.conf?dl=0

Am I correct in assuming troubleshooting quirks in dosbox is not your main focus?  Even if there were a dosbox error, you couldn't fix it. 

Honestly next time when do you do the compile for the runner just make sure everything is turned on and I'm positive these issues will resolve themselves.

**Comment by stoz** [comment]
Hey, I'm having this same issue with Heroes of Might and Magic 2. (I get the same MSCDEX error)

The GOG version comes with a "homm2.gog" and a "homm2.ins" file, which I suspect are actually bin and cue files respectively. (The homm2.ins file is a plain text file that points to the homm2.gog binary and a collection of .ogg music tracks for audio)

It would be great if the DOSBox runner could be updated work with these kinds of files.

**Comment by Zeioth** [comment]
This issue would be a good oportunity to update dosbox's version.

**Comment by legluondunet** [comment]
@strycore  has updated Dosbox-ECE runner, could you test it and tell us if it resolved this issue?

**Comment by strycore** [comment]
I wish Dosbox could use SDL2 lol.

**Comment by JoshuaPettus** [comment]
Hi,  Thanks I finally had a chance to try it out.  It looks like the issues have been resolved. Thanks!

**Comment by strycore** [comment]
we plan shipping Dosbox staging soon
