### ISSUE TITLE
Lutris not running as regular user (on Gentoo), SEGFAULTs instead

### ISSUE THREAD

**Issue by nicentra** [lutris/lutris#2205]
**Describe the bug**

When running Lutris as non-root user it segmentation faults

**Expected behavior**

Lutris should launch

**Current behavior**

Lutris doesn't launch

**Steps to reproduce**

I launch Lutris

**Lutris debugging output**
While `lutris -d` doesn't work I used `strace -f lutris` to get a log available [here](https://gist.githubusercontent.com/nicentra/c1681cc8a7b9374425650c535c25c119/raw/35a2ccf962ebdf7d96fbf9fc2345552ab157afe6/lutris.log) and then there's this screenshot

![image](https://user-images.githubusercontent.com/20487548/59870744-60356400-9396-11e9-8f31-c30026ddae09.png)

**System information**
`lutris --submit-issue`  available [here](https://gist.githubusercontent.com/nicentra/77913a96c058f122b9dd4f10510677ad/raw/fe7c4d00a39aeb296243ebbb0f8c618cec07b22e/lutris%2520issue)

**Screenshots**

Screenshots have been supplied.

**Final Notes**
I honestly don't know if it's an issue with the gentoo ebuild, or if I installed the dependencies wrong. I am sure I hav everything though otherwise I wouldn't be able to run lutris as root :/

**Comment by henry-malinowski** [comment]
I can say this has been happening for me the last 3 days on Arch.

System information
`lutris --submit-issue` available [here](https://gist.github.com/henry-malinowski/9cdfb92d7e543efba437f8caf529903f)

**Comment by Breavyn** [comment]
Same issue on gentoo. Lutris opens fine as root, but segfaults as normal user.

**Comment by Breavyn** [comment]
@nicentra Not sure if this will help you, but I've been having segfaults trying to get ueberzug image previews working in my terminal. I checked out dmesg and saw that the lutris segfaults, and ueberzug segfaults were originating from the same place. Uninstalled pillow-simd (via pip) and now lutris opens without issue.

**Comment by nicentra** [comment]
@Breavyn Hey, that did fix the issue! So seems like the issue is with pillow-simd and lutris works just fine!

**Comment by henry-malinowski** [comment]
Fixed the issue for me on Arch as well. I had to

```
# pacman -R python-ueberzug
# pacman -S python-pillow
```

And then tell pacman to remove the conflicting `python-pillow-simd`.
