### ISSUE TITLE
Update WineSteam runner to use up-to-date setup file

### ISSUE THREAD

**Issue by Askannz** [lutris/lutris#2208]
**Describe the bug**

Installing the WineSteam runner does not work. Steam will start updating itself, and at a random point in the download, will abort with a connection error.

Tried multiple times, on 2 different Internet connections, at different times of day.

It's not strictly a Lutris bug because I can reproduce the problem by pulling the `SteamInstall.msi` file from http://lutris.net/files/runners/SteamInstall.msi and running it manually in a clean prefix. However, running the `SteamSetup.exe` installer from https://store.steampowered.com works.

**Expected behavior**

Being able to install the Winesteam runner.

**Current behavior**

See above.

**Steps to reproduce**

In Lutris : trying to install the Winesteam runner.

In Wine : simply running `wine msiexec /i SteamInstall.msi`

**Lutris debugging output**

~~https://pastebin.com/BRWfXHe4~~ EDIT : was missing stderr
https://pastebin.com/ecGfKejM

The relevant part :

```
Aborting HTTP request because we received a response with a content-length over 64M and we are not streaming[2019-06-21 20:21:38] Error: Download of package (resources_all) failed after 0 bytes (200).
[2019-06-21 20:21:38] Download Complete.
[2019-06-21 20:21:38] Error: Steam needs to be online to update.  Please confirm your network connection and try again.
[2019-06-21 20:21:40] Shutdown
```

**System information**

[lutris-issue-report.txt](https://github.com/lutris/lutris/files/3313921/lutris-issue-report.txt)

**Screenshots**

![lutris_bug](https://user-images.githubusercontent.com/9202863/59914781-6d1d8a80-945e-11e9-942d-b94505c1fb34.png)

**Comment by AccountOneOff** [comment]
I tried my hand at this locally but I'm not that good at coding. This looks like it'd be easy to fix.

We just need to update [#L637](https://github.com/lutris/lutris/blob/master/lutris/runners/wine.py#L637) in lutris/runners/wine.py to add a silent switch and change [#L27](https://github.com/lutris/lutris/runners/winesteam.py#L27), [#L278](https://github.com/lutris/lutris/runners/winesteam.py#L278), and [#L289-L295](https://github.com/lutris/lutris/runners/winesteam.py#L289-L295) in lutris/runners/winesteam.py.

As well as remove the old msi file and add the SteamSetup.exe to the site (or pull from Steam directly).
