### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by JourneyUnkn0wn** [lutris/lutris#2209]
I've just started getting a segmentation fault when trying to launch lutris.

Current behaviour:
When laucnhing Lutris i get the below.

INFO     2019-06-21 20:38:28,594 [application.do_command_line:225]:Running Lutris 0.5.2.1
INFO     2019-06-21 20:38:28,594 [startup.check_driver:54]:Using NVIDIA drivers 430.26 for x86_64
INFO     2019-06-21 20:38:28,595 [startup.check_driver:58]:GPU: GeForce GTX 1080
INFO     2019-06-21 20:38:28,595 [startup.check_driver:75]:GPU: 10DE:1B80 1462:3367 using nvidia drivers
INFO     2019-06-21 20:38:28,614 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-06-21 20:38:28,615 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
Segmentation fault (core dumped)

How to replicate:
launch lutris

Intended behaviour:
The program should launch without issue

Looking in the system log i see the below:
kernel: traps: lutris[2565] general protection fault ip:7f9058861cfe sp:7fff164721b8 error:0 in _imaging.cpython-37m-x86_64-linux-gnu.so[7f9058855000+3a000]

System Information Below
[https://gist.github.com/JourneyUnkn0wn/b3ad3db435279c257ecf4f7e892180e5](url)

**Comment by telans** [comment]
`lutris -d` log?

**Comment by Ultracoolguy** [comment]
I can confirm I have the same issue with the same version of both Lutris and NVIDIA drivers, although in my case it's a GTX 1060. 

Everything worked yesterday. There was something(maybe an update) that broke it.

[This is my information](https://paste.ubuntu.com/p/vqwrzsTNx4/)

**Comment by jakelaurieNZ** [comment]
Disable origin in-game, solved it for me

**Comment by JourneyUnkn0wn** [comment]
Issue resolved - i found the below forum post.

https://forums.lutris.net/t/segmentation-fault-on-startup/6195

After removing python-pillow-simd and installing python-pillow in its place resolved the issue.

They also recommended using the GNU debugger if this doesn't resolve your issue.

**Comment by JourneyUnkn0wn** [comment]
In addition to my closing comment. 

I needed python-pillow-simd for Ueberzug, the way i got around this was to use pip install ueberzug (which re-installs python-pillow-simd). Then i simply reinstalled python-pillow after and so far both Lutris and Ueberzug are working for me.

**Comment by Breavyn** [comment]
I see you must've missed #2205 . Removing pillow-simd bricked ueberzug for me. I had to revert https://github.com/seebye/ueberzug/commit/7a49f2ec75db95c325841c8eb6e8d643c9c92ab3 and install again to fix.
