### ISSUE TITLE
side panels consume too much space

### ISSUE THREAD

**Issue by foresto** [lutris/lutris#2210]
I have limited screen space, and like to be able to see other things on my screen while using Lutris. Unfortunately, the side panels are rather wide, so I have to choose between accepting them and devoting a huge amount of screen space to the Lutris window, or hiding them and being unable to see what game is currently running.

Some ideas that might help with this problem:
* Make the panels shrink to fit their contents. Right now my left panel's contents need less than a third of the panel's width, so that panel is mostly empty space.
* Make it possible to show/hide each panel independently. I don't care about the left-hand panel. I wish I could hide it without hiding the right-hand one.
* Automatically hid the left-hand panel when only one item in it is in use. All my Lutris games are Wine games. I don't need a panel devoted to selecting other runners that none of my games use.
* Show running game status in a status bar. This way I could hide both panels, reclaim all the wasted screen space, and still see a little text at the bottom of the window indicating whether a game is running.

**Comment by Faalagorn** [comment]
I have the same problem and I'd like to see especially dot number 2 being addressed, as I'd also love to hide just one panel.

**Comment by tannisroot** [comment]
Panels can now be hidden.
