### ISSUE TITLE
Game header artwork is blurry on high DPI ("Retina") displays

### ISSUE THREAD

**Issue by SilverWolf32** [lutris/lutris#2217]
**Description**

On high DPI displays, the game artwork in the library view is very blurry.

**Expected behavior**

The image is scaled properly and rendered at native resolution.

**Current behavior**

It appears the image is scaled to half the proper resolution, and then scaled back _up_ before being displayed.

**Steps to reproduce**

- Set up your desktop with a 2x scaling factor.
- Install a game.
- Look at the header image.

**Screenshots**

The Okami HD header image, downscaled to match the Lutris display size (this is how it should look):

![okami-header_368linear](https://user-images.githubusercontent.com/43831298/60368869-fb928e80-99bf-11e9-8fe4-73c3600a40e5.png)

The image as displayed by Lutris:

![Screenshot from 2019-06-28 14 26 50@2x_headercrop](https://user-images.githubusercontent.com/43831298/60368894-0a794100-99c0-11e9-90ba-4d71a9f01e1c.png)

And the image scaled down to half the proper resolution, then back up (using linear interpolation):

![okami-header_368downup](https://user-images.githubusercontent.com/43831298/60368955-2c72c380-99c0-11e9-9f38-19c1f312b20b.png)

**Comment by telanus** [comment]
I'm going to close this one as we already have a issue open about this here: https://github.com/lutris/lutris/issues/149

**Comment by SilverWolf32** [comment]
That's a different issue though, isn't it? It looks like that one covers making the artwork images be physically larger, while this is about increasing the resolution in the esisting space.

**Comment by telanus** [comment]
Both have the same underlying problem. The banners I make, I make at 875x345, but due to Lutris currently displaying banners at 186x69, it doesn't save all the information. If Lutris had larger banners this issue would never happen.

**Comment by SilverWolf32** [comment]
Ah! That makes sense, thanks.
