### ISSUE TITLE
GOG Game installation failed when selecting already downloaded GOG .exe file paired to another .bin file 

### ISSUE THREAD

**Issue by orbitalchicken** [lutris/lutris#2225]
Some GOG installer failed when I point to my already downloaded ".exe" file instead of entering my GOG.com credentials. Ex: prince of persia - sands of time. This happened when there is a second ".bin" file.

![prince-of-persia](https://user-images.githubusercontent.com/9101553/60695245-0f9e2a80-9eaf-11e9-85d3-fb12720a8fe3.png)

![prince-of-persia-failed](https://user-images.githubusercontent.com/9101553/60695336-5e4bc480-9eaf-11e9-9fef-7dc80987909d.png)

**Comment by tannisroot** [comment]
Can you run the installer again but this time with logging?

**Comment by strycore** [comment]
Tested with the exact same game, disconnected from GOG, not directly using the PGA cache. The game installs and launches fine.
