### ISSUE TITLE
Satisfactory crash after starting game from main menue

### ISSUE THREAD

**Issue by 3nigm4** [lutris/lutris#2228]
Kernel: 5.1.16-arch1-1-ARCH
OS: Arch Linux
Graphics Card: Nvidia Geforce 1080 GTX
Driver: Nvidia 430.26-8

I installed all the dependencies listed here https://github.com/lutris/lutris/wiki/Wine-Dependencies

I installed the epic launcher with the satisfactory script https://lutris.net/games/satisfactory/ and then installed satisfactory.

I can launch the game, but when I try to start the game from the menue. It loads a bit but then almost always freezes. When lutris is launched via terminal the freeze produces those lines.

```
wine: Unhandled exception 0x20474343 in thread 100 at address 0x7b4554a7 (thread 0100), starting debugger...
0155:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.

```

**Comment by AccountOneOff** [comment]
Thanks for the report. Unfortunately, we only accept reports for the Lutris client and its installers.

**Comment by Eknem** [comment]
@3nigm4 Did you get this working?I have the same problem.

**Comment by 3nigm4** [comment]
Sorry, I did not!
