### ISSUE TITLE
Problem with Lutris 0.5.2.2, Wine 4.12.1, Gallium Nine Standalone v0.4.0.294-release

### ISSUE THREAD

**Issue by mixified** [lutris/lutris#2229]
Hi, I have a problem, all my games can't run if I run it through Lutris after installing Gallium Nine Standalone. I have provided a detailed explanation below :

Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.3
KDE Frameworks Version: 5.59.0
Qt Version: 5.12.3
Kernel Version: 4.15.0-54-generic
OS Type: 64-bit
Processors: 4 × AMD A8-7410 APU with AMD Radeon R5 Graphics
Memory: 3,3 GiB of RAM

glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
Max core profile version: 4.5
Max compat profile version: 4.5
Max GLES1 profile version: 1.1
Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.0-devel (git-7e0fcea 2019-07-10 bionic-oibaf-ppa)
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.0-devel (git-7e0fcea 2019-07-10 bionic-oibaf-ppa)
OpenGL shading language version string: 4.50
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.0-devel (git-7e0fcea 2019-07-10 bionic-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix,

**My games: Call of Duty Modern Warfare 2, Command and Conquer 3 Kane's Wrath, Command and Conquer Red Alert 3 Uprising, Need For Speed Hot Pursuit.**

**When I installing Gallium Nine, the terminal output is**

000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000b:fixme:winediag:start_process Wine Staging 4.12.1 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
000f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0012:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0014:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0022:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
installing 32bit binaries to /home/nightprince/.wine/dosdevices/c:/windows/syswow64
002d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
installing 64bit binaries to /home/nightprince/.wine/dosdevices/c:/windows/system32
enabling gallium nine
002f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
done

**All my games can run if I run it through a terminal, file manager, or app drawer.
For example, I tried to run Command and Conquer 3 Kane's Wrath. this is terminal output**

wine cnc3ep1.exe
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000b:fixme:winediag:start_process Wine Staging 4.12.1 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
000f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0012:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0014:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0022:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
002b:fixme:imm:ImmDisableTextFrameService Stub
002b:fixme:thread:SetThreadIdealProcessor (0x110): stub
002b:fixme:thread:SetThreadIdealProcessor (0x168): stub
002d:fixme:thread:SetThreadIdealProcessor (0x16c): stub
fixme:d3d9nine:D3DPERF_GetStatus (void) : stub
Native Direct3D 9 v0.4.0.294-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
002b:fixme:thread:SetThreadIdealProcessor (0x17c): stub

**When I run it from Lutris, it appears "Directx Error, Please make sure you have Directx 9.0 or higher installed......."
Terminal output:**

lutris -d
INFO 2019-07-11 05:43:59,385 [application.do_command_line:225]:Running Lutris 0.5.2.2
INFO 2019-07-11 05:43:59,406 [startup.check_driver:60]:Using X.Org
INFO 2019-07-11 05:43:59,407 [startup.check_driver:65]:Running Mesa driver 19.2.0 on AMD KABINI (DRM 3.23.0, 4.15.0-54-generic, LLVM 8.0.1) (0x9851)
INFO 2019-07-11 05:43:59,408 [startup.check_driver:75]:GPU: 1002:9851 1043:1C8D using amdgpu drivers
WARNING: radv is not a conformant vulkan implementation, testing use only.
INFO 2019-07-11 05:43:59,975 [startup.check_vulkan:129]:Vulkan is supported
INFO 2019-07-11 05:43:59,977 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG 2019-07-11 05:44:02,471 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG 2019-07-11 05:44:10,170 [application.launch:339]:Launching Command and Conquer 3 Kane's Wrath (wine) (139694653187560)
DEBUG 2019-07-11 05:44:10,196 [game.play:269]:Prelaunching <lutris.runners.wine.wine object at 0x7f0d322d0d68>
WARNING 2019-07-11 05:44:10,199 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,200 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,278 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,465 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,465 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
INFO 2019-07-11 05:44:10,487 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/system32/d3d11
INFO 2019-07-11 05:44:10,489 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/system32/d3d10core
INFO 2019-07-11 05:44:10,490 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/system32/d3d10_1
INFO 2019-07-11 05:44:10,490 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/system32/d3d10
INFO 2019-07-11 05:44:10,518 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/system32/d3d9
INFO 2019-07-11 05:44:10,548 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/syswow64/d3d11
INFO 2019-07-11 05:44:10,549 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/syswow64/d3d10core
INFO 2019-07-11 05:44:10,550 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/syswow64/d3d10_1
INFO 2019-07-11 05:44:10,550 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/syswow64/d3d10
INFO 2019-07-11 05:44:10,551 [dxvk.disable_dxvk_dll:146]:Removing DXVK dll /home/nightprince/.wine/drive_c/windows/syswow64/d3d9
DEBUG 2019-07-11 05:44:10,552 [display._get_vidmodes:15]:Retrieving video modes from XrandR
WARNING 2019-07-11 05:44:10,703 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,704 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
WARNING 2019-07-11 05:44:10,705 [wine.prefix_path:481]:Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
DEBUG 2019-07-11 05:44:10,705 [game.configure_game:305]:Launching Command and Conquer 3 Kane's Wrath: {'env': {'STEAM_RUNTIME': '/home/nightprince/.local/share/lutris/runtime/steam', 'LD_LIBRARY_PATH': '/usr/lib:/lib:/lib64:/lib32:/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/lib32:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib:/home/nightprince/.local/share/lutris/runtime/lib64:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH', 'WINEDEBUG': '-all', 'WINEARCH': 'win64', 'WINE': '/usr/bin/wine', 'WINEPREFIX': '/home/nightprince/.wine', 'WINEESYNC': '0'}, 'command': ['/usr/bin/wine', "/media/nightprince/Nightcrawler/Applications/Games/Command and Conquer 3 Kane's Wrath/cnc3ep1.exe"]}
DEBUG 2019-07-11 05:44:10,706 [game.configure_game:306]:Game info: {
"env": {
"STEAM_RUNTIME": "/home/nightprince/.local/share/lutris/runtime/steam",
"LD_LIBRARY_PATH": "/usr/lib:/lib:/lib64:/lib32:/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/lib32:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib:/home/nightprince/.local/share/lutris/runtime/lib64:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH",
"WINEDEBUG": "-all",
"WINEARCH": "win64",
"WINE": "/usr/bin/wine",
"WINEPREFIX": "/home/nightprince/.wine",
"WINEESYNC": "0"
},
"command": [
"/usr/bin/wine",
"/media/nightprince/Nightcrawler/Applications/Games/Command and Conquer 3 Kane's Wrath/cnc3ep1.exe"
]
}
DEBUG 2019-07-11 05:44:10,708 [command.start:111]:Running /usr/bin/lutris-wrapper 0 0 /usr/bin/wine /media/nightprince/Nightcrawler/Applications/Games/Command and Conquer 3 Kane's Wrath/cnc3ep1.exe
DEBUG 2019-07-11 05:44:10,708 [command.start:113]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG 2019-07-11 05:44:10,708 [command.start:113]:ENV: STEAM_RUNTIME="/home/nightprince/.local/share/lutris/runtime/steam"
DEBUG 2019-07-11 05:44:10,709 [command.start:113]:ENV: LD_LIBRARY_PATH="/usr/lib:/lib:/lib64:/lib32:/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/lib32:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/lib:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/i386/usr/lib:/home/nightprince/.local/share/lutris/runtime/lib64:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/lib:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/nightprince/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG 2019-07-11 05:44:10,709 [command.start:113]:ENV: WINEDEBUG="-all"
DEBUG 2019-07-11 05:44:10,710 [command.start:113]:ENV: WINEARCH="win64"
DEBUG 2019-07-11 05:44:10,710 [command.start:113]:ENV: WINE="/usr/bin/wine"
DEBUG 2019-07-11 05:44:10,710 [command.start:113]:ENV: WINEPREFIX="/home/nightprince/.wine"
DEBUG 2019-07-11 05:44:10,711 [command.start:113]:ENV: WINEESYNC="0"
DEBUG 2019-07-11 05:44:10,711 [command.start:113]:ENV: PYTHONPATH="/usr/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages"
DEBUG 2019-07-11 05:44:10,731 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7f0d322efdd8>> to 2248
Running /usr/bin/wine /media/nightprince/Nightcrawler/Applications/Games/Command and Conquer 3 Kane's Wrath/cnc3ep1.exe
Waiting on children
All children gone
Exit with returncode 0

**After running through Lutris, all my games cannot run even using a terminal, file manager, or application drawer**

**Comment by Saroufim** [comment]
Can confirm the same issue.

**Comment by sonicpp** [comment]
Hello,
did you install and set Gallium Nine in your prefix manually or via Lutris Runner options?

**Comment by strycore** [comment]
This should be fixed with #2904
