### ISSUE TITLE
Event hooks

### ISSUE THREAD

**Issue by RodrigoLeiteF** [lutris/lutris#2231]
I have a really bad habit of writing bash scripts for everything, and thus would like to integrate them with Lutris. It would be nice to have hooks we could use to run commands upon certain events, for example run an xrandr command after a certain game is closed or some other command when a game is launching or done launching.

**Comment by Medath** [comment]
This should be doable in the system options (after ticking the "Show advanced options" box) by entering the path to your script in the "Pre-launch command" or "Post-exit command" options

**Comment by RodrigoLeiteF** [comment]
Oh, that's true. I never noticed those options there. Thanks!
