### ISSUE TITLE
Problem while running Lutris

### ISSUE THREAD

**Issue by RustemB** [lutris/lutris#2232]
```
2019-07-14 19:52:55,663: Couldn't find a terminal emulator.
2019-07-14 19:52:55,988: Running Lutris 0.5.2.2
2019-07-14 19:52:55,988: Using X.Org
2019-07-14 19:52:55,989: Running Mesa driver 19.1.2 on AMD CARRIZO (DRM 3.32.0, 5.2.0-arch2-1-ARCH, LLVM 8.0.0) (0x9874)
2019-07-14 19:52:55,989: GPU: 1002:6900 103C:81FA using amdgpu drivers
2019-07-14 19:52:55,989: GPU: 1002:9874 103C:81FA using amdgpu drivers
2019-07-14 19:52:56,098: Vulkan is supported
2019-07-14 19:52:56,100: Updating DXVK versions
[1]    25411 segmentation fault (core dumped)  lutris
```
I don't know which terminal emulator it want, but I'm using Alacritty

**Comment by matoro** [comment]
@RustemB Could you get a traceback please?  Install gdb and run:
```
gdb --args /usr/bin/python /usr/bin/lutris
```
Then type:
```
r
```
When it crashes, run:
```
bt
```
and copy the topmost output.

**Comment by RustemB** [comment]
https://pastebin.com/9LPgxZcE

**Comment by matoro** [comment]
This looks like the same issues I helped somebody on discord with.  Do you happen to have a fork of python-pillow installed, perhaps as a dependency of another package?  If not what version of python-pillow are you on?

**Comment by RustemB** [comment]
```
python-pillow-simd 1:6.0.0.post0-1
python2-pillow 6.1.0-1
```

**Comment by matoro** [comment]
@RustemB Yep, it's as I thought.  The AUR package `python-pillow-simd` seems to have a broken implementation of `ImagingResampleHorizontalConvolution8u4x()` which Lutris requires.  Replace it with `python-pillow` from the official Arch repo.

@strycore I have seen this issue come up a lot with the `python-pillow-simd` AUR package.  Perhaps the maintainer of the official Arch package could add an explicit blacklist to the dependencies so that only vanilla Pillow can be used?

**Comment by strycore** [comment]
@matoro I'll make Pillow optional in the next release because it's not used that much

**Comment by strycore** [comment]
Pillow is no longer needed codewise (see https://github.com/lutris/lutris/commit/3f7bf74008497a59b358e3b848a1a3c385556f06 ) but that won't solve the issue with that particular fork of PIL. Please see if you can find a solution with the Arch maintainers.

**Comment by RustemB** [comment]
Yay, that's help me! But `python-pillow-simd` required by `python-ueberzug`
So, I don't use ueberzug at now
