### ISSUE TITLE
Error while launching MaxPayne 1 in lutris

### ISSUE THREAD

**Issue by Kamil2412** [lutris/lutris#2237]
while i am runing the game through lutris, it is giving these errors

┌─[✗]─[genius@parrot]─[~/Documents/Games/Max_Payne_1_Game]
└──╼ $LC_ALL=C lutris
Reading profile /etc/firejail/wine.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 18974, child pid 18975
Child process initialized in 103.85 ms

Parent is shutting down, bye...
2019-07-18 13:02:21,668: /home/genius/.PlayOnLinux/wine/linux-amd64/bin/wine
2019-07-18 13:02:21,937: Running Lutris 0.5.1.3
2019-07-18 13:02:21,938: Using Intel Open Source Technology Center
2019-07-18 13:02:21,938: Running Mesa driver 18.3.6 on Mesa DRI Intel(R) Ironlake Mobile  (0x46)
2019-07-18 13:02:21,939: GPU: 8086:0046 103C:3674 using i915 drivers
2019-07-18 13:02:22,013: Vulkan is not available or your system isn't Vulkan capable
2019-07-18 13:02:22,015: Updating DXVK versions
2019-07-18 13:02:22,610: Connected to lutris.net as kamil2412
Reading profile /etc/firejail/wine.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Parent pid 18985, child pid 18986
Child process initialized in 98.06 ms

Parent is shutting down, bye...
2019-07-18 13:02:29,133: Changing resolution to 1366x768
Warning:          Key <OUTP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
Running /home/genius/.local/share/lutris/runners/wine/ge-protonified-nofshack-4.9-x86_64/bin/wine /home/genius/Documents/Games/Max_Payne_1_Game/MaxPayne.exe

(wine:19003): GStreamer-CRITICAL **: 13:02:43.365: gst_pad_unlink: assertion 'GST_IS_PAD (srcpad)' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.366: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.366: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.366: gst_pad_unlink: assertion 'GST_IS_PAD (srcpad)' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.366: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.366: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_pad_unlink: assertion 'GST_IS_PAD (srcpad)' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_pad_unlink: assertion 'GST_IS_PAD (srcpad)' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_object_unref: assertion 'object != NULL' failed

(wine:19003): GStreamer-CRITICAL **: 13:02:43.378: gst_object_unref: assertion 'object != NULL' failed
wine: Unhandled page fault on write access to 0x28203d08 at address 0x7ff7e764 (thread 0009), starting debugger...
0047:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.

and game screen is crashing after 2 secondsthen it is saying Wine issue

Unhandled exception: page fault on write access to 0x28203d08 in 32-bit code (0x7b453c5c).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b453c5c ESP:003495b4 EBP:00349628 EFLAGS:00200216(   - --  I   -A-P- )
 EAX:003495cc EBX:00000000 ECX:00000008 EDX:00349650
 ESI:0034fdec EDI:00805ee0
Stack dump:
0x003495b4:  00000040 0034975c f7dd6497 00349718
0x003495c4:  00000000 003495d8 c0000005 00000000
0x003495d4:  00000000 7ff7e764 00000002 00000001
0x003495e4:  28203d08 0034f420 7ffa8b10 ffffffff
0x003495f4:  005737cf 00000002 00000004 00000000
0x00349604:  00000004 00000071 00000000 00573404
Backtrace:
=>0 0x7b453c5c in kernel32 (+0x23c5c) (0x00349628)
  1 0x7e912961 in msvcrt (+0x12960) (0x00349668)
  2 0x0040b6ea EntryPoint+0xffffffff() in maxpayne (0x0034fdf8)
  3 0x0040b73e EntryPoint+0xffffffff() in maxpayne (0x0034fec0)
  4 0x7b482c69 in kernel32 (+0x52c68) (0x0034fee8)
  5 0x7b485231 in kernel32 (+0x55230) (0x0034ffd8)
  6 0x7b482c7a in kernel32 (+0x52c79) (0x0034ffec)
0x7b453c5c: addl	$12,%esp
Modules:
Module	Address			Debug info	Name (43 modules)
PE	  400000-  8c956e	Export          maxpayne
PE	10000000-10067000	Deferred        rlmfc
PE	5f400000-5f4f2000	Deferred        mfc42
PE	780a0000-780b2000	Deferred        msvcirt
PE	780c0000-78121000	Deferred        msvcp60
PE	7a840000-7a849000	Deferred        opengl32
PE	7aa70000-7aa75000	Deferred        winegstreamer
PE	7abd0000-7abd4000	Deferred        winealsa
PE	7b430000-7b602000	Export          kernel32
PE	7b860000-7b864000	Deferred        midimap
PE	7b880000-7b884000	Deferred        msacm32
PE	7bc30000-7bc47000	Deferred        ntdll
PE	7bf50000-7bf54000	Deferred        winepulse
PE	7bf90000-7bf95000	Deferred        mmdevapi
PE	7bfc0000-7bfc5000	Deferred        msdmo
PE	7bfe0000-7bfe5000	Deferred        devenum
PE	7c120000-7c124000	Deferred        avicap32
PE	7c170000-7c17e000	Deferred        oleaut32
PE	7c290000-7c29d000	Deferred        msvfw32
PE	7c2c0000-7c2ca000	Deferred        msacm32
PE	7c320000-7c32c000	Deferred        quartz
PE	7db50000-7db5a000	Deferred        wined3d
PE	7dcb0000-7dcb5000	Deferred        d3d8
PE	7dce0000-7dce6000	Deferred        uxtheme
PE	7e240000-7e246000	Deferred        winex11
PE	7e2e0000-7e2e6000	Deferred        imm32
PE	7e310000-7e314000	Deferred        usp10
PE	7e380000-7e3d6000	Deferred        comctl32
PE	7e600000-7e60c000	Deferred        dinput
PE	7e680000-7e68d000	Deferred        rpcrt4
PE	7e740000-7e76d000	Deferred        ole32
PE	7e890000-7e895000	Deferred        dsound
PE	7e900000-7e915000	Export          msvcrt
PE	7e9b0000-7e9b5000	Deferred        version
PE	7e9f0000-7e9fd000	Deferred        advapi32
PE	7ea90000-7ea9e000	Deferred        gdi32
PE	7ebf0000-7ece4000	Deferred        user32
PE	7ee10000-7ee90000	Deferred        winmm
PE	7eee0000-7eee3000	Deferred        wow64cpu
PE	7fe80000-7ff14000	Deferred        e2_d3d8_driver_mfc
PE	7ff20000-7ff38000	Deferred        sndmfc
PE	7ff40000-7ff58000	Deferred        grphmfc
PE	7ff60000-7ffce000	Deferred        e2mfc
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\genius\Documents\Games\Max_Payne_1_Game\MaxPayne.exe
	[Z:\home\genius\Documents\Games\Max_Payne_1_Game\MaxPayne.exe]
	0000002f   15
	0000002d    0
	0000002c    0
	0000002b    0
	0000002a    0
	00000029    0
	00000009    0 <==
0000000e services.exe
	00000022    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	0000001f    0
	0000001c    0
	0000001b    0
	00000019    0
0000001d explorer.exe
	00000028    0
	00000027    0
	00000026    0
	0000001e    0
00000020 winedevice.exe
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000046 explorer.exe
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
System information:
    Wine build: wine-4.9 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.19.37-parrot1-amd64

Any solution for it please.....

**Comment by AccountOneOff** [comment]
Thanks for the report. Unfortunately, we only accept reports for the Lutris client and its installers.
