### ISSUE TITLE
Error re-generating winesteam

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#2238]
**Describe the bug**
Lutris fails to create the runner Wine Steam.

**Steps to reproduce**

- Delete the content of ~/.local/share/lutris/runners/winesteam/
- Open lutris and click the play button on the left bar > Wine Steam.

**Screenshots**
![tmp](https://user-images.githubusercontent.com/3357792/61495594-b4ddf600-a9b9-11e9-954f-d0d0162d96f9.png)
The error.

![tmp2](https://user-images.githubusercontent.com/3357792/61495639-cf17d400-a9b9-11e9-9324-fc768d8f58e0.png)
The same error, but with "Lutris -d"

**Workaround**

* Create an empty wine prefix with the command 

      WINEPREFIX="/a/folder/of/your/choice/" winecfg

* Use winetricks to install steam on the prefix you just created.
* Copy the content of the generated directory to ~/.local/share/lutris/runners/winesteam/
* Open lutris and click the play button on the left bar > Wine Steam.

**Comment by Zeioth** [comment]
I re-tested this in Lutris-git. Seems to reinstall WineSteam correctly now.

Border cases (optional):

- The WineSteam created doesn't show the store (black screen)

**Comment by strycore** [comment]
I was to reproduce the black screen error and resolved it by not disabling steamwebhelper during the prefix creation. 
However, the steam store and game library are a glitchy mess with the new UI. The Steam installer may need some patching, if it's possible to get Steam to work properly at all.
