### ISSUE TITLE
[Suggestion] Distribute Lutris on Steam

### ISSUE THREAD

**Issue by mindinsomnia** [lutris/lutris#2242]
Hey there.

Just a suggestion, how does the idea of distributing Lutris via Steam (in addition to the current methods) sound? Anyone who has Steam installed could launch Steam, search for Lutris, click install, boom it's done. Most gamers will have Steam installed anyway, so it could be a handy way of obtaining Lutris. There's already a decent library of software on Steam, so it would be in good company, and there's an unspoken benefit: Having Lutris on Steam would be an excellent promotion for Lutris, and make it much more visible to gamers on Steam.

**Comment by strycore** [comment]
Sadly, this is not possible since lutris manages steam and not the other way around. And because of that, Lutris wouldn't be accepted during the app submission process on Steam itself.
