### ISSUE TITLE
Application menu shortcut won't  work or dissapear after deleting game

### ISSUE THREAD

**Issue by Tdx3gamer** [lutris/lutris#2243]
I installed magic the gathering arena and it played and worked fine, but then I made the mistake of creating an application menu shortcut. The shortcut did not work so I thought I could just delete the game and it would go away... it didn't and I don't know how to remove it. I am using POP!_OS 19.04 please help.

**Comment by dino8890** [comment]
> I installed magic the gathering arena and it played and worked fine, but then I made the mistake of creating an application menu shortcut. The shortcut did not work so I thought I could just delete the game and it would go away... it didn't and I don't know how to remove it. I am using POP!_OS 19.04 please help.

You can install alacarte menu editor for GNOME using your package manager and remove application menu shortcut manually.

`sudo apt install alacarte`

If that doesn't work, try looking for the icons in :

- /usr/share/icons
- /home/\<username\>/.local/share/icons
- /usr/share/applications
- /home/\<username\>/.local/share/applications

For example, I had residual .desktop files in the game directory in .local/share/application/wine/Programs/. By removing them and restarting the gnome shell, the applications menu items disappeared.

**Comment by strycore** [comment]
I can't reproduce the issue. I verified that shortcuts are properly deleted when a game is uninstalled from lutris and they are.

I need a reliable way to reproduce the issue in order to fix it. Please re-open if that can be provided.
