### ISSUE TITLE
[Flatpak] 'libgamemodeauto.so' from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by Bryophyllum** [lutris/lutris#2248]
**Describe the bug**

The full path of libgamemodeauto.so is hard-coded. For this reason, [Feral's Gamemode does not work when using Flatpak to install Lutris](https://github.com/flathub/net.lutris.Lutris/issues/22#issuecomment-515764890).

**Expected behavior**

The linker should find the library, and provide Lutris with the correct path. 

**Current behavior**

Feral's Gamemode does not work because the library cannot be found in the hard-coded directory.

**Steps to reproduce**

- Install Lutris from flathub-beta via Flatpak
- Run it from a terminal, and enable Feral's Gamemode
- Start a game, and pay attention to the terminal output

**Lutris debugging output**

https://gist.github.com/Bryophyllum/e1bb8ec09449b1047173d9c674597ae2

**Comment by gasinvein** [comment]
My suggestion is to remove full path and use just `libgamemodeauto.so` here
https://github.com/lutris/lutris/blob/b908769a96e6dd2c00b3b1e439895dd61751eb30/lutris/game.py#L471
The dynamic loader should handle it and pick the library of correct architecture it's present in system library search paths. This may even fix #1304.
