### ISSUE TITLE
[Suggestion] Allow for larger game banner scale and Steam banners

### ISSUE THREAD

**Issue by pikasalt** [lutris/lutris#2249]
A larger banner size and the ability to use banners from sites like [SteamGridDB](https://www.steamgriddb.com/) and [Jinx's SGVI](https://steam.cryotank.net/) would go a long ways in making lutris look a bit more pretty.
Gamehub does this with outstanding results
![image](https://user-images.githubusercontent.com/52518103/62011179-8e972380-b13a-11e9-8fb0-71f20bed9356.png)
Compared to lutris:
![image](https://user-images.githubusercontent.com/52518103/62011212-d5851900-b13a-11e9-8b3c-87b09b8faffe.png)

**Comment by telanus** [comment]
I'm going to close this one as we already have a issue open about this here: https://github.com/lutris/lutris/issues/149
