### ISSUE TITLE
Lutrist RPG Maker MV games Unplayable

### ISSUE THREAD

**Issue by Gitlab1111** [lutris/lutris#2250]
System info:
Feren OS 
Cinnemon Version: 4.0.10
Linux Kernel   5.0.0-19 generic
Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
RAM: 4 gb

I have Wine installed and even when using a combination of Wine versions within Lutris it still does not run any games made with RPG Maker MV at all.

Will Lutris have support for these games. All that you get is a window of the game with a black screen only showing Loading which runs infinitely even refreshing it does nothing to fix it.

**Comment by telanus** [comment]
@Gitlab1111 does it work under wine when not using Lutris?

**Comment by Gitlab1111** [comment]
I have tried running it with Wine and even with different Windows OS versions such as xp 2003, 2008, Vista, 7 ,8,1 and Windows 10. No luck even when not using Lutris.  Still results in black screen with Loading.

**Comment by telanus** [comment]
Think you would need to create a bug report with the Wine team. If it doesn't work outside Lutris, it's not a Lutris bug

**Comment by Gitlab1111** [comment]
If there is a addon for Dosbox and other software to run games can't there be one for RPG Maker games?

**Comment by lavilao** [comment]
download the web runner from lutris and use the index.html file from the www folder, it worked for some games, if the file dows not exis just copy it from another rpg maker mv game.
