### ISSUE TITLE
[Feature Request] Include All Runner Dependencies in Lutris Runtime

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#2252]
It would be nice if Lutris included all the necessary libraries for its runners in the Lutris runtime. This would solve certain cases where runners fail to start due to missing libraries (such as Citra needing libQt5OpenGL.so.5). This would also make it easier to package Lutris for bleeding-edge desktops such as Fedora Silverblue. Additionally, it would prevent runners from breaking due to mismatched library versions or missing dependencies after a system upgrade.

**Comment by Saroufim** [comment]
Additionally, it would be great if Lutris provided its own additional libraries such as libstrangle as these libraries might not be available on all systems as well (Fedora Workstation for instance).

**Comment by strycore** [comment]
It would be nice but sadly, it's not possible.
