### ISSUE TITLE
Wiki page modify request

### ISSUE THREAD

**Issue by marioortizmanero** [lutris/lutris#2259]
The current page in the wiki on Wine is https://github.com/lutris/lutris/wiki/Wine

1. The last formatting of the "Arch/Antergos/Manjaro/Other Arch derivatives" instructions is incorrect and looks like a quote rather than a command. 

2. Shouldn't `pacman -S` be used instead of `pacman -Sy`?

3. Could you add a disclaimer indicating why such a huge amount of libraries is needed? 

Thanks

**Comment by tannisroot** [comment]
1. That's intentional as it's easier to view and copy.
2. Fixed.
3. Done.
