### ISSUE TITLE
Star Citizen 3.6.1 no longer is launching.

### ISSUE THREAD

**Issue by Ebojager** [lutris/lutris#2264]
**Describe the bug**

When launching Star Citizen from Lutris after the recent 3.6.1 update, the game crashes during the credits screen, where it just stays black.

If I switch to the System Wine version 4.12.1, it launches but performance is bad probably cause no esync. It also crashes using this version when changing graphic settings that require a resolution change or confirmation. And crashes after hitting yes to confirm.

I suspect it's because they changed the launcher.

**Expected behavior**
Game launches like it did on 3.6
 
Please describe the behavior you are expecting.

**Current behavior**
Won't continue past credits screen

What is the current behavior?
Won't continue past credits screen

**Steps to reproduce**

- Launch game from lutris 
-
-

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by tannisroot** [comment]
> performance is bad probably cause no esync
lutris-4.12.1 should support Esync
> It also crashes using this version when changing graphic settings that require a resolution change or confirmation
Try deleting contents of `~/.local/share/lutris/runtime/dxvk`.

**Comment by Ebojager** [comment]
I will try that, I downloaded the Lutris version of 4.12.1, thank you. I'll reply here afterwards.

**Comment by Ebojager** [comment]
> > performance is bad probably cause no esync
> > lutris-4.12.1 should support Esync
> > It also crashes using this version when changing graphic settings that require a resolution change or confirmation
> > Try deleting contents of `~/.local/share/lutris/runtime/dxvk`.

Iam not suppose to have Wine Mono installed am I?

**Comment by tannisroot** [comment]
It's normal to have it installed and it won't matter that much with Star Citizen if you don't install it.

**Comment by tannisroot** [comment]
User didn't reply in quite a while so closing.
