### ISSUE TITLE
Feature-request: Allow editing and forking scripts in Lutris-client as well 

### ISSUE THREAD

**Issue by deriv** [lutris/lutris#2265]
When browsing Lutris.net selection, for the moment one can only select install and view the script before installer proceeds, yet time to time would be really handy to make some changes to pre-existing script, at least locally. So it comes down to, could user edit about to installed script in Lutris, or at least download the script itself, but not install and allow user to edit it manually, all this in Lutris-client?

**Comment by strycore** [comment]
This feature will be tracked in #1000
