### ISSUE TITLE
Suggestion: Extending tabbed UI

### ISSUE THREAD

**Issue by deriv** [lutris/lutris#2266]
While this is related to tiled wm i3 issue: https://github.com/lutris/lutris/issues/1854 and the undeniable truth being that Lutris can't satisfy every whim of every wm and de - thus could Lutris try a different approach, for example like a fully tabbed interface / integrating the extra windows into pre-existing main interface which would allow presenting everything in a single window? Naturally this would be an optional layout.

![lutris-integrated-gui-sketch-script-options](https://user-images.githubusercontent.com/19568048/62825543-40603680-bbb6-11e9-8054-06bb1f3e4785.png)

If not displaying larger entities like installing process and configuration in the main window itself, maybe a temporary right column width increasement which one could hide back to normal width?

![lutris-integrated-gui-sketch-right-column-expanded-installing](https://user-images.githubusercontent.com/19568048/62825559-8917ef80-bbb6-11e9-9905-40a6bd204652.png)

![lutris-integrated-gui-sketch-right-column-expanded-configure](https://user-images.githubusercontent.com/19568048/62825562-91702a80-bbb6-11e9-80e7-80e6b51d77ca.png)

**Comment by tannisroot** [comment]
Seems super clunky to me tbh.
