### ISSUE TITLE
Betnesda launcher starts but doesn't installs any games

### ISSUE THREAD

**Issue by AdamFreemen** [lutris/lutris#2268]
Installed Betnesda launcher by script in Lutris.net. Betnesda launcher starts but doesn't installs any games. Seems like program doesn't have connection with Bethesda servers... although my Beshesda account is logged in.

**Comment by tannisroot** [comment]
This sounds like a configuration issue. Join our Discord server, we might be able to help you with that.
If you want a quick response there, mention me.

**Comment by AdamFreemen** [comment]
Александр, какой у тебя там ник? Да и вообще, закрывать трэд, который предназначен для всех, как-то... Чат - это туфта, похожая на бегущую строку, которую раз прочитал и забыл. Пиши сюда, раз тебе без разницы, где решать проблему...12.08.2019, 22:48, "Alexandr Oleynikov" <notifications@github.com>:This sounds like a configuration issue. Join our Discord server, we might be able to help you with that.
If you want a quick response there, mention me.

**Comment by tannisroot** [comment]
@AdamFreemen the nickname is the same as here, Tannis Root.
The reason I closed it is because this bugtracker is for the client, cluttering it with tech support regarding runners would turn it into a huge mess.
