### ISSUE TITLE
MESS runner : New game dialog tabs missing

### ISSUE THREAD

**Issue by appoloin** [lutris/lutris#2269]
The new game dialog for the mess runner has only one tab, there's no way to set rom location.
  
![Screenshot from 2019-08-11 10-38-03](https://user-images.githubusercontent.com/34371675/62859277-920edb00-bcf4-11e9-8193-98dfa89de0bb.png)

I also tried the attached script, started lutris from the terminal with  the "i" parameter.   The script installed but the configure dialog wouldn't open.

[Oh Mummy!!.txt](https://github.com/lutris/lutris/files/3491903/Oh.Mummy.txt)

With  lutris opened from  the terminal I tried to create a new mess game, this was the terminal output
Traceback (most recent call last):
File “/usr/lib/python3/dist-packages/lutris/gui/config/common.py”, line 400, in on_runner_changed
self._switch_runner(widget)
File “/usr/lib/python3/dist-packages/lutris/gui/config/common.py”, line 414, in _switch_runner
self._rebuild_tabs()
File “/usr/lib/python3/dist-packages/lutris/gui/config/common.py”, line 421, in _rebuild_tabs
self._build_runner_tab(“game”)
File “/usr/lib/python3/dist-packages/lutris/gui/config/common.py”, line 320, in _build_runner_tab
self.runner_box = RunnerBox(self.lutris_config, self.game)
File “/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py”, line 635, in init
self.generate_widgets(“runner”)
File “/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py”, line 118, in generate_widgets
helptext = helptext + “\n\n” if helptext else “”
TypeError: can only concatenate tuple (not “str”) to tuple

**Comment by strycore** [comment]
Fixed the type of help text in Mess runner
