### ISSUE TITLE
Error  building on Debian 8 / SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [lutris/lutris#227]
Error building on Debian 8 with `dpkg-buildpackage -rfakeroot -us -uc` Seems the sdl library isn't spec'd with a symbols file to that binary. How is your team building packages? I am building for SteamOS mainly, and yes I am aware you provide deb packages on your site. I wish to build this package form the master tree though. I don't want to use a hacky LD_LIBRARY path or override_dh_shlibdeps if I can help it.

error:
```
dh_shlibdeps -plutris    
dpkg-shlibdeps: error: couldn't find library libSDL2-2.0.so.0 needed by debian/lutris/usr/share/lutris/lib/koku-xinput-wine.so (ELF format: 'elf32-i386'; RPATH: '')
dpkg-shlibdeps: error: cannot continue due to the error above
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/lutris.substvars debian/lutris/usr/share/lutris/lib/koku-xinput-wine.so returned exit code 2
/usr/share/cdbs/1/rules/debhelper.mk:277: recipe for target 'binary-predeb-IMPL/lutris' failed
make: *** [binary-predeb-IMPL/lutris] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

library check:
```
desktop@steamos:~/build-lutris-temp/lutris$ ldd share/lutris/lib/koku-xinput-wine.so 
        linux-gate.so.1 (0xf7736000)
        libSDL2-2.0.so.0 => not found
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7614000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf75f6000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7484000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf743f000)
        /lib/ld-linux.so.2 (0x565f8000)
```

**Comment by ProfessorKaos64** [comment]
Update, libsdl2-2.0-0:i386 was a missing build dep in my case. Can this be added to the control file? If not, can you please tell me host best to build? Thank you.

**Comment by strycore** [comment]
Yes, you can add this to the BuildDeps and send a pull request. I didn't realize that the pacakging process would check for symbols in a binary library we ship. We build our debian package on openSUSE Build Service and it never complain about that, but I guess it's just the build options that are different.

**Comment by ProfessorKaos64** [comment]
understandable, will do @strycore , thank you.

**Comment by strycore** [comment]
I had to remove the build dependency on libsdl2 as the openSUSE Build Service does not support multiarch repositories. If this continues to be a problem, we should probably move the shared library to our runtime, that would solve the problem permanently.

**Comment by ProfessorKaos64** [comment]
OK. I'll just put a note in my build script regarding this for now, or inject a new control file / wed replace at build time. Thank you for the consideration. 

On December 29, 2015 10:28:22 PM EST, Mathieu Comandon <notifications@github.com> wrote:
>I had to remove the build dependency on libsdl2 as the openSUSE Build
>Service does not support multiarch repositories. If this continues to
>be a problem, we should probably move the shared library to our
>runtime, that would solve the problem permanently.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lutris/lutris/issues/227#issuecomment-167930479

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
