### ISSUE TITLE
fsync option

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2270]
Similar to esync.
https://github.com/Tk-Glitch/PKGBUILDS/commit/91444341b95e76bd098e29b17c638252ec3048a5
https://github.com/Tk-Glitch/PKGBUILDS/commit/767e955b85e7fa16371b8729a4b932039237d60d

**Comment by Medath** [comment]
The 4.13 build has fsync support, it can be enabled by setting WINEFSYNC=1. The only thing that's left is to figure out if the users kernel supports fsync

**Comment by strycore** [comment]
I just enabled Fsync when Esync is on.
I have no idea what Fsync is or does or if it's even worthwhile to ship it so I wrote the laziest implementation I could write.

**Comment by Ases** [comment]
> I just enabled Fsync when Esync is on.
> I have no idea what Fsync is or does or if it's even worthwhile to ship it so I wrote the laziest implementation I could write.
You can get more info here: 
https://steamcommunity.com/games/221410/announcements/detail/2957094910196249305
