### ISSUE TITLE
[Wiki] Ubuntu WineHQ-Staging 

### ISSUE THREAD

**Issue by modzilla99** [lutris/lutris#2276]
To install wine-staging you have to add a opensuse repository:
For disco:
>  curl -L https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_19.04/Release.key | apt-key add -
> apt-add-repository "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_19.04/ ./"

For bionic:
> curl -L https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | apt-key add -
> apt-add-repository "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./"

**Comment by richard378** [comment]
It is covered in this forum and is a known issue on WineHQ on installing on Ubuntu page.  I needed it to update my current Wine-Staging install https://forum.winehq.org/viewtopic.php?f=8&t=32192

**Comment by strycore** [comment]
It is not needed to install Wine Staging in order to play Wine games, our builds only require a recent version of Wine to be installed on the system to satisfy the dependencies.

If our documentation state somewhere that Wine Staging is needed, please let us know so we can update that information.
