### ISSUE TITLE
Lutris hang when opening the wine version manager

### ISSUE THREAD

**Issue by TheFrenchGhosty** [lutris/lutris#2286]
When clicking "Manage Versions" for Wine Lutris will hang for multiples seconds to multiples minutes for no reason.

See this gif : 
![lutris](https://user-images.githubusercontent.com/47571719/63453264-c93d6480-c437-11e9-94a8-502083163549.gif)

**Comment by Medath** [comment]
Does it still hang when you apply #2280 ?

What output do you get when you run this python script (run it a few times):
``` python
#!/usr/bin/env python3

import requests, time

starttime=time.time()
requests.get("https://lutris.net/api/runtime")
print("\nAPI call took %.2f seconds" % (time.time() - starttime))
```

**Comment by strycore** [comment]
The above PR should indeed solve this problem, closing.
