### ISSUE TITLE
Uninstalling a game will keep the side panel open

### ISSUE THREAD

**Issue by TheFrenchGhosty** [lutris/lutris#2287]
When uninstalling a game the side panel will stay opened with the game information, if the user click on "Remove" the option "Remove from library" will still be available (even if the game is already removed), clicking on it will remove the game details from the panel but keep some stuff (including the remove option)

![lutris](https://user-images.githubusercontent.com/47571719/63453570-7adc9580-c438-11e9-9335-8b6949f6d51d.png)

**Comment by vahtos** [comment]
This is the same issue that causes #2066 and #2082. I have already submitted a pull request that addresses it, which is currently under review.

**Comment by strycore** [comment]
This can be closed now since the pull request was merged.
