### ISSUE TITLE
[Feature Request] Present a valuable error in GUI (lack of cabextract)

### ISSUE THREAD

**Issue by Justinzobel** [lutris/lutris#2288]
**Feature Request**

When running the installer for BF-V it gave a wine error that wasn't really useful, running `lutris -d` told me that cabextract was missing. Can this please be presented in the GUI, that way it will make it easier for other users to identfiy what is missing. Also it may help to know what platform Lutris is missing and provide an appropriate error message:
Solus: sudo eopkg install cabextract
Ubuntu: sudo apt-get install cabextract
etc

**Expected behavior**

Dialog box or error message in the scrolling terminal to indicate the lack of cabextract

**Current behavior**

Issue is unknown unless user runs Lutris from a terminal and users don't often know how to do this or want to.

**System information**

Lutris 0.5.2.2 on Solus

**Comment by strycore** [comment]
if a script uses an external binary then it should have it in the `require-binary` directive in the installer.
