### ISSUE TITLE
Cannot run two EXEs inside the same prefix

### ISSUE THREAD

**Issue by VoodooCode14** [lutris/lutris#2289]
**Cannot run two EXEs inside the same prefix**

When trying to run two exes inside the same prefix or launching the main exe and trying to run another inside a prefix, the second exe is never executed. 

This changed after upgrading to version 0.5.2.2, previously (version < 0.5) this was possible.

**Expected behavior**

The second executable is run concurrently to the first one.

**Current behavior**

The second executable does not start.

**Steps to reproduce**

- Start lutris
- Start a program (like battle.net)
- Run another (like WC3 installer)

**Lutris debugging output**

The terminal output of `lutris -d`.

INFO     2019-08-23 17:46:42,255 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-08-23 17:46:42,255 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-08-23 17:46:42,255 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-08-23 17:46:42,255 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2019-08-23 17:46:42,256 [dxvk.enable_dxvk_dll:131]:Replacing /home/voodoocode/Games/battlenet/drive_c/windows/syswow64/d3d10 with DXVK version
DEBUG    2019-08-23 17:46:42,257 [wine.use_lutris_runtime:113]:/home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/bin/wine is provided by Lutris, using runtime
DEBUG    2019-08-23 17:46:42,257 [command.start:111]:Running /usr/bin/lutris-wrapper 0 0 /home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/bin/wine /home/voodoocode/Downloads/Warcraft-III-Setup.exe
DEBUG    2019-08-23 17:46:42,257 [command.start:113]:ENV: WINEARCH="win64"
DEBUG    2019-08-23 17:46:42,257 [command.start:113]:ENV: WINE="/home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/bin/wine"
DEBUG    2019-08-23 17:46:42,258 [command.start:113]:ENV: WINEPREFIX="/home/voodoocode/Games/battlenet"
DEBUG    2019-08-23 17:46:42,258 [command.start:113]:ENV: LD_LIBRARY_PATH="/home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/lib:/home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/lib64:/lib:/lib64:/lib32:/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/voodoocode/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/voodoocode/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/voodoocode/.local/share/lutris/runtime/steam/i386/lib:/home/voodoocode/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/voodoocode/.local/share/lutris/runtime/steam/i386/usr/lib:/home/voodoocode/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/voodoocode/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/voodoocode/.local/share/lutris/runtime/steam/amd64/lib:/home/voodoocode/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/voodoocode/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2019-08-23 17:46:42,258 [command.start:113]:ENV: PYTHONPATH="/usr/bin:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/home/voodoocode/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2019-08-23 17:46:42,261 [signals.register_handler:26]:Registering <bound method MonitoredCommand.on_stop of <lutris.command.MonitoredCommand object at 0x7faeb8179f28>> to 11841
Running /home/voodoocode/.local/share/lutris/runners/wine/lutris-4.13-x86_64/bin/wine /home/voodoocode/Downloads/Warcraft-III-Setup.exe
00d4:err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.
Waiting on children
Exit with returncode 1
DEBUG    2019-08-23 17:46:42,337 [command.on_stop:158]:The process has terminated with code 256
DEBUG    2019-08-23 17:46:42,338 [command.stop:241]:Management process looks dead already.
DEBUG    2019-08-23 17:46:42,338 [command.stop:253]:logger already detached

**Comment by strycore** [comment]
Was able to reproduce the issue. Passed environment variables to the custom executable (Esync wasn't passed, generating an error). I also added libgcrypt.so.11 to the runtime and now I can launch the Warcraft III installer without any issue.
