### ISSUE TITLE
Synchronized Steam library games has no Application ID set

### ISSUE THREAD

**Issue by Shished** [lutris/lutris#229]
I registered account on lutris.net, attached my Steam account and logged in Lutris app.
After that i synchronized library with app and my Steam library appeared in Lutris app, under Steam runner.
The problem is that all synchronized games has no Application ID set in Game Options. 
![appid](https://cloud.githubusercontent.com/assets/3143668/11767021/c8a40d00-a1a7-11e5-8bb4-36d07a438f7c.png)
This makes all games from Steam library unplayable. Games cannot be launched from Lutris app.

**Comment by strycore** [comment]
Library syncing and setting the SteamID are 2 separate things. The games that you have installed locally on your steam client should appear as installed and have their SteamID, was this not the case? For games that aren't installed yet, you can double click on the game and it will prompt you to install the game if there's an installer on lutris.net (there is one for Wargame: Red Dragon). If an installer is missing, it will prompt you to add one on the website, which is very straightforward for Steam games, just keep the default installer and submit the form.

**Comment by Shished** [comment]
I have all my steam for linux games installed.
If lutris has no installer for the game, it will mark game title gray, like this:
![app2](https://cloud.githubusercontent.com/assets/3143668/11777336/82df52e8-a256-11e5-8175-e2397344f94b.png)

After installing the game in Lutris (via right click menu on game title), it creates new title with AppID, and there are 2 identical game titles now (or even more if you tried to install game more than once) — one that was synced and added to library automatically (without AppID) and another one that was installed (with AppID).
![app3](https://cloud.githubusercontent.com/assets/3143668/11777430/2fd13b92-a257-11e5-8f22-1b381140d8e6.png)

This is wrong because for Steam games lutris does not actually installing anything. So why just not add Steam AppID for synced games?

**Comment by Shished** [comment]
This is not how synchronization works. Lutris should automatically install all games that are attached to my Lutris account.
Instead, i have over 100 games that i need to install manually and remove original synchronized titles because they cannot launch games.

**Comment by Xodetaetl** [comment]
Thanks for the screenshots and details. I can reproduce this bug, I'll fix it asap.
