### ISSUE TITLE
[Feature Request] Add additional exe shortcuts to wine prefix

### ISSUE THREAD

**Issue by sigboe** [lutris/lutris#2290]
Add additional exe shortcuts to wine prefix.

![untitled](https://user-images.githubusercontent.com/2087930/63679140-e89a1000-c7f0-11e9-9e7d-59b6990335a4.png)

Some examples where the button could be. 
Also maybe it could be launched via a shortcut like `lutris lutris:rungameid/83a` where the `a` letter following the id number would designate the first extra shortcut.

**Usecase 1:**
Add battle.net games like Diablo 3 and make them launch directly without Battle.net, and have a shortcut to open battle.net in the prefix to update and what not.

**Usecase 2:**
Add configuration utilities, some games have configurations in a seperate App

**Usecase 3:**
Open Map Editor or similar additional program

**Usecase 4:**
Open a modded version of the EXE, like skyrim script extender.

**Usecase 5:**
Open a trainer

**Comment by strycore** [comment]
That feature is already tracked in #607, fell free to add to it if you feel like the ticket is missing some information.
