### ISSUE TITLE
Tomb Raider 1 doesn't start. 

### ISSUE THREAD

**Issue by Stefan566** [lutris/lutris#2294]
I'm getting an error if I try to start Tomb Raider 1. I have submitted here the issue report and the link to the debug log.

[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/3556647/lutris-issue-report.json.txt)
https://paste.ubuntu.com/p/KjPwy8v5wT/

**Comment by telanus** [comment]
Are you trying to run a DOS game via Wine?

**Comment by strycore** [comment]
You are using the nouveau driver, you should probably switch to the nvidia drivers to play games. Are you able to play other wine games with that same configuration?

**Comment by Zeioth** [comment]
The game will be reviewed soon.
