### ISSUE TITLE
Add WINE_LARGE_ADDRESS_AWARE option, enable for D9VK when compatible build is in use

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2297]
It's required to pass `WINE_LARGE_ADDRESS_AWARE` envar set to `1` for 32-bit games when you use D9VK and DXVK, as otherwise they will often crash due to lack of memory, as by default wine only allows majority of 32-bit apps to only allocate 2GB of memory, while this envar allows all of them to be able to allocate up to 4GB. I also think we should enable this when D9VK/DXVK option is enabled.
It should also be noted that this envar only works for `lutris`, `ge` and `tkg` builds. Neither vanilla wine or wine-staging support it.
Without this feature, we can't ship a new Lutris release with D9VK option.

**Comment by strycore** [comment]
Not everything should be an option…
