### ISSUE TITLE
Move "Auto-Hide Launcher" to Preferences, rename the option to something more clear.

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2298]
I don't like it is currently resides in "View Options" menu, which is a menu for options that immediately affect how Lutris looks, not for a functionality options effect of which you can only see after you start a game using a shortcut. Plus, as it is right now, it's very unclear what it does.
I propose to move it to preferences, specifically Lutris tab. There, I suppose to rename it to `Show launcher on game launch from shortcut", and clarify that it will only have an affect when you launch the game using application menu/desktop shortcut or direct terminal command.

**Comment by strycore** [comment]
wait… that shit doesnt work …

**Comment by strycore** [comment]
Now it does.

**Comment by tannisroot** [comment]
I meant moving it from here:
![Screenshot from 2019-09-02 05-27-07](https://user-images.githubusercontent.com/10602045/64086951-9783a200-cd43-11e9-9379-3aaa28436685.png)
).
To here:
![Screenshot from 2019-09-02 05-27-13](https://user-images.githubusercontent.com/10602045/64086966-a10d0a00-cd43-11e9-886b-9659918c1392.png)
And the option was working as intended, it wasn't supposed to hide game library when you launch games specifically from it, only when you launch it from some kind of direct shortcut (`lutris lutris:rungameid/N`

**Comment by strycore** [comment]
Moved to the preferences dialog.
