### ISSUE TITLE
Feature Request: Set Platform for any game

### ISSUE THREAD

**Issue by trymeouteh** [lutris/lutris#2302]
Please add a setting for each game to choose what platform the game is. Platforms such as

Linux
Windows
Super Nintendo
Nintendo 64
Nintendo Gamecube
Nintendo Wii
Nintendo Wii U
PlayStation
PlayStation 2
PlayStation 3
etc

By add a feature to set and change the platform of any game in your Lutris library will help one sort their games.

**Comment by strycore** [comment]
Platforms are determined by what runner the game uses. I cases where a runner support multiple platforms, games get their platforms from a parameter like a libretro core for example.

**Comment by LeXofLeviafan** [comment]
…As I thought.
What he meant here is actually that he wants ability to group games by arbitrary categories in the client (which just happens to be based on the platform that the game was originally released on or something, in his case). Honestly, I would like such a feature as well (though I would be grouping them based on series or game genre instead). Even an entirely local single-pairing version will do (it'll certainly be better than nothing at all).

**Comment by strycore** [comment]
Sorting games by platform would be pretty neat indeed. Grouping games by other aspects would be neat as well, but we have a tagging ticket open for that purpose.

**Comment by LeXofLeviafan** [comment]
Can you please mark this request as a duplicate of that one then?

**Comment by trymeouteh** [comment]
> Platforms are determined by what runner the game uses. I cases where a runner support multiple platforms, games get their platforms from a parameter like a libretro core for example.

I understand the platform is determined by the runner, hovever when I install a game manually such as Skyrim it will say the platform for Skyrim is "Linux" since the runner I used is the Steam runner and I installed Skyrim in Steam using Steam Play/Proton. I want Skyrim to be set to Windows in my Lutris library and the only way I can do that now is if I install the Steam Windows Wine runner and reinstall the game.
