### ISSUE TITLE
ResidualVM: need a more recent version to run The Long Journey

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2303]
Hello,
I wrote the script for "The long journey" GOG edition with ResidualVM script.
The script should run perfectly but...TLJ needs a more recent ResidualVM version or the game will not be identify.

Could you upload a more recent version of this runner?

**Comment by strycore** [comment]
I've uploaded a build of the most recent git master branch.

**Comment by legluondunet** [comment]
the rvm version is now correct but...
1°) on Ubuntu 19.04 rvm don't want to launch, it asks for a dependency: libGLEW.so.2.0
on Ubuntu 19.04 I can install only this ones:
```
$ locate libGLEW.so.2
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1.0
```
So I copied /usr/lib/x86_64-linux-gnu/libGLEW.so.2.1 to the Lutris rvm runner folder and renamed it libGLEW.so.2.0.
Then I launched Lutris rvm runner like this:
`LD_LIBRARY_PATH=. ./residualvm`
and it launched correctly.
solution? : add libGLEW.so.2.0 to Lutris runtime or compile ResidualVM statically with libGLEW.so.2.0?

2°)Then I tried to launch the game TLJ but I obtain a rvm error:
![Capture d’écran de 2019-09-02 21-28-29](https://user-images.githubusercontent.com/325405/64131418-b8420b00-cdc8-11e9-9b71-26b739a806c2.png)
`Could not open shader stark_surface.vertex!!`
If I copy rvm "engines" folder from git : https://github.com/residualvm/residualvm/tree/master/engines to the Lutris rvm runner folder it works if I launch it in command line from rvm runner path.
But not from Lutris interface.

solution? : I don't know why Lutris rvm runner did not find engines folder, perrhaps there is a way to indicate it where to find it?

I joined you the missed files I used for my test.

**Comment by legluondunet** [comment]
Finally I found a workaround: if I copy "engines" folder in the main game folder, Lutris rvm found it and launched the game.

**Comment by legluondunet** [comment]
new issue, your build is not compiled with Vorbis support:
`WARNING: Cannot decode sound '0001.ovs', Vorbis support is not compiled in!`

**Comment by legluondunet** [comment]
opened issues: #2311 #2312 #2313
