### ISSUE TITLE
Lutris/Optimus/Arch wine mismatch WoW

### ISSUE THREAD

**Issue by stratus-ss** [lutris/lutris#2304]
Hi, I followed the guide to setting up WoW/Battle.net linked from the lutris page (back to the github links)

I have a laptop with the following:

```System:
  Host: stratus-15 Kernel: 5.2.11-arch1-1-ARCH x86_64 bits: 64 Console: tty 2 
  Distro: Arch Linux 
Machine:
  Type: Laptop System: Dell product: Inspiron 15 7000 Gaming v: N/A 
  serial: 6PM9YL2 
CPU:
  Quad Core: Intel Core i5-7300HQ type: MCP speed: 800 MHz min/max: 800/3500 MHz 
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] driver: nvidia v: 435.21 
  Display: server: X.org 1.20.5 driver: modesetting,nvidia tty: 86x26 
```

When I launch the battle.net installer from inside of a session running off the intel graphics I have the System settings to all the defaults except Optimus Launcher, which I have set to optirun/virtualgl 

I am running the following packages:

```local/wine-staging 4.15-1```

When I try to start the game, I see this in the lutris debug:

```Running optirun -b virtualgl /home/stratus/.local/share/lutris/runners/wine/ge-protonified-nofshack-4.9-x86_64/bin/wine /big_space/Lutris/WoW-Classic/drive_c/Program Files (x86)/World of Warcraft/World of Warcraft Launcher.exe
wine client error:0: version mismatch 584/589.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
Waiting on children
All children gone
```

If I turn off the optimus settings, the game launches but is quite obviously using the Intel Graphics.

If I start my whole desktop on the descrete card (with nvidia-xrun) the game runs perfectly.

I have tried setting the Optimus setting in lutris to both 'primusrun' and 'primus vk' both of which allow the game to launch but it is again using the intel graphics

How can I proceed? I would like to be able to use optirun so I don't have to log out all the time. (In steam for example I can set launch options in the game itself) 

Any help would be greatly appreciated

**Comment by aTosser** [comment]
The error you are receiving looks liks a wine upgrade (or you changed version in lutris) kill all wine processes and a relaunch should fix it. (verify all of the wine processes are gone in a process viewer)

To use optirun look for command prefix in system options for the game you are trying to configue. (Or you can add it to the system lutris wide system options.

**Comment by stratus-ss** [comment]
thank you for the reply. I found these suggestions on your forum previously.

I only have this error when I use the Optirun option inside of lutris. When I do not run the game with Optirun options (i.e. I set it to None) I do not have this wine-mismatch error.

Below are the settings used that *cause* the wine mismatch error. I have not tried changing the wine options

![image](https://user-images.githubusercontent.com/8162705/64181806-2c19fd00-ce35-11e9-9114-2844e8ea8287.png)

![image](https://user-images.githubusercontent.com/8162705/64181837-35a36500-ce35-11e9-9073-9ef99f4d7ba4.png)

These are the wine options I currently see:

![image](https://user-images.githubusercontent.com/8162705/64181917-54a1f700-ce35-11e9-9fb7-2ae00a1d53ca.png)


These are the optirun options I can see:

![image](https://user-images.githubusercontent.com/8162705/64181948-62f01300-ce35-11e9-9dea-390b4e46af50.png)


I have tried the following versions of wine from both the AUR and the main repositories:
```
wine-4.15
wine-staging-4.15
wine-staging-pba-git-3.17.r8
```
The version of lutris I have installed:
```
lutris 0.5.2.2-1
```

As per your suggestion, I did this test after a cold boot:

```
[stratus@stratus-15 ~]$ ps aux |grep exe
stratus   3529  0.0  0.0 311900  7764 ?        Sl   09:21   0:00 /usr/lib/gvfsd-trash --spawner :1.15 /org/gtk/gvfs/exec_spaw/0
stratus   6059  0.0  0.0   6264  2216 pts/0    S+   10:29   0:00 grep exe
[stratus@stratus-15 ~]$ ps aux |grep -i wine
stratus   6064  0.0  0.0   6264  2260 pts/0    S+   10:30   0:00 grep -i wine
```

Then I tried hitting 'play' and caused the same error

I appreciate you taking a look at this

**Comment by stratus-ss** [comment]
On a whimp I decided to try downloading wine-staging 4.9 from here: https://archive.archlinux.org/repos/2019/05/28/multilib/os/x86_64/

Since that seems to be the version indicated in lutris.

While this version allowed me to get further than the wine mismatch error I ended up with a virtualgl error:

```
Running optirun -b virtualgl /home/stratus/.local/share/lutris/runners/wine/ge-protonified-nofshack-4.9-x86_64/bin/wine /big_space/Lutris/WoW-Classic/drive_c/Program Files (x86)/World of Warcraft/World of Warcraft Launcher.exe
<html><head><title>Object moved</title></head><body>


<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>


</body></html>


<html><head><title>Object moved</title></head><body>


<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>


</body></html>


<html><head><title>Object moved</title></head><body>


<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>


</body></html>


Waiting on children
Waiting on children
[VGL] ERROR: Could not open display :8.
2019-09-03 19:23:40,892: Unable to read stat for process 3559
2019-09-03 19:23:40,892: Unable to read stat for process 3559
All children gone
Exit with returncode 0
```

**Comment by stratus-ss** [comment]
I poked around at this finding various articles/github issues from a long time ago saying that you should run `optirun bash` and then run your command. I attempted to do this via
```
optirun bash
lutris
```
And then launching the game. While this does work, it is quite clear its not using the discrete card

**Comment by Medath** [comment]
Can you run `lutris -d`, reproduce the version mismatch and then paste the output here? That would be very helpful

**Comment by FerventlyFree** [comment]
I'm sorry to hijack this thread, but I've encountered the same error with the same versions listed here.
Here is my output when running lutris -d 
https://pastebin.com/Ef5MY3rT

**Comment by gardotd426** [comment]
I'm encountering the same error on manjaro and Arch with Battlefield V.

**Comment by gardotd426** [comment]
This is a bug in lutris, it happens on clean boots, with absolutely no wine processes running.

**Comment by Caenhorn** [comment]
Same here with MTG Arena. Manjaro stable.

**Comment by dubcusb** [comment]
I'm having the same problem with Eve Online (after trying to get galliumnine from winetricks running). Not sure if my report here helps.

**Comment by tannisroot** [comment]
This should be fixed.
