### ISSUE TITLE
The database is locked when syncing from Steam or GOG

### ISSUE THREAD

**Issue by CartoonFan** [lutris/lutris#2306]
**Describe the bug**

Related to #2016, the database is locked when syncing on startup, preventing a successful sync.

**Expected behavior**

The database should be opened to receive data, I'd think.

**Current behavior**

When Lutris starts, the program displays various informational bits and then tries to sync with GOG and Steam, which fails with a popup and terminal output.

**Steps to reproduce**

- Enable "Sync all games at startup" for GOG or Steam in the Import Games section (Enabling GOG more reliably causes the issue for me).
- Restart Lutris.

**Lutris debugging output**

INFO     2019-09-03 01:00:19,976 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-09-03 01:00:19,978 [startup.check_driver:54]:Using NVIDIA drivers 435.19.02 for x86_64
INFO     2019-09-03 01:00:19,978 [startup.check_driver:58]:GPU: GeForce GTX 960
INFO     2019-09-03 01:00:19,978 [startup.check_driver:75]:GPU: 8086:0402 1043:8534 using i915 drivers
INFO     2019-09-03 01:00:20,010 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-09-03 01:00:20,012 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
INFO     2019-09-03 01:00:20,389 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
INFO     2019-09-03 01:00:20,390 [lutriswindow.toggle_connection:580]:Connected to lutris.net as CartoonFan
DEBUG    2019-09-03 01:00:20,399 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-09-03 01:00:20,400 [gog.get_library:175]:Returning cached GOG library
DEBUG    2019-09-03 01:00:20,408 [http.get:68]:GET https://lutris.net/api/games/library/CartoonFan
DEBUG    2019-09-03 01:00:20,586 [store.get_missing_media:194]:Requesting missing icons from API for 183 games
DEBUG    2019-09-03 01:00:20,588 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-03 01:00:20,627 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-03 01:00:22,639 [api.get_game_api_page:132]:Loaded 135 games from page 1
DEBUG    2019-09-03 01:00:22,782 [api.get_game_api_page:132]:Loaded 250 games from page 1
DEBUG    2019-09-03 01:00:22,786 [http.get:68]:GET https://lutris.net/api/games?page=2
DEBUG    2019-09-03 01:00:23,767 [api.get_game_api_page:132]:Loaded 7 games from page 2
ERROR    2019-09-03 01:00:29,308 [sql.cursor_execute:37]:SQL query 'SELECT * FROM games where slug=?' failed. 4 retries remaining
ERROR    2019-09-03 01:00:29,309 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:30,310 [sql.cursor_execute:37]:SQL query 'SELECT * FROM games where slug=?' failed. 3 retries remaining
ERROR    2019-09-03 01:00:30,311 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:30,936 [sql.cursor_execute:37]:SQL query 'select * from games WHERE steamid is not null AND steamid != ?' failed. 4 retries remaining
ERROR    2019-09-03 01:00:30,936 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:31,312 [sql.cursor_execute:37]:SQL query 'SELECT * FROM games where slug=?' failed. 2 retries remaining
ERROR    2019-09-03 01:00:31,313 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:31,937 [sql.cursor_execute:37]:SQL query 'select * from games WHERE steamid is not null AND steamid != ?' failed. 3 retries remaining
ERROR    2019-09-03 01:00:31,938 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:32,314 [sql.cursor_execute:37]:SQL query 'SELECT * FROM games where slug=?' failed. 1 retries remaining
ERROR    2019-09-03 01:00:32,315 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:32,939 [sql.cursor_execute:37]:SQL query 'select * from games WHERE steamid is not null AND steamid != ?' failed. 2 retries remaining
ERROR    2019-09-03 01:00:32,939 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:33,316 [jobs.target:32]:Error while completing task <function sync_from_remote at 0x7f1300e2db90>: database is locked
<class 'sqlite3.OperationalError'> database is locked
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/sync.py", line 94, in sync_from_remote
    updated = sync_game_details(remote_library)
  File "/usr/lib/python3.7/site-packages/lutris/sync.py", line 46, in sync_game_details
    local_game = pga.get_game_by_field(slug, "slug")
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 238, in get_game_by_field
    game_result = sql.db_select(PGA_DB, "games", condition=(field, value))
  File "/usr/lib/python3.7/site-packages/lutris/util/sql.py", line 106, in db_select
    cursor_execute(cursor, query, params)
  File "/usr/lib/python3.7/site-packages/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
ERROR    2019-09-03 01:00:33,941 [sql.cursor_execute:37]:SQL query 'select * from games WHERE steamid is not null AND steamid != ?' failed. 1 retries remaining
ERROR    2019-09-03 01:00:33,941 [sql.cursor_execute:39]:database is locked
ERROR    2019-09-03 01:00:34,942 [jobs.target:32]:Error while completing task <function LutrisWindow.sync_services.<locals>.full_sync at 0x7f12f2b07170>: database is locked
<class 'sqlite3.OperationalError'> database is locked
  File "/usr/lib/python3.7/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 321, in full_sync
    return syncer.sync(games, full=True)
  File "/usr/lib/python3.7/site-packages/lutris/services/steam.py", line 142, in sync
    pga_game = self.get_pga_game(game)
  File "/usr/lib/python3.7/site-packages/lutris/services/steam.py", line 127, in get_pga_game
    for pga_game in self.lutris_games:
  File "/usr/lib/python3.7/site-packages/lutris/services/steam.py", line 104, in lutris_games
    steamid__not=""
  File "/usr/lib/python3.7/site-packages/lutris/pga.py", line 217, in get_games_where
    return sql.db_query(PGA_DB, query, tuple(condition_values))
  File "/usr/lib/python3.7/site-packages/lutris/util/sql.py", line 120, in db_query
    cursor_execute(cursor, query, params)
  File "/usr/lib/python3.7/site-packages/lutris/util/sql.py", line 30, in cursor_execute
    return cursor.execute(query, params)
ERROR    2019-09-03 01:00:34,945 [lutriswindow.on_sync_complete:326]:Sync failed: database is locked

**System information**

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/3568460/lutris-issue-report.json.zip)

**Screenshots**

A window usually pops up at the end of the whole process:

![20190902-122126](https://user-images.githubusercontent.com/29664894/64155274-50e78380-cde7-11e9-8cae-2541a59e7b6f.png)

**Comment by tannisroot** [comment]
Can you check permissions of pga.db?

**Comment by CartoonFan** [comment]
Looks like it's world-read and writeable.

`-rwxrwxrwx 1 jeremiah users 118784 Sep  3 01:01 /home/jeremiah/.local/share/lutris/pga.db`

**Comment by CartoonFan** [comment]
This seems to be fixed as of https://github.com/lutris/lutris/commit/a067edd929c1de609a76f1e5511b4edabaf2525a .

Closing #2306 for now.

**Comment by CartoonFan** [comment]
Never mind, the issue's still here.

**Comment by strycore** [comment]
this cannot be reproduced and no one else has reported the issue, closing

**Comment by CartoonFan** [comment]
Ah, thank you. I haven't experienced the issue lately and I forgot to close this.
