### ISSUE TITLE
winesteam runner can't be run without installing a game first

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#231]
When you have a winesteam game installed already, the runner appears in the panel on the left and you can right-click it and set "Run" to start steam. But if no game is installed, the runner is not shown and you can't start steam this way.

I need to be able to start winesteam before installing games as I want to set a custom game installation directory in the steam settings. I can do this by starting an install, aborting and then winesteam is running, but that's messy :)

A solution could be to show all configured runners in the left panel even if no games are installed for those runners.

**Comment by strycore** [comment]
I agree, we have the ability to run a variety of runners by themselves with any games configured so it would be logic to show them in the sidebar even if no game are installed.

**Comment by Xodetaetl** [comment]
> A solution could be to show all configured runners in the left panel even if no games are installed for those runners.

Done in 48e564640be54706fb8a545b4a90e4f0e8c2dc25
