### ISSUE TITLE
ResidualVM: cannot launch, LibGLEW dependency not satisfied on Ubuntu

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2313]
Hello,
on Ubuntu 19.04 Lutris rvm runner don't want to launch, it asks for a dependency: libGLEW.so.2.0
But on Ubuntu 19.04 you can install only LibGLEW 2.1:

$ locate libGLEW.so.2
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1
/usr/lib/x86_64-linux-gnu/libGLEW.so.2.1.0

If I copy manually libGLEW.so.2.1 to Lutris runtime folder : ~/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/, and rename it libGLEW.so.2.0, Lutris rvm runner launches correctly from Lutris interface.

solution? : add libGLEW.so.2.0 to Lutris runtime or compile ResidualVM statically with libGLEW.so.2.0?

**Comment by strycore** [comment]
libGLEW.so.2.0 is now included in the lutris runtime

**Comment by legluondunet** [comment]
Hello Strycore, how could I test this? If I delete Lutris runtime folder, will it upload the libraries at next launch?

**Comment by legluondunet** [comment]
I deleted Lutris runtime folder and Lutris uploaded it at launch. ResidualVM now launches correctly. Thanks.

**Comment by strycore** [comment]
Runtime updates are done automatically, no need to delete anything, Lutris will check at startup if a new runtime is available and download it
