### ISSUE TITLE
Custom Wine Prefixes

### ISSUE THREAD

**Issue by Orochimarufan** [lutris/lutris#232]
I already have a Wine Prefix set up with Steam + a number of tweaks required to run some games (I use q4wine to manage them). I'd like to try Lutris, but I'm not going to switch over completely yet. Therefore, it would be nice to be able to have Lutris use an existing Prefix in a non-destructive manner.

I might take a look at this myself if I find some time in the christmas break.

**Comment by strycore** [comment]
You can do that already by right clicking on a Wine game, and selecting your pre-existing prefix in the Game options tab. If you are installing a new game, select your prefix's path when you are prompted for the install path. 
For Steam games, it's a bit more complicated as there's no way to change the default prefix (~/.local/share/lutris/runners/winesteam/prefix), you can change it on a per-game basis as I explained above but if you which to use a different prefix for all the steam games, you could symlink it to the path of the default lutris prefix.

**Comment by Orochimarufan** [comment]
Right, I didn't even think of symlinking it... An option in the Winesteam runner configuration GUI would be nice nonetheless.
Another Idea would be to run an Assistant on first launch that tells you about what it found where and asks if it missed something, where you could point it to an existing install.

**Comment by Xodetaetl** [comment]
We could move the `Prefix` option to the Runner level, so that it would be possible to set it globally for all winesteam games.

A first launch / import assistant would be very useful, that's on my mind.

**Comment by Orochimarufan** [comment]
I've put some work into the wine/winesteam code at https://github.com/Orochimarufan/lutris/tree/clean_wine . I also added a commit that moves Prefix and Arch to the runner level, which I've been using for a few days now and It's much more convenient than going through the games and changing it manually. Also, the symlink solution still feels like a hack.

However, due to how Lutris config currently works, this will lose all current prefix and arch settings. Maybe the settings could be copied from the game config if the runner config doesn't specify?

On that note, why are the configs separate in the first place? It should be perfectly OK to have a single cascading config instead of the more or less arbitrary 3 distinct configs/config sections/keyspaces (game/runner/system)

**Comment by strycore** [comment]
Hey @Orochimarufan , 
I know it's been a while but I'd like to take a look at this branch, do you think you could rebase it against the current master branch so we can review it and include it in the next release?

**Comment by strycore** [comment]
Btw, if you have changes that break current configs, you have to write a migration script so they won't break. There are examples in the lutris/migrations folder.

**Comment by strycore** [comment]
Just looked at your commits on your branch, you could rebase your branch without the code cleanups, it would be easier. Then submit the code cleanups in a separate PR.

**Comment by rijnhard** [comment]
This would be nice to bring back from the dead.

**Comment by strycore** [comment]
Closing, since this is closely related to winesteam and we don't have that anymore
