### ISSUE TITLE
Option to avoid GOG signin window to appear?

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2321]
Hello,
is there a way to avoid GOG sign in window to appear when I install a GOG game?
The feature is interesting but I prefer to not use it: it downloads only english version of the game. So it is not adapted to gamers from others countries that would prefer to download their GOG games directly on the GOG site in their native language (when it is available).
When you choose to not use this feature, it becomes annoying to see the GOG sign in windows appearing each time you install a GOG game.
Thank you for your help.

**Comment by legluondunet** [comment]
why it is necessary:
https://forums.lutris.net/t/install-script-how-to-choose-language-specific-installer/5090

**Comment by legluondunet** [comment]
it will be possible to let the choice to the user:
before to download GOG setup file, Lutris will ask user if it want to download directly setup file game from GOG or if it prefer to use a local GOG setup file.

**Comment by legluondunet** [comment]
@strycore we could consider this feature request is obsolete since 0.5.8?

**Comment by strycore** [comment]
yes, we can
