### ISSUE TITLE
Installed games still has install option

### ISSUE THREAD

**Issue by Shished** [lutris/lutris#233]
Already installed games still has install option in right click menu. Installing results in creating duplicate game title. Lutris 0.3.7 is used.

![image](https://cloud.githubusercontent.com/assets/3143668/11777982/43bd17fe-a25a-11e5-990f-27ed94df394f.png)

**Comment by Xodetaetl** [comment]
This is not a bug, it's to let you install different versions of the same game.
We should remove the versions already installed from the list though, and change the "Install" label to something more explicit like "Install another version".

**Comment by Xodetaetl** [comment]
PS: This feature isn't polished yet, the next version should add a way to visually differentiate versions if you have more than one installed. For now, they are order from first to last installed version in the games list. You can remove them separately safely.

**Comment by Xodetaetl** [comment]
> We should [...] change the "Install" label to something more explicit like "Install another version"

I did that. e36db6a41bddc3fe4fb1ec7aace54a00a3e513e4
