### ISSUE TITLE
Unable to install from local script [“Waiting for response from https://lutris.com"]

### ISSUE THREAD

**Issue by FakeTucan** [lutris/lutris#2333]
**Describe the bug**

It's not possible to install scripts locally. When trying to install a script with the command:

lutris -i /path/to/file

There comes a popup window "Waiting for response from https://lutris.com", which does nothing, only the cancel button does stuff.

**Expected behavior**

Just installing the game from a local script

**Current behavior**

Lutris idles and does nothing after running the command above.

**Steps to reproduce**

- lutris -i /path/to/file

**Lutris debugging output**

>> lutris -d -i /mnt/Games/Downloads/magic-the-gathering-arena-latest 
INFO     2019-09-09 22:39:21,455 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-09-09 22:39:21,456 [startup.check_driver:60]:Using X.Org
INFO     2019-09-09 22:39:21,456 [startup.check_driver:65]:Running Mesa driver 19.2.0 on Radeon RX 580 Series (POLARIS10, DRM 3.32.0, 5.2.13-1-ck-haswell, LLVM 8.0.1) (0x67df)
INFO     2019-09-09 22:39:21,457 [startup.check_driver:75]:GPU: 1002:67DF 1043:0525 using amdgpu drivers
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
INFO     2019-09-09 22:39:21,545 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-09-09 22:39:21,546 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-09-09 22:39:21,867 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-09-09 22:39:21,878 [store.get_missing_media:198]:Requesting missing icons from API for d2, frontschweine, pokemon-x
DEBUG    2019-09-09 22:39:21,879 [http.get:68]:GET https://lutris.net/api/games
INFO     2019-09-09 22:39:21,939 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-09-09 22:39:22,003 [api.get_game_api_page:132]:Loaded 1 games from page 1
DEBUG    2019-09-09 22:39:22,203 [interpreter.read_script:68]:Loading script(s) from /mnt/Games/Downloads/magic-the-gathering-arena-latest
INFO     2019-09-09 22:39:30,424 [application.do_shutdown:446]:Shutting down Lutris

**System information**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/3592543/lutris-issue-report.zip)

**Screenshots**

[![Screenshot from Gyazo](https://gyazo.com/a84031cf18b7752493280e490fd63f57/raw)](https://gyazo.com/a84031cf18b7752493280e490fd63f57)

**Comment by thecyberd3m0n** [comment]
you can merge @Medath PR, it works and helped me install Starcraft ;)

**Comment by marmalodak** [comment]
I'm getting this as I try to install Origin. I have lutris-0.5.3-1.fc30.x86_64 installed. How do I tell if this fix is in my installation?

**Comment by Medath** [comment]
A version with the fix has not been released yet, so you'll have to run the git version if you need this fix immediately. This error also only occurs when you try to install from a local installer. If you see this message (and it doesn't proceed after some time) with an installer from lutris.net, you have a separate issue

**Comment by VortexAcherontic** [comment]
This issue seems to be valid again in Lutris 0.5.3 (0.5.3-24.1 from the openSUSE repos) when will this fix be merged into a release?

**Comment by Medath** [comment]
0.5.3 is still affected by this bug. The fix has already been in master for a while but there was no release since then. You have to either run lutris from git or wait for an unspecified amount of time until 0.5.4 is out
