### ISSUE TITLE
cannot log in to lutris.net [7 days old issue]

### ISSUE THREAD

**Issue by thekayle** [lutris/lutris#2334]
created account,
+reset password
  שלום 
     'the user_id,password' message displays upon trying to sign in

**Comment by therealklanni** [comment]
What was the resolution? I'm having the same issue.

**Comment by thekayle** [comment]
"user id" is not your email address.
check your e-mail for your 'user id'
שלום

**Comment by therealklanni** [comment]
Thank you!
