### ISSUE TITLE
Rocket League no sound when ran from Lutris

### ISSUE THREAD

**Issue by vahtos** [lutris/lutris#2335]
**Describe the bug**

Rocket League does not have sound when I run it from Lutris. It is installed via Steam, and has been working for months, I do not know what changed... I tried removing it from my library and adding it again to clear any potential changes I may have made to its launch options in Lutris.

Please note, the game DOES have sound if I open Steam and launch it from there. I do not have this issue for any other game that I have noticed.

**Lutris debugging output**

https://pastebin.com/UpZm5myE

**System information**

https://pastebin.com/H7fEKcpS

**Comment by tannisroot** [comment]
Change wine to newer `lutris` version, should fix it.

**Comment by vahtos** [comment]
I will give this a try when I am home later, but Rocket League is a native game. So I don't understand why the WINE version would be affecting this.

**Comment by vahtos** [comment]
Tried it without any changes and suddenly it is working now... oh well.
