### ISSUE TITLE
Move Items from Gnome's App Menu into the already existing dedicated Menu

### ISSUE THREAD

**Issue by ZahnPastor** [lutris/lutris#2344]
See https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

Lutris is still using the App Menu in Gnome to display Settings 
![grafik](https://user-images.githubusercontent.com/21054889/64883266-420e9580-d65f-11e9-9304-377152e74ab1.png)

Gnome wants to retire this App Menu, so Lutris should move all necessary items into the already existing dedicated menu button 
![grafik](https://user-images.githubusercontent.com/21054889/64883341-6e2a1680-d65f-11e9-983c-48fe508dea07.png)

(dont know if this has already been brought up in another issue, i searched for app menu and didnt find any results)

**Comment by strycore** [comment]
Fixed in master
