### ISSUE TITLE
How to fill gogid and gogslug in yaml

### ISSUE THREAD

**Issue by zJoul** [lutris/lutris#2347]
How can I fill the gogslug and gogid in an install script for automatic download in the client.
The documentation is not very clear about that.

Take these gog installers :

- [The witcher 3 GOTY](https://lutris.net/api/installers/the-witcher-3-wild-hunt-game-gog?format=json)
- [Minoria](https://lutris.net/api/installers/minoria-gog?format=json)

The Witcher3 installer downloads automagically the files from gog, but the Minoria one doesn't and ask for the setup file. The only difference between these two is the `gogid` and `gogslug`

Doc says only the `script` part should be on the `yaml` and when editing the game page, I can't find any references to these two parameters

**Comment by tannisroot** [comment]
You can check them on gogdb.

**Comment by zJoul** [comment]
I know I necro this issue, but the question was not how to find the id, but how to fill it in the yaml since it's not on the `script` part

**Comment by tannisroot** [comment]
@zJoul only admins can do that.
Just give me a link to the game page and I'll add it.
