### ISSUE TITLE
[Fedora] v0.5.3 - installerwindow.py:437:on_install_finished:KeyError: 'id'

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#2349]
Seems like it might be the same as #2327 

Version-Release number of selected component:
lutris-0.5.3-1.fc30

Additional info:
reporter:       libreport-2.10.1
cmdline:        /usr/bin/python3 -s /usr/bin/lutris lutris:league-of-legends-appimg
crash_function: on_install_finished
exception_type: KeyError
executable:     /usr/bin/lutris
interpreter:    python3-3.7.4-1.fc30.x86_64
kernel:         5.2.13-200.fc30.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
installerwindow.py:437:on_install_finished:KeyError: 'id'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 567, in _iter_commands
    self._finish_install()
  File "/usr/lib/python3.7/site-packages/lutris/installer/interpreter.py", line 613, in _finish_install
    self.parent.on_install_finished()
  File "/usr/lib/python3.7/site-packages/lutris/gui/installerwindow.py", line 437, in on_install_finished
    game = Game(game_data["id"])
KeyError: 'id'

Local variables in innermost frame:
self: <installerwindow.InstallerWindow object at 0x7fb6feb5c140 (lutris+gui+installerwindow+InstallerWindow at 0x5622945f6cb0)>
game_data: {}

**Comment by BunnyApocalypse** [comment]
I just got another report of the same problem from a different user as well.

**Comment by BunnyApocalypse** [comment]
This is also happening on 0.5.3.1

**Comment by vahtos** [comment]
When is this error happening?

**Comment by tannisroot** [comment]
It usually happens after/during installs, I believe.

**Comment by BunnyApocalypse** [comment]
Yeah, none of the reports I have received added any additional information about when this happens. But given the installerwindow nature, I'd imagine it has something to do with that.
