### ISSUE TITLE
Lutris sometimes considers closed game as still active, button stop does nothing

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2350]
Since Lutris version 0.5.3, it doesn't know when a game exited:

![Capture d’écran de 2019-09-15 15-58-13](https://user-images.githubusercontent.com/325405/64924784-88433080-d7e8-11e9-9a96-ca6412b52e5e.png)

![Capture d’écran de 2019-09-15 18-36-27](https://user-images.githubusercontent.com/325405/64924788-91340200-d7e8-11e9-914f-dca49bc32666.png)

If I click on "Stop" button, nothing happened and I can not find related process in "ps aux".

This cause action planified after game exit don't happened like:
- reset keyboard to user local
- reset desktop resolution
...

**Comment by tannisroot** [comment]
I can't reproduce this. Please clarify the issue with 100% reliable steps to reproduce this.

**Comment by legluondunet** [comment]
Just happened again with A.O.D but for the moment I don't know how to reproduce.
This bug is very annoying so from today I start Lutris in debug mode and hope it will tell me something that can help in his debug logs.

**Comment by legluondunet** [comment]
Just happened with Dosbox, even if I press "stop" several times, Lutris still consider dosbox game "Rayman" as active:


![Capture d’écran de 2019-09-16 22-41-22](https://user-images.githubusercontent.com/325405/64992051-62df2100-d8d3-11e9-935e-bfd44db9f4f3.png)

```
DEBUG    2019-09-16 22:39:48,374 [game_actions.on_stop:172]:Removed game with ID 214 from running games
DEBUG    2019-09-16 22:40:00,286 [game_actions.on_stop:172]:Removed game with ID 214 from running games
DEBUG    2019-09-16 22:40:00,850 [game_actions.on_stop:172]:Removed game with ID 214 from running games
DEBUG    2019-09-16 22:40:01,092 [game_actions.on_stop:172]:Removed game with ID 214 from running games
DEBUG    2019-09-16 22:40:01,326 [game_actions.on_stop:172]:Removed game with ID 214 from running games
DEBUG    2019-09-16 22:40:01,552 [game_actions.on_stop:172]:Removed game with ID 214 from running games
```

**Comment by telanus** [comment]
I ran into the same problem this morning. there is no info on the terminal, and trying to reproduce it, fails

**Comment by G4E** [comment]
When it happens, could you post the output of "pstree" ? It might help.

**Comment by FalkF** [comment]
I had the same issue but clicking on "kill all wine processes" helped.

**Comment by legluondunet** [comment]
@FalkF  not with this issue: clicking on "kill all wine processes" or "stop" button does nothing.

**Comment by rezzafr33** [comment]
Try to turn off "Discord Rich Presence" under lutris preference.

**Comment by legluondunet** [comment]
I updated Lutris  to last git version and I can not reproduce this issue. I'll reopen it if necessary. Thank you all for your help.
