### ISSUE TITLE
Lutris window always starts in the middle of the screen

### ISSUE THREAD

**Issue by yaomtc** [lutris/lutris#2354]
**Describe the bug**

Lutris does not remember its window position. Instead it always starts in the middle of the screen. (This is using KWin.)

**Expected behavior**

If I set the window to be in a particular position, next time I start it, it should be in that position.

**Current behavior**

The window spawns in the middle of the screen, no matter what.

**Steps to reproduce**

* Start Lutris.
* Move window to non-middle position.
* Quit Lutris.
* Start Lutris.

**Lutris debugging output**

```
$ lutris -d
INFO     2019-09-17 00:13:49,893 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-09-17 00:13:49,894 [startup.check_driver:60]:Using X.Org
INFO     2019-09-17 00:13:49,894 [startup.check_driver:65]:Running Mesa driver 19.1.6 on Radeon RX 580 Series (POLARIS10, DRM 3.32.0, 5.2.14-arch2-1-ARCH, LLVM 8.0.1) (0x67df)
INFO     2019-09-17 00:13:49,894 [startup.check_driver:75]:GPU: 1002:67DF 1682:C580 using amdgpu drivers
INFO     2019-09-17 00:13:49,934 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-09-17 00:13:49,935 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-09-17 00:13:50,095 [store.get_missing_media:198]:Requesting missing icons from API for world-of-warcraft-classic
DEBUG    2019-09-17 00:13:50,097 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2019-09-17 00:13:50,108 [http.get:68]:GET https://lutris.net/api/games
INFO     2019-09-17 00:13:50,201 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-09-17 00:13:50,688 [api.get_game_api_page:132]:Loaded 1 games from page 1
INFO     2019-09-17 00:13:57,684 [application.do_shutdown:446]:Shutting down Lutris
```

**System information**

[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/3619225/lutris-issue-report.json.txt)

(JSON files cannot be attached for some reason.)

**Comment by tannisroot** [comment]
Possibly the same issue as https://github.com/lutris/lutris/issues/2320

**Comment by yaomtc** [comment]
Looking at the config file posted in that thread, it saves window size and width (which _does_ work for me) but there's no mention of window position.

**Comment by strycore** [comment]
This is in no way critical and should not be tagged for 0.5.3.1

**Comment by strycore** [comment]
Yes, this should now be closed. There shouldn't be a anything that tells lutris to start in the middle of the screen.
