### ISSUE TITLE
Add "Yuzu" runner

### ISSUE THREAD

**Issue by AymenStudios** [lutris/lutris#2356]
Add Support for Yuzu Emulater for play Nintendo Switch Games

**Comment by Adehom** [comment]
To add this emulator we need to add this runners in https://lutris.net/api/runners
        {
            "name": "Yuzu",
            "slug": "yuzu",
            "icon": "https://lutris.net/media/runners/icons/yuzu.png", #need to add this icons in this repository
            "website": "https://yuzu-emu.org/",
            "versions": [
                {
                    "version": "9d03a58ea",
                    "architecture": "x86_64",
                    "url": "https://lutris.net/files/runners/yuzu-linux-20191027-9d03a58ea.tar.xz", #need to add this file in this repository
                    "default": true
                }
            ]
        },

**Comment by Adehom** [comment]
With @xavierdlr, we add this emulator in runner list but to install it, we need this runner in https://lutris.net/api/runners and the installer in https://lutris.net/files/runners/.

How can we add it ?

>

    Traceback (most recent call last):
      File "/home/tony/lutris/lutris/gui/dialogs/runners.py", line 134, in on_install_clicked
        runner.install(downloader=simple_downloader)
      File "/home/tony/lutris/lutris/runners/runner.py", line 328, in install
        runner = self.get_runner_version(version)
      File "/home/tony/lutris/lutris/runners/runner.py", line 290, in get_runner_version
        runner_info = self.get_runner_info()
      File "/home/tony/lutris/lutris/runners/runner.py", line 282, in get_runner_info
        return request.get().json
      File "/home/tony/lutris/lutris/util/http.py", line 76, in get
        raise HTTPError("Request to %s failed: %s" % (self.url, error))
    lutris.util.http.HTTPError: Request to https://lutris.net/api/runners/yuzu failed: HTTP Error 404: Not Found

**Comment by strycore** [comment]
This can be closed, we have support for Yuzu now.
