### ISSUE TITLE
Request - Add a field for 'custom wine variables' to 'Runner options' page

### ISSUE THREAD

**Issue by zpangwin** [lutris/lutris#2364]
**Description**

Would be nice to add a quick way for setting custom wine environment variables in the GUI. Yes, sometimes a dedicated option for flags is nice, but sometimes new variables might get added or there may be requirements for using a particular setting (e.g. specific wine build / version) so I feel like being able to define custom ones would be the better option.

Example:
In this [ticket](https://github.com/lutris/lutris/issues/2297), there is mention of a new environment variable WINE_LARGE_ADDRESS_AWARE=1 which "only works for lutris, ge and tkg builds" of wine. It is also mentioned as a requirement for games running D9VK/DXVK. The option is not exposed in the UI (which I feel is very reasonable considering this option is both new and that it only works for very specific wine builds).

I would like to try this (and potentially other) settings even with D8VK/DXVK not selected. I already have Lutris v0.5.3 and the latest versions of the aforementioned wine builds installed, but there does not appear to be any obvious place to enter custom wine environment variables in Lutris.

In theory, I could just create a wrapper script under /usr/bin/ or similar which sets the flag and points to the appropriate wine binary under my lutris winesteam dir, then import that as a custom wine executable via the gui... but (a) that's not very convenient and (b) I bet there are a fair number of users who wouldn't bother/know how to do that.

It would be WAY more convenient if I could simply add any wine environment variable I want to set directly from the Runner options page, similar to how native steam users can configure launch options which include variables that get picked up by proton.

e.g.
Have a field name "Custom env vars:" -> I enter "WINE_LARGE_ADDRESS_AWARE=1" into a corresponding text input box then hit Save -> Yay!

which on the back-end would then converted to something like:
$CUSTOM_VARS WINEPREFIX="${WINE_PREFIX}" "${SELECTED_WINE_BINARY}" "${EXE_TO_BE_RUN}" $EXE_ARGS

I apologize in advance if something like this already exists and I missed it... I did see the "Arguments" field (Game options for custom launchers / Run options for steam launchers) but those both appear to be "Arguments that get passed to the exe being launched by Wine/to steam" rather than arguments for wine itself. And I _did_ look through all the tabs slowly, googled, and tried to search tickets but didn't find anything. So if it **does** exist, might be worth considering a different label to make it more obvious for dummies like me :-)

**Comment by Myrddin-Wyllt** [comment]
![image](https://user-images.githubusercontent.com/42914865/65633639-2df15f00-dfa2-11e9-84dc-b9c6a6a11061.png)
![image](https://user-images.githubusercontent.com/42914865/65633690-4ceff100-dfa2-11e9-8b4b-ab984d17da39.png)

**Comment by zpangwin** [comment]
Thanks. Feel kinda embarrassed that I missed that but mine also has "terminal application" directly above it instead of "resolution" so not too much bc I thought it that the headers were for that.

![shutter-19-09-25-163905](https://user-images.githubusercontent.com/29719631/65638199-972d9e00-dfb3-11e9-8c85-0e27953b6d67.png)

I'll go ahead and close this out.
