### ISSUE TITLE
Lutris doesn't show right and left panel by default

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2367]
This is a very serious issue, because now new users, by default, only see this:
![image](https://user-images.githubusercontent.com/10602045/65707831-f8c63900-e095-11e9-8845-78819d1e3fdc.png)
which is very confusing, as Lutris is missing half of its UI, and it's not obvious it even exists as it's hidden under an option in a menu!
If you already have Lutris installed, reproduction is very easy: you just need to remove `lutris.conf` file from `~/.cache`.

**Comment by strycore** [comment]
This is fixed
