### ISSUE TITLE
Lutris 'remove from library' button doesn't work. 

### ISSUE THREAD

**Issue by vesterlay** [lutris/lutris#2372]
Wanted to remove league of legends from my list and it disappears, but comes back quickly after synchronisation with the web account. 

_Lutris: 0.5.2.2
OS: Manjaro 18.1.0 
Kernel: Linux 4.19.69-1-MANJARO_

**Comment by vesterlay** [comment]
Update: I figured this out.. I had to delete this manually through site. But still it's a shame that lutris is not doing it automatically..

**Comment by Adehom** [comment]
It was normal. When lutris is launched, it's synchronized your library with your web account library.
You need to delete this game in your web account library or doesn't add games in your web account library.

**Comment by vesterlay** [comment]
I think it shouldn't work that way, because after you log in 'remove from library' is quite useless. It should synchronize under the hood or there should be an additional button to remove a game from your web library. Currently it's not intuitive at all, why would I have two separate game libraries, when they can be one?

**Comment by Adehom** [comment]
It's can be an new functionality. I'm going to see what I can do for this.

**Comment by tannisroot** [comment]
> It should synchronize under the hood or there should be an additional button to remove a game from your web library.
It absolutely should. Can you open a new issue for that to avoid confusion? Thanks.
