### ISSUE TITLE
Galaxy Squad is not imported by Lutris GOG Integration.

### ISSUE THREAD

**Issue by Patola** [lutris/lutris#2374]
**Describe the bug**

GOG Integration has already been working for me for some time on my Ubuntu 18.04.3 LTS. I resynchronized my list of GOG Games just after buying [Galaxy Squad](https://www.gog.com/game/galaxy_squad?pp=b2a10a6c3dcadb10c8ffd734c1bab896d55cf0ec). It appeared correctly on the list, but selecting and importing it yielded no result. As a control, I attempted the same operation with SOMA and it worked, and also sent the notification "1 game was imported to Lutris". Checking the two games and clicking on "Import Games" only sent me a notification that 1 game was imported. Note, as with SOMA, the game has a working Linux native version on GOG.

**Expected behavior**
Lutris should have imported Galaxy Squad and notified me that "1 game was imported to Lutris" as it did with SOMA. It works in the other GOG-compatible launcher [Games Nebula](https://github.com/yancharkin/games_nebula)

**Current behavior**
Checking "Galaxy Squad" on the list and clicking on "Import Games" does nothing. The game is not on my current games list.

**Steps to reproduce**
- Start Lutris
- Choose "import games"
- select GOG on the list. (you have to have your GOG credentials already configured)
- Choose one game to import, select "Import Games". It will work.
- Choose Galaxy Squad to import, it will not work.
- Message "No game found for 1911539873" appears on the console.

**Lutris debugging output**
NOTE: since the output is short, I just inserted it into the bug report instead of using pastebin or something.

```
INFO     2019-09-30 23:15:10,994 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-09-30 23:15:10,994 [startup.check_driver:54]:Using NVIDIA drivers 435.21 for x86_64
INFO     2019-09-30 23:15:10,994 [startup.check_driver:58]:GPU: GeForce GTX 1070
INFO     2019-09-30 23:15:10,995 [startup.check_driver:75]:GPU: 10DE:1B81 10DE:119D using nvidia drivers
INFO     2019-09-30 23:15:11,014 [startup.check_vulkan:129]:Vulkan is supported
INFO     2019-09-30 23:15:11,015 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-09-30 23:15:11,212 [store.get_missing_media:198]:Requesting missing icons from API for toonstruck, rockstar-games-launcher, steam32-xcom-bureau-endless-space-anomaly-2, the-king-of-fighters-2002, steam64, sunless-sea, willowtree
DEBUG    2019-09-30 23:15:11,212 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-30 23:15:11,213 [http.get:68]:GET https://lutris.net/api/runtime
INFO     2019-09-30 23:15:11,213 [lutriswindow.toggle_connection:580]:Connected to lutris.net as Patola
DEBUG    2019-09-30 23:15:11,215 [gog.get_library:175]:Returning cached GOG library
DEBUG    2019-09-30 23:15:11,215 [http.get:68]:GET https://lutris.net/api/games/library/Patola
DEBUG    2019-09-30 23:15:11,216 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-30 23:15:14,206 [api.get_game_api_page:132]:Loaded 4 games from page 1
INFO     2019-09-30 23:15:14,799 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-09-30 23:15:14,840 [api.get_game_api_page:132]:Loaded 28 games from page 1
DEBUG    2019-09-30 23:15:47,505 [gog.load_cookies:111]:Loading cookies from /home/patola/.cache/lutris/.gog.auth
DEBUG    2019-09-30 23:15:47,506 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:15:53,163 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:15:56,809 [gog.load_cookies:111]:Loading cookies from /home/patola/.cache/lutris/.gog.auth
DEBUG    2019-09-30 23:15:56,810 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:16:02,440 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:16:09,210 [gog.load_cookies:111]:Loading cookies from /home/patola/.cache/lutris/.gog.auth
DEBUG    2019-09-30 23:16:09,211 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:16:14,885 [http.get:68]:GET https://embed.gog.com/userData.json
DEBUG    2019-09-30 23:16:18,150 [gog.get_library:175]:Returning cached GOG library
DEBUG    2019-09-30 23:16:23,790 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-30 23:16:29,648 [api.get_game_api_page:134]:No game found for 1911539873
DEBUG    2019-09-30 23:16:35,814 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-09-30 23:16:41,690 [api.get_game_api_page:132]:Loaded 1 games from page 1
```

**System information**

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/3674110/lutris-issue-report.json.zip)

**Screenshots**
![Import games_194](https://user-images.githubusercontent.com/2991620/65929572-07d02280-e3d9-11e9-991d-78699a50a9f2.png)

**Comment by HerrIrrtum** [comment]
Can confirm. Exact same behavior with this game here.

**Comment by gatl** [comment]
I can see the same behaviour with _Total Annihilation: Commander Pack_, on GOG.

    DEBUG    2019-11-17 15:58:08,853 [http.get:68]:GET https://lutris.net/api/games
    DEBUG    2019-11-17 15:58:09,583 [api.get_game_api_page:134]:No game found for 1207658880

**Comment by liamhendricks** [comment]
Same issue for me with _Elder Scrolls IV, Oblivion GOTY_ on GOG.
```
DEBUG    2019-11-22 20:26:46,176 [http.get:68]:GET https://lutris.net/api/games
DEBUG    2019-11-22 20:26:46,793 [api.get_game_api_page:134]:No game found for 1458058109
```

**Comment by neroden** [comment]
Is there any GOG support in Lutris at all, actually?  I am getting the same debug errors, but it is now throwing a worse error, claiming that the game is already in the library.

**Comment by strycore** [comment]
we do not need importing GOG games anymore and every game should at least install whether or not they have installers
