### ISSUE TITLE
Some problems with the debian/control file in the source

### ISSUE THREAD

**Issue by stevenpusser** [lutris/lutris#2376]
First, Lutris is a pure python3 program, so it's architecture-independent. This means the Architecture field of the package needs to read "all", not "any".

Line 23 needs to be
`
X-Python3-Version: >= 3.4`

instead of 

`X-Python-Version: >= 3.4`

As it is, it's specifying python2 versions...

and  line 4 should read

`Build-Depends: debhelper (>= 9),`

Hope this helps!

Steve (lead MX Linux packager)

**Comment by Adehom** [comment]
In which file should we need to change this ?

**Comment by strycore** [comment]
The PR has been merged.
