### ISSUE TITLE
Import games parsing identifier issue

### ISSUE THREAD

**Issue by MrCapone** [lutris/lutris#2380]
If game has  trademark symbol (™) on its name lutris will add it to identifier during parsing.

**Expected behavior**

For example i have DARK SOULS™: REMASTERED installed on Steam with proton. Game has id on _[lutris.net](https://lutris.net/games/dark-souls-remastered/)_: **dark-souls-remastered**. I expecting that lutris will parse correct id to my library.

**Current behavior**

Lutris has parsed **dark-soulstm-remastered** id which is wrong.

Any game with trademark symbol affected. For example HITMAN™, STAR WARS™ Jedi Knight II: Jedi Outcast™ etc.

**Comment by LeXofLeviafan** [comment]
Current `slugify` implementation appears to be using [`unicodedata.normalize`](https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize) with `NFKD` form to convert names before stripping characters, which unfortunately includes special characters but ignores non-latin letters. A quick fix for this would be to use `NFD` which converts extended Latin to letters (like `ü` and `ç`) but doesn't convert special chars like `™` or `¹`. (It doesn't work on letters like `ß` but neither does `NFKD`…)
