### ISSUE TITLE
ePSXe Runner

### ISSUE THREAD

**Issue by trymeouteh** [lutris/lutris#2387]
There are runners for many emulators that focus on specific consoles such as PCSX2, Dolphin, Mupen64Plus. Please create a ePSXe runner too. ePSXe is the best PS1 emulator around. An easy script has been made to install it on Ubuntu distros and its in the AUR. Please add ePSXe as a Lutris runner!

https://github.com/brandleesee/ePSXe64Ubuntu

https://aur.archlinux.org/packages/epsxe

**Comment by AccountOneOff** [comment]
https://github.com/lutris/lutris/issues/594#issuecomment-392979510

**Comment by trymeouteh** [comment]
If it is in the AUR, wouldn't that mean it is open source?

**Comment by CartoonFan** [comment]
AUR seems to have software that is not open source, like [Skype](https://aur.archlinux.org/packages/skypeforlinux-stable-bin/) for example.

**Comment by trymeouteh** [comment]
How about making a ePSXe runner but it will require the user to install ePSXe on their system. The runner itself will not install ePSXe but allow you to run games in ePSXe from Lutris?
