### ISSUE TITLE
Steam Runner set OS

### ISSUE THREAD

**Issue by trymeouteh** [lutris/lutris#2388]
With the Dolphin runner, in the Configure->Game options tab you can choose weather the game is a Gamecube game or a Wii game. I think the Steam runner should have an option in the Configure->Game options tab to choose weather the game is a Linux game or a Windows game.

Most Steam games are Windows games and all of my Steam runners are under the Linux platform when most of my Steam games should be under the Windows platform.

I think this small addition to the Steam runner can easily help organise one's game library in Lutris.

**Comment by cbennydesuza8** [comment]
Why isn't this in an option for steam games? most steam games are made for windows and yet in lutris there under the linux os?

**Comment by tannisroot** [comment]
Pretty sure what you're describing should be covered by https://github.com/lutris/lutris/issues/1482.
