### ISSUE TITLE
Add the Game ID in --list-games

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#239]
Exposing the Game ID in `lutris --list-games` will allow third-party applications to launch Lutris games without having to go through the Lutris UI.

**Comment by RobLoach** [comment]
Just realized you can use `lutris lutris:supertux` rather than needing `lutris lutris:769`. Well done!

**Comment by strycore** [comment]
Eposing the id is still a good idea, it's totally possible to have several games with the same text identifier

**Comment by RobLoach** [comment]
Hit up https://github.com/lutris/lutris/pull/240 first.
