### ISSUE TITLE
League of Legends install Script seems to fail on KDE Neon

### ISSUE THREAD

**Issue by edenprojectde** [lutris/lutris#2390]
**Describe the bug**

Install script for League of Lutris is broken on Ubuntu/KDE Neon.

**Expected behavior**

A successful and running LoL installation.

**Current behavior**

League folder stays empty after installation. The Installer Script also shows errors on install.

**Steps to reproduce**

- Install League over the Installer Script https://lutris.net/games/league-of-legends/
- Result

**Lutris debugging output**

Short (only Lutris)
https://pastebin.com/dSYX13Mp
With -d
https://pastebin.com/5MLymcFv

**System information**

https://pastebin.com/LHqhniZP

**Screenshots**

-

**Comment by edenprojectde** [comment]
I can confirm this on a second machine also.

**Comment by Zeioth** [comment]
This should have been fixed. If not, please indicate if you are using wayland or xorg.
