### ISSUE TITLE
Draft install script for Steam runner doesn't fill application ID field

### ISSUE THREAD

**Issue by LeXofLeviafan** [lutris/lutris#2394]
Lutris v0.5.3 (installed from package manager)

When testing a draft script for a Steam game, the created game configuration consistently has an empty Application ID field (which is the one field that is absolutely required to run a Steam game).

Strangely enough, if you run the same script again _without removing the previously created game config_ (thus getting prompted to confirm a "reinstall"), the duplicate game configuration will be created _with_ the Application ID filled.

If it matters, external conditions for these cases are identical, as the game is already preinstalled in Steam itself (running an "install" is the simplest way to register an installed Steam game in Lutris currently, as "Import games" only registers the game as installed if it's not been registered to Lutris account).

Lutris debug output for both cases is identical (aside from ids and timestamps), sans for logging the "reinstall" confirmation:
```
2019-10-09 23:08:19,137: Action set to play
2019-10-09 23:08:19,137: Action set to install
2019-10-09 23:08:19,678: Action install confirmed
```
Although there _is_ an error printed after the "Saved game entry" line (in both cases):
```python
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/lutris/installer/interpreter.py", line 567, in _iter_commands
    self._finish_install()
  File "/usr/lib64/python3.6/site-packages/lutris/installer/interpreter.py", line 613, in _finish_install
    self.parent.on_install_finished()
  File "/usr/lib64/python3.6/site-packages/lutris/gui/installerwindow.py", line 437, in on_install_finished
    game = Game(game_data["id"])
KeyError: 'id'
```

**Comment by tannisroot** [comment]
I'm not sure this is a valid bug but the backtrace is worth looking at I guess.

**Comment by strycore** [comment]
I've read the current code and I don't see how this bug can be reproduced. I'm closing this, please reopen if still an issue in 0.5.5
