### ISSUE TITLE
battle.net app issue

### ISSUE THREAD

**Issue by rabbit24** [lutris/lutris#2397]
Hi there
my game diablo 3 was working perfect on Ubuntu. since the battle.net got an update. the battle net does not open up and i can not play. it freeze the all time. please look into the issue. 

Thanks
Marco

**Comment by b3nis** [comment]
I got the same with Battle.net, but I wanna play StarCraft II - you should probably change the title to Battle.net app issue.

**Comment by rabbit24** [comment]
Hi there. i just did. i hope the can sort this out though.

**Comment by AccountOneOff** [comment]
Thanks for the bug report. However, this doesn't sound like a Lutris issue but rather a Wine bug.

Open an issue here if you feel the need to: https://bugs.winehq.org/
