### ISSUE TITLE
Wiimotes not connecting to dolphin when launched though Lutris

### ISSUE THREAD

**Issue by JerareYoshi** [lutris/lutris#2399]
![Capture d’écran de 2019-10-13 15-07-09](https://user-images.githubusercontent.com/39435726/66716179-3384dc80-edcb-11e9-8959-2953009bc5c0.png)
Wiimotes can't be connected in dolphin when launched though Lutris.
It works with the Dolphin from Ubuntu repos.

I tried to enable/disable these options:
- Disable Lutris Runtime
- Prefer system libraries

This can be repoduced by launching Dolphin though Lutris, then in Controllers > Emulate the Wii's Bluethooth adapter > Wii Remote 1 > Real Wii Remote

**Comment by tannisroot** [comment]
I'll fix it when I update the Dolphin runner.

**Comment by strycore** [comment]
If this is related to the runner then this ticket should be in buildbot. Also, Dolphin has been updated since then so I'm gonna assume this is fixed.

**Comment by raulcraveiro** [comment]
I still can't connect my Wiimotes on the Dolphin runner. :/

**Comment by strycore** [comment]
Needs testing. I have some wiimotes laying around.

**Comment by raulcraveiro** [comment]
I can help testing ;)

**Comment by bigbruno** [comment]
Today in 5.0-11824 version, wiimote not connect too.

**Comment by strycore** [comment]
Can't reproduce, I can use my wiimote with the lutris build. Not with the Pop OS build.
