### ISSUE TITLE
[Feature] Application Bug Trackers

### ISSUE THREAD

**Issue by ItsMeMarioTheGreat22** [lutris/lutris#2402]
## Basic Information

**Feature**: Create bug tracker(s) for applications and proposed additions

**Why?**: Many applications on Lutris currently are broken like Fortnight [[1](http://web.archive.org/web/20191015044538/https://lutris.net/games/fortnite/)], while currently unlisted games like Roblox (_have?_) require external scripts for Linux. [[1](https://www.techwalla.com/articles/how-to-get-roblox-running-on-ubuntu),[2](https://roblox.fandom.com/wiki/Roblox_on_Linux)]

_Basically_, games change and it would be useful if users could discuss current issues and possible solutions. 

## More Information

**But bug trackers are only for code!**: Not necessarily, Peers has [peers /
peers-forum](https://notabug.org/peers/peers-forum) and IPFS has [ipfs/notes](https://github.com/ipfs/notes). 
<br/> Plus, Debian has a bug tracker for basically every application.
<br/>Example: https://bugs.debian.org/npm

__________________

**Comment by strycore** [comment]
We already kinda have that and it's not tracked on this repository anyway (it's on the website repo)
