### ISSUE TITLE
battle.net 

### ISSUE THREAD

**Issue by rabbit24** [lutris/lutris#2409]
Hi there
Just got an email from wine. they said i am suppose to report the issue with lutris team. i do not who to ask now. they said you do use non-wine software. so please fix my battle.net that does not open up since the update. please look into it.
Thanks
Marco

**Comment by codeman101** [comment]
I had the same problem you have to reinstall battle net although ever since then there always seems to be issues trying to get OverWatch to run correctly. I just reinstalled it today but I haven't tried it yet

**Comment by Zeioth** [comment]
I usually play hearthstone and battle.net works correctly. Please, follow the template we provide to fill bugs so we can do something about it. Also, indicate if you are experience the issue with an specific Lutris installer.

**Comment by rabbit24** [comment]
i have not tried that game yet. to be honest
