### ISSUE TITLE
Unable to open a game executable because the wine prefix is  a hidden folder

### ISSUE THREAD

**Issue by shag00** [lutris/lutris#2410]
When selecting a game to run a mini "explorer" window opens but does not display any of wine prefixes because they are all named. .wineXXXX. The problem is made worse because there does not appear to be provision to type the directory address,

**Expected behavior**

I was expecting 1 of 3 things:
1/ all directories displayed;
2/ a switch to display/hide hidden directories;
3/ a directory input line so i could type it in.

**Current behavior**

Only displays non hidden directories.

**Steps to reproduce**
Create a hidden directory/folder and try and access through the Lutris  explorer.

**Lutris debugging output**

Not applicable.

**System information**
Not applicable

**Screenshots**
Not really needed but availble if required.

**Comment by LeXofLeviafan** [comment]
The thing is, Lutris doesn't implement its own "Lutris explorer". It's using the system GTK file dialog, the very same that is used by browsers and such. And, though I'm not sure if you have exactly the same version as myself, but in the one I have there's a "Show Hidden Files" option in the popup menu (activated by right click anywhere in the file selection panel).

**Comment by shag00** [comment]
Ah yes, you are quite correct, the right click got me. Thank you for your reply and apologies for the trouble I put you to.

________________________________

**Comment by tannisroot** [comment]
I guess this got resolve so closing.
