### ISSUE TITLE
Configure caching/download directory as well as discarding installers after

### ISSUE THREAD

**Issue by OctarineSourcerer** [lutris/lutris#2411]
Currently with installer downloads, Lutris allows for:
- Discarding of installer files after install
- Caching installer files in a supplied path

The install files are discarded if the cache path is unsupplied, meaning there is no way to supply an alternate cache/download directory _and_ automatically delete them after. 

## Example case
I have a laptop with not much space left on the SSD, so I have connected an external HDD, which I intend to install the game on, without keeping the install files.

- I go to download a large game. 
- The download fails, as some way through there is not enough space to download more. 
- So I supply a directory in preferences to cache with (after deleting those files - I'm not sure how it would have gone if I moved those files to the new supplied directory). It is on the HDD, with much more space, and is therefore able to take the whole download
- As I have supplied this path, thereby also disabling discarding download files after download, I must go to this directory and delete the downloaded install files.

## Proposed changes
Change the caching preferences to, instead of supplying a path only, supply a download path for installer files and a checkbox for "discard installer files after install".

Should a download not have enough space, ask the user if there is another place they would like to download to instead, move downloads to there. It would be better if the client could quickly iterate through and get the metadata of _all_ the files it plans to download, so their size may be totalled and this warning could be displayed before downloading large amounts of data and only displaying it when it gets to the first chunk it cannot fit.

**Comment by LeXofLeviafan** [comment]
You can easily mount/symlink the Lutris cache folder to tmpfs though…

**Comment by OctarineSorcerer** [comment]
Apologies, hadn't been on GitHub for a little bit. Yes that's a possibility, but the user shouldn't be made to do that kind of thing to reproduce such functionality, and it shouldn't necessarily be assumed they have the ability to do so. 

It makes sense as an option, reducing both the work the user would have to do, and any likelihood of the procedure being messed up, etc. It also makes the scenario of discovering this is an issue before working around it yourself disappear.

**Comment by LeXofLeviafan** [comment]
>It also makes the scenario of discovering this is an issue before working around it yourself disappear.

How exactly do you expect a user who "doesn't have the ability to symlink a directory" to even consider working around it before he discovers the issue? AFAIK most users don't even try opening  preferences until they find out they need to change some…

**Comment by OctarineSorcerer** [comment]
I more meant that they wouldn't come across this, and then have to figure out how to get around it. In my case, I'm not quite familiar enough with symlinking to do it without a bit of google-fu, and so my response was changing the path, and then manually deleting them afterwards.

At least if the issue occurred, with this they'd open the preferences and see something related to it and able to fix it without further knowledge.

**Comment by LeXofLeviafan** [comment]
Well, that might work for some, I guess…
Though, honestly, it's rather better not to keep your `/home` on an SSD. It's not really something that can replace HDDs altogether, and amount of things that actually benefit from being there is rather limited to begin with.

**Comment by strycore** [comment]
This is solved in the file-selector branch
