### ISSUE TITLE
Auto update lutris runner with lutris updates

### ISSUE THREAD

**Issue by superbonaci** [lutris/lutris#2412]
Had lutris-4.13-x86_64 and had to manually download new runner 4.16 (which is now as default). couldn't it be done automatically?

**Comment by Zeioth** [comment]
It's been designed that way for stability reasons. The closest way to achieve what you are looking for is using your system's wine version.

![win](https://user-images.githubusercontent.com/3357792/68084401-3c4e5880-fe35-11e9-8b66-f01a979124cc.png)
