### ISSUE TITLE
lutris runner update requires game reinstall

### ISSUE THREAD

**Issue by superbonaci** [lutris/lutris#2413]
Had overwatch with runner lutris-4.13. After downloading manually 4.16, game will play sluggish and even link to executable was cleared. Could this be improved to doesn't mess things up?

**Comment by ZeikoFr** [comment]
Hi, I will need you to follow the required format for a bug report so anyone can have the necessary info to help you : https://github.com/lutris/lutris/issues/new?assignees=&labels=&template=lutris-bug-report.md&title=

**Comment by superbonaci** [comment]
Alright, will try to reproduce the issue when there's a Lutris update for ubuntu, but most likely will be in ubuntu 19.10 instead of 19.04.

**Comment by Zeioth** [comment]
The issue will be re-opened in case the missing information is submitted.
