### ISSUE TITLE
Open Source Game Clones

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#242]
Ran into this site:
http://osgameclones.com/

What Runners do you think would go well?

**Comment by strycore** [comment]
Most of them would not qualify as runners. Most Open Source game engines go into the "games" folder of the buildbot and are used in installer scripts. Engines that can handle a large amount of games and have lots of options can qualify as runners (all the Doom engines for example).
All other engines are treated as regular Linux games.

**Comment by strycore** [comment]
Also, this website seems to mix game engine that recreate the exact original game and open source games that were merely inspired by another game. Open source game that use different assets from the original game have their own page and are not listed as installers for the original game (for example, Frets on Fire is not going to be an installer for Guitar Hero, but Reminiscence is used for a Linux Flashback installer)

**Comment by RobLoach** [comment]
:+1:
