### ISSUE TITLE
Small bug about FPS limit

### ISSUE THREAD

**Issue by enesaltinkaya** [lutris/lutris#2427]
Hi,

Removing libstrangle, if a Fps limit is set beforehand breaks starting games.

To reproduce:
- Install libstrangle.
- Set a fps limit. Configure -> System options -> Fps limit, save.
- Remove libstrangle, restart Lutris. Fps limit option is now greyed but the set value is there.
- Try to start the game, watch console for python errors.

Version is lutris-0.5.3

Took me a while to figure it out.

`Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 519, in configure_game
    self.start_game()
  File "/usr/lib/python3.7/site-packages/lutris/game.py", line 533, in start_game
    self.game_thread.start()
  File "/usr/lib/python3.7/site-packages/lutris/command.py", line 111, in start
    logger.debug("Running %s", " ".join(self.wrapper_command))
TypeError: sequence item 3: expected str instance, NoneType found
`

**Comment by Adehom** [comment]
Hello @enesaltinkaya 
I think have find a corrective for your issue.
Can you try add in lutris/game.py file :
![image](https://user-images.githubusercontent.com/55432370/68195521-4d26d780-ffb7-11e9-9b9e-cd089ac68453.png)

**Comment by strycore** [comment]
Fix for this was merged
