### ISSUE TITLE
simpler icon chooser/system icons

### ISSUE THREAD

**Issue by lelgenio** [lutris/lutris#2428]
Right now when choosing an icon, Lutris opens a file dialog, but there is a icon dialog.
Here are some screenshots of menulibre, a program that uses this:
![image](https://user-images.githubusercontent.com/31388299/67641707-ed5b6d00-f8e2-11e9-8556-0b423028328e.png)
![image](https://user-images.githubusercontent.com/31388299/67641697-e03e7e00-f8e2-11e9-9d97-d496226dbf02.png)

Also, maybe we should check if there are system icons that match a game's slug name to use instead of the default one. this is mostly a problem on GNOME where icons are huge, and look like this:
![image](https://user-images.githubusercontent.com/31388299/67641810-fef14480-f8e3-11e9-9ef8-f92e28d94f82.png)
when it cloud look like this:
![image](https://user-images.githubusercontent.com/31388299/67641867-aff7df00-f8e4-11e9-8d1f-a020d370cf46.png)

**Comment by LeXofLeviafan** [comment]
>there is a icon dialog.

Actually there isn't. At least no generic-purpose one. The one in MenuLibre is implemented by the program itself.

>Also, maybe we should check if there are system icons that match a game's slug name to use instead of the default one.

It's not really a good thing to do _automatically_. Granted, most games have discernible names, but there's still quite a few more generic names that could certainly match an icon which has absolutely nothing to do with the game, or even games in general. (I actually encountered a similar problem when Lutris decided that some of the games from sgt-puzzles are actually games from its database based on the name alone, and refused to remove icon/poster of the detected game from them.)

**Comment by tannisroot** [comment]
Issue with low res icons is due to the fact that we get them from Steam and it only provides them in that resolution.
This should get resolved when website gets the option for users to submit their own icons for games.
Due to that and for reasons described above by someone else, closing.
