### ISSUE TITLE
Need instruction for configuration, in many game

### ISSUE THREAD

**Issue by Elrildu** [lutris/lutris#2437]
Many game on Lutris can't be install because we don't know witch parameter we must enter.
Hope some day, each game on Lutris will have it. I can tell problem for Diablo 2 or Worms. But they have others for sure.
It s a big task, so we have to be patient. But that must be done.

**Comment by Zeioth** [comment]
@Elrildu I'll see what I can do. Could you link what specific worms game you are speaking about?

**Comment by Elrildu** [comment]
Worms revolution
