### ISSUE TITLE
Add directory field and "Move" action to game config dialog.

### ISSUE THREAD

**Issue by Tibladar** [lutris/lutris#2439]
**Describe the bug**

When Lutris sets the `directory` key in pga.db and the location of the parent folder of `games` folder changes, `directory` isn't updated resulting in failing to execute pre-launch/post-end scripts (no permission at old location).
Here while trying to launch Overwatch pre-launch script:
(`/Lutris` was the old folder, `/Lutris2` the new)
```
ERROR    2019-11-03 16:58:00,974 [command.execute_process:230]:Failed to execute /usr/bin/lutris-wrapper 1 0 ctrl_fix_start.sh /Lutris2/games/overwatch/ctrl_fix_start.sh: [Errno 13] No permission: '/Lutris'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/command.py", line 219, in execute_process
    os.makedirs(self.cwd)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] No permission: '/Lutris'
```

**Expected behavior**

`directory` key should get updated

**Steps to reproduce**

- Install a game which has a prelaunch script and let Lutris set the `directory` key (e.g. Overwatch)
- Change the location of the parent folder of  the `directory` key on the drive
- Update all locations in Lutris UI
- Start the game and the start/stop script will fail (see above)

**Comment by strycore** [comment]
That needs to be implemented as part of the "Move game" feature.
