### ISSUE TITLE
Installing Anno 1800 fails with wine-tkg-4.6-x86_64.tar.xz not downloading

### ISSUE THREAD

**Issue by BRTPOB** [lutris/lutris#2440]
When attempting to install Anno 1800, or even trying to download the wine-tkg-4.6-x86_64.tar.xz file directly, the script and wget attempts will fail at 8 megabytes downloaded. Lutris will error out stating that "Compressed file ended before the end-of-stream marker was reached", while attempting to use wget will return the following:

```
--2019-11-03 18:09:42--  (try:20)  https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-tkg-protonified-4.6-x86_64.tar.xz
Connecting to lutris.nyc3.cdn.digitaloceanspaces.com (lutris.nyc3.cdn.digitaloceanspaces.com)|205.185.216.10|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 61085520 (58M), 52696912 (50M) remaining [application/octet-stream]
Saving to: ‘wine-tkg-protonified-4.6-x86_64.tar.xz’ wine-tkg-protonifie  13%[++                  ]   8.00M  --.-KB/s    in 0s 2019-11-03 18:09:43 (0.00 B/s) - Connection closed at byte 8388608. Giving up.

```
As you can see, wget attempted it 20 times and each time it failed at byte 8388608.

**Comment by BRTPOB** [comment]
As an addendum, I also tried using wget across two different machines in different locations and they both showed the same error with wget.

**Comment by tannisroot** [comment]
Something on your side is blocking our hosting service. It's usually due to interference from ISPs.
Seeing as this is not really our bug, I am closing the issue.
