### ISSUE TITLE
WineSteam Runner default arguments do not load the games list only black screen.

### ISSUE THREAD

**Issue by UXELDUXEL** [lutris/lutris#2451]
**Describe the bug**
The WineSteam Runner when started with default options will not load the new steam games library interface at all. Only a blank Screen is shown with a infinite loading screen. (I think SteamWebHelper is crashing in a endless loop)

**Expected behavior**
A Working Steam Games Library that is useable to for example manage stream launch options of games/beta participations etc etc.

**Current behavior**
Blank Screen
**Steps to reproduce**
- 1. Launch Lutris.
- 2. Install Winesteam runner.
- 3. Click the "Play" Button next the runner (at the left side of the lutris interface)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7772432/68529592-89806d80-0300-11ea-9059-adc2dceed53b.png)

**Solution I found to get everything going better**
Use the latest version of wine (4.19). The lutris build of wine works fine for that.
Change the offscreen rendering mode to "BackBuffer" <- This seems to be the most important one.

This will still show a black screen, however after a few seconds the black screen disappears completely and the ui will be completely useable. (Even the Steam Store now works)

I suggest making these options the default options for the winesteam runner (if no game is to be launcher, usually a games list is not required for launching a game. It is only required to tweak the settings of a winesteam game).

**Comment by mscansian** [comment]
Sadly it didn't work for me. I've changed the offscreen rendering to backbuffer but still get a black screen, even after a long time waiting.

**Comment by UXELDUXEL** [comment]
@mscansian Wine version 4.20 doesnt work for me either anymore but wine version 4.19 still works.

**Comment by strycore** [comment]
Wine Steam is very glitchy but now the content will show properly when the mouse hovers it. Going to close this since the client is somewhat usable. If this is to be reopened, it should go to the wine repo.
