### ISSUE TITLE
vulkan window dialog goes behind main window

### ISSUE THREAD

**Issue by superbonaci** [lutris/lutris#2454]
when the dialog box is displayed that I don't have vulkan support, eventually it may go behind the main Lutris windows, so I can't move or close the client. I have to realize that I have to minimize it clicking on the status bar to show the hidden dialog box.

Please fix so it stays on top until some action is taken.

**Comment by tannisroot** [comment]
I believe there is a very easy way to fix it so I'm tagging it for 0.5.4.

**Comment by strycore** [comment]
Can't get the DontShowAgainDialog to go under the main window. Which DE is being used here?

**Comment by superbonaci** [comment]
@strycore Plasma 5.17
`sudo add-apt-repository ppa:kubuntu-ppa/backports`

**Comment by strycore** [comment]
I have a Kubuntu 18.04 machine and this wasn't reproductible. Needs more testing.

**Comment by superbonaci** [comment]
The dialog that I don't have Vulkan support only happens when I install unofficial versions of the nvidia driver, but don't want to re-test it now. For some reason didn't/couldn't take screenshot, but will report again if happens next time.
