### ISSUE TITLE
pre/post commands aren't commands

### ISSUE THREAD

**Issue by nonchip** [lutris/lutris#2461]
after trying to figure out why lutris literally silently (even with `-d`) ignored whatever commands i put into the pre-launch and post-exit command fields, i realized from the code that you don't actually accept *commands* with arguments, but only single file paths without any arguments. might wanna change that to either:

- remove the `system.path_exists` because *why*? you could just show an error message if trying to actually run the "command" failed. often the user knows better than a single `if` in a python script. just try what they want and fail gracefully instead of literally deciding to ignore the setting.
- change it so it only sanity checks the first word (which will then fail as soon as people assume $PATH to work, like it would in any other "command" input box)
- or make it clear that you don't actually allow "commands" (as in "things you could give to `system`")

**Comment by tannisroot** [comment]
I'm going to just rename the option for now.
