### ISSUE TITLE
Failed to retrieve game library

### ISSUE THREAD

**Issue by Xvatten** [lutris/lutris#2462]
I'm trying to sync my games with Lutris.net when i get this message:
> GUI Message: "Failed to retrieve game library. There might be some problems contacting Lutris.net."

Terminal Output:

> INFO     2019-11-15 09:52:29,254 [application.do_command_line:225]:Running Lutris 0.5.3
> INFO     2019-11-15 09:52:29,254 [startup.check_driver:60]:Using X.Org
> INFO     2019-11-15 09:52:29,254 [startup.check_driver:62]:Running Mesa driver 19.2.4 on AMD NAVI10 (DRM 3.33.0, 5.3.11-ar
> INFO     2019-11-15 09:52:29,254 [startup.check_driver:73]:GPU: 1002:731F 1043:04E2 using amdgpu drivers
> WARNING: radv is not a conformant vulkan implementation, testing use only.
> INFO     2019-11-15 09:52:29,286 [startup.check_vulkan:129]:Vulkan is supported
> INFO     2019-11-15 09:52:29,287 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
> ERROR    2019-11-15 09:52:29,420 [jobs.target:32]:Error while completing task <bound method RuntimeUpdater.update of <lutr
> <class 'AttributeError'> module 'platform' has no attribute 'dist'
> INFO     2019-11-15 09:52:29,420 [lutriswindow.toggle_connection:580]:Connected to lutris.net as zengun
>   File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
>     result = self.function(*args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/lutris/runtime.py", line 143, in update
>     for remote_runtime in self._iter_remote_runtimes():
>   File "/usr/lib/python3.8/site-packages/lutris/runtime.py", line 152, in _iter_remote_runtimes
>     request = http.Request(RUNTIME_URL)
> ERROR    2019-11-15 09:52:29,421 [jobs.target:32]:Error while completing task <function sync_from_remote at 0x7fcabe0ad550
>   File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 48, in __init__
>     self.headers = {"User-Agent": self.user_agent}
>   File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 64, in user_agent
>     PROJECT, VERSION, " ".join(platform.dist()), platform.machine()
> <class 'AttributeError'> module 'platform' has no attribute 'dist'
>   File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
>     result = self.function(*args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/lutris/sync.py", line 87, in sync_from_remote
>     remote_library = api.get_library()
>   File "/usr/lib/python3.8/site-packages/lutris/api.py", line 86, in get_library
>     request = http.Request(url, headers={"Authorization": "Token " + credentials["token"]})
>   File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 48, in __init__
>     self.headers = {"User-Agent": self.user_agent}
>   File "/usr/lib/python3.8/site-packages/lutris/util/http.py", line 64, in user_agent
>     PROJECT, VERSION, " ".join(platform.dist()), platform.machine()
> INFO     2019-11-15 09:52:29,860 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
> INFO     2019-11-15 09:52:32,369 [application.do_shutdown:446]:Shutting down Lutris`

I'm running ArchLinux.

**Comment by BruceZhang1993** [comment]
It seems lutris is having issue running on Python 3.8
Waiting for PR

**Comment by tannisroot** [comment]
This is already fixed in master.

**Comment by Xvatten** [comment]
Thanks for fast apply. Installed git version instead. It's working. Thank you.

**Comment by tsndr** [comment]
When will the fixed version be released to the repos?
