### ISSUE TITLE
Right panel no longer updates its state after game exits

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2463]
How to reproduce:
1) Launch the game through right panel
2) Wait at least 1 minute (in order for playtime timer to increase)
3) Close the game through game itself and not Lutris.

Expected behavior: playtime gets updated and "Stop" button turns into "Play"
Observed Behavior: playtime stays the same and "Stop" button doesn't change into "Play" unless you reselect the game.
Probably caused by https://github.com/lutris/lutris/commit/47ecc419498abf127ee657fbc83bc313c883cb44

**Comment by strycore** [comment]
This bug is now #2473
