### ISSUE TITLE
Pass WINEDLLOVERRIDE to disable creation of Wine shortcuts

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2466]
Currently, Lutris disables creation of desktop shortcuts from Wine by making a registry key in the prefix.
However, because it happens after the generation of a Wine prefix, the shortcuts get generated anyway.
To solve this, I propose instead passing a `WINEDLLOVERRIDE` envar with the value being `winemenubuilder.exe=d`. By doing it this way, the menu builder will be disabled even when prefix gets created (during game installation).
However, the user should have the option to enable it, as some want Wine to generate shortcuts for type associations (for example, so that Photoshop could open .PSD files or Microsoft Word could open .DOC).

**Comment by rdaysky** [comment]
What’s wrong with having the shortcuts? Isn’t it quite convenient to have Lutris apps accessible using the system-wide launcher without any extra configuration?

**Comment by tannisroot** [comment]
Because in addition of shortcut creation, Wine almost creates MIME type associations with its internal apps like web browser, text editor and others, which is very annoying for a lot of users.

**Comment by soredake** [comment]
hope this will be fixed soon
