### ISSUE TITLE
Restarting Origin triggers "logins from too many different computers" account protection

### ISSUE THREAD

**Issue by JohanAR** [lutris/lutris#2471]
**Describe the bug**
Each time I start Origin through Lutris it seems like Origin thinks I'm logging in from a new computer, and if I have to do that 5 times within 24 hours I get locked out from my games.

According to [this comment](https://github.com/lutris/lutris/issues/808#issuecomment-375943089) it sounds like it has to do with Wine containers, but unfortunately I don't know enough about Wine/Lutris internals to add anything to that.

**Expected behavior**

Origin always running in the same container (if that's a thing)

**Current behavior**

Origin thinks each run is from a new computer

**Steps to reproduce**

1. Start Origin
2. Start Battlefield V
3. Close Origin
4. Repeat 5 times

**Lutris debugging output**

Nothing that looked relevant, but I can save and attach if necessary

**System information**

[lutris-issue-report.txt](https://github.com/lutris/lutris/files/3854728/lutris-issue-report.txt)

**Screenshots**

Not much to show, the popup says "Too many computers have accessed this accounts version of DisplayName field missing from registry. recently. Please try again later"

**Comment by tannisroot** [comment]
This should be resolved when we create an Origin runner.

**Comment by JohanAR** [comment]
> This should be resolved when we create an Origin runner.

That's nice to hear! Is there anywhere one can follow the progress of that? Issue #808 doesn't say if there's been any recent activity.

Should I close this issue, or keep it open until the solution has reached master?

**Comment by tannisroot** [comment]
I think it would be best to leave a comment describing your issue and how it's related to Origin runner in that issue and close this one.
