### ISSUE TITLE
Right panel font seems to try to bold an already bold font when a game is launched

### ISSUE THREAD

**Issue by tjackson** [lutris/lutris#2473]
**Describe the bug**
I can't reproduce this with the 0.5.3 version in the Arch repos, only when I build the git version myself.

The right panel by default seems to have a bold font for the game's runner. For example, a game that uses Windows has a wine glass icon and bold Windows text next to it. For some reason, that text turns really ugly when a game launches, almost like it's re-boldening it or completely loses its anti-aliasing.

**Expected behavior**

I would expect the font to look the same.

**Current behavior**

Currently the text turns ugly, see above.

**Steps to reproduce**

1. Install any game
2. Observe the changes in the right panel when it launches

**Lutris debugging output**

INFO     2019-11-18 00:52:36,120 [application.do_command_line:225]:Running Lutris 0.5.3
INFO     2019-11-18 00:52:36,120 [startup.check_driver:54]:Using NVIDIA drivers 440.31 for x86_64
INFO     2019-11-18 00:52:36,120 [startup.check_driver:60]:GPU: GeForce GTX 1050
INFO     2019-11-18 00:52:36,121 [startup.check_driver:77]:GPU: 8086:591B 1028:0798 using i915 drivers
INFO     2019-11-18 00:52:36,121 [startup.check_driver:77]:GPU: 10DE:1C8D 1028:0798 using nvidia drivers
INFO     2019-11-18 00:52:36,160 [startup.check_vulkan:132]:Vulkan is supported
INFO     2019-11-18 00:52:36,161 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-11-18 00:52:36,388 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2019-11-18 00:52:36,396 [store.get_missing_media:197]:Requesting missing icons from API for censored, censored, censored, censored
DEBUG    2019-11-18 00:52:36,396 [http.get:65]:GET https://lutris.net/api/games
INFO     2019-11-18 00:52:36,849 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-11-18 00:52:36,975 [api.get_game_api_page:134]:No game found for censored, censored, censored, censored

**System information**

2019-11-18 00:55:13,915: Running Lutris 0.5.3
2019-11-18 00:55:13,915: Using NVIDIA drivers 440.31 for x86_64
2019-11-18 00:55:13,916: GPU: GeForce GTX 1050
2019-11-18 00:55:13,916: GPU: 8086:591B 1028:0798 using i915 drivers
2019-11-18 00:55:13,916: GPU: 10DE:1C8D 1028:0798 using nvidia drivers
2019-11-18 00:55:13,959: Vulkan is supported
2019-11-18 00:55:13,960: Updating DXVK versions
2019-11-18 00:55:14,540: Updating D9VK versions
2019-11-18 00:55:19,055: Shutting down Lutris

**Screenshots**

pre-launch: 
![pre-launch](https://user-images.githubusercontent.com/4734979/69034616-e9c97c00-099e-11ea-8ab4-a3ee0079998b.png)

post-launch: 
![post-launch](https://user-images.githubusercontent.com/4734979/69034624-f057f380-099e-11ea-9533-5cc2a2c93177.png)

**Comment by tjackson** [comment]
This happens due to commit 56ff52d96bf892f7dafce8942d8fa062f9932ff7 but I don't know why ("Refresh right panel when a game is started").

**Comment by tannisroot** [comment]
It's not bolding, it's overlaying text upon some other text. I can reproduce this too:
![Screenshot from 2019-11-18 01-38-13](https://user-images.githubusercontent.com/10602045/69074607-c3f4b380-0a40-11ea-943c-9fe62055caf5.png)

**Comment by tannisroot** [comment]
@tjackson how did you find out that it's that commit? Did you perform a bisect?

**Comment by tjackson** [comment]
I didn't actually use the git bisect but git revert a bunch of times. I'm confident it's that one.

**Comment by tjackson** [comment]
Excuse me, I meant git reset --hard, not git revert

**Comment by strycore** [comment]
Marking that for 0.5.4 since I've managed to reproduce the issue while fixing another ticket.

**Comment by tjackson** [comment]
Awesome, thanks.
