### ISSUE TITLE
Wine installer without `files` section doesn't get Wine-specific envars passed on

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2480]
Can be reproduced with this
https://lutris.net/games/a-test-mtga-test/installer/edit
Results in a failure to create a prefix because the WINEPREFIX value that gets passed on is `None`.

**Comment by strycore** [comment]
This is the easiest way to distribute unverified files in installers.

**Comment by tannisroot** [comment]
Yeah Ik, I discovered the issue before noticing that the website is not an official one.
