### ISSUE TITLE
disable system variable

### ISSUE THREAD

**Issue by superbonaci** [lutris/lutris#2482]
here:

https://github.com/lutris/wine/issues/14#issuecomment-556882426

would like to be able to "disable" the variable `__GL_SHADER_DISK_CACHE_SKIP_CLEANUP` without having to remove it to test. So another column with a tick box `Enabled` will work. Instead of setting the var to 0 or 1 simulate it's removed altogether.

**Comment by strycore** [comment]
just put an extra character in the variable
