### ISSUE TITLE
Lutris doesn't detect Steam libraries on external hard drives 

### ISSUE THREAD

**Issue by Victor239** [lutris/lutris#2490]
In Steam I've got my default library pointed to an external hard drive, Lutris however doesn't detect the games there and I can't find any way to force Lutris to detect it.

**Comment by legluondunet** [comment]
I think I have the same issue on my computer and this could explain why I can not install Steam games with Lutris when the $STEAM function is called (Steam native Linux client).

**Comment by DAMO238** [comment]
I have also had this issue, although this did work a long time ago, before the redesign (I don't have the old packages in my cache anymore, so I am not sure what the version number was).

**Comment by frostworx** [comment]
Not sure if you have any use for it, but I more or less just ripped out [this](https://gist.github.com/frostworx/a19cf9113343d7193bf58db29172b679) from my launcher, after having seen [this](https://www.reddit.com/r/linux_gaming/comments/maexue/lets_test_lutris_bug_2490_games_on_external_hard/)

**Comment by strycore** [comment]
On my laptop, I have my Steam library on a SD card and I can launch game from Lutris just fine.

**Comment by strycore** [comment]
closing. Re-open with the necessary information to debug the issue if still present.
