### ISSUE TITLE
Update GZDoom Runner?

### ISSUE THREAD

**Issue by VortexAcherontic** [lutris/lutris#2491]
I am not sure where to put this but I noticed that Lutris (still) uses GZDoom 3.6.0 which is a bit outdated and not compatible with all latest Doom mods.

Maybe an update to a more recent version (currently ~4.2.4~ 4.3.3) might me a good thing.
I compiled the lates version on my own and placed the gzdoom binary in side ~/.local/share/lutris/runners/zdoom/ and every mod is now playable.

**Comment by xordspar0** [comment]
Can you clarify what you mean by "every mod is not playable"?

**Comment by VortexAcherontic** [comment]
Sorry a small typo I meant with the manually updated GZDoom binary I was able to play all recent and older mods just fine. The GZDoom binary shipped by Lutris is a little bit outdated and a lot of mods do not work properly. Bloom for example

**Comment by xordspar0** [comment]
Ah, I see. :smile:

That seems like an easy thing to fix, but I don't see in the code where that's determined. I don't know how runners work yet, unfortunately.

**Comment by strycore** [comment]
It's ok,I don't examples of mods that don't work. I'll just use my divination powers to figure out which ones need to be tested. Or I will test every single Doom mod ever made by mankind. Haven't decided yet.

**Comment by VortexAcherontic** [comment]
@strycore oof tough task :smile: I wish you all the best.

Just kidding, I could make an issue for each mod not playable with the currently shipped GZDoom runner but generally I would say using at least the latest stable release 4.3.3 should pretty much cover the most more recent mods.

> I was able to play all recent 
Let's say all mods I tried which are by far not all ever made wish of course would be ridiculous :smile:

**Comment by strycore** [comment]
I pushed a build of the latest version (64bit only, the 32bit build failed for some weird reason).

I'll test with Bloom to get started then I'll see if I need to test with every other possible mod :stuck_out_tongue:

**Comment by strycore** [comment]
I can't get that build to work, it keeps complaining about not finding the wad files.

**Comment by strycore** [comment]
Figured it out, the build is missing some pk3 files.

**Comment by strycore** [comment]
There we go: https://lutris.net/games/bloom/

**Comment by VortexAcherontic** [comment]
Nice :smile:
