### ISSUE TITLE
Doesn't work on Wine Steam runner via Lutris, works on wine runner.

### ISSUE THREAD

**Issue by Slyfox88** [lutris/lutris#2493]
Gamemode works correctly on the Wine runner in Lutris but doesn't activate on the Wine Steam runner. Both have identical launch perimeters:
Key=LD_PRELOAD Value=/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0

Ubuntu 19.10
Lutris 0.5.4 and same issue was on 0.5.3
Gamemode v1.5-dev 21 July 2019 according to man page

**Comment by RickAndTired** [comment]
Do you have Wine Steam running before you launch a game through Lutris?
You can't start Steam via Lutris on the side panel before you launch a game through Lutris. At least that's how it works with the regular non-wine Steam.
Might be related to #2690

**Comment by strycore** [comment]
We already have a ticket open for Gamemode, I'll close this one.
