### ISSUE TITLE
git tag duplicates

### ISSUE THREAD

**Issue by stephanlachnit** [lutris/lutris#2499]
There two tags in the repository which are duplicates:
`v0` at d5c2bd9, same as `v0.5.1.2`, and `0.5.2.2` at ad20eb2, same as `v0.5.2.2`
The `v0.5.0-beta` tag at 82d7328 is also somewhat suboptimal, since it's between `v0.5.0-beta1` and `v0.5.0-beta2`. Github shows the tag in the wrong order, so I would just remove it.
Also a little bit weird that `v0.5.0beta3` and `v0.5.0rc1` don't have a minus like `v0.5.0-beta1` and `v0.5.0-beta2`.

**Comment by tannisroot** [comment]
Fixed, not without an oopsie xD

**Comment by stephanlachnit** [comment]
I think you removed `0.5.2.2` and not `v0.5.2.2`, looking at github at least (haven't checked with git).

**Comment by stephanlachnit** [comment]
v0.5.5 got released but there is no tag yet, is that on purpose? Would start on the Debian package, but that doesn't work without a source tarball^^

Also, these are the commands I used to fix the tag ordering:
```bash
# this tags is labelled differently and causing a wrong order
git tag -d 0.5.2.2
git tag v0.5.2.2 ad20eb2
# remove beta tags because they just mess up the order completely
git tag -d v0.5.0-beta
git tag -d v0.5.0-beta1
git tag -d v0.5.0-beta2
git tag -d v0.5.0beta3
git tag -d v0.5.0rc1
```

Also on github one can promotes tags to releases, currently v0.5.2.1 is missing, and v0.5.2.2 will need to be redone after the tags are fixed.

**Comment by strycore** [comment]
> v0.5.5 got released but there is no tag yet

No it's wasn't.
Stop making ship up.

**Comment by strycore** [comment]
Dammit, how do other software projects handle this?
How can I bump the version number in my source code (because I *will* have to do it at some point) with people believing that I released something?

**Comment by stephanlachnit** [comment]
Ah ok sorry, just checked the older releases and there it was usually when the changelog entry was added.

**Comment by strycore** [comment]
No worry, the release is really due soon.

**Comment by stephanlachnit** [comment]
Btw the git tags are still pretty broken. Just keeping this list for me since pulling also pulls all tags.
```sh
git tag --delete v0 # is actually 0.5.1.2
git tag --delete 0.5.2.2 # wrong naming causes sorting issues on GitHub
git tag --delete v0.5.2.2 # this release isn't actually in the changelog nor in the master branch
git tag --delete v0.5.0rc1 # causes various sorting issues
git tag --delete v0.5.0beta3 # causes various sorting issues and is named inconsistent
git tag --delete v0.5.0-beta2 # causes various sorting issues
git tag --delete v0.5.0-beta1 # causes various sorting issues
git tag --delete v0.5.0-beta # causes various sorting issues
```

**Comment by strycore** [comment]
I've run the following command to delete the tags from github:

```
git push --delete origin v0 # is actually 0.5.1.2                                                              ─╯
git push --delete origin 0.5.2.2 # wrong naming causes sorting issues on GitHub
git push --delete origin v0.5.2.2 # this release isn't actually in the changelog nor in the master branch
git push --delete origin v0.5.0rc1 # causes various sorting issues
git push --delete origin v0.5.0beta3 # causes various sorting issues and is named inconsistent
git push --delete origin v0.5.0-beta2 # causes various sorting issues
git push --delete origin v0.5.0-beta1 # causes various sorting issues
git push --delete origin v0.5.0-beta # causes various sorting issues 
```

The v0.5.2.2 failed to delete but I'm not sure that's an issue.

**Comment by stephanlachnit** [comment]
Thanks!
Maybe because `v0.5.2.2` is not in the master branch? This should work
```
git fetch origin --tags
git push --delete origin v0.5.2.2
```
But it's not that important.

**Comment by strycore** [comment]
nope, it appears more than once.
```
git push --delete origin v0.5.2.2                                                                                                                                  ─╯
error: dst refspec v0.5.2.2 matches more than one
error: failed to push some refs to 'git@github.com:lutris/lutris'
```

**Comment by stephanlachnit** [comment]
Ahhhh. Now I got it.
```
git push origin :refs/tags/v0.5.2.2 # delete v0.5.2.2 tag
git fetch origin --prune --prune-tags # makes sure deleted tags on remote don't exist locally anymore
```

**Comment by strycore** [comment]
done!
