### ISSUE TITLE
Integrate the Lutris website into the client

### ISSUE THREAD

**Issue by seanbutnotheard** [lutris/lutris#250]
It would be nice to be able to open Lutris and add games to one's library that are listed on the Lutris web site without having to open a separate browser... something akin to the "store" part of the Steam client. It could be something as simple as a webkit frame that loads the site's "games" page and logs the user in automatically. (As a bonus, users would see Lutris news posts more easily as well!)

**Comment by strycore** [comment]
He plan adding this at some point but we'll probably render a special version of the website inside the client, not the current one (plus the current layout is not responsive so it won't adapt well inside the client)

**Comment by seanbutnotheard** [comment]
Great to hear! If this becomes a development focus I should be able to help, as I have a little bit of Django experience. Don't know a thing about desktop apps though. :D

**Comment by terndrup** [comment]
I know this is an old issue but I'd like to second this. The user experience would be miles better if you could just browse and install games/runners directly from the Client.

**Comment by AccountOneOff** [comment]
This can be closed.
