### ISSUE TITLE
Lutris always unresponsive on startup

### ISSUE THREAD

**Issue by ThaChillera** [lutris/lutris#2506]
**Describe the bug**
When starting lutris, it's always unresponsive on startup. I can't move the window, nothing shows etc. Then, after about 10 seconds, it displays all the games and acts normally again.

I assume during this hang time its loading information from disk, but this really shouldn't be done on the UI thread

**Expected behavior**
For the window to be moveable and resizeable whilst its loading my game library

**Current behavior**
See bug description

**Steps to reproduce**
Start Lutris

**Lutris debugging output**
`INFO     2019-12-01 18:51:56,427 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2019-12-01 18:51:56,428 [startup.check_driver:54]:Using NVIDIA drivers 440.36 for x86_64
INFO     2019-12-01 18:51:56,428 [startup.check_driver:60]:GPU: GeForce GTX 680
INFO     2019-12-01 18:51:56,428 [startup.check_driver:77]:GPU: 10DE:1180 3842:2686 using nvidia drivers
INFO     2019-12-01 18:51:56,468 [startup.check_vulkan:132]:Vulkan is supported
INFO     2019-12-01 18:51:56,470 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-12-01 18:51:56,833 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2019-12-01 18:51:56,842 [lutriswindow.toggle_connection:590]:Connected to lutris.net as ThaChillera
DEBUG    2019-12-01 18:51:56,843 [http.get:65]:GET https://lutris.net/api/games/library/ThaChillera
DEBUG    2019-12-01 18:51:56,855 [gog.get_library:176]:Returning cached GOG library
DEBUG    2019-12-01 18:51:56,914 [http.get:65]:GET https://lutris.net/api/games
INFO     2019-12-01 18:51:57,088 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-12-01 18:51:57,138 [store.get_missing_media:193]:Requesting missing icons from API for 36 games
DEBUG    2019-12-01 18:51:57,138 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2019-12-01 18:51:57,415 [api.get_game_api_page:132]:Loaded 100 games from page 1
DEBUG    2019-12-01 18:51:57,503 [api.get_game_api_page:132]:Loaded 33 games from page 1
`

**Comment by telanus** [comment]
Think this might have to do with Lutris' process whee it get's in contact with the server o see if there was any update to your linked website user, so that it can sync the local db with the servers db.

**Comment by tannisroot** [comment]
Can you provide more info please? Like which DE you use? A video that would showcase this would also be nice.

**Comment by ThaChillera** [comment]
Sure, I use KDE Plasma in Arch, and here is a link of a video: https://peertube.dk/videos/watch/6e2ec5be-4c2f-4191-9ae0-70e464046bd5

In that video, I try to drag the window & select buttons after startup, but it isn't responsive for the first ~15 to 20 seconds. (when it does become responsive the first drag fails (only goes down), that is due to DE settings & can be ignored)

**Comment by tannisroot** [comment]
The link you sent to me doesn't work. Can you upload it to something like Youtube instead?
Also, would you mind installing a GTK based DE, like Gnome, and checking whether it has the same issue?

**Comment by ThaChillera** [comment]
[Youtube link](https://youtu.be/c5-8EetPBBM ), although I can open the video in a private browser just fine, so do you have some crazy webbrowser or what?

I'll try another DE this weekend, don't have the time right now

**Comment by 7HEPOW** [comment]
@ThaChillera 
You don't happen to have **alot** of games in Lutris?
I have around 600 games in it and it takes a moment to show the window for me when launching Lutris. Due to the amount of banners etc. I would consider this as normal behaviour. :slightly_smiling_face:

**Comment by strycore** [comment]
This should be fixed now that all initialization is happening in its own window
