### ISSUE TITLE
Open RCT2 does not install.

### ISSUE THREAD

**Issue by Nilot352** [lutris/lutris#2512]
**Describe the bug**

OpenRCT2 does not proceed past the github package download step and throws the following error:

FileNotFoundError(2, 'No such file or directory')

**Expected behavior**

OpenRCT2 installs normally

**Current behavior**

OpenRCT2 does not install normally

**Steps to reproduce**

- Search for OpenRCT2 on lutris app.
- select install button
- wait for the message.

**Lutris debugging output**

The terminal output of `lutris -d`.
https://pastebin.com/y67iTiLW

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.
https://drive.google.com/open?id=1RunExiUmlyk4T51HK6LM2jzp2MDiBkYp

**Screenshots**

https://drive.google.com/open?id=1dRQzom9kHrPscIbQfi82hml0xgFjOiPn

**Comment by Mandy91** [comment]
It looks like the RCT2 demo is not available anymore to download...

**Comment by Mandy91** [comment]
I updated the file on Lutris, it is still in draft.
I tried installing it locally with exo-open "lutris:openrct2?revision=42177" but for some reason it cannot open it because the Lutris API cannot find my revision...

**Comment by legluondunet** [comment]
Hello, to install Rollercoaster Tycoon 2 with OpenRCT2 on Linux, please use only installers from this page: https://lutris.net/games/rollercoaster-tycoon-2/.
You will need the full game install from CD, GOG, Steam etc..
As the OpenRCT2 Lutris is not published nor validated, do not use it.

**Comment by legluondunet** [comment]
@strycore do we have to publish this page: https://lutris.net/games/openrct2/  or delete it? I think it's redundant with RCT2 Lutris page.

**Comment by strycore** [comment]
We don't make separate pages for Open Source engines. OpenRCT2 is still RollerCoaster Tycoon 2 so they should go on that page. We can create an alias to match both names on the same page.

**Comment by tannisroot** [comment]
this is fixed then i guess
