### ISSUE TITLE
[WIP] Epic Games Store Runner

### ISSUE THREAD

**Issue by buxel** [lutris/lutris#2521]
I'm not sure about the etiquette of asking questions in closed issues (#1794) but it has not received any attention, so I'm opening this one.

I started working on this because i was curious how Lutris works in general. Right now it's a big hack but it works for me. 

If there is interest in the community, I'd love to make this "production ready" together. It took some guesswork how things work in lutris so i definitely need some feedback on my [fork](https://github.com/buxel/lutris/tree/epic_games_store) and comments on [the changes i made](https://github.com/lutris/lutris/compare/master...buxel:epic_games_store).

> **Works**
> * Installing EGS as runner
> * Importer for installed games from EGS to lutris
> * Launching games
>   * Directly (DRM free)
>   * Trough EGS
> 
> **Issues**
> * still (ab)using steamId in some places
> * save/load game settings takes a while because wine registry is initialized each time (probably easy to fix)
> * lutris does not see game exiting, thinks its still running when launched trough EGS
> * most likely some dead code from winesteam
> 
> **Not working**
> * quit EGS after game exits
> * un/-install games (not sure if EGS supports this at all)

**Comment by tannisroot** [comment]
Great job! I would open a draft PR instead of an issue for this though.

**Comment by buxel** [comment]
Thank you! This is my first OSS contribution, so i'm still figuring things out.
Do you mean just open a PR marked as [Draft] in the title?
