### ISSUE TITLE
Games launched through shortcuts launch with fallback version of DXVK

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2522]
If you launch a game using a shortcut (or directly through terminal with a command like this `lutris  lutris:rungameid/109`) that DXVK without the version specified, the game will launch with a fallback DXVK version.
This doesn't happen if your turn off the internet or if you specify the version.
I suspect that this happens because Lutris modifies `dxvk_versions.json` on launch, so when Lutris also simultaneously tries to determine which latest version of DXVK it should use before launching the game, it fails to do that (as the file is being modified/changed) and uses the fallback version.
To fix this, Lutris might need to change the way it updates the `dxvk_versions.json` to avoid this issue.

**Comment by connectety** [comment]
> I guess DXVK might be affected as well

This does also affect DXVK
