### ISSUE TITLE
Steam play time not tracked

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2524]
When you launch a steam game via lutris, lutris doesn't keep track of the time you spend ingame. IE been playing Endless Sky, and according to Steam I've played 3 hours, and according to lutris I've only played 1 minute

**Comment by 7HEPOW** [comment]
Can confirm. Current behaviour:
**With Steam running**
- Launch Steam game from Lutris
- Game shows as running for a brief moment (1-5 seconds)
- Game doesn't show as running anymore, though it is still running

**With Steam not running**
- Launch Steam game from Lutris
- Game shows as running in Lutris
- Exit game not closing Steam
- Game shows as running in Lutris
- Close Steam manually
- Game doesn't show as running anymore

Time is tracked as long as Steam is running independent from the actual game. This is for Linux and Proton titles the same on my end.

I've noted this already a few months ago, but forgot to put it in... :slightly_smiling_face:

**Comment by theMarix** [comment]
Another side effect of this is that if you have any wrapper commands running–like `gamemoderun`–these will also exit before the actual game is running.

**Comment by strycore** [comment]
Closing that as a side effect of Steam games not being monitored.
