### ISSUE TITLE
Sonic Robo Blast 2

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#253]
https://github.com/STJr/SRB2

Something we could add to Lutris. @ProfessorKaos64 pointed it out on Reddit.

**Comment by ProfessorKaos64** [comment]
Let me know if you need any help with building this if you do add it.

**Comment by strycore** [comment]
I remember having a build of this, and that the setup method was downright stupid (I think it required Wine to extract some files) and undocumented.
This game need to be distributed in a single tar.gz containing everything (binaries + data) as it is very obvious that they aren't huge Linux fans.

**Comment by ProfessorKaos64** [comment]
I'll check my build script but it wasn't too hard yo make a Debian package.

**Comment by strycore** [comment]
Wait, this isn't the comment I came here to post. For game requests, the issues should go in the buildbot project for Open Source games or in the forums for generic game request.

**Comment by strycore** [comment]
@ProfessorKaos64 it wasn't hard to build the binaries but I remember having issues actually getting the data files for the game.

**Comment by ProfessorKaos64** [comment]
Hmm idk, I didn't have to fetch any data besides this. Maybe in the last it didn't use the open source Doom engine. 

On March 6, 2016 12:32:23 PM EST, Mathieu Comandon <notifications@github.com> wrote:
>@ProfessorKaos64 it wasn't hard to build the binaries but I remember
>having issues actually getting the data files for the game.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lutris/lutris/issues/253#issuecomment-192939535

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by strycore** [comment]
https://lutris.net/games/sonic-robo-blast-2/
