### ISSUE TITLE
Lutris does not respond when network operations take too long

### ISSUE THREAD

**Issue by Comevius** [lutris/lutris#2531]
Lutris takes several minutes to download DXVK and D9VK due to Github being unusally slow at this time (which I confirmed independently with curl). While waiting for the download to finish Lutris is either not responding, or the application I'm trying to run is not being run, despite Lutris indicating otherwise.

These network operations should happen in the background, and the user should be notified if they cause a delay.

```
DEBUG    2019-12-20 18:20:49,544 [downloader.start:55]:Starting download of:
 https://github.com/Joshua-Ashton/d9vk/releases/download/0.40.1/d9vk-0.40.1.tar.gz
```

**Comment by tannisroot** [comment]
This also happens when you open "Import Games" menu. It stalls for a substantial amount of time while it tries to fetch some info from GOG. Would be nice to make all of that fetching asynchronous.
