### ISSUE TITLE
Lutris logo

### ISSUE THREAD

**Issue by Raiden9** [lutris/lutris#2550]
The actual logo is ok but i wanted to improve it.
It's obviously an otter but with something of a salamander or a little dragon who are protected an egg.

https://www.deviantart.com/dakal-fr/art/Lutris-Logo-Test-Resolution-824940437
What do you think about it?

**Comment by an7ithe0s** [comment]
It seems like the creature in your version of the logo is really fat. :~) Otherwise it's nice.

**Comment by strycore** [comment]
The design is pretty cool and looks nice :D 
I wouldn't use it as a replacement for our current logo but that mascot could be integrated in some visual elements on the website, for example.

**Comment by Raiden9** [comment]
Ok, glad you like it. If you want the SVG version you can download it at:
http://calis-asso.org/lutris_logo.zip
CC By SA 4.0

Happy new year! :)

**Comment by strycore** [comment]
Happy new year!

Thanks for the SVG, I'm going to go on and close this issue and think about a way to integrate this somewhere :)
