### ISSUE TITLE
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'

### ISSUE THREAD

**Issue by sarnex** [lutris/lutris#2554]
**Describe the bug**
Lutris is failing to launch with the below error. I am using Python 3.6. Lutris used to work, but it recently started failing. I'm using Gentoo. Maybe this is related to a GTK update. My gtk is version 3.24.13

````
019-12-28 15:25:13,574: Running Lutris 0.5.4
2019-12-28 15:25:13,574: Using X.Org
2019-12-28 15:25:13,574: Running Mesa driver 20.0.0 on Radeon RX Vega (VEGA10, DRM 3.35.0, 5.4.6-gentoo, LLVM 9.0.1) (0x687f)
2019-12-28 15:25:13,574: GPU: 1002:687F 1DA2:E37F using amdgpu drivers
2019-12-28 15:25:13,574: GPU: 1002:6779 174B:E164 using radeon drivers
2019-12-28 15:25:13,588: Vulkan is supported
2019-12-28 15:25:13,589: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib64/python3.6/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib64/python3.6/site-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/usr/lib64/python3.6/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2019-12-28 15:25:13,774: Updating D9VK versions
````

**Expected behavior**

I expect it to open

**Current behavior**

It doesn't open

**Steps to reproduce**

- 1) Open lutris
-
-

**Lutris debugging output**

The terminal output of `lutris -d`.

Same as above output

**System information**

https://paste.ubuntu.com/p/SzVBJr47sD/

**Screenshots**

Not relevant

**Comment by Appadeia** [comment]
You probably want to share information on pygobject and gobject introspection version as well.

**Comment by sarnex** [comment]
pygobject : 3.32.1

gobject-introspection: 1.60.2

**Comment by gcarq** [comment]
I'm able to reproduce this. This happens with x11-libs/gtk+-3.24.13, however after downgrading to 3.24.11 lutris works again.

```
$ emerge --info gtk+
x11-libs/gtk+-3.24.11::gentoo was built with the following:
USE="X cups introspection wayland xinerama (-aqua) -broadway -cloudprint -colord -examples -gtk-doc -test -vim-syntax" ABI_X86="32 (64) (-x32)"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fno-plt -fuse-linker-plugin -tector -pipe"
```

**Comment by lo48576** [comment]
I tried to downgrade below packages (on gentoo linux) respectively, but they didn't help lutris work.

* Both dev-libs/gobject-introspection 1.60.2 -> 1.58.3 and dev-libs/gobject-introspection-common 1.60.2 -> 1.58.3
* dev-python/pygobject 3.32.1 -> 3.28.3

I didn't try downgrading all of them at the same time.

**Comment by linux923344** [comment]
I confirm after downgraded x11-libs/gtk+ . Lutris is working again. ( https://bugs.gentoo.org/704130)

**Comment by steils** [comment]
This patch works for me. Could you please test it with older version of gtk+, pygobject and gobject-introspection?

**Comment by linux923344** [comment]
After that upgrade the Lutris is running without any problem also with updated gtk+, pygobject and gobject-introspection. 
Thank You Guys!
Could you release new version of lutris after that I will upload the repo ( in my case Gentoo )?

**Comment by PLUkraine** [comment]
This issue happened to me today after I've upgraded the gtk3 package from 3.24.13-1 to 3.24.14-1. Downgrading back to 13 does help. But it is worth mentioning here anyway

**Comment by Porkepix** [comment]
@strycore @steils Looks like the issue is back, can we reopen please?
I was on the latest stable version, hence without the above patch (no new release since). Being on ArchLinux, I picke the lutris-git package instead to compile latest master, and same result: Lutris is able to show the support pop-up, and then crashes:

```
Feb 18 00:07:45 T470-clement systemd[795]: Started Application launched by gnome-shell.
Feb 18 00:07:45 T470-clement dleyna-renderer-service[9203]: Client :1.260 lost
Feb 18 00:07:46 T470-clement net.lutris.Lutris.desktop[1409]: 2020-02-18 00:07:46,304: Running Lutris 0.5.4
Feb 18 00:07:46 T470-clement net.lutris.Lutris.desktop[1409]: 2020-02-18 00:07:46,304: Using Intel Open Source Technology Center
Feb 18 00:07:46 T470-clement net.lutris.Lutris.desktop[1409]: 2020-02-18 00:07:46,304: Running Mesa driver 19.3.4 on Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  (0x1916)
Feb 18 00:07:46 T470-clement net.lutris.Lutris.desktop[1409]: 2020-02-18 00:07:46,304: GPU: 8086:1916 17AA:2245 using i915 drivers
Feb 18 00:07:46 T470-clement net.lutris.Lutris.desktop[1409]: 2020-02-18 00:07:46,313: Vulkan is supported
Feb 18 00:07:46 T470-clement dleyna-renderer-service[9203]: dLeyna: Exit
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]: Traceback (most recent call last):
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:   File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:     if not self.run_in_background:
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:   File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:     self.game_store = self.get_store()
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:   File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:     return settings.read_setting("filter_installed").lower() == "true"
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:   File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]:     )
Feb 18 00:07:50 T470-clement net.lutris.Lutris.desktop[1409]: AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
Feb 18 00:07:50 T470-clement systemd[795]: gnome-launched-net.lutris.Lutris.desktop-9082.scope: Succeeded.
Feb 18 00:07:55 T470-clement systemd[795]: gnome-terminal-server.service: Succeeded.
```

For the needed informations:
Lutris latest master - `Version         : 0.5.4.r134.g870428a8-1`
GTK3 (updated today - might be what broke Lutris) - `Version         : 1:3.24.14-1`
python-gobject - `Version         : 3.34.0-3`
gobject-introspection - `Version         : 1.62.0-3`

**Comment by Porkepix** [comment]
Downgrading the gtk3 didn't fix things.
From what I can read from my logs, Lutris was for the last time used successfully on 14th february.

Here are the packages updated since then:
```
[2020-02-16T19:51:44+0100] [ALPM] installed rhash (1.3.9-1)
[2020-02-16T19:51:44+0100] [ALPM] installed cmake (3.16.4-1)
[2020-02-16T19:51:44+0100] [ALPM] installed docbook-xml (4.5-8)
[2020-02-16T19:51:45+0100] [ALPM] installed docbook-xsl (1.79.2-5)
[2020-02-16T19:51:45+0100] [ALPM] installed glib2-docs (2.62.4-2)
[2020-02-16T19:51:45+0100] [ALPM] installed python-anytree (2.8.0-1)
[2020-02-16T19:51:46+0100] [ALPM] installed gtk-doc (1.32-2)
[2020-02-16T19:51:46+0100] [ALPM] installed netpbm (10.73.30-1)
[2020-02-16T19:51:46+0100] [ALPM] installed gts (0.7.6.121130-1)
[2020-02-16T19:51:46+0100] [ALPM] installed graphviz (2.42.3-2)
[2020-02-16T19:51:47+0100] [ALPM] installed vala (0.46.6-1)
[2020-02-16T21:12:38+0100] [ALPM] installed detox (1.3.0-2)
[2020-02-18T00:06:55+0100] [ALPM] installed xorg-server-xvfb (1.20.7-1)
[2020-02-18T00:06:55+0100] [ALPM] installed xorg-luit (1.1.1-3)
[2020-02-18T00:06:55+0100] [ALPM] installed xbitmaps (1.1.2-1)
[2020-02-18T00:06:55+0100] [ALPM] installed xterm (353-1)
[2020-02-18T00:06:55+0100] [ALPM] installed python-nose (1.3.7-6)
[2020-02-18T00:06:55+0100] [ALPM] installed python-coverage (4.5.4-3)
[2020-02-18T00:06:55+0100] [ALPM] installed python-nose-cover3 (0.1.0-5)
[2020-02-18T00:07:31+0100] [ALPM] installed lutris-git (0.5.4.r134.g870428a8-1)
[2020-02-18T00:32:35+0100] [ALPM] installed python-anytree (2.7.3-1)
[2020-02-18T00:33:53+0100] [ALPM] installed xorg-server-xvfb (1.20.7-1)
[2020-02-18T00:33:53+0100] [ALPM] installed xorg-luit (1.1.1-3)
[2020-02-18T00:33:53+0100] [ALPM] installed xbitmaps (1.1.2-1)
[2020-02-18T00:33:53+0100] [ALPM] installed xterm (353-1)
[2020-02-18T00:33:53+0100] [ALPM] installed python-nose (1.3.7-6)
[2020-02-18T00:33:53+0100] [ALPM] installed python-coverage (4.5.4-3)
[2020-02-18T00:33:53+0100] [ALPM] installed python-nose-cover3 (0.1.0-5)
[2020-02-18T00:34:00+0100] [ALPM] reinstalled lutris-git (0.5.4.r134.g870428a8-1)
```

**Comment by santisteban** [comment]
@PLUkraine @Porkepix A temporary solution until this is patched is to replace `Gtk.TreeModelSort.sort_new_with_model` with `Gtk.TreeModelSort.new_with_model` in `/usr/lib/python3.8/site-packages/lutris/gui/views/store.py`.

**Comment by krathalan** [comment]
I was in the process of filing a new bug when I found this one. @Porkepix downgrading gtk3 to 3.24.13 fixes the issue for me -- did you downgrade via the pacman cache (`sudo pacman -U /var/cache/pacman/pkg/gtk3-1\:3.24.13-1-x86_64.pkg.tar.xz`)? 

The terminal output of `lutris -d` with newest gtk3 version 3.24.14:

```

(lutris:6672): GVFS-WARNING **: 22:13:42.168: Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.Daemon: Unit gvfs-daemon.service is masked. (g-io-error-quark, 36)


(lutris:6672): dbind-WARNING **: 22:13:42.211: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.systemd1.UnitMasked: Unit at-spi-dbus-bus.service is masked.
INFO     2020-02-17 22:13:42,591 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-02-17 22:13:42,591 [startup.check_driver:54]:Using NVIDIA drivers 440.59 for x86_64
INFO     2020-02-17 22:13:42,592 [startup.check_driver:60]:GPU: GeForce GTX 980 Ti
INFO     2020-02-17 22:13:42,592 [startup.check_driver:77]:GPU: 10DE:17C8 1462:3232 using nvidia drivers
INFO     2020-02-17 22:13:42,622 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-02-17 22:13:42,623 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-02-17 22:13:42,895 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
```

The terminal output of `lutris -d` after downgrading to gtk3 3.24.13:

```
(lutris:6755): GVFS-WARNING **: 22:14:39.374: Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.Daemon: Unit gvfs-daemon.service is masked. (g-io-error-quark, 36)


(lutris:6755): dbind-WARNING **: 22:14:39.417: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.systemd1.UnitMasked: Unit at-spi-dbus-bus.service is masked.
INFO     2020-02-17 22:14:39,799 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-02-17 22:14:39,799 [startup.check_driver:54]:Using NVIDIA drivers 440.59 for x86_64
INFO     2020-02-17 22:14:39,799 [startup.check_driver:60]:GPU: GeForce GTX 980 Ti
INFO     2020-02-17 22:14:39,799 [startup.check_driver:77]:GPU: 10DE:17C8 1462:3232 using nvidia drivers
INFO     2020-02-17 22:14:39,836 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-02-17 22:14:39,837 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-02-17 22:14:40,021 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-02-17 22:14:40,268 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
```

And the window appears as expected.

**Comment by Porkepix** [comment]
Well, it should have fix it, but for me it didn't and I don't understand why. On top of that, when launched from the terminal it just « breaks » it, ie. even ctrl-c does not work to interrupt it and I can't get my prompt back.

**Comment by Nocifer** [comment]
@Porkepix maybe the gtk3 library was still loaded in your system's memory and used by other processes. For what it's worth, after updating gtk3 to 3.24.14 yesterday, at first Lutris wouldn't even produce any errors in the terminal output and would just silently launch with an "invisible" main window, even across multiple reboots. It was only after I reinstalled it, with gtk3 3.24.14 already installed, that it actually complained with this sort_new_with_model error. Probably a shared lib thing again.

On topic, downgrading to gtk3 3.24.13 definitely "fixes" the issue.

**Comment by Kodehawa** [comment]
Seems like the issue is back.

**Comment by krathalan** [comment]
The issue seems to be fixed for me with the latest `lutris` package 0.5.4-2 on the Arch repos.

**Comment by Porkepix** [comment]
Seems patched by https://git.archlinux.org/svntogit/community.git/tree/trunk/sort_new_with_model_fix.patch?h=packages/lutris

**Comment by fredoche** [comment]
I believe this bug to be present on fedora 32 beta as well. Cheers

**Comment by hrkrx** [comment]
happens too, on Ubuntu 20.04

**Comment by FireCulex** [comment]
![Screenshot from 2020-03-28 08-11-29](https://user-images.githubusercontent.com/9983630/77826357-14a1aa80-70cc-11ea-96bc-4c273e6af340.png)
RIP.

**Comment by ChemiKyle** [comment]
This is happening to me as well in Debian testing; `lutris -v` ends without returning anything, but I installed Lutris via package manager and have run `update` and `upgrade` to no avail.

**Comment by ca1ek** [comment]
the same issue surfaced for me today after upgrading Debian Testing
```
2020-04-18 20:53:43,373: Running Lutris 0.5.4
2020-04-18 20:53:43,373: Using NVIDIA drivers 440.82 for x86_64
2020-04-18 20:53:43,373: GPU: GeForce GTX 1050 Ti
2020-04-18 20:53:43,373: GPU: 10DE:1C82 19DA:A454 using nvidia drivers
2020-04-18 20:53:43,463: Vulkan is supported
2020-04-18 20:53:43,464: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-04-18 20:53:44,396: Updating D9VK versions

```

**Comment by Steinhagen** [comment]
@ca1ek You should try using the latest Lutris version. As you can see, your current version is pretty old:
`2020-04-18 20:53:43,373: Running Lutris 0.5.4`

**Comment by ca1ek** [comment]
> @ca1ek You should try using the latest Lutris version. As you can see, your current version is pretty old:
> `2020-04-18 20:53:43,373: Running Lutris 0.5.4`

thanks for the fast reply. I noticed my `/etc/apt/sources.list.d/lutris.list` file pointed still at Debian 9, I swapped it to 10 and am currently upgrading, will report if this resolves the issue.

**Comment by banchaa** [comment]
> @PLUkraine @Porkepix A temporary solution until this is patched is to replace `Gtk.TreeModelSort.sort_new_with_model` with `Gtk.TreeModelSort.new_with_model` in `/usr/lib/python3.8/site-packages/lutris/gui/views/store.py`.

Just changing the string in "store.py" did it for me too. I'm currently on Debian Testing (Bullseye) with KDE Plasma . The path to the store.py file was a bit different for me: /usr/lib/python3/dist-packages/lutris/gui/views/store.py

You might search the file location of store.py for your specific Distribution separately.

**Comment by strycore** [comment]
Update to the current lutris version.
