### ISSUE TITLE
Restore resolution on game exit sets scale to 200% instead of back to 100%

### ISSUE THREAD

**Issue by Morpheus0x** [lutris/lutris#2557]
OS: Manjaro
DE: Budgie

Game is Warcraft III non Battle.net version, Switch to resolution 800x600 is active. After exiting the game the resolution is restore to 2560x1440 but with Scaling set to 200% instead of the previous 100%.

**Comment by rawbits2010** [comment]
not sure if I understand this right but I also have 2x scaled display after games and have to run xrandr --output xxx --scale 1x1 after each game.
starting the game sets the resolution to the correct 1920x1080 1x1 first and then to the requested one (1280x720) for the game. and the resolution is set again after quitting the game but the scale won't change back.
is this that hard to fix?

**Comment by strycore** [comment]
We'll be removing all options regarding display management in a near future release.
We highly encourage users to use gamescope, which resolves most display related issues. 

There isn't a way to move forward with display configuration options with Wayland so Lutris will no longer try to manage those things.
