### ISSUE TITLE
Lutris "Dock Icon"

### ISSUE THREAD

**Issue by cybik** [lutris/lutris#2560]
This kind of just hit me, and I don't see either an active issue nor an option in the software, so here it is:

It would be interesting to have a "dock"/"systray" icon from which one can launch up to 5-7 favorite games, and which would keep Lutris active without having the window open.

**Comment by strycore** [comment]
I added an AppIndicator based tray icon and also put back the legacy one as a fallback. It will be available in the next release so marking this as done.
