### ISSUE TITLE
Add Fedora 31 and Ubuntu 19.10 troubleshoot on overwatch wiki

### ISSUE THREAD

**Issue by otavioschwanck** [lutris/lutris#2562]
After a long time trying, i manage to play Overwatch on Fedora 31.

The error is: General Error 0xE0010160 

1 - Install vulkan: 
sudo dnf install vulkan-loader vulkan-loader.i686

2 - Click on configure in overwatch icon

3 - Go to System Options and add a Enviroment Variable with:

VK_ICD_FILENAMES = /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json

For Ubuntu 19.10, use /usr/share/vulkan/icd.d/nvidia_icd.json instead for nvidia

OBS:  Change nvidia_cd to intel_icd or radeon_icd depending of your graphic driver.

Thats it

**Comment by tannisroot** [comment]
I added the vulkan loader bit, and there's already an option for choosing the loader.
