### ISSUE TITLE
Packages for Ubuntu 18.10 (cosmic) are not in PPA

### ISSUE THREAD

**Issue by mpnordland** [lutris/lutris#2571]
**Describe the bug**

There are no packages for Ubuntu 18.10 (cosmic) in the PPA

**Expected behavior**

Packages for cosmic available in PPA

**Current behavior**

There are no packages for Ubuntu 18.10 (cosmic) in the PPA

**Steps to reproduce**

- Follow the instructions to add the PPA to an Ubuntu cosmic installation
- Installation fails because it cannot find package 'lutris'

**Comment by stephanlachnit** [comment]
Looks like it wasn't uploaded. You can temporarily just use the Bionic package (or from any other series), should work without any problems.

**Comment by strycore** [comment]
Ubuntu 18.10 is no longer supported in Launchpad so packages can't be copied to cosmic.
If you *MUST* stay on 18.10 for any reason, using the packages from another release will work. But I highly recommend updating to something current.

![Screenshot from 2020-01-05 16-03-17](https://user-images.githubusercontent.com/280336/71788221-fc425800-2fd4-11ea-8c14-f032f647e64e.png)
