### ISSUE TITLE
Destroy the non-free Flaticon icons

### ISSUE THREAD

**Issue by JohnScott623** [lutris/lutris#2573]
Hello,
I've noticed in share/lutris/icons/hicolor/symbolic/apps/ that there are many icons, and copyright.old has some information on their licenses. Many are bound by these Flaticon terms, and the [concise summary](https://file000.flaticon.com/downloads/license/license.pdf) makes clear:
### What you CAN NOT DO:
* Distribute Flaticon Contents unless it has been expressly authorized by Flaticon
* Include Flaticon Contents in an online or online database or file
* Offering Flaticon Contents designs for download

Clearly this is not okay, and they're stuck in the git history.

**Comment by strycore** [comment]
> and they're stuck in the git history.
No one cares about that bit.

**Comment by strycore** [comment]
> This license allows you to use for free any of Flaticon contents for your projects as long as they are
attributed to their author in the definitive project.

That's what the license says, that's what we're doing. Stop being paranoid and learn out to read legal licenses.
