### ISSUE TITLE
winetricks command is not syncronous

### ISSUE THREAD

**Issue by buxel** [lutris/lutris#2574]
Opening this after checking with @openglfreak 

**Describe the bug**
The `winetricks` command is not syncronous, because it calls `wineexec` [non-blocking](https://github.com/lutris/lutris/blob/master/lutris/runners/commands/wine.py#L361). 
This causes unexpected behavior if a runner, which depends on some tricks, is being installed. Winetricks might not finish before the setup of the runner is started.

**Expected behavior**
`winetricks` should call `wineexec` with `blocking=True`.

**Issues**
If winetricks and/or the silent installation of a runner takes a long time, the download dialog from the runner setup and/or lutris might appear frozen.

**Comment by strycore** [comment]
will be fixed when the Epic store integration lands

**Comment by strycore** [comment]
closing because I have never experienced this, winetricks works as expected.
