### ISSUE TITLE
KDE Wayland Window Decoration issue

### ISSUE THREAD

**Issue by TRPB** [lutris/lutris#2575]
**Describe the bug**

When running on KDE Wayland, the window decorations are incorrect. There are two distinct issues:

1. There is no minimize or maximize button
2. There is an window enforced gap around the window. See my sc

I am not sure if this is a KDE bug, GTK bug or a lutris bug but it seems lutris specific.

Screenshot: 
![Screenshot_20200105_150625](https://user-images.githubusercontent.com/2454540/71782008-fd6f8700-2fcc-11ea-8779-5088839a4eb0.png)

I have tiled Lutris and Firefox. There should be no gaps around the window but there are, and the minimize and maximize buttons are missing

**Expected behavior**

The window should be drawn with the correct decorations.

**Steps to reproduce**

- Run Lutris on KDE Wayland
- Possibly on a high dpi monitor, I'm running 3840x2160

The terminal output of `lutris -d`.

```
INFO     2020-01-05 15:07:40,479 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-01-05 15:07:40,479 [startup.check_driver:62]:Using X.Org
INFO     2020-01-05 15:07:40,479 [startup.check_driver:64]:Running Mesa driver 19.3.1 on AMD Radeon VII (VEGA20, DRM 3.35.0, 5.4.7-arch1-1, LLVM 9.0.0) (0x66af)
INFO     2020-01-05 15:07:40,479 [startup.check_driver:77]:GPU: 1002:66AF 1002:081E using amdgpu drivers
INFO     2020-01-05 15:07:40,540 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-01-05 15:07:40,541 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-01-05 15:07:40,771 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-01-05 15:07:40,771 [store.get_missing_media:197]:Requesting missing icons from API for freelancer
DEBUG    2020-01-05 15:07:40,779 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-01-05 15:07:40,949 [api.get_game_api_page:132]:Loaded 1 games from page 1
INFO     2020-01-05 15:07:41,168 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
```

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/4023514/lutris-issue-report.zip)

**Comment by tannisroot** [comment]
There's absolutely no way it's our bug as it works perfectly fine under Gnome and other DEs, like LXQT.
