### ISSUE TITLE
d9vk not works Sapphire r9 270

### ISSUE THREAD

**Issue by BLOODYCOOT** [lutris/lutris#2577]
**Describe the bug**

i installed step by step but d9vk not works.

**Expected behavior**

goes well work with my video card.

**Current behavior**

useless

**Steps to reproduce**

- install lutris from main page
- install wine from https://github.com/lutris/lutris/wiki/Wine-Dependencies
- install AMD / Intel driver from https://github.com/lutris/lutris/wiki/Installing-drivers#installing-vulkan
- i installed d9vk from https://github.com/Joshua-Ashton/d9vk and not works.

**Lutris debugging output**

> Gtk-Message: 18:07:44.747: GtkDialog mapped without a transient parent. This is discouraged.
INFO     2020-01-06 18:07:45,876 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-01-06 18:07:45,877 [startup.check_driver:62]:Using X.Org
INFO     2020-01-06 18:07:45,877 [startup.check_driver:67]:Running Mesa driver 19.0.8 on AMD PITCAIRN (DRM 2.50.0, 5.0.0-37-generic, LLVM 8.0.0) (0x6811)
INFO     2020-01-06 18:07:45,877 [startup.check_driver:79]:GPU: 1002:6811 174B:E271 using radeon drivers
INFO     2020-01-06 18:07:45,911 [startup.check_vulkan:134]:Vulkan is not available or your system isn't Vulkan capable
INFO     2020-01-06 18:07:45,912 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-01-06 18:07:46,059 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-01-06 18:07:46,060 [lutriswindow.toggle_connection:590]:Connected to lutris.net as crashban
DEBUG    2020-01-06 18:07:46,061 [http.get:65]:GET https://lutris.net/api/games/library/crashban
INFO     2020-01-06 18:07:46,546 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2020-01-06 18:08:14,153 [application.launch:339]:Launching League of Legends (wine) (139828051874152)
DEBUG    2020-01-06 18:08:14,171 [game.play:295]:Prelaunching <lutris.runners.wine.wine object at 0x7f2c4211a4e0>
INFO     2020-01-06 18:08:14,668 [dxvk.disable_dxvk_dll:180]:Removing DXVK dll /root/Games/league-of-legends/drive_c/windows/system32/d3d9
INFO     2020-01-06 18:08:14,668 [dxvk.enable_dxvk_dll:160]:Replacing /root/Games/league-of-legends/drive_c/windows/system32/d3d9 with D9VK version
DEBUG    2020-01-06 18:08:14,669 [display._get_vidmodes:15]:Retrieving video modes from XrandR
Gtk-Message: 18:08:14.808: GtkDialog mapped without a transient parent. This is discouraged.
TypeError: refresh() takes 1 positional argument but 3 were given
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Böyle bir dosya ya da dizin yok: '/var/crash/_usr_bin_lutris.0.crash
Original exception was:
TypeError: refresh() takes 1 positional argument but 3 were given

**System information**

Sapphire R9 270 

> {
  "comment": "",
  "system": {
    "gpus": [
      {
        "DRIVER": "radeon",
        "PCI_ID": "1002:6811",
        "PCI_SUBSYS_ID": "174B:E271",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:01:00.0",
        "MODALIAS": "pci:v00001002d00006811sv0000174Bsd0000E271bc03sc00i00"
      }
    ],
    "env": {
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
      "LESSCLOSE": "/usr/bin/lesspipe %s %s",
      "LANG": "tr_TR.UTF-8",
      "SUDO_GID": "1000",
      "DISPLAY": ":0.0",
      "COLORTERM": "truecolor",
      "USERNAME": "root",
      "SUDO_COMMAND": "/bin/su",
      "USER": "root",
      "PWD": "/home/bugra",
      "HOME": "/root",
      "SUDO_USER": "bugra",
      "SUDO_UID": "1000",
      "MAIL": "/var/mail/root",
      "SHELL": "/bin/bash",
      "TERM": "xterm-256color",
      "SHLVL": "1",
      "LANGUAGE": "tr",
      "LOGNAME": "root",
      "XAUTHORITY": "/home/bugra/.Xauthority",
      "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games",
      "LESSOPEN": "| /usr/bin/lesspipe %s",
      "_": "/usr/bin/lutris"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "60",
        "model name": "Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz",
        "stepping": "3",
        "microcode": "0x27",
        "cpu MHz": "1108.821",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7199.96",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "60",
        "model name": "Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz",
        "stepping": "3",
        "microcode": "0x27",
        "cpu MHz": "1093.306",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7199.96",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "60",
        "model name": "Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz",
        "stepping": "3",
        "microcode": "0x27",
        "cpu MHz": "1142.498",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7199.96",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "60",
        "model name": "Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz",
        "stepping": "3",
        "microcode": "0x27",
        "cpu MHz": "1082.993",
        "cache size": "3072 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm arat pln pts md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "7199.96",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "label": null,
        "uuId": null,
        "mountpoInt": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "label": null,
            "uuId": "4151-3438",
            "mountpoInt": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "label": null,
            "uuId": "b6606492-8b81-4eaa-8cf5-3bbef902e1a4",
            "mountpoInt": "/"
          }
        ]
      }
    ],
    "ram": {
      "bellek": {
        "total": "8106300",
        "used": "1695988",
        "free": "1468656",
        "shared": "110016",
        "buff/cache": "4941656",
        "available": "5996608"
      },
      "takas": {
        "total": "2097148",
        "used": "1036",
        "free": "2096112"
      }
    },
    "dist": [
      "Linux Mint",
      "19.3",
      "tricia"
    ],
    "glxinfo": {
      "opengl_shading_language_version": "4.50",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 19.0.8",
      "name_of_display": ":0.0",
      "opengl_core_profile_context_flags": "(none)",
      "display": ":0",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_renderer": "AMD PITCAIRN (DRM 2.50.0, 5.0.0-37-generic, LLVM 8.0.0)",
      "opengl_core_profile_version": "4.5 (Core Profile) Mesa 19.0.8",
      "opengl_version": "4.5 (Compatibility Profile) Mesa 19.0.8",
      "opengl_context_flags": "(none)",
      "direct_rendering": "Yes",
      "opengl_profile_mask": "compatibility profile",
      "opengl_core_profile_shading_language_version": "4.50",
      "opengl_vendor": "X.Org",
      "screen": "0",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20"
    }
  }
}

**Screenshots**

https://drive.google.com/file/d/1yejrZXeJdbN7wR7BhMjawoHi3at3_l3u/view?usp=sharing

**Comment by tannisroot** [comment]
Southern Islands cards (which is what you have) default to `radeon` driver, which doesn't support Vulkan. You need to enable an option so that `amdgpu` gets used instead, which should provide Vulkan support.
Also, you didn't follow the instructions properly, as you're using a Mesa version that is very outdated.
