### ISSUE TITLE
No image on "Disconnect" button in "Import games from GOG" window

### ISSUE THREAD

**Issue by TotalCaesar659** [lutris/lutris#2578]
There is no image on "Disconnect" button in "Import games from GOG" window.
![0](https://user-images.githubusercontent.com/14265316/71849960-49611f80-30e4-11ea-9703-676a265b0d54.png)
Lubuntu 18.04.3, Lutris 0.5.4 from official PPA.

**Comment by tannisroot** [comment]
Gnome devs suggest that app developers ship our own icons. Perhaps that's what we should do here to solve this issue.
