### ISSUE TITLE
Any plans to add RenderDoc ?

### ISSUE THREAD

**Issue by MuraliSridhar** [lutris/lutris#2579]
Lutris - is really great, thanks guys.

Any plans to support RenderDoc ? something like : from Runner Options where we can enable RenderDoc

**Comment by tannisroot** [comment]
That's a graphics debug tool, which is not something Lutris should have an option for in my opinion.
If you really need to use RenderDoc together with Lutris, just add ENABLE_VULKAN_RENDERDOC_CAPTURE=1 to the list of environment variables for the game.
