### ISSUE TITLE
Add option to turn columns on/off in List View

### ISSUE THREAD

**Issue by TotalCaesar659** [lutris/lutris#2581]
When right-clicking to table headbar in List View, you expect to get a menu for turning columns on/off, but you just select first game in the list.

**Comment by tannisroot** [comment]
Yeah, if you right click on "Name" here the menu for the first game gets opened, which is a bit weird:
![image](https://user-images.githubusercontent.com/10602045/71997869-a200fb80-324f-11ea-9ac4-be8663d44c35.png)

**Comment by strycore** [comment]
2 very different issues.
The initial report is a feature request (and, no. You shouldn't expect columns to be hidden / shown on right click, this is in no way universal)
The other is an actual bug.

Going to fix the right click on header bar issue independently of this ticket and move that one for a later release.

**Comment by strycore** [comment]
Tried to change the behavior related to the 1st row being select when right clicking the headers but didn't find a solution
