### ISSUE TITLE
Ability to start runners/GameStores only, like Steam Client.

### ISSUE THREAD

**Issue by TriMoon** [lutris/lutris#2582]
**Describe the bug**

It would be very welcomed to be able to start the runners without any game, for example to startup the Steam Client only.
That way we can use the Steam Client in this example to install games in case there is no pre-made config for the game yet.
This would i think also benefit other game stores like the Epic Game Store etc.

**Expected behavior**

Have a seperate entry for the runners/GameStores

**Current behavior**

Only way is to "run exe inside wine prefix" and manually navigating to correct exe.

**Steps to reproduce**

**Lutris debugging output**

**System information**
Kubuntu 19.10

**Screenshots**

**Comment by tannisroot** [comment]
You can already do this with native and wine steam (just over over those runners in the left panel, you will see a "play" button near the runner name), and EGS currently doesn't have a dedicated runner, but I'm sure it will have such option when it gets one.

**Comment by TriMoon** [comment]
ohhh never noticed that because i didnt use the left panel :laughing:
