### ISSUE TITLE
Steam Client display bugs

### ISSUE THREAD

**Issue by TriMoon** [lutris/lutris#2583]
**Describe the bug**
See my usename in screenshot.
Plus there is flickering and blackout when you are viewing your game library.

**Expected behavior**
It should display correctly

**Current behavior**

Looks like it is not UTF-8 friendly?

**Steps to reproduce**
**Lutris debugging output**
**System information**
Kubuntu 19.10

**Screenshots**

![Screenshot_Steam20200107_174858](https://user-images.githubusercontent.com/1723378/71904041-72ca8b80-3176-11ea-89fd-f4e978d59626.png)

**Comment by tannisroot** [comment]
How does your nickname supposed to look like?

**Comment by strycore** [comment]
does installing various font package through winetricks fix the issue? We already install asian fonts in our default WineSteam prefix, we can add more if needed.

**Comment by TriMoon** [comment]
> How does your nickname supposed to look like?

☾★TriMoon☾★

@strycore i have no idea how to do that for the wine-steam runner.

**Comment by strycore** [comment]
@TriMoon if you have at least 1 winesteam game that is using the default winesteam prefix then you can run winetricks on it. Once you have winetricks open, there is a section specific to installing fonts where you can try a bunch of them.

**Comment by TriMoon** [comment]
@strycore  A step-by-step instruction, to reproduce what you say, would be very welcome... :eyes:

**Comment by TriMoon** [comment]
@strycore Just FYI, im experienced with Linux, but im a noob with wine and wintricks.
Therefor a step-by-step instruction would not only benefit me but other readers also...
Thanks in advance...

**Comment by tannisroot** [comment]
@TriMoon open Winetricks, select "Select the default wineprefix"->"Install a font" and then experiment with various font verbs and see if any fix this.

**Comment by strycore** [comment]
I tried installing a bunch of fonts and it didn't do anything (actually, I managed to changed the width of the rectangles). None of the fonts work.
Since the winesteam runner is less a priority because Proton exists, I'm going to close this.
If someone really wants to see this solved, maybe this can be reopened in the wine repo.

**Comment by jarrard** [comment]
I also seem to have this issue. I'm testing wine steam because I've had some issues with proton and my VFS MO2 loader.
