### ISSUE TITLE
Add Lutris logo to the notifications

### ISSUE THREAD

**Issue by TotalCaesar659** [lutris/lutris#2585]
The Lutris notifications often blends right into the background.
![0](https://user-images.githubusercontent.com/14265316/71908436-0acc7300-317f-11ea-9696-642db6a8b2af.png)
Adding Lutris logo will get it more visible, e.g. Transmission.
![1](https://user-images.githubusercontent.com/14265316/71908458-1881f880-317f-11ea-8da9-184b269fb495.png)

**Comment by tannisroot** [comment]
In Gnome, it seems to be using some fallback bulb icon, and yeah it would be nice to differentiate Lutris notifications from other apps. 
![Screenshot from 2020-01-08 19-35-47](https://user-images.githubusercontent.com/10602045/71997078-5f8aef00-324e-11ea-9cd7-5b7e3a518dd1.png)
