### ISSUE TITLE
PCSX2 Runner: Add config path/file options (Feature request)

### ISSUE THREAD

**Issue by 7HEPOW** [lutris/lutris#2590]
It would be nice to have a way to specify a config file as for example some games run better with a multi-threaded microVU than others. It would also enable to have different window sizes set for those seeking square pixels as some NTSC games run at 640x448 and others use 512x448. Same goes for PAL region games. :slightly_smiling_face: 

The command line is: `PCSX2 --cfg=<str>`

I'm absolutely fine if you put it on low priority as probably only few people use PCSX2 anyways. :wink:

**Comment by strycore** [comment]
Anything that involves adding an option for a command line flag is super easy to implement. And having a way to set the whole config can be really useful. I'm going to mark this for next release.

**Comment by strycore** [comment]
this should be tested.

**Comment by 7HEPOW** [comment]
I heard the call :smile: 

Doesn't work unfortunately. When launching a game with a configure ini file the button on the panel simply changes to "Lauching" and that's it.

I should've put in a little more effort before.

Not sure why --cfg doesn't work correctly. Running PCSX2 from a terminal with config file given, it doesn't write anything to it after exiting PCSX2 (1.4.0). May be a bug in the emulator itself.

However passing a folder with --cfgpath works as intended and all ini files are written correctly. Full reconfiguration of the emulator is needed if no files are present. This also enables to confgure the plugins separately, which --cfg doesn't.

I took a look at the runner and it says "--conf" instead of "--cfg" in line 47.

I forked it and changed it to use --cfgpath but I get this error:
```
arguments.append("--cfgpath=%s", self.runner_config["config_path"])
TypeError: append() takes exactly one argument (2 given)
```
That's a far as I get with my non-coding skills. :stuck_out_tongue_winking_eye: 

Here's a link to the runner for reference:
https://github.com/7HEPOW/lutris/blob/master/lutris/runners/pcsx2.py

I guess having the arguments fixed, should solve all of the issues.

**Comment by strycore** [comment]
dammit, I forgot to push a fix for that before the release

**Comment by 7HEPOW** [comment]
Preferably --cfgpath should be the thing istead of --cfg :smile:

**Comment by AlexanderRavenheart** [comment]
Please add support for both options (--cfgpath for sets of config files and --cfg which is better suited for game specific small config file) and allow the user to choose which one to use depending on their requirements.

**Comment by 7HEPOW** [comment]
Added both options in this PR: https://github.com/lutris/lutris/pull/2758

**Comment by malefice** [comment]
I am not sure if I should open a new ticket or not, but attempting to launch a game with either `--cfg` and `--cfgpath` options set will throw this error:

```
  File "/path/to/lutris/lutris/runners/pcsx2.py", line 64, in play
    arguments.append("--cfgpath=%s", self.runner_config["config_path"])
TypeError: append() takes exactly one argument (2 given)
```

This happens because `arguments` is a actually Python `list`, so the `append` method invoked is the `list`'s `append` method, not some magical function (which I initially thought) that accepts an arbitrary number of arguments that will substitute placeholders like `%s` with the actual values. The substitution must be performed manually, so instead of commas, they should have been `%` symbols like so:

```
# line 62
arguments.append("--cfg=%s" % self.runner_config["config_file"])

# line 64
arguments.append("--cfgpath=%s" % self.runner_config["config_path"])
```

Or using `str.format` style:

```
# line 62
arguments.append("--cfg={}".format(self.runner_config["config_file"]))

# line 64
arguments.append("--cfgpath={}".format(self.runner_config["config_path"]))
```

Anyway, I prefer the `str.format` style, and I can submit a PR for this if you wish. Just tell me which style you prefer.
