### ISSUE TITLE
"extract" directive needs support to specify the extractor manually

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#260]
Godot provides export templates in a zip archive with extension changed to ```tpz``` (templates-zip), mostly because users were trying to unarchive it when it was named zip instead of installing it automatically from within the editor.

Anyway, for my Godot installer I want to pre-install the templates, but the ``extract`` directive chokes on the extension:
```
RuntimeError('Could not extract `/home/akien/.cache/lutris/installer/godot-engine/Godot_v2.0_stable_20160223_export_templates.tpz` as no appropriate extractor is found',)
```

It would be nice to have an option to specify the extractor and thus override the extension check (e.g. ``extractor: zip`` or ``extractor: 7z``).

**Comment by Xodetaetl** [comment]
`format: zip`
;)

**Comment by akien-mga** [comment]
Thanks! :D
We really need a wiki page that describes all install script options and commands :)

**Comment by Xodetaetl** [comment]
We do, but that option was actually documented !

**Comment by akien-mga** [comment]
> We do, but that option was actually documented !

Oops, indeed :D
