### ISSUE TITLE
Graceful gog account management

### ISSUE THREAD

**Issue by Sergaster** [lutris/lutris#2600]
Hello!

I have faced with problem in lutris-5.3: after changing GOG account password the button "Import games" became broken. After removing cache directory the button start working again.

The problem was with saved old password in cache and failed authorization in GOG. I think It is necessary to add some interface for management accounts data.

Thx

**Comment by tannisroot** [comment]
Lutris 0.5.3 is an outdated version. Please upgrade to a newer version.
