### ISSUE TITLE
Failure to read Steam's config.vdf due to wrong case

### ISSUE THREAD

**Issue by PracticallyNothing** [lutris/lutris#2605]
Lutris can't read Steam's config.vdf file because the "Steam" value is actually lowercase when Lutris expects it to be uppercase.

![19:05:34](https://user-images.githubusercontent.com/17669985/72685104-730c4480-3aef-11ea-9217-4df94fac22bd.png)

Same as #1966.

**Comment by ZeikoFr** [comment]
The original problem was solved here : https://github.com/lutris/lutris/commit/5c833761d53f37571daafd6deaeefa30663ac6ea

But it seems the code changed since that and I don't know where Strycore solved this now :/

We can just try to d o something like this 
`
except KeyError:
        try:
            return config["InstallConfigStore"]["Software"]["valve"]["steam"]
`
I think Strycore will have the final answer on this

**Comment by PracticallyNothing** [comment]
Can't the keys for the dictionary be made case insensitive?

**Comment by connectety** [comment]
Ok I got 2 possible solutions to this.
These are more PoCs, not tested and probably need a little refactoring.
I just wanna know which one I should improve and create a PR for.

1. [Just adding the case that "valve" is lowercase.](https://github.com/connectety/lutris/commit/572518a650383c7c0bce7705a060f8617c3a7ea8)
2. [Adding a method, which looks through the dictionary recursively. ](https://github.com/connectety/lutris/commit/8736f374b6ef59a024dcb2be51dfc9b7032f7fb8)

**Comment by strycore** [comment]
The first method is mostly a hack that resembles the initial implementation (which was bad and ended up not being sufficient).
The second method seems like a way better choice.
I feel the best choice for this would be to have some kind of case insensitive dict like the one implemented here: https://pypi.org/project/pydicti/

**Comment by connectety** [comment]
The VDF format does seam to be case-sensitive.
The [valve docs](https://developer.valvesoftware.com/wiki/KeyValues) don't say anything about case sensitivity and the vdf python module is case-sensitive. Only this specific case seams to need a case-insensitive implementation.
I feel like an extra library for one case is a bit excessive, but often a good & finished implementation is better then a homemade one.

**Comment by strycore** [comment]
There is a vendor folder in the source code where we can put stuff like that. pydicti's code is contained to a single file so it's easy to distribute if we ever need to.
For the time being can you create a PR for your 2nd solution? I this solves the bug, it's a good solution.
