### ISSUE TITLE
Installing Windows applications

### ISSUE THREAD

**Issue by Helg1980** [lutris/lutris#2606]
Good afternoon! 
Lutris is a great program, is it possible to modify the program so that in addition to games it is possible to install applications on the principle of "one click"?

**Comment by ZeikoFr** [comment]
Hi, 

Lutris is dedicated to gaming so I don't think the use of it for classic application will be added

**Comment by tannisroot** [comment]
It's focused on games but isn't limited to them. You can add a program manually to Lutris or make an installer for it just like with games.

**Comment by strycore** [comment]
https://lutris.net/games/microsoft-word/

https://lutris.net/games/adobe-lightroom-5/
