### ISSUE TITLE
[Humble Bundle] No game found 

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2610]
**Describe the bug**
when trying to add games from humble I get the following on the terminal: 

`
No game found for jalopy, spacepilgrim_episode1, ponyisland, outlast_whistleblower, serioussamkamikazeattack, tacoma`

Think it might be a case due to the fact that IE Pony Island is lusted as pony-island while importing from humble it's ponyisland thus the games aren't added to your library.

**Comment by strycore** [comment]
This is not resolved client side
