### ISSUE TITLE
Lutris not localized

### ISSUE THREAD

**Issue by amivaleo** [lutris/lutris#2611]
Hi!

I use Fedora 31 and gnome-shell 3.34.3. I installed Lutris version 0.5.3-1.fc31 from the gnome-software app. Such version is not localized in my native language (italian), although the po file is in this repo here.

Are you planning to push the latest Lutris version on gnome-software so that it will be localized (and updated with all the latest commits)? Thanks!

**Comment by strycore** [comment]
we have plenty of tickets about that already, look them up.
