### ISSUE TITLE
Problem with Yuzu installation

### ISSUE THREAD

**Issue by Adehom** [lutris/lutris#2612]
Hi,
As said in the issue #2356 and Pull request #2497, we need to add some information in https://lutris.net/api/runners :

   {

        "name": "Yuzu",
        "slug": "yuzu",
        "icon": "https://lutris.net/media/runners/icons/yuzu.png", #need to add this icons in this repository
        "website": "https://yuzu-emu.org/",
        "versions": [
            {
                "version": "813f9d590",
                "architecture": "x86_64",
                "url": "https://lutris.net/files/runners//yuzu-linux-20200122-813f9d590.tar.xz", #need to add this file in this repository
                "default": true
            }
        ]
    },

url to download installer : https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-140/yuzu-linux-20200122-813f9d590.tar.xz

**Lutris debugging output**

Traceback (most recent call last):
  File "/home/tony/lutris/lutris/gui/dialogs/runners.py", line 134, in on_install_clicked
    runner.install(downloader=simple_downloader)
  File "/home/tony/lutris/lutris/runners/runner.py", line 328, in install
    runner = self.get_runner_version(version)
  File "/home/tony/lutris/lutris/runners/runner.py", line 290, in get_runner_version
    runner_info = self.get_runner_info()
  File "/home/tony/lutris/lutris/runners/runner.py", line 282, in get_runner_info
    return request.get().json
  File "/home/tony/lutris/lutris/util/http.py", line 76, in get
    raise HTTPError("Request to %s failed: %s" % (self.url, error))
lutris.util.http.HTTPError: Request to https://lutris.net/api/runners/yuzu failed: HTTP Error 404: Not Found

**Comment by strycore** [comment]
I uploaded a build and got Yuzu to show up the GUI (and then it crashed). That's about as much testing as I can do on my end.
