### ISSUE TITLE
Hots high fps drops

### ISSUE THREAD

**Issue by davidkak007** [lutris/lutris#2613]
Heroes of the storm are said to work with platinum rating, however, there are playable high fps lags, ubuntu under 19.10 and all updates are installed and Drivers are installed.

**Comment by Zeioth** [comment]
Be aware it might take some time until your shader cache fills. Anyway, it's not Lutris fault, refer to [dxvk](https://github.com/doitsujin/dxvk) and please, include the required information in the report. Otherwise they won't ba able to help.
