### ISSUE TITLE
General Error Dual Video

### ISSUE THREAD

**Issue by joeg1484** [lutris/lutris#2614]
Hi,

I have an Asus GU501 ROG laptop with in Intel 630 and an Nvidia 1060. I have the standard nvidia driver (Driver Version: 435.21) using Kubuntu 19.10 fully patched.
When I try to run Overwatch, I get the following error:
`General Error: 0xE0010160`

I noticed that Lutris sees 2 cards and I wonder if this is the cause. In the troubleshooting section, I see instructions for setting up an Intel card, and I tried the same process for my nvidia card, but it didnt work.

$ lutris
2020-01-24 23:06:09,259: Running Lutris 0.5.4
2020-01-24 23:06:09,259: Using NVIDIA drivers 435.21 for x86_64
2020-01-24 23:06:09,259: GPU: GeForce GTX 1060
**2020-01-24 23:06:09,259: GPU: 10DE:1C20 1043:185E using nvidia drivers
2020-01-24 23:06:09,259: GPU: 8086:3E9B 1043:1FD0 using i915 drivers**
2020-01-24 23:06:09,299: Vulkan is supported
2020-01-24 23:06:09,300: Updating DXVK versions
2020-01-24 23:06:09,440: Connected to lutris.net as USERNAME
2020-01-24 23:06:09,978: Updating D9VK versions

Any idea how to get this to work on my setup?

Thanks!
Joe Giles

**Comment by tannisroot** [comment]
Check if it resolves if you set this **advanced** Vulkan ICD loader option to use nvidia json file: 
![image](https://user-images.githubusercontent.com/10602045/75859465-1c429c00-5e0b-11ea-9e58-277205addf11.png)

**Comment by ZeikoFr** [comment]
Hi @joeg1484 did you tried the proposal of tannisroot ?

Can you give some update on the problem ?

**Comment by joeg1484** [comment]
Hi @ZeikoFr  and @tannisroot Yes, this worked fine for me. I apologize for not replying sooner, its been a crazy couple of weeks.

Thanks for the replies!
