### ISSUE TITLE
missing icons when I launch Lutris git version

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2616]
Hello,
most of the time I do not use Lutris from official distribution packages but from git, to test last code and new features available.
But if I launch Lutris this way, it missed some  icons:
![Capture d’écran de 2020-01-28 12-50-42](https://user-images.githubusercontent.com/325405/73261875-3fa37700-41cd-11ea-8a5d-75284fa86b85.png)

- "Search Lutris.net" icon
- "Amiga 500", "Amiga 500+", Nintendo 64...
- Tray icon

Could it be possible to add this icons to Lutris for a more portable concept?

**Comment by tannisroot** [comment]
What Linux distribution are you running and what DE do you have installed (and what's its version?)?

**Comment by legluondunet** [comment]
Voilà: Ubuntu 19.10 and GNOME Shell 3.34.3.

**Comment by strycore** [comment]
To get the Lutris icon in the search and the tray, you need to have lutris installed on your system so the icons are registered.

I added some missing icons for platforms but this is in no way exhaustive. I'll try to add icons as I notice missing ones but it would be nice to have some PRs for them too.
