### ISSUE TITLE
ScummVM runner: please add free command line options

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2618]
Hello,
could you add a command line option for ScummVM runner?
Some games require a specific configuration which cannot be managed with the actual Lutris interface.
For example, I wrote a script installer for Beneath a Steel Sky, I could add language choice during script install adding this command line:
-- language=fr

ideas:
- ? add an "args" field for Lutris ScummVM runner in the "Game Options" or "Runner Options" tab
- ? add this script function: 
![Capture-20200131205821-416x247](https://user-images.githubusercontent.com/325405/73576859-bebdd700-447b-11ea-8eb8-fdacaf01404a.png)

for your information, other available commands line:
https://wiki.scummvm.org/index.php?title=User_Manual/Appendix:_Command_line_options

**Comment by strycore** [comment]
Closed by #2791
