### ISSUE TITLE
Can't use undersore "_" in identifier names

### ISSUE THREAD

**Issue by pollaloca** [lutris/lutris#2625]
**Describe the bug**
I can not add an identifier name that uses underscore "_"
Due to this Watch Dogs game is not getting the corresponding image and icon.
https://lutris.net/games/watch_dogs/

**Expected behavior**
Either Identifier field should accept underscore or change the identifier name of Watch Dogs from watch_dogs to watch-dogs

**Current behavior**

What is the current behavior?

**Steps to reproduce**

- 
-
-

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by strycore** [comment]
Changed the ID for watch dogs (also created an alias to keep compatibility)
