### ISSUE TITLE
setxkbmap forced to use us keyboard, impossible change to different locale?

### ISSUE THREAD

**Issue by runboy93** [lutris/lutris#2628]
I'm from Finland, and would be very interested to use my keyboard locale keys such as: öäå in WoW and WoW classic to able write actual words in my main locale.

But looks like lutris code forces setxkbmap on us locale, why isn't there other option for us who would like use own keyboard locale, like in this case "setxkbmap fi", like script (I'm not coder ofc) example which works on lutris.

**Comment by tannisroot** [comment]
I have a non-english keyboard myself and I can type in my own language just fine.
Are you sure you didn't enable this option by accident? 
![image](https://user-images.githubusercontent.com/10602045/75858357-18ae1580-5e09-11ea-8214-6b92b21da7db.png)

**Comment by strycore** [comment]
Lutris does not change the keyboard layout unless that option is enabled.
This option exist for games that were poorly designed and only work properly on a US layouts.
So far I haven't heard of a game that only works properly on a layout other than standard qwerty, will reconsider if that ever comes up.
