### ISSUE TITLE
Fix for Overwatch General Error

### ISSUE THREAD

**Issue by kksgandhi** [lutris/lutris#2631]
Please add this to Game:Overwatch wiki

If the game displays a black screen, then crashes with General Error (OxE0010160): Type "cd /usr/share/vulkan/icd.d" and "ls". Note the various files in the directory. Under settings, environment variables, add "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/XXXXX.json" where XXXXXX.json is the file corresponding to your graphics card.

I'm new to git so please let me know if this is not the correct way to do things.

**Comment by tannisroot** [comment]
We have a dedicated option for this, actually.

**Comment by tannisroot** [comment]
![image](https://user-images.githubusercontent.com/10602045/75858002-578f9b80-5e08-11ea-95dc-1f1d7b9049bf.png)

**Comment by kksgandhi** [comment]
Interesting... regardless I was hoping it would be added to the wiki, since when I was installing OW, I would not have known how to set the Vulkan ICD loader from the wiki or install script, and I'd like others who install it in the future to see that information

**Comment by tannisroot** [comment]
yeah I'll add a note to myself to add this to wiki when I get to updating it.
