### ISSUE TITLE
Cannot launch games with wine as the runner

### ISSUE THREAD

**Issue by rharish101** [lutris/lutris#2633]
Lutris shows the following error in a popup window when opening a game with wine as the runner:
> symlink: src should be string, bytes or os.PathLike, not NoneType

On closing this, it shows:
> An error prevented the game from running

On running lutris from the terminal with the `-d` flag, this is the output that is received:
```python
DEBUG    2020-02-20 11:15:51,802 [game.play:295]:Prelaunching <lutris.runners.wine.wine object at 0x7f27500daac0>
ERROR    2020-02-20 11:15:51,831 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f27500daac0>>: symlink: src should be string, bytes or os.PathLike, not NoneType
<class 'TypeError'> symlink: src should be string, bytes or os.PathLike, not NoneType
  File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/runners/wine.py", line 791, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3.8/site-packages/lutris/runners/wine.py", line 949, in sandbox
    wine_prefix.desktop_integration(restore=True)
  File "/usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py", line 124, in desktop_integration
    os.symlink(xdgshortcuts.get_xdg_entry(DESKTOP_XDG[i]), path)
ERROR    2020-02-20 11:15:51,832 [game.configure_game:312]:symlink: src should be string, bytes or os.PathLike, not NoneType
ERROR    2020-02-20 11:15:53,425 [game.configure_game:315]:Game prelaunch unsuccessful
```

This occurs for any game with wine as the runner. Here are the contents of `~/.config/lutris/runners/wine.yml`:
```yml
system: {}
wine:
  autoconf_joypad: false
  d9vk: true
  d9vk_version: Manual
  dxvk: true
  dxvk_version: Manual
  esync: true
  overrides:
    mscoree: d
    mshtml: d
  sandbox: false
```
Here are the contents of `~/.config/lutris/system.yml`:
```yml
system:
  game_path: /mnt/Data/Games
  optimus: 'off'
  prelaunch_command: /mnt/Data/Programs/Bash/before_game.sh
  reset_desktop: true
  vk_icd: /usr/share/vulkan/icd.d/nvidia_icd.json
```
For reference, here are the contents of `/mnt/Data/Programs/Bash/before_game.sh`:
```sh
#!/usr/bin/zsh
xset dpms 0 0 0
```

Note that I am able to run these games when I run them using wine from the command line. The issue occurs when I run them through Lutris. I have tried deleting the game runners from lutris and recreating them from Lutris's GUI, but the problem persists.

My system configuration is:
* OS: Arch Linux
* Lutris version: lutris-0.5.4
* Wine version: wine-5.0-419-g1a7d5eaf58 (this is Valve's version of wine, from [wine-valve-git](https://aur.archlinux.org/packages/wine-valve-git/), modified to use the "proton_5.0" branch)
* DXVK version: 1.5.4, installed into my wine prefix using `setup_dxvk install --symlink`
* DE: Xfce 4.14 (for daily use), Openbox 3.6.1 inside [nvidia-xrun](https://github.com/Witko/nvidia-xrun) (for gaming with Lutris)

**Comment by rharish101** [comment]
I was able to solve this by re-enabling the "Create a sandbox for wine folders" option. The new contents of `~/.config/lutris/runners/wine.yml` are:
```yml
system: {}
wine:
  autoconf_joypad: false
  d9vk: true
  d9vk_version: Manual
  dxvk: true
  dxvk_version: Manual
  esync: true
  overrides:
    mscoree: d
    mshtml: d
```

**Comment by tannisroot** [comment]
@rharish101 can you try this with current master version of Lutris?

**Comment by rharish101** [comment]
@tannisroot I tried it using the [PKGBUILD on AUR](https://aur.archlinux.org/packages/lutris-git/), which pulls from the master branch. I'm still getting the same error, and the logs show that it's the same one.

**Comment by connectety** [comment]
This problem is very strange to me.
Looking at the logs, we can determine that `get_xdg_entry` somehow returned `None`.
Because we do not get a `ValueError` from `get_xdg_entry`, we know that `GLib.get_user_special_dir` is called with something valid but returns `None`.

Not an error because something did go wrong, but just `None`.
I took a look at the GLib docs, but it does not say anything about `None`.
The only thing I could find in this direction is: https://github.com/flatpak/flatpak/issues/1062
And in a case like this, it would not be lutris fault.

**Comment by rharish101** [comment]
@connectety This is what that command returns: `/home/rharish/Desktop`
