### ISSUE TITLE
Computer does not boot after driver installation

### ISSUE THREAD

**Issue by Osrip** [lutris/lutris#2634]
**Describe the bug**

After following instructions under the headline 
"If you have Ubuntu 18.04 Bionic Beaver or Ubuntu 18.10 Cosmic Cuttlefish"
My computer does not boot anymore

**Steps to reproduce**

I use Linux Mint Cinnamon, 
Specs: AMD Threadripper processor, Radeon Graphics cart

Followed the instructions below "If you have Ubuntu 18.04 Bionic Beaver or Ubuntu 18.10 Cosmic Cuttlefish" :

- sudo add-apt-repository ppa:kisak/kisak-mesa
-sudo dpkg --add-architecture i386 
-sudo apt update && sudo apt upgrade
-sudo apt install libgl1-mesa-glx:i386 libgl1-mesa-dri:i386
-sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386

Any suggestions on how to reset the system to previous state?

**Comment by JanGalek** [comment]
@Osrip Did you try remove installed packages ?

```
sudo apt remove libgl1-mesa-glx:i386 libgl1-mesa-dri:i386
sudo apt remove mesa-vulkan-drivers mesa-vulkan-drivers:i386
```

**Comment by tannisroot** [comment]
I'm sorry this happened, but unfortunately this repository is not for these kind of issue.
Personally, I would suggest to use a newer distribution, like Ubuntu 19.10.
