### ISSUE TITLE
Showing the amount of games which are using a wine version

### ISSUE THREAD

**Issue by Trollwut** [lutris/lutris#2635]
Hey folks!

Is there some indicator on how many games are using a specific WINE version?

I'm thinking about the "manage WINE versions" dialog: https://i.imgur.com/Pi0gmu1.png

I think it would be nice to have a third row with the amount of games that are currently set to the wine versions. With this, it would be easy to clean up some versions to get disk space :)

**Comment by strycore** [comment]
we have that now. we still need to link that number to the actual list of games using that version but that will come
