### ISSUE TITLE
Battlenet crashes when opening overwatch

### ISSUE THREAD

**Issue by Spryc** [lutris/lutris#2636]
**Describe the bug**

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**
When i click on play overwatch in battlenet it crashes
Please describe the behavior you are expecting.
That the game would work and start normally
**Current behavior**

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

https://paste.ubuntu.com/p/TTsttC8hhC/

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

{
  "comment": "I can open battlenet but when i open overwatch it just shuts down",
  "system": {
    "gpus": [
      {
        "DRIVER": "amdgpu",
        "PCI_ID": "1002:67DF",
        "PCI_SUBSYS_ID": "1DA2:E387",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:26:00.0",
        "MODALIAS": "pci:v00001002d000067DFsv00001DA2sd0000E387bc03sc00i00"
      }
    ],
    "env": {
      "SHELL": "/bin/bash",
      "WINDOWID": "60817422",
      "COLORTERM": "truecolor",
      "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
      "I3SOCK": "/run/user/1000/i3/ipc-socket.1353",
      "DESKTOP_SESSION": "i3",
      "GTK_MODULES": "canberra-gtk-module",
      "XDG_SEAT": "seat0",
      "PWD": "/home/linus",
      "XDG_SESSION_DESKTOP": "i3",
      "LOGNAME": "linus",
      "XDG_SESSION_TYPE": "x11",
      "XAUTHORITY": "/home/linus/.Xauthority",
      "DESKTOP_STARTUP_ID": "i3/kitty/1353-15-linus-pc_TIME11400179",
      "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/linus",
      "HOME": "/home/linus",
      "LANG": "en_US.UTF-8",
      "XDG_CURRENT_DESKTOP": "i3",
      "KITTY_WINDOW_ID": "1",
      "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
      "XDG_SESSION_CLASS": "user",
      "TERMINFO": "/usr/lib/kitty/terminfo",
      "TERM": "xterm-kitty",
      "USER": "linus",
      "DISPLAY": ":0",
      "SHLVL": "1",
      "XDG_VTNR": "7",
      "XDG_SESSION_ID": "2",
      "MOZ_PLUGIN_PATH": "/usr/lib/mozilla/plugins",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XDG_DATA_DIRS": "/home/linus/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop",
      "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin",
      "GDMSESSION": "i3",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "HG": "/usr/bin/hg",
      "MAIL": "/var/spool/mail/linus",
      "_": "/usr/bin/lutris"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ],
      "RADEON": [
        [],
        []
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1661.705",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "0",
        "cpu cores": "6",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "1",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1439.777",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "1",
        "cpu cores": "6",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "2",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1525.151",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "2",
        "cpu cores": "6",
        "apicid": "4",
        "initial apicid": "4",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "3",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.593",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "4",
        "cpu cores": "6",
        "apicid": "8",
        "initial apicid": "8",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "4",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.706",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "5",
        "cpu cores": "6",
        "apicid": "10",
        "initial apicid": "10",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "5",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.508",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "6",
        "cpu cores": "6",
        "apicid": "12",
        "initial apicid": "12",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "6",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "2532.707",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "0",
        "cpu cores": "6",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "7",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1469.076",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "1",
        "cpu cores": "6",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "8",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1449.357",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "2",
        "cpu cores": "6",
        "apicid": "5",
        "initial apicid": "5",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "9",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.504",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "4",
        "cpu cores": "6",
        "apicid": "9",
        "initial apicid": "9",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "10",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.578",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "5",
        "cpu cores": "6",
        "apicid": "11",
        "initial apicid": "11",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      },
      {
        "processor": "11",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "8",
        "model name": "AMD Ryzen 5 2600 Six-Core Processor",
        "stepping": "2",
        "microcode": "0x800820d",
        "cpu MHz": "1549.241",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "12",
        "core id": "6",
        "cpu cores": "6",
        "apicid": "13",
        "initial apicid": "13",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6799.39",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate cpb eff_freq_ro [13] [14]"
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "ext4",
            "fsver": "1.0",
            "label": "HDD",
            "uuid": "45748464-00f6-444f-afac-498a656b506f",
            "fsavail": "703.4G",
            "fsuse%": "18%",
            "mountpoint": "/mnt/HDD"
          }
        ]
      },
      {
        "name": "sdb",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdb1",
            "fstype": "vfat",
            "fsver": "FAT32",
            "label": null,
            "uuid": "E1E1-B678",
            "fsavail": "420M",
            "fsuse%": "18%",
            "mountpoint": "/boot"
          },
          {
            "name": "sdb2",
            "fstype": "ext4",
            "fsver": "1.0",
            "label": null,
            "uuid": "8bff1593-eb15-4313-84a0-60dcd9fdd804",
            "fsavail": "279.5G",
            "fsuse%": "34%",
            "mountpoint": "/"
          }
        ]
      }
    ],
    "ram": {
      "mem": {
        "total": "16409984",
        "used": "3170116",
        "free": "4818704",
        "shared": "191536",
        "buff/cache": "8421164",
        "available": "12719352"
      },
      "swap": {
        "total": "4194300",
        "used": "1792",
        "free": "4192508"
      }
    },
    "dist": [
      "Arch Linux",
      "rolling",
      "n/a"
    ],
    "glxinfo": {
      "opengl_core_profile_version": "4.5 (Core Profile) Mesa 19.3.4",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "direct_rendering": "Yes",
      "name_of_display": ":0",
      "opengl_context_flags": "(none)",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_version": "4.5 (Compatibility Profile) Mesa 19.3.4",
      "screen": "0",
      "opengl_core_profile_shading_language_version": "4.50",
      "opengl_shading_language_version": "4.50",
      "display": ":0",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 19.3.4",
      "opengl_profile_mask": "compatibility profile",
      "opengl_renderer": "Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.5.5-zen1-1-zen, LLVM 9.0.1)",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_vendor": "X.Org"
    }
  }
}

**Screenshots**

**Comment by tannisroot** [comment]
> This repository isn't for reporting game bugs or game related issues. Feel free to contact us on Discord, the Forums, or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.
