### ISSUE TITLE
Qt frontend

### ISSUE THREAD

**Issue by varsbhat** [lutris/lutris#2637]
I am learning Python and also am learning Qt. I would love to port Lutris to Qt. There are 3 possibilities:
1) Creating downstream Qt port.
2) Adding Qt gui portion to Lutris master branch itself.
3) project splitting into core,gtk-gui,and qt-gui (much like transmission bt project).

So,i would ask you how to proceed ? I can't promise when the work will be done but i will be doing it anyway.

**Comment by PopeRigby** [comment]
Why'd you close the issue?

**Comment by varsbhat** [comment]
I have created downstream fork for the time being . I am working on Qt UI files at this moment. I will add all UI files to this Repo when Complete.
[lutris-qt](https://github.com/varsbhat/lutris-qt)

Can you suggest which QT binding to choose? There are two: PySide2 and PyQt5 . I think that I will go with PyQt5

**Comment by rodneyrod** [comment]
@varsbhat Looks like your link isn't working any more?

**Comment by varsbhat** [comment]
> @varsbhat Looks like your link isn't working any more?

Yeah , i deleted the repo , also closed this issue . The reason is that  i have been still working on qt skills . i have designed ui and am porting code tied with GTK . I have closed the issue since it is not issue anyway
