### ISSUE TITLE
Slime rancher - goginstaller not found error when installing

### ISSUE THREAD

**Issue by life8853** [lutris/lutris#2638]
logs here  https://paste.ubuntu.com/p/7DRV3jNcrp/

**Comment by noblica** [comment]
It seems there's an issue with installing games from GOG. I have the same "goginstaller not found" error pop up when installing various games (Crimsonland for example).

**Comment by legluondunet** [comment]
I had the same error until I download the last git version.

**Comment by noblica** [comment]
@legluondunet  I'm using the latest version:

![Screenshot from 2020-03-03 16-36-21](https://user-images.githubusercontent.com/9339019/75791667-33cb4780-5d6d-11ea-899e-c7e92820ac7f.png)

**Comment by tannisroot** [comment]
For now please use master version of Lutris. We will make a new release with a fix soon.
