### ISSUE TITLE
Older Wine versions are gone from the runner list.

### ISSUE THREAD

**Issue by Rencer** [lutris/lutris#2639]
There are some old games that I like to play,  and they are runs ONLY with old Wine versions.
Some are even required a specific Wine version, they don't run with any other just that one.

After the latest update old Wine versions are gone. Why?

Please add them back, and not just those that you removed, but it would be great if you can add even more version to the list. Because of some case when somthing required a specific older Wine version.

Thanks.

**Comment by tannisroot** [comment]
Those versions are very old and we can no longer guarantee that they will work properly on newer Linux distribution, which is why they were pulled from our download list.
You can still download some from https://lutris.net/files/runners/ but they will not return to the download list.
If you can't launch certain games in newer version, please report this regression to Wine's bugtracker, preferably with information like in which version it stopped working exactly (and with which app) and maybe after which specific commit.

**Comment by tannisroot** [comment]
It's not always a myth - sometimes regressions happen in Wine that don't get fixed for years, even when they were properly reported.

**Comment by strycore** [comment]
Regressions are real, yes. But they are also pretty rare with current versions of Wine. Keeping old versions of wine around for the sake of avoiding potential but unlikely regressions does not nothing but slow down Wine development. As you said, it makes regressions actually go unnoticed when they could be fixed very quickly.

**Comment by Rencer** [comment]
> You can still download some from https://lutris.net/files/runners/ but they will not return to the download list.
> If you can't launch certain games in newer version, please report this regression to Wine's bugtracker, preferably with information like in which version it stopped working exactly (and with which app) and maybe after which specific commit.

Thanks for the link for the older versions.

Wine developers, doesn't give a poop about they broke almost everything in every update. It's a fact, you like ot not.
I wrote countless times about this on the Wine bug tracker, but NOTHING changed. They doesn't even replyed to most of those posts...
Every time a new Wine version come out, 90% of the time, some programs that worked before, they stop working on the new vesrion! 
There are countless times that a game-braking bug fixed in one version, the next time the exact same problem come up again. Then it fixed, and with the next version that same bug come back. Again and again. And this happening all the time.
Back some years ago there was an exact same issue with many games. The original first report created A DEACDE AGO, but people still posting to that same report! They fixd it, right?
It is fixed, and than it occured again, and it is fixed, and the same bug occured again, etc.
This is the best example how Wine development works...

They doesn't care that they broke what worked before. Every version of Wine is made for a specific "era", that means they just make the current version to run the most "trendy" software: they just make sure that what are the current most popular games and software out there works. That means almost every Wine version is capable of running a maximum 2-3 year old stuff, but older programs likely to don't run anymore.

Now, I'm really disappointed with Lutris, because this platform seems to be the best.
But not supporting old softwares (a.k.a older Wine versions) is the worst decision...

**Comment by Rencer** [comment]
> Regressions are real, yes. But they are also pretty rare with current versions of Wine. Keeping old versions of wine around for the sake of avoiding potential but unlikely regressions does not nothing but slow down Wine development. As you said, it makes regressions actually go unnoticed when they could be fixed very quickly.

I thougt this post is about Lutris.
I can't understand why you talking about Wine developement...
