### ISSUE TITLE
Can't launch Lutris in Ubuntu 16

### ISSUE THREAD

**Issue by epangar** [lutris/lutris#2643]
I can't launch Lutris in Ubuntu 16. If I try to launch it from terminal, I get the following error:

`
 Traceback (most recent call last):
  File "/usr/bin/lutris", line 34, in <module>
    from lutris.gui.application import Application
ImportError: No module named 'lutris'

`

Any suggestions?

**Comment by strycore** [comment]
I don't know how you have installed lutris but this is certainly not the right way.
We do not support Ubuntu 16.04 any more. It's ships with libraries that are too old for Lutris to work properly. The solution is to update to a current system.
