### ISSUE TITLE
Cannot download game binaries, archive broken

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [lutris/lutris#2648]
**Describe the bug**

Hello, I'm installing Osu! for windows with lutris on ubuntu. 
It crashes mid-download, giving this error message : 
`Failed to extract /home/geoffrey/.cache/lutris/wine-tkg/osu-4.6-x86_64.tar.xz: Compressed file ended before the end-of-stream marker was reached`

**Expected behavior**

The game should download this file.

**Current behavior**

The file cannot be downloaded, neither with Lutris nor wget in a terminal.

**Steps to reproduce**

- Have Lutris
- Download osu! windows (lutris:osu-windows)

**Lutris debugging output**

No debug output (?)

**System information**
[Link to JSON output](https://paste.ubuntu.com/p/cymYJq94vk/)

---------

This bug looks similar to #2234, which was resolved by purging CDN cache. 
I'm in France if this helps.

**Comment by tannisroot** [comment]
I purged all of our CDN caches. Please check if you still get the error.

**Comment by GeoffreyCoulaud** [comment]
No more error, great !
