### ISSUE TITLE
Ubuntu 16.04 Build

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#265]
Would be great to get a 16.04 release in:
http://download.opensuse.org/repositories/home:/strycore/

Opened up a Pull request to [Add Lutris to Ubuntu MATE Welcome](https://bitbucket.org/RobLoach/ubuntu-mate-welcome/pull-requests/2/add-lutris-installer/diff).

**Comment by strycore** [comment]
Sadly I do not have any control over this :( 
Running 16.04 myself, I'd sure like to have the repo ready instead of having to use the 15.10 one.

I just hope that openSUSE Build Service will offer Ubuntu 16.04 soon after the release.

**Comment by dennisjj5** [comment]
I concur. I just switched to 16.04 (Ubuntu MATE) myself.

**Comment by strycore** [comment]
I've updated the installation instructions so that copy/pasting the commands will not result in a non-existent repository (will default to 15.10).

**Comment by strycore** [comment]
Ubuntu 16.04 is now supported in OBS

**Comment by RobLoach** [comment]
:+1:
