### ISSUE TITLE
Cannot start wine games without pulseaudio

### ISSUE THREAD

**Issue by nilzeronull** [lutris/lutris#2651]
**Describe the bug**

Starting a game that uses a wine runne does not work without pulse-audio installed since the pulse audio reset is called no matter what.
It is worth noting that playing games on wine without pulseaudio still works, even though jack support is officially removed. 

**Expected behavior**

I can start the game.

**Current behavior**

The game cannot be started due to pulseaudio not being installed.

**Steps to reproduce**

- Start a game with wine runner without having pulseaudio installed

**Lutris debugging output**
```Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/game.py", line 377, in configure_game
    audio.reset_pulse()
  File "/usr/lib/python3.8/site-packages/lutris/util/audio.py", line 9, in reset_pulse
    subprocess.Popen(["pulseaudio", "--kill"])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulseaudio'
```

**Comment by tannisroot** [comment]
Just to be clear- you **don't have this option enabled**, right? 
![image](https://user-images.githubusercontent.com/10602045/77259919-9c835100-6c95-11ea-9764-aae9c316cbc4.png)

**Comment by strycore** [comment]
there's a check disallowing to enable it when pulseaudio isn't enabled. There's a bunch of installers that set this option when it's totally useless to do so: https://lutris.net/games/?q=reset_pulse&search-installers=on
