### ISSUE TITLE
Search takes way too long

### ISSUE THREAD

**Issue by Lucy-UwU** [lutris/lutris#2658]
When I use the search feature, or any other connection to the lutris server it takes way to long.
It takes about a minute to get an awnser.

The search feature should just instantly show results

This could verry well be a problem with my machine. I set it up today so I dont really suspect this.

**Lutris debugging output**
`INFO     2020-03-15 02:51:37,585 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-03-15 02:51:37,586 [startup.check_driver:55]:Using NVIDIA drivers 440.64 for x86_64
INFO     2020-03-15 02:51:37,586 [startup.check_driver:60]:GPU: GeForce GTX 1060 6GB
INFO     2020-03-15 02:51:37,586 [startup.check_driver:79]:GPU: 10DE:1C03 1462:3283 using nvidia drivers
INFO     2020-03-15 02:51:37,662 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-15 02:51:37,663 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-03-15 02:51:37,844 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-03-15 02:51:38,182 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2020-03-15 02:52:07,936 [lutriswindow.search_games:742]:website search for :overwatch
DEBUG    2020-03-15 02:52:07,936 [http.get:65]:GET https://lutris.net/api/games?search=overwatch
DEBUG    2020-03-15 02:53:11,513 [interpreter.fetch_script:54]:Fetching installer https://lutris.net/api/installers/overwatch
DEBUG    2020-03-15 02:53:11,513 [http.get:65]:GET https://lutris.net/api/installers/overwatch
INFO     2020-03-15 02:53:36,487 [application.do_shutdown:450]:Shutting down Lutris`

**System information**

`{
  "comment": "",
  "system": {
    "nvidia_driver": {
      "nvrm": {
        "vendor": "NVIDIA",
        "platform": "UNIX",
        "arch": "x86_64",
        "version": "440.64",
        "date": "Fri Feb 21 01:17:26 UTC 2020"
      }
    },
    "nvidia_gpus": [
      {
        "Model": "GeForce GTX 1060 6GB",
        "IRQ": "32",
        "GPU UUID": "GPU-4e016ae3-9427-3fda-eca8-17dc7eda709f",
        "Video BIOS": "86.06.0e.00.a4",
        "Bus Type": "PCIe",
        "DMA Size": "47 bits",
        "DMA Mask": "0x7fffffffffff",
        "Bus Location": "0000:01:00.0",
        "Device Minor": "0",
        "Blacklisted": "No"
      }
    ],
    "gpus": [
      {
        "DRIVER": "nvidia",
        "PCI_ID": "10DE:1C03",
        "PCI_SUBSYS_ID": "1462:3283",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:01:00.0",
        "MODALIAS": "pci:v000010DEd00001C03sv00001462sd00003283bc03sc00i00"
      }
    ],
    "env": {
      "SHELL": "/bin/bash",
      "SESSION_MANAGER": "local/DesktopDebian:@/tmp/.ICE-unix/1344,unix/DesktopDebian:/tmp/.ICE-unix/1344",
      "QT_ACCESSIBILITY": "1",
      "COLORTERM": "truecolor",
      "XDG_MENU_PREFIX": "gnome-",
      "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
      "GTK_IM_MODULE": "ibus",
      "LANGUAGE": "en_GB:en",
      "QT4_IM_MODULE": "ibus",
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "XMODIFIERS": "@im=ibus",
      "DESKTOP_SESSION": "gnome",
      "SSH_AGENT_PID": "1237",
      "GTK_MODULES": "gail:atk-bridge",
      "PWD": "/home/lucy",
      "LOGNAME": "lucy",
      "XDG_SESSION_DESKTOP": "gnome",
      "XDG_SESSION_TYPE": "x11",
      "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
      "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
      "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
      "WINDOWPATH": "2",
      "GDM_LANG": "en_GB.UTF-8",
      "HOME": "/home/lucy",
      "USERNAME": "lucy",
      "IM_CONFIG_PHASE": "1",
      "LANG": "en_GB.UTF-8",
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
      "XDG_CURRENT_DESKTOP": "GNOME",
      "VTE_VERSION": "5803",
      "GNOME_TERMINAL_SCREEN": "/org/gnome/Terminal/screen/ad3584bb_b780_464a_b83e_fd91aeea9898",
      "INVOCATION_ID": "cad3e736af4645db9457b0dd2132e40e",
      "MANAGERPID": "1131",
      "CLUTTER_IM_MODULE": "ibus",
      "GJS_DEBUG_OUTPUT": "stderr",
      "XDG_SESSION_CLASS": "user",
      "TERM": "xterm-256color",
      "USER": "lucy",
      "GNOME_TERMINAL_SERVICE": ":1.102",
      "DISPLAY": ":1",
      "SHLVL": "1",
      "QT_IM_MODULE": "ibus",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "JOURNAL_STREAM": "9:32773",
      "XDG_DATA_DIRS": "/usr/share/gnome:/home/lucy/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/",
      "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games",
      "GDMSESSION": "gnome",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "_": "/usr/bin/lutris"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.357",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.372",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.347",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "4",
        "initial apicid": "4",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.356",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "6",
        "initial apicid": "6",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "4",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.299",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "5",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.349",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "6",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.205",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "5",
        "initial apicid": "5",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "7",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "42",
        "model name": "Intel(R) Xeon(R) CPU E31270 @ 3.40GHz",
        "stepping": "7",
        "microcode": "0x28",
        "cpu MHz": "1596.365",
        "cache size": "8192 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "7",
        "initial apicid": "7",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "6784.52",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "36 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "label": null,
            "uuid": "0541-E1D4",
            "fsavail": "505.8M",
            "fsuse%": "1%",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "label": null,
            "uuid": "b4f81f52-80d3-440d-bcc2-de5e03b815ee",
            "fsavail": "15.9G",
            "fsuse%": "37%",
            "mountpoint": "/"
          },
          {
            "name": "sda3",
            "fstype": "swap",
            "label": null,
            "uuid": "b309c56c-89f8-445d-9785-5d85a9b2b6c0",
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": "[SWAP]"
          },
          {
            "name": "sda4",
            "fstype": "ext4",
            "label": null,
            "uuid": "8c170fee-00ff-4969-8887-a7714aa0c445",
            "fsavail": "389.3G",
            "fsuse%": "1%",
            "mountpoint": "/home"
          }
        ]
      },
      {
        "name": "sdb",
        "fstype": "crypto_LUKS",
        "label": null,
        "uuid": "80d9804d-a49b-4883-b152-fc86bd655310",
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null
      },
      {
        "name": "sdc",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdc1",
            "fstype": "ntfs",
            "label": "TOSHIBA EXT",
            "uuid": "E6B88F54B88F2263",
            "fsavail": "35.7G",
            "fsuse%": "96%",
            "mountpoint": "/media/lucy/TOSHIBA EXT"
          }
        ]
      },
      {
        "name": "sr0",
        "fstype": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null
      }
    ],
    "ram": {
      "mem": {
        "total": "16406600",
        "used": "3465300",
        "free": "8896804",
        "shared": "360752",
        "buff/cache": "4044496",
        "available": "12262916"
      },
      "swap": {
        "total": "16714748",
        "used": "0",
        "free": "16714748"
      }
    },
    "dist": [
      "Debian GNU/Linux",
      "testing",
      "bullseye"
    ],
    "glxinfo": {
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_es_profile_version": "OpenGL ES 3.2 NVIDIA 440.64",
      "opengl_shading_language_version": "4.60 NVIDIA",
      "direct_rendering": "Yes",
      "opengl_vendor": "NVIDIA Corporation",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_renderer": "GeForce GTX 1060 6GB/PCIe/SSE2",
      "opengl_core_profile_shading_language_version": "4.60 NVIDIA",
      "display": ":1",
      "name_of_display": ":1",
      "opengl_version": "4.6.0 NVIDIA 440.64",
      "opengl_context_flags": "(none)",
      "opengl_profile_mask": "(none)",
      "screen": "0",
      "opengl_core_profile_version": "4.6.0 NVIDIA 440.64",
      "opengl_core_profile_context_flags": "(none)"
    }
  }
}`

Edit: Just curled the url given with the debug and I instantly got the output expected.

**Comment by strycore** [comment]
Haven't noticed any issue but we had some problems related to search in 0.5.4...
I'm going to close this, please reopen if you still experience issues in 0.5.6.
