### ISSUE TITLE
Can't configure the wiimote buttons on Dolphin runner

### ISSUE THREAD

**Issue by raulcraveiro** [lutris/lutris#2671]
**Describe the bug**

I'm connecting the Wiimote with my Ubuntu 19.10 using the back button, but there isn't a way to configure the buttons using the Dolphin runner, and this way the Wiimote doesn't work with any game. :/

**Expected behavior**

There should be a way to configure the controller button.

**Current behavior**

There's not a way, so the wiimote doesn't work.

**Comment by strycore** [comment]
You can launch the main Dolphin UI from the side bar, this will let you remap wiimote buttons.
