### ISSUE TITLE
Wine: Using 'Proton 5.0' doesn't work, gives several python errors, libselinux.so.1 error

### ISSUE THREAD

**Issue by RiantAnda** [lutris/lutris#2673]
**Describe the bug**
When I setup a game with "Proton 5.0" as 'Wine version', the game doesn't attempt to launch.
Logs show:
Traceback (most recent call last):
  File "/usr/bin/lutris-wrapper", line 9, in <module>
    from lutris.util.monitor import ProcessMonitor
  File "/usr/lib/python3.8/site-packages/lutris/util/monitor.py", line 5, in <module>
    from lutris.util.log import logger
  File "/usr/lib/python3.8/site-packages/lutris/util/log.py", line 6, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

**Expected behavior**
The game should (at least attempt to) launch.
This issue doesn't happen with the older 'Proton 4.11'. 

**Current behavior**
Nothing happens after I press 'Play'

**Steps to reproduce**
Setup any game with Runner = Wine
Select 'Proton 5.0' under Wine version (Needs steam for linux and steamplay installed on system?)
Press 'Play' to start game

**Lutris debugging output**
[Lutris-d.txt](https://github.com/lutris/lutris/files/4364831/Lutris-d.txt)

**System information**
[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/4364834/lutris-issue-report.json.zip)

**Comment by RiantAnda** [comment]
I found out that this problem goes away when I disable 'Prefer system libraries'.
Seems to be an issue between my Arch Linux system and the Proton build?

**Comment by michaudg** [comment]
Installing [libselinux](https://aur.archlinux.org/packages/libselinux/) from AUR solve the problem.

**Comment by gardotd426** [comment]
@RiantAnda How is Lutris detecting your Proton versions without them in `~/.local/share/lutris/runners/wine/`? 

Lutris has never detected anything in `~/.steam/root/compatibilitytools.d/` or the Steam official Proton for me, there's even open bug reports about it, and we never even got any confirmation that it's supposed to show up at all.

**Comment by RiantAnda** [comment]
@gardotd426 
I can't answer your questions. It worked for me ever since, so I opened this issue.
Because the devs accepted it, I assume this if officially supported.
My proton versions are in $HOME/.local/share/Steam/steamapps/common

**Comment by strycore** [comment]
Proton is now removed some available Wine versions.
