### ISSUE TITLE
Only use Wine's builtin d3d10 and d3d10_1 with DXVK 1.6 (and newer) and wine 5.3 (and newer)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2675]
Thought this would be enough and just work with older version of Wine and DXVK (https://github.com/lutris/lutris/commit/10ec196653766875411550268bdaf5202b2f4278) but apparently it's not clear whether this will actually work (i can't test as I dont have any d3d10 games) so it would be best to be safe and add a check there.
The check will simply need to check that the version of DXVK in use is 1.6 (or newer, plus it has to account for potential point versions like 1.6.1 and weird names like `froggination-1.7`) and that Wine version is 5.3 or newer (only the version matters).

**Comment by tannisroot** [comment]
I'm putting this into 0.5.5 to avoid DXVK devs being annoyed because Lutris is so behind with these kind of changes.

**Comment by strycore** [comment]
why is this a priority? this is only to satisfy DirectX 10 games that *do not* run with Wine 5.3 / DXVK 1.6.
I'm not sure this needs to be solved at all. Maybe that can be reopened if that *ever* becomes an issue.

**Comment by tannisroot** [comment]
> why is this a priority? this is only to satisfy DirectX 10 games that do not run with Wine 5.3 / DXVK 1.6.
I'm not sure this needs to be solved at all. Maybe that can be reopened if that ever becomes an issue.

Not true. This is needed to prevent breakage of existing setups.
I believe it's important not to interfere with people's setups with out client updates and if you agree, I would like to reopen this.

**Comment by strycore** [comment]
How would this break setups?

**Comment by tannisroot** [comment]
Because before DXVK 1.6, d3d10_1 and d3d10 components of DXVK were linked to d3d10core (https://github.com/doitsujin/dxvk/commit/3697583f71e86e82b9f0f36f50c4b75ea1bd4f0b), so if somebody has a installation with an old DXVK version specified (like, for example, if they use custom DXVK with async patches), it will cause unforeseen breakage, which people will complain about not on our repo, but on dxvk's repo, and I really want to avoid that.

**Comment by tannisroot** [comment]
And regarding the check for Wine versions - I am not sure how exactly not passing overrides for d3d10 and d3d10_1 on old wine versions (older than 5.3) break things on a technical level because I am not a Direct3D developer, but I've been told by Phillip himself that it **will** break games like Crysis, for example.
