### ISSUE TITLE
Add a DXVK suboption to use builtin DXGI implementation (and enable it by default for some wine versions)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2676]
As we are getting very close to shipping VKD3D in our lutris builds (meaning D3D12 support), there are now some changes needed in the client to make it work properly.
Specifically, there is now need for an option that wouldn't add a dxgi.dll override when DXVK is enabled. And it will also have to be enabled automatically if the build in use is a custom Lutris one (their names all contain `lutris`) *and* uses 5.5 (or newer) as base (this is because i plan to add VKD3D support in `lutris-5.5` build, older builds don't and won't have it). Note that the check for this has to account for various build flavors (like `lutris-fshack-5.5`  or `lutris-somebrokengame-5.7`) and shouldn't be enabled by default for regular Wine builds.
And yes, it has to be a GUI option because we have to account for cases when the user wants to use their own custom wine build that has VKD3D support with DXGI patches that add proper DXVK interoperability.

**Comment by strycore** [comment]
Can we limit that version checking stuff? 
We can choose a default and stick with it. If the default doesn't work for some case, then there's an option for that.
Checking if this is a custom build is even more far fetched.

Moving to 0.5.6 because Wine 5.5 doesn't even exist yet.

**Comment by tannisroot** [comment]
> Can we limit that version checking stuff?
Sure. The alternative is changing version string that `wine --version` reports that says something like
``` wine-5.5 ( Lutris Staging Esync Fsync DXVK-COMPATIBLE VKD3D )```
and Lutris can simply check for presence of ```DXVK-COMPATIBLE VKD3D``` in the string.
I believe we even have code for that from Esync option.
> We can choose a default and stick with it. If the default doesn't work for some case, then there's an option for that.
The issue is that if we enable it by default, it will break existing installations with outdated Wine builds.
> Moving to 0.5.6 because Wine 5.5 doesn't even exist yet.
It will be released in 2 days, I was just planning ahead. And it would be really unfortunate if we would have to postpone our VKD3D support until Lutris 0.5.6 :(

**Comment by strycore** [comment]
I added the option to support to enable VKD3D support, which uses an alternative DXVK manager without DXGI. I was never suggesting to enable this option by default. This is experimental and only needed by a few games, we shouldn't change our current behavior for that.

There is no version or feature checking implemented at all. If using dxgi.dll on Wine >= 5.5 still enables to play DX9/DX10/DX11 then I'm fine with this. If for some reason this breaks DXVK entirely for those builds, then I may look into that more.
