### ISSUE TITLE
Remove "Lutris is already running but seems unresponsive" message

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#268]
This message box simply does not work the way it should, when clicking "yes", I *still* have to restart the client once more. 

And I do not see any use case where any user would click "No" as in "No, I don't want to fix my currently broken and unresponsive game client"

This message should not exists, when the interface is unresponsive, it should be restarted silently without any user input.

**Comment by Xodetaetl** [comment]
> And I do not see any use case where any user would click "No"

The potential use case I thought of was that Lutris could be stuck on some long blocking process and the user would prefer to wait and see if it finishes.

**Comment by strycore** [comment]
> The potential use case I thought of was that Lutris could be stuck on some long blocking process and the user would prefer to wait and see if it finishes. ¯\_(⋅⋅)_/¯

Hmm, yeah, I don't see that ever happening. Whenever DBus is not responding means that the client was already terminated and somehow, something is still running (which shouldn't happen). Even if a blocking process was running, one would never see its results anyway.

**Comment by strycore** [comment]
Well, the dialog box is gone but something needs to be done about the following error handling. That will deserve its own issue.
