### ISSUE TITLE
Commit 9102071 Breaks Gentoo compatibility

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#2681]
Using a relative path breaks Gentoo compatibility.

Due to Gentoo's ability to have multiple versions of python installed simutaneously, they do some symlink resolution magic that determines which python interpreter should be used for a package based on the constraining flags applied at installation.

Because of this lutris script is not located in /usr/bin/lutris. This is a symlink to the resolver that then performs its magic. This causes lutris to fail to be able to call the python-wrapper script.

Recommend non-relative path to lutris-wrapper.

**Comment by strycore** [comment]
And that's what I was waiting for.

@sharkwouter please send a fix or I'll revert your PR before the release.

**Comment by sharkwouter** [comment]
Will do

**Comment by sharkwouter** [comment]
I've made a pull request which makes lutris check for the lutris-wrapper binary in more locations. This should solve this issue. See #2683

**Comment by aTosser** [comment]
From a quick glance and some copy paste it seems the PR fixes this issue on Gentoo.

**Comment by sharkwouter** [comment]
That's great, thanks for testing
