### ISSUE TITLE
Can't install Lutris using lutris-git AUR script (test failure)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2687]
Caused by https://github.com/lutris/lutris/commit/85f1976e3a2a49f91950dec3126f4de4d1a213d3 from @sharkwouter .
Seems like it causes a test failure (see https://travis-ci.org/github/lutris/lutris/builds/667512890?utm_source=github_status&utm_medium=notification), which the package doesn't like.

**Comment by sharkwouter** [comment]
Thanks for fixing this. This one confused me D:
