### ISSUE TITLE
Remove "Connecting to your Lutris.net account to sync your library" from the main page if an account is linked and library is empty

### ISSUE THREAD

**Issue by MrTimscampi** [lutris/lutris#269]
This is mainly a UI suggestion.  
It makes more sense clarity-wise to remove that entry when an account is linked, as having it there implies you haven't connected any account yet.

If an account is linked and library has been synced, that entry should be removed and only adding a game manually and browsing the website should be options.

**Comment by strycore** [comment]
Makes sense and it's quite simple to implement. I'll set the milestone to the next release.

**Comment by MrTimscampi** [comment]
"Register account" in the "Lutris" menu should also be hidden when connected.

I may try to tackle this, if it's okay with you, as a way to familiarize myself with PyGObject and the Lutris source.
