### ISSUE TITLE
Gamemode Doesn't Work If Steam Is Already Running

### ISSUE THREAD

**Issue by RickAndTired** [lutris/lutris#2690]
**Describe the bug**
Launching a Steam game through Lutris does not start Gamemode if Steam is already running.
Launching a Steam game through Lutris without Steam running will start Gamemode fine.
This is the same for both Native and Proton games.

**Expected behavior**
Gamemode should start

**Current behavior**
Gamemode doesn't start

**Steps to reproduce**

- Start Lutris
- Run Steam via Lutris or on its own
- Launch a Steam game via Lutris with Gamemode toggled on

**Lutris debugging output**
[lutris-gamemode.txt](https://github.com/lutris/lutris/files/4396637/lutris-gamemode.txt)

**System information**
[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/4396638/lutris-issue-report.json.txt)
(GitHub wouldn't let me  upload a .json so I added .txt to the end of the name)

**Comment by strycore** [comment]
Let Lutris start steam and it you won't have this issue.

**Comment by RickAndTired** [comment]
> Let Lutris start steam and it you won't have this issue.

I started Steam through Lutris and Gamemode still does not get activated.
