### ISSUE TITLE
Portable Games for Linux (AppImage)

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#270]
[Portable Linux Games](http://portablelinuxgames.org) is a site that builds [AppImage](http://appimage.org/) containers for Linux games. Pretty cool! Anything that Lutris could do to pair with it?

I suppose it could use it for some of its open source game installers.

**Comment by strycore** [comment]
At one point the Gens/GS emulator was an appimage but it was still broken and we switched to dgen (which is an inferior emulator but works). Also, Lutris is in there (but it needs to be updated: https://portablelinuxgames.org/game/lutris ).

For the rest, I'd guess that would be a nice solution for games that neeeeeeeeeeed a sudo make install or a distro package (Alien Arena, 0AD, etc)

**Comment by Xodetaetl** [comment]
Our installer for 0.A.D uses an AppImage from this site.
My personal experience of creating AppImages isn't full of success though.

PS: The forums are the better place for suggestions now.

**Comment by RobLoach** [comment]
> PS: The forums are the better place for suggestions now.

Pssssh, I live code repos.

**Comment by strycore** [comment]
> The forums are the better place for suggestions now.

Yeah, the thing is, with issues like this one, I have no idea when I should close them.

**Comment by RobLoach** [comment]
Meh!
