### ISSUE TITLE
no json output from lutris -j

### ISSUE THREAD

**Issue by PureArtistry** [lutris/lutris#2701]
**Describe the bug**

lutris -j option just prints out this debug info

2020-04-01 10:18:24,751: Package 'distro' unavailable. Unable to read Linux distribution
2020-04-01 10:18:25,013: Running Lutris 0.5.5
2020-04-01 10:18:25,014: Using NVIDIA drivers 440.64 for x86_64
2020-04-01 10:18:25,014: GPU: GeForce GTX 960M
2020-04-01 10:18:25,014: GPU: 10DE:139B 152D:1097 using nvidia drivers
2020-04-01 10:18:25,014: GPU: 8086:0416 152D:1097 using i915 drivers
2020-04-01 10:18:25,038: Vulkan is supported
2020-04-01 10:18:25,039: Updating DXVK versions

opens the gui interface (not behaviour I would expect, don't know if it's supposed to do that) and then waits until you close the gui before exiting printing only:

2020-04-01 10:31:07,056: Shutting down Lutris

prior to a recent update trying the -j option would cause it to hang on/after "updating D9VK" and not open the gui. The D9VK message no longer appears

**Lutris debugging output**

The terminal output of `lutris -d`.

2020-04-01 10:37:53,739: Package 'distro' unavailable. Unable to read Linux distribution
INFO     2020-04-01 10:37:53,993 [application.do_command_line:245]:Running Lutris 0.5.5
INFO     2020-04-01 10:37:53,993 [startup.check_driver:54]:Using NVIDIA drivers 440.64 for x86_64
INFO     2020-04-01 10:37:53,994 [startup.check_driver:60]:GPU: GeForce GTX 960M
INFO     2020-04-01 10:37:53,994 [startup.check_driver:77]:GPU: 10DE:139B 152D:1097 using nvidia drivers
INFO     2020-04-01 10:37:53,994 [startup.check_driver:77]:GPU: 8086:0416 152D:1097 using i915 drivers
INFO     2020-04-01 10:37:54,018 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-04-01 10:37:54,019 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-04-01 10:37:54,186 [http.get:65]:GET https://lutris.net/api/runtime

(at this point is opens the gui and waits until I close it)

INFO     2020-04-01 10:39:47,654 [application.do_shutdown:491]:Shutting down Lutris

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/4414203/lutris-issue-report.json.txt)

**Comment by connectety** [comment]
`--json` is an option for `--list-games`.
so you need to pass `--list-games` for it to show something.
Probably it would be best to add a hint for that to `--help`

> prior to a recent update trying the -j option would cause it to hang on/after "updating D9VK" and not open the gui. The D9VK message no longer appears

D9VK was removed / migrated to DXVK, because it got merged into DXVK.
And as far as i can tell there has not been a change to the `--json` argument in 0.5.5.

**Comment by PureArtistry** [comment]
I feel stupid now for never trying it with another arg, just misunderdstood the help message and assumed something was wrong.

This is a pebkac issue, very sorry to waste your time.
