### ISSUE TITLE
Battle.net installer freezes - Startcraft 2

### ISSUE THREAD

**Issue by MGadhvi** [lutris/lutris#2709]
When installing Starcraft 2, the login window remains on the screen and does not automatically close. The last few lines of the installer say:

```
00e4:fixme:reg:RegDisableReflectionKey 0xa4: stub
00e4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00e4:err:ole:CoGetClassObject class {f3bdfad3-f276-49e9-9b17-c474f48f0764} not registered
00e4:err:ole:CoGetClassObject class {f3bdfad3-f276-49e9-9b17-c474f48f0764} not registered
00e4:err:ole:create_server class {f3bdfad3-f276-49e9-9b17-c474f48f0764} not registered
00e4:fixme:ole:CoGetClassObject CLSCTX_REMOTE_SERVER not supported
00e4:err:ole:CoGetClassObject no class object {f3bdfad3-f276-49e9-9b17-c474f48f0764} could be created for context 0x17
00e4:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
00e4:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
00e4:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
00e4:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
0145:fixme:ver:GetCurrentPackageId (0xfaff0c (nil)): stub
00a6:fixme:win:FlashWindowEx 0x329960 - semi-stub
00a6:fixme:win:FlashWindowEx 0x32cb34 - semi-stub
00c5:fixme:file:ReplaceFileW Ignoring flags 2
0123:fixme:file:ReplaceFileW Ignoring flags 2
```
I suspect an Ubuntu update has borked something. When closing the login window, the installer completes but when logging in, you get a Blizzard error "The application encountered an unexpected error". log states:

```
ft-ii/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe
Initial process has started with pid 13436
Game is considered started.
esync: up and running.
Initial process has exited.
wine: Call from 0x7bc95619 to unimplemented function vulkan-1.dll.vkGetInstanceProcAddr, aborting
```

I haven't had to setup vulcan when playing starcraft before. This has only been an issue in the last few days

Running on Ubuntu 18.04.4 LTS. Was happily running Starcraft on medium settings with no slowdown until a few days ago

**Comment by Micronetic** [comment]
The same happens with the Battle.net installer for WoW and WoW: Classic as you can see on the Lutris forums: https://forums.lutris.net/t/battlenet-not-working-with-the-new-lutris-0-5-5-version/8718

**Comment by MGadhvi** [comment]
I saw the thread, thank you. Feels a little reassuring to know I'm not the only one and it's not just my screw up. Trying to play around with the wine settings to see if that does anything

**Comment by Micronetic** [comment]
I have tried to play around with the settings and different wine versions etc. nothing helped, the only way it seems is to downgrade to 5.4 Lutris but I don't like this idea.

**Comment by MGadhvi** [comment]
Tried to run it with version 5.4 and ended up in a login loop. This was just after adding DefaultLimitNOFILE=524288

**Comment by MGadhvi** [comment]
> I have tried to play around with the settings and different wine versions etc. nothing helped, the only way it seems is to downgrade to 5.4 Lutris but I don't like this idea.
> 
> Edit: Okay looks like it is working a little bit again, when you come to the state of the log-in window not closing automatically just close it and cancel the installation, press play in Lutris. Just did it right now with a fresh installation of Lutris. https://i.imgur.com/EBcSjhq.png

could you explain the steps you took to do this? I closed the battle.net login window and cancelled the installation. This would mean there is nothing installed to run?

**Comment by Micronetic** [comment]
Yes, while the login window was open and the Lutris window was stuck I just closed the Blizzard login window and pressed "cancel" on the Lutris window, then pressed play in the main Lutris window and it worked, don't know why because it didn't work yesterday.

**Comment by MGadhvi** [comment]
> Yes, while the login window was open and the Lutris window was stuck I just closed the Blizzard login window and pressed "cancel" on the Lutris window, then pressed play in the main Lutris window and it worked, don't know why because it didn't work yesterday.

Tried this and it creates the same error for me as my first post

**Comment by MGadhvi** [comment]
Just another quick update:

I can get Starcraft 2 installed on 5.4. Then prompted to set up Esync.

After changing the system and user .conf files, Ubuntu goes into a login loop. I can revert the files via safe mode boot but can’t run Starcraft 2 now

**Comment by Micronetic** [comment]
This is really weird and I don't know at this point if this is an Ubuntu thing or not because on Arch it worked for me with the installation cancelling, I don't know why because I didn't do anything special like config files or so.

**Comment by MGadhvi** [comment]
> This is really weird and I don't know at this point if this is an Ubuntu thing or not because on Arch it worked for me with the installation cancelling, I don't know why because I didn't do anything special like config files or so. I am going to uninstall WoW and Battle.net and try it again while recording it so I can show you what I did, hopefully it will work again :-D
> 
> 
> 
> Edit: here is the video how I did it and it works in 0.5.5: https://youtu.be/04dhScqxXws

That was really helpful. Thank you. What did you have setup in terms of Vulkan, Esync etc? Did you use the wine version in your package or via the Lutris guide?

**Comment by MGadhvi** [comment]
Dump from last attempt. Same issue as first post:

```
Running /home/mgd/.local/share/lutris/runners/wine/lutris-5.5-2-x86_64/bin/wine /home/mgd/Games/world-of-warcraft/drive_c/Program Files (x86)/Battle.net/Battle.net.exe
Initial process has started with pid 6753
Game is considered started.
esync: up and running.
libGL error: Different GPU, but blitImage not implemented for this driver
libGL error: failed to load driver: i965
[0404/211211.636:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
[0404/211212.195:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 373
[0404/211212.691:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
info:  Game: Battle.net.exe
info:  DXVK: v1.6
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
wine: Call from 0x7bc95e69 to unimplemented function vulkan-1.dll.vkGetInstanceProcAddr, aborting
Initial process has exited.
```

**Comment by MGadhvi** [comment]
Ok, I've managed to make some progress. This line caught my eye

```
wine: Call from 0x7bc95e69 to unimplemented function vulkan-1.dll.vkGetInstanceProcAddr, aborting
```

When trying to use vulkan, my Ubuntu desktop seems to crash when doing `sudo apt install nvidia-driver-430 libnvidia-gl-430 libnvidia-gl-430:i386`

So i omitted that line and followed the rest. Now Battle.net opens and has started downloading SC2. There was a bit of delay before downloading started. Before that, battle.net would sometimes open but freeze the system. 

The log is empty for some reason

**Comment by Micronetic** [comment]
> That was really helpful. Thank you. What did you have setup in terms of Vulkan, Esync etc? Did you use the wine version in your package or via the Lutris guide?

I am using the wine version of the Lutris guide. And on the screenshot are the settings I am using for WoW/Bnet: https://i.imgur.com/ePpFYa2.png

**Comment by MGadhvi** [comment]
# Update

Starcraft 2 installed correct and could open. As soon as it did, my computer froze. After some investigation, the issue seems to be with the nvidia driver for my graphics card (GeForce gt 1030) as there was no issue with my on board graphics card. Again, this wasn’t an issue with the previous version

**Comment by Micronetic** [comment]
What if you try the 440 Nvidia driver version? It is the one I am using.

**Comment by strycore** [comment]
This should be fixed in master.

**Comment by MGadhvi** [comment]
Confirmed that this is working now. Had a few games.

Startcraft is now stuck on updating. I don't know if this is a different issue?

**Comment by strycore** [comment]
If the game itself gets stuck then yes, it's a different issue.

Closing this and marking it for 0.5.6

**Comment by consideRatio** [comment]
Arrived here on Ubuntu 20.04 with Lutris 6.0, but closing the login window manually and waiting 30 seconds or so after that did the trick to reach "installation complete", which allowed me to then start the battle.net software to install SC2.

**Comment by strycore** [comment]
I think there is another, separate issue regarding Battle.net. I'm also experiencing heavy slowdowns while using this client.

**Comment by Micronetic** [comment]
> but closing the login window manually and waiting 30 seconds or so after that did the trick to reach "installation complete"

The Lutris installer even says you should manually close the login window while installing at the top in the window...

**Comment by consideRatio** [comment]
Hmmm, for me it said that i shouldn't try login but instead wait for it to automatically close. I assume this is a difference in version or similar.

**Comment by Micronetic** [comment]
> Hmmm, for me it said that i shouldn't try login but instead wait for it to automatically close. I assume this is a difference in version or similar.

This could be possible, I am on Arch and got the latest version. I remember it didn't say you should close it manually some months ago and that you had to wait. I closed it back then manually nonetheless and it worked.
