### ISSUE TITLE
Provide an installer directive to cat files together

### ISSUE THREAD

**Issue by testfest12** [lutris/lutris#271]
Hi

I was trying to write an installer for the GOG version of [The Witcher 2](https://lutris.net/games/the-witcher-2-assassins-of-kings-enhanced-edition/). Usually the GOG installer for a game can just be unzipped and everything works but in this case there is an additional step that needs to be followed.

The installer contains three files named pack0.dzip.split0{0..2} (2-4GB each). These need to be merged into pack0.dzip for the game to start. After unzipping the installer I need to run
`cat pack0.dzip.split0* > pack0.dzip`.

I found the merge directive but it seems to merge the content of a source directory to the destination directory (or copies it, if dest doesn't exist).

So what would be the best solution for this problem? I think implementing a new directive is the way to go:

```
concat:
   src:
       - file1
       - file2
       - file3
   dst: destinationFile
```

But maybe some of you have a better idea.

**Comment by Xodetaetl** [comment]
There is an installer for The Witcher 2 GOG that does this already (with a bash script). I just forgot to republish it after fixing it last week...

We could have a shell_command directive that would cover this case and many others.
What do you think @strycore ?

**Comment by strycore** [comment]
> We could have a shell_command directive that would cover this case and many others.
What do you think @strycore ?

The execute command can do that already (see Neverwinter Nights where I call /bin/chmod). I know there's another script out there where I call /bin/bash with a more advanced command as the argument.

Only problem is that the absolute path to the executable has to be provided but we can fix that.

As for a concat directive, sure, why not.

**Comment by dennisjj5** [comment]
I'd say, why not rename the existing 'merge' action to 'move', since that's what it is (seemingly) doing, and add the new action as 'merge'.

**Comment by strycore** [comment]
Move is already an existing command and it's different from merge (which doesn't move anything).
