### ISSUE TITLE
Install script fails when one Monitor is disabled in Gnome on Xorg

### ISSUE THREAD

**Issue by raohag** [lutris/lutris#2710]
**Describe the bug**

I have my TV connected to my PC but not always active, together with two monitors.
When said TV is disabled in the display configurator, Lutris fails to continue on install scripts as it tries to grab the Screenwidth of my disabled monitor (my guess).
I got the install script running upon re-enabling my TV.

**Expected behavior**

Normal installation of any game

**Current behavior**

Upon selecting the install script, the window goes blank and the stacktrace appears in the console.

**Steps to reproduce**

- Have (at least) two monitors
- Have one disabled
- Try to install a game

**Lutris debugging output**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 237, in on_installer_selected
    self.prepare_install(installer_slug)
  File "/usr/lib/python3.8/site-packages/lutris/gui/installerwindow.py", line 195, in prepare_install
    self.interpreter = interpreter.ScriptInterpreter(install_script, self)
  File "/usr/lib/python3.8/site-packages/lutris/installer/interpreter.py", line 151, in __init__
    self.current_resolution = DISPLAY_MANAGER.get_current_resolution()
  File "/usr/lib/python3.8/site-packages/lutris/util/graphics/displayconfig.py", line 635, in get_current_resolution
    return str(current_mode.width), str(current_mode.height)
AttributeError: 'NoneType' object has no attribute 'width'
```

**System information**

Not necessarily applicable.
NVIDIA Proprietary drivers,
Gnome on X.org

**Screenshots**
TV Enabled:
![image](https://user-images.githubusercontent.com/10381133/78351645-7029d780-75a7-11ea-8519-def60996b0fc.png)
TV Disabled:
![image](https://user-images.githubusercontent.com/10381133/78351843-c3038f00-75a7-11ea-914f-4b91b088391e.png)

**Comment by mario-marin** [comment]
Dont know if this helps but I have the same behavior/problem.

**Comment by strycore** [comment]
I pushed a fixed for that but haven't been able to test it because I'm unable to switch off monitors individually in my version of Gnome.
