### ISSUE TITLE
Ubuntu 16.04 xenial installation fails from the repositories

### ISSUE THREAD

**Issue by blretribution** [lutris/lutris#2711]
**Describe the bug**

I can not install lutris in my ubuntu xenial i am trying to install lutris but terminal output gives me an error

**Expected behavior**

Normal installation of the software

**Current behavior**

Using the commands to add the lutris repository and install from it gives me an error

**Steps to reproduce**

- Ubuntu 16.04 LTS xenial
- sudo add-apt-repository ppa:lutris-team/lutris
- sudo apt-get install lutris

**Lutris debugging output**

Not necessary i can't install lutris

**System information**

luser@LubuntuL:~$ inxi -F
System:    Host: LubuntuL Kernel: 4.4.0-176-generic x86_64 (64 bit)
           Desktop: LXDE (Openbox 3.6.1) Distro: Ubuntu 16.04 xenial
Machine:   System: Dell (portable) product: Latitude E6400
           Mobo: Dell model: 0X574R Bios: Dell v: A34 date: 06/04/2013
CPU:       Dual core Intel Core2 Duo P8600 (-MCP-) cache: 3072 KB 
           clock speeds: max: 2401 MHz 1: 1600 MHz 2: 1600 MHz
Graphics:  Card: NVIDIA G98M [Quadro NVS 160M]
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
![Screenshot from 2020-04-03 13-09-13](https://user-images.githubusercontent.com/63115828/78387240-fc8ac900-75ac-11ea-8c3e-df0d1d7b20cb.png)
![Screenshot from 2020-04-03 13-13-27](https://user-images.githubusercontent.com/63115828/78387259-03b1d700-75ad-11ea-8b28-bf2a2635e5ef.png)

**Screenshots**

**Comment by strycore** [comment]
The Ubuntu 16.04 repository no longer exists. Even if it did, the current code wouldn't run on this distribution.
Please update to 18.04

**Comment by strycore** [comment]
For Ubuntu, do not use the OpenSUSE Build Service. Use the Launchpad PPA: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris

**Comment by blretribution** [comment]
> For Ubuntu, do not use the OpenSUSE Build Service. Use the Launchpad PPA: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris

Thanks
