### ISSUE TITLE
Lutris fails to launch (ValueError: Received incorrect value for ldconfig line: R9P)

### ISSUE THREAD

**Issue by Volkor3-16** [lutris/lutris#2717]
I (and [one other reddit user](https://old.reddit.com/r/Lutris/comments/fv7g3m/lutris_stopped_launching/)) am unable to open lutris at all.

**Expected behavior**

lutris opens

**Current behavior**

it doesn't open

**Steps to reproduce**

- Have debian sid
- open lutris from terminal

**Lutris debugging output**

```
Traceback (most recent call last):
  File "/usr/games/lutris", line 34, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 34, in <module>
    from lutris import pga
  File "/usr/lib/python3/dist-packages/lutris/pga.py", line 10, in <module>
    from lutris.util import sql, system
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 10, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 419, in <module>
    LINUX_SYSTEM = LinuxSystem()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 124, in __init__
    self.shared_libraries = self.get_shared_libraries()
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 326, in get_shared_libraries
    lib = SharedLibrary.new_from_ldconfig(lib_line)
  File "/usr/lib/python3/dist-packages/lutris/util/linux.py", line 391, in new_from_ldconfig
    raise ValueError(
ValueError: Received incorrect value for ldconfig line: R9P
                                                           *P"@:P
```

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

Can't even run the command to generate json, but:

- ryzen 5 2600/nvidia 1070/ 16gb ram
- debian unstable/sid
- Linux 5.4.0-4-amd64 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux

**Comment by violaian1** [comment]
I am having the same issue too. Lutris gui does not launch, but the app is running in the background. Not sure how to get a log tho.

Arch Linux
Ryzen 7 1700
R9 290

Tried both lutris and lutris-git packages, uninstalled and reinstalled both. Cleaned the app cache. Deleted config folder. Nothing works.

**Comment by strycore** [comment]
What in the name of he who shall not be named is the output of your ldconfig? 
What did you do to your system? This is insanity!!

**Comment by Chance4us** [comment]
@Volkor3-16 after updating of libc6 to libc6 2.31.0experimental0 on my debian lutris worked again.
So libc6 seem to be broken.

**Comment by Volkor3-16** [comment]
Updating again today has fixed the problem for me on debian sid. ¯\_(ツ)_/¯

**Comment by strycore** [comment]
Going to remove the exception raising since ldconfig is no longer trustworthy…
