### ISSUE TITLE
Problem with wine steam runner

### ISSUE THREAD

**Issue by psychaos999** [lutris/lutris#2723]
Whenever Lutris try to install steam windows client Xorg crashes and Im back to login screen

**Comment by legluondunet** [comment]
Please start Lutris from a terminal with this command:
lutris -d>lutris.txt

and post the txt file here

**Comment by psychaos999** [comment]
I solved the problem with
export SDL_VIDEODRIVER=X11
Log was saying sdl couldn't find a screen, or something like that

**Comment by strycore** [comment]
Ok, that's doesn't look like a lutris bug
