### ISSUE TITLE
Removing and no game folder

### ISSUE THREAD

**Issue by RDL-28** [lutris/lutris#2726]
hi.
If you add a game manually, then when you delete it you can’t set the “delete all data” flag.

<a href="https://imgur.com/N5kJqsW.png">
  <img src="https://imgur.com/N5kJqsW.png" />
</a>

**Comment by strycore** [comment]
The game folder is specified at install time, for manually added games, lutris has no way of figuring out the game folder. I'm thinking about making this editable but that has to be integrated into the "Move game" feature we want to add.

For now, I can add an easy fix and make the game folder default to the path of the executable. This will likely be correct for most games except Windows games which would use something closer to "drive_c/Program Files/Game/"

**Comment by RDL-28** [comment]
Sometimes in games, the executable is located in subfolders.
For example, "D: \ Games \ namegame \ bin \ game.exe"
By your logic, the bin folder will be deleted, but the namegame folder will remain.
It would be logical to make the "Game Catalog" field where it will be possible to specify the game directory. Ie "D: \ Games \ namegame \"
After removal, the directory with the play and the directory with the prefix should be deleted.

**Comment by strycore** [comment]
It would be pretty simple to check wine games for the presence of a `drive_c` folder and `user.reg` file in the parent directories of the exe.
If the prefix and the game are separated then there's really nothing that can be done.
