### ISSUE TITLE
winekill script option is inefficient

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2727]
Hello,
after installing dotnet35sp1 with winetricks, some process do not terminate at the end of the install, you have to kill them.

So in a script I tried to use:
```
- task:
    arch: win64
    name: winekill
    prefix: $GAMEDIR
```
Even if the Lutris script correctly execute this command, it stayed some active processes in the WIneprefix: mscorsvw.exe

Finally the only efficient way is to execute this command:
`killall -9 explorer.exe services.exe plugplay.exe mscorsvw.exe winedevice.exe`

Normally "winekill" option script should be as efficient as the command above, isn't it?
Is this an issue?

Thank you for your help.

**Comment by tannisroot** [comment]
Already fixed by https://github.com/lutris/lutris/commit/aaadb29ccc8ba4d0134b66c276de41a753e923a9. Should arrive in the next release.
