### ISSUE TITLE
[Humble Bundle] Multiple file install issue

### ISSUE THREAD

**Issue by Adam-Stambaugh** [lutris/lutris#2731]
Humble install scripts for games that have multiple installers/archives aren't working. I've tested Cave Story+, Braid, Hyper Light Drifter, Hollow Knight, Shovel Knight, and Bit.Trip Runner. It worked fine with Hollow Knight and Shovel Knight, since they only have a single option on Humble. Cave Story+ and Hyper Light Drifter failed. Braid tried to download the first option from Humble, but that's the wrong file for the script. Even when signed out from Humble, it doesn't give the option to select the files I downloaded beforehand.

**Expected behavior**

The option to choose which file to download from Humble when there are multiple files.

OR

The script automatically select which file, possibly predefined by the author of the script.

**Current behavior**

It either fails completely or attempts to download the first file from Humble, which the installer script may not be designed for.

**Steps to reproduce**

- Try to install a game through Lutris that has multiple options for Linux downloads.

**Lutris debugging output**

[lutris.log](https://github.com/lutris/lutris/files/4459756/lutris.log)

**System information**

[lutris-issue-report.txt](https://github.com/lutris/lutris/files/4459755/lutris-issue-report.txt)

**Screenshots**

![Screenshot_2020-04-09_21-47-44](https://user-images.githubusercontent.com/49969486/78960201-dbf6cd80-7adc-11ea-85b5-054b9dcf43da.png)
![Screenshot_2020-04-09_21-48-47](https://user-images.githubusercontent.com/49969486/78960208-e0bb8180-7adc-11ea-9612-a41b34d8c6b3.png)

**Comment by strycore** [comment]
I've written a quick fix that deprioritize deb files over the other ones. I've tried it with cave story and braid and it worked fine. 
This needs a bit more work to cleanly handle this but this mostly depends on the file-picker branch to be merged in so that fix will do for now.
