### ISSUE TITLE
GOG download options

### ISSUE THREAD

**Issue by axet** [lutris/lutris#2732]
Hello! I'm listing few features lutrics must have to handle games propertly.

1) Download games from GOG have several issues. Some games have double installers (32 and 64) listed as one download. For example Styx listed 6 files, 3 of them 32 installer size of 6 gb, and second 3 links represents anoter 6 gb of the same game but with 64bit installer. Would be nice to have filter option available using install script and download dialog. This issue mentioned related to Humble Bundle as well here: https://github.com/lutris/lutris/issues/2731

  * https://www.gog.com/game/styx_master_of_shadows
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer0
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer1
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer2
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer3
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer4
  * https://www.gog.com/downloads/styx_master_of_shadows/en1installer5

2) Some games on GOG has separate installer for different language for example STALKER has russian installer and english installer as separate download links. Would be nice if Lutris allow me to create installer scripts which choice correct language version as well as download dialog which shows me what I can get from GOG. Dialog may have option to use already downloaded file. Similar issue here: https://github.com/lutris/lutris/issues/2321

  * https://www.gog.com/game/stalker_shadow_of_chernobyl
  * https://www.gog.com/downloads/stalker_shadow_of_chernobyl/en1installer4
  * https://www.gog.com/downloads/stalker_shadow_of_chernobyl/en1installer5
  * https://www.gog.com/downloads/stalker_shadow_of_chernobyl/ru1installer4
  * https://www.gog.com/downloads/stalker_shadow_of_chernobyl/ru1installer6
  * https://www.gog.com/downloads/stalker_shadow_of_chernobyl/ru1installer7

3) Some games has additional exe to launch when configured and prepared resolution. Would be nice to have lutrics support multiply runners for one game. STALKER has resolution configuration separate from game executable and some other games like Evil Islands.

  * https://www.gog.com/game/evil_islands

4) Some GOG games has DLC available trough default content links and it would be nice if lutrics can catch it up and suggest to install or download it via script / installer. Games like EVERSPACE.

  * https://www.gog.com/game/everspace

5) Nice to have option to sign in with different credentials / multiply accounts for GOG and others platforms. I have multiple accounts and have to sign in / logout manually.

6) If game misses on current gog account install script will crash and give no option to use predownloaded gog game with following error: "TypeError: 'NoneType' object is not subscriptable"

7) Optionally. Some games has double installers for Linux/Windows. And surprisingly windows version under wine works faster then native linux port. For example Everspace game. Nice to have script option to select OS which I want download content for (filter links) so we can prepare different installers scripts.

Considering all above we can handle it by adding additional installers if lutris add script command to filter download content by os/language/name. And additional we can have better dialog with multiply download options (and local files as source)

EDIT: https://lutris.net/games/stargunner/ trying to download gog windows installer and failed, since script written for linux version.

**Comment by axet** [comment]
Since GOG sometimes offers multiple downloads even files we do not need to download we need a name filter. And suggested download dialog will work with a multiply file sources if file name match a name filters.

![2020-04-17 01 37 15](https://user-images.githubusercontent.com/298672/79514142-28e32280-804e-11ea-9648-ff8d9a1c69c8.jpg)

If source match some file filters then it shown first and its done. Sources can be represented by multiple gog accounts, torrents, magnet links, local folders or individual files.

Adding sources from command line can ease life. `lutris -i game1 --source magnet:dfdfdfdf -source gog@name:password`

**Comment by strycore** [comment]
@axet if you're going to be drawing mockups for this, you'd better check the file-picker branch here. It's horribly out of date though, it's based on lutris 0.5.4.

**Comment by axet** [comment]
Another idea, for GOG we can use direct download links instead of filters, like:

```
files:
 - goginstaller: https://www.gog.com/downloads/evil_islands/ru1installer1
```

To download correct file with specific language. Right now lutris failed to download it.

**Comment by strycore** [comment]
This is not how Lutris implements GOG support, please read the current implementation!!

**Comment by strycore** [comment]
closing this since this is only confusing me and most of the work is done.
