### ISSUE TITLE
Steam (native) runner relaunching first game when Steam was not running before the first launch doesnt work.

### ISSUE THREAD

**Issue by UXELDUXEL** [lutris/lutris#2739]
**Describe the bug**
If a game is launched when Steam is not running then that game cannot be relaunched after it has been closed once until the steam client was also closed.

**Expected behavior**
Relaunching a game is always possible no matter if Steam was running prior to lutris or not.

**Current behavior**
Whenever I run a game (Steam is closed) by pressing the "Play" Button in Lutris it opens Steam and the game. After i have closed the game, i can launch any other game except the one that caused Steam to be launched. All I can press instead of play is stop. When pressing "Stop" sometimes it closes the Steam client (which allows me to relaunch the inital game) and sometimes does nothing. To relaunch the game I have to more often than not close the Steam client manually.

**Steps to reproduce**

- Stop Steam Client
- Run a Native Steam Game (I tested with Stellaris)
- Close the game once it opens.
- Trying to relaunch the same game runs into the issue described above.

**Lutris debugging output**
INFO     2020-04-12 20:35:59,227 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-04-12 20:35:59,227 [startup.check_driver:55]:Using NVIDIA drivers 440.64 for x86_64
INFO     2020-04-12 20:35:59,227 [startup.check_driver:60]:GPU: GeForce GTX 1080 Ti
INFO     2020-04-12 20:35:59,227 [startup.check_driver:79]:GPU: 10DE:1B06 1458:374C using nvidia drivers
INFO     2020-04-12 20:35:59,227 [startup.check_driver:79]:GPU: 8086:3E92 1043:8694 using i915 drivers
INFO     2020-04-12 20:35:59,277 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-04-12 20:35:59,278 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-04-12 20:35:59,404 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-04-12 20:35:59,406 [store.get_missing_media:198]:Requesting missing icons from API for appid_4560, yes-your-grace, star-wars-the-force-unleashed-ultimate-sith-edition, star-wars-knights-of-the-old-republic-ii-the-sith-lords, total-war-napoleon-definitive-edition, doom-eternal, dont-starve-together
DEBUG    2020-04-12 20:35:59,406 [http.get:65]:GET https://lutris.net/api/games
INFO     2020-04-12 20:35:59,598 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2020-04-12 20:35:59,616 [api.get_game_api_page:132]:Loaded 3 games from page 1
DEBUG    2020-04-12 20:36:03,166 [application.launch:339]:Launching Stellaris (steam) (140576878800688)
INFO     2020-04-12 20:36:03,167 [runner.use_runtime:241]:Runtime disabled by system configuration
DEBUG    2020-04-12 20:36:03,168 [game.play:295]:Prelaunching <lutris.runners.steam.steam object at 0x7fda9af2f9e8>
DEBUG    2020-04-12 20:36:03,169 [display._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2020-04-12 20:36:03,204 [system.execute:38]:Executing pgrep steam$
INFO     2020-04-12 20:36:03,211 [runner.use_runtime:241]:Runtime disabled by system configuration
DEBUG    2020-04-12 20:36:03,211 [game.configure_game:331]:Launching Stellaris: {'command': ['/usr/bin/steam', 'steam://rungameid/281990'], 'env': {'DRI_PRIME': '1'}}
DEBUG    2020-04-12 20:36:03,211 [game.configure_game:332]:Game info: {
  "command": [
    "/usr/bin/steam",
    "steam://rungameid/281990"
  ],
  "env": {
    "DRI_PRIME": "1"
  }
}
DEBUG    2020-04-12 20:36:03,213 [command.start:112]:Running /usr/bin/lutris-wrapper 0 0 /usr/bin/steam steam://rungameid/281990
DEBUG    2020-04-12 20:36:03,213 [command.start:114]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2020-04-12 20:36:03,214 [command.start:114]:ENV: DRI_PRIME="1"
DEBUG    2020-04-12 20:36:03,214 [command.start:114]:ENV: game_name="Stellaris"
DEBUG    2020-04-12 20:36:03,214 [command.start:114]:ENV: PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2020-04-12 20:36:41,301 [game_actions.on_stop:172]:Removed game with ID 21 from running games
DEBUG    2020-04-12 20:36:41,302 [command.on_stop:161]:The process has terminated with code 3840
DEBUG    2020-04-12 20:36:41,302 [command.stop:246]:Management process looks dead already.
INFO     2020-04-12 20:36:41,303 [command.on_stop:167]:Full shutdown prevented
DEBUG    2020-04-12 20:36:43,240 [game.beat:622]:Game thread stopped
WARNING  2020-04-12 20:36:43,240 [game.on_game_quit:654]:Game still running (state: running)
INFO     2020-04-12 20:36:43,240 [game.stop:637]:Stopping Stellaris (steam)
DEBUG    2020-04-12 20:36:43,241 [command.stop:246]:Management process looks dead already.
DEBUG    2020-04-12 20:36:43,268 [game.on_game_quit:673]:Stellaris stopped at So, 12 Apr 2020 20:36:43
DEBUG    2020-04-12 20:36:43,268 [game.save:234]:Saving Stellaris (steam)
DEBUG    2020-04-12 20:36:43,280 [lutriswindow.on_game_updated:721]:Updating game Stellaris (steam)

Workaround:
The main issue i think is due to the Steam client beeing started as a child process of lutris wrapper and the pyhton script does not terminate until all child processs have truely exited. With this knowledge I have found a workaround which always allows me to relaunch the game. In the Steam Runner Config in the "Runner options" tab I specified a custom shell script in the "Custom executable for the runner" field.  In my custom script I first attempted to run the steam command with setsid prefix but that alone sadly did not work. I do not know what methods you use to check if the child process of the child are still running but simply starting steam and the game with setsid and also killing the parent process (lutris-wrapper) works. So my final "Custom executable for the runner" script looks like this:

#!/bin/bash
setsid /usr/bin/steam "$@" </dev/null &>/dev/null & disown
kill -9 $PPID

This way the Play button only flickers to the "Stop" button and instantly turns back to "Play" allowing me to relaunch the game. (Btw this is also the behavior for every launched Steam game without my script if Steam is already running prior to the launch, so my script is not really changeing the behavior there...) 

Suggestion:
I am aware that detecting if the game is still running or not is not a trivial task at all, so I would suggest that you add a simple checkbox to the runners that allows us to specify if we want to wait for the games termination or not before allowing a relaunch of the game. That way i wouldn't need such a dirty hack as a workaround and could just simply check that box in the Steam runner config.

**Comment by JFingerle** [comment]
I encountered the same problem problem this week and I'm using a similar woraround now.

I use Lutris to launch all my Game (Steam, native, etc.) so I would love a solution here.

**Comment by strycore** [comment]
The game never stops because the internal game process isn't monitored, once the subprocess monitor is able to get track of Steam's (or another game launcher) game then the problem won't occur.

Closing this ticket as the subprocess monitor feature is tracked on #3372
