### ISSUE TITLE
Not booting properly after installing drivers

### ISSUE THREAD

**Issue by ilyocoris** [lutris/lutris#2740]
I am in Ubuntu 18.04 and followed the instructions to install vulkan drivers for intel. After rebooting to set the changes, the computer goes to a black screen with green [OK]s to the left and white text. I can enter through recovery mode, although screen is zoomed in.

I think there is some sort of issue with the graphic card driver's, i do not know if it has a relationship to this:
*-display UNCLAIMED       
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
Either way I am a bit lost and would very much appreciatte some help.

Thank you.

**Comment by byte1024** [comment]
Depending on if someone else suggests something else, personally, I would slowly and carefully try to undo what was done. eg apt-get remove the vulkan driver (make sure what it wants to remove is ok before accepting).

See what happens. Absolute worst case you need to backup files install again. But as long as you can get to a command line one way or another you should be able to get through it without a new install if you do the right things.

**Comment by strycore** [comment]
You launched `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` and rebooted and then your desktop wouldn't show up? Is that it?

**Comment by tannisroot** [comment]
No response in months, closing.

**Comment by ilyocoris** [comment]
Hey sorry for not replying, I ended up having to delete and reinstall the
ubuntu partition of my computer, but luckily could save its contents.

Cheers!
