### ISSUE TITLE
Add support for itch.io downloads

### ISSUE THREAD

**Issue by axet** [lutris/lutris#2746]
Hello!

Having static files section has it's own issues. Right now only 'url', 'filename' and 'referrer' are supported but some sites require additional scripting to get download links.

For example to add games from itch.io you need ask for CDN dynamic url address (for load purpose or protection, I do not know) which can be done by simple script:

wget $(curl -X POST https://rayfowler.itch.io/remnants-of-the-precursors/file/2122764 | jq -r .url)

I face this issue trying to add game https://lutris.net/games/remnants-of-the-precursors/

It can be done with expanded script (scripts for stores), or inside lutris it self.

**Comment by strycore** [comment]
I think the best way to handle this would be to add support for Itch.io specifically like we do for Humble Bundle and GOG.
Trying to come up with some scripting solution that is flexible for a number of unknown use case will just create an unmaintainable mess.

**Comment by Moth-Tolias** [comment]
would love to see this happen, the official itch client is quite a pain to work around. [butler](https://github.com/itchio/butler) [which i understand is the bit that actually manages all the downloading] is open source though, so that should make things easier hopefully.

**Comment by strycore** [comment]
closing in favor of issue #243
