### ISSUE TITLE
Lutris 5.6 Guild Wars 2

### ISSUE THREAD

**Issue by hunabku94** [lutris/lutris#2747]
**Describe the bug**

Guild Wars 2 Crash with Lutris 5.6 but not with Lutris 5.5

**Expected behavior**

Show Arena crash window after showing first character screen image

**Current behavior**

What is the current behavior?

**Steps to reproduce**

- Install lutris-git
- [Optionnal] Install Guild Wars 2
- Launch Guild Wars 2

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by strycore** [comment]
This is incomplete. Please reopen with terminal output.
