### ISSUE TITLE
World of Warcraft unplayable on battery

### ISSUE THREAD

**Issue by ferdinando-arfe** [lutris/lutris#2755]
Hello, i have a Asus Rog Strix GL503VM with Core i7-7700 HQ+NVIDIA 1060 GTX running Ubuntu 19.10 and Lutris: when i play World of Warcraft : Battle for Azeroth in battery mode i've to reduce all the settings at level 2 or minus and in some case the brightness sensor start to blink in the middle of the screen and my character become unplayable. When i play attached to the power surge all is great and i can play at maximum settings. Is there something that i miss in the configuration of Lutris or is it normal? Thanks in advance for the reply.

**Comment by strycore** [comment]
looks like installing gamemode would help

**Comment by ferdinando-arfe** [comment]
Ok, i'll try then!

**Comment by tannisroot** [comment]
Not a client bug, closing.
