### ISSUE TITLE
proton 5.0-6

### ISSUE THREAD

**Issue by axet** [lutris/lutris#2772]
Hello!

Proton is Steam wine version (I know you know). It is looks open-source (not sure if all source available and all toolchains are open-source) solution and can be complied from sources. Whole process takes about 4 hours and requires a few skills which not every gamer has. Would be nice to see one more version of wine available to download "proton 5.0-6" using lutris client. It allows to run Doom Ethernal and it is always nice to have another runner to try.

Proton depends on recent Nvidia drivers **or** Mesa 19.1 which already available to the end users with recent Ubuntu release. So, only Proton it self is missing.

To see mesa version run: `glxinfo | grep "OpenGL version"`

To build proton on Ubuntu follow few simple steps:

```
sudo apt install virtualbox vagrant-sshfs vagrant

reboot # to refresh vbox group

git clone --recurse-submodules https://github.com/ValveSoftware/Proton.git proton
cd proton
vagrant up --provider virtualbox
make proton
make redist
tar xvf vagrant_share/proton-5.0-6/proton_dist.tar.gz -C ~/.local/share/lutris/runners/wine/proton-5.0-6/
```

Having crossover wine would be nice option too...

**Comment by GloriousEggroll** [comment]
Lutris already detects proton versions installed on the system and can be chosen in the runner drop down menu for each game. There is no need to redownload it.
