### ISSUE TITLE
Feral gamemode option does not support GAMEMODERUNEXEC

### ISSUE THREAD

**Issue by sgleizes** [lutris/lutris#2775]
**Describe the bug**

This bug is about the `Feral gamemode` system option and integration with the `gamemoderun` helper script. This script picks up `libgamemodeauto.so` for LD_PRELOAD and additionally allows a command prefix `GAMEMODERUNEXEC` to wrap the given command (see [gamemode hybrid GPU](https://github.com/FeralInteractive/gamemode#note-for-hybrid-gpu-users)).

In my case I use this env var to set the appropriate environment so that games use my discrete GPU (see [optimus-manager hybrid mode](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode#for-lutris)). I could just add these 3 variables to the lutris system config, but gamemode is the better place to encapsulate these settings.

While it (strangely) seems to work for wine games even though the same method is used (LD_PRELOAD), I have a different behavior with a Linux native game (Eggnogg+ in my case).

**Expected behavior**

The game is launched using `gamemoderun` so that my gamemode command prefix is used.

**Current behavior**

The game is launched using `LD_PRELOAD="libgamemodeauto.so"`, so GAMEMODERUNEXEC is not run (even though gamemoded is properly started).

**Steps to reproduce**

- [Install Eggnogg+](https://lutris.net/games/eggnogg/)
- Make sure gamemode and lib32-gamemode are installed and `Feral gamemode` is enabled in lutris
- Set `GAMEMODERUNEXEC` to `echo`
- Run Eggnogg+ from lutris

With this value, the game is not expected to launch since the GAMEMODERUNEXEC wrapper should simply print out the game command. The fact that it launches demonstrates the issue.

**Comment by strycore** [comment]
I've removed support for the old version of gamemode which used LD_PRELOAD. Now, if gamemoderun is in your PATH it should be detected and used.
