### ISSUE TITLE
Abstract Base Class for Syncer

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2776]
**Expected behavior**
Shouldn't all Syncer class be derived from an ABC (Abstract Base Class)?
From what I can tell in lutriswindow.py, the Syncer class is used and it's always expected to have load and sync methods.

Also, maybe abstracting this will pave the future where each runner will be an individual installable module?

**Comment by strycore** [comment]
It's going to be refactored eventually and I likely won't use an Abstract Base Class
