### ISSUE TITLE
Add an option to disable DXVK's d3d9 implementation

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2782]
Why this is needed -  DXVK's d3d9 implementation is still quite new and somewhat WIP and has plenty of issue.
For example, due to lack of partial presentation support, DXVK currently can't render .Net apps that use d3d9 for presentation, they will be just look black. A good real life example of it is MTGALauncher.exe - with wined3d it renders just fine, but with DXVK it looks almost completely black. However, I can't just disable DXVK completely, because the game itself (MTGA.exe) is a d3d11 app, and it doesn't render properly with wined3d on Ultra settings (most of the environment is black). Right now, in the game script (https://lutris.net/games/install/17330/view) I install DXVK through Winetricks and then set d3d9.dll through overrides to builtin, which is a messy hack that will not allow Lutris to update DXVK to a newer version later on.

**Comment by papjul** [comment]
I now understand why some "games" I had were working in DXVK 1.4.6 but no longer with a black window in 1.5 (D3D9 was merged in 1.5):
- Affinity Photo https://lutris.net/games/affinity-photo/
- Affinity Designer
- Affinity Publisher

**Comment by legluondunet** [comment]
L.A.Noire is also affected by this issue.

**Comment by strycore** [comment]
I wrote a patch but haven't tested it.
