### ISSUE TITLE
MAME observations

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2785]
Something I noticed today:

1) When you select a machine, Lutris will show the platform in the right side-panel, but will not show up under platform in the left side-panel

2) Will it be possible to add an argument field? one where you can add arguments when needed by the driver IE The maciici driver (for mame) you need to specify -ramsize or for Apple2e to get joystick support you need -gameio joy. It's motly usefull for slot devices 

For 2) don't think we need to worry about it too much (ie create a pull down-list as I doubt a lot of people will use that functionality

**Comment by strycore** [comment]
1) noticed it as well, I'll look into it
2) easy to implement, no problem at all

**Comment by strycore** [comment]
Side effect of fixing the first issue… 

![Peek 2020-06-26 00-05](https://user-images.githubusercontent.com/280336/85843164-a82f5980-b755-11ea-94b8-7f459d66bc10.gif)
