### ISSUE TITLE
Disable Gnome Night Light during games on Wayland

### ISSUE THREAD

**Issue by xordspar0** [lutris/lutris#2786]
Problem: Lutris can disable night light on X using xgamma. On Wayland, client programs can't directly change the color settings like that.

Solution: I don't know of any Wayland protocol or protocol extension that exposes this, so I think we need to talk to talk to Gnome directly using a DBus API. Here is how Gnome shell does it (in Javascript): https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/status/nightLight.js

```javascript
        this._proxy = new ColorProxy(Gio.DBus.session, BUS_NAME, OBJECT_PATH,
                                     (proxy, error) => {
                                         if (error) {
                                             log(error.message);
                                             return;
                                         }
                                         this._proxy.connect('g-properties-changed',
                                                             this._sync.bind(this));
                                         this._sync();
                                     });
```

```javascript
        this._disableItem = this._item.menu.addAction('', () => {
            this._proxy.DisabledUntilTomorrow = !this._proxy.DisabledUntilTomorrow;
        });
```

Here is the documentation for the GSettings API for C clients: https://developer.gnome.org/gio/stable/GSettings.html. I haven't tracked down the corresponding Python documentation yet.

**Comment by A6GibKm** [comment]
The DBus API you want is [org.gnome.SettingsDaemon.Color](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/data/dbus-interfaces/org.gnome.SettingsDaemon.Color.xml), which is used at [nightLight.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/status/nightLight.js) (updated link). Here are the python docs for [GDBusProxy](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/DBusProxy.html#Gio.DBusProxy).

In general using gnome shell dbus interfaces is highly discouraged as these are not stable and could break at any time.

**Comment by xordspar0** [comment]
> Problem: Lutris can disable night light on X using xgamma.

Is it true that this already works on X? I think I misunderstood #587 to imply that Lutris did know how to control night light on X, but I don't see any evidence of this in the code.

I would be happy to add support for this in Wayland if it were already supported in X. It doesn't look hard at all to hook into the gsettings API. But I'm not as interested in advocating for adding this feature if it doesn't already exist. Maybe it isn't Lutris's job to manage the night light.

I'm closing this for now, but anyone who's interested in this feature can feel free to continue to discuss it (though over the past 2 years it looks like there has been no interest).

**Comment by A6GibKm** [comment]
@xordspar0 The reason there isn't much interest (at least from my part) is that there simply isn't an API to control night light. If anyone wants to help producing a correct solution, that would involvee contributing with upstream.

See https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5222

> Is it true that this already works on X

Yes, in X apps can do whatever they want to the screen

**Comment by xordspar0** [comment]
> Yes, in X apps can do whatever they want to the screen

True, but it doesn't seem like Lutris currently supports automatically resetting gamma and restoring it to its original value after a game exits. I guess I wanted this feature 2 years ago when I opened this issue, but now I agree with Daniel in the upstream Gnome issue that you [linked to](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5222#note_1410751):

> If you need night light on then you probably need it on in all apps. But if anyone wants to turn it off then that's only a couple of clicks away in the system menu.
> 
> Seems very subjective and therefore something the user should do manually rather than allowing an app to break the user's (probably intended) night light.

**Comment by A6GibKm** [comment]
> > Yes, in X apps can do whatever they want to the screen
> 
> True, but it doesn't seem like Lutris currently supports automatically resetting gamma and restoring it to its original value after a game exits. I guess I wanted this feature 2 years ago when I opened this issue, but now I agree with Daniel in the upstream Gnome issue that you [linked to](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5222#note_1410751):
> 
> > If you need night light on then you probably need it on in all apps. But if anyone wants to turn it off then that's only a couple of clicks away in the system menu.
> > Seems very subjective and therefore something the user should do manually rather than allowing an app to break the user's (probably intended) night light.

That comment misses the point, right now apps can modify this stuff at will. There are two solutions:

- An interface to do so (or at least a subset of features) in an agnostic way where the user can opt-out
- removing the private api so that no one can do it in wayland
