### ISSUE TITLE
 Unable to locate package lutris

### ISSUE THREAD

**Issue by SaraNyn** [lutris/lutris#2787]
This is happening (again it seems, I found older references) when I follow the instructions to install on Linux Mint 18.3

**Comment by strycore** [comment]
We don't support Linux Mint 18.3. It's too old.

**Comment by SaraNyn** [comment]
and mint 19 won't install wine......great
60 inches of Black FuryBehold my my works ye mighty and despair.... 

    On Wednesday, April 22, 2020, 05:32:17 PM EDT, Mathieu Comandon <notifications@github.com> wrote:  
 
 


We don't support Linux Mint 18.3. It's too old.

**Comment by strycore** [comment]
Might have able to help more if I had been more information to begin with but sadly, that wasn't the case so yeah, find a way to upgrade to Mint 19 (or better yet, install another distro)

**Comment by SaraNyn** [comment]
You have taken on a tough job (Supporting all these favors of linux) and appreciate your efforts> The real problem is the lack of anything like centralization makes it certain that people will have a bad experience with the OS at some point.
60 inches of Black FuryBehold my my works ye mighty and despair.... 

    On Wednesday, April 22, 2020, 05:38:00 PM EDT, Mathieu Comandon <notifications@github.com> wrote:  
 
 


Might have able to help more if I had been more information to begin with but sadly, that wasn't the case so yeah, find a way to upgrade to Mint 19 (or better yet, install another distro)
