### ISSUE TITLE
uploading jpg become blackbox

### ISSUE THREAD

**Issue by axet** [lutris/lutris#2788]
Uploading this jpg fine at preview but blackbox after upload. This game:

https://lutris.net/games/frontier-elite-ii/

https://upload.wikimedia.org/wikipedia/en/3/32/Frontier_elite2_box.jpg

![Frontier_elite2_box](https://user-images.githubusercontent.com/298672/80071866-08cfc980-854e-11ea-88fc-da87ce7c4c88.jpg)

**Comment by AlexanderRavenheart** [comment]
This should probably be in https://github.com/lutris/website unless there's a new upload feature in Lutris application I'm unaware of.
