### ISSUE TITLE
[Feature Request] Date / Time format

### ISSUE THREAD

**Issue by john-2000** [lutris/lutris#2794]
**Current behavior**

The Lutris library highlights exactly when a program was last run or installed to the second! This is inconvenient and also rather messy

**Expected behavior**

Using human readable / relational dates and/or compressed date formats would be better, with the choice of showing either
a) parsed relational dates like 
last played: ... 5 min ago .... 5 months ago
installed: .... 3 years ago .... 2 days ago

b) compressed dates
last played:
at 15:00 --- if today at 15:00
yesterday --- if yesterday 
Friday --- if last Friday
10th of March -- if 10th of March
February-20 --- if in Feb
2019 --- if last year

An immediate alternative would be to at least drop the seconds in the display.

I am using Lutris 0.5.6 on Focal Fossa Ubuntu 20.04 amd64

**Comment by xordspar0** [comment]
Note that this is only in the list view. The right sidebar when you click on a game shows the day that the game was last played and the a human readable play time like "5 hours and 3 minutes". It looks like the last played time and installed time use your locale settings.

Here is the relevant code for textually representing the times, if anyone is interested in taking a look:

- Installed time: https://github.com/lutris/lutris/blob/master/lutris/gui/views/pga_game.py#L95
- Last played time: https://github.com/lutris/lutris/blob/master/lutris/gui/views/pga_game.py#L108

**Comment by john-2000** [comment]
Hi @xordspar0 thanks for the fast reply,
please accept my apology that my programming-fu is weak so this will by neither pythonic nor compact..

-- installed time:
simplest fix:
I have had a think about it - I am presuming that if the %X is changed to fixed version then  other locals would have a problem.

as a first solution I would propose dropping the time component from installed, I think the hour, minute and second a game was installed has no relevance. this should be straight forward

line 95:
`            time.strftime("%x", time.localtime(self._pga_data["installed_at"]))`

it would be nice to choose a time format in the settings or the conf file, perhaps making %x the default 

relative time: 
the natural library appears a nice way of [https://natural.readthedocs.io](url) appears to be a nice way of working 

`date.duration(time.time()-time.localtime(self._pga_data["installed_at"]), precision =2, pad=" ")`

with the precision parameter curtailing the output i.e. a game installed 2 years, 3 months, 2 days, 4 hours ago is shown as 2 years 3 months ago at precisions 2

Please let me know how I can help more

**Comment by malefice** [comment]
I understand the appeal in time differences expressed in a "humanized" manner but only up to a certain point and in certain situations. Beyond those use cases, I seriously have to question the practicality and the value it brings if a complete timestamp will just be better.

Personally, I have never needed to know when I installed a game post-installation, and if ever I will need to, I will just look up the complete timestamp VS dealing with how many units of time ago it was, and may the heavens have mercy on you if you still need it to be expressed as "today" or "yesterday" or "X days ago" where X is less than 7. As for "Last Played", there is a stronger case but not by much.

On that note, are you guys OK with "Installed At" represented by a week of the day and date only (e.g. Sunday, 14 June, 2020) and "Last Played" represented by a week of the day and minute resolution datetime (e.g. 05:00 PM Sunday, 14 June, 2020)?

**Comment by strycore** [comment]
The date information is now simplified. Marking this as fixed.
