### ISSUE TITLE
Lots of "which" error at startup

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#280]
Lutris tries to find what is available to it at startup and generates a lot of non-useful output to terminal when launching.

Example of what I get:
`
which: no primusrun in (/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/icecat:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no aterm in (/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/icecat:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no cool-retro-term in (/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/icecat:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no Eterm in (/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/icecat:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
`

There's about 15 more of those outputting.
Looking at the code for execute(), it shouldn't output to the terminal that way, but it still does.

**Comment by akien-mga** [comment]
Indeed, this output should be silenced, it's not relevant in this form to end users.

**Comment by strycore** [comment]
I've noticed that on distros other than Ubuntu, this will get a fix for next release

**Comment by akien-mga** [comment]
I've checked, and on Mageia the output of a failed ``which`` is sent to ``stderr``:
```
$ which primusrun 1>/dev/null
which: no primusrun in (/bin:/usr/bin:/usr/local/bin:/usr/local/games:/usr/games:/usr/lib64/qt4/bin:/usr/lib64/qt5/bin:/home/akien/bin)
$ which primusrun 2>/dev/null
```

**Comment by akien-mga** [comment]
``subprocess.Popen`` seems to display the stdout and stderr by default. [Based on this example](http://stackoverflow.com/questions/7082623/suppress-output-from-subprocess-popen), I could silence the warning this way:
```
subprocess.Popen(['which','primusrun'], stderr=open(os.devnull, 'w'))
```

**Comment by strycore** [comment]
@akien-mga great, I've implemented this solution it works fine!
