### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2800]
With the new RetroArch PR that went in I got this on the terminal, and Lutris won't start: https://paste.ubuntu.com/p/TqQzCvz56j/

**Comment by AlexanderRavenheart** [comment]
Can you provide more details? Can you attach the output of lutris -d?

**Comment by telanus** [comment]
Here is the info files. lutris -d gives what I posted nothing anything more

[info.zip](https://github.com/lutris/lutris/files/4534753/info.zip)

**Comment by byte1024** [comment]
Went from too many to not enough
https://github.com/lutris/lutris/issues/1737
https://github.com/lutris/lutris/commit/e0d183bea9946b18b0f4540bdf54ba099a52033e

Might want to take a different approach or keep going? Seems to be that there's some sort of variation happening.

**Comment by telanus** [comment]
> Went from too many to not enough
> #1737
> [e0d183b](https://github.com/lutris/lutris/commit/e0d183bea9946b18b0f4540bdf54ba099a52033e)
> 
> Might want to take a different approach or keep going? Seems to be that there's some sort of variation happening.

@byte1024 seems it's Dolpin's fault. It creates a .directory and the current implementation isn't suited for it. There is a PR that fixes it.
