### ISSUE TITLE
Library suddenly shows hundreds of games I do not own

### ISSUE THREAD

**Issue by wheelsofsteel** [lutris/lutris#2816]
**Describe the bug**

Hundreds of games have been imported into my library that I do not own or have on any account.

**Expected behavior**
Only my library of games from gog, steam or local.

**Current behavior**

Hundreds of games are listed. Maybe the entire library of lutris.net.

**Steps to reproduce**
Uncheck 'Show Installed Only', UI lags, hundreds of games appear.

**Lutris debugging output**
INFO     2020-04-30 12:03:00,036 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-04-30 12:03:00,036 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-04-30 12:03:00,036 [startup.check_driver:60]:GPU: Unknown
INFO     2020-04-30 12:03:00,036 [startup.check_driver:77]:GPU: 10DE:1E84 1458:3FFC using nvidia drivers
INFO     2020-04-30 12:03:00,036 [startup.check_driver:77]:GPU: 1002:67EF 1DA2:E348 using amdgpu drivers
INFO     2020-04-30 12:03:00,739 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-04-30 12:03:00,743 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-04-30 12:03:01,074 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-04-30 12:03:01,080 [gog.get_library:161]:Returning cached GOG library
DEBUG    2020-04-30 12:03:01,084 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-04-30 12:03:01,230 [store.get_missing_media:208]:Requesting missing icons from API for 1958 games
DEBUG    2020-04-30 12:03:01,230 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-04-30 12:03:01,475 [api.get_game_api_page:132]:Loaded 79 games from page 1
DEBUG    2020-04-30 12:03:03,160 [api.get_game_api_page:132]:Loaded 100 games from page 1
DEBUG    2020-04-30 12:03:03,161 [http.get:65]:GET https://lutris.net/api/games?page=2
DEBUG    2020-04-30 12:03:05,083 [api.get_game_api_page:132]:Loaded 100 games from page 2
DEBUG    2020-04-30 12:03:05,084 [http.get:65]:GET https://lutris.net/api/games?page=3
DEBUG    2020-04-30 12:03:06,925 [api.get_game_api_page:132]:Loaded 100 games from page 3
DEBUG    2020-04-30 12:03:06,925 [http.get:65]:GET https://lutris.net/api/games?page=4
DEBUG    2020-04-30 12:03:08,756 [api.get_game_api_page:132]:Loaded 100 games from page 4
DEBUG    2020-04-30 12:03:08,757 [http.get:65]:GET https://lutris.net/api/games?page=5
DEBUG    2020-04-30 12:03:10,628 [api.get_game_api_page:132]:Loaded 100 games from page 5
DEBUG    2020-04-30 12:03:10,628 [http.get:65]:GET https://lutris.net/api/games?page=6
DEBUG    2020-04-30 12:03:13,529 [api.get_game_api_page:132]:Loaded 100 games from page 6
DEBUG    2020-04-30 12:03:13,530 [http.get:65]:GET https://lutris.net/api/games?page=7
DEBUG    2020-04-30 12:03:15,414 [api.get_game_api_page:132]:Loaded 100 games from page 7
DEBUG    2020-04-30 12:03:15,414 [http.get:65]:GET https://lutris.net/api/games?page=8
DEBUG    2020-04-30 12:03:17,278 [api.get_game_api_page:132]:Loaded 100 games from page 8
DEBUG    2020-04-30 12:03:17,278 [http.get:65]:GET https://lutris.net/api/games?page=9
DEBUG    2020-04-30 12:03:19,218 [api.get_game_api_page:132]:Loaded 100 games from page 9
DEBUG    2020-04-30 12:03:19,218 [http.get:65]:GET https://lutris.net/api/games?page=10
DEBUG    2020-04-30 12:03:21,102 [api.get_game_api_page:132]:Loaded 100 games from page 10
DEBUG    2020-04-30 12:03:21,103 [http.get:65]:GET https://lutris.net/api/games?page=11
DEBUG    2020-04-30 12:03:23,320 [api.get_game_api_page:132]:Loaded 100 games from page 11
DEBUG    2020-04-30 12:03:23,321 [http.get:65]:GET https://lutris.net/api/games?page=12
DEBUG    2020-04-30 12:03:25,254 [api.get_game_api_page:132]:Loaded 100 games from page 12
DEBUG    2020-04-30 12:03:25,254 [http.get:65]:GET https://lutris.net/api/games?page=13
DEBUG    2020-04-30 12:03:27,705 [api.get_game_api_page:132]:Loaded 100 games from page 13
DEBUG    2020-04-30 12:03:27,705 [http.get:65]:GET https://lutris.net/api/games?page=14
DEBUG    2020-04-30 12:03:29,642 [api.get_game_api_page:132]:Loaded 100 games from page 14
DEBUG    2020-04-30 12:03:29,643 [http.get:65]:GET https://lutris.net/api/games?page=15
DEBUG    2020-04-30 12:03:31,564 [api.get_game_api_page:132]:Loaded 100 games from page 15
DEBUG    2020-04-30 12:03:31,564 [http.get:65]:GET https://lutris.net/api/games?page=16
DEBUG    2020-04-30 12:03:33,621 [api.get_game_api_page:132]:Loaded 100 games from page 16
DEBUG    2020-04-30 12:03:33,622 [http.get:65]:GET https://lutris.net/api/games?page=17
DEBUG    2020-04-30 12:03:35,657 [api.get_game_api_page:132]:Loaded 100 games from page 17
DEBUG    2020-04-30 12:03:35,658 [http.get:65]:GET https://lutris.net/api/games?page=18
DEBUG    2020-04-30 12:03:37,690 [api.get_game_api_page:132]:Loaded 100 games from page 18
DEBUG    2020-04-30 12:03:37,690 [http.get:65]:GET https://lutris.net/api/games?page=19
DEBUG    2020-04-30 12:03:39,618 [api.get_game_api_page:132]:Loaded 100 games from page 19
DEBUG    2020-04-30 12:03:39,619 [http.get:65]:GET https://lutris.net/api/games?page=20
DEBUG    2020-04-30 12:03:41,354 [api.get_game_api_page:132]:Loaded 56 games from page 20
DEBUG    2020-04-30 12:03:41,356 [http.get:65]:GET https://lutris.net/games/banner/angry-birds-rio.jpg
DEBUG    2020-04-30 12:03:41,356 [http.get:65]:GET https://lutris.net/games/banner/atari-anniversary-edition.jpg
DEBUG    2020-04-30 12:03:41,356 [http.get:65]:GET https://lutris.net/games/banner/atelier-ayesha-the-alchemist-of-dusk-dx.jpg
DEBUG    2020-04-30 12:03:41,356 [http.get:65]:GET https://lutris.net/games/banner/atelier-escha-logy-alchemists-of-the-dusk-sky-dx.jpg
DEBUG    2020-04-30 12:03:41,357 [http.get:65]:GET https://lutris.net/games/banner/atelier-shallie-alchemists-of-the-dusk-sea-dx.jpg
DEBUG    2020-04-30 12:03:41,365 [http.get:65]:GET https://lutris.net/games/banner/azur-lane-crosswave.jpg
DEBUG    2020-04-30 12:03:41,369 [http.get:65]:GET https://lutris.net/games/banner/bang-gunship-elite.jpg
DEBUG    2020-04-30 12:03:41,378 [http.get:65]:GET https://lutris.net/games/banner/bloons-monkey-city.jpg
DEBUG    2020-04-30 12:03:41,532 [http.get:65]:GET https://lutris.net/games/banner/builders-of-egypt-prologue.jpg
DEBUG    2020-04-30 12:03:41,532 [store.on_icon_loaded:351]:atari-anniversary-edition has no banner
DEBUG    2020-04-30 12:03:41,556 [store.on_icon_loaded:351]:atelier-shallie-alchemists-of-the-dusk-sea-dx has no banner
DEBUG    2020-04-30 12:03:41,556 [http.get:65]:GET https://lutris.net/games/banner/conflict-desert-storm-ii.jpg
DEBUG    2020-04-30 12:03:41,568 [http.get:65]:GET https://lutris.net/games/banner/conflict-global-storm.jpg
DEBUG    2020-04-30 12:03:41,569 [http.get:65]:GET https://lutris.net/games/banner/construct-2-personal.jpg
DEBUG    2020-04-30 12:03:41,569 [store.on_icon_loaded:351]:azur-lane-crosswave has no banner
DEBUG    2020-04-30 12:03:41,578 [store.on_icon_loaded:351]:angry-birds-rio has no banner
DEBUG    2020-04-30 12:03:41,579 [http.get:65]:GET https://lutris.net/games/banner/dark-fall-ghost-vigil.jpg
DEBUG    2020-04-30 12:03:41,579 [store.on_icon_loaded:351]:atelier-ayesha-the-alchemist-of-dusk-dx has no banner
DEBUG    2020-04-30 12:03:41,586 [http.get:65]:GET https://lutris.net/games/banner/death-track-prototype.jpg
DEBUG    2020-04-30 12:03:41,586 [store.on_icon_loaded:351]:bang-gunship-elite has no banner
DEBUG    2020-04-30 12:03:41,593 [http.get:65]:GET https://lutris.net/games/banner/drache-isolation.jpg
DEBUG    2020-04-30 12:03:41,593 [store.on_icon_loaded:351]:bloons-monkey-city has no banner
DEBUG    2020-04-30 12:03:41,600 [http.get:65]:GET https://lutris.net/games/banner/earthsiege-2.jpg
DEBUG    2020-04-30 12:03:41,600 [store.on_icon_loaded:351]:atelier-escha-logy-alchemists-of-the-dusk-sky-dx has no banner
DEBUG    2020-04-30 12:03:41,738 [http.get:65]:GET https://lutris.net/games/banner/edgar-torronteras-extreme-biker.jpg
DEBUG    2020-04-30 12:03:41,738 [store.on_icon_loaded:351]:builders-of-egypt-prologue has no banner
DEBUG    2020-04-30 12:03:41,759 [http.get:65]:GET https://lutris.net/games/banner/excessive-speed.jpg
DEBUG    2020-04-30 12:03:41,760 [http.get:65]:GET https://lutris.net/games/banner/evolution-gt.jpg
DEBUG    2020-04-30 12:03:41,760 [http.get:65]:GET https://lutris.net/games/banner/familiar-travels.jpg
DEBUG    2020-04-30 12:03:41,761 [store.on_icon_loaded:351]:death-track-prototype has no banner
DEBUG    2020-04-30 12:03:41,773 [store.on_icon_loaded:351]:dark-fall-ghost-vigil has no banner
DEBUG    2020-04-30 12:03:41,774 [http.get:65]:GET https://lutris.net/games/banner/farm-quest.jpg
DEBUG    2020-04-30 12:03:41,774 [store.on_icon_loaded:351]:conflict-desert-storm-ii has no banner
DEBUG    2020-04-30 12:03:41,775 [http.get:65]:GET https://lutris.net/games/banner/fifa-football-2005.jpg
DEBUG    2020-04-30 12:03:41,779 [http.get:65]:GET https://lutris.net/games/banner/flying-corps-gold.jpg
DEBUG    2020-04-30 12:03:41,780 [store.on_icon_loaded:351]:conflict-global-storm has no banner
DEBUG    2020-04-30 12:03:41,791 [store.on_icon_loaded:351]:earthsiege-2 has no banner
DEBUG    2020-04-30 12:03:41,791 [store.on_icon_loaded:351]:drache-isolation has no banner
DEBUG    2020-04-30 12:03:41,791 [store.on_icon_loaded:351]:construct-2-personal has no banner
DEBUG    2020-04-30 12:03:41,979 [store.on_icon_loaded:351]:excessive-speed has no banner
DEBUG    2020-04-30 12:03:41,991 [store.on_icon_loaded:351]:edgar-torronteras-extreme-biker has no banner
DEBUG    2020-04-30 12:03:41,991 [store.on_icon_loaded:351]:farm-quest has no banner
DEBUG    2020-04-30 12:03:41,997 [store.on_icon_loaded:351]:flying-corps-gold has no banner
DEBUG    2020-04-30 12:03:41,999 [store.on_icon_loaded:351]:evolution-gt has no banner
DEBUG    2020-04-30 12:03:42,006 [store.on_icon_loaded:351]:familiar-travels has no banner
DEBUG    2020-04-30 12:03:42,007 [store.on_icon_loaded:351]:fifa-football-2005 has no banner
DEBUG    2020-04-30 12:03:42,007 [http.get:65]:GET https://lutris.net/games/icon/atelier-escha-logy-alchemists-of-the-dusk-sky-dx.png
DEBUG    2020-04-30 12:03:42,008 [http.get:65]:GET https://lutris.net/games/icon/atelier-ayesha-the-alchemist-of-dusk-dx.png
DEBUG    2020-04-30 12:03:42,008 [http.get:65]:GET https://lutris.net/games/icon/atelier-shallie-alchemists-of-the-dusk-sea-dx.png
DEBUG    2020-04-30 12:03:42,012 [http.get:65]:GET https://lutris.net/games/icon/azur-lane-crosswave.png
DEBUG    2020-04-30 12:03:42,012 [http.get:65]:GET https://lutris.net/games/icon/bloons-monkey-city.png
DEBUG    2020-04-30 12:03:42,017 [http.get:65]:GET https://lutris.net/games/icon/familiar-travels.png
DEBUG    2020-04-30 12:03:42,025 [http.get:65]:GET https://lutris.net/games/icon/farm-quest.png
DEBUG    2020-04-30 12:03:42,232 [store.on_icon_loaded:351]:azur-lane-crosswave has no icon
DEBUG    2020-04-30 12:03:42,240 [store.on_icon_loaded:351]:atelier-shallie-alchemists-of-the-dusk-sea-dx has no icon
DEBUG    2020-04-30 12:03:42,260 [store.on_icon_loaded:351]:atelier-escha-logy-alchemists-of-the-dusk-sky-dx has no icon
DEBUG    2020-04-30 12:03:42,260 [store.on_icon_loaded:351]:familiar-travels has no icon
DEBUG    2020-04-30 12:03:42,264 [store.on_icon_loaded:351]:atelier-ayesha-the-alchemist-of-dusk-dx has no icon
DEBUG    2020-04-30 12:03:42,265 [store.on_icon_loaded:351]:farm-quest has no icon
DEBUG    2020-04-30 12:03:42,282 [store.on_icon_loaded:351]:bloons-monkey-city has no icon
gtk-update-icon-cache: Cache file created successfully.

**System information**

(Not using json for privacy reasons)

Arch Linux 5.6.6
KDE Plasma 5.18.4
Lutris 0.5.6-2
Attempted logged in and not.
![Screenshot_20200430_115744](https://user-images.githubusercontent.com/11930310/80703992-4f37a200-8ad3-11ea-8a00-76ec93d237a5.png)

**Comment by john-2000** [comment]
also affects me thanks

**Comment by strycore** [comment]
There was a glitch on the website that has caused this. I can provide directions to get rid of all uninstalled games (the games that are actually in the lutris library will come back)

**Comment by strycore** [comment]
To remove any uninstalled Lutris game run:

`sqlite3 ~/.local/share/lutris/pga.db "DELETE FROM games WHERE installed IS NOT 1;"`

**Comment by strycore** [comment]
Going to close this since the issue on the website has been solved

**Comment by john-2000** [comment]
The issue can stay closed 

for reference: if you want to take a deeper look at your library, open in sqlitebrowser and these fault entries all have the same installed time and you can delete them in the gui.
Just remember to write changes and then close the database.

**Comment by bphd** [comment]
> The issue can stay closed
> 
> for reference: if you want to take a deeper look at your library, open in sqlitebrowser and these fault entries all have the same installed time and you can delete them in the gui.
> Just remember to write changes and then close the database.

I can get a clean list of phantom games by sorting by "installed_at", it's not exactly the same time for all the phantom game but they still stick between them considering that it's between 1588158516 and 1588158596

**Comment by john-2000** [comment]
Yes sorry not exactly same time you are right

**Comment by smichel17** [comment]
Just in case anyone is still affected, here's a slightly more complete version (preserves playtime for games you've played before and then uninstalled):
```bash
sqlite3 ~/.local/share/lutris/pga.db "DELETE FROM games WHERE installed IS NOT 1 AND playtime IS NULL"
```
