### ISSUE TITLE
Feature request : default runner for a platform

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#2819]
I play nds games, and some games start with retroarch (but it doesn't work great for me) and some with desmume (that I replace by melonds, because it is faster and better for my use case)

So I think selecting a runner by default for a platform would be useful and easier for the end user because that will allow to install titles from the lutris db while keeping the same config for the same platform (mainly targeted to platforms that have multiple great emulators, e.g. nds or nintendo switch)

**Comment by strycore** [comment]
We kind of have that already but it's on the website only.
Would be nice to have something that is more platform oriented vs runner oriented.

**Comment by strycore** [comment]
We now have that thanks to the TOSEC integration. I added a bunch of platforms in default_installers.py, feel free to add more or contest my choice of default core / emulator
