### ISSUE TITLE
Python3's version is too great.

### ISSUE THREAD

**Issue by AussieEevee** [lutris/lutris#2820]
I am unable to install Lutris due to a dependency problem. Python3's version is too high.

I am using Ubuntu 20.04.

Aptitude gives me the following output when I try to install Lutris:

The following NEW packages will be installed:
  lib32gcc-s1{a} lib32gcc1{a} libc6-i386{a} libfaudio0{a} libstb0{a} libvkd3d1{a} libwine-development{a} lutris python3-evdev{a} python3-setproctitle{ab} 
0 packages upgraded, 10 newly installed, 0 to remove and 12 not to upgrade.
Need to get 73.7 MB of archives. After unpacking 492 MB will be used.
The following packages have unmet dependencies:
 python3-setproctitle : Depends: python3 (< 3.8) but 3.8.2-0ubuntu2 is installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     lutris [Not Installed]                             
2)     python3-setproctitle [Not Installed]               

Accept this solution? [Y/n/q/?] y
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 12 not to upgrade.
Need to get 0 B of archives. After unpacking 0 B will be used.

**Comment by byte1024** [comment]
Is this already fixed? https://github.com/lutris/lutris/commit/43afda0bf9b205c6a0cb20abca4f3583318d5600

I can't tell if its related or not but seems like they just have dealt with it. If you pull the git master version of Lutris, I'm thinking it will work (or wait for whatever way you're using to have it).

**Comment by strycore** [comment]
No one has problems running the current version version of lutris on 20.04 or Python 3.8.
Your problem is that you're using aptitude.

**Comment by AussieEevee** [comment]
> No one has problems running the current version version of lutris on 20.04 or Python 3.8.
> Your problem is that you're using aptitude.

I cannot install Lutris on any package management system on ubuntu 20.04.

**Comment by strycore** [comment]
Remove python3-setproctitle and you should be ok

**Comment by Makazy** [comment]
20.04 uses a bogus python3-setproctitle version with python 3.8 as seen here : http://copr.fedorainfracloud.org/coprs/g/python/python3.8/package/python-setproctitle/
https://packages.debian.org/fr/buster/python3-setproctitle

The package version of 20.10 fixes the issue :
http://archive.ubuntu.com/ubuntu/pool/main/p/python-setproctitle/python3-setproctitle_1.1.10-2_amd64.deb
(found here: https://pkgs.org/download/python3-setproctitle)
