### ISSUE TITLE
After the latest patch, WoW dies silently after clicking play in Battle.net launcher

### ISSUE THREAD

**Issue by skinofthesoul** [lutris/lutris#2821]
Hello everybody,

I hope this is the right place to post, if not please feel free to send me elsewhere!

I have been using Lutris to playWorld of Warcraft for some months now, and while I do get the very occasional #132 error followed by a game crash, I am super happy with it. Today I started the game and the Battle.net launcher updated to the latest patch (8.3.0.34220). I then clicked PLAY, the launcher closed and nothing happened. This happens every time I try. I have so far:

- rebooted my system,
- swapped the WoW cache,
- disabled DXVK,
- disabled the Lutris runtime,
- enabled VKD3D.

None of that made any difference. I also tried switching the wine version from lutris-4.16-x86_64 to my system's Ubuntu 4.0.2-1 (with esync disabled). This resulted in the game's window frame appearing with no content, and then a crash.

I really don't know how to find out where the problem is, but since the game is running as expected on a nearby Windows computer, it must be somewhere in the Linux department.

I have started lutris with the debug option, and while I get a LOT of output including a few errors, my guess is that I've had these before since the Battle.net launcher works as expected. However, here's the output after I click on play:

```
[0430/180005.913:ERROR:mf_audio_decoder.cc(713)] Unsupported codec by MfAudioDecoder: 4
[0430/180005.923:ERROR:mf_video_decoder.cc(747)] Unsupported codec by MfVideoDecoder: 6
*** stack smashing detected ***: <unknown> terminated
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
[0430/180011.509:ERROR:browser_process_sub_thread.cc(221)] Waited 9 ms for network service
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 0
DEBUG    2020-04-30 18:00:11,942 [command.on_stop:182]:The process has terminated with code 0
DEBUG    2020-04-30 18:00:11,957 [command.stop:266]:Management process looks dead already.
DEBUG    2020-04-30 18:00:11,957 [command.stop:274]:Detaching logger
DEBUG    2020-04-30 18:00:13,266 [game.beat:596]:Game thread stopped
WARNING  2020-04-30 18:00:13,267 [game.on_game_quit:626]:Game still running (state: running)
INFO     2020-04-30 18:00:13,267 [game.stop:611]:Stopping World of Warcraft (wine)
DEBUG    2020-04-30 18:00:13,267 [command.stop:266]:Management process looks dead already.
DEBUG    2020-04-30 18:00:13,267 [command.stop:278]:logger already detached
DEBUG    2020-04-30 18:00:13,276 [game.on_game_quit:645]:World of Warcraft stopped at Do, 30 Apr 2020 18:00:13
DEBUG    2020-04-30 18:00:13,277 [game.save:249]:Saving World of Warcraft (wine)
DEBUG    2020-04-30 18:00:13,353 [lutriswindow.on_game_updated:779]:Updating game World of Warcraft (wine)
```

The errors on the first two lines show up twice before that. The stack smashing seems to me the most interesting bit. I don't know what to make of it though.

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/4559535/lutris-issue-report.json.zip)

Thank you for making lutris!!

**Comment by skinofthesoul** [comment]
I only just came across [this forum thread](https://forums.lutris.net/t/world-of-warcraft-not-starting/9069/9) – using wine 5.7 fixed the issue for me! Thank you also for making using a different wine version so easy!!

**Comment by byte1024** [comment]
Point out for the future, the problem with Wine is that _any_ game updates could cause something to break. In this case, it broke on older versions and you at least have a newer version that can work.

Also, Lutris is native Linux application so once you start the game's launcher, that will be a Wine problem when using Wine. Lutris should have no responsibility from there.

Of note too, the mf_ issues, Wine is still being worked on for Media Foundation which videos that are used in games that use Microsoft stuff to play them. They've always been broken and are now being worked on. Generally, those can be ignored unless they crash a game. Normally, it will just be a black screen when they play.

Have fun :-)
