### ISSUE TITLE
Feature request: Add functionalties to set private tags & notes for games

### ISSUE THREAD

**Issue by gsantner** [lutris/lutris#2824]
**Description**

Currently the client's only way to find the game I want to play right now is, to know it's name or to find it by random in my huge game library.

It would be very helpful and handsome if I could:
* set a note to each game (like what I like on this game, setup/backup/restore notes, ...) 
* set custom & searchable tags to each game so I can categorize stuff however I like it
* synchronize these private & personal "game notes" via Lutris services (or i.e. alternatively a file I can check into git repo, or otherwise sync on my own)

Please note the difference to the "public game tags" and "public website comments": This is about ordering my own personal game library. I don't expect any of these information to be public.

Especially with the raise of supported game services like Steam, itch (#2746), HumbleBundle (#334), GOG (#154) the library keeps growing with especially free indie games and it's sometimes hard..do I know this game? what is it about? have I played it at least once? does it work on my PC even? Thats everything I could add with this feature as my personal notes & searchable tags.

**Comment by Sneethe** [comment]
This would a very welcome addition. Steam has actually added a note taking functionality and it is very useful.

**Comment by gsantner** [comment]
Didn't get attention over 3 years so guess won't get implemented. Closing.

**Comment by danieljohnson2** [comment]
Well, these things get lost in the mists of time. But Lutris has a user-defined categories feature now, which seems similar to what you want (albeit without the notes part)

**Comment by Victor239** [comment]
This is incomplete as notes aren't implemented. It would be very useful to have a feature for this like Steam already has.
