### ISSUE TITLE
Lutris does't start on Kali Linux ( debian ) - Failed to execute command "lutris %U"

### ISSUE THREAD

**Issue by TheSpriTeLegeNd** [lutris/lutris#2831]
After doing everything that says on the site ( adding the repository) and installing lutris ( apt-get install lutris ) i try to launch it and does't start, showing me this error: Failed to execute command "lutris %U".

Failed to execute child process "lutris" (No such file or directory). 

I tried adding a directory path from some file that i found with the name lutris but the error keeps showing up. If i try to open it from terminal it says ,,command not found".
The only folder that i was able to find was on /usr/share/lutris/media and has nothing to give me a clue how to start the program from the ,,exe". 

What to do? I can't find a solution on internet and it does't seem that anyone has one like mine. 
![Screenshot 2020-05-03 17:38:51](https://user-images.githubusercontent.com/25528089/80917307-94bfcd80-8d66-11ea-8f64-05aaa34b023e.png)
![Screenshot 2020-05-03 17:39:21](https://user-images.githubusercontent.com/25528089/80917318-b02ad880-8d66-11ea-985d-828948a70e0c.png)

**Comment by TheBrainScrambler** [comment]
Hello, did you try to uninstall and reinstall Lutris ?
Else, according to https://lutris.net/downloads/ you should download lutris from their repositories.
I don't know if Kali Linux supports PPA, but if so try :
```
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
sudo apt-get install lutris
```
Else, check their website

**Comment by strycore** [comment]
Kali is not a distribution we support and we would generally suggest that you play games on another OS.
Alternatively, if you do insist on playing video games on Kali, your Linux skill set should be good enough to let you solve that issue by yourself.

**Comment by edy2310** [comment]
> Kali is not a distribution we support and we would generally suggest that you play games on another OS.
> Alternatively, if you do insist on playing video games on Kali, your Linux skill set should be good enough to let you solve that issue by yourself.

Turn down for what!

**Comment by Loubaris** [comment]
wow lutris staff is like this ?

**Comment by strycore** [comment]
No. I am like this. The rest of the team has their own views.
And I don't understand what the issue is. Kali is a pentesting tool. You want to do gaming on a pentesting tool? Great. But we have more important issues to deal with so you're on your own.

We support Linux distributions that we judge fit for gaming. Kali isn't one of them. (Neither is stuff like Void or Alpine btw)

**Comment by MohammadTeeU** [comment]
Go folder `/usr/games/` then run the file lutris `$ python3 lutris`

**Comment by andriyyatsykiv** [comment]
> Go folder `/usr/games/` then run the file lutris `$ python3 lutris`

This worked perfectly for another edge-case, thanks!

I'm using a webtop to run lutris from a server for better ease-of-use.
