### ISSUE TITLE
[Icons] Mixed naming schemes for platform icons

### ISSUE THREAD

**Issue by AlexanderRavenheart** [lutris/lutris#2832]
There are currently 3 types of platform names defined in Lutris runners:
- Manufacturer + Abbreviated system name (Ex: Nintendo NES, Nintendo SNES)
- Manufacturer + System name (Ex: Nintendo GameCube, Sony PlayStation, Nintendo Game Boy Advance)
- System  name (Ex: Nintendo Entertainment System, GameCube, Wii, Game Boy, Game Boy Color)

Some runners use only one of the first two types while others (Ex: mednafen) use both.
The third type is used by Libetro cores. 

We should decide and conform to just one of the three types of platform names.
Personally I vote for using only the full system/platform name (third type) as the icons are platform specific and should not contain manufacturer information in their naming.

**Comment by AlexanderRavenheart** [comment]
@matoro Opened this issue to continue the discussion that was opened in the PR.

**Comment by matoro** [comment]
@AlexanderRavenheart I am sure this is going to need some review from you all.  But hopefully https://github.com/lutris/lutris/pull/2990 is a good starting point for making the naming scheme more flexible and getting the platform name -> icon mapping right.  What do you think?

**Comment by AlexanderRavenheart** [comment]
@matoro Hey, I just checked out the PR you linked and I think adding options is the wrong way to go. We need a standard, to align all runners to it and reduce the maintainability effort when cores are added/updated and not keep lists upon lists of hard coded names in the code.

Can you explain which of the 3 variants mentioned in the description of this issue did you make your PR to support as default?

**Comment by lukasfink1** [comment]
The problem with the libretro runner is that it extracts the platform name from the chosen libretro core.
To me it seems as though the only complete fix would be to add an option to manually specify the platform.
It could of course try to translate the libretro platform names to the names we choose. The problem with this approach is that some cores support multiple platforms (e.g. mesen-s supports SNES, GB, GBC).

**Comment by strycore** [comment]
To avoid licensing issues for the inclusion of Lutris in Debian, I've removed all icons from the project and moved them to an icon pack that gets downloaded with the lutris runtime.
It makes little sense to distribute icons in a .tar.xz like I'm doing. It would be much more flexible to have icons provided through our REST API. This would allow us much more flexibility in platform naming. We can easily make aliases like we do for games.

**Comment by matoro** [comment]
@lukasfink1 That is on purpose, from a change that @AlexanderRavenheart added.  I do actually agree that manually specifying the platform is actually probably the cleaner solution, but there's a lot of code right now that assumes you can always derive the platform name from the runner.  Before I tried that approach I would want to get @strycore 's blessing.  It would of course default to using the platform name the runner provides.

**Comment by strycore** [comment]
Any naming convention should be done from the Lutris REST API.
