### ISSUE TITLE
Lutris crashes at start up on Xubuntu 16.04

### ISSUE THREAD

**Issue by hansimann11** [lutris/lutris#2833]
Hello,
Have been using Lutris for several months, now I get the following error when I launch Lutris:

> lutris -d
> INFO     2020-05-03 21:15:24,515 [application.do_command_line:245]:Running Lutris 0.5.6
> INFO     2020-05-03 21:15:24,515 [__init__.migrate:29]:Running migration: fix_playtime
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in do_command_line
>     migrate()
>   File "/usr/lib/python3/dist-packages/lutris/migrations/__init__.py", line 31, in migrate
>     migration.migrate()
>   File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 23, in migrate
>     fix_playtime(game)
>   File "/usr/lib/python3/dist-packages/lutris/migrations/fix_playtime.py", line 9, in fix_playtime
>     if not broken_playtime.endswith(" hrs"):
> AttributeError: 'float' object has no attribute 'endswith'
> INFO     2020-05-03 21:15:24,566 [application.do_shutdown:491]:Shutting down Lutris
>

**Comment by rlaPHOENiX** [comment]
Same thing over here on arch linux.

**Comment by enboig** [comment]
Same on 20.04
