### ISSUE TITLE
Lutris won't start

### ISSUE THREAD

**Issue by googlefan2** [lutris/lutris#2838]
**I tried to open Lutris, after downloading it using the instructions from the website**

**Expected behavior**

I was hoping for it to open.

**Current behavior**

It will not open. 

**Lutris debugging output**
When I went to check it out in the terminal, this was the result:
Traceback (most recent call last):
  File "/usr/games/lutris", line 40, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 35, in <module>
    from lutris.game import Game
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 11, in <module>
    from lutris.runners.runner import Runner
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 7, in <module>
    from lutris.config import LutrisConfig
  File "/usr/lib/python3/dist-packages/lutris/config.py", line 6, in <module>
    from lutris import settings, sysoptions
  File "/usr/lib/python3/dist-packages/lutris/sysoptions.py", line 9, in <module>
    from lutris.util.display import USE_DRI_PRIME, DISPLAY_MANAGER
  File "/usr/lib/python3/dist-packages/lutris/util/display.py", line 4, in <module>
    from dbus.exceptions import DBusException
ModuleNotFoundError: No module named 'dbus'`.

**Comment by Steinhagen** [comment]
You don't have python-dbus installed on your system. Also, make sure that you have the version for Python 3 installed.

**Comment by AlexanderRavenheart** [comment]
Installing Lutris on any supported distribution should not require the user installing any additional packages, the dependencies should be handled automatically using the distribution's package manager.

If it is not doing that then the package dependencies need to be updated. The maintainer of the package for the corresponding distribution needs to be notified.

**Comment by strycore** [comment]
If python3-dbus wasn't a dependency in one of the distros we support, we would know.

**Comment by YourFriendCaspian** [comment]
I'm running Debian 10 with python3-dbus installed and I'm having the same issue. I'm also getting this error - 
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Any help would be greatly appreciated.

**Comment by byte1024** [comment]
> I'm running Debian 10 with python3-dbus installed and I'm having the same issue. I'm also getting this error -
> ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> Any help would be greatly appreciated.

If you're getting "ModuleNotFoundError: No module named 'dbus'`." then it could be that dbus isn't installed correctly (apparently that's a thing).

see: https://nixx.co/no-module-named-dbus/

I'm not sure these are really Lutris issues. It really can't fix every single problem known to man on install.

**Comment by googlefan2** [comment]
thanks a lot, all!
