### ISSUE TITLE
On startup: Failed to create secure directory (/run/user/1001/pulse)

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#284]
A Mageia QA tester gets the following error messages in the terminal output when starting lutris 0.3.7.2 and 0.3.7.5:
```
Failed to create secure directory (/run/user/1001/pulse): Permission denied
```
See https://bugs.mageia.org/show_bug.cgi?id=18410#c3

I haven't tried yet to reproduce it myself, but will do asap.

**Comment by strycore** [comment]
This is weird, there is no direct call to pulseaudio unless the reset_pulse system option is active and that would happen before a game is launched.
Would it be possible to pinpoint more precisely what part of the program causes this?

**Comment by akien-mga** [comment]
The user who reported the issue could not reproduce it anymore on a second try :/
I'll see if I can reproduce it with a new user account.

**Comment by strycore** [comment]
I'll consider that this issue wasn't related to the Lutris client.
