### ISSUE TITLE
[Issue] Startup Segfault

### ISSUE THREAD

**Issue by Devorlon** [lutris/lutris#2841]
Hi,

When I try to start Lutris I get a segmentation fault. Running 

`gdb --args /usr/bin/python /usr/bin/lutris, r, bt` And `lutris -d`

I get https://pastebin.com/eKsWtYh8 & https://pastebin.com/CxpKuvZZ

My best guess is that after the segfault python is trying to allocate a nonexistent thread which is why you can see it try to switch to thread 0x7fffe8ce5700. Though I'm not that good at programming and that might just be a address to something.

I'm using arch with a custom Tk-Glitch kernel and a R5 3600

Thanks

**Comment by byte1024** [comment]
It still fails without mangohud?

I don't like the fact that it shows up just before the crash there.

**Comment by Devorlon** [comment]
Ye, Mangohud was the problem. 

More specifically Goverlay, a companion app which enabled it globally in my $HOME/.profile. Removeing the var and rebooting worked.

Thanks for the help
