### ISSUE TITLE
Mangohud causes Lutris to segfault on start

### ISSUE THREAD

**Issue by Simmonz** [lutris/lutris#2844]
When I try to launch Lutris it doesn't start. I have tried by clicking the icon and by running through terminal.

**Expected behavior**

To launch Lutris

**Current behavior**

Unable to launch Lutris

**Steps to reproduce**

-  Try to run Lutris

**Lutris debugging output**

"INFO     2020-05-06 11:29:01,067 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-05-06 11:29:01,067 [startup.check_driver:62]:Using X.Org
INFO     2020-05-06 11:29:01,067 [startup.check_driver:64]:Running Mesa driver 20.0.6 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.8-1-MANJARO, LLVM 10.0.0) (0x731f)
INFO     2020-05-06 11:29:01,068 [startup.check_driver:77]:GPU: 1002:731F 1462:3816 using amdgpu drivers
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/matthew/.config/MangoHud/python3.8.conf [ not found ]
parsing config: /home/matthew/.config/MangoHud/MangoHud.conf [ ok ]
INFO     2020-05-06 11:29:01,100 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-05-06 11:29:01,100 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
Segmentation fault (core dumped)"

**System information**

AMD Ryzen 5 2600X | 16GB DDR4-3000 CL15 | MSI RX 5700 XT 8GB Gaming X | Mesa 20.0.6 | Manjaro 20.0 | Mate 1.24 | Kernel 5.6.8-1-MANJARO | Lutris 0.5.6

**Comment by byte1024** [comment]
And another one lol.

Can you try it without mangohud? Does it still crash without that?

**Comment by richardtatum** [comment]
I too can reproduce this issue with MangoHud installed:

```
2020-05-06 17:14:06,099: Running Lutris 0.5.6
2020-05-06 17:14:06,099: Using X.Org
2020-05-06 17:14:06,099: Running Mesa driver 20.0.6 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.10-zen1-1-zen, LLVM 10.0.0) (0x731f)
2020-05-06 17:14:06,099: GPU: 1002:731F 1002:0B36 using amdgpu drivers
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/rt/.config/MangoHud/python3.8.conf [ not found ]
parsing config: /home/rt/.config/MangoHud/MangoHud.conf [ ok ]
2020-05-06 17:14:06,151: Vulkan is supported
2020-05-06 17:14:06,155: Providing missing platform for game astroneer
fish: “lutris --submit-issue” terminated by signal SIGSEGV (Address boundary error)
```

Removing MangoHUD allows me to once again open Lutris.

**Comment by strycore** [comment]
what the fuck is going on with mangohud?

**Comment by Generator** [comment]
Lutris shouldn't be launch with MangoHud (`$ mangohud lutris`), instead should be added to 'Environment variables'
```
MANGOHUD=1 # Vulkan games
LD_PRELOAD=/usr/lib/libMangoHud.so # OpenGL games
```

Using it for some time, no issues with Lutris

**Comment by Simmonz** [comment]
Yeah it was ManghoHUD for me as well. Closing.

**Comment by strycore** [comment]
While launching Lutris with Mangohud instead of running Mangohud through Lutris doesn't make a lot of sense, I still manage to do that on my setup without any crashes.
