### ISSUE TITLE
Dosbox runner 

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#2847]
THe current runner no longer works for me

The commit where it "broke" for me is https://github.com/lutris/lutris/commit/31d851bd159f121d7168362d9ac5ea5565418423#diff-49c07d72e26bf5e09a6aa0c2e6510abe If I go back to https://github.com/lutris/lutris/commit/bf2bcdf398b04320b7eda34f328b1c75778f5a02#diff-49c07d72e26bf5e09a6aa0c2e6510abe it works. 

What happens:
When I run a dos game via lutris (with the current runner) it'll show in the gui that it's launching the game, and freeze, while printing :
```

DEBUG    2020-05-07 14:05:08,592 [application.launch:409]:Launching Bio Menace (dosbox)
DEBUG    2020-05-07 14:05:08,610 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
```

on the terminal, before freezing. Nothing else gets printed

I'm on Kubuntu 18.04.2 with Python 2.7.17 & Python 3.6.9

**Comment by AlexanderRavenheart** [comment]
The commit you're pointing to is a merge from master to a dev branch and is not the cause of the issue. You might wanna check out the commits that were brought in with that dev branch: #2763.

**Comment by telanus** [comment]
> You might wanna check out the commits that were brought in with that dev branch: #2763. That PR changed the way args are handled for the Dosbox runner.

With this applied to the working runner, it won't launch dosbox on my system. Wonder since it now relies on shlex if that's the problem for me, without shlex it works. So ye reverting that makes it work for me
