### ISSUE TITLE
Games crash with newer versions of Wine unless running Lutris from the terminal.

### ISSUE THREAD

**Issue by azsorlex** [lutris/lutris#2849]
**Describe the bug**

I found a problem that doesn't allow me to run games via the Wargaming Game Center while using newer versions of wine unless I launch Lutris from the terminal. I would usually start Lutris using the application menu shortcut, which is when I would experience the issue. When using new versions of wine (such as Proton 5.0, lutris-5.7, and even my system's wine (5.0)), I'll be able to open the Wargaming Game Center, but World of Tanks/Warships would crash very shortly after I try to run either one of them. This problem disappears when launching Lutris from the terminal, either by running **lutris -d** or **lutris**. I'm using Pop!_OS 20.04. I've briefly experienced the not starting up issue on Manjaro, however, I haven't tested if running Lutris from the terminal fixes it there or not.

**Expected behavior**

World of Tanks/Warships should run with most (if not all) versions of wine when launching Lutris from the application menu shortcut.

**Current behavior**

World of Tanks/Warships does not run with most versions of wine when launching Lutris from the application menu shortcut.

**Steps to reproduce**

_When launching Lutris from the application menu shortcut. Using Proton 5.0_
- Start Wargaming Game Center (success)
- Attempt to start either World of Tanks or World of Warships (failure)

_When launching Lutris from the terminal. Using Proton 5.0_
- Start Wargaming Game Center (success)
- Start World of Tanks and play a game (success)
- Start World of Warships and play a game (success)

**Lutris debugging output**

Starting the launcher, successfully loading World of Tanks, and gracefully quitting it with Proton 4.11: https://paste.ubuntu.com/p/YjQHsMX5wf/

ditto but with Proton 5.0: https://paste.ubuntu.com/p/bHWCq7v2X7/

ditto but with lutris-5.7: https://paste.ubuntu.com/p/Bb7Zxb2VtR/

ditto but with my system-installed wine stable (5.0): https://paste.ubuntu.com/p/kMHrtWkNcd/

**System information**

[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/4596178/lutris-issue-report.json.txt)

**Screenshots**

Launched Lutris via the application menu shortcut, trying to run World of Warships using lutris-5.7:
![Screenshot from 2020-05-08 09-06-51](https://user-images.githubusercontent.com/8101141/81353314-0e134380-910c-11ea-8455-e898ed50a67c.png)

Launched Lutris via the terminal, trying to run World of Warships using lutris-5.7:
![Screenshot from 2020-05-08 09-11-47](https://user-images.githubusercontent.com/8101141/81353324-10759d80-910c-11ea-9843-31d240f627b6.png)

**Comment by aorozsa** [comment]
Another thing. In the Lutris application menu shortcut's file, I changed the "Terminal" value to true and that allowed me to run the games after launching Lutris from the application menu shortcut. But then again, that isn't the prettiest fix.

**Comment by aorozsa** [comment]
I can also confirm that running Lutris from the terminal fixes it on Manjaro.

**Comment by aorozsa** [comment]
The issue (and fix) also applies to running game shortcuts from the application menu.

**Comment by tannisroot** [comment]
All your paste links are dead. 
Can you please try it with a fresh prefix made with our lutris-5.7-8 build? Also please don't use Valve's Proton, it breaks wine prefixes.

**Comment by aorozsa** [comment]
@tannisroot Do I have to reinstall the game to get a fresh prefix?

**Comment by tannisroot** [comment]
Yes but I believe most game launchers support locating existing game files so that the user could avoid redownloading them.

**Comment by aorozsa** [comment]
Ok, I went ahead and installed a different instance of the game anyway, and the result is the same.

The differences between last time, however, are of course lutris-5.7-8, Lutris 0.5.7.1, I'm now using EndeavourOS, and I collected a log that I should've thought of when I initially posted this. Below is the output of `lutris %U -d > /home/alex/shortcut_execution.txt` which I added to the application menu's shortcut. This way I was able to collect the log of World of Tanks attempting to launch and failing shortly afterwards. I also added the terminal execution (which has WoT launch successfully) for comparison `(lutris -d > /home/alex/terminal_execution.txt)`.

[Shortcut execution](https://paste.ubuntu.com/p/hhQdHkbdnV/)
[Terminal execution](https://paste.ubuntu.com/p/Tr6GrBkDwh/)

**Comment by legluondunet** [comment]
I can reproduce this issue on Arch distribution.

**Comment by legluondunet** [comment]
@strycore the bug is resolved in game script, I saw with azorlex, you can close this issue now

**Comment by legluondunet** [comment]
how to resolve this issue: 
```
  overrides:
    ucrtbase: b,n
```
