### ISSUE TITLE
"[system]:Executing which steam" every 10 seconds

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#285]
I don't know if it's a bug, but I'll let you decide.

When running lutris 0.3.7.5 with the ``--debug`` switch, I guess a message about "executing which steam" every 10 seconds:
```
DEBUG    2016-05-12 07:56:32,891 [system]:Executing which steam
DEBUG    2016-05-12 07:56:42,892 [system]:Executing which steam
DEBUG    2016-05-12 07:56:52,892 [system]:Executing which steam
DEBUG    2016-05-12 07:57:02,893 [system]:Executing which steam
```

**Comment by strycore** [comment]
Yep, it's a bug (https://github.com/lutris/lutris/issues/212) or more precisely, the current implementation should be changed to a inotify watcher (it is doing what it's supposed to after all)

Closing this issue so we can focus on the first report.
