### ISSUE TITLE
Importing games from the Dolphin emulator

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#2854]
**Describe the bug**

After adding the dolphin launcher and specifying the default installation folder of its games no games are loaded into Lutris. The games are all loaded in Dolphin when running Dolphin.

**Expected behavior**

After adding the default installation folder all games of the Dolphin emulator should show in Lutris. Alternatively there could be an entry for the Dolphin emulator under Import games. It would be nice if this feature could be added.

**Current behavior**

Games need to be added manually via + in upper left -> Add Game...

**System information**

Debian 10/KDE
Lutris 0.5.6

**Comment by strycore** [comment]
WHAT THE FUCK @#$%@%^*()$@%^()@#$(%_!@#(%_

https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/UICommon/GameFile.cpp

WHO understands ANY of this BS?!?!!??!

**Comment by strycore** [comment]
I can read hex better than I can read C++ so it's OK now.

**Comment by strycore** [comment]
Closed in 0.5.9
