### ISSUE TITLE
Ensuring integrity of the downloaded launchers

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#2855]
**Describe the bug**

Does Lutris check for integrity of the downloaded launchers? Does it compare checksums before installation? And how is it ensured that the files it downloads match the actual builds / source code? This is similar to the issue I recently created for flatpak/flathub here: https://github.com/flathub/flathub/issues/1498 - more relevant information can be found there.

Downloading and installing unverified packages from unverified sources constitutes a substantial security risk. If Lutris doesn't yet have a comprehensive mechanism for ensuring integrity of the installers built in, it should probably be added - either directly or by adding some third-party software for these checks.

**Expected behavior**

Lutris checking checksums of launchers after download and a mechanism that ensures that the files provided are genuine and secure to launch.

**Current behavior**

Currently it's unclear whether there are such mechanisms built in and if so which.

**Comment by Medath** [comment]
related: #1218
I would also love some kind of validity check, optimally all runners and the runtime would be signed with a public key that only trusted team members have access to. This could even allow safely hosting mirrors that the lutris client can use to reduce hosting costs for Lutris

**Comment by xordspar0** [comment]
This isn't just related to the linked issue, it's a duplicate, isn't it? We should continue discussing this at #1218 rather than here.

**Comment by mYnDstrEAm** [comment]
> This isn't just related to the linked issue, it's a duplicate, isn't it? We should continue discussing this at #1218 rather than here.

Sorry, didn't know about that issue. It's mostly a duplicate: that other issue is only concerned with the checksums of the launchers but not with ensuring that the checksummed files are genuine and secure to launch.
This issue could be edited so that it's only about the latter, or the other issue could be edited so that it also addresses making sure that the files are secure to launch or the other issue could be made a subissue/task of this issue. I'd say discussing it there would probably be fine because a good mechanism to checksum and verify checksums of files would be the main part of this and once this works reliably some users could simply compare the checksums to downloaded files from the official websites and put them up for others to compare. For making sure that they are secure to launch the people selecting which runner is made available within Lutris could choose only stable versions so that the security/stability depends on the package-devs. There could also be inbuilt sandboxing by default like firejail and other security/stability features like AppArmor. That would be another (sub)issue(s).

**Comment by tannisroot** [comment]
Closing as a duplicate
