### ISSUE TITLE
Resolution Reseting - "Switch resolution to" and "Run in a terminal"

### ISSUE THREAD

**Issue by Anigai** [lutris/lutris#2857]
Manjaro XFCE
Lutris 0.5.4

When running a game in Fullscreen using the "Switch resolution to" and "Run in a terminal" options under System options the resolution will switch to the specified resolution for a few seconds before switching back to the desktop resolution.

The issue does not occur when deselecting the "Run in a terminal" option which is how I get around the issue.

I would use spoiler bbcode for the below inxi if I could figure out how to get it to work.

[sean@NEWDESTINY ~]$ inxi -Fxzc0
System:    Host: NEWDESTINY Kernel: 5.4.22-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.1 Desktop: Xfce 4.14.2 
           Distro: Manjaro Linux 
Machine:   Type: Desktop System: MSI product: MS-7850 v: 1.0 serial: <filter> 
           Mobo: MSI model: Z97 PC Mate(MS-7850) v: 1.0 serial: <filter> UEFI [Legacy]: American Megatrends v: 4.11 
           date: 02/16/2016 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master charge: 55% (should be ignored) 
           status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i7-4790K bits: 64 type: MT MCP arch: Haswell rev: 3 L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 64026 
           Speed: 943 MHz min/max: 800/4400 MHz Core speeds (MHz): 1: 1965 2: 1421 3: 2158 4: 1630 5: 1998 6: 2126 7: 1782 
           8: 1883 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 430.64 bus ID: 01:00.0 
           Display: x11 server: X.org 1.20.7 driver: nvidia resolution: <xdpyinfo missing> 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 430.64 direct render: Yes 
Audio:     Device-1: Intel 9 Series Family HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Device-3: Kingston HyperX 7.1 Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 2-3:3 
           Sound Server: ALSA v: k5.4.22-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI driver: r8168 
           v: 8.048.00-NAPI port: d000 bus ID: 02:00.0 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad bus ID: 2-2:2 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 4.88 TiB used: 1.10 TiB (22.4%) 
           ID-1: /dev/sda vendor: SanDisk model: SDSSDA120G size: 111.79 GiB 
           ID-2: /dev/sdb vendor: Seagate model: ST1000DX001-1CM162 size: 931.51 GiB 
           ID-3: /dev/sdc vendor: Samsung model: SSD 850 EVO 250GB size: 232.89 GiB 
           ID-4: /dev/sdd vendor: Seagate model: ST2000DX002-2DV164 size: 1.82 TiB 
           ID-5: /dev/sde vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB 
           ID-6: /dev/sdg type: USB vendor: Western Digital model: WD10EURX-63FH1Y0 size: 931.48 GiB 
Partition: ID-1: / size: 109.53 GiB used: 74.07 GiB (67.6%) fs: ext4 dev: /dev/sda1 
           ID-2: swap-1 size: 16.00 GiB used: 768 KiB (0.0%) fs: swap dev: /dev/sde3 
Sensors:   System Temperatures: cpu: 32.0 C mobo: N/A gpu: nvidia temp: 51 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Info:      Processes: 236 Uptime: 2h 21m Memory: 15.59 GiB used: 2.13 GiB (13.6%) Init: systemd Compilers: gcc: 9.2.1 
           clang: 9.0.1 Shell: bash v: 5.0.16 inxi: 3.0.37

**Comment by xordspar0** [comment]
This isn't phpBB, so there are no bbcodes. :slightly_smiling_face: It's possible to use HTML to make collapsible sections, but it's not necessary. Just marking log output as code by surrounding it with ``` above and below is fine.

Could you run lutris in the command line with `lutris -d` and reproduce the issue again, then post the output here?

**Comment by strycore** [comment]
You shouldn't change the resolution if you play terminal games. It doesn't make a lot of sense.
