### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#286]
Just a suggestion or two.

1) a checkbox that if checked it would minimize lutris. Found that a few games have weird lagging issues with lutris open, which dissapears when I minimize Lutris, by either minimizing before the game starts displaying, or alttabbing out.

2) add more existing options to existing emus

3a) Use existing emus(?) for more of their supporting systems (IE MESS)
3b) split existing runners (of those supporting multiple system into different runners) (IE MESS that support multiple systems, the most used systems could each get a runner) (thus if one part of the input system changes for a particular system, the whole runner for the emu doesn't need to be rewritten only the system that changed)

4) changing of plugins in runners that support that feature

**Comment by strycore** [comment]
1) There is absolutely *no way* we are adding such an option. If games are lagging because of Lutris, we have to found out why and fix the root cause ASAP. I'm afraid I won't be able to reproduce with a 4.4GHz i7 CPU so if someone does, file a bug report about it.

2) What options to what emu? File an issue for specific options and we will add them.

3a) It's possible to manually specify the system used with MESS but we have to find a better way of handling an emulator that runs 1000 different systems.
3b) I don't understand and I don't agree with the little I understand

4) Maybe, but I'd be in favor of getting rid of as much emulators that use plugins as possible because they are a horrible idea (ie. PCSX)

**Comment by Xodetaetl** [comment]
Strycore was a bit harsh in his reply (too much coffee? :^), so here's a more moderated (and late) one: 

1) Let's try to fix the issue first before thinking of implementing a workaround. If you can provide more information (What games are concerned? What are your system specs?), please do so in a separate issue entry.

2) We will add more runner options along the way of course, but if you need some *now*, let us know (in a separate entry) and it will get prioritized.

3) I haven't messed enough with Mess so I don't have answers, but I have questions, for @strycore: a thousand platforms on a single runner seems bound to be problematic as you say, so why not have, like Telanus suggests, separate runners for, for example, families of emulators that can consistently share a set of runner options and code?

4) @strycore: can you expand on plugins being a horrible idea?

Anyway, are these suggestions all relevant if we are to switch to libretro for emulators?

PS @telanus : I've been moderating your game submissions lately and I like your work on banners but some of them are cropped at the edge of text, which isn't great. Try to leave some margin and it'll be perfect. If necessary, you can squeeze the source image (moderatly so it's not noticeable) with an image editor before cropping to make it fit better in the format we have.

**Comment by strycore** [comment]
MESS is a family of emulator that uses a set of options and code, I don't understand how I could be broken down differently.

Plugins in emulators could be a neat idea, in theory. The reality is that they never caught on and there is often only one plugin by subsystem or one good plugin and several rubbish ones. Soon the only plugin based emulator will be PCSX2, one of those were there are not many options when in comes to configuring it correctly.
I can't wait for the libretro team to complete their work on Mednafen so we can get rid of PCSX. Same goes for Mupen64 which is another plugin based but very unstable and poorly executed emulator. 
The libretro approach is actually the ideal way of doing things. Here the plugins are the actual machine emulators (called cores but they work in the same way as plugins), gfx rendering, sound or input do not need plugins, they only need good code.
