### ISSUE TITLE
Lutris not opening

### ISSUE THREAD

**Issue by yeebi** [lutris/lutris#2864]
lutris won't stop loading and won't open

**Comment by Casul51** [comment]
run `lutris -d ` in terminal

**Comment by yeebi** [comment]
it said run was not a command

**Comment by TheBrainScrambler** [comment]
@yeebi on which Linux distribution are you ? Where did you install Lutris from ? We need more infos to help you

**Comment by AlexanderRavenheart** [comment]
@Casul51  You need to type `lutris -d` inside of a terminal and press Enter (that is what was meant by run lutris -d in terminal, run is not part of the command, it was meant to tell you what to execute for getting the required information)

**Comment by strycore** [comment]
Either the migration issue which is solved in master or MangoHud which is not our bug. Closing.
