### ISSUE TITLE
Segmentation fault with Manjaro

### ISSUE THREAD

**Issue by leucome** [lutris/lutris#2866]
Lutris do not start and the last message in the terminal is...
2020-05-11 14:43:28,160: Updating DXVK versions
Segmentation fault (core dumped)

What I tried so far.

Revert to an earlier version of Lutris and I get The same issue. 
Revert  Manjaro to a previous state from 2 weeks ago and then Lutris works. 
If I reapply all Manjaro update Lutris stop to work again. 

Seems like there is an incompatibility with one of the newest package. Based on this behaviour I think it's not a configuration files issue, probably.  It is likely to be caused by one these updated packages but since there is over 600 updates I'm not sure how I'll find which one cause the issue.
I'm suspecting maybe a GTK package as the Segmentation fault  happens  were we usually get some GTK messages in the terminal. 

The .json file created by typing `lutris --submit-issue` in a terminal.  About that... Where this files is supposed to be? The documentation do not really provide the expected location of the generated files. 

So is there somebody who use Manjaro that experience the same issue.  If so did you find which specific package cause this.

**Comment by Medath** [comment]
Sounds like an issue with your Manjaro installation to me. What output do you get when you run `lutris -d` in a terminal? Also after running it, `coredumpctl info -1` will likely show more information about whatever caused the crash and it might be a good hint to see which package is at fault

**Comment by strycore** [comment]
Also make sure you're not doing weird stuff with mangohud. We've been seeing a trend of that lately.

**Comment by leucome** [comment]
Yes I'm  I also think there is something wrong with a package in my Manjaro installation. 
Also I indeed use Mangohud so I'll do some test to see if it's the culprit. 

There more output. 

[leucome@Manjaro-Ryzen-PC ~]$ lutris -d

(lutris:3558277): Gtk-WARNING **: 17:12:34.092: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:3558277): Gtk-WARNING **: 17:12:34.092: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:3558277): Gtk-WARNING **: 17:12:34.092: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO     2020-05-11 17:12:34,474 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-05-11 17:12:34,474 [startup.check_driver:62]:Using X.Org
INFO     2020-05-11 17:12:34,474 [startup.check_driver:64]:Running Mesa driver 20.0.6 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.7-14-tkg-pds, LLVM 10.0.0) (0x731f)
INFO     2020-05-11 17:12:34,474 [startup.check_driver:77]:GPU: 1002:731F 1849:5101 using amdgpu drivers
/mnt/home/leucome/.local/share/vkBasalt/vkBasalt.conf
set option effects equal to cas
set option casSharpness equal to 0.4
set option fxaaQualitySubpix equal to 0.75
set option fxaaQualityEdgeThreshold equal to 0.125
set option fxaaQualityEdgeThresholdMin equal to 0.0312
set option smaaEdgeDetection equal to luma
set option smaaThreshold equal to 0.05
set option smaaMaxSearchSteps equal to 32
set option smaaMaxSearchStepsDiag equal to 16
set option smaaCornerRounding equal to 25
set option debandAvgdiff equal to 1.8
set option debandMaxdiff equal to 4.0
set option debandMiddiff equal to 2.0
set option debandRange equal to 24.0
set option debandIterations equal to 1
set option lutFile equal to /path/to/lut/without/spaces
interrupted create instance
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: disabling NGG because ACO is used.
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /mnt/home/leucome/.config/MangoHud/python3.8.conf [ not found ]
parsing config: /mnt/home/leucome/.config/MangoHud/MangoHud.conf [ ok ]
afer destroy instance
INFO     2020-05-11 17:12:34,518 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-05-11 17:12:34,520 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
Segmentation fault (core dumped)
[leucome@Manjaro-Ryzen-PC ~]$ coredumpctl info -1
           PID: 3558277 (lutris)
           UID: 1000 (leucome)
           GID: 1001 (leucome)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-05-11 17:12:34 EDT (9s ago)
  Command Line: /usr/bin/python /usr/bin/lutris -d
    Executable: /usr/bin/python3.8
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (leucome)
       Boot ID: d5b69e3e0928465a98cf1c2426946f3e
    Machine ID: 979645520bb04eb6ba0d60a45d30fcc0
      Hostname: Manjaro-Ryzen-PC
       Storage: /var/lib/systemd/coredump/core.lutris.1000.d5b69e3e0928465a98cf1c2426946f3e.3558277.1589231554000000000000.lz4
       Message: Process 3558277 (lutris) of user 1000 dumped core.
                
                Stack trace of thread 3558313:
                #0  0x00007f2da1208bef n/a (n/a + 0x0)
[leucome@Manjaro-Ryzen-PC ~]$

**Comment by leucome** [comment]
Yeas you are

> Also make sure you're not doing weird stuff with mangohud. We've been seeing a trend of that lately.

Yeah you are right it was Mangohud who caused the issue.

**Comment by strycore** [comment]
yes, it's because of mangohud.
Is it becoming the new norm to launch desktop every application with Mangohud on Manjaro?
Btw, I've tried doing the same thing, running Lutris with Mangohud, but it didn't crash on Pop 20.04 so something else is off on Manjaro.

**Comment by leucome** [comment]
I guess using Mangohud all the time may become common  with GOverlay that allow to turn on Mangohud and Vkabastk setting globally with a switch. 

It was Mangohud version  0.3.5-1  from AUR.  It may be an issue that come from this specific package.

**Comment by strycore** [comment]
Closing as not our bug
