### ISSUE TITLE
p7zip security risk

### ISSUE THREAD

**Issue by FelschR** [lutris/lutris#2868]
`p7zip` hasn't received any updates since mid-2016 (https://sourceforge.net/projects/p7zip/).
There are multiple known vulnerabilities:
https://www.cvedetails.com/vulnerability-list/vendor_id-9220/product_id-30936/7-zip-P7zip.html

Many distributions ship patches for these issues but as there is no active development for the project it remains a possible security threat.

NixOS has marked the package as unsafe which causes installation to fail by default:
https://github.com/NixOS/nixpkgs/pull/86417

**Comment by strycore** [comment]
And?

**Comment by strycore** [comment]
People are going to hack their own computer?

**Comment by strycore** [comment]
The build script is here: https://github.com/lutris/buildbot/blob/master/tools/p7zip/build.sh

As long as we don't use any feature, we can switch to another source, PRs welcome.

**Comment by DavHau** [comment]
> People are going to hack their own computer?

No, but others can.
If you read the CVEs:

`"...allows remote attackers to cause a denial of service (segmentation fault) or execute arbitrary code via a crafted RAR archive. "`

`"allows remote attackers to cause a denial of service (out-of-bounds write) or potentially execute arbitrary code via a crafted ZIP archive. "`

**Comment by strycore** [comment]
It's not up to us to fix p7zip. If there is a fixed version we can ship, good. We'll ship it. 
Otherwise, I don't care, this is just noise. The way Lutris works means that we have to be careful in what's published on the website. People don't need a specially crafted zip to do something malicious.
