### ISSUE TITLE
Atari800 problem

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#287]
when I start the game from lutris, the emulator "freezes" and does not accept user input, closing that window using the x button, drops you back to another atari800 window that will accept all user input, but the rom you have loaded has been ejected, thus you need to go look for it again.

is there around it or not?

**Comment by strycore** [comment]
Have you tried pressing F4? It's mapped to the Atari start key (see full mappings here: https://sourceforge.net/p/atari800/source/ci/master/tree/DOC/USAGE)

**Comment by telanus** [comment]
I've used Atari800 before, so do know my way around it :smile: 

used F4 and nothing happens.

My System: Linux Mint 17.3 with Cinnamon 2.8.8

**Comment by strycore** [comment]
I've tried it with Choplifter (1982)(Broderbund)[color version].atr, what game are you trying it with?

**Comment by telanus** [comment]
OK I found a problem, and solved another one.

with the "normal" a800 everything seems to hunky-dory, but found that if you set it to a5200 then it'll stop responding to input, so somewhere Atari800 does get the idea that it's suppose to emulate the a5200, but forgets to add the a5200's joysticks.
