### ISSUE TITLE
Support Proton GE Custom 5.8

### ISSUE THREAD

**Issue by lazerl0rd** [lutris/lutris#2870]
**Describe the bug**

Assuming `ge-protonified` is Proton GE Custom, the version install-able by Lutris (4.10) is quite old. Please update it.

**Expected behavior**

The latest Proton GE available.

**Current behavior**

Proton GE 4.10 is the maximum available.

**Steps to reproduce**

n/a

**Lutris debugging output**

`n/a`

**System information**

`n/a`

**Screenshots**

![image](https://user-images.githubusercontent.com/24303423/81727045-43a78c00-9480-11ea-9042-dd2e9fb3cc61.png)

**Comment by Galcian79** [comment]
[https://github.com/lutris/docs/blob/master/WineBuilds.md](https://github.com/lutris/docs/blob/master/WineBuilds.md)

**Comment by strycore** [comment]
Proton GE builds are already supported. Place them in the expected directory.
ge-protonified is something else, it's a wine build

**Comment by strycore** [comment]
I removed the ge-protonified entries from our API
