### ISSUE TITLE
Lutris ignores Winetricks failures

### ISSUE THREAD

**Issue by rockerbacon** [lutris/lutris#2871]
**Describe the bug**

Lutris continues installation even after Winetricks fails. If an installer specifies Winetricks it's because they are essential for the correct functioning of the game.

Because of this behaviour a lot of installers on Lutris.net are straight up broken because no one knows things are failing.

That problem also affects good installers used on incorrectly configured machines which cannot run Winetricks. The user will be plagued with bugs after installation simply because no one warned them there were problems going on.
**Expected behavior**

Lutris should stop installation and show a descriptive error message after Winetricks fails.

**Current behavior**

Lutris continues installation after Winetricks fails.

**Steps to reproduce**

- Install Mod Manager 2 from Lutris.net (just an example)
- Notice in the logs that Winetricks fails because of conflicts between vcruntimes and ends up not installing `dotnet40` which is essential for the application to work
- Notice that the installer continues installation as if nothing had happened even after the error

**Comment by strycore** [comment]
Closing this issue in favor of #2852, the key is allow keeping track of the return code of the process.
