### ISSUE TITLE
Better ZX Specturm support

### ISSUE THREAD

**Issue by axet** [lutris/lutris#2872]
A lot of zx spectrum games available online for free and with default debian installation I can play almost all of them.

For example installing 'fuse-emulator-gtk' 'spectrum-roms' allows me to download and run a lot of games from https://www.worldofspectrum.org by simple calling:

`fuse --machine 128 --tape "$HOME/Downloads/NetherEarth.tzx.zip"`

But lutris does not allow me to specify tap files (or zipped versions). By the looks of it lutris only works with snapshots (for game data) and unknown rom files, which I unable to figure it out how to use it. Seems like no one actually using zx specturm at lutris.

Can we have fuse as emulator with basic roms available by default?

Few amazing games:

  * https://www.worldofspectrum.org/infoseekid.cgi?id=0003391
  * https://www.worldofspectrum.org/infoseekid.cgi?id=0001686
  * https://www.worldofspectrum.org/infoseekid.cgi?id=0001484

**Comment by xordspar0** [comment]
I wish that Lutris had a better way to do emulators in general. The concept of an installer doesn't make as much sense for emulated games. You just need to download a file, and you can use that file with any emulator you choose.

I haven't tried using the libretro runner. Maybe that works better. But the user doesn't always get to pick a runner. This is a ZX Spectrum game that only offers an installer that uses the MESS runner, for example: https://lutris.net/games/golden-axe/

**Comment by axet** [comment]
I've tried them all already: mess, mame, libreto. I do not know how to configure them trough lutris. I do not know all emulators (mgba missing most games available freely), but for zx specturm here is amazing solution fuse (can do all things I need: tapes, configs, roms, speed, tape loaders, etc) and it is covered with rooms and downloadable games.

And BTW: mess merged by mame.

**Comment by strycore** [comment]
The next release of Lutris will deprecate the MESS runner and also bring some improvements to the MAME runner. In the near future, Lutris will be able to do mass-import of MAME games, including console/home computers. However, since MAME's software list is somewhat restricted, mass import will improve even more when we have TOSEC / No-Intro support.

**Comment by strycore** [comment]
I added support for ZX spectrum tapes in the following commit https://github.com/lutris/lutris/commit/265bc8ef7487c8684628afd8fff40b9442fad781

This means you can drag and drop a tzx or tap file (zips work too) and it will automatically be added to Lutris, given the checksum is known in the TOSEC database.
