### ISSUE TITLE
[Feature Request] Lutris Streaming Server

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#2873]
This is probably an unusual request but it would be nice if Lutris can sit on a server and stream games on demand for the user using technologies such as x2go in order to forward the game window directly into a local client. The Lutris client itself can connect to the Lutris server and list available games which can be started and streamed on demand. It would be like a self-hosted Stadia. Is this difficult to achieve?

**Comment by strycore** [comment]
isn't x2go a really old remote software with really crappy performance?
I think it would be more viable to stream video with ffmpeg than using the subpar solutions that exist for remote desktops

**Comment by strycore** [comment]
I gave X2go a try.
I wasn't expecting anything but I was still let down…

Unless we develop our own streaming technology with realtime input over the network, I don't think this is possible. Any remote desktop currently out there is not suited to run games.

**Comment by xordspar0** [comment]
> It would be like a self-hosted Stadia. Is this difficult to achieve?

I think you're underestimating the engineering work that went into Stadia. :smile: It's a cool idea, but that's a project that someone should take on separately from Lutris.
