### ISSUE TITLE
Lack of install progress for games with multiple files

### ISSUE THREAD

**Issue by Steinhagen** [lutris/lutris#2877]
**Describe the bug**
Try to download a game from GOG that is made from multiple parts like the Witcher 3 (it has around 20 parts, 4Gb each). When you are trying to install the game, the Lutris interpretor will show you the download progress for each part, but won't show you how many parts are left.
The interesting part is that this information is being displayed in the Lutris logger, but not the installation window.
> logger.info("Downloading file %d of %d", len(self.game_files) + 1, len(self.files))

**Expected behavior**
The installation window should display how many parts are left to download.

**Current behavior**
The installation window displays the progress of the current download part without showing you how many parts are left. For a small game, that is ok, but for a 100Gb game made of 20 parts, it surely isn't.

**Steps to reproduce**
Install a GOG game made of multiple parts (like the Witcher 3).

**Lutris debugging output**
> ...........................................
> 2020-05-16 20:00:11,260: Downloading file 4 of 20
> ...........................................

**Comment by buxel** [comment]
Tracking this for #2894

**Comment by strycore** [comment]
closing this bug since this is already implemented in the file-picker branch
