### ISSUE TITLE
Setting LD_LIBRARY_PATH is likely to cause linking problems

### ISSUE THREAD

**Issue by rockerbacon** [lutris/lutris#2886]
**Describe the bug**

Lutris keeps LD_LIBRARY_PATH set while executing custom commands. I have not tested if the same is true for executing files.

Additionally, Lutris also sets LD_LIBRARY_PATH for native Linux applications by default.

This problem was found when someone on Reddit reported my installer was not working under Ubuntu 20.04. Investigation showed that LD_LIBRARY_PATH was set and causing link issues between Zenity and libatk-bridge. A simple `export LD_LIBRARY_PATH=""` at the beginning of the affected command fixed the issue.

**Expected behavior**

LD_LIBRARY_PATH is a very delicate environment variable that should only be used when all libraries used by an application are very well known. Setting it makes sense for Wine, where the Lutris devs know exactly what the binaries are linking against. It does not make sense when Lutris is executing native binaries whose shared libraries have not been carefully analyzed beforehand.

**Current behavior**

Lutris sets LD_LIBRARY_PATH when executing custom commands during game installation and also sets it by default for native Linux applications.

**Comment by buxel** [comment]
Have a look at the system options. There is a toggle "Prefer system libraries", which gives you some control.

**Comment by strycore** [comment]
That's how the lutris runtime works. It's the same mechanism as the Steam runtime btw. Yes, it's likely to cause issues, that's why we try to troubleshoot issues and update the runtime by adding missing libs or removing problematic ones.
Disabling the runtime entirely is not a solution since lutris uses it as a standard base for most runners.
