### ISSUE TITLE
Change runners install location

### ISSUE THREAD

**Issue by tm-st** [lutris/lutris#2895]
Hi.

Is it possible to change the runners install location? They are currently installing to /home/user/.local/share/lutris/runners

Is there a setting to change this to another location? I couldn't find anything in the UI.

Thanks

**Comment by byte1024** [comment]
From what it looks like they use

[RUNNER_DIR = os.path.join(DATA_DIR, "runners")](https://github.com/lutris/lutris/blob/4efadf948c6af7611c44855444e56d3852d5a1c3/lutris/settings.py)

and that comes from

DATA_DIR = os.path.join(GLib.get_user_data_dir(), "lutris")

which uses

https://developer.gnome.org/pygobject/stable/glib-functions.html#function-glib--get-user-data-dir

so no, it looks like you cannot in an official way.

You could in a not official way by changing the settings.py line but that could have unintended and unknown consequences plus you would have to deal with it continually. I think if you knew programming then you could change it by git or forking or whatever but I can tell that you're not and as such I would highly not recommend doing that.

Either they could add an official way (I would expect not but who knows) or if not then it would be best for you to just get over it.

**Comment by tm-st** [comment]
Thanks for letting me know. I'd rather not keep my own fork but again, thanks for the suggestion.
