### ISSUE TITLE
Can't disable Discord rich presence

### ISSUE THREAD

**Issue by blandin** [lutris/lutris#2901]
**Describe the bug**

There is no user configuration for disabling the Discord rich presence feature of Lutris.

**Expected behavior**

Especially given the terrible implementation of Discord presence in Lutris, the user should be able to turn it off completely. The Discord client provides for detecting running Games and updating presence on its own, and in my experience this even works with games running under Wine. The user can't do this, however, while Lutris continues to set its own presence.

**Current behavior**

Lutris sets the user's Discord presence to "Playing Lutris" instead of the game that's running, and the user has no means of disabling this.

**Steps to reproduce**

- Launch Discord
- Launch Lutris

**Comment by strycore** [comment]
wtf… Discord presence is enabled by default?
I'm sorry, it's true, our Discord implementation sucks.

**Comment by strycore** [comment]
no it's not enabled by default and yes there is an option to disable it.

**Comment by blandin** [comment]
I mean, if that's the intention, it doesn't match my experience.

Here are screenshots of the available settings in the menu, as well as the entire preferences window. (And while we're at it, I have never seen the tray icon in my appindicator area.)

![Main window](https://github.com/blandin/random-files/raw/master/lutris-issue-2901/Screenshot%20from%202020-05-26%2023-40-43.png)
![Preferences window 1](https://github.com/blandin/random-files/raw/master/lutris-issue-2901/Screenshot%20from%202020-05-26%2023-57-42.png)
![Preferences window 2](https://github.com/blandin/random-files/raw/master/lutris-issue-2901/Screenshot%20from%202020-05-26%2023-40-15.png)
![Preferences window 3](https://github.com/blandin/random-files/raw/master/lutris-issue-2901/Screenshot%20from%202020-05-26%2023-40-18.png)

And here is a Screenshot of how my Discord profile appears to anyone as long as Lutris is running, and regardless of the game I'm playing.

![Discord profile](https://github.com/blandin/random-files/raw/master/lutris-issue-2901/Screenshot%20from%202020-05-26%2023-41-25.png)

As you can see, the only setting I've modified is the default installation path.

If there's an option for Discord presence, I'm not seeing it. If it's somewhere else, or if I need to edit a config file, that would be good documentation to have appear when someone searches "Discord" on your project wiki or forums, or when Googling "lutris disable discord presence".

That said, a manual config file edit would be counter to the reason I'm using Lutris: precisely so I don't have to mess with config file tweaks and terminals to run my games, and it's terrible UX.

Even if I'm completely wrong, and blind, and perhaps even stupid for not noticing a setting you say exists, instead of dismissing someone's bug report out of hand and denying their experience with a sarcastic remark, it would have been better to point to documentation, or a file path, or a screenshot that would get the user the answer they were looking for in the first place.

**Comment by strycore** [comment]
I see what's going on.

Yes, our Discord implementation sucks but it's not that bad. The fact that you do not have the PyPresence library installed.

What is happening is outside of our control. Discord sees an executable from /usr/games/ is running and puts it there. We can't do anything, it's on Discord part to stop being dumb fucks.

**Comment by Ammako** [comment]
```
sudo mv /usr/games/lutris /usr/local/games
sudo mv /usr/share/lutris /usr/local/share/lutris
```

**Comment by xordspar0** [comment]
That's the idea, but be warned that if you actually do that you'll have trouble in the future. If you move files that are owned by a package then things will not go as expected when you upgrade the package. /usr/local/bin likely comes before /usr/bin in your PATH, so you'll be using the old binary, and there will be 2 data directories: /usr/local/share/lutris and /usr/share/lutris.

**Comment by blandin** [comment]
I'd like to start by apologizing to @strycore: When you replied, I read sarcasm and dismissal where, upon a second and more objective look at your response, there really isn't any. I could blame this on text being a poor conductor of tone, but I won't. I was frustrated with the problem I was having and it affected how I perceived your words. For that, I'm sorry.

Next, to slightly modify @Ammako's suggestion, I've done the following and it seems to work really well.
```sh
sudo ln -s /usr/games/lutris /usr/local/bin/lutris
sudo ln -s /usr/share/lutris /usr/local/share/lutris
```
As @xordspar0 mentioned, moving files around can have consequences for package updates down the line. Also, symlinks are bitchin' and I use them whenever I can.

I chose `/usr/local/bin` rather than `/usr/local/games` to avoid having to modify my `$PATH`. Discord is no longer locking down my presence when I'm running Lutris. :+1:

**Comment by strycore** [comment]
This is caused by a recent change we did for Debian packaging compliance.
Debian packages that are in the Games category should have their executable in the /usr/games/ and Discord just picks up any process from that folder and displays it as now playing. Steam doesn't do that because Steam gets special treatment.

I believe the binary could possibly moved out of /usr/games but we would have to remove the Game category in the Debian package (Lutris isn't a game anyway)

@blandin no offense taken, I'm more angry at Discord for offering such poor APIs and offering so little control over what game creators can do.

**Comment by blandin** [comment]
There is a [thread on Discord's feedback site](https://support.discord.com/hc/en-us/community/posts/360061593871-Feature-to-block-specific-processes-from-showing-discord-RPC) about this. Maybe I'm being naive or overly optimistic, but more attention on that might get them to do something.

**Comment by Ammako** [comment]
Wouldn't hold my breath, Discord is awful when it comes to feedback.

I hadn't even tried symlinks, I figured if I wanted to update I would just move everything back to their original directories. But that's definitely the better solution.
