### ISSUE TITLE
Use xdg-open instead of Firefox please

### ISSUE THREAD

**Issue by Eluminae** [lutris/lutris#2906]
Hello there,

When opening http urls, lutris open firefox directly and by-pass my xdg-open configurations.

Please consider adding a configuration for the browser at minimum.

Thanks a lot, lutris rocks,

kiss

**Comment by Eluminae** [comment]
Or maybe it is using /usr/bin/xdg-open and not simply xdg-open ?

**Comment by xordspar0** [comment]
Which URL do you see this with? The forums, IRC, and Discord buttons in the right pane use xdg-open, and it opens the correct browser when I change my default.

**Comment by baryluk** [comment]
It does find xdg-open in the `PATH`, no absolute paths hard-coded.

You can overwrite behavior using some configs in config file: `browser`, `custom_browser_executable`, `custom_browser_args` (last one to pass extra flags, i.e. if you want to maybe run the links in a separate container, or new window vs new tab decisions).

**Comment by strycore** [comment]
> Try using strace -p maybe to see what happens?
wtf.

**Comment by Eluminae** [comment]
> Which URL do you see this with?

I click on "view on lutris" for example

> You can overwrite behavior using some configs in config file

It seems my perfect workaround

> Try using strace -p maybe to see what happens?

It log shit x) Dunno what I can do with that. Maybe I can add filters or something.

**Comment by Eluminae** [comment]
> Also AFAIK lutris will try to use Gnome / Gtk mechanism to opening URIs, so if you change your default in Gnome / MATE settings for example, it should be respected, even if xdg-open says something else. Check Menu -> System -> Preferences -> Personal -> Preferred Applications in your DM.

I don't use DMs

> It does find xdg-open in the PATH, no absolute paths hard-coded.

It seems crazy cause nor my ~/bin/xdg-open or /usr/bin/xdg-open try to run firefox. My ~/bin is in my path. Maybe something is wrong in lutris?

**Comment by xordspar0** [comment]
Oh, my mistake. It Lutris doesn't use xdg-open by default. First it tries to use the Gtk function [show_uri()](https://developer.gnome.org/pygtk/stable/gtk-functions.html#function-gtk--show-uri), and it only uses xdg-open if that fails.

https://github.com/lutris/lutris/blob/3757415a7073b67444bb0689f0521dc927429dad/lutris/gui/widgets/utils.py#L44-L51

I don't know how the Gtk function is implemented, but that would explain why changing xdg-open has no effect.

**Comment by Eluminae** [comment]
I lost 1 hour searching how to configure gsettings / gtk configs default uri handlers and I didn't find anything.

So, is it possible to configure my lutris to use a specific program?

**Comment by xordspar0** [comment]
> how to configure gsettings / gtk configs default uri handlers

I did some poking around in the [source](https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/gdesktopappinfo.c#L3669) [code](https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/gdesktopappinfo.c#L3427) and found that Gnome (and probably other DEs) use `~/.config/mimeapps.list` to set the URI handlers. My config looks something like this (plus a couple hundred other lines):

```
[Default Applications]
x-scheme-handler/http=firefox.desktop
x-scheme-handler/https=firefox.desktop
```

> You can overwrite behavior using some configs in config file: browser, custom_browser_executable, custom_browser_args

I'm not sure what those settings are for, but they're not used for opening links in the UI.

> is it possible to configure my lutris to use a specific program

Not currently, but I think it would be pretty easy to add. I'm not sure of the best way to design it though. Would it make sense to use xdg-open and if it's not installed then fall back to the built-in Gtk functionality? The fallback mechanism was added in https://github.com/lutris/lutris/commit/a1f50c2a679ae7344f155c67ec416ff13ccda2d3, but I don't know the context around the issue that the commit was trying to solve. From my naïve perspective, I think using xdg-open would be a reasonable default because the standard implementation uses the mime database anyway. If you're providing your own xdg-open script, you could override it however you want.

**Comment by Eluminae** [comment]
> I did some poking around in the source code and found that Gnome (and probably other DEs) use ~/.config/mimeapps.list to set the URI handlers. My config looks something like this (plus a couple hundred other lines)

```
[Default Applications]
x-scheme-handler/http=qutebrowser.desktop;firefox.desktop
x-scheme-handler/https=qutebrowser.desktop;firefox.desktop
```

It seems this file is not used in the Lutris workflow unfortunately cause it doesn't run qutebrowser but firefox.

> Would it make sense to use xdg-open and if it's not installed then fall back to the built-in Gtk functionality?

I agree, xdg-open seems the more generic way.

**Comment by baryluk** [comment]
> > Try using strace -p maybe to see what happens?
> 
> wtf.

That was just a suggestion. strace is great tool for inspecting the behaviour of programs, without even checking the source. This was a last resort way of checking if lutris is calling xdg-open, or if it check path, etc. The text of the original issue suggested he has own `xdg-open` in the path (i.e. not in `/usr/bin`), which might be skipped by lutris. Similarly the gtk might be reading some files to inspect what program to launch for a given URL, and strace would help with that too. This is why suggested checking strace to see if lutris does execute it or not. There are other ways to debug it too, but strace isn't worst first order approximation to the problem.

I don't think this deserves `wtf`, from the maintainer of the project.

Regards,
Witold

**Comment by baryluk** [comment]
> > Also AFAIK lutris will try to use Gnome / Gtk mechanism to opening URIs, so if you change your default in Gnome / MATE settings for example, it should be respected, even if xdg-open says something else. Check Menu -> System -> Preferences -> Personal -> Preferred Applications in your DM.
> 
> I don't use DMs.
> 
> edit: What are those Gnome/Gtk mechanisms ?
> 
> > It does find xdg-open in the PATH, no absolute paths hard-coded.
> 
> It seems crazy cause nor my ~/bin/xdg-open or /usr/bin/xdg-open try to run firefox. My ~/bin is in my path. Maybe something is wrong in lutris?

It is kind of complex, and I myself don't know all the details. Gnome/Gtk has these "registry" like config (gconf? dconf? gsettings? I am pretty sure only 1 of the 3 is non-deprecated, but I don't know which one), and one of the entries there is probably responsible for selecting a behavior of prefered web browser. Just my guess. I tried looking at `gsettings` data, but I can't really find where it stored prefered web browser, so maybe it is not the place to look.

People already suggested `~/.config/mimeapps.list` is probably the right place to use.

**Comment by strycore** [comment]
> I don't think this deserves `wtf`, from the maintainer of the project.

I know, I was just confused by the issue and ways used to solve it. strace can do the job.

We don't do anything special or hardcode the browser to Firefox anywhere. Setting the default browser to something else should apply it to the Gnome settings, unless…

> I don't use DMs.

That seems to be the issue here. Not using a DM will not update the necessary Gnome settings and will not set the default browser to whatever is desired.
There's some level of responsibility involved in not using a DM. It's usually the user's responsibility to take care and be knowledgeable about such thing.

As such, this issue is considered closed.

**Comment by Eluminae** [comment]
> There's some level of responsibility involved in not using a DM. It's usually the user's responsibility to take care and be knowledgeable about such thing.

Don't speak of responsibilities when we actually got no possibilities to control who Lutris call external resources. You force your users to use a paradigm that is related to one distribution.

Add a config somewhere as "who lustris should open url" and you'll give flexibilities and THEN you could tell people "not our bug"

**Comment by john-2000** [comment]
Lets be friendly,....

**Comment by strycore** [comment]
> Don't speak of responsibilities when we actually got no possibilities to control who Lutris call external > resources. You force your users to use a paradigm that is related to one distribution.

Nope. Lutris follows standard Gtk recommendations and doesn't force anything on anyone. Any sane linux distro is able to change the default browser at a global level in a way that is transparent to the user. The fact that you chose to roll with your own desktop without the knowledge required to change Gtk defaults is not our problem. Everything here is open source and tries to stick to standards, there is no barrier except your own knowledge.
