### ISSUE TITLE
Lutris library empty after downgrade

### ISSUE THREAD

**Issue by derbrachialist** [lutris/lutris#2909]
After downgrading Lutris to 0.5.5 because of [Bug#28](https://github.com/lutris/wine/issues/28) my Library is empty. To start the game I have to search "World of Warcraft" in the search bar on Lutris.com, then it finds the already installed game.

[Screenshots](https://imgur.com/a/B9eKqTp)

**Comment by xordspar0** [comment]
It's not really possible to downgrade the database unless you have a backup of the older version, sorry. :confused:

**Comment by derbrachialist** [comment]
Ok so I will have to wait until the performance issues of 0.5.6 are fixed and upgrade again.
