### ISSUE TITLE
Keep track of play times per game and per session

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#291]
this is a feature request :smile: 

This is something I think a lot of users would find useful, My feature request is a stats provider menu thingy. something like a times a game is played, the time played per game, average time played and even average time played by game.

**Comment by strycore** [comment]
Yes that's something I wanted to implement for a while, the extra stats would be neat to have as well. I think the process tracking is now reliable enough to begin implementing this.

**Comment by Xodetaetl** [comment]
And we can do it better than Steam by not counting idle time (no input for x seconds).

**Comment by telanus** [comment]
@Xodetaetl would be great especially with games like Race 07 that takes a while to start, due to it caching all the mods that one can have for the game. On Windows it took almost 7-10 minutes before it started, now down to perhaps 3-5 due to it now living on an ext4 hdd and not ntfs anymore

**Comment by tannisroot** [comment]
This is partially solved by playtime features.
