### ISSUE TITLE
JSON based runners

### ISSUE THREAD

**Issue by strongjaw16** [lutris/lutris#2912]
There are many emulators that are not included as runners in Lutris that I prefer to use, such as ePSXE, VBA-M, and fceux. I know that the systems that these programs emulate are all available under RetroArch, but it would be nice to be able to add a custom runner to my runner library so that I can launch games with my preferred emulator from withing Lutris. I think many people would use this, as it opens up so many more possibilities for everyone, and it would be a really great feature that would improve Lutris' usability.

**Comment by xordspar0** [comment]
> I know that the systems that these programs emulate are all available under RetroArch, but it would be nice to be able to add a custom runner to my runner library so that I can launch games with my preferred emulator from withing Lutris.

Did you know that libretro is one of the runners for Lutris? You can use any libretro emulator, *and* you can launch it in Lutris.

**Comment by strycore** [comment]
I have plans to get some generic runners implemented from a JSON file. This would allow for custom runners like you want.

**Comment by strongjaw16** [comment]
That's great! I really appreciate Lutris, thanks so much for working on it!

**Comment by strycore** [comment]
Still need to figure out a good location for user provided runners
