### ISSUE TITLE
humble bundle integration: can't login

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2913]
**Describe the bug**

Pressing "Log in" button in humblebundle window does nothing.

**Expected behavior**

You know....

**Current behavior**

Does not work.

**Steps to reproduce**

- Install kubuntu 20.04
- Launch lutris (tried release/git)
- Try to login into humblebundle

**Lutris debugging output**

[humble.log](https://github.com/lutris/lutris/files/4710710/humble.log)

**System information**

[lutris-issue-report.tar.gz](https://github.com/lutris/lutris/files/4710715/lutris-issue-report.tar.gz)

**Screenshots**

**Comment by xordspar0** [comment]
From you log, this seems to be the problem. For some reason, Humble Bundle responded with HTML instead of answering Lutris's question:

```
DEBUG    2020-06-01 13:14:15,570 [http.get:65]:GET https://www.humblebundle.com/api/v1/user/order
ERROR    2020-06-01 13:14:16,578 [jobs.target:32]:Error while completing task <bound method HumbleBundleSyncer.load of <class 'lutris.services.humblebundle.HumbleBundleSyncer'>>: Invalid response (https://www.humblebundle.com/api/v1/user/order:200): <!doctype html>
<html lang="en" class="">
  <head>
    <title>
Humble Bundle - L
<class 'ValueError'> Invalid response (https://www.humblebundle.com/api/v1/user/order:200): <!doctype html>
<html lang="en" class="">
  <head>
    <title>
Humble Bundle - L
```

**Comment by soredake** [comment]
It's log after i pressed disconnect after closing login window.

**Comment by byte1024** [comment]
That error is "normal" at this time and doesn't reflect on the ability to login in as I get this and log in successfully.

However, its impossible to remove the account when signed out. It stays sort of logged in but that's a different issue.

**Comment by soredake** [comment]
For the record, it was worked on archlinux

**Comment by byte1024** [comment]
At least to me it looks like its using

`login_url = "https://www.humblebundle.com/login?goto=/home/library"`
...
```
""Connect to Humble Bundle""
dialog = WebConnectDialog(SERVICE, parent)
```
...
`class WebConnectDialog(Dialog):`
...
`self.webview.load_uri(service.login_url)`

and the problem should be with https://www.humblebundle.com 

If you browse to https://www.humblebundle.com/login?goto=/home/library this login window is what you see and the login button is under the authority of https://www.humblebundle.com server.

The only possible point of issue I can see with Lutris here is a connection one like a timeout. The login shouldn't be able to be snooped on but the server responses for the cookie, tokens, errors, whatever should be all that Lutris is capable of during that time.

So once the login page shows it should ultimately be out of Lutris hands except for server responses or being able to save a token of some sort in a good situation.

Maybe I missed something but I shouldn't have. I've coded these things before. Really, when a user presses on the login button on the secure web page, Lutris shouldn't have anything to do with that.

**Comment by byte1024** [comment]
At least to me it looks like its using

`login_url = "https://www.humblebundle.com/login?goto=/home/library"`
...
```
""Connect to Humble Bundle""
dialog = WebConnectDialog(SERVICE, parent)
```
...
`class WebConnectDialog(Dialog):`
...
`self.webview.load_uri(service.login_url)`

and the problem should be with https://www.humblebundle.com 

If you browse to https://www.humblebundle.com/login?goto=/home/library this login window is what you see and the login button is under the authority of https://www.humblebundle.com server.

The only possible point of issue I can see with Lutris here is a connection one like a timeout. The login shouldn't be able to be snooped on but the server responses for the cookie, tokens, errors, whatever should be all that Lutris is capable of during that time.

So once the login page shows it should ultimately be out of Lutris hands except for server responses or being able to save a token of some sort in a good situation.

Maybe I missed something but I shouldn't have. I've coded these things before. Really, when a user presses on the login button on the secure web page, Lutris shouldn't have anything to do with that.

It is _possible_ that the webview library has a bug in that situation and an update of the library or whatever could fix it. But, I'm not aware of any other reason why it could happen.

**Comment by byte1024** [comment]
Further testing shows that there are times when the google and Facebook login buttons do nothing but will work after right clicking and reloading the page.

I believe this is a WebKit2 issue. About all Lutis can do is try to update it.

**Comment by byte1024** [comment]
Confirmation that the problem also occurs with Epiphany Technology Preview browser which uses webkit. https://wiki.gnome.org/Apps/Web/Development

**Comment by strycore** [comment]
Is this still an issue on 0.5.7?

**Comment by soredake** [comment]
I can login and import games in 0.5.7

**Comment by haliphax** [comment]
Issue is back for me in 0.5.10.

**Comment by strycore** [comment]
@haliphax the currently open issue about this is #4099 
Also, Cloudflare protection just gave up after 10 tries? that's interesting and weird...
