### ISSUE TITLE
Lutris shouldn't monitor processes of pre-launch and post-exit scripts

### ISSUE THREAD

**Issue by HugLifeTiZ** [lutris/lutris#2915]
**Describe the bug**

Lutris seems to monitor the processes started from pre-launch and post-exit scripts, which causes pre-launch and post-exit both to hang if they start any processes.

**Expected behavior**

I am expecting it to simply run the script and nothing else. If I want the script to wait for a process to do something, I can block inside the script.

**Current behavior**

If I start any programs in the background from within the script, Lutris starts monitoring them, and won't consider the scripts finished until all the processes are gone. So I can't start OBS Studio and start a recording before starting a game, or restart picom or conky after a game is over.

**Steps to reproduce**

* Create a pre-launch script that starts up a program in the background.
* Tick "Wait for pre-launch script completion."
* Start a game.
* The program started in your script will start, but the game never will.
* Similarly, if you use this script for post-exit, it will start the program and never consider the game stopped.

**Comment by HugLifeTiZ** [comment]
Looking at the code, it seems that something that exacerbates this issue is that the list of excluded processes it not applied to the prelaunch or postexit scripts.

**Comment by AlexanderRavenheart** [comment]
I guess this is coming from a misunderstanding of what "pre-launch script completion" is.

Perhaps the code could be changed so that "Wait for pre-launch script completion" only waits for that script to finish without monitoring anything else spawned during it's execution.

**Comment by HugLifeTiZ** [comment]
Misunderstanding, or miscommunication.

In any case, if I change the code myself to replace the prelaunch and postexit parts of the code with calls to `os.system`, it gets the behavior I desire. I'm sure that's not ideal, so I'll leave it to you all to decide what the right way is and implement that. :)

**Comment by strycore** [comment]
Why did you check "wait for completion" if you want to no wait and launch the game immediatly, I don't understand.
I'm going to close this and assume it was a misunderstanding.
If the "Wait for pre-launch script completion." option is proven to not work then reopen.

**Comment by HugLifeTiZ** [comment]
Immediately closing and not even trying to understand? That's pretty concerning.

I interpreted the option "wait for completion" to mean that Lutris would wait for the script itself to be done. Like if you opened up a terminal, typed the command yourself, then waited for the command prompt to reappear. It doesn't say anything about watching any processes started by the command, and in my opinion, watching the processes started by those scripts is a dramatic overreach. Those scripts may deal with starting and stopping desktop or system services, things that Lutris absolutely should not be concerned with. And since the process exclusion list doesn't apply to pre-launch and post-exit commands, there's nothing we can presently do to stop it from caring about those processes.

**Comment by strycore** [comment]
I think you are still not understanding how the option works. 
The default is to launch a command and immediately launch the game after.
There is a command that gives you the option to wait until the command has terminated.
I don't understand how this can be misinterpreted.
If you have better wording in mind, please suggest them but I do really think that you just got confused on how processes work in a general manner.

**Comment by HugLifeTiZ** [comment]
When you run a sequence of commands in a shell script, the shell does not sit around waiting for every process spawned by a given command to terminate before proceeding to the next command. When the command returns, it moves on to the next one, and when it reaches the end of the script, the script itself returns, even when there are background processes left behind by some of its children. It's not its job to care about that.

I understand why Lutris has the ability to watch for processes, as it facilitates installation and run scripts that might need that sort of thing to function correctly. (where "correctly" just means "as a user just double clicking the game banner would expect it to") But I feel that the application of that framework to user-made and user-specified pre-run and post-run scripts that are meant to control a user's environment is terribly detrimental.

I'm not going to argue any further if you don't agree; I've migrated to launching games through Pegasus because I wanted a launcher that can be navigated by controller, and my workflow has already been adapted. At this point, I only have Lutris to install and run games that are obtuse to install. But there might be other users invested in Lutris as an all-in-one solution who are going to get thrown off by this behavior.

**Comment by strycore** [comment]
> When you run a sequence of commands in a shell script, the shell does not sit around waiting for every process spawned by a given command to terminate before proceeding to the next command. When the command returns, it moves on to the next one, and when it reaches the end of the script, the script itself returns, even when there are background processes left behind by some of its children. It's not its job to care about that.

What are you on about… Yes, the shell waits until a script has finished to return a prompt. Unless you daemonize your script or the commands in the script themselves are daemonized.

Your understanding of processes is weird. I'm glad that you have found a solution that works for you.

**Comment by HugLifeTiZ** [comment]
> Unless you daemonize your script or the commands in the script themselves are daemonized.

Hold on. This might be the point of misunderstanding. If your script runs commands that background themselves, or if you explicitly background them with a following & character, the script will still return after it has executed every command, even if the backgrounded processes are still running.

You can try it yourself; make a file called `/tmp/bg.sh` and the only thing you need to put into it is `/bin/sleep 5 &`. When you run this script, regardless of if it's `sh /tmp/bg.sh` or `bash /tmp/bg.sh`, the script will return immediately. It will not sit around and wait for the backgrounded sleep process to be done before returning control to the terminal.

Lutris's current behavior is to sit and wait for every subprocess spawned by a pre-launch or post-exit command to exit. When I say "wait for script completion", I am saying "wait for the script to return", not "wait for every single command it has ever started to go away". If I start OBS and start recording, I might want to wait to be sure OBS is done starting and has successfully started recording, that's something I can do myself in my script.

Maybe after a game has finished, I want to restart my external compositor. So the game-end script starts the picom process. And then it will never consider the game as having finished because picom remains running as part of the post-exit command that has itself already returned. I have tried and tried and tried, and there is literally nothing I can do to get Lutris to ignore background processes started in post-exit. Not nohup, not &, nothing. It was started as a subprocess, and Lutris's overzealous process watcher inappropriately applied to arbitrary user-defined commands sees that and decides on its own that the command is not done even though the script itself has returned.

It's not your place decide that "done" means every process ever started has gone away and sit there waiting until that is the case. It's your understanding that's weird.

**Comment by strycore** [comment]
> It will not sit around and wait for the backgrounded sleep process to be done before returning control to the terminal.

I know. That's what I was trying to tell you by "the commands in the script themselves are daemonized."

You've daemonized `sleep`. Scripts usually don't do that. They run processes in the foreground. I don't know where you got the idea that shell scripts are daemonizing commands by default but this is weird.

**Comment by HugLifeTiZ** [comment]
And you've conveniently ignored the rest of my post that had actual **practical** use-cases for setting up and tearing down an in-game environment. It's clear you're going to do everything in your power to avoid budging on this, so I'm done.

**Comment by strycore** [comment]
And all this time you've ignored the fact that I've told you that *not* checking a checkbox would provide the desired result.
I was done long ago, I was just trying to make sense of your understanding of Unix processes.
Lutris is a big project and I do not have time to educate user about Unix or computing in general. There are resources freely available for that. Please read them.

**Comment by Stefan99353** [comment]
Hi @strycore, I kind of have the same problem as OP:

I have a python script that has some amount of startup time and needs to be running before the game starts and needs to keep running while the game starts. So this would be the order of steps I want lutris to do:

1. Start pre-launch script called `launch.sh`
2. pre-launch script starts the actual script `inject.sh` in a background job (`& disown`)
3. `launch.sh`sleeps for 2 seconds to ensure the main script has started and is ready
4. `launch.sh`exits
5. Lutris starts the game

Is this possible in another way?

**Comment by strycore** [comment]
make sure "Wait for pre-launch script completion" is disabled and it should have the desired effect

**Comment by Stefan99353** [comment]
Sadly that is not the case. Tested setting the sleep command to 5min but the game starts almost immediately. I want the game to start after the sleep command finishes and `launch.sh`exits.

**Comment by HugLifeTiZ** [comment]
I should have unsubscribed from this issue after the lead maintainer insinuated that I am stupid or uneducated about how Linux processes and scripting work, but I didn't, and here I am looking at *this* conversation again. If someone else has come here asking about this, that means that Lutris's overzealous process watcher is currently still being applied to pre-launch and post-exit commands.

I am going to try **one last time** to try and explain the differences in behavior between what Lutris currently exhibits and what Stefan is looking for (and what I was looking for before migrating to a different launcher). Mathieu, you keep saying "use the checkbox for your desired behavior." But the checkbox does not currently function the way *we* expect it to. Let's go ahead and outline a couple of simple dummy scripts that we might want to use for some behavior:

pre-launch.sh
``` sh
#!/bin/sh
pkill picom  # Stop external compositor.
obs &  # Start OBS Studio in the background.
sleep 3  # Wait for it to be ready.
obs-start-recording.sh  # Use a websockets client or something to start recording.
```

post-exit.sh
``` sh
#!/bin/sh
obs-stop-recording.sh  # Use a websockets client or something to stop recording.
sleep 2  # Wait for recording to be stopped.
pkill obs  # Exit OBS Studio.
picom &  # Restart external compositor.
```

These are realistic, *practical* things that any given user might want to do any time they start or stop a game. Most people will use their window manager's integrated compositor and tweak that instead, but we're using picom because it illustrates the process issue.

What we expect the checkbox "wait for script completion" to do is the difference between `./pre-launch.sh` and `/pre-launch.sh &` in a terminal. So what happens in each case? When you run `./pre-launch.sh`, what will happen is that your terminal will wait for about 3-4 seconds and then give you your control back. In that three seconds, we can be reasonably sure that OBS Studio has started up and has started recording. If you append that `&`, what happens instead is that you immediately get back control in your terminal.

What does Lutris *currently do?* It has this process monitor that looks at every single descendant of a process started by a command, and *waits for them to exit.* **Every single one.** When Lutris uses the process monitor, it has its own idea of "the command is done" that is different from that of your shell, and is *considerably more overbearing and opinionated.*

The intended behavior of this script is "start up OBS studio in the background, wait a few seconds, then return control." The shell sees that the command exited, and *has no reason to disbelieve that.* With Lutris's process monitor in play, the main command has exited, but it's still looking at that OBS in the background. "No, the command isn't done yet, this child process hasn't exited yet." We never told Lutris to care about that child process. If we wanted to wait on a backgrounded process, we can do that just fine in our scripts, like this:

``` sh
#!/bin.sh
complicated-lengthy-setup-command.sh &
setup_pid=$?
other-setup-thing-a.sh
other-setup-thing-b.sh
persistent-background-thing.sh &
wait $setup_pid
```

This script will intentionally wait on that one lengthy setup command that has to be done before we start our game, while letting the persistent background thing stick around. Lutris's current behavior is sort of like [wait with no operands](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/wait.html#top) except much more overzealous.

A script considers itself done *when it exits*, regardless of whether or not any of its background processes are still alive. If a script considers itself done and leaves behind background processes, **that is intentional.**

The entire lynchpin of this discussion is "what does it mean for the script to be complete?" Mathieu, you have been absolutely insistent that it means "every command it has ever started has exited", contrary to the way **literally every shell in the world** behaves. And you keep sidestepping this with "then don't check the box" even though there are so many valid usecases where we would want to wait on one thing but let another thing keep running in the background and consider it done. I want to make sure my recording has stopped before I consider the command done, but it's going to start my compositor and leave it running while the script doing that exits.

I don't have much faith in this elaborately-constructed post changing any minds due to how badly the last conversation went, so I'll end it with this. If we can't come to any sort of consensus on what "complete" means, then maybe this checkbox should be a set of three options instead:

- Do not wait on script at all
- Wait for the script to exit
- Wait for the script and all descendant processes to exit

**Comment by AlexanderRavenheart** [comment]
I agree with replacing the checkbox. A combobox with those 3 options will cover any desired use case and will avoid misunderstandings about what "complete" means.

**Comment by strycore** [comment]
I don't want to clutter the UI with more options. Especially ones that will confuse users.
I've got rid of the MonitoredCommand for synchronous prelaunch scripts, we now simply execute the script in the foreground and return when it's done.
