### ISSUE TITLE
Suggestion: Allow custom icon / banner

### ISSUE THREAD

**Issue by althonos** [lutris/lutris#292]
Hi ! Title says it all, I've been using Lutris with ROM-hacked games and as it is just the different version of the same game, it shares banners and make it a bit confusing...
So why not look for banners and icons named .icon and .banner in the game folder, only falling back to default ones if those files are absent / not working ?

**Comment by jtrees** [comment]
I would also be interested in being able to set custom banners for games that were added manually.

**Comment by strycore** [comment]
The current implementation available in the master branch allows to set custom banners for all games :)

**Comment by jtrees** [comment]
Oh sweet. I look forward to the release.
