### ISSUE TITLE
No debian builds for 0.5.6 on Opensuse

### ISSUE THREAD

**Issue by nolange** [lutris/lutris#2920]
For some reason, the [Debian packages on Opensuse](https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris) are missing the current version (0.5.6). The links are there, but broken, the apt repo is just having 0.5.4

**Comment by xordspar0** [comment]
Maybe it was a temporary issue? I was just able to download lutris_0.5.6_amd64.deb.

**Comment by byte1024** [comment]
Looks good on my end as well. I expect this to be a user side issue.

**Comment by nolange** [comment]
Yes, works now
