### ISSUE TITLE
Desktop files created in system by Lutris Wine

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#2922]
I have noticed that Wine from Lutris has created some desktop files in my `~/.local/share/applications` directory:
```
$ cat ~/.local/share/applications/wine-extension-*
[Desktop Entry]
Type=Application
Name=winhlp32
MimeType=application/winhlp;
Exec=env WINEPREFIX="/home/asciiwolf/.games/halo-online" /home/ubuntu/buildbot/runners/wine/lutris-5.6-2-x86_64/bin/wine start /ProgIDOpen hlpfile %f
NoDisplay=true
StartupNotify=true
Icon=4137_winhlp32.0
[Desktop Entry]
Type=Application
Name=hh
MimeType=application/vnd.ms-htmlhelp;
Exec=env WINEPREFIX="/home/asciiwolf/.games/halo-online" /home/ubuntu/buildbot/runners/wine/lutris-5.6-2-x86_64/bin/wine start /ProgIDOpen chm.file %f
NoDisplay=true
StartupNotify=true
Icon=A35F_hh.0
[Desktop Entry]
Type=Application
Name=Wine Installer
MimeType=application/x-wine-extension-msp;
Exec=env WINEPREFIX="/home/asciiwolf/.games/halo-online" /home/ubuntu/buildbot/runners/wine/lutris-5.6-2-x86_64/bin/wine start /ProgIDOpen Msi.Patch %f
NoDisplay=true
StartupNotify=true
Icon=2402_msiexec.0
[Desktop Entry]
Type=Application
Name=A Wine application
MimeType=application/x-wine-extension-vbs;
Exec=env WINEPREFIX="/home/asciiwolf/.games/halo-online" /home/ubuntu/buildbot/runners/wine/lutris-5.6-2-x86_64/bin/wine start /ProgIDOpen VBSFile %f
NoDisplay=true
StartupNotify=true
```

It has also added new mimetypes to `~/.local/share/applications/mimeinfo.cache`:
```
[MIME Cache]
application/vnd.ms-htmlhelp=wine-extension-chm.desktop;
application/winhlp=wine-extension-hlp.desktop;
application/x-wine-extension-msp=wine-extension-msp.desktop;
application/x-wine-extension-vbs=wine-extension-vbs.desktop;
```

This happened on my Fedora 32 machine with latest Lutris from system repository, after installing Halo Online that uses Wine with `--no-sandbox` switch.

**Comment by dawkot** [comment]
Annoyed me as well. These are obviously not the desktop files you can create/remove from the Lutris UI.

**Comment by amillette** [comment]
I had the same problem when installing Magic: The Gathering Arena on my Fedora 32 laptop. It created multiple .desktop files, mimetypes, icons inside my home directory. 

I was able to remove most of them by runnning these commands ([Wine FAQ](https://wiki.winehq.org/FAQ#How_do_I_clean_the_Open_With_List.3F)):

```
rm -f ~/.local/share/mime/packages/x-wine*
rm -f ~/.local/share/applications/wine-extension*
rm -f ~/.local/share/icons/hicolor/*/*/application-x-wine-extension*
rm -f ~/.local/share/mime/application/x-wine-extension*

rm -f ~/.config/menus/applications-merged/wine*
rm -rf ~/.local/share/applications/wine
rm -f ~/.local/share/desktop-directories/wine*
rm -f ~/.local/share/icons/????_*.{xpm,png}
rm -f ~/.local/share/icons/*-x-wine-*.{xpm,png} }}}
```
The only settings I found in Lutris is 'Create a sandbox for wine folders' in the runner advanced options but it was enable by default.

**Comment by AsciiWolf** [comment]
Workaround is to always use the Proton version of Wine. It has winemenubuilder disabled. :-)

**Comment by strycore** [comment]
it would be cool if the lutris builds also disabled winemenubuilder, that would solve the problem.

**Comment by amillette** [comment]
I have found a similar [issue](https://github.com/lutris/lutris/issues/2466) that seems to have a fix:

```
self.dll_overrides = {
    "winemenubuilder.exe": "d"
}
```

Should'nt It have prevent wine from creating those files ?

**Comment by AsciiWolf** [comment]
It just happened again! With _lutris-6.0-x86_64_ Wine version and wineprefix set to 32bit, after installing [ZDaemon](https://lutris.net/games/zdaemon/):

![screenshot](https://user-images.githubusercontent.com/2339930/112152652-cfcb2980-8be2-11eb-9a3d-9c890b636280.png)

Never had this issue when using official Proton version of Wine, but Lutris one constantly has this problem for years. :-/

**Comment by AsciiWolf** [comment]
It just happened again for another game. It seems to happen only with 32bit wineprefixes. 64bit prefixes work correctly.

**Comment by AsciiWolf** [comment]
And it just happened even when using 64bit wineprefix. :-(

![screenshot2](https://user-images.githubusercontent.com/2339930/112235521-1c445280-8c3f-11eb-8ad1-6267675a17bf.png)

**Comment by AsciiWolf** [comment]
```
$ ls -l /home/asciiwolf/.local/share/applications
total 44
-rw-r--r--. 1 asciiwolf asciiwolf    0 Jun  4  2020 mimeapps.list
-rw-r--r--. 1 asciiwolf asciiwolf  558 Mar 24 01:10 mimeinfo.cache
drwxr-xr-x. 3 asciiwolf asciiwolf 4096 Mar 24 01:17 wine
-rw-r--r--. 1 asciiwolf asciiwolf  301 Mar 24 01:10 wine-extension-application.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  312 Mar 24 01:10 wine-extension-appref-ms.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  276 Mar 24 01:07 wine-extension-chm.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  305 Mar 24 01:10 wine-extension-compositefont.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  278 Mar 24 01:07 wine-extension-hlp.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  299 Mar 24 01:07 wine-extension-msp.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  281 Mar 24 01:07 wine-extension-vbs.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  329 Mar 24 01:10 wine-extension-xaml.desktop
-rw-r--r--. 1 asciiwolf asciiwolf  322 Mar 24 01:10 wine-extension-xbap.desktop
```

**Comment by AsciiWolf** [comment]
I forgot to mention that both recent cases when this issue happened were using draft installers (using a "Test this installer" button from Lutris website). But I don't think that there is any diference between draft (test) installers and regular (published) ones...

**Comment by AsciiWolf** [comment]
It just happened again, this time on a clean, fully updated installation of Ubuntu 20.04 and World of Warcraft Classic installed using the official Lutris script with latest lutris-6.4-x86_64 Wine.

**Comment by AsciiWolf** [comment]
@strycore Please, consider disabling the winemenubuilder in Lutris Wine builds as @amillette suggested.

**Comment by amillette** [comment]
@AsciiWolf Which wine version are you using ? Since I am on Pop OS 21.04, I don't have this problem anymore. I think it may be related to the wine version or it's dependencies.

**Comment by AsciiWolf** [comment]
You mean the system Wine version or a Lutris one? I don't think this problem is caused by a system Wine, but it is version 5.0-3ubuntu1.

**Comment by amillette** [comment]
I installed World of Warcraft Classic using the official Lutris script and wasn't able to reproduce your issue.

Could you try installing Wine Staging (6.5) as showed in the documentation ? 
- [WineDependencies](https://github.com/lutris/docs/blob/master/WineDependencies.md)

Make sure you are using the latest version of Lutris (0.5.8.3).

**Comment by AsciiWolf** [comment]
I did not install any dependencies, only the ones required by the Lutris package itself. To be honest, I don't think that this is a problem. Both Battle.net launcher and WoW itself work fine without any external dependencies installed and this bug is hardly caused by it. It is clearly caused by the Lutris Wine running winemenubuilder although it should not. When I was using Lutris Wine builds based on Proton, I had no such issues because they all had winemenubuilder disabled.

**Comment by tannisroot** [comment]
I fixed this in Wine itself.

**Comment by AsciiWolf** [comment]
I just got the same issue again on Fedora 35 with Lutris 0.5.10-1 and lutris-fshack-7.2, this time when using "Install a Windows game from media" option (local .exe installer). Was this really fixed even for the fshack builds?

Also, ~/.wine was created for some reason (maybe a wrong WINEPREFIX was used at some point during the installation by Lutris?) and I got an "Game executable not found" (or similar) error when trying to launch the game after the installation.

**Comment by amillette** [comment]
Just tried with Fedora 36, Manjaro and OpenSuse Tumbleweed to see if the issue is distro related, but I can confirm it happening with all of them.  Some desktop entries are created in "/home/<user>/.local/share/applications/wine/Programs/*" for the game and sometime applications like Powershell. I used Lutris version 0.5.10.1 to reproduce the issue.

**Comment by AsciiWolf** [comment]
I had the same issue again when installing World of Warcraft. I have also noticed that during the Arial font installation task from [the installer](https://lutris.net/games/install/8505/view), there was a Wine dialog window displayed about the `~/.wine` prefix being configured (instead of the correct game prefix).
