### ISSUE TITLE
Support for xdg-desktop-portal

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2924]
**Describe the bug**

https://www.reddit.com/r/kde/comments/a5cxwk/firefox_v64_can_now_use_the_kde_file_selection/
Would be nice to have KDE file selection dialog.

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

Support this

**Current behavior**

Not supported............

**Steps to reproduce**

- Launch lutris.
- Cry in pillow after seeing gtk file dialog.

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by soredake** [comment]
https://gitlab.gnome.org/GNOME/gimp/-/issues/1830

**Comment by strycore** [comment]
https://github.com/flatpak/xdg-desktop-portal

**Comment by soredake** [comment]
https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser

**Comment by A6GibKm** [comment]
This does not require to use the portal directly, one can simply use [GtkFileChooserNative](https://docs.gtk.org/gtk3/class.FileChooserNative.html) instead of GtkFileChooser. Ill look into it.

**Comment by soredake** [comment]
@strycore i tried latest lutris from flathub-beta and it still used gtk file picker.

**Comment by A6GibKm** [comment]
All file choosers in lutris make use of the native one, if thats not working there is something wrong with your machine or you are in an older build. I suggest to report it to your distribution.
