### ISSUE TITLE
Lutris client should be able to add a game to my remote lutris.net library

### ISSUE THREAD

**Issue by Anarch157a** [lutris/lutris#2925]
**Describe the bug**

When I add a game or import a library (Say, from GOG), Lutris doesn't sync the added games with lutris.net. I have to manually click in "View on Lutris.net", then on the page click in "Add to my library",for each and every one of the games.

**Expected behavior**

There should be a button on Lutris Client to do that for me, something like "Add game to Lutris.net LIbrary".

**Current behavior**

There's no option to inform Lutris.net that I have the game in my local library

**Steps to reproduce**

- 

**Lutris debugging output**

not needed

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by xordspar0** [comment]
This is on the roadmap. I can't find an issue for it, but it's mentioned [in the README](https://github.com/lutris/lutris#planned-features). This would be a great feature, but it will take a lot of work. :slightly_smiling_face:

**Comment by strycore** [comment]
I don't think there's an open ticket about it but it was kinda always in the plans to have 2 way sync instead of the 1 way sync we have currently.

**Comment by strycore** [comment]
This feature will be tracked in #5299
