### ISSUE TITLE
Missing game cerberus

### ISSUE THREAD

**Issue by roppit** [lutris/lutris#2927]
Cerberus - Crowdsourcing en e-learning platform. Yesterday I installed Cerberus with Lutris. The (Windows Ios and Android) game works out of the box. I't a "sim city" like game with the use of real world maps. 

I wanted to register this game in Lutris so other linux players can also play it.
The developper has an website: https://www.blackshore.eu/
And a facebook page: https://www.facebook.com/cerberusgame

Hou do I (or you) rigister this game in Lutris? ( at the moment I cannot select the game developer at https://lutris.net/games/cerberus/suggest-changes)

**Comment by xordspar0** [comment]
You should click the "Write a new installer" link on the game page: https://lutris.net/games/cerberus

Not being able to select the game developer on the suggest changes page is a separate issue. Hopefully that will get added soon. There's an issue open for it here: https://github.com/lutris/website/issues/470

**Comment by xordspar0** [comment]
Or is this a completely different game than the arcade game you linked to with the same name? If it is a different game, then you should fill out the form for a new game here: https://lutris.net/games/add-game/

**Comment by strycore** [comment]
Closing this issue since instructions to create the game have been provided.
