### ISSUE TITLE
Switching Wine version to Proton breaks savegames

### ISSUE THREAD

**Issue by felschr** [lutris/lutris#2928]
Another issue reported by TomB on the forums:

>It’s great that Lutris lets you try proton as a wine version but it s a bit annoying that savegames, configuration and anything else in the documents directory is lost when switching between proton and another wine version.
>
>The problem is that proton uses the username steamuser and stores its files in `$GAMEDIR/drive_c/users/steamuser`. I doubt you can change Proton but it would be useful, when proton is selected, to symlink `$GAMEDIR/drive_c/users/steamuser` to `$GAMEDIR/drive_c/users/$USER` so that when switching to/from proton, you don’t need to copy the savegames and configuration files across.

_Originally posted by @AccountOneOff in https://github.com/lutris/lutris/issues/1381#issuecomment-443398357_

**Comment by tannisroot** [comment]
This is one of the reasons I think we should stop allowing people to switch to Proton as a wine version in Lutris @strycore. The other that I am aware of is that it breaks windows steam games due to swapping of steamclient calls to native lib.

**Comment by strycore** [comment]
We can possibly create a symlink during prefix creation to handle the 'steamuser' issue. 
It's useful to be able to use Proton inside Lutris. Installers never use Proton so when users enable it, they know what they're doing.

**Comment by tannisroot** [comment]
> Installers never use Proton so when users enable it, they know what they're doing.
Yeah that's the thing, they almost always don't. People complain about Proton breaking their prefix on Lutris' Reddit and Discord all the time. I suppose this is because people think that since Proton works so well with their Steam games, it will work just as well with their Lutris ones or somehow improve things, but that's not true whatsoever.

**Comment by tannisroot** [comment]
It is getting increasingly annoying to deal with users who break their prefixes by running it with Proton so I think this needs to be addressed sooner.

**Comment by strycore** [comment]
0.5.9 is the milestone where we're dealing with Steam/Proton related issues. For 0.5.8, I'm targeting UI changes and the merging of the file-picker branch.

**Comment by tannisroot** [comment]
Proton is not supported anymore so closing.
