### ISSUE TITLE
Gamepad misbehaving on wine for lutris

### ISSUE THREAD

**Issue by luismglvieira** [lutris/lutris#2930]
Hello. Today my gamepad (PS3 controller) started misbehaving on wine games.

The issue is that it's acting like I'm holding left, but running jstest /dev/input/js0 it seems like everything is fine, with a 0 input on idle... also antimicro is acting normal and gamecube emulator as well, seems like it's an issue only with wine games.

Important to know that I use different wineprefixes for each game, and I tried different games and it's happening everywhere... Also, I use lutris to run these games. I thought it was a recent update on my system but a timeshift didn't solve the issue...

When playing a wine game on steam, the issue doesn't happen and the controller works correctly. But wine games running through lutris are still broken.

`System:    Kernel: 5.4.28-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.3.0 
           Desktop: Xfce 4.14.2 Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: MSI model: B250M PRO-VD (MS-7A74) v: 1.0 serial: <filter> 
           UEFI: American Megatrends v: 1.A0 date: 02/27/2018 
CPU:       Topology: Quad Core model: Intel Core i7-7700 bits: 64 type: MT MCP arch: Kaby Lake rev: 9 
           L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 57616 
           Speed: 800 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 
           6: 800 7: 800 8: 800 
Graphics:  Device-1: Intel HD Graphics 630 vendor: Micro-Star MSI driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.8 driver: intel resolution: 1680x1050~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) v: 4.6 Mesa 19.3.5 
           direct render: Yes `

**Comment by strycore** [comment]
* Have you tried Wine games outside of Lutris (not proton, just the system installed one)
* Have you tried several Wine versions in Lutris? I think some recent builds had issues with input.

**Comment by luismglvieira** [comment]
Hello @strycore !
It's very weird, I can't find a consistent way to replicate this. This is happening in 3 games that I run on lutris, Tony Hawk's 4, Marc Ecko and Need for Speed Underground 2. I tried some of the different wine versions that I have on lutris, but these games only work on very specific wine versions for me, so I don't have much room to work with. I can't run them at all with wine outside lutris... the games just hang!

On another hand, I have some games on lutris that work fine, like Colin McRae 04 and Outrun 2006 (I don't have much games to try out outside of steam) these games even work on the same wine versions that the others don't ... which was a particular case with lutris-4.20, doesn't work with NFSU2 but works with Colin McRae. This is very strange and I don't know what to do. The best way would be to find a way to override the gamepad mapping with lutris, but I always just plugin and play the games by default and it's been working fine.

It's funny that this happened all of a sudden and I thought it was a Manjaro update, but a roll back didn't solve it.

**Comment by luismglvieira** [comment]
Hey. So this issue happens with Need for Speed Underground 1 as well. And by running the game through wine, I can't even use the gamepad at all... with lutris it connected immediately, but still turning left all times.

**Comment by tannisroot** [comment]
Can you reproduce the issue with regular wine and not our builds?

**Comment by legluondunet** [comment]
No answer from user, @strycore could you close this issue?
