### ISSUE TITLE
Lutris 0.5.6 on Fedora 32 wont open... probably after trying to install Epic Games

### ISSUE THREAD

**Issue by msmafra** [lutris/lutris#2933]
**Describe the bug**

Lutris (0.5.6) is not opening any more. I use Fedora 32 and it looks like it started when I tried to install Epic Games some weeks ago.
Even uninstalling, removing related files, and reinstalling did not solve it.

**Expected behavior**

Lutris to open its window.

**Current behavior**

It won't open.

**Steps to reproduce**

- Run lutris from a terminal or from the programs list.

**Lutris debugging output**

```
❯ lutris -d
INFO     2020-06-10 14:02:46,754 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-06-10 14:02:46,755 [startup.check_driver:54]:Using NVIDIA drivers 440.82 for x86_64
INFO     2020-06-10 14:02:46,755 [startup.check_driver:60]:GPU: GeForce GTX 1050
INFO     2020-06-10 14:02:46,755 [startup.check_driver:77]:GPU: 10DE:1C8D 1025:1128 using nvidia drivers
INFO     2020-06-10 14:02:46,755 [startup.check_driver:77]:GPU: 8086:591B 1025:1127 using i915 drivers
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/marcelo/.config/MangoHud/python3.8.conf [ not found ]
parsing config: /home/marcelo/.config/MangoHud/MangoHud.conf [ ok ]
INFO     2020-06-10 14:02:46,846 [startup.check_vulkan:132]:Vulkan is supported
[1]    101063 segmentation fault (core dumped)  lutris -d
```

**System information**

```
❯ lutris --submit-issue >> /tmp/lutris.json
2020-06-10 14:04:53,449: Running Lutris 0.5.6
2020-06-10 14:04:53,449: Using NVIDIA drivers 440.82 for x86_64
2020-06-10 14:04:53,449: GPU: GeForce GTX 1050
2020-06-10 14:04:53,450: GPU: 10DE:1C8D 1025:1128 using nvidia drivers
2020-06-10 14:04:53,450: GPU: 8086:591B 1025:1127 using i915 drivers
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/marcelo/.config/MangoHud/python3.8.conf [ not found ]
parsing config: /home/marcelo/.config/MangoHud/MangoHud.conf [ ok ]
2020-06-10 14:04:53,528: Vulkan is supported
[1]    101464 segmentation fault (core dumped)  lutris --submit-issue
```

**Screenshots**

![lutris-bug-report](https://user-images.githubusercontent.com/1005457/84298163-3264a480-ab3e-11ea-877d-4b81921716db.png)
![lutris-bug-report-2](https://user-images.githubusercontent.com/1005457/84298331-79529a00-ab3e-11ea-8808-f93594f69fb5.png)

**Comment by byte1024** [comment]
You're using mangohud. It is known to cause Lutris from starting. You should try to disable it.

You can search and find other issues about it. Possible duplicate.

**Comment by strycore** [comment]
I'm going to close this as a duplicate, yes.
