### ISSUE TITLE
Low resolution game icons displayed in GNOME

### ISSUE THREAD

**Issue by Mel34** [lutris/lutris#2934]
**Describe the bug**

Icons displayed in GNOME shell for entries created by "Create application menu shortcut" option are very low resolution. Please see attached screenshot.

**Expected behavior**

Icons displayed in GNOME shell for entries created by "Create application menu shortcut" option are high-rez and crisp like native ones.

**Current behavior**

Any menu entries icons created by Lutris using "Create application menu shortcut" use pixelated, low resolution icons, even if high resolution (256x256 png) is provided and set as an icon for the game. This can be observed on GNOME version 3.36.3

**Steps to reproduce**

- Use the "Create application menu shortcut" option in Lutris
- Open GNOME's applications list
- Observe low resolution icons on Lutris generated menu entries

**Lutris debugging output**

The terminal output of `lutris -d`.

```
~ ▶ lutris -d
INFO     2020-06-11 13:23:35,506 [application.do_command_line:245]:Running Lutris 0.5.6
INFO     2020-06-11 13:23:35,507 [startup.check_driver:62]:Using X.Org
INFO     2020-06-11 13:23:35,507 [startup.check_driver:64]:Running Mesa driver 20.1.1 on Radeon RX 580 Series (POLARIS10, DRM 3.37.0, 5.7.2-zen1-1-zen, LLVM 10.0.0) (0x67df)
INFO     2020-06-11 13:23:35,507 [startup.check_driver:77]:GPU: 1002:67DF 1DA2:E366 using amdgpu drivers
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
INFO     2020-06-11 13:23:35,534 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-06-11 13:23:35,534 [dxvk.get_dxvk_versions:22]:Updating DXVK versions
DEBUG    2020-06-11 13:23:35,740 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-06-11 13:23:35,741 [store.get_missing_media:212]:Requesting missing icons from API for slaps-and-beans, ftl, serious-sam-3
DEBUG    2020-06-11 13:23:35,745 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-06-11 13:23:35,901 [api.get_game_api_page:134]:No game found for slaps-and-beans, ftl, serious-sam-3
```
**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

```~ ▶ lutris --submit-issue
2020-06-11 13:24:18,827: Running Lutris 0.5.6
2020-06-11 13:24:18,828: Using X.Org
2020-06-11 13:24:18,828: Running Mesa driver 20.1.1 on Radeon RX 580 Series (POLARIS10, DRM 3.37.0, 5.7.2-zen1-1-zen, LLVM 10.0.0) (0x67df)
2020-06-11 13:24:18,828: GPU: 1002:67DF 1DA2:E366 using amdgpu drivers
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
2020-06-11 13:24:18,855: Vulkan is supported
2020-06-11 13:24:18,856: Updating DXVK versions
```

**Screenshots**

![Screenshot from 2020-06-11 13-15-47](https://user-images.githubusercontent.com/13254332/84379987-fa656c00-abe6-11ea-8898-b8507532cf26.png)

**Additional notes**

Possibly related:
`https://forums.lutris.net/t/application-menu-shortcut-with-very-low-resolution/6567`
`https://github.com/lutris/website/issues/333`

**Comment by soredake** [comment]
https://github.com/lutris/website/issues/424

**Comment by tannisroot** [comment]
This not a bug, at least not with the client. We support distribution of icons with the size up to 128x128, and some games actually provides icons in that resolution, the problem is obtaining them in that resolution or higher isn't possible for Steam games, at least to my knowledge.

**Comment by Mel34** [comment]
> This not a bug, at least not with the client. We support distribution of icons with the size up to 128x128, and some games actually provides icons in that resolution, the problem is obtaining them in that resolution or higher isn't possible for Steam games, at least to my knowledge.

I don't even have steam installed.
```
~ ▶ cat .local/share/applications/net.lutris.warframe-15.desktop 

[Desktop Entry]
Type=Application
Name=Warframe
Icon=lutris_warframe
Exec=lutris lutris:rungameid/15
Categories=Game
```
Icon is set by lutris, as you can see in the case of warframe.
![image](https://user-images.githubusercontent.com/13254332/88806316-8d1a9400-d1b0-11ea-95b1-1cc5365f9a6c.png)

These icons certainly were not set by me. Warframe was installed using the script provided at https://lutris.net/games/warframe/

I don't know why you assumed that this is a Steam related issue, but just for the sake of clarity, blurry icons were not installed via Steam.

**Comment by Mel34** [comment]
I've found a 800x800 px transparent PNG online to test with:
https://i7.pngguru.com/preview/336/423/824/warframe-logo-clan-emblem-warframe.jpg
![image](https://user-images.githubusercontent.com/13254332/88806954-6446ce80-d1b1-11ea-9d52-dc835f7fb9f0.png)

I've set the icon to that.
This was the result
![image](https://user-images.githubusercontent.com/13254332/88806916-585b0c80-d1b1-11ea-8632-1e8338c8049e.png)

So the icon gets set by lutris, and it gets re-dimensioned and it also loses it's transparency.

I'm requesting this bug be reoppened.

**Comment by tannisroot** [comment]
Please open a new bug report about this issue, as it has no connection with the issue you're describing in the bug report.
> I don't even have steam installed.
We get our icons from Steam's website, and they are only available in 32x32 resolution.

**Comment by Mel34** [comment]
> Please open a new bug report about this issue, as it has no connection with the issue you're describing in the bug report.

This is absurd.

> 
> > I don't even have steam installed.
> 
> We get our icons from Steam's website, and they are only available in 32x32 resolution.

I provided lutris with an 800x800 icon and it converted it to 32x32. I fail to see the reason to open another bug report.

I've manually edited out lutris' assigned icons and used high resolution ones, now I've got crisp icons in GNOME.
This can stay closed then, my issue is resolved and as you say there are no problems with the lutris client.

**Comment by tannisroot** [comment]
Ok, I think i misunderstood the original bug report due to the way it's worded.
As I understand, the original issue was all along about custom icons being resized weirdly even if they were high res originally, and not about our standard icons coming in low res. This is a valid bug report then.

**Comment by tannisroot** [comment]
I'm really not sure why we transform icons and banners when the user sets a custom one anyway. 
I think it would be much simpler to make no transformation whatsoever and just check whether the input image fits the criteria for an icon/banner (we could check whether the image is square and in png format for icons and whether it's the right pixel size for a banner).
