### ISSUE TITLE
Add metadata to installers

### ISSUE THREAD

**Issue by jimj316** [lutris/lutris#2937]
While writing installers for various games, I've run across a recurring problem; how to handle games where the executable changes it's name with each release, even though the install process stays the same. 

I see this a lot with portable executables; for instance, I'm currently writing an installer for the game MidBoss, which is distributed as a single executable file (currently) called "MidBoss-Linux-142-bin", but I've also sometimes seen executables inside archives having version numbers attached.

I'm not sure how to handle this with the installer; I can have the user select the executable and copy it to the game directory, but I'll have to hardcode the executable name for the chmodx command and for referencing the game executable, which will break once a new version of the game is released.

I can think of a couple of ways of fixing this: the easiest would be to add a "rename" command so that the executable can be renamed to a sensible constant (eg. "MidBoss"). The other way would be to allow the use of file ids for chmodx, and for the game executable.

**Comment by byte1024** [comment]
Could also attempt using the same name as before as it does now but if it fails then pop up a browse for executable dialog to the user in the last known location.

Shouldn't be renaming things the game provides. The script or Lutris should be dealing with it or devs need to stop doing it.

**Comment by YihaoPeng** [comment]
For now, you can consider writing a `.bat` script to find the executable file, and then start it by `cmd.exe /c your.bat`.

**Comment by strycore** [comment]
what if we add a `meta` section to installers that is a key value mapping? That way, we can have a VERSION meta field set to whatever the latest version of a game is. Then that field can be referenced in the script like: `chmodx: mygame${VERSION}.exe`

This could also make the installer submission process easier. A lot of submission we receive are just for bumping a version number so if we keep script metadata separated, it means less messing with installers.

We can also possibly let user modify the metadata field before the installation. That way, you can just install a new version of a game when you know it's available.

**Comment by strycore** [comment]
Closed in 0.5.9 
Installers now support a variable section for which the values are interpolated inside the script
