### ISSUE TITLE
Lutris Wine Bundle Getting Old

### ISSUE THREAD

**Issue by mpalermo73** [lutris/lutris#2938]
**Describe the bug**

Lutirs Wine Bundle Getting Old.  The version available in Lutris is 5.7.  WineHQ is on 5.10.  There has been a good deal of work done since 5.7 - most importantly major work on Vulkan bakend.  

**Expected behavior**

I "Manage Wine Versions" in Lutris UI expecting to see more current wine bundles

**Current behavior**

I "Manage Wine Versions" in Lutris UI and onlyh see old versions

**Steps to reproduce**

- Manage Wine Versions

**Lutris debugging output**

The terminal output of `lutris -d`.

The only output from "lutris -d" is a couple GTK warnings.  Nothing related to Lutris itself.

**System information**

[lutris-issue-report.json.txt](https://github.com/lutris/lutris/files/4774493/lutris-issue-report.json.txt)

**Screenshots**

![Screenshot_20200613_065756](https://user-images.githubusercontent.com/847259/84567178-e9327180-ad44-11ea-84f1-44d2b16c2fa3.png)

**Comment by hydrian** [comment]
I know wine 5.8 and 5.9 had regression issues. I think wine 5.10 is still going through testing.

**Comment by mpalermo73** [comment]
Oh!  I guess I wasn't aware there was show stopping issues with those versions.  My apologies for opening up this ticket.

**Comment by hydrian** [comment]
I happened to be in discord when they were talking about it.

**Comment by nifker** [comment]
When will we see newer versions of Wine?

**Comment by mpalermo73** [comment]
> When will we see newer versions of Wine?

For whatever it's worth, Manjaro recently updating wine-staging to 5.20.  I play World of Warcraft perfectly fine.

**Comment by nifker** [comment]
@mpalermo73 I thought lutris downloads the wine versions themself and just needs one from the distro. So I basically need to wait for my distro to update it?

**Comment by mpalermo73** [comment]
Lutris does offer precompiled specially patched versions of wine.  I'm saying that I gave up waiting for the Lutris version(s) and tried Manjaro's (Arch's) wine staging and it turns out it works great.  I did also ensure I installed all the Vulkan stuff locally.

**Comment by strycore** [comment]
@tannisroot I had a good experience with the lutris-5.20 build. Should we release it? Even if it is not made the default.
