### ISSUE TITLE
Lutris closes when attempting to log into GOG

### ISSUE THREAD

**Issue by Harpwind** [lutris/lutris#2956]
**Describe the bug**
When I attempt to connect to my gog account, it launches a second window (I assume a login window) and then promptly closes (both windows close).

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

Please describe the behavior you are expecting.

I assume a login window should appear allowing me to connect to my GOG account and allow me to select games to download.

**Current behavior**

What is the current behavior?
Lutris crashes

**Steps to reproduce**

- Launch Lutris from Gnome
-Click + button
Select "Import Games..."
Select GOG button on the left
Click "Connect  your account"
-

**Lutris debugging output**

The terminal output of `lutris -d`.

INFO     2020-06-20 18:27:31,947 [application.do_command_line:225]:Running Lutris 0.5.2.1
INFO     2020-06-20 18:27:31,947 [startup.check_driver:60]:Using nouveau
INFO     2020-06-20 18:27:31,947 [startup.check_driver:65]:Running Mesa driver 19.3.4 on NV134 (0x1b81)
INFO     2020-06-20 18:27:31,948 [startup.check_driver:75]:GPU: 10DE:1B81 1043:8599 using nouveau drivers
INFO     2020-06-20 18:27:32,027 [startup.check_vulkan:131]:Vulkan is not available or your system isn't Vulkan capable
Gtk-Message: 18:27:32.049: GtkDialog mapped without a transient parent. This is discouraged.
INFO     2020-06-20 18:27:34,876 [dxvk.get_dxvk_versions:24]:Updating DXVK versions
DEBUG    2020-06-20 18:27:35,051 [http.get:68]:GET https://lutris.net/api/runtime
DEBUG    2020-06-20 18:27:41,426 [gog.connect:253]:Connecting to GOG
Gtk-Message: 18:27:41.567: GtkDialog mapped without a transient parent. This is discouraged.
Gdk-Message: 18:27:42.814: Error 71 (Protocol error) dispatching to Wayland display.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

{
  "comment": "When I attempt to connect to my gog account, it launches a second window (I assume a login window) and then promptly closes (both windows close).",
  "system": {
    "gpus": [
      {
        "DRIVER": "nouveau",
        "PCI_ID": "10DE:1B81",
        "PCI_SUBSYS_ID": "1043:8599",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:01:00.0",
        "MODALIAS": "pci:v000010DEd00001B81sv00001043sd00008599bc03sc00i00"
      }
    ],
    "env": {
      "NVM_DIR": "/home/harpist/.nvm",
      "LS_COLORS": "rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:",
      "XDG_MENU_PREFIX": "gnome-",
      "LANG": "en_US.UTF-8",
      "GDM_LANG": "en_US.UTF-8",
      "HISTCONTROL": "ignoredups",
      "DISPLAY": ":0",
      "HOSTNAME": "Smaug.lan",
      "OLDPWD": "/home/harpist/lutris",
      "COLORTERM": "truecolor",
      "NVM_CD_FLAGS": "",
      "USERNAME": "harpist",
      "XDG_VTNR": "2",
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "XDG_SESSION_ID": "2",
      "USER": "harpist",
      "DESKTOP_SESSION": "gnome",
      "WAYLAND_DISPLAY": "wayland-0",
      "GNOME_TERMINAL_SCREEN": "/org/gnome/Terminal/screen/a5eff7d0_65f2_4c11_8720_a5357dd03f4b",
      "PWD": "/home/harpist/lutris/Lutris-RHEL-CentOS-8",
      "HOME": "/home/harpist",
      "XDG_SESSION_TYPE": "wayland",
      "XDG_DATA_DIRS": "/home/harpist/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/",
      "XDG_SESSION_DESKTOP": "gnome",
      "GJS_DEBUG_OUTPUT": "stderr",
      "MAIL": "/var/spool/mail/harpist",
      "VTE_VERSION": "5202",
      "TERM": "xterm-256color",
      "SHELL": "/bin/bash",
      "QT_IM_MODULE": "ibus",
      "XMODIFIERS": "@im=ibus",
      "NVM_BIN": "/home/harpist/.nvm/versions/node/v14.4.0/bin",
      "XDG_CURRENT_DESKTOP": "GNOME",
      "GNOME_TERMINAL_SERVICE": ":1.72",
      "XDG_SEAT": "seat0",
      "SHLVL": "2",
      "GDMSESSION": "gnome",
      "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
      "LOGNAME": "harpist",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "PATH": "/home/harpist/.local/bin:/home/harpist/bin:/home/harpist/.nvm/versions/node/v14.4.0/bin:/home/harpist/.local/bin:/home/harpist/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin",
      "NVM_INC": "/home/harpist/.nvm/versions/node/v14.4.0/include/node",
      "HISTSIZE": "1000",
      "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
      "SESSION_MANAGER": "local/unix:@/tmp/.ICE-unix/6139,unix/unix:/tmp/.ICE-unix/6139",
      "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
      "_": "/usr/bin/lutris"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [
          "libsqlite3.so.0"
        ],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "1512.500",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "16",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "1",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "2540.842",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "17",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "2",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "1982.240",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "2",
        "cpu cores": "4",
        "apicid": "18",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "3",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "2430.631",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "3",
        "cpu cores": "4",
        "apicid": "19",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "4",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "3581.910",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "4",
        "cpu cores": "4",
        "apicid": "20",
        "initial apicid": "4",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "5",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "2303.545",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "5",
        "cpu cores": "4",
        "apicid": "21",
        "initial apicid": "5",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "6",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "3538.696",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "6",
        "cpu cores": "4",
        "apicid": "22",
        "initial apicid": "6",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      },
      {
        "processor": "7",
        "vendor_id": "AuthenticAMD",
        "cpu family": "21",
        "model": "2",
        "model name": "AMD FX(tm)-8350 Eight-Core Processor",
        "stepping": "0",
        "microcode": "0x6000852",
        "cpu MHz": "3695.278",
        "cache size": "2048 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "7",
        "cpu cores": "4",
        "apicid": "23",
        "initial apicid": "7",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold",
        "bugs": "fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "8026.80",
        "TLB size": "1536 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "48 bits physical, 48 bits virtual",
        "power management": "ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro"
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "label": null,
            "uuid": "D288-5003",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "label": null,
            "uuid": "bd440536-2b9b-4fc8-930b-66a0140f05e4",
            "mountpoint": "/boot"
          },
          {
            "name": "sda3",
            "fstype": "LVM2_member",
            "label": null,
            "uuid": "2khlTg-C3an-ogAl-OGWc-kKLa-mK0b-0ZE0wf",
            "mountpoint": null,
            "children": [
              {
                "name": "cl-root",
                "fstype": "xfs",
                "label": null,
                "uuid": "6e5894a9-011e-4a37-a3ec-04e37b62f5a1",
                "mountpoint": "/"
              },
              {
                "name": "cl-swap",
                "fstype": "swap",
                "label": null,
                "uuid": "03a161dd-3b15-405b-958e-3ff2fa4c4364",
                "mountpoint": "[SWAP]"
              },
              {
                "name": "cl-home",
                "fstype": "xfs",
                "label": null,
                "uuid": "34d06d99-2881-417a-893f-1f59aad5f3cf",
                "mountpoint": "/home"
              }
            ]
          }
        ]
      },
      {
        "name": "sdb",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdb1",
            "fstype": null,
            "label": null,
            "uuid": null,
            "mountpoint": null
          },
          {
            "name": "sdb2",
            "fstype": "ntfs",
            "label": "New Volume",
            "uuid": "A058D03758D00E42",
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sdc",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdc1",
            "fstype": "vfat",
            "label": "TerabyteOne",
            "uuid": "CA7C-F6F1",
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sdd",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdd1",
            "fstype": "ext4",
            "label": "terabytetwo",
            "uuid": "879dea9b-a571-4060-b724-2854242fe7cc",
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sde",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sde1",
            "fstype": null,
            "label": null,
            "uuid": null,
            "mountpoint": null
          },
          {
            "name": "sde2",
            "fstype": "ntfs",
            "label": "Back Up Drive",
            "uuid": "F0EAF511EAF4D536",
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sdf",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdf1",
            "fstype": "ntfs",
            "label": "Recovery",
            "uuid": "FEECC1D7ECC189FB",
            "mountpoint": null
          },
          {
            "name": "sdf2",
            "fstype": "vfat",
            "label": null,
            "uuid": "9EC9-EBC9",
            "mountpoint": null
          },
          {
            "name": "sdf3",
            "fstype": null,
            "label": null,
            "uuid": null,
            "mountpoint": null
          },
          {
            "name": "sdf4",
            "fstype": "ntfs",
            "label": null,
            "uuid": "CCA0D28AA0D27B02",
            "mountpoint": null
          }
        ]
      },
      {
        "name": "sr0",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null
      }
    ],
    "ram": {
      "mem": {
        "total": "32665656",
        "used": "2284876",
        "free": "27878384",
        "shared": "216124",
        "buff/cache": "2502396",
        "available": "29718600"
      },
      "swap": {
        "total": "16482300",
        "used": "0",
        "free": "16482300"
      }
    },
    "dist": [
      "CentOS Linux",
      "8",
      "Core"
    ],
    "glxinfo": {
      "display": ":0",
      "name_of_display": ":0",
      "screen": "0",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 19.3.4",
      "opengl_core_profile_shading_language_version": "4.30",
      "direct_rendering": "Yes",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_context_flags": "(none)",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_vendor": "nouveau",
      "opengl_shading_language_version": "4.30",
      "opengl_core_profile_version": "4.3 (Core Profile) Mesa 19.3.4",
      "opengl_profile_mask": "compatibility profile",
      "opengl_version": "4.3 (Compatibility Profile) Mesa 19.3.4",
      "opengl_renderer": "NV134"
    }
  }
}

**Screenshots**

**Comment by strycore** [comment]
It looks like you're using Wayland on the nouveau driver, I don't know about the stability of that.

You should start with installing the Nvidia drivers since you have a model that is recent and might not function well with nouveau.

**Comment by Harpwind** [comment]
> It looks like you're using Wayland on the nouveau driver, I don't know about the stability of that.
> 
> You should start with installing the Nvidia drivers since you have a model that is recent and might not function well with nouveau.

Turns out nvidia and Wayland don't work well together, but the proprietary drivers don't work with Wayland.   For anyone else who has similiar trouble.

**Comment by strycore** [comment]
for Nvidia, I would recommend staying on X11 and using the proprietary drivers. Nouveau doesn't have the performance required to play games (or only basic ones)

**Comment by byte1024** [comment]
Actually, the Nvidia proprietary driver does work with Wayland now. It has to be enabled specially.

No real point in doing it however because of various problems with Wayland and also a few with Nvidia.

But it does work quite well otherwise.
