### ISSUE TITLE
Performance issues with 0.5.6

### ISSUE THREAD

**Issue by derbrachialist** [lutris/lutris#2957]
I have huge performance issues on Lutris 0.5.6 in world of warcraft.
My fps dropped from about 144 to 15.
I tried different versions of wine and dxvk, the only thing that worked was downgrading to 0.5.5.
It seems to be a cpu issue: https://imgur.com/a/B7Q8OwS
Lutris 0.5.6 only uses 1 core at a time and 0.5.5 uses all cores.

I have this problem since release of 0.5.6 and tested it again today.

**Comment by tannisroot** [comment]
That makes no sense, why would Lutris use so much of your CPU? Do you have logging enabled perhaps?

**Comment by strycore** [comment]
it's not Lutris using CPU, it's the game being single core restricted.
@derbrachialist did you enable "Run in single core" in the options by mistake?

**Comment by byte1024** [comment]
Looks to me that single core usage would show one core at 99% in the graph and the rest next to 0 but that's not what his graph shows.

Is it the same Wine version being used?

Could enabling eg heavy debugging in one Lutris version cause a major fps decrease or some other setting and not be carried over? I haven't tested that.

**Comment by derbrachialist** [comment]
here are the settings form .5.5 and .5.6 https://imgur.com/a/v8L5lbz
No single core restriction, same Wine versions.

**Comment by derbrachialist** [comment]
Solved by using DXVK 1.6 instead of 1.7

**Comment by byte1024** [comment]
Nice. Good find :-)
