### ISSUE TITLE
Lutris shows system wine when its not installed

### ISSUE THREAD

**Issue by byte1024** [lutris/lutris#2959]
**Describe the bug**

eg "$ sudo dnf remove wine"

Lutris will still show in the wine version selection drop down list "system (x.xx (staging))" leading to failed usage when said wine version is selected.

eg "wldap32.dll" cannot be found upon running an application/game leading to more confusion eg trying to install a missing libldap 32 bit/i686 when in fact actually needing to run "$ sudo dnf install wine".

After installing wine, application/game using system wine then works when previously it failed.

**Expected behavior**

System wine should not be included in the drop down list as its not actually installed.

**Current behavior**

System wine shows up in the list and games/applications fail to start because its not really installed.

**Steps to reproduce**

Maybe:

1) "$ sudo dnf remove wine"

2) Start Lutris and check wine version drop down list.

**System information**

Fedora 32
Lutris 0.5.6

**Comment by hydrian** [comment]
@byte1024 Lutris will download and install the wine version a game needs inside the $GAMEDIR if a game needs wine. It usually doesn't rely on the distro version of wine which is often customized and old.

**Comment by byte1024** [comment]
Whatever it is, it doesn't do that here.

It updates the version but everything fails until $ dnf install wine.

Could be that whatever Lutris does is missing a dependency that $ sudo dnf wine installs however. I didn't look into that.

So its one or the other. Shouldn't have to install distro wine to get all dependencies through and it shouldn't break when removing distro wine.

**Comment by strycore** [comment]
Did you restart Lutris after removing wine?

**Comment by hydrian** [comment]
Also, check the installer script. Do you have janky installer script?

**Comment by byte1024** [comment]
Yes, Lutris has been this way from me since using it as far as I can remember so it has been restarted a lot :-) I only just now looked into it further.

There's no installer script. Just switch an already installed application/game to system wine or import a game using system wine and it fails to start until after installing distro wine and after removing distro wine.

Will try to see if I can find something else to report.

**Comment by byte1024** [comment]
Well, that didn't take long.

So it looks like maybe the real issue is ldap missing and removing wine shows it as an unused dependency?

This actually fixes the issue without needing to install distro wine:

`$ sudo dnf install wine-ldap`

Removing distro wine shows:

```
Removing unused dependencies:
...
 wine-ldap                      i686       5.10-1.fc32       @updates     382 k
 wine-ldap                      x86_64     5.10-1.fc32       @updates     449 k
...
```

I don't know ldap is supposed to come from somewhere else with Lutris system wine use. I wasn't previously able to get any ldap working until doing it exactly as distro wine does it just now.

Using Lutris system wine without wine-ldap results in:

`00c8:err:module:import_dll Library WLDAP32.dll (which is needed by [redacted exe and path]) not found`

Said exe doesn't require the 32 bit ldap so its not that kind of an issue.

**Comment by hydrian** [comment]
Now I'm curious. What is using with Lutris, wine, and LDAP? I do lots with LDAP in my daily life.

**Comment by byte1024** [comment]
> Now I'm curious. What is using with Lutris, wine, and LDAP? I do lots with LDAP in my daily life.

Redacted it just because that's my preference at times.

Recent temporary game demo on steam which was part of the indie event and still works for those that have it /path/Relicta Demo/Relicta.exe

I see

Lutris install doc recommends installing wine:


https://github.com/lutris/lutris/blob/314bcabedd5f8a13181dab718fffbf46fcb9cb83/INSTALL.rst

**Comment by byte1024** [comment]
> Now I'm curious. What is using with Lutris, wine, and LDAP? I do lots with LDAP in my daily life.

Redacted it just because that's my preference at times.

Recent temporary game demo on steam which was part of the indie event and still works for those that have it /path/Relicta Demo/Relicta.exe

I see that the Lutris install doc recommends installing wine for this reason so have closed this issue:

`Wine (not actually needed, but installing it is the easiest way to get all the libraries missing from our runtime).`

https://github.com/lutris/lutris/blob/314bcabedd5f8a13181dab718fffbf46fcb9cb83/INSTALL.rst

Seems to be a bit backward to me as I still would expect Lutris providing wine to make sure it has everything but I guess that's how it is.

**Comment by byte1024** [comment]
Indeed happens with everything.

`0200:err:module:import_dll Library WLDAP32.dll (which is needed by L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win64\\EpicGamesLauncher.exe") not found`

Its not just one application/game but all on Fedora 32 for me.

**Comment by byte1024** [comment]
Fedora 32 also needs wine-alsa and wine-pulseaudio 64 bit (plus 32 bit if playing an older game) with Lutris

**Comment by GloriousEggroll** [comment]
dude none of this is lutris's issue. the issue you're facing has to do with not installing all of the native wine dependencies required for wine on fedora, per the standard wine documentation.

lutris is not responsible for you not installing your packages properly per the documentation provided by winehq:

https://wiki.winehq.org/Fedora
