### ISSUE TITLE
3ds max

### ISSUE THREAD

**Issue by kregan96** [lutris/lutris#2965]
@
i want to download 3ds max 2021 please make it compatible linux pls for lutris you are better lutris

**Comment by byte1024** [comment]
Wine issue, not Lutris. You're probably looking for a small miracle anyway lol.

**Comment by strycore** [comment]
First step on getting it to work is figuring out why it's not.
Do you have any logs to show?

**Comment by byte1024** [comment]
To add more to it if the issue creator doesn't:

3D Studio Max has a long history of being borked with Wine https://appdb.winehq.org/objectManager.php?sClass=application&iId=343

Lutris could alternatively add in installing Windows into a VM or something like that as I don't think it does that right? And then 3D Studio Max could be installed there as soon as VM usage is working.

But, of course, the issue creator could have it working today by using Virtual box or something and then buying a $10 or $15 legit Windows key and using that on Linux. Yes, Windows is involved and I know some people have a pine cone up their butt about that.

**Comment by strycore** [comment]
That's jumping through a lot of hoops just not to have to use Blender...

**Comment by byte1024** [comment]
> That's jumping through a lot of hoops just not to have to use Blender...

I agree, just use blender though I'm sure some people can't for whatever reason.

It would be interesting though if the fixes are simple here with how long wine has been in development and how well it works considering.

But, I'm not hopeful about it same as with some other applications.

If its as bad as windows media support has been, it would be quite bad.

**Comment by tannisroot** [comment]
this is not a valid issue, and yes Blender is a thing.
