### ISSUE TITLE
Installation fails - GPG key unavailable

### ISSUE THREAD

**Issue by edifus** [lutris/lutris#2974]
**Describe the issue**

Cannot locate Lutris GPG key to install from Ubuntu keyserver
http://keyserver.ubuntu.com/pks/lookup?search=82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4&fingerprint=on&op=index

Installation hangs adding PPA GPG key, key in question doesn't exist when you do a search from keyserver.ubuntu.com-
sudo add-apt-repository ppa:lutris-team/lutris
You are about to add the following PPA:
 Stable releases for the Lutris client
 More info: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.XyQf9Ca4JB/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4

**Expected behavior**

GPG key to be available for installation

**Current behavior**

Installation hangs adding PPA. Trying to manually add APT source and install key (sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4) also fails. Searching Ubuntu keyserver through HTTPS web page, and the key is not found. Checked from multiple locations and different networks to confirm not being blocked. Error from keyserver - Not Found.

**Comment by byte1024** [comment]
The keyserver is here and exists: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4

Missing a 0x in front of the 82 with your top link there.

Personally though I can't tell what's happening now lol. I'm not sure I see a problem with what you posted as an issue. Maybe the Lutris devs will see something as I don't? *puzzled and confused*

**Comment by edifus** [comment]
The link you provided works and shows a result (I was simply searching for the key from CLI output when adding the PPA), but adding PPA and/or adding key using apt-key still fails. Adding the PPA results in the import of their GPG key, but that hangs on the Ubuntu keyserver like I stated above. The line showing "Executing: /tmp/apt-key=gpghome....." is where everything hangs. Same issue running apt-key manually. I can add other keys from keyserver.ubuntu.com

I've connected from phone hotspot, through home network and from work network this morning. Pretty sure it's not a network issue from my end. Especially when the link you provided is working and keyserver.ubuntu.com is accessible from my end. I would be willing to concede that my work network is not the best place to test since we do a lot of content filtering, but I'm the network admin here and know what's allowed and not allowed. Even added keyserver.ubuntu.com to the WSA bypass with no change and logs show all traffic being allowed from my client. And this is after trying to install from my home network and also connecting to phone hotspot as another test.

The output from adding PPA was included above, there's issues accessing the GPG key and installing it-
```
$ sudo add-apt-repository ppa:lutris-team/lutris
You are about to add the following PPA:
 Stable releases for the Lutris client
 More info: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.XyQf9Ca4JB/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
^C

gpg: signal Interrupt caught ... exiting
```



Manually trying to install the key using apt-key also fails, I had to Ctrl+C after 30 minutes because it just sits here (same as above)
```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
Executing: /tmp/apt-key-gpghome.yloNVyO6hX/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
^C
gpg: signal Interrupt caught ... exiting
```

Is there a key file published somewhere that can be manually downloaded and installed?
Something like-
```
wget -O - https://somewhere.to.download.com/lutris.key  | sudo apt-key add -
```

**Comment by edifus** [comment]
Just a follow up. Got a friends PC to help me out. Exported the key from his installation to a separate file and was able to import manually.

```
$ sudo apt-key export 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4 > lutris.key
<xfer>
$ sudo apt-key add lutris.key
```

**Comment by byte1024** [comment]
Are there any new gpg versions for your distro?

From what I can see this looks to be the real problem:

`gpg: signal Interrupt caught ... exiting`

You can force this to happen by starting gpg eg "$ gpg" then ctrl+c exiting. So it looks like gpg is crashing unless you're resting your hand on the ctrl & c keys and I'm sure you're not :-)

The launchpad stuff is auto generated on upload and looks like there's only a problem on Lutris side if a build fails. Though they have builds already. Maybe they can see something else we can't on this side. But, I suspect its not on their side.

I will test it on my laptop Ubuntu's install right now. If it fails will update. No update in an hour or less from this post and you can be assured it is working. If something like that works for one, it should be working for all.

**Comment by edifus** [comment]
As I stated in my previous messages, yes I have to Ctrl+C to kill the
process because it gets stuck and never advances (left it for 30 minutes) -
IT NEVER RETRIEVES THE LUTRIS GPG KEY FROM UBUNTU KEYSERVER. It's not
retrievable using "add-apt-repository" or through "apt-key adv" like I
stated before. I can install other keys just fine from Ubuntu keyserver. I
have been reinstalling software all day on my laptop with a fresh install
of Linux Mint 20. It's not an issue from my end.

But as I also stated, this is resolved by exporting the key from another
machine and manually importing that exported key.

**Comment by byte1024** [comment]
I tested it and it works so don't know what else to tell you.

It's going to be the same generated stuff for everyone which should be a local issue (OS related) regardless of if it works for everything else.

Also Lutris its launchpad that probably should deal with it as they auto generate what you get for adding a ppa here.

Maybe the Lutris devs can notice something but I would be surprised if there's anything.
