### ISSUE TITLE
auto/manual-deletion of old unavailable runners version

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2986]
**Describe the bug**

For example, i now have 2 old unavailable wine runner versions:
![image](https://user-images.githubusercontent.com/5204968/86379674-cf28e680-bc93-11ea-9c94-5601aae1201b.png)

Would be nice to have to have button to delete them, or have lutris delete them automatically.

**Expected behavior**

Have this functionality.

**Current behavior**

No functionality.

**Steps to reproduce**

- Start lutris.
- Download wine runner.
- Wait for runner to be updated.

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/4865322/lutris-issue-report.zip)

**Screenshots**

See above.

**Comment by strycore** [comment]
We're not going to start randomly deleting stuff. The Wine download dialog now shows how many games are using a wine build and you can just uncheck those not in use.
