### ISSUE TITLE
Melonds (JSON based)

### ISSUE THREAD

**Issue by QuintusNX** [lutris/lutris#2988]
Why not a melonds runner ?
It's (for me) a much better emulator than desmume

**Comment by soredake** [comment]
You can use libreto runner and choose melonds core.

**Comment by QuintusNX** [comment]
The libretro core have really less functions and optimisations than the real runner.
The only reason to stay with desmume i see pertinant is cheats, but they are planed in melonds too

**Comment by soredake** [comment]
What functions? What optimizations?

**Comment by strycore** [comment]
if it's a simple emulator, a JSON based runner is possible
