### ISSUE TITLE
Vortex Mod Manager doesn't run from Lutris

### ISSUE THREAD

**Issue by DGSZink** [lutris/lutris#2993]
I installed Vortex Mod Manager 1.2.17 using Wine 5.12 in the default ~/.wine prefix, then I opened it from it's location in "Program Files/Black Tree Gaming Ltd/Vortex" since I remembered it having an issue where it wouldn't start after an install and would only open the first time since it automatically starts after an install. (so I closed it after it opened on the install finish, and started it again)

That problem isn't present and it starts up without any problems.

Then I copied that prefix over in a place where I usually keep Lutris prefixes (I have Lutris 0.5.7 currently) , added it through the "Add Game" option, added the prefix path and set the runner to "System (5.12 (staging))" (the same one I used the first time), and then clicked "Play" but it wouldn't start.

I tried making brand new prefixes, or using different Wine versions (even though the one installed system-wide should have worked, and started up fine without Lutris) but to no avail.

Here's a log:
[lutris_vortex_error.txt](https://github.com/lutris/lutris/files/4875909/lutris_vortex_error.txt)

And another one:
[lutris_d_vortex_error.txt](https://github.com/lutris/lutris/files/4879794/lutris_d_vortex_error.txt)

I don't think this is a Wine or Vortex issue because it starts up fine without Lutris and it's just when you start it through Lutris that the problem appears.

**Comment by strycore** [comment]
I tried updating the version of Vortex but this caused the program to crash as you experienced.
I downgraded to it's original version and I've had reports that it is working normally again.

**Comment by DGSZink** [comment]
As I mentioned, the LATEST version works with systems Wine version without Lutris, just not when using Lutris.
It's true an older version of Vortex still works with Lutris, doesn't change the fact that newer versions don't work with it, yet still work with standalone Wine.

**Comment by AlexanderRavenheart** [comment]
From the log output I noticed you have DXVK enabled in Lutris for this app. Can you try disabling it, run the app again and post the new debug output?

**Comment by DGSZink** [comment]
[lutris_log_no_dxvk1.txt](https://github.com/lutris/lutris/files/4949631/lutris_log_no_dxvk1.txt)
[lutris_log_no_dxvk2.txt](https://github.com/lutris/lutris/files/4949632/lutris_log_no_dxvk2.txt)
[lutris_log_no_runtime1.txt](https://github.com/lutris/lutris/files/4949633/lutris_log_no_runtime1.txt)
[lutris_log_no_runtime2.txt](https://github.com/lutris/lutris/files/4949634/lutris_log_no_runtime2.txt)

Disabled DXVK for the first two, disabled DXVK and the Lutris Runtime for the other two.
I have no environment variable added manually.
