### ISSUE TITLE
After the Lutris update, no games start.

### ISSUE THREAD

**Issue by Mo0nCake** [lutris/lutris#2994]
On the previous version 0.5.6, all games were launched.
After updating Lutris to version 0.5.7-1, **not a single game starts if "Disable desktop effects" is enabled in preference**
Here is what the console writes. **FileNotFoundError: [Errno 2] No such file or directory: 'qdbus'**
Archlinux.
python-dbus is installed
![image](https://user-images.githubusercontent.com/67700024/86579374-e878ae00-bf85-11ea-9528-60aeeb460fca.png)

**Comment by connectety** [comment]
Before toggling compositing, lutris checks if it's enabled.
To do this lutris on Plasma runs: `qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active`
On your system, the `qdbus` command (QTs DBus command) is not found.

I am not sure this is **SOLELY** lutris problem.
I would create a fix tho, once I figure out what to do instead. (The maintainer would of course have to accept it).

**Comment by byte1024** [comment]
The code was recently changed for 5.7 there. Probably an unforeseen problem. That's how it goes.

**Comment by connectety** [comment]
In lutris 5.6, there was no check if compositing was enabled.
But `qdbus` still was used to enable and disable compositing.

**Comment by byte1024** [comment]
> I think its unlikely that this is a lutris problem.
> 
> In lutris 5.6, there was no check if compositing was enabled.
> But `qdbus` still was used to enable and disable compositing on plasma.
> 
> It could of course be that the desktop-environment was not properly detected and nothing was done anyway.
> (There was a change that `DESKTOP_SESSION` does not have to match perfectly, it only has to end with "plasma").

My bad. I originally read what you typed as it as probably being with Lutris but now I read it again and that's not quite what you said lol.

Considering the amount of code changes there in Lutris 5.7 I would personally assume Lutris since it worked the version before so. It is possible yes (I won't argue that it isn't with this) that Lutris does something good and finds a problem with the user's system or packages on the system.

**Comment by strycore** [comment]
The qdbus program is provided by the `qtchooser` package if you want to install it and workaround the issue.
