### ISSUE TITLE
Max C: drive size

### ISSUE THREAD

**Issue by Chidhambararajan** [lutris/lutris#2995]
I don't know why , but due to some reason , my all my lutris instances have a max disk capacity of 53GB how do i fix this?
I can't install larger games.. My hard disk free space is 600GB

**Comment by Chidhambararajan** [comment]
never mind it was a minor glitch , got rectified on restart.. why don't you guys think about extending support to softwares other than games too

**Comment by strycore** [comment]
well…  https://lutris.net/games/microsoft-excel/
