### ISSUE TITLE
Unable to confirm my email address

### ISSUE THREAD

**Issue by FieryCod** [lutris/lutris#3016]
**Describe the bug**
After clicking on _Send validation link_ on profile section the email is not sent to me. Could you please investigate what might be the cause? My mail is ****@tuta.io

**Expected behavior**
Should be able to validate email address.

**Current behavior**

Unable to validate the email address, therefore unable to contribute to lutris formulas.

**Steps to reproduce**
1. Visit the site
2. Go to profile
3. Click on _Send validation link_
4. Check your mail both spam & trash

There will be no mail.

**Comment by byte1024** [comment]
Recently, I tore though my own email for sending and receiving and there's so many potential issues both ways.

Frankly, I wouldn't blame their side first.

At least for what I use for receiving, there's a tool that shows when an email was received by the mail server and therefore if it's delayed before being received or even going missing after from eg stronger spam detection where the email is discarded. This would be handy here on your side though you may not have access to something like that.

It is possible they have some situation, but in general and as long as emails are sending, the email should still go through and then show up in spam.

Though I have seen my emails not showing for someone before when they show for others using the same mail servers.

Its really complicated today as there's a lot of possible stuff happening in the background.

**Comment by strycore** [comment]
I've stopped using my personal mail server and switched to SendGrid during the last server migration. Anything email related should be a lot more stable than it once was.
I deactivated the trackers from SendGrid for obvious reasons so that makes it harder to troubleshoot this type of issue. I'll see if I can find something though.

**Comment by strycore** [comment]
```Recipient address rejected: Sender ip blocked by:ix.dnsbl.manitu.net see: Your e-mail service was detected by mx-ha.web.de (NiX Spam) as spamming at Mon, 13 Jul 2020 16:39:45 +0200. Your admin should visit http://www.dnsbl.manitu.net/lookup.php?value=167.89.100.245```

Some dumbass thought it was a good idea to put the SendGrid IP, used by thousands of different services in a DNS blocklist.
SendGrid has strong policies in place against spamming. However, they may have realized their mistake because the IP is not found on the given link. I believe it has been removed already.

@FieryCod you can give it another try, and if you still don't find the email, do you have another email address you can use to registration?

**Comment by byte1024** [comment]
Would it be possible to add in alternative authentication here?

I understand there desire to authenticate via email but adding in an alternative would easily workaround potential issues such as a block.

**Comment by strycore** [comment]
Hm, maybe we could have some kind of user confirmation via Discord too? Plus it would give us a reason to work on tighter Discord integration

**Comment by strycore** [comment]
Or we could add a "Log in with Steam" and use Steam's OpenID system for user creation. The good thing is that we already have the code for Steam OpenID.

**Comment by FieryCod** [comment]
Yay! Finally confirmed the e-mail address. Thank you very much!

**Comment by tkalfaoglu** [comment]
Interesting -- I am unable to confirm my email address as well on Lutris forums.. 
It apparently sent me a confirmation email ONCE when I registered, and there appears to be no way to ask it to send another confirmation email, ever!

**Comment by strycore** [comment]
The registration to the lutris forums is done on the website side, confirming your email on the forums isn't needed.

**Comment by tkalfaoglu** [comment]
Unfortunately I don't see that.. I am logged into Lutris.net, I even synced my games with Steam.
Then I clicked the Forum link and there is a LOGIN button in the upper corner..  When I click that Login, it tells me that "You must confirm the email link" , with no other thing on the page.
This is Fedora 36, Firefox, mostly default settings.

**Comment by tkalfaoglu** [comment]
Thanks! I found the email confirm link in the "Account" page and just did that.. Sorry for not seeing it earlier.
