### ISSUE TITLE
setup.py does not install lutris/runners/json/

### ISSUE THREAD

**Issue by Jan200101** [lutris/lutris#3017]
**Describe the bug**

installing lutris by manually installing it over setup.py results in the json directory not being installed and being unable to start lutris

**Expected behavior**

It just works

**Current behavior**

lutris will not start because it is unable to walk through a directory

**Steps to reproduce**

- install lutris using `python3 setup.py install` (use --root to install into a test folder)
- find json directory missing

**Screenshots**

![image](https://user-images.githubusercontent.com/15076013/87341834-8d792500-c54a-11ea-838d-e41a7adf6d7a.png)

**Comment by strycore** [comment]
I haven't managed to reproduce this but I'm going to move the JSON files from the Python code anyway. This is not a correct location for them.
