### ISSUE TITLE
internal winetricks broken?

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#302]
the internal winetricks script fails on complex tasks like installing .net for example:

''''
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "dotnet35"
      }
    },
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "dotnet35sp1"
      }
    }
''''

**Comment by strycore** [comment]
What game is this? I haven't noticed such issues with Winetricks.

**Comment by sixsixfive** [comment]
the game currently doesnt exist(I just tried to install the GOGDownloader with lutris -i )

```
{
  "files": [
    {
      "downloader": "http://static.gog.com/download/d3/stable/Setup_Downloader_3.6.0_stable.exe"
    }
  ], 
  "exe": "", 
  "runner": "wine", 
  "installer_slug": "test-gog",
  "game_slug": "test",
  "version": "GOG",
  "year": 2014,
  "installer": [
    {
      "task": {
        "name": "create_prefix",
        "prefix": "$GAMEDIR",
        "arch": "win32"
      }
    },
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "dotnet35"
      }
    },
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "dotnet35sp1"
      }
    },
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "windowscodecs"
      }
    },
    {
      "task": {
        "prefix": "$GAMEDIR",
        "args": "", 
        "executable": "downloader",
        "name": "wineexec"
      }
    }
  ],
  "slug": "test-gog",
  "name": "TEST"
}
```

>  I haven't noticed such issues with Winetricks.

easy tasks like setting the winever or installing a dll worked for me, too. I guess winetricks hangs because no one accepted the eula(running in quiet mode)

**Comment by RobLoach** [comment]
I think you can combine those winetricks tasks...

``` json

    },
    {
      "task": {
        "name": "winetricks",
        "prefix": "$GAMEDIR",
        "app": "dotnet35 dotnet35sp1 windowscodecs"
      }
    }
```

**Comment by sixsixfive** [comment]
yeah i did this first, but it failed so i created one task for each to see which one failed

**Comment by RobLoach** [comment]
Hmm, interesting. Do you have a link to the game on lutris.net? I could try it out.

**Comment by sixsixfive** [comment]
as said the game dosnt exist, you need to save the above json file and try it with 

    lutris --debug -i <JSONFILE>

**Comment by RobLoach** [comment]
Added the entry in Lutris and made some tweaks:
https://lutris.net/games/gog-downloader/

Please test! :+1:

**Comment by sixsixfive** [comment]
no, its still hanging at installing game data..., also even if it would install fine I probably couldnt launch it since you changed the wine arch to 64bit...

**Comment by strycore** [comment]
I've made a few changes like setting the Wine version to use a 64bit build, downloading netframework3 and adding descriptions on tasks.

Seems to be stuck on the .NET 3.5 install.

**Comment by strycore** [comment]
I removed the globally installed winetricks so lutris would use its own copy and it work (installing .NET 3.5  still take a few minutes but that's expected). 

I'll remove the part were we use the global winetricks if it's found so we rely on a tested version.

**Comment by strycore** [comment]
GOG downloader itself does not work but that's a totally different issue (and a very low priority one).

**Comment by Xodetaetl** [comment]
If it doesn't work, shouldn't the installer be unpublished? :S

**Comment by strycore** [comment]
No, we have installer ratings now. I forgot to rate it as Garbage but I'll do it right now.

**Comment by sixsixfive** [comment]
>GOG downloader itself does not work but that's a totally different issue (and a very low priority one).

well, it works in a clean wineprefix(and without lutris)

anyway lutris and wine is still not working here with the latest lutris git

for example i tried: https://lutris.net/games/raiden-iii - everything works until lutris calls winetricks to install the d3d9 dll. then it hangs and winetricks becomes a zombie.

![screenshot_20160703_184411](https://cloud.githubusercontent.com/assets/3780774/16546538/3c124586-414e-11e6-9dcb-77b92bdfdf57.png)

here is a log:

[log.txt](https://github.com/lutris/lutris/files/345178/log.txt)

**Comment by sixsixfive** [comment]
apparently installing psmisc fixed all my winetricks issues - so you should add it to the debs depends field...

**Comment by strycore** [comment]
Fair enough, there's a bunch of very common packages that depend on it so it's one pf those packages I'd just assume everyone got installed.

**Comment by strycore** [comment]
Well, duh! It provides fuser, which we use to monitor wine processes, no wonder it wasn't working. Of course I'll add it as a dependency!

**Comment by sixsixfive** [comment]
also there is still an issue for me since lutris calls winetricks in quiet mode wich won't work for apps that have an EULA screen 

for example: https://lutris.net/games/install/2274/view

.net and xna with lutris will never install, if I execute 

```
curl -s https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks | WINEPREFIX=$HOME/Games/revolver360-reactor bash -s xna40 dotnet40
```

it will work and install fine
