### ISSUE TITLE
Top Bar game launcher

### ISSUE THREAD

**Issue by RPGHank** [lutris/lutris#3023]
I would like to have the ability to launch games from the top bar similar to how Steam and Itch apps implement it

**Comment by strycore** [comment]
the top bar of the lutris client or your Dekstop?

**Comment by RPGHank** [comment]
Desktop
Sorry for the late response

**Comment by strycore** [comment]
Like that?
![Screenshot from 2020-07-26 10-28-37](https://user-images.githubusercontent.com/280336/88485482-e2de0a80-cf2a-11ea-8bdc-2c6dbdc72136.png)

**Comment by RPGHank** [comment]
Yes
Was this option already there?

**Comment by f3ck4r** [comment]
> Yes
> Was this option already there?

yeah!

**Comment by RPGHank** [comment]
oh

**Comment by strycore** [comment]
Be sure to check your Gnome Shell extensions or other AppIndicator related libraries if the icon doesn't show up.
