### ISSUE TITLE
Installation fails - E: Package 'python3-distro' has no installation candidate

### ISSUE THREAD

**Issue by shelagh-lewins-ucl** [lutris/lutris#3025]
**Describe the bug**

I can't install Lutris on Linux Mint 18.1 Cinnamon 64-bit.

**Expected behavior**

I should be able to install Lutris.

**Current behavior**

Installation fails with the error: E: Package 'python3-distro' has no installation candidate

**Steps to reproduce**

I'm running Linux Mint 18.1 Cinnamon 64-bit.
I'm following the instructions for Debian on the downloads page:
https://lutris.net/downloads/

```
echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get install lutris
```

**Comment by strycore** [comment]
Please use the Launchpad PPA instead, you should get better results from there: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris

Reopen the ticket if using launchpad does not resolve your issue

**Comment by shelagh-lewins-ucl** [comment]
I guess after doing this:

```
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt-get update
```

I should be able to install Lutris through the Software Manager?

Unfortunately, if I open the Software Manager, search for Lutris and click "Install", a progress bar runs briefly at the bottom of the dialog but then the Software Manager just sits there saying "not installed". There is no error or feedback or further action.

Can you suggest any way to install Lutris?

**Comment by shelagh-lewins-ucl** [comment]
BTW I can't see a way to reopen the ticket? Maybe you would need to do that?

**Comment by AlexanderRavenheart** [comment]
Please run `sudo apt-get install lutris` from terminal and post what output you get.

**Comment by shelagh-lewins-ucl** [comment]
The following packages have unmet dependencies.
 lutris : Depends: python3-distro but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by AlexanderRavenheart** [comment]
Run `sudo apt-get upgrade` followed by `sudo apt-get install python3-distro` and post the output.

**Comment by shelagh-lewins-ucl** [comment]
```
sudo apt-get install python3-distro
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-distro is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-distro' has no installation candidate
```

**Comment by AlexanderRavenheart** [comment]
What is the output of `apt-cache search python3-distro`?

**Comment by shelagh-lewins-ucl** [comment]
`python3-distro-info - information about distributions' releases (Python 3 module)`

**Comment by AlexanderRavenheart** [comment]
Okay, based on what info I managed to gather it seems the python3-distro package is only available in Ubuntu 18.04 or higher, so you would have to upgrade to at least Linux Mint 19 (if you want to keep Linux Mint). I couldn't find any deb package that would be compatible with Linux Mint 18.x.

**Comment by strycore** [comment]
the distro package should not be a requirement in the latest version of lutris

**Comment by AlexanderRavenheart** [comment]
![Screenshot from 2020-07-20 21-39-16](https://user-images.githubusercontent.com/7274337/87973816-c3318700-cad1-11ea-8982-9c87956986fb.png)

**Comment by strycore** [comment]
the package should be moved to a recommends instead, Lutris can run without it.

**Comment by darkwolf740** [comment]
I am having the same problem I have tried everything but it's still not working I am using Ubuntu 16.04.If you find a solution help me

**Comment by strycore** [comment]
Closing this issue as the python-distro won't be a hard dependency in 0.5.8 which will solve the problem.
