### ISSUE TITLE
don't force a dark theme

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#304]
https://github.com/lutris/lutris/blob/master/lutris/gui/lutriswindow.py#L82

the most icon themes does not really work well with dark themes, so the user should either be able to disable the dark theme or you should force adwaitas symbolic icon theme.

eg: icons made for bright/grey widget themes are terrible to read:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/16539491/1ff1d5c4-4045-11e6-9005-fb94037901f9.png)

I would suggest to disable this settings so everbody can set this for himself(eg GTK_THEME=Adwaita:dark lutris)

**Comment by strycore** [comment]
the dark theme is now an option in the view menu!
