### ISSUE TITLE
[Feature Request] Close/Resize Runners and Profile Window to give Game Library More Space

### ISSUE THREAD

**Issue by ThrashMetalComputers** [lutris/lutris#3042]
Would it be possible to close/resize the Runners and Profile windows on either side of the games library, so that I can only have my library showing? Something like this:

<img src="https://i.ibb.co/sVcZ7bQ/window-resize.png" alt="window-resize" border="0">

Thank you always for this brilliant piece of software.

**Comment by AlexanderRavenheart** [comment]
![image](https://user-images.githubusercontent.com/7274337/88176638-3f41e100-cc30-11ea-88bb-bd4cc6e68e5f.png)

**Comment by strycore** [comment]
yes, there are options the dropdown menu. Also, the sidebars as they are now are subject to change, it is not a definitive desgin. The right hand one is likely to go away soon.

**Comment by ThrashMetalComputers** [comment]
> yes, there are options the dropdown menu. Also, the sidebars as they are now are subject to change, it is not a definitive desgin. The right hand one is likely to go away soon.

I'm completely blind, sorry for wasting your time with this request! I can't believe I didn't see that!
