### ISSUE TITLE
Geforce Now crash

### ISSUE THREAD

**Issue by SuperMage1** [lutris/lutris#3043]
When I try to open Geforce Now with Lutris it just closes after few seconds with next log.

lutris-wrapper: GeForce NOW
Running /home/supermage/.local/share/lutris/runners/wine/lutris-5.7-5-x86_64/bin/wine /home/supermage/Games/geforce-now/drive_c/users/supermage/AppData/Local/NVIDIA Corporation/GeForceNOW/CEF/GeForceNOW.exe
Initial process has started with pid 1698
Game is considered started.
[3920-07-23/ 02:19:08.519:ERROR:network_change_notifier_win.cc(141)] WSALookupServiceBegin failed with: 0
[3920-07-23/ 02:19:08.858:INFO:browser_app.cc(369)] Framework Microsoft Windows 64bit
[3920-07-23/ 02:19:08.858:INFO:browser_app.cc(373)] Version NVIDIACEFClient/79.3945.117.2/gfn_release/088f93da5
[3920-07-23/ 02:19:08.859:INFO:browser_app.cc(674)] No urlRoute value found.
[3920-07-23/ 02:19:08.873:ERROR:file_watcher_win.cc(185)] Error in updating the filepath to watch
[3920-07-23/ 02:19:08.873:WARNING:file_watcher_win.cc(274)] Not calling CancelIoEx because the directory handle is invalid. Initialization likely failed
[3920-07-23/ 02:19:08.873:INFO:browser_app.cc(751)] Geronimo Logger Init
[3920-07-23/ 02:19:08.873:INFO:browser_app.cc(850)] CreateCefWindowInstance
[3920-07-23/ 02:19:08.873:INFO:browser_app.cc(855)] Add handler 00000000043F3720
[3920-07-23/ 02:19:08.876:INFO:cef_dark_window.cpp(240)] GDI+ startup
[3920-07-23/ 02:19:09.061:INFO:cef_dark_window.cpp(817)] Could not get browser reference while drawing system icons
[3920-07-23/ 02:19:09.066:INFO:cef_dark_window.cpp(817)] Could not get browser reference while drawing system icons
[3920-07-23/ 02:19:09.072:INFO:cef_dark_window.cpp(817)] Could not get browser reference while drawing system icons
[3920-07-23/ 02:19:09.077:INFO:cef_dark_window.cpp(817)] Could not get browser reference while drawing system icons
[3920-07-23/ 02:19:09.081:INFO:cef_dark_window.cpp(817)] Could not get browser reference while drawing system icons
[3920-07-23/ 02:19:09.144:INFO:browser_app.cc(939)] Start app event thread
[3920-07-23/ 02:19:09.273:INFO:ipc_cef.cc(52)] Creating IPC instance with name = GeForceNOW, type = mallclient
[3920-07-23/ 02:19:09.294:INFO:ipc_cef.cc(74)] Finished initialization.
[3920-07-23/ 02:19:09.295:INFO:file_watcher_win.cc(340)] Detected file modified
[3920-07-23/ 02:19:09.530:INFO:cef_plugin_win.cpp(28)] Loaded dependency module CrimsonUtil.dll
[3920-07-23/ 02:19:09.956:INFO:cef_plugin_win.cpp(28)] Loaded dependency module NetworkTestSDK.dll
[3920-07-23/ 02:19:10.001:INFO:cef_plugin_win.cpp(137)] Loaded Cef Plugin  cef/common/NetworkTest.dll
[3920-07-23/ 02:19:10.133:INFO:cef_plugin_win.cpp(137)] Loaded Cef Plugin  cef/common/SystemInfo.dll
[3920-07-23/ 02:19:10.133:INFO:cef_plugin_manager.cpp(112)] Initializing all plugins
[3920-07-23/ 02:19:10.134:INFO:cef_plugin.cpp(72)] 2020-07-23T02:19:10.133[I]                     LoggingImpl.cpp:203  Initialize CrimsonNative logger
wine: Unhandled page fault on read access to 0000000004863F8C at address 000000014007DC23 (thread 0050), starting debugger...
[3920-07-23/ 02:19:10.293:INFO:cef_plugin_manager.cpp(219)] Starting all plugins
Unhandled exception: page fault on read access to 0x04863f8c in 64-bit code (0x000000014007dc23).
Register dump:
 rip:000000014007dc23 rsp:0000000006ccf250 rbp:0000000006ccf350 eflags:00010256 (  R- --  I  Z-A-P- )
 rax:0000000004863f8c rbx:0000000000000017 rcx:00000000000f8028 rdx:0000000000000043
 rsi:0000000004863f80 rdi:0000000000000000  r8:0000000000000000  r9:0000000000000000 r10:00000000044da570
 r11:0000000000000000 r12:0000000000000010 r13:00000000003e00a1 r14:00000000044da570 r15:0000000004483c80
Stack dump:
0x0000000006ccf250:  0000000000000000 0000000000000000
0x0000000006ccf260:  0000000000000008 0000000000000000
0x0000000006ccf270:  0000000000000000 0000000000000000
0x0000000006ccf280:  000000014024fbc8 0000000140244ad0
0x0000000006ccf290:  0000000000000000 0000000000000000
0x0000000006ccf2a0:  0000000006ccf290 0000000006ccf298
0x0000000006ccf2b0:  0000000000000000 0000000000000000
0x0000000006ccf2c0:  0000000006ccf2b0 0000000006ccf2b8
0x0000000006ccf2d0:  0000000000000000 0000000006ccf2d0
0x0000000006ccf2e0:  0000000006ccf2d4 0000000004484f90
0x0000000006ccf2f0:  0000000000000000 0000000000000004
0x0000000006ccf300:  0000007800000000 0000000140244a68
Backtrace:
=>0 0x000000014007dc23 in geforcenow (+0x7dc23) (0x0000000006ccf350)
  1 0x000000014007c9cc in geforcenow (+0x7c9cb) (0x0000000006ccf670)
0x000000014007dc23: cmpw	$0,(%rax,%r9,2)
Modules:
Module	Address					Debug info	Name (97 modules)
PE	          260000-          35e000	Deferred        chrome_elf
PE	          360000-          78e000	Deferred        d3dcompiler_47
PE	          790000-         1218000	Deferred        bifrost2
PE	         1220000-         17fa000	Deferred        geronimo
PE	         1800000-         199a000	Deferred        gsaudiowebrtc
PE	         7cb0000-         7f8f000	Deferred        crimsonutil
PE	         7f90000-         86a4000	Deferred        networktestsdk
PE	         86b0000-         898c000	Deferred        networktest
PE	         8990000-         8c8e000	Deferred        systeminfo
PE	        6c740000-        6c8b2000	Deferred        sdl2
PE	        7a850000-        7a858000	Deferred        opengl32
PE	        7b010000-        7b027000	Deferred        kernelbase
PE	        7b410000-        7b5db000	Deferred        kernel32
PE	        7bc20000-        7bc35000	Deferred        ntdll
PE	       140000000-       140349000	Export          geforcenow
PE	       180000000-       1873ba000	Deferred        libcef
PE	    7fe58e440000-    7fe58e45e000	Deferred        wldap32
PE	    7fe58e4b0000-    7fe58e4b5000	Deferred        directmanipulation
PE	    7fe58e8c0000-    7fe58e8c8000	Deferred        windowscodecs
PE	    7fe58ec90000-    7fe58ec94000	Deferred        atlthunk
PE	    7fe58ecc0000-    7fe58ecc4000	Deferred        winepulse
PE	    7fe58ed00000-    7fe58ed05000	Deferred        mmdevapi
PE	    7fe58ed30000-    7fe58ed35000	Deferred        msctf
PE	    7fe58ed60000-    7fe58ed67000	Deferred        combase
PE	    7fe58edd0000-    7fe58edd4000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	    7fe58ede0000-    7fe58ede5000	Deferred        rsaenh
PE	    7fe58ee20000-    7fe58ee25000	Deferred        imagehlp
PE	    7fe58ee40000-    7fe58ee44000	Deferred        cryptnet
PE	    7fe58ee60000-    7fe58ee64000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
PE	    7fe58f0a0000-    7fe58f0a4000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	    7fe58f0c0000-    7fe58f0c4000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	    7fe58f0d0000-    7fe58f0d4000	Deferred        api-ms-win-core-string-l1-1-0
PE	    7fe58f0e0000-    7fe58f0e4000	Deferred        api-ms-win-core-localization-l1-2-1
PE	    7fe58f0f0000-    7fe58f0f4000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	    7fe58f110000-    7fe58f114000	Deferred        api-ms-win-core-synch-l1-2-0
PE	    7fe58f3f0000-    7fe58f3f4000	Deferred        kerberos
PE	    7fe590180000-    7fe590185000	Deferred        winex11
PE	    7fe590240000-    7fe590244000	Deferred        msimg32
PE	    7fe590260000-    7fe59026c000	Deferred        gdiplus
PE	    7fe5902f0000-    7fe5902f5000	Deferred        pdh
PE	    7fe590310000-    7fe590314000	Deferred        wlanapi
PE	    7fe590320000-    7fe590325000	Deferred        msdmo
PE	    7fe590340000-    7fe590344000	Deferred        qwave
PE	    7fe590350000-    7fe590355000	Deferred        dsound
PE	    7fe5903c0000-    7fe5903d0000	Deferred        msvcrt
PE	    7fe590490000-    7fe590497000	Deferred        esent
PE	    7fe5904a0000-    7fe5904a5000	Deferred        ncrypt
PE	    7fe5904c0000-    7fe5904c4000	Deferred        dhcpcsvc
PE	    7fe5904d0000-    7fe5904d6000	Deferred        jsproxy
PE	    7fe5904f0000-    7fe5904f7000	Deferred        winhttp
PE	    7fe590530000-    7fe590534000	Deferred        dxva2
PE	    7fe590560000-    7fe590565000	Deferred        d3d9
PE	    7fe5905a0000-    7fe5905a5000	Deferred        uxtheme
PE	    7fe5905f0000-    7fe5906cc000	Deferred        cryptui
PE	    7fe590700000-    7fe5907ad000	Deferred        comdlg32
PE	    7fe590800000-    7fe59081d000	Deferred        credui
PE	    7fe590840000-    7fe59084d000	Deferred        winspool
PE	    7fe590890000-    7fe590895000	Deferred        d3d11
PE	    7fe590910000-    7fe590915000	Deferred        dwmapi
PE	    7fe590920000-    7fe590924000	Deferred        dwrite
PE	    7fe5909c0000-    7fe5909c7000	Deferred        propsys
PE	    7fe5909f0000-    7fe5909f7000	Deferred        dbghelp
PE	    7fe590a70000-    7fe590a75000	Deferred        hid
PE	    7fe590a80000-    7fe590a84000	Deferred        wtsapi32
PE	    7fe590aa0000-    7fe590aa5000	Deferred        uiautomationcore
PE	    7fe590ac0000-    7fe590ad8000	Deferred        oleacc
PE	    7fe590b20000-    7fe590b25000	Deferred        bcrypt
PE	    7fe590b50000-    7fe590b97000	Deferred        crypt32
PE	    7fe590c50000-    7fe590c56000	Deferred        wintrust
PE	    7fe590c80000-    7fe590c84000	Deferred        userenv
PE	    7fe590cb0000-    7fe590cb6000	Deferred        dnsapi
PE	    7fe590ce0000-    7fe590ce7000	Deferred        netapi32
PE	    7fe590d20000-    7fe590d24000	Deferred        secur32
PE	    7fe590d90000-    7fe590d99000	Deferred        wined3d
PE	    7fe590f20000-    7fe5910fe000	Deferred        dxgi
PE	    7fe590f20000-    7fe5910fe000	Deferred        winmm
PE	    7fe590f20000-    7fe5910fe000	Deferred        iphlpapi
PE	    7fe590f20000-    7fe5910fe000	Deferred        wininet
PE	    7fe590f20000-    7fe5910fe000	Deferred        ws2_32
PE	    7fe590f20000-    7fe5910fe000	Deferred        mpr
PE	    7fe591160000-    7fe591166000	Deferred        imm32
PE	    7fe591180000-    7fe591184000	Deferred        usp10
PE	    7fe5911d0000-    7fe591225000	Deferred        comctl32
PE	    7fe591320000-    7fe59132a000	Deferred        aclui
PE	    7fe591340000-    7fe591345000	Deferred        shcore
PE	    7fe591370000-    7fe59137f000	Deferred        shlwapi
PE	    7fe5913e0000-    7fe591cdb000	Deferred        shell32
PE	    7fe591e50000-    7fe591e5d000	Deferred        oleaut32
PE	    7fe591f90000-    7fe591f9c000	Deferred        gdi32
PE	    7fe592130000-    7fe59213b000	Deferred        rpcrt4
PE	    7fe5921e0000-    7fe5921fe000	Deferred        ucrtbase
PE	    7fe5922e0000-    7fe5922e5000	Deferred        version
PE	    7fe592300000-    7fe592317000	Deferred        setupapi
PE	    7fe5923a0000-    7fe592491000	Deferred        user32
PE	    7fe592610000-    7fe59261b000	Deferred        advapi32
PE	    7fe5926c0000-    7fe5926ec000	Deferred        ole32
PE	    7fe592810000-    7fe592824000	Deferred        urlmon
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	[C:\windows\system32\services.exe]
	00000025    0
	00000022    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000001f    0
	0000001e    0
	0000001d    0
	0000001c    0
	0000001b    0
	00000019    0
00000020 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000026    0
	00000024    0
	00000023    0
	00000021    0
0000002c (D) C:\users\supermage\AppData\Local\NVIDIA Corporation\GeForceNOW\CEF\GeForceNOW.exe
	["C:\users\supermage\AppData\Local\NVIDIA Corporation\GeForceNOW\CEF\GeForceNOW.exe"]
	0000006e    0
	0000006d    0
	0000006b    0
	00000066    0
	00000065    0
	0000005a    0
	00000059    0
	00000058    0
	00000057    0
	00000056    0
	00000055    0
	00000054    0
	00000053    0
	00000052   -2
	00000051    0
	00000050    0 <==
	0000004f    0
	0000004e    0
	0000004d   -2
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000039   -2
	00000038    0
	00000037    0
	00000036    0
	00000035    0
	0000002d    0
0000002e explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
00000046 GeForceNOW.exe
	["C:\users\supermage\AppData\Local\NVIDIA Corporation\GeForceNOW\CEF\GeForceNOW.exe" --type=gpu-process --field-trial-handle=600,17143437035962239163,9379435764893104298,131072 --disable-features=MimeHandlerViewInCrossProcessFrame --no-sandbox --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --log-severity=info --lang=en-US --gpu-preferences=KAAAAAAAAADgAAAwAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --service-request-channel-token=1139234374880976794 --mojo-platform-channel-handle=608 /prefetch:2]
	0000005d    0
	00000047    0
0000005b GeForceNOW.exe
	["C:\users\supermage\AppData\Local\NVIDIA Corporation\GeForceNOW\CEF\GeForceNOW.exe" --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --field-trial-handle=600,17143437035962239163,9379435764893104298,131072 --disable-features=MimeHandlerViewInCrossProcessFrame --lang=en-US --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --log-severity=info --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=17731971253035038932 --renderer-client-id=3 --mojo-platform-channel-handle=1072 /prefetch:1]
	00000070    0
	0000006f    0
	0000006c    0
	00000064    0
	00000063    0
	00000062    0
	00000061   -2
	00000060    0
	0000005f    0
	0000005e    0
	0000005c    0
00000069 GeForceNOW.exe
	["C:\users\supermage\AppData\Local\NVIDIA Corporation\GeForceNOW\CEF\GeForceNOW.exe" --type=utility --field-trial-handle=600,17143437035962239163,9379435764893104298,131072 --disable-features=MimeHandlerViewInCrossProcessFrame --lang=en-US --service-sandbox-type=network --no-sandbox --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --log-severity=info --lang=en-US --log-file="C:\users\supermage\Local Settings\Application Data\NVIDIA Corporation\GeForceNOW\debug.log" --service-request-channel-token=9470872231654655614 --mojo-platform-channel-handle=1188 /prefetch:8]
	0000006a    0
System information:
    Wine build: wine-5.7.r0.g2ad422ff ( TkG Staging Esync Fsync Vkd3d DXVK-Compatible )
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.6.19-2-MANJARO
Initial process has exited.
Game is considered exited.
All monitored processes have exited.
Exit with returncode 1280

**Comment by qarmin** [comment]
This seems to be Wine, not Lutris bug - https://bugs.winehq.org/show_bug.cgi?id=40430

**Comment by tannisroot** [comment]
You should be able to workaround this by installing msxml3 with winetricks

**Comment by SuperMage1** [comment]
> You should be able to workaround this by installing msxml3 with winetricks

It is installed
