### ISSUE TITLE
Feature suggestion: duplicate game's settings with one click (useful for Wine games)

### ISSUE THREAD

**Issue by warriormaster12** [lutris/lutris#3045]
In my case I would like to duplicate Origin launcher's parameters for Battlefield 4 game because it requires special version of Wine that fixes the pimg issue in multiplayer matches. Every other Origin game I would like to work with latest Wine/Proton version.

To achieve this currently I would need to add a new game and duplicate manually every single setting that is required for Origin and Battlefield to work. 

With suggested feature I would need right click Origin and select duplicate option. The option would duplicate all parameters and the only thing that I would need to change is the name of the prefix from Origin to Battlefield.

**Comment by strycore** [comment]
That could be cool. You don't need to change the prefix btw, a lot of games will work using the same prefix. As long as it's basic and not tons of winetricks applied to it.

**Comment by warriormaster12** [comment]
@strycore I don't know why I used term prefix 😅. What I meant was duplicating stuff that would currently require going back and forth between two games or launcher/game.

**Comment by strycore** [comment]
bug tracked in #3102 and PR in #4032
