### ISSUE TITLE
Unable to open Installer due to missing icons

### ISSUE THREAD

**Issue by Jan200101** [lutris/lutris#3046]
**Describe the bug**

Currently on the master branch the installer GUI does not properly work due to it attempting to use icons which were deleted in 66d26e776b996d91ca5dea4573e7fe404a6ac911 but still fetched by the installer GUI  [/lutris/gui/widgets/installer.py#L69-L73](https://github.com/lutris/lutris/blob/master/lutris/gui/widgets/installer.py#L69-L73)

a fix has been pushed to the file-picker branch (bc1cf5abf1559c20626699feffeeecdbb6d59955) but the branch has its own share of issues that prevent game installation

**Expected behavior**

Working Installer GUI

**Current behavior**

Installer GUI just shows a window without any installers

**Steps to reproduce**

- run master (c00fc96a185d9177f74380122504648b7ef05077 as of speaking)
- open the Installer gui for anything

**Lutris debugging output**

The terminal output of `lutris -d`.

[relevant output](https://gist.github.com/Jan200101/fc7edb0b86f9acc84b55f0eaf4c93832)

**System information**

not relevant

**Screenshots**

![image](https://user-images.githubusercontent.com/15076013/88295648-fd7f6c00-ccfd-11ea-8211-a8ab5035697b.png)

**Comment by strycore** [comment]
master branch is now fixed and reads icons from the runtime folder.
