### ISSUE TITLE
No play time is recorded by Lutris when run in terminal is chosen

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#3047]
At the title states, Lutris 0.5.7 exits the run state when run in terminal is used from the application config system options. This causes Lutris to have no play time for that application.

If it starts from Lutris, however its done, Lutris should count the time.

Reproduce by configuration of application in Lutris's system options tab to run in terminal.

Is there a way to keep attached to the terminal that it opens?

**Comment by strycore** [comment]
I know a lot of people misuse this option which is only used for playing text based games but I tried with Moon Buggy and I can confirm the issue is present.

**Comment by strycore** [comment]
Lutris can now track the status of Moon Buggy and other processes not spawned by the client.
