### ISSUE TITLE
how to add cm0304.exe -small_screen launch options on Lutris

### ISSUE THREAD

**Issue by dedeoglumrt** [lutris/lutris#3053]
i want to play 800x600 this game. i select virtual desktop 800x600 but game doesnt work without -small_screen parameters.
i tried lutris/game options/arguments section but didnt work.

Please help me.

**Comment by tannisroot** [comment]
Can you make a screen of your Game Options tab with that parameter there in arguments field?

**Comment by dedeoglumrt** [comment]
i resolved the issue by doing following settings ;

- no virtual desktop settings for the game on Litrus / wine
- litrus launch arguments : -small_screen -windowed


then it worked well with any resolution issue or alt tab problem.
