### ISSUE TITLE
Handle script without shebang errors

### ISSUE THREAD

**Issue by kpj** [lutris/lutris#306]
Hello,

I am using Lutris 0.3.7.5 on archlinux and I am trying to start a native executable using optirun. In order to do so, I created a bash-script containing
`optirun <executable name in $PATH>`
and added it using a native runner.

Whenever I try to start this, I get the following error:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/lutris/thread.py", line 79, in run
    self.game_process = self.execute_process(self.command, env)
  File "/usr/lib/python2.7/site-packages/lutris/thread.py", line 110, in execute_process
    cwd=self.cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lutris/thread.py", line 195, in watch_children
    self.return_code = self.game_process.returncode
AttributeError: 'NoneType' object has no attribute 'returncode'
```

How can I fix this behaviour?

**Comment by strycore** [comment]
I've managed to reproduce this issue. This behavior happen when a shell script is called but doesn't contain a shebang like "#!/bin/bash" at the start of the script. Adding it fixed the issue. 

Not sure what we can do about this on the client, this seems to be a limitation in the Python library but we should be able to handle that error more gracefully.

Also,  we do support running games with Primusrun (game configuration, system tab) but we don't have Optirun. Is there a big difference between those 2? (maybe @Xodetaetl can help with this).

Either way, you can also set an arbitrary prefix command in the system preference for any game so you can run games with optirun without having to write a script.

**Comment by kpj** [comment]
Neat, great to hear that there is such an easy fix!

Regarding `optirun` vs `primusrun`, there seems to be an explanation [here](http://askubuntu.com/a/669026).
Furthermore: "primusrun (from package primus) is becoming the default choice, because it consumes less power and sometimes provides better performance than optirun/virtualgl. It may be run separately, but it does not accept options as optirun does. Setting primus as the bridge for optirun provides more flexibility." (from https://wiki.archlinux.org/index.php/bumblebee#Primusrun)

You mentioned that you support running the game with primusrun. After looking into the options once more, I was now able to find the checkbox :-)
Thanks as well for the command prefix tip!

**Comment by strycore** [comment]
Lutris will now display a proper error message when encountering badly formatted scripts instead of failing silently
