### ISSUE TITLE
DRM version incompatibility

### ISSUE THREAD

**Issue by TheHaricover** [lutris/lutris#3063]
**Describe the bug**

When launching Lutris in terminal, the line `amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.` appears.

**Expected behavior**

The line doesn't appear, or a line that's expected to replace it.

**Current behavior**

When launching Lutris in terminal, the line `amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.` appears.

**Steps to reproduce**

Install Lutris on a PC with a Radeon HD 7950 with Mesa driver 20.1.3 and linux-video on Manjaro 20.0.3

**Lutris debugging output**

```
Unable to load locale dir, translations won't work.
2020-08-03 21:00:05,411: MAME XML generation launched in the background, not returning anything this time
2020-08-03 21:00:05,411: Getting full game list from MAME...
2020-08-03 21:00:05,413: MAME isn't installed, can't retrieve systems list.
INFO     2020-08-03 21:00:05,606 [application.do_command_line:275]:Running Lutris 0.5.7
INFO     2020-08-03 21:00:05,606 [startup.check_driver:60]:Using X.Org
INFO     2020-08-03 21:00:05,606 [startup.check_driver:62]:Running Mesa driver 20.1.3 on AMD TAHITI (DRM 2.50.0, 5.7.9-1-MANJARO, LLVM 10.0.0) (0x679a)
INFO     2020-08-03 21:00:05,607 [startup.check_driver:73]:GPU: 1002:679A 1458:229A using radeon drivers
amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.
INFO     2020-08-03 21:00:05,648 [startup.check_vulkan:126]:Vulkan is not available or your system isn't Vulkan capable
DEBUG    2020-08-03 21:00:05,886 [http.get:71]:GET https://lutris.net/api/runtime
INFO     2020-08-03 21:00:06,290 [mame.notify_mame_xml:31]:MAME XML written

(lutris:40769): Gdk-CRITICAL **: 21:00:06.369: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**System information**

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/5017252/lutris-issue-report.json.zip)

**Screenshots**
 
![image](https://user-images.githubusercontent.com/16842716/89208498-c3934d00-d5bc-11ea-85c0-b6315f1fced4.png)

![image](https://user-images.githubusercontent.com/16842716/89208435-a2caf780-d5bc-11ea-987c-437431b1773e.png)

![image](https://user-images.githubusercontent.com/16842716/89208452-ad858c80-d5bc-11ea-962f-48cf7754e340.png)

**Comment by strycore** [comment]
I have zero clue what your talking about. This is not our bug.

**Comment by byte1024** [comment]
The line above it clearly states

`Running Mesa driver 20.1.3 on AMD TAHITI (DRM 2.50.0, 5.7.9-1-MANJARO, LLVM 10.0.0) (0x679a)`

When you combine that with

`DRM version is 2.50.0 but this driver is only compatible with 3.x.x.`

Its telling you that the drm running with mesa 20.1.3 is 2.50.0 but the driver is only compatible with 3.x.x. This is a system problem (not Lutris) and this issue should technically be closed. It keeps Lutris from running sure, but that's not the fault of Lutris. Its like saying that Lutris should run with a broken desktop environment or Lutris should fix your computer for you.

https://forum.manjaro.org/t/amd-gpu-driver-and-vulkan/86358/6
https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1696231

**Comment by TheHaricover** [comment]
Alright, thank you :smile: 
And sorry for the inconvenience !
