### ISSUE TITLE
Broken computer causes Xrandr to crash lutris

### ISSUE THREAD

**Issue by BillGR17** [lutris/lutris#3064]
Lutris crashes everytime i change xrandr settings i have set it to close secondary monitor and if its not off it turns it off and crashes if its off there are no issues

heres the log when lutris crashes

```
(lutris:83031): Gdk-WARNING **: 12:10:52.692: GdkWindow 0x120003a unexpectedly destroyed

(lutris:83031): Gdk-ERROR **: 12:10:52.701: The program 'lutris' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 19486 error_code 143 request_code 139 (RENDER) minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  lutris
```

**Comment by strycore** [comment]
Your computer is clearly broken and you have to fix that, not lutris.

**Comment by strycore** [comment]
Reading the stack trace, I don't think there's anything we can do. It's not in our code but directly in the Gdk libraries.
Our programs relies on functional xrandr, sorry. You can bypass that by going on Wayland. We won't use Xrandr there.

**Comment by BillGR17** [comment]
It appears to be i3-gaps problem not lutris sorry.

**Comment by strycore** [comment]
is it fixable or is it something we should detect and warn users about?

**Comment by BillGR17** [comment]
The issue appears at i3 version 4.18.2 on i3 version 4.18.1 everything works perfect.
 After checking the i3 github the issue has been reported and they are working on a fix
