### ISSUE TITLE
Dolphin doesn't run without libopengl0 package manually installed

### ISSUE THREAD

**Issue by TheWranger** [lutris/lutris#3065]
**Describe the bug**

Dolphin will not run at all if the libopengl0 package is not installed; this is not a dependency of lutris

**Expected behavior**

Manual installation of libopengl0 will not be required to get Dolphin running, or the user should be notified that manual installation of the package is required.

**Current behavior**

The user has to manually install libopengl0

**Steps to reproduce**

- Don't have libopengl0 installed
- Attempt to run Lutris's Dolphin runner inside Lutris

This was also reported at https://forums.lutris.net/t/dolphin-emu-libopengl-so-0-needed/5643

**Comment by strycore** [comment]
added a check for this library in dolphin (still needs to be installed but will show an appropriate message)
