### ISSUE TITLE
How to disable log files in game directory?

### ISSUE THREAD

**Issue by Flo082002** [lutris/lutris#3067]
I have the plan to play GTA 5. The game works fine when I enable DXVK/VKD3D in the Runner options.
Unfortunately, log files are written to the folder of the game. 

```
wmic_dxgi.log
GTA5.dxvk-cache
GTA5_dxgi.log
SocialClubHelper_dxgi.log
SocialClubHelper_d3d11.log
SocialClubHelper_d3d9.log
GTA5_d3d11.log
GTA5_d3d9.log

```
This prevents me from being able to play online, as it counts as a change to the game files if you change or add files to this folder. Is there any way to move these log files / the dxvk-cache file to another folder or to disable them completely?

**Comment by byte1024** [comment]
For dxvk logging

```
DXVK_LOG_LEVEL=none|error|warn|info|debug Controls message logging.
DXVK_LOG_PATH=/some/directory Changes path where log files are stored.
DXVK_CONFIG_FILE=/xxx/dxvk.conf Sets path to the configuration file.
```
https://github.com/doitsujin/dxvk

and VKD3D

`Vkd3d provides VKD3D_DEBUG and VKD3D_SHADER_DEBUG environment variables to control debug log messages. The debug variables can be set to one of the following debug log levels: none, err, fixme, warn, trace. `

https://wiki.winehq.org/Vkd3d

`DXVK_STATE_CACHE_PATH`

The dxvk-cache https://github.com/rcpoison/dxvk-cache-pool

**Comment by Flo082002** [comment]
Thanks for your help.
Unfortunately nothing changed

```
export DXVK_LOG_LEVEL=none
export DXVK_LOG_PATH=~/Games/cache/DXVK_Log_Path
export DXVK_STATE_CACHE_PATH=~/Games/cache/DXVK_State_Cache_Path
export VKD3D_DEBUG=none
export VKD3D_SHADER_DEBUG=none
```

**Comment by Flo082002** [comment]
Thanks for helping. Found it 
![Bildschirmfoto vom 2020-08-04 16-29-59](https://user-images.githubusercontent.com/27300374/89306205-d31f9e00-d66f-11ea-8bdb-5d228866c2f7.png)
