### ISSUE TITLE
Vulkan isn't working with Lutris even with drivers.

### ISSUE THREAD

**Issue by RTSAjwad** [lutris/lutris#3068]
I tried running league of legends and it says that "Vulkan is not installed or is not supported by your system". I'm using Pop!_OS and have followed the instructions on https://github.com/lutris/docs/blob/master/InstallingDrivers.md.

It still hasn't resolved the issue.

**Comment by byte1024** [comment]
What happens when you run $ vulkaninfo

You might need to install vulkan-tools first.

**Comment by RTSAjwad** [comment]
On a fresh setup with wine installed from https://wiki.winehq.org/Ubuntu and 32bit enabled etc:

> 
> ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
> ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
> /build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:477: failed with ERROR_INITIALIZATION_FAILED

**Comment by RTSAjwad** [comment]
I'm currently looking at this as it seems relevant:
https://www.reddit.com/r/linux4noobs/comments/g9ru6n/vulkan_not_working_ubuntu_2004/

**Comment by RTSAjwad** [comment]
After looking at that. I believe the issue

**Comment by RTSAjwad** [comment]
Okay I fixed my issue by switching from radeon to amdgpu. Ill post a link to the page that gave the details on it but essentially I editing `/etc/default/grub/` and changing:

>GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"

to

>GRUB_CMDLINE_LINUX_DEFAULT="quiet splash radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1"
