### ISSUE TITLE
PCSX2 Old Build

### ISSUE THREAD

**Issue by TheWranger** [lutris/lutris#3070]
![image](https://user-images.githubusercontent.com/24642838/89366716-c1df9b80-d71a-11ea-9587-e6148daa7aeb.png)
The PCSX2 build in Lutris is nearly 9 months old, and the plugins it come with have received updates as well. It might be time for a more recent build to be added. There has also been a new major stable release (1.6.0) since then.

**Comment by strycore** [comment]
I've pushed a build of PCSX 1.7-dev
