### ISSUE TITLE
(Presumed personal issue) Lutris fails to launch due to a python issue

### ISSUE THREAD

**Issue by bradley-r** [lutris/lutris#3073]
**Describe the bug**

Lutris now won't launch; it was working fine previously.

**Expected behavior**

Running `lutris` in the terminal or launching from LatteDock opens the Lutris application.

**Current behavior**

Running `lutris` in the terminal or launching from LatteDock fails to open the Lutris application. The error given is a (Python) `ModuleNotFoundError: No module named 'requests'

**Steps to reproduce**

- Attempt to launch Lutris after a period of no usage approx ~1 month. (Possibly update related?)

**Lutris debugging output**

> `[bradleyr@Maelstrom ~]$ lutris --d
> Unable to load locale dir, translations won't work.
> Traceback (most recent call last):
>   File "/usr/bin/lutris", line 54, in <module>
>     from lutris.gui.application import Application  # pylint: disable=no-name-in-module
>   File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 36, in <module>
>     from lutris.command import exec_command
>   File "/usr/lib/python3.8/site-packages/lutris/command.py", line 17, in <module>
>     from lutris import runtime, settings
>   File "/usr/lib/python3.8/site-packages/lutris/runtime.py", line 12, in <module>
>     from lutris.util.downloader import Downloader
>   File "/usr/lib/python3.8/site-packages/lutris/util/downloader.py", line 6, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> `

**System information**

> The .json file created by typing `lutris --submit-issue` in a terminal.

Running `lutris --submit-issue` results in the same error; no record of a .json being created - is the process breaking before the --submit-issue utility can be run?

**Screenshots**

![Screenshot_20200805_193916](https://user-images.githubusercontent.com/43189454/89450982-65e53900-d753-11ea-916c-2c9f396b3664.png)

Terminals showing launch error, my attempt at fixing, pretty error report and contents of `/usr/lib/python3.8/site-packages/lutris/util/`. A requests.py file is not present, including after reinstalls.

**Comment by byte1024** [comment]
You can check to see if you python installation has the requests module:

$ python

help("modules")

And look for it in the list.

It kind of sounds like it doesn't. I'm not seeing an issue with Lutris using Python, so at this time, also feel its not with Lutris code unless there's something really specific that the code doesn't deal with.

**Comment by bradley-r** [comment]
You're correct in the fact that it doesn't appear. `requests_file` and `requests_ftp` appear, but no standalone `requests` module. I'm not versed in Python whatsoever, language or usage-wise, but a `pip install requests --user` returns `requirement already satisfied` - suggesting that somewhere the module must exist. Searching `/usr/lib/python3.8/site-packages/lutris` and the util folder therein does not show a requests.py anywhere.

It is almost certainly not a Lutris issue, but given nothing has changed in regards to my Lutris and Python installations bar routine updates since I last used it, I'm at a loss as to why it suddenly isn't working.

**Comment by byte1024** [comment]
Some more ways are listed here https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

Can be bit of a pain :-)

**Comment by bradley-r** [comment]
Alright, I've managed to get a copy of requests from [here](https://pypi.org/project/requests/#files), but copying the requests folder to `/usr/lib/python3.8/site-packages/lutris/util/` or `/usr/local/lib/python3.8/site-packages/`does not fix Lutris' error. Running `sudo easy_install -U requests` returned `Installed /usr/local/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg`, but again it didn't allow Lutris to launch.

I have restarted for sanity's sake and nothing changed. Would clearing out Lutris' python folder then reinstalling be worth it, or would it fetch a previous config from user data elsewhere? Running out of options I can think of to get this working again, so might be the only thing left to try.

**Comment by byte1024** [comment]
I get this exact error if I uninstall requests from python.

I can't find any requests.py with lutris. Working on solving it via lutris will probably not work out. 

The error is from lutris downloader.py which asks python to import requests. That is lutris asks it to give the request code. It says it has nothing to give.

So you can try the following. If it doesn't work then your installations if python are for some reason messed up here.

$ sudo pip install requests
$ sudo pip2 install requests
$ sudo pip3 install requests

The try lutris again.

If it still doesn't work then you need to figure out why python is having an issue with requests.

You should be able to run the following also to check directly from python:

$ python
import requests

$ python
import requests

$ python3
import requests

If those show nothing then its good. If it shows an error, that's bad.

I have requests working for python and python3. When I uninstall requests with pip3, lutris breaks in this way.

Hope that helps.

**Comment by bradley-r** [comment]
Okay, here we go:

- `sudo pip install requests` runs, but returns `Requirement already satisfied` as in the original screenshot.
- `sudo pip2 install requests` fails to run - `command not found`. [Python27 is installed.](https://imgur.com/a/jxVHyYt)
- `sudo pip3 install requests` runs, but fails just as `pip` does in the original screenshot.

After each attempt running Lutris at the CLI returns the same error as before.

- `$ python import requests` returns no response. Therefore all good.
- `$ python(presumed and run as python2) import requests`returns `ImportError: No module named requests`.
- `$ python3 import requests` returns no response. Also good.

From this I seemingly have an identical config as you listed, so the root cause continues to elude me. Until troubleshooting this error, I hadn't so much as even looked at Python on my system, so to my knowledge there is little that could have caused it to go awry.

**Comment by byte1024** [comment]
Maybe someone else here has a better idea.

To me, its looking like something is messed up with the python installs.

I've seen stupid things happen and maybe its one of those things but not sure.

I guess just relax and see what else pops up to try.

**Comment by strycore** [comment]
you should probably install requests with your package manager and not with pip

**Comment by bradley-r** [comment]
It appeared as already installed, but a reinstall and restart to be safe has Lutris working again, thanks @strycore for that solution, and thanks again to @byte1024 for the help diagnosing the issue. Still no idea what could have caused the requests module specifically to breaK.

**Comment by byte1024** [comment]
At least it's fixed :-)
