### ISSUE TITLE
UT GOLD - Illegal distribution

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#308]
https://lutris.net/games/install/27/view

Its clearly mentioned in the FAQ and installer readme that a different redistribution is not allowed: http://www.oldunreal.com/wiki/index.php?title=Oldunreal_227_FAQ#Why_should_I_use_Unreal_227.3F

**Comment by strycore** [comment]
Well, if they have a problem with this, they come talk to me, I'm open for discussion.

In their FAQ, they do not say anything about redistribution, only that their patch should be installed with Wine for legal reasons, which does not make the slightest amount of sense. This is also the obvious reason why I'm distributing the file on lutris.net, there is no single reason to use Wine here.

Also, 18 year game running on a mod that was last updated 4 years ago, it's not much of a stretch to assume that everyone stopped caring a long time ago. (Which is yet another reason to self host the files, people stop caring and then one day it's all gone, with all their files).

All video game preservation projects have to deal at some point with a bit of legal grey areas and this is a risk I'm totally willing to take, to some extent (which is nothing compared to what archive.org does).
