### ISSUE TITLE
When trying to install Geforce now, it would take forever and fail

### ISSUE THREAD

**Issue by HamzaGaming400** [lutris/lutris#3081]
Hello, I recently found lutris for Linux ubuntu, and I got interested in it. But when I went to download GeForce now, It would take forever to download the libraries, it would reach 431550K then say the following 

2020-08-12 13:06:49 (280 KB/s) - Read error at byte 441910599 (Success).Retrying.

--2020-08-12 13:06:50--  (try: 2)  https://web.archive.org/web/20110608170121/http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe
Connecting to web.archive.org (web.archive.org)|207.241.226.190|:443... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2020-08-12 13:07:08--  (try: 3)  https://web.archive.org/web/20110608170121/http://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe
Connecting to web.archive.org (web.archive.org)|207.241.226.190|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘windows6.1-KB976932-X64.exe’

I don't know how many times it did this because I left It overnight. please help

**Comment by byte1024** [comment]
You can try again using the latest DXVK https://github.com/doitsujin/dxvk/releases/tag/v1.7.1

`Implemented NV12 video format support for D3D9. This should make the GeForce Now app usable with DXVK.`

It is not available all ways as of yet so you can wait for it or whatever. I suggest keeping things as they are and wait for it.

**Comment by byte1024** [comment]
I suggest not using "web.archive.org". I don't see why this is a Lutris issue.

You should be using this (which isn't using web.archive.org) https://lutris.net/games/geforce-now/

Also, latest DXVK solves a problem with Geforce Now https://github.com/doitsujin/dxvk/releases/tag/v1.7.1 so keep that in mind.

**Comment by byte1024** [comment]
I see some of the stuff is being pulled in from "web.archive.org" during install which is likely the real problem as those connections are quite horrible. I believe this is stemming from winetricks https://github.com/Winetricks/winetricks/issues/628

It worked for me so this looks just to be a problem with the issuer and "web.archive.org". Its a 900MB+ file and the issuer cannot get it in full. I really don't see any other way here.

It would be a major change and would require a lot of work to skip or divert from "web.archive.org" and their servers don't seem to support resuming of file streams.

If it doesn't work for you, you may be kind of stuck on that one. If you can find an alternative source or something and get it downloaded, you can install Geforce Now manually without the script. I don't know if there will ever be another way.

**Comment by strycore** [comment]
That kind of issue with winetricks can usually be worked around by finding the required file on the internet and manually dropping it in the winetricks cache folder (~/.cache/winetricks)
This needs to be the exact same file with the correct checksum and filename.

**Comment by legluondunet** [comment]
Hello @HamzaGaming400 , concerning Lutris games scripts, you will obtain more support on Discord or our forum. Issues on Github concern mainly Lutris app. @strycore could you close this issue?
