### ISSUE TITLE
Disable Energy Management and screensaver

### ISSUE THREAD

**Issue by schnedann** [lutris/lutris#3082]
just successfully installed lutris + one of my games.
Was running as advertised by your library, but in the game the screensaver was activated (Gamepad input seems not to case events...)
So Energy saving and screensavers are useful and I don't want to disable. 
Would be nice if lutris could disable (pause) energy saving and screensaver like some media players do when starting a game and restore when finished

**Comment by AlexanderRavenheart** [comment]
You can use the pre-launch script and post-exit script options to handle something like that. You can find those in the System options tab. Just make 2 bash scripts that enable/disable the screensaver, make them executable and specify them in the two fields. Or you can make just script one and have it enable/disable based on an input argument. The choice is yours.

The problem with having something done automatically by Lutris is that there are many possible screensavers that have different configurations and ways of being disabled/paused/enabled, as not all of them conform to some common standard.

**Comment by schnedann** [comment]
Good Tip but e.g. in Case of XFCE there seems to be no shellcommand to do this... maybe there are interfaces like DBus or so.
Isnt there a opotunity to support at least Gnome, KDE, XFCE ... Guess this alone would cover 80%+ of all users.

**Comment by mYnDstrEAm** [comment]
Sounds like something for [gamemode](https://github.com/FeralInteractive/gamemode).

**Comment by soredake** [comment]
Related: https://bugs.kde.org/show_bug.cgi?id=328987

**Comment by legluondunet** [comment]
@strycore do you know if gamemode effectively manages Energy Management and screensaver?

**Comment by legluondunet** [comment]
on gamemode github https://github.com/FeralInteractive/gamemode saw:

* Screensaver inhibiting

**Comment by strycore** [comment]
Until we have a better solution, I agree that we can depend on Gamemode for that kind of stuff.
