### ISSUE TITLE
Lutris not launching via terminal/applications.

### ISSUE THREAD

**Issue by Our-ly** [lutris/lutris#3088]
NOTE: This is a similar issue to [Tzeny's issue](https://github.com/lutris/lutris/issues/3087) though I have more lines printed into terminal when running `lutris`.

Refused to launch, multiple installations. MAME error in console when launching via terminal

I expected lutris to launch successfully, though:

It doesn't launch via applications nor terminal.

**Steps to reproduce**

`sudo apt-get install lutris`
`sudo dpkg --add-architecture i386`
`~$ wine --version
wine-5.0.2`
`Exec=LC_ALL=en_GB.UTF-8   lutris %U` into desktop file.

**Lutris debugging output**
https://pastebin.com/aHQSDyQL

**System information**

> The .json file created by typing `lutris --submit-issue` in a 

UNABLE since lutris is unable to launch due to mame being "missing".

**Screenshots**

![image](https://user-images.githubusercontent.com/57875026/90348455-a79b9c80-dffb-11ea-94dc-d19f9ba80d6a.png)

**Comment by byte1024** [comment]
> "UNABLE since lutris is unable to launch due to mame being "missing"."

Its actually not related to that. This is the problem:

`ValueError: invalid literal for int() with base 10: 'dbus.UInt32(1440)'`

**Comment by strycore** [comment]
I can't work on this issue. Please try with Lutris 0.5.8 when it's released.
