### ISSUE TITLE
Brutal Wolfenstein

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#309]
http://forum.zdoom.org/viewtopic.php?f=19&t=48035
https://youtu.be/-8erThH8V7Q

**Comment by RobLoach** [comment]
Since these are currently on MediaFire, we'd likely want to how this ourselves. Put an initial installer up for this at:
https://lutris.net/games/brutal-wolfenstein/

Not working yet.

**Comment by RobLoach** [comment]
The ZDoom Runner would make this easier: https://github.com/lutris/lutris/pull/241

**Comment by strycore** [comment]
I hosted the game files here https://lutris.net/files/games/brutal-wolfenstein/ and you should now be able to use the zdoom runner (a build is available).
