### ISSUE TITLE
Local script folder to override the API

### ISSUE THREAD

**Issue by scandas** [lutris/lutris#3091]
Is it possible to list locally saved install scripts (e.g. in the directory ~/.lutris/local_script ) in the window in which all available install scripts for a given game are listed and list it as the first entry? 
You could check if in the local directory an install script with the same game_slug exists.

I sometimes modify install scripts to do additional things and I have to use the terminal to use my install script.
The modifications are for example that my save game is downloaded an copied into the right directory so that i can continue the game where I stopped.
I don't want to make the modifications public because no one will want to continue my save game.

**Comment by strycore** [comment]
I've seen stuff done with SaltStack that used a similar way of doing things. I think this is a good idea, and also could be used to make lutris work in "offline" mode. (You still need to be online to download stuff but it removes a dependency from the lutris website.

**Comment by strycore** [comment]
This feature (or an equivalent one) will be tracked in issue #1000
