### ISSUE TITLE
Support xdg-utils for desktop icons after an app is installled

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#3093]
Don't have support for desktop icons

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

Desktop icons showing up after app is installed

**Current behavior**

App is installed but no desktop icon

**Steps to reproduce**

- Install an app
- Nothing
- Nothing

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by strycore** [comment]
I do not understand this issue.
