### ISSUE TITLE
fightcade doesn't work on windows or linux

### ISSUE THREAD

**Issue by dinhokusanagi** [lutris/lutris#3095]
I use fedora silverblue and lutris flatpak, and fightcade doesn't roast lutris in any way.

**Comment by telanus** [comment]
We need lot more info to work out what's wrong. 

To help you, we need logs!
To create a log, first close Lutris completely. Then, open your terminal application, execute 
lutris -d 
and try to reproduce your issue.
After that, you need to copy the output in the terminal and share it with us (all of it).
It's recommended to use this ad-free paste service: https://paste.ubuntu.com/

**Comment by dinhokusanagi** [comment]
gamemodeauto: 
lutris-wrapper: Fightcade - Online Retro Gaming
Running /var/home/wellington/Games/fightcade-online-retro-gaming/Fightcade2
Initial process has started with pid 43
Game is considered started.
ERROR: can't find python 2.x
dbus[43]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 765.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 134

**Comment by dinhokusanagi** [comment]
[wellington@localhost ~]$ python
Python 3.8.5 (default, Aug 12 2020, 00:00:00)

**Comment by legluondunet** [comment]
Hello @dinhokusanagi , concerning Lutris games scripts, you will obtain more support on Discord or our forum. Issues on Github concern mainly Lutris app. @strycore could you close this issue?
