### ISSUE TITLE
The abiility to use Steam flatpak as a runner

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#3099]
**Describe the bug**

Can't use Steam flatpak as a runner

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

The ability to select Steam flatpak as a runner

**Current behavior**

It can't find it

**Steps to reproduce**

- Use steam flatpak
- Install lutris
- Try to installl Steam runner and it fails

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**

**Comment by strycore** [comment]
Steam Flatpak is now correctly handled

**Comment by strycore** [comment]
Lutris 0.5.14 will support using the Dolphin Flatpak
