### ISSUE TITLE
Prevent deletion of any directory used by another game + show size of deleted directory

### ISSUE THREAD

**Issue by PopeRigby** [lutris/lutris#3100]
Lutris deleted my entire 100GB GOG games directory because I wasn't looking when I uninstalled a game. There should really be some sort of confirmation before Lutris irreversably deletes something this big.

**Comment by byte1024** [comment]
There should already be a confirmation when deleting from Lutris.

But I guess this is an issue when you delete single games from Lutris UI that it doesn't take into account other games in the folder.

**Comment by PopeRigby** [comment]
Yeah. There should probably be some sort of fail safe if Lutris detects there's more than one game in the folder you're deleting.
