### ISSUE TITLE
Empty directories in prefixed

### ISSUE THREAD

**Issue by RDL-28** [lutris/lutris#3101]
**Describe the bug**

All Wine prefixes contain empty directories in "/drive_c/users /username /"
These directories are highlighted in the screenshot

![Снимок экрана_2020-08-20_19-28-24](https://user-images.githubusercontent.com/33255217/90760250-8cdb6780-e31c-11ea-9d83-55b547e09de2.png)

**Expected behavior**

These directories should not exist. They only appear if you create a prefix with Lutris.

**Comment by strycore** [comment]
lacking information to reproduce + no one else has run into this issue.
