### ISSUE TITLE
Lutris hangs when installing steam in wine on Opensuse 42.1

### ISSUE THREAD

**Issue by Mirppc** [lutris/lutris#311]
http://pastebin.com/tKizCwDw

There is the log that i gathered.  Lutris would hang at installing Steam for Wine and idle at 7% on one core.

Games tested:
Banished
Tropico 3
Bit Dungeon

Edit:

Adding ~/Games didnt work.

**Comment by strycore** [comment]
Should be ok now, if not, install wine with zypper
