### ISSUE TITLE
Missing innoextract gives misleading error message when extracting

### ISSUE THREAD

**Issue by gabor-udvari** [lutris/lutris#3110]
**Describe the bug**

If the innoextract executable is missing from the system, an installer using the extract directive with gog format will print out the following error message:

> RuntimeError('specified exe is not a GOG setup file')

This is misleading as the setup file is fine, only innoextract is missing from the system. Installing innoextract makes this error disappear.

**Steps to reproduce**

- Download any Windows installers from GOG
- Write an installer script with an extract directive, eg.:
```
script:
  files:
    - setup: "N/A: Select the Windows installer provided by GOG"                            
  installer:
    - extract:
        format: gog
        file: setup
        dst: $GAMEDIR
```
- Make sure innoextract is not in your $PATH or inside your lutris runtime
- Try to install the game with the installer script, observe the error message

**Lutris debugging output (Optional)**

[lutris-error-innoextract.log](https://github.com/lutris/lutris/files/5120224/lutris-error-innoextract.log)

**Screenshots (Optional)**

![lutris-error-innoextract](https://user-images.githubusercontent.com/1449353/91095118-1b712100-e65c-11ea-9321-28bde2aa67a3.png)

**Possible solutions**

- In `utils/extract.py` the `check_inno_exe` is silently returning False if innoextract is not found on the system, therefore `decompress_gog` is never called which would raise the proper OSError message. Maybe this is as easy as moving the OSError exception from `decompress_gog` to `check_inno_exe`.
- If innoextract is added to the `required_binaries` directive inside the installer, then it will properly alert the user. Maybe this info can be added to the [installers.rst docs.](https://github.com/lutris/lutris/blob/master/docs/installers.rst)
- Some installers are downloading the innoextract binary from the lutris website, eg. [Archimedian Dynasty](https://lutris.net/games/install/7726/view). Maybe this can be done by lutris itself if innoextract is not found on the system.

**Comment by strycore** [comment]
First step is to ship innoextract in the lutris runtime. There is no reason having such tools in an installer. Once we do game caching, users will end up with hundreds of duplicates of innoextract in their cache...
Once innoextract is available from the runtime, we can have proper integration in the client and have proper error messages.

**Comment by nikitalita** [comment]
> First step is to ship innoextract in the lutris runtime. There is no reason having such tools in an installer. Once we do game caching, users will end up with hundreds of duplicates of innoextract in their cache...
> Once innoextract is available from the runtime, we can have proper integration in the client and have proper error messages.

gog extract support in scripts was added over a year ago (https://github.com/lutris/lutris/pull/2241), and the additions were made to the buildbot (https://github.com/lutris/buildbot/pull/93), why is lutris still not shipping it with the runtime?

**Comment by strycore** [comment]
Closed in 0.5.9
We ship innoextract and it's used by GOG installers automatically in lutris

**Comment by domdfcoding** [comment]
With lutris 0.5.14 (installed from https://download.opensuse.org/repositories/home:/strycore/Debian_12/ per https://lutris.net/downloads) I can't find innoextract anywhere and `lutris.util.extract.get_innoextract_path()` returns `None`. Is it supposed to be bundled with the deb packages?

**Comment by strycore** [comment]
innoextract should be downloaded on startup and be available in the runtime folder

![image](https://github.com/lutris/lutris/assets/280336/988ae584-f37e-4e17-b1bb-f78a1e7bc88e)


Start Lutris from a terminal and check if the runtime components are downloading correctly.
