### ISSUE TITLE
merge or extracts operations sometimes never ending

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3114]
Hello,
it takes a while I have this issue:
merge or extract operations sometimes never ending and I have to stop/cancel script and relaunch Lutris script.
I can not reproduce this issue each time I install a Lutris script, but it can appear several times in a day.
If I launch Lutris in debug mode, it says nothing, just a normal merge process.
I'm using Ubuntu 20.04 French locale and last official Lutris packages from Launchpad.

**Comment by strycore** [comment]
i have noticed the same thing

**Comment by strycore** [comment]
I'm moving this to 0.5.9 because I don't want it to be a release blocker but if I find a solution to this during QA then I will ship 0.5.8 with a fix

**Comment by legluondunet** [comment]
can not reproduce this issue with 0.5.8 git

**Comment by legluondunet** [comment]
@strycore I can not reproduce this bug with Lutris 0.5.8

**Comment by strycore** [comment]
Me neither, it's safe to close it.
