### ISSUE TITLE
Winetricks Doesn't Install VCrun2019 (and Sometimes Other Components)

### ISSUE THREAD

**Issue by ThisNekoGuy** [lutris/lutris#3116]
**Describe the bug**

Quite often, even if I directly update Winetricks myself for Lutris (use the latest up-to-date system Winetricks), attempting to install vcrun2019 or certain .NET version never works. Even if I run the installer executables myself in the wine prefix, they still refuse to run at all.

**Steps to reproduce**

- Use Latest Lutris Wine
- Winecfg to setup the prefix (I always set it to Win7)
- Launch Winetricks
- Attempt to install vcrun2019 and/or .NET 4.8 or similar
  - Alternatively by selecting INSTALL in Winetricks' uninstaller for a given executable
- Installation never seems to start/complete

**Lutris debugging output (Optional)**

[The terminal output of `lutris -d`.](https://gist.github.com/ThisNekoGuy/1a9f1f0f938f52198269b356aca0bdca)

**System information (Optional)**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/5126949/lutris-issue-report.zip)

**Comment by YihaoPeng** [comment]
This is a winetricks bug, look at this:
https://github.com/Winetricks/winetricks/issues/1596

**Comment by strycore** [comment]
Agreed, if winetricks was updated to a more recent version from the one we ship then this should be sorted with the winetricks project.

**Comment by druidasse** [comment]
> This is a winetricks bug, look at this: [Winetricks/winetricks#1596](https://github.com/Winetricks/winetricks/issues/1596)

So, how can I work around this? I did not have the issue, then reinstalled on a different nvme and now I can't get it to work... I read several reddit post, and the link you've shared but was not able to find a proper solution...

Thanks in advance.

**Comment by danieljohnson2** [comment]
You might download the component you need right from Microsoft (if you can find it!) and then install it using the "Run EXE inside Wine Prefix" command that Lutris offers.

Or maybe check that you need it- Wine has been getting better and better and I find I need winetricks very rarely now.
