### ISSUE TITLE
[Runner] DOSBox has missing dependency libopusfile.so.0 (on Manjaro)

### ISSUE THREAD

**Issue by JHerseth** [lutris/lutris#3118]
DOSBox has missing dependency libopusfile.so.0 (on Manjaro)

Solved it by installing [opusfile](https://www.archlinux.org/packages/community/x86_64/opusfile/).

**Steps to reproduce**

- Install Lutris on Manjaro
- Install DOSBox runner
- try running a dosbox game

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/5138258/lutris-issue-report.json.zip)

**Comment by strycore** [comment]
We now have the technology to let users know of their missing library :sunglasses: 
That said, libopus is something we could ship in the lutris runtime itself.

**Comment by xihnik** [comment]
On Linux Mint this problem too

**Comment by strycore** [comment]
![Screenshot from 2020-09-04 12-05-35](https://user-images.githubusercontent.com/280336/92277121-253e2400-eea7-11ea-88b9-ebcde44f4123.png)
On Pop, if you try to get rid of libopus, you half your OS.

**Comment by strycore** [comment]
Ah no, my mistake. It's libopus.so.0 that causes half the system to be removed.
I added a check for libopusfile.so.0 in the dosbox runner. 

![Screenshot from 2020-09-04 12-11-30](https://user-images.githubusercontent.com/280336/92277548-02f8d600-eea8-11ea-9040-4345d42a96dc.png)

**Comment by JHerseth** [comment]
thats perfect. the worst thing about the "bug" was that it fails silently. So you have to start digging to figure out whats happening.
