### ISSUE TITLE
[Request] Display DXVK downloading in lutris' logs/terminal

### ISSUE THREAD

**Issue by 2str8** [lutris/lutris#3125]
When I tried to open game with multiple DXVK version, it takes about 5 minutes to start game because i need to dl other version of DXVK, what I didn't know, checked lutris' terminal - quite. I suggest to display that required files are downloading in order to start a game in lutris' terminal. The way I got that lutris downloading dxvk - start in linux terminal lutris to see logs

**Comment by YihaoPeng** [comment]
Vote for this. A download progress bar displayed at the bottom of the window is excellent, which will solve people's doubts about "why the game won't start". Especially when Lutris is just installed, there is more than 300MB of runtime to download. In some users, this takes a very long time.

**Comment by strycore** [comment]
DXVK now gets preloaded during startup with the rest of the lutris runtime so you shouldn't experience this delay anymore
