### ISSUE TITLE
a Runner for the Creativision

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#313]
would like to know if this could be added? 

I had the original console but it no longer exist, but still have the games I use to play :smile: 

this is the emu: https://sourceforge.net/projects/creativisionemulator/ tried writing a runner, but my programming languages isn't useful here :stuck_out_tongue:

**Comment by strycore** [comment]
There is a way to run Creativision games with mess by specifying 'crvision' as the machine name. If MESS is not good enough, I'll consider adding a separate runner. 

Can you try it out and see if it looks ok for you?

**Comment by RobLoach** [comment]
Was MESS merged into MAME somewhat recently?

**Comment by strycore** [comment]
kind of, you're thinking about UME (http://mamedev.emulab.it/haze/2012/05/21/ume-0-146-universal-machine-emulator/) which is a single binary for both MAME and MESS. 
Other than that, I think MESS and MAME always were coming from the same codebase (you can see that on the buildbot buildscript)

**Comment by RobLoach** [comment]
https://en.wikipedia.org/wiki/MAME

> MESS, an emulator for many video game consoles and computer systems, based on the MAME core, has been integrated into MAME in 2015.

Thought so.

**Comment by strycore** [comment]
Hmm, so UME is just MAME? I should update both of them anyway, I haven't done that in  a while.

**Comment by telanus** [comment]
the MESS runner doesn't have the creativision as an option. one more request could the creativision and colecovision be added to the gamedb? (pretty please)

And as @ RobLoach stated mess is no more, it's now part of mame. according to wikipedia: More recently, on May 27, 2015, MESS was formally integrated with MAME and became a part of MAME

**Comment by strycore** [comment]
For the MESS/MAME fusion, I'll updated the runners to use an unified one for next release.

Regarding creativision, you can specify the system by entering 'crvision' as the machine, MESS itself supports more than 1000 machine types so only a few of them are listed as an option (I'll add crvision to this list). 

For the GamesDB, you are referring to this I presume http://thegamesdb.net/platforms/ ? If so, I do not have control over this website.  If you are referring to the Lutris website, yes, I can add Creativision as a platform (and it will have an automated MESS installer).

**Comment by telanus** [comment]
> For the GamesDB, you are referring to this I presume http://thegamesdb.net/platforms/ ? If so, I do not have control over this website. If you are referring to the Lutris website, yes, I can add Creativision as a platform (and it will have an automated MESS installer).

was talking about our website :smile:

**Comment by strycore** [comment]
Oh, good! I was confused because the website we use to provide the search field on the game submission form is calling TheGamesDB API ^^
Anyway, I added the Creativision platform along with a default installer. I added a game but I could figure out how to actually start the game :/ 
Other than that, the emulation provided by MESS seems to be good enough that we can avoid adding an extra runner.
Tell me if this seems good enough and if so I'll close the issue.

**Comment by telanus** [comment]
> Other than that, the emulation provided by MESS seems to be good enough that we can avoid adding an extra runner.

I don't know, I find using creativisionemu is much more user friendly and easier to use as mess' creativision emulation.

**Comment by RobLoach** [comment]
> btw here's a better banner for planet defender: http://i.imgur.com/2FlkXtj.png

Updated the banner for ya.

**Comment by telanus** [comment]
Another better image for police jump (creativision): http://imgur.com/kR433xb

going thru my collection and adding games for the system as I make new banners

**Comment by strycore** [comment]
Discussion on how to make this runner better will happen in the 0.4 release cycle, current implementation good enough for 0.3.7.6

**Comment by strycore** [comment]
I actually managed to play Creativision games with MESS as opposed to just launching it, the experience is good enough.
