### ISSUE TITLE
slow game selection change

### ISSUE THREAD

**Issue by veksha** [lutris/lutris#3133]
To reproduce:
Using keyboard try to press down key and hold. UI stops repaint itself for some time.

Expected:
User wants to see row/icon selection change in real-time.

this line can be a culprit:
https://github.com/lutris/lutris/blob/fe01f93f85371e105fa288187e974294f2fab377/lutris/gui/lutriswindow.py#L804

maybe caching is not implemented correctly.

**Comment by strycore** [comment]
The game panel is no more. I've trying reproducing the issue by holding an arrow key and no issue was detected.
