### ISSUE TITLE
avoid Lutris erase all roms from a folder

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3137]
Hello Lutris devs team,
imagine I manually installed a game from a rom file and the rom file located in a folder with others roms/files.
If i delete the game from Lutris library, per default Lutris will delete the folder with all my others roms/files.
I think this is very dangerous to activate this option per default and should be disable per default when folder is not located in the main Lutris "games" folder. 
Another security option would be to move files/folders game to the DE trash.

This change will avoid a lot of sad accidents.

**Comment by byte1024** [comment]
I still need to confirm but recently did a test game using a folder inside my Downloads folder and lost the Downloads folder. Fortunately, I have daily backups done. You reminded me of that.

I believe it was something like add an exe inside the downloads folder to lutris then remove it selecting both. If that does it then it is quite dangerous especially if it was done in an even worse location.

It could be fairly difficult to deal with though as what constitutes a game only folder vs something else.

However, this will probably be fixed if/when they implement remembering of files installed as noted in a different issue.

**Comment by legluondunet** [comment]
@byte1024 like you I had a backup and I culd restore all my others files, to my point of view it is a very dangerous trap.

> It could be fairly difficult to deal with though as what constitutes a game only folder vs something else.

Or lutris dev team could add this rules:
`If game manually installed do not delete files by default?`
`If game folder is not located in the main Lutris games folder, do not delete files by default?`
...

**Comment by strycore** [comment]
We have to add some description of how to find the game files and we have to do it for each runner.
Most runners reference a single file and it is possible to find related files automatically. For example, if the main file is a .cue file, we can reasonably expect to also find a .bin with the same name. There are only a few runners that should be allowed to delete whole folders (linux, wine, dosbox, scummvm...). For runners that support only one or a few file types, we can have a list of accepted extensions for extra validation.

**Comment by byte1024** [comment]
Just to confirm, adding exe direct from Downloads folder then removing and selecting to remove all game files from folder will completely remove the Downloads folder and everything that shouldn't be deleted.

In addition, another offender is that of skipping trash. Just that alone should warrant an immediate change.

**Comment by strycore** [comment]
Manually added games no longer delete any files.
