### ISSUE TITLE
Add some platforms to the website

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#314]
Hi

Just a small request thread: 

1) could the following systems be added (like the creativision, thanx for this)
a) Colecovision 
b) Mattel Aquarius 
c) Apple //
d) Apple IIGS
f) Magnavox Odyssey²
g) Tomy Tutor
h) x680000
i) PC-98
j) Neogeo Pocket
k) Epoch Super Cassette Vision

2) could there be perhaps be a Junior game moderator on the website to help with filling in the detail of games that come from steam, or added without any info? instead of being published onto the website these "fixes" get added back into the queue for acceptance of one of the senior mods?

Another Question:
How will the website handle homebrew games? something like this http://hol.abime.net/4494. I'm not talking hacks but original content

**Comment by Xodetaetl** [comment]
> 2) could there be perhaps be a Junior game moderator on the website to help with filling in the detail of games that come from steam, or added without any info? instead of being published onto the website these "fixes" get added back into the queue for acceptance of one of the senior mods?

Regarding Steam games, no need to lose time doing it manually, we'll be able to scrape all data automatically from the Steam Store API. [Example here](http://store.steampowered.com/api/appdetails?appids=504360)

**Comment by telanus** [comment]
>Regarding Steam games, no need to lose time doing it manually, we'll be able to scrape all data from the Steam Store API
OK didin't know about that :smile: 
But there is this one (and might be more didn't look too hard): https://lutris.net/games/tekken-3/

**Comment by strycore** [comment]
so, obviously, most of the runner requests are going to rely  on MESS. I'll add the platforms to the website as I did for the Creativision.

System names in MESS:
Colecovision > coleco
Mattel Aquarius > aquarius
Apple ][ > apple2
Apple //e > apple2ee
Apple IIgs > apple2gs
Odyssey 2 > odyssey2 (also supported by the o2em runner)
Tomy Tutor > tutor
X68000 > x68000
PC-9801F > pc9801f
NeoGeo Pocket > ngp
Super Cassette Vision > scv

**Comment by strycore** [comment]
There are no junior / senior mods, there are only mods and administrators (which have access to stuff that has nothing to do with game submissions).
I'm currently in the process of improving the way we handle community submissions but we could use some help. Come on #lutris on IRC (Freenode) if you want to discuss about being promoted to moderator.

**Comment by dennisjj5** [comment]
That looks good, except "ngp" for NeoGeo Pocket and "scv" for Super Cassette Vision are less than obvious. Maybe something better for those two? And, why does Apple //e have a system name with two 'E''s? That system name is simply weird.

**Comment by strycore** [comment]
Homebrew games are just games, we could even consider open source games to be homebrew, right? 
So you can treat them as regular games regarding the submissions

**Comment by strycore** [comment]
@dennisjj5 I do not decide what identifiers MESS developers use in their code. I could use neogeo-pocket but MESS would only tell me "what the hell are you on about?" XD

**Comment by strycore** [comment]
What are the differences between the different Apple II models? Is the software made for a particular model incompatible with the other ones? 
There is no need to have all the Apple II variants (and there a lot more of them) if we can just run every software with one model.

**Comment by strycore** [comment]
All platforms added to the website!

**Comment by dennisjj5** [comment]
The Apple //GS is a 16-bit Apple and any 16-bit Apple II games will only run on the IIGS. But, as far as Apple //e vs. the original Apple ][, the //e is almost 100% compatible with all 8-bit Apple ][ software.

**Comment by strycore** [comment]
Ok, so we would only need one 8bit Apple II and one 16bit model (For the 8bit, this would show up as simply Apple II, even if a better model is used internally with MESS)

**Comment by dennisjj5** [comment]
Might as well use the enhanced //e (apple2ee), since some games need the extra RAM (the enhanced //e is 128K, vs 64K for the original //e, and 48K (or less) for the ][ and ][+), plus the available (for hardware, emulators include this) 80-column card (also provides double-res high and low graphics modes)

**Comment by strycore** [comment]
Ok for Apple //e and Apple IIGS then!
