### ISSUE TITLE
Courier of the Crypts Crash (and other 2D games) crash on user input

### ISSUE THREAD

**Issue by Lalarian** [lutris/lutris#3141]
Hello!
I am having trouble with 2D games crashing. For example this happens in  Courier of the Crypts and Baby Is You.
Of all the 3D game I have, none has this problem.
The crash is always triggered on user input. This means, that I can stand doing nothing in the games and the game will run fine.
But when I play the games, after some time they will crash in exacty the moment of a keypress, or a button on a gamepad (Happens with Logitech Cordless Rumblepad 2 and with Dual shock 3 controllers and keyboard).
My other suspicion is, that it might be related to a sound effect being played in result of a user input.
I tried switching many different DXVK versions, inclusing some really old ones, disabled DXVK, switched to use system libraries, toggles Esync/Fsync, tried several Lutris-Wine builds from older ones (like tkg) to the most recent ones (with and without fshack) and tried changing Windows version from 10, through to xp with all in between, but it keeps crashing.
Also the pure System build (5.16) and Proton 5.0 build have this problem when launched through Lutris, while it doesn't crash when ran through Steam.

So, when running these games through Steam (Proton 5.0), they run without crashing (but have another problem there, where the controls get stuck every few seconds, forcing me to release they key or button and pressit again, for moving on).

Here's one crash report:

>
Unhandled exception: page fault on read access to 0x00000010 in 32-bit code (0x004131c3).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:004131c3 ESP:0032fc90 EBP:0032fcc8 EFLAGS:00010212(  R- --  I   -A- - )
 EAX:00a51d58 EBX:017433c0 ECX:0000001c EDX:00000430
 ESI:00000000 EDI:00000004
Stack dump:
0x0032fc90:  7e5f1420 00000001 01768680 00436d72
0x0032fca0:  01768680 01763670 00000000 004b953f
0x0032fcb0:  01768680 01763670 00000000 4017d3b7
0x0032fcc0:  44884310 017660f0 0032fd34 0043678a
0x0032fcd0:  00000001 3ff3c000 c0b49d00 00000000
0x0032fce0:  01763670 00000001 00b1bdcc 01768680
Backtrace:
=>0 0x004131c3 EntryPoint+0xffffffff() in courierofthecrypts (0x0032fcc8)
  1 0x0043678a EntryPoint+0xffffffff() in courierofthecrypts (0x0032fd34)
  2 0x00418541 EntryPoint+0xffffffff() in courierofthecrypts (0x0032fd80)
  3 0x00438bff EntryPoint+0xffffffff() in courierofthecrypts (0x0032fdb0)
  4 0x0041aa8a EntryPoint+0xffffffff() in courierofthecrypts (0x0032fdcc)
  5 0x0047f080 EntryPoint+0xffffffff() in courierofthecrypts (0x0032fde0)
  6 0x00414d7b EntryPoint+0xffffffff() in courierofthecrypts (0x0032fe2c)
  7 0x0041483f EntryPoint+0xffffffff() in courierofthecrypts (0x0032fe84)
  8 0x00425957 EntryPoint+0xffffffff() in courierofthecrypts (0x0032feb4)
  9 0x004e224b in courierofthecrypts (+0xe224a) (0x0032ff20)
  10 0x7b4521c9 in kernel32 (+0x321c8) (0x0032ff48)
  11 0x7b452664 in kernel32 (+0x32663) (0x0032ffd8)
  12 0x7b4521da in kernel32 (+0x321d9) (0x0032ffec)
0x004131c3 EntryPoint+0xffffffff in courierofthecrypts: movl	0x10(%esi),%eax
Modules:
Module	Address			Debug info	Name (57 modules)
PE	  400000-  512000	Export          courierofthecrypts
PE	  520000-  710000	Deferred        fmod
PE	10000000-100c0000	Deferred        sdl2
PE	3b400000-3b441000	Deferred        steam_api
PE	62aa0000-62af9000	Deferred        glew32
PE	7a840000-7a849000	Deferred        opengl32
PE	7b020000-7b03c000	Deferred        kernelbase
PE	7b420000-7b5f1000	Export          kernel32
PE	7bc30000-7bc47000	Deferred        ntdll
PE	7c550000-7c571000	Deferred        msvcr120
PE	7c630000-7c63a000	Deferred        concrt140
PE	7c650000-7c654000	Deferred        api-ms-win-core-localization-l1-2-1
PE	7c670000-7c676000	Deferred        uxtheme
PE	7c6d0000-7c6d4000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7c6f0000-7c6f4000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7cf50000-7cf55000	Deferred        winex11
PE	7d0d0000-7d0d4000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	7d0e0000-7d0e6000	Deferred        api-ms-win-crt-string-l1-1-0
PE	7d100000-7d104000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	7d110000-7d117000	Deferred        api-ms-win-crt-math-l1-1-0
PE	7d130000-7d134000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	7d140000-7d145000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	7d150000-7d154000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	7d160000-7d165000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	7d180000-7d186000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	7d1d0000-7d1fd000	Deferred        msvcp140
PE	7d2c0000-7d2ca000	Deferred        msacm32
PE	7d2f0000-7d2f7000	Deferred        iphlpapi
PE	7d350000-7dc4c000	Deferred        shell32
PE	7dd70000-7dd74000	Deferred        api-ms-win-crt-time-l1-1-0
PE	7dd80000-7dd85000	Deferred        vcruntime140
PE	7dda0000-7dda7000	Deferred        ws2_32
PE	7dde0000-7dde7000	Deferred        wsock32
PE	7de20000-7de2e000	Deferred        oleaut32
PE	7df30000-7df34000	Deferred        usp10
PE	7df90000-7dfe6000	Deferred        comctl32
PE	7e0d0000-7e0da000	Deferred        aclui
PE	7e110000-7e13d000	Deferred        ole32
PE	7e260000-7e266000	Deferred        shcore
PE	7e280000-7e292000	Deferred        shlwapi
PE	7e2e0000-7e2e6000	Deferred        imm32
PE	7e320000-7e32e000	Deferred        gdi32
PE	7e470000-7e47d000	Deferred        rpcrt4
PE	7e500000-7e50d000	Deferred        advapi32
PE	7e5a0000-7e5c8000	Deferred        ucrtbase
PE	7e6a0000-7e6b9000	Deferred        setupapi
PE	7e740000-7e834000	Deferred        user32
PE	7e950000-7e9d0000	Deferred        winmm
PE	7efe0000-7efe5000	Deferred        version
PE	7eff0000-7eff3000	Deferred        wow64cpu
PE	f51e0000-f51e5000	Deferred        msctf
PE	f7320000-f7325000	Deferred        hid
PE	f7340000-f734c000	Deferred        dinput8
PE	f7960000-f7965000	Deferred        xinput1_4
PE	f7990000-f7994000	Deferred        winepulse
PE	f79d0000-f79d5000	Deferred        mmdevapi
PE	f7a00000-f7a05000	Deferred        dsound
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Program Files\Courier of the Crypts\CourierOfTheCrypts.exe
	["C:\Program Files\Courier of the Crypts\CourierOfTheCrypts.exe"]
	00000009    0 <==
	00000061    0
	00000062    0
	00000063    0
	00000064    0
	00000065   15
	00000066    0
	00000067    2
	00000068    0
	00000069    2
	0000006a    0
	0000006b    0
	0000006c    1
	0000006f    0
0000000e services.exe
	0000000f    0
	00000010    0
	00000013    0
	0000001a    0
	0000001f    0
	00000024    0
	00000027    0
00000011 plugplay.exe
	00000012    0
	00000016    0
	00000017    0
00000018 winedevice.exe
	00000019    0
	0000001b    0
	0000001c    0
	0000001d    0
	0000001e    0
	00000020    0
	00000023    0
00000021 winedevice.exe
	00000022    0
	00000025    0
	00000026    0
	00000028    0
0000002b explorer.exe
	0000002c    0
	00000031    0
	00000032    0
	00000033    0
00000070 explorer.exe
	00000071    0
	00000072    0
	00000073    0
	00000074    0
System information:
    Wine build: wine-5.7.r0.g2ad422ff ( TkG Staging Esync Fsync Vkd3d )
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.7.19-2-MANJARO
`

This problem started some months, ago. so maybe it's related to an Manjaro update. I don't know how to fix this, so please help :)

**Comment by byte1024** [comment]
This should be coming from wine. Proton has its own changes on top of wine so not really comparable which is why it's called proton. There would be no reason to call it proton if it were the same.

Could be missing wine packages in your system though or newer wine version breaks it.

Lutris doesn't guarantee that anything won't be missing and can't guarantee newer wine versions will not have regressions.

**Comment by byte1024** [comment]
The backtrace (error) looks to be originating from Wine. I've done a lot of testing Wine through Lutris to know its probably not Lutris. It could be possible to say its Lutris as you're going through Lutris so they should fix it but Wine is Wine and that isn't technically Lutris.

Point in fact, I've seen problems using System Wine that don't show up with Lutris wine because they are different. Lutris wine adds some things on top of Wine which solves some problems that regular Wine may have and so using System Wine requires some re-working of the game/application setup and/or system packages over Lutris.

Its a pain, but I really would do a ton more testing with this if I were you. Its easy to mistake Lutris as being the problem since its in the way. I do it too, and sometimes we might even think Lutris should do something but that's up to them really.

**Comment by byte1024** [comment]
On top of that, Valve is a bit different. They work with Code Weavers who do a lot of work on Wine.

And I can't seem to find anyone trying to play Courier of the Crypts outside of Steam so, you might need to post it to one of the Wine issue areas eg If you test it using Syteam wine, get a log from that and post it to wine official.

**Comment by Lalarian** [comment]
The reason I tried playing it outside Steam is, that in Steam using Proton 5.0 there's this problem with controls:
Every few seconds the character won't move anymore, and I have to release the key and press it again for him to move on.
So there might be a relation, that maybe everytime when the character gets stuck using Steam, the game instead crashes when using Lutris. But of course these might aswell be two different problems, either.
From my understanding it seems to effect SDL games and is not related to graphics.
Sadly that's the most information I could gather in regards to encircle the issue, yet.
It would be very helpful, if I had a rough orientation on which technical aspect I got to search for the issue.

**Comment by byte1024** [comment]
Haven't tried it but this may work (see the answer photos which show sound=disable) https://askubuntu.com/questions/77210/how-to-change-the-default-audio-in-wine-to-alsa-only

If you're doing a full log, it will probably be too excessive and require grepping through it assuming you get it and it doesn't fail.

I actually use two other medium variations but not with the computer right now to say what exactly they are. One style you can find in the Steam Proton dir or somewhere around there but you will need to know how to edit Lutris source code and insert them.

The Lutris debugging ones aren't great really. Enabled is too little and all is often too heavy.

**Comment by Lalarian** [comment]
Thank you! I will try the sound disabling tomorrow. You are right about the full debugging lo. I just cancelled, because after haldn an hour the game's main menu wasn't even loaded. And the 'Enabled' option didn't say more than the very first line of that crash windows I posted before.

**Comment by byte1024** [comment]
```
(_("Proton style"), "+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree"),
(_("Alt"), "+all,-heap,-relay,-seh,-snoop,-message,-mscoree,-loaddll,-module,-resource,-nls,-crypt,-cryptasn"),
```
Add it to this file: https://github.com/lutris/lutris/blob/master/lutris/runners/wine.py

like so

```
...
(_("Full (CAUTION: Will cause MASSIVE slowdown)"), "+all"),
(_("Proton style"), "+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree"),
(_("Alt"), "+all,-heap,-relay,-seh,-snoop,-message,-mscoree,-loaddll,-module,-resource,-nls,-crypt,-cryptasn"),
],
```

**Comment by Lalarian** [comment]
Thanks!
The Proton-Variant is working great. It doesn't help me much with finding the problem, though.

63001.619:0008:0009:fixme:thread:RtlCreateUserThread stack_commit != 0 is unimplemented
63008.628:0008:0009:fixme:thread:RtlCreateUserThread stack_commit != 0 is unimplemented

##########CRASH!#######################################

63119.393:0008:0009:trace:seh:raise_exception code=c0000005 flags=0 addr=0x4131c3 ip=004131c3 tid=0009
63119.393:0008:0009:trace:seh:raise_exception  info[0]=00000000
63119.393:0008:0009:trace:seh:raise_exception  info[1]=00000010
63119.393:0008:0009:trace:seh:raise_exception  eax=00a51d58 ebx=018533c0 ecx=0000001c edx=00000430 esi=00000000 edi=00000004
63119.393:0008:0009:trace:seh:raise_exception  ebp=0032fcc8 esp=0032fc90 cs=0023 ds=002b es=002b fs=0063 gs=006b flags=00010212
63119.393:0008:0009:trace:seh:call_stack_handlers calling handler at 0x4e25ef code=c0000005 flags=0
63119.393:0008:0009:trace:seh:call_stack_handlers handler at 0x4e25ef returned 1
63119.393:0008:0009:trace:seh:call_stack_handlers calling handler at 0x4e238e code=c0000005 flags=0
63119.393:0008:0009:trace:seh:call_stack_handlers handler at 0x4e238e returned 1
63119.393:0008:0009:trace:seh:call_stack_handlers calling handler at 0x4e2ad0 code=c0000005 flags=0
63119.393:0008:0009:trace:seh:call_stack_handlers handler at 0x4e2ad0 returned 1
63119.393:0008:0009:trace:seh:call_stack_handlers calling handler at 0x4e1a0b code=c0000005 flags=0
63119.393:0008:0009:trace:seh:_except_handler4_common exception c0000005 flags=0 at 0x4131c3 handler=0x4e1a0b 0x32f96c 0x32f92c cookie=242a3a09 scope table=0x4f6658 cookies=-2/0,-52/0
63119.393:0008:0009:trace:seh:_except_handler4_common level 0 prev -2 filter 0x4e173b
63119.394:0008:0009:trace:seh:_XcptFilter (c0000005,0x32f848)
63119.394:0008:0009:trace:seh:_except_handler4_common filter returned CONTINUE_SEARCH
63119.394:0008:0009:trace:seh:_except_handler4_common reached -2, returning ExceptionContinueSearch
63119.394:0008:0009:trace:seh:call_stack_handlers handler at 0x4e1a0b returned 1
63119.394:0008:0009:trace:seh:call_stack_handlers calling handler at 0x7b46b130 code=c0000005 flags=0
wine: Unhandled page fault on read access to 00000010 at address 004131C3 (thread 0009), starting debugger...
63119.394:0008:0009:trace:seh:start_debugger Starting debugger L"winedbg --auto 8 668"

From there it's same as the standard crash log.

The 'Alt' choice doesn't work for my PC, maybe there's not enoguh processign power. but thanks to your help I now know about the Wine "debug channels" and will try to filter it down until it's working, usig this site https://wiki.winehq.org/Debug_Channels

**Comment by Lalarian** [comment]
I have done some experimenting with different debug-logging filters. At one point I saw some Steam-calls, despite I of course wasn't running the game through Steam.
Is it possible that there's kind of a protection, or that features lilke this achievement stuff (which I don't need) could cause the crash, if the game isn't run through Steam?

**Comment by byte1024** [comment]
Maybe. Debugging Wine is a whole nother world. Many things are not as they seem in wine logs and so often the problem isn't immediately obvious.

Personally, I would only pick out "wine: Unhandled page fault on read access" from above but it doesn't really do much to solving it.

A bunch of it just looks to be crash related so it doesn't look to be very useful. Much of what could be useful is just address info and doesn't really spell anything out or nothing there is a problem with successfully running the game and the problem might not yet even be found or easily understood.

Wine is a complicated beast.

**Comment by byte1024** [comment]
Seems the game is heavily based on sdl https://www.reddit.com/r/AMA/comments/2n71la/i_am_the_solo_developer_on_the_courier_of_the/

So would probably look in that direction. The preview demo doesn't appear to be available anymore so I can't really help much further.

Its possible that Steam/Proton through Steam may load different library/package versions than outside of it or something along those lines. Just hard to say.

**Comment by Lalarian** [comment]
Yes, I have seen many SDL2 related lines in some of the logging configs I tried. At least I am not the only one who can't do much with ll these adresses and codes xD
I hoped to find something like a library being the reason, so an easy solution could have been to supply this natively.
In the meantime I have finally got it to run decent from Steam (no idea what the problem with controls really was, but after disabling and enabling some controller related options it's OK now.)
But I will experiment some more.

**Comment by byte1024** [comment]
A note that there should be various sdl library versions in various places. Since it relies heavily on it, maybe the .10, .9, .8, etc versions will have different effect. I've never really looked into that before so not sure. Steam shows a .10 possibility. Lutris might not be using that one. Lutris looks like it might use .0 or .8

$ locate libSDL2-2.0.so.0

https://discourse.libsdl.org/c/sdl-announcements/

Might make a difference. However, don't know if that's even related to the problem you're having here.

**Comment by Lalarian** [comment]
Hello!
I found that Steam's SDL2 lib version goes up to 0.10, while the latest Lutris 5.7.9 I have installed, goes up to 0.9
So I copied to 0.10 from steam into the Lutris lib folder. I didn't help and still crashed. I don't know if the 0.10 would even get loaded by the executeable, or if I have to do additionals changes (like overwriting the lower version files and the master lib file, too)
But during this test I made an observation that might help in closing in the issue:
The crash occured exactly when I was walking over a rat, which usually makes a squishing sound in Steam. I could reproduce this behavious. So I copied the whole Proton5 folder to the directroy of Lutri's builds and chose it as the runner for CotC - and it works!
So ye,s we are on the right track here and I really suspect one (or multiple) of the sound related libs there.
The strange this is, that Lutris of course offered the Proton 5.0 build (from it's original path in Steam) and the game crashed when I tried this, too...

**Comment by byte1024** [comment]
Good find :-)

In theory anyway (and should be in practice as well), copying vs just using shouldn't make a difference unless there's a bug or problem with something. That may require debugging what is happening.

**Comment by Lalarian** [comment]
Thank you for your help! I got lost in playing the game. Learned a bit about identifying problems using the logs and maybe, if I find the time, I will return with more info on this specific issue, for improving Lutris!
I will close this as solved now, because obviously the game is running and I don't want to increase the pile of unsolved issues even more :)
