### ISSUE TITLE
Epic games launcher does not open.

### ISSUE THREAD

**Issue by LinoBigatti** [lutris/lutris#3146]
**Describe the bug**

The epic games launcher stops inmediately after starting, the error code is 13568

**Steps to reproduce**

- Install lutris
- Install epic games launcher
- Open epic games launcher

**Lutris debugging output (Optional)**

``lutris -d``
https://gist.githubusercontent.com/LinoBigatti/5822bfee2c91b0fc0e0090e345c02401/raw/6f899224ad0fe143471aec2fd3e868c399359f66/lutris_-d_output.txt

``game logs with wine debug``
https://gist.githubusercontent.com/LinoBigatti/5822bfee2c91b0fc0e0090e345c02401/raw/6f899224ad0fe143471aec2fd3e868c399359f66/wine_debug_logs.txt

**System information (Optional)**

https://gist.githubusercontent.com/LinoBigatti/5822bfee2c91b0fc0e0090e345c02401/raw/6f899224ad0fe143471aec2fd3e868c399359f66/lutris-issue-report.json

**Comment by byte1024** [comment]
The only relevant lines I can see:
```
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0009:err:module:load_so_dll failed to load .so lib "/home/lino/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/../lib/wine/wldap32.dll.so": libp11-kit.so.0: wrong ELF class: ELFCLASS64
0009:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe") failed (error c000007a).
```

I believe you're missing required package(s). You probably need to install wine-ldap 32 bit and 64 bit packages or maybe some other ldap one and maybe others if you still have a problem.

Lutris for whatever reason the devs feel that they aren't responsible for missing packages despite "shipping" wine with Lutris so this should be closed unless they change their mind.

Depending on the games you play you will probably also be missing other wine packages. So you can cherry pick the distro wine packages to install that have no dependencies or you do a full distro wine install to get all in one shot and minimum fuss.

Have fun lol.

**Comment by strycore** [comment]
> Lutris for whatever reason the devs feel that they aren't responsible for missing packages despite "shipping" wine with Lutris so this should be closed unless they change their mind.

Lutris explicitely recommends installing the system version of wine precisely to provide those dependencies. We have checks in the client to make sure system version is installed. Not every library can be included in the lutris runtime in a way that works on evry linux distro so we have to rely on some libraries being present.

What I want to do is use our new library detection system, remove the check for system wine and just straight up refuse to launch wine until all the dependencies are satisfied. We got to many people believe they can just ignore the system wine recommendation and still have games working.

**Comment by LinoBigatti** [comment]
Thanks, I found out legendary can work as the epic games launcher and it is open source and such, so probably gonna leave this issue as is if someone who can reproduce it wants to pick it up. The info on packages is good to know tho, will surely help.
