### ISSUE TITLE
Lutris deleted my entire Desktop folder

### ISSUE THREAD

**Issue by coomac** [lutris/lutris#3147]
Incompletely installing a game with an installer.exe downloaded from the game producer's website sets the game folder as the location where the exe is saved instead of the wine prefix or even the working prefix. This means that if you hit the Remove icon and then Apply without paying attention, the folder the installer.exe is saved in gets deleted since the option to delete the game folder is selected by default. I'm currently on lutris 0.5.7.1 and just discovered this bug the hard way as the title says. I only started using lutris again after a break of several months and this wasn't the behavior in the versions I used previously.

To reproduce:

Download an exe from the producer's website
Select Add Game
On the Game Info tab > enter a name and select Wine as the Runner
On the Game Options tab > select the installer.exe as the Executable, set a different location for the Working Directory and the Wine Prefix
Hit Save (note that if you click the Remove icon here, the game folder is the location of installer.exe)
Hit Play and let the launcher installation complete
If you click the Remove icon after the launcher is installed, the game folder is still the location of installer.exe
Even if you select an executable in a different location (such as launcher.exe under the wine prefix), the location of installer.exe remains the game folder

The expected behavior is that the game folder should be the wine prefix
Previously, once I hit Play to install installer.exe, the option to remove all data from the game folder became greyed out. This worked fine as well.

Edit: Oops I just noticed this sounds pretty similar to issue #3137

**Comment by byte1024** [comment]
Yeah its kind of a duplicate in that the other was issued in different words / idea but its the same problem in the end. There's yet another one on a similar topic as well with multiple games in one folder and that is basically the same problem as well in the end.

I'm waiting for someone to delete their entire home folder. Its going to happen at some point if it continues.

**Comment by strycore** [comment]
> I'm waiting for someone to delete their entire home folder. Its going to happen at some point if it continues.

It has already happened in the past and we now have code that prevents it.

**Comment by byte1024** [comment]
At least that's a positive. Good to hear :-)

**Comment by RandomElephant** [comment]
Nothing really new to add but I had to comment. 
I haven't updated Lutris in a month and managed to delete 50gb worth of my Downloads folder just now, not paying attention. Not angry, just disappointed.

**Comment by legluondunet** [comment]
Strycore, what do you think about a simple condition:
if game is manually installed or if game folder located out of main Lutris game golfer
--> do not remove data is default.

**Comment by strycore** [comment]
yep, sounds like a sane solution.

**Comment by RandomElephant** [comment]
Just to explain my scenario better - I made the path to exec be my installation file located in my Downloads folder, but I made a typo in the game name (leading to Lutris not automatically assigning icon and thumbnail), so I proceeded to remove the game to simply re-enter it and ofc I left remove data checked. 
I don't know why I did that, as I didn't even begin the installation, but I did. 
I don't know if there's a easy way to prevent this from happening, other than me not being dumb and actually reading what I'm about to do before doing it, but I thought I'd share my mishap just so you know what can happen to users. :)

**Comment by Martina-Neumayer** [comment]
Damn it! It just happened to me. That same thing. I just want to remove a game - an exe file placed on my desktop and this damn app erased my entire desktop with all folders and files. What a mess! :/ No warnings are, no confirmations just puff and all is gone after pressing a "delete" key on one particular game.
Files should be moved to the trash bin as usual on my Arch system, not to be deleted permanently!
It is a very pitty problem in the lutris app imho.

**Comment by strycore** [comment]
This is no longer possible with the current behavior
