### ISSUE TITLE
Disable desktop effects and pre launch/post exit scripts not working for Steam runner

### ISSUE THREAD

**Issue by tralph3** [lutris/lutris#3149]
**Describe the bug**

When using the Steam runner, the Disable desktop effects option and the pre launch script and post exit scripts are not working. I've tested it on Insurgency and ISLANDERS. I'm unaware if the issue is exclusive to my DE or distro (Manjaro 20.1 XFCE 4.14) or if other options are also not working under the Steam runner.

**Steps to reproduce**

- Put a custom script that spits its output into a file (to see if it ran, echo should do the trick).
- Set the script to run at pre-launch.
- Run any game with the Steam runner.
- Check the file to see if it outputs anything.

You may change the runner to Linux and direct lutris to the game launcher (if it's a native game). Then you can do the same test and see that it worked.

**Lutris debugging output (Optional)**

Here's the output of lutris -d with the Steam runner, and the Linux one. I had two scripts, one for disabling the desktop compositor, and another for enabling it when the game exits (called turn-off-compositor.sh and turn-on-compositor.sh respectively). This should not be needed, as "Disable desktop effects" should do the same thing already, but it wasn't working, so I wanted to try this way.

[steam-runner.txt](https://github.com/lutris/lutris/files/5244165/steam-runner.txt)
[linux-runner.txt](https://github.com/lutris/lutris/files/5244154/linux-runner.txt)

**System information (Optional)**

```
[System]
OS:              Manjaro Linux 20.1 Mikah
Arch:            x86_64
Kernel:          5.8.6-1-MANJARO
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  3.0 Mesa 20.1.7
OpenGL Core:     4.2 (Core Profile) Mesa 20.1.7
OpenGL ES:       OpenGL ES 3.0 Mesa 20.1.7
Vulkan:          Supported
```

**Comment by strycore** [comment]
Steam games are now correctly tracked so this should work as expected
