### ISSUE TITLE
Not all steam games get added to your account when syncing 

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#315]
Something that I picked up today, I synced my Steam account a few times already (when adding new games to steam) and found today that like Tomb raider II doesn't get picked up by the syncing and I have it from 2013. Same happens with Tomb Raider III. 

Don't know if it has anything todo with the bundle I bought back in 2013. Got the bundle with the Winter-sale, and know that when Tomb Raider 2013 was released on Linux, there was a struggle with that bundle

**Comment by strycore** [comment]
Can you recreate that issue here? https://github.com/lutris/website/issues 
This does not affect the client.
