### ISSUE TITLE
DXVK Breaks when Proton-GE is used

### ISSUE THREAD

**Issue by TheWranger** [lutris/lutris#3152]
**Describe the bug**

Games do not open if DXVK is enabled and Proton-GE Is being used

**Steps to reproduce**

- Create a new game in Lutris with Wine as the runner
- Set Proton-5.9-GE-6-ST as the Wine version
- Makes sure DXVK is enabled
- Attempt to run the game

**Lutris debugging output (Optional)**

Doesn't display any error in the log, the game just doesn't open

**Comment by strycore** [comment]
Since Proton is not an officially supported wine build, I'm going to close this. Also, I've not experienced the issue. Proton has worked whether the DXVK option was checked or not
