### ISSUE TITLE
Lutris overrides wine windowed desktop titles

### ISSUE THREAD

**Issue by simifor** [lutris/lutris#3155]
**Describe the bug**
When you enabled windowed desktops, the default title for the window becomes WineDesktop, however this can be changed in the registry, however when using lutris the title gets changed back (which doesn't happen when launching the game from the terminal)

**Steps to reproduce**

- Open the registry and navigate to HKEY_CURRENT_USER/Software/Wine/Explorer
- Change Desktop key value to the desired title
- Go to HKEY_CURRENT_USER/Software/Wine/Explorer/Desktops and rename the key name WineDesktop to the title you used in the last step.
- Launch the game throguh lutris
- Desktop (inside HKEY_CURRENT_USER/Software/Wine/Explorer) value get's change to WineDesktop, and the key WineDesktop reappears (inside HKEY_CURRENT_USER/Software/Wine/Explorer/Desktops).

**Comment by simifor** [comment]
I played a bit with lutris and removed what changed those things in the registry, it's working fine in an existing game installation that had already been set to use windowed desktop, I'd need to test with new games that weren't set to used windowed wine to make sure my changes don't break anything even if I don't expect them to.

Though, if possible I'd like to know if there were any particular reasons to have this set on lutris, a reason why devs wouldn't want this changed, otherwise I might open a PR for this when I have more time (and it's beent ested more).

**Comment by simifor** [comment]
It's been a while since I haven't been playing games as of late, my solution won't work with new games as it won't set all the necessary regedit values needed for windowing. I think the best solution will have to be having a textfield for the desired name and checking for it to replace WineDesktop.

**Comment by strycore** [comment]
closing because I don't see why you would change the name of the wine desktop to begin with
