### ISSUE TITLE
Feature Request: Implement comprehensive sync system with all popular gaming platforms

### ISSUE THREAD

**Issue by BeatLink** [lutris/lutris#3157]
Lutris could build on its existing sync capabilities by integrating sync modules for other popular game platforms. These sync systems (just like the steam version) would allow users to track, catalog, install and uninstal their games from one centralized location, even if it hasn't been installed to their system

Here's some suggestions to start
* Steam (Done)
* GOG (Done)
* Humblebundle (Done)
* Epic Games
* Origin
* Itch.io
* ARC games
* IGDB
* RAWG
* Battle.net
* UPlay

**Comment by BeatLink** [comment]
For some inspiration you could check out:

* Playnite
* Gamehub (elementary os)

**Comment by strycore** [comment]
We now have a more integrated solution which removes the need to sync anything. It's now only required to login to the service and games will appear in the main UI.
We already have some tickets for pending services like EGS. Origin, Uplay and Battle.net. There are also plans to add support for MAME and Itch.io. We can add more services as time goes. It is likely that we'll get all the 3rd party integrations GOG galaxy has.
Going to close this to keep each service implementation in its own ticket.

**Comment by BeatLink** [comment]
That should cover the bases, I didnt know which issues existed or not, or if the existing issues were speaking to account integration and syncing specifically or just the runners. I hope this isn't seen as too spammy. If it is, I apologize in advance. I just think being able to sync games from as many online game libraries as possible will do so much to make lutris the best gaming platform on linux.
