### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'present'

### ISSUE THREAD

**Issue by Anequit** [lutris/lutris#3161]
**Describe the bug**
While starting lutris I'm greeted with an error

**Steps to reproduce**

- Run lutris through terminal 
-
-

**Lutris debugging output (Optional)**

The terminal output of `lutris -d`.

INFO     2020-09-29 10:57:37,490 [application.do_command_line:219]:Running Lutris 0.5.1.3
INFO     2020-09-29 10:57:37,490 [startup.check_driver:55]:Using NVIDIA drivers 450.66 for x86_64
INFO     2020-09-29 10:57:37,490 [startup.check_driver:59]:GPU: GeForce GTX 1060 3GB
INFO     2020-09-29 10:57:37,491 [startup.check_driver:74]:GPU: 10DE:1C02 103C:82FC using nvidia drivers
INFO     2020-09-29 10:57:37,514 [startup.check_vulkan:113]:Vulkan is supported
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 172, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 100, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 287, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 117, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 335, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information (Optional)**
I'm running parrot0s

**Screenshots (Optional)**

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by skriptmonkey** [comment]
Looks like you're running version 0.5.1.3. Are you able to upgrade to a newer version and give that a try?

**Comment by strycore** [comment]
Please upgrade. 0.5.1 is long unsupported.
