### ISSUE TITLE
Browse files does not work on some games in my library

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [lutris/lutris#3163]
On some games in my library, the "Browse Files" button does not work as intended.
One game for example: 
![Screenshot from 2020-09-30 20-48-41](https://user-images.githubusercontent.com/38913802/94687154-6fa7a900-035e-11eb-8ed2-0daba7f6aecf.png)
but when I click on the Browse Files button, this happens:
![Screenshot from 2020-09-30 20-48-55](https://user-images.githubusercontent.com/38913802/94687221-8ea63b00-035e-11eb-884d-38edaa26e60f.png)

Another game, this time using wine runner:
![Screenshot from 2020-09-30 20-33-22](https://user-images.githubusercontent.com/38913802/94687277-a7aeec00-035e-11eb-8ffb-7626180757d3.png)
but when I click on the Browse Files button, this happens:
![Screenshot from 2020-09-30 20-33-35](https://user-images.githubusercontent.com/38913802/94687336-b5647180-035e-11eb-9f3d-bab36d2ced6e.png)

I need to mention that lutris was working in perfect condition before but after one of the updates, all these started happening.

**Steps to reproduce**

Install a game, click on browse files button

**System Info**
```
[System]
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.4.0-48-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.4 GB
Swap:            1.7 GB

[Graphics]
Vendor:          X.Org
OpenGL Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.38.0, 5.4.0-48-generic, LLVM 10.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 20.0.8
OpenGL Core:     4.6 (Core Profile) Mesa 20.0.8
OpenGL ES:       OpenGL ES 3.2 Mesa 20.0.8
Vulkan:          Supported
```

**Comment by strycore** [comment]
in lutris 0.5.8, it will be possible to set the correct game location with the "Move" button
![Screenshot from 2020-10-19 07-39-01](https://user-images.githubusercontent.com/280336/96465771-2ff61380-11de-11eb-8acc-01a64199ee37.png)
