### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by codeman101** [lutris/lutris#3166]
I searched about dark mode not working and found a reddit post suggesting to change th GTK theme on the system. I changed my GTK 2 and 3 theme to every available option but it never triggered.

**Comment by byte1024** [comment]
Can you run "lutris -d" from terminal and is there an error related to dark mode, UI, or something there?

I run only dark mode on 2 different distro's and have seen no problem doing so. Am thinking this is some weird user OS issue. But, at the same time, haven't looked at the git changes for a while now - I just don't think its with Lutris however.

**Comment by strycore** [comment]
This is an issue with your Linux desktop. Lutris uses standard dark theme features from Gtk.
Change your Gtk theme to one that supports a dark variant.

**Comment by codeman101** [comment]
@strycore 
I did. I tried setting the GTK 2 and 3 to adwaita-dark and breath dark. Neither worked.
