### ISSUE TITLE
Lutris doesn't show import for Steam games outside original library path.

### ISSUE THREAD

**Issue by 3vi1** [lutris/lutris#3168]
- If Steam games are installed to ~/.steam/.steam, they show as available in the Lutris Import Games list.
- If you've defined another library folder as your default steam path (/data/steam, an external 2TB drive, in my case), none of the installed games will be available for import.

These images show how the Lutris import shows that there are no available Steam game on my system - though there are 472 games installed in my steam-defined-default library path.

![Empty Import List, 400+ games installed](https://i.imgur.com/8rgZDvD.png)

![Games installed in a different path that has been set as default](https://i.imgur.com/am4oMSH.png)

Perhaps Lutris could check the Steam runner's "Default installation folder" and let us override the path there, if it can't detect all Steam Library paths automagically?  It seems like this would be a very common problem for those of us that don't want to fill up our fast SSD /home partitions, yet keep a lot of games installed to avoid re-downloading.

Thanks.

**Comment by strycore** [comment]
Steam games are now fetched from the API

**Comment by 3vi1** [comment]
Hmmm... still doesn't appear to work (tested with current git version).

Command line output shows:
```
20:22:21 evil@H510 ~/src/lutris/bin» ./lutris 
Unable to load locale dir, translations won't work.
2020-10-28 20:22:23,565: Lutris 0.5.7.1
2020-10-28 20:22:23,565: Using NVIDIA drivers 455.28 for x86_64
2020-10-28 20:22:23,565: GPU: GeForce RTX 2070 SUPER
2020-10-28 20:22:23,565: GPU: 10DE:1E84 3842:2072 (nvidia drivers)
2020-10-28 20:22:29,342: Config key mostrecent not found in AccountName, PersonaName, RememberPassword, Timestamp, WantsOfflineMode
2020-10-28 20:22:29,342: Unable to find SteamID from Steam config
2020-10-28 20:22:42,730: Steam games are already loading
```
The Steam list still shows "No Games Found".  I noticed the message says "loading" and not "loaded", so I waited five minutes, but it still shows "No Games Found" and has no indication that it's loading anything.

**Comment by 3vi1** [comment]
I added some debug logging in read_user_config and found that Lutris was using ~/.steam/ as the data dir instead of ~/.steam/steam.  This was because an old ~/.steam/steamapps subdirectory did exist.  I've had steam installed since the very first days, so that's probably old cruft from before the path changed on Ubuntu.

It could probably be avoided by moving ~/.steam/steam higher in the path than ~/.steam, but there are probably few people that have a really old steam install like I do.  So, it's not a big deal.

After clearing the old junk, I can confirm it's now loading the Steam games.  Thanks!

**Comment by 3vi1** [comment]
Whoops... noticed something that is still wrong:  While Lutris now lists all my steam games, it does not think any of them are actually installed; they are all greyed and showing the install option at the bottom of the screen.
