### ISSUE TITLE
Add option to import games from Origin

### ISSUE THREAD

**Issue by BeatLink** [lutris/lutris#3173]
It would be great if Lutris would allow users to sign into their origin account and sync their games library from that platform. 

As per the response from https://github.com/lutris/lutris/issues/3157, it was recommended to have individual tickets for the various game libraries and platforms. This ticket is to track origin integration specifically. If this a duplicate issue, please feel free to link it and close this one.

**Comment by strycore** [comment]
Closed as duplicate of #808
