### ISSUE TITLE
Allow Steam native and wine to run at the same time

### ISSUE THREAD

**Issue by SFort** [lutris/lutris#3181]
You currently can't run steam nativley and under wine simultaneously
see [steam-for-linux/4412](https://github.com/ValveSoftware/steam-for-linux/issues/4412)
in the issue a solution is shown, could the Wine steam runner implement it by default or optionally?

**Comment by byte1024** [comment]
It fully depends if the issue must be fixed within Steam application code or not. On the Wine side, it might be possible to fake/change the network connection to something that doesn't conflict.

But, Valve could have code in Steam for any reason to check eg the computer name to obtain a successful connection and it can't be duplicate (who knows).

**Comment by strycore** [comment]
It is no longer needed to run steam in wine and we are going to delete the wine steam runner.

**Comment by SFort** [comment]
@strycore Running steam in wine is clearly still usefull for issues like the one linked
besides that it's also generally more stable with less glitches then proton for certain games
(I'm assuming that is why your removing the wine steam runner since you didn't specify a reason)

**Comment by SFort** [comment]
@byte1024 The reason for having two versions of steam open is so you can run 
steam chat and other features nativley(since they don't work under wine steam)
while being able to run games that won't launch outside of wine steam

**Comment by byte1024** [comment]
> @byte1024 The reason for having two versions of steam open is so you can run 
> steam chat and other features nativley(since they don't work under wine steam)
> while being able to run games that won't launch outside of wine steam

I believe other Wine versions can be used with Steam  anyway instead of Proton.

Either way, if Lutris can get the game from steam its still rather very minimal. I view changing the tactic as more worthwhile than fitting things to the tactic.

**Comment by strycore** [comment]
Until proven otherwise, Proton is just as capable as WineSteam.
WineSteam has been increasingly glitchy and unusable over time, we strongly that anyone still using it migrate their games to Proton and stop using WineSteam as fast as possible.

**Comment by SFort** [comment]
@strycore 
[Proton/3886](https://github.com/ValveSoftware/Proton/pull/3886)
It compleatly prevent's some games from booting, outside of wine steam.

If by wine steam has been glitchy you surely don't mean the games 
There are several seasure enducing bugs that occur when running rust with proton on mesa/amd like rainbow colored water(they don't on wine steam)

I do belive the steam part of wine steam has been glitchy as several of it's components don't work under wine
which is why i submitted this issue in the first place as those componets would not matter if this workaround was used
