### ISSUE TITLE
Don't show Lutris after quit a game

### ISSUE THREAD

**Issue by Philippe734** [lutris/lutris#3187]
Feature request
Actual state:
When Lutris works fine, after quit or exit a game (started from Lutris), Lutris appears and show up. We have to close Lutris.
Desire state:
When quit or exit a game (launched from Lutris), Lutris doesn't appears and we can do some other stuff.
Here a screencast. I started Unigine Superposition from Lutris, I close Superposition, then Lutris appears !
![ezgif-6-4cf3ba7e5782](https://user-images.githubusercontent.com/24923693/95240543-dae4f580-080c-11eb-93a7-dc172d9b92f0.gif)

**Comment by byte1024** [comment]
I feel this only makes sense when paired with a way to start a game direct (icon or terminal).

If you're entering something with multiple possible games, configurations, etc, it generally doesn't make sense to exit it. Lutris isn't normally run once and forget.

If actually doing it however, it could possibly be quite annoying so the setting might need to be direct on the main UI or deal with toggling it less and hide it more.

**Comment by strycore** [comment]
This is the expected behavior for the client when "minimize the client on game launch" is active.
