### ISSUE TITLE
set a different keyboard layout

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#319]
many shmups/platformers use Z & X keys but its a bit weird to reach that keys on a QWERTZ keyboard so there should be a way to force a specific one.

eg something like this:

````
_set_us_keyboard=true

case $_set_us_keyboard in
	true|TRUE)
		if type setxkbmap &>/dev/null; then
			if type xkbcomp &>/dev/null; then
				setxkbmap -model pc101 us -print|xkbcomp - $DISPLAY 2>/dev/null
			fi
		fi
		trap "setxkbmap" EXIT;;
esac

exec ./<GAMEBIN>

case $_set_us_keyboard in
	true|TRUE)
		setxkbmap;;
esac
exit "$_exitcode"
````

**Comment by strycore** [comment]
yes! I remember when I was using an azerty layout that this was often a cause of trouble. That has its place in the system options and it's not very difficult to implement

**Comment by strycore** [comment]
Can you review the commit above and confirm is does what is expected?

**Comment by sixsixfive** [comment]
doesnt work, tested with cho ren sha 68k

also python3-evdev isnt available on debian so i had to move it into recommends also some depends were still python2 and made it impossible to install

modified control:

````
Source: lutris
Section: games
Priority: optional
Build-Depends: debhelper, python3, dh-python, gir1.2-gtk-3.0, gir1.2-glib-2.0, python3-gi, libgirepository1.0-dev
Maintainer: Mathieu Comandon <strider@strycore.com>
Standards-Version: 3.9.5
Vcs-Git: https://github.com/lutris/lutris
Homepage: https://lutris.net
X-Python-Version: >= 3.4

Package: lutris
Architecture: any
Depends: ${misc:Depends}, ${python3:Depends}, python3-yaml, python3-dbus, python3-gi, python3-pyinotify, python3-xdg, gir1.2-gtk-3.0, xdg-user-dirs, psmisc
Recommends: python3-evdev, libc6:i386, libtxc-dxtn-s2tc0:i386
Suggests: bumblebee, xboxdrv, xserver-xephyr, x11-xkb-utils, mono-complete, default-jre, wine | wine-development | winehq-devel | winehq-staging
Description: Install and play any video game easily
 Lutris is a gaming platform for GNU/Linux. Its goal is to make
 gaming on Linux as easy as possible by taking care of installing
 and setting up the game for the user. The only thing you have to
 do is play the game. It aims to support every game that is playable
 on Linux.
````

**Comment by sixsixfive** [comment]
since there isnt much debug output from lutris

https://drive.google.com/file/d/0B_2_dsXrefR-dEtYQWpvRDBxd2s/view

also if it would work it would display an Y instead of a Z

**Comment by strycore** [comment]
I've added the environment when running the layout switching commands and made this gist to test if it works properly:
https://gist.github.com/strycore/9748bfbdb55bb3ffb704bc74ab60487f

does it make any difference on your side?

**Comment by sixsixfive** [comment]
dpkg-buildpackage -us -uc -rfakeroot still produces an uninstallable package due its broken control file

dpkg: dependency problems prevent configuration of lutris:
 lutris depends on python:any (>= 3.4~); however:
  Version of python on system is 2.7.11-2.
 lutris depends on python3-yaml; however:
  Package python3-yaml is not installed.
 lutris depends on python3-dbus; however:
  Package python3-dbus is not installed.
 lutris depends on python3-pyinotify; however:
  Package python3-pyinotify is not installed.
 lutris depends on python3-evdev; however:
  Package python3-evdev is not installed.

dpkg: error processing package lutris (--install):


also it still wont work(tested with torus trooper) also there is a much bigger problem now lutris does not see if the game ends and creates zombies that will make the system freeze.

![aaa](https://cloud.githubusercontent.com/assets/3780774/18614853/4ea1d93e-7d97-11e6-87f4-4c752b1d35e7.png)

**Comment by strycore** [comment]
The control file isn't broken. Lutris now requires Python 3.4 which should be installable in your distro. python3-evdev isn't available in Debian so I moved it to Recommends.

I should look into this zombie process thing, I've seen those before but do they really freeze your system? That seems very unlikely.

**Comment by sixsixfive** [comment]
>The control file isn't broken. Lutris now requires Python 3.4 which should be installable in your distro.

yes but the package for python >=3 is named python3 and not python(which is ver 2.0)

```
ssf@schleppi:~$ LANG=C aptitude show python
Package: python                          
Version: 2.7.11-2
State: installed
Automatically installed: no
Multi-Arch: allowed
Priority: standard
Section: python
Maintainer: Matthias Klose <doko@debian.org>
Architecture: amd64
Uncompressed Size: 663 k
Depends: python2.7 (>= 2.7.11-11~), libpython-stdlib (= 2.7.11-2)
PreDepends: python-minimal (= 2.7.11-2)
Suggests: python-doc (= 2.7.11-2), python-tk (>= 2.7.11-11~)
Conflicts: python-central (< 0.5.5), python:i386
Breaks: update-manager-core (< 0.200.5-2)
Replaces: python-dev (< 2.6.5-2), python-dev:i386 (< 2.6.5-2)
Provides: python-ctypes, python-ctypes:any, python-ctypes:i386, python-email, python-email:any,
          python-email:i386, python-importlib, python-importlib:any, python-importlib:i386,
          python-profiler, python-profiler:any, python-profiler:i386, python-wsgiref,
          python-wsgiref:any, python-wsgiref:i386, python:any (= 2.7.11-2)
Description: interactive high-level object-oriented language (default version)
 Python, the high-level, interactive object oriented language, includes an extensive class library
 with lots of goodies for network programming, system administration, sounds and graphics. 
 
 This package is a dependency package, which depends on Debian's default Python version (currently
 v2.7).
Homepage: http://www.python.org/
Tags: devel::interpreter, devel::lang:python, implemented-in::c, implemented-in::python,
      interface::commandline, role::metapackage, role::program, scope::utility
```

>I should look into this zombie process thing, I've seen those before but do they really freeze your system? That seems very unlikely.

they do, since they will never stop and i can still run new apps so after running 2-3 apps my cpu and ram usage goes to ~90% which is like a freeze(its not a full freeze but i need to switch to a tty and kill lutris to make it usable again)

**Comment by sixsixfive** [comment]
also you should be able to test the keyboard layout by yourself eg: launch a script like this with lutris

```
#!/bin/sh
while true; do
	setxkbmap -query|awk 'NR==3 { print $2}'
	sleep 2
done
```

**Comment by strycore** [comment]
> it is since the package for python >=3 is named python3 and not python(which is ver 2)

Right, I had python3 in  the Build-Depends and the correct X-Python-Version but I had to fix the Depends to have ${python3:Depends}, should be good now.

> they do, since they will never stop and i can still run new apps so after running 2-3 apps my cpu and ram usage goes to ~90% which is like a freeze(its not a full freeze but i need to switch to a tty and kill lutris to make it usable again)

I managed to reproduce that, it's unrelated to the new keyboard layout code and I'm trying to figure out how to fix it. Depending on how many cores/cpu threads you have that could result in a freeze indeed.

**Comment by strycore** [comment]
The latest commit should fix the 100% CPU problem can you confirm that?

**Comment by sixsixfive** [comment]
yes it does work now ;)

**Comment by strycore** [comment]
Current status: 
Lutris doesn't change layouts, my gist does and your script will show 'fr' whether the layout is qwerty or azerty

**Comment by strycore** [comment]
And it should work in Lutris now.

**Comment by sixsixfive** [comment]
awesome =)
