### ISSUE TITLE
Interest in developing  Mac OS version 

### ISSUE THREAD

**Issue by minilandl** [lutris/lutris#3195]
So with Mac os dxvk support coming along nicely I would be interested in starting work on a version of lutris for Mac OS or a similar application. How much of lutris is Linux specific how easy would it be to port to OSX ? 

https://github.com/KhronosGroup/MoltenVK/issues/203

**Comment by strycore** [comment]
> How much of lutris is Linux specific 
All of it.

> how easy would it be to port to OSX ?
Very hard. Especially considering I won't help you.

**Comment by Gcenx** [comment]
@minilandl your time would be better served helping an already established project that supports macOS.

Trying to add macOS support into Lutris would be a PITA

**Comment by strycore** [comment]
One of the main goal of Lutris is to make Linux a bigger platform than Mac for gaming so we can get better publisher support.
Accordingly, I would never do anything that would benefit the Apple ecosystem just a tiny bit.

**Comment by minilandl** [comment]
Yeah Its just a shame that proton dosen't support osx. I wouldn't think it would be too difficult to build something similar to lutris or gamehub on osx as both linux and mac and unix based and python and gtk are cross platform. I might work on something as a separate project as dxvk support is getting better on osx. The other issue is apple keeps changing things like dropping 32bit support and switching to arm. I mainly game on linux and alsoand want linux to be better. But I'm sure many mac users would appreciate an easier way to run games because currently its a mess.

**Comment by strycore** [comment]
> I'm sure many mac users would appreciate

They chose to buy a device with a walled garden. Now they live with the consequences of that choice or....
Linux systems are free and can be installed on Macs. They'll be welcome once they switch.

**Comment by minilandl** [comment]
True but I'm surprised at how many people over on r/macgaming  and in r/wine_gaming continue to ask how to run X AAA game on mac os and run windows for gaming on their mac . I usually direct them to protondb and linux its just a shame because if mac supported vulkan dxvk and proton would work on both.

**Comment by oscarbg** [comment]
+1

**Comment by strycore** [comment]
Putting any kind of effort on something that would benefit the Apple ecosystem would go against everything I have stood for in the past 25 years.

**Comment by Serentty** [comment]
> They chose to buy a device with a walled garden. Now they live with the consequences of that choice

How does the supposed walled garden have anything to do with this? It doesn't block a Mac version of Lutris. PlayOnLinux and CrossOver run just fine. Above you said it was your choice not to port it, because you didn't want to help Apple. That's fine and dandy, but then it's on you that there's no Mac version.

**Comment by YusufKhan-gamedev** [comment]
> > I'm sure many mac users would appreciate
> 
> They chose to buy a device with a walled garden. Now they live with the consequences of that choice or....
> Linux systems are free and can be installed on Macs. They'll be welcome once they switch.

Same with the person who got a laptop from eBay with the bios ripped off, they chose to buy e-waste.

**Comment by YusufKhan-gamedev** [comment]
> One of the main goal of Lutris is to make Linux a bigger platform than Mac for gaming so we can get better publisher support.
> Accordingly, I would never do anything that would benefit the Apple ecosystem just a tiny bit.

Linux is already a bigger platform than mac(game wise) many games just don't run because someone decided it was too much hassle changing a application from a 32 bit one to a 64 bit app. We know most of them have 64 bit versions of their engines and even some games. Example, Valve, Half Life 2 and other source engine games are known to have 64 bit versions but they aren't giving it to macos.

**Comment by YusufKhan-gamedev** [comment]
> > How much of lutris is Linux specific
> 
> All of it.
> 
> > how easy would it be to port to OSX ?
> 
> Very hard. Especially considering I won't help you.

All of it will probably have to be rewritten, I agree, there is no point in porting lutris directly to mac.

**Comment by ll3macorn** [comment]
> > I'm sure many mac users would appreciate
> 
> They chose to buy a device with a walled garden. Now they live with the consequences of that choice or.... Linux systems are free and can be installed on Macs. They'll be welcome once they switch.

me when i cant install linux because my school will litterly stab me

**Comment by strycore** [comment]
It's illegal for school staff to stab their students.

**Comment by ll3macorn** [comment]
> It's illegal for school staff to stab their students.

its also annoying when 1.5 years ago you took a linux laptop to school and was not ever allowed to use that laptop ever again, and was given a school computer

**Comment by 96jaco96** [comment]
Just wanted to say that while i understand personal preferences of both OP and strycore, i find that this whole response was quite rude... We're better than that, and it's because of such unwelcoming attitudes that people are driven away from Linux and see it as a niche thing that only "nerds" use. 

If i was a mechanic and someone asked me "Hey can i put this Chevy part on my Ford truck" i would simply say 
"No, because they aren't compatible and there's not much you can do about it" 
I wouldn't say stuff like: "Ford sucks your car is bad, it won't fit there because you have to buy a Chevy truck" 
That would make me look like an ahole and i would only lose a customer and drive people away from my product in general.

In the end no OS is perfect, and they're just tools for specific uses. 
There's no "better" OS but only the right tool for a task, and sadly gaming is not MacOS task; simple as that.

**Comment by ll3macorn** [comment]
> Just wanted to say that while i understand personal preferences of both OP and strycore, i find that this whole response was quite rude... We're better than that, and it's because of such unwelcoming attitudes that people are driven away from Linux and see it as a niche thing that only "nerds" use. 
> 
> If i was a mechanic and someone asked me "Hey can i put this Chevy part on my Ford truck" i would simply say 
> "No, because they aren't compatible and there's not much you can do about it" 
> I wouldn't say stuff like: "Ford sucks your car is bad, it won't fit there because you have to buy a Chevy truck" 
> That would make me look like an ahole and i would only lose a customer and drive people away from my product in general.
> 
> In the end no OS is perfect, and they're just tools for specific uses. 
> There's no "better" OS but only the right tool for a task, and sadly gaming is not MacOS task; simple as that. 

Well I use Linux on a daily basis on a my home machines but I use a Mac for school. Also it is very good for gaming, I get 300 fps on minecraft which is better than my 1060 computer

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Yeah, @ll3macorn, since the release of the RISC macs, the old but previously  accurate stereotype of slow macs is utterly incorrect now.

**Comment by ll3macorn** [comment]
> Yeah, @ll3macorn, since the release of the RISC macs, the old but previously accurate stereotype of slow macs is utterly incorrect now.

100000% agree, actually before i used the M1 i had a family member that had a 2008 imac, that thing played period accurate games good too

**Comment by danieljohnson2** [comment]
I do not think the issue here is that Macintoshes are too slow. I'd expect Lutris to work fine on an x86 Mac that was running Linux.

But porting Lutris to OS X would be very... non-trivial. It's a big thing to ask for, and I don't blame @strycore for not wanting to invest in it

The Mac community isn't usually all that fond of half-assed ports anyway. They'd be better served by a proper Mac program.

**Comment by strycore** [comment]
Don't mind me, I'm just here running Half Life on a Raspberry Pi :sunglasses: 
![20220805_040450](https://user-images.githubusercontent.com/280336/183223651-58191b2b-c939-47d9-9ee6-e192bba8b5f3.jpg)

**Comment by danieljohnson2** [comment]
Heretic!

**Comment by capnslipp** [comment]
Just copying this here (stolen from a Reddit post) about why Valve's Proton can't be easily compiled & run on macOS:

* eventfd syscall is Linux-specific, without good alternative on macOS
* Apple does not support Vulkan, which is needed for DXVK
* Apple deprecated OpenGL support, which is needed for WineD3D

I don't know much about the internals of Lutris so I don't know if those are the same issues one would encounter trying to get Lutris to run on Mac, but there is a point that beyond the popular libraries that are supported natively by Mac (make, Python, GTK, etc.) there's a lot that isn't plausible (Vulkan would require getting Lutris to use the MoltenVK Vulkan→Metal translation library) or even possible.

My 2¢: Modern Apple is no longer Steve Job's Apple, which had a stronger interest in embracing open standards and providing compatibility layers to entice devs and users (macOS used to support writing native apps in Java, macOS's X support has fallen off, Bootcamp seems deprecated, etc.).

**Comment by Serentty** [comment]
I agree with many of the other points but...

> Bootcamp seems deprecated

This one is because Microsoft does not license the ARM version of Windows to end users, only OEMs. This one is on Microsoft, really.

**Comment by Heavy0331** [comment]
> Putting any kind of effort on something that would benefit the Apple ecosystem would go against everything I have stood for in the past 25 years.
🤡

**Comment by capnslipp** [comment]
@Serentty Even before Apple Silicon, Bootcamp had seen better days.  It was still there and generally worked, but Apple was putting no real effort into making it work fully.  In the early days it was awesome; 4 years ago, for example, it was hacking your EFI to get Windows to recognize your eGPU (that is plug-and-play in macOS or with Windows on a normal Windows machine) and accepting that you can’t plug or unplug it without shutting down.
