### ISSUE TITLE
Lutris does not launch

### ISSUE THREAD

**Issue by DondoChaca** [lutris/lutris#3196]
**Describe the bug**

When trying to launch Lutris it gives out a ValueError

**Steps to reproduce**

Run Lutris from terminal

**Lutris debugging output (Optional)**

The terminal output of `lutris -d`.

lutris -d
Unable to load locale dir, translations won't work.
Traceback (most recent call last):
  File "/usr/bin/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 52, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 25, in <module>
    from lutris.gui.widgets.services import SyncServiceWindow
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/services.py", line 11, in <module>
    from lutris.gui.widgets.notifications import send_notification
  File "/usr/lib/python3.8/site-packages/lutris/gui/widgets/notifications.py", line 9, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available

**System information (Optional)**

Liguros GNU+Linux, Gentoo derivative
eix lutris
[?] games-util/lutris [1]
     Available versions:  (~)0.5.4-r1^t (~)0.5.6^t (~)0.5.7^t **9999*l^t {test PYTHON_TARGETS="python3_5 python3_6 python3_7 python3_8 python3_9"}
     Installed versions:  0.5.7.1^t(06:37:57 PM 10/11/2020)(-test PYTHON_SINGLE_TARGET="python3_8 -python3_5 -python3_6 -python3_7 -python3_9")
     Homepage:            https://lutris.net/
     Description:         An open source gaming platform for GNU/Linux

Linux liguros 5.8.10_p1-debian #1 SMP Tue Oct 6 00:13:16 CEST 2020 x86_64 AMD Ryzen 5 3600 6-Core Processor Authentic AMD GNU/Linux

**Screenshots (Optional)**

N/A

**Comment by strycore** [comment]
Typical gentoo user...
Messes their system, does not how to troubleshoot basic problems.

Install the pygobject-notify bindings. This will solve your issue.
