### ISSUE TITLE
Importing Neverwinter Nights: Enhanced Edition from GOG adds Diamond Edition

### ISSUE THREAD

**Issue by KonKode** [lutris/lutris#3197]
I own both versions of Neverwinter Nights. When I import `neverwinter-nights-enhanced-edition` from my GOG library, it instead adds `neverwinter-nights`. Both games are correctly listed separately in the Import tab.

A workaround is to manually add a new game and give it the correct identifier of `neverwinter-nights-enhanced-edition`. Clicking *Install another version* will then present the correct installation options.

After the game is installed and launched for the first time, Lutris automatically detects it and adds a second listing for  `neverwinter-nights-enhanced-edition` with the correct artwork from the database.

**Comment by strycore** [comment]
I removed the wrong association on Diamond
