### ISSUE TITLE
Unable to paste password when trying to connect an account

### ISSUE THREAD

**Issue by Popkornium18** [lutris/lutris#3198]
**Describe the bug**

When I try to paste my password into the login window of GOG or HumbleBundle nothing happens. I use 64 character long passwords which are completely randomized. Typing them would be a massive PITA.

**Steps to reproduce**

- Click on 'Connect your Account'
- Try to paste your password

**Comment by Popkornium18** [comment]
Seems like this isn't caused by Lutris

**Comment by Polynomial-C** [comment]
I already reported a very similar issue before in #2132. That issue was caused by using [keepassreboot/keepassxc](https://github.com/keepassxreboot/keepassxc) and was later fixed. Any chance this issue re-appeared?

**Comment by hakimzulkufli** [comment]
>  Any chance this issue re-appeared?

@Polynomial-C I can confirm it reappeared. Using CTRL+C or CTRL+B on the entries list completely breaks pasting anything into the login windows on Lutris.

KeePassXC 2.7.6
Lutris 0.5.14
kernel-liquorix 6.5.9
KDE Plasma 5.27.9
