### ISSUE TITLE
Duplicate Entries when Importing Steam Games

### ISSUE THREAD

**Issue by andrfgs** [lutris/lutris#3201]
**Describe the bug**

Whenever I import steam games to Lutris, all entries are duplicated in the list. Regardless of whether they are native or windows only steam games.

**Steps to reproduce**

- Open Lutris
- Select `Steam` tab
- `+` > `Import Games...`
- Select `Steam` (`Steam for Windows` has no entries)

The list of games contains all titles duplicated. Even for native games in Steam.

**Lutris debugging output (Optional)**

I doubt this output will be of any use because there seems to be no error here:

```
Unable to load locale dir, translations won't work.
INFO     2020-10-14 18:08:45,763 [application.do_command_line:275]:Running Lutris 0.5.7.1
INFO     2020-10-14 18:08:45,763 [startup.check_driver:54]:Using NVIDIA drivers 455.28 for x86_64
INFO     2020-10-14 18:08:45,763 [startup.check_driver:58]:GPU: GeForce GTX 1070
INFO     2020-10-14 18:08:45,764 [startup.check_driver:73]:GPU: 10DE:1BA1 1462:1215 using nvidia drivers
INFO     2020-10-14 18:08:45,764 [startup.check_driver:73]:GPU: 8086:3E9B 1462:1215 using i915 drivers
INFO     2020-10-14 18:08:45,793 [startup.check_vulkan:124]:Vulkan is supported
DEBUG    2020-10-14 18:08:46,152 [http.get:71]:GET https://lutris.net/api/runtime
DEBUG    2020-10-14 18:08:46,157 [store.get_missing_media:191]:Requesting missing icons from API for among-us
DEBUG    2020-10-14 18:08:46,158 [http.get:71]:GET https://lutris.net/api/games
DEBUG    2020-10-14 18:08:46,404 [api.get_game_api_page:130]:Loaded 1 games from page 1
INFO     2020-10-14 18:08:46,459 [mame.notify_mame_xml:31]:MAME XML written
INFO     2020-10-14 18:09:08,685 [application.do_shutdown:520]:Shutting down Lutris
```

**System information (Optional)**

I doubt this is related to my system, but why not report it anyway?

OS: Arch Linux 5.8.14
DE: Plasma 5.19.5 (using KWin compositor with OpenGL 2.0 backend)
PC: MSI GP 73 Leopard 8RF (Laptop)
CPU: Intel i7-8750H (12) @ 4.100GHz 
iGPU: Intel UHD Graphics 630 
dGPU: NVIDIA GeForce GTX 1070 Mobile

**Comment by odysseywestra** [comment]
Figured it out for me. It duplicates cause we probably have steam-native-runtime. If you were to uninstall that package and refresh the steam source, then there's no duplicates. 

So I guess it comes down to how lutris pulls the information off of steam and whether it trigging it for both versions? Sadly you have to have the steam(runtime) in order to have navtive runtime to install.

**Comment by strycore** [comment]
We now import Steam games from the Steam API which prevents those issues.

**Comment by andrfgs** [comment]
This still happens on version `0.5.7.1`. Which branch has the fix?

**Comment by Jan200101** [comment]
Still happens on the latest master commit
This issue should probably be reopened

**Comment by lavadrop** [comment]
Same problem

**Comment by andrfgs** [comment]
So since someone closed this issue when they shouldn't should I create a new issue? Because I can't reopen it.

**Comment by strycore** [comment]
It's a completely different bug. But I'll hijack because i don't feel like opening a new one.
