### ISSUE TITLE
DOOM3: BFG Edition - openjpeg 

### ISSUE THREAD

**Issue by truggleswick** [lutris/lutris#321]
~/Games/doom-3-bfg-edition/RBDoom3BFG: error while loading shared libraries: libopenjpeg.so.2: cannot open shared object file: No such file or directory

------------------------------
ls /usr/lib | grep openjpeg

libopenjpeg.so
libopenjpeg.so.1
libopenjpeg.so.1.5.2
openjpeg-2.1

On Arch 64. That's every version of openjpeg that I could find via packer.

I'm guessing 3 letters need changing somwhere?

**Comment by strycore** [comment]
I added libopenjpeg.so.2 to the runtime, can you test again and see if it works now?

**Comment by truggleswick** [comment]
It does :D

**Comment by strycore** [comment]
Nice!
