### ISSUE TITLE
Serious Sam first GOG installed, but list as "not installed" in GOG sources

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3215]
Hello,
I installed "Serious Sam first" from GOG, list as installed in "all" sources, but it is list as "not installed" in GOG sources.

You can see the log here:
https://github.com/lutris/lutris/issues/3214#issuecomment-712110134

**Comment by strycore** [comment]
this log does not show anything relevant. It can be a matter of the game not matching on the website for the installer used.
