### ISSUE TITLE
Question: how do I edit scripts before running them?

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3216]
I know I can view a script immediately before installing a game, but I can't seem to edit it at that time. I also can't find any trace of the scripts on disk, nor info on how to find or edit them. How would I go about doing this?

Background: Since the majority of all game installations I've tried seem to fail, often on some trivial step like trying to copy or open files in directories that don't exist, I'm working under the assumption that most script are in need of handholding, hence I would like to edit them immediately before they run.

**Comment by byte1024** [comment]
I know you can run and edit from the Lurtis website. All edits there are public though.

**Comment by appoloin** [comment]
Changes to existing scripts are private until they are submitted and approved by a moderator, so in theory if you don't submit the changes for approval the script will remain in your account and private for ever.     The downside is you cant run the script from the app.

**Comment by byte1024** [comment]
Thought I checked and found they were public? Maybe I did that incorrectly.

**Comment by byte1024** [comment]
No, I was right to an extent anyway. They appear to be public after you sign in as is evidenced from the EGS script: https://lutris.net/games/epic-games-store-latest/installer/edit

**Comment by anohren** [comment]
Thanks for your replies. I understand. 

 Currently I'm not interested in creating an account; I'm at the stage where Lutris is mostly an application that downloads 3 GB of data and leaves me with an empty folder. Even after stumbling on a switch to enable caching of these huge files I am left with an unusable installer because the script either A. downloaded a Windows installer despite saying it would use the native installer, or B. extracted the contents of the native installer and discarded it, leaving me with 3 GB of unusable files — unless I can e.g. correct a variable name in the script, which otherwise presumably knows what to do with these files. 

As it is now, I'm only left with the realization that I need to download the native installer manually, which I would say is the wrong time to ask any user to increase their investment by creating an account. Hence I think the feature has its place in the application.

**Comment by strycore** [comment]
![2020-10-20_07-20](https://user-images.githubusercontent.com/280336/96599432-c856cb80-12a4-11eb-87f9-76d8f3036e5e.png)

**Comment by anohren** [comment]
@strycore 

Sorry, I'm not sure what your proposed steps are in order to do this. 

Is it to view the script source, copy it all to a file, edit it, hope that any file extension is fine, hope that "yml file" also means it can contain json, and then decipher the CLI?

**Comment by anohren** [comment]
@strycore You've implied that what I'm asking about is possible. If it is, but you do not wish to elaborate, could you please leave the issue open so that someone else might take the opportunity to clarify the steps needed?

**Comment by AlexanderRavenheart** [comment]
@anohren Open the game page on Lutris.net, click on the dropdown (down arrow) next to the install button of the script you want to view/edit, select "View install script", click on the orange "download" link, click Raw Data, click Save and then you can edit that file and pass it to Lutris with the -i parameter. I don't remember if you need to convert it to yaml format or if you even need to change the extension of the file since yaml can load json data.

**Comment by anohren** [comment]
Thanks for the steps @AlexanderRavenheart  

I see, so the script is not complete when viewed directly inside the client. Your method worked much better than what I tried initially.

Looking at the output for [the second step in this script](https://lutris.net/api/installers/baldurs-gate-ii-shadows-of-am-gog?format=json), I interpret it as trying to extract files from a .exe:

```
Running /home/username/.cache/lutris/installer/baldurs-gate-ii-complete/unzip /home/username/Games/lutris cache/baldurs-gate-ii-complete/gog/setup_baldurs_gate_ii_enhanced_edition_2.5.16.6_(21849).exe -d /home/username/Games/baldurs-gate-ii-complete data/noarch/*
```

Unfortunately it seems to result in:

```
Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 237, in <module>
    main()
  File "/usr/share/lutris/bin/lutris-wrapper", line 120, in main
    initial_pid = subprocess.Popen(args).pid
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/username/.cache/lutris/installer/baldurs-gate-ii-complete/unzip'
```

After some more testing I can only conclude that `unzip` is not a 32 bit executable. I guess it was not an easy fix for me after all.

What should the script have said instead in order to refer to the tool in an architecture independent way?

**Comment by appoloin** [comment]
Why does that script extract using unzip if it's going to use the wine runner for the game.   Have look at the example below, this script runs the gog installer using wine.

name: baldurs-gate 2
game_slug: baldurs-gate-2
version: Installer
slug:  baldurs-gate-2-installer
runner: wine

script:
  game:
    exe: $GAMEDIR/drive_c/GOG Games/Baldur's Gate II - Enhanced Edition/Baldur.exe
    arch: win32
    prefix: $GAMEDIR

  files:
    - setup: N/A:Select the GOG installer

  installer:
    - task:
        name: create_prefix
        arch: win32
        install_mono: false
        install_gecko: false
        prefix: $GAMEDIR

    - task:
        executable: $setup
        name: wineexec
        prefix: $GAMEDIR

**Comment by anohren** [comment]
When reading your script I suddenly notice that I completely missed that part where it has apparently downloaded the _Enhanced Edition_ installer when it should have downloaded the original game (BG2 "_Complete_"). That's confusing.

**Comment by appoloin** [comment]
The example is a generic install script for wine.  You point the script to the exe on your harddrive,  lutris creates the bottle and runs the exe.  

Modify the following lines so lutris displays the correct name and icon the library 

name: baldurs-gate 2
game_slug: baldurs-gate-2
slug: baldurs-gate-2-installer

You cane leave this one and change the setting in lutris's options after the game has been installed.

exe: $GAMEDIR/drive_c/GOG Games/Baldur's Gate II - Enhanced Edition/Baldur.exe

**Comment by anohren** [comment]
Your script is an example (thanks!), but I meant that after reading it I then looked at the output that I had posted and noticed the name of the .exe installer that was downloaded, and it appears to be for the wrong game(!). Sorry for the confusion.

**Comment by appoloin** [comment]
The exe line is only used to run the game after install.  That line could be "$GAMEDIR/drive_c/" the script would still run the installer.  

Log lutris out of gog and run the script again, Lutris will ask for a login cancel that and you should get a file select option

**Comment by anohren** [comment]
I'm talking about the installer `.exe` that the script downloaded and that was passed to `unzip`, not the exe line. 

The script has two "execute" directives, one of which runs `unzip`.

**Comment by appoloin** [comment]
From code snippets from the script you linked to.

This unzips the game installer
- execute:
    args: $game -d "$GAMEDIR" "data/noarch/*"
    file: $CACHE/unzip
 
This is creates a symbolic link, $INPUT is from the choice you made at the start (ie English, German etc), it looks like destination for the game.exe depends on the language.  I'm guessing was done so the exe: tag in the script was valid.
- execute:
    args: -s "$GAMEDIR/Game/prefix/drive_c/GOG Games/$INPUT" "$GAMEDIR/Game/prefix/drive_c/GOG
      Games/Baldur's Gate 2"
    file: /bin/ln

**Comment by anohren** [comment]
> This unzips the game installer

Except it doesn't, since it fails. 

Even if it did succeed it would unzip the wrong game.

**Comment by appoloin** [comment]
> Except it doesn't, since it fails.
A possible reason for the failure is because gog have changed the installer and the files don't extract to the location the script expects.   That's why I suggested running the installer using wine, a game's install location can change with installer versions (ie one version will install to c drive root, another version will install to program files).   

> Even if it did succeed it would unzip the wrong game.
Log Lutris out of GOG and provide the correct installer exe when asked.

**Comment by anohren** [comment]
> A possible reason for the failure is because gog have changed the installer and the files don't extract to the location the script expects.

Or more likely it's because running `unzip` results in a "format error", after which I could conclude that `unzip` is not a 32 bit executable, hence incompatible with the hardware platform.

> Log Lutris out of GOG and provide the correct installer exe when asked.

At which point using Lutris becomes, well, pointless since then I can just run the native installer directly.
