### ISSUE TITLE
Steam sync not working

### ISSUE THREAD

**Issue by LiamDawe** [lutris/lutris#3219]
Trying out the latest 0.5.8 Beta and it appears the new Steam sync system is not working.

When clicking the refresh button, terminal says:

> 2020-10-20 10:13:42,907: Invalid response from steam: <Response [500]>

Is there somewhere we actually need to set it up, or is it supposed to just hook into Steam that's installed in our system? It's not explained.

Running in debug mode "-d" gives no extra info.

**Comment by eitch** [comment]
For me the steam sync doesn't work either, but i see the following:

    INFO     2020-10-20 16:37:26,632 [config.get_steam_library:83]:No games in response of 
    https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/? key=XXX&steamid=XXX&format=json&include_appinfo=1&include_played_free_games=1

But steam runs well on my system and has been for many years. I can also play games with Proton etc.

**Comment by eitch** [comment]
Maybe it has something to do with this:

	DEBUG    2020-10-20 16:42:17,227 [steam.load:110]:Steam games loaded
	Traceback (most recent call last):
	  File "/home/zzz/lutris/lutris/gui/lutriswindow.py", line 450, in update_store
	    self.game_store.add_game(game)
	  File "/home/zzz/lutris/lutris/gui/views/store.py", line 173, in add_game
	    game.playtime_text,
	  File "/home/zzz/lutris/lutris/gui/views/store_item.py", line 142, in playtime_text
	    _playtime_text = get_formatted_playtime(self.playtime)
	  File "/home/zzz/lutris/lutris/util/strings.py", line 124, in get_formatted_playtime
	    hours = math.floor(playtime)
	TypeError: must be real number, not str

**Comment by strycore** [comment]
Lutris now gets Steam games from the Steam API. It uses the same method as the Lutris website and GameHub. Your game library should be public before syncing. I will add a message that notifies the user of this.

This was kind of a last minute addition but I thought it would be worthwhile of having a complete Steam library instead of just locally installed games.

**Comment by LiamDawe** [comment]
Not an issue of public or not in this case of the error, as mine is and I did a manual API call myself and it detects it fine. So it seems there's a bug in Lutris grabbing it somewhere.

**Comment by veksha** [comment]
> Lutris now gets Steam games from the Steam API. It uses the same method as the Lutris website and GameHub. Your game library should be public before syncing. I will add a message that notifies the user of this.
AFAIK, GameHub do not require game details to be public. It makes use of API-Key.

**Comment by strycore** [comment]
it is the exact same API call used by the lutris website and the lutris website requires the library to be public.

**Comment by dhollinger** [comment]
> Trying out the latest 0.5.8 Beta and it appears the new Steam sync system is not working.
> 
> When clicking the refresh button, terminal says:
> 
> > 2020-10-20 10:13:42,907: Invalid response from steam: <Response [500]>
> 
> Is there somewhere we actually need to set it up, or is it supposed to just hook into Steam that's installed in our system? It's not explained.
> 
> Running in debug mode "-d" gives no extra info.

I got this same issue, so I did some of my own digging. My profile is completely public. We need to make sure that when Lutris makes the API call, it is using user's SteamID is in SteamID64 format, NOT the string or SteamID3 format. Otherwise you will get an error 500 in return.

**Comment by dhollinger** [comment]
Here's what I see if I add a print to print out my SteamID:

```
2020-10-20 10:54:47,126: Getting full game list from MAME...
2020-10-20 10:54:47,126: MAME XML generation launched in the background, not returning anything this time
2020-10-20 10:54:47,128: MAME isn't installed, can't retrieve systems list.
INFO     2020-10-20 10:54:47,201 [application.do_command_line:319]:Lutris 0.5.7.1
INFO     2020-10-20 10:54:47,202 [startup.check_driver:61]:Using NVIDIA drivers 455.28 for x86_64
INFO     2020-10-20 10:54:47,202 [startup.check_driver:65]:GPU: GeForce RTX 2060
INFO     2020-10-20 10:54:47,202 [startup.check_driver:81]:GPU: 10DE:1F11 1558:95E1 (nvidia drivers)
INFO     2020-10-20 10:54:47,202 [startup.check_driver:81]:GPU: 8086:3E9B 1558:95E6 (i915 drivers)
INFO     2020-10-20 10:54:47,554 [mame.notify_mame_xml:31]:MAME XML written
DEBUG    2020-10-20 10:54:47,957 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-10-20 10:54:48,253 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-10-20 10:54:54,384 [base.wipe_game_cache:44]:Deleting games from service-games for steam
None
ERROR    2020-10-20 10:54:54,724 [config.get_steam_library:80]:Invalid response from steam: <Response [500]>
DEBUG    2020-10-20 10:54:54,736 [http.get:73]:GET https://lutris.net/api/games
DEBUG    2020-10-20 10:54:55,049 [steam.load:110]:Steam games loaded
```

**Comment by dhollinger** [comment]
@strycore Found the issue:

`.get("mostrecent") == "1":` at https://github.com/lutris/lutris/blob/master/lutris/util/steam/config.py#L63 should be `.get("MostRecent") == "1":`

I can push a PR up if you'd like

**Comment by pakro** [comment]
IMO I would let the user decide whether he or she wants the games fetched from the Steam API -- requiring a public profile -- or from the local installations. In fact every API -- if possible -- should behave that way.
This is a) privacy friendly and b) working offline, which are great features.

**Comment by strycore** [comment]
@dhollinger Your patch is broken. You can imagine that if I pushed this feature, it worked on my end so the key on my computer really is "mostrecent".
Steam comes from the Windows world and as such is it very liberal in its use of case. It is very frequent to have folders or configuration keys written with one case on a machine and a totally different one.
The fix is to make the  matching case insensitive.

**Comment by dhollinger** [comment]
@strycore In that case, wouldn't it be more prudent convert all keys to lowercase on reading of the configfile? We shouldn't be expecting users to dig into text files that they normally wouldn't have to, should we?

**Comment by strycore** [comment]
> We shouldn't be expecting users to dig into text files that they normally wouldn't have to, should we?

I never suggested that or even thought it would be a consideration.

> wouldn't it be more prudent convert all keys to lowercase after reading the configfile?

pretty much what I did, yes

**Comment by dhollinger** [comment]
Yeah, I re-read your comment and realized what you meant
