### ISSUE TITLE
Provide tools in the runtime to extract more archive formats

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#323]
Binaries should be provided in a runtime package called 'tools' to provide out of the box support for:

- unzip
- 7z
- rar
- cabextract
- innoextract

**Comment by RobLoach** [comment]
That'd be nice.

**Comment by RobLoach** [comment]
Something like https://pypi.python.org/pypi/libarchive ?

**Comment by strycore** [comment]
I'd rather ship executables directly in the runtime rather than make the client depend on exotic 3rd party modules that might require some compilation.

**Comment by strycore** [comment]
7zip support has been added and provides support for 7z, zip, rar and cab, it may also extract files requiring innoextract (and unshield as well). The last 2 may be used manually in installers as they are pretty rare.

Here's the full list of formats supported:

        '7z', 'xz', 'bzip2', 'gzip', 'tar', 'zip',
        'ar', 'arj', 'cab', 'chm', 'cpio', 'cramfs', 'dmg', 'ext',
        'fat', 'gpt', 'hfs', 'ihex', 'iso', 'lzh', 'lzma', 'mbr',
        'msi', 'nsis', 'ntfs', 'qcow2', 'rar', 'rpm', 'squashfs',
        'udf', 'uefi', 'vdi', 'vhd', 'vmdk', 'wim', 'xar', 'z',
