### ISSUE TITLE
local sources: some issues

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3234]
Hello Lutris dev team,
concerning "local" sources in left panel, some issues:

1) as you can see in the joined picture some characters are not correct (War1gus - Warcraft: Orcs & Humans)
2) Lutris should reuse local icons or icons from Lutris website

![Capture d’écran de 2020-10-26 22-48-44](https://user-images.githubusercontent.com/325405/97232903-4e5f9e80-17de-11eb-8cb9-7ec6af4048ea.png)

**Comment by veksha** [comment]
it is removed now forever?

**Comment by strycore** [comment]
yes. Should have sent a patch with the issue if you wanted to keep it.
