### ISSUE TITLE
Lutris sources: some issues

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3237]
Hello Lutris dev team,

concerning Lutris sources in last Lutris git version:

1) when you double click on a banner of an already installed game, Lutris launch another install of this game instead of just launch it. When I double click on an already installed game, normally user just want to launch it, not to install it again.
To install another version of this game, user should normally use right click mouse menu "install another version".

![gnome-shell-screenshot-KSK3S0](https://user-images.githubusercontent.com/325405/97304357-e64f9d80-185b-11eb-97fa-8b14a9ded887.png)

2) right click menu is not enable

**Comment by strycore** [comment]
This is related to #3238. If you look at the bottom bar, the game is marked as installed as it should be. The view doesn't get updated correctly. On my end installed games still show greyed.
