### ISSUE TITLE
Banners not loaded properly when searching for games under Lutris / Community Installers

### ISSUE THREAD

**Issue by pakro** [lutris/lutris#3238]
I'm on the latest git version and experiencing problems in the banner display.
If I search for a game in Lutris / Community Installers I see the games without the banner. 
Changing the search term slightly does load the banners from the previous search but new ones won't get displayed again.
In the debug logs you see that assets like icons are at leas loaded. It is probably an event that is missing to notify the UI about updating the banners after the assets have been loaded.

Steps to reproduce:

- Go to Lutris / Community Installers

- Search for "Project Cars"

- You should see empty banners (not even the default banner)

- Search for "Project Car"

- You see the banners related to "Project Cars" but the new game banner for "Car Tune: Project" is not shown.

This works basically with every other game respectively search term. Because as soon as you searched it once it will be cached even if you restart Lutris.

Expected behavior that the banners are displayed instantly given the search query was successful.

Probably the commit 2eb681b30a64bf4ec2f4eedd6c5ebc2df9773b71 altered that behavior. Another suspect could be also 9f23c629f0c1257552eac5f4d5865ebfa01db142.

Could it be possible that the event "icons-loaded" (which if I'm understanding it right also loads the banners) is fired before all futures are ready and therefore only half on the stuff can be displayed? At least this would explain  the behavior when searching for terms with potentially many results like "socc".

**Comment by strycore** [comment]
I removed a lot of code related to UI updates because it was causing a lot of crashes. I instead went with redrawing the full view in most cases. I do have to put back some code handling icon updates but I have to be really careful about that because it is easily the most unstable part of Gtk, especially when threads are thrown in.

**Comment by strycore** [comment]
I put back individual icon updates but this causes lutris to freeze during the icon download... The UI gets spammed with icon-loaded signals. The UI becomes responsive again once the icons are downloaded.
