### ISSUE TITLE
can't launch .lnk's...

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#324]
somethings weird here...

[game](https://lutris.net/games/install/2504/view)

with lutris:
![wihlutris](https://cloud.githubusercontent.com/assets/3780774/17790451/ca468fda-6596-11e6-808b-eea96d4a95cc.jpg)

running in pure wine:
![withoutlutris](https://cloud.githubusercontent.com/assets/3780774/17790383/7733b84a-6596-11e6-8458-b0adc0a17589.jpg)

**Comment by strycore** [comment]
Fixed, don't forget to update your install script, the exe should be the lnk file and "start /unix" will be added automatically by Lutris
