### ISSUE TITLE
lutris beta: can not use right click menu in "Lutris sources"

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3244]
Hello,
I can not use right click menu in "Lutris sources".
For an uninstalled game could be: "remove game from my Lutris library", "Install game"....
For an already  installed game, it could show the same menu as the menu available in bottom bar.

**Comment by strycore** [comment]
We never have supported upstream library sync. That's to come way later. So there would only be Install game. No point for a right click menu.
