### ISSUE TITLE
Lutris not downloading icons for games into icons folder (no icons displayed in Kodi due to "GetImageHash - unable to stat url")

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#3249]
**Describe the bug**

I'm trying to setup a modern media center for Debian 10 stable. For this I used [Kodi (latest version)](https://github.com/basilgello/kodi-nightly-debian-repo) and installed the [Kodi-Lutris addon](https://github.com/RobLoach/lutris-kodi-addon/issues) to make it integrate Lutris in a section for games.

However, for half the games no icon is displayed even though in Lutris (when starting Lutris directly) an icon is displayed. In Kodi's debug log there is:

`DEBUG <general>: GetImageHash - unable to stat url /home/username/.local/share/icons/hicolor/128x128/apps/lutris_game-name.png`

~/.local/share/icons/hicolor/128x128/apps/lutris_game-name.png does not exist but icons for the games for which an icon is displayed do exist in that folder. The icons also don't exist anywhere else under ~/.local/share/icons (and I don't know where they are stored and how they are getting fetched).

How does Lutris display these icons and why are they being handled differently than the icons which do display in Kodi (and exist in that directory)? Could this please be changed so that the icons are also downloaded and/or copied into the ~/.local/share/icons/hicolor/128x128/apps folder?

**Steps to reproduce**
- Install/use the latest Debian stable (with KDE)
- Install/use the latest Kodi via Basil Gello's repo (link above)
- Install/use the Kodi-Lutris addon (link above)
- In Kodi navigate to "Games" and click on "Lutris" (for the error messages enable Debug logs under Settings->System->Logging)

**Comment by strycore** [comment]
It looks like the issue is from Lutris-kodi where it doesn't substitute "game-name" with the actual game identifier.
