### ISSUE TITLE
wine sandbox: incorrect video user folder

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3254]
Hello Lutris dev team,

as you can see in this picture, Lutris created all Wine needed user folders.
But one folder called "Mes viéos" is a double of "Mes Vidéos" user folder with an incorrect name.

![Capture d’écran de 2020-11-03 02-16-25](https://user-images.githubusercontent.com/325405/97936189-124ab180-1d7b-11eb-9048-c48644b96178.png)

**Comment by legluondunet** [comment]
I looked on my all hard disk, I have no directory called my viéos others than Lutris created.

**Comment by pakro** [comment]
Hi @legluondunet,

I've searched the repository -- latest master as of now -- and can't find the String "Mes viéos". So I'm not sure that Lutris is actually responsible for creating that folder. Do you mind explaining why do you thing Lutris has created this folder?

**Comment by legluondunet** [comment]
you mean it could be a wine bug with accented character? Do you know if it's wine that create this folders in Wine prefix? Or Lutris for sandbox needs? Sorry to answer your question by 2 questions, but for the moment I have just an issue, no answer.

**Comment by pakro** [comment]
Wine at least contains the translation in it its correct form "Mes vidéos". However this line wasn't touched for 9 years and it is correct from the beginning it has been introduced. So Wine is not the source of the problem. Do you mind explain Lutris for Sandbox needs? I'm fairly new to this so I can't correlate everything properly. 

It would also be helpful if you could provide -- if possible -- the steps to reproduce this. Like I said when I search the whole project for "Mes viéos" or the correct form "Mes vidéos"  I don't find anything. If it is a Lutris issue there should be a result if I search for the string, right? 

Does the folder contains something that would indicate what created it?
Does the folder reappear if you delete it (see steps to reproduce)?

**Comment by legluondunet** [comment]
This is my user profile created in wineprefix with official wine version from Ubuntu 20.04:

```
$ ll
total 68
drwxrwxr-x 17 legluondunet legluondunet 4096 nov.   5 01:25  ./
drwxrwxr-x  4 legluondunet legluondunet 4096 nov.   5 01:25  ../
drwxrwxr-x  3 legluondunet legluondunet 4096 nov.   5 01:25  AppData/
drwxrwxr-x  3 legluondunet legluondunet 4096 nov.   5 01:24 'Application Data'/
lrwxrwxrwx  1 legluondunet legluondunet   19 nov.   5 01:24  Bureau -> /home/legluondunet/Bureau/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Contacts/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Cookies/
lrwxrwxrwx  1 legluondunet legluondunet   13 nov.   5 01:24  Downloads -> /home/legluondunet//
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Favorites/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Links/
drwxrwxr-x  5 legluondunet legluondunet 4096 nov.   5 01:25 'Local Settings'/
lrwxrwxrwx  1 legluondunet legluondunet   20 nov.   5 01:24 'Ma musique' -> /home/legluondunet/Musique/
lrwxrwxrwx  1 legluondunet legluondunet   22 nov.   5 01:24 'Mes documents' -> /home/legluondunet/Documents/
lrwxrwxrwx  1 legluondunet legluondunet   19 nov.   5 01:24 'Mes images' -> /home/legluondunet/Images/
lrwxrwxrwx  1 legluondunet legluondunet   20 nov.   5 01:24 'Mes vidéos' -> /home/legluondunet/Vidéos/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  NetHood/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  PrintHood/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Recent/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25 'Saved Games'/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Searches/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  SendTo/
drwxrwxr-x  3 legluondunet legluondunet 4096 nov.   5 01:25 'Start Menu'/
drwxrwxr-x  2 legluondunet legluondunet 4096 nov.   5 01:25  Temp/
lrwxrwxrwx  1 legluondunet legluondunet   21 nov.   5 01:24  Templates -> /home/legluondunet/Modèles/
```

**Comment by strycore** [comment]
"Mes viéos" is not present anywhere in the project.
