### ISSUE TITLE
Hide GOG checksum files from download list

### ISSUE THREAD

**Issue by gatl** [lutris/lutris#3259]
I'm using a fairly recent Git version of Lutris.

When I try to install a game from my GOG library, I'm presented with dialog box that tells me what files it needs to download. I see two entries.

If I use the "continue" button, everything runs fine: the files get downloaded and the game installs fine.
If I choose to install the game from a local installation file (using the "Download" button to change the widget into a "Local" button selection) and proceed to select the proper installation file from my local filesystem, then the "Continue" button is grayed out and inactive.

I find this window a bit unintuitive and I need to click thing to try to figure out what they do. I don't know what the upper (XML?) file is, (the first file listed in this window, above the installer), and I don't recall it being part of the GOG files I usually download. Whatever it is, I would expect that could be downloaded if I use a local file, since the installer is the same either way.

Could someone clarify things a little bit, please (here and in the software)?
I do think this new process is an improvement, but I find it confusing.

**Comment by strycore** [comment]
When you provide a local file, the contiinue button should let you complete the install. I'm not sure what your issue is since I've tested that the feature was working as expected.
For the XML file, yes this is confusing because it is the file for the checksum check for the GOG file. This shouldn't be shown in the files list.

**Comment by gatl** [comment]
On a more recent version from git the continue button is working as intended.

**Comment by strycore** [comment]
I know but I still want the XML files not to appear in the list of downloads

**Comment by strycore** [comment]
XML files are now removed
