### ISSUE TITLE
lutris beta: remove a game in "games" section does not delete folder in ~/Games

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3260]
Hello,
lutris beta: remove a game in "games" section does not delete folder in ~/Games.

**Comment by strycore** [comment]
not enough information about this is. I think this is by design,

**Comment by legluondunet** [comment]
@Strider, it's a true issue, I can reproduced it several times.
You can not reproduce it?

**Comment by strycore** [comment]
I don't know what the issue is

**Comment by legluondunet** [comment]
1) right click on an installed game in "games" section
2) choose remove, uninstall the game

Look at the ~/Games folder where your Lutris games installed.
Game folder is still present.

**Comment by strycore** [comment]
If the games was manually installed then it must be manually deleted.

**Comment by legluondunet** [comment]
they was not manually installed.

**Comment by legluondunet** [comment]
I f you do nt reopen it, I will write again this issue tomorrow, good night :)
