### ISSUE TITLE
Mafia Definitive Edition 

### ISSUE THREAD

**Issue by Mark-papi** [lutris/lutris#3267]
Hello !
First of all I want to point out that I really like your program!
I managed to install couple of games like re3 remake and some others with no rooblem.
I want to ask if it's gonna be possible in the future to run mafia definitive edition with lutris runner.
Right now when I'm running it I get some performance /net errors and cannot be started.
Thanks for any answer regarding this topic.

**Comment by legluondunet** [comment]
Hello, concerning Lutris games scripts, you will obtain more support on Discord or our forum. Issues on Github concern mainly Lutris app. @strycore could you close this issue?
