### ISSUE TITLE
LoL doesn't want to get installed

### ISSUE THREAD

**Issue by CreepyJeweller** [lutris/lutris#3268]
**Describe the bug**
When I'm trying to install LoL I get an error and installation just freezes

**Steps to reproduce**

- Start installing League of Legends
- Wait
- BOOM HERE COMES THE BLOCKER

**Lutris debugging output (Optional)**
Unable to load locale dir, translations won't work.
2020-11-10 01:13:29,319: Getting full game list from MAME...
2020-11-10 01:13:29,319: MAME XML generation launched in the background, not returning anything this time
2020-11-10 01:13:29,319: MAME isn't installed, can't retrieve systems list.

(lutris:16641): Gtk-WARNING **: 01:13:29.359: Theme parsing error: gtk.css:6329:10: 'height' is not a valid property name
INFO     2020-11-10 01:13:29,379 [application.do_command_line:275]:Running Lutris 0.5.7.1
INFO     2020-11-10 01:13:29,379 [startup.check_driver:54]:Using NVIDIA drivers 455.38 for x86_64
INFO     2020-11-10 01:13:29,379 [startup.check_driver:58]:GPU: GeForce GTX 970
INFO     2020-11-10 01:13:29,379 [startup.check_driver:73]:GPU: 10DE:13C2 3842:2974 using nvidia drivers
INFO     2020-11-10 01:13:29,434 [startup.check_vulkan:124]:Vulkan is supported

(lutris:16641): Gtk-WARNING **: 01:13:29.472: Theme parsing error: gtk.css:6329:10: 'height' is not a valid property name
DEBUG    2020-11-10 01:13:29,580 [http.get:71]:GET https://lutris.net/api/runtime
INFO     2020-11-10 01:13:29,832 [mame.notify_mame_xml:31]:MAME XML written
INFO     2020-11-10 01:13:43,315 [application.do_shutdown:520]:Shutting down Lutris

**System information (Optional)**
Fedora 33
![Screenshot from 2020-11-10 00-53-31](https://user-images.githubusercontent.com/45186238/98611358-11bd9800-22f2-11eb-894b-2348a441b56d.png)

**Screenshots (Optional)**

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by byte1024** [comment]
Don't think there's enough info here. Someone probably needs to provide a better log and / or more testing.

**Comment by legluondunet** [comment]
Please update you Lutris version to 0.5.8 and use last Lutris script installer for League of Legend.
If you still have problem to install this game, you will obtain more support on Discord or our forum.

**Comment by legluondunet** [comment]
@strycore you can close this issue?
