### ISSUE TITLE
[Request] Can we add  winecfg to Lutris

### ISSUE THREAD

**Issue by hk3wx** [lutris/lutris#3273]
It would be really helpful to have a 'winecfg' added to the button.
And here I thought control panel was the cfg ¬¬

![lutris](https://user-images.githubusercontent.com/26763836/98987310-d5ae5100-2504-11eb-94f0-575aee039e4d.png)

**Comment by strycore** [comment]
We have winecfg. You're not seeing it because you have Proton instead instead of Wine as your version.
