### ISSUE TITLE
metainfo fails on validation after 0.5.8

### ISSUE THREAD

**Issue by A6GibKm** [lutris/lutris#3277]
```
$ appstream-util validate net.lutris.Lutris.metainfo.xml 
```

Fails, the output is 

```
net.lutris.Lutris.metainfo.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [GPL-3.0+]
• attribute-invalid     : <screenshot> width too large [https://lutris.net/static/images/lutris-window.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://lutris.net/static/images/lutris-window.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://lutris.net/static/images/lutris-window.png]
• style-invalid         : <image> has horizontal padding [https://lutris.net/static/images/lutris-window.png]
Validation of files failed
```

Somehow 

```
  <metadata_license>GPL-3.0-or-later</metadata_license>
```
is invalid while 

```
  <project_license>GPL-3.0-or-later</project_license>
```

is valid.

**Comment by A6GibKm** [comment]
See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html.

**Comment by stephanlachnit** [comment]
> ```
> $ appstream-util validate net.lutris.Lutris.metainfo.xml 
> ```
> 
> Fails, the output is 
> 
> ```
> net.lutris.Lutris.metainfo.xml: FAILED:
> • tag-invalid           : <metadata_license> is not valid [GPL-3.0+]
> • attribute-invalid     : <screenshot> width too large [https://lutris.net/static/images/lutris-window.png] maximum is 1600px
> • attribute-invalid     : <screenshot> height too large [https://lutris.net/static/images/lutris-window.png] maximum is 900px
> • style-invalid         : <image> has vertical padding [https://lutris.net/static/images/lutris-window.png]
> • style-invalid         : <image> has horizontal padding [https://lutris.net/static/images/lutris-window.png]
> Validation of files failed
> ```

The image stuff is purely optional, they work fine in KDE Discover and Gnome Software.

> Somehow 
> 
> ```
>   <metadata_license>GPL-3.0-or-later</metadata_license>
> ```
> is invalid while 
> 
> ```
>   <project_license>GPL-3.0-or-later</project_license>
> ```
> 
> is valid.

Run `appstreamcli --pedantic --explain` and you will see why. It's not a big issue (even if e. g. the FSFAP or CC0-1.0 would be more approriate).

**Comment by A6GibKm** [comment]
Indeed the images are not an issue.

The problem is that that license issue is a blocker for building https://github.com/flathub/net.lutris.Lutris. GPL-3 is a code license, whereas metainfo files should probably use CC0 which is GPL compatible. I cannot patch the file downstream due to the legal nature of the issue.

**Comment by stephanlachnit** [comment]
You'll need to ask @strycore then to change it. AFASIK both FSFAP as well as CC0-1.0 are widely accepted as metainfo licenses due to their nature of being public domain (-ish).

**Comment by A6GibKm** [comment]
I think the best scenario would be to have in master this change (GPL -> CC0-1.0 or FSFAP), and cherry pick that commit downstream.

**Comment by strycore** [comment]
If it won't be an issue for Debian inclusion then I'm ok making the metainfo CC0. 
It was CC0 at some point but I changed it back to GPL-3 because I wanted to limit the number of license we use. If Flatpak isn't ok with that for some reason, please send a PR with the CC0 change.

**Comment by stephanlachnit** [comment]
CC0-1.0 is fine with Debian.
