### ISSUE TITLE
Lutris and the new Steam Sync issues

### ISSUE THREAD

**Issue by LiamDawe** [lutris/lutris#3279]
With the new system pulling games in with the Steam Sync feature (which is nice), the app entirely freezes whilst it's doing it. I was about to kill it when it suddenly popped back to life.

Is there anything that can be done to prevent the whole thing locking up while it does it?

Additionally, while it detects owned games, I still have to go through and "install" them to have Lutris realise they're already installed. That could do with some improving too.

With regards to the above: on top of that, there's also an issue that comes up with the likes of Blasphemous. It's now supported on Linux, but I can't seem to set it up with Lutris + Steam as Lutris only gives the Windows install option? 
Shot: https://imgur.com/a/wlNamij (this is again, despite it already being installed for Linux).

**Comment by strycore** [comment]
I've addressed the 3rd point. There should be no game with both a steam and winesteam installer. All winesteam installers that are basic enough have been converted to proton and this leaves us with 259 remaining installers for winesteam which are a bit more advanced and chose not to migrate automatically.

**Comment by strycore** [comment]
Closed in 0.5.9
The other 2 points have been addressed
