### ISSUE TITLE
lutris lutris:rungameid/ does not work

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#3281]
**Describe the bug**

Using desktop shortcut does work, lutris not starting the game.

**Steps to reproduce**

- Install kubuntu 20.10 + lutris 0.5.8.
- Install game, create a desktop shortcut from lutris.
- Try to launch game using desktop shortcut

**Lutris debugging output (Optional)**

All log:
```
~
❯ lutris -d lutris:rungameid/1219
INFO     2020-11-15 15:53:55,474 [application.do_command_line:319]:Lutris 0.5.8
INFO     2020-11-15 15:53:55,474 [startup.check_driver:69]:Running X.Org Mesa driver 20.2.2 on Radeon RX 560 Series (POLARIS11, DRM 3.39.0, 5.9.8-xanmod1, LLVM 11.0.0) (0x67ff)
INFO     2020-11-15 15:53:55,475 [startup.check_driver:81]:GPU: 1002:67FF 1043:04BC (amdgpu drivers)
```
**System information (Optional)**
[lutris-issue-report.zip](https://github.com/lutris/lutris/files/5542468/lutris-issue-report.zip)

**Screenshots (Optional)**

If your issue is hard to explain with words, feel free to attach screenshots.

**Comment by pizzadude** [comment]
Same issue with lutris git build on Fedora 33 KDE.

**Comment by roerch** [comment]
can confirm this behaviour with the recent update (0.5.8) coming in yesterday for Debian testing. Desktop shortcuts using rungameid not working, however starting from Lutris itself, the games work.

**Comment by gsantner** [comment]
worked in the past, broken with 0.5.8

**Comment by solbero** [comment]
This also affects the [Lutris Kodi Addon](https://github.com/RobLoach/lutris-kodi-addon) since it uses `lutris lutris:rungameid/` to launch games.

**Comment by jpleau** [comment]
I have ran a `git bisect` and have found that a04c640e678e6851015ddaa311ca685f357c425a is the commit that introduced this issue. Investigating a bit more to see if I can find a fix but I have never look at lutris' code before, maybe someone will beat me to it!

**Comment by tuxtergames** [comment]
> Same issue with lutris git build on Fedora 33 KDE.

Could you fixed it? same problem here on F33 KDE, or the solution is create everything manual again?

**Comment by pizzadude** [comment]
> > Same issue with lutris git build on Fedora 33 KDE.
> 
> Could you fixed it? same problem here on F33 KDE, or the solution is create everything manual again?

I use this COPR for lutris git and it's fixed in this COPR. https://copr.fedorainfracloud.org/coprs/sentry/lutris-git/
