### ISSUE TITLE
automatically suggest a directory name for a game when you change the installation location

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3283]
by default lutris installs games in "~/ Games / + game slug folder"

1) ![Capture d’écran de 2020-11-14 18-28-08](https://user-images.githubusercontent.com/325405/99191377-a9950900-276c-11eb-87ec-762651c23aa7.png)

If I change install location, lutris will not add game slug folder at the end of the choose path:
2) ![Capture d’écran de 2020-11-14 18-29-16](https://user-images.githubusercontent.com/325405/99191419-e3660f80-276c-11eb-91fa-a77a71b55e82.png)

So the user have  to manually create a folder and name it, could it be possible to suggest the same directory name as picture 1)?

**Comment by strycore** [comment]
I am against it.

**Comment by legluondunet** [comment]
Strycore, I respect your decision, you are the project chief, but I'm interesting to know why?  I thnk thefeature I ask here for Lutris will add imho value.
In this case why Lutris suggests a folder in the first picture and not in the second one?

**Comment by legluondunet** [comment]
@strycore  , I respect your decision, you are the project chief, but I'm interesting to know why? I think the feature I ask here for Lutris will add (a little more) imho value.
In this case why Lutris suggests a folder in the first picture and not in the second one?

**Comment by strycore** [comment]
95% of the time, if I want to change the default location, it's to change the name of the default folder.
This means that when you click browse and select a destination then the game doesn't get installed in that destination but instead creates a subfolder which will hold the destination.
It seems that you should change the default path for your games, this would fix your issue.

**Comment by legluondunet** [comment]
> 95% of the time, if I want to change the default location, it's to change the name of the default folder.
95% of the time, when I want to change the default location, it's to change the hard drive because I don't have enough space on the Lutris default. And in this case, I have to create a folder with the name of the game slug manually when it could be automatic.
> It looks like you need to change the default path of your games, that would solve your problem.
not really but thank you for taking the time to answer my question.

**Comment by strycore** [comment]
There are several reasons to change the default folder name. I might have an existing copy of the game and I don't want to overwrite it. Or inversely, I want to write over an existing install that resides in another folder.
Say I want to move my-game to my-game2. Then doing as you would suggest would set the path to ~/Games/my-games2/my-game. Which is not what I asked for. In the other where I want to install the game in an already existing location, your suggestion would result in /some/other/location/my-existing-game/my-game, which is again, not what I'm asking for.

You really can solve your problem by setting your default path to a drive where you have enough disk space.

**Comment by AlexanderRavenheart** [comment]
You can just copy the slug name from the entry field, Browse to the new location and paste the copied slug name (with an / before the slug name).

**Comment by legluondunet** [comment]
Of course I could do that manually, @AlexanderRavenheart  please...:)
We could do a lot of thing manually but we don't, think more user support and friendly interface.
