### ISSUE TITLE
Heroes of the Storm crashes with fatal error since today's 1.8 update  (via apt)

### ISSUE THREAD

**Issue by adarknessinside** [lutris/lutris#3288]
Since lutris 5.8 update, HotS crashes on every launch. Battle.net is working, but HotS crashes with "Fatal error" (this is the message Battle.net is giving). 
I tried reinstalling Lutris, then installed V5.5 via Python, which caused several problems for me, so i restored the 5.8 version.
Overwatch is still working tho.

**Lutris debugging output (Optional)**

The terminal output of `lutris -d`.

it does not output anything to the shell.

![grafik](https://user-images.githubusercontent.com/74513654/99199485-c0a11e80-279f-11eb-9c0b-da96bcb1ca03.png)

**Comment by adarknessinside** [comment]
Maybe i should mention that there was no change to the game files in the meanwhile

**Comment by byte1024** [comment]
I think 1.8 is supposed to be 5.8?

You probably won't get anything from lutris -d since its a game within a "game" or launcher in this case. You need to open the launcher config of Lutris and enable debug log on the lightest log type and try again. That might be enough to get an error for the problem to show up after you open up Lutris console output not far from the config menu item.

**Comment by adarknessinside** [comment]
Yes, that is right, i am referring to Patch 5.8. Typo there ^^'
Where is the configuration file stored?

**Comment by adarknessinside** [comment]
[lutris.log](https://github.com/lutris/lutris/files/5543610/lutris.log)

**Comment by adarknessinside** [comment]
i played around with the wineprefix, changed Windows version to "Windows 10", now its working...

**Comment by byte1024** [comment]
Well that's one way. If it works, it works lol.

I was looking at your log and there's too many WIne errors to be sure what might be the cause there but I notice VKD3D-Proton was updated to 2.0 recently and maybe they pushed that with 5.8, I don't know. Also, if it was Lutris runtime, then you could also have tried to disable that in the config in Lutris for the launcher but that's really iffy to even get working in my experience.

Wine version looks like it probably didn't update, etc. So about all I can find is this without lots of time and testing.
