### ISSUE TITLE
python-magic dependency conflicts with file-magic (official python bindings for libmagic)

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#3292]
**Describe the bug**

I'm the Lutris packager for Mageia.

Lutris 0.5.8 added a dependency on `python-magic`, which is https://github.com/ahupp/python-magic

`python-magic` provides the `magic.py` module, which conflicts with the official Python bindings for libmagic provided by the `file` package (`python3-file-magic` on Mageia - previously `python3-magic` but I renamed it to make room for the conflicting `python-magic` package).

Long story short, those seem to be two competing implementations for the `magic` module and they can't be installed next to each other. Which means that once packaged in a distro, you can't install packaged software which independently require `file-magic` and `python-magic`.
Downstream issue (`rpmlint` and `lutris` can't be installed together): https://bugs.mageia.org/show_bug.cgi?id=27619

Upstream issue (8 years old, made some progress 2 years ago but still not resolved): https://github.com/ahupp/python-magic/issues/21

That's an unfortunate upstream issue and not directly related to Lutris but it does make packaging trickier. I'm not sure what the best solution would be here, but it might be worth checking if Lutris could use `python-magic` OR `file-magic`, whichever is installed? This would let distros settle on one fork as the main dependency for their packages.

**Steps to reproduce**

- Try to install a package that depends on `file`'s libmagic Python bindings together with Lutris that requires https://github.com/ahupp/python-magic

**Comment by Jan200101** [comment]
Quote from the Fedora Bug Report https://bugzilla.redhat.com/show_bug.cgi?id=1899279

```
Did a very quick source dive, it's used as part of the new automatic installers for gog and humble. Lutris degrades gracefully if it's not present — the install will complete, but you'll need to manually select the executable in the game's options afterward. Installers from Lutris.net should continue to work normally.
```
it should be noted that before a62c3149955416fd188b5a140de94d9831bee3f4 lutris didn't used to degrade but instead outright not work

**Comment by przerull** [comment]
I added a fairly lengthy note in the pull request #3320 for this.   Perhaps that should have been here instead (sorry).
