### ISSUE TITLE
Lutris 5.8 breaks existing desktop shortcuts and new shortcuts don't work

### ISSUE THREAD

**Issue by shag00** [lutris/lutris#3294]
**Describe the bug**

Clicking on a lutris 5.7 desktop shortcut or a new 5.8 shortcut does not start the game. Cursor changes to a game option curser and then the whole start process just stops.

**Steps to reproduce**

- turn on pc, click shortcut

**Lutris debugging output (Optional)**

**System information (Optional)**
AMD 3077X
Kubuntu 20.10

**Screenshots (Optional)**

**Comment by pizzadude** [comment]
Duplicate of #3281
