### ISSUE TITLE
Improving the local installer cache

### ISSUE THREAD

**Issue by gatl** [lutris/lutris#3296]
I'm not sure I understand the new cache button in the installation dialogue. It is not intrusive, but I imagine it could be improved.

This is my use-case: I have my game installers backed up locally, and as you understand, I prefer to install from there if possible.
Here is how I would expect the cache system to work:

1. A global preference option exists to set the default cache location.
2. When I install a game, Lutris will look through that location, recursively, and look for each file it needs. (They are likely all in the same directory).
3. Each file it cannot find, it will propose to download from the game store.
4. Each file it _did_ find could also be changed to download, if desired.
5. Manual selection of game files may be activated at this point.
6. Now that I know how big the download will be, I could make a more informed decision on where to place the cached files (and if I need them). Since I like to keep my own library my way, it makes sense for me to point Lutris to some provisional location and move them at a later time to a proper place. The files will be found by Lutris at the default location in the future. But to me, the cache button only makes sense at _this_ point.

I don't think this is an outlandish usage of the cache. I could even set it up as $HOME/Downloads or even at $HOME if I'm not an organized person (though it may take a bit of time searching in that case). Hopefully the current system can be improved.

**Comment by strycore** [comment]
Yes, this is pretty much what lutris is already doing. I agree that the UI could be made better.
