### ISSUE TITLE
Headerbar buttons dont work with new UI

### ISSUE THREAD

**Issue by Tids** [lutris/lutris#3297]
**Describe the bug**

With version 0.5.8, 2 headerbar buttons do not work. I can't tell what they would do.

**Steps to reproduce**
- Start Lutris
- click the 2 most right buttons

**Lutris debugging output (Optional)**

The terminal output of `lutris -d`.
lutris -d
Unable to load locale dir, translations won't work.
2020-11-20 10:04:27,299: Your version of python-magic is too old.
INFO     2020-11-20 10:04:27,464 [application.do_command_line:319]:Lutris 0.5.8
INFO     2020-11-20 10:04:27,465 [startup.check_driver:69]:Running X.Org Mesa driver 20.2.2 on AMD RENOIR (DRM 3.39.0, 5.9.9-zen1-1-zen, LLVM 11.0.0) (0x1636)
INFO     2020-11-20 10:04:27,465 [startup.check_driver:81]:GPU: 1002:1636 1043:10B2 (amdgpu drivers)
DEBUG    2020-11-20 10:04:27,816 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-20 10:04:27,974 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-11-20 10:04:29,627 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-20 10:04:29,801 [http.get:73]:GET https://lutris.net/api/runtimes/icons
DEBUG    2020-11-20 10:04:32,023 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-20 10:04:32,186 [http.get:73]:GET https://lutris.net/api/runtimes/icons

**Screenshots (Optional)**
Here is a Video: https://streamable.com/9wa0fs

**Comment by Xathros1** [comment]
I have exactly the same problem with openSUSE Tumbleweed (Gnome)
The pull-down menu and the options menu in the upper right corner of Lutris cannot be opened
Same debugging output

**System information (Optional)**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/5583211/lutris-issue-report.zip)

**Comment by ilyazzz** [comment]
Same issue on Arch Linux with Sway. A workaround is to run lutris with XWayland with `GDK_BACKEND=x11 lutris`.

**Comment by Xathros1** [comment]
> Same issue on Arch Linux with Sway. A workaround is to run lutris with XWayland with `GDK_BACKEND=x11 lutris`.

thanks, the mentioned workaround works

**Comment by elsandosgrande** [comment]
I too am getting this with Wayland, but only Wayland.

```
Gdk-Message: 12:59:02.586: Window 0x36d9090 is a temporary window without parent, application will not be able to position it on screen.

(lutris:20969): Gdk-CRITICAL **: 12:59:02.603: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```

**Comment by mihawk90** [comment]
@Tids considering the above comments all only relating to Wayland, please clarify whether you are running an X11 or Wayland session and if it is reproducible on both or only Wayland for you.

**Comment by nunocastromartins** [comment]
I can also confirm on my end that it only happens with Wayland, both popups in the headerbar and bottom "game bar" don't work. This makes it impossible to, for example, use "Run EXE within Wine prefix" on Wayland (without using the XWayland workaround mentioned above).

**Comment by Tids** [comment]
@mihawk90 Default GNOME, so yes it's the wayland one. I also can confirm that @Xathros1workaround `GDK_BACKEND=x11 lutris` works.

**Comment by strycore** [comment]
I've made a patch that should resolve this but I don't have Wayland. Can someone confirm the master branch no longer has the issue?

**Comment by ilyazzz** [comment]
Still broken, tried on both on GNOME and Sway.

**Comment by strycore** [comment]
I've reopened the issue here: https://github.com/lutris/lutris/issues/3341

**Comment by strycore** [comment]
Wrote another patch, it's good now.
