### ISSUE TITLE
[Design] selection "box" of the left panel looks alien

### ISSUE THREAD

**Issue by Tids** [lutris/lutris#3298]
**Describe the bug**
The new UI brings in a new left panel. That's pretty cool. However, the panel on the left brings in a round-edged focus for the element that is currently selected. This elements looks very out of place and is not part of any repeating design language concept, because highlight and buttons have sharper edges

**Screenshots**
#### Full view
![image](https://user-images.githubusercontent.com/18744080/99783399-ab6b1d80-2b1a-11eb-845c-5a568379a4e4.png)

##### Hover over different element:
![image](https://user-images.githubusercontent.com/18744080/99781806-9b523e80-2b18-11eb-8605-4f307bd7f6ef.png)

##### Hover over selection:
![image](https://user-images.githubusercontent.com/18744080/99782411-6397c680-2b19-11eb-9fa1-36640356c161.png)

##### Click on selection:
![image](https://user-images.githubusercontent.com/18744080/99782380-5549aa80-2b19-11eb-9f39-aa43f5d5af1b.png)

##### just use the GTK defaults (if there are) or flat elements.
![image](https://user-images.githubusercontent.com/18744080/99783161-5b8c5680-2b1a-11eb-8248-64f80009536c.png)
![image](https://user-images.githubusercontent.com/18744080/99783331-95f5f380-2b1a-11eb-907e-1bd0c4c4ebd1.png)

**Comment by Sporknife** [comment]
I totally agree with this user. I too suggest usage of flat elements.

**Comment by bsdf** [comment]
with #3284 being merged, you can add this following to your `gtk.css`:

```css
#lutris .sidebar row {
  border-radius: 0;
}
```

**Comment by Tids** [comment]
@bsdf I think it would be more clean if this would be the standard and the "with-border-radius>0" option could be an option.

**Comment by ernestask** [comment]
Honestly, I find it hilarious that the GTK interface is built by KDE users. There are more alien design choices, but this one smacks you over the face quite early when starting to use Lutris (well, and the padding + separator in the “Missing vulkan libraries” dialog).

**Comment by Tids** [comment]
@ernestask please stay polite. Pointing fingers at each other won't help.

**Comment by ernestask** [comment]
Not to veer too far off-topic, but you’re misinterpreting me. It makes no sense to write an interface using a toolkit that’s not native to the DE that you use, because, more often than not, the end result will be the worst of both worlds, as we’re seeing here.

**Comment by claike** [comment]
@ernestask as far as my experience goes both gtk and qt are equally as good and l&f-wise it's only the developers to blame for their poor design choices, not the toolkit. If some KDE user want to write apps with GTK considering the great support for GTK that KDE provides does that make a difference? At the end of the day they'd look exactly the same so what's your point?

**Comment by claike** [comment]
And I also find this being a poor design decision, that just doesn't fit. Considering that most of the things in the UI are rectangular objects this actually looks alien.
