### ISSUE TITLE
/usr/bin/wine script from wine-development package is not monitored by fuser

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#330]
https://lutris.net/games/install/2498/view

game works also in normal wine:

    WINEPREFIX=~/Games/airmech wine "C:/AirMech.exe"

**Comment by strycore** [comment]
Works great here, do you have any error message?

**Comment by sixsixfive** [comment]
no, it just kills itself:

https://drive.google.com/file/d/0B_2_dsXrefR-cUNKMmU1WVZFTmc/view?usp=sharing

[log.txt](https://github.com/lutris/lutris/files/429144/log.txt)

**Comment by strycore** [comment]
hmm, interesting. When the game launches, Lutris only sees a zombie process and terminates the game. On my end, I also get the zombie process but also have another AirMech.exe process marked as running. I assume that the zombie is C:/AirMech.exe while the running one is C:/users/strider/Application Data/Carbon/AirMech/AirMech.exe but Lutris doesn't pick up the other one on your config.

**Comment by strycore** [comment]
Ah right, thanks for pointing that out. I'm used to the WineHQ PPA so I need another method for detecting wine binaries for this package
