### ISSUE TITLE
PlayStation Now - File Not Found

### ISSUE THREAD

**Issue by cow-killer** [lutris/lutris#3307]
**Describe the bug**
Black screen when running PS Now. DXVK, Esync, Fsync disabled, using lutris-5.7-8, compatibility set to Windows XP. Small window that says "file not found".

**Steps to reproduce**
- Install PS Now through Lutris
- Get a "file not found" error

**System information**
Adding system info to [Pastebin](https://pastebin.com/Wj2rd9H8), as GitHub apparently doesn't support `JSON` files as attachments.

**Screenshots**
![Screenshot from 2020-11-21 01-05-10](https://user-images.githubusercontent.com/12868939/99869192-122e1c80-2b97-11eb-8e4f-3380e08be816.png)

**Comment by mihawk90** [comment]
1. This is not an issue with the Lutris client.
2. You didn't specify which installer you used, the PS Now page has 2.
3. If the file is not present you changed install paths in the PS Now installer and/or didn't go through the entire installation
4. PS Now works fine
5. Join the Discord and ask for help there, #lutris_support channel. (or the IRC if that's your jam)

**Comment by cow-killer** [comment]
Thanks for the curt response, I uninstalled the application and re-installed it through the "Install" button on the page you linked, seems to be working fine now. Thanks, I guess.
