### ISSUE TITLE
"Rename error" on multiple game installs

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3315]
I'm getting this error for multiple games when installing: `Rename error, source path does not exist: /home/user/Games/broken-sword-1-shadow-of-the-templars-directors-cu/data/noarch`. Since it's not isolated to a single game I'm assuming it's not a script specific problem.

If I had to guess I'd say it's related to the cause I mentioned in this issue: https://github.com/lutris/lutris/issues/3216#issuecomment-715572953 i.e. trying to run a 64 bit exectutable on a 32 bit platform.

Version 0.5.7.1

**Comment by byte1024** [comment]
> If I had to guess I'd say it's related to the cause I mentioned in this issue: #3216 (comment) i.e. trying to run a 64 bit exectutable on a 32 bit platform.

If I had to take a guess at what you're saying there, I think you're confused or over complicating it.

All programs are either 32 bit, 64 bit, or mixed 64 bit with some 32 bit stuff. The 32 bit only installers/programs need a pure 32 bit prefix. The second one needs 64 bit prefix. The last one requires a mixed 64 bit prefix (this is the same as selecting 64 bit with Lutris) which is standard as there are mixed games/applications that I run on Wine and Proton using 64 bit.

You can select to use 32 bit prefix in Lutris game/application config and then it will create a 32 bit prefix if you eg run winecfg after saving it (as long as you don't have an existing 64 bit prefix already).

I have no idea why you're getting a path does not exist error though or what you're doing. Didn't read your whole issue thread. Never seen this before with 64 and 32 bit installs.

**Comment by anohren** [comment]
> If I had to take a guess at what you're saying there, I think you're confused or over complicating it.
uff (games have been this way for a while).

That's not what I'm saying. I'm saying you can't run 64 bit executables on 32 bit hardware. I think that's as simple as it can get. 

I'm afraid I could not put the rest of your post into the context of this bug report. What does wine prefixes have to do with this?

> I have no idea why you're getting a path does not exist error though or what you're doing. Didn't read your whole issue thread. 

That would explain it. Although you would only have had to read the one comment that was linked to to get an idea.

**Comment by byte1024** [comment]
> > If I had to take a guess at what you're saying there, I think you're confused or over complicating it.
> 
> That's not what I'm saying. I'm saying you can't run 64 bit executables on 32 bit hardware. I think that's as simple as it can get.

Of course you can't. That's a hardware limitation. Its not even a bug to be reported. Like I said, I think you're confused or over complicating it.

You cannot run 64 bit on 32 bit hardware. Its not backwards compatible.

**Comment by anohren** [comment]
> Its not even a bug to be reported

Good thing I'm not reporting that. I'm reporting not being able to install multiple games. The two are distinct. Reread the OP.

> You cannot run 64 bit on 32 bit hardware. Its not backwards compatible.

Yes, I believe I made that point already.

If multiple 32 bit games get slapped with 64 bit utilities in their install scripts and thereby get constrained to 64 bit platforms just because the utilities aren't referenced in an architecture independent way, then that's not "not backwards compatible" — it's just bad design, or a mistake.

> Also just because a game or application is regarded as 32 bit, the installer executable may still be 64 bit so those won't run on 32 bit hardware anyway.

> The only thing you can do is to use a 32 bit prefix

I'm supposed to run the example 64 bit Linux `unzip` utility in a 32 bit Wine prefix? You're right, you solved the problem there.

It still seems you haven't taken the time to understand this bug report nor the linked comment.

> The fact that you can't understand that yet means that you're confused.

You seem to like to point that out.

> Both issues should be closed.

Unsurprisingly lacking any trace of justification.

**Comment by strycore** [comment]
This is valid. Installers for 32bit games should not rely on 64bit tool. Furthermore, any installer downloading unzip instead of calling the extract installer command should be considered of low quality and broken and should be fixed.
No good lutris installer downloads a copy of unzip.

**Comment by strycore** [comment]
There is another ticket regarding the removal of unzip from installers: #4852

**Comment by anohren** [comment]
I seem to recall this being part of a milestone for a long time, but it's not planned now? Why is the duplicate issue (created three years later) still open then? Sorry, having some difficulty interpreting the signals.

**Comment by strycore** [comment]
I'm not sending signals, just cleaning up Github issues.
Now, if you want to make yourself useful, there's a bunch of installers that need migrating: 
https://fosstodon.org/@lutris/110427302868300313

It's at anyone's reach.

**Comment by anohren** [comment]
> I'm not sending signals

That's kind of a strange thing to say in an open forum meant for communication, where every message generates a signal (whether we think it does or not), and where every message will notify others, who subsequently have to interpret them. It's like me saying I was "not communicating" when I opened an issue :) 

I just asked for clarification, but by all means... I can't force anyone to clarify what the conflicting signals mean, even though I firmly believe that clear communication also is within our collective reach.

Sorry to hear that you don't think I'm being useful.

**Comment by anohren** [comment]
To clarify from my point of view: the tag "not planned" conflicted with the open status of the duplicate issue in my mind, while, earlier, the "milestone" gave me the impression that "maybe I'll see it in a future update". 

Now, I'm not currently invested in the project more than opening a few issues and maybe follow their statuses. That's what I tried to do here. If I'm supposed to open issues mainly if I'm prepared to tackle them myself then that's fine as far as policy goes, but if that's the case I just wasn't aware of that. I simply had this archived under "someone familiar with the code base, installer intricacies and database probably knows of a quick fix when the time comes".

**Comment by danieljohnson2** [comment]
@anohren, I'm not sure what is troubling you. I think @strycore is just consolidating issues, not dismissing them. He's not saying this stuff should not get fixed.

He just doesn't want GitHub issues to grow into a Cthulhoid monstrosity that eats Cincinnati.

**Comment by anohren** [comment]
> He just doesn't want GitHub issues to grow into a Cthulhoid monstrosity that eats Cincinnati.

That's a valid concern. 

I guess that when it said "not planned" I interpreted it as "not getting fixed". Was that the wrong interpretation? 

You'll notice also that I asked how to interpret that signal.

How would you suggest I go about this in the future @danieljohnson2 ?

**Comment by danieljohnson2** [comment]
Well, GitHub only gives us the option to close as 'completed' or 'not planned', and this hasn't be completed. He did post a message pointing at the issue that will carry this stuff going forward.

I think you might do better to try to find the pre-existing issue yourself, and contribute to that, if you can. I do understand that this can be hard to do, and it's not always obvious when two issues are really the same thing.

We do what we can, and clean up the mess afterwards. That's life in the big repo!

**Comment by anohren** [comment]
> GitHub only gives us the option to close as 'completed' or 'not planned'

Got it. Haven't been very active here lately and have forgotten how bad GitHub is at generating proper signals. 

Thanks for the advice. 

> I think you might do better to try to find the pre-existing issue yourself

So in this case I guess I did pretty well considering that I created the pre-existing issue?

**Comment by danieljohnson2** [comment]
You did? Why create two then?

**Comment by anohren** [comment]
> You did? Why create two then?

Sorry, I'm not following. This issue and... which is the other one I created?

**Comment by danieljohnson2** [comment]
Oh, I see. This is the older one; @strycore decided to keep the new one. I guess you should have made @SaltSouls find you item. Please dispatch your flying monkeys accordingly.

**Comment by anohren** [comment]
> I guess you should have made @SaltSouls find you item. Please dispatch your flying monkeys accordingly.

I'm not really into scouring arbitrary repos for duplicates of year-old issues, and it's up to the project members which of them to close. Me, I just got notified of activity and wanted to stay updated. I'm certainly not going to complain to anyone that they opened a duplicate — especially if it seems to have benefited the project owner.

But sure, speaking of signals, closing the older issue does send one, in case you want to cultivate the behavior you're advocating.

Anyway, thanks for resolving the ambiguity about "not planned" for me!

**Comment by strycore** [comment]
There is a design issue with Gtihub for sure. The "Not planned" option includes duplicates as well. 

![image](https://github.com/lutris/lutris/assets/280336/9c39e480-e436-43a4-b198-0ba4a86ec3ee)

Anyway, regardless of the signals we send, this is eventually getting fixed. This issue doesn't belong to this repo because there's no work on the client involved.

As I don't see anyone wanting to fix over 100 scripts, I'll likely script the whole thing as a task in the lutris website.

**Comment by strycore** [comment]
Finally done! No more installers using unzip.

**Comment by anohren** [comment]
Nicely done! I'll try it out next time I touch that machine
