### ISSUE TITLE
Lutris does not delete game directory

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3317]
Hello,
I don't know why Lutris does not want to delete some games directory.
For example Enemy Territory https://lutris.net/games/wolfenstein-enemy-territory/:
![Capture d’écran de 2020-11-25 11-35-27](https://user-images.githubusercontent.com/325405/100221329-d12c6400-2f18-11eb-8a57-6f28e034f6e3.png)

**Comment by odziom91** [comment]
I had "similar" story but in my case... Lutris deleted whole directory with all games. I'm pretty sure that I don't make a mistake. From now I remove all data from unused games manually. :)

**Comment by legluondunet** [comment]
@odziom91 that's another issue that is already reported.

**Comment by strycore** [comment]
This working as designed to avoid the kind of problem @odziom91 had.
