### ISSUE TITLE
FS-Launcher issue

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#332]
I've added lotus esprit challenge 2 to lutris using the command 
**executable**: fs-uae-launcher 
**argument**: c7a3263c-b075-5951-807f-4133db25f62e
using that in the terminal works, but it won't launch from lutris complains: http://pastebin.com/FYDkCuUN

 I've created a lotus2.sh and added the command to it, and it'll complain in lutris but not in the terminal.  btw I'm using the latest development release from ppa:fengestad/devel

**Comment by strycore** [comment]
I'll put aside the fact that you're using a game launcher to launch another game launcher to launch  a game for now and focus on the issue ;)

Both Lutris and FS-UAE launcher are written in Python so it appears that Lutris is modifying the Python path in some way and FSUAE can't import the modules when being run from Lutris.

I need to inspect this closer by reproducing the issue, then I'll be able to figure out what's going on by inspecting the content of sys.path

**Comment by strycore** [comment]
I was unable to reproduce this issue

**Comment by telanus** [comment]
Ok, tested here again, still get the problem, but found that disabling the lutris runtime will make it work

**Comment by strycore** [comment]
So a runtime issue, not a Python issue, interesting.
