### ISSUE TITLE
game not appear in library

### ISSUE THREAD

**Issue by ludo77** [lutris/lutris#3321]
Hello,
I have 1 game which does not appear in the lutris library although it appears in sources.
And I have games that appear several times in the library

How to reset this
Thanks

**Comment by SwimmingTiger** [comment]
Did you hide it? Try this option:

![ScreenShot](https://user-images.githubusercontent.com/4986069/101123989-0465a600-3631-11eb-8776-e8ffc0d84687.png)

https://github.com/lutris/lutris/issues/3345

**Comment by strycore** [comment]
This issue doesn't give enough details to have a resolution, closing.
