### ISSUE TITLE
Lutris 5.21-2-x86_64 and directx 12

### ISSUE THREAD

**Issue by nipnipj** [lutris/lutris#3322]
Is anyone else having a black screen (the game runs normaly --- you can interact with it, but u can see the actual game) when trying to run games on Directx 12 api?

**Comment by nipnipj** [comment]
I think lutris is not using DKD3D.

**Comment by byte1024** [comment]
Lutris should be using VKD3D-Proton as far as I know.

Is there more info to go with this? Did the gane work in dx12 with older Lutris, Wine, or VKD3D-Proton version?

**Comment by strycore** [comment]
This is a claim that Lutris 5.21-2 does not support VKD3D which it does. I just tested it on Metro Exodus. This claim is therefore false and I am closing the issue since nothing else can be done without further information.
