### ISSUE TITLE
Add Ruffle as a runner

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#3338]
With [Ruffle](https://ruffle.rs/) now being able to play a number of games, it'd be nice to have a runner of it.

**Comment by strycore** [comment]
I'm interested as well but I've heard it has really bad performance at the moment. Like 3 fps on the binding of isaac. Usability might be better on some older titles.

**Comment by Hasnep** [comment]
I have a fork [here](https://github.com/Hasnep/lutris) where I added Ruffle as a runner, but I discussed it briefly with @strycore on Discord back in December 2020, and we agreed that while Ruffle only has nightly releases it doesn't make sense to add it and we can come back to this when Ruffle has a stable release.

**Comment by strycore** [comment]
@Hasnep going to merge your runner, Ruffle should be stable enough now.

**Comment by strycore** [comment]
Looks good!

![image](https://github.com/lutris/lutris/assets/280336/0b1e6c19-b4a2-4262-9c3b-71d85360f3e1)

**Comment by Hasnep** [comment]
Great! Glad it still worked after two years! :sweat_smile:
