### ISSUE TITLE
Users Still Having Problems With Headerbar Buttons 0.5.8.1

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#3341]
Looks like some Fedora users are getting issue #3297 even with version 0.5.8.1

I'm not personally getting the issue, but it's been mentioned a few times here https://bodhi.fedoraproject.org/updates/FEDORA-2020-067fec37a1

**Comment by strycore** [comment]
I've made a patch but I don't have a Wayland setup to test it on. From what I've gathered from the report, the headerbar menus were missing a parent widget and they now have one defined.

**Comment by strycore** [comment]
Re-opening. Patch did not help.

**Comment by strycore** [comment]
Should be good now, I wrote the patch on Fedora 33.
I have no understanding of the solution. I just have a more negative perception of Wayland now.

**Comment by ilyazzz** [comment]
The bug is still present for the menus on the bottom bar (near play and wine configuration buttons)

**Comment by strycore** [comment]
Oh, so that means it's not related to the header bar... Should be an easy fix.

**Comment by strycore** [comment]
It wasn't easy.

**Comment by A6GibKm** [comment]
I did not want to open a new issue for this, but I wanted you to know that the fix works on the flatpak version in wayland :confetti_ball:.

*But*,  you can open both menus simultaneously. The popover api allows to close them automatically afaik.

**Comment by strycore** [comment]
> The popover api allows to close them automatically afaik.

The issue was that modal popovers (the ones that close automatically) don't display on Wayland so now we have this subpar behavior without the ability to do anything about it.

**Comment by A6GibKm** [comment]
This has nothing to do with modal, I am testing Shortwave and opening one popover menu closes the other, in wayland of course.

**Comment by strycore** [comment]
You believe what you want but the fix was to add `popover.set_modal(False)`.

**Comment by strycore** [comment]
Also, ShortWave is in Rust which seems much closer to C Gtk+ in regards of API stability. With PyGObject it's a total mess.

**Comment by strycore** [comment]
It's not like the code isn't open source anyway or that my commits haven't been detailed. It easily reproducible and I have been the only person trying to find a solution. The popovers have been here for a while and I don't see what would have broken them in Wayland except some arbitrary breakage. Random API breaks have happened before, in minor versions, so I wouldn't be surprised.

**Comment by A6GibKm** [comment]
@strycore Those popups should have never been modal as that is intended only for top windows, so indeed removing that prop solved the issue. But my point is that they should hide automatically when clicking elsewhere, and that there is something weird still, modal has nothing to do with it. In any case, thanks for the fix!, I have to admit that I failed at it.

I been playing a lot with both rust and & python bindings, and I assure you that the bindings work the same in terms of GTK. In password safe (python), popover menu also disappears when clicking elsewhere).

I suggest you to add to lutris' never ending TODO list (I know how it is to handle a pygobject project, it never stops giving work) to port them to <menu>, see https://developer.gnome.org/gtk3/stable/GtkPopover. If there is any plan for an eventual port to GTK 4, thats a must anyways.

**Comment by strycore** [comment]
> Those popups should have never been modal as that is intended only for top level windows
The popovers where made in Glade and had what I believe default settings, nothing fancy. And there are working fine with X. 
I would like to know more about why this solved the issue because I don't understand what the issue is to being with. I don't think we've done anything weird to the PopOvers.
> to port them to <menu>, see https://developer.gnome.org/gtk3/stable/GtkPopover

It is not clear what I need to port, I have read that page previously and it seemed we were doing things accordingly. If not, I don't see what we're not doing right.

> If there is any plan for an eventual port to GTK 4, thats a must anyways.

Once Gtk 4 is shipped in every distro we support, we can start working on Gtk4 specific features.

**Comment by A6GibKm** [comment]
> The popovers where made in Glade

Glade is known for adding incorrect or deprecated properties :(.

When I have the time I will try to submit a PR with some menus ported.

**Comment by strycore** [comment]
We have to make sure that any changes do not break compatibility with older systems. I do not know yet what really causes the bug, I just found a workaround. I still think it's worth investing some more for the 0.5.8.3 release and at the very least restore 0.5.7's behavior.

**Comment by strycore** [comment]
I managed to find the cause of the problem. The window initialization was done on a `map-event` handler. On Wayland, `map-event` is called every time the header bar buttons are clicked, which calls the window initialization again instead of showing the popup menu.
This way, I able to restore the original behavior of popovers.
