### ISSUE TITLE
jail execute commands to $cache and $gamedir

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#335]
It's probably not a good idea to let installer scripts modify the whole filesystem. It would also enough if people could view/inspect/(maybe modify) the game installer before running

**Comment by sixsixfive** [comment]
also this should have top priority since its a huge security flaw

**Comment by strycore** [comment]
Do you have a proposal on how we should implement this?

**Comment by sixsixfive** [comment]
a text view/edit option shouldn't be an issue

for a jail: fakechroot could be the answer maybe a restricted shell would be enough
