### ISSUE TITLE
Lutris crashed when I try to reinstall a cancelled install

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3357]
Hello,
Lutris crashes each time I did that actions:

1) install a game from Lutris interface
2) during install, click on cancel button
3) reinstall the game from Lutris interface, Lutris crashes

![Peek 29-12-2020 21-43](https://user-images.githubusercontent.com/325405/103312983-f8e28080-4a1e-11eb-8ea5-c6e87f49f455.gif)

I can reproduce this crash everytime on different computers/distributions and with different Lutris version since 5.8.

log:
https://paste.ubuntu.com/p/pqzyyk87Tf/

**Comment by strycore** [comment]
I have had this crash as well

**Comment by strycore** [comment]
Well I can't reproduce it on my dev machine so it's getting postponed to 0.5.9 because it's a bit of an edge case.

**Comment by stephanlachnit** [comment]
FYI: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982255

**Comment by strycore** [comment]
`sudo apt install python3.9-dbg python3-gi-dbg libglib2.0-0-dbgsym libgtk-3-0-dbgsym libffi7-dbgsym`

well that looks like something I can make use of. I wish it was more common knowledge...

**Comment by emorrp1** [comment]
To be honest it was a bit of a pain to figure out, you have to find anywhere the stacktrace contains `?? ... libfoo.so` then either hope "apt install libfoo" tab completion mentions -dbg or -dgbsym or just start searching for libfoo etc. until all the question marks have disappeared. Also needed to add a repo entry, learn how to gdb a python app and crash lutris several times - overall a "fun" experience.

```
# /etc/apt/sources.list
deb http://deb.debian.org/debian-debug buster-debug main contrib non-free
```

**Comment by strycore** [comment]
It doesn't seem this happens anymore. Which is good because no one could debug the issue.
