### ISSUE TITLE
continue button inactive when I install a game and setup files are already cached

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3358]
Tried to install Dead Space GOG, with last git version, I can not click on "Continue" button.

I can reproduce this bug on another computer, but only the second time I tried to install it, once the install files are cached...so try to install a game from Lutris interface, delete it and try to install it again (files setup are cached), button continue is not active.

[Peek 29-12-2020 21-30.zip](https://github.com/lutris/lutris/files/5782836/Peek.29-12-2020.21-30.zip)

I can not reproduce this issue with last stable Lutris version (I have both installed on my system to compare issues).

**Comment by legluondunet** [comment]
The bug is still present after #fab3420 commit. I can reproduce it everytime with Tom Raider 1 - OpenLara GOG for example.

**Comment by legluondunet** [comment]
ooops II just saw I didn't joined the right gif, I just replaced it.

**Comment by strycore** [comment]
The gif I currently see is the one about lutris crashing when retrying a cancelled install.

**Comment by legluondunet** [comment]
done!

**Comment by legluondunet** [comment]
Finally I can not reproduce this bug, should be fixed.

**Comment by strycore** [comment]
That's reassuring, I don't know how you update lutris but you shouldn't do anything beyond `git pull`

**Comment by strycore** [comment]
It's not the first time you've done that. Please make sure that you find a better way to update your code in the future yo avoid this kind of situation. This is extremely disturbing for me and slows down the development of the project.
It must be somewhat confusing for you, I assume.
So, please, for the love of the project, try to find a better workflow.

**Comment by legluondunet** [comment]
Mathieu, I always try as much as possible to disturb you as little as possible. But I am not immune to making mistakes either. As we say here, it is only people who do nothing who are never wrong.

**Comment by strycore** [comment]
I know and it's ok. I just want to make sure that you have a workflow that isn't convoluted. I know some people have some extra steps in their dev setup which aren't needed (the use of a virtualenv, using setup.py, etc)
If you keep your workflow simple and straightforward then there are less chances of making mistakes. If your workflow is already simple and it was just an oversight, then cool, no worry. But that also applies to anyone who happens to read this.

**Comment by legluondunet** [comment]
currently I have three computers on which I am testing the Lutris scripts. I think I forgot to do a "git pull" on one of them, probably tired. Sorry for the inconvenience. My workflow is very simple, I'm not a coder, I don't have this skills, I just do a "git pull".

**Comment by strycore** [comment]
ok, cool, that's good. Just making sure because I've seen many people setup convoluted systems (*especially* non developers) for their dev env for no good reason. Forgetting a git pull when using multiple machines is very frequent and even happens to me!
