### ISSUE TITLE
ARM: lutris should identify arm architecture (in 32 or 64 bits) and not install x86 runners

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3367]
Hello,
I tested Lutris on ARM architecture:
- Raspberry PI 4 with 8 Go ram
- Manjaro Linux 64 bits

I could installed Lutris and launched it with success.
I tried to install a scummVM game, Lutris began to download and install ScummVM runner but for x86 architecture.
It would be pertinent to avoid x86 runners install and if no arm runner is available, to inform user:
"We can not install your game because no runner is available for your computer architecture".

**Comment by strycore** [comment]
That's a bug because we already have error messages that explicitly say "This runner is not available for your architecture"

**Comment by pakro** [comment]
I've searched for the String you mentioned but couldn't find anything. Do you have a small hint where to search for this error message, maybe I can fix this issue.

**Comment by strycore** [comment]
I went looking for it and maybe it got removed in some recent release. But the code that handles the architecture check is in runner.py in get_runner_version

**Comment by pakro** [comment]
Hi @strycore,

i've searched the code and maybe found the problem. In https://github.com/lutris/lutris/blob/master/lutris/util/linux.py#L191 the program tries to detect the architecture. This is also the place where the warning is logged you mentioned. According to https://stackoverflow.com/a/45125525 the call `platform.machine` can result in many architectures that have the string "64" in them. Namely the possibilites are:

- aarch64_be (arm64)
- aarch64 (arm64)
- armv8b (arm64 compat)
- armv8l (arm64 compat)

One of the last two must be used in the Raspi v4 according to https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/. But it maybe also one of the other two above.

@legluondunet can you please open up a terminal on your Raspi who has this issue and enter the command `uname -m`?
This should print a similar string Python is using in the call `platform.machine`. Maybe we just make the platform detection more precise to solve this issue.

**Comment by legluondunet** [comment]
```
[legluondunet@lgdn-pi4 ~]$ uname -m
aarch64
[legluondunet@lgdn-pi4 ~]$ uname -a
Linux lgdn-pi4 5.4.83-1-MANJARO-ARM #1 SMP PREEMPT Mon Dec 14 08:37:33 CST 2020 aarch64 GNU/Linux
```

**Comment by pakro** [comment]
Thanks for the quick response @legluondunet! This should be the problem. Because there is a `"64"` in the string the program assumes a `x86_64` architecture thus falsely allowing the installation of the ScummVM runner.

**Comment by pakro** [comment]
Hi @strycore,
I will try to propose a fix today evening for at least proper x64, i386, i686 detection. Regarding ARM we may need to revisit the architecture handling because currently the only ARM 32-bit seems to be supported. And I don't know if that is going to stay or will be extended in the future.

**Comment by legluondunet** [comment]
if Lutris could detect correctly ARM platform, with 32 or 64 bits, we could then add runners for this platform. Scummvm, AGS Dosbox-staging...works nicely on this platform.

**Comment by strycore** [comment]
@pakro thanks, that should be a simple fix. That check for "64" in the architecture should indeed be a check for "x86_64"

**Comment by strycore** [comment]
do we need different builds for aarch64 and armv8?

**Comment by pakro** [comment]
@strycore you are welcome. I've opened up a pull request for that here: https://github.com/lutris/lutris/pull/3422/

Regarding the question. As far as my research goes, aarch64 and armv8 are both 64 bit natively (every arm 8th generation is 64 bit). arm7 was the last one having only 32bit. So I would say we don't need different builds for both of them (aarch64 and armv8), but we need a separate for arm7. But aarch64 and armv8 can still run 32 bit Software if needed. So we may need something like that (similar to the one for x86 processor already in the code)

`    def runtime_architectures(self):
        """Return the architectures supported on this machine"""
        if self.arch == "aarch64" or self.arch == "armv8":
            return ["armv7, "armv8"]
        return ["amv7"]
`

**Comment by pakro** [comment]
> if Lutris could detect correctly ARM platform, with 32 or 64 bits, we could then add runners for this platform. Scummvm, AGS Dosbox-staging...works nicely on this platform. And I see on forum/reddit more and more users asking for Lutris to support this platform.

@legluondunet  You surely have a point that this would be a good idea to also support newer generations of ARM processors as the different runners also support them by now and this really widens the field of application of Lutris. Maybe you open up another issue so that @strycore can plan this? I believe this is a little bit more work, since the Lutris API needs to be extended for that as the software -- at least as far as I understand it correctly -- is simply not yet able to handle 64 bit ARM.

**Comment by strycore** [comment]
I haven't done a whole lot of testing on ARM but providing native runners should be a good enough start. We can assess the situation when we've made a few runners available are we're able to test them on a few machines.
I'll likely get a RPi400 in the near future as the reference machine for ARM64 development.

**Comment by pakro** [comment]
> I haven't done a whole lot of testing on ARM but providing native runners should be a good enough start. We can assess the situation when we've made a few runners available are we're able to test them on a few machines.
> I'll likely get a RPi400 in the near future as the reference machine for ARM64 development.

I must search my stuff but I have a RasPi too somewhere. I don't remember which one but it is some years old, so probably it is a 32bit only machine. So I might help out on this.

**Comment by legluondunet** [comment]
@Strider I'm sure you ask on tweeter for a Raspberry PI 4 to test Lutris and you will quickly receive one.

**Comment by strycore** [comment]
It's ok, I can order my own with the funds received from Patreon or Paypal, that's what those are for :smile:

**Comment by legluondunet** [comment]
ok.
FYI pr https://github.com/lutris/lutris/pull/3422 does not fixed this issue, but perhaps there complementary changes to add?

**Comment by pakro** [comment]
@legluondunet You still are able to download ScummVM runner for x86 architecture?
Do you see the warning `Unsupported architecture <arch>` when running Lutris with -d option from terminal?

**Comment by legluondunet** [comment]
yes this warning is present in terminal, but that changed nothing to install process: no dialog box to inform user and Lutris installed ScummVM x86 runner
https://paste.ubuntu.com/p/w4Rq7rPJFs/

**Comment by pakro** [comment]
Currently looking at this code snippet https://github.com/lutris/lutris/blob/000aa27b4d447da1a0ea5086e6eb9266adef8000/lutris/runners/runner.py#L356
If I understand it correctly we always return something even if does not match the architecture. Is this correct @strycore ?
