### ISSUE TITLE
Create monitor for processes

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#3372]
There once was a process monitor in lutris that allowed to see which game were running when launched by a additional launcher such as Steam.
The script wrapper that falsely claims to be a process monitor just hangs on process execution and doesn't do anything until the main started process has quit. This is useless for our purposes of tracking processes running. 

A real process monitor needs to be re-implemented. It must not be called from the script wrapper as we lose all control the moment we enter this script. It should periodically check for processes in /proc and be smart enough to find wine processes which are not child processes of lutris-wrapper.

Once the processes are periodically checked, actions can be taken to manage Steam games. (Stop the Steam client if wanted, etc...)

**Comment by AaronOpfer** [comment]
Isn't this what the "excluded processes" concept was meant to achieve? Looks like the launch script waits for at least one non-excluded process to exist, and has a lot of complexity for watching processes on a timer, waiting for there to be no primary processes.

**Comment by strycore** [comment]
We don't want to exclude the game launcher to be unmonitored. We want it to be treated as a normal program and track what it is doing. Excluded processes are for stuff like winedevice.exe and other processes we actually never care about.

**Comment by strycore** [comment]
Lutris now keeps track of newly created process after the game was started. By matching the game path or a generated UUID, Lutris is now able to track Steam and CLI games.
