### ISSUE TITLE
Boolean json runner configurations are ignored

### ISSUE THREAD

**Issue by dackst** [lutris/lutris#3376]
**Describe the bug**

I believe `self.runner_config.get(option["option"])` should be checked before arguments with a boolean configuration are added for json-based runners here:
 
https://github.com/lutris/lutris/blob/19f9d75ccf242cada399452b1a84a73df06a6ea9/lutris/runners/json.py#L42

As it stands, those arguments are always used when lutris launches a json runner, even if configured to be off. 

**Steps to reproduce**

- Add entry that uses json-based runner with boolean option (ags, dgen, ppsspp, virtualjaguar)
- Disable fullscreen in runner options
- Launch entry in fullscreen

**Comment by strycore** [comment]
Thanks for the hint, that was the correct fix.
I've also noticed that some runners don't honor the fullscreen option whether the fullscreen flag is present or absent (dgen and ags). Might require a true / false value list if those runners require a flag like `-w` or `-windowed` to honor the other behavior.
