### ISSUE TITLE
Expose more data field in JSON terminal output

### ISSUE THREAD

**Issue by solbero** [lutris/lutris#3379]
I would like to create a PR to add more data field to the JSON output when running `lutris --list-games --json`. However, I would like to know if such is a PR would be accepted and fits the scope of the project.

The reason why I would like these data field to be output is to to be able to display more game information and more granular categories in [kodi-lutris-addon](https://github.com/RobLoach/lutris-kodi-addon), a Kodi add-on I co-develop with @RobLoach .

As of now the following data fields are output when running `lutris --list-games --json`:
* id
* slug
* name
* runner
* platform
* directory

I would like to expose the following data fields to the JSON output from the Lutris database:
* lastplayed
* year
* playtime
* hidden

The data field `platform` was added to the JSON output in commit https://github.com/lutris/lutris/commit/063232ee1f7a9d0b9e9a9d4a188bb76056dcf4cf by @maxjoehnk. This leads me to believe that adding more data field to the JSON output would be OK.

**Comment by strycore** [comment]
@solbero any effort to make Lutris move away from Gtk and work on other UIs like Kodi is welcome!

**Comment by solbero** [comment]
How would you feel about adding another command flag to dump all the fields from the database? Right now the flags `--list-installed` and `--json` outputs the most most important data fields about the games.

I feel that those two flags should output the same data, only that `--json` formats that that data as JSON. In other words, they should mirror each other. I tried to add more more data fields to the function that generates the JSON, but it did not feel right that adding the `--json` flag suddenly generates a lot more data as compared to just using the `--list-installed` flag. 

A solution could be to add a flag like `--list-games --dump` and `--list-games --json --dump` that would dump all the data fields for all the games in the `pga.db` into the terminal. The flag could be named something other than `--dump` to make it clearer what it does.

**Comment by strycore** [comment]
having a full dump of the sqlite database seems like a nice idea, it would be useful to do imports/exports

**Comment by strycore** [comment]
Patch merged, thanks!
