### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by sucrecacao** [lutris/lutris#3382]
**Describe the bug**
Can't launch lutris binary when trying to install lutris from source. ( https://lutris.net/downloads/ )

**Steps to reproduce**

-git clone https://github.com/lutris/lutris.git
- cd lutris
- `./bin/lutris -d`

**Lutris debugging output (Optional)**
```
Traceback (most recent call last):
  File "./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/media/joe/perso/src/lutris/lutris/gui/application.py", line 26, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by strycore** [comment]
do you have lutris installed to have all dependencies satisfied?

**Comment by sucrecacao** [comment]
No I'm actually trying to install it from source.
I have also run `sudo ./setup.py install` and `sudo apt install libgirepository1.0-dev` but I still have the same output.

**Comment by sucrecacao** [comment]
Fixed after installing wine

**Comment by strycore** [comment]
![how the fuck](https://memegenerator.net/img/instances/24500782/how-the-fuck.jpg)

**Comment by sucrecacao** [comment]
???

**Comment by strycore** [comment]
this doesn't add up.
Wine and PyGObect have no relation with each other.
Please use your package manager to install lutris to have the dependencies installed.
