### ISSUE TITLE
Identifier field in Game info tab does not accept many characters.

### ISSUE THREAD

**Issue by shag00** [lutris/lutris#3395]
Lutris 0.5.8.2

**Describe the bug**

It is not possible to copy or type an address into the the Identifier field appearing in the Game info tab of the Lutris GUI which contain, among other keyboard characters ".",  "/" and "@".

**Steps to reproduce**
Just attempt to copy or type a full URL address into this field.

**Lutris debugging output (Optional)**

This is a keyboard input which is not accepted so lutris -d not run.

**System information (Optional)**

Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-41-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce GTX 1080/PCIe/SSE2

**Screenshots (Optional)**
Not necessary.

**Comment by strycore** [comment]
that's by design, the identifier is url-friendly. it is used by our API to uniquely identify games and does not contain special characters.
