### ISSUE TITLE
"Steam.exe could not be found"

### ISSUE THREAD

**Issue by hzulla** [lutris/lutris#340]
- installed Lutris 0.3.8 on XUbuntu 16.04, using Lutris .deb repository
- clicked "Steam" for Windows install
- Lutris reported no errors during install
- clicked "Launch game"
- "Steam.exe could not be found"

Thanks for Lutris!

**Comment by hzulla** [comment]
Tried again, this time with the "Manage runners" configuration.

Clicked "Install" for "Wine Steam". A minimized window "Wine" window pops up that I cannot resize, another minimized "Wine-Mono-Installation" pops up that I cannot resize either.

From this point on, nothing happens. Both Wine windows stay on the screen. I did not find a log file that told me what is going on or if there is installation progress.

**Comment by strycore** [comment]
there have been some modifications made to the install process, can you test with the current git branch to see if the bug is still present?
