### ISSUE TITLE
Locate previously installed GOG games

### ISSUE THREAD

**Issue by CharoSW** [lutris/lutris#3404]
**Describe the bug**

The games provided by the GOG source don't allow me to locate a previously installed copy of the game.  I am pretty sure the old system allowed you to locate the game manually

**Steps to reproduce**

- Go to GOG source and click on a game
- there is one button: "install" which allows you to download and install the game

**Comment by JeffRockatansky** [comment]
This feature is very much needed. Is there any info on it's development status?

For comparison, Minigalaxy detects all compatible games in the directory and is able to update and launch those. But some are not compatible, so Minigalaxy doesn't detect them.

**Comment by CartoonFan** [comment]
Honestly, I feel like this is one of the biggest losses from old Lutris. It was a very useful way to work around the lack of an installer or sidestep the process if the game was already installed. It's not limited to GOG, either: any game that does not have an installer is affected, at least on my system. So far, in addition to this bug, there's also #1432 and perhaps #2858 as well. Perhaps we should make a meta issue? It's a pretty important feature, IMO.

**Comment by strycore** [comment]
Closed in 0.5.9
Now the DRM free services have a "locate existing game" button
