### ISSUE TITLE
Python Error when Launching App on init_import_size

### ISSUE THREAD

**Issue by kiranshila** [lutris/lutris#3405]
**Describe the bug**

When trying to install something (Like for example the Epic Games Store) or even launching an app, things are failing due to `init_import_size: Failed to import the site module`.

**Steps to reproduce**

- Launch a game, look at console

**Lutris debugging output**

```
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.9/site.py", line 73, in <module>
    import os
  File "/usr/lib/python3.9/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/usr/lib/python3.9/_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
```

**Comment by kiranshila** [comment]
Interestingly, I reinstalled python, and now it works. Unusual.

**Comment by TickingFeather** [comment]
Can I ask you what your distro and Python version are ? I have the exact same issue but reinstalling didn't do much in my case, and it might be useful to solve #3528
