### ISSUE TITLE
"Cancel" where "Confirm" would usually be in the File Picker

### ISSUE THREAD

**Issue by jannuary** [lutris/lutris#3410]
**Describe the bug**

When opening the file picker, say, when one wants to install a game from a file, the header bar has "OK" and "Cancel" on the right side.

Since the GTK file picker in every other app has "Confirm" where on the right side and "Cancel" on far left, it is quite odd to have Lutris not follow the same behavior.

**Steps to reproduce**

1. Open the "Add Game" wizard
2. Pick the Wine runner (or any other that requires an executable file)
3. Press "Browse" when setting the executable file

**Screenshots (Optional)**

![image](https://user-images.githubusercontent.com/27908024/107025572-35528a80-67dc-11eb-8d8b-1b7e86becfe1.png)
File Picker in Firefox: 
![image](https://user-images.githubusercontent.com/27908024/107025759-7185eb00-67dc-11eb-82d8-18fce649784d.png)

**Comment by strycore** [comment]
We are using standard Gtk file pickers, please open a bug against the Gtk project.
