### ISSUE TITLE
Steam game sync PopOS_! 20.10

### ISSUE THREAD

**Issue by Flbk** [lutris/lutris#3412]
I installed Steam flatpak and Lutris (from pop os PPA) cannot sync my installed games. Then I've installed Steam from pop os PPA and the issue remained.

I've noticed that my the steam game installation directory (on flatpak: `~/.local/share/Steam`, on pop installation: `~/.steam/debian-installation`) is not listed in the `STEAM_DATA_DIRS` variable in [lutris/util/steam/config.py](https://github.com/lutris/lutris/blob/master/lutris/util/steam/config.py)

I've added it and it worked.

**Comment by strycore** [comment]
I think that's a duplicate but I'm not sure of which ticket. i'll just close it for good measure

**Comment by strycore** [comment]
oh wait, I'm mistaking this ticket for another one. This one is an easy fix, let me push a  patch
