### ISSUE TITLE
Help interpret log of non-launching game (v 0.5.8.3)

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3415]
Running Lutris 0.5.8.3 on Ubuntu 20.10 on Wayland I try to launch a Wine game ("[Rune Classic](https://lutris.net/games/install/21076/view)" from GOG). It doesn't launch and I'm not sure how to interpret the output in order to identify the problem.

The result of doing Play in the GUI is: no visual results other than Play turning into Stop in the GUI
The results of doing Stop: screen blinks momentarily and the available action is now Play

The log after Stop:
```
Running /home/username/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/wine start /unix /home/username/Games/gog/rune-classic/drive_c/GOG Games/Rune Classic/Launch Rune Classic.lnk
Initial process has started with pid 23800
Start monitoring process.
Initial process has exited (return code: 0)
Caught signal 15
passing along signal to PID 23804
--terminated processes--
Monitored process exited.
All children have exited.
Exit with returncode 0
```

The results of running that command in a terminal:
```
$ /home/username/.local/share/lutris/runners/wine/lutris-6.0-rc1-x86_64/bin/wine start /unix "/home/username/Games/gog/rune-classic/drive_c/GOG Games/Rune Classic/Launch Rune Classic.lnk"
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 6.0-rc1 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0048:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0048:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0050:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0050:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00c0:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
00ec:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00ec:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:err:environ:run_wineboot boot event wait timed out
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00f4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00f4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
0024:fixme:exec:SHELL_execute flags ignored: 0x00004100
```
No window appears and no further progress is made. I'm not sure if any of this indicates a fatal error.

Results of using the system's `wine` in the above command:
```
010c:err:environ:run_wineboot boot event wait timed out
011c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
011c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00004100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:exec:SHELL_execute flags ignored: 0x00000100
Application could not be started, or no application associated with the specified file.
'ShellExecuteEx' failed: Access denied.
```
(Last two lines translated)

What would be a helpful next step?

System info:
```
[System]
OS:              Ubuntu 20.10 groovy
Arch:            x86_64
Kernel:          5.8.0-41-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             3.7 GB
Swap:            1.7 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  3.0 Mesa 20.2.6
OpenGL Core:     4.2 (Core Profile) Mesa 20.2.6
OpenGL ES:       OpenGL ES 3.0 Mesa 20.2.6
Vulkan:          Supported

```

**Comment by strycore** [comment]
I would the newer lutris build instead of the RC1 one and on Xorg instead of Wayland to see if this solves anything. Also check your install location. Make sure it's installed on a writable ext4 drive. 
I've installed Rune Classic from GOG on multiple machines so no issue there. Wine seems to be giving an "'ShellExecuteEx' failed: Access denied." error

**Comment by strycore** [comment]
Also if you want easier debugging, there is a command line option to generate a bash script to run a lutris game:

`lutris --output-script run-rune.sh lutris:rune-classic`

**Comment by anohren** [comment]
Thanks for the suggestions! You were right, Wine does not seem to play nice with Wayland.

- [x] Switched to Wine 6 non RC 
  (mistakenly concluded that I was using the latest since "6.0-rc1" was sorted above "6.0")

- [x] Switched to an X session
  This made it launch in a black window spawning "not responding" dialogs while playing the intro sound effects and repeatedly transitioning from fullscreen to windowed to minimized.

- [x] Enabled "Windowed (virtual desktop)"
  This made the intro actually visible, and got rid of all the "not responding" dialogs.

**Comment by anohren** [comment]
Actually, for anyone else with this problem, it was probably enough to enable "Windowed (virtual desktop)" since it launches in Wayland now too.

The downside is that in Wayland Wine never seems capable of using the correct monitor. It always puts too-large-to-fit windows on the small internal screen instead of the external one :-/ I guess the reason there's no option in Lutris to select monitor preference for Wine window placement is because Wine doesn't support that yet.

**Comment by strycore** [comment]
I think this is more an issue with Mutter or XWayland since Wayland doesn't deal with window management. 
Anyway, Wayland still causes this kind of problem very frequently and I do not recommend it for gaming. Wayland itself seems ok but the software built around it needs to mature a bit in order to become production ready.

This is very annoying since I would like lutris to be able to do some level of window management, with games doing all sorts of wacky things in that area...

**Comment by anohren** [comment]
Interesting, I see. 

I read a discussion about Wayland in the Wine forums that gave me the impression that there was some trouble with placing windows because "Wayland does not support absolute window coordinates", but I don't know enough about it to judge. I'll take your word for it. 

To the next person with this problem I can only agree and recommend to switch to an X session, because suddenly I don't even need to enable windowed mode to launch the game under Wayland, i.e. i ended up not being able to draw a single conclusion about what the roadblock actually was.

**Comment by strycore** [comment]
> Wayland does not support absolute window coordinates

That's the whole issue right here. It's the reason why we have this libgnome-desktop dependency as well because it's the only way to get a list of monitors and resolutions. This is specific to Mutter so when KDE or XFCE get proper Wayland support, each one will have their own, different implementation. 

There is a very aggressive stance from the Wayland project against traditional window management, which is understandable from a given point of view but doesn't really help getting a legacy of 30 years of video games (which are stuck in a given paradigm forever) run on Linux.
