### ISSUE TITLE
script install: can not continue

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3418]
Hello,

the Quake GOG installer script from this page:
https://lutris.net/games/quake-the-offering/

no more works:

![Capture d’écran de 2021-02-11 21-30-05](https://user-images.githubusercontent.com/325405/107695372-c6c86d80-6cb0-11eb-81b0-85917bbb881a.png)

Could you test it and tell me if you meet the same issue: even if you put all needed files, clicking on "continue" does nothing and you can not do more.

https://paste.ubuntu.com/p/ddwF8CDhkZ/

**Comment by strycore** [comment]
I've confirmed this. I previously wrote a fix for a similar problem but it didn't account for "N/A" files
