### ISSUE TITLE
lutris overwriting RADV_DEBUG environment variable

### ISSUE THREAD

**Issue by kackb00n** [lutris/lutris#3419]
I already posted the issue in the support forum [link to forum](https://forums.lutris.net/t/cant-get-radv-debug-environment-variable-get-passed-to-games/11984) - it seems like I cannot pass any RADV_DEBUG environment variable to a game. Especially RADV_DEBUG=llvm, which is needed to get some games running properly with NAVI2 cards.

From a quick look into the code I think it might be this line, where the RADV_DEBUG Environment variable is set. 
https://github.com/lutris/lutris/blob/c37e5f1372b1c7161dbc187f71b69c7575e403c9/lutris/runners/wine.py#L896-L897
If it was already set before it will be overwritten here. A fix might be appending the "zerovram" option if RADV_DEBUG is already set and does not yet contain "zerovram".
(Disclaimer: though I am a dev, I am new to linux, got no experience with neither lutris code nor python, so don't blame me, if this isn't the bug's origin.)

**Comment by kackb00n** [comment]
just tested with editing this line directly in the wine.py with "zerovram,llvm" - llvm runs just fine.

**Comment by kackb00n** [comment]
ok. just wrote a fix. How can I get rights to contribute (create a fix branch & post a pull request)?

**Comment by strycore** [comment]
@kackb00n thanks for writing a patch. You can send a PR, the repo is no longer locked. There is just a CLA to accept to make sure that PRs are aligned with our milestones.
Don't know yet how you solved this but giving higher priority to user defined env vars would solve it (whether the zerovram value is kept is only a matter of how complex it is to keep it)

**Comment by kackb00n** [comment]
> w yet how you solved this but giving higher priority to user defined env vars would solve it (whether the zerovram value is kept is only a matter of how complex it is to keep it)

ok. I opened a merge request for this. Can't I link it to this issue or am I just to dumb to do so?

**Comment by strycore** [comment]
you add `(Closes #3419)` or `(Fixes #3419)` to the commit message, it will auto-close this issue when merged. Otherwise, not a big deal and we can close this manually.

**Comment by strycore** [comment]
I've merged the patch, thanks.

**Comment by kolAflash** [comment]
FTR
The patch: https://github.com/lutris/lutris/commit/db51837097b48ede392e5642fb94b0611fe728b5
