### ISSUE TITLE
allow to set env variables in installers

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#342]
reasons:

many old OpenGL games require to set an older GL_EXTENSIONS sting or they will crash: Quake, DOOM, RTCW just to name a few.

other also may need LD_PRELOADS etc. eg: my old Loki games. http://www.improbability.net/loki/

-------------------
PS:

also it should be possible to disable Lutris LD_PRELOADS in execute commands and launch commands (eg: Blitzkrieg crashes with lutris runtime)

-------------------
PPS:

also to get old libaries it would be nice if lutris would be able to extract deb/ar & txz archives (eg getting them from https://archive.debian.net/ )

eg for txz's: 

    ar p mypackage.deb data.tar.xz | tar xJ

**Comment by strycore** [comment]
Setting env variables is actually an undocumented feature :p (I should really document it…). See https://lutris.net/games/install/1807/view for an example

You can do something similar to disable the runtime:

```
system:
  disable_runtime: true

```

Lastly, I plan to add support for more formats, we should get xz support out of the box now that we have switched to Python 3 but I'd like to go a bit further and ship unzip, unrar, 7z, innoextract and cabextract binaries as part of the runtime (We will be able to simplify all the installers that use our version of unzip)

**Comment by strycore** [comment]
A note on the Loki games LD_PRELOAD, if you have a case were the LD_PRELOAD is required, I'd like to know about it. I think I have all Loki games and I didn't need any of this to run games on Ubuntu 16.04

**Comment by sixsixfive** [comment]
nice 
---------
also you could just integrate p7zip since it is able to extract almost anything: https://sevenzip.osdn.jp/chm/general/formats.htm
---------

games that need very old gcc libs like:
ftp://ftp.bgtelecom.ru/pub/Linux/app/games/Rollemup.tar.gz
