### ISSUE TITLE
cant see custom proton

### ISSUE THREAD

**Issue by Taza53** [lutris/lutris#3425]
In $HOME/.steam/steam/compatibilitytools.d added https://github.com/GloriousEggroll/proton-ge-custom/releases but cant see any in lutris.

How to submit the file from lutris --submit-issue?

**Comment by strycore** [comment]
Oh you don't like our wine builds? You think they are not good enough for you? You want Proton even though Proton is meant to run in Steam and not Lutris? You want to break you game settings? You've had enough of video games? Computing is just not for you? 

Do not worry! I have the solution! You can run lutris with `LUTRIS_ENABLE_PROTON=1 lutris` and the Proton versions will show up letting you cause fire... carnage... destruction... chaos... annihilation... the void... the singularity like you used to in the good old days.
