### ISSUE TITLE
provide a way to install chrome as browser runner

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#343]
why chrome?
- lightweight
- supports flash out-of-the-box
- supports latest html5 features
- has support for almost any video or audio codec
- app mode
- gamepad support

for example do something like this:

```
wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
ar x chrome.deb data.tar.xz
mkdir chrome
tar xfp data.tar.xz -C chrome
su -c "chown root:root chrome/opt/google/chrome/chrome-sandbox"
su -c "chmod 4755 chrome/opt/google/chrome/chrome-sandbox"
chrome/opt/google/chrome/google-chrome --app=http://www.contrejour.ie
```

**Comment by strycore** [comment]
I like the idea, especially the "--app" flag. I don't know how we would handle the chown root thing though, we don't ask the root password for anything in Lutris, is it required?

**Comment by Xodetaetl** [comment]
Does chromium lack any of these features?

**Comment by strycore** [comment]
Chromium lacks Flash and some audio/video codecs

**Comment by sixsixfive** [comment]
>we don't ask the root password for anything in Lutris, is it required?

yes, sandbox needs to be owned by root

also you could use polkit to do that eg:

`pkexec --user root /bin/sh -c "$(type -p chown) root:root $PWD/chrome/opt/google/chrome/chrome-sandbox && $(type -p chmod) 4755 $PWD/chrome/opt/google/chrome/chrome-sandbox"`

you could also use gksu and/or launch a term as fallback( https://sources.debian.net/src/menu/2.1.47/scripts/su-to-root/ )

**Comment by sixsixfive** [comment]
also it would be possible to get the crx url( https://chrome.google.com/webstore/detail/give-me-crx/acpimoebmfjpfnbhjgdgiacjfebmmmci?u)

download>extract and force chrome to run this extension(--load-extension flag eg: https://packages.debian.org/sid/chromium-lwn4chrome)

on this way lutris would be able to use any chrome webstore/nacl game like:

* AirMech: https://chrome.google.com/webstore/detail/airmech/hdahlabpinmfcemhcbcfoijcpoalfgdn
* Arcane Legends: https://chrome.google.com/webstore/detail/arcane-legends/ibmlkgieigeddcedpbijnpojheoddido
* Rad Soldiers: http://www.warchest.com/games/radsoldiers

etc.

**Comment by daniel-j** [comment]
How about using [Electron](http://electron.atom.io/)? You could build a small electron app that launches an url in it. You can integrate it more to the OS etc.

**Comment by daniel-j** [comment]
Video demonstration!
https://youtu.be/rqB-aHF_ArA

**Comment by sixsixfive** [comment]
that would be nice but afaik electron has limited codec support also compared to chrome ist doesnt provide nacl, flash or gamepad support support

**Comment by daniel-j** [comment]
Maybe http://nwjs.io can be used instead of Electron, it seem to have NaCl support atleast. Was a while since I used it though. Electron and NW are very similar projects.
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20NaCl%20in%20NW.js/

**Comment by strycore** [comment]
NW seems nicer indeed. By the way, what are some games using the gamepad API or video codes we could test these with?

**Comment by daniel-j** [comment]
I have now tested NW, ported the launcher to it. NW has a lot of annoying bugs like broken fullscreen support and single-instance only, that I think outweigh NaCl support, which is AFAIK the only thing I can see that it has that Electron doesn't. For now, I will continue work with Electron only. Chrome apps have been discontinued by Google and are now only for Chrome OS. I doubt gamepad support is different between NW and Electron. I don't have any proof of lack of some codecs in Electron compared to Chrome, they could always be compiled in though. It's ffmpeg.

**Comment by daniel-j** [comment]
Web runner #380

**Comment by daniel-j** [comment]
@sixsixfive With the new web runner you can add Chrome/Chromium and make it open web games with `--app="$GAME"` if you don't want to use Electron. This will launch the browser (if it isn't already running) and you get all your extensions too!
![Runner config](http://i.imgbox.com/JsZXLpoq.png)
You could also combine it with `--user-data-dir` if you want it separate from your default Chrome settings.
