### ISSUE TITLE
always display free games

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#344]
free games(even if not in libary) should always be installable/displayed(if view>Installed games only is unticked), of course steam based free games should be still hidden(since they req. a special service).

**Comment by RobLoach** [comment]
Some free games are terrible, and I don't want them in my library.

**Comment by strycore** [comment]
There will soon be a game browser to be able to search games from the website within the client. It will have filter to search free games or open source games just like the website. We can have a similar layout to the game library but the two won't be mixed together.
This should be implemented during the 0.4.x release cycle.

**Comment by strycore** [comment]
Then again, we current layout is the simplest thing to do but it would be nicer to embed some HTML content in the store tab to allow more complex layouts.

**Comment by sixsixfive** [comment]
>Some free games are terrible, and I don't want them in my library.

the could be a blacklist...

**Comment by strycore** [comment]
There will be no blacklist, the games browser will allow to search for every (published) available game and will allow filtering just like the search options on the website.
