### ISSUE TITLE
Download tasks should stop when install is cancelled

### ISSUE THREAD

**Issue by akapps** [lutris/lutris#3443]
If game installation is cancelled by the user while still downloading files, the install window is closed but the downloads continue in the background.
One must explicitly cancel each DL **before** stopping the installation. The only way to stop them afterward is by closing Lutris.

**Comment by strycore** [comment]
Duplicate of other tickets. Not useful.

**Comment by akapps** [comment]
I haven't found an issue that describes this problem. There seems to be others related to the downloader though.

I initially opened this ticket because I think I can try submit a patch for this specific part. Perhaps I should have opened the PR without creating an issue - sorry for that.

Related PR: #3453
