### ISSUE TITLE
lutris slow startup 

### ISSUE THREAD

**Issue by mh-cbon** [lutris/lutris#3444]
hi;

been using lutris smoothly for a while now, but since a few days it is very slow to start.

running lutris with debug shows
```sh
$ lutris -d -v
2021-02-25 14:03:55,964: Your version of python-magic is too old.
2021-02-25 14:03:56,086: Initializing lutris
2021-02-25 14:05:56,685: Downloading DXVK releases to /home/mh-cbon/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-02-25 14:05:56,688: Runtime updated. Initialization complete.
lutris-0.5.8.3
```
It has spent 2 minutes to do whatever it needs with the dxvk thing.

I though for the past two days it was related to that python package, but it seems not.

**Comment by mh-cbon** [comment]
I believe there is a more general problem. It is like if all network operations has become super slow. Getting the popup to install a game, slow, getting a game to download, slow, getting a game to download some resources, slow. each time it is about network operations.
When i am able i try to get the related url, hit it with my browser and it is fast.
I am unsure about how to trace that behavior, any suggestions ?
I guess my next step is to uninstall wine completely then re install it see if that helps...

**Comment by mh-cbon** [comment]
for example, see this log output

```sh
1478 [7] INFO DefaultLog (null) - Starting SendThread
1490 [7] INFO DefaultLog (null) - Sending Message: {"MessageType":"ReinstallData","RegionId":"","Details":{"sessID":"9f3f6d63-6641-49e4-a4b3-652cbe9fef08","ping":"2021-02-26T16:31:09.4815622Z"}}
1491 [7] INFO DefaultLog (null) - Message Length: 143
2151 [5] INFO DefaultLog (null) - LauncherVersion From Doormat:1.0.94.809059
2152 [5] INFO DefaultLog (null) - ClientVersion From Doormat:0.1.3397.845979
2156 [5] INFO DefaultLog (null) - Parsing Launcher version:1.0.94
2157 [5] INFO DefaultLog (null) - Got local launcher version file:1.0.94
2164 [5] INFO DefaultLog (null) - Checking version
2165 [5] INFO DefaultLog (null) - Getting local version file
2167 [5] INFO DefaultLog (null) - Local file didn't exist:C:\Program Files\Wizards of the Coast\MTGA\version
2168 [5] INFO DefaultLog (null) - newest version:0.1.3397.845979
2171 [5] INFO DefaultLog (null) - current version:0.0
2173 [5] INFO DefaultLog (null) - Parsing Launcher version:1.0.94
2175 [5] INFO DefaultLog (null) - Attempt 1 to get the Remote version file from:https://mtgarena.downloads.wizards.com/Live/Windows64/versions/3397.845979/version
61532 [3] INFO DefaultLog (null) - Adding message to queue: clientID:d13b4a90-04b5-4d65-8959-8b56506401ec environmentID:Prod region: logLevel:Info sourceType:Installer messageType:ReinstallData details:{
  "sessID": "9f3f6d63-6641-49e4-a4b3-652cbe9fef08",
  "ping": "2021-02-26T16:32:09.5411695Z"
}
62497 [7] INFO DefaultLog (null) - Sending Message: {"MessageType":"ReinstallData","RegionId":"","Details":{"sessID":"9f3f6d63-6641-49e4-a4b3-652cbe9fef08","ping":"2021-02-26T16:32:09.5411695Z"}}
62498 [7] INFO DefaultLog (null) - Message Length: 143
102280 [5] INFO DefaultLog (null) - Attempt 2 to get the Remote version file from:https://mtgarena.downloads.wizards.com/Live/Windows64/versions/3397.845979/version
121592 [3] INFO DefaultLog (null) - Adding message to queue: clientID:d13b4a90-04b5-4d65-8959-8b56506401ec environmentID:Prod region: logLevel:Info sourceType:Installer messageType:ReinstallData details:{
  "sessID": "9f3f6d63-6641-49e4-a4b3-652cbe9fef08",
  "ping": "2021-02-26T16:33:09.6007768Z"
}
122502 [7] INFO DefaultLog (null) - Sending Message: {"MessageType":"ReinstallData","RegionId":"","Details":{"sessID":"9f3f6d63-6641-49e4-a4b3-652cbe9fef08","ping":"2021-02-26T16:33:09.6007768Z"}}
122503 [7] INFO DefaultLog (null) - Message Length: 143
```

when i hit https://mtgarena.downloads.wizards.com/Live/Windows64/versions/3397.845979/version with my browser, it is almost instant.

**Comment by mh-cbon** [comment]
the log shows the download of a resource per lutris runtime, but in game i also face network problem i should not, though, so far i was not able to log much in that case.

**Comment by mh-cbon** [comment]
I may have found the culprit. In [this](https://forums.lutris.net/t/lutris-is-opening-very-slow/3602/12) thread someone suggests to disable ipv6

Though, running fedora

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

I followed this article https://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/ to temporarily disable ipv6

```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

now it seems to work, lutris is fast to start, the game launch and does not hang dead on some missing resources.

I have tried before to modify all sort of settings (runners, dxvk, single core, buffering kind, esync, you name it) without success.

**Comment by feer9** [comment]
Is this issue closed because it has been fixed? I can confirm I have the exact same issue with lutris-0.5.9.1 on Manjaro Linux

**Comment by mh-cbon** [comment]
I remember i stopped using this hack a few weeks ago because it was fixed by the distro upstream. but i dont have more details. @feer9 you should report your distro if you are havng such problem.

**Comment by feer9** [comment]
@mh-cbon yeah, it seems fixed right now. I didn't have this problem anymore 😁
