### ISSUE TITLE
GOG Neverwinter Nights Diamond Install Issue

### ISSUE THREAD

**Issue by LoneWolfPR** [lutris/lutris#3446]
Trying to install this gets me through selecting the options I want to install (I select all of them) then it starts downloading components. Eventually it hits me with this error: ExtractFailure('Compressed file ended before the end-of-stream marker was reached')

Edit:
This issue relates to the first of two install methods. The "Official Linux Client with game files from GOG's Windows version".

The second install option, which is GOG Windows version, GUI Installer also fails after running through wine. The output in the installer for that is in the attached text file.
[installer-output.txt](https://github.com/lutris/lutris/files/6052360/installer-output.txt)

**Comment by legluondunet** [comment]
Hello, I just tested "GOG Diamond WIN 1.69" Lutris script installer, it installed and launched nicely.
I not tested others script installer versions and I advice you to install only this one to play this game.
Anyway this is not a Lutris issue and Lutris github space are only to report Lutris issue.
Use Lutris forum or DIscord to obtain support for local issues or scripts installer issues.
