### ISSUE TITLE
Add option for `MESA_VK_DEVICE_SELECT`

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#3447]
Available gpu's can be listed with `MESA_VK_DEVICE_SELECT=list vkcube` for example. 
More info:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1766

**Comment by 8andage** [comment]
Mesa seems to require MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE=1 to choose which GPU to use with vulkan.
Arc cards in particular can't be selected with icd if you also have intel integrated graphics

[8andage@laptop ~]$ vkcube
Selected GPU 1: Intel(R) Arc(tm) A750 Graphics (DG2), type: DiscreteGpu
[8andage@laptop ~]$ MESA_VK_DEVICE_SELECT=list vkcube
selectable devices:
  GPU 0: 8086:56a1 "Intel(R) Arc(tm) A750 Graphics (DG2)" discrete GPU
  GPU 1: 8086:9a49 "Intel(R) Xe Graphics (TGL GT2)" integrated GPU
[8andage@laptop ~]$ MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE=1 vkcube
Selected GPU 0: Intel(R) Xe Graphics (TGL GT2), type: IntegratedGpu
[8andage@laptop ~]$

**Comment by strycore** [comment]
Wouldn't that overlap with the Vulkan ICD feature we already have?

@GloriousEggroll would adding this feature in Lutris make sense?
