### ISSUE TITLE
Feature Request: Ability to Organise Games via Tags

### ISSUE THREAD

**Issue by jtrees** [lutris/lutris#345]
It would be great if there was a way to organise games into some kind of structure via tags (or something equivalent) as it can otherwise be difficult to keep track of certain games. This feature would allow users to structure their library by genre/platform/release year/what they are currently playing/etc.

Steam offers this functionality via Categories (which essentially work like tags because a game can be in more than one category at once), GOG Galaxy also has tag support.

**Comment by strycore** [comment]
This is a good idea, I think we'll go with Categories like Steam.

**Comment by parkerlreed** [comment]
Was this ever added? I don't see the option when using latest git.

**Comment by AccountOneOff** [comment]
It's in its own branch. https://github.com/lutris/lutris/tree/categories

You have to restart Lutris when adding new categories. It doesn't auto update currently.

**Comment by parkerlreed** [comment]
Thanks! 
![image](https://user-images.githubusercontent.com/841440/58344262-39315400-7e23-11e9-97d0-87e67516aab4.png)

I don't get the Category header but the category works
