### ISSUE TITLE
Can't install some games

### ISSUE THREAD

**Issue by JStrm** [lutris/lutris#3456]
When I try to install a game, in this case CS:GO, by double-clicking or clickin the "Install" button, nothing happens. The console outputs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/game_bar.py", line 22
    self.service.install(self.db_game)
  File "/usr/lib/python3.9/site-packages/lutris/services/steam.py", line 143, in 
    appid = db_game["appid"]
KeyError: 'appid'
```
I've read that this was fixed in issue #3252, but I've still got the error. 
I am using version 0.5.8.3, running Archlinux. I've tried this with both the lutris and lutris-git version.

**Comment by legluondunet** [comment]
Hello,
do you still have this issue?
If so in which case you can reproduce it:
- when you click on install from Lutris game web page?
- when you click on game banner from Library/Games ?
- when you click on game banner from Library/Lutris ?

**Comment by JStrm** [comment]
Yes, I still have the issue.

- When clicking the install button from lutris.net, the error is not reproduced.
- When clicking the banner from Library/Games, the error is reproduced.
- When clicking the banner from Sources/Lutris, the error is not reproduced.

**Comment by Cattodeveloper909** [comment]
Hello! Am on Manjaro and for me everything works nice, I think the error that you are having is a python outdated version error, becuase python updated to 3.9.2, as I said in issue #3504, and have you tried of installing the game through steam and then syncronize it with lutris?  am not sure but I would be glad that helped

**Comment by JStrm** [comment]
Hey,
I have python 3.9.3 installed on my system.
When I install the game through Steam and then synchronize it, it works, although I can't synchronize it in the "Games" tab. I have to use the "Lutris" tab.
Thanks for your contribution!

**Comment by strycore** [comment]
fixed
