### ISSUE TITLE
Magic The Gathering Arena doesn't want start

### ISSUE THREAD

**Issue by lediable** [lutris/lutris#3457]
Hello,

Today I had some problem with magic arena, doesn't want start. Before today it has worked without any problem.

How can I solve this? I am using the lutris mtga 5.0

Here the log
[mtga log](https://github.com/lutris/lutris/files/6092396/mtga.log)

**Comment by legluondunet** [comment]
Hello,
I can not reproduce your issue and this github account is only to report Lutris issues, this is not one.
You will find support for Lutris script installer on our forum or Discord.
