### ISSUE TITLE
bash scripts

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#346]
Didn't know if I should post it here or as an appendage to the FS-UAE problem I described. I'm using PoL to configure most of my windows games, and it works great, no problems so far.  

I have steam for windows living inside a PoL-prefix, and found a nice bash script that will launch PoL-steam and then run a game from your collection (I only use it for games that need steam to run, like Dark Zero Void, FF8 & Burnout Paradise since their DRM is tied to steam). 

If I run the bash script from the terminal, everything runs fine, steam gets launched and once it's up and running the script triggers steam to launch the game I'm launching. If I add the bash script in lutris, steam will start, but the game never launches.

On the terminal I don't get any warnings from the script, but in lutris it complains: "grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc"

this is burnout's script: http://pastebin.com/JTXSNx3F

**Comment by strycore** [comment]
Can you try with the Lutris runtime disabled to see if it makes any difference?

You can also try changing your script to:

`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$WINEVERSION/lib:$WINEVERSION/lib64"
`
This might have a different effect

**Comment by telanus** [comment]
> Can you try with the Lutris runtime disabled to see if it makes any difference?

seems this helps running the scripts :+1: :smiley_cat:
