### ISSUE TITLE
Add private steam API key to fetch private data

### ISSUE THREAD

**Issue by RobinFrcd** [lutris/lutris#3461]
Everybody is able to get an API key from https://steamcommunity.com/dev/apikey

**Comment by strycore** [comment]
steam api key can now be set in the settings file

**Comment by strycore** [comment]
Not at the moment. 

To set a custom API key, open ~/.config/lutris/lutris.conf (or ~/.local/share/lutris/lutris.conf for people from the future) and add (no quotes needed for the API key):

`steam_api_key = xxxxxxxx` 

to the `[lutris]` section
