### ISSUE TITLE
Modal dialog in main window blocks auxiliary window interaction

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3466]
A modal dialog, e.g. "about Lutris" in the main window inexplicably blocks all interaction in e.g. the download window. Given that the latter can — and usually will —  be on top of and visually block the former, I'm left with no clue as to why I can't interact with the application, and will conclude that its frozen. 

In Windows I seem to recall they "solve" this by flashing the titlebar, to at least indicate the app is alive while still leaving you clueless. MacOS solves it by making the dialogs part of the parent window, and be done with it — the problem doesn't exits there. 

I don't know what gnomes solution is, and I can't guess what they're thinking considering they seem to treat modal dialogs both as independent windows (by giving them a separate titlebar, etc) as well as part of the parent window (by blocking interaction and locking their positions to the parent). 

Anyway, the proper solution from my perspective is to not block interaction in the windows that don't own the modal dialog.

**Comment by briaguya-ai** [comment]
this is standard gnome behavior, even [gedit](https://en.wikipedia.org/wiki/Gedit) has this problem (try opening "Tools->Document Statistics" in a text editor window and then clicking "About Text Editor"

i agree that it's odd behavior, but it seems as though it'll be best addressed [upstream](https://wiki.gnome.org/Community/GettingInTouch/BugReportingGuidelines)

**Comment by anohren** [comment]
Sounds reasonable, if it's something clients have no control over

**Comment by danieljohnson2** [comment]
Clients do have control over this.

'gedit' does exhibit the problem, but it is perhaps more excusable with a little 'moveable modal' dialog- which is like an extension of the main window. I'm still not a fan since the document-stats dialog *looks* exactly like a normal window, and is not dimmed by the modal dialog- it's just frozen.

But this can be avoided by putting separate windows in their own window groups.

**Comment by anohren** [comment]
@danieljohnson2 Nice, I hope you'll get it merged
