### ISSUE TITLE
Manually entering DXVK v1.8 or v1.8.1 doesn't actually load DXVK

### ISSUE THREAD

**Issue by BloodyIron** [lutris/lutris#3469]
For Overwatch, I wanted to try DXVK v1.8 and v1.8.1. However, when I go to manual, or type in  "v1.8.0" or "v1.8.1" in the version for DXVK, when the game launches, I'm pretty sure it loads WineD3D instead, as I don't get DXVK_HUD and my FPS is 40-50FPS in training room, when I normally get 110-120FPS.

Pretty sure this isn't pulling from the Github repo for DXVK for releases, or something like that.

**Comment by briaguya-ai** [comment]
sounds like the problem here is allowing saving a string to the DXVK field that doesn't correspond to an option in the dropdown.

pretty sure you should just be selecting "manual" for your use case but i don't know enough about it to help more.

suggested tags:
user experience
bug
runner options

**Comment by legluondunet** [comment]
DXVK 1.8 is available in Lutris and is now default DXVK version used.
If it doesn't show in Lutris, remove this folder:
~/.local/share/lutris/runtime/dxvk
and relaunch Lutris.

**Comment by BloodyIron** [comment]
@legluondunet that doesn't actually address the issue. The issue is that the manual version method doesn't work.

**Comment by legluondunet** [comment]
It works, where did you extract dxvk 1.8 archive?
Please  open a terminal in dxvk folder, execute this command:
find - r *
And copy paste result here.

Le dim. 18 avr. 2021 à 15:54, BloodyIron ***@***.***> a
écrit :

**Comment by BloodyIron** [comment]
You missed the part earlier where I said "Pretty sure this isn't pulling from the Github repo". As in, earlier versions of Lutris stated that it was pulling from the DXVK github repo for releases, and that's what I expect, whether it's manually entering the version, or selecting from the list. That's the whole original issue. Lutris didn't show the newer version of DXVK as an option, when I tried to manually enter it, it didn't pull it from the DXVK github repo, which is important to have.

**Comment by legluondunet** [comment]
You are right, Lutris uses his own DXVK build.

**Comment by BloodyIron** [comment]
Ahh that's a bummer, any particular reason Lutris doesn't pull from the DXVK github repo or something like that? (or have the option to do so?) I could swear it did that before, maybe that changed, or maybe I'm mistaken, not sure.
