### ISSUE TITLE
always provide an option to use the systems runner if installed

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#347]
since most of the runners are available on my distribution so I would like to use them instead of the generic compiled mostly incompatible lutris runners.

**Comment by telanus** [comment]
@strycore said here he'll introduce this in a later release: https://forums.lutris.net/t/runners/36

**Comment by strycore** [comment]
Yes, it's planned very soon. Btw, what runners are incompatible with your system and what distro are you using?

**Comment by sixsixfive** [comment]
>Yes, it's planned very soon. 

thats nice

>Btw, what runners are incompatible with your system and what distro are you using?

the GPU plugin from PCSXR is incompatible with my system

![a](https://cloud.githubusercontent.com/assets/3780774/18605411/2a356b34-7c92-11e6-8d3c-bd182e3d4ea5.png)

Devuan testing/unstable amd64

```ssf@schleppi:~$ LANG=en aptitude show libxv1
Package: libxv1                          
Version: 2:1.0.10-1+b1
State: installed
Automatically installed: yes
Multi-Arch: same
Priority: optional
Section: libs
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Architecture: amd64
Uncompressed Size: 37.9 k
Depends: libc6 (>= 2.14), libx11-6 (>= 2:1.6.0), libxext6
PreDepends: multiarch-support
Breaks: libxv1:i386 (!= 2:1.0.10-1+b1)
Replaces: libxv1:i386 (< 2:1.0.10-1+b1)
Description: X11 Video extension library
 libXv provides an X Window System client interface to the XVideo extension to the X protocol. 
 
 The XVideo extension allows for accelerated drawing of videos.  Hardware adaptors are exposed to
 clients, which may draw in a number of colourspaces, including YUV. 
 
 More information about X.Org can be found at: <URL:http://www.X.org> 
 
 This module can be found at git://anongit.freedesktop.org/git/xorg/lib/libXv
Tags: role::shared-lib
```

also it might be better if runners were portable apps: http://appimage.org since they would include all needed libaries

**Comment by strycore** [comment]
>the GPU plugin from PCSXR is incompatible with my system
No, don't worry, there's nothing wrong with your system, PCSX is broken everywhere, it's the worst runner we currently ship. One of the priority goals of Lutris 0.4.0 is to get rid of it and replace it with a libretro core.

> also it might be better if runners were portable apps: http://appimage.org since they would include all needed libaries

That's what the runtime is for, we build everything on Ubuntu 14.04 and ship all the required libs bundled together. We used to have one runner using an AppImage (gens-gs) but it was still a mess and it was hard to package in an automated manner so I replaced it with dgen which was packaged in a more traditionnal way (but dgen itself isn't very good and is going to get replaced by a libretro core too)

**Comment by sixsixfive** [comment]
not sure about libretro since i never really liked it for ps1 and more adv. consoles(no nice shader support(the old ogl2 plugin for pcsx is still unmatched), button configuration is also a pain but we'll see

>we build everything on Ubuntu 14.04 and ship all the required libs bundled together. 

since ubuntu patches many of its libaries, its probably not the best choice for a multidistro app but i guess its OK until they switch to mir and more weird custom stuff

also did you try statifier? http://statifier.sourceforge.net

**Comment by strycore** [comment]
this is a tradeoff we have to do, PCSX is unusable and unmaintainable (the codebase is in desperate need of being ported to SDL2) but the libretro cores don't offer high-res graphics. Given the choice, I'd rather have lower res graphics and a working emulator… Of course, this is only temporary, what I'm really waiting for is the new Mednafen core which will provide stability and good graphics: http://www.libretro.com/index.php/mednafenbeetle-psx-hw-alpha-version/

> since ubuntu patches many of its libaries, its probably not the best choice for a multidistro app but i guess its OK until they switch to mir and more weird custom stuff

We used to be based on Debian 8 but at some point, the dependencies were just too old. Ubuntu 14.04 is starting to get old too, we can't build Dolphin with it. 

statifier looks interesting, I'll have a look :)

**Comment by strycore** [comment]
I forgot to close this but this has been implemented a few releases back.
