### ISSUE TITLE
Show what you play on Discord 

### ISSUE THREAD

**Issue by vesterlay** [lutris/lutris#3471]
I wonder if it's possible to integrate Lutris with discord. As this guy did https://github.com/MrPotatoBobx/FetchCord but instead of OS, Lutris would pass currently playing game.

**Comment by RobinFrcd** [comment]
Lutris already handles RPC pretty well, see: https://github.com/lutris/lutris/blob/master/lutris/discord.py

However, I only see an `extras_require` in [setup.py](https://github.com/lutris/lutris/blob/master/setup.py) and nothing about `pypresence` in the [Pipfile](https://github.com/lutris/lutris/blob/master/Pipfile). 

Any reason why `pypresence` is not a mandatory dependency here ?

**Comment by vesterlay** [comment]
> @vesterlay You can install `python-pypresence` and everything should work fine.

After installation nothing has changed. 

Is that an expected behavior? 
SouthPark FBW
![image](https://user-images.githubusercontent.com/39202451/111029071-f4f9b400-83fa-11eb-990f-aad5c8540a89.png)

Lutris in the background 
![image](https://user-images.githubusercontent.com/39202451/111029088-0478fd00-83fb-11eb-9139-5d054a475b67.png)

CS:GO Native 
![image](https://user-images.githubusercontent.com/39202451/111029137-41dd8a80-83fb-11eb-81dc-ab87f6bfa9a1.png)

**Comment by RobinFrcd** [comment]
Have you enabled Discord RPC in Lutris -> System Option ?
![image](https://user-images.githubusercontent.com/29704178/111034094-57ab7980-8414-11eb-9a50-5561df8177b1.png)

**Comment by vesterlay** [comment]
It works! But now there is no game icon, I guess it hasn't been implemented yet. 
![image](https://user-images.githubusercontent.com/39202451/111038601-2f2e7a00-842a-11eb-941d-4ec5a1e45bd0.png)

I wonder why it's not enabled by default. Furthermore why is there a separate setting for such thing? Kinda kills simplicity

**Comment by RobinFrcd** [comment]
If we want to have an image, we'll need a specific ID for every game and set the image on https://discord.com/developers/applications kind of tedious task.

And yes, that was my question above, I don't know why it's not the default.

**Comment by Raspberry-Pi0** [comment]
@vesterlay From what I've heard, in the pictures you sent, it's not a Lutris problem, it's a Discord problem. I *believe* Discord doesn't know how to filter out most Linux applications like it does on Windows.
