### ISSUE TITLE
Lutris hangs on start

### ISSUE THREAD

**Issue by Sycration** [lutris/lutris#3475]
Computer: 
```OS: Pop!_OS 20.10 x86_64 
Host: MS-7B17 1.0 
Kernel: 5.8.0-7642-generic 
Uptime: 1 day, 2 hours, 15 mins 
Packages: 3136 (dpkg), 16 (flatpak), 14 (snap)
Shell: zsh 5.8 
Resolution: 2560x1440 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce RTX 2080 Rev. A 
Memory: 8059MiB / 15947MiB
```  

When I run lutris with `lutris` (from the ppa) I get the attached output
[log.txt](https://github.com/lutris/lutris/files/6160760/log.txt)

It then simply stops, with the [lutris is starting] window open

**Comment by briaguya-ai** [comment]
notable from the log
`2021-03-17 18:45:16,266: Download failed: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)` 

does the version from the pop shop work for you?
