### ISSUE TITLE
Remove option deleted my Download folder.

### ISSUE THREAD

**Issue by NickVolt77** [lutris/lutris#3476]
I've tried to run Opera GX on Linux. There was OperaGXsetup.exe in my Download folder on Linux. I've added this exe to Lutris, I've set run folder and game folder to /home/user/programs/opera. Installation of Opera failed, so I wanted to remove Opera GX from games list. I used "remove" from context menu. Lutris should remove /home/user/programs/opera, instead ask to remove Download folder and just remove this folder. /home/user/programs/opera still exists.
BTW: Opera GX is still visible in a list.

**Comment by briaguya-ai** [comment]
sounds like you've gotten yourself into a "lutris has a game without a game" spot after being in a ""lutris thought the installer was the game"

the first thing to try is just removing but unchecking the "Delete ~/path/to/your.exe" box, that should get it off your list

if that fails for some reason, a workaround for is to make a copy of any random exe you have sitting around, set the executable in the "Game options" tab to the newly copied exe, and then allow lutris remove to delete that copied exe on uninstall.

suggested tags:
user experience
removing games
unexpected states

**Comment by strycore** [comment]
no longer possible with current code
