### ISSUE TITLE
Add a switch between new and old GUI.

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#3479]
I would really appreciate if the switching option was added between the old (0.5.7.1) and the new (0.5.8🠕) GUI because I liked it more (and I'm not alone).

**Comment by briaguya-ai** [comment]
5.7 to 5.8 [was big](https://github.com/lutris/lutris/compare/v0.5.7.1...0.5.8-beta).

it would be difficult to switch over, however, if you could elaborate upon which specific user experience patterns you miss from the old version, this could become an actionable issue.

suggested tags:
improvement
undefined

**Comment by kajlando** [comment]
I miss the sidebar the most.
![lutris 7 vs 8](https://user-images.githubusercontent.com/76191122/111929066-a9f43680-8ab5-11eb-8420-a5c17e19dd21.png)
Also I deleted some apps in 0.5.8 but they showed back in 0.5.7. So I guess 0.5.8 doesn't delete apps, only hides them hide but that's a different issue.

**Comment by kajlando** [comment]
![Lutris 7 vs 8](https://user-images.githubusercontent.com/76191122/111930442-43711780-8ab9-11eb-8c90-a74eaa75f72f.png)
I miss the sidebar the most.
Also I deleted some apps in 0.5.8 but they showed back in 0.5.7. So I guess 0.5.8 doesn't delete apps, only hides them but that's a different issue.

**Comment by kajlando** [comment]
![Lutris 7 vs 8](https://user-images.githubusercontent.com/76191122/111930442-43711780-8ab9-11eb-8c90-a74eaa75f72f.png)
I miss the sidebar the most.
Also I deleted some apps in 0.5.8 but they showed back in 0.5.7. So I guess 0.5.8 doesn't delete apps, only hides them but that's a different issue.

**Comment by fmlatghor** [comment]
While you're add it can we get the import feature back that was useful....
