### ISSUE TITLE
Lutris segfaults when started

### ISSUE THREAD

**Issue by edgarogh** [lutris/lutris#3481]
When I start Lutris, it doesn't do anything or even log anything, I just get notified of a SIGSEGV by my shell.

I don't really know if the bug is easily reproducible and what conditions I can emulate to try to get it working and narrow down the cause of this problem. Running lutris as superuser doesn't help. Lutris worked at some point in time on this exact machine and OS installation (around April to June 2020), and I used it regularly. I just noticed that it wouldn't work. That said, it could be completely unrelated to Lutris' updates, maybe it's just some kind of conflict with something I installed/updated in the meantime.

Here's a `gdb` backtrace, the only tool I know how to use to search the cause of a segfault: https://gist.github.com/edgarogh/daafea83864da7f50a9357ed2263426e
The crash occurs inside the `libmagic` native shared lib, from the `magic` python module, but the invalid state could obviously result from something else.

**Installation:**
  * OS: Linux Mint 19.3 Cinnamon, Linux 5.4.0-67-generic
  * Lutris installed with `apt`: `lutris/bionic,bionic,now 0.5.8.3~ubuntu18.04.1 all` (up to date at the time of writing)

Feel free to ask for more information. :otter:

**Comment by strycore** [comment]
fixed
