### ISSUE TITLE
Availability in the Snap Store

### ISSUE THREAD

**Issue by Hans03430** [lutris/lutris#3482]
Hello, i was wondering if Lutris would ever be released as a Snap? That way, it would be easier to install Lutris through the Ubuntu Store instead of using the PPA.

If Lutris is ever released as a Snap, the LZO compression can be used in the snapcraft.yaml file to allow a faster startup speed.

**Comment by CapeCrusader321** [comment]
@Hans03430  I have started building and maintaining a snap, can you help me with testing it in this repo -->  https://github.com/CapeCrusader321/Lutris-snap 

Download the snap ;

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/lutris)

**Comment by Hans03430** [comment]
Hello! I installed Lutris from the snap store and i got the following error when trying to launch it with the command line. When clicking on its launcher/icon, nothing happened :(

![image](https://github.com/lutris/lutris/assets/56232381/64a069f4-926e-4757-b2bf-264954688560)

**Comment by Hans03430** [comment]
I can now access the lutris snap but it has the default gear in a box icon instead of the lutris one :(

**Comment by CapeCrusader321** [comment]
@Hans03430  Please report lutris reported issues at -->   https://github.com/CapeCrusader321/Lutris-snap

**Comment by strycore** [comment]
Development of the Lutris snap is now tracked in #4861
