### ISSUE TITLE
Remove hidden software from library

### ISSUE THREAD

**Issue by mm47** [lutris/lutris#3484]
I've installed some softwares with lutris, then I removed/deleted them, but they remained in my library. The only option left was to hide them, but they remain there and I would like to know if there's a way to completely remove them. Same thing happens when the launchers get updates and get broken, I have to reinstall them, but can't completely remove them from my library, so they become duplicated. I have already deleted the files folder, but they don't disappear. Is there any commands I can run to obliterate those entries? 

I'm running Linux Mint 19.3
Lutris 0.5.8.3
Kernel 5.4.0-70-generic

![Captura de tela_2021-03-29_00-55-17](https://user-images.githubusercontent.com/28028426/112785163-be8e7c80-9029-11eb-9da3-ebde308f2b3e.png)

**Comment by dino8890** [comment]
You can install SQLite Browser, open .`$HOME/.local/share/lutris/pga.db,` and delete unnecessary entries from `games` table.

There used to be an option to remove the games before the GUI update, it would be useful if we could get it back.

**Comment by mm47** [comment]
This worked perfectly! Thank you very much!

**Comment by legluondunet** [comment]
This bug is already resolved in latest Lutris git version.
