### ISSUE TITLE
lib32-gnutls needs to be included in the installer

### ISSUE THREAD

**Issue by Wasabi-Cheetah** [lutris/lutris#3488]
I had to install lib32-gnutls separately to get Ubisoft Connect to work, same with Origin and GOG.
If it is, it might be the case that it wasn't included since I'm on an x64 version of Manjaro and that package is only included for x32 platforms, but that's an issue i solved alone.

**Comment by kleinermob** [comment]
https://github.com/lutris/lutris/issues/3597

**Comment by Wasabi-Cheetah** [comment]
oh, I just noticed this, sweet, thank you

**Comment by strycore** [comment]
I believe 32bit gnutls is a dependency of Wine, which we encourage to install alongside Lutris.

We also check for gnutls at startup ( `lutris/util/linux.py:81` ) so anyone without both 64 and 32 bit versions of that library will get a warning on startup.

If the default installation of Lutris doesn't work on your distro, please get in touch with the maintainer of Lutris for that particular distro.
