### ISSUE TITLE
add some dependency tests for execute commands

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#349]
there could be an extra line inside the installer file eg:

depends: curl, wget, 7z, xz

so before the installation is starting lutris could do something like:

```
type 7z >/dev/null 2>&1 || { echo >&2 "I require 7z, but it's not installed. aborting!";}
```

**Comment by RobLoach** [comment]
7z issue is at https://github.com/lutris/lutris/issues/323 .

**Comment by sixsixfive** [comment]
7z is just an example... you could replace it with java or mono

the current way is just frustrating eg: you download 8gb of data and extraction will fail...
