### ISSUE TITLE
[Feature request] GOG games updater

### ISSUE THREAD

**Issue by JeffRockatansky** [lutris/lutris#3490]
GOG games installed from Lutris can't be updated unless via reinstallation. That's not very convenient, nor it is metered connection friendly (it's not). And this user scenario conflicts with uninstallation procedure.

Also, it's not entirely clear what "Remove" context menu option does with a game, but that's a different issue.

**Comment by junglized** [comment]
Yes, that's what I experience too. Are there any plans to add GOG games updater?

**Comment by JeffRockatansky** [comment]
Let's discuss internet traffic usage.

AFAIK, each time you try to update a GOG game with Lutris, it downloads the whole installation package instead of just downloading only an update and putting it besides pre-cached installer executable and previous updates. The latter procedure could be a viable temporary solution. It will require twice the space, but it could be made optional.

**Comment by V10lator** [comment]
> GOG games installed from Lutris can't be updated unless via reinstallation.

What stops you from downloading the update only from https://www.gog.com/account and applying it manually (for example with the Lutris function "Run EXE inside Wine prefix") ?

**Comment by JeffRockatansky** [comment]
> What stops you from

Hackiness of the process? It's too much additional manual work for a tool that should help automate the process.

**Comment by sluedecke** [comment]
Minigalaxy does that here: https://github.com/sharkwouter/minigalaxy/blob/1141313ae196e25badbad8edbe6a09c5b1f5c4c7/minigalaxy/game.py#L63

**Comment by V02460** [comment]
For those wondering, it’s https://github.com/lutris/lutris/commit/7453cdb5dd72ce4d9d25bff58b7745605822cb03.
