### ISSUE TITLE
Myst V End of Ages Limited Edition : Installing with Lutris from Gog.com stalls with repeating message

### ISSUE THREAD

**Issue by maxUPnorth** [lutris/lutris#3491]
The downloads are complete, and installation starts; some of the actions at the bottom of windows are blacked out, and the log shows
![lutris installing myst V](https://user-images.githubusercontent.com/81757832/113298361-a782af80-92f3-11eb-8f12-a5bd7fa6d9c7.png)
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable 0: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable -1: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable 0: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable -1: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable 0: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable -1: stub!
00ec:fixme:win:WINNLSEnableIME hwnd 00010132 enable 0: stub!

**Comment by maxUPnorth** [comment]
Computer is Intel NUC Hades Canyon running Xubuntu 20.04. Detailed information is below.

System:
  Host: snuc-NUC Kernel: 5.4.0-70-generic x86_64 bits: 64 
  Desktop: Xfce 4.14.2 Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Machine:
  Type: Mini-pc System: Intel Client Systems product: NUC8i7HNK 
  v: J71486-603 serial: <superuser/root required> 
  Mobo: Intel model: NUC8i7HNB v: J68197-602 
  serial: <superuser/root required> UEFI: Intel 
  v: HNKBLi70.86A.0059.2019.1112.1124 date: 11/12/2019 
CPU:
  Quad Core: Intel Core i7-8705G type: MT MCP speed: 900 MHz 
  min/max: 800/4100 MHz 
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
  Device-2: AMD Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu 
  v: kernel 
  Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati,modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: AMD VEGAM (DRM 3.35.0 5.4.0-70-generic LLVM 11.0.0) 
  v: 4.6 Mesa 20.2.6 
Network:
  Device-1: Intel Ethernet I219-LM driver: e1000e 
  Device-2: Intel I210 Gigabit Network driver: igb 
  Device-3: Intel Wireless 8265 / 8275 driver: iwlwifi 
Drives:
  Local Storage: total: 4.68 TiB used: 3.46 TiB (74.0%) 
Info:
  Processes: 322 Uptime: 7h 52m Memory: 7.69 GiB used: 1.87 GiB (24.3%) 
  Shell: fish inxi: 3.0.38

**Comment by strycore** [comment]
fixed
