### ISSUE TITLE
Trojan virus 

### ISSUE THREAD

**Issue by landlord96** [lutris/lutris#3499]
Somehow the "iexplore.exe" trojan virus got into my wine through Lutris.
affected folder: /lutris/runners/wine/lutris-6.0-x86_64/lib/wine/iexplore.exe
It seems like this issue was being caused by running Diablo III in Lutris.

**Comment by ericschdt** [comment]
Are you sure it's not a false positive? How do you know it's a Trojan? https://github.com/lutris/lutris/blob/63570f6918fa134295aaea8f5cd4de014988e814/lutris/util/wine/wine.py#L129

**Comment by landlord96** [comment]
I found 3 of them with the ESET NOD32 for Linux just yesterday.
It's clearly a trojan meant for Windows systems, though it's unfortunate that wine caught it with it's mostly safe operations.
Is it possible that it's not a virus just recognized as one?
Then why it has the fake internet explorer exe name?

**Comment by nutta-git** [comment]
https://github.com/ValveSoftware/Proton/issues/4738#issuecomment-814271235

**Comment by legluondunet** [comment]
I close this report cause It's not  a Lutris issue.
