### ISSUE TITLE
steam games

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#350]
I found this bug, when you start a steam game (linux steam), it'll add a clone for that game in the launcher, and it'll stay there till you close lutris and restart it
![screenshot at 2016-09-14 17-39-30](https://cloud.githubusercontent.com/assets/19357986/18525626/94822d50-7abd-11e6-9fdc-c653209acb4b.png)

**Comment by strycore** [comment]
Yes, I did some silly thing with the Steam monitor, if a game is updating, it will create a bunch of duplicate entries which will disappear when the client is restarted.
