### ISSUE TITLE
question / not necessarily a bug: winetricks - wrong wineprefix selected

### ISSUE THREAD

**Issue by dreamcat4** [lutris/lutris#3501]
Hello,
I hope this report can be helpful for anybody else encountering the same exact issue. AFAIKT it's not an issue in Lutris per-se. But it occurs when using Lutris. So this is why I have posted here. To make it better known amongst the lutris users.

Steps to reproduce the issue:

* `export` a custom wineprefix env var in your `~/.profile` for example: `export WINEPREFIX=foo`
* Open Lutris
* Open Game settings, with a wine runner selected (that is not the system wine)
* Set the per-game wineprefix to something else

This is the config part done. Next to navigate to where the bug exists:

* Select game
* Click on the 'wine menu' at the bottom of lutris main page. The icon of a wine glass
* Select 'Winetricks' from the win menu (runs winetricks for this game)
* A popup dialog menu appears
* Select the middle option (already selected as a default choice): 'Select the default wineprefix'
* This then gets to the 2nd list of options
* Top Menubar says: Winetricks - current prefix is "/custom/per/game/wineprefix/for/my/game"

Now to trigger the bug:

* From 2nd winetrick GUI menu screen, select option: `Run a commandline shell (for debugging)
* This then launches a terminal, and the CWD is changed to that of your custom wineprefix

BUG:

However the environment variable inside of the shell still says the env var `WINEPREFIX=` whatever you set in your `~/.profile`

ASSESSMENT:

I think this happens because winetricks sets the wineprefix correctly first, but then launching terminal it logs the user on again. At which point the `~/.profile` script is re-launched. And wineprefix env var is set again.

QUESTION:

So how best to solve this issue do you guys think? I see 2 different ways:

* Just remove entirely the line `WINEPREFIX=` from my user login script
  * This means that the default wineprefix location is used. which i can mask with a symlink to some other place if needed (since my disk space is too small etc.)

or

* Check in my `~/.profile` if the variable `WINEPREFIX` is already been set before
  * and if already set, then don't overwrite the env var

It seems best ways i can think of IMHO. But is the 2nd way a bad idea perhaps? Or am i overthinking things? Very much good day. I shall be back later after trying these methods. To confirm which ways works.

BTW It's kindda a shame we have to always click through these menus so much. So if you know of a faster way to access this shell / environment from lutris (not the `cmd.exe` version of a shell, but linux shell). Then please let me know! Many thanks

**Comment by dreamcat4** [comment]
hi again,

decided on option 1, + a symlink to `~/.wine` for changing the default wineprefix. Seems best option overall in case of other situations where the login script does not get run.

it had the desired effect and solved my bug

**Comment by strycore** [comment]
I don't really understand, Lutris will use the prefix set in its prefix path option, it is highly discouraged to leave it blank and default to ~/.wine.
