### ISSUE TITLE
(requires) add operators

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#351]
It would be nice if the requires field would support operator like or, and, provides etc.

for example on this way the freespace2 binary could be used with the steam, gog and the retail release

**Comment by strycore** [comment]
Yes, nice idea!
I will probably implement something similar to the Debian packaging format: multiple dependencies (AND) with commas and OR with the pipe character.

eg: 
`requires: freespace2-steam | freespace2-gog | freespace2-cd`

`provides` is a bit more tricky to implement but the idea is interesting.
