### ISSUE TITLE
Lutris ignore the native version on GOG

### ISSUE THREAD

**Issue by mleduque** [lutris/lutris#3510]
When i try to install Children of Morta from GoG, which has a native  linux version available on GoG, I get an "Install Children of Morta" dialog with only one option :
GOG w/ DXVK
I'm not especially knowledgeable on all that, but I though that was strange as for me that was a wine thing (is it?).
When I click on "install" and "view source", I see many things about windows (incl. a ChildrenOfMorta.exe) and nothing about a linux binary.

Why would it try to install the windows version and run it with wine when there's a linux binary?

**Comment by Cattodeveloper909** [comment]
Hello! because there isn't a install script of the native linux game, what I would recommend is to download the native game from the GOG webpage and then add it to lutris [manually](https://www.reddit.com/r/wine_gaming/comments/ejoh2x/manually_installing_games_with_lutris/) hope I can help you!

**Comment by mleduque** [comment]
Hm yes... but there is an install script, it's named children_of_morta_1_1_70_3_40979.sh !

**Comment by legluondunet** [comment]
Hello @mleduque ,
I just looked at https://lutris.net/games/children-of-morta/
Like @Cattodeveloper909  said there is no Lutris script for native GOG version of this game.
So you have two solutions:
- write a Lutris script for native GOG version of this game
- install the Lutris Windows GOG version of this game
