### ISSUE TITLE
don't preload the steam runtime for non-steam games

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#352]
one of my systems(debian unstable) is now incompatible with the steam runtime(steam runtime is built against an older libc), however I don't use steam so there is no reason to preload it.

also the most non-steam games are not built againt the runtime so its probably not a wise idea to use those libs with them

---------------------------------

also another solution would be game specific runtimes: 

* after the game is installed
* run an ldd check for all dynamicly linked libaries and binaries inside the $$gamedir to find missing and incompatible libs (could be done everytime the game starts)
* add only the missing libaries to a game specific runtime(eg $$gamedir/libs) and preload this dir

it would be a cleaner solution than the current one

also it could use distro archives like archive.debian.org and packages.debian.org to get almost any libary.

**Comment by strycore** [comment]
This is a little more complicated. We don't use the Steam runtime directly but take the Steam runtime, remove some libraries and add some other ones (from Ubuntu 14.04).

The build process is here: https://github.com/lutris/buildbot/blob/master/runtime/build.sh

The Lutris runtime is meant *specifically* for non Steam games, it's even disabled by default for Steam games: https://github.com/lutris/lutris/blob/master/lutris/runners/steam.py#L63

This runtime is meant to provide a base system that will ensure that most things we ship will run, regardless of what is installed on the user's computer. It is built on the same container that builds every  runner we ship (with some exceptions like Dolphin).

**Comment by Xodetaetl** [comment]
> it would be a cleaner solution than the current one

The current solution has a lot of issues, one of the major ones being our lack of expertize. We're relying on Valve for maintenance of 90% of the runtime (I don't even know if they do any security updates to theirs) and the remaining 10% is a lot of inject-shit-and-cross-fingers quality work by me and strycore. :'D

My hope is that Flatpak or another virtualization solution will save us of this mess soon. In fact Flatpak might already be ready for prime time Lutris games packaging. I'm trying to get a grasp of it.

**Comment by sixsixfive** [comment]
also i could track this down to the gpg-error libs under (~/.local/share/lutris/runtime/steam/* both are totally outdated (you ship 0.8, current/my system is 1.2.4) 

-----------------------------

@Xodetaetl 

ugh i have a poetterware déjà-vu

flatpack will probably not run on my non-systemd systems, it will also not work with bsd & co.

**Comment by Xodetaetl** [comment]
> flatpack will probably not run on my non-systemd systems, it will also not work with bsd & co.

[Here](https://github.com/flatpak/flatpak/releases/tag/0.6.10):
> Flatpak 0.6.10
>
> Dropped requirement for systemd --user. The way we detect if an process we're talking to is sandboxed, and what application id it has doesn't use cgroups anymore, which means that the dependency on systemd in the user session is now optional. This also means the --no-desktop argument is not needed any more. (It is still accepted but does nothing.)"

**Comment by strycore** [comment]
The procedure to follow for reporting runtime issues is now available here: http://wiki.lutris.net/index.php/Runtime
