### ISSUE TITLE
Running .yml locally leads to fatal python error init_import_size

### ISSUE THREAD

**Issue by hikkidev** [lutris/lutris#3528]
In general, I don’t know. If I run the installer from the site (like, `Test this script`) then everything works correctly, but running the installer locally via CLI leads to an exception. 
```console
$ lutris -di lutris-installation-script.yml
....
DEBUG    2021-05-02 12:39:43,759 [command.start:131]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/lib/python3.9/site-packages"
DEBUG    2021-05-02 12:39:43,759 [command.start:132]:/usr/share/lutris/bin/lutris-wrapper /home/hikki/.local/share/lutris/runners/wine/lutris-6.4-x86_64/bin/wine 0 0 /home/hikki/.local/share/lutris/runners/wine/lutris-6.4-x86_64/bin/wine /home/hikki/.cache/lutris/installer/Game/Some_installer.exe
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
File "/usr/lib/python3.9/site.py", line 73, in <module>
import os
File "/usr/lib/python3.9/os.py", line 29, in <module>
from _collections_abc import _check_methods
File "/usr/lib/python3.9/_collections_abc.py", line 12, in <module>
GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
DEBUG    2021-05-02 12:39:43,783 [command.on_stop:180]:Process hasn't terminated yet
DEBUG    2021-05-02 12:39:43,783 [command.on_stop:182]:Process 699056 has terminated with code 0
...
```
Error:
```Python
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.9/site.py", line 73, in <module>
    import os
  File "/usr/lib/python3.9/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/usr/lib/python3.9/_collections_abc.py", line 12, in <module>
    GenericAlias = type(list[int])
TypeError: 'type' object is not subscriptable
```

![image](https://user-images.githubusercontent.com/52655010/116804083-46463a00-ab46-11eb-9b62-f12c14fb153a.png)

**Comment by hikkidev** [comment]
Can I provide a different Python version in the metadata?

**Comment by TickingFeather** [comment]
I have the same error when running the Overwatch installer (a "gold" one, which I have used many times successfully in the past), without even editing it locally or anything. I tried reinstalling Python, without success.

**Comment by hikkidev** [comment]
I didn't go deep into the problem, but once I noticed that it worked after rebooting in "safe mode" (disabled various services while configuring other things for software dev).

**Comment by hikkidev** [comment]
The problem is somewhere in the updates of other packages on the system

**Comment by TickingFeather** [comment]
Alright, I found the problem. The main `lutris` executable (which is a python script) has `#!/usr/bin/env python` as a shebang, which points to the latest Python 3.9 installed on my system, but the `lutris-wrapper` used `#!/usr/bin/env python3` which pointed to an old Python 3.8 I installed manually a while ago. I had checked the target of the a `python3` symlink in `/usr/bin/`
