### ISSUE TITLE
After installation of EasyRPG runner executable for the runner has to be set manually

### ISSUE THREAD

**Issue by Layerex** [lutris/lutris#3529]
After installation of EasyRPG runner its executable is downloaded to `~/.local/share/lutris/runners/easyrpg/easyrpg-player`, but not used, so runner is not usable from lutris till `Custom executable for runner` in `Runner options` is set accordingly.

**Comment by deane-c64** [comment]
also, this might be Happening when you try to download the runner in install runners.
