### ISSUE TITLE
lutris[next] hangs now

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#353]
lutris is now unable to install openspades-x86-64

after extraction the shell becomes a zombie and lutris freezes

**Comment by strycore** [comment]
Well this proves that there are still some bugs resulting from the Python 2 -> 3 port. Thanks for noticing that!

**Comment by sixsixfive** [comment]
also it still doesnt work jet(aborting after 5min)

![aaa](https://cloud.githubusercontent.com/assets/3780774/18721642/a8ff4370-8031-11e6-95ad-a84ac1c8133d.png)

**Comment by strycore** [comment]
Is there any way I can try to reproduce this? and does this also happen if you remove 'sh' from the ignored processes in thread.py?
