### ISSUE TITLE
Support for Pipewire?

### ISSUE THREAD

**Issue by odziom91** [lutris/lutris#3531]
Hello!

I would like to request for Pipewire support.
In some distros it is a replacement for PulseAudio and some features are not available in Lutris. Unfortunately it requires to put it some options manually - for example it is not possible to set up PulseAudio Latency option, but package pipewire-pulseaudio is installed.
Maybe Pipewire can solve some problems with "choppy" or "unstable" sound in the future?

Kind regards,
Chris

**Comment by tannisroot** [comment]
https://github.com/lutris/lutris/commit/44b92adfdc529d6605373f528aee66b52f9e9ba6
