### ISSUE TITLE
[Feature request] Split dxvk and vkd3d-proton delivering

### ISSUE THREAD

**Issue by Mikaka27** [lutris/lutris#3537]
Currently dxvk and vkd3d-proton are delivered via dxvk lutris repository, which is updated when dxvk updates.

Since dxvk is in maintenance mode it won't see much updates. Therefore it would make sense to split dxvk and vkd3d-proton and deliver them separately.

What do you think?

**Comment by TheLostWanderer** [comment]
An alternative would be to add another hook to the lutris repository. That way it would also update when there is a new vkd3d release. That may be a faster workaround to implement.

This may need however to rename the releases of the lutris build to include both dxvk and vkd3d version number.

**Comment by tannisroot** [comment]
done
