### ISSUE TITLE
Updating Runners is messy / often bricks a prefix

### ISSUE THREAD

**Issue by s-iso** [lutris/lutris#3538]
Since quite a few months I've noticed that updating a game runner (which sometimes is essential due to games having patches that demand different plugins or running better with newer versions of wine) does not work properly. For some reason, various install steps are being silently omitted, the wine version isn't being upgraded properly and is stuck at a lower version still and, in various cases, the whole game is getting bricked by a wine version mismatched afterwards.

The only solution is to completely reinstall the game in a renamed folder (for example by adding a 2 at the end of the game folder), which means one has to completely redownload all game files again in most cases and one has to reconfigure everything (in certain games likes Star Citizen, this is an absolute pain in the ass).

I'd really love to see some improvements in this regard, because many AAA multiplayer titles are affected by this (I've had this exact issue happen with World of Warcraft, Overwatch and Star Citizen so far).

**Comment by t0cc** [comment]
I second this. Redownloading 50Gb+ every time you switch runner is not optimal.

**Comment by strycore** [comment]
I what specific situation have you encountered issues? 

I've been able to switch wine versions on any game prefix for years. I have never had a prefix been bricked by switching wine version?
