### ISSUE TITLE
Steam is not stopped after game exit.

### ISSUE THREAD

**Issue by PowaBanga** [lutris/lutris#3539]
Hi,
Is normal that steam is not stopped on game exit ? Have i something to do for that this feature work ?
Lutris version : 0.5.8.3
OS : Archlinux

**Comment by kajlando** [comment]
Click on Wine icon (in Lutris) -> Kill all WIne processes
Or create a bash file to kill all Wine processes (made by GloriousEggroll)
kill -9 $(ps -ef | grep -E -i '(wine|processid|\.exe)' | awk '{print $2}')
killall -9 pressure-vessel-adverb

**Comment by kajlando** [comment]
Click on Wine icon (in Lutris) -> Kill all WIne processes
Or create a bash file to kill all Wine processes (written by GloriousEggroll)
kill -9 $(ps -ef | grep -E -i '(wine|processid|.exe)' | awk '{print $2}')
killall -9 pressure-vessel-adverb

**Comment by kajlando** [comment]
Click on Wine icon (in Lutris) -> Kill all WIne processes
Or use this command (in the terminal or as a bash file) to kill all Wine processes (written by GloriousEggroll)
kill -9 $(ps -ef | grep -E -i '(wine|processid|.exe)' | awk '{print $2}')
killall -9 pressure-vessel-adverb

**Comment by PowaBanga** [comment]
hm yeah, is I simply click on "stop", this will do the work too
The problem is that is need launch my script when the game is finished, to kill my specifics xboxdrv conversions for exemple. In my case, i have differents config for every games
Is there a feature "launch script after the game"  who just not work on steam because steam is still running. 

So yes i can close steam manually with your script or simply by clicking on "stop" in lustris, but if i have to do that every time, I have to launch lutris everytime that i want to play a game, so it's not recommended to use menu shortcuts because finaly it's easier to use lutris to kill steam.

Anyway, in my case, i need to automatically launch my script post game. here it's not automatic, because i have to stop steam for that the game stop in lutris. And if steam is running before that i launch the game, so lutris will think that the game is finished after 20 seconds, and will launch my post script before the end of the start of the game, and so, kill my xboxdrv conversions

**Comment by kajlando** [comment]
I tried Configure->"Post-exit script" it didn't work with git and normal versions.
I found two "solutions": Configure->System options->Run in terminal and then ctrl + c to close and kill or apply the command to a custom keyboard shortcut that will kill Wine.
But yeah, there's something wrong with Lutris not closing Wine processes.

**Comment by kajlando** [comment]
I tried Configure->"Post-exit script" it didn't work with git and normal version.
I found two "solutions": Configure->System options->Run in terminal and then ctrl + c to close and kill or apply the command to a custom keyboard shortcut that will kill Wine.
But yeah, there's something wrong with Lutris not closing some Wine processes.

**Comment by PowaBanga** [comment]
it is nice of you to try to help me to find some other way to do it, i understand that there is very much way to kill steam process manually, but i posted this issue because it's not automatic as it should.

**Comment by tannisroot** [comment]
It's not really feasible to implement it sorry, just exit Steam manually too when you exit the game

**Comment by PowaBanga** [comment]
So maybeshould you delete the case option about that in lutris no ?

**Comment by tannisroot** [comment]
Case option?

**Comment by PowaBanga** [comment]
yes, this one : 
![](https://i.imgur.com/hjU0l9R.png)
why is the feature offered if it is not possible to implement it ?

**Comment by tannisroot** [comment]
It used to work but now it doesn't. It should probably be removed.
