### ISSUE TITLE
Lutris will not start after AMD driver 21.10-1247438 update

### ISSUE THREAD

**Issue by BrotherPatrix** [lutris/lutris#3541]
Operating system and kernel information:
```bash
$ uname -a
... 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
AMD GPU driver:
```bash
$ apt show amdgpu
Package: amdgpu
Version: 21.10-1247438
Priority: optional
Section: metapackages
Maintainer: Advanced Micro Devices (AMD) <slava.grigorev@amd.com>
Installed-Size: 9,216 B
Depends: amdgpu-dkms (= 1:5.9.20.104-1247438), amdgpu-lib (= 21.10-1247438)
Download-Size: 1,688 B
APT-Sources: file:/var/opt/amdgpu-pro-local ./ Packages
Description: Meta package to install amdgpu components.

$ apt show rocm-dkms
Package: rocm-dkms
Version: 4.2.0.40200-21
Priority: optional
Section: devel
Maintainer: ROCm-DKMS Meta Package Support <rocm-dkms.support@amd.com>
Installed-Size: 13.3 kB
Depends: rocm-dev, rock-dkms
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 784 B
APT-Manual-Installed: yes
APT-Sources: https://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack
```

ERROR:
```bash
$ lutris -d
2021-05-13 12:17:26,491: Initializing lutris
2021-05-13 12:17:28,534: Downloading DXVK releases to /home/user/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-05-13 12:17:28,534: Runtime updated. Initialization complete.
INFO     2021-05-13 12:17:28,535 [application.do_command_line:315]:Lutris 0.5.8.3
INFO     2021-05-13 12:17:28,536 [startup.check_driver:57]:Running AMD Mesa driver 20.3.4 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.41.0, 5.8.0-53-generic, LLVM 11.0.1) (0x731f)
INFO     2021-05-13 12:17:28,536 [startup.check_driver:69]:GPU: 1002:731F 1DA2:E409 (amdgpu drivers)
/usr/bin/python3: symbol lookup error: /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so: undefined symbol: amdgpu_query_video_caps_info
```

**Comment by Haijo7** [comment]
This is not a problem caused by Lutris, I get the ```undefined symbol: amdgpu_query_video_caps_info``` error when I try to run anything that uses vulkan. I think returning to an older driver version may fix the problem.

**Comment by BrotherPatrix** [comment]
I'm so sorry, I forgot to come back with a fix. My fix was to leave the default driver provided by the kernel and then follow the steps on https://github.com/lutris/docs/blob/master/WineDependencies.md to get Wine installed and then follow the guide on https://github.com/lutris/docs/blob/master/InstallingDrivers.md that indicates to install kisak-mesa for AMD/Intel.
Another thing to help people understand something, if you want to use programs that require OpenCL, I don't understand why the AMD driver script is not working either with amdgpu or amdgpu_pro(or something like that), but leaving the default AMD linux drivers and then installing ROCm using this guide https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html completly solved my problem.

**Comment by jameshulse** [comment]
I had the same issue, but resolved it by uninstalling the official AMD drivers (amdgpu) by running `amdgpu-uninstall` on the command line. It must have fallen back to using the default drivers now. I didn't install ROCm yet to see if that works.

**Comment by BrotherPatrix** [comment]
> I had the same issue, but resolved it by uninstalling the official AMD drivers (amdgpu) by running `amdgpu-uninstall` on the command line. It must have fallen back to using the default drivers now. I didn't install ROCm yet to see if that works.

I specified `if you want to use programs that require OpenCL`, so my use case was to be able to play games, but at the same time use a program that required OpenCL, in my case it was DaVinci Resolve, and ROCm was the solution for me that din't interfere with Lutris requirements.

**Comment by neoedmund** [comment]
`amdgpu_query_video_caps_info` is located in `libdrm_amdgpu.so`
so upgrade libdrm from https://gitlab.freedesktop.org/mesa/drm
and make sure  `ldd libvulkan_radeon.so` referencing the new built version of `libdrm_amdgpu.so`
