### ISSUE TITLE
Star Citizen 3.13 Needs Two New Functions

### ISSUE THREAD

**Issue by Ackurus** [lutris/lutris#3542]
Hello

I'm not sure if this is the right place to raise an issue about a runner.

I've submitted a PR and an issue for Lutris-6.4 which would allow that runner to work with Star Citizen. One of the commits is already in upstream wine 6.8, and the other one is in the patches list. Wine 6.4 already includes fixes to wineserver Star Citizen benefits from which are not in 6.3. So, patching 6.4 provides the best outcome for Star Citizen users.

Thank you!

**Comment by t0cc** [comment]
What's your setup and configuration? I try to get SC running for days and even `lug-helper` did not help solving this.

**Comment by Ackurus** [comment]
Star Citizen 3.13.1 dropped the need for a query wine didn't support. wine-lutris-6.10-x86_64 is functional with Star Citizen, all versions of wine from 6.8 and after should work with Star Citizen 3.13.1.
