### ISSUE TITLE
Game not starting correctly without using terminal

### ISSUE THREAD

**Issue by TheNyneR** [lutris/lutris#3543]
Hello everyone,

I’m trying to get the game “Starsector” to work.
When I run Lutris via Terminal with `lutris -d` the game starts and all assets are loaded correctly. When I run the game options in a terminal it also works.
However when I just execute Lutris the game itself starts but it can not load the needed assets.
I can not exit the game and have to kill it with a SIGTERM, while I have to kill the lutris wrapper with SIGKILL.

Here are some system info and the log of the game:
[Lutris issue report](https://paste.sr.ht/~nyner/379f5d22b1a288d96c64059b62cc8d8c186b6f81)
[Starsector log](https://paste.sr.ht/~nyner/fca2b5f04b87b0fa4be5f2edb83b8cacf3b59534)

**Comment by TheLostWanderer** [comment]
Hey

I get a similar problem with HorizonZeroDown. The difference is game only launches if I start lutris with `lutris -d` in terminal and then launch the game or with directly launching the game from the terminal (using `lutris lutris:rungameid/ID`). Other than that, it just fails.

[Lutris game logs when failing](https://0bin.net/paste/Y8zcXSN2#TtwdSMkNnAErV0cx73iqD-N9LLgMsXwYf2qnq/WhINm)
[Lutris game logs when launching the game](https://0bin.net/paste/AYlMb7Yl#htxZkZs2MiOF2Pl19qwZ04UFDtcv4P5DciaZcI3FMBC)

**Comment by TheNyneR** [comment]
Found out what it was for me.
I'm using Sway on Wayland and was practically starting Lutris with
`lutris | xargs swaymsg exec --`.
Somehow this broke the game as well as the download functionality in Lutris itself (BrokenPipeError Errno 32).
