### ISSUE TITLE
PermissionError: os.kill(int(pid), signal.SIGTERM)

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3546]
Was plating Ri-Li, and when I closed it, I got this on the terminal:

```
DEBUG    2021-05-19 01:37:32,131 [command.on_stop:193]:Process 588 has terminated with code 0
Traceback (most recent call last):
  File "~/src/lutris/lutris/game_actions.py", line 144, in on_game_stop
    game.force_stop()
  File "~/src/lutris/lutris/game.py", line 525, in force_stop
    os.kill(int(pid), signal.SIGTERM)
PermissionError: [Errno 1] Operation not permitted
```

I had to ctrl+c to kill Lutris, as Lutris became totally unresponsive

**Comment by telanus** [comment]
@strycore. It's still happening with the latest GIT

**Comment by telanus** [comment]
> It doesn't happen when using a normal mame game, only with chd based games

Was playing Circus Charlie this morning, and this bug reared his head again.

**Comment by strycore** [comment]
fixed
