### ISSUE TITLE
question about wine dependecy

### ISSUE THREAD

**Issue by methane4** [lutris/lutris#3547]
So i was just installing lutris and i noticed lutris would install wine as a dependecy. Wasnt it suposed to be installed as a runtime inside lutris? im asking because i dont want my system to be able to execute windows binaries (apart from the games inside lutris) in normal usage

**Comment by dpanter** [comment]
Which distro and how did you install? Wine isn't a dependency for Lutris in the Debian repos.

**Comment by methane4** [comment]
Fedora, it installs wine as a dependecy. i removed wine now but it shouldnt be listed as a dependecy
