### ISSUE TITLE
Lutris dependencies not fully documented

### ISSUE THREAD

**Issue by Lewiscowles1986** [lutris/lutris#3553]
Firstly, thanks for making this tool. I've not used it, but I plan to and it's nice that someone took the time to share this with the world.

Unfortunately I hit a problem. Not wanting to add a ppa, I decided to build from source. I would have used a snap, appimage or flatpak if one were provided, but I didn't see it on https://lutris.net/downloads/ or the README.md of this repo. If it does exist, please let me know.

Anyway... I found it prohibitively difficult when considering anyone who is not a coder or sysadmin.

This is one of a series of issues about the experience. I'll make more if it is of interest, but maybe I'm underestimating the target audience.

At the end of my journey, after getting additional system dependencies, I received this message after completing the install of all requirements on ubuntu 18.04 LTS using python 3.9 in a virtualenv, x86_64 using `pip install -r requirements.txt`.

```
~/lutris$ bin/lutris -d
2021-05-29 08:47:10,286: Package 'distro' unavailable. Unable to read Linux distribution
Traceback (most recent call last):
  File "/home/lewis/lutris/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/lewis/lutris/lutris/gui/application.py", line 43, in <module>
    from lutris.gui.installerwindow import InstallerWindow
  File "/home/lewis/lutris/lutris/gui/installerwindow.py", line 17, in <module>
    from lutris.installer import interpreter
  File "/home/lewis/lutris/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/home/lewis/lutris/lutris/installer/installer.py", line 13, in <module>
    from lutris.services import SERVICES
  File "/home/lewis/lutris/lutris/services/__init__.py", line 9, in <module>
    from lutris.services.gog import GOGService
  File "/home/lewis/lutris/lutris/services/gog.py", line 9, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

```

I solved this issue (for me, not for others who might run into it) by using the following command.

```
pip install lxml
```

**Comment by strycore** [comment]
Reminder that while virtualenvs are great, Lutris is not really fitted to this kind of setup due to it's usage of PyGObject. 

I see that lxml is now present in the setup.py so the installation on a very minimal python setup should now work. But there are no guarantees the software will work properly from a venv.

**Comment by strycore** [comment]
> I would have used a snap, appimage or flatpak if one were provided

Flatpak is now available!
