### ISSUE TITLE
[Feature Request] Tagging/Categorising.

### ISSUE THREAD

**Issue by Latrolage** [lutris/lutris#3555]
Feature request for tagging/categorizing apps/games in lutris manually (or automatically through lutris.net?).
It could help with sorting the view screen, for example, the user could make custom "views". Which would be like tabs on lutris which each show games with different set of tags (both manually added and tags a game has on lutris.net).

Something else could be folders in lutris. Grouping applications/games in a familiar folder/directory like structure.

**Comment by strycore** [comment]
Implemented in https://github.com/lutris/lutris/pull/4482
