### ISSUE TITLE
Lutris Crash on Installation (of Battle.net)

### ISSUE THREAD

**Issue by raQai** [lutris/lutris#3556]
When opening the installation dialog fo Battle.net and closing/cancelling it because e.g. you want to check your dependencies beforehand, re-running the installation will close/crash Lutris.

I currently do not know whether this is only related to Battle.net or any other application.

**Steps to reproduce:**
1. Start Lutris
2. Search Battle.net
3. Install Battle.net (only open the dialog)
4. Cancel installation (from dialog)
5. Install Battle.net again

**System configuration:**
```
~ >>> cat /etc/lsb-release                                                                 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.5
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```
```
GNOM Version 40.1.0
Kernel Version 5.11.19-1
Lutris Version 0.5.8.3
```

If anything else is needed, let me know

**Comment by tannisroot** [comment]
Yeah a log of `lutris -d` would be nice

**Comment by raQai** [comment]
This has been fixed with one of the recent updates and can no longer be reproduced on my system.
