### ISSUE TITLE
Improve UI: "No installer for" should give user a visible feedback (notification window e.g.)

### ISSUE THREAD

**Issue by DeltaLima** [lutris/lutris#3558]
OS: Ubuntu 20.04.2
Lutris: v0.5.8.3 from lutris ppa

I was a bit confused when i tried to install a game, which was found in the lutris library but when I clicked on "Install" nothing happened.
When I started lutris from the shell I saw the reason for it: "No installer for GameXYZ" 

It would be nice  the UI gives the user a visible feedback (notification window e.g.) when there is no lutris installer available for it. 
For a beginner or unexperienced user the actual behavior might look that the program is broken.

Best regards :)

**Comment by strycore** [comment]
fixed
