### ISSUE TITLE
Debian 10 Key expired at Suse Build Service

### ISSUE THREAD

**Issue by sysms** [lutris/lutris#3562]
Dear maintainer(s),

I just want to inform you, that the key file at 

https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key

has expired yesterday:

pub   rsa2048 2014-11-04 [SC] [expired: 2021-06-02]
      A338 F71A 89CD 06FD 5F97  1858 2F7F 0DA5 FD5B 64B9
uid           [ expired] home:strycore OBS Project <home:strycore@build.opensuse.org>

Without a valid key, no installation and/or updating from this repo is possible.

Please fix this. Thank you.

**Comment by strycore** [comment]
Thanks for letting me know, I've renewed the PGP key so it should be working now.

**Comment by Maxwellfire** [comment]
This key has expired again as of today
