### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by doughyboy** [lutris/lutris#3563]
I feel as though it would be trivial to add Discord Rich Presence functionality, as Lutris is written in Python and Discord conveniently has a python library. Any thoughts?

**Comment by nyym** [comment]
Long time since I'm waiting to see this on Lutris and Steam, that would be great.

**Comment by Technetium1** [comment]
I strongly support this request.

**Comment by tannisroot** [comment]
We had it and it was useless because we could only show that users are using lutris, and it was adding an unnecessary dependency.
