### ISSUE TITLE
Epic Games doesn`t work in Ubuntu 20.04

### ISSUE THREAD

**Issue by TomaszMyszak** [lutris/lutris#3568]
Hello everyone, 
I have a problem to start EG. This is a log file:
[https://1drv.ms/u/s!AnEjX48symZYmqADPFxv_vcD88Kwcg?e=pVNeXA](url)

im tying to fix it to use this:

apt-get install --reinstall gstreamer1.0-alsa gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0 libgstreamer1.0-0

and still doesn`t work, could U have eny idea to fix this bug.

**Comment by SheilaGLZ** [comment]
could you solve this problem?
