### ISSUE TITLE
After compiling from source, runner options are not shown

### ISSUE THREAD

**Issue by MossyMossMoss** [lutris/lutris#3571]
Since the latest release (0.5.8.3), the runner menu has gotten an overhaul. I can no longer access the options of the runners whereas I can in the latest release. When pressing the config button in the runners list, it brings me to the system options tab. I can click on the 'Runner options' tab, but it just gives me the message 'Select a runner in the Game Info tab'

**Comment by tannisroot** [comment]
I cannot reproduce this with the Wine runner
