### ISSUE TITLE
Origin doesnt work under Manjaro Linux

### ISSUE THREAD

**Issue by nonunknown** [lutris/lutris#3575]
When installing origin or battlefield 4 from lutris website the following error when initializing application

```
Running /home/nonunknown/.local/share/lutris/runners/wine/lutris-6.10-2-x86_64/bin/wine /run/media/nonunknown/3a1f3657-ce4a-4ffa-8f65-f41e1dfcaf68/games/battlefield-4/drive_c/Program Files (x86)/Origin/Origin.exe
Initial process has started with pid 47011
Start monitoring process.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
info:  Game: Origin.exe
info:  DXVK: v1.8.1
info:  Found config file: /run/media/nonunknown/3a1f3657-ce4a-4ffa-8f65-f41e1dfcaf68/games/battlefield-4/dxvk.conf
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
Initial process has exited (return code: 768)
Monitored process exited.
All monitored processes have exited.
Exit with returncode 768
2021-06-16 08:27:35,274: Game still running (state: running)
2021-06-16 08:27:35,275: Stopping Battlefield 4 (wine)


```

**Comment by tannisroot** [comment]
Your drivers are broken
https://github.com/lutris/docs/blob/master/InstallingDrivers.md

**Comment by nzbtuxnews** [comment]
I have the exact same problem on Linux Mint 20.2 (fully up to date) with NVidia GT1030 and drivers 470.57.02.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+

libvulkan1 and libvulkan1:i386 are both installed and are latest version.

Vulkan is also installed and vkcube demo works flawlessly

vulkaninfo

Vulkan Instance Version: 1.1.126
Instance Extensions: count = 18
VK_EXT_acquire_xlib_display : extension revision 1
VK_EXT_debug_report : extension revision 9
VK_EXT_debug_utils : extension revision 2
VK_EXT_direct_mode_display : extension revision 1
VK_EXT_display_surface_counter : extension revision 1
VK_KHR_device_group_creation : extension revision 1
VK_KHR_display : extension revision 23
VK_KHR_external_fence_capabilities : extension revision 1
VK_KHR_external_memory_capabilities : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2 : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 1
VK_KHR_get_surface_capabilities2 : extension revision 1
VK_KHR_surface : extension revision 25
VK_KHR_surface_protected_capabilities : extension revision 1
VK_KHR_wayland_surface : extension revision 6
VK_KHR_xcb_surface : extension revision 6
VK_KHR_xlib_surface : extension revision 6
Layers: count = 0
Presentable Surfaces
GPU id : 0 (NVIDIA GeForce GT 1030)
   Surface types: count = 4
   Formats: count = 2
   Present Modes: count = 3
   VkSurfaceCapabilitiesKHR
   VkSurfaceCapabilities2EXT
   VkSurfaceProtectedCapabilitiesKHR
GPU id : 1 (NVIDIA GeForce GT 1030)
   Surface types: count = 4
   Formats: count = 2
   Present Modes: count = 3
   VkSurfaceCapabilitiesKHR
   VkSurfaceCapabilities2EXT
   VkSurfaceProtectedCapabilitiesKHR


Lutris is version 0.5.8.4


However when I run "vulkaninfo" it spits :

WARNING: [Loader Message] Code 0 : loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
WARNING: [Loader Message] Code 0 : loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
