### ISSUE TITLE
[FEATURE REQUEST] Add support for Box86 as a runner

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#3578]
### Add support for Box86 as a runner for games
I was testing out [Twister os](https://twisteros.com/) on my [Raspberry Pi 4B](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/), mostly to see how well Wine, Box86, and other emulators worked on it. I found that Lutris was installed by default on the os so I decided to try it out. The games that it came with worked, though I had trouble finding games that worked other than the few that were installed by default. For example, when I tried to install supertux it couldn't run it because it was x86, and not running through Box86. I had to install it through apt, find the executable and add it to Lutris instead. So far my experience with Lutris has been perfect other than this though 😄 thank you for developing this awesome software!

EDIT: If this idea is approved, I'd be willing to help in any way I can do add this! I have a good amount of python experience (No expert at emulation though)

**Comment by strycore** [comment]
Box86 isn't a runner, it doesn't work like one, it can't be shipped or installed by Lutris and it just needs to be installed and Lutris will support x86 executables
