### ISSUE TITLE
Add an option to rebind keys

### ISSUE THREAD

**Issue by MrHeating** [lutris/lutris#3586]
It would be very helpful if there was an option to rebind keys for specific games, and unbind them back to default when exiting the game, similar to how changing resolutions works.

Perhaps it'd also make sense to keep track of whether the game is focused and bind/unbind keys depending on whether it is.

**Comment by tannisroot** [comment]
We may add this functionality if it's implemented by some library or a program, in a form of integration.
Please open a new issue if you find such program.
