### ISSUE TITLE
Lutris error: AttributeError: 'NoneType' object has no attribute 'show'

### ISSUE THREAD

**Issue by Dodgexander** [lutris/lutris#3598]
Description of problem:
Launching world of warcraft via lutris, error happened straight away but did not seem to cause a problem.

Version-Release number of selected component:
lutris-0.5.8.3-6.fc34 (also happens with latest version)

Additional info:
reporter:       libreport-2.15.2
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-net.lutris.world\x2dof\x2dwarcraft\x2d1-11403.scope
cmdline:        /usr/bin/python3 -s /usr/bin/lutris lutris:rungameid/1
crash_function: on_game_start
exception_type: AttributeError
executable:     /usr/bin/lutris
interpreter:    python3-3.9.5-2.fc34.x86_64
kernel:         5.12.13-301.fsync.fc34.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
sidebar.py:377:on_game_start:AttributeError: 'NoneType' object has no attribute 'show'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/sidebar.py", line 377, in on_game_start
    self.running_row.show()
AttributeError: 'NoneType' object has no attribute 'show'

Local variables in innermost frame:
self: <sidebar.LutrisSidebar object at 0x7fe57d41a040 (LutrisSidebar at 0x557e551da670)>
_game: World of Warcraft (wine)

More info and backtraces of various crashes here:
https://bugzilla.redhat.com/show_bug.cgi?id=1978078

**Comment by eiglow** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1991109 There is also this bug report, almost a duplicate, but the error is on a different line of the same file. I ran into this when starting Minecraft Java Edition MultiMC

**Comment by tannisroot** [comment]
Make a new issue if this is still a valid in 0.5.9.1, I am not really able to reproduce.
