### ISSUE TITLE
[Feature request] Pass CLI arguments to the process

### ISSUE THREAD

**Issue by Maykin-99** [lutris/lutris#3602]
I have Cemu set up with Lutris and it works fine.
What I would like to do now is to write a bunch of `.desktop` files for each emulated game.
For that I need to be able to pass arguments to `Cemu.exe`.

The interface would look like that:
```
lutris lutris:rungame/cemu -- -g /path/to/game -f
```
and it should run:
```
Cemu.exe -g /path/to/game -f
```
Currently everything after `lutris:rungame/cemu` is being ignored.

You might ask why I don't copy Cemu in Lutris and add the arguments in the "Game options": Simply to avoid redundancy. If I want to make changes to Cemu in Lutris I want these changes to be applied to all games

**Comment by tannisroot** [comment]
You can use a single Cemu prefix for all your custom game entries to avoid redundancy.

**Comment by Maykin-99** [comment]
Can you please elaborate what a "single Cemu prefix" is?

I've added a new game in Lutris and I gave it the same Wine prefix as Cemu but - as far as I can see - the Runner Options and System options that are set in Cemu aren't applied to the new game.

**Comment by Maykin-99** [comment]
For anyone having the same issue:

Use `lutris -b cemu.sh cemu` to export a bash script and slap `"$@"` at the end.

Then you can use `cemu.sh -g /path/to/game -f`

**Comment by tannisroot** [comment]
@Maykin-99 you can copy configuration for new games in .config/lutris/games

**Comment by Maykin-99** [comment]
What's the difference between copying the `.yml` file and copying the game in Lutris itself?

But as stated in the original post: I don't want to copy. I want to extend. I don't want to readjust the copies if I adjust the "original".

I now have for each game a `.desktop` file which all use the bash script exported by Lutris with the `-b` option.
If I need to make adjustments (to Cemu in this case) then I just make them in Lutris and re-export the bash script and all games are automatically updated as well.

I think that's an acceptable solution to my problem.
