### ISSUE TITLE
Lutris hangs for a very long time after clicking install on a Steam game

### ISSUE THREAD

**Issue by CorvetteCole** [lutris/lutris#3611]
Completely fresh install of Lutris on Arch Linux with Gnome. When I click install on a Steam game Lutris hangs for a very long time, then crashes. I still miss the library syncing :(

Here is the Lutris Issue Report JSON: https://ghostbin.co/paste/oy4r37a

I have attached the Lutris debug output below
```
2021-07-30 21:06:47,772: No cores found
2021-07-30 21:06:47,823: Initializing lutris
2021-07-30 21:08:48,547: Downloading DXVK releases to /home/coleg/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-07-30 21:08:48,813: Writing to /home/coleg/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-07-30 21:08:48,814: Runtime updated. Initialization complete.
INFO     2021-07-30 21:08:48,815 [application.do_command_line:315]:Lutris 0.5.8.4
INFO     2021-07-30 21:08:48,815 [startup.check_driver:57]:Running AMD Mesa driver 21.1.5 on AMD Radeon RX 5700 XT 50th Anniversary (NAVI10, DRM 3.41.0, 5.13.6-arch1-1, LLVM 12.0.1) (0x731f)
INFO     2021-07-30 21:08:48,816 [startup.check_driver:69]:GPU: 1002:731F 1002:0B36 (amdgpu drivers)
DEBUG    2021-07-30 21:09:01,646 [http.get:73]:GET https://lutris.net/api/games/service/steam
DEBUG    2021-07-30 21:10:01,957 [__init__.fetch_script:22]:Fetching installer https://lutris.net/api/installers/beamngdrive
DEBUG    2021-07-30 21:10:01,957 [http.get:73]:GET https://lutris.net/api/installers/beamngdrive
DEBUG    2021-07-30 21:11:23,015 [displayconfig.get_current_resolution:624]:Retrieving current resolution
DEBUG    2021-07-30 21:11:23,016 [installerwindow.on_runners_ready:301]:Installer doesn't require files
DEBUG    2021-07-30 21:11:23,018 [installer.write_game_config:224]:Writing game config to /home/coleg/.config/lutris/games/beamngdrive-steam-1627697483.yml
DEBUG    2021-07-30 21:11:23,021 [game.save:260]:Saving BeamNG.drive (steam) with config ID beamngdrive-steam-1627697483
DEBUG    2021-07-30 21:11:23,063 [lutriswindow.on_game_collection_changed:780]:Game collection changed
DEBUG    2021-07-30 21:11:23,070 [http.get:73]:GET https://lutris.net/api/games/beamngdrive
DEBUG    2021-07-30 21:12:24,431 [http.get:73]:GET https://lutris.net/games/banner/beamngdrive.jpg
INFO     2021-07-30 21:13:24,881 [http.write_to_file:123]:Writing to /home/coleg/.local/share/lutris/banners/beamngdrive.jpg
Gdk-Message: 21:13:24.914: Error reading events from display: Connection reset by peer
```

**Comment by CorvetteCole** [comment]
hello @tannisroot I see you've closed the issue, can I get a quick reason why? Thanks

**Comment by tannisroot** [comment]
Because I cannot reproduce this, there is nothing in the log that indicates Lutris crashes and you provided no specific reproduction steps.

**Comment by CorvetteCole** [comment]
@tannisroot I pulled the latest git and built it. This crash is not present in the latest version. However, it still does hang for an extremely long time after clicking the install button (no feedback, just frozen, 1.5+ minutes). I think this may be related to a slow internet connection, but I think Lutris should handle it better. I am looking in to the code to see where specifically this issue is happening

**Comment by tannisroot** [comment]
Thanks you. I wish I could help but it just doesn't happen here.

**Comment by GloriousEggroll** [comment]
https://bugs.winehq.org/show_bug.cgi?id=51516
check if gst-editing-services is installed on your system

**Comment by CorvetteCole** [comment]
I will check that later today and update this issue. Thanks for the lead!

**Comment by tannisroot** [comment]
@GloriousEggroll i am not sure if it's applicable to Lutris since we point to our own GST libraries, and when I had the issue with that package installed, I couldn't reproduce it with the Lutris builds.

**Comment by strycore** [comment]
fixed
