### ISSUE TITLE
Lutris doesn't correctly load all necessary Vulkan ICD files

### ISSUE THREAD

**Issue by GloriousEggroll** [lutris/lutris#3612]
When Vulkan ICD files are loaded, it needs to load both 64 and 32 bit. 
The 'Auto' option only loads the 64 bit by default. This causes 32 bit applications (usually game launchers) to fail.
The other drop down options only allow selection of either the 32 bit or 64 bit file, not both.

Example from uplay:

```
Initial process has exited (return code: 0)
info:  Game: upc.exe
info:  DXVK: v1.9.1-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
Monitored process exited.
All monitored processes have exited.
Exit with returncode 0
```

A temporary workaround is to specify both in an envvar, example:
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json`

**Comment by tannisroot** [comment]
Please test https://github.com/lutris/lutris/commit/089b8652906222f46323093b2aabb4cf80f0faaa

**Comment by GloriousEggroll** [comment]
This issue still persists in Fedora. Re-opening. I am looking into it and working on a resolution.

**Comment by GloriousEggroll** [comment]
edit -- seems I'm not able to re-open the issue.

**Comment by GloriousEggroll** [comment]
Figured it out, will submit PR shortly.
