### ISSUE TITLE
Namespace GnomeDesktop not available

### ISSUE THREAD

**Issue by Jigoku** [lutris/lutris#3621]
```
> $ ./bin/lutris -d                                                                              
Traceback (most recent call last):
  File "/home/jigoku/bin/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/jigoku/bin/lutris/lutris/gui/application.py", line 31, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```

How come Lutris requires Gnome dependencies? Is there a solution to get this running without Gnome related packages installed?

**Comment by strycore** [comment]
How did you install lutris? Every package available should install libgnome-desktop as a dependency.

Libgnome-desktop is not Gnome, it's a poorly named library that is used to get a list of screen resolutions for wayland.

**Comment by Jigoku** [comment]
libgnome-desktop isn't required for anything on my system, and i didn't actually install lutris, i'm running it from the cloned git... I'm just curious, if it's only required for wayland, couldn't that check be ignored in the case wayland is not present? Just seems like a weird dependency...

**Comment by AlexanderRavenheart** [comment]
It is mentioned on the download [page](https://lutris.net/downloads/) that if you use the Tarball or Source variants, you have to ensure you have all dependencies installed.

As a recommendation, even if you only want to use a development version, you should install the version available in the package manager of your distribution so that all required dependencies are installed for you, without having to track down and install individual packages.

**Comment by Jigoku** [comment]
Yeah libgnome-desktop isn't available on my distribution (slackware -current), can't find it in the additional slackbuilds either. 
I don't mean to nag, but what is that library doing exactly? Is it just wayland related things, if it is, might be worth adding an exception for systems where wayland isn't present?

**Comment by strycore** [comment]
> Yeah libgnome-desktop isn't available on my distribution (slackware -current)

not true, it might have another name but people have run lutris on slackware before.

**Comment by strycore** [comment]
Install this
https://slackware.pkgs.org/14.2/slackonly-x86_64/gnome-desktop-3.18.2-x86_64-1_slonly.txz.html

I can't and don't want to explain why installing the gnome-desktop package won't install the gnome desktop. Just install it, it won't install Gnome. This is just incredibly bad naming.
