### ISSUE TITLE
In 0.5.9beta1 Epic Login panel only shows language codes

### ISSUE THREAD

**Issue by BiRo96** [lutris/lutris#3632]
## Only language codes are visible for strings on login panel
![image](https://user-images.githubusercontent.com/22392953/128008547-029b6126-5aff-4a15-b601-d2349df06d7b.png)  
![image](https://user-images.githubusercontent.com/22392953/128008749-00daf62e-ce0e-401e-ae1a-df74dd292d26.png)  
![image](https://user-images.githubusercontent.com/22392953/128009049-ef5cfdcd-67f2-425e-bb19-1d7d36d437f0.png)

**Comment by BiRo96** [comment]
![image](https://user-images.githubusercontent.com/22392953/128008712-1cdec713-ffd8-4f54-8016-ee3dc71eaf08.png)

**Comment by tannisroot** [comment]
I cannot reproduce this
