### ISSUE TITLE
Option to add an image to the Discord Rich presence

### ISSUE THREAD

**Issue by Smashidachi** [lutris/lutris#3633]
i just recently discovered the Discord Rich Presence function in Lutris and i wondered if there is some way to also let it show an image? I don't want a separate image for each game i just want one single image for Lutris itself. I already hooked a custom application from my Discord account into Lutris so now i would just need an option to select an art asset.
I would call this a feature request but i have no clue how to set labels so i hope this is not causing any trouble.

**Comment by tannisroot** [comment]
Discord Rich presence support is being nuked AFAIK
