### ISSUE TITLE
EGS service does not sync

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3634]
Hello Lutris Team, is the EGS service working for you?
I updated today Lutris to latest git  version
and when I try to sync EGS games, I only have a dialog box saying  it doesn't find  '/home/legluondunet/Games/epic-games-store/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests'

INFO     2021-08-03 09:35:16,299 [egs.add_installed_games:328]:EGS detected in /home/legluondunet/Games/epic-games-store
ERROR    2021-08-03 09:35:16,300 [jobs.target:36]:Error while completing task <bound method BaseService.reload of <egs.EpicGamesStoreService object at 0x7f6b353ff280 (lutris+services+egs+EpicGamesStoreService at 0x3094d00)>>: <class 'FileNotFoundError'> [Errno 2] Aucun fichier ou dossier de ce type: '/home/legluondunet/Games/epic-games-store/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests'
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/services/base.py", line 81, in reload
    self.add_installed_games()
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/services/egs.py", line 333, in add_installed_games
    for manifest in egs_launcher.iter_manifests():
  File "/home/legluondunet/Autres_applications/Jeux/Lutris/lutris/lutris/util/egs/egs_launcher.py", line 14, in iter_manifests
    for manifest in os.listdir(manifests_path):

**Comment by tannisroot** [comment]
I am not sure about pre-existing installations but I can reliably reproduce this if I do a clean set up of the EGS service (including removing existing EGS prefix).

**Comment by strycore** [comment]
I've added a check to prevent the crash if the manifest path doesn't exist.
