### ISSUE TITLE
Disabling the side bar hides all games

### ISSUE THREAD

**Issue by Blaqwood** [lutris/lutris#3636]
When I disable the side bar, lutris starts up with an empty game list(looks like a freshly installed lutris) and the only way to see them again is to change the zoom level or click the view toggle or just enable the side bar again

the command line still works but I can't actually play anything using the GUI

Startup without sidebar
![image](https://user-images.githubusercontent.com/68885343/128104784-cc7b285b-8d72-40fa-a597-730bd89579ea.png)

Startup with sidebar
![image](https://user-images.githubusercontent.com/68885343/128104940-73b6fb7e-6135-43fe-ae9e-bea697f84b80.png)

Startup with sidebar then clicking [toggle view]
![image](https://user-images.githubusercontent.com/68885343/128104850-22d2c3cc-3bae-4b71-8493-4a05860fee24.png)

**Comment by Weenut** [comment]
Forgot to mention that I'm running version 0.5.9

**Comment by tannisroot** [comment]
Can you provide system info from our special section in preferences

**Comment by Weenut** [comment]
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.13.10-zen1-1-zen
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD A9-9400 RADEON R5, 5 COMPUTE CORES 2C+3G
Physical cores:  2
Logical cores:   2

[Memory]
RAM:             7.2 GB
Swap:            16.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD STONEY (DRM 3.41.0, 5.13.10-zen1-1-zen, LLVM 12.0.1)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 21.1.6
OpenGL Core:     4.5 (Core Profile) Mesa 21.1.6
OpenGL ES:       OpenGL ES 3.2 Mesa 21.1.6
Vulkan:          Supported

**Comment by strycore** [comment]
fixed
