### ISSUE TITLE
[Icon View] New installed games are put at the end of the list

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#364]
@strycore 
Er, you've used Lutris at all since switching the icon view to grid? :P

**Comment by strycore** [comment]
I did! And I've been fixing the issues as I came across them :p The Flowbox is still missing a sort function, thanks for reminding that

**Comment by telanus** [comment]
@strycore seems current sorting now makes a distinction between capital leters and not. IS Zupapa will now before eXceed: http://i.imgur.com/uPtd5NK.png

**Comment by strycore** [comment]
That's weird, I copied the sort function from the previous game view. Anyway, I've changed it to make it case insensitive, should be ok now.
