### ISSUE TITLE
Lutris option to enable ACO shader compiler is no longer needed since ACO is already default

### ISSUE THREAD

**Issue by Venemo** [lutris/lutris#3641]
RADV contributor here. Last year we already made ACO the default shader compiler in RADV, and this is what we recommend as a default to our users. You no longer need any environment variable or specific config to enable ACO, it will be already enabled if you use **mesa 20.2** or later (which is about a year old already at this point).

To avoid confusion, I suggest to remove the "Enable ACO shader compiler" switch from Lutris's System options dialog.

Side note: in the rare case when ACO has a bug and the user wants to test against RADV's old LLVM compiler backend, `RADV_DEBUG=llvm` can still be used. However we don't recommend promoting this option because these days we spend most of our effort advancing ACO and less effort on maintaining the old backend.

**Comment by strycore** [comment]
Closed in c22629b30f13420d9788599a0e635962a164ba17 and 59eeaf5f2ff27cb378c56af413dacc6b0145e4ff
