### ISSUE TITLE
When I restart pc no wine apps from lutris will open I have to shutdown pc.

### ISSUE THREAD

**Issue by Sultech** [lutris/lutris#3644]
So, I was playing Rocket league from the epic games launcher using lutris, everything was working fine. Then I restart my computer and no wine app from lutris will open, epic games doesn't open neither does any of my other games that use wine. I tried different wine versions nothing worked. I also tried to run a app with my normal wine installed and it worked so its a problem with lutris. Then I shutdown my pc, instead of restarting, turned it back on and everything starts to work again. I don't understand why this is happening. 

My distro is manjaro gnome and im using kernel 5.13

**Comment by Sultech** [comment]
I'm using v0.5.8.4

**Comment by tannisroot** [comment]
Maybe you had your nvidia drivers updated and those require a restart. This is not the place to get support, instead join our Discord and ask me for help there.
