### ISSUE TITLE
[Feature request] Allow to pass arguments to games from cli

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [lutris/lutris#3648]
It would be useful to be able to pass arguments to a game via the lutris command.
A good example of this is to start Cemu games (Wii U emulator for windows) directly from the cli, without touching the gui.
It would be useful to add desktop entries for these games that are started via a program started itself via lutris.

**Comment by GeoffreyCoulaud** [comment]
Well, #3602 seems to propose a solution. 
However, it would still be nice to integrate this better into lutris IMO.

**Comment by tannisroot** [comment]
> Maybe that’s opening a can of worms in CLI complexity though, because then they might want to add the ability to extend every configuration option through CLI...

exactly plus we fail to see the usefulness for such feature
