### ISSUE TITLE
left bottom corner is not rounded in gnome 40

### ISSUE THREAD

**Issue by narisuzu** [lutris/lutris#3649]
the left bottom corner of the main window is not rounded
![image](https://user-images.githubusercontent.com/16162768/128660425-2c470570-2319-4138-891b-2a9d56dc52f5.png)

**Comment by tannisroot** [comment]
The corners are not rounded in default Adwaita, so I can't reproduce.
Seeing how this is a third-party theme or something of the sort, I suggest to contact developers of that instead.
