### ISSUE TITLE
Check for MAME ROM dependencies

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#365]
Hi

the mame runners work great, but found an exception, games where there is no roms just chd's like xiistag won't run with the current runner. 

could the rom selector made to accept keyboard input so that you could specify just the rom name?

**Comment by strycore** [comment]
I pointed the ROM to xiistag.chd and it worked great! what files are you trying to load?

**Comment by telanus** [comment]
I've tried it that way, but mame exits and according to the log it can't find the bios file:

`coh-3002t.353 NOT FOUND (tried in xiistag taitogn xiistag)`
`upd78081.655 NOT FOUND (NO GOOD DUMP KNOWN) (tried in xiistag taitogn xiistag)`
`flash.u30 NOT FOUND (tried in xiistag taitogn xiistag)`
`Fatal error: Required files are missing, the machine cannot be run.`

Just passing the rom name to mame makes it work, as I've setup all my paths and stuff

**Comment by strycore** [comment]
That's normal and not related to the chd, some MAME roms require another rom to run, in most cases a BIOS. In that case, taitogn is required to run the game, which I had downloaded after the CHD since EmuParadise will tell you when a game has dependencies.

MAME support will get better than it currently is but it requires parsing data from MAME itself (some 200MB XML file)

**Comment by telanus** [comment]
If the game does not need a bios MAME will complain that it does not understand the chd being passed to it:

https://media.discordapp.net/attachments/288951868082749441/424955869797679105/Screenshot_at_2018-03-18_17-40-23.png?width=650&height=481

https://cdn.discordapp.com/attachments/288951868082749441/424955872033243155/Screenshot_at_2018-03-18_17-40-28.png

https://cdn.discordapp.com/attachments/288951868082749441/424955944645033985/Screenshot_at_2018-03-18_17-40-35.png

**Comment by Zeioth** [comment]
@telanus , that has nothing to do with Lutris, it's a Mame issue. My recomendation is: Always run your ROM from the original zip file.

**STATUS:** Solved, please close it.

**Comment by telanus** [comment]
@Zeioth it's not a mame issue, it work from the terminal. The problem is that lutris sends mame the wrong info for chd based sets.

**Comment by Zeioth** [comment]
@telanus could you check if this issue was fixed please?

**Comment by strycore** [comment]
that's not fixed yet, there is code implemented to check mame rom dependencies
