### ISSUE TITLE
Lutris 0.5.8.3 crashes

### ISSUE THREAD

**Issue by Real-Otternaut** [lutris/lutris#3651]
On Lutris when I choose Sources > Lutris > Install-Program from community > search for "grand theft auto" > and choose the first GTA  > click install > cancel install-wizard > click install again > Lutris crashes reproducible.

Pop OS 21.04, Lutris 0.5.8.3

**Comment by nzbtuxnews** [comment]
Same with 0.5.8.4 trying to install Sim City 4 Deluxe on a brand new Linux Mint 20.2 setup.  I cannot install anything.  Sometimes, when I hit the install button, lutris just quits.  Nothing in the terminal either.

**Comment by tannisroot** [comment]
Logs

**Comment by tannisroot** [comment]
closing in favor of https://github.com/lutris/lutris/issues/3656
