### ISSUE TITLE
Wrong sign in implementation

### ISSUE THREAD

**Issue by iMonZ** [lutris/lutris#3658]
Login Should be redirected to the browser instead the lutris own browser.
For security reasons (When you log in over example: Google or Apple) And for convenient reasons like when you use a password manager.

**Comment by iMonZ** [comment]
Anything new here? This is actually pretty important for Lutris!

**Comment by strycore** [comment]
we can't get the credentials if we're using a system browser

**Comment by iMonZ** [comment]
> we can't get the credentials if we're using a system browser

What do you mean with that?

**Comment by iMonZ** [comment]
There is definitely a possible way to do that.
Could you please reopen the issue?

**Comment by strycore** [comment]
No, you don't even understand the basics of how lutris works and you are making unreasonable requests. Don't wear my patience out.
