### ISSUE TITLE
GOG galaxy 2.0 hangs on the login screen.

### ISSUE THREAD

**Issue by Bitwolfies** [lutris/lutris#3661]
Installed through the official script, just hangs on this after install, im unable to sign in. 
![image](https://user-images.githubusercontent.com/65789901/130303994-d60bc36d-6f84-42fd-b6e5-b0b9739bffff.png)

**Comment by drwarner** [comment]
Don't think this is a lutris issue FWIW; it's happening on windows native clients. GoG has been having some kind of service outage they haven't been entirely transparent about communicating (and that error message is not super helpful)

**Comment by Bitwolfies** [comment]
Why do things always have to go out at the times I’m migrating/testing so it looks like the fault of the app?

If this is true I’ll close the issue, but for the moment I cannot confirm if it’s gogs fault alone, thanks for the information however.

**Comment by Bitwolfies** [comment]
I can get to the login screen using crossover, this is 100% a lutris issue.
