### ISSUE TITLE
Changes in runner configuration (Wine version) not reflected in the log

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3674]
- I change Wine version from e.g. "System 6.0.1" to "lutris-fshack-..." for one game. 
- I launch the game (which fails to launch and stops immediately)  
- I then open the log using the context menu. The log still begins with `Running gamemoderun /usr/bin/wine ...` which is the wrong Wine. 
- I confirm that the launcher settings were saved properly by opening and inspecting them again. 

At that point it's very confusing to look at the log: Did the settings not get written properly (they seem to be saved just fine), or not read properly? Am I looking at the log for the very latest launch attempt, or did the context menu present me an old log? How do I figure that out? I can't find any time stamps in the log window. 

A time stamp in the log window title would be helpful as a first step. A list of all recent logs in a sidebar would be even better, but maybe too much effort. 

Note that at some undetermined point later (I.e. after some later launch attempt) the log starts reflecting use of the correct wine version, so there's nothing missing in that regard. Not sure what triggers it.

**Comment by tannisroot** [comment]
provide logs
