### ISSUE TITLE
Add Options: 'wine-wayland' & 'disable runtime-updates'

### ISSUE THREAD

**Issue by slynobody** [lutris/lutris#3675]
Hi,

a request for 2 new options:

    integrate an option to disable the runtime-updates
    each time the client starts a series of tries to update runtimes are performed. you can stop this by pressing escape (i stumbled upon this, there is no text about it).
    if you have no keyboard around (f.e. lutris runnig through kodi etc.) and/or are offline the time until the client starts as well as each game chosen started (until the update-procedure accepts a failure or has reached a time-limit, i did not take a look) is a serious time-waste. you minimally should integrate an option to disable the update-checks if you force your users to tolerate this checks each single time the client starts or a game is chosen.

    integrate wine-wayland
    name says it all, seems to be one way to the long-term-future of wine. should be integrated.
btw: i heard gallium9 seems to be wayland-enhanced in the future, too.

Thank you.

**Comment by tannisroot** [comment]
Wine-Wayland is an unofficial fork and it's not mature enough yet, if it's ever going to be.
