### ISSUE TITLE
Crash when a game entry has no installers

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3679]
Trying to install Psychonauts 2 from internal search (it does show up in the search) doesn't work
https://lutris.net/games/psychonauts-2/
```
WARNING  2021-08-28 15:41:53,460 [lutriswindow.on_game_selection_changed:778]:No game found. Replacing with placeholder {'id': 'psychonauts-2', 'appid': 'psychonauts-2', 'name': 'Psychonauts 2', 'slug': 'psychonauts-2', 'service': 'lutris'}
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 495, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3.9/site-packages/lutris/services/lutris.py", line 119, in install
    installers = fetch_script(slug)
  File "/usr/lib/python3.9/site-packages/lutris/installer/__init__.py", line 16, in fetch_script
    raise ValueError("No game_slug provided. Can't query an installer")
ValueError: No game_slug provided. Can't query an installer
```

**Comment by strycore** [comment]
this is one more reason to remove this search, Psychonauts 2 is installable from Steam or GOG without the need of an installer on the website. People keep searching for stuff on the website that doesn't exist and isn't needed.

**Comment by tannisroot** [comment]
But there are quite a few GOG games out there that need more than a basic installer. For example, Mirror's Edge needs PhysX library for proper object physics in-game.
