### ISSUE TITLE
Can't uninstall game through Lutris

### ISSUE THREAD

**Issue by pm4rcin** [lutris/lutris#3684]
Hi, when I try to remove the [Gothic](https://lutris.net/games/gothic/) (gog version) via lutris it says that "the folder /home/user/Games/gog/gothic is used by other games and will be kept" but it is the only game installed and has it's own prefix. So I have to remove folder by hand... When I tried uninstalling the [Gothic 2 Gold](https://lutris.net/games/gothic-ii-gold-edition/) also gog version it was removed without problems.
OS: EndeavourOS 5.13.13-arch1-1
Lutris: 0.5.8.4

**Comment by tannisroot** [comment]
I cannot reproduce this issue.

**Comment by strycore** [comment]
Not really a problem. What is a problem is when lutris deletes stuff that it shouldn't
