### ISSUE TITLE
Run game from command line and passing command line arguments

### ISSUE THREAD

**Issue by RushingAlien** [lutris/lutris#3686]
Hello, I would like to be able to run games from command line and also passing the command line arguments. This will allow games be launched via lutris through a `.desktop` entry. As of right now, putting this line into a `.desktop`
``` 
Exec=lutris lutris:rungameid/001
```
does not work. I believe this feature will bring greater integration of lutris (Such as easy configuration) into peoples' desktop. And will help some games that *require* system integration, such as Roblox. Roblox uses a browser to browse games and launches the game using a url protocol.

Other projects such as bottles offers such features and can be put into a `.desktop` file
```
Exec=bottle -b [bottle name] -e [/path/to/executable]
```
Thanks for the **great** project, cheers!👍️

**Comment by tannisroot** [comment]
Desktop shortcuts work for me just fine. If they don't work for you, please open a new issue and provide clear reproduction steps.

**Comment by RushingAlien** [comment]
I'm sorry but this does not solve the issue. Lutris creates desktop shortcuts entries just like how winemenubuilder creates one (Lutris uses winemenubuilder?). Therefore the desktop icons they create are static and does not respond to lutris's configuration change. The exec line looks something like this as of current implementation
```
Exec=env WINEPREFIX=/path/to/wineprefix WINE=/path/to/wine/binary WINEFSYNC=1 wine [relevant argument]
```
Therefore if changes are made inside lutris for a given game/prefix, such as changing runners, enabling disabling esync/fsync, adding arguments, adding environment variables, using system's/lutris' runtime, etc. The desktop icon/shortcut will not reflect the changes unless you manually edit the `.desktop` file.

I shall open a new issue with more clarification and reproduction steps.

**Comment by tannisroot** [comment]
No Lutris has the ability to create proper icons that execute Lutris. The ones made by winemenubuilders are a result of a bug.
To make a proper shortcut, right click on the game and select "Create desktop shortcut" or application menu shortcut.

**Comment by RushingAlien** [comment]
My bad. Thanks for the help. I will be more careful before posting an issue next time.

**Comment by tannisroot** [comment]
np

**Comment by oblitum** [comment]
Hello. I think I'm still looking for something like this. I don't run games in lutris, I run game platforms or emulators in it, for example, cemu or the epic games store. When running these application with wine, I can for example, pass as command line parameter an specific game path so that the emulator launches the game right away, this is specially useful for integration with Steam. I have no idea how I could pass a game path to a lutris installed emulator. Any help?
