### ISSUE TITLE
Epic Authentication API Change, now require 'country' param

### ISSUE THREAD

**Issue by rezzafr33** [lutris/lutris#3688]
Due to Auth API changes, EGS service can't login.

```bash
$ lutris -d
...
DEBUG    2021-09-07 08:56:34,735 [base.login:251]:Connecting to Epic Games Store
DEBUG    2021-09-07 08:57:54,364 [egs.login_callback:183]:Login to EGS successful
DEBUG    2021-09-07 08:57:54,364 [egs.login_callback:184]:b'{"redirectUrl":"https://epicgames.com/account/personal","sid":"[REDACTED]"}'
ERROR    2021-09-07 08:57:56,149 [egs.login_callback:203]:Failed to connec to EGS (Status 400): {'errorCode': 'errors.com.epicgames.accountportal.parameter_required', 'message': 'Parameter "country" is required', 'correlationId': '[REDACTED]'}
```
I put this 
```py
_session.cookies['EPIC_COUNTRY'] = 'US'
```
after this line https://github.com/lutris/lutris/blob/a17b6fbf542404a3fcdf2dc55102fc1fb6f428e2/lutris/services/egs.py#L194 
relogin, then it works again.

related: https://github.com/derrod/legendary/commit/d3026672d1d210de49f2b757f927d74eba651106

**Comment by AlexanderRavenheart** [comment]
The solution should use the user's country based on the configured system regional settings or allow it to be specified as a Lutris configuration option.

The reason being that this value may impact what is available to a user or may lead to bans/temporary restrictions if EGS implements checks of this in relation to user's IP or some other draconian DRM/region-lock system.

**Comment by rezzafr33** [comment]
> The solution should use the user's country based on the configured system regional settings or allow it to be specified as a Lutris configuration option.
> 
> The reason being that this value may impact what is available to a user or may lead to bans/temporary restrictions if EGS implements checks of this in relation to user's IP or some other draconian DRM/region-lock system.

**Comment by rezzafr33** [comment]
I agree, my comment was not suggestion, more like hotfix or prove of concept.
Also lutris hardcode the country to US at this line 
https://github.com/lutris/lutris/blob/a17b6fbf542404a3fcdf2dc55102fc1fb6f428e2/lutris/services/egs.py#L257

**Comment by smichel17** [comment]
legendary gets the country code here:

https://github.com/derrod/legendary/blob/d3026672d1d210de49f2b757f927d74eba651106/legendary/core.py#L68-L79

```python
        self.language_code, self.country_code = ('en', 'US')

        if locale := self.lgd.config.get('Legendary', 'locale', fallback=getdefaultlocale()[0]):
            try:
                self.language_code, self.country_code = locale.split('-' if '-' in locale else '_')
                self.log.debug(f'Set locale to {self.language_code}-{self.country_code}')
                # adjust egs api language as well
                self.egs.language_code, self.egs.country_code = self.language_code, self.country_code
            except Exception as e:
                self.log.warning(f'Getting locale failed: {e!r}, falling back to using en-US.')
        else:
            self.log.warning(f'Could not determine locale, falling back to en-US')
```

**Comment by rezzafr33** [comment]
I can't reproduce with current lutris-git (b9b8bcbf), should I close this issue?
