### ISSUE TITLE
I can't install League of Legends in my lutris, D3D11 error

### ISSUE THREAD

**Issue by dragonjvps** [lutris/lutris#3692]
I can't install League of Legends in my lutris, I get an error ¨04c0:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 0xa1ed40". Help me I use manjaro KDE

![image](https://user-images.githubusercontent.com/70447838/132934411-6998ec9f-1738-4397-b5c4-b73a89d41139.png)

**Comment by EduardTheFirst** [comment]
winetricks dxvk
try that

**Comment by EduardTheFirst** [comment]
and do you have a log for this ?
please upload it

**Comment by dragonjvps** [comment]
It's just close the launcher and wait
