### ISSUE TITLE
Allow user to set cache directory in settings and change the language around it

### ISSUE THREAD

**Issue by Slater91** [lutris/lutris#3695]
I have just found myself in the rather unpleasant situation of having my /home partition completely full due to Lutris saving the installer file in /home/user/.cache/lutris. This led to the installation process failing and to me having to download 30+ GB of files _again_.
Now, there is indeed a "cache" option, but it is rather difficult to understand what it does if one doesn't click on it and read the text, which is rather poor UX. I only found it out _after_ the download failed, as it was _not_ clear from the language that this would be the place where the downloaded files would be saved. I also noticed that that option is nowhere to be fond in the general "settings" page, so one can't set it as a general rule.
I would therefore suggest moving the option there or at least making it available there as a general, application-wide option that can be then overridden with the button in the installation phase. I would also suggest renaming the feature from "cache", which has little meaning to most users in this context, to "set installer download path", "save installer to" or similar verbiage, so that the feature is clearer in its scope and definition.

**Comment by teras** [comment]
Not only this. In my system due to broken download, Lucris didn't understand that files needed to be re-downloaded. By manually changing the cache location, tings started to operate correctly again. So, before changing cache location, first I went to configuration, even opened the "advanced" options, but there was nothing here. So I came here for a bug report and found this one. :smile:

**Comment by tannisroot** [comment]
We should add a cache purge option too.

**Comment by strycore** [comment]
I also suspect that with the default cache location some installs are failing on the Steam Deck. 
I couldn't install 9 Years of Shadows from GOG until I moved the cache to the SD card.

**Comment by pcoder59** [comment]
Why is this issue still open if we don't want an option in settings? What exactly does this issue require?

**Comment by strycore** [comment]
I've added a way to specify the cache path in the settings.
