### ISSUE TITLE
Lutris is not working

### ISSUE THREAD

**Issue by NoobKomura** [lutris/lutris#3696]
I have been using lutris since I installed again linux mint, I got a problem with the nvidia drivers so I dowgnrade  them to 460.91.03 because with the new drivers the games didn run well.
After that I could keep using Lutris but since yesterday Lutris won run again, so I tried to uninstall lutris and Battlenet but it keeps saying that the .exe of battlenet is missing on the lutris installer.

**Comment by EduardTheFirst** [comment]
Hey so whats doesn't work ?
lutris or battlenet.exe ?

**Comment by NoobKomura** [comment]
I tried to run battlenet, Origin and Ubisoft Connect but when the installation is over and I try to run any of them it says that the .exe is not installed in the last few times I have tried. Before I uninstalled Lutris I could open them but then before starting any of the aplications, it just stop working and get closed.

**Comment by EduardTheFirst** [comment]
can you contact me on discord ?.
300NARKO#5660

**Comment by NoobKomura** [comment]
Solved, I uninstalled wine and Lutris then  reinstalled both of them and now they work again.
