### ISSUE TITLE
Unable to launch Flatpaks

### ISSUE THREAD

**Issue by Victor239** [lutris/lutris#3699]
Currently I can launch Minigalaxy via the command line using `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=minigalaxy io.github.sharkwouter.Minigalaxy`. I can't figure out how to launch this in Lutris, putting different bits in the Executable or Arguments boxes when trying to add it as a new game.

**Comment by tannisroot** [comment]
We don't really manage the flatpaks, please ask for support here https://github.com/flathub/net.lutris.Lutris

**Comment by Victor239** [comment]
No, this is nothing to do with the Lutris Flatpak. It's that I can't launch Flatpaks from Lutris itself.

**Comment by AlexanderRavenheart** [comment]
I have a PR in progress for this.

**Comment by bayazidbh** [comment]
Hi, one of the devs on the Flatpak Lutris mentioned that for Flatpak Runner (which I requested as a workaround for dealing with [Flatpak Lutris not being able to mount/run the AppImage runners](https://github.com/flathub/net.lutris.Lutris/issues/198)), it should be handled by the upstream Lutris development, as the person believe that Flatpak apps shouldn't patch upstream's releases?

I think something that would work like detecting Flatpak Steam would be great, and apparently Lutris is already able to work with Flatpak plugins like mangohud.

I would be happy if I could use Lutris on an immutable OS like Endless OS, Fedora Silverblue/Kinoite, and soon SteamOS. I wouldn't mind beta testing this, either. Thanks!

**Comment by bayazidbh** [comment]
Hi, it seems that Lutris on Flatpak can now [run/spawn other flatpak apps](https://github.com/flathub/net.lutris.Lutris/issues/198#issuecomment-1502749083)?

I saw that you can pass in args and such as well. Would it be possible to create a toggle inside a runner's setting to use its flatpak version of the runner instead? For example, we can already run Yuzu with the flatpak runner, so toggling some sort of "use Flatpak runner" inside the runner setting for Yuzu would just change it to doing flatpak spawn yuzu and passing the game ROM (and other settings) as arguments.

I simply want a way to separate my games between runner/emulators.

**Comment by strycore** [comment]
Lutris is now able to launch Flatpaks, even from Flatpak itself.
