### ISSUE TITLE
[command-line] errors and ommisions

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#370]
did a lutris -l and it crashed:

`Traceback (most recent call last):`
`  File "./bin/lutris", line 104, in <module>`
    `game['directory'] or '-'`
`TypeError: non-empty format string passed to object.__format__`

lutris -s gives `lutris: error: no such option: -s` the readme states: -s, --list-steam      List Steam (Windows) games

**Comment by strycore** [comment]
Thanks, I've also updated the README with the new command line options
