### ISSUE TITLE
Dolphin Change Config File Location

### ISSUE THREAD

**Issue by TheWranger** [lutris/lutris#3700]
Similar to how Libretro has the 'Config file' option to set a custom config file location, Dolphin should have this too.
Can be done easily, as seen in https://dolphin-emu.org/docs/guides/controlling-global-user-directory/
```
On Linux and macOS, the Global User Directory's location can be changed with the command:

/path/to/dolphin/build/dolphin-emu -u /path/to/user/directory
```

**Comment by strycore** [comment]
I added the option (make sure Advanced Options is checked)
