### ISSUE TITLE
Lutris game won't start

### ISSUE THREAD

**Issue by Fares-Basousy** [lutris/lutris#3701]
![Screenshot from 2021-09-17 00-07-29](https://user-images.githubusercontent.com/80477030/133692059-53be56ae-b7a7-4b37-825e-78c1e7daed24.png)
lutris launches the game and i can see it from the system monitor but it won't start, in the system monitor it uses only  8 Mgb of ram and almost 0.08% of processor

**Comment by EduardTheFirst** [comment]
have you installed microsoft fonts?
