### ISSUE TITLE
Unable to run installers or to change the runner used for GOG

### ISSUE THREAD

**Issue by canepan** [lutris/lutris#3706]
Hi, I am new to Lutris, and I tried to install it on my Debian 11.
I first tried with the version provided with the distribution (0.5.8.3), then with the version from http://download.opensuse.org/repositories/home:/strycore/Debian_11/ (0.5.8.4), but the behavior is the same.
In particular, all the installation I tried (Gothic, the latest Larry and World of Warcraft) appear to run, but when the installation begins (after the download), I see this on the console where I launched Lutris:
```
------------------------------------------------------
warning: /home/XXX/.local/share/lutris/runners/wine/lutris-fshack-6.14-3-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "wine: Unhandled illegal instruction at address 004066B7 (thread 00bc), starting debugger...
wine: could not load kernel32.dll, status c0000135"
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All children have exited.
Exit with returncode 256
```

I tried to select different runners, even the system one (which is 32 bit), but those lines stay the same.
I managed to install a game only by:
* removing `/home/XXX/.local/share/lutris/runners/wine/lutris-fshack-6.14-3-x86_64`
* creating a symbolic link from /usr to `/home/XXX/.local/share/lutris/runners/wine/lutris-fshack-6.14-3-x86_64`

Is there a way to make the selection for the runner actually use it?
I tried both with the defaults and enabling all the options to use the system libraries/to not use the Lutris libraries, with no changes

Thank you and please forgive me if I am missing something basic: I couldn't wind any help on the web and I am experienced in Linux but not in Lutris.

Thank you.

Nicola

**Comment by EduardTheFirst** [comment]
> wine: could not load kernel32.dll, status c0000135"

wine: could not load kernel32.dll, status c0000135

That has to do with your wine prefix. Delete the standard prefix (~/.wine) or create a new custom one with:

mkdir -p ~/myapp/prefix
export WINEPREFIX=$HOME/myapp/prefix 
export WINEARCH=win32 
export WINEPATH=$HOME/myapp 
wineboot --init
winetricks

**Comment by canepan** [comment]
Thanks for the procedure to create the prefix, but how can I then make sure lutris (always) uses it?
Do I have to manually set the environment variables in my `.bashrc`?
And why does it work if I do the symbolic link trick?

**Comment by AlexanderRavenheart** [comment]
Is this issue still present in Lutris 0.5.9.1?

**Comment by tannisroot** [comment]
I can't reproduce it
