### ISSUE TITLE
Steam font is rectangles

### ISSUE THREAD

**Issue by MrBrodieSkyland** [lutris/lutris#3708]
I just got Steam but when I open it, it shows a bunch of rectangles for the font what should I do?
![Steam](https://user-images.githubusercontent.com/84057971/135363262-390fb637-9e48-48b3-be0a-944a6a179471.png)

**Comment by LutraLutris** [comment]
What flavor are you running?

**Comment by LutraLutris** [comment]
I would think that all you need are the right font packages. Try with ttf-ms-win10 and ttf-liberation.
