### ISSUE TITLE
Enabling Gallium Nine Breaks Prefix

### ISSUE THREAD

**Issue by EmmettCarpenter** [lutris/lutris#3709]
Issue:
Enabling Gallium Nine makes games instantly close on launch with no errors. If it is then disabled the problem still remains.

To reproduce:
Install wine-nine package, then toggle the Gallium Nine setting in the prefix's runner options and attempt to start a dx9 game. 
Disable Gallium Nine then attempt to start the same game without DXVK enabled and the problem will persist. 

System Info:
Manjaro Linux (Arch)
CPU: Intel i7 8565U
GPU: Intel UHD 620 (integrated with the cpu)

**Comment by strycore** [comment]
Gallium Nine is no longer an option in 0.5.9.
