### ISSUE TITLE
[icon view] double entries

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#371]
I did a git pull about an hour ago and it worked, did a git pull after seeing #355 being fixed, now when I startup it correctly, but now it'll load the game list and then (on my machine) starting at q double evry installed game, thus you end up with two of eery icon

**Comment by strycore** [comment]
Ok, I have no idea how you did that o_o

**Comment by telanus** [comment]
went and had a look seems the "bug" got introduced here: https://github.com/lutris/lutris/commit/dd9d2bb0b093527c6b8e21062c90b2af92f6ad9e

it's the first one that add double entries

**Comment by strycore** [comment]
Can you try with the latest commit I just pushed? It may have fixed that issue.

**Comment by telanus** [comment]
@strycore yip is fixed :dancers:
