### ISSUE TITLE
Lutris seems to have deleted every file in home directory beginning with .

### ISSUE THREAD

**Issue by cpw** [lutris/lutris#3717]
Hi,
So I have no idea how to reproduce this, nor would I like to, but it seems that during an update to roblox, lutris somehow managed to get a bit confused, tried to copy roblox into itself, and then proceeded to delete _every_ directory beginning with `.` in the users' home directory. Yeah, this isn't good, it's trashed every other app the user has.

The user concerned is my daughter and to say she's a bit upset is an understatement.

I think it might have been trying to apply some sort of rollback to roblox?

I've attached the syslog, which shows something happening in the lutris UI, followed by a large number of "I can't find files" errors over the subsequent minutes, as what I'm guessing is lutris or roblox is annihilating all of the files beginning with . in the users' home directory.

[borkedsys.log](https://github.com/lutris/lutris/files/7272608/borkedsys.log)

**Comment by tannisroot** [comment]
How did you try to update Roblox?

**Comment by strycore** [comment]
lutris cannot do this unless the script is broken and does nasty stuff in which case it shouldn't have been published

**Comment by mrboxly** [comment]
Yes just happen me too right now!, lutris just delete all my file on partition that selected.
