### ISSUE TITLE
[precompiled WINE] installation is stuck at prefixcreate

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#372]
Lutris hangs now on every wine installation

there are two wine windows open with no content

probably the ask to install winemono window, however wine should work(since my depends havent changed much:  https://chakralinux.org/ccr/pkgbuild_view.php?p=lutris-git)

also there aren't any errror messages:

![screenshot_20160929_233002](https://cloud.githubusercontent.com/assets/3780774/18973468/dce27b4a-869d-11e6-989e-94b6a10bd56a.png)

**Comment by strycore** [comment]
I have fixed an issue that was blocking monitoring of Wine processes, can you confirm it works now? (I installed AirMech without any issue)

**Comment by sixsixfive** [comment]
yes it works now :)
