### ISSUE TITLE
Stuck on "Lutris is Starting" during initial application start

### ISSUE THREAD

**Issue by ryangwsimmons** [lutris/lutris#3720]
Hello,

The title basically describes the issue. I'm trying to run Lutris, and I am currently unable to start the application. I tried running `lutris --submit-issue`, however I encountered the same issue I had running that command as I did starting Lutris normally. The command did not output any file.

My system specs are as follows:
- Distro: Pop_OS! 21.04
- DE: GNOME 3.38.5
- WM: Mutter
- Graphics: it's a laptop with hybrid graphics, the integrated graphics is Intel UHD Graphics 620, the dedicated card is an NVIDIA GeForce MX150.

Please let me know if there's any other info you need regarding my system specs, etc. I'll be happy to provide.

[Here is the output of `lutris -d`](https://paste.ubuntu.com/p/pC4MnTY9KF/)

**Comment by ryangwsimmons** [comment]
> Disable ipv6 and try again. This should fix it.

I disabled IPv6 as described in #3946, this made no difference.

**Comment by Dhamma-valence** [comment]
I'm having the exact same issue, and have also disabled ipv6 with sysctl but to no avail.

**Comment by strycore** [comment]
if you have mangohud enabled globally, try disabling it and relaunch lutris

**Comment by strycore** [comment]
The original issue seemed to have been caused by some kind of network hiccup (github and digital ocean connections failing).

Since this issue was posted, we've made the initialization code more robust so it shouldn't stay stuck on the "Lutris is starting" window.
