### ISSUE TITLE
Question: what state is this uninstalled game in?

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#3721]
I'm having trouble figuring out in the UI what state Lutris is trying to tell me a game is in. 

- Before it's installed its image is grayed out (transparent) in the Sources section. They lack a bit too much contrast for me personally, but the meaning is clear enough: Greyed out = uninstalled. 
- It was then installed, at which point it appeared in Library → Games, and was no longer grayed out. Game is installed → not grayed out, and shows up in Games Library (which I interpret as "added automatically to the library"). 
- Then I uninstall it using the context menu. It uninstalled successfully, and is once again grayed out. But it's still in my Games Library and I cannot remove it (can't find any such menu option anywhere). 

To me this makes it hard to form a mental model: On the one hand, the "+" button suggests to me that adding a game is separate from installing a game, and that I'm allowed to add — and, by extension, manage — games manually. On the other hand, I can't remove games that have been added but aren't installed, suggesting that I'm not expected to manage their "added" state manually. 

This means I can't figure out what the collection of games called the Games Library represents. Games that I want to be there? No — can't remove them. Games that are installed? Not that either. 

Are uninstalled games in the Games Library in some special UI state? 

(I'm leaving "hide game" out of it since it would get even more confusing. I'm assuming "adding" and "hiding" are not inverse of each other, considering there's also the action "unhide")

**Comment by tannisroot** [comment]
The game got added to your Lutris library. The games in the library may either be installed or uninstalled, normal or grey-ed out. If you don't want to see them, activate "Installed games only".

**Comment by anohren** [comment]
> It's like your collection

Thanks. I think you might have missed the part where it was impossible to remove games, hence couldn't possibly be my collection, since I didn't have control of it. 

But I think later versions have removed the ambiguity by introducing an explicit Remove option from the context menu
