### ISSUE TITLE
Gamescope failure

### ISSUE THREAD

**Issue by jarrard** [lutris/lutris#3729]
Spot the issue, I can't. Just enabled gamescope with latest version but it seems there is invalid syntax. 

Started initial process 34578 from gamescope -f -- gamemoderun /home/theriddick/.local/share/lutris/runners/wine/lutris-ge-6.18-1-x86_64/bin/wine /mnt/GamesNVMe/Games/Encased A Sci-Fi Post-Apocalyptic RPG/Encased.exe
Start monitoring process.
gamescope: invalid option -- ' '
See --help for a list of options.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256

**Comment by JoshStrobl** [comment]
The issue is likely the unescaped "Encased A Sci-Fi Post-Apocalyptic RPG".

**Comment by cirk2** [comment]
It's not limited to paths with spaces:
```
Started initial process 117687 from gamescope -f -- gamemoderun /usr/bin/strangle 100 /home/felix/.local/share/lutris/runners/wine/lutris-ge-6.19-1-x86_64/bin/wine /home/felix/Storage/Games/warhammer-online-return-of-reckoning/drive_c/WarhammerOnline-ReturnofReckoning/RoRLauncher.exe
Start monitoring process.
gamescope: invalid option -- ' '
See --help for a list of options.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```
The command is accepted when I use it in a terminal with zsh, so something has to be different between the command as shown and the command as run.
