### ISSUE TITLE
Can't get banner and icon for games with tm in its title

### ISSUE THREAD

**Issue by Lrss** [lutris/lutris#3730]
It looks like if the games titles contains a Trademark symbol ™ it is parsed differently on the back-end providing banners and icons. Lutris outputs the following for the games "Batman™: Arkham Origins" and "Dishonored®: Death of the Outsider™" 
```
DEBUG    2021-10-11 08:56:31,827 [http.get:73]:GET https://lutris.net/games/icon/batman-arkham-origins.png
DEBUG    2021-10-11 08:56:31,834 [http.get:73]:GET https://lutris.net/games/icon/dishonored-death-of-the-outsider.png
ERROR    2021-10-11 08:56:31,874 [http.download_file:161]:Failed to get url https://lutris.net/games/icon/batman-arkham-origins.png: Request to https://lutris.net/games/icon/batman-arkham-origins.png failed: HTTP Error 404: Not Found
ERROR    2021-10-11 08:56:31,877 [http.download_file:161]:Failed to get url https://lutris.net/games/icon/dishonored-death-of-the-outsider.png: Request to https://lutris.net/games/icon/dishonored-death-of-the-outsider.png failed: HTTP Error 404: Not Found
DEBUG    2021-10-11 08:56:36,791 [http.get:73]:GET https://lutris.net/games/banner/batman-arkham-origins.jpg
DEBUG    2021-10-11 08:56:36,793 [http.get:73]:GET https://lutris.net/games/banner/dishonored-death-of-the-outsider.jpg
ERROR    2021-10-11 08:56:36,840 [http.download_file:161]:Failed to get url https://lutris.net/games/banner/batman-arkham-origins.jpg: Request to https://lutris.net/games/banner/batman-arkham-origins.jpg failed: HTTP Error 404: Not Found
ERROR    2021-10-11 08:56:36,841 [http.download_file:161]:Failed to get url https://lutris.net/games/banner/dishonored-death-of-the-outsider.jpg: Request to https://lutris.net/games/banner/dishonored-death-of-the-outsider.jpg failed: HTTP Error 404: Not Found
```
I can see that I am able to find the Dishonored [banner](https://lutris.net/games/banner/dishonored-death-of-the-outsidertm.jpg) and [icon](https://lutris.net/games/icon/dishonored-death-of-the-outsidertm.png) by adding a tm to the url.

It only occurs when displayed in the 'Library'-section. It loads icons and banners fine for game in 'Sources'-section (Tested for GOG and Steam).

**Comment by Lrss** [comment]
The "View on Lutris.net" button doesn't work for those games either.
| Actual url | What "View on Lutris.net" opens |
| ------- | ---------------- |
| https://lutris.net/games/batmantm-arkham-origins/ | https://lutris.net/games/batman-arkham-origins/ |
| https://lutris.net/games/dishonored-death-of-the-outsidertm/ | https://lutris.net/games/dishonored-death-of-the-outsider/ |

**Comment by strycore** [comment]
I've merged those 2 games, banners will download with either ID with the development version
