### ISSUE TITLE
Can't install, broken python syntax

### ISSUE THREAD

**Issue by Sanaki** [lutris/lutris#3734]
When trying to install via apt or via the release deb on Linux Mint 19.3 with python 3.6.9 at /usr/bin/python3, and python 3.8.12 for `python3` at a user level. Tried bumping system to 3.8 temporarily as well, no change. Can't bump it permanently without breaking my DE severely. Tried removal and reinstall as well, though unsurprisingly that did nothing.
```
Setting up lutris (0.5.9~ubuntu18.04.1) ...
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243
    if library_config := self.get_library_config():
                       ^
SyntaxError: invalid syntax

dpkg: error processing package lutris (--configure):
 installed lutris package post-installation script subprocess returned error exit status 1
```
As might be expected, attempting to run it with the package broken is equally fruitless.
```
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 39, in <module>
    from lutris.game import Game
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 23, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 9, in <module>
    from lutris.runners.commands.wine import (  # noqa: F401 pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/lutris/runners/commands/wine.py", line 16, in <module>
    from lutris.util.wine.prefix import WinePrefixManager
  File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 7, in <module>
    from lutris.util.wine.registry import WineRegistry
  File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 9, in <module>
    from lutris.util.wine.wine import WINE_DEFAULT_ARCH
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 9, in <module>
    from lutris.runners.steam import steam
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243
    if library_config := self.get_library_config():
                       ^
SyntaxError: invalid syntax
```
Any advice would be appreciated. For now, I've reverted to v0.5.8.4 and held the package.

**Comment by mihailim** [comment]
Oh, turns out there's already a PR for this dated 10 days ago. D'oh. https://github.com/lutris/lutris/pull/3714

**Comment by RafaelJVicente** [comment]
Same error in Ubuntu 18 (Python 3.6.9), [Walrus operator](https://docs.python.org/3/reference/expressions.html#assignment-expressions) is only available from Python 3.8.

**Comment by iPoe** [comment]
@mihailim Thx, u are a god 🦊

**Comment by mxdpeep** [comment]
> If the above steps are too much for you, the alternative is to hold the old version: `apt remove lutris` Download and install the deb here: https://github.com/lutris/lutris/releases/tag/v0.5.8.4 `apt hold lutris`

`sudo apt-mark hold lutris`

**Comment by Sanaki** [comment]
He asked specifically about Mint, which supports the mentioned syntax as-is. For other apt-based distros, yes, the one you specified is the way to go.

**Comment by Eric1212** [comment]
I think i will have to reopen this ticket as 0.5.9.1 does keep the error.

```
dpkg -i /home/eric/Téléchargements/lutris_0.5.9-1_all.deb 
(Lecture de la base de données... 462590 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../lutris_0.5.9-1_all.deb ...
Dépaquetage de lutris (0.5.9-1) sur (0.5.9-1) ...
Paramétrage de lutris (0.5.9-1) ...
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243
    if library_config := self.get_library_config():
                       ^
SyntaxError: invalid syntax

dpkg: erreur de traitement du paquet lutris (--install) :
 installed lutris package post-installation script subprocess returned error exit status 1
```

I've downloaded from https://packages.debian.org/sid/all/lutris/download (AK 0.5.9.1)

**Comment by strycore** [comment]
this is not 0.5.9.1, this is 0.5.9-1. In Debian this means it's the first iteration of the package for the 0.5.9 release.
once we release 0.5.9.1, Debian will have 0.5.9.1-1
