### ISSUE TITLE
Ubuntu update fail

### ISSUE THREAD

**Issue by mxdpeep** [lutris/lutris#3738]
Setting up lutris (0.5.9~ubuntu18.04.1) ...
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243
    if library_config := self.get_library_config():
                       ^
SyntaxError: invalid syntax

**Comment by AetherUnbound** [comment]
Simlar to @etchevef I was able to get this installed using the following:
```python
library_config = self.get_library_config()
if library_config
    # rest of the code
```

This preserves the logic while making it installable in Python <3.9. I did get the same warning from dpkg.

**Comment by tannisroot** [comment]
Duplicate
