### ISSUE TITLE
wine wayland

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#3742]
I wonder if we can have one of these in lutris in the future.

Good question?

**Comment by tannisroot** [comment]
It's very WIP and unstable atm

**Comment by xrishox** [comment]
you guys have a bunch of random one off versions of wine for specific games with a million different configurations. I think that having a 1 off version of wine with native wayland support wouldn't really hurt anything and would be helpful for people who want to play around with it. 

https://gitlab.collabora.com/alf/wine/activity
this is the official collabora/wine branch with wayland support

https://github.com/varmd/wine-wayland/releases

this is a fork that is being worked on by a separate group with wayland support.

**Comment by tannisroot** [comment]
the answer is still the same

**Comment by tannisroot** [comment]
If you need you can compile your own experimental versions using our tools, they are all public and easy to use
