### ISSUE TITLE
Ryujinx not installing

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3743]
https://github.com/lutris/lutris/commit/bc4bc7ea05bb5236fa871456bc9bc04088c6487a introduced Ryujinx as a runner, but it seems the emu download isn't stable. Tried to install it tonight, and got this:

![Screenshot_20211014_211457](https://user-images.githubusercontent.com/19357986/137381840-06f72207-4772-45b2-9aaf-d5c0beaefa78.png)

trying the download link in firefox gives the following: {"message":"Artifact not found or access denied."}

We would need to self-house to emu, since the download is based on github, and the files get replaced every other day

@strycore @EduardTheFirst

**Comment by strycore** [comment]
Fixed in master, I changed the URL to a build we host. Ideally, this runner should use the runner API from your website to get download links.
