### ISSUE TITLE
Pretentious Bleeding Edge Python Features Break Older Python Installations

### ISSUE THREAD

**Issue by wolfmanx** [lutris/lutris#3744]
The "walrus operator" really serves no deeper purpose, but breaks the program miserably on ubuntu 18.04.

What do you get out of that feature in the context of a single-evaluation `if` statement?

https://github.com/lutris/lutris/blob/b9b8bcbf077cd7de440acfe6fcfa70caa01b8004/lutris/runners/steam.py#L243

instead of:

```
        library_config = self.get_library_config()
        if library_config:
```

Thanks for needlessly breaking my system upgrade?

**Comment by tannisroot** [comment]
Duplicate
