### ISSUE TITLE
Can't install any games

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3747]
How to repro:
1) Search for a game you don't already have installed in Community Installers
2) Click on the game, click Install
Result:
![Screenshot_20211014_211239](https://user-images.githubusercontent.com/10602045/137428173-5bbc5651-7db6-4596-b5ad-9bd0a56f4439.png)

Offending commit: faf5a77bb4cabebe7feb6c87e468b3a2ff190143
See: https://discord.com/channels/512538904872747018/538908173877379082/898308229489131540

**Comment by strycore** [comment]
Fixed in 0.5.9.1
