### ISSUE TITLE
Libretro Cores

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#375]
is it possible to use more than the few cores? also is it possible to use the cores you already installed?

**Comment by strycore** [comment]
You can download more cores from RetroArch itself, for the cores already installed, if they're not already detected then it must be an issue with config files.

If there are cores you think we should include, let me know :)

**Comment by telanus** [comment]
currently I've symlinked the cores under the runner to /usr/lib/libretro so lutris should be able to see all the cores I've downloaded. those cores that lutris comes with does get detected after another restart.

The Cores I use:

- fceumm_libretro.so
- picodrive_libretro.so
- handy_libretro.so
- mednafen_gba_libretro.so
- hatari_libretro.so
- mednafen_ngp_libretro.so
- mednafen_pce_fast_libretro.so
- mednafen_supergrafx_libretro.so
- mednafen_wswan_libretro.so
- ppsspp_libretro.so
- fuse_libretro.so
a few I use as it integrates with retroachievements, and ppsspp as it's faster on my system than the stand alone one

**Comment by telanus** [comment]
For the gba I'd use vbam_libretro.so as vba next has problems: http://libretro.com/forums/showthread.php?t=7110

**Comment by telanus** [comment]
added [this](http://pastebin.com/ngpXSzhc) seeing https://github.com/lutris/lutris/commit/e6b13e05b8bb7c69b266aea70cafad1f1f82d147

**Comment by strycore** [comment]
Thanks for the list, all those cores are now available :)
