### ISSUE TITLE
Lutris leaves 'lutris.log' file in user's home directory

### ISSUE THREAD

**Issue by danieljohnson2** [lutris/lutris#3750]
When you start a game, Lutris sends log output to stdout, but also to the file ~/lutris.log. It's rude to leave visible files at the root of the home directory; this is a place where the user keeps his own files. Lutris shouldn't pollute it with junk files by default, even if they are sometimes useful for troubleshooting.

It looks to me like this was caused by commit '449a00d39023125f2dc733f7b6808f84fd45de68' in the file 'lutris-wrapper'; previously this code had been commented out. Perhaps this is debug code that should have been commented out again after use, but was not.

The simplest fix might be to comment this code out again.

Alternatively, if this file it considered too useful to lose, it might be moved somewhere else; ~/.local/share/lutris/lutris.log might be better. Or just ~/.lutris.log, to merely keep it out of sight.

**Comment by strycore** [comment]
Fixed in 0.5.9.1

You can delete the lutris.log file
