### ISSUE TITLE
[SOLUSOS] Can't connect to epic store (Gdk-ERROR)

### ISSUE THREAD

**Issue by Amosar** [lutris/lutris#3751]
Hi, I have an issue when I try to connect to my epic store account, lutris just crash.
My computer specification : https://gist.github.com/Amosar/41e455b99444c885291fae66242d9625
I can login directly with my epic account but when I click to login with google lutris crash

This is the error I get:
```
(lutris:4979): Gdk-ERROR **: 19:33:15.403: The program 'lutris' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 6918 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 1 "python3" received signal SIGTRAP, Trace/breakpoint trap.
0x00007fffe9c5a6ef in g_log_writer_default () from /usr/lib/libglib-2.0.so.0
```

If I can give you more informations I'll be happy to help.

**Comment by tannisroot** [comment]
Hi, this isn't really a lutris client bug, please contact for support on our discord server.

**Comment by PCSuchti** [comment]
@Amosar Were you able to resolve the issue? I'm having the exact same problem but can't find a solution anywhere. Only thing I was able to gather is that it might be something related to nvidia graphics drivers.

**Comment by tannisroot** [comment]
contact for support on our discord server
