### ISSUE TITLE
Epic Store Launcher installed through Lutris won't start with exit code 256

### ISSUE THREAD

**Issue by raploz** [lutris/lutris#3755]
I installed Lutris through the PPA on KDE Neon 5.23. Later I enabled the Epic Games Store service in the options, logged in and tried to install a game. A window appeared and it installed the EG Store and created a desktop shortcut. When I try to open the Store or install any games this is the log:

`Started initial process 25136 from /home/guilherme/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine /home/guilherme/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
esync: up and running.
LogInit: Display: Command Line: "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe" -opengl -SkipBuildPatchPrereq -SaveToUserDir -Messaging
LogWindows: Error: === Critical error: ===
LogWindows: Error: 
LogWindows: Error: Assertion failed: WindowHandle [File:D:/build/++Portal/Sync/Engine/Source/Developer/StandaloneRenderer/Private/Windows/OpenGL/SlateOpenGLContext.cpp] [Line: 53] 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: [Callstack] 0x000000007b010fe6 kernelbase.dll!RaiseException() []
LogWindows: Error: [Callstack] 0x000000000065034e EpicGamesLauncher.exe!PrintScriptCallstack() []
LogWindows: Error: 
Initial process has exited (return code: 256)
Monitored process exited.
Exit with return code 256
`

This is my system info:

`[System]
OS:              KDE neon 20.04 focal
Arch:            x86_64
Kernel:          5.11.0-37-generic
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Physical cores:  6
Logical cores:   6

[Memory]
RAM:             7.6 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.11.0-37-generic, LLVM 12.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.4 - kisak-mesa PPA
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.4 - kisak-mesa PPA
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.4 - kisak-mesa PPA
Vulkan:          Supported
`

Lutris is on version 0.5.9.1

**Comment by KyLinuxOS** [comment]
Same problem

**Comment by tannisroot** [comment]
I cannot reproduce this.

**Comment by maminakurtka1** [comment]
Same, but with battle.net

**Comment by lintong-zhang** [comment]
same here!

**Comment by seem-less** [comment]
Same here when launching Epic Games Store. This is the log:
```
Started initial process 12009 from /home/waseem/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine /home/waseem/Documents/Other/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
fsync: up and running.
LogInit: Display: Command Line: "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe" -opengl -SkipBuildPatchPrereq -SaveToUserDir -Messaging
LogConfig: Warning: FConfigCacheIni::GetString failed to find Filename 
LogWindows: Error: === Critical error: ===
LogWindows: Error: 
LogWindows: Error: Assertion failed: PixelFormat [File:D:/build/++Portal/Sync/Engine/Source/Developer/StandaloneRenderer/Private/Windows/OpenGL/SlateOpenGLContext.cpp] [Line: 100] 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: [Callstack] 0x000000007b0111e6 kernelbase.dll!RaiseException() []
LogWindows: Error: [Callstack] 0x000000000065430e EpicGamesLauncher.exe!PrintScriptCallstack() []
LogWindows: Error: 
Initial process has exited (return code: 256)
Monitored process exited.
Exit with return code 256
```

System details:
[System]
OS: Debian 11
Arch: 64-bit
Kernel: #1 ZEN SMP PREEMPT liquorix 5.16-27.1~bullseye (2022-03-31)
Desktop: Gnome
Display Server: wayland

[CPU]
Model: AMD® Ryzen 7 4800h with radeon graphics × 16

[Memory]
RAM: 64 GB

[Graphics]
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: AMD
OpenGL renderer string: AMD RENOIR (DRM 3.44.0, 5.16.0-18.2-liquorix-amd64, LLVM 11.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by seem-less** [comment]
Same here when launching Epic Games Store. This is the log:
```
Started initial process 12009 from /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine /home/user/Documents/Other/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
fsync: up and running.
LogInit: Display: Command Line: "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe" -opengl -SkipBuildPatchPrereq -SaveToUserDir -Messaging
LogConfig: Warning: FConfigCacheIni::GetString failed to find Filename 
LogWindows: Error: === Critical error: ===
LogWindows: Error: 
LogWindows: Error: Assertion failed: PixelFormat [File:D:/build/++Portal/Sync/Engine/Source/Developer/StandaloneRenderer/Private/Windows/OpenGL/SlateOpenGLContext.cpp] [Line: 100] 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: 
LogWindows: Error: [Callstack] 0x000000007b0111e6 kernelbase.dll!RaiseException() []
LogWindows: Error: [Callstack] 0x000000000065430e EpicGamesLauncher.exe!PrintScriptCallstack() []
LogWindows: Error: 
Initial process has exited (return code: 256)
Monitored process exited.
Exit with return code 256
```

System details:
[System]
OS: Debian 11
Arch: 64-bit
Kernel: #1 ZEN SMP PREEMPT liquorix 5.16-27.1~bullseye (2022-03-31)
Desktop: Gnome
Display Server: wayland

[CPU]
Model: AMD® Ryzen 7 4800h with radeon graphics × 16

[Memory]
RAM: 64 GB

[Graphics]
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: AMD
OpenGL renderer string: AMD RENOIR (DRM 3.44.0, 5.16.0-18.2-liquorix-amd64, LLVM 11.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by GoudronViande24** [comment]
Same here
