### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [lutris/lutris#3756]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/lutris/lokal -name '*.py')
```

**Comment by elfring** [comment]
:thought_balloon: Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?

**Comment by tannisroot** [comment]
What are you proposing exactly and what benefit would it provide?

**Comment by elfring** [comment]
I suggest to achieve another bit of collateral evolution also according to [the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13).
Would you find reduced memory allocations (because of in-place modifications) desirable? :thinking:

**Comment by tannisroot** [comment]
Is this some AI bot talking? GPT-3 using a Github dataset?

**Comment by elfring** [comment]
>Is this some AI bot talking?

No.


>Real people do not talk like that.

I suggest to reconsider such a view. :thought_balloon:
It seems that I represent a fraction of software developers who would like to benefit a bit more from computer-aided source code analyses and transformations.
