### ISSUE TITLE
[icon view]  wide view

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#376]
seems when adding games to empty runners (IE libretro) the icons is spaced way too far apart, unlike in combined view
![screenshot at 2016-10-02 07-44-01](https://cloud.githubusercontent.com/assets/19357986/19019043/d50c0b44-8877-11e6-904a-e6b94d7ebad0.png)

**Comment by strycore** [comment]
This is unfortunately the normal behavior for the new widget we're using for the icon view. I'm not sure there's a way to change that.

**Comment by telanus** [comment]
Seems as soon as enough games are added the spacing goes down, so doubt it's Lutris fault, Thus Closing this :dancing_women:
