### ISSUE TITLE
Add refresh rate option for gamescope

### ISSUE THREAD

**Issue by RicArch97** [lutris/lutris#3761]
By default enabling gamescope runs it without the `-r` flag, which defaults the refresh rate to 60hz.

Ideally the user would select the output where gamescope should run; 
Then we are able to get the resolution & the refresh rate of that output. 

This could be done using `xrandr`:
```console
$ xrandr
Screen 0: minimum 16 x 16, current 6000 x 1440, maximum 32767 x 32767
XWAYLAND1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   2560x1440     59.96*+
   1920x1440     59.97
   ...
XWAYLAND3 connected 3440x1440+2560+0 (normal left inverted right x axis y axis) 800mm x 330mm
   3440x1440    159.92*+
   1920x1440    159.87
   ...
```
which works for both X11 and XWayland.

And then round the numbers to get 60Hz and 160Hz specially for this setup.

Of course being able to change this manually is welcome in case users want to change this.

**Comment by boltronics** [comment]
In the meantime, you can globally set it in `runner_interpreter.py` by adding the lines:

```
    launch_arguments.insert(0, "240")
    launch_arguments.insert(0, "-r")
```

here:

https://github.com/lutris/lutris/blob/e8ea081fb850576e76712e10c95989a97782db7f/lutris/runner_interpreter.py#L114

where you set 240 to whatever you want your refresh rate to be. Restart Lutris after making the change.

**Comment by danieljohnson2** [comment]
We've added a bunch of Gamescope options, but not this one.

**Comment by strycore** [comment]
yes, we have it, it's just not labelled as Refresh rate but as Framerate limiter

**Comment by QmwJlHuSg9pa** [comment]
> yes, we have it, it's just not labelled as Refresh rate but as Framerate limiter

I was confused by intent of this issue, as the ticket is about video modes, but mentions "-r". Looking further into it, it seems "-r" is equivalent to "--nested-refresh", which is indeed a form of frame limiter.

There is an [open Gamescope ticket](https://github.com/ValveSoftware/gamescope/issues/265) to deal with setting monitor refresh rate (a hypothetical "-R" option is suggested), though I suspect such a feature may be poorly supported until GNOME officially supports changing video modes in Wayland ("gnome-monitor-config" and "gnome-randr" both exist, but are not maintained nor included with GNOME shell). I am not sure of the current situation with KDE Plasma.
