### ISSUE TITLE
Feature Request: Requesting the ability to move game install directories.

### ISSUE THREAD

**Issue by kalrach** [lutris/lutris#3763]
I have a fairly large game library and feel like it would be very nice to have the ability to move install directories of games kind of like how you can on steam. Having multiple hard drives I like to keep the games that I play more on my SSD and all others in my "deep" storage drive. This is definitely more of a quality of life thing than anything.

**Comment by strycore** [comment]
There is a move button in the game configuration.
![Screenshot from 2022-02-17 14-16-03](https://user-images.githubusercontent.com/280336/154580078-39f4e9fa-8649-4c07-93f1-9f9f74686d9e.png)

This feature will receive some improvements in the future (Something more like Transmission has)
