### ISSUE TITLE
Lutris 0.5.9 missing Steam Source Service

### ISSUE THREAD

**Issue by Torbuntu** [lutris/lutris#3765]
Is it expected that `Steam` is no longer an available source service?
![image](https://user-images.githubusercontent.com/17347324/138094432-cd04a579-197c-4579-9212-b4162a530ea9.png)

I still have the `Runner` available in the tab with the installed games I added to Lutris:
![image](https://user-images.githubusercontent.com/17347324/138094503-942ace1e-3dc7-469e-a20f-95e6bb1c7d7a.png)

But the only source option is Steam for Windows but I'm unsure what that is.

**Comment by strycore** [comment]
If the service isn't enabled, this means Lutris can't find a `steam` executable on your system

**Comment by Torbuntu** [comment]
But it was/is working with 0.5.8...
