### ISSUE TITLE
[suggestion] support the heroic game launcher as a source

### ISSUE THREAD

**Issue by elypter2** [lutris/lutris#3778]
it's much lighter, less cumbersome than the epic game store and runs natively on linux

**Comment by tannisroot** [comment]
Heroic is not as flexible in terms of workarounds as our wine runner.

**Comment by tobil4sk** [comment]
I prefer installing my EGS games through Heroic. It automatically sets up a separate wine prefix for each game and I don't need to have the Epic Game Store installed through Wine (which is much slower than Heroic).

It would be nice to have a simple way to add EGS games installed via Heroic to my Lutris library. Right now, to do this, I have to:
1. Install the EGS via lutris
2. Click on the "install" button in Lutris for the game I want to run
3. Wait for the the Epic Games Store install menu to come up
4. Close it without installing, and Lutris will be tricked into thinking that the game has been installed in EGS
5. Configure the game's runner to native Linux and run the game via something like:
`/usr/bin/heroic --no-gui "heroic://launch/530f09c9ac834a7bbc98056c69b44471"`

What would be more convenient is if Lutris provided integration for Heroic the same way it does for Steam, in a way that automatically synchronises the library. Each game only needs an "app id" field for the game like is done for Steam:
![image](https://user-images.githubusercontent.com/41230637/205306687-d1810e16-e72d-46f9-965c-06f3ff11acd1.png)

> Heroic is not as flexible in terms of workarounds as our wine runner.

There doesn't need to be much flexibility on the Lutris side for configuring Heroic games, it should just launch them. It wouldn't replace the current Epic Games Store source, but it would just provide an alternative. Not having an easy solution for integrating Heroic (which is used by a lot of people) makes it difficult for Lutris to be "a central interface to launch all your games".

Is there still no chance of something like this?
