### ISSUE TITLE
[Runners] Vice

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#378]
redownloaded the Vice runner this morning, and still no luck. Got vice from the Ubuntu repositories (apt-get install vice) set it up and then symlinked the binaries so that thre runner now uses the locally installed vice. runs great :smile_cat: 

but found a problem :D 

when you change the emulated machine from the C64 to the PET it'll throw:
`
/home/user001/.local/share/lutris/runners/vice/bin/xpet: /home/user001/.local/share/lutris/runtime/steam /amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)`
`/home/user001/.local/share/lutris/runners/vice/bin/xpet: /home/user001/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)`
`HW scale not available, forcing to disabled`
`HW scale not available, forcing to disabled`
`Unknown option '-Crtcdsize'.`
`Error parsing command-line options, bailing out. For help use '-help'`

The C128 needed 2 extra roms not in the runner : kernalch & chargch (not sure if its because of my vice install or not, but got the roms from WinVICE-2.4.18-x86-r29460)

**Comment by strycore** [comment]
There is a new Vice runner I uploaded which is built from the latest SVN version and works much better than the previous one. I also fix the command line arguments for the emulators (Crtcdsize should have been CRTCdsize).
Please note that only our build is supported, if you use another one, the command line options can differ, especially with Vice where they keep changing them between releases.

**Comment by strycore** [comment]
By the way, the missing ROMS are provided by the current SVN version
