### ISSUE TITLE
[Suggestion] Add support for KDE Global Menu

### ISSUE THREAD

**Issue by Darth-Ness** [lutris/lutris#3781]
Bascially what KDE Global Menu is the App Menu (like "File", 'Edit" , "View, "Window", etc.) in usually your top bar. It's very similar to the one on MacOS (I think it's called Universal Menu). KDE"s built in apps like Konsole and Dolphin have support for it. So adding this in will make it fit in.

**Comment by tannisroot** [comment]
We are a GTK3 app and such UI element goes against Gnome HID.
