### ISSUE TITLE
Feature Request: Graphical option for installing software from external yml files

### ISSUE THREAD

**Issue by SViN24** [lutris/lutris#3785]
Lutris has the -i option for directly installing from a yml file.
So far however there seems to be no graphical way of installing software directly from a script.
this could also be extended furthermore with a special extension called (maybe .lutris) that is nothing more than a renamed .yml file.

Benefits:
Less server load for lutris 
Software provider can directly control the preferred options for the piece of software he is providing.
Ease of installing for new linux users more used to the windows approach

Negatives:
Some scripts may be malicious.

**Comment by tannisroot** [comment]
Yml file installation is an advanced feature, there's really no need for it to have a graphical GUI since our centralized installer system is so much easier in use and distribution.
And the negative you mentioned is a huge issue.
