### ISSUE TITLE
Feature Request: libTAS integration

### ISSUE THREAD

**Issue by Koppajin** [lutris/lutris#3788]
Is this something that could be implemented in any way to allow for TASing of any game through Lutris?

@clementgallet

https://github.com/clementgallet/libTAS

**Comment by tannisroot** [comment]
From a quick glance I don't really understand the purpose of this, but I see that it involves messing with graphical APIs. Would you mind explaining briefly how adding this as a feature would benefit the project and whether it supports Vulkan?

**Comment by Koppajin** [comment]
It's a program to create Tool Assisted Speedruns. Here is a snippet from [tasvideos.org](http://tasvideos.org) glossary:

> Tool-assisted speedrun, TAS
> A tool-assisted speedrun (short: TAS) is a speedrun that is made with use of tools.
> 
> Tools are features that help the playing that are not available in regular playing.
> Common examples of tools:
> 
>     Slow motion, pause, and frame advance
>         (Never letting the game to go too fast to handle.) 
>     Precise timer
>         (A frame-by-frame counter of movie length, that helps comparing different paths.) 
>     Re-recording
>         (Ability to undo unwanted actions and retry.) 
>     Hex-editing
>         (Copying and editing of input stream segments.) 
>     Autofire
>         (Also called “turbo”, as found in some game controllers. Automatically repeating pressing of a button.) 
> 
> More in [Wikipedia](http://en.wikipedia.org/wiki/Tool-assisted_speedrun).
> 
> Instructions on using tools are found at the Using Emulator Tools page.
> 
> Use of all of the aforementioned features is not necessary for a movie to be called tool-assisted. If the movie uses even one of these tools (timer excluded, autofire is disputable), it is a tool-assisted movie and not a regular speedrun. 

I'm assuming it will use whatever graphics API of the game you launch with it.

**Comment by tannisroot** [comment]
Unfortunately this seems a little bit too much out of scope for the project, since our main goal is compatibility with non-Linux platforms.

**Comment by Koppajin** [comment]
The whole reason I asked for this is to TAS games through Lutris...which are mainly Windows games, lol.

**Comment by tannisroot** [comment]
But surely it's shouldn't be very hard to integrate it with Lutris without a dedicated integration, we provide features for that.
