### ISSUE TITLE
Star Citizen Installation - 403 Client Error

### ISSUE THREAD

**Issue by cabels2carbells** [lutris/lutris#3791]
During installation for Star Citizen, the client will attempt to download a custom runner (which I am already using), and will return a 403 Client Error Forbidden URL for the custom runner.
It's a little confusing why the installer would try to install a wine runner that I am actively using.
It is very confusing why an install would return a 403.

**Comment by GloriousEggroll** [comment]
Received an email about this. I just ran the installer for a clean install and the runner downloaded just fine. Seems an issue on your side. It's just pulling the download directly from github.

https://github.com/GloriousEggroll/wine-ge-custom/releases/download/6.16-GE-1/lutris-ge-6.16-1-x86_64.tar.xz

**Comment by cabels2carbells** [comment]
Interesting.
Do you have any idea what could be causing this behavior?
I'm, frankly, completely out of ideas, and nobody I've reached has had any
idea either.

**Comment by cabels2carbells** [comment]
I am still not sure what the issue was with the 403, but I was able to circumvent the download entirely.
It turned out that I was actually not using the version it was trying to download (18-1 instead of 16-1, ACK), and running the installation with that configured was able to skip the install and carry on from there.
I still have no idea why the download was returning a 403.
