### ISSUE TITLE
[Feature Request] More proton options

### ISSUE THREAD

**Issue by tunbridgep** [lutris/lutris#3792]
Hi there, I really like the options that wine prefixes give you - such as running an EXE inside a wine prefix.

I would like to see some of the same options implemented in the same menu, but for proton, namely

- Run EXE inside Proton Wine Prefix (more info on how to do this at https://gist.github.com/michaelbutler/f364276f4030c5f449252f2c4d960bd2)
- Run protontricks
- "Browse Files" context menu option should open the Steam proton path for the game, rather than saying "This game has no installation directory"

The main reason I feel this is important is because there are certain games that have unofficial patches or other third-party executables (such as for installing mods), and if we play a game through proton then there is no simple way to run the exe in the context of the proton wineprefix

I am trying to use this to install Forged Alliance Forever.

We can currently do this in a somewhat clunky way by specifying a custom game binary path, but this isn't quite the same thing and requires us to change it back afterwards

**Comment by tannisroot** [comment]
At the moment we don't really support Proton. Maybe in the future.
