### ISSUE TITLE
[Feature request] Search for shared runners by default

### ISSUE THREAD

**Issue by HenryJk** [lutris/lutris#3797]
Hello, is it possible for lutris to detect and use a shared executable by default? The proposed behavior is to search on /usr/share/lutris/runners before searching for runners at user home. Runners at user home will override runners from shared folder. The use case of such feature is to allow the distro package manager to install custom runners on the shared folder for users that wants to use latest release of runners.

**Comment by AlexanderRavenheart** [comment]
Hello,

I have some questions:
- How would the shared folder be populated? 
- Would it contain just the runner's main executable or the entire folder specific to a runner?
- If it contains just the main executable, it would have to be a symlink pointing to the location of the system installed runner, right?
- And in that case, all config files/parameters would have to contain absolute paths and not relative paths to the runner specific folder that Lutris maintains, right?
- And finally, who would maintain the shared folder? The user, manually? Lutris? The system's package manager by updating the distribution's specific package for each emulator/launcher/runner to account for that extra location?

**Comment by HenryJk** [comment]
The idea is to make /usr/share/lutris/runners have identical purpose with ~/.local/share/lutris/runners, only that it is shared and on root. So, yes, it contains the entire folder of a specific runner, multiple runners even. This configuration is inspired by steam proton where steam will search at /usr/share/steam/compatibilitytools.d for custom proton versions. The one maintaining this shared folder would normally be the system package manager. For most sense and purpose, lutris would just read the folder like it would normally on ~/.local/share/lutris/runners.

**Comment by strycore** [comment]
3 new options can now be specified in lutris.conf: runner_dir, runtime_dir and cache_dir
Those settings will override the current settings. Those folders need to be writable by lutris users for runner installation / runtime updates / game media
