### ISSUE TITLE
Dosbox is broken

### ISSUE THREAD

**Issue by atolstoy** [lutris/lutris#3799]
I recently noticed that my Prehistorik 2 became unplayable - the game starts, but it crashes soon after passing the title screens, and all i get is a "segmentation fault" from Dosbox. Seems like Lutris pulls out a broken Dosbox runner. If I override the runner settings and set the official [Dosbox build for Linux](https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.77.1/dosbox-staging-linux-v0.77.1.tar.xz), the game plays fine. I believe Lutris needs to replace the default Dosbox Staging runner with a fixed version.
Steps to reproduce: try to run the [game](https://gamesnostalgia.com/download/prehistorik-2/1536?t=78609596) with the stock Dosbox Staging runner in Lutris.

**Comment by telanus** [comment]
@atolstoy  I've just tried to reproduce this "bug" but it works for me. 

Could you retry the default lutris runner. 

To help you, we need logs! To create a log, first close Lutris completely. Then, open your terminal application, execute lutris -d and try to reproduce your issue. After that, you need to copy the output in the terminal and share it with us (all of it).
It's recommended to use this ad-free paste service: https://paste.ubuntu.com/



![Screenshot_20211103_230145](https://user-images.githubusercontent.com/19357986/140193284-f8bd023c-21da-49ad-b217-4991f0386003.png)

**Comment by atolstoy** [comment]
> @atolstoy I've just tried to reproduce this "bug" but it works for me.
> 

Press 1 to start level 1, then select difficulty, then try to start actual playing. Does it crash?

**Comment by telanus** [comment]
> > @atolstoy I've just tried to reproduce this "bug" but it works for me.
> 
> Press 1 to start level 1, then select difficulty, then try to start actual playing. Does it crash?

Yes it crashes me see. I've tested the game with the latest development version from here: https://dosbox-staging.github.io/downloads/devel/ and it gives the same problem as the one Lutris has as default runner

**Comment by telanus** [comment]
Tested with the version you linked, and for me it behaves precisely like Lutris' runner. IE crashes as soon as I enter the game

**Comment by atolstoy** [comment]
I doubled check it and I can confirm that the game crashes in both variants of Dosbox Staging 0.77.1.
However, I decided to use my distribution's version of Dosbox 0.77.1, and it does not crash.
So, there is something wrong in the pre-built Dosbox binary they distribute.

**Comment by strycore** [comment]
@atolstoy your distribution likely ships the regular dosbox, report the issue to Dosbox Staging: https://github.com/dosbox-staging/dosbox-staging/issues
