### ISSUE TITLE
Sync issue: Implement single instance

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#38]
Games won't appear after installing from the web if Lutris was already running.

**Comment by TingPing** [comment]
(Note that Gtk has this built in via GtkApplication as used in my PR)

**Comment by Xodetaetl** [comment]
Argh. 
Well, Google, you did a bad job this time.

I'll let @strycore see what he wants. (Ehh, I suppose the advantage of not using GtkApplication is that it simplifies porting to another toolkit.)
