### ISSUE TITLE
Lutris does not initialize the main view when the side panel is hidden

### ISSUE THREAD

**Issue by danieljohnson2** [lutris/lutris#3800]
To reproduce this, use the little drop down menu thingy and uncheck "Show Side Panel". Next, close Lutris completely. Re-open it.

It opens to a blank window. I expect to see something here; either the last view I had used, or some default view. If you go back and recheck "Show Side Panel", the view will then appear.

I think this is happening because the side panel will not be realized if hidden, and it is the handler for the realize signal that is selecting the initial view. The signal emitted upon selection is what triggers the view to initialize, but this does not happen.

**Comment by AlexanderRavenheart** [comment]
I think at this point it would simply be better to remove the option to hide the Side Panel and simply have it be always visible seeing how integral it is to Lutris' functionality.

Unless there is a very good reason to have the ability to hide the Side Panel. I can't think of one.
@strycore Why do we have an option to hide the Side Panel? Is there an important use case covered by having this option?

**Comment by danieljohnson2** [comment]
Removing the option would be a larger change than fixing it, certainly.

I can't imagine many people used this option with this bug in. But it seems to me that it could be useful on small screens, or on ordinary screens when the UI is enlarged with the "Large Text" or HiDPI options. You might want to do this if your eyesight wasn't so great.

I've been known to do this, but really I also maximize the window instead of hiding the side-panel.

**Comment by danieljohnson2** [comment]
On the other hand, removing this option is not really hard and would remove a source of bugs.

If you decide you want to go that way, I can toss you a pull request for that instead.
