### ISSUE TITLE
Click icon load bar and crash.

### ISSUE THREAD

**Issue by SiposIosfi** [lutris/lutris#3805]
Useing amd drivers and did not work with and without tham.
Reinstalling litrus from POP shop (nothing)
install from webpage still nothing. 
no error code.
one time it started but cod not oppen the steam library.

**Comment by tannisroot** [comment]
Can you provide logs?

**Comment by SiposIosfi** [comment]
> Can you provide logs
i miss blicked my amd drivers. and after good instalation works just fine
