### ISSUE TITLE
Github download link appears to break installerwindow.py script

### ISSUE THREAD

**Issue by Swizzler121** [lutris/lutris#3813]
Attempted to update the installer script for Morrowind GOTY edition to support the new version of OpenMW.

The new version isn't hosted on their website anymore, so I had to update the URL from Line 2 of the installer script from:

`- openmwarchive: https://downloads.openmw.org/linux/generic/openmw-0.46.0-Linux-64Bit.tar.gz`

to:

`- openmwarchive: https://github.com/OpenMW/openmw/releases/download/openmw-0.47.0/openmw-0.47.0-Linux-64Bit.tar.gz`

this is the singular change I make in the config. It goes from a working script to one that hangs on a page that says "Please review the files needed for the installation then click 'Continue'" except no files are listed and there is no continue button. Which is from line 307 of installerwindow.py

This page does not appear at all in the 0.46 of this installer, which works fine.

**Comment by Swizzler121** [comment]
No, I ran several tests, I was able to query the download and complete the download in isolated environments when no credentials were provided. Both on Windows and Linux machines, in terminal and in graphical environments.

**Comment by strycore** [comment]
looks like the OpenMW downloads are hosted on their website again. 

There are also lots of scripts downloading released from Github so I believe this is no longer an issue.
