### ISSUE TITLE
Lutris.net will not open lutris app when installign games

### ISSUE THREAD

**Issue by Abhs15** [lutris/lutris#3816]
so i was using lutris i run manjaro xfce everything was working perfectly until randomly lutris website just wont open lutris anymmor it just gives me an eror im using opera briwser i tried it on firefox chrome chromium it just wint work heres a pic
![Screenshot_2021-11-12_17-10-32](https://user-images.githubusercontent.com/92677987/141639017-763f4883-deee-4305-bf6b-9a9a03937b49.jpg)

**Comment by tannisroot** [comment]
can you provide some information on your system?

**Comment by tannisroot** [comment]
it's not really a bug with the client, you must have broken xdg associations that's all.
