### ISSUE TITLE
Make installer (and possibly other names) a reserved keyword

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#382]
game: https://lutris.net/games/kings-quest-i-quest-for-the-crown-adg-remake/

it seems wine has trouble with some filenames 

```
DEBUG    2016-10-07 14:31:56,020 [thread]:Running command: "/home/ssf/.local/share/lutris/runners/wine/1.9.20-i386/bin/wine" "/home/ssf/.cache/lutris/installer/kings-quest-i-quest-for-the-crown-adg-remake/countdl.php?action=download&game=11"
wine: cannot find '/home/ssf/.cache/lutris/installer/kings-quest-i-quest-for-the-crown-adg-remake/countdl.php?action=download&game=11'
DEBUG    2016-10-07 14:31:57,523 [system]:Executing fuser /home/ssf/.local/share/lutris/runners/wine/1.9.20-i386/bin/wine
```

so why not save files as their var:
```
files:
- installer: http://agdinteractive.com/countdl.php?action=download&game=11
game:
....
```

eg http://agdinteractive.com/countdl.php?action=download&game=11 will become 'installer' instead of of  its url name 'http://agdinteractive.com/countdl.php?action=download&game=11'

**Comment by daniel-j** [comment]
From installer documentation
> The ``files`` section of the installer references every file needed for
installing the game. This section's keys are unique identifier used later in
the ``installer`` section. The value can either be a string containing a URI
pointing at the required file or a dictionary containing the ``filename`` and
``url`` keys. The ``url`` key is equivalent to passing only a string to the
installer and the ``filename`` key will be used to give the local copy another
name.

I'm guessing it's used like this:
```
files:
- installer:
    url: http://agdinteractive.com/countdl.php?action=download&game=11
    filename: install.exe
```

**Comment by strycore** [comment]
To workaround the file not receiving a proper filename, the solution @daniel-j gave is the correct one.

However there seems to be another problem here: 
`Running command: "/home/ssf/…`
I have been avoiding naming my installer files installers because I suspected that there could be some issues doing that and it seems that there are. The installer is trying to run a command called installer, which is not right at all. I'll try to see if it can be fixed and if not, I'll display an error when "installer" is used as a file identifier.

**Comment by strycore** [comment]
Ok, no issue using 'installer' as a file identifier, it works just fine.
Using the explicit url/filename arguments fixes the issue.
I've also made a few more modifications to the installer: 
- I've removed the wine.arch and wine.prefix entries in the game section, this does nothing.
- I set the Wine prefix to $CACHE and merged the game folder to $GAMEDIR once installed, this gets rid of an useless wine prefix.

**Comment by sixsixfive** [comment]
>I've removed the wine.arch and wine.prefix entries in the game section, this does nothing.

so how do i force a 32bit wine on 64bit then?

**Comment by strycore** [comment]
> so how do i force a 32bit wine on 64bit then?

You pass 'arch' to the wineexec task, wine.arch in a ags game section will do literally nothing.

**Comment by sixsixfive** [comment]
so i would need to do it with the wineprefix create task otherwise it wont work anymore (since: C:\Program files becomes C:\Program files (x86) )

**Comment by sixsixfive** [comment]
also why did you remove the dll override? in its current form it will mess up the xdg menu and mimetypes

**Comment by strycore** [comment]
>so i would need to do it with the wineprefix create task otherwise it wont work anymore (since: C:\Program files becomes C:\Program files (x86) ) 
Yes, the create prefix task also supports the arch argument (I think all wine related tasks support both arch and prefix arguments, if not, they should)

**Comment by strycore** [comment]
> also why did you remove the dll override? in its current form it will mess up the xdg menu and mimetypes

It's a throwaway wine prefix, it's deleted right after the installation is finished.
I've noticed that's it's something that you systematically put in your wine installers but if you believe that this should become the default behavior, please create an issue explaining in detail why it's needed and I'll make it so all created prefixes have this behavior.

Same thing for the sandbox task you use in your wine installers. Create another issue and I'll make this the default behavior.
