### ISSUE TITLE
Unexpected Manipulations

### ISSUE THREAD

**Issue by AuracleTech** [lutris/lutris#3826]
Why do I need the job of a package manager.
Isn't it the point of linux to have everything easily done?
Why do I need to click buttons and do commands myself...
![image](https://user-images.githubusercontent.com/40531871/142019303-64f5e54d-1923-49e7-9899-8659afa3feb7.png)

**Comment by tannisroot** [comment]
It just asks you to install the a graphics driver and its stuffs. We have a guide for that to do that very trivially. You do that on Windows too.

**Comment by tannisroot** [comment]
https://github.com/lutris/docs/blob/master/InstallingDrivers.md
https://github.com/lutris/docs/blob/master/WineDependencies.md

**Comment by tannisroot** [comment]
I do agree that this sort of wall of instructions is overwhelming tho. I will take a lot at this game page and fix it up later.
