### ISSUE TITLE
Strange categories in OpenSUSE .desktop file

### ISSUE THREAD

**Issue by edave64** [lutris/lutris#3827]
The .desktop file on OpenSUSE categorizes Lutris as "Network;FileTransfer;", not "Game" as on [the default desktop file](https://github.com/lutris/lutris/blob/master/share/applications/net.lutris.Lutris.desktop#L4)

This issue seems to have been previously spotted, (https://github.com/lutris/lutris/commit/890d4c980fc7b92f57eee893361f9a6e04bfc8ef) but has been reverted (https://github.com/lutris/lutris/commit/91d482a8b183dc1cd6c9809837395f95663d5b92) without any stated reason I could find.

**Comment by tannisroot** [comment]
Idk why that was reverted but I un-reverted it.
