### ISSUE TITLE
Game from Epic game store crush

### ISSUE THREAD

**Issue by malccin** [lutris/lutris#3828]
When I try run a game from Epic store, game crush and finally log me out from system (regardless of which version of wine I use.). Log below:

INFO     2021-11-16 20:57:35,777 [startup.check_driver:61]:Running AMD Mesa driver 21.2.5 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.35.0, 5.4.0-90-generic, LLVM 12.0.1) (0x67df)
INFO     2021-11-16 20:57:35,777 [startup.check_driver:73]:GPU: 1002:67DF 1462:3413 (amdgpu drivers)
INFO     2021-11-16 20:57:35,777 [startup.check_driver:73]:GPU: 8086:0112 1849:0112 (i915 drivers)
DEBUG    2021-11-16 20:57:36,379 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2021-11-16 20:57:55,981 [lutriswindow.update_store:451]:Showing 185 games
DEBUG    2021-11-16 20:58:01,373 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/dxgi.dll with DXVK version
DEBUG    2021-11-16 20:58:01,375 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3d11.dll with DXVK version
DEBUG    2021-11-16 20:58:01,375 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3d10core.dll with DXVK version
DEBUG    2021-11-16 20:58:01,376 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3d9.dll with DXVK version
DEBUG    2021-11-16 20:58:01,377 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/dxgi.dll with DXVK version
DEBUG    2021-11-16 20:58:01,378 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3d11.dll with DXVK version
DEBUG    2021-11-16 20:58:01,379 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3d10core.dll with DXVK version
DEBUG    2021-11-16 20:58:01,380 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3d9.dll with DXVK version
DEBUG    2021-11-16 20:58:01,381 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3d12.dll with VKD3D version
DEBUG    2021-11-16 20:58:01,381 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/nvapi64.dll with DXVK-NVAPI version
DEBUG    2021-11-16 20:58:01,381 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/nvml.dll with DXVK-NVAPI version
DEBUG    2021-11-16 20:58:01,381 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/nvapi.dll with DXVK-NVAPI version
DEBUG    2021-11-16 20:58:01,382 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/nvml.dll with DXVK-NVAPI version
ERROR    2021-11-16 20:58:01,382 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2021-11-16 20:58:01,382 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2021-11-16 20:58:01,382 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,382 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_46.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dcompiler_47.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_33.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_34.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_35.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_36.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,383 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_37.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_38.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_39.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_40.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_41.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,384 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx10.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx11_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx11_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_24.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_25.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_26.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,385 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_27.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_28.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_29.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_30.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_31.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_32.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_33.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,386 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_34.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_35.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_36.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_37.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_38.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_39.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_40.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,387 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_41.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/system32/d3dx9_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_46.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dcompiler_47.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_33.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,388 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_34.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_35.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_36.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_37.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_38.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_39.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_40.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,389 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_41.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,390 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,390 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,390 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx10.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,390 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx11_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,390 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx11_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_24.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_25.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_26.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_27.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_28.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_29.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,391 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_30.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_31.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_32.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_33.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_34.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_35.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_36.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,392 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_37.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_38.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_39.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_40.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_41.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_42.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,393 [dll_manager.enable_dll:131]:Replacing /home/marcin/Games/epic-games-store/drive_c/windows/syswow64/d3dx9_43.dll with D3D Extras version
DEBUG    2021-11-16 20:58:01,437 [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:DRI_PRIME="1"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:LD_LIBRARY_PATH="/opt/wine-staging/lib:/opt/wine-staging/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib:/lib/i386-linux-gnu/i686/sse2:/lib/i386-linux-gnu/sse2:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib32:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/marcin/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/marcin/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/marcin/.local/share/lutris/runtime/steam/i386/lib:/home/marcin/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/marcin/.local/share/lutris/runtime/steam/i386/usr/lib:/home/marcin/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/marcin/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/marcin/.local/share/lutris/runtime/steam/amd64/lib:/home/marcin/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/marcin/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:DXVK_HUD="compiler"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:MESA_GL_VERSION_OVERRIDE="4.4COMPAT"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:__GL_SHADER_DISK_CACHE_PATH="/home/marcin/Games/epic-games-store"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:WINEDEBUG="-all"
DEBUG    2021-11-16 20:58:01,653 [command.start:139]:WINEARCH="win64"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINE="/opt/wine-staging/bin/wine"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINEPREFIX="/home/marcin/Games/epic-games-store"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINEESYNC="1"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINEFSYNC="0"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:DXVK_NVAPIHACK="0"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:game_name="World of Goo"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages"
DEBUG    2021-11-16 20:58:01,654 [command.start:139]:LUTRIS_GAME_UUID="1cacb84c-ec3a-47a9-a74d-010fc9b82a75"
Started initial process 18349 from gamemoderun /opt/wine-staging/bin/wine /home/marcin/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/Anemone?action=launch
Start monitoring process.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
esync: up and running.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Initial process has exited (return code: 0)
libGL error: Different GPU, but blitImage not implemented for this driver
libGL error: failed to load driver: i965

**Comment by tannisroot** [comment]
This is a driver issue, please ask for help on our Lutris Discord server.
