### ISSUE TITLE
[Feature Request] Add an easy way to launch sources

### ISSUE THREAD

**Issue by aflyingpumpkin** [lutris/lutris#3835]
Currently, if a user wan't to launch a source such as Epic Games, Steam, or DolphinEMU the user has to do so manually. Adding in an easy way to do so would be a nice QOL feature. There are two ways I can think of for doing this:
1: Double click on source to launch.
2: Add in right click menu with a variety of functions such as disabling the source, refreshing, and launching.

**Comment by tannisroot** [comment]
I don't understand, we already a way to enable and disable sources in preferences?

**Comment by aflyingpumpkin** [comment]
This is not for disabling and enabling sources. This is for launching sources (EX: Opening epic games, opening steam, etc.), I am sorry that I did not make that clear.

**Comment by danieljohnson2** [comment]
I notice that many runners (DOSBOX, hatari, etc) have a 'runnable alone' feature- they get a little 'play' button in the sidebar. Click this to start the runner with no game.

Maybe this should work the same way- a little 'play' button in the sidebar.

Though I wonder what you'd get if you used this button on the Lutris source. Another Lutris window? Open the web site?

**Comment by strycore** [comment]
I'd like to have a way to run the launchers from the sidebar. My main worry is that we'll have 3 buttons per service row and that's going to overlap with the labels unless we increment the size of the sidebar.

We could have a single icon to show a menu, like we have on the bottom bar.

**Comment by strycore** [comment]
EGS, Origin and Ubisoft Connect can now launch from the side bar
