### ISSUE TITLE
Pass Nvidia's _GL_SHADER envars for every game

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3838]
And when I mean every game, I mean for every runner Lutris has.
Nvidia has this stupid shader cache size limitation for their default folder in .cache/nvidia, so to avoid games losing their cached shader entries, especially ones with very large amounts of shaders like Overwatch, we should set a dedicated shader cache path for every game launched through Lutris. This way, the caches aren't mashed together and pruned by the nvidia driver when the folder size exceeds a certain amount (I don't remember what it is but definitely less than half a gig).
Envars that need to be set:
__GL_SHADER_DISK_CACHE=1
__GL_SHADER_DISK_CACHE_PATH=$GAMEDIR
Setting this will create a GLCache folder in $GAMEDIR.

**Comment by danieljohnson2** [comment]
Well, this did not seem as challenging as I thought. Have a tiny PR.
