### ISSUE TITLE
Refresh log window after a game is launched

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3840]
If you open the "Logs" window before the game is launched, it will remain empty, you need to close it and open the window again. And it will also not have newer output if you stop the game and launch it again.

**Comment by danieljohnson2** [comment]
For some reason opening the log window does not create the log text buffer, if it does not exist yet. That makes this log window singularly useless.

I think opening the window should create the log buffer. The game can use it once it starts.
