### ISSUE TITLE
Clear log info before launching a game the second time

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3841]
Lutris will combine log output from previous runs with the latest run. This can be confusing when trying to debug something or get some information, so it would be nice if Lutris cleared logs from previous sessions and only showed logs from the current session.

**Comment by danieljohnson2** [comment]
The issue seems to be that Lutris throws away the TextBuffer holding the log rather than clearing it. The log window retains the buffer and doesn't care about this event. I think this was meant to do what you want, but is bugged.

Clearing the buffer instead works.
