### ISSUE TITLE
Document $WINEBIN

### ISSUE THREAD

**Issue by ReillyBrogan** [lutris/lutris#3843]
I am trying to setup the Discord RPC bridge, which seems best integrated with Lutris by using a pre-launch script. It would be very helpful if Lutris could export environmental variables for the wineprefix and the wine path such that they could be referenced by scripts rather than requiring per-game scripts if for example you needed to do something in the wine prefix. Perhaps exporting them as LUTRIS_WINEPREFIX and LUTRIS_WINEPATH?

**Comment by tannisroot** [comment]
Typically $GAMEDIR is used as the prefix and we provide path to our Wine via $WINEBIN envar
https://github.com/lutris/lutris/commit/f6838a8a4cef8d94fae9fc8cd8381266ebc17381
The latter should be documented however.
