### ISSUE TITLE
Epic Game Store Service not displaying all games

### ISSUE THREAD

**Issue by rym002** [lutris/lutris#3844]
### Bug description

I noticed battlefront 2 is not displaying in my library and is the only game missing. After some investigation it appears when using the library-service API https://library-service.live.use1a.on.epicgames.com/library/api/public/items?includeMetadata=true.

### How to Reproduce

1. Go to 'Epic Game Store Service'
2. Click on 'Refresh Library'
3. Do 'authentication'
4. See 'observe Battlefront 2 is not displayed in lutris but visible in epic game store'

### Expected behavior

All games in the EGS Library should be available in lutris

### Log output

```shell
N/A
```

### System Information

```shell
N/A
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tannisroot** [comment]
You didn't provide logs

**Comment by rym002** [comment]
Logs dont have any error. The api being used for some reason does not show that game. I have patched the code and opened a PR. The using the library URL returns the missing game.

**Comment by tannisroot** [comment]
ah, whoops just woke up and didn't really pay a lot of attention to the description
