### ISSUE TITLE
Deprecate Wine Steam runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3847]
Now that Steam added support for CEG, we can deprecate this hunk of junk of a runner.
For those few games that for whatever reason do not work with native Steam, we can just install windows steam ourselves in an installer.

**Comment by strycore** [comment]
done

**Comment by Zireael07** [comment]
I have a game that doesn't want to work with native Steam, how do I use Windows Steam now?

**Comment by strycore** [comment]
@Zireael07 Use the installer on this page: https://lutris.net/games/steam/

**Comment by Zireael07** [comment]
This should be better documented - people usually won't think of searching for "Steam" on Lutris page...
