### ISSUE TITLE
add an option to toggle the composite manager

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#385]
for best performance there should be an easy way to disable the windowmanagers composite.

eg:

-->user want to run a game
-->lutris disables composite if enabled and launches game
-->user exists game
-->lutris re-enables composite

also here some commands to start:

Plasma/kwin:

```
if [ "$(qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.active)" = "true" ]; then
    qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.suspend
else
    qdbus org.kde.KWin /Compositor org.kde.kwin.Compositing.resume
fi
```

also same is possibe with xfwm, metacity & co if i remember correctly they just use their own tools xfconf, gsettings/gconf

eg xfwm:

```
xfconf-query --channel=xfwm4 --property=/general/use_compositing --set=false 
```

**Comment by tannisroot** [comment]
Feature was implemented in #881.
