### ISSUE TITLE
Don't scare a user with "Error code 256" messages

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3850]
They are usually harmless and just occur if a program is closed, don't scare the user by giving them a scary popup message with that error code.

**Comment by ALipAkrohk** [comment]
Exactly, I also reject this error message.
EXIT WITH RETURN CODE 256
This error occurs more when installing a new game or program.
![Screenshot_20211124_164627](https://user-images.githubusercontent.com/27810360/143246028-5a4567b6-9e91-467e-9d65-f29c7b62c132.png)

**Comment by tannisroot** [comment]
Your error actually indicates an issue, which is right there in the log output box.
