### ISSUE TITLE
"Could not retrieve game installer" when trying to install a game from EGS source

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3853]
Whenever I try to install a game through the Epic Games source, I always get a "Could not retrieve game installer" when the installer window pops up. After I close it (which seems to put the installer window to foreground for some reason, very annoying), I can install EGS just fine.

**Comment by danieljohnson2** [comment]
I'm seeing this same thing with GOG installers. They work, but the bogus error forces the install dialog into the background.

It appears to me that a couple of places where install() gets called, the caller expects a game_id (or 'slug'?) and if it gets 'None' back it understands this to mean 'installer not found'. I can find no install() method that does that- they return 'None' to mean 'not installed yet- I'm working on it'. Installers are mostly asynchronous- they start in the install method, but may run for a long time. Only 'local' installers return a game_id, and they don't seem to fail to find the installer anyway.

Seems simple to fix; I'm working up a PR now.

**Comment by ThymiG** [comment]
if you had "Cannot retrieve game installer" just go to https://lutris.net, and search ur game and install from that page.
