### ISSUE TITLE
[Requerst] Genshin Impact

### ISSUE THREAD

**Issue by ALipAkrohk** [lutris/lutris#3858]
*** Sorry ***

Sorry, I deleted this issue so that the script server information does not get into miHoYO.

**Comment by AlexanderRavenheart** [comment]
Please discuss this in the **requests_and_feedback** or **writing_installers** channel of Lutris' Discord server.

**Comment by YihaoPeng** [comment]
![image](https://user-images.githubusercontent.com/26923506/143721803-1ef5710d-3886-4a25-8963-9186b19b13ce.png)
