### ISSUE TITLE
"Running" tab is not refreshed when a game stops/starts

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3863]
If you stop a game that is listed in the running tab, it will not disappear from it, this will only happen if you switch to a different one and back.
Similar thing happens when a game starts through an application/desktop shortcut, the game is running but it's not listed because the view is not refreshed.
![Peek 2021-11-28 22-15](https://user-images.githubusercontent.com/10602045/143782556-aed44254-86de-4978-8227-41bacc8ff02c.gif)
![Screenshot from 2021-11-28 22-12-54](https://user-images.githubusercontent.com/10602045/143782562-4dece53f-284c-473f-ba36-a493138dc237.png)

**Comment by danieljohnson2** [comment]
Seems like it's missing a handler for 'game-stop'- it removes the sidebar row when the last game stops, but not the game itself. And the running row remains selected even after it is removed.

I've put together a fix, though it is not perfect. It updates the running page when the game stops, which loses the selection and (I think) scroll position. I figure they won't be missed, but there may be a better way. It also selects the 'Game' page if the 'Running' page is selected when hidden.

**Comment by danieljohnson2** [comment]
Er, never mind. That fix does not even work on natural game exits. I'll need to rethink it.

**Comment by tannisroot** [comment]
@danieljohnson2 You might want to look at how the bottom panel is refreshed when the selected game stops

**Comment by danieljohnson2** [comment]
The game-bar at the bottom hooks up the game-stopped emission. It responds by regenerating its content, and at that time it checks the field 'Game.state'; that's what tells it if the game is running or what.

That could indeed be useful. Thanks for the tip.

**Comment by danieljohnson2** [comment]
OK, there's another try. The key seems to be making is_game_displayed() know about the running tab's special rules. Seems to me to work better, anyhow.
