### ISSUE TITLE
Lutris unmet dependancy out of nowhere

### ISSUE THREAD

**Issue by zlatedam** [lutris/lutris#3865]
### Bug description

So i have been running lutris fine with a few games installed for about 2 weeks now on arch (endeavour technically) and out of nowhere today i tried upgrading my system by issuing the command Sudo pacman -Syu 

It returned me with this error 
: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 endeavouros is up to date
 home_ungoogled_chromium_Arch is up to date
:: Starting full system upgrade...
resolving dependencies...
warning: cannot resolve "mesa-utils", a dependency of "lutris"
:: The following package cannot be upgraded due to unresolvable dependencies:
      lutris

:: Do you want to skip the above package for this upgrade? [y/N] 

I have tried installing the package by doing sudo pacman -S mesa-utils and a few other ones (not sure if that is right at all as im still very new to it) but i cannot seem to find anyone else with this issue, or how to fix it.

### How to Reproduce

Steps to reproduce this behavior:
unsure if you can replicate it but just trying to upgrade lutris through the terminal gave me this issue. 

### Expected behavior

I expected to be able to update the package with out this error of dependency not being met.

### Log output

```shell
2021-11-29 09:15:45,900: Magic not available. Unable to automatically find game executables. Please install python-magic
2021-11-29 09:15:45,933: Starting Lutris 0.5.9.1
2021-11-29 09:15:45,961: No cores found
2021-11-29 09:15:47,386: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk/releases
2021-11-29 09:15:47,713: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk-nvapi/releases
2021-11-29 09:15:48,063: Failed to read content length on response from https://api.github.com/repos/lutris/vkd3d/releases
2021-11-29 09:15:48,374: Startup complete
INFO     2021-11-29 09:15:48,375 [startup.check_driver:53]:Using NVIDIA drivers 495.44 for x86_64
INFO     2021-11-29 09:15:48,375 [startup.check_driver:57]:GPU: Unknown
INFO     2021-11-29 09:15:48,375 [startup.check_driver:73]:GPU: 10DE:2503 1458:4074 (nvidia drivers)
DEBUG    2021-11-29 09:15:48,555 [lutriswindow.update_store:451]:Showing 18 games
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          5.15.5-arch1-1
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.44
OpenGL Core:     4.6.0 NVIDIA 495.44
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.44
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tannisroot** [comment]
That makes no sense. What command do you run to upgrade? Are you able to install `mesa-utils` separately?
Also this is a packaging issue with Arch, not really our problem, but i will leave this open

**Comment by SGOrava** [comment]
package `mesa-utils` is in `extra` repository, see https://archlinux.org/packages/extra/x86_64/mesa-utils/
it was in testing before, so just wait a while for your mirrors to sync or change your mirrors to the faster syncing ones.
