### ISSUE TITLE
Null Play Time Causes Lutris to Crash Upon Using "lutris -lj"

### ISSUE THREAD

**Issue by KasKatto** [lutris/lutris#3866]
### Bug description

If there is a game that has no play time tracking (in my case Civ 6 installed from steam - native linux build) and you try running "lutris -lj" or "lutris --list-games --json", lutris will crash immediately.

### How to Reproduce

1. Have a game installed from steam's native linux package
2. Run said game from lutris to make sure play time isnt being tracked
3. Run "lutris -lj" in a console

### Expected behavior

Lutris spits out the games list in json format

### Log output

```shell
$ lutris --list-games --json

2021-11-29 13:49:25,999: Starting Lutris 0.5.9.1
2021-11-29 13:49:26,042: No cores found
2021-11-29 13:49:26,576: Startup complete
2021-11-29 13:49:26,577: Running AMD Mesa driver 21.3.0 on Radeon RX Vega (VEGA10, DRM 3.42.0, 5.14.0-19.2-liquorix-amd64, LLVM 12.0.1) (0x687f)
2021-11-29 13:49:26,577: GPU: 1002:687F 148C:2387 (amdgpu drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 342, in do_command_line
    self.print_game_json(command_line, game_list)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 580, in print_game_json
    games = [
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 588, in <listcomp>
    "playtime": str(timedelta(hours=game["playtime"])),
TypeError: unsupported type for timedelta hours component: NoneType
2021-11-29 13:49:26,649: Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Ubuntu 21.04 hirsute
Arch:            x86_64
Kernel:          5.14.0-19.2-liquorix-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 1700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            31.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: Radeon RX Vega (VEGA10, DRM 3.42.0, 5.14.0-19.2-liquorix-amd64, LLVM 12.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.0-devel
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.0-devel
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.0-devel
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tannisroot** [comment]
Try this PR https://github.com/lutris/lutris/pull/3796

**Comment by KasKatto** [comment]
I can confirm the pull request works as expected. Games with no play time simply have null as the json output for the field instead of crashing lutris.
