### ISSUE TITLE
Ubisoft Connect Runner

### ISSUE THREAD

**Issue by linux4life1** [lutris/lutris#3869]
While trying to install Ubisoft Connec via the runner it hangs at initializing

when viewing the logs this appears every 5 seconds repeating 

 `"HTML Imports is deprecated and has now been removed as of M80. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: uplay://localhost/ui/view/start/main.html (13 `

fedora 35
Ryzen 7 3800
RX 5700 XT
[ubisoft.txt](https://github.com/lutris/lutris/files/7626149/ubisoft.txt)

**Comment by tannisroot** [comment]
Lutris does not have a Ubisoft Connect Runner.
