### ISSUE TITLE
Add option to import an existing game

### ISSUE THREAD

**Issue by Elendil211** [lutris/lutris#3873]
Currently there is no option to add an existing game that was previously installed via Lutris.

This is relevant for example when someone reinstalls the system, and wants to add games that are stored on a different partition.

While it is possible to add games manually, this requires to set all options manually. It would be easier to make use of the online scripts, while still not being required to also download and install the game.

**Comment by tannisroot** [comment]
We have plans to easily migrate your old library to a new installation. For now, just backup `lutris` folders in `.local/share`, `.config` and `.cache`.
