### ISSUE TITLE
Can't install a GOG game that is not in the account's library if logged into GOG

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3876]
If I'm logged into GOG source and try to install a game that is not in my library (for testing for example), the installation will bork out with an empty error window and refuse to proceed. In the logs, i see this:
```
2021-12-03 18:53:13,076: Failed to request https://api.gog.com/products/1260828108/downlink/installer/en1installer0, check your GOG credentials and internet connectivity
2021-12-03 18:53:13,077: 
None
```
If I log out, everything works normally.

**Comment by danieljohnson2** [comment]
Do you mean can install GOG games normally when logged out of GOG? Or are you also logged in to Lutris?

**Comment by tannisroot** [comment]
I have the installation files for a game from GOG that I do not own on my main account. When I am logged into GOG, if I try to install the game by clicking on "Install" on Lutris.net (i guess the same would happen with builtin installer search), the installation will fail because Lutris will try request files for a game that I do not have in my GOG account. So if I log out, it won't try to download it the installation files from there.
Instead Lutris.net should understand that I don't own this particular game and fallback to installation from local files.

**Comment by strycore** [comment]
fixed
