### ISSUE TITLE
Create desktop/application menu shortcut writes a bad .desktop file

### ISSUE THREAD

**Issue by daniel-j** [lutris/lutris#388]
File contents:
```
[Desktop Entry]
Type=Application
Name=%s
Icon=%s
Exec=lutris lutris:%s
Categories=Game
```
**How to reproduce**
Right click a game and select Create desktop shortcut.
Navigate to ~/Desktop
You see a file with name `gameslug-id.desktop` but it contains what's above. If you're in a file manager you see the game title instead of the filename, so it appears as `%s` there.

**Lutris debug output**
```
[system]:Executing which xdg-user-dir
```

Operating system: Arch Linux

**Comment by strycore** [comment]
Nice!
