### ISSUE TITLE
Apply some options during installation phase

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3882]
Options that are enabled by default (DXVK, VKD3D, D3DExtras, DXVK-NVAPI, Esync) or specified by the installer's configuration (like Virtual Desktop, DLL overrides, environment variables) should be applied and work during the installer phase, since some of them are a requirement not just when the game is actually played, but during installation as well.
Note that for default options, the the option values specified in the installer itself should be respected. So if an installer disables DXVK, it shouldn't be enabled during installation either.

**Comment by danieljohnson2** [comment]
I've made an attempt at this, but there's something I don't understand.

How can an installer decline DXVK? I don't see it, and I expect my PR #3962 won't understand about this at this point.
