### ISSUE TITLE
Unable to fast-forward when pulling from the master branch

### ISSUE THREAD

**Issue by jrobeson** [lutris/lutris#3891]
### Bug description

When i type `git pull` I see:

`fatal: Not possible to fast-forward, aborting.`

Did somebody force push the master branch?

### How to Reproduce

1. Have an existing lutris checkout
2. Type `git pull` when in the repo directory

### Expected behavior

Expect to receive the newest changes

### Log output

```shell
N/A
```

### System Information

```shell
N/A
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by AlexanderRavenheart** [comment]
What is the first commit you see when you do `git log`?

**Comment by jrobeson** [comment]
$ git log -1
commit 34aa083ef24ba9034bb7db58020e7d6839c9cd02 (HEAD -> master)
Author: Alexandr Oleynikov <10602045+tannisroot@users.noreply.github.com>
Date:   Sat Nov 20 11:44:52 2021 +0300

    Improve documentation for some installer task types

**Comment by tannisroot** [comment]
> Did somebody force push the master branch?

Yes.
Do `fetch && git reset --hard origin/master`.
