### ISSUE TITLE
Can't stop Game using AppID

### ISSUE THREAD

**Issue by adro79** [lutris/lutris#3892]
### Bug description

Hi there,

I'm trying to play some games that I have on my Windows partition.
When I add the games to the library and start them it starts showing this line trough the terminal:

`2021-12-07 01:11:14,749: Data path for SteamApp *STEAM APPID* not found.`

I can exit the game but the Stop button doesn't change.

Thanks in advance.

### How to Reproduce

1. Add Custom Game
2. Set runner to Steam, add the app ID and the excecutable path and turn DRM Free On.
3. Start.
4. Stop from game, Lutris don't switch to start again.

### Expected behavior

The problem is solved when I delete the Application ID, but I feel like it should be a warning or a workaround instead of freezing.

### Log output

```shell
When it starts:

INFO     2021-12-07 01:18:49,518 [steam.get_game_path_from_appid:215]:Data path for SteamApp 1145360 not found.


When I try to stop it from lutris:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/game_actions.py", line 144, in on_game_stop
    game.force_stop()
  File "/usr/lib/python3.9/site-packages/lutris/game.py", line 527, in force_stop
    os.kill(int(pid), signal.SIGTERM)
PermissionError: [Errno 1] Operation not permitted
```

### System Information

```shell
[System]
OS:              Manjaro Linux 21.2.0 Qonos
Arch:            x86_64
Kernel:          5.15.2-2-MANJARO
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.44
OpenGL Core:     4.6.0 NVIDIA 495.44
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.44
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by AlexanderRavenheart** [comment]
I'm pretty sure it's been said multiple times in the forums and on the Discord channel: Don't run your games from a Windows (NTFS/FAT/exFAT) partition. It causes all sorts of issues that won't be solved anytime soon since those file system formats are not open-sourced.

**Comment by tannisroot** [comment]
The error should be handled though.

**Comment by adro79** [comment]
Not everyone is on this Discord server, specially the new users. I suggest some warning implementation and skipping this error, can be painful for the new users.

**Comment by tannisroot** [comment]
That's the plan

**Comment by strycore** [comment]
fixed
