### ISSUE TITLE
Hide "Add game" somewhere

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3896]
When helping people on our Discord, I've noticed many, many users like to use the "Add Game" menu to install games because it's the most intuitive part of the UI, thinking Lutris works like PoL, and they don't really explore the sources that Lutris provides.
The issue is that when they install games like that, they create broken installations that use default system wine and default $HOME/.wine prefix, which is very bad.
Ideally, the sources UX should be revamped, but for now, the menu can be hidden to force people to explore the 'Sources" section. Hiding it in the hamburger button menu would be ok.
![image](https://user-images.githubusercontent.com/10602045/145447978-5f59cbc0-ab5f-47b3-89ed-3c651a7d1dbf.png)

**Comment by strycore** [comment]
We're going to make that button the main way to add a game and search game installers so it's fine where it is.
