### ISSUE TITLE
Lutris Source search shows unpublished games

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3897]
![image](https://user-images.githubusercontent.com/10602045/145453869-bcbc6c6b-178d-4afc-9e7c-b49e3e00eefe.png)
This "game" is not published:
https://lutris.net/games/this-game-should-not-be-shown/

**Comment by danieljohnson2** [comment]
Hmm. This seems simple, I think. It appears that the Lutris server returns a dict for each game containing "is_public", which is True for most games but False for this one. We can just filter on that; I guess that indicates what is published.

I also noticed that the api.search_games() method returns None if there's a network problem, but the UI code does not understand this, so I added a bit of code to treat None as the empty list, too.

**Comment by strycore** [comment]
fixed in the new dialog, I added support for a with-installers parameter in the API
