### ISSUE TITLE
Provide resolution dimensions in a hex format

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3900]
Currently, Lutris provides resolution dimensions via the envars $RESOLUTION_WIDTH and $RESOLUTION_HEIGHT, which is incredibly useful.
However, some games have resolutions coded in the Wine registry as DWORDs, which are 6 character long hex numbers (1080 is `000438`, for example).
Right now, I workaround this with printf:
```
- execute:
    command: 'printf -v $RESOLUTION_HEIGHT_HEX '%06x\n' $RESOLUTION_HEIGHT'
```
It would be nice if Lutris could also expose hex variants of those envars by default.

**Comment by strycore** [comment]
fixed
