### ISSUE TITLE
Add migration for banners cache

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3906]
Since https://github.com/lutris/lutris/commit/db6c0f4e03395946c6f1dc0abcfe208cfd447056 changed the location for banners, Lutris should add a migration that will move banners that are already stored in the data dir location to the cache dir location.
Because right now, when you start Lutris, all games are missing banners, and Lutris does not seem to redownload them.

**Comment by danieljohnson2** [comment]
Hmm. What bothers me is that Lutris does not redownload missing banners. I actually have a branch that does download them when they are view (if missing).

But this seems like its intended, not a bug.

Can anyone tell me *why* Lutris won't redownload missing banners or icons?

**Comment by danieljohnson2** [comment]
On the other hand, why squander disk space? The migration seems pretty simple to do.
