### ISSUE TITLE
Redream runner shows with wrong styling

### ISSUE THREAD

**Issue by yuckyy** [lutris/lutris#3911]
Shows up with full, coloured logo, really massive. Screenshot attached
![2021-12-17_21-03](https://user-images.githubusercontent.com/60288171/146607719-84e70073-94f5-4ed6-94d8-a8aee15ab0de.png)
.

**Comment by tannisroot** [comment]
@strycore redream is dead, shouldn't be deprecated in favor of flycast?

**Comment by danieljohnson2** [comment]
This is happening because the 'Redream' runners symbolic icon is missing. It is falling back on a less symbolic icon, which is too big.

I've got a PR to resize that icon, which helps. But we could use a proper symbolic icon for it, but I don't really have the artistic talent to provide one.

**Comment by yuckyy** [comment]
> @strycore redream is kinda dead to OSS community, shouldn't it be deprecated in favor of flycast?

Redream is still a great emulator, although closed source, it is sometimes essential for running games.
