### ISSUE TITLE
[Feature Request] Option to add locally installed games in the Lutris Source view

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3950]
Currently you can only install games, and it works for installable games, but it's cumbersome at rom based games. 

A better idea would be to have an option to add "locally installed games" to the entry

**Comment by danieljohnson2** [comment]
Doesn't Lutris have this? You select the runner, click the "add" button in the header bar, and off you go. What's not to like?

**Comment by telanus** [comment]
> Doesn't Lutris have this? You select the runner, click the "add" button in the header bar, and off you go.

That's trueut my feature request is the option to add a game manually from the lutris source, not the runner. 
It would help , if you :
A) reinstalled you distro or distro hopped. The entry is already there and thus easier to add.
B) added a bunch of games on the website. Once synced it is the same, easier to add.

**Comment by danieljohnson2** [comment]
Oh, so more like the "Locate installed game" command available in the GOG source, but for some reason not in the Lutris source?

Seems like every source should have that one.

**Comment by danieljohnson2** [comment]
I see what it is- that option is available only on "DRM free" sources, specifically GOG and Humble Bundle. But it is also available for the 'platform' sections like "Windows", so once you get a game into your PGA you can use the command anyway, DRM or no.

I don't think this makes much sense. Even a source that uses DRM can have individual DRM free games, and if it has not, you can still install the game *from that source*, then want to link it in to Lutris.

**Comment by telanus** [comment]
@danieljohnson2 Dumb question, wouldn't be easier, and less code to change  drm_free = False  # DRM free games can be added to Lutris from an existing install to True in  lutris/services/base.py?

**Comment by danieljohnson2** [comment]
That would be a more local change, but it would also mean that drm_free would be misleading- it would always be true. Nothing else uses it *now*, but it would be an attractive nuisance for the future.

Alternately, we could just remove the check- then drm_free is no more misleading than before, but it is dead code. But the less code the better, and dead code is easy.

**Comment by strycore** [comment]
This will be made possible in the new "add game" window, it will allow scanning for existing game installs and also allow scanning folders for ROMs. 
We have a scanner that is mostly working for Retroarch, I've added support for a few platforms.

**Comment by strycore** [comment]
We can now import several ROMs at once with the drag and drop support.
Part of the ticket mentioning the Lutris source will be handled with the local to website library sync, which is tracked in #2925
