### ISSUE TITLE
Unsupported Graphics Card

### ISSUE THREAD

**Issue by BlazingCooper83** [lutris/lutris#3974]
Trying to open epic games launcher using lutris and get presented with the unsupported graphics card error.
Tried uninstalling and reinstalling to no success, also tried disabling dxvk and vkd3d in lutris and that isn't working either.
Running arch with kde plasma if that helps.

**Comment by juanbelieni** [comment]
I don't know if this is the same problem, but disabling DXVK worked for me. Reference: https://github.com/lutris/lutris/issues/2876#issuecomment-630410753

**Comment by strycore** [comment]
your drivers aren't properly installed. Don't forget to install both 64 and 32 bit variants of your graphics driver.

**Comment by kapcom01** [comment]
![εικόνα](https://user-images.githubusercontent.com/21684/156877535-d7ec5413-d400-4ae9-951f-e49a8dd2835e.png)
I am on Arch and I have installed lib32-mesa. I have an old integrated Intel GPU.
This error appears after th EGL update completes and tries to run. So I cannot install any games. I know it is not a problem with my games because if I use legendary I can install and play games because it bypasses EGL.

**Comment by SkyfallWasTaken** [comment]
@kapcom01 Did you find a solution to the issue?

**Comment by kapcom01** [comment]
> @kapcom01 Did you find a solution to the issue?

I stopped using this laptop for games.

**Comment by ilyaigpetrov** [comment]
> your drivers aren't properly installed. Don't forget to install both 64 and 32 bit variants of your graphics driver.

Is it even possible? I believe most Linux Distros dropped 32x support. Maybe there is some config in Lutris/wine/winetricks?

The error I get is `ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

<details>
  <summary>Log</summary>  
  <pre>
2022-12-23 08:40:11,099: Starting Lutris 0.5.12
2022-12-23 08:40:11,406: Running Intel Mesa driver 22.0.5 on Mesa Intel(R) HD Graphics 3000 (SNB GT2) (0x116)
2022-12-23 08:40:11,407: GPU: 8086:0116 17AA:21DA (i915 drivers)
2022-12-23 08:40:11,627: Startup complete
2022-12-23 08:40:14,816: Unable to load libGLX_nvidia.so.0
2022-12-23 08:40:14,816: Unable to locate libGLX_nvidia
Discord ID: 
2022-12-23 08:40:15,098: Discord RPC Disabled or Discord APP ID Not Present
Started initial process 31843 from gamemoderun /home/ilyaigpetrov/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/ilyaigpetrov/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
LogInit: Display: Command Line: "C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe" -opengl -SkipBuildPatchPrereq -SaveToUserDir -Messaging
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/DashedBorder.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/cursor_grab.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/cursor_cardinal_cross.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/TrashCan.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/TrashCan_Small.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Cross_12x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/denied_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_error_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_help_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_info_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_warning_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_Downloads_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_undo_16px.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_redo_16px.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Copy_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Cut_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Delete_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Paste_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Duplicate_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Edit/icon_Edit_Rename_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/PlusSymbol_12x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Cross_12x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/ellipsis_12x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/DashedBorder.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/ToolTip_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Border.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/eyedropper_16px.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_generic_toolbar.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_generic_toolbar.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_tab_toolbar_16px.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/toolbar_expand_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Button.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_tab_toolbar_16px.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/toolbar_expand_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Button.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background_Inverted_Border_Bold.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Notification_Border_Flash.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/notificationlist_success.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/notificationlist_fail.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/OuterDockingIndicator.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/DockingIndicator_Center.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/DockingIndicator_Center.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Tutorials/TutorialBorder.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Tutorials/TutorialShadow.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_tab_WidgetReflector_16x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_tab_WidgetReflector_40x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/icon_tab_WidgetReflector_40x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/MessageLog/Log_Error.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/MessageLog/Log_Warning.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/MessageLog/Log_Note.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/BackIcon.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/NextIcon.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Old/Menu_Background.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/ShowTabwellButton_Normal.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/ShowTabwellButton_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/ShowTabwellButton_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Normal.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_Inactive.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_Active.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_ColorOverlay.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_ColorOverlayIcon.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_Foreground.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/Tab_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/TabContentArea.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Normal.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/CloseApp_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_Inactive.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_Active.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_ColorOverlay.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_ColorOverlayIcon.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_Foreground.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTab_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Docking/AppTabContentArea.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../../Engine/Content/Slate/Icons/Empty_14x.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Window/Icon_Info.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialBang.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/Circle.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Sharing/FB.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/TabClose.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/UserCard/Portrait.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/UserCard/CalloutArrow.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/UserCard/Menu Background.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Tutorials/PulseHalo.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Tutorials/PulseCore.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/CloudSave/Cloud.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/CloudSave/Machine.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialCloseArrow.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/back_arrow.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/clipboard_graphic.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/Grayed_check.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/Green_Check.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/Error_inline.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/unfilled_check.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/BlueCheck_header.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Troubleshoot/error_big.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/epic.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-home.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-library.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-search.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-settings.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-social.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-store.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-download.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-profile.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-influencer.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/PrimaryNavBar/nav-ue.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialExpander_normal.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialExpander_normal.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialExpanderOpen_normal.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialExpanderOpen_normal.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/WindowBorder.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/FortniteGlobalChat.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialActionArrowLeft.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialActionArrowRight.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/SocialTipArrow.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/Circle.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/Circle.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/Circle.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Minimize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Maximize_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Restore_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/Close_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/UE/Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/UI/Library/EngineslotRemoveButton.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/DebugLogging_Close.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/DebugLogging_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Window/DebugLogging_Pressed.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn_hover.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/secondary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_left.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/primary_btn.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/EcosystemStyle/split_btn_right.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/TextBox.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/TextBox_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/TextBox_Hovered.png' error.
LogStreaming: Warning: Failed to read file '../../Content/New UI/Social/TextBox_ReadOnly.png' error.
LogStreaming: Warning: Failed to read file 'C:/ProgramData/Epic/EpicGamesLauncher/Data/Launcher.manifest' error.
LogWindows: Warning: Register touch input failed!
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Slate User Destroyed.  User Index 0, Is Virtual User: 0
Initial process has exited (return code: 0)
Monitored process exited.
Exit with return code 0
2022-12-23 08:40:35,113: Game still running (state: running)
2022-12-23 08:40:35,113: Stopping Epic Games Store (wine)
2022-12-23 08:40:35,114: Shutting down Lutris
2022-12-23 08:40:35,157: Shutting down Lutris
  </pre>
</details>

**Comment by ilyaigpetrov** [comment]
I resolved the issue by:
1) `sudo apt remove lutris` // Deleting Lutris.
2) `sudo apt autoremove` // Deleting dependencies.
3) `sudo apt install ./lutris_0.5.12_all.deb` // latest .deb from the official site.

**Comment by janek251** [comment]
I had the same problem too. I solved it by installation Wine from its official repository instead of Wine from Ubuntu repository.
