### ISSUE TITLE
"Run EXE inside wine prefix" for a game with disabled Lutris runtime still includes Lutris runtime

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#398]
If I set a game (not the runner or in the system) to "Disable Lutris Runtime" and then try to "Run EXE inside wine prefix" from the game's right-click menu, Lutris still includes its runtime in the execution.

**Comment by daniel-j** [comment]
Can confirm. Applies to wineexec in wine runner (run exe, regedit, probably winetricks..). Does not affect winecfg, since that never runs with runtime it seems.

**Comment by strycore** [comment]
Should be fixed by 5d3af3df95f213a2666a1f 
Please re-open if you still experience issues.

**Comment by strycore** [comment]
use the game settings
