### ISSUE TITLE
Black Screen while playing a wine game

### ISSUE THREAD

**Issue by Decapitater** [lutris/lutris#3984]
A rather specific issue , while playing a wine game (death stranding) i am experiencing black screens sometimes. 
This is rather odd and maybe game specific as another wine game (control) worked fine. However Interestingly the first game did not require lutris to run , but this one (death stranding) requires it as i cannot use it with bare wine , it requires either dxvk or dv39.

1. Os - arch
2.  Latest lutris
3.  wine 7. something detected by lutris

Help Would be appreciated 
@danieljohnson2 ?

**Comment by danieljohnson2** [comment]
I saw this item when it was posted- but I don't have "Death Stranding", don't run Arch, and so can't reproduce this.

If you want me to have any chance, you need to provide more information.

I suggest you fill out the bug report form. Include the "lutris -d" log output for a session were this happens. I can sometimes resolve bugs I can't reproduce if I can get a traceback, and that is the most likely place to find one.

It might also help if you can refine "sometimes" down- can you say *when* this happens? Is there something you can do that will trigger the bug it reliably? Without the game, I may not be able to use that- but maybe someone else can.

I'm not too optimistic though; fixing bugs that I cannot reproduce is always marginal. And this sounds likely to be an issue in the game, or with Wine, and both are a bit outside my competence.

**Comment by Decapitater** [comment]
Some more insights , will place the log in the next comment 

The bug seems to trigger when the load is somewhat more than usual ingame runs , in save zones etc .. the volume doesn't not stop and the movement and everything works fine it just goes black. The maximum time the screen stays black is 1.5 min. The black screen flashes and remains for 5sec and then works. 

Interestingly sometimes there is a wine error while running , a background service dies but the game does not stops it stops in a odd fashion in save area. Game starts reworking after killall the .exe and re running with lutris. 

Is it possible to get help from any other lutris devs those use arch ?,it would be really helpful

**Comment by Decapitater** [comment]
I stopped using lutris , this was a game specific and also for high power consumption , open/comment if needed
