### ISSUE TITLE
Preferences window doesn't open when running on aarch64 (RPI4/400, Manjaro)

### ISSUE THREAD

**Issue by midwan** [lutris/lutris#3988]
### Bug description

Testing on a Pi400 running the latest Manjaro XFCE (aarch64).
I installed lutris using `pacman -S lutris`, which also installed the dependencies. I can start it up normally, but I cannot open the preferences window.

Starting it from the console showed some more details:
If I try to open the Prefs window, it crashes with the following piece of the traceback:
```
"/usr/lib/python3.9/site-packages/lutris/util/linux.py", line 449, in gather_system_info_str 
cpu_dict["Vendor"] = system_info["cpus"][0]["vendor_id"] 
KeyError: 'vendor_id'
```

As the author of Amiberry, I was looking at how I could integrate it to Lutris so it can launch Amiga games (I know FS-UAE is already available). I could set up a "Linux" game hardcoding the emulator path and parameters to a game, and it worked as expected, so it would be interesting to fully integrate the emulator the "proper" way.
But the prefs window problem is a bit of a blocker for now. :)

### How to Reproduce

1. Use a Raspberry Pi 4 or Pi400, running the latest Manjaro XCFE
2. Install lutris using `pacman`
3. Run lutris from the console to see the messages
4. Try to open the Preferences window

### Expected behavior

The aarch64 CPU should be detected and the application should function normally (Prefs window should open).

### Log output

```shell
midwan@pi400 ~]$ lutris -d
2022-01-14 11:22:47,571: Unsupported architecture aarch64
2022-01-14 11:22:48,184: Starting Lutris 0.5.9.1
2022-01-14 11:22:48,273: No cores found
2022-01-14 11:22:49,327: Startup complete
INFO     2022-01-14 11:22:49,330 [startup.check_driver:61]:Running Broadcom Mesa driver 21.2.5 on V3D 4.2 (0xffffffff)
INFO     2022-01-14 11:22:49,331 [startup.check_driver:73]:GPU:   (v3d drivers)
INFO     2022-01-14 11:22:49,331 [startup.check_driver:73]:GPU:   (vc4-drm drivers)
WARNING  2022-01-14 11:22:49,336 [startup.check_vulkan:132]:Vulkan is not available or your system isn't Vulkan capable
DEBUG    2022-01-14 11:22:50,828 [lutriswindow.update_store:451]:Showing 1 games
WARNING  2022-01-14 11:22:54,937 [linux.get_arch:198]:Unsupported architecture aarch64
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 661, in on_preferences_activate
    self.application.show_window(PreferencesDialog)
  File "/usr/lib/python3.9/site-packages/lutris/gui/application.py", line 254, in show_window
    window_inst = window_class(parent=self.window, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/gui/config/preferences_dialog.py", line 50, in __init__
    self.build_scrolled_window(SysInfoBox()),
  File "/usr/lib/python3.9/site-packages/lutris/gui/config/sysinfo_box.py", line 31, in __init__
    sysinfo_str = gather_system_info_str()
  File "/usr/lib/python3.9/site-packages/lutris/util/linux.py", line 449, in gather_system_info_str
    cpu_dict["Vendor"] = system_info["cpus"][0]["vendor_id"]
KeyError: 'vendor_id'
INFO     2022-01-14 11:22:56,229 [application.do_shutdown:631]:Shutting down Lutris
```

### System Information

```shell
unable to generate, preferences window doesn't open.
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I don't have aarch64, an the log says Lutris does not support it, so this is probably not going to help too much.

But... the crash is because Linux is not supplying the vendor_id fields in /proc/cpuinfo. This is apparently (I read) normal on aarch64, and won't be fixed.

I've queued up a PR to tolerate missing fields of this kind, so the preferences can be displayed anyway. Even if Lutris will never run on ARM, it's is better to be robust about this- after all, maybe a future Linux kernel will rename one of these guys and break Lutris that way.

**Comment by danieljohnson2** [comment]
Well, I can't test it, but hopefully with my PR in you can at least get further. But I expect there'll be more issues.
