### ISSUE TITLE
Lutris runtime gives "unable to load" libgl driver errors w/ winesteam runner

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#400]
```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  986
Current serial number in output stream: 990
```

**Comment by daniel-j** [comment]
Can confirm, tried both system wine-staging and wine1.8-i386 from lutris.
Was a bit annoying to debug due to #399.

**Comment by strycore** [comment]
This is not blocking for the release of lutris 0.4.0 since runtime updates can be pushed at any time.

Also, disabling the runtime should reliably work now.

**Comment by strycore** [comment]
I've tried Winesteam on my Intel based laptop and it works fine. Is this specific to Arch?

**Comment by strycore** [comment]
I managed to reproduce the bug on my Arch VM, I'l try to find a small game I can use to fix the issue to avoid having to launch Steam every time. (If anyone has any suggestions…)

**Comment by strycore** [comment]
Nevermind, I managed to break my Arch VM so someone else will have to do this. 
Currently, I only know that the lib causing the issue is in 'runtime/lib32'. Try removing some libs until wine works and send me the name of the lib so I can distribute an update.

**Comment by strycore** [comment]
Btw the trick is to use a classic bisect method. Divide the libs in 2 folders (ie, a 'lib64' and a 'lib64.bak') and copy half the libs to lib64 and see if wine crashes with the runtime. Keep adding another half when there is no crash or remove the infringing half when there is.

**Comment by strycore** [comment]
Instructions for reporting runtime issues are available here: http://wiki.lutris.net/index.php/Runtime
