### ISSUE TITLE
"Failed to initialize video backend" with Lutris but not Dolphin

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#4030]
### Bug description

When I run lutris on Debian11/KDE with Wayland and start a Gamecube game iso this message is shown in an error message window (which has the title "Question" and the buttons "OK" and "Ignore for this session").

The console output is:
```
Starting Lutris 0.5.9.1
No cores found
Startup complete
Running ...
GPU: ...
Vulkan is not available or your system isn't Vulkan capable
Started initial process 1..... from gamemoderun /home/username/.local/share/lutris/runners/dolphin/dolphin-emu -e /home/username/Games/dir/game.iso
Start monitoring process.
```
When I start the same game iso directly with Dolphin it works. Another game iso did work with Lutris.

### How to Reproduce

1. Go to 'Library'->'Games' and start a Gamecube game by double click (or add a game before doing so; I tried readding it but that didn't help) on Debian11/KDE
2. Wait approximately 1 second

### Expected behavior

Start the game

### Log output

```shell
Starting Lutris 0.5.9.1
No cores found
Startup complete
INFO     [startup.check_driver:61]:Running ...
INFO     [startup.check_driver:73]:GPU: ...
WARNING  [startup.check_vulkan:132]:Vulkan is not available or your system isn't Vulkan capable
DEBUG    [lutriswindow.update_store:451]:Showing .. games
DEBUG    [grid.on_item_activated:57]:Item activated: ...
DEBUG    [lutriswindow.on_game_activated:833]:No service for view
DEBUG    [xrandr._get_vidmodes:14]:Retrieving video modes from XrandR
DEBUG    [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    [command.start:139]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    [command.start:139]:LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:/lib/i386-linux-gnu:/usr/lib32:/lib32:/usr/local/lib:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib:/lib64:/lib64:/home/username/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/username/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/username/.local/share/lutris/runtime/steam/i386/lib:/home/username/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/username/.local/share/lutris/runtime/steam/i386/usr/lib:/home/username/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/username/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/username/.local/share/lutris/runtime/steam/amd64/lib:/home/username/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/username/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    [command.start:139]:game_name="gamename"
DEBUG    [command.start:139]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/home/username/.local/lib/python3.9/site-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages"
DEBUG    [command.start:139]:LUTRIS_GAME_UUID="..."
Started initial process 1870076 from gamemoderun /home/username/.local/share/lutris/runners/dolphin/dolphin-emu -e /home/username/dir/gamename.iso
Start monitoring process.
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 11 bullseye
Arch:            x86_64
Kernel:          5.10.0-11-amd64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           [...]
Physical cores:  [...]
Logical cores:   [...]

[Memory]
RAM:             [...] GB
Swap:            [...] GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL Core:     4.6 (Core Profile) Mesa 20.3.5
OpenGL ES:       OpenGL ES 3.2 Mesa 20.3.5
Vulkan:          Not Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by tannisroot** [comment]
Weird how your system info is incomplete

**Comment by mYnDstrEAm** [comment]
Is any of the excluded info relevant to this issue? I replaced it with dots in the log output and the system info.

**Comment by tannisroot** [comment]
It very much is

**Comment by tannisroot** [comment]
Please never replace system info like that without telling you did so

**Comment by mYnDstrEAm** [comment]
Sorry, it really shouldn't be related to the cause of this because 
When I start the same game iso directly with Dolphin it works. Another game iso did work with Lutris.
What could be causes if it works with Dolphin but not Lutris?

**Comment by tannisroot** [comment]
This is either caused by Lutris for whatever reason failing to check if Vulkan works on your system (due to your possibly funky Vulkan setup, which I can't help with because you are not sharing the information) or due to a difference in Dolphin versions. I think the former is likely the true reason.
But I can't really help without such basic information.

**Comment by mYnDstrEAm** [comment]
I added system info. Any ideas how it's being caused so far with this?

Also there may be problems with the Dolphin version. When I try to import games (see https://github.com/lutris/lutris/issues/2854) by clicking the refresh button next to Dolphin under Sources, it says "Incompatible Dolphin version" and it has this error in the console (after the line `Vulkan is not available or your system isn't Vulkan capable`):

```
Error while completing task <bound method BaseService.reload of <dolphin.DolphinService object at 0x7fa2f81bfd80 (lutris+services+dolphin+DolphinService at 0x3a40c20)>>: <class 'Exception'> Incompatible Dolphin version
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 83, in reload
    self.load()
  File "/usr/lib/python3/dist-packages/lutris/services/dolphin.py", line 36, in load
    cache_reader = DolphinCacheReader()
  File "/usr/lib/python3/dist-packages/lutris/util/dolphin/cache_reader.py", line 68, in __init__
    raise Exception('Incompatible Dolphin version')
)
```
I intend(ed) to create a new issue about this problem. The solution may be to simply build the latest version of Dolphin on Debian (there not being a repo with a prebuilt Dolphin for Debian or it being in the official repos is another problem). I have Dolphin 5.0. However, if that's the solution it may also cause games to stop working under Dolphin because they do work currently in Dolphin but aren't working in Lutris.

**Comment by mYnDstrEAm** [comment]
I built the latest Dolphin version and now I have this problem both in Dolphin and when starting the game with Lutris. Dolphin doesn't have issues enabled in its repo. The version of Dolphin is 5.0-17197 and there is no useful output in the console after launching the game, only:
```
Start monitoring process.
Monitored process exited.
No return code
Game still running (state: running)
Stopping {game name} (dolphin)
The game has run for a very short time, did it crash?
```
If easy to answer: how are runners upgraded with Lutris? In the case of Dolphin on Debian11 are you supposed to build Dolphin and then copy the binary to a specific folder (where the previous executable was located)? If so how is this path set?

**Comment by danieljohnson2** [comment]
Sounds like a Dolphin issue, not a Lutris one.

Lutris will automatically download a new version of Dolphin. I believe this happens when it is published on the Lutris website, not when it is first released by the Dolphin project, however, so there may be a delay on this after they fix this issue.

The error you are getting in that back-trace you had was replaced with a warning in Lutris 0.5.10. If you are still on 0.5.9.1, you should probably upgrade to a more recent Lutris.

**Comment by mYnDstrEAm** [comment]
Thanks, the problem was that the Lutris repo wasn't upgraded during my Debian10->11 upgrade.

I removed the Dolphin runner and added it again. There may have been an issue with the previous Dolphin runner on this machine as iirc, it only showed 5.0 and not the specific version in the About window.

After doing so, the version of Dolphin is 5.0-14480. Is that the correct version or should it be 5.0-11824? This error still occurs with Dolphin 5.0-14480.

On another machine I only upgraded Lutris and didn't change anything Dolphin-related. There Dolphin is at version 5.0-11824 (it doesn't ask for an update or anything and I didn't remove and readd it) and works just like it did before.

(Security concerns in regards to downloading runners would probably be a separate question/issue as it would need checks for verified hashsums of the downloaded files to make sure they are genuine but if there already is an issue about this, I'd be interested.)

**Comment by danieljohnson2** [comment]
I get Dolphin 5.0-14480 when I install it. I'm not a user and am not familiar with Dolphin verisons.

Security concerns are concerning, and maybe it would be better to cryptographically sign everything, though I'm not sure how to work that. How does an open source project like this one keep the signing keys secret?

I will note that at least Lutris puts everything it can through SSL, so it should be hard to man-in-the-middle your download. But malware injected into the server- say via a 'helpful' PR- is a possibility, to be sure.

Someone who managed that could inject malware into Lutris proper, as well, mind. But perhaps your local OS's repository's management would catch that. I'm a little skeptical, but maybe.

Security is hard.

**Comment by mYnDstrEAm** [comment]
It's a Dolphin issue, also getting this with Dolphin without Lutris now - the bug report is here: https://bugs.dolphin-emu.org/issues/13086

**Comment by mylesbartlett72** [comment]
it might be because dolphin does not support wayland (or at least not properly)

does it work if you run lutris with `env -u WAYLAND_DISPLAY lutris`?  (this forces xwayland)

**Comment by strycore** [comment]
Maybe the solution is to stick with an older version of Dolphin? 
We have some available referenced here: https://lutris.net/api/runners/dolphin

Lutris only support runners versions with wine so these will have to be downloaded manually and placed in ~/.local/share/lutris/runners/

Also, if some runners don't support Wayland well, try them with Gamescope

**Comment by mylesbartlett72** [comment]
I think I saw a way to do it with an environment variable that tells Qt to run in xwayland, but i had to reimage my system and cant remember what it was

you have to restart dolphin after you close a game or it wont launch another even if you do

you can also make a wrapper script as a custom executable that unsets `WAYLAND_DISPLAY`
