### ISSUE TITLE
Resolve issues with curl/wget when certain libraries are shipped in runtime

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#4035]
When I tried adding more libraries to Lutris Runtime, it created an issue where installers that tried to utilize programs like wget/curl to download stuff would not work, since those programs, which are installed system wide from distro's repositories and not by Lutris, would try to load libraries from Lutris runtime, which are far older the ones curl/wget expect and thus incompatible.
There are 2 possible solution to this:
1) Ship curl/wget in our runtime. I've already added the programs to runtime as a network-tools package, the client just needs to be hooked up to use them instead of system ones.
**Pros**:
   Installers can always expect curl/wget to be available for usage
**Cons**:
   Creates an additional burden on runtime maintenance
   Possible worsened functionality due to us shipping outdated libraries in runtime
2) Do not pass the envars that specify Lutris runtime for these programs to avoid library incompatibility
**Pros**:
   Less work for us
   If something doesn't work, blame can be put on distributions and not on us.
**Cons:**
   Installers _can't_ expect curl/wget to be available for usage for all users

Ideally, those programs should not be needed for installers at all, but are due to lacking functionality of Lutris' fetching functionality in installers

**Comment by strycore** [comment]
> Ideally, those programs should not be needed for installers at all, but are due to lacking functionality of Lutris' fetching functionality in installers

That should be the priority imo, we should add whatever is needed to lutris to make curl and wget unneeded. 
Since we already have wget and curl available in the runtime, why not use them.

**Comment by tannisroot** [comment]
Yes
https://lutris.net/games/balsamiq-wireframes/

**Comment by strycore** [comment]
the network-tools folder is now added to $PATH.
This doesn't work if an installer or script calls /usr/bin/curl

**Comment by reidswanson** [comment]
Sorry to butt in, but I've been trying to install balsamiq-wireframes without success because of an error with libcurl and was wondering if this issue was the source of my problem. 

Running the following:
`lutris -id "https://raw.githubusercontent.com/balsamiq/balsamiq-wireframes-linux/master/balsamiq-wireframes-installer.json"`

results in the error:
```
curl: /usr/lib64/libcurl.so.4: no version information available (required by curl)
VERSION=
curl: /usr/lib64/libcurl.so.4: no version information available (required by curl)
curl: (48) An unknown option was passed in to libcurl
Initial process has exited (return code: 12288)
```

I run Gentoo with lutris 0.5.10.1 and curl 7.79.1
