### ISSUE TITLE
WINE-runner disable winemenubuilder by default

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#404]
the winemenubuilder should be disabled by default, since it never really worked eg. every wineprefixcreate will make wine notepad app the default editor for any text files)

its also not very useful in case that wine is used just as installer/extractor to get the game files(it will create menu and desktop entries for something that doesnt exist)

---------------------------
secondly the should be an option to to enable to the enable winetricks sandbox mode. This will make wine independent from your system(eg Home folder is C:\users\NAME instead of ~) the only downside of this is that it will also prevent this prefix from running files outside its prefix

also instead of a sandbox mode lutris could also set the HOME variable to the gamedir see: https://github.com/lutris/lutris/issues/329

**Comment by strycore** [comment]
I was comparing the sandbox implementation in winetricks with our equivalent implementation ( https://github.com/lutris/lutris/blob/master/lutris/runners/wine.py#L217 ) and winetricks has something more going on:

    # Disable unixfs
    # Unfortunately, when you run with a different version of Wine, Wine will recreate this key.
    # See http://bugs.winehq.org/show_bug.cgi?id=22450
    "$WINE" regedit /d 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\Namespace\{9D20AAE8-0625-44B0-9CA7-71889C2254D9}'

    # Disable recreation of the above key - or any updating of the registry - when running with a newer version of Wine.
    echo disable > "$WINEPREFIX/.update-timestamp"

Is this part needed or can we stick with what we currently have? I'm not sure about the "any updating of the registry" part of this, it could have some unwanted side effects and if there is any reason to actually delete this registry key, we can do it at runtime.

**Comment by sixsixfive** [comment]
the best would be to force the homedir to the gamedir for all wine applications the reason for this is that you dont know for sure what the appication does (eg a multiuser windows application will be installed inside the users homedir. For wine this would mean that the application is installed in /home/<user>/documents and not inside the gamedir)

**Comment by strycore** [comment]
Now, disabling winemenubuilder and sandbox mode will be applied at after each prefix creation and before launching any Wine game. The current implementation doesn't use Wine at all so it's very fast.
