### ISSUE TITLE
Lutris leaves behind dead winedevice processes

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#4046]
How to reproduce:
1) Launch a Wine game through Lutris
2) Stop it
Result: all wine processes are killed but winedevice.exe, which persists and can only be terminated via "sigkill".

I am not really sure why this happens, I haven't looked at our process monitoring code but just using wineserver to shut things down shouldn't leave any processes behind.

**Comment by danieljohnson2** [comment]
After some experimentation, I get two winedevice processes and only one dies when I hit stop.

It's trying to kill them both with SIGTERM, but one winedevice refuses to die. The stop button does not use wineserver -k, but the separate "kill all wine processes" does- and it does not seem to kill winedevice either.

I tried changing it to SIGKILL, and that works. But is that appropriate for the Stop command? I might have it try SIGTERM, and if that does not kill everything in a few seconds, try SIGKILL on the survivors.

I understand SIGKILL is supposed to be unsafe, but it seems to me that "Stop" should be more assertive than a polite request.

**Comment by danieljohnson2** [comment]
Yes, I did a test and wineserver was the very first process to get SIGTERM.  But that was just one test; it might not be stable. Still, at least once, winedevice went later, and one winedevice survived.

**Comment by tannisroot** [comment]
Yeah wineserver definitely should not be SIGTERM-ed first, if at all.

**Comment by tannisroot** [comment]
Also, I think only one instance of winedevice.exe is present in a prefix instance, all previous ones must be leftovers from previous runs.

**Comment by danieljohnson2** [comment]
Hmm, I've been killing all winedevices before testing. It starts two every time.

**Comment by danieljohnson2** [comment]
Well, this may be too extreme but I have found nothing less that works, except for just SIGKILLing everything willy-nilly. So, have a PR.

**Comment by tannisroot** [comment]
Have you tried executing `wineserver -k` first, before sigterm?

**Comment by tannisroot** [comment]
Or not sending sigterm to wineserver

**Comment by danieljohnson2** [comment]
I did not; getting this to be different for WINE games will be trickier.

But I did observe that wineserver -k *does not* kill the extra winedevice process, so I figured it was not worth bothering with it. Any reason to think that wineserver -k followed by SIGTERM will be better?

Not sure why you'd want to spare wineserver though.

**Comment by bigalmax** [comment]
I am also getting a rogue winedevice hang when exiting certain games such as GOG Pathfinder WotR so far.  When trying the stop button or when "killing all wine processes" - it kills everything under Lutris and then an instance of winedevice hangs separately. Have also tried wineserver -k - no effect. Hope this info helps.

**Comment by tannisroot** [comment]
@danieljohnson2 wineserver will not kill extra winedevice processes because they were not launched in its instance, after wineserver is dead, those processes becomes "zombies".
> Any reason to think that wineserver -k followed by SIGTERM will be better?
Because with `wineserver -k`, the prefix processes will exit first, such as winedevice.exe, and only then wineserver will exit on its own, gracefully.
And SIGTERM should not even be really needed.
> Not sure why you'd want to spare wineserver though.
Because it's able to shut down on its own. If it doesn't (like if it crashes,) and becomes unresponsive, it can be killed after a certain time out with SIGKILL.

**Comment by danieljohnson2** [comment]
I wonder where the extra winedevice came from, if it was not the wineserver that runs the game.

In any case, I'll defend the current design. Stop is, I think, *meant* to be rude. It's for games that are "stuck", not normally functioning games. If they worked properly, you'd just exit the game.

That is why SIGKILL is reasonable at all. The question is: should it wait at all, or just keep it simple and SIGKILL right out of the gate.

There is actually a separate command entirely ("Kill all WINE processes") that issues 'wineserver -k', if that's what you want. There's no need to re-purpose Stop to do that.

**Comment by nzbtuxnews** [comment]
I am observing something very similar with lutris 0.5.9.1.   When I close the game, 8 times out of 10, the wine destop remains and the STOP button has to be pressed.  Sometimes, it doesnt close the desktop and tons of .exe processes are still running in the background.  If the STOP button closes the Wine desktop, often there will be many remaining .exe processes in the background.

Pretty much the only way to make sure that all processes are closed after I am done with the game is to use htop and kill them one by one (fastidious).

This screenshot is from htop after a game while the wine desktop was stuck open and the game was not exiting.  After pressing STOP, most of the processes disappeared but most of the "winedevice.exe" stayed behind and had to be killed with SIGKILL

![Screenshot_2022-02-20_20-41-44](https://user-images.githubusercontent.com/1290357/154876482-6e47ca43-9fc9-43fb-9533-b2d6454aa208.png)

System specs
Kernel: 5.4.0-100-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Gnome 3.36.9 
wm: xfwm4 dm: GDM3, LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
AMD Phenom II X4 965 bits: 64 type: MCP arch: K10 rev: 3 
NVIDIA GP108 [GeForce GT 1030] vendor: ASUSTeK driver: nvidia v: 470.103.01 
Display: x11 server: X.Org 1.20.13 driver: nvidia 
resolution: 1920x1080~60Hz, 3440x1440~60Hz 
OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 470.103.01 
direct render: Yes 
DXVK enabled (ver 1.9.1L)
Wine: lutris-6.13-3-x86_64
VKD3D version: v2.5L-c0a3fa8
DXVK NVAPI ver v0.5-e23d450

**Comment by tannisroot** [comment]
> That is why SIGKILL is reasonable at all. The question is: should it wait at all, or just keep it simple and SIGKILL right out of the gate.

I just really don't like the use SIGKILL because it's trying to solve the symptoms and not the root cause, which is wineserver being killed before some of the processes.
What if sigterm is sent to all processes but wineserver, and after they all exited and if wineserver is still alive, sigterm is sent to wineserver too?

**Comment by danieljohnson2** [comment]
I've experimented further with this, and found a second solution, but I don't think it's acceptable as-is.

I modified the Stop command to just send SIGTERM and to skip wineserver (by checking for 'wineserver' in the process command line) and I also neutered the signal handling in lutris-wrapper, so that if you SIGTERM that it does not in turn SIGTERM anything itself.

That actually worked! All processes did die in my test case, and with no five second delay either.

I did further testing, restoring lutirs-wrapper and instead skipping wineserver and lutris-wrapper. This did stop winedevice and wineserver somehow, but the game itself did not stop (!).

But I consider these changes too broken to use. I completely broke lutris-wrapper's signal propagation. The new 'Stop' logic is clearly WINE specific. I could rewrite the Stop logic so that WINE is a special case, but getting lutris-wrapper to also be so seems much tougher, and I can't believe it's okay to just break the signal propagation like this.

So I ask you, *is SIGKILL so wrong*? It still seems to be me like the better option. It gets the job done, albeit after a delay sometimes, and works on anything, not just WINE. WINE is surely not the recalcitrant thing we want to stop, right?

If SIGKILL is absolutely verboten, I'd still not want to use this second fix as it is. I'd just not fix this bug, and let the user kill winedevice manually if he likes.

**Comment by nzbtuxnews** [comment]
I'm nowhere close to you guys in understanding how all of this works, but what I currently do is more or less throw a nuclear bomb in wine to kill everything at once....

I dont really care if the processes are exiting peacefully and the proper way, as long as when I am done with the game, NO .exe processes remain running indefinitely.

As a matter of fact, I'd vote for the STOP button to do exactly what I manually do, that is, kill everything but the lutris process itself (of course ;).  Am I wrong to understand that the problem may partially reside with the poor design of wine or these games not gracefully exiting ?  If its the case then yes, I fully stand behind the "nuclear option"...

**Comment by danieljohnson2** [comment]
SIGKILL them all and let root sort them out?

A PR for that would be easy, but @strycore has asked me not to give him choose-your-own-adventure PRs, so I'm sticking with the PR I think best.

I think @strycore will likely have to make the call on this.

**Comment by danieljohnson2** [comment]
So 'Stop' *should* be different for WINE. But I observe that 'Kill all Wine processes' does not get all the winedevice processes. It does wineserver -k, but that seems not to be enough. Do we resort to SIGKILL then, or what?

**Comment by danieljohnson2** [comment]
'Kay. It'll take some time for me to put that together. I'll leave my old PR alive until ready to replace it, in case you feel the need to ship any fix, even if its not really right.

**Comment by danieljohnson2** [comment]
OK, there's another try. This time 'Stop' is polymorphic- for non WINE games it behaves as before (SIGTERM), but for WINE it issues 'wineserver -k'. In either case, there's an up-to-5-second wait and then any surviving processes get SIGKILL. Also, I removed 'Kill all WINE processes' from the menu.

In my testing this behaves just a bit differently- both winedevice processes do die promptly when 'wineserver -k' goes off, but there's *another* process that's not quite dead. I can't tell what it is- it has no command line, no environment, nothing that I can see. Some kind of zombie? Anyway, it holds up the Stop for 5 seconds, then gets SIGKILL.
