### ISSUE TITLE
Lutris doesn't create coverart folder

### ISSUE THREAD

**Issue by Tibladar** [lutris/lutris#4049]
### Bug description

After upgrading Lutris to v0.5.10-beta1 at every start a popup is shown with the text
`[Errno 2] No such file or directory: '/home/user/.cache/lutris/coverart'`

After clicking 'OK' Lutris starts normal
Restarting Lutris displays the popup again since the folder isn't created

Manually creating the 'coverart' folder works and Lutris starts fine

### How to Reproduce

1. Have v0.5.9.1 installed
2. Install v0.5.10-beta1
3. Open Lutris
4. See popup

### Expected behavior

Lutris shouldn't display a popup but create the missing folder

### Log output

```shell
INFO     2022-02-12 17:06:00,408 [startup.init_lutris:164]:Starting Lutris 0.5.10
WARNING  2022-02-12 17:06:00,427 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-02-12 17:06:00,432 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-02-12 17:06:00,458 [startup.check_driver:65]:Running AMD Mesa driver 21.3.6 on AMD Radeon RX 5700 (NAVI10, DRM 3.44.0, 5.13.0-generic, LLVM 13.0.0) (0x731f)
INFO     2022-02-12 17:06:00,458 [startup.check_driver:77]:GPU: 1002:731F 148C:2398 (amdgpu drivers)
ERROR    2022-02-12 17:06:00,489 [jobs.target:36]:Error while completing task <bound method LutrisInitDialog.initialize of <dialogs.LutrisInitDialog object at 0x7fa950b9aac0 (lutris+gui+dialogs+LutrisInitDialog at 0x1aac2b0)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/user/.cache/lutris/coverart'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/__init__.py", line 195, in initialize
    init_lutris()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 201, in update_runtime
    sync_media()
  File "/usr/lib/python3/dist-packages/lutris/services/lutris.py", line 159, in sync_media
    covers_available = {fn.split(".")[0] for fn in os.listdir(settings.COVERART_PATH)}
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by runboy93** [comment]
![lutris0510beta1error](https://user-images.githubusercontent.com/21213705/153721432-239df54c-cac4-4f3a-940b-ad5eb93a3896.png)

**Comment by runboy93** [comment]
And yeah, when manually creating empty folder called "coverart" to location "/home/user/.cache/lutris/x" there are no error anymore, as workaround.

`
INFO     2022-02-14 21:47:02,120 [startup.init_lutris:164]:Starting Lutris 0.5.10
WARNING  2022-02-14 21:47:02,147 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-02-14 21:47:02,154 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-02-14 21:47:02,186 [startup.check_driver:57]:Using NVIDIA drivers 510.47.03 for x86_64
INFO     2022-02-14 21:47:02,186 [startup.check_driver:61]:GPU: Unknown
INFO     2022-02-14 21:47:02,186 [startup.check_driver:77]:GPU: 10DE:1D10 1025:1220 (nvidia drivers)
INFO     2022-02-14 21:47:02,186 [startup.check_driver:77]:GPU: 8086:5917 1025:1220 (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

INFO     2022-02-14 21:47:02,265 [startup.update_runtime:203]:Startup complete
DEBUG    2022-02-14 21:47:02,468 [lutriswindow.update_store:431]:Showing 0 games
`
