### ISSUE TITLE
TIC-80 runner logo larger than any others

### ISSUE THREAD

**Issue by Evilhotdog** [lutris/lutris#4051]
### Bug description

The logo for the runner of the TIC-80 is several times larger than any of the others

### How to Reproduce

1. Add the TIC-80 runner
2. Return to the main screen
3. TIC-80 logo is too big 

### Expected behavior

TIC-80 logo should be the same size as the others (Wine, Steam, Web, etc)

### Log output

```shell
2022-02-12 18:03:40,773: Starting Lutris 0.5.9.1
2022-02-12 18:03:40,782: No cores found
2022-02-12 18:03:41,471: Startup complete
INFO     2022-02-12 18:03:41,472 [startup.check_driver:61]:Running AMD Mesa driver 21.3.5 on AMD Radeon RX 5600 XT (NAVI10, DRM 3.44.0, 5.16.8-arch1-1, LLVM 13.0.0) (0x731f)
INFO     2022-02-12 18:03:41,472 [startup.check_driver:73]:GPU: 1002:731F 1682:5710 (amdgpu drivers)
ERROR    2022-02-12 18:03:41,568 [i18n.get_user_locale:10]:Unable to get locale
DEBUG    2022-02-12 18:03:41,833 [lutriswindow.update_store:451]:Showing 0 games
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.16.8-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            16.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5600 XT (NAVI10, DRM 3.44.0, 5.16.8-arch1-1, LLVM 13.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.5
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.5
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.5
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by runboy93** [comment]
![TIC80logosize](https://user-images.githubusercontent.com/21213705/153724003-0d3de8ba-c5ca-47d5-bb3f-c42e0b20e696.png)

This is normal size?

**Comment by Evilhotdog** [comment]
Thanks!
