### ISSUE TITLE
Ubisoft Connect can't download games

### ISSUE THREAD

**Issue by ienzo** [lutris/lutris#4058]
I am using 0.5.10. Downloaded it just now. 
I added Ubisoft to the list of approved sources.
I logged into ubisoft just fine. 
I attempted to install Assassin's Creed Unity by pressing the install button. Nothing happens. 
![image](https://user-images.githubusercontent.com/4653894/153752484-53fe8228-835a-4d91-a5f4-8a79af1a9ca8.png)

I'm using: 
`OS: Linux Mint 20.3 x86_64`
`Kernel: 5.4.0-99-generic`

**Comment by dubigrasu** [comment]
Similar on Ubuntu 20 LTS.

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 516, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 225, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/ubisoft.py", line 207, in generate_installer
    ubisoft_connect = Game(ubi_db_game["id"])
KeyError: 'id'

**Comment by ienzo** [comment]
I ran Lutris in deubug mode, went to the Ubisoft Connect tab, and tried to install AC Rogue. Again, nothing happened. This is the output:

```

INFO     2022-02-16 18:18:59,943 [startup.init_lutris:164]:Starting Lutris 0.5.10
WARNING  2022-02-16 18:18:59,984 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-02-16 18:18:59,993 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-02-16 18:19:00,027 [startup.check_driver:57]:Using NVIDIA drivers 510.47.03 for x86_64
INFO     2022-02-16 18:19:00,027 [startup.check_driver:61]:GPU: Unknown
INFO     2022-02-16 18:19:00,027 [startup.check_driver:77]:GPU: 10DE:134D 1025:1133 (nvidia drivers)
INFO     2022-02-16 18:19:00,027 [startup.check_driver:77]:GPU: 8086:5916 1025:1133 (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ERROR    2022-02-16 18:19:00,112 [jobs.target:36]:Error while completing task <bound method LutrisInitDialog.initialize of <dialogs.LutrisInitDialog object at 0x7fcc1c52a500 (lutris+gui+dialogs+LutrisInitDialog at 0x1784330)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/miggoy/.cache/lutris/coverart'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/__init__.py", line 195, in initialize
    init_lutris()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 201, in update_runtime
    sync_media()
  File "/usr/lib/python3/dist-packages/lutris/services/lutris.py", line 159, in sync_media
    covers_available = {fn.split(".")[0] for fn in os.listdir(settings.COVERART_PATH)}
DEBUG    2022-02-16 18:19:02,244 [lutriswindow.update_store:431]:Showing 97 games
DEBUG    2022-02-16 18:19:04,465 [lutriswindow.update_store:431]:Showing 11 games
DEBUG    2022-02-16 18:19:09,703 [base.install:209]:Installing 3499bde3-6f0e-4ddc-84fb-736f93078be2 from service ubisoft
DEBUG    2022-02-16 18:19:09,704 [http.get:83]:GET https://lutris.net/api/games/service/ubisoft
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 516, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 225, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/ubisoft.py", line 208, in generate_installer
    uc_exe = ubisoft_connect.config.game_config["exe"]
AttributeError: 'NoneType' object has no attribute 'game_config'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_games_lutris.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 516, in on_game_install
    game_id = service.install(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 225, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3/dist-packages/lutris/services/ubisoft.py", line 208, in generate_installer
    uc_exe = ubisoft_connect.config.game_config["exe"]
AttributeError: 'NoneType' object has no attribute 'game_config'
INFO     2022-02-16 18:19:17,245 [application.do_shutdown:653]:Shutting down Lutris

```

I hope this helps.

**Comment by strycore** [comment]
It's missing the actual Ubisoft Connect client. Lutris should install it if it's not available but looks like it doesn't.

You can install Ubisoft Connect from the website installer and try again.

**Comment by strycore** [comment]
Lutris will now install the Ubisoft Client if needed

**Comment by Megalomaniak** [comment]
I get an `[Errno 2] No such file or directory '/run/media/user/GAMES/ubisoft/drive_c/Program Files (x68)/Ubisoft/Ubisoft Game Launcher/cache/configuration/configurations'` after letting lutris install the Ubi Client. BTW, I really dislike how the lutris errors are never highlightable text and can't be copied - having to hand type it out like this. That's just bad UX.

**Comment by danieljohnson2** [comment]
Well, if you'd like support you'll have better luck posting the "lutris -d" log output, not just the error message. And perhaps in a new item, not a closed one.

But uncopyable error text is lame, so I've just added code in master to make it selectable; you can right click now to get 'Select all' and 'Copy' commands. Or you will be able to, in the next Lutris release.

**Comment by Megalomaniak** [comment]
No worries, I wasn't expecting the issue here to be reopened or something, just fishing to see if someone who had experienced and followed this issue might have also seen this error and might have some advice on it. But as the edit above said, I did figure it out. :)

> But uncopyable error text is lame, so I've just added code in master to make it selectable; you can right click now to get 'Select all' and 'Copy' commands. Or you will be able to, in the next Lutris release.

That's great! I appreciate it a lot.
