### ISSUE TITLE
This message only shows up in CLI: "Steam for Linux installation is not handled by Lutris"

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#406]
It should show up in a popup. I think it did in the past? I'm labelling this as a bug.

**Comment by strycore** [comment]
Didn't I fix this a few days ago? At least in the runners dialog

**Comment by strycore** [comment]
I pushed a fix for another bug and now the error dialog shows when installing a game from the website or manually trying to install the runner.
