### ISSUE TITLE
Cannot update translations because runners.py is missing

### ISSUE THREAD

**Issue by Vistaus** [lutris/lutris#4062]
### Bug description

I'm running

ninja lutris-update-po -C builddir

but it fails.

### How to Reproduce

1. Run ninja lutris-update-po -C builddir
2. Watch it fail:

```
~ ninja lutris-update-po -C builddir
ninja: Entering directory `builddir'
[0/1] Running external command lutris-update-po (wrapped by meson to set env)
xgettext: error opening 'lutris/gui/dialogs/runners.py' for reading: File or folder doesn't exist
while executing ['/usr/bin/meson', '--internal', 'gettext', 'update_po', '--pkgname=lutris', '--extra-args=--from-code=UTF-8']
FAILED: meson-lutris-update-po 
/usr/bin/meson --internal exe --unpickle /home/thefish/Downloads/lutris/builddir/meson-private/meson_exe_meson_455c5f458251e6293737583b5857a633a30c2422.dat
ninja: build stopped: subcommand failed.
```

### Expected behavior

Not to fail.

### Log output

```shell
-
```

### System Information

```shell
-
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I think you are supposed to run "./po/generate-potfiles.sh" first to update that file. At least, that's what that po/README.md suggests, and it seems to me like it works.

**Comment by strycore** [comment]
I've manually removed the reference to that file in POTFILES so it should be working alright now.

**Comment by danieljohnson2** [comment]
Watch out, the script changes more than that.

**Comment by strycore** [comment]
I ran the script to add missing entries too

**Comment by Vistaus** [comment]
I can confirm that it's working now. Thank you! 🙂
