### ISSUE TITLE
browser runner(run local html files?)

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#407]
I wonder how this works:
lutris:infinite-mario-html5
https://lutris.net/games/install/2896/view

**Comment by daniel-j** [comment]
Try remove $GAMEDIR from main_file. Have a look at this [installer script](https://lutris.net/games/install/2852/view).
Also, I see you set runner to Browser, try set it to Web which is the new runner for web based games.

**Comment by sixsixfive** [comment]
yay! that works :)
