### ISSUE TITLE
Can't translate Lutris (or its website) - or can't find where from!

### ISSUE THREAD

**Issue by heidiwenger** [lutris/lutris#4076]
Linux gaming is growing and not everybody is familiar with English language. Also i think English should not be the sole and only language in such volume in many places, in these times of choice. 

I was about to help on this, to bring about translation FROM English, but the source seems "well hidden" on the website, Github and so on. Where (or how) can i start translating Lutris?

Thank you very much!

**Comment by strycore** [comment]
Nothing is hidden, it's all here: https://github.com/lutris/lutris/tree/master/po

If you're looking to translate the website itself then open an issue on the appropriate repository.
