### ISSUE TITLE
_check_timeout(): subprocess.py:1178:_check_timeout:subprocess.TimeoutExpired: Command '['glxinfo', '-B']' timed out after 2 seconds

### ISSUE THREAD

**Issue by farchord** [lutris/lutris#4077]
### Bug description

(This is a bug report submitted using abrt on Fedora Core 35 (Issue also occurs on 34), started happening on 2021-11-17 and latest happened on 2022-02-09. There are multiple instances of this error, but only one will be submitted as they are all happening at the same place in the same file.

### How to Reproduce

Submitted by the user through an automated tool (No steps to reproduce)

### Expected behavior

No Expected behavior

### Log output

```shell
Version-Release number of selected component:
lutris-0.5.9.1-3.fc35

Additional info:
reporter:       libreport-2.15.2
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-net.lutris.Lutris-47184.scope
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: _check_timeout
exception_type: subprocess.TimeoutExpired
executable:     /usr/bin/lutris
interpreter:    python3-3.10.2-1.fc35.x86_64
kernel:         5.16.5-200.fc35.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
subprocess.py:1193:_check_timeout:subprocess.TimeoutExpired: Command '['wine', '--version']' timed out after 2 seconds

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/game_actions.py", line 178, in on_edit_game_configuration
    EditGameConfigDialog(self.window, self.game)
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/edit_game.py", line 16, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 70, in build_tabs
    self._build_info_tab()
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 83, in _build_info_tab
    self.runner_box = self._get_runner_box()
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 143, in _get_runner_box
    self.runner_dropdown = self._get_runner_dropdown()
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 202, in _get_runner_dropdown
    runner_liststore = self._get_runner_liststore()
  File "/usr/lib/python3.10/site-packages/lutris/gui/config/common.py", line 225, in _get_runner_liststore
    for runner in runners.get_installed():
  File "/usr/lib/python3.10/site-packages/lutris/runners/__init__.py", line 100, in get_installed
    runner = import_runner(runner_name)()
  File "/usr/lib/python3.10/site-packages/lutris/runners/wine.py", line 170, in __init__
    "default": get_default_version(),
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/wine.py", line 245, in get_default_version
    installed_versions = get_wine_versions()
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/wine.py", line 207, in get_wine_versions
    versions += get_system_wine_versions()
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/wine.py", line 159, in get_system_wine_versions
    version = get_wine_version(WINE_PATHS[build])
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/wine.py", line 265, in get_wine_version
    version = system.read_process_output([wine_path, "--version"])
  File "/usr/lib/python3.10/site-packages/lutris/util/system.py", line 84, in read_process_output
    return subprocess.check_output(
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.10/subprocess.py", line 1993, in _communicate
    self._check_timeout(endtime, orig_timeout,
  File "/usr/lib64/python3.10/subprocess.py", line 1193, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['wine', '--version']' timed out after 2 seconds

Local variables in innermost frame:
self: <Popen: returncode: 0 args: ['wine', '--version']>
endtime: 20464.995051242
orig_timeout: 2
stdout_seq: []
stderr_seq: None
skip_check_and_raise: True
```

### System Information

```shell
(All bugs for this issue are private)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by farchord** [comment]
I'm also a new co-packager for the lutris package on Fedora, if more details are needed, please do let me know. I'm very much a newbie at this and just want to make sure I'm submitting all the information that you need. 

If a bug isn't private, I'll also submit the link to the bugzilla ticket.

**Comment by strycore** [comment]
Is there any repro details on how this bugs happens? Is the system able to run those commands normally outside of lutris?

The title mentions glxinfo -B but the bug content mentions wine --version.

Both these commands should return in under 2 seconds.

**Comment by farchord** [comment]
We have about a dozen bugs at the exact same line and file but with different commands done. Sorry if the bug body and subject vary i probably took them from different bug reports. Would it help if i submitted more stack traces of the same bug?

**Comment by farchord** [comment]
And unfortunately those are automated submissions, we cant get more info from the user.

**Comment by strycore** [comment]
It looks like this is the same bug, no matter which command is passed to `read_process_output()`.
Without more context, this is going to be hard to solve since I haven't ran into this issue neither was it reported by anyone else.

The timeout was added initially for lspci, which would get stuck in some cases: https://github.com/lutris/lutris/pull/2983/commits/a50b8346c8bf655cf28aa970038d8bb4669ecc0a

**Comment by farchord** [comment]
No worries, but in case you need it, there's one of the bugs not flagged as private you should be able to see all the information:

https://bugzilla.redhat.com/show_bug.cgi?id=2015718

The others have the same error but with different commands, here's some samples:

Truncated backtrace:
subprocess.py:1193:_check_timeout:subprocess.TimeoutExpired: Command '['xrandr']' timed out after 2 seconds

Truncated backtrace:
subprocess.py:1193:_check_timeout:subprocess.TimeoutExpired: Command '['wine', '--version']' timed out after 2 seconds

Truncated backtrace:
subprocess.py:1193:_check_timeout:subprocess.TimeoutExpired: Command '['glxinfo', '-B']' timed out after 2 seconds

Truncated backtrace:
subprocess.py:1193:_check_timeout:subprocess.TimeoutExpired: Command '['/usr/sbin/ldconfig', '-p']' timed out after 2 seconds

Those are pretty much the 4 unique commands I can find in the bug reports, the glxinfo one seems to be the most common.

If you can't fix those that's fine, but I figured I'd let you know. :)

**Comment by farchord** [comment]
Here's the CPUs of the others I can see:

On the xrandr command one: R9 3900x
"wine --version" one: R5 5600G
Another xrandr one: Intel i7 10750H
glxinfo -B: Intel i5 8250U
Another glxinfo -B: Intel i3 8130U
Another glxinfo -B: Intel i5 7300HQ
And the last glxinfo -B I sent to you.

**Comment by strycore** [comment]
Is this still an issue on current versions of Fedora and Lutris?

**Comment by farchord** [comment]
I do not think so no.

Le lun. 5 juin 2023 à 01:47, Mathieu Comandon ***@***.***> a
écrit :

**Comment by strycore** [comment]
ok, cool
