### ISSUE TITLE
Gamescope doesn't work

### ISSUE THREAD

**Issue by t0msk** [lutris/lutris#4084]
### Bug description

When I enable gamescope, then game will not launch.

### How to Reproduce

1. Enable gamescope
2. Start a game

### Expected behavior

Start gamescope instance

### Log output

```shell
[tomsk@tomsk-PC ~]$ lutris -d
2022-02-23 10:18:06,621: Magic not available. Unable to automatically find game executables. Please install python-magic
2022-02-23 10:18:06,697: Starting Lutris 0.5.9.1
2022-02-23 10:18:06,732: No cores found
2022-02-23 10:18:07,485: Startup complete
INFO     2022-02-23 10:18:07,486 [startup.check_driver:53]:Using NVIDIA drivers 510.54 for x86_64
INFO     2022-02-23 10:18:07,486 [startup.check_driver:57]:GPU: Unknown
INFO     2022-02-23 10:18:07,487 [startup.check_driver:73]:GPU: 10DE:1C03 1458:3716 (nvidia drivers)
INFO     2022-02-23 10:18:07,487 [startup.check_driver:73]:GPU: 8086:0412 1043:8534 (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
DEBUG    2022-02-23 10:18:08,295 [lutriswindow.update_store:451]:Showing 32 games
INFO     2022-02-23 10:18:11,713 [runner.use_runtime:258]:Runtime disabled by system configuration
INFO     2022-02-23 10:18:11,719 [runner.use_runtime:258]:Runtime disabled by system configuration
DEBUG    2022-02-23 10:18:11,722 [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:DRI_PRIME="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__NV_PRIME_RENDER_OFFLOAD="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__GLX_VENDOR_LIBRARY_NAME="nvidia"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__VK_LAYER_NV_optimus="NVIDIA_only"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:game_name="Albion Online"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/tomsk/.local/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:LUTRIS_GAME_UUID="55003f04-634f-416f-b2b3-a035eb4fe513"
Started initial process 12006 from gamescope -f -- /run/media/tomsk/Data/Games/Albion Online/Albion-Online
Start monitoring process.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
vulkan: selecting physical device 'NVIDIA GeForce GTX 1060 6GB'
vulkan: physical device does not support DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
DEBUG    2022-02-23 10:18:12,296 [command.on_stop:193]:Process 12004 has terminated with code 256
DEBUG    2022-02-23 10:18:13,731 [game.beat:588]:Game thread stopped
WARNING  2022-02-23 10:18:13,731 [game.on_game_quit:614]:Game still running (state: running)
INFO     2022-02-23 10:18:13,731 [game.stop:599]:Stopping Albion Online (linux)
DEBUG    2022-02-23 10:18:13,731 [game.stop_game:554]:Albion Online (linux) has run for 2 seconds
WARNING  2022-02-23 10:18:13,731 [game.stop_game:556]:The game has run for a very short time, did it crash?
DEBUG    2022-02-23 10:18:13,737 [game.on_game_quit:632]:Albion Online stopped at Wed, 23 Feb 2022 10:18:13
DEBUG    2022-02-23 10:18:13,737 [game.save:257]:Saving Albion Online (linux) with config ID albion-online-desktopapp
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.16.10-arch1-1
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             15.3 GB
Swap:            7.6 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL Version:  3.0 Mesa 21.3.6
OpenGL Core:     4.5 (Core Profile) Mesa 21.3.6
OpenGL ES:       OpenGL ES 3.1 Mesa 21.3.6
Vulkan:          Supported
```

### Checklist:

- [x] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by runboy93** [comment]
```
MESA-INTEL: warning: Haswell Vulkan support is incomplete
vulkan: selecting physical device 'NVIDIA GeForce GTX 1060 6GB'
vulkan: physical device does not support DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
```
Instead of gamescope, this might be reason. Vulkan cannot be used because neither iGPU or GPU can't use it.

**Comment by t0msk** [comment]
Vulkan works, I use that iGPU with Dota 2 Vulkan and it works, but it doesn't matter because if you look at:
```

DEBUG    2022-02-23 10:18:11,722 [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:DRI_PRIME="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__NV_PRIME_RENDER_OFFLOAD="1"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__GLX_VENDOR_LIBRARY_NAME="nvidia"
DEBUG    2022-02-23 10:18:11,723 [command.start:139]:__VK_LAYER_NV_optimus="NVIDIA_only"
```

You will see that I use for this instance discrete GPU --> Nvidia GTX 1060 6GB which has full Vulkan support.

**Comment by runboy93** [comment]
Then why does system information default is iGPU and not GPU?

**Comment by t0msk** [comment]
Because I use hybrid graphics, I use KVM with GPU Passthrough so I cannot use discrete GPU all time, I switch between them.

Nvidia says no erros, I play games on this Nvidia normally, just gamescope doesn't work, I need it for Warthunder game, because my mouse doesn't capture in primary monitor (fullscreen/window mode), so I need gamescope to capture mouse in that monitor.

**Comment by strycore** [comment]
I'm not sure gamescope works on nvidia yet. It works fine on AMD though.

**Comment by runboy93** [comment]
> I'm not sure gamescope works on nvidia yet. It works fine on AMD though.

Yeah indeed, what been checking various bug reports on github, here on lutris and elsewhere not much about NVIDIA user reports seen, pretty much all on AMD.

Would be there any info anywhere about gamescope x nvidia and why so far just AMD works?

**Comment by strycore** [comment]
What is missing is clearly stated on the Gamescope repository:

```It runs on Mesa + AMD or Intel, and could be made to run on other Mesa/DRM drivers with minimal work. AMD requires Mesa 20.3+, Intel requires Mesa 21.2+. Can support NVIDIA if/when they support atomic KMS + accelerated Xwayland + Vulkan DMA-BUF extensions.```

Nvidia has been aware of those issues for years. They are so attached to having closed source drivers that it makes it much more complicated to comply with Gamescope's requirement.

**Comment by strycore** [comment]
The gamescope option will now be disabled on nvidia systems.

**Comment by Yaikava** [comment]
> The gamescope option will now be disabled on nvidia systems.

Hi, sorry to bother you, but it seems that it can run on nvidia now.
At least according to the [readme](https://github.com/ValveSoftware/gamescope/blob/master/README.md).
Any chances of this coming back. Would like to play around with it?

**Comment by strycore** [comment]
We already enable gamescope on nvidia for the supported drivers.

**Comment by Yaikava** [comment]
I will check my nvidia driver version later. It might be that.
Is there any other reason possible for the option being grayed out?

**Comment by strycore** [comment]
Lutris checks if Gamescope is installed and if the Nvidia driver is > 515

**Comment by Yaikava** [comment]
Weird, I should meet the requirements, but is grayed out.
![image](https://github.com/lutris/lutris/assets/83710104/2c7fa647-7f4a-44ac-ad7c-e1e1a40b0a30)

**Comment by strycore** [comment]
Are you using the Lutris flatpak by any chance?

**Comment by Yaikava** [comment]
> Are you using the Lutris flatpak by any chance?

yes

**Comment by Yaikava** [comment]
Installing flatpak version fixed it. Sorry, kinda forgot about that.

**Comment by RichardFevrier** [comment]
Installed flatpak gamescope with AMD system but still greyed out for League of legends.
Did you do something particular @Yaikava ?

**Comment by RichardFevrier** [comment]
Never mind my installed gamescope was provided by `com.valvesoftware.Steam.Utility.gamescope` when apparently lutris does not recognize. Moved to `org.freedesktop.Platform.VulkanLayer.gamescope` everything is good.
