### ISSUE TITLE
05.10.beta2 fails to install.

### ISSUE THREAD

**Issue by TaliesinEmrys** [lutris/lutris#4093]
dpkg-deb: error: archive 'lutris_0.5.10_beta2_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive lutris_0.5.10_beta2_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing

**Comment by strycore** [comment]
which distro are you on? It looks like it doesn't support the newer zst compression method...

**Comment by TaliesinEmrys** [comment]
Oh, sorry I forgot to mention that detail.
Debian SID.

**Comment by strycore** [comment]
That's weird, Sid should have the latest stuff... 
I have to see if I can build a deb using an older compression format

**Comment by TaliesinEmrys** [comment]
No worries, it is odd indeed.

I found a bug report in debian where it mentioned the need to support the newer compression formats.

Currently.

apt-cache policy dpkg
dpkg:
  Installed: 1.21.1
  Candidate: 1.21.1

**Comment by strycore** [comment]
that's more recent than what I used to build the deb:

apt-cache policy dpkg                                                                                                                             
dpkg:
  Installed: 1.20.9ubuntu2
  Candidate: 1.20.9ubuntu2

**Comment by TaliesinEmrys** [comment]
It is odd indeed, perhaps the debian package is built / compiled without zst support.
I know nothing about building debs, so don't know if that is even possible.

**Comment by strycore** [comment]
@stephanlachnit, you probably know better about this

**Comment by stephanlachnit** [comment]
Gonna answer with more infos tomorrow, but tldr Ubuntu switched to Zstd compression for debs, but Debian hasn't merged the support yet. When 5.10 releases I'll provide a deb working on Debian.

**Comment by stephanlachnit** [comment]
The relevant Debian bug report is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664

It probably makes sense for Lutris default deb to not be compressed with Zstd but zlib. This can be enforced in `debian/rules`:

```make
override_dh_builddeb:
	dh_builddeb -- -Zgzip
```

I'll open a PR.
