### ISSUE TITLE
Local translation not show.

### ISSUE THREAD

**Issue by lahtis** [lutris/lutris#4096]
### Bug description

using 0.5.10-beta2 deb version. Program show only English. I checked in github. My language has 100 % translated. Why it not show.

### How to Reproduce

1. Download  0.5.10-beta2 deb version in github
2. installed.
3. The default language in the operating system is Finnish.
4. Run the program $ lutris
5. When the program starts. The language is English.

### Expected behavior

Using program in my language.

### Log output

```shell

tuomas@Valvoja-CoolComputer:~$ LC_ALL=C lutris
2022-03-01 22:55:18,483: Starting Lutris 0.5.10
2022-03-01 22:55:18,507: No folder at /home/tuomas/.local/share/lutris/runners/retroarch/
2022-03-01 22:55:18,526: Using NVIDIA drivers 470.103.01 for x86_64
2022-03-01 22:55:18,526: GPU: NVIDIA GeForce GTX 770
2022-03-01 22:55:18,527: GPU: 10DE:1184 1043:8465 (nvidia drivers)
Gtk-Message: 22:55:18.669: GtkDialog mapped without a transient parent. This is discouraged.
2022-03-01 22:55:18,680: Startup complete
2022-03-01 22:55:18,823: Unable to get locale

tuomas@Valvoja-CoolComputer:~$ lutris -d
INFO     2022-02-26 12:37:34,928 [startup.init_lutris:164]:Starting Lutris 0.5.10
WARNING  2022-02-26 12:37:34,977 [libretro.get_libretro_cores:24]:No folder at /home/tuomas/.local/share/lutris/runners/retroarch/
INFO     2022-02-26 12:37:35,028 [startup.check_driver:57]:Using NVIDIA drivers 470.103.01 for x86_64
INFO     2022-02-26 12:37:35,028 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 770
INFO     2022-02-26 12:37:35,028 [startup.check_driver:77]:GPU: 10DE:1184 1043:8465 (nvidia drivers)
Gtk-Message: 12:37:35.144: GtkDialog mapped without a transient parent. This is discouraged.
INFO     2022-02-26 12:37:35,153 [startup.update_runtime:203]:Startup complete
DEBUG    2022-02-26 12:37:35,632 [lutriswindow.update_store:430]:Showing 7 games
```

### System Information

```shell
[System]
OS:              Ubuntu 18.04 Bionic Beaver
Arch:            x86_64
Kernel:          5.4.0-100-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Phenom(tm) II X4 965 Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             7.8 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 770/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.103.01
OpenGL Core:     4.6.0 NVIDIA 470.103.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.103.01
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by A6GibKm** [comment]
I can confirm that running `LANGUAGE=es flatpak run net.lutris.Lutris` nor `LANGUAGE=es poetry run lutris` do not work.

**Comment by lahtis** [comment]
LC_ALL=C lutris
2022-03-01 22:55:18,483: Starting Lutris 0.5.10
2022-03-01 22:55:18,507: No folder at /home/tuomas/.local/share/lutris/runners/retroarch/
2022-03-01 22:55:18,526: Using NVIDIA drivers 470.103.01 for x86_64
2022-03-01 22:55:18,526: GPU: NVIDIA GeForce GTX 770
2022-03-01 22:55:18,527: GPU: 10DE:1184 1043:8465 (nvidia drivers)
Gtk-Message: 22:55:18.669: GtkDialog mapped without a transient parent. This is discouraged.
2022-03-01 22:55:18,680: Startup complete
2022-03-01 22:55:18,823: Unable to get locale

**Comment by A6GibKm** [comment]
Running `meson _build && ninja -C _build` does not generate any po files, the directory `_build/po` is empty.

**Comment by Lrss** [comment]
I would love contribute a translation, but I can't seem to be able to test my translation do to this issue

**Comment by strycore** [comment]
I recently fixed the issue for Flatpak. The package wasn't using meson to build the translation. Are there any other packages not providing translations?

**Comment by JulienDlq** [comment]
Same issue here using Lutris from Gentoo portage tree. My language is French.

```
$ lutris -v
lutris-0.5.13
```

```
[System]
OS:              Gentoo 2.14 n/a
Arch:            x86_64
Kernel:          6.4.12-gentoo-x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical cores:  8
Logical cores:   8

[Memory]
RAM:             31.3 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.104.05
OpenGL Core:     4.6.0 NVIDIA 535.104.05
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.104.05
Vulkan Version:  1.3.250
Vulkan Drivers:  NVIDIA GeForce GTX 1660 Ti (1.3.242)
```

**Comment by strycore** [comment]
> Same issue here using Lutris from Gentoo portage tree. My language is French.

You have to report the issue to the Gentoo packager and tell them to use Meson to build Lutris otherwise the translations won't show up.

**Comment by JulienDlq** [comment]
> > Same issue here using Lutris from Gentoo portage tree. My language is French.
> 
> You have to report the issue to the Gentoo packager and tell them to use Meson to build Lutris otherwise the translations won't show up.

Just done today, and fixed by Gentoo. Can confirm it works!
