### ISSUE TITLE
Can not log into Humble Bundle [Access to https://www.humblebundle.com/api/v1/user/order denied]

### ISSUE THREAD

**Issue by marissa999** [lutris/lutris#4099]
### Bug description

I am unable to login into my Humble Bundle account through Lutris.

When I try to login the login window opens, I can enter my account credentials, but nothing happens when I click on login. (But I can login into my Humble Bundle account through the webbrowser).

After trying that when I reopen Lutris it tells me that I am logged into a Humble Bundle account (In the sources it gives me a logout and sync button now), but when I try to sync my library I get an error message "Access to https://www.humblebundle.com/api/v1/user/order denied"

This error message indicate to me that there was a recent change to the API from Humble Bundle?

### How to Reproduce

1. Open Lutris
2. In "Sources" in the side-pannel of the main window from Lutris click on the "Human"-icon next to Humble Bundle to open the login window
3. Enter your account credentials and click login
4. Nothing happens (the login window flickers, maybe a reload?)
5. Restart Lutris
6. See that you are apparently logged into Lutris now
7. Click on the "Sync"-icon next to Humble Bundle

### Expected behavior

Being logged into Humble Bundle and being able to sync my games. 

### Log output
While trying to sync the Humble Bundle library:
```shell
2022-02-26 14:04:12,424: Error while completing task <bound method BaseService.reload of <humblebundle.HumbleBundleService object at 0x7fea250280c0 (lutris+services+humblebundle+HumbleBundleService at 0x55a5b77d74a0)>>: <class 'lutris.util.http.UnauthorizedAccess'> Access to https://www.humblebundle.com/api/v1/user/order denied
  File "/app/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/lutris/services/base.py", line 83, in reload
    self.load()
  File "/app/lib/python3.9/site-packages/lutris/services/humblebundle.py", line 97, in load
    library = self.get_library()
  File "/app/lib/python3.9/site-packages/lutris/services/humblebundle.py", line 147, in get_library
    for order in self.get_orders():
  File "/app/lib/python3.9/site-packages/lutris/services/humblebundle.py", line 171, in get_orders
    gamekeys = self.make_api_request(self.api_url + "api/v1/user/order")
  File "/app/lib/python3.9/site-packages/lutris/services/humblebundle.py", line 117, in make_api_request
    request.get()
  File "/app/lib/python3.9/site-packages/lutris/util/http.py", line 93, in get
    raise UnauthorizedAccess("Access to %s denied" % self.url)
```

### System Information

```shell
[System]
OS:              GNOME 41 Flatpak runtime
Arch:            x86_64
Kernel:          5.16.11-zen1-1-zen
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3400G with Radeon Vega Graphics
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.4 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.54
OpenGL Core:     4.6.0 NVIDIA 510.54
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.54
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by samuele-mattiuzzo** [comment]
I confirm the above also happens when one tries to sign in their HB account through Google, just a flicker then nothing else

**Comment by Dimensional** [comment]
This may be related to the change made back in February where they removed all non-Windows versions of games from their Trove, and pushed out their own Windows App for the game library.

**Comment by Enqueued** [comment]
Same exact steps recreated on my machine.
OS - Fedora 35
Lutris Version - 0.5.9.1

**Comment by twiztedtbone** [comment]
Can confirm that this is also happening on up to date Arch with Lutris 0.5.9.1

**Comment by DDzwiedziu** [comment]
Can comfirm – Ubuntu 21.10, Lutris 0.5.9.1

**Comment by finndo77** [comment]
I can confirm, but also add something :)  if others could check, I have 2FA enabled and there is no prompt for me to enter the PIN code.  
Are others with this issue also using 2FA?  

Also, I can still DL purchased games and purchase new games specifically for Linux.

Linux Mint 20.3 fresh install yesterday.  With Lutris 0.5.9.1
steam is working fine with 2fa.

**Comment by marissa999** [comment]
> I can confirm, but also add something :) if others could check, I have 2FA enabled and there is no prompt for me to enter the PIN code. Are others with this issue also using 2FA?

I was not using Two-Step Verification (the proper TOTP one). I do always receive a code via E-Mail from Humble Bundle account protection whenever I try to login into my account though. 

I enabled Two-Step Verification now, and just out of curiosity tried to login to my Humble Bundle Account in Lutris and (prob to the surprise to no one) the login still does not work.

> Also, I can still DL purchased games and purchase new games specifically for Linux.
How are you able to do that? For me the login process in Lutris does not work at all, and therefore I do not even get a list of my games that run on Linux in Lutris. Or do you mean on [https://www.humblebundle.com/home/library](https://www.humblebundle.com/home/library)? On that page I can still see all of my games, including the option to download a Linux version for games that do run on Linux.

**Comment by finndo77** [comment]
yes I was referring to the website, as it was commented that linux games had been removed.

If you were not using 2FA before, then I Guess that has nothing to do with this issue.  :(

**Comment by dhollinger** [comment]
My guess, though I have not had time to do a lot of digging, is that it has to do with some potential changes in HTTP Headers or Cookies that are used for authentication to humble bundle. The API endpoint is still valid and active, I was able to view it in my browser I was logged into.

**Comment by Metastopheles** [comment]
Just advising I have experienced the same issue described here. I use 2FA at Humble Bundle.
I'll also add I entered my password incorrectly and the login window Lutris presents does not advise the error where it does at Humble Bundle site.

I'm running Kubuntu 20.04.

**Comment by idarlund** [comment]
I opened a support ticket with Humble Bundle and this is what I got as an answer (I removed employee name):

Hi there,

Unfortunately at this time we do not have a publicly available API or product feed for all the prices on our site.

All the best,

-Xxxx
Humble Bundle
http://support.humblebundle.com/

**Comment by idarlund** [comment]
Now I'm really confused.. 🤔 Asked them if there is a plan to re-implement an api such as the old one, or will they not provide an api anymore.

..and got this answer:
"We have actually never offered a publicly-available API, and we do not have plans to implement it at this time. Apologies for any confusion!"

Was the https://www.humblebundle.com/api reverse engineered when it was implemented in Lutris?

**Comment by miketo09** [comment]
> This may be related to the change made back in February where they removed all non-Windows versions of games from their Trove, and pushed out their own Windows App for the game library.

HB has a new Windows-only launcher for their games and removed Linux and Mac support: https://arstechnica.com/gaming/2022/01/humble-subscription-service-is-dumping-mac-linux-access-in-18-days/. The Ars Technica article suggests that in the future HB may be looking to have exclusives available only through their Windows-only launcher. Removing Linux and Mac versions sounds like a cost-cutting measure as I imagine there's a lot of support costs per market share.

Linux versions purchased prior to the changeover *may* still available in the Humble Library; I still have Linux Psychonauts in my library. Other Windows games *may* be available as Steam keys in the library.

The only workarounds for Lutris devs I can think of (warning: not a dev) are to spoof the HB launcher's user agent string in the API, or some kludgy workaround running the Humble launcher in Lutris using Wine. Otherwise, we have to redeem keys in Steam or download Linux versions outside of Lutris and then add them as local games.

**Comment by derevo** [comment]
I know others have provided more info, but I wanted to include that I am also affected by this: Lutris 0.5.9.1, Ubuntu 20.04.

> The only workarounds for Lutris devs I can think of (warning: not a dev) are to spoof the HB launcher's user agent string in the API, or some kludgy workaround running the Humble launcher in Lutris using Wine. Otherwise, we have to redeem keys in Steam or download Linux versions outside of Lutris and then add them as local games.

It would be interesting to maybe run Fiddler or something on Windows with their client open to see what it's doing and whether Lutris can just mimic it, which I can try to do soon, but I'm new to Linux and am not too familiar with desktop application development in general.

**Comment by Lamdarer** [comment]
Manjaro user here, the last patch from 0.5.10.1-1 -> 0.5.10.1-2 fixed the Humble Bundle Login for me.
Though I am not sure what exactly could have caused it

**Comment by strycore** [comment]
No one has done anything to fix the issue yet.

**Comment by strycore** [comment]
Switching to the testing branch solves nothing. The issue is still present in Manjaro or any other system.

**Comment by Lamdarer** [comment]
I dont know why but it worked and the update is pretty much the only change on my side that could have influenced it. Can I provide you with any other that might help?

**Comment by strycore** [comment]
I'm not sure. The block is coming from Cloudflare and doesn't seem to be always consistent. 
I've reached out to Humble Bundle to ask them for a recommendation.

**Comment by tin-pham** [comment]
Same issue

**Comment by MattByName** [comment]
I'm on 5.10.1 on fedora and experiencing this issue too. Will report back if 5.10.2 also fixes it for me when it makes its way to fedora

**Comment by sobkas** [comment]
After a talk with HumbleBundle support I got:
"Sadly, we're unable to troubleshoot login issue with a third party app. We've made the changes on our end to hopefully help getting you logged in. "
And was able to log in to my Humble Bundle account in Lutris without any problems.

**Comment by strycore** [comment]
I can confirm this is fixed as well!

> "Sadly, we're unable to troubleshoot login issue with a third party app. We've made the changes on our end to hopefully help getting you logged in. "

This is such a weird thing to say, it's basically "Sorry, we can't help you, but we've fixed the issue btw"

**Comment by rcrit** [comment]
Still not working for me. Maybe some DNS caches still need to expire.

**Comment by strycore** [comment]
Yes, that would make sense since Cloudflare acts as the nameserver.

**Comment by twistyfix** [comment]
Not working for me either on Mint 20.3.

**Comment by strycore** [comment]
Reopening, since it does not seemed solved for everyone.

**Comment by jvonhoff** [comment]
So, reading through here, and #4277, I'm not seeing a working method to get logged in via Lutris.  Is that correct?

**Comment by strycore** [comment]
There's no method, either you are blocked by Cloudflare in which case there is no workaround or you aren't blocked, in which case the feature works normally.

**Comment by rcrit** [comment]
The only workaround I've found is to manually create the cookie jar in ~/.cache/lutris/.humblebundle.auth

It's important to start with HB disconnected otherwise the cookies will be overwritten. The first time you start Lutris after this manual creation your Humble Bundle should have a Reload and Quit symbols next to it otherwise it isn't going to work (because it means the cookies didn't validate so it will prompt for new credentials).

A sample jar will look like (tab-delimited):

```
.humblebundle.com       TRUE    /       TRUE    1670638989      csrf_cookie    XXXXXXXXXXXXX-XX-X-XXXXXXXXXX    None
#HttpOnly_.humblebundle.com     TRUE    /       TRUE    1662862989      _simpleauth_sess        XXXXXXXXXXXXXXXXXXXXXXXXXX==|1655086989|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        None
#HttpOnly_.humblebundle.com     TRUE    /       TRUE    1655088789      __cf_bm XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=        None
```

Use FF developer tools (F12) in a private window, log into HB, go to the Network the look at requests for the cookies.

Copy the cookie values for each over the appropriate XXX bit.

Start Lutris and click reload. Profit.

I don't yet know how long this will work or if one can manually extend the cookie dates. You might be able to twiddle the simpleauth_sess and csrf_cookie dates to make it last longer. Once expired your HB games won't be available in Lutris and you'll be prompted to log in again.

**Comment by Metastopheles** [comment]
> The only workaround I've found is to manually create the cookie jar in ~/.cache/lutris/.humblebundle.auth

Thank you for this work around rcrit. 

This was what I had been looking for but did not consider the auth files would be hidden. Wish I could say rookie error but been doing this for nearly 20 years...so no valid excuse.

By the way, for my Firefox, I found the cookies under the "Storage" tab.

If you attempt to log in, and fail, the auth file will be created. Close Lutris, update the cookie bits as per rcrit into the listed sections and log back into Lutris, click reload. Worked for me.

**Comment by jvonhoff** [comment]
> Thank you for this work around rcrit.

Seconded!  Awesome find.  I'm logged in now.  For posterity, I followed these steps:
1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
3. Close Lutris
4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
- csrf_cookie
- _simpleauth_sess
- __cf_bm
and place that value where noted in above response from @rcrit .
6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
7. Save & close the .humblebundle.auth file, and re-open Lutris.

I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.

Thanks again for the workaround!

**Comment by Kitocco** [comment]
> > Thank you for this work around rcrit.
> 
> Seconded! Awesome find. I'm logged in now. For posterity, I followed these steps:
> 
> 1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
> 2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
> 3. Close Lutris
> 4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
> 5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
> 
> * csrf_cookie
> * _simpleauth_sess
> * __cf_bm
>   and place that value where noted in above response from @rcrit .
> 
> 6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
> 7. Save & close the .humblebundle.auth file, and re-open Lutris.
> 
> I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.
> 
> Thanks again for the workaround!

This was being helpful, as I had no idea which aspects of my cookies to copy/save to replace in the file... until I found that there was no /lutris/ folder in my /.cache/ folder on my Steam Deck (more specifically, /home/deck/.cache). I even have "Show Hidden Items" on in Dolphin, the built-in file explorer of SteamOS 3.3.
I've tried re-launching Lutris & attempting to log in again, logging out & trying to log in again, even just closing the app windows once I logged out & clicked the person icon in Lutris to no dice. 

...maybe my best bet now is waiting for an update, I guess...

**Comment by dhollinger** [comment]
> > > Thank you for this work around rcrit.
> > 
> > 
> > Seconded! Awesome find. I'm logged in now. For posterity, I followed these steps:
> > 
> > 1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
> > 2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
> > 3. Close Lutris
> > 4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
> > 5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
> > 
> > 
> > * csrf_cookie
> > * _simpleauth_sess
> > * __cf_bm
> >   and place that value where noted in above response from @rcrit .
> > 
> > 
> > 6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
> > 7. Save & close the .humblebundle.auth file, and re-open Lutris.
> > 
> > I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.
> > Thanks again for the workaround!
> 
> This was being helpful, as I had no idea which aspects of my cookies to copy/save to replace in the file... until I found that there was no /lutris/ folder in my /.cache/ folder on my Steam Deck (more specifically, /home/deck/.cache). I even have "Show Hidden Items" on in Dolphin, the built-in file explorer of SteamOS 3.3. I've tried re-launching Lutris & attempting to log in again, logging out & trying to log in again, even just closing the app windows once I logged out & clicked the person icon in Lutris to no dice.
> 
> ...maybe my best bet now is waiting for an update, I guess...

Maybe I missed in the previous posts, but for each one of the mentioned cookies, you _have to_ make sure you update the unix timestamp in the `.humblebundle.auth` file that comes right before the cookie name in the file. You can find it in the firefox storage tab. Under each cookie, find the "expires" key and convert it to a UNIX timestamp, then replace the existing timestamp with that one in the auth file

**Comment by Kitocco** [comment]
> [x]

Hmmm... I'm not sure I follow, but I think my problem is the nonexistence of a .lutris folder, or any such 'humblebundle.auth' file for me to replace cookie keys with. Do I just create them all?

**Comment by Metastopheles** [comment]
> Hmmm... I'm not sure I follow, but I think my problem is the nonexistence of a .lutris folder, or any such 'humblebundle.auth' file for me to replace cookie keys with. Do I just create them all?

@Kitocco make sure you have attempted to log into Humble Bundle. This should create an auth file. Also, it is a hidden file, it has the dot in front of it ".humblebundle.auth", so set you file manager to view hidden files.

**Comment by Terrance** [comment]
For anyone who's installed Lutris via Flatpak, `~/.var/app/net.lutris.Lutris/cache/lutris/.humblebundle.auth` is the path to the cookie file noted in the workarounds above.

**Comment by maddoodles** [comment]
> > > Thank you for this work around rcrit.
> > 
> > 
> > Seconded! Awesome find. I'm logged in now. For posterity, I followed these steps:
> > 
> > 1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
> > 2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
> > 3. Close Lutris
> > 4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
> > 5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
> > 
> > 
> > * csrf_cookie
> > * _simpleauth_sess
> > * __cf_bm
> >   and place that value where noted in above response from @rcrit .
> > 
> > 
> > 6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
> > 7. Save & close the .humblebundle.auth file, and re-open Lutris.
> > 
> > I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.
> > Thanks again for the workaround!
> 
> This was being helpful, as I had no idea which aspects of my cookies to copy/save to replace in the file... until I found that there was no /lutris/ folder in my /.cache/ folder on my Steam Deck (more specifically, /home/deck/.cache). I even have "Show Hidden Items" on in Dolphin, the built-in file explorer of SteamOS 3.3. I've tried re-launching Lutris & attempting to log in again, logging out & trying to log in again, even just closing the app windows once I logged out & clicked the person icon in Lutris to no dice.
> 
> ...maybe my best bet now is waiting for an update, I guess...

Unfortunately, when following these steps I simply get "Access to https://www.humblebundle.com/api/v1/user/order denied" popping up.

I am still on 0.5.10.1 at the minute, as I installed Luris through the Pop!_Shop, which doesn't appear to have updated to the latest version yet.

**Comment by TheCyberQuake** [comment]
> > Thank you for this work around rcrit.
> 
> Seconded! Awesome find. I'm logged in now. For posterity, I followed these steps:
> 
>     1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
> 
>     2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
> 
>     3. Close Lutris
> 
>     4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
> 
>     5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
> 
> 
>     * csrf_cookie
> 
>     * _simpleauth_sess
> 
>     * __cf_bm
>       and place that value where noted in above response from @rcrit .
> 
> 
>     6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
> 
>     7. Save & close the .humblebundle.auth file, and re-open Lutris.
> 
> 
> I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.
> 
> Thanks again for the workaround!

Just verified that this fixes the issue on Steam Deck, though the location of the cookie is different for flatpak users, which was posted above by Terrance:

> For anyone who's installed Lutris via Flatpak, `~/.var/app/net.lutris.Lutris/cache/lutris/.humblebundle.auth` is the path to the cookie file noted in the workarounds above.

**Comment by strycore** [comment]
I'm tempted to handle this error in Lutris. This is not something we normally do because I'd rather solve the problem instead of documenting it.
If we get the error denied response from Humble, we could display a dialog better explaining the situation, the workaround and 3 text fields to paste the cookie values so there is no need for the user to go edit a file manually.

**Comment by seanlynch** [comment]
I submitted a bug report to Humble Bundle, because I don't think they really intend to be blocking us from using software like Lutris. I'd suggest others do the same so that they realize this is a serious issue.

**Comment by idarlund** [comment]
> 

got a link for the bug report, or is it just a support ticket as I had and got denied on? https://github.com/lutris/lutris/issues/4099#issuecomment-1068830593 and https://github.com/lutris/lutris/issues/4099#issuecomment-1072674629

**Comment by seanlynch** [comment]
Just a support ticket. Is there a place to report bugs that show up publicly?

**Comment by idarlund** [comment]
> Just a support ticket. Is there a place to report bugs that show up publicly?

don't know. that's why I asked :)

**Comment by strycore** [comment]
It's safe to assume that Humble Bundle does not want to address the issue.

It's the usual stance for most companies to enter a panicked state whenever they read the word Linux and they will do anything they can to stay away from it.

**Comment by anark10n** [comment]
Fresh install of Humble App, and no .humblebundle.auth file in ~/.cache/lutris on arch linux.

**Comment by rcrit** [comment]
The Humble App is a different thing. The ~/.cache/lutris allows Lutris to log in, not run the app. I think the same principle may apply but the cookie would be stored somewhere inside the wine prefix.

**Comment by hrrsnmb** [comment]
> > Thank you for this work around rcrit.
> 
> Seconded! Awesome find. I'm logged in now. For posterity, I followed these steps:
> 
>     1. In Lutris, log out of HumbleBundle (if you've tried like I have)... it's the small arrow leaving the circle icon.
> 
>     2. Still in Lutris, click the Connect icon (little profile of a person) and attempt login to create the .humblebundle.auth file
> 
>     3. Close Lutris
> 
>     4. In Firefox, open a Private window and log in to HumbleBundle -- I had a code emailed to me to enter, and finally got logged in
> 
>     5. F12 to open Firefox dev tools, and then, from the Storage tab (thanks @Metastopheles) copy the corresponding data fields for
> 
> 
>     * csrf_cookie
> 
>     * _simpleauth_sess
> 
>     * __cf_bm
>       and place that value where noted in above response from @rcrit .
> 
> 
>     6. I had a couple of extra lines in my .humblebundle.auth file, which I just deleted, making sure the 3 above were intact, and updated with the data values from Firefox
> 
>     7. Save & close the .humblebundle.auth file, and re-open Lutris.
> 
> 
> I believe I had to click the Refresh button on the HumbleBundle store (in Lutris) but several games showed up.
> 
> Thanks again for the workaround!

This workaround is still working on Fedora 37 as of Lutris 0.5.11. Thanks @rcrit & @jvonhoff!

A few things to note for any folks still having trouble:

- You need to turn on 'hidden files' in your distro's file browser.

- The location of the file for me was:

`/home/YourLowercaseUsername/.var/app/net.lutris.Lutris/cache/lutris/.humblebundle.auth`

- The three fields you're editing in the .auth file begin with:

```
.humblebundle.com	TRUE	/	TRUE	...	csrf_cookie ...
#HttpOnly_.humblebundle.com	TRUE	/	TRUE	...	_simpleauth_sess ...
#HttpOnly_.humblebundle.com	TRUE	/	TRUE	...	__cf_bm ...
```

- It may help with visibility to turn off text-wrapping in your text editor.

- For me, the corresponding cookie data copied from FireFox for 'csrf cookie' & 'cf bm' was exactly the same number of characters as what was already in the file, but the 'simpleauth sess' string was a good bit longer after pasting.

- Once the three strings are pasted, make sure to:

_quit/exit Lutris > save your changes to the file > launch Lutris > press the reload button next to Humble Bundle in your sources list_

- It may take several minutes your games to show up.

**Comment by rcrit** [comment]
I got tired of manually refreshing the cookies so I wrote a script to help, https://github.com/rcrit/lutris-humble-cookies .
YMMV
I don't have a Steam Deck nor work with FlatPak so the instructions very well could be wrong.

**Comment by strycore** [comment]
The Lutris client now has an alternate method that will accept cookies in a plain text field that will be used instead of the Webkit2 based auth.
The client will recommend a Firefox extension to make the process easier but any valid cookie file will work.
