### ISSUE TITLE
Lutris freezes/hangs when game install completes

### ISSUE THREAD

**Issue by daniel-j** [lutris/lutris#411]
[Video demonstration](https://www.youtube.com/watch?v=vixcXMP5fcE)

Happens for all game installs when installing from inside Lutris. No debug output when it happens.
When installing from the website with Lutris closed it does not happen.

Systems tested on: Arch Linux, Void Linux

**Comment by telanus** [comment]
Tried it, If I use the online install from Achtung, die Kurve! it will freeze Lutris as seen in the Vid, runnung Lutris -d doesn't output any info on why
