### ISSUE TITLE
fix 0.4.0 release with python3-setup tools

### ISSUE THREAD

**Issue by ProfessorKaos64** [lutris/lutris#412]
You may want to re-release 0.4.0 with python3-setup.tools in debian/control. The [0.4.0](https://github.com/lutris/lutris/blob/ab5cd0448efb5948000e43ed1953ead158adc270/setup.py) setup.py still includes setuptools as a module.

**Comment by strycore** [comment]
I released 0.4.0ubuntu1 with a bunch of packaging fixes.
