### ISSUE TITLE
[Enhancement] Make searching for installation data non-case sensitive

### ISSUE THREAD

**Issue by t0msk** [lutris/lutris#4120]
Hello,

I wanted to install Need For Speed II, and installation script wanted me to locate “fedata” and “gamedata” folder in installation drive, but my folders are called “FeData” and “GameData”, so I had to rename it to match Lutris installation script, but Lutris could do non-case sensitive search for these folders and files by default.

**Comment by strycore** [comment]
This should be fixed by https://github.com/lutris/lutris/commit/2a67f2ba1e0704b26e45c77a68cdffdfa50de073 

Needs testing
