### ISSUE TITLE
Manually installed Windows games not launching

### ISSUE THREAD

**Issue by IAmJoker47** [lutris/lutris#4125]
So I just moved to Linux just a couple of weeks back and I seem to be having this problem ever since. Running my pre-installed (from windows) games just wont launch with lutris. But if I try to open them directly from the folder with wine they work perfectly fine. I've tried 4 games so far, 2 of which work but not very well. Civ4 and GTAVC wont work at all. Civ5 and Undertale works but I can't seem to be able to go fullscreen. I've tried using virtual desktop/windowed mode option in lutris but it was not a very good experience.

I've also tried Runescape but it was a Linux game anyway so ofc it would work.

I believe I'm doing something wrong but I just can't figure it out. If someone can help me I would really appreciate it.

Anyway, here is the log:
Started initial process 8543 from gamemoderun /opt/wine-devel/bin/wine /home/joker/Games/Civilization IV Complete/Civ4/Beyond the Sword/Civ4BeyondSword.exe
Start monitoring process.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
wine: could not load kernel32.dll, status c0000135
Monitored process exited.
Initial process has exited (return code: 13568)
Exit with return code 13568

**Comment by danieljohnson2** [comment]
What do you mean when you say the games are "pre-installed (from Windows)"? Did you copy the game's directory off a Windows disk or something?

I see you are using Feral GameMode; were you doing that when it worked? The errors in the log seem related to it. Could you try turning that off in Lutris?

Do the games work if you use Lutris' option for the "System" WINE version?

**Comment by IAmJoker47** [comment]
By "pre-installed" I just meant that I installed it when I was using windows (before I installed Linux Mint). English isn't my first language so sorry if I worded it wrong. And yes I installed the game from a disk.

No lutris never worked actually. I only used wine to be able to play them, like opened the game straight from the directory. And yes I tried to open it without Feral GameMode and this time lutris just mentioned it was running and never stopped like the previous times. The game didn't actually launch tho.

Tried using the "System" wine version and got the same result.

Now the log just says this:
Started initial process 24660 from /usr/bin/wine /home/joker/Games/Civilization IV Complete/Civ4/Beyond the Sword/Civ4BeyondSword.exe
Start monitoring process.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.

All my games are in the /home/Games directory.

**Comment by danieljohnson2** [comment]
I'm have a hard time understanding how these games that you installed when using Windows wound up in your Linux Games directory.

Can you install one of these using Lutris? Does it work if you install it that way?

**Comment by IAmJoker47** [comment]
I just copied them there lmao.

Also no I don't think it works that way. I could've installed it with wine. If I didnt lose my disk that is.

**Comment by keenanweaver** [comment]
This is what I would do so Lutris plays nice with what you have.

1) Open Lutris, use the add a new/manually installed game option.
2) Set a name and the runner to Wine. Under Game options, leave all blank/default except Wine prefix. Set this to `/home/joker/Games/civ-iv-complete` or whatever you want to call it. Under runner options, use one of the Lutris Wine versions (lutris-fshack variant is the default) and probably enable DXVK. Hit OK.
3) Optional: Right-click the game entry, select configure and set the identifier to "sid-meiers-civilization-iv-the-complete-edition".
4) Click Civ IV and then the Wine dropdown menu at the bottom, and select 'Wine configuration'. It will "build" the Wine prefix at this point. After that, close the Wine configuration window that appears.
5) Copy the original game directory you have and place it inside the Wine prefix that was created. It'd be `/home/joker/Games/civ-iv-complete/drive_c/Program Files (x86)/Civilization IV Complete`
6) Right-click -> configure on Civ IV and set the executable to the appropriate one in the Game options. `/home/joker/Games/civ-iv-complete/drive_c/Program Files (x86)/Civilization IV Complete/Civ4/Beyond the Sword/Civ4BeyondSword.exe`
7) Try launching the game.

If it's still throwing an error, then I'd recommend taking a look at what the [Lutris installers](https://lutris.net/games/sid-meiers-civilization-iv-the-complete-edition/) are doing to configure the Wine prefix to run the game, and also the [Wine AppDB](https://appdb.winehq.org/objectManager.php?sClass=version&iId=10158) to see any other changes you may need to make.

**Comment by danieljohnson2** [comment]
Even if you have set up the WINE prefix properly, these games might not run. You've copied the game files but not the registry entries the game's installer would have set up. The game might work anyway, but it might not.

**Comment by IAmJoker47** [comment]
> This is what I would do so Lutris plays nice with what you have.
> 
>     1. Open Lutris, use the add a new/manually installed game option.
> 
>     2. Set a name and the runner to Wine. Under Game options, leave all blank/default except Wine prefix. Set this to `/home/joker/Games/civ-iv-complete` or whatever you want to call it. Under runner options, use one of the Lutris Wine versions (lutris-fshack variant is the default) and probably enable DXVK. Hit OK.
> 
>     3. Optional: Right-click the game entry, select configure and set the identifier to "sid-meiers-civilization-iv-the-complete-edition".
> 
>     4. Click Civ IV and then the Wine dropdown menu at the bottom, and select 'Wine configuration'. It will "build" the Wine prefix at this point. After that, close the Wine configuration window that appears.
> 
>     5. Copy the original game directory you have and place it inside the Wine prefix that was created. It'd be `/home/joker/Games/civ-iv-complete/drive_c/Program Files (x86)/Civilization IV Complete`
> 
>     6. Right-click -> configure on Civ IV and set the executable to the appropriate one in the Game options. `/home/joker/Games/civ-iv-complete/drive_c/Program Files (x86)/Civilization IV Complete/Civ4/Beyond the Sword/Civ4BeyondSword.exe`
> 
>     7. Try launching the game.
> 
> 
> If it's still throwing an error, then I'd recommend taking a look at what the [Lutris installers](https://lutris.net/games/sid-meiers-civilization-iv-the-complete-edition/) are doing to configure the Wine prefix to run the game, and also the [Wine AppDB](https://appdb.winehq.org/objectManager.php?sClass=version&iId=10158) to see any other changes you may need to make.

Okay so I tried but, first of all, nothing happens when I click on "Wine Configurations". Then I thought okay something must've happened when I clicked it, maybe the "drive_c" directory you mentioned would be there and, surely enough, it was. But there was only one "windows" folder inside it and within it two more folders which contained a lot of direct x files.

**Comment by keenanweaver** [comment]
Did you follow the instructions on the [Wine Dependencies](https://github.com/lutris/docs/blob/master/WineDependencies.md) page? It's sounding to me like something is missing or corrupted.

**Comment by IAmJoker47** [comment]
First off, I want to apologize for the late response. I've been very busy these few days.

I think maybe that IS the case. So I tried to install the packages and dependencies but then it showed me the error "N: Updating from such a repository can't be done securely, and is therefore disabled by default." So now I can't install it.

I want to apologize once again for my lack of experience with Linux. I just switched to Linux a few weeks ago.

**Comment by keenanweaver** [comment]
No need to apologize! We were all new at one point or another. I'm still pretty new! Never feel ashamed of inexperience--use it as a motivator to learn. Anyone who chastizes another because of lack of experience needs a lesson in empathy.

I'm not very familiar with Mint or apt, really, so I can't say for certain what's going on. [Here's an older guide](https://www.reddit.com/r/linuxmint/comments/hgfu0f/how_to_set_up_linux_mint_20_for_gaming_native_and/) on Reddit. Maybe steps 2 & 3 will fix it.

**Comment by IAmJoker47** [comment]
Thanks man. You're amazing.

I tried that guide as well and unfortunately, I had no luck. I now think it's probably my laptop. I had some issues trying to install Mint as well. Anyways its not like I can't play at all. Its just Lutris that doesn't work. Wine works just fine. I'm going to get a new PC soon. Hopefully I wont face any problems there.

Thanks to everyone who took their time trying to help. I really appreciated it.

**Comment by keenanweaver** [comment]
Sorry to hear that. Hopefully next time it works out for you.

**Comment by IAmJoker47** [comment]
Yeah man. Thanks for everything.
