### ISSUE TITLE
Images are not loaded by lutris, and I am not seeing all of the games both installed and in search.

### ISSUE THREAD

**Issue by aboss10123** [lutris/lutris#4128]
### Bug description

I am on gentoo, running the latest version of lutris. When I search for a game i.e league of legends I can't find it. And this is the same for many other games too. Also you cant see any images of the games it is just blank. I used to use 0.5.8.4 which didnt have images loaded but atleast I had access to all the games and they were not missing like I have now. 

### How to Reproduce

Latest version of lutris on gentoo.

### Expected behavior

I should see images and see all the games downloaded and in search too not just a select few.

### Log output

```shell
~ lutris -d
2022-03-02 18:28:48,998: Package 'distro' unavailable. Unable to read Linux distribution
2022-03-02 18:28:49,179: Starting Lutris 0.5.9.1
2022-03-02 18:28:49,203: No cores found
2022-03-02 18:28:50,594: Startup complete
INFO     2022-03-02 18:28:50,595 [startup.check_driver:61]:Running AMD Mesa driver 22.0.0 on AM
na_cichlid, LLVM 13.0.0, DRM 3.44, 5.16.6-gentoo-dist) (0x73bf)
INFO     2022-03-02 18:28:50,595 [startup.check_driver:73]:GPU: 1002:73BF 1DA2:E437 (amdgpu dri
DEBUG    2022-03-02 18:28:50,920 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-02 18:28:53,092 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-02 18:28:53,093 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-02 18:28:57,232 [http.get:81]:GET https://lutris.net/api/games?search=league
DEBUG    2022-03-02 18:28:59,229 [lutriswindow.update_store:451]:Showing 250 games
ERROR    2022-03-02 18:28:59,236 [utils.get_pixbuf:51]:Unable to load icon from image /home/tohka/.local/share/lutris/banners/20000-leagues-under-the-sea-captain-nemo.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 455, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store.py", line 158, in add_game
    game.get_pixbuf(),
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store_item.py", line 107, in get_pixbuf
    return get_pixbuf(image_path, self.service_media.size, is_installed=self.installed)
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/utils.py", line 62, in get_pixbuf
    pixbuf.composite(
AttributeError: 'NoneType' object has no attribute 'composite'
DEBUG    2022-03-02 18:29:00,314 [lutriswindow.update_store:451]:Showing 1 games
ERROR    2022-03-02 18:29:00,314 [utils.get_pixbuf:51]:Unable to load icon from image /home/tohka/.local/share/lutris/banners/league-of-legends.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 455, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store.py", line 158, in add_game
    game.get_pixbuf(),
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store_item.py", line 107, in get_pixbuf
    return get_pixbuf(image_path, self.service_media.size, is_installed=self.installed)
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/utils.py", line 58, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py:673: Warning: Source ID 1871 was not found when attempting to remove it
  GLib.source_remove(self.search_timer_id)
DEBUG    2022-03-02 18:29:02,440 [lutriswindow.update_store:451]:Showing 1 games
ERROR    2022-03-02 18:29:02,441 [utils.get_pixbuf:51]:Unable to load icon from image /home/tohka/.local/share/lutris/banners/league-of-legends.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/lutris/gui/lutriswindow.py", line 455, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store.py", line 158, in add_game
    game.get_pixbuf(),
  File "/usr/lib/python3.9/site-packages/lutris/gui/views/store_item.py", line 107, in get_pixbuf
    return get_pixbuf(image_path, self.service_media.size, is_installed=self.installed)
  File "/usr/lib/python3.9/site-packages/lutris/gui/widgets/utils.py", line 58, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
INFO     2022-03-02 18:29:04,207 [application.do_shutdown:631]:Shutting down Lutris
 ~
```

### System Information

```shell
[System]
OS:              u n k n o w n
Arch:            x86_64
Kernel:          5.16.6-gentoo
Desktop:         Not found
Display Server:  tty

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 (sienna_cichlid, LLVM 13.0.0, DRM 3.44, 5.16.6-gentoo-dist)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.0-rc1
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.0-rc1
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.0-rc1
Vulkan:          Supported
```

### Media (optional)

![league](https://user-images.githubusercontent.com/89280115/156425546-1717c753-54fe-4b46-92d7-13d3293c71b4.png)
![steam](https://user-images.githubusercontent.com/89280115/156425578-2132db48-a23c-44fd-b5f5-99feaf56ad83.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by aboss10123** [comment]
I have now installed the zip file for the latest 5.10 beta 2 and I do see more of the games. I am not sure what changed from 0.5.8.4 to 0.5.9 to 0.5.10 to get this weird habit. However I still do not see any pictures for any version so that issue still persists. I would also like to know why it was the case that I could not see all the games in search even if they were downloaded

**Comment by danieljohnson2** [comment]
We've been fixing bugs around this (#3768, #3802, #3907), so I think the latest beta does better here because it crashes less when it can't get the media files.

I'm not sure why you don't have any banners though, but for #3768 it turned out to be a "problem related to my Linux distribution"- somehow it wasn't able to decode the JPEGs as it ought. The fix was to tolerate this better so you could use Lutris without banners if this happened.

**Comment by aboss10123** [comment]
> We've been fixing bugs around this (#3768, #3802, #3907), so I think the latest beta does better here because it crashes less when it can't get the media files.
> 
> I'm not sure why you don't have any banners though, but for #3768 it turned out to be a "problem related to my Linux distribution"- somehow it wasn't able to decode the JPEGs as it ought. The fix was to tolerate this better so you could use Lutris without banners if this happened.

Thanks for the response. I will try to figure out the banner problem then hopefully if anyone else has a similar issue that they will be able to solve it as well. But for now the other issue is solved just the image problem is left. Maybe its something to do with pixbuf? I am not sure

**Comment by aboss10123** [comment]
I solved the issue, looks like I forgot to compile gdkgetpixbuf with jpeg support. It works flawlessly
