### ISSUE TITLE
Fix Ubuntu 14.04 package dependencies

### ISSUE THREAD

**Issue by daniel-j** [lutris/lutris#413]
It depends on `python3-dbus-python`, which I think should be `python3-dbus`.

http://download.opensuse.org/repositories/home:/strycore/xUbuntu_14.04/Packages

![screenshot](http://i.imgur.com/zYDUNA8.png)

**Comment by strycore** [comment]
I think that may be a bug with OBS…

**Comment by strycore** [comment]
Fixed !
