### ISSUE TITLE
Snes9x runner does not install / launch

### ISSUE THREAD

**Issue by tehmasterer** [lutris/lutris#4131]
### Bug description

The Snes9x runner built into Lutris does not install / launch. It doesn't even exist, as I checked the folder in .local. Both the links pointing Snes9x versions on Lutris.net are blank pages. Does this mean support has been dropped?

I compiled the latest version of Snes9x which runs perfect **outside** of Lutris. In Lutris, I pointed to the default installation folder, which holds the emulator and my games. No games will launch when I click play.

- I have no issues with graphics drivers or wine. The emulator and games work fine outside of Lutris. Wine is not involved.
- I already went to Discord for help and got no responses
- Nothing to do with Wine
- Not a feature request

### How to Reproduce

1. Press play on any SNES game in my library.
2. Play changes to **Stop** for about 3 seconds
3. Stop changes back to **Play**
4. Game / Emulator never launches

### Expected behavior

The emulator and game should launch.

Runners don't install

### Log output

```shell
2022-03-03 21:36:23,983: Starting Lutris 0.5.9.1
2022-03-03 21:36:24,022: No cores found
2022-03-03 21:36:25,030: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk/releases
2022-03-03 21:36:26,370: Startup complete
INFO     2022-03-03 21:36:26,371 [startup.check_driver:61]:Running AMD Mesa driver 21.2.6 on Radeon RX 570 Series (POLARIS10, DRM 3.41.0, 5.13.0-30-generic, LLVM 12.0.1) (0x67df)
INFO     2022-03-03 21:36:26,371 [startup.check_driver:73]:GPU: 1002:67DF 1462:341B (amdgpu drivers)
INFO     2022-03-03 21:36:26,371 [startup.check_driver:73]:GPU: 8086:0412 1458:D000 (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
DEBUG    2022-03-03 21:36:26,892 [lutriswindow.update_store:451]:Showing 7 games
MESA-INTEL: warning: Haswell Vulkan support is incomplete
DEBUG    2022-03-03 21:37:05,225 [application.show_window:259]:Showing window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
DEBUG    2022-03-03 21:37:22,456 [application.on_app_window_destroyed:276]:Removed window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
```

### System Information

```shell
[System]
OS:              Ubuntu 21.10 impish
Arch:            x86_64
Kernel:          5.13.0-30-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[C
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
You didn't post any logs of the emulator crashing.
I've tested Snes9x on Pop 21.10 and it was working fine.

**Comment by strycore** [comment]
I added support for the Flatpak version of SNES9x so in case the lutris provided one doesn't work, this is an alternative.
