### ISSUE TITLE
[Feature request] Add game to steam option (SteamDeck)

### ISSUE THREAD

**Issue by liberavia** [lutris/lutris#4137]
Adding a game to steam as a non-steam game should be offered after install and as a game context action.

**Prequisites:**
* Check if steam is installed and only offer option in case that's true
* Use https://github.com/ValvePython/vdf and replace or extend outdated implementation in https://github.com/lutris/lutris/blob/master/lutris/util/steam/vdf.py
* Target is (binary-)file: .steam/debian-installation/userdata/<SteamUserId>/config/shortcuts.vdf

**How can it be managed?**
A small script like this:
```
import vdf
with open('/home/andre/.steam/debian-installation/userdata/114179503/config/shortcuts.vdf', 'rb') as shortcuts:
    data = vdf.binary_loads(shortcuts.read())
```

... produce resultset like this:
```
{
   "shortcuts":{
      "0":{
         "appid":-1795212867,
         "AppName":"Grand Theft Auto V",
         "Exe":"\"lutris\"",
         "StartDir":"\"./\"",
         "icon":"/home/andre/.local/share/icons/hicolor/128x128/apps/lutris_grand-theft-auto-v.png",
         "ShortcutPath":"/home/andre/.local/share/applications/net.lutris.grand-theft-auto-v-61.desktop",
         "LaunchOptions":"lutris:rungameid/61",
         "IsHidden":0,
         "AllowDesktopConfig":1,
         "AllowOverlay":1,
         "OpenVR":0,
         "Devkit":0,
         "DevkitGameID":"",
         "DevkitOverrideAppID":0,
         "LastPlayTime":1609970753,
         "tags":{
            "0":"Installed",
            "1":"Installed  locally"
         }
      },
      ...
   }
}
```

Due to all needed data should be available in lutris, we have to find a way to determine how to safely add new entries and save them back into shortcuts.vdf.

**Comment by liberavia** [comment]
It seems that `vdf.binary_dump(obj, fp)` will do the job of writing: https://github.com/ValvePython/vdf/blob/8104cb27c0b222bd802b69df58204ab389fc714c/vdf/__init__.py#L432

**Comment by strycore** [comment]
once we release 0.5.10, I want to get this PR merged in: https://github.com/lutris/lutris/pull/2729
This is pretty much the same thing

**Comment by liberavia** [comment]
Yes this is exactly what I wanted. At least, I checked that you prefer implementing lib-code over setting it as a dependency ;-)
