### ISSUE TITLE
cursor error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#414]
found this on the terminal when closing Lutris, not sure why

```
Traceback (most recent call last):
  File "/home/user01/src/lutris/lutris/gui/lutriswindow.py", line 375, in refresh_status
    display.set_cursor('default', self.window.get_window())
  File "/home/user01/src/lutris/lutris/util/display.py", line 13, in set_cursor
    window.set_cursor(cursor)
AttributeError: 'NoneType' object has no attribute 'set_cursor'
```

**Comment by strycore** [comment]
The set_cursor function now has a bunch of checks to avoid such errors

**Comment by telanus** [comment]
ERROR    2016-10-18 11:54:10,792 [display]:No window provided in set_cursor

**Comment by daniel-j** [comment]
From where in the code does lutris call `display.set_cursor` that causes this warning to be logged?

**Comment by telanus** [comment]
@daniel-j in lutriswindow.py there is a 
`display.set_cursor('default', self.window.get_window())`

**Comment by daniel-j** [comment]
There are multiple in that file, which one? So, it happens when you close Lutris? With a game running or not?

**Comment by telanus** [comment]
I got this when I was closing Lutris. No game launched by lutris was open

**Comment by daniel-j** [comment]
https://github.com/lutris/lutris/commit/ce70f562127a731486736b08a21c6e631d2c680c
