### ISSUE TITLE
[Feature Request] Right Click to launch

### ISSUE THREAD

**Issue by waffleboi9000** [lutris/lutris#4154]
A feature to right click and immediately launch games from the tray icon (like steam) would be very useful.

**Comment by strycore** [comment]
Enable the tray icon in the preferences and you'll have the 10 last played games launchable directly

![Screenshot from 2022-03-31 15-26-48](https://user-images.githubusercontent.com/280336/161159922-f0c193b2-cad0-4062-b064-9f52c951fa9d.png)
