### ISSUE TITLE
Cant login to Humble Bundle account

### ISSUE THREAD

**Issue by Draluy** [lutris/lutris#4161]
### Bug description

It is not possible to connect to my Humble Bundle account due to Cloudflare rejecting my login request. This only happens on the popup Lutris displays. Using Firefox or Chromium work fine.

### How to Reproduce

1. When I try to connect to my humble bundle account, I clickl on the little person icon at the right of the "Humble bundle" label on  the Sources menu.

2. A popup appears, that asks me to accept cookies. I click on "Agree and access site"

3. I then enter my HUmble Bundle credentials, and click on "LOG IN" (I DONT use "log in with google" or "log in with facebook" )

4. Nothing happens. I can see that this request fails:

curl 'https://www.humblebundle.com/processlogin' \
-X 'POST' \
-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
-H 'Accept: application/json, text/javascript, */*; q=0.01' \
-H 'Referer: https://www.humblebundle.com/login?goto=/home/library' \
-H 'Origin: https://www.humblebundle.com' \
-H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept-Language: en-US' \
-H 'Connection: Keep-Alive' \
-H 'Cookie: _evidon_consent_cookie={"consent_date":"2022-03-21T18:32:13.164Z","consent_type":1}; csrf_cookie=-n4YsgHp7RZ25kP4-1-1647887528; _simpleauth_sess="eyJpZCI6ImxmdXJSUFhyRFYifQ\075\075|1647887528|ed94aff12bf677239acfd593b38261a93203fc72"; __cf_bm=TgZGzmhd1Mq.JJrZXaDea2CHosjf5JbVclH7eEyXjEE-1647887528-0-Af9UaHv0gZvdpVaom/qBFbdnJogq9X22HTpCQMiQYMkNyAKf5+DCeMPoG3zXjrUuDZVARc7n9/a/FRA3IiN730w=; _ga=GA1.2.880843517.1647887529; _gid=GA1.2.26554920.1647887529; _hp2_props.2199522758=%7B%22subscription_perks_status%22%3A%22inactive%22%2C%22pause_state%22%3Afalse%2C%22owns_active_content%22%3Afalse%7D; _hp2_ses_props.2199522758=%7B%22ts%22%3A1647887529014%2C%22d%22%3A%22www.humblebundle.com%22%2C%22h%22%3A%22%2Flogin%22%2C%22q%22%3A%22%3Fgoto%3D%2Fhome%2Flibrary%22%7D; _hp2_id.2199522758=%7B%22userId%22%3A%228610587433836164%22%2C%22pageviewId%22%3A%221677245098279192%22%2C%22sessionId%22%3A%227652094878505599%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%224.0%22%7D; cjConsent=MHxZfDB8Tnww; __ssid=302003cbaf9a15637f99cbf53de99d7; _gcl_au=1.1.487699866.1647887533; _fbp=fb.1.1647887533221.638081395; _rdt_uuid=1647887533235.f9f6e6f6-1e19-4879-b764-62ffbf84a344; _pin_unauth=dWlkPVptTm1aalV4TkRndE9XTmtNaTAwTkRBd0xXRmhOVFF0WXpSak5qTmlZV00xTWpVMw; _gali=' \
-H 'Content-Length: 112' \
-H 'CSRF-Prevention-Token: -n4YsgHp7RZ25kP4-1-1647887528' \
-H 'X-Requested-With: XMLHttpRequest' \
--data 'access_token=&access_token_provider_id=&goto=%2Fhome%2Flibrary&password=<nope>&qs=&username=draluy%40yahoo.fr'

The answer from the server is HTML contains:

<title>Access denied | www.humblebundle.com used Cloudflare to restrict access</title>

and <p>This website is using a security service to protect itself from online attacks.</p>

### Expected behavior

I should be connected to my account.

### Log output

```shell
No need
```

### System Information

```shell
[System]
OS:              Ubuntu 21.10 impish
Arch:            x86_64
Kernel:          5.13.0-35-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            9.3 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.41.0, 5.13.0-35-generic, LLVM 12.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.6
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.6
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by jthadden** [comment]
same here, same error, same <title>Access denied | www.humblebundle.com used Cloudflare to restrict access</title>

**Comment by Drakkai** [comment]
I have the same issue, debug shows only this:
```
DEBUG    2022-03-24 21:50:23,482 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-24 21:50:24,448 [base.login:253]:Connecting to Humble Bundle
https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js:1:7828: CONSOLE LOG Evidon -- evidon-notice-link not found on page, cant display the consent link.
https://www.tp88trk.com/scripts/sdk/everflow.js?_=1648155025597:1:53962: CONSOLE WARN Unable to track. Missing "offer_id" or "transaction_id" parameter.
```

**Comment by Draluy** [comment]
> I have the same issue, debug shows only this:
> 
> ```
> DEBUG    2022-03-24 21:50:23,482 [lutriswindow.update_store:451]:Showing 0 games
> DEBUG    2022-03-24 21:50:24,448 [base.login:253]:Connecting to Humble Bundle
> https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js:1:7828: CONSOLE LOG Evidon -- evidon-notice-link not found on page, cant display the consent link.
> https://www.tp88trk.com/scripts/sdk/everflow.js?_=1648155025597:1:53962: CONSOLE WARN Unable to track. Missing "offer_id" or "transaction_id" parameter.
> ```

Lutris log is useless. To see the request and server response, you have to bring up developer tools using right click->inspect element in the login popup.

**Comment by Drakkai** [comment]
From console:
`[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (processlogin, line 0)`
From response:
```
[...]
            <h1>
                <span class="error-description">Access was denied</span>
                <span class="code-label">
                    Error code 
                    <span>1020</span>
                </span>
            </h1>
            <div class="large-font">
                <p>You do not have access to www.humblebundle.com.</p>
                <p>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.</p>
            </div>
[...]
```

**Comment by ludo77** [comment]
if I click to connect my account.
I have a problem.
`2022-04-02 20:31:00,468: Starting Lutris 0.5.10
2022-04-02 20:31:00,508: No folder at /home/name/.local/share/lutris/runners/retroarch/
2022-04-02 20:31:00,558: Using NVIDIA drivers 470.103.01 for x86_64
2022-04-02 20:31:00,558: GPU: NVIDIA GeForce GTX 1650 Ti
2022-04-02 20:31:00,559: GPU: 10DE:1F95 1043:1E91 (nvidia drivers)
2022-04-02 20:31:00,559: GPU: 8086:9BC4 1043:1E91 (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2022-04-02 20:31:00,632: Startup complete
https://c.evidon.com/sitenotice/evidon-sitenotice-tag.js:1:7828: CONSOLE LOG Evidon -- evidon-notice-link not found on page, cant display the consent link.
https://www.tp88trk.com/scripts/sdk/everflow.js?_=1648924264716:1:53962: CONSOLE WARN Unable to track. Missing "offer_id" or "transaction_id" parameter.
`
once, my login/pw entered, I click on the "connect" button I don't see my game list.

**Comment by ShalokShalom** [comment]
Same on Gamehub. Cloudflare seems to be the issue 
https://github.com/tkashkin/GameHub/issues/627#issuecomment-1093182023=

**Comment by strycore** [comment]
closing as duplicate of #4099
