### ISSUE TITLE
unable to get dxvk1.10L

### ISSUE THREAD

**Issue by witcherenjoyer** [lutris/lutris#4163]
Ok, i am getting very tired trying to solve this issue. I hope someone knows how to solve this.
I have been playing overwatch on lutris without any problems, but once i tried to open battle.net last night i got the error "unable to get dxvk1.10L"
I tried to reinstall battle.net, and it launched and worked, overwatch installed and launched again. but once i quit battle.net, and tried to relaunch it the error returned. 
I tried to google and find fixes, i tried to use the dxvk1.10 release doitsujin, and then i realized it was the L version i needed, i moved it to:  ~/.local/share/lutris/runtime/dxvk/dxvk-1.10L and ran the setup script. 
i once again reinstalled battle.net, but the error persists still. 

i am on opensuse leap 15.3, and i am running the latest version of lutris in my repo. i really hope someone knows how to solve this issue. i look forward to any help

**Comment by Cathie44** [comment]
having the same problem here

**Comment by strycore** [comment]
I believe this was caused by a bad update of DXVK and was solved long ago.
