### ISSUE TITLE
Lutris hangs during creation of new wine prefix

### ISSUE THREAD

**Issue by t0msk** [lutris/lutris#4167]
### Bug description

Hello,

I wanted to install World of Warcraft --> https://lutris.net/games/world-of-warcraft/ (Battle.net version), and during creation of new wine prefix Lutris will hangs as you can see on screenshot and nothings happens (circle animation was animating so it didn't freeze).

### How to Reproduce

Search for game "World of Warcraft" and install it (battle.net version).

### Expected behavior

Wine prefix should be created.

### Log output

```shell
[tomsk@tomsk-PC ~]$ lutris -d
2022-03-23 22:37:36,504: Starting Lutris 0.5.9.1
2022-03-23 22:37:36,532: No cores found
2022-03-23 22:37:37,368: Startup complete
INFO     2022-03-23 22:37:37,369 [startup.check_driver:53]:Using NVIDIA drivers 510.54 for x86_64
INFO     2022-03-23 22:37:37,369 [startup.check_driver:57]:GPU: Unknown
INFO     2022-03-23 22:37:37,369 [startup.check_driver:73]:GPU: 10DE:1C03 1458:3716 (nvidia drivers)
INFO     2022-03-23 22:37:37,370 [startup.check_driver:73]:GPU: 8086:0412 1043:8534 (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
DEBUG    2022-03-23 22:37:37,627 [lutriswindow.update_store:451]:Showing 38 games
DEBUG    2022-03-23 22:37:42,306 [lutriswindow.update_store:451]:Showing 1 games
DEBUG    2022-03-23 22:37:43,585 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-23 22:37:43,586 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2022-03-23 22:37:51,096 [http.get:81]:GET https://lutris.net/api/games?search=world+of+warcraft
DEBUG    2022-03-23 22:37:51,725 [lutriswindow.update_store:451]:Showing 26 games
WARNING  2022-03-23 22:37:53,559 [lutriswindow.on_game_selection_changed:779]:No game found. Replacing with placeholder {'id': 'world-of-warcraft', 'appid': 'world-of-warcraft', 'name': 'World of Warcraft', 'slug': 'world-of-warcraft', 'service': 'lutris'}
DEBUG    2022-03-23 22:37:54,720 [__init__.fetch_script:22]:Fetching installer https://lutris.net/api/installers/world-of-warcraft
DEBUG    2022-03-23 22:37:54,720 [http.get:81]:GET https://lutris.net/api/installers/world-of-warcraft
DEBUG    2022-03-23 22:37:54,918 [application.show_window:259]:Showing window <class 'lutris.gui.installerwindow.InstallerWindow'>world-of-warcraft
DEBUG    2022-03-23 22:37:56,310 [displayconfig.get_current_resolution:624]:Retrieving current resolution
INFO     2022-03-23 22:37:58,655 [runner.get_runner_version:303]:Getting runner information for wine
DEBUG    2022-03-23 22:37:58,655 [http.get:81]:GET https://lutris.net/api/runners/wine
DEBUG    2022-03-23 22:37:58,779 [interpreter.get_runners_to_install:215]:Default wine version is lutris-fshack-7.2
DEBUG    2022-03-23 22:37:58,783 [files_box.check_files_ready:69]:Files are ready? True
DEBUG    2022-03-23 22:37:58,785 [interpreter.create_game_folder:173]:Creating destination path /home/tomsk/Games/world-of-warcraft
DEBUG    2022-03-23 22:38:00,749 [files_box.on_file_available:91]:setup is available
INFO     2022-03-23 22:38:00,749 [files_box.on_file_available:97]:All files available
INFO     2022-03-23 22:38:00,749 [installerwindow.on_files_available:414]:All files are available, continuing install
DEBUG    2022-03-23 22:38:00,750 [interpreter._iter_commands:303]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2022-03-23 22:38:00,751 [cache.save_to_cache:28]:Skipping caching of /run/media/tomsk/Data/Games/.lutris_cache/world-of-warcraft/setup/Battle.net-Setup-enUS.exe, already cached in /run/media/tomsk/Data/Games/.lutris_cache/world-of-warcraft/setup
INFO     2022-03-23 22:38:00,752 [wine.create_prefix:96]:Creating a win64 prefix in /home/tomsk/Games/world-of-warcraft
DEBUG    2022-03-23 22:38:00,752 [system.execute:49]:Executing /home/tomsk/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wineboot
DEBUG    2022-03-23 22:38:00,752 [system.execute:55]:WINEARCH=win64 WINEPREFIX=/home/tomsk/Games/world-of-warcraft WINEDLLOVERRIDES=winemenubuilder=
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.16.16-arch1-1
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             15.3 GB
Swap:            7.6 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL Version:  3.0 Mesa 21.3.7
OpenGL Core:     4.5 (Core Profile) Mesa 21.3.7
OpenGL ES:       OpenGL ES 3.1 Mesa 21.3.7
Vulkan:          Supported
```

### Media (optional)

![Screenshot from 2022-03-23 22-37-22](https://user-images.githubusercontent.com/7276200/159801101-ac75362f-26dc-4ded-a7a9-ac0fe60348c8.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This one I figured I could take a crack at, but it failed to repro entirely for me. World of Warcraft installed and could start; no freeze or hang. I tried with versions 5.9.1 and the current master as well; both were fine for me.

There's nothing I see in the log I can work on either.

This does seem similar to #3973, but that issue didn't get resolved either. So that's not too helpful. 

I think there must be something outside of Lutris to explain this; you seem to be having a lot of problems, and I wonder if they aren't caused by some common factor- whatever that might be.

**Comment by t0msk** [comment]
> This one I figured I could take a crack at, but it failed to repro entirely for me. World of Warcraft installed and could start; no freeze or hang. I tried with versions 5.9.1 and the current master as well; both were fine for me.
> 
> There's nothing I see in the log I can work on either.
> 
> This does seem similar to #3973, but that issue didn't get resolved either. So that's not too helpful.
> 
> I think there must be something outside of Lutris to explain this; you seem to be having a lot of problems, and I wonder if they aren't caused by some common factor- whatever that might be.

Interesting, my biggest problem now is that Wine games aren't working under X.org with NVIDIA offload (https://github.com/lutris/lutris/issues/4165), but under Wayland they launch.

And this prefix issue, I don't know how to workaround it.

**Comment by danieljohnson2** [comment]
Well, have you tried to install WoW while using Wayland? If that works, it would suggest that this is all tied to your X11 problem.

**Comment by t0msk** [comment]
> Well, have you tried to install WoW while using Wayland? If that works, it would suggest that this is all tied to your X11 problem.

Yes, I tried it now and under Wayland prefix was created just fine.

![image](https://user-images.githubusercontent.com/7276200/159808034-bd0a7be6-fb7d-4d86-a312-af5bb62fffcd.png)

**Comment by danieljohnson2** [comment]
Then I think that these two issues are really just one- WINE not working on X11. But I haven't a clue what that would be, so I'm still not able to help with it.

**Comment by t0msk** [comment]
At least we know that there is some issue between Wine and X11 :)

**Comment by t0msk** [comment]
Looks like this is solved because of this --> https://github.com/lutris/lutris/issues/4165

**Comment by kbulgrien** [comment]
I have had two install scripts (Lord of the Rings Online and Magic the Gathering Arena) obtained from the Lutris site repeatedly fail to create a prefix.  The script does act like it creates it, including downloading dependencies like .NET stuff, but then when its all said and done, the game launch icons spins and fails to launch the game.  Looking at the wine prefix, its not there.  Monitoring the place where the prefix is created shows it creates, but then it mysteriously disappears, and oddly enough the dependencies show as installing even when it is not there on the disk.  This using 0.5.8.4.  I had create the prefix and manually start the installer for it to work.  I'm using KDE/Plasma.

**Comment by SuperSandro2000** [comment]
I run into a similar issue which was solved by creating the directory where the prefix should be installed into.

**Comment by strycore** [comment]
I can confirm the issue with wine + vfio drivers. We can track this issue in #4165
