### ISSUE TITLE
Can't install script on 0.4

### ISSUE THREAD

**Issue by scottviger** [lutris/lutris#417]
Can't install script with "lutris -i"
![as2](https://cloud.githubusercontent.com/assets/22118081/19462926/d051a6fc-94bd-11e6-8bc8-ab9ffac3713d.png)

As you can see the command "lutris -i /home/scottviger/Bureau/minecraft" **(1)**
Result in this:
`scottviger@tuxinatux:~$ lutris -i /home/scottviger/Bureau/minecraft
INFO     2016-10-17 23:04:48,730 [lutris]:Installing 
Traceback (most recent call last):
  File "/usr/bin/lutris", line 202, in <module>
    InstallerDialog(installer or game_slug)
  File "/usr/lib/python3/dist-packages/lutris/gui/installgamedialog.py", line 85, in __init__
    self.get_scripts()
  File "/usr/lib/python3/dist-packages/lutris/gui/installgamedialog.py", line 105, in get_scripts
    self.on_scripts_obtained(scripts)
  File "/usr/lib/python3/dist-packages/lutris/gui/installgamedialog.py", line 127, in on_scripts_obtained
    self.choose_installer()
  File "/usr/lib/python3/dist-packages/lutris/gui/installgamedialog.py", line 159, in choose_installer
    runner = script['runner']
KeyError: 'runner'
scottviger@tuxinatux:~$ 
`
And trigger **(2)** and **(3 if lutris is already open)**

**(4)** is the [code i used ](https://lutris.net/games/install/59/view) , i tried json and yalm, neither worked.

I'm on Xubuntu 16.10, if you need more info, just ask (;
Don't stop your great work!

**Comment by strycore** [comment]
Ah, I see what's going on…
The script you see here is not complete, when you install the usual way, there is some extra info added (for instance, the runner, which is missing here). If you need to get a copy of the script locally, there is a "Download script" link below "View script". 

I'll make it clear on the website that "View script" is not fit for installation and I'll also catch that error so it displays a proper error message.

**Comment by strycore** [comment]
Those kind of errors will be caught in the next client update and I added a note on top of the View script page.
