### ISSUE TITLE
Suggest installing Ubisoft Connect after logging in the service

### ISSUE THREAD

**Issue by zolfone** [lutris/lutris#4174]
Hi,
I cloned lutris from git to test Origin and Ubisoft Connect but without success so far.
With Origin I can login successfully from the gui but then it doesn't load my library
and I have to relogin because it doesn't keep the credentials I just gave it.
Here's what I see on the console when logging in with Origin:

```
https://eaassets-a.akamaihd.net/resource_signin_ea_com/551.0.20220304.209.e841b7c/p/statics/originX/js/jquery.originX-pc-common.v_1618545688-min.js:1:9015:``` CONSOLE LOG [ORIGIN][WEBCHANNEL] No connection.
https://signin.ea.com/p/originX/login?execution=e443737216s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fdisplay%3DoriginXWeb%252Flogin%26response_type%3Dcode%26release_type%3Dprod%26redirect_uri%3Dhttps%253A%252F%252Fwww.origin.com%252Fviews%252Flogin.html%26locale%3Den_US%26client_id%3DORIGIN_SPA_ID:44:28: CONSOLE LOG authenticaitonJShelper undefined
https://signin.ea.com/p/originX/login?execution=e443737216s1&initref=https%3A%2F%2Faccounts.ea.com%3A443%2Fconnect%2Fauth%3Fdisplay%3DoriginXWeb%252Flogin%26response_type%3Dcode%26release_type%3Dprod%26redirect_uri%3Dhttps%253A%252F%252Fwww.origin.com%252Fviews%252Flogin.html%26locale%3Den_US%26client_id%3DORIGIN_SPA_ID:52:28: CONSOLE LOG [[ env =
https://www.origin.com/views/login.html?code=QUOwAB405q2PF8idA-svf5eJClc10alh0meNTAnkAQ:13:29: CONSOLE JS WARN Can't close the window since it was not opened by JavaScript
2022-03-27 13:34:08,032: Error while completing task <bound method BaseService.reload of <origin.OriginService object at 0x7f1a2c507380 (lutris+services+origin+OriginService at 0x560ee48cca60)>>: <class 'RuntimeError'> User not authenticated to Origin
  File "/home/user/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/user/lutris/lutris/services/base.py", line 96, in reload
    self.load()
  File "/home/user/lutris/lutris/services/origin.py", line 208, in load
    user_id, _persona_id, _user_name = self.get_identity()
  File "/home/user/lutris/lutris/services/origin.py", line 176, in get_identity
    identity_data = self._request_identity()
  File "/home/user/lutris/lutris/services/origin.py", line 170, in _request_identity
    headers=self.get_auth_headers()
  File "/home/user/lutris/lutris/services/origin.py", line 252, in get_auth_headers
    raise RuntimeError("User not authenticated to Origin")
```
Same goes for Ubisoft Connect, I can login, this time it keeps the credentials but no game library:

```
https://ubistatic-a.akamaihd.net/0106/prod/global/tracking/analyticssdk.js:2:124800: CONSOLE LOG %cAnalytics SDK: Privacy has not been accepted to use pageevent: background: #222; color: #bada55 [object Object]
2022-03-27 14:47:12,759: Response status: <Response [200]>
2022-03-27 14:47:12,923: Response status: <Response [200]>
2022-03-27 14:47:12,924: No headers in kwargs, using session headers
2022-03-27 14:47:13,138: Response status: <Response [200]>
2022-03-27 14:47:13,141: No headers in kwargs, using session headers
2022-03-27 14:47:13,368: Response status: <Response [200]>
2022-03-27 14:47:13,368: No headers in kwargs, using session headers
2022-03-27 14:47:13,677: Response status: <Response [200]>
2022-03-27 14:47:13,678: Ubisoft Connect not installed
```
I hope it's the right place to report this, if not please forgive me and point me to the right section.
Let me know if I can can do to help or test something to make it work.

Thanks

**Comment by zolfone** [comment]
Hi @strycore,
I'll try that and let you know how it goes, actually I have at least a game in my Ubisoft library.
What about Origin though?
Thanks

**Comment by zolfone** [comment]
So I installed Ubisoft Connect and it let me log in, but I see only demo games in my library from lutris.
If I run Ubisoft Connect I can see both demo and bought games in the library.

**Comment by zolfone** [comment]
> If you refresh your game list in Lutris, it should show all games now that Ubisoft Connect is installed

I tried refreshing and even logging out/in again, I still see only demo games
> Origin should work, if you have auth issues try logging out then logging back in.

Logged out but didn't work, I had to tick "remember me" on the credentials to make it work the first time.

**Comment by lal12** [comment]
Do you see any exception in your lutris log? Issue #4193 prevented some games from loading for me.

**Comment by zolfone** [comment]
No, I see no exceptions on the console output, I can't find any other specific lutris log (if there are any).

**Comment by lal12** [comment]
Adding `print(response)` after line 151 of `lutris/services/ubisoft.py` might be helpful. Look if you can see your games anywhere in the output and/or post the corresponding output here.

**Comment by zolfone** [comment]
I did as you suggested, here is the output:
`{'data': {'viewer': {'id': 'some-alphanumeric-id', 'ownedGames': {'totalCount': 0, 'nodes': []}}}}`
(I obfuscated the ID just for precaution, I don't know if it's my Ubisoft ID or some other sensitive data)
I tried logging out/in again in Ubisoft, same story.

**Comment by lal12** [comment]
Well that at least limits the possibilities. It seems that for whatever reason the API or the request send to it don't work for you.
I couldn't find any information about this API, so I don't know where the developers got it from. But since the URL includes`v1` and `uplay` it might be the old API for Uplay and only showing data if you actually had an (older) Uplay account.

I also couldn't find the API being used by the Ubisoft Connect client anymore, it instead uses a (mostly) binary API via `dmx.upc.ubisoft.com`. 

How old is your account?

**Comment by zolfone** [comment]
It is old for sure, I bought the game in the 2014 and I played it with Uplay, so maybe that's the problem.
I'm not a developer so I can only help with testing if you tell me what to do.
Thanks

**Comment by strycore** [comment]
Lutris will now check if the game launcher is installed before logging in a service. Maybe there can also be a check so see if the user is logged in the client,  which is necessary for Ubisoft Connect.
