### ISSUE TITLE
Steam updated this morning. Lutris doesn't work

### ISSUE THREAD

**Issue by Dichotomia** [lutris/lutris#4175]
ibGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/quentin/.drirc: No such file or directory.
libGL: using driver amdgpu for 4
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/quentin/.drirc: No such file or directory.
libGL: pci id for fd 4: 1002:67df, driver radeonsi
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/quentin/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/quentin/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/quentin/.drirc: No such file or directory.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
libGL: Using DRI3 for screen 0
2022-03-29 10:06:18,243: Starting Lutris 0.5.9.1
2022-03-29 10:06:18,308: No cores found
2022-03-29 10:06:19,592: Startup complete
2022-03-29 10:06:19,593: Running AMD Mesa driver 22.0.0 on AMD Radeon RX 590 Series (polaris10, LLVM 13.0.1, DRM 3.44, 5.17.0-rc8-amd64) (0x67df)
2022-03-29 10:06:19,593: GPU: 1002:67DF 1682:9587 (amdgpu drivers)
libGL: Can't open configuration file /etc/drirc: Aucun fichier ou dossier de ce type.
libGL: Can't open configuration file /home/quentin/.drirc: Aucun fichier ou dossier de ce type.
libGL: Can't open configuration file /etc/drirc: Aucun fichier ou dossier de ce type.
libGL: Can't open configuration file /home/quentin/.drirc: Aucun fichier ou dossier de ce type.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
2022-03-29 10:06:27,897: Runtime disabled by system configuration
2022-03-29 10:06:28,118: Unable to load libGLX_nvidia.so.0
2022-03-29 10:06:28,118: Unable to locate libGLX_nvidia
2022-03-29 10:06:28,136: Runtime disabled by system configuration
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 756, in get_env
    env["WINE"] = self.get_executable()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 524, in get_executable
    wine_path = self.get_path_for_version(version)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 505, in get_path_for_version
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'

**Comment by Dichotomia** [comment]
Ok i made the same modification as in https://github.com/lutris/lutris/commit/072e72a4aefd91101b79dd05d8ce9f100a4b6b0c and it works

**Comment by strycore** [comment]
if the non beta Steam update is crashing the current stable version of Lutris, this means we should push the update asap. 

Leaving this open for now to give some visibility.

**Comment by NysNight** [comment]
Here is a short explanation for the not so coding savy people who are trying to fix their lutris game launch problem and don't know what to do with the commit linked above in Dichotomia's second comment.

You need to find where this file lives on your drive first of all, of course.

For me it was `/usr/lib/python3.10/site-packages/lutris/util/steam/`
I expect it will be the same for most.

If it's not there, start lutris via the terminal using -d, so `lutris -d`
Then start whatever game you're having trouble with.
If it hangs at a Key Error and the last few lines are talking about contentstatsid, this is exactly the problem we're trying to fix.
It should also inform you of the path if you look in the last few lines of debug info.

Now that we know where it is, open `config.py` with an editor with sudo. (Maybe make a backup first if you're not sure what you're doing)
Go to line 161 and ad `, None` right after `"contentstatsid"`

The line should now look as it does in the commit above .
`         library["libraryfolders"].pop("contentstatsid", None)`

If your editor supports syntax highlighting and your entry isn't highlighted, you've likely done something wrong.
Save the file. Restart lutris and try to launch your game, it should work now.

Hope this helps someone.

**Comment by there-is-foxy** [comment]
help I'm new to all that and I'm pretty lost, someone could help me ? I'm here because I have an issue with lol

**Comment by strycore** [comment]
> help I'm new to all that and I'm pretty lost, someone could help me ? I'm here because I have an issue with lol

just wait for the next release

**Comment by strycore** [comment]
It's out https://github.com/lutris/lutris/releases/tag/v0.5.10

**Comment by Dichotomia** [comment]
Thanks a lot

**Comment by pungentstentch** [comment]
Thanks, it solved my issue too.

**Comment by gDollaZ** [comment]
This fix worked here on Ubuntu 22.04:
/usr/lib/python3/dist-packages/lutris/util/steam/config.py

i know this is closed and fixed in the next release, but just wanted to add this if anyone stumbles across this in the mean time

**Comment by DaDummy** [comment]
If you're stuck with the broken version 5.9.1 on Ubuntu 22.04, add the ppa as described here to get the Update: https://lutris.net/downloads

**Comment by xdrago1** [comment]
> 

I did that so many times now, but im still stuck on 5.9.1. What ever I do it always installs that broken version....

**Comment by M4rQu1Nh0S** [comment]
> Here is a short explanation for the not so coding savy people who are trying to fix their lutris game launch problem and don't know what to do with the commit linked above in Dichotomia's second comment.
> 
> You need to find where this file lives on your drive first of all, of course.
> 
> For me it was `/usr/lib/python3.10/site-packages/lutris/util/steam/` I expect it will be the same for most.
> 
> If it's not there, start lutris via the terminal using -d, so `lutris -d` Then start whatever game you're having trouble with. If it hangs at a Key Error and the last few lines are talking about contentstatsid, this is exactly the problem we're trying to fix. It should also inform you of the path if you look in the last few lines of debug info.
> 
> Now that we know where it is, open `config.py` with an editor with sudo. (Maybe make a backup first if you're not sure what you're doing) Go to line 161 and ad `, None` right after `"contentstatsid"`
> 
> The line should now look as it does in the commit above . ` library["libraryfolders"].pop("contentstatsid", None)`
> 
> If your editor supports syntax highlighting and your entry isn't highlighted, you've likely done something wrong. Save the file. Restart lutris and try to launch your game, it should work now.
> 
> Hope this helps someone.

Fixed here too, this problem come to me after install a new distro, keeping the /home directory in another partition and without steam after new system install.

**Comment by Request7535** [comment]
> > 
> 
> I did that so many times now, but im still stuck on 5.9.1. What ever I do it always installs that broken version....

I had the same issue, uninstalling and reinstalling Lutris multiple times, with the "About Lutris" section always saying 0.5.9 instead of 0.5.10. I also fixed the config.py file as specified here, which didn't really do anything.

However after a restart of my machine (it was switched off overnight actually) it now seems to work. I can launch my games and Lutris prints 0.5.10. No idea what changed, it feels like a caching-problem to me.

So I can confirm that this worked for me on Ubuntu 22.04 (I started having this problem after upgrading from 20.04)

**Comment by judofright** [comment]
can't use wine to directly target an exe file.  Lutris config is denying me permission.  even tho I'm supposed to be admin.  really getting turned off by linux right now.

**Comment by LeoColman** [comment]
> However after a restart of my machine (it was switched off overnight actually) it now seems to work. I can launch my games and Lutris prints 0.5.10. No idea what changed, it feels like a caching-problem to me.

With this idea in mind, `pkill - lutris` did the job to update the version for me.
