### ISSUE TITLE
Libgomp not found

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#419]
Got this when I tried to run PPSSPP and forgot to disable the lutris runtime :smiley_cat: 
`
/usr/games/ppsspp: /home/user01/.local/share/lutris/runtime/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/lib/x86_64-linux-gnu/libsoxr.so.0)`

**Comment by strycore** [comment]
I have added libsoxr.so.0 to the runtime which should fix the issue.
