### ISSUE TITLE
[idea] Quit lutris after running a game started from command line

### ISSUE THREAD

**Issue by rapenne-s** [lutris/lutris#4191]
hi, that would be very convenient if lutris could close itself after closing a game run from the command line through lutris. This would be really useful since it's now easy to add a Lutris game to steam. I use this new feature for playing games remotely, but it's not practical when lutris stays opened once I quit the game, and that I just have a controller in my hands.

I've looked for a command line parameter or option for this purpose but I didn't find any.

**Comment by crtgamer** [comment]
hello.  would you please describe the method you are using to launch the game in more detail? would it be possible to add a Post-exit script in the game's system options menu, or perhaps an exit or kill function to your launch script/command?

**Comment by rapenne-s** [comment]
@crtgamer in Lutris I do a right click on a game, and "Create steam shortcut", that's all. Then if I run the game from Steam, Lutris will stay open once I quit the game.

**Comment by strycore** [comment]
@rapenne-s do you have "Minimize client while game is running" enabled?
I had this enabled and Lutris wouldn't quit when launched from the Steam Deck UI. Once disabled, the game would quit properly.

**Comment by rapenne-s** [comment]
I confirm this. Using "Minimize client while game is running" will display Lutris after exiting the game. If disabled, lutris doesn't seem to be running at all once the game is closed.

**Comment by strycore** [comment]
Lutris will no longer open the UI if only a game or an installation is launched
