### ISSUE TITLE
Migrate list view to Gtk.ListBox

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#420]
Having an API a lot closer to Gtk.FlowBox, the ListBox will allow to remove legacy code, allow for more customisation in the layout and provide an overall cleaner codebase. 

The widget has made available in Gtk 3.10 so it shouldn't be an issue for Ubuntu 14.04 and Mint 17.3 users.

https://developer.gnome.org/gtk3/stable/GtkListBox.html

**Comment by strycore** [comment]
@TingPing do you feel like taking up on this one? if not, no problem, I'll postpone it for 0.5, it's not urgent.

**Comment by TingPing** [comment]
Probably not in the near future. TBH Gtk.ListBox, while having potential for a clean unified API, is pretty awful atm.

Firstly the performance of it is trash, once you get just hundreds to a thousand entries it visibly lags. Secondly it has the great promise of directly mapping to a `Gio.ListModel` except if you use that feature you suddenly lose filtering and sorting and there is no implementation of a sortable/filterable `Gio.ListModel`. And there are no pythonic overrides for `Gio.ListStore/Gio.ListModel` yet (minor deal though).

**Comment by strycore** [comment]
I've noticed that the Flowbox was a lot slower to display all games compared to the IconView. I also has the same impression of an unfinished API regarding ListModel.

The thing is that we now have 2 codebases to manage the game list: one for the FlowBox and one for the ListView. Do you have any idea if the situation on the ListModel is going to improve soon (like in Gtk 4.0)?

**Comment by TingPing** [comment]
Most of the work in Gtk4 so far is removing deprecated things and completely redoing rendering. So not much time has been spent on any specific widgets to my knowledge.

**Comment by strycore** [comment]
If they don't fix the performance issues, I'm not planning to use ListBox or FlowBox any time soon. The default view has been reverted to GameGridView.
