### ISSUE TITLE
error running "lutris --list-steam-folders"  - TypeError: 'dict_values' object is not subscriptable

### ISSUE THREAD

**Issue by spirritus** [lutris/lutris#4202]
### Bug description

running "lutris --list-steam-folders" produces  the error: 
TypeError: 'dict_values' object is not subscriptable

I assume the above is also why steam games do not show up in lutris.

### How to Reproduce

1. run lutris --list-steam-folders 
2. observe error

### Expected behavior

steam folders are listed

### Log output

```shell
2022-04-08 14:32:39,857: Starting Lutris 0.5.10
2022-04-08 14:32:39,883: No folder at /home/dc/.local/share/lutris/runners/retroarch/
2022-04-08 14:32:40,021: Using NVIDIA drivers 510.54 for x86_64
2022-04-08 14:32:40,021: GPU: Unknown
2022-04-08 14:32:40,021: GPU: 10DE:13C0 1462:3170 (nvidia drivers)
2022-04-08 14:32:40,021: GPU: 8086:0412 1043:8534 (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 434, in do_command_line
    self.print_steam_folders(command_line)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 782, in print_steam_folders
    for path in steamapps_paths[platform] if steamapps_paths else []:
TypeError: 'dict_values' object is not subscriptable
2022-04-08 14:32:40,118: Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 11 bullseye
Arch:            x86_64
Kernel:          5.16.0-0.bpo.3-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             15.5 GB
Swap:            7.5 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 980/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.54
OpenGL Core:     4.6.0 NVIDIA 510.54
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.54
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
The code that is failing here is odd; it's trying to look-ups for the Linux and Windows platform, but I can't see why it would and there does not seem to be anywhere to do the look up. But I think it does not need to do this. So I'll pop a PR to remove this look-up; perhaps there's just no need for it.
