### ISSUE TITLE
v0.5.10 not available for Ubuntu users

### ISSUE THREAD

**Issue by victoria-miltcheva** [lutris/lutris#4204]
The recent [v0.5.10](https://github.com/lutris/lutris/releases/tag/v0.5.10) update wasn't made available to Ubuntu users - [`0.5.9.1`](https://launchpad.net/~lutris-team/+archive/ubuntu/lutris) is the latest available version.

**Comment by victoria-miltcheva** [comment]
I've tried running the below commands, but the new update is not available:
```
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt update
sudo apt install lutris
```
Output of last command:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lutris is already the newest version (0.5.9.1~ubuntu21.10.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by strycore** [comment]
Please use the contact form on launchpad to notify the maintainer: https://launchpad.net/%7Elutris-team/+contactuser

**Comment by muzena** [comment]
@victoria-miltcheva 
Fixed.
https://code.launchpad.net/~lutris-team/+recipe/lutris-stable
