### ISSUE TITLE
[0.5.10] Your system kernel is not patched with fsync

### ISSUE THREAD

**Issue by Sengorius** [lutris/lutris#4208]
### Bug description

I'm playing Guild Wars 2 with Lutris for several months now and its working great. Today I installed the 0.5.10 version via package manager on Linux Mint and things started to fail. Starting the game is impossible now, as 2 popups appear

1. "Your system kernel is not patched with fsync" (maybe different translation as I see the message in german)
2. Unknown error: FSYNC_NOT_SUPPORTED

However downgrading to 0.5.9 totally fixed that issue. I have just that game installed, so I cannot reproduce this with other games.

### How to Reproduce

1. Install game
2. Install current version of Lutris
3. Try to start the game (doesn't matter if from shell or application starter)

### Expected behavior

What is `fsync` and why do I need it now?

### Log output

```shell
└─▶ lutris -d
INFO     2022-04-10 11:02:11,492 [startup.init_lutris:173]:Starting Lutris 0.5.10
DEBUG    2022-04-10 11:02:11,535 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-04-10 11:02:11,623 [startup.check_driver:57]:Using NVIDIA drivers 510.54 for x86_64
INFO     2022-04-10 11:02:11,623 [startup.check_driver:61]:GPU: Unknown
INFO     2022-04-10 11:02:11,623 [startup.check_driver:77]:GPU: 10DE:1C03 1462:3281 (nvidia drivers)
INFO     2022-04-10 11:02:11,695 [startup.update_runtime:213]:Startup complete
DEBUG    2022-04-10 11:02:11,807 [lutriswindow.update_store:437]:Showing 3 games
WARNING  2022-04-10 11:02:19,249 [application.on_game_stop:691]:1 not in []
ERROR    2022-04-10 11:02:19,264 [lutriswindow.on_game_error:678]:Guild Wars 2 (wine) crashed
```

### System Information

```shell
[System]
OS:              Linux Mint 20.3 una
Arch:            x86_64
Kernel:          5.13.0-39-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.54
OpenGL Core:     4.6.0 NVIDIA 510.54
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.54
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Ztrawberry777** [comment]
Same here - Updated this morning and Starcraft 2 fails with the same error.

Unknown error: FSYNC_NOT_SUPPORTED

**System Information**

`[System]
OS:              Ubuntu 21.10 impish
Arch:            x86_64
Kernel:          5.13.0-39-generic
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             15.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce 840M/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.103.01
OpenGL Core:     4.6.0 NVIDIA 470.103.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.103.01
Vulkan:          Supported

`

**Comment by danieljohnson2** [comment]
I have a guess.

Lutris 0.5.10 has fsync turned on by default, so maybe you don't have fsync kernel support and don't need it, but Lutris 0.5.10 now tries to enable it anyway and fails and it all ends in tears.

Try turning off "Enable fsync" in the "Runner options" of your game configuration. Does that fix the issue?

If I'm right about this, maybe Lutris should be smarter about its default here, if that is possible.

**Comment by Ztrawberry777** [comment]
> I have a guess.
> 
> Lutris 0.5.10 has fsync turned on by default, so maybe you don't have fsync kernel support and don't need it, but Lutris 0.5.10 now tries to enable it anyway and fails and it all ends in tears.
> 
> Try turning off "Enable fsync" in the "Runner options" of your game configuration. Does that fix the issue?
> 
> If I'm right about this, maybe Lutris should be smarter about its default here, ~if that is possible~ since that is possible. I've got a PR for that, but let me know if turning off fsync helps for you. I'll make a note of it.

Yep, I turned it off globally and everything is now back to normal. Thanks @danieljohnson2

**Comment by danieljohnson2** [comment]
Excellent!

**Comment by Sengorius** [comment]
Yes, works for me, too! Thank you!

**Comment by Raybeth** [comment]
Had the same error 

> I have a guess.
> 
> Lutris 0.5.10 has fsync turned on by default, so maybe you don't have fsync kernel support and don't need it, but Lutris 0.5.10 now tries to enable it anyway and fails and it all ends in tears.
> 
> Try turning off "Enable fsync" in the "Runner options" of your game configuration. Does that fix the issue?
> 
> If I'm right about this, maybe Lutris should be smarter about its default here, ~if that is possible~ since that is possible. I've got a PR for that, but let me know if turning off fsync helps for you. I'll make a note of it.


Actually works! Thanks!
