### ISSUE TITLE
mangohud.x86 doesn't exist anymore

### ISSUE THREAD

**Issue by aMir733** [lutris/lutris#4214]
### Bug description

As mentioned [here](https://github.com/flightlessmango/MangoHud/issues/328), the binary file `mangohud.x86` does not exist anymore and it's been baked into the main `mangohud` binary. But lutris still tries to execute `mangohud.x86` when setting the `FPS counter (MangoHud)` setting to `Enabled (32bit)`.

### How to Reproduce

1. Get the latest (0.6.6-1) MangoHud version, build and install it.
2. Set the configuration setting `FPS counter (MangoHud)` to `Enabled (32bit)`
3. Look at the produced log errors

### Expected behavior

Lutris executing the main `mangohud` even for 32bit applications.

### Log output

```shell
Start monitoring process.
env: ‘mangohud.x86’: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

### System Information

```shell
[System]
OS:              u n k n o w n
Arch:            x86_64
Kernel:          5.17.2-tkg-pds
Desktop:         Unity
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (dimgrey_cavefish, LLVM 13.0.1, DRM 3.44, 5.17.2-tkg-pds)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.1.0-devel (git-5da8c280b7)
OpenGL Core:     4.6 (Core Profile) Mesa 22.1.0-devel (git-5da8c280b7)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.1.0-devel (git-5da8c280b7)
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by aMir733** [comment]
You can solve this issue temporarily by making a symlink in your path pointing to the main `mangohud` binary.
```
sudo ln -s mangohud $(which mangohud).x86
```

**Comment by strycore** [comment]
This simplifies the MangoHUD option and allows it to be converted to a simple switch!

Fixed in https://github.com/lutris/lutris/commit/50cdc65e77a6fd2f2b8779d4f80458c9e777ef85
