### ISSUE TITLE
[issue] AttributeError 'NoneType' when calling dll_manager.version.lower()

### ISSUE THREAD

**Issue by gbschenkel** [lutris/lutris#4216]
### Bug description

Trying to install Star Citizen, when Lutris try to install DLLs it throw an error. `NoneType' object has no attribute 'lower'`.
I realize is similar to the #3787 and I was using 0.5.9.1, and I upgraded to 0.5.10, but it is not the same.

```bash
ERROR    2022-04-12 00:42:28,265 [jobs.target:36]:Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7f5ff2393880 (lutris+installer+interpreter+ScriptInterpreter at 0x2b6ed40)>>: <class 'AttributeError'> 'NoneType' object has no attribute 'lower'
  File "/usr/lib64/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/lutris/installer/commands.py", line 436, in task
    command = task(**data)
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 346, in winetricks
    return wineexec(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 299, in wineexec
    wine.prelaunch()
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 799, in prelaunch
    self.setup_dlls(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 776, in setup_dlls
    if dll_manager.version.lower() != "manual":
ERROR    2022-04-12 00:42:28,266 [interpreter._iter_commands:302]:Last install command failed, show error
```

### How to Reproduce

1. Try to install Star Citizen
2. After clicking on Install the problem arise

### Expected behavior

Install the game.

### Log output

```shell
INFO     2022-04-12 00:54:54,131 [startup.init_lutris:173]:Starting Lutris 0.5.10
WARNING  2022-04-12 00:54:54,159 [libretro.get_libretro_cores:24]:No folder at /home/schenkel/.local/share/lutris/runners/retroarch/
DEBUG    2022-04-12 00:54:54,167 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-04-12 00:54:54,199 [startup.check_driver:65]:Running AMD Mesa driver 21.3.8 on AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.44.0, 5.17.2, LLVM 13.0.1) (0x73bf)
INFO     2022-04-12 00:54:54,199 [startup.check_driver:77]:GPU: 1002:73BF 1043:04F2 (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
INFO     2022-04-12 00:54:54,278 [startup.update_runtime:213]:Startup complete
DEBUG    2022-04-12 00:54:54,430 [lutriswindow.update_store:437]:Showing 0 games
DEBUG    2022-04-12 00:54:56,837 [application.show_window:332]:Showing window AddGamesWindow{}
DEBUG    2022-04-12 00:55:01,559 [http.get:83]:GET https://lutris.net/api/games?search=star+citizen&with-installers=True
DEBUG    2022-04-12 00:55:02,957 [api.get_game_installers:160]:Fetching installer https://lutris.net/api/installers/star-citizen
DEBUG    2022-04-12 00:55:02,958 [http.get:83]:GET https://lutris.net/api/installers/star-citizen
DEBUG    2022-04-12 00:55:03,380 [application.show_window:332]:Showing window InstallerWindowstar-citizen
DEBUG    2022-04-12 00:55:03,381 [application.on_app_window_destroyed:350]:Removed window AddGamesWindow{}
DEBUG    2022-04-12 00:55:04,146 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-04-12 00:55:05,568 [interpreter.get_extras:159]:Checking if service provide extra files
DEBUG    2022-04-12 00:55:05,568 [installer.prepare_game_files:146]:No service to retrieve files from
DEBUG    2022-04-12 00:55:05,582 [interpreter.create_game_folder:181]:Creating destination path /home/schenkel/Games/star-citizen
DEBUG    2022-04-12 00:55:07,036 [downloader.start:65]:⬇ https://install.robertsspaceindustries.com/star-citizen/RSI-Setup-1.5.4.exe
DEBUG    2022-04-12 00:55:12,200 [downloader.download_cb:125]:Finished downloading https://install.robertsspaceindustries.com/star-citizen/RSI-Setup-1.5.4.exe
INFO     2022-04-12 00:55:12,547 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-04-12 00:55:12,547 [files_box.on_file_available:93]:client is available
INFO     2022-04-12 00:55:12,547 [files_box.on_file_available:99]:All files available
INFO     2022-04-12 00:55:12,547 [installerwindow.on_files_available:463]:All files are available, continuing install
DEBUG    2022-04-12 00:55:12,549 [interpreter._iter_commands:317]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2022-04-12 00:55:12,551 [wine.create_prefix:96]:Creating a win64 prefix in /home/schenkel/Games/star-citizen
DEBUG    2022-04-12 00:55:12,552 [system.execute:56]:Executing /home/schenkel/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wineboot
DEBUG    2022-04-12 00:55:12,552 [system.execute:62]:WINEARCH=win64 WINEPREFIX=/home/schenkel/Games/star-citizen WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/schenkel/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/mono WINE_GECKO_CACHE_DIR=/home/schenkel/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/gecko
INFO     2022-04-12 00:55:28,120 [wine.create_prefix:147]:win64 Prefix created in /home/schenkel/Games/star-citizen
DEBUG    2022-04-12 00:55:28,167 [interpreter._iter_commands:317]:Installer command: {'task': {'app': '--force arial vcrun2019 win10', 'arch': 'win64', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
DEBUG    2022-04-12 00:55:28,196 [wine.use_lutris_runtime:115]:/home/schenkel/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine is provided by Lutris, using runtime
ERROR    2022-04-12 00:55:28,627 [jobs.target:36]:Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7f3335f9e240 (lutris+installer+interpreter+ScriptInterpreter at 0x22d6e20)>>: <class 'AttributeError'> 'NoneType' object has no attribute 'lower'
  File "/usr/lib64/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/lutris/installer/commands.py", line 436, in task
    command = task(**data)
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 346, in winetricks
    return wineexec(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 299, in wineexec
    wine.prelaunch()
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 799, in prelaunch
    self.setup_dlls(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 776, in setup_dlls
    if dll_manager.version.lower() != "manual":
ERROR    2022-04-12 00:55:28,628 [interpreter._iter_commands:302]:Last install command failed, show error
```

### System Information

```shell
[System]
OS:              Slackware 15.0 current
Arch:            x86_64
Kernel:          5.17.2
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            16.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.44.0, 5.17.2, LLVM 13.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.8
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.8
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.8
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gbschenkel** [comment]
I have patched my lutris but It now throws another problem:
```bash
2022-04-14 00:42:25,654: Starting Lutris 0.5.10
2022-04-14 00:42:25,684: No folder at /home/schenkel/.local/share/lutris/runners/retroarch/
2022-04-14 00:42:25,725: Running AMD Mesa driver 21.3.8 on AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.44.0, 5.17.2, LLVM 13.0.1) (0x73bf)
2022-04-14 00:42:25,725: GPU: 1002:73BF 1043:04F2 (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
2022-04-14 00:42:25,837: Startup complete
2022-04-14 00:42:53,522: Download completed
2022-04-14 00:42:53,522: All files available
2022-04-14 00:42:53,523: All files are available, continuing install
2022-04-14 00:42:53,526: Creating a win64 prefix in /home/schenkel/Games/star-citizen
2022-04-14 00:43:14,051: win64 Prefix created in /home/schenkel/Games/star-citizen
2022-04-14 00:43:14,585: Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7f2cabee8640 (lutris+installer+interpreter+ScriptInterpreter at 0x1756880)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/schenkel/.local/share/lutris/runtime/dxvk/dxvk_versions.json'
  File "/usr/lib64/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/lutris/installer/commands.py", line 436, in task
    command = task(**data)
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 346, in winetricks
    return wineexec(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/commands/wine.py", line 299, in wineexec
    wine.prelaunch()
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 800, in prelaunch
    self.setup_dlls(
  File "/usr/lib64/python3.9/site-packages/lutris/runners/wine.py", line 779, in setup_dlls
    dll_manager.enable()
  File "/usr/lib64/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 213, in enable
    if not self.download():
  File "/usr/lib64/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 118, in download
    url = self.get_download_url()
  File "/usr/lib64/python3.9/site-packages/lutris/util/wine/dll_manager.py", line 105, in get_download_url
    with open(self.versions_path, "r", encoding='utf-8') as version_file:
2022-04-14 00:43:14,592: Last install command failed, show error
```
Appears Lutris is not downloading DXVK before trying to running it.

**Comment by gbschenkel** [comment]
Okay, found where the problem resides, on my previous attempts I have only removed the `.local/share/lutris` and `.config/lutris`, I didn't see `.cache/lutris`. I have now removed all 3 directories before trying and it was able to start installing the Star Citizen launcher, and correct me other issues with icons on Sources tab, which don't was loading.

Maybe, just speculation, could be good, after a new lutris version been installed, on the first run, the .cache/lustris directory could been clean, if this doesn't impact anything.

Please put a sticker if you guys read this, since it is closed. Thanks!

**Comment by strycore** [comment]
There is no situation where any of those directories should be removed. We never advertise removing those directories.
There was a faulty situation in your setup but with the data gone, it's no longer possible to find the cause.

**Comment by danieljohnson2** [comment]
It's curious though. That trace-back shows that some WINE components' versions,json file was missing. But if the entire .local/share/lutris directory is missing, it should redownload all of them at startup, right?

Could it be that you removed those directories while Lutris was actually running? That could make it fail in very messy ways.

We could try to harden Lutris against this (redownloading the components if they are found to be missing when needed) but I really wonder if its worth doing.

**Comment by gbschenkel** [comment]
@strycore , yes, I agree is not productive remove all 3 directories, what I mean is if `.cache/lutris` could be cleaned anytime.
@danieljohnson2 Before deleting the other 2 folders (config, local) I have done `kill -9 python` since I got the problem of infinite loading on version 0.5.9.1, but I have upgraded to 0.5.10 before tried run it, got a blank screen on the SC launcher, then when I tried reinstall just the SC Launcher, I start receiving the initial problem of this Issue, I thought was because what I tried to do not worked, then I have removed all installation of SC, when the problem still afflicting me, I have removed, as the last resort, the config and local directories of lutris, missing the cache.

**Comment by strycore** [comment]
> what I mean is if .cache/lutris could be cleaned anytime.

By removing this folder, you'll lose: all images for all services, all authentication tokens for every service, your logs and a few other files. The only file in ~/.cache/lutris that would affect the issue youre running into is updates.json which records the last time updates were made to lutris. 
If an update fails, it's not supposed to write to updates.json, it should only do so after a successful update. 

> Are the components validated with md5sum or sha256sum for check if it is corrected downloaded?

Not yet, but it's been planned for a while. It's now pretty high in the priorities of the project.

**Comment by strycore** [comment]
> We could try to harden Lutris against this (redownloading the components if they are found to be missing when needed) but I really wonder if its worth doing.

The goal of the updates.json file is to not try to download an update for every component every time lutris starts. This can be quite time consuming for medias so we only check at most once every 24h. For runtime components, it's 12h and for dlls, it's 6h. But those delays are only applied if the update was run at least once successfully. Maybe in this case, the DLL updater is silently failing and still registering as a valid update.

**Comment by danieljohnson2** [comment]
No, no, I meant to re-download the component if it is found to be missing when it is wanted, not on each startup or on any timer.

But I'm not sold on this idea; I can't understand what happened to @gbschenkel and if re-downloading would have helped. And maybe this was just a symptom of his troubleshooting anyway, and who knows what the original problem was.

**Comment by RamenRanger** [comment]
I hit this issue myself just now and it affected both games that I currently have installed on Lutris (Warframe and ESO).  I have no idea what caused the issue in the first place.  I didn't upgrade anything, but I did travel to a different location and stopped using my external monitors and started using my laptop's built-in screen.

I hacked up my wine.py and got it to work (it allowed me to play the game).  Afterwards, I discovered the PR above and it did not work for me.  I got the following errors in dialog box:

[Errno2] No such file or directory: '/home/user/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json

Below is my fix that is only slightly different from the PR above.  Basically, I just bail on the setup_dlls() call entirely if there's no version.  I've only spent about half an hour with the wine code.  I have no idea about the implications of this hacky workaround.  I don't know why my workaround allowed me to play the game and the code in the PR didn't.  I don't believe that it allowed me to download anything that was missing because if I remove my workaround then the game fails to launch in the same way as before.

```
    def setup_dlls(self, manager_class, enable, version):
        """Enable or disable DLLs"""
        dll_manager = manager_class(
            self.prefix_path,
            arch=self.wine_arch,
            version=version,
        )

        if dll_manager.version is None:
            return

        # manual version only sets the dlls to native
        if dll_manager.version.lower() != "manual":
            if enable:
                dll_manager.enable()
            else:
                dll_manager.disable()

        if enable:
            for dll in dll_manager.managed_dlls:
                # We have to make sure that the dll exists before setting it to native
                if dll_manager.dll_exists(dll):
                    self.dll_overrides[dll] = "n"
```

Hope that this is helpful.

**Comment by danieljohnson2** [comment]
Interesting. Apparently this condition is not as unique to @gbschenkel as I thought.

I think you could also address this by turning off the component (DXVK for @gbschenkel  or dgvoodoo2 for @RamenRanger) in the configuration.

But I'll take another look at this. Why isn't Lutris downloading that versions .json file? You can only get away without it because you don't need the offending component.

**Comment by danieljohnson2** [comment]
OK, I've dug into this and I think I found the underlying bug. The auto-download code for this has a timer on it so it runs no more than once every 6 hours. But it's bugged; if the time since the last update is more than a day, it stops working. You'll never get another download of that component.

You can work around this by deleting your ~/.cache/lutris/updates.json file. But I'll PR a real fix.

**Comment by danieljohnson2** [comment]
OK, PR is ready.

Could you try the fix? It's in the branch [component_download](https://github.com/danieljohnson2/lutris/tree/dj/component_download)

If I'm right, running this will download the missing file on startup, and you should not get the missing file error anymore.

**Comment by RamenRanger** [comment]
Unfortunately, I'm no longer able to reproduce the problem.  It must have something to do with delta.seconds and the fact that I went to sleep for 8 hours.

It seems that my dgvoodoo2Manager object now has a version of v2.64 where it previously had a version of NoneType.

I can confirm that the fix doesn't break my ability to run the game.

**Comment by danieljohnson2** [comment]
That fits my expectation. The bug triggers if you start Lutris in a 6 hour window during each day; miss that window and it will download the missing components. Sleeping for 8 hours and then starting Lutris would very do this.

This is why not everybody is hitting this bug - you only have to 'miss' the bug window once and then you're fine. But it could happen again the next time Lutris adds a new component.

**Comment by RamenRanger** [comment]
Sounds good.  After reviewing and properly understanding your previous comments, this makes perfect sense.

Not sure that it's important at this point, but I did try disabling DXVK (based on comments in other forums) prior to implementing my workaround.  That did not resolve the issue for me.  I was still getting the NoneType error.

**Comment by danieljohnson2** [comment]
You needed to disable dgvoodoo2, that was what was missing for you, according to the error you reported.
