### ISSUE TITLE
Edit popup for "Enable fsync" option

### ISSUE THREAD

**Issue by UsernameRandomlyGenerated** [lutris/lutris#4224]
Currently after hovering on the popup of "enable fsync" option it shows message saying "Requires a custom kernel with the fsync patchset". Fsync is in Linux mainline since 5.16. I believe that message should be change to reflect that.

**Comment by strycore** [comment]
Fixed in https://github.com/lutris/lutris/commit/c49dc6e85e65e3d602a0f8dc16588c10622fe234
