### ISSUE TITLE
How do I reinstall Ubisoft Connect/Uplay if I borked the initial installation?

### ISSUE THREAD

**Issue by ienzo** [lutris/lutris#4233]
I deleted the folder `ubisoft-connect`  and I cannot reinstall it. I'm currently on version `0.5.10.1`.

**Comment by strycore** [comment]
Is it uninstalled as well in Lutris? You should be able to reinstall it if it is

**Comment by ienzo** [comment]
No, I keep getting the error `The file [...]/UbisoftConnect.exe could not be found`

**Comment by strycore** [comment]
That's because it's still installed. Right click on Ubisoft Connect and select "Remove"

**Comment by ienzo** [comment]
I can't seem to right click it at all. That option doesn't seem to be available when I try right clicking the ubisoft connect button under sources.

**Comment by strycore** [comment]
You also have ubisoft connect as a lutris game, type ubisoft in the search field with "Games" selected in the sidebar

**Comment by ienzo** [comment]
Thanks! You can close this issue now, I was able to remove it and I'm reinstalling it now.
