### ISSUE TITLE
I can't install the same game from two different sources

### ISSUE THREAD

**Issue by ienzo** [lutris/lutris#4234]
I've installed Assassin's Creed 2 via Steam. For whatever reason, it won't work. I want to install it again through Ubisoft Connect via Lutris. Assassin's Creed 2 is not listed as a game that I can install via Lutris on the Ubisoft Connect sources page. I suspect it could be because I've already installed it through Steam. However, I'm unwilling to uninstall the Steam installation on the off-chance that I can find a solution for it. Is there any way to install it again through Ubisoft Connect? 

I'm on version 0.5.10.1.

**Comment by strycore** [comment]
Do you have the Ubisoft Connect client installed in Lutris and are you logged in into it?
The Ubisoft API doesn't return all games, most games are fetched from the client's files but you need to be logged in for them to be available to Lutris.
This shouldn't have anything to do with the game being installed in Steam.

**Comment by ienzo** [comment]
I have the Ubisoft client installed. I confirm I am logged into it. I ran the Ubisoft client and confirmed that Assassin's Creed 2 is in my library. Curiously, I have an anno game on my Ubi library that isn't showing up on the Lutris client either. Maybe this bug is wholly unrelated to Steam installation?

**Comment by strycore** [comment]
The issue is unrelated to Steam yes. I've made a guide to explain some issues happening with ubisoft connect. https://youtu.be/Xt4JI1nR3xg

**Comment by ienzo** [comment]
Okay I looked over you video. I cannot replicate your solution. 

- I don't have a folder called `uplay` in my `Games` folder but I do have a folder called `ubisoft-connect` and I am running under the assumption this is the same. 

1. Disconnected Ubisoft connect
2. Reconnected Ubisoft connect
3. Disconnected again
4. Renamed `ubisoft-connect` folder
5. reconnected
6. disconnected
7. Renamed `ubisoft-connect` back
8. reconnected, the missing games are still missing

I did this a few times. By the way, I'm on version 0.5.10.1.

**Comment by strycore** [comment]
Yes, it's called uplay because it's from an old install but it should be called ubisoft-connect now.
Maybe if you open the client and install assassin's creed 2 then refresh the service in lutris, it should show up.
I never had any problem with AC2 showing but for Ubisoft games it depends a lot on how you got the game in the first place. Most of my games are from Humble Bundle keys. Those could be be handled differently than Ubisoft+ games or direct store purchases.

**Comment by ienzo** [comment]
Okay, I could open the client and install AC2, but it's asking me to install Steam for Windows when I do (because I got the game on Steam). I've successfully installed AC: Unity on Lutris before and it skipped the installing Steam for Windows part. I was hoping that by using Lutris to download it, I could skip installing Steam for Windows. 

1. Open Ubisoft Connect via the "play" button on Lutris.
2. Pressed AC:2 to install
3. Steam for Windows installer launches. 

Is there any way to skip installing Steam for Windows?

**Comment by strycore** [comment]
Ok, I understand better, it's a Steam game.
In that case I would really be better to just play the game on Steam. You could install Steam for Windows, but the client is really buggy on Wine.
That's also why it doesn't show up in your Ubi library, it's a Steam game.

**Comment by ienzo** [comment]
The vast majority of my Ubisoft games are from Steam. Most of the Steam games show up. I guess this goes back to my first original point, that I can't install AC2 from Steam and Ubisoft Connect via Lutris at the same time. I tried installing Steam for Windows on Wine via Ubisoft Connect, but it's buggy to the point of being unusable. I'll try it though.

**Comment by strycore** [comment]
No, you can uninstall the game from Steam completely and you'll still have the same issue.
These are Steam games meant to be played on Steam and not on Ubisoft Connect. 
You have nothing to gain by running the game in Steam for Windows except additional bugs.

**Comment by ienzo** [comment]
Hmm alright. What can I do about it then?

**Comment by strycore** [comment]
Play the games on Steam?

**Comment by ienzo** [comment]
No, it doesn't work on Proton/Steamplay, and I can't find any reference online to any other person who had this bug. 

Update, I've installed Steam for Windows, downloaded AC2, and frustratingly got the same bug with the Proton/Steamplay version. I guess I'm not really interested in continuing to report on the bug where games don't show up since the result is the same for me. 

Thanks for your help though!

**Comment by strycore** [comment]
Getting AC2 running would be a different issue but you should be able to. 
I haven't tried the Steam version but the Ubisoft version has always worked fine on my end. ProtonDB mentions some CD keys issues but they seem to be resolved now.

If the game still fails to run, try asking for support in our Discord server.

**Comment by ienzo** [comment]
Thanks! I think I'll try that.
