### ISSUE TITLE
Lutris arch community package out of date

### ISSUE THREAD

**Issue by prorounak2005** [lutris/lutris#4239]
### Bug description

Lutris package is flagged as out of date in arch community repository. 
https://archlinux.org/packages/community/any/lutris/
http://0x0.st/oTyT.png

### How to Reproduce

NA

### Expected behavior

NA

### Log output

```shell
NA
```

### System Information

```shell
NA
```

### Media (optional)

NA

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by pizza4554** [comment]
Just checked today and this appears to have been resolved. The "last updated" field shows it was updated yesterday.

**Comment by dataprolet** [comment]
Also this is an issue the package maintainers need to address, not the Lutris developers.

**Comment by strycore** [comment]
The package is now up to date.
Please do apply to become an Arch maintainer if you have the skills, we need more of them.
