### ISSUE TITLE
[Feature Request] Support new gnome console

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [lutris/lutris#4242]
not sure if this is possible or not (due to the env variables), but it would be nice if lutris could support gnome console.

**Comment by strycore** [comment]
is this a new terminal emulator? if so we only need the name of the executable so we can add it to the list of known terminal emulators.

**Comment by Etaash-mathamsetty** [comment]
> is this a new terminal emulator? if so we only need the name of the executable so we can add it to the list of known terminal emulators.

`/usr/bin/kgx`
kinda weird name, but yeah

**Comment by strycore** [comment]
>  kinda weird name, but yeah

Since we don't have a name to executable map, it will show up as "kgx" but it is now supported.
