### ISSUE TITLE
No lutris icon when open managerunner/installer

### ISSUE THREAD

**Issue by scottviger** [lutris/lutris#425]
I know the title isn't great but the picture will explain it all!
![final](https://cloud.githubusercontent.com/assets/22118081/19864790/2df2ead4-9f70-11e6-984d-23dfedf20925.png)

1 is the main window
2 is the installer windows

The icon of 2 doesn't seem to be set...
The problem can happen in the installer and in the manage runner.

I'm on Xubuntu 16.10 (XFCE4)

Don't stop the great work!

**Comment by strycore** [comment]
This is now fixed!
