### ISSUE TITLE
Hangs when running dual gpu setup with iGPU as primary

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [lutris/lutris#4264]
### Bug description

Attempting to run Lutris, either through Pop OS's package or the tarball, results in the command hanging forever. Upon sending a Ctrl+C to kill it, the Python stack trace is printed as follows:

```
^CTraceback (most recent call last):
  File "/home/{redacted}/Downloads/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/{redacted}/Downloads/lutris/lutris/gui/application.py", line 39, in <module>
    from lutris.game import Game, export_game, import_game
  File "/home/{redacted}/Downloads/lutris/lutris/game.py", line 17, in <module>
    from lutris.config import LutrisConfig
  File "/home/{redacted}/Downloads/lutris/lutris/config.py", line 7, in <module>
    from lutris import settings, sysoptions
  File "/home/{redacted}/Downloads/lutris/lutris/sysoptions.py", line 298, in <module>
    "default": get_vk_icd_choices()[0][1],
  File "/home/{redacted}/Downloads/lutris/lutris/sysoptions.py", line 116, in get_vk_icd_choices
    glxvendor = glxvendorget.communicate()[0].decode("utf-8")
  File "/usr/lib/python3.10/subprocess.py", line 1136, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt

```

After looking through the source I discovered that `DRI_PRIME` is set to 1 when multiple GPUs are detected, however my system uses a dedicated Geforce 210 only for secondary display output, and uses the iGPU for the workhorse. Setting DRI_PRIME=1 causes the glxinfo command to hang, not sure if this is a bug in that as well. Forcing `lutris.util.display.USE_DRI_PRIME = 0` via modifying the source code fixes the issue.

### How to Reproduce

1. Set iGPU as primary via UEFI and add secondary ancient dGPU (Geforce 210)
2. Install lutris, either via apt or tarball
3. Run lutris, observe hang

### Expected behavior

More intelligently determine whether `DRI_PRIME` should be set based on whether iGPU is primary or not, unsure if even possible

### Log output

```shell
N/A, hangs and does not output
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          5.17.5-76051705-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600G with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.1 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD RENOIR (LLVM 13.0.1, DRM 3.44, 5.17.5-76051705-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.1
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.1
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.1
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
This should be fixed in the current release
