### ISSUE TITLE
Portrait banners are not displayed

### ISSUE THREAD

**Issue by matthiakl** [lutris/lutris#4265]
### Bug description

When increasing the banner size, at one point they switch from landscape to portrait mode, but no image is shown anymore. Additionally, spinner shows up with no apparent effect when it disappears.

### How to Reproduce

1. Select a banner for a game
2. Increase the image size step by step

### Expected behavior

In the game settings there should be an additional image selection for portrait mode, which is then displayed with larger image sizes.

### Log output

```shell
None
```

### System Information

```shell
[System]
OS:              Arch Linux  
Arch:            x86_64
Kernel:          5.4.191-1-lts54
Desktop:         X-Cinnamon
Display Server:  x11
```

### Media (optional)

Before:
![Bildschirmfoto vom 2022-05-09 20-23-43](https://user-images.githubusercontent.com/23122583/167485237-9f85711e-1646-4bec-896a-fafd18c1aeb7.png)
After:
![Bildschirmfoto vom 2022-05-09 20-23-56](https://user-images.githubusercontent.com/23122583/167485251-dfbbeb50-8b75-44e3-a323-96401f7b9bd4.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by telanus** [comment]
methinks minecraft doesn't have a coverart banner. Unfortunately the current source that lutris uses to get coverart, isn't a great source for it, as it lacks coverart for a majority of games, and of the coverart they do have a small percentage of them i of poor quality. 

Alternate sources was put foward to suppliment the source that Lutris use, but that idea was shot down, so that leaves Lutris without a good source of coverart.

So unless one create one's own art or use a site like https://www.steamgriddb.com (which was suggsted, and then rejected), with a caveat that they need modifications to work with Lutris, one will have to live with no coverart

**Comment by matthiakl** [comment]
> So unless one create one's own art or use a site like https://www.steamgriddb.com/

I'm happy with adding a coverart manually, but for this a selection dialog should be present somewhere in the game settings.

**Comment by telanus** [comment]
> > So unless one create one's own art or use a site like https://www.steamgriddb.com/
> 
> I'm happy with adding a coverart manually, but for this a selection dialog should be present somewhere in the game settings.

it was suggested, but ..................

**Comment by SandyRodgers-2017** [comment]
> > So unless one create one's own art or use a site like https://www.steamgriddb.com/
> 
> I'm happy with adding a coverart manually, but for this a selection dialog should be present somewhere in the game settings.

While you can't do it from gui you can do it  from the manually using the folder structure.

**Comment by SandyRodgers-2017** [comment]
adf

**Comment by SandyRodgers-2017** [comment]
adsf
af
af
adfadsf
adf

**Comment by vedkothavade** [comment]
Any chance of revisiting adding a UI for portrait mode?

**Comment by danieljohnson2** [comment]
If you mean adding custom cover art, the 0.5.12 beta has a UI for that in the configuration dialog.

I'll close this item; I think the requirement is covered by that.
