### ISSUE TITLE
Failed to check drivers version with NVIDIA open source GPU drivers

### ISSUE THREAD

**Issue by YidaozhanYa** [lutris/lutris#4270]
### Bug description

Lutris uses the method of splitting the string to check the driver version, but the "version" file output of the open source driver and the proprietary driver are different, so the drivers version cannot be checked, resulting in Lutris unable to start.

It is recommended to use different string splits for open source and proprietary drivers.

### How to Reproduce

Just start lutris simply

### Expected behavior

Lutris will start normally

### Log output

```shell
INFO     2022-05-12 12:20:02,769 [startup.init_lutris:174]:Starting Lutris 0.5.10.1
WARNING  2022-05-12 12:20:02,798 [libretro.get_libretro_cores:24]:No folder at /home/yidaozhan/.local/share/lutris/runners/retroarch/
DEBUG    2022-05-12 12:20:02,806 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-05-12 12:20:03,076 [startup.check_driver:58]:Using NVIDIA drivers for for Open
INFO     2022-05-12 12:20:03,076 [startup.check_driver:62]:GPU: NVIDIA GeForce GTX 1650 Ti
INFO     2022-05-12 12:20:03,076 [startup.check_driver:78]:GPU: 10DE:1F95 103C:8742 (nvidia drivers)
INFO     2022-05-12 12:20:03,077 [startup.check_driver:78]:GPU: 8086:9BC4 103C:8742 (i915 drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 409, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 157, in run_all_checks
    check_driver()
  File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 82, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
INFO     2022-05-12 12:20:03,077 [application.do_shutdown:885]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.5-xanmod1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.4 GB
Swap:            15.6 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.3
Vulkan:          Supported
```
<details>
  <summary><strong>This information was obtained after modifying the /usr/lib/python3.10/site-packages/lutris/util/graphics/drivers.py file so the NVIDIA graphics card is not shown.</strong></summary>
<img src="https://user-images.githubusercontent.com/73830635/167992159-6b936ea0-69c5-4b05-9118-06d7e3126081.png">
</details>

### Media (optional)

![图片](https://user-images.githubusercontent.com/73830635/167991552-c86a50dd-6d74-4a5b-8125-03deb99e64c5.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by YidaozhanYa** [comment]
This is the content of the version file:
```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  515.43.04  Release Build  (archlinux-builder@archlinux)  
GCC version:  gcc 版本 11.2.0 (GCC)
```

**Comment by YidaozhanYa** [comment]
Please merge https://github.com/lutris/lutris/pull/4271 .

**Comment by strycore** [comment]
Patch merged, thanks for providing it.

**Comment by benaryorg** [comment]
Gentoo lately updated the *nvidia-drivers* package to allow usage of the open source drivers, those drivers are hence slowly entering rolling release territory, however Lutris doesn't seem to have had a release since.
Any chance of getting a release out anytime soon?
