### ISSUE TITLE
Allow more tolerant installer format

### ISSUE THREAD

**Issue by ChargedByte** [lutris/lutris#4276]
### Bug description

When attempting to install from a local yml file, the file selection dialogue is blank.

Possibly similar to https://github.com/lutris/lutris/issues/3290

### How to Reproduce

Steps to reproduce the behaviour:
1. Download yml file from https://pastebin.com/a0bP0f9e
2. Run `flatpak run net.lutris.Lutris -d -i /path/to/game.yml`
3. Select install from the first dialogue
4. the Second dialogue is empty

### Expected behavior

After selecting the install option, expected to see a dialogue for selecting the installer

### Log output

```shell
Gtk-Message: 16:05:45.484: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:05:45.484: Failed to load module "pk-gtk-module"
INFO     2022-05-13 16:05:45,486 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-13 16:05:45,511 [libretro.get_libretro_cores:24]:No folder at /home/chargedbyte/.var/app/net.lutris.Lutris/data/lutris/runners/retroarch/
INFO     2022-05-13 16:05:45,540 [startup.check_driver:57]:Using NVIDIA drivers 510.68.02 for x86_64
INFO     2022-05-13 16:05:45,540 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1070
INFO     2022-05-13 16:05:45,541 [startup.check_driver:77]:GPU: 10DE:1B81 1043:85A0 (nvidia drivers)
INFO     2022-05-13 16:05:45,603 [startup.update_runtime:213]:Startup complete
DEBUG    2022-05-13 16:05:45,680 [lutriswindow.update_store:437]:Showing 1 games
DEBUG    2022-05-13 16:05:45,741 [__init__.read_script:14]:Loading script(s) from /home/chargedbyte/Projects/Lutris/test.yml
DEBUG    2022-05-13 16:05:45,751 [application.show_window:332]:Showing window InstallerWindowgame
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/lutris/gui/installerwindow.py", line 157, in on_installer_selected
    self.interpreter = interpreter.ScriptInterpreter(script, self)
  File "/app/lib/python3.9/site-packages/lutris/installer/interpreter.py", line 50, in __init__
    self.installer = LutrisInstaller(installer, self, service=self.service, appid=_appid)
  File "/app/lib/python3.9/site-packages/lutris/installer/installer.py", line 38, in __init__
    for file_desc in self.script.get("files", [])
AttributeError: 'NoneType' object has no attribute 'get'
DEBUG    2022-05-13 16:06:03,537 [application.on_app_window_destroyed:350]:Removed window InstallerWindowgame
INFO     2022-05-13 16:06:05,581 [application.do_shutdown:885]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              GNOME 42 Flatpak runtime
Arch:            x86_64
Kernel:          5.17.6-300.fc36.x86_64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.68.02
OpenGL Core:     4.6.0 NVIDIA 510.68.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.68.02
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/8603727/168290490-cca521ea-f4e4-4156-9a67-a5c861066bbd.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
This is because it's not a valid Lutris script. You should have your metadata at the top and have the script content indented under a `script` section.
Note that I'm going to change this behavior and make the script section optional, allowing for sections like `game`, `installer` and `system` to be placed at the root level

**Comment by ChargedByte** [comment]
Crap, that's my bad. I don't know how I missed that there was a script section.

**Comment by strycore** [comment]
Let's not.
