### ISSUE TITLE
shortcuts.vdf causes an error in update_all_artwork

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4279]
### Bug description

I found another bug that has to do with shortcuts.vdf. Was adding a few games, and restarted Lutris. 

### How to Reproduce

Don't have shortcuts.vdf and it'll come up with this error

### Expected behavior

to start cleanly

### Log output

```shell
ERROR    2022-05-12 06:41:37,946 [jobs.target:36]:Error while completing task <bound method LutrisInitDialog.initialize of <dialogs.LutrisInitDialog object at 0x7fcd983cb500 (lutris+gui+dialogs+LutrisInitDialog at 0x1770340)>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '~/.steam/debian-installation/userdata/69473804/config/shortcuts.vdf'
  File "~/src/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "~/src/lutris/lutris/gui/dialogs/init.py", line 197, in initialize
    init_lutris()
  File "~/src/lutris/lutris/startup.py", line 213, in update_runtime
    update_all_artwork()
  File "~s/src/lutris/lutris/util/steam/shortcut.py", line 151, in update_all_artwork
    with open(shortcut_path, "rb") as shortcut_file:
```

### System Information

```shell
irrelevant
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Fixed by: https://github.com/lutris/lutris/pull/4281
