### ISSUE TITLE
dgvoodoo2 stopped working with latest Nvidia update (515.xx)

### ISSUE THREAD

**Issue by zewm** [lutris/lutris#4284]
### Bug description

When dgvoodoo2 is enabled, the game runs without a game window. Lutris says it's running and gives no error, and leaves it running until you manually stop it. If you disable dgvoodoo2, the game runs fine. 

This just started happening after I updated to the latest nvidia drivers. 510 -> 515.

I tried deleting the dgvoodoo folder and letting lutris try to download it again but it did nothing and gave an error that it couldn't find the folder.

Using Arch with Linux-Zen kernel (all latest) on KDE-Plasma Xorg-X11

### How to Reproduce

1. enable dgvoodoo2
2. start game
3. stop game (manually)
4. disable dgvoodoo2
5. start game

### Expected behavior

game window renders

### Log output

```shell
[zewm@tardis ~]$ lutris -d
INFO     2022-05-16 00:20:18,771 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-16 00:20:18,791 [libretro.get_libretro_cores:24]:No folder at /home/zewm/.local/share/lutris/runners/retroarch/
DEBUG    2022-05-16 00:20:18,797 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-05-16 00:20:18,820 [startup.check_driver:57]:Using NVIDIA drivers 515.43.04 for x86_64
INFO     2022-05-16 00:20:18,820 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3090
INFO     2022-05-16 00:20:18,820 [startup.check_driver:77]:GPU: 10DE:2204 10DE:147D (nvidia drivers)
INFO     2022-05-16 00:20:18,847 [startup.update_runtime:213]:Startup complete
DEBUG    2022-05-16 00:20:18,961 [lutriswindow.update_store:437]:Showing 3 games
DEBUG    2022-05-16 00:20:20,569 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/zewm/Games/AnarchyOnline/drive_c/Funcom/Anarchy Online"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:LD_LIBRARY_PATH="/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib:/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64:/usr/lib:/usr/lib32:/usr/lib/libfakeroot:/usr/lib64:/home/zewm/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/zewm/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/zewm/.local/share/lutris/runtime/steam/i386/lib:/home/zewm/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/zewm/.local/share/lutris/runtime/steam/i386/usr/lib:/home/zewm/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/zewm/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/zewm/.local/share/lutris/runtime/steam/amd64/lib:/home/zewm/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/zewm/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINEDEBUG="-all"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINEARCH="win64"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINE="/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINE_MONO_CACHE_DIR="/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/mono"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/gecko"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64/gstreamer-1.0/:/home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib/gstreamer-1.0/"
DEBUG    2022-05-16 00:20:20,575 [command.start:141]:WINEPREFIX="/home/zewm/Games/AnarchyOnline"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:WINEESYNC="1"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:WINEFSYNC="1"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dimm,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,ddraw,dxgi,glide,glide2x,glide3x,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:game_name="Anarchy Online"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/lib/python3.10/site-packages"
DEBUG    2022-05-16 00:20:20,576 [command.start:141]:LUTRIS_GAME_UUID="d664e743-44ee-485e-8116-65b0e9494e8d"
lutris-wrapper: Anarchy Online
Started initial process 17250 from gamemoderun /home/zewm/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine /home/zewm/Games/AnarchyOnline/drive_c/Funcom/Anarchy Online/AnarchyOnline.exe
Start monitoring process.
gamemodeauto: 
fsync: up and running.
Initial process has exited (return code: 65280)
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.7-zen1-1-zen
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
Physical cores:  10
Logical cores:   20

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.43.04
OpenGL Core:     4.6.0 NVIDIA 515.43.04
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.43.04
Vulkan:          Supported
```

### Media (optional)

https://user-images.githubusercontent.com/5915302/168520491-c3b3705b-fa03-4030-b617-7528f6c5cdc7.mp4

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by natiels** [comment]
I have experienced the same thing with the 515 driver.
Ubuntu 22.04 on kernel 5.16.19-76051619-generic with a laptop 3060

**Comment by odziom91** [comment]
I'm not confirm that dgVooDoo doesn't work at all with NVidia 515 - I use it on few games without problems.
Sometimes it should be implemented manually, sometimes it works out of the box (with Lutris checkbox) - there is no rule, because some games requires different files to run.
![lutris_dgVooDoo](https://user-images.githubusercontent.com/19655744/172812996-dc4c9dc8-c20e-44b3-a380-baca278d70ca.png)
Please check details about game from websites like here: https://www.pcgamingwiki.com/wiki/Anarchy_Online
I see that this game use DirectX9 - as far as I remember by default dgVooDoo in Lutris is configured for DirectX 7/8 games - but it will be good to confirm with config, etc..
I use GTX 1060 6GB on Wayland (Arch Linux - Zen Kernel with KDE).
![nvidia](https://user-images.githubusercontent.com/19655744/172813694-40779b99-279b-47a8-994c-365642117017.png)
Here is a screen from DirectX 7 game translated to DirectX 11 (DXVK).
![dgVooDoo](https://user-images.githubusercontent.com/19655744/172815206-eb1577e8-6b49-46d5-ba78-21945c695173.png)

**Comment by sfjuocekr** [comment]
> I have experienced the same thing with the 515 driver. Ubuntu 22.04 on kernel 5.16.19-76051619-generic with a laptop 3060

Were you able to run any games with the 515? I can't seem to get anything to run right now, the strange thing is that steam's proton seems to work fine for some (64bit) games so I assume the lack of i386 libraries is the cause here.

Im on Jammy and switch back to 510 if I need to...

**Comment by sfjuocekr** [comment]
You need the 32bit libraries, download the NVIDIA-Linux-x86_64-515.48.07.run file and run it with the -x parameter to extract the files.

There is a directory called 32 inside there, you need to copy these files to /usr/lib/i386-linux-gnu and then run ldconfig.

If this did not work goto /usr/lib/i386-linux-gnu and run:
`
ln -s libcuda.so.515.48.07 libcuda.so
ln -s libEGL_nvidia.so.515.48.07 libEGL_nvidia.so
ln -s libEGL.so.1.1.0 libEGL.so
ln -s libGLdispatch.so.0 libGLdispatch.so
ln -s libGLESv1_CM_nvidia.so.515.48.07 libGLESv1_CM_nvidia.so
ln -s libGLESv1_CM.so.1.2.0 libGLESv1_CM.so
ln -s libGLESv2_nvidia.so.515.48.07 libGLESv2_nvidia.so
ln -s libGLESv2.so.2.1.0 libGLESv2.so
ln -s libGL.so.1.7.0 libGL.so
ln -s libGLX_nvidia.so.515.48.07 libGLX_nvidia.so
ln -s libGLX.so.0 libGLX.so
ln -s libnvcuvid.so.515.48.07 libnvcuvid.so
ln -s libnvidia-allocator.so.515.48.07 libnvidia-allocator.so
ln -s libnvidia-compiler.so.515.48.07 libnvidia-compiler.so
ln -s libnvidia-eglcore.so.515.48.07 libnvidia-eglcore.so
ln -s libnvidia-encode.so.515.48.07 libnvidia-encode.so
ln -s libnvidia-fbc.so.515.48.07 libnvidia-fbc.so
ln -s libnvidia-glcore.so.515.48.07 libnvidia-glcore.so
ln -s libnvidia-glsi.so.515.48.07 libnvidia-glsi.so
ln -s libnvidia-glvkspirv.so.515.48.07 libnvidia-glvkspirv.so
ln -s libnvidia-ml.so.515.48.07 libnvidia-ml.so
ln -s libnvidia-nvvm.so.515.48.07 libnvidia-nvvm.so
ln -s libnvidia-opencl.so.515.48.07 libnvidia-opencl.so
ln -s libnvidia-opticalflow.so.515.48.07 libnvidia-opticalflow.so
ln -s libnvidia-ptxjitcompiler.so.515.48.07 libnvidia-ptxjitcompiler.so
ln -s libnvidia-tls.so.515.48.07 libnvidia-tls.so
ln -s libOpenCL.so.1.0.0 libOpenCL.so
ln -s libOpenGL.so.0 libOpenGL.so
ln -s libvdpau_nvidia.so.515.48.07 libvdpau_nvidia.so
`
