### ISSUE TITLE
Testing new version

### ISSUE THREAD

**Issue by t0msk** [lutris/lutris#4291]
Hello,

this is not hate, I love Lutris but I would like to ask you if you have some testing before releasing new versions, because there are some breaking changes like here: https://github.com/lutris/lutris/milestone/51 which should have top priority and fixed asap, because installing games and running them on discrete GPU are the most important features of Lutris, I mean lot of things doesn't work work with new release, for example use only iGPU and nvidia prime doesn't work anymore.

Thank you

**Comment by danieljohnson2** [comment]
I don't think Lutris's testing department is really earning its keep! We should dock their pay. We could save a whopping 0% of the Lutris budget!

Jokes aside, it's just folks doing the best they can. @strycore puts out betas, and people can test and report issues if they wish to. Contributors can then try to fix the bugs.

If you'd like it to be better, you can't really make other people step up. What you *can* do is chip in yourself.

If that appeals... well, could you go and test my PR #4228? I had hoped that it would fix your issue #4255.

If it *works* for you, I'll advocate its merger for 0.5.10.2, but at this point I can only hope it helps you,

**Comment by strycore** [comment]
No one on the development team has a laptop with hybrid graphics
