### ISSUE TITLE
[steam] Game installed but not shown

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#430]
Saw this, this morning, if you get a new game on steam, and install it, then launch Lutris, without adding it to your library via the website, lutris will state, in the terminal: 

`[steam]:Setting You Have to Win the Game as installed`

but won't show in the front-end, the first time you run lutris, only shows up on the second launch.

**Comment by RobLoach** [comment]
Confirmed...

1. Quit Lutris
1. Make sure https://lutris.net/games/you-have-to-win-the-game/ is part of your lutris.net library
1. Install http://store.steampowered.com/app/286100 through Steam
1. Run Lutris
1. See `Setting You Have to Win the Game as installed` appear in the console
1. You Have To Win The Game is not in the Lutris window
1. Quit Lutris
1. Re-run it
1. See the game now in the Lutris window

**Comment by daniel-j** [comment]
Fixed in #493

**Comment by telanus** [comment]
one problem I've seen, when you remove a game IE QMC2 (mame frontend) and restart Lutris it will be readded to Lutris,

**Comment by daniel-j** [comment]
Right now there is a game/executable blacklist in desktopapp.py. I want this to be configurable in the future, but for now you can submit a PR that adds MAME to the blacklist :)
