### ISSUE TITLE
pango_layout_check_lines: assertion failed

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4300]
Was playing around with MAME's software lists. Added a few. Duplicated one, as to copy the arguments needed to run the game, and right-clicked on the duplicate, to be able to configure this new entry, when Lutris crashed.

It left this on the terminal:

```
Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Bail out! Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
```

not sure why it does that

**Comment by strycore** [comment]
not sure if this can be reproduced.
