### ISSUE TITLE
mongohud: OK, gamescope: OK, mangoHud + gamescope

### ISSUE THREAD

**Issue by potens1** [lutris/lutris#4305]
Hi,

I'm doing some experiments to use gamescope (to be able to use FSR scaling) and, while I'm able to use gamescope alone in lutris, or mangohud alone in lutris, the combination of both just do... nothing.

The game stop before intializing, (sometimes) nothing in the logs, sometimes a beautifull coredump from gamescope. I've been told (https://github.com/Plagman/gamescope/issues/512#issuecomment-1144864291) `mangohud` should not be used with `gamescope`, but `mangoapp` should be

I saw on the discord server I'm not the only one to have that, maybe grayout FPS counter when gamescope is activated ?

**Comment by trinukso** [comment]
https://flathub.org/apps/details/com.valvesoftware.Steam

**Comment by strycore** [comment]
both mangohud + gamescope can be activated at the same time now.
