### ISSUE TITLE
[Feature Request] MAME adding extra slots for Software

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4308]
This would help with systems that MAME emulate where you need more than one option to boot a system IE Mac II where you boot into MacOS 6.0.8 on a harddisk, and load a floppy especially for games where there floppy isn't bootable.

So you'll end up with two Rom file and Storage type, one for the first diks/rom and another for the second disk/rom

**Comment by strycore** [comment]
This will be available in next release
