### ISSUE TITLE
PS5 Dualsense Controller do not work using Lutris

### ISSUE THREAD

**Issue by rscm** [lutris/lutris#4309]
Hi

I have a PS5 Dualsense Controller that gets detected by linux and the module is loaded

```
❯ lsmod | grep playstation
hid_playstation        20480  0
led_class_multicolor    16384  1 hid_playstation
ff_memless             20480  1 hid_playstation
```

```
❯ bluetoothctl info
Device D0:BC:C1:B9:1C:15 (public)
	Name: Wireless Controller
	Alias: Wireless Controller
	Class: 0x00002508
	Icon: input-gaming
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	WakeAllowed: yes
	LegacyPairing: no
	UUID: Human Interface Device... (00001124-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v054Cp0CE6d0100
```

It works on Steam, but in Lutris does not work. It doesn't get detected

If I open the Wine Control Panel in Lutris I can see it gets detected and is enabled and available

![Captura desde 2022-06-05 13-27-54](https://user-images.githubusercontent.com/6588120/172062715-f06c9cf8-322c-45d6-a120-8d9bb5862f5d.png)
![Captura desde 2022-06-05 13-27-39](https://user-images.githubusercontent.com/6588120/172062716-1b29bc15-5ce8-48ca-88b3-201087477a94.png)

---

```
❯ flatpak list | grep lutris
Lutris	net.lutris.Lutris	0.5.10.1	beta	flathub-beta	user
```

```
❯ inxi -zSb
System:
  Kernel: 5.17.11-300.fc36.x86_64 arch: x86_64 bits: 64 Desktop: GNOME
    Distro: Fedora release 36 (Thirty Six)
Machine:
  Type: Laptop System: LENOVO product: 82B1 v: Lenovo Legion 5 15ARH05H
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0R33126 WIN
    serial: <superuser required> UEFI: LENOVO v: FSCN14WW date: 08/26/2020
Battery:
  ID-1: BAT0 charge: 48.8 Wh (60.0%) condition: 81.3/80.0 Wh (101.7%)
    volts: 15.1 min: 15.4
CPU:
  Info: 8-core AMD Ryzen 7 4800H with Radeon Graphics [MT MCP] speed (MHz):
    avg: 1396 min/max: 1400/2900
Graphics:
  Device-1: NVIDIA TU106M [GeForce RTX 2060 Mobile] driver: nvidia
    v: 510.68.02
  Device-2: AMD Renoir driver: amdgpu v: kernel
  Device-3: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.2 compositor: gnome-shell
    driver: X: loaded: amdgpu,nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: amdgpu resolution: 1920x1080~144Hz
  Message: Wayland GBM/EGL data currently not available.
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:
  Local Storage: total: 476.94 GiB used: 434.88 GiB (91.2%)
Info:
  Processes: 438 Uptime: 18h 55m Memory: 15.06 GiB used: 3.88 GiB (25.8%)
  Shell: Bash inxi: 3.3.16

```

**Comment by Alepunch** [comment]
Hi, Soluzione?

**Comment by lostalejandro** [comment]
Same problem happening here, it also recognizes triggers on Wine's Control Panel but games just simply won't recognize it

**Comment by rscm** [comment]
> Same problem happening here, it also recognizes triggers on Wine's Control Panel but games just simply won't recognize it

if this works for you, as a workaround I use the program `xboxdrv` to emulate the controller as an xbox 360 controller
https://xboxdrv.gitlab.io/, just run it before and at least you'll be able to use it

```
xboxdrv \
  --evdev /dev/input/by-id/usb-Sony_Interactive_Entertainment_Wireless_Controller-if03-event-joystick \
  --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y,ABS_X=X1,ABS_Y=Y1,ABS_RX=X2,ABS_RY=Y2,ABS_Z=LT,ABS_RZ=RT \
  --evdev-keymap BTN_SOUTH=A,BTN_EAST=B,BTN_NORTH=Y,BTN_WEST=X,BTN_START=start,BTN_MODE=guide,BTN_SELECT=back \
  --evdev-keymap BTN_TL=LB,BTN_TR=RB,BTN_TL2=LT,BTN_TR2=RT,BTN_THUMBL=TL,BTN_THUMBR=TR \
  --axismap -y1=y1,-y2=y2 \
  --mimic-xpad \
  --force-feedback \
  --silent

```

I put those lines inside a bash script in my local bin dir

**Comment by Etaash-mathamsetty** [comment]
> > Same problem happening here, it also recognizes triggers on Wine's Control Panel but games just simply won't recognize it
> 
> if this works for you, as a workaround I use the program `xboxdrv` to emulate the controller as an xbox 360 controller [xboxdrv.gitlab.io](https://xboxdrv.gitlab.io/), just run it before and at least you'll be able to use it
> 
> ```
> xboxdrv \
>   --evdev /dev/input/by-id/usb-Sony_Interactive_Entertainment_Wireless_Controller-if03-event-joystick \
>   --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y,ABS_X=X1,ABS_Y=Y1,ABS_RX=X2,ABS_RY=Y2,ABS_Z=LT,ABS_RZ=RT \
>   --evdev-keymap BTN_SOUTH=A,BTN_EAST=B,BTN_NORTH=Y,BTN_WEST=X,BTN_START=start,BTN_MODE=guide,BTN_SELECT=back \
>   --evdev-keymap BTN_TL=LB,BTN_TR=RB,BTN_TL2=LT,BTN_TR2=RT,BTN_THUMBL=TL,BTN_THUMBR=TR \
>   --axismap -y1=y1,-y2=y2 \
>   --mimic-xpad \
>   --force-feedback \
>   --silent
> ```
> 
> I put those lines inside a bash script in my local bin dir
> 
> check if your id is different and change it accordingly `/dev/input/by-id`

that's a long command, luckily there is this project that makes it easier
https://github.com/yoyossef/ds360

**Comment by lostalejandro** [comment]
> > > Same problem happening here, it also recognizes triggers on Wine's Control Panel but games just simply won't recognize it
> > 
> > 
> > if this works for you, as a workaround I use the program `xboxdrv` to emulate the controller as an xbox 360 controller [xboxdrv.gitlab.io](https://xboxdrv.gitlab.io/), just run it before and at least you'll be able to use it
> > ```
> > xboxdrv \
> >   --evdev /dev/input/by-id/usb-Sony_Interactive_Entertainment_Wireless_Controller-if03-event-joystick \
> >   --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y,ABS_X=X1,ABS_Y=Y1,ABS_RX=X2,ABS_RY=Y2,ABS_Z=LT,ABS_RZ=RT \
> >   --evdev-keymap BTN_SOUTH=A,BTN_EAST=B,BTN_NORTH=Y,BTN_WEST=X,BTN_START=start,BTN_MODE=guide,BTN_SELECT=back \
> >   --evdev-keymap BTN_TL=LB,BTN_TR=RB,BTN_TL2=LT,BTN_TR2=RT,BTN_THUMBL=TL,BTN_THUMBR=TR \
> >   --axismap -y1=y1,-y2=y2 \
> >   --mimic-xpad \
> >   --force-feedback \
> >   --silent
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I put those lines inside a bash script in my local bin dir
> > check if your id is different and change it accordingly `/dev/input/by-id`
> 
> that's a long command, luckily there is this project that makes it easier https://github.com/yoyossef/ds360
> 
> also what version of wine are you using, the dualsense controller only works correctly on vanilla wine or wine staging (7.4 or higher), it doesn't work reliably on anything based on valve's fork of proton (plugplay broken, bluetooth broken) or lutris wine (doesn't work at all).

THIS is definitely the answer. Just stick to lutris' default wine version `lutris-7.2.2-x86_64` . Working on all games i tried (Obviously they at least has to have native controller support. If they don't i recommend trying sc-controller)

**Comment by Mershl** [comment]
8-7 also fixes the DualSense mapping issues previously seen on Flatpak Lutris -> https://github.com/flathub/net.lutris.Lutris/issues/329 (tested on fresh prefix).

**Comment by jclsn** [comment]
How to download lutris-GE-Proton8-7-x86_64? It is not available for download under starters for me in Lutris. I can only use my PS5 controller with the System starter, but it does not run all games.

**Comment by strycore** [comment]
> How to download lutris-GE-Proton8-7-x86_64?

Stop using old versions of GE-Proton.
