### ISSUE TITLE
invalid error message when trying to install game to custom folder

### ISSUE THREAD

**Issue by Ryder17z** [lutris/lutris#4329]
[image](https://user-images.githubusercontent.com/2000703/174504688-17f41184-c001-4baf-9665-e6e1070e8156.png)

Despite the fact there should be little to no restrictions on this drive, lutris for whatever reason doesn't see it that way

Version: 0.5.10.1
This is on manjaro xfce

**Comment by strycore** [comment]
Set correct permissions to your drive and don't install a game at the root of a drive

**Comment by Ryder17z** [comment]
Again, the permissions **SHOULD** be fine, and I have specified a subdir but it throws an error at root level.

**Comment by kbulgrien** [comment]
> Again, the permissions **SHOULD** be fine, and I have specified a subdir but it throws an error at root level.

The screenshot doesn't prove anything.  To make a reasonable case for an issue, back up that assertion with a proper dump of the permissions including acls, etc., on the folder and everything above it.

**Comment by Ryder17z** [comment]
Look below. Others: read+write

**Comment by Ryder17z** [comment]
Finally some better info, thanks. But that's rather stupid.

Now you see why it seems like an invalid error.

But let's consider this as case solved.
