### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by GoshaEgorian** [lutris/lutris#4332]
I had problem with python and I had to reinstall Ubuntu. So now I have fresh install of Ubuntu but not fresh home folder.
I had errors with lutris and I tried to reinstall it too. I remove package and manually remove `.cache/lutris` and `.local/share/lutris` and `.config/lutris`. After that I install lutris again and now it does not start at all. Also there is no created folders `.local/share/lutris` and `.config/lutris`. Only `.cache/lutris` exist with empy .log file.

Error:
> lutris crashed with sqlite3.OperationalError in __enter__(): unable to open database file

**Comment by readyready15728** [comment]
I'm having the exact same error and I'm not sure what fixed it for OP

**Comment by danieljohnson2** [comment]
Run lutris in debug mode:
```
lutris -d
```
And give us the terminal spam. Might be a clue in there!

**Comment by readyready15728** [comment]
I don't know why I thought of this but for some reason I wondered whether there was a running Lutris instance without a window and `ps aux` came back with two. I killed them both and tried running Lutris again and it started up properly. Hopefully this information helps other users and devs. Now it won't load my GOG games, but that's a separate matter.
