### ISSUE TITLE
Lutris stuck at "Launching"

### ISSUE THREAD

**Issue by AdolfRoxler** [lutris/lutris#4336]
Once anything is installed, it just stares blankly at the void while it says "Launching". Sometimes Ubuntu (KDE) notifies me that some process crashed.

Any fix?

**Comment by danieljohnson2** [comment]
Not a clue. Maybe post your debug log at least? Might be a hint in there.

**Comment by AdolfRoxler** [comment]
Closing issue, moved to arch. Works perfetcly.
