### ISSUE TITLE
Lutris does not load banners

### ISSUE THREAD

**Issue by palpebral** [lutris/lutris#4344]
Lutris does not load banners on the regular "LIbrary" section, it however loads it when I'm inside the steam section.
There is nothing in the "/home/user/.cache/lutris/banners/" folder other than epic games and another game that i manually installed.

How to replicate:

Have steam/egs installed, install lutris
Install a game on steam/egs, and when lutris updates it on the client it will not show the banner when viewing the "Library" section, it will however show it on the individual steam/egs section. Idk about others like gog/origin/ etc. I only tried it on steam and egs.
I'm very new to linux and lutris, If you need more info i would be happy to provide it.

**Comment by palpebral** [comment]
It updates the banners once I manually copy the banners from "/.cache/lutris/steam/banners/"

**Comment by palpebral** [comment]
https://imgur.com/Xp7BmzN
https://imgur.com/QwFHrL9

screenshots of the issue

**Comment by Dertosh** [comment]
I think it can be related with cloudflare check.

**Comment by STiAT** [comment]
I'd say it could be related with actually downloading.
But yes, copying them to the ~/.cache/lutris/banners folder from ~/.cache/lutris/steam/banners actually works, so the banners (or some) have been downloaded.
![image](https://user-images.githubusercontent.com/1781015/183279833-5254596b-50c7-4742-b54d-79f1e10ba345.png)

**Comment by Dertosh** [comment]
Some games can be hide in steam. You can check it by id such as https://steamdb.info/app/29660/ and https://steamdb.info/app/200060/

**Comment by strycore** [comment]
Please note that banners/coverarts are not shared between services. So the EGS coverart will not be used for the Lutris coverart. All services have different sizes for their image format. 

Once games are installed from a service, Lutris should match with its own coverart. So if anything is missing, that has to be provided on  the website.
