### ISSUE TITLE
How to run The Binding of Isaac on Epic Games Store?

### ISSUE THREAD

**Issue by Leutwiler** [lutris/lutris#4345]
Hi, it's my first time running Lutris and I would like to download The Binding of Isaac: Repentance, which is on Epic Games Store.

After the installation of the Epic Games Store and The Binding of Isaac on Lutris, I supposed I also needed to install it again directly through Epic Games Store, which I did, but when I click to start the game, the game does not start.

The base game runs natively on Linux and Repentance, the last DLC, runs fine with some Proton versions on Steam. So I guess I was supposed to be able to run the same game on Epic Games using Lutris.

Can someone help me with this issue, please?

**Comment by Etaash-mathamsetty** [comment]
try using heroic games launcher with proton
im pretty sure you aren't supposed to put issues with game compatibility here, but that's my advice for you

**Comment by crazyc4t** [comment]
As @Etaash-mathamsetty said, you can use heroic games launcher for epic games, but lutris has an extension of epic games, and it looks like this:
![Screenshot from 2022-07-04 12-24-59](https://user-images.githubusercontent.com/62523210/177198328-dc0d5c71-cac3-4991-9cad-1ecaf284648e.png)

Where you just sign in, and it will show you all of your games, you could try it, or use heroic, as you wish.

**Comment by Leutwiler** [comment]
Thanks, guys! :)
