### ISSUE TITLE
Cannot search for games on lutris.

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#4346]
I installed lutris on my arch pc and then I logged into lutris.net after making a new account. When I search for games like overwatch which is already there on lutris. It says `No games matching "overwatch" was found`. Here is the ss - http://0x0.st/oSJL.png

Here is my system info -
```
                   -`                    rounak@archissexy 
                  .o+`                   ----------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.18.6-zen1-1-zen 
               `+oooooo:                 Uptime: 42 mins 
               -+oooooo+:                Packages: 1006 (pacman) 
             `/:-:++oooo+:               Shell: bash 5.1.16 
            `/++++/+++++++:              Resolution: 1366x768 
           `/++++++++++++++:             DE: Plasma 5.25.1 
          `/+++ooooooooooooo/`           WM: KWin 
         ./ooosssso++osssssso+`          WM Theme: Breeze 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze-Dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack 14 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i3-9100F (4) @ 4.200GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 1650 
 `++:.                           `-/+/   Memory: 3854MiB / 11777MiB 
 .`                                 `/
                                                                 
                                                                 


```

**Comment by danieljohnson2** [comment]
Could you check to see if "Show hidden games" is checked off in Lutris's hamburger menu? That is usually the cause when this happens to me.

Lutris *sometimes* changes the 'not found' message when this happens, but not always. I checked and this is one of the cases when it does not.

**Comment by danieljohnson2** [comment]
I think we can do better about this, so here's a PR to change the messages you get.

I casually assume that your problem is no worse than that, so please advise if it isn't.

**Comment by prorounak2005** [comment]
> Could you check to see if "Show hidden games" is checked off, or if 'Installed games only' is checked off? They are in Lutris's hamburger menu. That menu is usually the cause when this happens to me.
> 
> Lutris _sometimes_ changes the 'not found' message when this happens, but not always. I checked and this is one of the cases when it does not.

Umm... - 

![image](https://user-images.githubusercontent.com/69617708/177033585-d184c535-95e7-4352-8bbe-d9f2a80a52e1.png)

This is my system info in details btw - 
```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.18.8-zen1-1-zen
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             11.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.57
OpenGL Core:     4.6.0 NVIDIA 515.57
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.57
Vulkan:          Supported


```

**Comment by khewweifeng** [comment]
> > Could you check to see if "Show hidden games" is checked off, or if 'Installed games only' is checked off? They are in Lutris's hamburger menu. That menu is usually the cause when this happens to me.
> > Lutris _sometimes_ changes the 'not found' message when this happens, but not always. I checked and this is one of the cases when it does not.
> 
> Umm... -
> 
> ![image](https://user-images.githubusercontent.com/69617708/177033585-d184c535-95e7-4352-8bbe-d9f2a80a52e1.png)
> 
> This is my system info in details btw -
> 
> ```
> [System]
> OS:              Arch Linux rolling n/a
> Arch:            x86_64
> Kernel:          5.18.8-zen1-1-zen
> Desktop:         KDE
> Display Server:  x11
> 
> [CPU]
> Vendor:          GenuineIntel
> Model:           Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
> Physical cores:  4
> Logical cores:   4
> 
> [Memory]
> RAM:             11.5 GB
> Swap:            4.0 GB
> 
> [Graphics]
> Vendor:          NVIDIA Corporation
> OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
> OpenGL Version:  4.6.0 NVIDIA 515.57
> OpenGL Core:     4.6.0 NVIDIA 515.57
> OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.57
> Vulkan:          Supported
> ```

I also facing this issue 

I install via lutris website as workaround

**Comment by danieljohnson2** [comment]
Guess that PR won't do. Let me ask for another screenie. Can I see what the library looks like with *no* filter? I want to see the Overwatch icon in there- maybe it is misspelled or something.

Maybe you could try searching for something else too. Can you find anything at all?

Another thing that might help is the lutris debug log. Run 'lutris -d' and capture the output, then do your search and post the output here.

**Comment by khewweifeng** [comment]
the UI is different from ubuntu OS (on ubuntu, you can see 2 tab) but in other distro it does not have that tab section

the library looks same as this one https://github.com/lutris/lutris/issues/4346#issuecomment-1173045807

**Comment by JFOZ1010** [comment]
- The solution for me was in the terminal Run the command:
![image](https://user-images.githubusercontent.com/82562585/233751913-238a135c-ec60-4ade-8bcb-bea95b50084a.png)
- After that, you are installing each package, dependency that asks you for the interfaces that appear to you, I am in a debian kali linux distro. and be patient, there are many dependencies.

**Comment by strycore** [comment]
The Lutris source is used to search for games you have in your Lutris.net library. It doesn't do searches on the whole website.

To search for games on the website, click the + icon on top and select "Search the Lutris website for installers"
