### ISSUE TITLE
SIGSEGV When Attempting to Login to Game Stores

### ISSUE THREAD

**Issue by serafk** [lutris/lutris#4348]
First up, system info.
```
[System]
OS:              Fedora Linux 36 
Arch:            x86_64
Kernel:          5.18.6-201.fsync.fc36.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             62.7 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.48.07
OpenGL Core:     4.6.0 NVIDIA 515.48.07
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.48.07
Vulkan:          Supported
```

When attempting to authenticate with third party game stores (EGS, Origin, Ubisoft Connect, and GOG all experience this) the dialogue box to do so is created but is fully gray with no other UI elements and then the entire application crashes.

Here is the output from the console.
```
lutris -d
INFO     2022-06-27 20:08:53,407 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-06-27 20:08:53,424 [libretro.get_libretro_cores:24]:No folder at /home/serafk/.local/share/lutris/runners/retroarch/
INFO     2022-06-27 20:08:53,451 [startup.check_driver:57]:Using NVIDIA drivers 515.48.07 for x86_64
INFO     2022-06-27 20:08:53,451 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 2080 SUPER
INFO     2022-06-27 20:08:53,451 [startup.check_driver:77]:GPU: 10DE:1E81 3842:3081 (nvidia drivers)
INFO     2022-06-27 20:08:53,498 [startup.update_runtime:213]:Startup complete
DEBUG    2022-06-27 20:08:53,572 [lutriswindow.update_store:437]:Showing 1 games
DEBUG    2022-06-27 20:08:58,724 [base.login:285]:Connecting to Ubisoft Connect
fish: Job 1, 'lutris -d' terminated by signal SIGSEGV (Address boundary error)
```

Looking through the github, reddit, and other online sources pointed to a potential issue with some stores using an outdated OpenSSL implementation but as this is happening with all of the above stores I cannot believe that to be the case. Regardless, I tried launching Lutris with UnsafeLegacyNegotiation enabled and it did not change the behaviour.

**Comment by Aluminite** [comment]
I'm having the exact same problem.
```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.18.9-zen1-1-zen
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 515.57
OpenGL Core:     4.6.0 NVIDIA 515.57
OpenGL ES:       OpenGL ES 3.2 NVIDIA 515.57
Vulkan:          Supported
```

**Comment by vieiraa** [comment]
It's a Wayland (or a wayland+nvidia?) thing. It works for me on X11.

**Comment by serafk** [comment]
Wouldn't surprise me if it is the wayland+nvidia, as they're still catching up on supporting wayland. That said... Is this something Lutris can resolve or are we stuck waiting for further NVidia updates?

Alternatively, is it possible for Lutris to run XWayland and utilize X11 through it? I'm not super savvy on this admittedly so just spitballing.

**Comment by vieiraa** [comment]
It works using GDK_BACKEND=x11 lutris.

**Comment by vieiraa** [comment]
The crash is caused by WPEBackend-fdo. I am opening a pull request to fix it.

**Comment by vieiraa** [comment]
Fix merged, and WPEBackend-fdo package updated in Arch. Don't know about Fedora, though.

**Comment by serafk** [comment]
Works on Fedora now as well. Login prompts are showing as expected.

Thanks folks!
