### ISSUE TITLE
Feedback: Icons look tiny on 4K

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#4354]
This is how Lutris looks on 4K resolution (with zoom set at maximum).

![screenshot_2022-07-01_02-03-49_928341985](https://user-images.githubusercontent.com/3357792/176797725-d20de51c-3782-4449-92e3-270ee98092c4.png)

## PROPOSED SOLUTION:

1. Simple (conceptually): An option to scale GUI icons.
2. Advanced: A more advanced solution would be to also: Automatically chose the correct icon size based on the current screen resolution when opening Lutris, unless the user defines a custom size on the settings explicitly. (which might be hard, if we cannot find a way to report the current resolution in an agnostic way).

## Why is this necessary
The solution proposed by the community is [to enable upscaling](https://wiki.archlinux.org/title/HiDPI#Fractional_scaling) system wide. But this is not a good solution, as for most resolution sizes, this implies fractional scaling and noticeable loss in visual definition. Also, when using scaling, most resolutions won't be available on games. This also makes impossible to use FSR/dlss.

**Comment by danieljohnson2** [comment]
I think the community is basically right; though there are certainly compatibility problems that Lutris can't always work around. Linux HiDPI support is not really great, so I can see the desire for a workaround here

But... Lutris *already has* an option to show very large banners, and @strycore just recently added two new sizes ("Cover Art" he calls them); the largest size (shown below) is pretty near unusable on my LoDPI screen:

![Screenshot from 2022-07-09 10-53-15](https://user-images.githubusercontent.com/6507403/178110994-848e66c2-71ae-4b6f-a689-bd562a2ca8b7.png)

Those are enormous banners there. So, I think Lutris has what you are asking for already, and does not need an enhancement here.

**Comment by Zeioth** [comment]
The current level of quality of Lutris HiDPI GUI is subpar atm.

You can compare Lutris (maximum size)
![screenshot_2023-01-06_09-35-30_452575066](https://user-images.githubusercontent.com/3357792/210964263-142fc06d-9c1d-4145-8076-b933cece40c8.png)

And Steam
![screenshot_2023-01-06_09-35-32_708670356](https://user-images.githubusercontent.com/3357792/210963119-7858dc01-11fd-428f-909a-5817e08d9391.png)

This is no minor story. I advise keeping it open unti this is addressed permanentlly. I'm aware GTK GUI stying is painful. That's why we shoud start thinking a solution.

**Comment by Zeioth** [comment]
Maybe related: https://gitlab.gnome.org/GNOME/gtk/-/issues/4528

**Comment by strycore** [comment]
> You can compare Lutris (maximum size)

That's not how Lutris looks in Hi-DPI. I have a Surface Pro and Lutris looks normal. 
Yours is Lutris in Lo-DPI with a larger font.
