### ISSUE TITLE
Cant open jar in lutris

### ISSUE THREAD

**Issue by gitdrug** [lutris/lutris#4358]
I wanted to add [betacraft.uk/](https://betacraft.uk/)  (Minecraft Launcher) to Lutris games list but when i add command to open it java -jar /path/to/the/launchers/.jar it doesn't open thru Lutris. How would i make a .jar file run thru Lutris?

**Comment by mihailim** [comment]
1. Add game (click the + button)
2. Add locally installed game.
3. On the Game info tab:
    * Name: `Betacraft` (or whatever you want to call the launcher)
    * Runner: Linux (Runs native games)
4. On the Game options tab:
    * Executable: `java`
    * Arguments: `-jar /path/to/your/launcher.jar`
    * Working directory: `/path/to/your` (likely you want the directory in which the .jar is located)
5. Click Save.
6. Done.

**Comment by strycore** [comment]
You can also use different Java runtimes by providing an absolute path to the Java executable, if this is needed.
