### ISSUE TITLE
Regedit isn't detected as stopped

### ISSUE THREAD

**Issue by Konfuz** [lutris/lutris#436]
While investigating another issue, I noticed that after executing regedit via the lutris menu, according to the the debug-information lutris won't stop calling  **Executing fuser /usr/bin/wine** (and wine64) once a second, even after closing regedit. 

# Debug-Output

```
[...]
DEBUG    2016-11-16 16:16:28,470 [system]:Executing fuser /usr/bin/wine
DEBUG    2016-11-16 16:16:28,528 [system]:Executing fuser /usr/bin/wine64
DEBUG    2016-11-16 16:16:29,971 [system]:Executing fuser /usr/bin/wine
DEBUG    2016-11-16 16:16:30,021 [system]:Executing fuser /usr/bin/wine64
DEBUG    2016-11-16 16:16:31,471 [system]:Executing fuser /usr/bin/wine
DEBUG    2016-11-16 16:16:31,528 [system]:Executing fuser /usr/bin/wine64
DEBUG    2016-11-16 16:16:32,971 [system]:Executing fuser /usr/bin/wine
DEBUG    2016-11-16 16:16:32,998 [system]:Executing fuser /usr/bin/wine64
DEBUG    2016-11-16 16:16:34,473 [system]:Executing fuser /usr/bin/wine
DEBUG    2016-11-16 16:16:34,531 [system]:Executing fuser /usr/bin/wine64
[...]
```

# How to reproduce:

1. right-click any wine-game from the lutris menu
2. choose "wine registry" 
3. the fuser-calls will start to appear in the Debug-Info and the regeditor opens
4. close the regeditor
5. fuser calls will continue to be made, until you exit lutris. 

# Spec's

- lutris 0.4.2
- Ubuntu 14.04-ish system (bodhi) 
- wine-1.9.22 (Staging)

**Comment by strycore** [comment]
fuser calls are how we know how wine processes are still running since they are not descendants of the lutris process.

There is an actual problem is regedit is not detected as stopped.

**Comment by Konfuz** [comment]
Since you try to determine if the process is still running, do you want the "Stop Game" button to be able to also kill regedit?  In case you do: The button is never activated in the first place, when regedit is executed and also not when manually running an exe inside the prefix.

btw: I like it a lot, that you can actually see the status of the button. PlayOnLinux has no indication there, and it is a big annoyance.

**Comment by strycore** [comment]
I've removed regedit from the ignored process names, soon Lutris itself won't be using regedit internally so it doesn't have to be on that list.
