### ISSUE TITLE
Revert not showing winecfg menu option for Proton

### ISSUE THREAD

**Issue by Random-Chain** [lutris/lutris#4362]
[This commit](https://github.com/lutris/lutris/commit/f1d2033573b73a8f32c5f6609d11da8efc94aee0) removes the Wine configuration option from the menu when using any wine proton version, it was done to fix [bug #1381](https://github.com/lutris/lutris/issues/1381). That made sense when proton did not come with its own winecfg binary.
However now users can download lutris-GE-Proton versions directly from Wine version management and they have winecfg that works fine, I believe this change should be reverted.

(To address the original issue, I think Lutris should catch the exception and just give some "winecfg executable not found" error instead of crashing, but I realise this can be a little more complicated to implement)

**Comment by strycore** [comment]
I've removed the Proton condition for Winecfg
