### ISSUE TITLE
Can't access lutris from my network

### ISSUE THREAD

**Issue by daniel-bencic** [lutris/lutris#4363]
Hello,

I somehow can't access any Lutris service from my network. Not even the Lutris website works. I could verfiy that it works from
another network (can access the website from my mobile phone). This prevents me from installing any game, because I fails with: "Failed to retrieve wine information). I'm not using any VPN.

**Comment by danieljohnson2** [comment]
That sounds like an issue with that particular network. You need to have access to www.lutris.net.

Can you access *any* websites on the affected network?

When you try to access lutris,net with your browser, what happens? Is there an error message?

You can also run lutris with the command 'lutris -d', trigger the error, and post the output here. There may be more useful information in there.

**Comment by crazyc4t** [comment]
Hello, It could help to use `traceroute`  to check what happens between the connection of your device to the website, as @danieljohnson2 said, does it throws an error? Have you tried another browser? Have you tried the `ping` command?

Let us know! Am happy to help

**Comment by daniel-bencic** [comment]
Thanks for the reply.

> That sounds like an issue with that particular network. You need to have access to [www.lutris.net](http://www.lutris.net).
>
> Can you access _any_ websites on the affected network?
>
> When you try to access lutris,net with your browser, what happens? Is there an error message?
>
> You can also run lutris with the command 'lutris -d', trigger the error, and post the output here. There may be more useful information in there.

There is no website I am aware of that I can't access from this network.

If I access the Lutris website with Firefox the following error occurs:
```
The connection has timed out.
The server at lutris.net is taking too long to respond.
```

Output of lutris -d:
- After launch
```
DEBUG    2022-07-04 20:03:54,123 [http.get:83]:GET https://lutris.net/api/runtimes?enabled=1
ERROR    2022-07-04 20:04:54,159 [runtime._iter_remote_runtimes:216]:Failed to get runtimes: Unable to connect to server https://lutris.net/api/runtimes?enabled=1: <urlopen error [Errno 101] Network is unreachable>
```
- After pressing "Install" for a script
```
DEBUG    2022-07-04 20:05:36,344 [http.get:83]:GET https://lutris.net/api/runners/wine
ERROR    2022-07-04 20:06:36,406 [runner.get_runner_version:337]:Unable to get runner information: Unable to connect to server https://lutris.net/api/runners/wine: <urlopen error [Errno 101] Network is unreachable>
ERROR    2022-07-04 20:06:36,406 [interpreter.install_runner:261]:Failed to retrieve wine (lutris-ge-lol-7.0-2-x86_64) information
ERROR    2022-07-04 20:06:36,407 [errors.__init__:18]:Failed to retrieve wine (lutris-ge-lol-7.0-2-x86_64) information
None
```

> Hello, It could help to use `traceroute` to check what happens between the connection of your device to the website, as @danieljohnson2 said, does it throws an error? Have you tried another browser? Have you tried the `ping` command?
>
> Let us know! Am happy to help.

`ping`:
```
PING lutris.net (188.114.97.3) 56(84) bytes of data.

--- lutris.net ping statistics ---
255 packets transmitted, 0 received, 100% packet loss, time 260100ms
```

`traceroute -m 255`:
```traceroute to lutris.net (188.114.97.3), 255 hops max, 60 byte packets
 1  router.lan (192.168.10.1)  0.180 ms  0.162 ms  0.271 ms
 2  192.168.22.1 (192.168.22.1)  0.864 ms  1.820 ms  0.884 ms
 3  * * *
 4  * * *
... * * * until
255 * * *
```

**Comment by crazyc4t** [comment]
That is indeed so weird, could be a port closed or something related, do you have a firewall activated?

**Comment by strycore** [comment]
fyi, the forums are still hosted on the previous server, which isn't behind CloudFlare. That would explain why you wouldn't be blocked on them.

apparently, the block wasn't related to the firewall rules in CF. Some IP range get banned when I notice unusual traffic but those are mostly located in datacenters.
