### ISSUE TITLE
Invalid path to executable if working directory has a trailing slash

### ISSUE THREAD

**Issue by NekoiNemo** [lutris/lutris#4369]
(I was able to observe this with Linux runner, not sure if behaviour is the same with other runners)

If Working Directory has a trailing slash and points to the directory where executable is located, the executable name is resolved incorrectly and results in error.

To illustrate: say i want to launch Kitty terminal and specify `/usr/bin/kitty` with `/usr/bin/` as the workDir. Attempting to launch results in `Failed to execute process '.kitty'. Check that the file exists` error in log (i assume it was supposed to resolve to `./kitty`).

The same error happens if you go up the path and specify `/usr/` as workDir, which results in binary being resolved to `.bin/kitty`.

This, however, does not happen if working directory doesn't share path prefix with the binary (like `/home/` for this example) or if you specify just `/` as workDir.

**Comment by danieljohnson2** [comment]
This is a bug in the code that generates the path for the command to execute; it tries to build a working-directory-relative path, but is confused by some extra characters. But Python provides os.path.relpath() to do this job; we can use that and get a much better result.
