### ISSUE TITLE
lutris fails to locate user.reg on wine-launch (for unspecified wine-prefix)

### ISSUE THREAD

**Issue by Konfuz** [lutris/lutris#437]
Having installed lutris only recently, I tried to make a launcher for a game installed under my default wine-prefix. The launcher fails silently, when I use any one of the default "play game" options, it however works flawlessly when I choose "run EXE inside wine prefix" instead. 

Running lutris with debug-output I discovered the true problem:
```
DEBUG    2016-11-16 16:40:22,855 [system]:Executing which wine
ERROR    2016-11-16 16:40:22,864 [jobs]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7fa011877710>>: Registry 'user.reg' does not exists
<class 'OSError'> Registry 'user.reg' does not exists
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 708, in prelaunch
    prefix_manager.setup_defaults()
  File "/usr/lib/python3/dist-packages/lutris/util/wineprefix.py", line 16, in setup_defaults
    self.override_dll("winemenubuilder.exe", "")
  File "/usr/lib/python3/dist-packages/lutris/util/wineprefix.py", line 49, in override_dll
    self.set_registry_key(key, dll, mode)
  File "/usr/lib/python3/dist-packages/lutris/util/wineprefix.py", line 33, in set_registry_key
    registry = WineRegistry(self.get_registry_path(key))
  File "/usr/lib/python3/dist-packages/lutris/util/wineregistry.py", line 78, in __init__
    raise OSError("Registry '%s' does not exists" % reg_filename)
```
I figured that the path to my user.reg is underspecified, because the default option for the wineprefix is blank, and that apparently gets carried over to the method responsible of locating the user.reg 

# Workaround
The Problem can be circumvented, by explicitly setting the wineprefix to the default-location **~/.wine**
in the config-menu 

# Spec's
- lutris 0.4.2

**Comment by strycore** [comment]
Yep, this is an actual bug, it will be fixed in the next release.

**Comment by testman42** [comment]
Which latest version?
I just updated to lutris-0.4.3-15.2.noarch on Fedora 25 x86_64 and I still encounter this bug.

**Comment by strycore** [comment]
@testman42 I have written another fix for this bug as it still affected empty wine prefixes. I'll try to release 0.4.4 today
