### ISSUE TITLE
can't sign in to anything

### ISSUE THREAD

**Issue by RK33DV** [lutris/lutris#4371]
i'm unable to sign in to anything. i first tried epic games then steam then ogg and none worked. i ran lutris -d and got this:

EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect:1:181: CONSOLE RENDERING ERROR Viewport argument key "minimal-ui" not recognized and ignored.

when i click the sign in button.
i dont know what is going on. Thanks.

**Comment by RK33DV** [comment]
after further googleing, i have discovered that its a problem with the mesa drivers  that come with ubuntu 21.10(mesa version 22.1.3) i didnt find a way to downgrade it and it doesnt look like something a new linux user should mess with. maybe someone here can help since this is a place full of linux users

**Comment by RK33DV** [comment]
i have no idea what i did but it works now

**Comment by EzequielRamis** [comment]
@RK33DV hey! did you remember something apart from mesa drivers? I'm having the same error without using ubuntu.

**Comment by Trevoke** [comment]
I'm also unable to log in now and would love some wisdom!

**Comment by UlyssesZh** [comment]
I am encountering the exact same error.
