### ISSUE TITLE
Use discrete gpu instead of integrated gpu for Vulkan-ICD-Loader in wine settings

### ISSUE THREAD

**Issue by spacemanspiff2007** [lutris/lutris#4373]
I have an Intel CPU with integrated GPU and an AMD GPU. 
By default the `vulcan icd loader` under wine -> system settings (extended options) is set to the internal GPU: 
``Intel Open Source (MESA:ANV) (standard)``
Only after changing this to ``AMD RADV Open Source (MESA:RADV)`` the discrete gpu is used and the low frame rate disappears.

**Comment by strycore** [comment]
Multi GPU support should be better in the latest Lutris version
