### ISSUE TITLE
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'

### ISSUE THREAD

**Issue by belkka** [lutris/lutris#4379]
Following python exception is raised when I try to change wine runner settings for a game. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 47, in synchronized_call
    result.append(func())
TypeError: display_vulkan_error() missing 1 required positional argument: 'on_launch'
```

Steps to reproduce:
1. Choose a wine game
2. Right-click -> menu option "Configure" -> tab "Runner options" 
3. Turn on "Enable DXVK" switch, then save
4. See the error
5. Open options again, see that switch is turned off, despite we've turned it on

**Comment by danieljohnson2** [comment]
Seems straightforward; the display_vulkan_error is being called with no arguments. I've made its one argument optional with a default value, so this call will succeed. Should fix this.
