### ISSUE TITLE
Some uninstalled Origin games have the wrong box art

### ISSUE THREAD

**Issue by sonic2kk** [lutris/lutris#4383]
A couple of my Origin games have the wrong cover art. "Madden NFL 22" and "Plants vs. Zombies: Battle for Neighborville™" display the wrong cover art in my library, displaying the art for "Knockout City™".

![image](https://user-images.githubusercontent.com/7917345/179408189-ed7c9661-f82e-4f81-9bd6-90a4979c4bb9.png)

"The Sims 4™" also has *wrong-ish* cover art. I have the game on Steam and Origin with the Origin purchase being for the so-called "Digital Deluxe" edition, but both the Steam and Origin listings show the  "Origin Digital Deluxe" box art. The reason I say *wrong-ish* for this game is that the cover art is there and mostly correct, and I'm not even sure if there is a regular box art cover for this game available. It's not really as much of a big deal as the first two games.

Sorry if this has been reported before, I looked around the issue tracker and couldn't find an issue about it but I could've just missed it.

**Comment by strycore** [comment]
We're removing the Origin integration in favor of an EA App integration. There's a lot of code in common with the Origin integration and so far the media has been loading correctly on both.
