### ISSUE TITLE
Fall Guys/EAC requires LD_PRELOAD

### ISSUE THREAD

**Issue by sad-goldfish** [lutris/lutris#4387]
See [this comment](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1513#issuecomment-1183124550). Fall Guys/EAC requires LD_PRELOAD to be set though it can be empty (LD_PRELOAD=""). Consider setting this (if not previously set) when the EAC runtime is enabled.

**Comment by sad-goldfish** [comment]
Fall guys works with a build of Wine Lutris 7.2-2. After
- `cp drive_c/Program Files/Epic Games/FallGuys/{EasyAntiCheat/easyanticheat_x64.so,FallGuys_client_game_Data/Plugins/x86_64}`
- Set `TargetApplicationPath=FallGuys_client_game.exe` in `drive_c/Program Files/Epic Games/FallGuys/FallGuys_client.ini`
- Use the LD_PRELOAD workaround above.
My Lutris Runtime is disabled (which might affect `LD_PRELOAD`).

**Comment by strycore** [comment]
I have Fall Guys installed on 2 different machines, no LD_PRELOAD is needed.
Don't disable the lutris runtime

**Comment by sad-goldfish** [comment]
@strycore Makes sense if you don't support disabling the lutris runtime but, given the Heroic Games issue I linked and the fact that they have merged a fix [in this pull request](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1564), I think there is some truth to it.
