### ISSUE TITLE
RPCS3 AppImage can't replace the executable.

### ISSUE THREAD

**Issue by HoboDev** [lutris/lutris#4392]
I've installed the rpcs3 runner but because there are daily builds of rpcs3 it's a bit outdated.

So I replaced the executable of the runner with the AppImage file (which auto updates)
But when trying to start a game the logs show that a specific version of glibc is missing.

Starting the game with the AppImage from command line works flawless.

**Comment by strycore** [comment]
I've updated the Lutris runner to RPCS3 v0.23. 
Do you still have errors about glibc using this one?
