### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by jld3103** [lutris/lutris#4394]
My builds fail since commit 3f5a64e074d20adeee39364c8455a488c2300eab (found via git bisect) with this error message:
```log
ninja: Entering directory `/home/jld3103/src/lutris/build'                                          
[1/13] Generating po/fi/LC_MESSAGES/lutris-fi.mo with a custom command
FAILED: po/fi/LC_MESSAGES/lutris.mo 
/usr/bin/msgfmt ../po/fi.po -o po/fi/LC_MESSAGES/lutris.mo
../po/fi.po:140: end-of-line within string
../po/fi.po:140:10: syntax error
../po/fi.po:141: end-of-line within string
/usr/bin/msgfmt: found 3 fatal errors
[12/13] Generating net.lutris.Lutris.metainfo.xml with a custom command
FAILED: net.lutris.Lutris.metainfo.xml 
/usr/bin/meson --internal msgfmthelper --msgfmt=/usr/bin/msgfmt ../share/metainfo/net.lutris.Lutris.metainfo.xml net.lutris.Lutris.metainfo.xml xml /home/jld3103/src/lutris/po
/home/jld3103/src/lutris/po/fi.po:140: end-of-line within string
/home/jld3103/src/lutris/po/fi.po:140:10: syntax error
/home/jld3103/src/lutris/po/fi.po:141: end-of-line within string
/usr/bin/msgfmt: found 3 fatal errors
[13/13] Generating net.lutris.Lutris.desktop with a custom command
FAILED: net.lutris.Lutris.desktop 
/usr/bin/meson --internal msgfmthelper --msgfmt=/usr/bin/msgfmt ../share/applications/net.lutris.Lutris.desktop net.lutris.Lutris.desktop desktop /home/jld3103/src/lutris/po
/home/jld3103/src/lutris/po/fi.po:140: end-of-line within string
/home/jld3103/src/lutris/po/fi.po:140:10: syntax error
/home/jld3103/src/lutris/po/fi.po:141: end-of-line within string
/usr/bin/msgfmt: found 3 fatal errors
ninja: build stopped: subcommand failed.
```
I'm building using `arch-meson . build && meson compile -C build`.

@tutacat @strycore

**Comment by danieljohnson2** [comment]
It looks like a very simple syntax error, but I'll pop a PR for this since @strycore slapped my hands away from the .po files recently. So he can decide if he likes the angle of my quotation marks.

**Comment by tutacat** [comment]
Whoops sorry, I made the mistake of a PR withiut testing, that may break the order of languages or not work at all

I would see if just reverse that specific commit on /po/LINGUAS if that fixed it.

@danieljohnson2

**Comment by codevski** [comment]
exact same issue

**Comment by strycore** [comment]
> It looks like a very simple syntax error, but I'll pop a PR for this since @strycore slapped my hands away from the .po files recently. So he can decide if he likes the angle of my quotation marks.

It's more a matter of not mixing code patches and translation stuff and also not modifying files that are usually modified by external tools.
I've corrected the file, which had a misplaced line break
