### ISSUE TITLE
download too slow

### ISSUE THREAD

**Issue by plokid** [lutris/lutris#4398]
It's too slow for me to download `wine-lutris.tar.xz` from github. I usually download github files from mirror website, but there is no way for me to change that.

**Comment by plokid** [comment]
I tried to download and copy `wine-lutries-7.2-2-x86-64.tar.xz` to `$HOME/.cache/lutris/`, but it can't be re recognized.

**Comment by strycore** [comment]
you need to extract the archive to `~/.local/share/lutris/runners/wine/` and the client won't try to download it
