### ISSUE TITLE
Lutris Overwrites Steam Artwork On Launch with low resolution Banners

### ISSUE THREAD

**Issue by tlneondo** [lutris/lutris#4405]
My Process for Adding non-steam games to steam is to make them launch through lutris, then use lutris to add the shortcut to steam.

Then I use https://github.com/boppreh/steamgrid to automatically fill the steam shortcuts with high res covers, logos, and background art, plus my own preferences.

Whenever a lutris steam shortcut is used to launch a game it seems to overwrite the cover art with low resolution art.
This is what it looked like after running Titanfall 2 via Origin Lutris integration.
![image](https://user-images.githubusercontent.com/12129080/182962666-066aec84-b9e2-4755-9009-77890e40faf5.png)
![image](https://user-images.githubusercontent.com/12129080/182962705-dcd53b54-4ff8-4dc6-8354-474821050141.png)

After I fixed it, and what it was before I launched titanfall 2.
![image](https://user-images.githubusercontent.com/12129080/182963036-2b9cdcd6-f1d0-43a1-96ce-6af927a1c153.png)
![image](https://user-images.githubusercontent.com/12129080/182963063-d7047883-d453-4ebc-b624-0cbf87688645.png)

**Comment by tlneondo** [comment]
I believe I may have found a workaround by removing the logo from lutris's game entries.

**Comment by crimson-snow** [comment]
#4439 should fix this issue.

**Comment by strycore** [comment]
PR merged
