### ISSUE TITLE
Cannot modify wine runners in 0.5.11

### ISSUE THREAD

**Issue by pm4rcin** [lutris/lutris#4407]
Hi, when trying to open the window with wine runners it shows the error `too many values to unpack (expected 2)`. It is a regression that never happened in 0.5.10 for me.
To reproduce:
1. Start lutris
2. Click manage versions button
Environment:
Flatpak Lutris 0.5.11
Window Manager: dwl (Wayland wlroots)
Console output
```fish
❯ flatpak run net.lutris.Lutris -d
INFO     2022-08-05 09:59:15,610 [startup.init_lutris:174]:Starting Lutris 0.5.11
DEBUG    2022-08-05 09:59:15,647 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2022-08-05 09:59:15,677 [startup.check_driver:58]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-08-05 09:59:15,677 [startup.check_driver:62]:GPU: NVIDIA GeForce GTX 1650
INFO     2022-08-05 09:59:15,677 [startup.check_driver:78]:GPU: 10DE:1F99 17AA:3A43 (nvidia drivers)
INFO     2022-08-05 09:59:15,677 [startup.check_driver:78]:GPU: 1002:1636 17AA:3A3F (amdgpu drivers)
DEBUG    2022-08-05 09:59:15,862 [lutriswindow.update_store:446]:Showing 0 games
INFO     2022-08-05 09:59:15,869 [startup.update_runtime:215]:Startup complete
ERROR    2022-08-05 09:59:18,745 [jobs.target:36]:Error while completing task <function get_runners at 0x7f3469b288b0>: <class 'ValueError'> too many values to unpack (expected 2)
  File "/app/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/lutris/api.py", line 84, in get_runners
    (_family, _type, _proto, _canonname, (_address, _port)) = answers[0]
ERROR    2022-08-05 09:59:18,745 [runner_install.runner_fetch_cb:86]:too many values to unpack (expected 2)
```
![1659686370-wayshot](https://user-images.githubusercontent.com/37148802/183031626-705f6f65-577d-408d-89ef-a3e44b2d8e5d.png)

**Comment by nabel0** [comment]
Same problem here with the flatpack version...

**Comment by runboy93** [comment]
Can anyone reproduce this on deb version or is this just flatpak exclusive bug?

**Comment by nabel0** [comment]
i think it's only a flatpak problem

**Comment by Tibladar** [comment]
Also happening with the deb package

**Comment by danieljohnson2** [comment]
I see it. Some recent code is looking at the result of getaddrinfo, but tries to decompose the socket address- and it expects an IPv4 address. This explodes if it gets an IPv6 address.

But it does not use this information, so it can just not do that.
