### ISSUE TITLE
Write widget to edit environment variables.

### ISSUE THREAD

**Issue by Konfuz** [lutris/lutris#442]
When specifying a _command prefix_ in the settings, whilst at the same time using _primusrun_ (required for Nvidia Optimus chipsets) the _command prefix_ is inserted between the _primusrun_ command and the rest of the execution line.  

This makes it impossible to set environment-variables as a _command prefix_, because sadly primusrun tries to exec them.

I do not know if there is a use-case where one would like the current behavior. At least I can't think of an case where I had to put something between _primusrun_ and the executable. 

**Edit:** Actually I seem to be entirely mistaken, because i get a "file not found" error for my environment-variables, even when not using primusrun.  Also according to the debug output the command order is correct (first the prefix then primusrun) so the Issue I discovered is that lutris wont allow setting env-vars as a prefix at all?

**Comment by Konfuz** [comment]
Apparently the issue is that all components of the _command prefix_ are encapsulated in quotes, which is a bad thing for the env-vars. 

See line 69 in _thread.py_: 
```python
        self.command_string = ' '.join(
            ['"%s"' % token for token in self.command]
        )
```

**Comment by strycore** [comment]
There is an undocumented feature for adding environment variables when launching games. The main reason it's not shown in the UI is that is would require a custom widget I haven't written yet ;)

You can add environment variables manually if you find the correct config file and put your variables in the system/env section.
There's an example here: https://lutris.net/games/install/1807/view

**Comment by Konfuz** [comment]
Good to know, but is there a particular reason to limit the command prefix to executable stuff?

Adding a separate form for env-vars feels a bit like an unnecessary complication. I mean... It's not like there is a shortage of input-fields and checkboxes in the existing UI... Plus you would not have to write that widget :smirk:

**Comment by strycore** [comment]
Yeah, the UI is getting a bit cluttered that's true. But I don't think it would be possible to pass environment variables in the prefix command because the commands are not launched in a shell. If you look at thread.py, you see that environment variables are passed separately from the executable and its arguments and that calls to subprocess.Popen don't set shell to True. If we wanted to use that field for environment variables, we would have parse the line to extract anything that looks like a variable and pass them to env instead.

**Comment by Konfuz** [comment]
Thanks for the explanation :+1:  I used Popen myself in the past but that specialty slipped my mind. I remember the documentation is plastered with big red warning labels not to use shell=true for unfiltered user-input to avoid arbitrary command execution. However – since lutris is kind of an arbitrary- command-execution-machine anyway it might still be a viable option(?) 

If the _command prefix_ wont get passed to a shell, perhaps it could get renamed? Having the input-field for Envvars close-by would also help to clarify.

**Comment by strycore** [comment]
The widget is done (https://github.com/strycore/pygobject-demos/blob/master/editable-grid.py), now I have to integrate it to Lutris.

**Comment by strycore** [comment]
Done!
