### ISSUE TITLE
libgio-2.0.so.0: undefined symbol: g_atomic_ref_count_inc

### ISSUE THREAD

**Issue by NoxInmortus** [lutris/lutris#4425]
Hello, trying to play Gog version of Morrowind (https://lutris.net/games/the-elder-scrolls-iii-morrowind-goty-edition/)

But the game fails to start, with following error log:
```
Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 16, in <module>
    from lutris.util.log import logger
  File "/usr/lib/python3/dist-packages/lutris/util/log.py", line 7, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_atomic_ref_count_inc
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_lutris_bin_lutris-wrapper.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 16, in <module>
    from lutris.util.log import logger
  File "/usr/lib/python3/dist-packages/lutris/util/log.py", line 7, in <module>
    from gi.repository import GLib
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_atomic_ref_count_inc
```

`/lib/x86_64-linux-gnu/libgio-2.0.so.0` file is present and provided by `libglib2.0-0` package which is installed:
```bash
$ apt policy libglib2.0-0
libglib2.0-0:
  Installed: 2.64.6-1~ubuntu20.04.4
  Candidate: 2.64.6-1~ubuntu20.04.4
  Version table:
 *** 2.64.6-1~ubuntu20.04.4 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by danieljohnson2** [comment]
Odd error.

In the game's configuraiton, there's an option to "Disable Lutris Runtime"; it's on the "System Options" tab.

Can you turn that on and try again? Does it start to work? If not, does the error output change?

**Comment by NoxInmortus** [comment]
Not working and the error log does not change either. Tried to disable/enable "Prefer system libraries" as well, but either option does not change the result either.

**Comment by danieljohnson2** [comment]
Rats. Another beautiful theory shot to hell by pesky reality.

**Comment by NoxInmortus** [comment]
I tried to execute the Executable path (/home/user/Games/morrowind/openmw-launcher) in my case. The launcher do run correctly, but after clicking Play, I just get a purple window with some music. Console logs shows that it fails to find some ressources
```plaintext
[...]
[00:08:40.551 E] Failed to open image: Resource 'textures/water/ripple00.dds' not found
[...]
```

I already tried to reinstall the game once, idk what I did wrong...

**Comment by NoxInmortus** [comment]
Instead of starting from https://lutris.net/games/the-elder-scrolls-iii-morrowind-goty-edition/, I tried to uninstall, login on my gog account on Lutris, and start the installer from there, without making any fuss, just clicking install/continue everytime, and still at first launch, same error shown in logs.

I found [this issue](https://github.com/project-slippi/Ishiiruka/issues/323) on another project, which seems to be close, and is talking about conflicts with some libraries which may be loaded from the system. I did not found libgio in `/home/user/Games/morrowind/lib` but there is `/home/user/Games/gog/the-elder-scrolls-iii-morrowind-goty-edition/lib/libglib-2.0.so.0 ` that may be a different version from system `libgio-2.0.so.0.6400.6`, what do you thing @danieljohnson2  ?

I'm not sure why having the "Prefer system libraries" option enabled would not fix the issue in this case tho

**Comment by NoxInmortus** [comment]
Dang, I tried to move away `libglib-2.0.so.0` from `/home/user/Games/morrowind/lib`, and the launcher started.

After clicking on "Play" on the launcher, the game starts, but still with a purple screen and music, and the same error logs of failure to find ressources. Would it be caused by Lutris or the game/OMW itself ?

**Comment by danieljohnson2** [comment]
I think you are getting there. I've seen issues like this with GOG; the game includes a bunch of libraries, but also uses system provided libraries and they conflict. The Lutris settings do not help because they affect *Lutris* supplied libraries; but Lutris knows nothing of what GOG packaged with the game.

You probably have solved your first issue by removing libglib from the game; the purple screen is a separate issue.

The fact that you have libglib in there at all makes me think you using the OpenMW version, a Linux port. Here's the troubleshooting page:
[Common Problems](https://openmw.readthedocs.io/en/stable/manuals/installation/common-problems.html)
The last issue sounds similar to yours, maybe that will help.

If not, I have different idea. Linux is not that great at backwards compatibility compared to Windows, but WINE offers that part of the Windows experience on Linux (to a point). If you install using the "Auto Generated" GOG installer instead of the Lutris.net custom one, I think you should wind up running Morrowind on WINE.

That should be resolve everything (and perhaps will bring new issues).

**Comment by NoxInmortus** [comment]
Thanks for your help, I successfully launched the game after doing https://openmw.readthedocs.io/en/stable/manuals/installation/common-problems.html#music-plays-but-only-a-black-screen-is-shown

Thanks for your help. Feel free to close this issue, I opened an another one on OpenMW about the `libgio` problem : https://gitlab.com/OpenMW/openmw/-/issues/6935

**Comment by danieljohnson2** [comment]
Sure. Closing issues is fun. See: *Close*!
