### ISSUE TITLE
[Errno 2] no such file or directory: dxvk_versions.json

### ISSUE THREAD

**Issue by HawHawDaw** [lutris/lutris#4429]
disabling dxvk gives the same error in vk3d, disabling vk3d gives the same error in dxvp nvapi. it seems my lutris can't make these json files for whatever reason. so far I've tried deleting the folders but lutris only recreated the folders with nothing in them. feel free to ask me anything to help me solve it.

**Comment by danieljohnson2** [comment]
Could you run "lutris -d" and provide the output? It might help us understand what went wrong.

The most obvious thing is that maybe you have an old version of Lutris. We've had some bugs around those versions.json files; it should be much more eager to re-download them in version 0.5.10.1.

**Comment by HawHawDaw** [comment]
> Could you run "lutris -d" and provide the output? It might help us understand what went wrong.
> 
> The most obvious thing is that maybe you have an old version of Lutris. We've had some bugs around those versions.json files; it should be much more eager to re-download them in version 0.5.10.1.

~$ lutris -d
INFO     2022-08-16 00:09:21,484 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-08-16 00:09:21,537 [libretro.get_libretro_cores:24]:No folder at /home/minutemen/.local/share/lutris/runners/retroarch/
DEBUG    2022-08-16 00:09:21,545 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-08-16 00:09:21,595 [startup.check_driver:65]:Running AMD Mesa driver 21.2.6 on AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.42.0, 5.15.0-46-generic, LLVM 12.0.0) (0x15d8)
INFO     2022-08-16 00:09:21,595 [startup.check_driver:77]:GPU: 1002:15D8 17AA:3808 (amdgpu drivers)
DEBUG    2022-08-16 00:09:21,695 [http.get:83]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2022-08-16 00:09:40,454 [http.write_to_file:134]:Writing to /home/minutemen/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
INFO     2022-08-16 00:09:40,456 [dll_manager.upgrade:241]:Downloading D3D Extras v2...
INFO     2022-08-16 00:09:40,457 [dll_manager.download:123]:Downloading https://github.com/lutris/d3d_extras/releases/download/v2/v2.tar.xz to /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2.tar.xz
DEBUG    2022-08-16 00:09:40,458 [http.get:83]:GET https://github.com/lutris/d3d_extras/releases/download/v2/v2.tar.xz
DEBUG    2022-08-16 00:18:45,038 [http.write_to_file:134]:Writing to /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2.tar.xz
INFO     2022-08-16 00:18:45,048 [dll_manager.download:128]:Extracting /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2.tar.xz to /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2
DEBUG    2022-08-16 00:18:45,049 [extract.extract_archive:123]:Extracting /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2.tar.xz to /home/minutemen/.local/share/lutris/runtime/d3d_extras/v2
ERROR    2022-08-16 00:18:46,096 [extract.extract_archive:134]:Extraction failed: Compressed file ended before the end-of-stream marker was reached
ERROR    2022-08-16 00:18:46,096 [jobs.target:36]:Error while completing task <bound method LutrisInitDialog.initialize of <dialogs.LutrisInitDialog object at 0x7fb577524c40 (lutris+gui+dialogs+LutrisInitDialog at 0x256e320)>>: <class 'lutris.util.extract.ExtractFailure'> Compressed file ended before the end-of-stream marker was reached
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/__init__.py", line 197, in initialize
    init_lutris()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 207, in update_runtime
    dll_manager.upgrade()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 242, in upgrade
    self.download()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dll_manager.py", line 129, in download
    extract_archive(archive_path, self.path, merge_single=True)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 135, in extract_archive
    raise ExtractFailure(str(ex)) from ex
DEBUG    2022-08-16 00:18:53,058 [lutriswindow.update_store:437]:Showing 1 games

it looks like lutris can't download the things it needs. i think this might be because of my internet, i had weird connection problems to different url's in the past. i'll try my phone's provider and try again to see if it downloads them properly

**Comment by HawHawDaw** [comment]
Lutris installed everything at launch after i switched my internet to a different provider. it seems the problem was my internet not being able to connect to the url where lutris was trying to download things
