### ISSUE TITLE
Lutris does not synchronize Steam games added via CD-KEY

### ISSUE THREAD

**Issue by mdeguzis** [lutris/lutris#443]
I added Duke Nukem Forever (.95 cents US wooo) via the CD-KEY on Steam. I could see it in Steam for Windows on my Arch Linux box. I manually added it to Lutris, using winesteam and the AppID. Steam for Windows loaded up and started downloading right away, confirming functionality and ownership. 

Is it possible to fix this scenario?

**Comment by strycore** [comment]
Did you sync your Steam library on the website first? It might not be able to sync it from the local install but might be able to do it from your remote library.

**Comment by ProfessorKaos64** [comment]
Yep, I did. I opened up Steam (Linux) on my desktop. Added the CD key, say it in my Library, then opened Lutris and tried a few syncs.

**Comment by strycore** [comment]
I've added a lot of games by key, is this still an issue?

**Comment by Medath** [comment]
I added a game via a key today and after installation it got picked up by Lutris immediately.
