### ISSUE TITLE
Xemu support

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#4431]
It would be great if a runner for XEMU could get added. [Looks like it's the best Xbox emulator now](https://emulation.gametechwiki.com/index.php/Xbox_emulators#Emulators).

Seems like by now it can run a few games. https://xemu.app/

https://github.com/mborgerson/xemu

Issues about Xbox360, not Xbox: #2432 https://github.com/lutris/agora/issues/36

**Comment by strycore** [comment]
I've tried Xemu and was able to play some games. We can likely have a runner for next release (not the one in beta but the one after)

**Comment by strycore** [comment]
Xemu runner is available in the latest beta
