### ISSUE TITLE
FAILED: meson-lutris-pot

### ISSUE THREAD

**Issue by telometto** [lutris/lutris#4438]
I'd like to add a translation to Lutris, but running `ninja lutris-pot -C builddir` results in the following error:

```
FAILED: meson-lutris-pot 
/usr/bin/meson --internal exe --unpickle /home/MYUSER/Documents/meson/lutris/builddir/meson-private/meson_exe_meson_a8f66f35396872f53aeebbe6ccf5315d31e16dd6.dat
ninja: build stopped: subcommand failed.
```

How can I get around this error?

**Comment by danieljohnson2** [comment]
You run './po/generate-potfiles.sh' to update 'POTFILES'.

Looks like it's been a while since anybody did this. I've gone ahead and done it for you; go ahead and 'git pull' and try again- should work now.

**Comment by telometto** [comment]
@danieljohnson2 Worked a charm! Thanks.
