### ISSUE TITLE
Detect if some libs like libfreetype6:i386 are unavailable

### ISSUE THREAD

**Issue by CapsAdmin** [lutris/lutris#444]
I'm using kde neon (based on ubuntu 16.04) and I installed lutris through the ubuntu repositories. The wine version lutris decided to install is "staging-1.9.21-i386"

When attempting to install a windows game the usual dialog you get about installing gecko and mono (or something) was just a tiny window without any text. I pressed enter which I assume continued the installation and then steam shows up but it's also lacking font rendering.

Launching lutris with -d and then launching wine through lutris says it can't find freetype

Launching "/home/caps/.local/share/lutris/runners/wine/staging-1.9.21-i386/bin/*" outside of lutris also complains about missing freetype.

**Comment by strycore** [comment]
That's strange, we do ship libfreetype6 with our version of the Steam Runtime: .local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu/libfreetype.so.6
