### ISSUE TITLE
5.11 deb package seen as a downgrade in apt (Pop!_OS 22.04)

### ISSUE THREAD

**Issue by ItsRogueRen** [lutris/lutris#4446]
When installing the deb package, Eddy shows it as installing a downgrade rather than an update. The previous package of 5.10.01 is also reinstalled if `sudo apt upgrade` is run from a terminal with 5.11 installed. Tested both without and with the Ubuntu PPA.

More than likely it could just be that the repo isn't updated, but having this happen with the PPA listed on the Lutris [downloads](https://lutris.net/downloads) page is what's been confusing me.

(EDIT: slight rephrasing)

**Comment by danieljohnson2** [comment]
Hmm. I don't have Eddy, but when I install it via dpkg, it appears to be an upgrade, and then apt-upgrade puts it back to 0.5.10.1, but it calls that an downgrade explicitly. So it seems like your basic dpkg/apt stuff understands the versions here correctly.

**Comment by ItsRogueRen** [comment]
Eddy is basically just a GUI for dpkg, I like it more than using the terminal for .deb files

**Comment by danieljohnson2** [comment]
I'm not too sure what you are seeing that seems wrong to you. Can we get a screenie?

**Comment by ItsRogueRen** [comment]
I can in a few hours, I'll update this tonight

**Comment by ItsRogueRen** [comment]
Here is my current Lutris version, and Eddy showing 5.11 as a downgrade rather than an update
![image](https://user-images.githubusercontent.com/75085610/187010071-c91ddbd6-b7ff-495d-8f4e-2c90e7016a80.png)

And here is apt downgrading 5.11 back to 5.10.01 via `sudo apt-get upgrade` after 5.11 has been installed
![image](https://user-images.githubusercontent.com/75085610/187010176-13e2921f-7c99-4c48-8f75-a3d5e1a1dd79.png)

**Comment by danieljohnson2** [comment]
OK, so apt is doing the same thing for you as for me. It wants to reinstall 0.5.10.1 but is clearly calling it out as a "DOWNGRADE" so I think that apt has it right here, or at least doing what it intends to do.

Eddy is offering a "downgrade" button which does not seem right. But that appears to be a known issue with Eddy: donadigo/eddy#104

I've reviewed Eddy's compare_versions function and I find it *highly* bogus, though it is not obvious why I would not detect that "0.5.11" > "0.5.10.1". But:
1. It has an array out of bounds error; Vala does not provide array bounds checks itself.
2. It compares components as strings, so "2" > "10".
3. A patch for this (issue donadigo/eddy#80) tries to fix this, but is just checking length first, so "0001" > "2", and for the last component only.
4. The handling of "~" suffixes doesn't compare the suffixes, only their presence, and overrides all other components.

Eddy does not seem to be seeing any maintenance; last commit was Jan 3 2022, for release 1.3.2- but this was not a fix to the code, just "This release fixes payments not working in the AppCenter". Release 1.3.1 was more substantial on Aug 12 2021; that was the last real progress I see in this repo.

I think Eddy is abandoned and you should find an alternative.
