### ISSUE TITLE
in version 0.5.11 no access to the humble bundle library

### ISSUE THREAD

**Issue by ludo77** [lutris/lutris#4448]
Hello,
I am under Ubuntu 22.04.1, I had the version 0.5.10.XX. I had no more access to the library Humble Bundle. I downloaded the latest version 0.5.11, but I still do not see the access to the library of humble bundle. is this normal?
Thanks for the answer.

**Comment by danieljohnson2** [comment]
Does not sound normal.

What do you see instead of your Humble Bundle library? Is there an error message?

The Lutris debug log might help here. Run "lutris -d" at the command line and post what it outputs here.

**Comment by tiagobugarin** [comment]
Not sure if I am having the same problem. If OP disagrees with mine i'll open another issue.

Arch Linux (up to date as of 20220827 15:00 UTC)
Linux Kernel 5.19.4-arch1-1
Gnome 42
Lutris 0.5.11 (flatpak but also tested with arch community package)
Nvidia Geforce GTX 960M (515.65.01)

What happens: After clicking to connect to the Humble Bundle service the modal web login pops up letting me type my email and password for the service. When I press the "LOG IN" blue button for a very brief moment the spinning wheel shows up and comes back to the email and password screen. No messages appears on the login screen.

Running Lutris with the `-d` option from the command line returns no message at all when connecting to Humble Bundle.

When I tryed to see the console log for that screen the web dev screen would not respond to any clicks so I was not able to read the JS console log.

When trying to access Humble Bundle with Gnome Web (Epiphany) I was able to recreate a situation that looks exactly like the Lutris embedded one by enabling "Smart Tracking Prevention".
This is the console log error at Gnome Web:

```
[Info] Content blocker prevented frame displaying https://www.humblebundle.com/login?hmb_source=navbar&goto=%2F from loading a resource from https://www.mczbf.com/tags/11509/tag.js (login, line 432)
[Info] Content blocker prevented frame displaying https://www.humblebundle.com/login?hmb_source=navbar&goto=%2F from loading a resource from https://connect.facebook.net/en_US/fbevents.js (login, line 461)
[Warning] Unable to track. Missing "offer_id" or "transaction_id" parameter. (everflow.js, line 1)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (processlogin, line 0)
```

Disabling that feature always works for login in to Humble Bundle with Gnome Web.

**Comment by ludo77** [comment]
For the humble bundle library, it does not appear: see the capture.

![lutris bibliotheque](https://user-images.githubusercontent.com/8209508/187033123-51729f4a-1c78-4cc9-aae8-a1471384fa1c.png)

here is the report
[rapport.txt](https://github.com/lutris/lutris/files/9438226/rapport.txt)

**Comment by danieljohnson2** [comment]
So, let's check the obvious: Go into preferences (it's in the hamburger menu in the upper right), click in "Sources" on the left, and check if "Humble Bundle" is turned on here. That is what should make the icon appear in the sidebar.

**Comment by ludo77** [comment]
It's ok. In "Sources" the Humble Bundle is not check. It's solved

**Comment by danieljohnson2** [comment]
Very good.
