### ISSUE TITLE
Flatpaked Steam Not Detected 

### ISSUE THREAD

**Issue by Taza53** [lutris/lutris#4449]
steam is installed(flatpak). I am using lutris(flatpak) and steam is not showing up as a source.
![image](https://user-images.githubusercontent.com/34032665/187029295-c44440ef-6a87-486b-bdfe-5e18af906824.png)
file system permissions seem to be set correctly
![image](https://user-images.githubusercontent.com/34032665/187029366-2339f0fe-2970-4528-91f3-80d8218cc6c6.png)

**Comment by BobbyByrne** [comment]
Also encountered this issue. Tried uninstalling and wiping data on both Lutris and steam, but it still doesn't show. Permissions look correct. 

What's interesting is if I reinstall a game from my lutris profile that is from my Steam library, The game installs instantly and runs without issue. This will only work for games already on my lutris profile. So new games are still not showing.

Running fedora 36, lutris flatpack, steam flatpack
