### ISSUE TITLE
lutris.net unreachable

### ISSUE THREAD

**Issue by cheater** [lutris/lutris#4450]
On my network lutris.net resolves to 188.114.96.12, which is unreachable (via ping or browser or tracert).
This is pretty serious as without this server lutris is pretty much useless.
I'm located in Europe.

**Comment by cheater** [comment]
someone in the irc channel said to ping @strycore

**Comment by strycore** [comment]
Your IP might be blocked in the Cloudflare firewall, please send it to me in private so I can check.

**Comment by cheater** [comment]
Actually, my country just blocked cloudflare for a few days. But it's unblocked now. LOL!
