### ISSUE TITLE
cannot install wrc7,8 through amazon games integration

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [lutris/lutris#4452]
whenever I try installing wrc8 or wrc7 it fails with this error
```
2022-08-27 21:05:25,319: Failed http request https://sds.amazon.com/amazon/
2022-08-27 21:05:25,320: There was an error getting patches: 4ec0904f-79ab-2749-0d57-4ecdeabbea78
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/gui/lutriswindow.py", line 861, in on_game_activated
    game_id = self.service.install(service_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/base.py", line 252, in install
    installer = self.generate_installer(db_game)
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 605, in generate_installer
    file_dict, directories = self.get_game_files(details["id"])
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 544, in get_game_files
    game_patches = self.get_game_patches(game_id, manifest_info["versionId"], hashpairs)
  File "/usr/lib/python3.10/site-packages/lutris/services/amazon.py", line 504, in get_game_patches
    raise UnavailableGame(
lutris.exceptions.UnavailableGame: ('Unable to get the patches of game, please check your Amazon credentials and internet connectivity', '4ec0904f-79ab-2749-0d57-4ecdeabbea78')
```
installing literally any other game works fine however
the normal amazon games launcher works as well

**Comment by ssartell** [comment]
I'm having the exact same issue but with Rain World when attempting to install with the flatpak version of Lutris on Steam Deck.
```
DEBUG    2022-08-29 13:24:37,797 [base.install:230]:Installing 58c0f7ff-5dbb-5c8c-c8e9-09621b4e0bd1 from service ama
zon
DEBUG    2022-08-29 13:24:37,798 [http._request:83]:GET https://lutris.net/api/games/service/amazon
ERROR    2022-08-29 13:24:38,445 [api.get_http_response:99]:Unable to get games from API: HTTP Error 405: Method Not
Allowed
DEBUG    2022-08-29 13:24:38,448 [http._request:83]:POST https://sds.amazon.com/amazon/
DEBUG    2022-08-29 13:24:38,751 [http._request:83]:GET https://client.legacy-app.games.a2z.com/presigned/manifests/
b2ff6f93-467a-407c-b001-aa4334b31990?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220829T182438Z&X-Amz-SignedHeader
s=host&X-Amz-Expires=129600&X-Amz-Credential={redacted}
DEBUG    2022-08-29 13:24:39,641 [http._request:83]:POST https://sds.amazon.com/amazon/
ERROR    2022-08-29 13:24:40,471 [amazon.request_sds:412]:Failed http request https://sds.amazon.com/amazon/
ERROR    2022-08-29 13:24:40,473 [amazon.get_game_patches:503]:There was an error getting patches: 58c0f7ff-5dbb-5c8
c-c8e9-09621b4e0bd1
Traceback (most recent call last):
 File "/app/lib/python3.9/site-packages/lutris/gui/application.py", line 628, in on_game_install
   game_id = service.install(db_game)
 File "/app/lib/python3.9/site-packages/lutris/services/base.py", line 252, in install
   installer = self.generate_installer(db_game)
 File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 605, in generate_installer
   file_dict, directories = self.get_game_files(details["id"])
 File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 544, in get_game_files
   game_patches = self.get_game_patches(game_id, manifest_info["versionId"], hashpairs)
 File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 504, in get_game_patches
   raise UnavailableGame(
lutris.exceptions.UnavailableGame: ('Unable to get the patches of game, please check your Amazon credentials and int
ernet connectivity', '58c0f7ff-5dbb-5c8c-c8e9-09621b4e0bd1')
```

**Comment by Etaash-mathamsetty** [comment]
> I'm having the exact same issue but with Rain World when attempting to install with the flatpak version of Lutris on Steam Deck.
> 
> ```
> DEBUG    2022-08-29 13:24:37,797 [base.install:230]:Installing 58c0f7ff-5dbb-5c8c-c8e9-09621b4e0bd1 from service ama
> zon
> DEBUG    2022-08-29 13:24:37,798 [http._request:83]:GET https://lutris.net/api/games/service/amazon[](https://lutris.net/api/games/service/amazon)
> ERROR    2022-08-29 13:24:38,445 [api.get_http_response:99]:Unable to get games from API: HTTP Error 405: Method Not
> Allowed
> DEBUG    2022-08-29 13:24:38,448 [http._request:83]:POST https://sds.amazon.com/amazon/[](https://sds.amazon.com/amazon/)
> DEBUG    2022-08-29 13:24:38,751 [http._request:83]:GET https://client.legacy-app.games.a2z.com/presigned/manifests/[](https://client.legacy-app.games.a2z.com/presigned/manifests/)
> b2ff6f93-467a-407c-b001-aa4334b31990?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220829T182438Z&X-Amz-SignedHeader
> s=host&X-Amz-Expires=129600&X-Amz-Credential={redacted}
> DEBUG    2022-08-29 13:24:39,641 [http._request:83]:POST https://sds.amazon.com/amazon/[](https://sds.amazon.com/amazon/)
> ERROR    2022-08-29 13:24:40,471 [amazon.request_sds:412]:Failed http request https://sds.amazon.com/amazon/[](https://sds.amazon.com/amazon/)
> ERROR    2022-08-29 13:24:40,473 [amazon.get_game_patches:503]:There was an error getting patches: 58c0f7ff-5dbb-5c8
> c-c8e9-09621b4e0bd1
> Traceback (most recent call last):
>  File "/app/lib/python3.9/site-packages/lutris/gui/application.py", line 628, in on_game_install
>    game_id = service.install(db_game)
>  File "/app/lib/python3.9/site-packages/lutris/services/base.py", line 252, in install
>    installer = self.generate_installer(db_game)
>  File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 605, in generate_installer
>    file_dict, directories = self.get_game_files(details["id"])
>  File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 544, in get_game_files
>    game_patches = self.get_game_patches(game_id, manifest_info["versionId"], hashpairs)
>  File "/app/lib/python3.9/site-packages/lutris/services/amazon.py", line 504, in get_game_patches
>    raise UnavailableGame(
> lutris.exceptions.UnavailableGame: ('Unable to get the patches of game, please check your Amazon credentials and int
> ernet connectivity', '58c0f7ff-5dbb-5c8c-c8e9-09621b4e0bd1')
> ```

you can use the official launcher while this bug gets solved
the official one has been working since wine 7.15 or the latest wine-ge

**Comment by ssartell** [comment]
@Etaash-mathamsetty are you using the official launcher directly with Wine or through Bottles or something else? I tried using it with Bottles on my Steam Deck and I could get the launcher installed, but it crashes after about a minute (wine-ge 7.24).

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty are you using the official launcher directly with Wine or through Bottles or something else? I tried using it with Bottles on my Steam Deck and I could get the launcher installed, but it crashes after about a minute (wine-ge 7.24).

You need wine get 7-25

**Comment by strycore** [comment]
I was able to reproduce and fix this. Please test on the latest master branch.

**Comment by Etaash-mathamsetty** [comment]
this is still broken on lutris-git from the chaotic aur (which has the updated log message, showing the patch is present)
```
2022-11-30 07:07:15,734: Failed http request https://sds.amazon.com/amazon/: HTTP Error 400: Bad Request
2022-11-30 07:07:15,767: There was an error getting patches: 4ec0904f-79ab-2749-0d57-4ecdeabbea78
```

**Comment by strycore** [comment]
Ok, so it seems the Amazon API is returning a 400 response for a different reason for those games.

**Comment by imLinguin** [comment]
The issue is that those titles contain more than 1000 files which is the limit to get from the `GetPatches` request, solution is to just split it to multiple requests. 

See how this function behaves in Nile https://github.com/imLinguin/nile/blob/main/nile/downloading/manager.py#L39

**Comment by danieljohnson2** [comment]
I don't have an Amazon account, but this seems a simple fix, if you are right about this @imLinguin.

Try [my branch here](https://github.com/lutris/lutris/tree/dj/amazonian_batches).

Just download that, run the 'bin/lutris' script, and then try to install 'wrc7' or the like. If this branch works better I'll merge it.

**Comment by imLinguin** [comment]
That seems to do a job, although that game has `19 000` files, running this synchronously takes a while. Also it's save to split it by exactly `1000`

**Comment by danieljohnson2** [comment]
It does "a" job? Which job? Did it do a good job?

I guess it didn't break everything at least. Is there some reason to go for 1000 at a time? Seems like a lot to me; I feel more comfortable with a smaller number. But if it makes a difference...

Getting this onto a worker thread is going to be non-trivial; definitely not a thing for release 0.5.13.

**Comment by imLinguin** [comment]
Yes, manages to generate the patches. Performance of the client is a different story - install page renders a UI element for each file. I think I don't need to add more to that. (more than 19 000 files = more than 19 000 elements)

**Comment by danieljohnson2** [comment]
19000 elements is a lot, but the batch size won't matter for that. I'll merge this puppy.
