### ISSUE TITLE
Yaml problem

### ISSUE THREAD

**Issue by testman42** [lutris/lutris#446]
For me, Lutries does not start due to what appears to be missing dependency.
```[user@localhost ~]$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 47, in <module>
    from lutris.config import check_config  # , register_handler
  File "/usr/lib/python3.5/site-packages/lutris/config.py", line 6, in <module>
    import yaml
ImportError: No module named 'yaml'
```
I'm on Fedora 25 x86_64
`dnf install python-yaml` and `pip install pyyaml` both say that I already have the thing installed.

**Comment by testman42** [comment]
Figured it out.
Due to (I have no idea why) using Python 3.5, I had to download PyYAML from their official site and install it manually using the `python3.5` command instead of normal `python`.

**Comment by strycore** [comment]
uh? there is a PyYAML package in Fedora! 

Also, that reminds me that I have to add Fedora 25 in OBS, you want to use a package, I'm pretty sure that you're missing a bunch of other stuff.

**Comment by strycore** [comment]
And of course OBS doesn't have Fedora 25 yet -_- 

Please use the Fedora 24 repo, it should work just fine.

**Comment by strycore** [comment]
The Fedora 25 package is now available.
