### ISSUE TITLE
"Wait for pre-launch script completion" not respected in 0.5.10.1

### ISSUE THREAD

**Issue by Juppstein** [lutris/lutris#4464]
Tried to use a pre-launch script that starts an application before the game is started. 

pre-launch script line : /home/kodi/Documents/jack/lutris_startrocksmith
"Wait for pre-launch script completion" enabled

The script has a sleep timer of 10 but the game is immediately launched, resulting in an error because the start application from the script is not ready yet. This leads me to believe that "Wait for pre-launch script completion" is not respected in build 0.5.10.1

Running on Ubuntu 22.04 LTS

**Comment by danieljohnson2** [comment]
I tried to repro this but no dice; it seems like it works. Might be an issue with the script- or it might be that the script wasn't run at all.

Could you post the output of 'lutris -d' when you try this? Might be an error message in there with a clue.

**Comment by Juppstein** [comment]
Sure, here's the output: https://pastebin.com/FSvjjuFb

And here's the content of the pre-launch script: 
`#!/bin/bash
steam -nochatui -nofriendsui -silent
sleep 5`

And yes, you are right, it looks like the script is not executed at all. Running it manually works though. Also the post exit script, which is a sleep timer and then a pkill for steam, works within Lutris and when called separately.

**Comment by danieljohnson2** [comment]
That pastebin link says "This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff."

The log output might tell us why it did not run the pre-launch script.

**Comment by Juppstein** [comment]
Strange, happend to me as well just now. Here's the log using another service

https://controlc.com/1fbde9e9

**Comment by danieljohnson2** [comment]
Well, it looks like the error you are getting is:
[Errno 2] No such file or directory: ''

But that just opens another question- why is it trying to open a file with an empty name? Lutris appears to be running '/home/kodi/Documents/jack/lutris_startrocksmith'; and its not obvious how that could be the same as ''. This sounds like issue #3650, but that had no resolution.

But- that issue suggests that the command can launch if "wait for prelaunch" is turned off, and you say the *post* launch script works. Post-launch is done via the MonitoredCommand class, and  so is prelaunch unless you have it wait. If you have it wait, it uses 'system.execute'. So... I think *that* is the trigger for the bug; MonitoredCommand works, system.execute does not work.

But it does work for me. So there's still something missing.

I will look at this some more.

**Comment by danieljohnson2** [comment]
I have an idea. It's using the game directory for the current working directory here, but there's more complex error handling around this in MonitoredCommand.

So, could you look at the Configuration dialog and tell us what the "Directory" is? It's on the first tab. Maybe *that* is the blank.

**Comment by Juppstein** [comment]
Yup, the Directory field is blank.

**Comment by danieljohnson2** [comment]
Bingo! Now I can reproduce the bug.

I've just done a commit (df4046b2b25287b5d1ca1775921b96db44bad9a6) that should help with this. Please try the latest master (you needn't install it- just run the bin/lutris script in it).

If that works, you can work around this by setting the directory on the game (use the Move button to do this).

**Comment by Juppstein** [comment]
Setting the directory allows the pre-launch script to be launched. But the script is somehow not allowed to terminate/exit properly so the application itself can start. It just hangs there until I kill the steam process, then it will try to launch the game but since steam is not there it will complain about the missing API.

> INFO     2022-09-04 12:57:25,663 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-09-04 12:57:25,687 [libretro.get_libretro_cores:24]:No folder at /home/kodi/.local/share/lutris/runners/retroarch/
DEBUG    2022-09-04 12:57:25,693 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-09-04 12:57:25,763 [startup.check_driver:57]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-09-04 12:57:25,763 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 2060
INFO     2022-09-04 12:57:25,763 [startup.check_driver:77]:GPU: 10DE:1E89 1458:3FC1 (nvidia drivers)
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/kodi/.config/MangoHud/python3.10.conf [ not found ]
parsing config: /home/kodi/.config/MangoHud/MangoHud.conf [ ok ]
INFO     2022-09-04 12:57:25,939 [startup.update_runtime:213]:Startup complete
DEBUG    2022-09-04 12:57:26,040 [lutriswindow.update_store:437]:Showing 2 games
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/kodi/.config/MangoHud/python3.10.conf [ not found ]
parsing config: /home/kodi/.config/MangoHud/MangoHud.conf [ ok ]
DEBUG    2022-09-04 12:57:36,461 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR

(lutris:14538): Gtk-WARNING **: 12:57:36.509: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Inhibit”
INFO     2022-09-04 12:57:36,509 [game.start_prelaunch_command:378]:Prelauch command: /home/kodi/Documents/jack/lutris_startrocksmith, waiting for completion
DEBUG    2022-09-04 12:57:36,509 [system.execute:56]:Executing /home/kodi/Documents/jack/lutris_startrocksmith
DEBUG    2022-09-04 12:57:36,510 [system.execute:62]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=/home/kodi/.steam/steam/steamapps/common/Rocksmith2014 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json LD_LIBRARY_PATH=/home/kodi/.steam/steam/compatibilitytools.d/GE-Proton7-30/files/lib:/home/kodi/.steam/steam/compatibilitytools.d/GE-Proton7-30/files/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib32:/lib:/usr/local/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/kodi/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/kodi/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/kodi/.local/share/lutris/runtime/steam/i386/lib:/home/kodi/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/kodi/.local/share/lutris/runtime/steam/i386/usr/lib:/home/kodi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/kodi/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/kodi/.local/share/lutris/runtime/steam/amd64/lib:/home/kodi/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/kodi/.local/share/lutris/runtime/steam/amd64/usr/lib WINEDEBUG=-all DXVK_LOG_LEVEL=none WINEARCH=win64 WINE=/home/kodi/.steam/steam/compatibilitytools.d/GE-Proton7-30/files/bin/wine WINE_MONO_CACHE_DIR=/home/kodi/.local/share/lutris/runners/wine/custom/mono WINE_GECKO_CACHE_DIR=/home/kodi/.local/share/lutris/runners/wine/custom/gecko WINEPREFIX=/home/kodi/.steam/steam/steamapps/compatdata/221680/pfx WINEESYNC=0 WINEFSYNC=0 WINE_FULLSCREEN_FSR=1 DXVK_NVAPIHACK=0 DXVK_ENABLE_NVAPI=1 PROTON_BATTLEYE_RUNTIME=/home/kodi/.local/share/lutris/runtime/battleye_runtime PROTON_EAC_RUNTIME=/home/kodi/.local/share/lutris/runtime/eac_runtime WINEDLLOVERRIDES=d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder= WINE_LARGE_ADDRESS_AWARE=1 game_name=RS 2014 Lutris

And the long I wait the more instances of Steam it seem to open so it looks like it is repeatingly executing the pre-launch script over and over. Waiting for 40 seconds resulted in 4 open steam instances in task manager (given my script has a 10 second sleep timer in it)

**Comment by Juppstein** [comment]
Just for kicks downloaded from master again and the pre script now works as intended, so YAY! No clue what went wrong the first time. What I can see now is that the post script seems to be running ad infinitum as "lutris-wrapper: /path-to-post-script"
That's not normal, no?

**Comment by danieljohnson2** [comment]
That is very odd, but perhaps the post-script itself has hung. Is there also a process hanging around for it, apart from the lutris-wrapper?

**Comment by Juppstein** [comment]
Nope, not that I see

![Screenshot_2022-09-05_10-59-04](https://user-images.githubusercontent.com/8590930/188410891-8d50e7db-ec78-4788-b4f1-53faebe4dae4.png)

**Comment by strycore** [comment]
Fixed a long time ago...
