### ISSUE TITLE
Origin install hangs during login sequence

### ISSUE THREAD

**Issue by cheater** [lutris/lutris#4467]
When installing Origin, the step when you log in hangs, because Origin hangs around in the system tray. You have to quit it from the sys tray and then the installation can continue. It would be nice if the installer displayed information that you should quit Origin from the system tray.

**Comment by mbaran5** [comment]
Thanks. Ran into the same issue, this helped.

**Comment by strycore** [comment]
Origin is no more and EA App should install properly on our current Wine default version.

I noticed that the EA App wouldn't succeed if my Nvidia GPU was bound to VFIO drivers and only completes when I bind it back to the nvidia drivers.
