### ISSUE TITLE
Add lutris games as non-steam games

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#447]
Apparently this project can do it and so should we: https://github.com/sirnuke/steamfootbridge

**Comment by RobLoach** [comment]
How would this work?

**Comment by testman42** [comment]
If I understand correctly, strycore suggests that for example OpenArena, installed trough Lutris, would also appear in your Steam library as non-steam game.
In Steam you can add non-Steam games by pressing "+ ADD A GAME..." in the bottom left corner.

However, I do not see why you would want to (unnecessarily) duplicate the game-launching functionality into multiple game-hub clients.

**Comment by strycore** [comment]
That's exactly it @testman42, I wouldn't used the feature myself but quite a few people are asking for it.

Also, I'll leave this here so I remember to read the source code: https://github.com/scottrice/Ice

**Comment by mdeguzis** [comment]
I believe the core piece of Ice that does this is pysteam, namely within [_shortcut_generator.py](https://github.com/scottrice/pysteam/blob/master/pysteam/_shortcut_generator.py). Check into that as well.

https://github.com/scottrice/pysteam

**Comment by 8BitCerberus** [comment]
> However, I do not see why you would want to (unnecessarily) duplicate the game-launching functionality into multiple game-hub clients.

Resurrecting this old thread instead of duplicating a feature request. But one good reason for having the duplicate launching is people who use Steam's in-home streaming either from client to client or using a Steam Link.

Another reason would be for people who use a Steam Controller or use Steam to manage their other/3rd party controller configurations. Launching from Steam gets you access to the overlay so you can manage the configuration. sc-controller can work in many situations, but it's not as fully featured as Steam's own configuration utility.

Fortunately Lutris makes it fairly easy to add individual games as non-Steam games by exporting a .desktop file that we can add to Steam manually. But it would be super convenient to have it directly in Lutris both on a per-game basis, and as a one shot "add all to Steam" option.

**Comment by RobLoach** [comment]
Automatically add shortcuts to all non-Steam Lutris games in Steam... That'd be cool.

Here's how to do it manually:
https://github.com/lutris/lutris/wiki#steam

**Comment by buxel** [comment]
For the poeple coming here from google: some time ago i created [a script](https://gist.github.com/buxel/fa710969bbc650447d924cf8f7d15204) for personal use to do this. Feel free to take & adopt it. 
- can be run multiple times without creating duplicates (using tag/category as identifier)
- uses 'lutris lutris:rungame/{slug}' as target
- adds icons & banners (pixelated, tough)

@strycore if there is a good place integrate this into lutris, tell me and I'll give it a try. My last PR went stale qickly so i'd rather ask first.

**Comment by strycore** [comment]
@buxel we don't have a dependency on the vdf python module so this is basically unusable for us.

**Comment by buxel** [comment]
Too bad. i guess the reason is because you are strictly managing your external dependencies, right?

The groundwork was done [here](https://github.com/CorporalQuesadilla/Steam-Shortcut-Manager/wiki/Steam-Shortcuts-Documentation), so working around the vdf dependency could be possible.

**Comment by strycore** [comment]
We can only depend on python packages that are widely available in all supported Linux distributions, I wouldn't expect this vdf package to be distributed anywhere.
Plus we already have code to read/write vdf files in lutris, we don't need an extra project. If there are missing features in our vdf code, that can be added very simply.

**Comment by buxel** [comment]
I wasn't aware of that when writing this script. I'm still wondering _where_ in Lutris would be a good place for such a feature. Any opinion on that?

**Comment by strycore** [comment]
Not really a big deal, code can be refactored and moved around.
I'd say somewhere in lutris/util/steam would be a good place to start.

**Comment by buxel** [comment]
It looks like the `vdf` util in lutris cannot manage the odd binary-looking vdf format described in the groundwork i linked previously.

**Comment by strycore** [comment]
looks like the code from the vdf package in Pypi can easily be vendorized into Lutris.

**Comment by buxel** [comment]
I'm not sure if i "vendorized" it properly, but i created a WIP PR for this.
