### ISSUE TITLE
Can't use Epic Games Store as source

### ISSUE THREAD

**Issue by baioc** [lutris/lutris#4472]
Lutris no longer lists games from the Epic Games Store.
In fact, after disconnecting, further attempts to reconnect to an Epic Games account from Lutris don't seem to do anything: after logging in, the authentication window closes and nothing else happens.

Seen on:
- Lutris version: 0.5.10.1
- OS,DE: Pop!_OS 22.04, Gnome 42.3.1

Edit: [Somebody else has also reported this issue on the forums](https://forums.lutris.net/t/cant-connect-epic-games-as-source/16118).

**Comment by madpipeline** [comment]
Having the same symptoms. I've tried starting lutris from the CLI to get some logs and here's what I've got:

```
$ lutris 
2022-09-02 08:55:44,068: Command /usr/sbin/lspci after 3 seconds
Gtk-Message: 08:55:44.652: Failed to load module "appmenu-gtk-module"
2022-09-02 08:55:44,654: Starting Lutris 0.5.10.1
2022-09-02 08:55:44,692: No folder at /home/XXX/.local/share/lutris/runners/retroarch/
2022-09-02 08:55:45,669: Running Intel Mesa driver 21.1.8 on Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x191b)
2022-09-02 08:55:45,670: GPU: 8086:191B 1028:06E0 (i915 drivers)
2022-09-02 08:55:45,671: GPU: 1002:682B 1028:06E0 (radeon drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2022-09-02 08:55:45,788: Startup complete

(lutris:358982): GLib-GIO-CRITICAL **: 08:55:46.061: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
2022-09-02 08:55:51,833: EGS Token expired
2022-09-02 08:55:51,842: Error while completing task <bound method BaseService.reload of <egs.EpicGamesStoreService object at 0x7fdedddceb40 (lutris+services+egs+EpicGamesStoreService at 0x558a74343e40)>>: <class 'lutris.services.base.AuthTokenExpired'> 
  File "/usr/lib/python3.9/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/lutris/services/base.py", line 96, in reload
    self.load()
  File "/usr/lib/python3.9/site-packages/lutris/services/egs.py", line 323, in load
    raise AuthTokenExpired from ex
Gtk-Message: 08:55:52.142: Failed to load module "appmenu-gtk-module"
https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect:1:164: CONSOLE RENDERING ERROR Viewport argument key "minimal-ui" not recognized and ignored.
https://www.epicgames.com/id/api/redirect:1:1: CONSOLE SECURITY ERROR Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.
2022-09-02 08:56:13,686: Failed to connec to EGS (Status 401): {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': 'f3b2b110-2a83-11ed-b1fa-b750a595f1e8'}
```
My system:
Fedora 34 KDE, 64 bit. Installed Lutris with `dnf` as instructed on the Lutris downloads page for Fedora.
These logs are the third start-up of Lutris. Each start-up I've had an attempt at logging into Epic Games.

**Comment by SourceCodeDeleted** [comment]
I am experiencing the same issue and it seems to be related from this recent update.

**Comment by PalmTamino** [comment]
Same issue here! I would appreciate a hotfix

**Comment by ArchKubi** [comment]
2022-09-03 20:16:54,945: Failed to connec to EGS (Status 401): {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': '355beea0-2bac-11ed-93a2-55f96b50b917'}

**Comment by SourceCodeDeleted** [comment]
I am not familiar with the code . To me it seems that this process is handled in python. I could be completely wrong though. 

Looking at the code there it seems URLS need to be updated at least. I have a feeling though that the egs.py is just prototyping and not really apart of the lutris program.

Can anyone provide details?

**Comment by minimeee** [comment]
It seems that this issue has already been fixed in the ["legendary" launcher](https://github.com/derrod/legendary/issues/468). The relevant commits there could be helpful:

* https://github.com/derrod/legendary/commit/5a20f1246187bb17eee84971b6bd4b515fe63494
* https://github.com/derrod/legendary/commit/b13674816826163d76537a7933b31d2bebc3ac5b

**Comment by SourceCodeDeleted** [comment]
> It seems that this issue has already been fixed in the ["legendary" launcher](https://github.com/derrod/legendary/issues/468). The relevant commits there could be helpful:
> 
> * [derrod/legendary@5a20f12](https://github.com/derrod/legendary/commit/5a20f1246187bb17eee84971b6bd4b515fe63494)
> * [derrod/legendary@b136748](https://github.com/derrod/legendary/commit/b13674816826163d76537a7933b31d2bebc3ac5b)

yeah it looks like this is a fix and the code appears to be exact. So a copy paste/ cherry pick maybe might be enough.

**Comment by kekkodance** [comment]
same issue here. hope for a fix soon?

**Comment by DisarmedSpy** [comment]
Hopefully there's a fix soon but as of this comment it has yet to be fixed. :(

**Comment by JustAFriendlyCat** [comment]
Same issue :/ let's hope for a fix soon.

**Comment by All3xJ** [comment]
lutris version: 0.5.10.1

I can't log in to Epic Games Store with Steam Account authentication. When I try to login to Epic Games Store and the login popup appears and I select Steam and then put credentials, I receive these errors:
https://www.epicgames.com/id/oauth-authorized?state=eyJpZCI6IjFlYTIyYjhlYWQ1ODRiNDNiMTUyNGRiNzEzZWQ4N2UxIn0=&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198076854056&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198076854056&openid.return_to=https%3A%2F%2Faccounts.epicgames.com%2FOAuthAuthorized%3Fstate%3DeyJpZCI6IjFlYTIyYjhlYWQ1ODRiNDNiMTUyNGRiNzEzZWQ4N2UxIn0%3D&openid.response_nonce=2022-09-09T06%3A57%3A09Z6GXVjqv16GNj8LkuKrHYMNznGUs%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=twR%2Fr%2ByyuhFZ4cTcRGc0O%2FBac7U%3D:1:164: CONSOLE RENDERING ERROR Viewport argument key "minimal-ui" not recognized and ignored.

(process:90102): GLib-GIO-CRITICAL **: 08:57:12.628: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed

(process:90102): GLib-GIO-CRITICAL **: 08:57:12.628: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed

(process:90102): GLib-GIO-CRITICAL **: 08:57:12.628: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed

(process:90102): GLib-GIO-CRITICAL **: 08:57:12.628: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed

(process:90102): GLib-GIO-CRITICAL **: 08:57:12.628: g_task_get_cancellable: assertion 'G_IS_TASK (task)' failed
https://static-assets-prod.unrealengine.com/account-portal/static/static/js/main.fe87b475.chunk.js:1:235937: CONSOLE ERROR TypeError: null is not an object (evaluating 'localStorage.getItem')
https://static-assets-prod.unrealengine.com/account-portal/static/static/js/main.fe87b475.chunk.js:1:484560: CONSOLE ERROR [object Object]
https://www.epicgames.com/id/login/steam?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Fid%2Fapi%2Fredirect&prompt=&extLoginState=_VERYLONGSTRINGTHATIAMNOTPUTTINGHERE_: CONSOLE RENDERING ERROR Viewport argument key "minimal-ui" not recognized and ignored.
https://www.epicgames.com/id/api/redirect:1:1: CONSOLE SECURITY ERROR Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.
2022-09-09 08:57:18,442: Failed to connec to EGS (Status 401): {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': '_STRINGWITHNUMBERSANDLETTERS_'}

**Comment by TobiPeterG** [comment]
I have the same issue using the flatpak version on the steam deck, heroic published a fix today

**Comment by danieljohnson2** [comment]
It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.

You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.

**Comment by SourceCodeDeleted** [comment]
> It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.
> 
> You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.


Yes this fixes it . Literally all you need to do is replace the egs.py file with this 

https://github.com/Relms12345/lutris/blob/d350cd7d29c79acaeddfa846dbd118c5385141a4/lutris/services/egs.py

A merge request should be the proper fix for this though.

**Comment by ArchKubi** [comment]
ı can't find lutris/lutris/services/ this place

**Comment by SourceCodeDeleted** [comment]
Check your cloned repository - _<project_root>/lutris/services/egs.py_ since it isn't in the main branch you wont see it on your machine in that directory .

**Comment by ArchKubi** [comment]
cloned repository what ? ı just install lutris in arch linux

**Comment by SourceCodeDeleted** [comment]
At this point this is already off topic for this issue. You appear to be a standard user and will need to wait until an official fix is pushed out.

**Comment by fl0uf** [comment]
The workaround works fine ! Thanks :)

**Comment by zombiebungle** [comment]
> > It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.
> > You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.
> 
> Yes this fixes it . Literally all you need to do is replace the egs.py in lutris/lutris/services/ file with this
> 
> https://github.com/Relms12345/lutris/blob/d350cd7d29c79acaeddfa846dbd118c5385141a4/lutris/services/egs.py
> 
> A merge request should be the proper fix for this though.



> > It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.
> > You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.
> 
> Yes this fixes it . Literally all you need to do is replace the egs.py in lutris/lutris/services/ file with this
> 
> https://github.com/Relms12345/lutris/blob/d350cd7d29c79acaeddfa846dbd118c5385141a4/lutris/services/egs.py
> 
> A merge request should be the proper fix for this though.

your link no longer works. could you add this again please?

**Comment by Relms12345** [comment]
@zombiebungle apologies I deleted the fork haha. Here's the fix ^^ https://raw.githubusercontent.com/lutris/lutris/31803ed04ff2d42fbc4fcce540798db44065be21/lutris/services/egs.py

**Comment by zombiebungle** [comment]
> > It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.
> > You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.
> 
> Yes this fixes it . Literally all you need to do is replace the egs.py in lutris/lutris/services/ file with this
> 
> https://github.com/Relms12345/lutris/blob/d350cd7d29c79acaeddfa846dbd118c5385141a4/lutris/services/egs.py
> 
> A merge request should be the proper fix for this though.



> > It'd be helpful if people having this issue could try out @Relms12345 PR to see if it works for you.
> > You do not need to install it; download [his branch](https://github.com/Relms12345/lutris/tree/fix/egs) and run the bin/lutris within.
> 
> Yes this fixes it . Literally all you need to do is replace the egs.py in lutris/lutris/services/ file with this
> 
> https://github.com/Relms12345/lutris/blob/d350cd7d29c79acaeddfa846dbd118c5385141a4/lutris/services/egs.py
> 
> A merge request should be the proper fix for this though.

your link no longer works. could you add this again please?

> 
thanks for this but just realised i dont have a clue how to use it. thanks anyway

**Comment by nettnikl** [comment]
Hey @zombiebungle!
It depends on your system, of course. But for this error, for example:
```
  File "/usr/lib/python3.10/site-packages/lutris/services/egs.py", line 307, in load
    raise AuthTokenExpired from ex
```

Those commands work for me:
```
wget https://raw.githubusercontent.com/lutris/lutris/31803ed04ff2d42fbc4fcce540798db44065be21/lutris/services/egs.py
sudo mv egs.py /usr/lib/python3.10/site-packages/lutris/services/egs.py
sudo chown root: /usr/lib/python3.10/site-packages/lutris/services/egs.py
```

**Comment by phlepper** [comment]
Thanks @nettnikl that worked for me. 

For anyone else looking, on my system (I'm using the flatpak version of Lutris), that egs.py file is in:

```
~/.local/share/flatpak/app/net.lutris.Lutris/x86_64/stable/46f4d8bdde456e6f056b02cb78221837ddbee9f6db8a8b1efe6842299d424ca0/files/lib/python3.9/site-packages/lutris/services
```

Paul

**Comment by minimeee** [comment]
Now that Epic authentication has finally been fixed, it's time to release a new [flatpak](https://github.com/flathub/net.lutris.Lutris) version, which is what most Steam Deck owners are using. The latest one is two months old...

**Comment by mm47** [comment]
> ```
> wget https://raw.githubusercontent.com/lutris/lutris/31803ed04ff2d42fbc4fcce540798db44065be21/lutris/services/egs.py
> sudo mv egs.py /usr/lib/python3.10/site-packages/lutris/services/egs.py
> sudo chown root: /usr/lib/python3.10/site-packages/lutris/services/egs.py
> ```

I did this (just had to change python3.10 to python3 and site-packages to dist-packages), copied the file just fine, no problems. But it didn't work. Epic asks for authentication, I log in, but then it closes and nothing happens. There's a loading icon next to "Epic Game Store", but it loads forever and nothing happens.

I'm on Linux Mint 20.3 with Lutris 0.5.10

**Comment by nettnikl** [comment]
> > ```
> > wget https://raw.githubusercontent.com/lutris/lutris/31803ed04ff2d42fbc4fcce540798db44065be21/lutris/services/egs.py
> > sudo mv egs.py /usr/lib/python3.10/site-packages/lutris/services/egs.py
> > sudo chown root: /usr/lib/python3.10/site-packages/lutris/services/egs.py
> > ```
> 
> I did this (just had to change python3.10 to python3 and site-packages to dist-packages), copied the file just fine, no problems. But it didn't work. Epic asks for authentication, I log in, but then it closes and nothing happens. There's a loading icon next to "Epic Game Store", but it loads forever and nothing happens.
> 
> I'm on Linux Mint 20.3 with Lutris 0.5.10

You took the file path from the error message? And you did restart Lutris afterwards? You could verify the version you are using has been successfully copied to the path you see in the error message.

If it doesn't help, it sounds like you have a different issue.

**Comment by danieljohnson2** [comment]
I have contacted @strycore about this, and he's amenable to a Lutris release "soon". Hopefully, you won't have to wait too much longer to get this fix properly.

**Comment by mm47** [comment]
> > > ```
> > > wget https://raw.githubusercontent.com/lutris/lutris/31803ed04ff2d42fbc4fcce540798db44065be21/lutris/services/egs.py
> > > sudo mv egs.py /usr/lib/python3.10/site-packages/lutris/services/egs.py
> > > sudo chown root: /usr/lib/python3.10/site-packages/lutris/services/egs.py
> > > ```
> > 
> > 
> > I did this (just had to change python3.10 to python3 and site-packages to dist-packages), copied the file just fine, no problems. But it didn't work. Epic asks for authentication, I log in, but then it closes and nothing happens. There's a loading icon next to "Epic Game Store", but it loads forever and nothing happens.
> > I'm on Linux Mint 20.3 with Lutris 0.5.10
> 
> You took the file path from the error message? And you did restart Lutris afterwards? You could verify the version you are using has been successfully copied to the path you see in the error message.
> 
> If it doesn't help, it sounds like you have a different issue.

There was no error message. It was copied, it was in the folder. I restarted Lutris, nothing happened.

**Comment by LeXofLeviafan** [comment]
Just tried out the [patched pre-release](https://github.com/lutris/lutris/tree/v0.5.12-beta1).

In the stable version (0.5.11), when trying to log into EGS via Steam (picking "Sign in with Steam" in the login dialog), the appropriate Steam page is shown and I'm able to log in; the only part that doesn't seem to work is retaining that login after the window is closed.

In the patched version, after I click "Sign in with Steam", what I get is an empty dialog with "Loading…" in the window title; nothing happens after that, and closing the dialog results in a crash (the only thing printed out in the terminal is "Segmentation fault"). The same thing happens if I choose Nintendo, PSN, Xbox, Google, or Facebook; so the only options that don't have this issue are Epic and Apple.

…Oh, and when I reopen Lutris after the crash, EGS source is mislabelled as connected (i.e. it has reload/disconnect buttons).

**Comment by distante** [comment]
Does anyone knows what do I need to edit this file on a steam deck? KFind finds it inside `./steamos` but as read only. I already put a password to the deck so I can use `sudo` but I can not find `./steamos` on the terminal...

Thank you!

**Comment by minimeee** [comment]
If by "this file" you mean `egs.py`, you can locate it with this command in the terminal:
```
find /var/lib/flatpak/ -name "egs.py"
```

**Comment by distante** [comment]
> @distante: If by "this file" you mean `egs.py`, you can locate it with this command in the terminal:
> 
> ```
> find /var/lib/flatpak/ -name "egs.py"
> ```

thanks!

**Comment by junglized** [comment]
I'm trying to log in into Epic Game Store and Lutris prompts me to install EGS with Wine. Is it normal behaviour?

**Comment by strycore** [comment]
> I'm trying to log in into Epic Game Store and Lutris prompts me to install EGS with Wine. Is it normal behaviour?

yes

**Comment by canepan** [comment]
I am unable to login to the Epic Game Store, neither.
When I try, with the epic email/password, the windows becomes unresponsive, if I move it it's all white, and I need to close it via the window "x" button.
I am running PopOs with `lutris-.5.12~1671557885~22.04~d624bd3` (latest available)

After replacing `/usr/lib/python3/dist-packages/lutris/services/egs.py` with the one linked in this thread, nothing changes.
Debug logs with the new egs.py  as follows (nothing useful imho):
```
INFO     2023-04-15 11:26:06,961 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-04-15 11:26:07,330 [startup.check_driver:65]:Running X.Org Mesa driver 22.3.5 on AMD RV630 (DRM 2.50.0 / 6.1.11-76060111-generic, LLVM 15.0.6) (0x9583)
INFO     2023-04-15 11:26:07,330 [startup.check_driver:77]:GPU: 1002:9583 106B:0083 (radeon drivers)
DEBUG    2023-04-15 11:26:08,945 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-04-15 11:26:09,197 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-04-15 11:26:14,744 [base.wipe_game_cache:343]:Deleting egs cache /home/nicola/.cache/lutris/egs-library.json
DEBUG    2023-04-15 11:26:14,745 [base.wipe_game_cache:156]:Deleting games from service-games for egs
WARNING  2023-04-15 11:26:14,747 [egs.load:306]:EGS Token expired
DEBUG    2023-04-15 11:26:14,751 [lutriswindow.update_store:448]:Showing 0 games
ERROR    2023-04-15 11:26:14,752 [jobs.target:36]:Error while completing task <bound method BaseService.reload of <egs.EpicGamesStoreService object at 0x7f20a812ca40 (lutris+services+egs+EpicGamesStoreService at 0x564eb0d38a60)>>: <class 'lutris.services.base.AuthTokenExpired'> 
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 131, in reload
    self.load()
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 307, in load
    raise AuthTokenExpired from ex
DEBUG    2023-04-15 11:26:14,888 [base.wipe_game_cache:343]:Deleting egs cache /home/nicola/.cache/lutris/egs-library.json
DEBUG    2023-04-15 11:26:14,890 [base.wipe_game_cache:156]:Deleting games from service-games for egs
DEBUG    2023-04-15 11:26:14,891 [base.logout:358]:logged out from egs
DEBUG    2023-04-15 11:26:14,895 [lutriswindow.update_store:448]:Showing 0 games
DEBUG    2023-04-15 11:26:14,963 [base.login:332]:Connecting to Epic Games Store
```

**Comment by mrwensveen** [comment]
`When I try, with the epic email/password, the windows becomes unresponsive, if I move it it's all white, and I need to close it via the window "x" button.`

I have the same issue, unfortunately.

**Comment by judastadeo** [comment]
sigue el problema con epic store

**Comment by Johner97** [comment]
I use steam and epic games. Both platforms are good. But I can't say which is better. [This post](https://gamerseo.com/blog/epic-games-vs-steam-which-is-the-best-gaming-store/) compares these platforms well.

**Comment by Nobody1707** [comment]
I'm having the same problem with the OpenSUSE Tumbleweed Lutris package. Using KDE5 with Wayland.

```txt
2023-08-03 10:32:54,639: Starting Lutris 0.5.13
2023-08-03 10:32:54,641: Running AMD Mesa driver 23.1.4 on AMD Radeon RX 5700 (navi10, LLVM 16.0.6, DRM 3.52, 6.4.6-1-default) (0x731f)
2023-08-03 10:32:54,641: GPU: 1002:731F 1849:5102 (amdgpu drivers)
2023-08-03 10:32:56,858: EGS Token expired
2023-08-03 10:32:56,859: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f19c7af3d80>: <class 'lutris.services.base.AuthTokenExpired'>
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/services/base.py", line 141, in do_reload
    self.load()
  File "/usr/lib/python3.11/site-packages/lutris/services/egs.py", line 310, in load
    raise AuthTokenExpired from ex

(lutris:2812): Gdk-CRITICAL **: 10:32:56.903: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed

(lutris:2812): Gdk-CRITICAL **: 10:32:59.455: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
[1]    2812 segmentation fault (core dumped)  lutris
```

**Comment by AbdulRhmanHS** [comment]
I can log in to Epic Games Store but, Lutris doesn't list any game in the store like in Steam and Ubisoft.
I replaced the egs.py file with the new one but it doesn't fix the issue.

**Comment by guareber** [comment]
Problem still exists on v0.5.14 installed through flatpack on SteamDeck
