### ISSUE TITLE
Ampersand ("&") in game titles replaced with "&amp;"

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#4473]
It doesn't happen consistently, and sometimes it fixes itself by just switching to another view and then coming back, but sometimes ampersands get replaced with "&amp;".

This seems to happen when adding a new game, or when interacting (launching or stopping) with a game with an ampersand in its title.
![Screenshot from 2022-09-02 17-12-41](https://user-images.githubusercontent.com/10992973/188168124-2c5f76a7-3ac9-4a77-9d64-84d975a339c7.png)

**Comment by danieljohnson2** [comment]
I see it. It's quite simple; Lutris must escape & to &amp; for GTKs benefit, but the code is duplicated in one place. It's actually generating &amp;amp; with hilarious results.

I've removed the duplication, and it should now be fixed.

**Comment by hazelnot** [comment]
Even more hilariously, the email I received with your reply displayed it like "It's actually generating &amp;&amp; with hilarious results."

**Comment by danieljohnson2** [comment]
I have no idea how it managed that! But I've fixed my comment to escape *harder* so maybe it'll rendered better on the website.
