### ISSUE TITLE
Resolution problem with League of Legends [Intel HD4000]

### ISSUE THREAD

**Issue by abderrahmanebenhalima** [lutris/lutris#4474]
i've a weird problem with resolution in-game League of Legends , my native screen resolution is 1366x768 but the max ingame resolution is 1360x768 ,i know it's a slight different but very noticeable with blur. 
any solution ?

**Comment by strycore** [comment]
Maybe try running the game in a virtual desktop? 
I would have suggested Gamescope but that's not going to work well on a HD4000.

The issue might also be fixed in the latest build for LoL
