### ISSUE TITLE
Flatpak Lutris needs additional read-only permission to be able to read MangoHud config

### ISSUE THREAD

**Issue by ak-42** [lutris/lutris#4476]
Hi. If you install Lutris and MangoHud (`org.freedesktop.Platform.VulkanLayer.MangoHud`), both from Flathub, you can enable it in Lutris' configurations as expected, but MangoHud does not respect the config file found in `xdg-config/MangoHud` the same way that non-Flatpak MangoHud does; presumably because it cannot read it. 

The solution is to execute `flatpak override --user --filesystem=xdg-config/MangoHud:ro net.lutris.Lutris`.

It'd be helpful if this permission was included so that no manual intervention is necessary.

**Comment by NoxInmortus** [comment]
Hi, using both lutris and MangoHud 21.08 on Flatpak, but canno't make MangoHud to work even with flatpak override command. Does anyone have any more details ?

**Comment by strycore** [comment]
I added the permission here https://github.com/flathub/net.lutris.Lutris/commit/fd0fac08e737a9a00a94e135efc72d62a2e8bc06
It will be in the next release unless Flathub says no.
