### ISSUE TITLE
Wine shortcuts still being created during game installs

### ISSUE THREAD

**Issue by KotoWhiskas** [lutris/lutris#4485]
For example, when installing hearthstone from battle.net, it will create a game shortcut, but eventually this shortcut opens neither by lutris nor the current lutris runner, it will use the correct wine prefix but wrong runner

**Comment by Juppstein** [comment]
Can confirm. Just had a look and saw an entry for Ubisoft Connect and Rocksmith+ in there, which were installed via Lutris script. They use another wine version than what is installed on my system (winehq-staging)

Application command line:
> env WINEPREFIX="/data/lutris/games/ubisoft-connect" wine C:\\users\\kodi\\AppData\\Roaming\\Microsoft\\Windows\\Start\ Menu\\Programs\\Ubisoft\\Ubisoft\ Connect\\Ubisoft\ Connect.lnk

Working directory:
> /data/lutris/games/ubisoft-connect/dosdevices/c:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher

**Comment by strycore** [comment]
Wine shortcuts should not be created, this is an issue with winemenubuilder not being disabled at all times. (It was supposed to be disabled from Wine builds). The only shortcuts that should be coming from Lutris are the ones manually created by the user in the UI.

**Comment by strycore** [comment]
I don't believe this is valid anymore. We've had winemenubuilder disabled for a long long time.
