### ISSUE TITLE
[return code: 32512] can't play any wine games after updating fmt.

### ISSUE THREAD

**Issue by zimakkkk** [lutris/lutris#4486]
```
Start monitoring process.
env: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```
after updating fmt to  9.1 i dont have the libfmt.so.8 anymore so nothing starts. and i can't downgrade because it breaks some packages. is there a fix?

**Comment by ritlew** [comment]
Having the same issue

**Comment by ritlew** [comment]
Issue went away when I disabled mangohud

**Comment by ritlew** [comment]
Reinstalling mangohud resolved the issue
```
yay -S mangohud --rebuild --rebuildtree
```

**Comment by zimakkkk** [comment]
> Reinstalling mangohud resolved the issue https://github.com/flightlessmango/MangoHud/issues/832
> Arch:
> ```
> yay -S mangohud --rebuild --rebuildtree
> ```

Thanks for the reply but i already figured it out 👍
