### ISSUE TITLE
Crash when trying to refresh Steam games

### ISSUE THREAD

**Issue by Victor239** [lutris/lutris#4493]
Clicking the refresh button spins for a few seconds, then crashes Lutris. Command line logs below:

<details>
  <summary>Logs</summary>
  
$ lutris
2022-09-09 09:28:57,297: Starting Lutris 0.5.10.1
2022-09-09 09:28:57,384: Running Intel Mesa driver 22.1.7 on Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
2022-09-09 09:28:57,384: GPU: 8086:3EA0 1028:08AF (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
2022-09-09 09:28:57,433: Startup complete
2022-09-09 09:29:09,905: Failed to download http://cdn.akamai.steamstatic.com/steam/apps/397080/capsule_184x69.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,036: Failed to download http://cdn.akamai.steamstatic.com/steam/apps/596350/capsule_184x69.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,472: Failed to download https://cdn.cloudflare.steamstatic.com/steam/apps/596350/header.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,472: Failed to download https://cdn.cloudflare.steamstatic.com/steam/apps/397080/header.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,864: Failed to download http://cdn.steamstatic.com/steam/apps/485000/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,864: Failed to download http://cdn.steamstatic.com/steam/apps/407530/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,865: Failed to download http://cdn.steamstatic.com/steam/apps/399820/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,880: Failed to download http://cdn.steamstatic.com/steam/apps/311730/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:10,880: Failed to download http://cdn.steamstatic.com/steam/apps/397080/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,183: Failed to download http://cdn.steamstatic.com/steam/apps/1083500/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,183: Failed to download http://cdn.steamstatic.com/steam/apps/543870/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,184: Failed to download http://cdn.steamstatic.com/steam/apps/596350/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,184: Failed to download http://cdn.steamstatic.com/steam/apps/207490/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,312: Failed to download http://cdn.steamstatic.com/steam/apps/242550/library_600x900.jpg: HTTP Error 404: Not Found
2022-09-09 09:29:11,501: Failed to download http://cdn.steamstatic.com/steam/apps/616560/library_600x900.jpg: HTTP Error 404: Not Found

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.175: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: g_value_type_compatible: assertion 'src_type' failed
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'pixbuf' of type 'GdkPixbuf' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.176: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.177: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-WARNING **: 09:29:12.177: lutris+gui+views+grid+GameGridView 0x55e1c9c042f0 reported min size 18 and natural size 6 in get_preferred_width(); natural size must be >= min size

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-WARNING **: 09:29:12.382: Failed to set text from markup due to error parsing markup: Error on line 1 char 15: Invalid UTF-8 encoded text in name — not valid “.%\xb1\u001e,\u007f”

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.382: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'markup' of type 'gchararray' from value of type '(null)'
  return Gio.Application.run(self, *args, **kwargs)

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.383: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.568: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.568: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.568: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.568: gtk_tree_path_to_string: assertion 'path != NULL' failed
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: g_sequence_get: assertion '!is_end (iter)' failed
  return Gio.Application.run(self, *args, **kwargs)

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_tree_path_to_string: assertion 'path != NULL' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed

(lutris:1026594): Gtk-CRITICAL **: 09:29:12.569: gtk_tree_path_to_string: assertion 'path != NULL' failed
**
Gtk:ERROR:../../../../gtk/gtkiconview.c:1511:gtk_icon_view_get_preferred_item_size: assertion failed: (!gtk_icon_view_is_empty (icon_view))
Bail out! Gtk:ERROR:../../../../gtk/gtkiconview.c:1511:gtk_icon_view_get_preferred_item_size: assertion failed: (!gtk_icon_view_is_empty (icon_view))
Aborted (core dumped)
  
</details>

Lutris v0.5.10.1
Kubuntu 22.04
Native Lutris and Steam

**Comment by PowaBanga** [comment]
I have exactly the same issue on 
archlinux x86_64
lutris 0.5.11-1

**Comment by mrmatteastwood** [comment]
Exactly the same issue here.

Lutris 0.5.10.1
Linux Mint 21

lutris -d output:

`thebrightside@SATANICLIZARD:~$ lutris -d
INFO     2022-09-18 15:17:09,274 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-09-18 15:17:09,292 [libretro.get_libretro_cores:24]:No folder at /home/thebrightside/.local/share/lutris/runners/retroarch/
DEBUG    2022-09-18 15:17:09,297 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-09-18 15:17:09,380 [startup.check_driver:57]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-09-18 15:17:09,380 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1080 Ti
INFO     2022-09-18 15:17:09,380 [startup.check_driver:77]:GPU: 10DE:1B06 3842:6696 (nvidia drivers)
INFO     2022-09-18 15:17:09,513 [startup.update_runtime:213]:Startup complete
DEBUG    2022-09-18 15:17:09,733 [lutriswindow.update_store:437]:Showing 193 games
DEBUG    2022-09-18 15:17:12,645 [base.wipe_game_cache:121]:Deleting games from service-games for steam
DEBUG    2022-09-18 15:17:31,312 [http.get:83]:GET https://lutris.net/api/games/service/steam
DEBUG    2022-09-18 15:17:51,517 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/267490/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,518 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/26800/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,518 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/666220/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,519 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/203810/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,519 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/28050/library_600x900.jpg
ERROR    2022-09-18 15:17:51,822 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/203810/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:51,822 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/26800/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:51,823 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/21100/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,823 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/16450/library_600x900.jpg
ERROR    2022-09-18 15:17:51,825 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/666220/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:51,826 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/267490/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:51,826 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/28050/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:51,826 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/290930/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,827 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/32460/library_600x900.jpg
DEBUG    2022-09-18 15:17:51,828 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/448850/library_600x900.jpg
ERROR    2022-09-18 15:17:52,065 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/21100/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,065 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/16450/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,066 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/19980/library_600x900.jpg
DEBUG    2022-09-18 15:17:52,066 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/219680/library_600x900.jpg
ERROR    2022-09-18 15:17:52,068 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/290930/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,069 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/448850/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,069 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/34440/library_600x900.jpg
DEBUG    2022-09-18 15:17:52,069 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/34460/library_600x900.jpg
ERROR    2022-09-18 15:17:52,070 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/32460/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,071 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/18070/library_600x900.jpg
ERROR    2022-09-18 15:17:52,303 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/19980/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,304 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/219680/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,306 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/32360/library_600x900.jpg
DEBUG    2022-09-18 15:17:52,306 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/231160/library_600x900.jpg
ERROR    2022-09-18 15:17:52,307 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/34460/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,308 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/18490/library_600x900.jpg
ERROR    2022-09-18 15:17:52,308 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/18070/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,308 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/4540/library_600x900.jpg
ERROR    2022-09-18 15:17:52,309 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/34440/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,309 [http.get:83]:GET http://cdn.steamstatic.com/steam/apps/4550/library_600x900.jpg
ERROR    2022-09-18 15:17:52,543 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/32360/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,543 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/231160/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,546 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/4540/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,547 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/18490/library_600x900.jpg: HTTP Error 404: Not Found
ERROR    2022-09-18 15:17:52,552 [service_media.download:88]:Failed to download http://cdn.steamstatic.com/steam/apps/4550/library_600x900.jpg: HTTP Error 404: Not Found
DEBUG    2022-09-18 15:17:52,569 [steam.add_installed_games:170]:19 Steam games detected and installed
DEBUG    2022-09-18 15:17:52,569 [steam.add_installed_games:171]:Games found in: /home/thebrightside/.local/share/Steam/steamapps, /mnt/Gaming/Steam/steamapps
DEBUG    2022-09-18 15:17:52,682 [config.remove:213]:Removed config /home/thebrightside/.config/lutris/games/steam-204340-1660213512.yml
DEBUG    2022-09-18 15:17:52,684 [steam.add_installed_games:185]:1 Steam games removed
DEBUG    2022-09-18 15:17:52,685 [steam.add_installed_games:202]:0 Steam games deduplicated
Segmentation fault (core dumped)`

My PC's specs: https://termbin.com/cr0m

**Comment by strycore** [comment]
I used to see this crash too but I haven't encountered it recently, even with a large Steam library.
