### ISSUE TITLE
nice work epic games not install now

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#4497]
------------------------------------------------------
warning: /home/archkubi/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
![2022-09-11-135013_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/189523523-cc20222e-7991-4516-8c19-d5626d5ddad8.png)

**Comment by SourceCodeDeleted** [comment]
This is due to Epic Games changing it's API. 

There is an open issue on this . 
https://github.com/lutris/lutris/issues/4472

**Comment by ArchKubi** [comment]
ı now this but everthing like this return code: 256
last time ı can install but ı cant login now ı can't install @SourceCodeDeleted

**Comment by SourceCodeDeleted** [comment]
Actually I tried the fix and it appears to work fine. I will post more about it in the main issue.

**Comment by ArchKubi** [comment]
#4475 okay just look at this

**Comment by AceroRomano** [comment]
Not work for me  [https://i.postimg.cc/BnF7jjLx/Screenshot-20220924-215915.png](url)

**Comment by strycore** [comment]
Fixed in current Lutris and Wine releases
