### ISSUE TITLE
Native Java (.jdk) support

### ISSUE THREAD

**Issue by bpavuk** [lutris/lutris#4499]
There is a lot of popular games that are packed in .jar files. Most known is Minecraft. Please add automatical Java installing in neither OpenJDK nor another JDK/JVM not found if user will try to install Java game at Lutris

**Comment by bpavuk** [comment]
Sorry, "if", not "in"

**Comment by bpavuk** [comment]
Sorry, "if" not "in"

**Comment by strycore** [comment]
We used to have Minecraft download the JRE so that should still be an option. 

The demo version of Amygdala still uses this method: https://lutris.net/games/amygdala/
