### ISSUE TITLE
Fetching GOG games after logging in logs an error message `HTTP Error 405: Method Not Allowed`

### ISSUE THREAD

**Issue by Steffo99** [lutris/lutris#4500]
## Logs

```
2022-09-12 18:49:00,812: Unable to get games from API: HTTP Error 405: Method Not Allowed
```

## Debug logs

```
DEBUG    2022-09-12 18:53:12,510 [http._request:83]:GET https://embed.gog.com/userData.json
DEBUG    2022-09-12 18:53:12,785 [base.wipe_game_cache:328]:Deleting gog cache /home/steffo/.cache/lutris/gog-library.json
DEBUG    2022-09-12 18:53:12,785 [base.wipe_game_cache:141]:Deleting games from service-games for gog
DEBUG    2022-09-12 18:53:12,816 [http._request:83]:GET https://embed.gog.com/userData.json
DEBUG    2022-09-12 18:53:13,128 [http._request:83]:GET https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=1
DEBUG    2022-09-12 18:53:15,637 [http._request:83]:GET https://lutris.net/api/games/service/gog
ERROR    2022-09-12 18:53:15,746 [api.get_http_response:99]:Unable to get games from API: HTTP Error 405: Method Not Allowed
DEBUG    2022-09-12 18:53:15,768 [lutriswindow.update_store:446]:Showing 0 games
```

## Deduction

It seems that the URL that Lutris used for GOG does not exist anymore: `https://lutris.net/api/games/service/gog`

**Comment by Steffo99** [comment]
Wait, I forgot I had the "Installed games filter". Please ignore this! :sweat_smile:

**Comment by danieljohnson2** [comment]
Oh, I'm seeing it too. Not nice.

The issue is that the URL 'https://lutris.net/api/games/service/gog' now requires a POST request instead of GET. That seems off. I can fix the client to use POST but I am in doubt. I'll ask @strycore.

**Comment by danieljohnson2** [comment]
So @strycore says both GET and POST should work and is looking into this.

However, he also says POST should be preferred for this, so I will change it over. That will make GOG refresh work on the master branch, but of course the website needs to be fixed for the sake of the current client version.
