### ISSUE TITLE
Custom artwork not loading

### ISSUE THREAD

**Issue by 91rl** [lutris/lutris#4506]
Hey all, when I select an image to use as artwork for a native linux game I added, it doesn't load. Changing between zoom sizes and icon/image modes, and restarting the program doesn't effect this either. Any suggestions?

Running latest Lutris, on Debian 11, KDE.

**Comment by elogicuk** [comment]
same issue here and im running manjaro

**Comment by danieljohnson2** [comment]
It might help if you could provide the debug output from lutris. Run "lutris -d" and post the output.

**Comment by elogicuk** [comment]
i removed the custom artwork, and then added it again (still dont show)

here is the log

` lutris -d                                                        ✔ 
INFO     2022-09-18 16:55:26,591 [startup.init_lutris:174]:Starting Lutris 0.5.11
INFO     2022-09-18 16:55:26,781 [startup.check_driver:58]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-09-18 16:55:26,782 [startup.check_driver:62]:GPU: NVIDIA GeForce RTX 2060 SUPER
INFO     2022-09-18 16:55:26,783 [startup.check_driver:78]:GPU: 10DE:1F06 1462:3861 (nvidia drivers)
DEBUG    2022-09-18 16:55:27,192 [lutriswindow.update_store:446]:Showing 2 games
INFO     2022-09-18 16:55:27,219 [startup.update_runtime:215]:Startup complete
DEBUG    2022-09-18 16:55:31,097 [application.show_window:326]:Showing window EditGameConfigDialog2
DEBUG    2022-09-18 16:55:34,071 [game.save:269]:Saving Mass Effect Legendary Edition (wine) with config ID mass-effect-legendary-edition-1663491034
DEBUG    2022-09-18 16:55:34,071 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=mass-effect-legendary-edition-1663491034, runner=wine) config to /home/home/.config/lutris/games/mass-effect-legendary-edition-1663491034.yml
DEBUG    2022-09-18 16:55:34,236 [application.on_app_window_destroyed:344]:Removed window EditGameConfigDialog2
DEBUG    2022-09-18 16:55:45,013 [application.show_window:326]:Showing window EditGameConfigDialog2
DEBUG    2022-09-18 16:55:50,004 [game.save:269]:Saving Mass Effect Legendary Edition (wine) with config ID mass-effect-legendary-edition-1663491034
DEBUG    2022-09-18 16:55:50,005 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=mass-effect-legendary-edition-1663491034, runner=wine) config to /home/home/.config/lutris/games/mass-effect-legendary-edition-1663491034.yml
DEBUG    2022-09-18 16:55:50,175 [application.on_app_window_destroyed:344]:Removed window EditGameConfigDialog2
`

**Comment by 91rl** [comment]
here you go

`lutris -d
INFO     2022-09-19 14:23:07,628 [startup.init_lutris:174]:Starting Lutris 0.5.11
DEBUG    2022-09-19 14:23:07,680 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2022-09-19 14:23:08,031 [startup.check_driver:66]:Running Intel Mesa driver 20.3.5 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
INFO     2022-09-19 14:23:08,031 [startup.check_driver:78]:GPU: 8086:5917 17AA:2256 (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

DEBUG    2022-09-19 14:23:08,249 [lutriswindow.update_store:446]:Showing 8 games
INFO     2022-09-19 14:23:08,288 [startup.update_runtime:215]:Startup complete
DEBUG    2022-09-19 14:23:11,440 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2022-09-19 14:23:11,759 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2022-09-19 14:23:12,083 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2022-09-19 14:23:12,509 [application.show_window:326]:Showing window EditGameConfigDialog8
DEBUG    2022-09-19 14:23:28,824 [game.save:269]:Saving Baba is You (linux) with config ID baba-is-you-1663560748
DEBUG    2022-09-19 14:23:28,824 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=baba-is-you-1663560748, runner=linux) config to /home/user/.config/lutris/games/baba-is-you-1663560748.yml
DEBUG    2022-09-19 14:23:28,971 [application.on_app_window_destroyed:344]:Removed window EditGameConfigDialog8
`

**Comment by danieljohnson2** [comment]
Thanks for the logs. Unfortunately, I'm not seeing anything abnormal.

Do you see any artwork for this game, or just a grey box?

**Comment by 91rl** [comment]
> Thanks for the logs. Unfortunately, I'm not seeing anything abnormal.
> 
> Do you see any artwork for this game, or just a grey box?

Just a gray box.

**Comment by elogicuk** [comment]
same here just a grey box

**Comment by danieljohnson2** [comment]
So I've been looking at the code and what it does is copy the new artwork into the ~/.cache/lutris/banners, with the filename <identifier>.jpg, using the identifier of your game, so like this: "~/.cache/lutris/banners/baba-is-you.jpg"

Could you check and see if what's in that file? Your custom artwork? Maybe it's 0 length or missing?

Try manually sticking your artwork there with the right filename. Does that make it appear in Lutris?

**Comment by 91rl** [comment]
Ah, I think I see what the problem might be. I, and perhaps the other poster, misunderstood that we were assigning a banner, and thought we were applying artwork that is shown when one has the zoom setting to to maximum :facepalm: I zoomed in to the level where the banners are shown and the custom artwork showed up. If this is the case, then I guess my actual issue is, can one customise the artwork that is shown when the zoom level is set to the highest value? (The "boxart"?)

**Comment by elogicuk** [comment]
take this file https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/32639db9ccbc0455d0fb654e7bbdfc05.png

rename it to tom-clancys-splinter-cell-blacklist.jpg

place it inside here /.cache/lutris/coverart

and now it works.

but if i do it via the lutris app it still dont work :(

![image](https://user-images.githubusercontent.com/25700447/191475842-ec2799d4-b893-4b10-bfaa-e6ff1e125d26.png)

**Comment by danieljohnson2** [comment]
I believe that the issue here is that you  have *no* way to customize the cover art in the UI, as you can the banner. This seems like an oversight, so here's a PR to provide that.

Grab [the branch](https://github.com/lutris/lutris/tree/dj/custom_coverart) and give it a try; it should let you customize your cover art, and that should stick when you run the release Lutris too.

**Comment by elogicuk** [comment]
hello daniel im new to linux i dont understand how to "grab the branch and give it a try" if you tell me how i will try it and report back, thanks

**Comment by 91rl** [comment]
> I believe that the issue here is that you have _no_ way to customize the cover art in the UI, as you can the banner. This seems like an oversight, so here's a PR to provide that.
> 
> Grab [the branch](https://github.com/lutris/lutris/tree/dj/custom_coverart) and give it a try; it should let you customize your cover art, and that should stick when you run the release Lutris too.

Wow, thanks for doing that work, really appreciated :)

**Comment by elogicuk** [comment]
hello daniel it works great!
