### ISSUE TITLE
Steam Deck: can't browse for game executable

### ISSUE THREAD

**Issue by minimeee** [lutris/lutris#4507]
I've installed Lutris through Discover / Flatpak and the problem is that the "Browse" button for selecting the game executable doesn't work (nothing happens when you klick on it). The other "Browse" buttons (e. g. for selecting the prefix) are working, though. 

As a workaround, I've selected Dolphin as the default application for opening folders, as described here: https://www.youtube.com/watch?v=3_g-k5c-Hys

However, while this fixes the issue in desktop mode, it makes things worse in gaming mode: now the other "Browse" buttons don't work either (they are all broken). Is there a real fix for this issue? 

I also wonder if it's caused by / limited to the Flatpak version or is it sth. Deck specific?

**Comment by nabel0** [comment]
This is a very specific bung in the "KDE portal" on the Steam Deck

--> https://github.com/ValveSoftware/SteamOS/issues/775

As a Workaround just run this command in the terminal:

systemctl restart --user xdg-desktop-portal

You have to runt this everytime if you switch to desktop mode...

**Comment by minimeee** [comment]
Thanks for the link! With such a long history, it seems to be a rather complex issue.

But are you sure that it also causes the behaviour described above? Because, as I wrote, 2 out of 3 Lutris "Browse" buttons actually work. I'd assume that all three would be equally affected if Lutris would not be allowed to open a file browser. And why does it work if I set "Dolphin" as the default application for opening folders? It still doesn't make 100% sense to me...

**Comment by petersterne** [comment]
Just chiming in to say that this has been driving me crazy but running `systemctl restart --user xdg-desktop-portal` worked for me. Thanks!

**Comment by szeligus** [comment]
> Just chiming in to say that this has been driving me crazy but running `systemctl restart --user xdg-desktop-portal` worked for me. Thanks!

I found that on reddit, better than write command every time i go to desktop mode

"
A more permanent fix I found was the following:

Create the file /home/deck/.config/plasma-workspace/env/restartportal.sh

Write the following into this file:

#!/bin/sh
systemctl --user restart xdg-desktop-portal
Right-click -> Properties -> Permissions -> Check "Is Executable"

Restart desktop mode

This script will basically just run the restart-command whenever you enter desktop-mode

I think KDE-Plasma [already fixed this](https://bugs.kde.org/show_bug.cgi?id=419874) in 5.24, but steam os is still stuck on an older version
"

**Comment by StegoZ** [comment]
> > Just chiming in to say that this has been driving me crazy but running `systemctl restart --user xdg-desktop-portal` worked for me. Thanks!
> 
> I found that on reddit, better than write command every time i go to desktop mode
> 
> " A more permanent fix I found was the following:
> 
> Create the file /home/deck/.config/plasma-workspace/env/restartportal.sh
> 
> Write the following into this file:
> 
> #!/bin/sh systemctl --user restart xdg-desktop-portal Right-click -> Properties -> Permissions -> Check "Is Executable"
> 
> Restart desktop mode
> 
> This script will basically just run the restart-command whenever you enter desktop-mode
> 
> I think KDE-Plasma [already fixed this](https://bugs.kde.org/show_bug.cgi?id=419874) in 5.24, but steam os is still stuck on an older version "

and how to revert back to original state? just in case somehow this already fixed in future updates..

**Comment by minimeee** [comment]
> and how to revert back to original state? just in case somehow this already fixed in future updates..

By deleting the `restartportal.sh` script.

**Comment by strycore** [comment]
This is now fixed in the current SteamOS release
