### ISSUE TITLE
Setting GOG Cache path after downloads have started

### ISSUE THREAD

**Issue by james2432** [lutris/lutris#4509]
If you set the cache dir after you start a game install on GOG, it will fail the installation and say file xyz does not exist, especially if it's the .exe that was downloaded.

Cache button should either be greyed out or move the already downloaded files when changed

**Comment by danieljohnson2** [comment]
Disabling the 'Cache' button should do okay, but we should also make the dialog properly modal so you can't start the install 'underneath'. I've made these tweaks.
