### ISSUE TITLE
Lutris can't find vulkan shared object files after brew install shared-mime-info

### ISSUE THREAD

**Issue by jwilkeson** [lutris/lutris#4511]
Everything was working fine until I ran `brew install shared-mime-info` now Lutris responds with the following when I try to launch it along with a prompt to install drivers even though I've already completed the steps [here][1] 

    2022-09-16 00:20:09,461: Starting Lutris 0.5.10.1
    2022-09-16 00:20:09,488: No folder at /home/dan/.local/share/lutris/runners/retroarch/
    2022-09-16 00:20:09,522: Running AMD Mesa driver 22.1.7 on AMD Radeon RX 5700 XT (navi10, LLVM 14.0.6, DRM 3.42, 5.15.0-46-generic) (0x731f)
    2022-09-16 00:20:09,523: GPU: 1002:731F 1002:0B36 (amdgpu drivers)
    2022-09-16 00:20:09,523: i386 libGL.so.1 missing (needed by opengl)
    2022-09-16 00:20:09,523: x86_64 libGL.so.1 missing (needed by opengl)
    2022-09-16 00:20:09,523: i386 libvulkan.so.1 missing (needed by vulkan)
    2022-09-16 00:20:09,523: x86_64 libvulkan.so.1 missing (needed by vulkan)
    2022-09-16 00:20:09,523: i386 libgnutls.so.30 missing (needed by gnutls)
    2022-09-16 00:20:09,523: x86_64 libgnutls.so.30 missing (needed by gnutls

I'm not sure if it's relevant but there's another user directory in `/home` called `linuxbrew`. I know these libraries are installed as when I run the respective commands to install them, apt tells me they're already present and at their newest version, is it something wrong with my path? It seems like they're there but Lutris just can't find them.

On another note, when I try to run steam it tells me `You are missing the following 32-bit libraries, and Steam may not run: libc.so.6` this isn't really the issue but I put it here in case it gives insight.

I'm using Ubuntu 20.04 with AMD.

Edit: when I run `sudo find / -iname "libvulkan.so.1"` I get 

    /snap/gnome-3-38-2004/115/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /snap/gnome-3-38-2004/112/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /snap/mesa-core20/120/egl/lib/libvulkan.so.1
    /snap/plex-desktop/18/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /snap/plex-desktop/17/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    find: ‘/run/user/1000/doc’: Permission denied
    find: ‘/run/user/1000/gvfs’: Permission denied
    /usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /usr/lib/i386-linux-gnu/libvulkan.so.1
    /usr/share/code/libvulkan.so.1
    /home/dan/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy/pinned_libs_64/libvulkan.so.1
    /home/dan/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /home/dan/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libvulkan.so.1
    /home/dan/.steam/debian-installation/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libvulkan.so.1

And similar output for the other shared object files that lutris says are missing.

Upon the first time launching Lutris it looks like from the terminal output that it installs DXVK drivers automatically, why doesn't it do that in this particular case? Maybe getting it to do that would allow it to install these drivers in its own particular way so it could find them maybe?

The dialog that appears when trying to startup Lutris says 

`Lutris was unable to detect Vulkan support for the i386 and x86_64 architecture. This will prevent many games and programs from working. To install it, please use the following guide: Installing Graphics Drivers`

  [1]: https://github.com/lutris/docs/blob/master/InstallingDrivers.md

**Comment by danieljohnson2** [comment]
This looks like you are trying to use two package managers at once (brew and APT); that's going to produce strange results. You appear to have libvulkan installed by APT, but not by brew.

This case could be some kind of mismatched set of libraries between the two, if its trying to use libraries from both. But also it may be that brew is preventing Lutris from seeing the APT installed stuff (though that seems unlikely- I'd expect that to break everything, not just Vulkan).

I'd suggest you either remove brew (Ubuntu is still really APT based even now) or install Vulkan via brew, if that's possible.

**Comment by jwilkeson** [comment]
Right, brew and apt are both package managers, I should've known that would cause issues, well I uninstalled the prior and then reinstalled Lutris and things look to be working now, knock on wood.
