### ISSUE TITLE
Pop-OS missing 32bit binaries for origin/ wont install

### ISSUE THREAD

**Issue by janat08** [lutris/lutris#4518]
There's a load of missing packages and none are even mentioned in readme. The ones listed in forums don't cover it. On my system the install fails because lutris fails to recognize that install has completed, so you need to cancel it after which trying to run origin through shortcut fails.

**Comment by janat08** [comment]
Adding all of the binaries that actually can be found doesn't resolve issue. I still get errors that packages are missing by they appear to relate to wine as apposed linux side of things given that errors point to the packages not being i386 with a full path pointing to C disk I think, rather than just something in PATH.

**Comment by Costinteo** [comment]
Same here. Origin used to work but no longer boots. A reinstall ends up having the same problem, although at first boot (during the install process), the login screen does pop up.

When I start up Origin, it simply freezes the window it pops up.

I'm not convinced it's a missing binaries problem, as I've had Origin installed for quite some time now and it used to work. It simply stopped working one day (don't know when). I was thinking it might have been an Origin update that broke it.

**Comment by Costinteo** [comment]
At some point in the installation process, the login screen will pop up. You have to avoid signing in and exit Origin, at which point Lutris should recognise that the installation process is finished. Have you tried this?

**Comment by janat08** [comment]
Fair enough. The message should be changed the window should be closed.

**Comment by janat08** [comment]
It still doesn't start though. The login window shows, but not the client.

**Comment by Costinteo** [comment]
This is true. The point still stands that something is wrong with Origin (possibly only on Pop OS), but I am not convinced it is missing binaries. I am also on Pop OS and am experiencing the same problems.

**Comment by strycore** [comment]
We do mention in several places that Wine and the Vulkan drivers (including their 32bit versions) should be installed in order to have the full dependencies to install and run games.

Lutris will show warnings if those are not fully installed.
