### ISSUE TITLE
flowbox error?

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#452]
Added Rogue Wizards this morning restarted Lutris and got this on the terminal:

`ERROR    2016-12-04 06:25:26,448 [flowbox]:Couldn't get item for game {'updated': '2016-12-04T03:26:51.416061Z', 'year': 2016, 'lastplayed': None, 'directory': '/home/user01/Games', 'installer_slug': None, 'installed': 1, 'steamid': '', 'has_custom_icon': None, 'has_custom_banner': None, 'slug': 'rogue-wizards', 'platform': None, 'parent_slug': None, 'executable': None, 'name': 'Rogue Wizards', 'id': 1088, 'runner': 'linux', 'configpath': 'rogue-wizards-1480822996'}
`

**Comment by strycore** [comment]
I believe this can happen but now I have to find a way to reproduce that. Will look into it for 0.4.5

**Comment by strycore** [comment]
We got rid of flowbox, this shouldn't happen anymore.
