### ISSUE TITLE
Automatic artwork loading unpredictably

### ISSUE THREAD

**Issue by 91rl** [lutris/lutris#4523]
When I install games that are in the Lutris games database the artwork downloads and displays very upredictaby, sometimes taking several days. Is there a way to manually refresh the process to trigger the process to happen straight away?

**Comment by danieljohnson2** [comment]
There is a way; delete the file "~/.cache/lutris/updates.json" and restart Lutris.

But installing games should download the artwork right then, so it sounds like there may be a problem.

Specifically how do you install the games that are giving you trouble?

**Comment by 91rl** [comment]
> There is a way; delete the file "~/.cache/lutris/updates.json" and restart Lutris.
> 
> But installing games should download the artwork right then, so it sounds like there may be a problem.
> 
> Specifically how do you install the games that are giving you trouble?

Well if it isn't the resident artwork expert again :) Yeah it can take quite a while, initially the only reason I was adding custom artwork (RE my previous issue with custom artwork that you resolved) because it was so slow I didn't even know automatic artwork downloading was a feature until a couple days had passed and some of the artwork showed up. I install via: add new game -> add locally installed game. Then just add the name, year, pick linux or wine (proton GE for lutris) and then add the exectuable.

**Comment by danieljohnson2** [comment]
Well, this is getting very messy.

But I fixed this scenario: changing the "Identifier" in your configuration will update the display of the media at the top, and will trigger a download of media for the new identifier.

But this made for an ugly merge for #4520. I think I'll hold off on more image-media fixes for a bit until that PR gets sorted.

**Comment by 91rl** [comment]
Thanks! :)
