### ISSUE TITLE
Banners, icons, coverarts.

### ISSUE THREAD

**Issue by begin-theadventure** [lutris/lutris#4524]
1. Instead of putting banners and coverarts in `~/.cache/lutris` put them in `~/.config/lutris` or `~/.local/share/lutris`.
2. Don't change the resolution of _custom_ banners and icons (+ coverarts if 3. was added).
3. Allow coverarts to be set from the GUI.
4. Option to re-download them.

**Comment by danieljohnson2** [comment]
1. The banners used to be in ~/.local/share/lutris but were moved. As long as you don't customize this does make sense- they will eventually redownload if deleted. Perhaps only custom media should go in ~/.loca/share/lutris?
2. Do you mean Lutris should display many different sizes at the same time?
3. Try recent PR #4520. Does that help?
4. Why redownload what you already have? If you want to redownload to reset custom artworks, PR #4520 does that too.

**Comment by begin-theadventure** [comment]
1. Because cache can be easily deleted with something like BleachBit.
2. Only stretch the picture don't change to a crappy resolution.
3. Would be great it it was added in the next version.
4. In case of accidental of deletion of `~/.cache/lutris`, it happened to me when I cleaned with BleachBit. Only for stuff installed with official script.

1. Because the cache can be easily removed with something like BleachBit.
2. Just stretch the image don't change it to a crappy resolution.
3. It would be great if it was added in the next version.
4. In case of accidental deletion of `~/.cache/lutris`, it happened to me when cleaning with BleachBit. Only for things installed with the official scripts.

**Comment by begin-theadventure** [comment]
1. Because the cache can be easily removed with something like BleachBit.
2. Just stretch the image don't change it to a crappy resolution.
3. It would be great if it was added in the next version.
4. In case of accidental deletion of `~/.cache/lutris`, it happened to me when cleaning with BleachBit. Only for things installed with the official scripts.

**Comment by begin-theadventure** [comment]
1. Because the cache can be easily removed with something like BleachBit.
2. Just stretch (or maybe cut) the image don't change it to a crappy resolution.
3. It would be great if it was added in the next release.
4. In case of accidental deletion of `~/.cache/lutris`, it happened to me when cleaning with BleachBit (until I realized where Lutris saves banners and coverarts). Only for things installed with the official scripts.

**Comment by begin-theadventure** [comment]
1. Because the cache can be easily removed with something like BleachBit.
2. Just stretch (or maybe cut) the image don't change it to a crappy resolution.
3. It would be great if it was added in the next release.
4. In case of accidental deletion of `~/.cache/lutris`, it happened to me when cleaning with BleachBit (until I realized where Lutris saves banners and coverarts). Only for things installed with official scripts.

**Comment by danieljohnson2** [comment]
I hope @strycore will bless my PR with his mergey approval, but he may have left that button out on purpose. My guess it that it'll go in- I would guess he found the button coming out too big. We'll see how it goes.

What's the difference between stretching the media and changing the resolution of it?

Lutris will (after about 24 hours and a restart) automatically redownload all the media, if they are lost. But any custom artwork would be gone, so maybe separating the custom stuff is the way.

But I do not want to try that until the fate of PR #4520 is decided. It's got enough stuff in it already, and this enhancement would conflict for sure.

**Comment by begin-theadventure** [comment]
What's the difference between stretching the media and changing the resolution of it?
    I mean that it currently changes the image to a really low resolution and that can sometimes look bad, especially with desktop and menu shortcuts. Currently the only way to have high-resolution images is of course to not to set them with the GUI but simply put them in folders.

**Comment by danieljohnson2** [comment]
Hmm. Are you running on a High-DPI display perhaps?

I've been researching that and it's painful. GDK PixBufs are never high DPI- its 96 DPI or bust, and that is what Lutris uses, so you get blur-tastic results at high DPIs. Not great.

Near as I can make out the solution is supposed to be to abandon PixBufs for Cairo surfaces. That's a very GNOMEy answer. This looks significantly more complicated than using PixBufs.

I'm not sure there a great amount of value in doing this. It's cosmetic, obviously, and in my experience WINE reacts poorly to high-dpi scenarios anyway. WINE isn't everything, but it's a big chunk of Linux gaming.

I suppose it would be better to do it that not, but maybe there are other tasks more worth the time.

**Comment by begin-theadventure** [comment]
I don't think so.
Lutris converts banners to 184x69, icons to 128x128 and coverarts to 264x352, jpg format.
I set up custom images from Lutris and they looked bad, especially the shortcuts because the resolution was low so.
I edited the images to a proper shape (of the banner and coverart) but with a higher resolution then put the images in the right folders with the right name and changed the icon of shortcuts and the change was immediately noticeable because of the higher image resolution.

**Comment by begin-theadventure** [comment]
Lutris converts banners to 184x69, icons to 128x128 and coverarts to 264x352, jpg format.
I set up custom images from Lutris and they looked bad, especially the shortcuts because the resolution was low so.
I edited the images to a proper shape (of the banner and coverart) but with a higher resolution then put the images in the right folders with the right name and changed the icon of shortcuts and the change was immediately noticeable because of the higher image resolution.

**Comment by begin-theadventure** [comment]
Placed by me in banners folder:
![image](https://user-images.githubusercontent.com/99835765/192107036-62765ab4-b7b5-4eae-8495-c2e142affd71.png)
Set with Lutris:
![image](https://user-images.githubusercontent.com/99835765/192107102-95661c32-4298-4fee-ad03-835155a71e4a.png)

**Comment by danieljohnson2** [comment]
Holy crud. Lutris is re-encoding that, and that banner really suffers.

I'll look into it.

**Comment by danieljohnson2** [comment]
OK, I've got it. Commit b73e7e006ab6ee52720b8bbac553625640068c70 should address this.

Your original PNG is being re-encoded into a (very slightly smaller) JPEG at default quality. That treats this banner poorly- broad areas of color and short borders do not make nice JPEGs.

I've added the 'quality' option here at its max value of 100, which produces the best (but largest) JPEGs we can have. I feel it looks much better this way, and the banner is still 3k in size.

**Comment by begin-theadventure** [comment]
Custom banners and covers look better now, but it still converts custom icons to 32x32 instead of 128x128.
I was wrong, because 128x128 icons are only used for things installed with official scripts.
Desktop![Desktop shortcut](https://user-images.githubusercontent.com/99835765/192137167-42f0f956-51d9-408a-965a-933d08860ef6.png)
Menu![Menu shortcut](https://user-images.githubusercontent.com/99835765/192137591-82808055-61af-4163-8769-31e3a0800c35.png)

**Comment by danieljohnson2** [comment]
Oh, I see. Yeah, we always display at 32x32 (with the High-DPI issues I described) but we don't need to re-encode at that size, and doing so precludes fixing this in future. I'll adjust this up to 128x128, just for the custom icon transcoding.

**Comment by danieljohnson2** [comment]
I've been able to move this ball forward some; I've just committed a custom renderer for the main game view, which provides better performance on large libraries.

Since we're doing this, I've added scaling code so that if your media do have higher resolution, we'll preserve it at render time. We're still re-encoding media when you use Lutris to install them, but you can paste them into the ~/.cache/lutris directories to avoid this.
