### ISSUE TITLE
Lutris Flatpak doesn't allow to create (desktop,application,steam)shortcuts but on RPM it works fine

### ISSUE THREAD

**Issue by PalmTamino** [lutris/lutris#4525]
https://streamable.com/186wq4

Here a video of the bug

**Comment by A6GibKm** [comment]
https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.DynamicLauncher allows to create desktop files from a sandbox

**Comment by strycore** [comment]
it's a limitation of Flatpak
