### ISSUE TITLE
[Feature Request]: Add support for Microsoft Store games

### ISSUE THREAD

**Issue by pupilo-py** [lutris/lutris#4531]
I don't know if it's possible, but I wanted to ask for the addition of Microsoft Store support, I can't get access to the games I own there by any other means.

**Comment by adro79** [comment]
It's impossible for now since Microsoft apps are built with UWP.

Best you can do is play with Xbox Cloud.

**Comment by gwhizoftv** [comment]
Does this include minecraft ?

**Comment by strycore** [comment]
Not possible at the moment, since UWP isn't supported. As mentioned above, Xbox cloud gaming is the best option for now.

@gwhizoftv no, the Minecraft launcher can be installed natively (for Minecraft Java Edition) and with Wine (for Minecraft Dungeons).
