### ISSUE TITLE
Empty install game dialog when Wine dependency not met

### ISSUE THREAD

**Issue by zakkvry** [lutris/lutris#4533]
When some dependencies are not met, error handling is in place to explain that they should be downloaded (eg `xdelta3`, `xterm`). However the unmet `wine` dependency was not conveyed in the UI. I found the indication of this with `lutris --debug`. After installing Wine everything worked as expected. :) 

yaml -> https://lutris.net/games/install/31198/view

### Behavior
![Screenshot from 2022-09-30 18-41-04](https://user-images.githubusercontent.com/16073358/193369344-5744e53e-9daa-4a70-9f60-e8cb7c010883.png)
![Screenshot from 2022-09-30 18-40-23](https://user-images.githubusercontent.com/16073358/193369304-9407e7df-f271-412c-83e2-a4874934f927.png)

### Expected 
![Screenshot from 2022-09-30 18-42-34](https://user-images.githubusercontent.com/16073358/193369322-16be8467-f39c-4820-a8f9-a5a1ca3a60b6.png)

### Environment
OS: Manjaro Linux x86_64
Kernel: 5.17.15-1-MANJARO
DE: GNOME 42.4

**Comment by danieljohnson2** [comment]
This isn't quite what it seems. From the traceback, Lutris thinks wine is available but the wine executable is not there. This generates an exception but that is just breaking the dialog (a perennial problem with this dialog).

I've added code to report errors in this scenario. But I've also added code to cope with missing WINE exes better.

I don't think this installation will *work* without a functional WINE, but hopefully it will fail better now.
