### ISSUE TITLE
Ubisoft Connect two-factor authentication support

### ISSUE THREAD

**Issue by Wiedzmin89** [lutris/lutris#4534]
I can't login in Ubisoft Connect through Lutris, because two-factor authentication page can't be loaded.

Steps to reproduce:
1. Enable two-factor authentication in Ubisoft account
2. Install Ubisoft Connect with Lutris
3. Login into Ubisoft Connect account with Lutris
4. Login process stuck on empty page

Video demonstration: https://drive.google.com/file/d/1nFA8aSht7fUNIy8MBNFRGJ8N9KzHhC2W/view?usp=sharing

lutris: 0.5.11-1

```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.15.71-1-lts
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.3 GB
Swap:            4.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.1.7
OpenGL Core:     4.6 (Core Profile) Mesa 22.1.7
OpenGL ES:       OpenGL ES 3.2 Mesa 22.1.7
Vulkan:          Supported
```

**Comment by 1nikolas** [comment]
Have the same problem seems to be 2FA related indeed

**Comment by Peltori** [comment]
Yup same here, gona try to log in without 2FA enabled to see if the issue is still there. Gona post here when i get to home to test this.

**Comment by 1nikolas** [comment]
I can confirm it works with 2fa disabled

**Comment by Peltori** [comment]
> I can confirm it works with 2fa disabled

Yup 2FA disabled it works here as well.

**Comment by DaKingBean** [comment]
yup same issue here too

**Comment by Wiedzmin89** [comment]
@danieljohnson2 Can you do something about that?

**Comment by danieljohnson2** [comment]
I do not feel hopeful. I do not have an Ubisoft account still less two-factor authentication for it. These bug reports do not give me anything I can work with, without that.

Maybe if you guys posted the Lutris debug log ("lutris -d") there would be something. But I did not ask for it because I'm not feeling optimistic on this one.

Indeed, I just now told @strycore not to hold the next release over this one. Too many fixes waiting to go out to wait for someone to figure out this one.

**Comment by tchatain** [comment]
@Wiedzmin89 and @danieljohnson2 I took a few hours to mess around with this part of the code tonight. I have a work-around that shows the full login flow, including MFA, but I had to steal the genome ID and app ID from Ubisoft's own web app. I'm assuming that's not what we want, but the app ID currently being used seems to be misconfigured. Regardless, here is the commit (it's not much): https://github.com/lutris/lutris/commit/57e0c18ec443974c22e497c4463b0efd4ce41cac

**Comment by danieljohnson2** [comment]
I would expect that Lutris will never get its own IDs, so *borrowing* the Ubisoft web app's is the only way.

I think you should put submit a PR with that commit; do it soon if you want it considered for the next release.

**Comment by Wiedzmin89** [comment]
https://github.com/lutris/lutris/commit/57e0c18ec443974c22e497c4463b0efd4ce41cac It's worked for me. But Ubisoft API still sucks
@tchatain Thanks

**Comment by tchatain** [comment]
> I would expect that Lutris will never get its own IDs, so _borrowing_ the Ubisoft web app's is the only way.
> 
> I think you should put submit a PR with that commit; do it soon if you want it considered for the next release.

Fair enough - I'm used to dealing with 3rd-party ID providers like GitHub and Google, but I guess that's not what Ubisoft is! :)
PR is up!

**Comment by 1nikolas** [comment]
To maintainers:
Be careful with Client IDs that are not publicly available (eg acquired by reverse engineering), companies can take down the whole repository for this

**Comment by danieljohnson2** [comment]
Ubisoft could do that anyway, but I'd like to think they'd try a cease & desist first, if they want Linux users to not purchase games from their service.

Still, if there's a more legitimate way to do this integration, and if Ubisoft does not object, we should certainly prefer to do it that way.

**Comment by strycore** [comment]
no need to be paranoid about stuff that has never happened.
Lutris and other projects such as GOG Galaxy integrations have been shipping such IDs for years.
No one cares.
