### ISSUE TITLE
Ubisoft integration bugged

### ISSUE THREAD

**Issue by KrOOb-5** [lutris/lutris#4535]
When trying to install the ubisoft integration everything goes awesome. But i cant see my Ubisoft library. Also i clicked on the “person” icon and my window goes blank when authenticating and if i sync my library it gets me this error : (Errno 2) No such file or directory ‘/home/deck/.var/app/net.lutris.Lutris/cache/lutris/ubisoft/.token’.

**Comment by KrOOb-5** [comment]
When attempting to create this .token file under that directory. Gives me this message: 
Expecting value: line 2 column 1 (char 2)

**Comment by Wiedzmin89** [comment]
Do you use two-factor authentication for Ubisoft Connect login?

**Comment by KrOOb-5** [comment]
Yes, it gets me to a point when the window just stays white

**Comment by Wiedzmin89** [comment]
Then it's the same issue https://github.com/lutris/lutris/issues/4534

**Comment by KrOOb-5** [comment]
Hoping in the future this can be patched. ❤️

**Comment by KrOOb-5** [comment]
New info: i can enter trough lutris but i cant sync the games to lutris. The error message is still the same when syncing…

**Comment by DrLegitamate** [comment]
Any update on this issue? Still having the same problem. I can open ubisoft connect itself through lutris but the account connect still doesnt work

**Comment by danieljohnson2** [comment]
If indeed this is the Ubisoft 2FA issue from #4534, then there's a fix for it for the next release.

Try the [beta of 0.5.12](https://github.com/lutris/lutris/releases/tag/v0.5.12-beta1), see if that works better for you.

**Comment by KrOOb-5** [comment]
Hey im on steam deck. How do i install such update ?

**Comment by strycore** [comment]
Fix is now released
