### ISSUE TITLE
Properly uninstall Lutris and all files/runners it installed

### ISSUE THREAD

**Issue by Zeit08** [lutris/lutris#4536]
Hi all, I have not found a guide of how to properly, completely uninstall lutris.

My situation: I installed Lutris via Software app of Fedora 36 (.rpm repositories). Then I logged in using various platforms: GOG, Ubisoft, Origin, Epic Games and Steam. 
I noticed it also created some icons of those launchers in my distro. 
I have installed one game, tried it, then uninstalled (my laptop is not powerful enough) and decided to remove lutris completely.

I went to lutris and tried to find some options to uninstall things, but found only a few. Then I decided to uninstall lutris via Software app. But I still see Epic Game Launcher, Ubisoft, Origin, etc. launcher on my distro.

Is there a command to find anything related to "lutris" and remove it? Like in terminal for instance.

**Comment by Wiedzmin89** [comment]
Check files in `~/.local/share/applications/`, folder wine contains all launchers by default

**Comment by Zeit08** [comment]
ok I deleted all files there related to wine and lutris. So the procedure is: delete lutris from system via normal uninstall. Then go to that folder and delete the related files.

**Comment by inukaze** [comment]
Yesterday i had download manually lutris i extract and use

```
sudo su
python3 setup.py build
python3 setup.py install
ldconfig
exit
```

`lutris`

> Traceback (most recent call last):
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/dialogs/webconnect_dialog.py", line 7, in <module>
>     gi.require_version("WebKit2", "4.1")
>   File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit2 not available
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/lutris", line 4, in <module>
>     __import__('pkg_resources').run_script('lutris==0.5.16', 'lutris')
>   File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
>     exec(code, namespace, namespace)
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/EGG-INFO/scripts/lutris", line 58, in <module>
>     from lutris.gui.application import Application  # pylint: disable=no-name-in-module
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/application.py", line 44, in <module>
>     from lutris.gui.config.preferences_dialog import PreferencesDialog
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/config/preferences_dialog.py", line 10, in <module>
>     from lutris.gui.config.game_common import GameDialogCommon
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/config/game_common.py", line 22, in <module>
>     from lutris.services.lutris import LutrisBanner, LutrisCoverart, LutrisIcon, download_lutris_media
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/__init__.py", line 5, in <module>
>     from lutris.services.amazon import AmazonService
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/amazon.py", line 22, in <module>
>     from lutris.services.base import OnlineService
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/base.py", line 17, in <module>
>     from lutris.gui.dialogs.webconnect_dialog import DEFAULT_USER_AGENT, WebConnectDialog
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/dialogs/webconnect_dialog.py", line 9, in <module>
>     gi.require_version("WebKit2", "4.0")
>   File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit2 not available
> 

```
sudo su
slackpkg search webkit
```

> Looking for webkit in package list. Please wait... DONE
> 
> The list below shows all packages with name matching "webkit".
> 
> [ installed ] - kdewebkit-5.90.0-x86_64-1
> [ installed ] - qt5-webkit-5.212.0_alpha4-x86_64-7
> 
> You can search specific files using "slackpkg file-search file".
> 

`slpkg -F webkit`

> Packages with name matching [ webkit ]
> 
> +==============================================================================
> | Repository  Package                                                      Size
> +==============================================================================
>   slack       kdewebkit-5.90.0-x86_64-1.txz                                72 K
>   slack       qt5-webkit-5.212.0_alpha4-x86_64-7.txz                    15700 K
>   salix       webkit2gtk-2.34.3-x86_64-1gv.txz                          21073 K
>   slackl      webkitgtk-2.4.11-x86_64-5dj.txz                            9791 K
>   slackl      webkit2gtk-2.32.1-x86_64-2dj.txz                          20730 K
> 
> Found summary
> ===============================================================================
> Total found 5 packages in 3 repositories.

`slpkg -s slackl webkitgtk ; ldconfig`

> Reading package lists... Done
> Resolving dependencies... Done
> 
> The following packages will be automatically installed or upgraded 
> with new version:
> 
> +==============================================================================
> | Package                 New Version        Arch    Build  Repos          Size
> +==============================================================================
> Installing:
>   webkitgtk               2.4.11             x86_64  5      slackl       9791 K
> Installing for dependencies:
>   icu4c-compat            73.2               x86_64  1      slackl      19745 K
> 
> Installing summary
> ===============================================================================
> Total 2 packages.
> 2 packages will be installed, 0 will be upgraded and 0 will be reinstalled.
> Need to get 28.84 Mb of archives.
> After this process, 115.38 Mb of additional disk space will be used.
> 
> Would you like to continue [y/N]? y

> 
> [1/1][ Download ] --> icu4c-compat-73.2-x86_64-1dj.txz
> 
> --2024-02-06 09:34:22--  http://www.slackel.gr/repo/x86_64/current/slackel/slack_files/icu4c-compat-73.2-x86_64-1dj.txz
> Resolviendo www.slackel.gr (www.slackel.gr)... 204.68.111.101
> Conectando con www.slackel.gr (www.slackel.gr)[204.68.111.101]:80... conectado.
> Petición HTTP enviada, esperando respuesta... 200 OK
> Longitud: 20219440 (19M)
> Grabando a: «/tmp/slpkg/packages/icu4c-compat-73.2-x86_64-1dj.txz»
> 
> icu4c-compat-73.2-x86_64-1dj.txz        100%[============================================================================>]  19,28M   450KB/s    en 40s     
> 
> 2024-02-06 09:35:03 (488 KB/s) - «/tmp/slpkg/packages/icu4c-compat-73.2-x86_64-1dj.txz» guardado [20219440/20219440]
> 
> 
> [1/1][ Download ] --> webkitgtk-2.4.11-x86_64-5dj.txz
> 
> --2024-02-06 09:35:03--  http://www.slackel.gr/repo/x86_64/current/slackel/extra/webkitgtk-2.4.11-x86_64-5dj.txz
> Resolviendo www.slackel.gr (www.slackel.gr)... 204.68.111.101
> Conectando con www.slackel.gr (www.slackel.gr)[204.68.111.101]:80... conectado.
> Petición HTTP enviada, esperando respuesta... 200 OK
> Longitud: 10026668 (9,6M) [application/x-troff-man]
> Grabando a: «/tmp/slpkg/packages/webkitgtk-2.4.11-x86_64-5dj.txz»
> 
> webkitgtk-2.4.11-x86_64-5dj.txz         100%[============================================================================>]   9,56M   275KB/s    en 41s     
> 
> 2024-02-06 09:35:44 (241 KB/s) - «/tmp/slpkg/packages/webkitgtk-2.4.11-x86_64-5dj.txz» guardado [10026668/10026668]
> 
> 
> +==============================================================================
> | MD5SUM check for icu4c-compat-73.2-x86_64-1dj.txz [ PASSED ]
> +==============================================================================
> 
> [ installing ] --> icu4c-compat-73.2-x86_64-1dj.txz
> 
> +==============================================================================
> | Installing new package /tmp/slpkg/packages/icu4c-compat-73.2-x86_64-1dj.txz
> +==============================================================================
> 
> Verifying package icu4c-compat-73.2-x86_64-1dj.txz.
> Installing package icu4c-compat-73.2-x86_64-1dj.txz:
> PACKAGE DESCRIPTION:
> # icu4c-compat (International Components for Unicode)
> #
> # The International Components for Unicode (ICU) libraries provide
> # robust and full-featured Unicode services on a wide variety of
> # platforms.
> # This package contains the shared libraries of older releases,
> # to be used on slackware-current for compatibility reasons.
> #
> # Homepage: http://www.icu-project.org/
> #
> Executing install script for icu4c-compat-73.2-x86_64-1dj.txz.
> Package icu4c-compat-73.2-x86_64-1dj.txz installed.
> Completed!
> 
> 
> +==============================================================================
> | MD5SUM check for webkitgtk-2.4.11-x86_64-5dj.txz [ PASSED ]
> +==============================================================================
> 
> [ installing ] --> webkitgtk-2.4.11-x86_64-5dj.txz
> 
> +==============================================================================
> | Installing new package /tmp/slpkg/packages/webkitgtk-2.4.11-x86_64-5dj.txz
> +==============================================================================
> 
> Verifying package webkitgtk-2.4.11-x86_64-5dj.txz.
> Installing package webkitgtk-2.4.11-x86_64-5dj.txz:
> PACKAGE DESCRIPTION:
> # webkitgtk (GTK+ port of the WebKit)
> #
> # WebKit/GTK+ is the new GTK+ port of the WebKit, an open-source web
> # content engine that powers numerous applications such as web
> # browsers, email clients, feed readers, web and text editors, and a
> # whole lot more.
> #
> # https://www.webkitgtk.org/
> #
> Executing install script for webkitgtk-2.4.11-x86_64-5dj.txz.
> Package webkitgtk-2.4.11-x86_64-5dj.txz installed.
> Completed!
> 
> +==============================================================================
> | Total 2 packages installed and 0 package upgraded
> +==============================================================================
> | Package icu4c-compat-73.2 installed successfully
> | Package webkitgtk-2.4.11 installed successfully
> +==============================================================================
> 

```
exit
lutris
```

> Traceback (most recent call last):
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/dialogs/webconnect_dialog.py", line 7, in <module>
>     gi.require_version("WebKit2", "4.1")
>   File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit2 not available
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/lutris", line 4, in <module>
>     __import__('pkg_resources').run_script('lutris==0.5.16', 'lutris')
>   File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
>     exec(code, namespace, namespace)
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/EGG-INFO/scripts/lutris", line 58, in <module>
>     from lutris.gui.application import Application  # pylint: disable=no-name-in-module
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/application.py", line 44, in <module>
>     from lutris.gui.config.preferences_dialog import PreferencesDialog
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/config/preferences_dialog.py", line 10, in <module>
>     from lutris.gui.config.game_common import GameDialogCommon
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/config/game_common.py", line 22, in <module>
>     from lutris.services.lutris import LutrisBanner, LutrisCoverart, LutrisIcon, download_lutris_media
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/__init__.py", line 5, in <module>
>     from lutris.services.amazon import AmazonService
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/amazon.py", line 22, in <module>
>     from lutris.services.base import OnlineService
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/services/base.py", line 17, in <module>
>     from lutris.gui.dialogs.webconnect_dialog import DEFAULT_USER_AGENT, WebConnectDialog
>   File "/usr/lib64/python3.9/site-packages/lutris-0.5.16-py3.9.egg/lutris/gui/dialogs/webconnect_dialog.py", line 9, in <module>
>     gi.require_version("WebKit2", "4.0")
>   File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit2 not available
> 

`root@Slack64:/home/inukaze/Descargas/lutris# ls`

> AUTHORS  build           debian  docs         LICENSE  lutris.egg-info  Makefile     meson.build              po              README.rst  setup.py  tests
> bin      CONTRIBUTING.md  dist    INSTALL.rst  lutris   lutris.spec      MANIFEST.in  optional_settings.py.in  pyproject.toml  schema      share     utils
> 

`root@Slack64:/home/inukaze/Descargas/lutris# python3 setup.py uninstall`

> python3 setup.py uninstall
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'uninstall'

`python3 setup.py --help`

> Common commands: (see '--help-commands' for more)
> 
>   setup.py build      will build the package underneath 'build/'
>   setup.py install    will install the package
> 
> Global options:
>   --verbose (-v)      run verbosely (default)
>   --quiet (-q)        run quietly (turns verbosity off)
>   --dry-run (-n)      don't actually do anything
>   --help (-h)         show detailed help message
>   --no-user-cfg       ignore pydistutils.cfg in your home directory
>   --command-packages  list of packages that provide distutils commands
> 
> Information display options (just display information, ignore any commands)
>   --help-commands     list all available commands
>   --name              print package name
>   --version (-V)      print package version
>   --fullname          print <package name>-<version>
>   --author            print the author's name
>   --author-email      print the author's email address
>   --maintainer        print the maintainer's name
>   --maintainer-email  print the maintainer's email address
>   --contact           print the maintainer's name if known, else the author's
>   --contact-email     print the maintainer's email address if known, else the
>                       author's
>   --url               print the URL for this package
>   --license           print the license of the package
>   --licence           alias for --license
>   --description       print the package description
>   --long-description  print the long package description
>   --platforms         print the list of platforms
>   --classifiers       print the list of classifiers
>   --keywords          print the list of keywords
>   --provides          print the list of packages/modules provided
>   --requires          print the list of packages/modules required
>   --obsoletes         print the list of packages/modules made obsolete
> 
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help

`python3 setup.py --help-commands`

> Standard commands:
>   build             build everything needed to install
>   build_py          "build" pure Python modules (copy to build directory)
>   build_ext         build C/C++ and Cython extensions (compile/link to build directory)
>   build_clib        build C/C++ libraries used by Python extensions
>   build_scripts     "build" scripts (copy and fixup #! line)
>   clean             clean up temporary files from 'build' command
>   install           install everything from build directory
>   install_lib       install all Python modules (extensions and pure Python)
>   install_headers   install C/C++ header files
>   install_scripts   install scripts (Python or otherwise)
>   install_data      install data files
>   sdist             create a source distribution (tarball, zip file, etc.)
>   register          register the distribution with the Python package index
>   bdist             create a built (binary) distribution
>   bdist_dumb        create a "dumb" built distribution
>   bdist_rpm         create an RPM distribution
>   bdist_wininst     create an executable installer for MS Windows
>   check             perform some checks on the package
>   upload            upload binary package to PyPI
> 
> Extra commands:
>   alias             define a shortcut to invoke one or more commands
>   bdist_egg         create an "egg" distribution
>   develop           install package in 'development mode'
>   dist_info         create a .dist-info directory
>   easy_install      Find/get/install Python packages
>   egg_info          create a distribution's .egg-info directory
>   install_egg_info  Install an .egg-info directory for the package
>   rotate            delete older distributions, keeping N newest files
>   saveopts          save supplied options to setup.cfg or other config file
>   setopt            set an option in setup.cfg or another config file
>   test              run unit tests after in-place build (deprecated)
>   upload_docs       Upload documentation to sites other than PyPi such as devpi
> 
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 

Why don't have any command to remove/purge the installation made it by the script ?
i want remove the software because result useless for me, well i will going to search any alternative to lutris make it in c++ or rust and nothing of python or java.
