### ISSUE TITLE
Cannot find Xephyr when installed

### ISSUE THREAD

**Issue by maddoodles** [lutris/lutris#4538]
Hello, as per the title Lutris is giving me an error about not being able to find Xephyr when Xephyr options are turned on.

To reproduce: 
- Configure a game
- In system options, select a Xephyr setting (in my case I'm trying to use 16bit)
- Try to launch the game.

I can confirm that I have Xephyr installed on my system (Pop_OS 22.04). I have been able to use Xephyr on previous .deb versions of Lutris, I am currently using Flatpack version 0.5.11.

**Comment by danieljohnson2** [comment]
Could you try the latest .deb for Lutris?

I would not be surprised if flatpak didn't support this sort of thing.

**Comment by maddoodles** [comment]
> Could you try the latest .deb for Lutris?
> 
> I would not be surprised if flatpak didn't support this sort of thing.

It was in fact a flatpak issue, thank you.

**Comment by strycore** [comment]
using Xephyr is deprecated, use Gamescope instead.
