### ISSUE TITLE
Adding an "unspecified" option to the Vulkan ICD Loader may be useful, which would allow switching graphics cards in-game

### ISSUE THREAD

**Issue by SwimmingTiger** [lutris/lutris#4540]
I added an new option `Unspecified (Use System Default)` to the Vulkan ICD Loader in my lutris fork:

https://github.com/winegame/lutris/commit/27459c209f59db1087e46018d3898dc88ec3a1cd

```
choices.append((_("Unspecified (Use System Default)"), ""))
```

![图片](https://user-images.githubusercontent.com/4986069/193632861-85c19c41-540f-42da-9cf7-97c020af3368.png)

Then I can switch graphics cards in-game, just like in Windows. This option may be useful compared to existing AMD/Intel/NVIDIA. Because once a specific graphics card is selected, other graphics cards disappear from the game menu.

![图片](https://user-images.githubusercontent.com/4986069/193629776-02593d07-408f-4a53-90b4-fae5003d8d8f.png)

![图片](https://user-images.githubusercontent.com/4986069/193629853-3e75371a-3b14-477d-8f2a-0105b58fc993.png)

**Comment by danieljohnson2** [comment]
That seems like it might be a good idea; perhaps you should pop a PR about it.

**Comment by strycore** [comment]
PR merged
