### ISSUE TITLE
Overwatch 2 Crash

### ISSUE THREAD

**Issue by MiMillieuh** [lutris/lutris#4543]
Hello, I noticed that Overwatch 2 crashed on Fedora 36 / 37 without any reasons after a few minutes or after a few seconds, it's random.

Logs : 
https://pastebin.com/KwYkgypQ

Demostration : 
https://youtu.be/lkJoLqYV01Q

**Comment by Smoukus** [comment]
OW2 currently only works with Caffe 7.18 runner.
All other runners cause it to crash.

**Comment by MiMillieuh** [comment]
> OW2 currently only works with Caffe 7.18 runner ([this one](https://github.com/bottlesdevs/wine/releases/tag/caffe-7.18)). All other runners cause it to crash.

Thanks for your reply,

It ended up crashing also with Cafe 7.18 sadly...

**Comment by Azunyan-** [comment]
Also on Fedora, seems like I have the same issue.

**Comment by MiMillieuh** [comment]
> > OW2 currently only works with Caffe 7.18 runner ([this one](https://github.com/bottlesdevs/wine/releases/tag/caffe-7.18)). All other runners cause it to crash.
> 
> Thanks for your reply,
> 
> It ended up crashing also with Cafe 7.18 sadly...
> 
> Edit : it's not crashing any more but it has significant frame drops instead after the same few moments

Update on it, it's working fine it's the framedrop is just du to that poor nvidia driver that it really just a mess

Cafe 7.18 fixed it I just miss configured Lutris.

So framedrop related to this : https://github.com/NVIDIA/open-gpu-kernel-modules/issues/367
