### ISSUE TITLE
Games added through Steam don't show up with images

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4545]
https://user-images.githubusercontent.com/48409293/194724421-9f98f324-3fe6-48f5-b67d-de7879834915.mp4

Video explains the problem.

Basically I pressed the `refresh` symbol next to the Steam source. The games got recognized as installed, and are able to be found when searching for them in `Steam` and `Games` tab.

`Steam` tab shows those games with their proper images, but `Games` tab shows them as no image.

**Comment by Sid127** [comment]
After some investigation, I found that lutris was facing 404 errors downloading banners for some steam apps. In addition, banners for affected apps weren't being downloaded from Lutris' database too.
Lutris is using multiple folders for banners. Steam tab uses banners from `~/.cache/lutris/steam/banners`, while the Games tab uses it from `~/.cache/lutris/banners`. Banners for most games exist in both places, but some games have entries only in the steam banners folder.

I found a temporary fix for this, documented below:
```
rm -rf ~/.cache/lutris
(launch lutris once, press refresh button on steam, close lutris)
rm -rf ~/.cache/lutris/steam/banners
ln -s ~/.cache/lutris/banners ~/.cache/lutris/steam/
(launch lutris again, press refresh on steam again. This should make banners consistent between both tabs)
```
I think it'd be better for lutris to link all cache folders to the same place, to make banners consistent across tabs and to prevent issues such as this one.

I have also attached lutris debug logs from the first launch in my temporary fix, right after deleting the cache folder, in case they're required.
[lutris.log](https://github.com/lutris/lutris/files/10097827/lutris.log)

**Comment by danieljohnson2** [comment]
I don't think linking these directories together is a good idea. The banners are sometimes of different sizes for different services.

**Comment by Sid127** [comment]
The banner viewports (if that makes sense) are all of the same size in lutris though, I fail to see how banners being a different size will make a difference

**Comment by danieljohnson2** [comment]
Compare the 'Lutris' size:
![image](https://user-images.githubusercontent.com/6507403/204141671-c2443549-3858-499f-9440-e73544bf47d7.png)
And the 'GOG' size:
![image](https://user-images.githubusercontent.com/6507403/204141687-2b7eeac2-757a-4f3a-9d36-8c7966e4b29b.png)

The GOG banners are taller. GOG is shown at the 'medium' size, but none of the sizes match Lutris banners.

**Comment by Sid127** [comment]
I see... Either way, I think having a fallback way to grab the images would be a good idea. Maybe get something off of https://steamgriddb.com ?

**Comment by strycore** [comment]
Our initial banner format was based from the Steam format (184x69). That's the only format we can potentially share. 

Lutris should download banners from the website and if the Steam ID associations with a game are correct, the banner should appear in both Steam and Game sections.

**Comment by exit91** [comment]
I had the same problem and accidentally solved it by pressing the three buttons in the screenshot below.
This doesn't feel intuitive to me at all, because they look like "clear" or "reset" buttons and even the tooltip only says "Remove custom cover art/banner/symbol".

![grafik](https://github.com/lutris/lutris/assets/3222/70e02ee0-2f9d-4b17-9fa6-0eba04e03cd9)

**Comment by danieljohnson2** [comment]
You are not supposed to need to use those reset buttons for this; Lutris should download the media when you install the game, or if you change the 'Identifier'. But perhaps there's a bug.

I'd ask how you installed this game, with the media missing.

**Comment by strycore** [comment]
> I'd ask how you installed this game, with the media missing.

By syncing installed Steam games.

**Comment by hedgehog1029** [comment]
Indeed, I have this same issue: when importing from Steam by using the refresh button, everything looks OK in the Steam source page...

![Lutris steam source page](https://github.com/lutris/lutris/assets/3532945/ae7ef490-155e-4def-82e9-3a31f010378f)

... but over on the Games tab, they're all missing images (Cogmind is non-steam, manually added):

![image](https://github.com/lutris/lutris/assets/3532945/b3b63563-45d0-48df-b8b1-7fb47e4e314c)

**Comment by danieljohnson2** [comment]
I am not seeing anything funny about the Steam media. Is it just Steam, or do you have trouble with itchio, GOG, or whatnot?

I think maybe you should post debug log for this. Run lutris at the terminal via ``lurtis -d`` and click that refresh button, then post the terminal spam here.

**Comment by hedgehog1029** [comment]
@danieljohnson2 It's the same with games installed from itch.io, for example.

I spent a while last night querying the sqlite database and reading through the code, here's my conclusions:

1. when games are imported from Steam, `BaseService#load_icons` is called, which caches all the *Steam* media (as the SteamService has `medias` set)
2. when on the Steam runner page, the `ServiceMedia` is a `SteamBanner`, so it's reading from `.cache/lutris/steam/banners/`. These appear to be populated correctly by the reload.
3. when on the Library page, the `ServiceMedia` defaults to `LutrisBanner`, which tries to read from `.cache/lutris/banners`. Since only the Steam media was downloaded, and not the Lutris media, the targeted banners don't exist on disk.
4. clicking the "custom image reset" button calls `download_lutris_media`, which downloads the media to the correct path, resolving the issue.

**Comment by danieljohnson2** [comment]
Hmm. Okay, I see it now.  You are getting your games installed when you refresh Steam; this code-path does not install the Lutris media at all. We are supposed to install media for specific games as they are installed but this one seems to have been missed.

I've added code for all the services that can install games this way to also download media for *newly installed*  games.

Please test this for me, @hedgehog1029! Download the latest master and run the bin/lutris script within- no need to install.

Indeed, you probably need to completely remove some of these Steam games from your Games view, then refresh Steam. These games should be re-installed and should have their media now. Does it work?

If so, you can get the other missing media too- there's a "Download Missing Media" button to be found in the "Preferences" dialog in master, that will fill in any that are missing. But please test the fix before using that!

**Comment by hedgehog1029** [comment]
Importing seems to work correctly now on latest master :100:
