### ISSUE TITLE
[Flatpak] Unable to Launch Containerized Games

### ISSUE THREAD

**Issue by qstambaugh** [lutris/lutris#4546]
Currently, with Lutris 0.5.11 installed through Flatpak, you can't launch other Flatpaks or AppImages, at least not without some tweaking under Flatseal.

**Comment by gwhizoftv** [comment]
Is this saying that once Lutris is installed, ALL of Flatpakl is broken? Please clarify

**Comment by qstambaugh** [comment]
Oh no, sorry. I mean that the flatpak version of Lutris can not launch other flatpaks or AppImages itself by default. For example: If you use the flatpak version of Lutris to install OpenRA (which is prepackaged as an AppImage) you won't be able to launch OpenRA using the flatpak version of Lutris

**Comment by strycore** [comment]
We now have support for both Flatpaks and AppImages in the Lutris Flatpak
