### ISSUE TITLE
wine-wl support

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [lutris/lutris#4548]
https://gitlab.collabora.com/alf/wine/-/tree/wayland
https://aur.archlinux.org/packages/wine-wl-git
I know it hasn't even been released yet, but will there ever be support for pure wayland wine?

**Comment by danieljohnson2** [comment]
Gee, that gitlab repo's last commit was 10 months ago; that does not look active.

**Comment by nvidiaLinuxUser** [comment]
@danieljohnson2 Oh, I didn't notice that. In that case, I think we should wait for official wayland support in wine
