### ISSUE TITLE
Selecting Incorrect Updates for Game Installs and "Removing Files" Uninstalls Game Instead of the Associated Update

### ISSUE THREAD

**Issue by ThisNekoGuy** [lutris/lutris#4549]
I'll go over the order of events first to make this clear:

1. Some time ago, (maybe a year ago? Can't remember) I installed Ghostrunner from GOG via Lutris
2. Just now, not knowing what version of the game I originally installed, I attempted to install a GOG game update via the Lutris feature
3a. I chose the bottom-most / oldest update version, assuming I had to apply the patches in order
3b. Off-topic but noted: When doing this, my Wine selection was overridden by Lutris to use something else (which was not desired)
4. When the updater ran, it informed me that it was not for this version of the game, so I canceled the installation in the installer
5. The Lutris dialogue window recieved a 512 error code (if I remember correctly) and, that window didn't close, so I clicked the close-window button via the window manager (Kwin)
6. Lutris asked me if I wanted to remove the game files: _I had thought Lutris meant the associated updater download files, so I opted for yes_
7. Lutris instead, contrary to my expectation, deleted the game off my system instead... :|

By now, I'm sure it's clear that this is unintended and very clearly not helpful to the user experience...
Either this should be more clear, or this should (**_preferably_**) actually perform the requested operation in the context of the associated action rather than "globally" to the entire game installation...

**Comment by danieljohnson2** [comment]
That does not seem ideal. But let me ask- was the "Remove game files" checkbox pre-checked for you? It should not have been.

**Comment by ThisNekoGuy** [comment]
No, it wasn't pre-checked; but again, I had expected it to be in the context of the current operation (the downloaded data that didn't install) rather than the entire game itself...

**Comment by danieljohnson2** [comment]
I agree. I've tweaked the installer window to not even show this option for updates or DLC.
