### ISSUE TITLE
Lutris 0.5.11, Exit with return code 256

### ISSUE THREAD

**Issue by Wolfsorgil** [lutris/lutris#4552]
Hello,
This is a repeat of an issue recorded with earlier lutris versions, but seems to stil occur with the most current version. All attempts to install Battle.net result in an "Exit with return code 256" then hang on the Ariel font installation. All dependencies have been installed and updated and I am running the most current form of Linux Mint. The following is the install log that Lutris provides:

> Started initial process 69858 from /home/user1/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
> Start monitoring process.
> Executing mkdir -p /home/user1/Games
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> ------------------------------------------------------
> WINEPREFIX INFO:
> Drive C: total 28
> drwxrwxr-x  7 user1 user1 4096 Oct 10 09:19 .
> drwxrwxr-x  4 user1 user1 4096 Oct 10 09:20 ..
> drwxrwxr-x  3 user1 user1 4096 Oct 10 09:18 ProgramData
> drwxrwxr-x  6 user1 user1 4096 Oct 10 09:18 Program Files
> drwxrwxr-x  6 user1 user1 4096 Oct 10 09:19 Program Files (x86)
> drwxrwxr-x  4 user1 user1 4096 Oct 10 09:18 users
> drwxrwxr-x 21 user1 user1 4096 Oct 10 09:20 windows
> 
> Registry info:
> /home/user1/Games/battlenet/system.reg:#arch=win64
> /home/user1/Games/battlenet/user.reg:#arch=win64
> /home/user1/Games/battlenet/userdef.reg:#arch=win64
> ------------------------------------------------------
> ------------------------------------------------------
> warning: /home/user1/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
> ------------------------------------------------------
> Monitored process exited.
> Initial process has exited (return code: 256)
> All processes have quit
> Exit with return code 256
> 

I checked the to make sure I had a 32 bit Wine prefix set up before posting, but found Lutris appears to try to reconfigure it to 64 bit then throws the same Wine prefix error shown above. The following is some basic system information:

> [System]
> OS:              Linux Mint 21 Vanessa
> Arch:            x86_64
> Kernel:          5.15.0-48-generic
> Desktop:         MATE
> Display Server:  x11
> 
> [CPU]
> Vendor:          AuthenticAMD
> Model:           AMD Phenom(tm) II X4 955 Processor
> Physical cores:  4
> Logical cores:   4
> 
> [Memory]
> RAM:             11.7 GB
> Swap:            1.7 GB
> 
> [Graphics]
> Vendor:          AMD
> OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.0-48-generic)
> OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.5
> OpenGL Core:     4.6 (Core Profile) Mesa 22.0.5
> OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.5
> Vulkan:          Supported

What should I be attempting next to make this function?

**Comment by Jdelefosse** [comment]
I know it will sound weird, but try installing bnet through Gnome to see if it's working.
I have this error as well, and saw in a previous bug report that under Gnome it wasn't a problem.
I tried under AwesomeWM, i3, Openbox and KDE and couldn't install anything. I installed Gnome for the test and it worked correctly.
I hope this is a bug that'll be correct in the future.

**Comment by Wolfsorgil** [comment]
Installed Gnome and attempted a battle.net install, and came to the same result. Exit with return code 256, then hangs at Ariel font install. Only difference was Gnome reached it slower.

**Comment by leo-lb** [comment]
I got the same issue, can't tell where it comes from

**Comment by stefanow30** [comment]
I had similar problem. Fortunately the solution is simple - just delete ".wine" folder in your Home; it will be recreated and then it will proceed without errors.

**Comment by GamerGoat112** [comment]
Sadly, that is only a temporary fix. There needs to be a permanent one. Or at least long lasting.

**Comment by legluondunet** [comment]
Hello, battle.net script recently updated, could you test it and tell us if this issue is still relevant?
If the issue is still present, please post your terminal log (lutris -d).

**Comment by strycore** [comment]
I have confirmation for several sources that Battle.net installs and runs fine on the current version.

**Comment by bigkrp** [comment]
I had error 256, while trying install from [here](https://lutris.net/games/starcraft-ii/)


```
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_tahoma 
grep: warning: stray \ before /
Executing cd /home/krp/.cache/winetricks/tahoma
Downloading https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB to /home/krp/.cache/winetricks/tahoma
wget: /home/krp/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by wget)
wget: /home/krp/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by wget)
wget: /home/krp/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by wget)
Executing cd /home/krp/.cache/winetricks/tahoma
Downloading https://web.archive.org/web/2000/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB to /home/krp/.cache/winetricks/tahoma
wget: /home/krp/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by wget)
------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB failed
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
Started initial process 32080 from /usr/bin/bash -c WINEPREFIX="/home/krp/Games/battlenet" "wine" "/home/krp/Games/battlenet"/drive_c/Battle.net-Setup.exe
Start monitoring process.
0154:err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256

```
