### ISSUE TITLE
Lutris not respecting Runner selection

### ISSUE THREAD

**Issue by ChiefGyk3D** [lutris/lutris#4555]
Been trying for several days to get [Battle.net](https://battle.net/) installed via Lutris, but for some reason I keep getting a 404 error on Pop!_OS 22.04 and can't seem to make it work with the Lutris script for [Battle.net](https://battle.net/) or Overwatch 2. I can't think of anything further and yes I did even try disabling IDS/IPS in PfSense as well as I have whitelisted *.blizzard.com and *.battle.net in the firewall.

"lutris-wrapper: /home/chiefgyk3d/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine

Started initial process 6515 from /home/chiefgyk3d/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/chiefgyk3d/.var/app/net.lutris.Lutris/cache/lutris/installer/overwatch-2/setup/Battle.net-Setup.exe

Start monitoring process.

fsync: up and running.

<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="[http://www.blizzard.com/404](http://www.blizzard.com/404)">here</a>.</h2>

</body></html>

GIF89aInitial process has exited (return code: 0)"

I have installed Caffe, but can't seem to get it installed using Caffe and seems to use the Lutris runner from the overwatch 2 installation script. https://lutris.net/games/overwatch-2/

**Comment by ChiefGyk3D** [comment]
Seems for some reason, Lutris is not respecting the default Runner setting.

**Comment by danieljohnson2** [comment]
Which default runner setting is not being respected?

Have you tried the master branch? It should be better about runner settings during install.

**Comment by ChiefGyk3D** [comment]
Here is a pastebin of my most recent issues installing it 
https://pastebin.com/wCup4p1w
![image](https://user-images.githubusercontent.com/19499446/195397444-f4a33c4e-80e8-411e-b7c7-a5491cf43cd2.png)

**Comment by ChiefGyk3D** [comment]
Nope @danieljohnson2 I tested it pulled from master, I got the same result running the Overwatch install script. It is still trying to use the Lutris 7.2.2 runner, instead of the Caffe 7.18 that has been selected and is even specified in the yaml file

**Comment by danieljohnson2** [comment]
I think I understand; you are setting the WINE version in the WINE runner options, and it does affect installation, so if the installer fails it won't help.

This is known issue; my last attempt at it went sideways, and we're too close to release to risk another try.

But I do not think 'Caffe 7.18' is a WINE build that Lutris supports. You'll have to hack it in. Maybe you can replace the latest lutris version of WINE with it, the one it is using by default, and that would cause it to be used?

**Comment by ChiefGyk3D** [comment]
That's what I am trying to figure out, a little blind here so if I can be pointed at how I can hack it in, that would be much appreciated.

**Comment by danieljohnson2** [comment]
If you have Caffe 7.18- I don't know where to get it- then try this.

Rename the directory '~/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64' to something like 'lutris-fshack-7.2-x86_64 (old)'.

Now, place Caffe 7.18 in its place. It should be in a directory with that exact path. I think you should wind up with a file at
'~/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine', but it will now be the Cafe version of that file.

Now, start Lutris and try the install. Cross your fingers!

After this is done, whether it works or not, reverse this procedure. Remove Cafe and rename that 'lutris-fshack-7.2-x86_64 (old)' to 'lutris-fshack-7.2-x86_64' to restore the balance of the cosmos.

Good luck!

**Comment by bell07** [comment]
Is the issue duplicate for #4370 ?
