### ISSUE TITLE
Lutris PPA for Ubuntu is gone?

### ISSUE THREAD

**Issue by dtantono** [lutris/lutris#4558]
Hi
I tried to add PPA for Ubuntu. But the output is:
Cannot add PPA: 'ppa:~lutris-team/ubuntu/lutris'.
The team named '~lutris-team' has no PPA named 'ubuntu/lutris'
Please choose from the following available PPAs:
and I opened the URL https://launchpad.net/~lutris-team/+archive/ubuntu/lutris is gone.
What happened?

**Comment by ehickox** [comment]
https://github.com/lutris/lutris/issues/4296#issuecomment-1278177212

**Comment by danieljohnson2** [comment]
The PPA has been removed because it was not being maintained; no new releases were going out. You may as well use the .deb or the flatpak, if your distro does not carry Lutris.

**Comment by gerardlouw** [comment]
Using a slightly modified version of the official Debian installation instructions on https://lutris.net/downloads worked for me.

I just replaced `sudo tee /etc/apt/trusted.gpg.d/lutris.asc` with `sudo apt-key add -`.

So the full set of commands becomes:
```
echo "deb https://download.opensuse.org/repositories/home:/strycore/Debian_11/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_11/Release.key -O- | sudo apt-key add -
sudo apt update
sudo apt install lutris
```

This allowed me to upgrade from `0.5.10.1~ubuntu20.04.1` to `0.5.11`, which is working just fine.

**Comment by muzena** [comment]
@danieljohnson2 
Who is maintainer of lutris PPA?
I made a [Lutris PPA ](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/lutris)
If you want you can add me in Launchpad Lutris team, So I can fix PPA.

**Comment by alson** [comment]
@gerardlouw The procedure from [https://lutris.net/downloads](https://lutris.net/downloads) worked fine for me on Ubuntu 22.04, and Lutris installed from there runs well. Putting the key in `/etc/apt/trusted.gpg.d/lutris.asc` works, although as described in the AskUbuntu link you posted is not the recommended method.

**Comment by danieljohnson2** [comment]
@muzena, I don't know who the maintainer was, but I understand @strycore can't contact him anymore.

If you want to maintain the lutris-team PPA, I'll flag down @strycore and see if he's willing. The thing needs to get updates when new Lutris versions come out.

**Comment by enigma9o7** [comment]
> @danieljohnson2 Who is maintainer of lutris PPA? I made a [Lutris PPA ](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/lutris) If you want you can add me in Launchpad Lutris team, So I can fix PPA.

Can you have it  build for bionic too (unless technical reason)? (your ppa and/or the old one if you revive it - the old PPA did have bionic builds, and 18.04LTS is still officially supported by Ubuntu til April next year) 

Thanks much.

**Comment by muzena** [comment]
@danieljohnson2 

> If you want to maintain the lutris-team PPA, I'll flag down @strycore and see if he's willing. The thing needs to get updates when new Lutris versions come out.

Ok.

@enigma9o7 
Bionic build is broken, too old dependencies.

**Comment by danieljohnson2** [comment]
Do you mean you want to maintain the PPA and I should flag down @strycore?

**Comment by strycore** [comment]
I've re-created a PPA with the same URL as the old one. @muzena, you're also added as a maintainer.

Please keep in mind that that goal here is to automate publication to the PPA so it is done (semi-)automatically when we release a new version.

There is an `upload-ppa` rule in the Makefile but this only pushes to one Ubuntu release (the one present in the Debian changelog). We should adapt this to push to all supported Ubuntu series. 
Alternatively, we can setup github actions and push to the PPA from there but the process becomes a bit more involved and we have to be careful only to push final releases and not betas.

**Comment by strycore** [comment]
The PPA is outdated again. We need automation to push packages to the PPA as soon as the release is pushed to Github.

**Comment by strycore** [comment]
@Amaylia that's really cool! 
I'll setup a lutris-staging ppa so we can start testing this since there are no immediate plans for a release
