### ISSUE TITLE
[Feature Request] Search for installers in the Search Games bar

### ISSUE THREAD

**Issue by adro79** [lutris/lutris#4562]
It would be an improvement to suggest installers in the search bar. Would give more utility for the ones who doesn't have that many games installed.
Also it would be a more logic access to installers if you're new to the GTK language.

**Comment by danieljohnson2** [comment]
What kind of search would this even be? Would I search for "GOG (auto-generated)" and find the installers auto-generated by Lutris?

Maybe an example of how this would work would help.

**Comment by adro79** [comment]
My idea would suggest other installers after the ones in the user library.

![suggestion](https://user-images.githubusercontent.com/57686179/196001538-253c7476-baef-46c1-8ad0-bb65dff72fea.png)

For example in this case should be faster installing Retroarch games of the same series. Or searching for games like you would do in the Lutris website.

**Comment by danieljohnson2** [comment]
Oh, I see. You want to search the GOG website for the stuff you don't even own yet.
 
There's something sort-of like what you want. Hit the [+] button in the corner and click the "search the Lutris website" option. You get this:
![image](https://user-images.githubusercontent.com/6507403/196002019-46ed2a0b-0423-485d-a1ed-37bed7382311.png)
That searches Lutris.net, not GOG.com. But not too dissimilar.

I don't like the alternative UI you propose though; it feels too much like advertisements for my comfort. I know where GOG.com is if I want it.

**Comment by adro79** [comment]
My idea is adding this results in the main search. If you don't like it there might be an option to disable it, but for new users would suppose a few less clicks.

**Comment by julikaiba** [comment]
agreed, i always forget this doesnt work and search in the search bar instead of clicking plus first. I think this was already possible at some point in the past

**Comment by danieljohnson2** [comment]
There sort of was; you had to switch to "Community Installers" mode and it would do that.

@strycore, however, ruled otherwise. He wanted the [+] and dialog that you now see. I don't think that's going to be reversed anytime soon.

**Comment by strycore** [comment]
When / If we move to something better and more flexible than Gtk we can envision more elegant UIs.
