### ISSUE TITLE
[Feature Request] Allow detailed view of installer window YAML / stdout 

### ISSUE THREAD

**Issue by mdeguzis** [lutris/lutris#457]
I was installing Uplay and had no idea what was going on while "Installing game data" kept spinning. Currently waiting for it to finish. It would be highly beneficial if we could get a > (right carrot) that is clickable or some button to show the background shell process / anything that is running. The  best comparison is how Debian-based distros present the installer. You don't seen anything but the top-level text unless you click the arrow and expand it. I'd rather know what is going on so I know if the script installer is hanging at a certain point.

**Comment by strycore** [comment]
We now have the console output displayed on the installer window and there is a button to view the YAML script
