### ISSUE TITLE
Please add new window adaptation from new GTK 4 Gnome 43

### ISSUE THREAD

**Issue by bpavuk** [lutris/lutris#4570]
https://youtu.be/fW_IR0SQA8Q Here is the video demo of a thing I talk about

**Comment by danieljohnson2** [comment]
I don't know that Lutris is ready to take a dependency on GTK 4.

**Comment by bpavuk** [comment]
What about using mechanism "if-not-this-then-that"? For example, GTK4 not installed, then use v3

**Comment by bpavuk** [comment]
Sorry, accidentially closed

**Comment by danieljohnson2** [comment]
I doubt that'll work out; GTK is not terribly fond of being compatible, and I think we'd need a lot of changes to get on GTK 4, when we decide we want to do that.

**Comment by bpavuk** [comment]
What's the lang GUI of Lutris written?

**Comment by danieljohnson2** [comment]
It is written in Python 3.

**Comment by bpavuk** [comment]
Nice

**Comment by danieljohnson2** [comment]
I think so; that's one reason I started contributing to Lutris.

**Comment by bpavuk** [comment]
Hmph, what 'bout Kotlin GUI? Buuut... Is GTK can be used in Kotlin?

**Comment by danieljohnson2** [comment]
I 'unno. I'm not to strong on Kotlin. Can that be used without a JVM?

**Comment by bpavuk** [comment]
Kotlin/Native may be in beta, but Linux progs it compiles very well. Shindows has problems, but who needs that?

**Comment by bpavuk** [comment]
Btw, I'm just learning it for now, but maybe I'll return to Python for making PR with with "if-not-this-then-that" mechanism for Lutris GTK3/4

**Comment by bpavuk** [comment]
Where is Lutris' GUI code? In which folder?

**Comment by bpavuk** [comment]
I'd like to make another branch, where people will choose what to use. If they'll use gtk4, they'll download needed package, else standard package

**Comment by danieljohnson2** [comment]
If you want to try convert to GTK 4, you should fork the repository. I think this will be challenging, but you could learn a lot even if you fail.

The GUI code is largely in the lutris/gui directory, but there's stuff in the share directory too.

I imagine that Lutris will want to move to GTK 4 when it is available widely enough that this won't cause issues for the users.

I don't think we want something that switches between GTK 3 and GTK 4 dynamically; that seems like too much complexity for too little gain.

**Comment by strycore** [comment]
The widget demoed is not only Gtk4 but also part of libawaita afaik. He can keep track of this in #3886
