### ISSUE TITLE
Origin integration login redirecting to new EA App

### ISSUE THREAD

**Issue by CHFernandes** [lutris/lutris#4576]
Hello guys, so I was refreshing my lutris to pick up some newly installed games through the store and I noticed origin redirecting to the new EA App:

The login page inside lutris opens as normal:
![image](https://user-images.githubusercontent.com/20386403/197666380-880dcad3-38a6-49aa-9db9-a26cb4df3c41.png)

However, after loggin in, it redirects me into the new EA App:
![image](https://user-images.githubusercontent.com/20386403/197666504-c1be05ad-54eb-4cbb-ab1e-c52b1730c108.png)

Is the lutris integration with origin dead due to the new ea app?
How is going to be for our games in the origin store?

I am out of the loop concearning this new store, considering he kernel level anti-cheat that they made also being migrated to the ea app it does makes me worried

I hope that someone could cast a light upon this issue, it does appear to be rather recent

**Comment by Annoiied** [comment]
Same here! Its actually preventing me from using Origin entirely :(

**Comment by jsztojka** [comment]
A workaround i found that works for me, is to change your User Agent.
Clone the repo, and make sure you can launch by navigating to the bin folder and running lutris from there.
If that works, edit the file lutris/gui/dialogs/webconnect_dialog.py. There is a variable called DEFAULT_USER_AGENT on line 16. 
Just add QtWebEngine/5.8.0 after Firefox/100.0 so the whole thing looks like this: 
"Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0 QtWebEngine/5.8.0"
If you then start lutris again, you should be able to sign in.

**Comment by danieljohnson2** [comment]
We can be a bit more precise than that; I've put together a branch that applies that user agent only for Origin.

[It's right here](https://github.com/lutris/lutris/tree/dj/origin_user_agent)

Please download that code and run the bin/lutris script within. Try to log in. If that works for you, I'll merge these changes.

**Comment by danieljohnson2** [comment]
Can anybody with an Origin account test my branch? Anybody? @CHFernandes? @Annoiied?

The 0.5.12 release should be happening soon. I'd like this to be fixed by then, but I can't test this myself.

**Comment by CHFernandes** [comment]
@danieljohnson2 It indeed worked for me, thank you sooooo much! (Sorry for not responding earlier I really hadn't recieved a notification)

![image](https://user-images.githubusercontent.com/20386403/203022446-7df78d8a-07c5-459c-956f-9cd958c76ac4.png)

**Comment by danieljohnson2** [comment]
Good enough! Declaring victory! Branch merged! Thank you @CHFernandes1

**Comment by tegaidogun** [comment]
> We can be a bit more precise than that; I've put together a branch that applies that user agent only for Origin.
> 
> [It's right here](https://github.com/lutris/lutris/tree/dj/origin_user_agent)
> 
> Please download that code and run the bin/lutris script within. Try to log in. If that works for you, I'll merge these changes.

Your link is invalid.

**Comment by jsztojka** [comment]
@tegaidogun You don't need the link anymore.
The Fix has already been merged, and even released. 
If your Distro doesn't package [5.12](https://github.com/lutris/lutris/releases/tag/v0.5.12) yet, you can use the master branch or if you use a Debian or derived Distro you can use the Deb File from the Releases page.

**Comment by lobneroO** [comment]
I just installed Lutris for the first time on Arch Linux. It was 5.11 at first, so I updated to 5.12, but I still get the EA App screen I can't get rid of

**Comment by jsztojka** [comment]
@lobneroO That's weird, I managed to reconnect without issues with 5.12.
Maybe your old User Agent from 5.11 is still cached somehow. Altough I don't know enough about that to know if that's even possible. 

@tegaidogun The Flatpak should already be at 5.12

**Comment by jsztojka** [comment]
@lobneroO Did you maybe mean the EA App Prompt once origin is launched?
That's an entirely different thing. I would suggest making a new Issue for that.
Origin is apparently no longer supported by EA.

**Comment by Spurlos** [comment]
Having the OP issue, althou im already on 5.12 (upgraded from some older version month ago)

Can we consider re-opning this issue, as it looks like the upgrade path is still not tested (improper cache invalidation probably)

![image](https://user-images.githubusercontent.com/667533/217923952-f6de328b-2e19-483c-9584-9d255d3a4f5e.png)
![image](https://user-images.githubusercontent.com/667533/217923991-d2b290dc-afd1-4219-9bad-48a78a6562c9.png)

**Comment by hughesjs** [comment]
Yeah, this hasn't been solved, I'm still having the same issue on 0.5.12 on a fresh system install, so there's definitely nothing cached

**Comment by nicolabaesso** [comment]
For everyone facing this issue, or atleast until it really get fixed:

1. Run Origin
2. Install the EA Desktop app as forced
3. Leave the same path (or change the following instructions accordingly)
4. Complete the installation (do what required, so login ecc...)
5. Close everything related to Origin and EA
6. From this point on, if you try to run Origin it will not found the .exe. This is because the EA Desktop app removes by default Origin (and you cannot change it). So, go to the configuration file at /home/YOUR_USERNAME/.config/lutris/games (changing YOUR_USERNAME with your actual username)
7. The file you're interested in is called something like "origin-latest-1676137843.yml" (it may change, be sure it's origin)
8. We need to change the "exe:" voice, specifically:
game:
   exe: /media/YOUR_USERNAME/Games/Origin/drive_c/Program Files (x86)/Origin/Origin.exe
 ...
script:
   files:
      ....
   game:
      exe: $GAMEDIR/drive_c/Program Files (x86)/Origin/Origin.exe
Change the path from "drive_c" with drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EADesktop.exe

You should now good to go!
The only issue with this is that it doesn't start the download by default, but at least you can use it...
Hope it helps.
