### ISSUE TITLE
Lutris froze while file manager was opened using "Browse files".

### ISSUE THREAD

**Issue by tuantran1632001** [lutris/lutris#4578]
Lutris froze when pressing "Browse files" button of any game, but doesn't seem to crash. It remained unresponsive until the file manager, in this case Dolphin, closed. However, while Lutris was "unresponsive", if I clicked anywhere in the GUI, after closing the file manager, all the interactions were registered all at once. The log didn't show any thing special.

System infos:
OS: Arch Linux
DE: KDE Plasma, with Dolphin as the file manager.
Lutris version 0.5.11

**Comment by danieljohnson2** [comment]
Do you mean the "Browse files" menu item? If so, that is very strange.

If you are seeing an actual "Browse" button, this may be an issue I've worked on. Try the [beta of 0.5.12](https://github.com/lutris/lutris/releases/tag/v0.5.12-beta1) and see if that helps.

Though even now the 'Browse' buttons are a bit sketchy.

**Comment by tuantran1632001** [comment]
> Do you mean the "Browse files" menu item?
Yes, that one.

> Try the [beta of 0.5.12](https://github.com/lutris/lutris/releases/tag/v0.5.12-beta1) and see if that helps.
No, it doesn't help. Same behavior happened.

However, I found out that Lutris doesn't freeze if the file manager is already opened before.

**Comment by danieljohnson2** [comment]
I have a theory; maybe on your system xdg-open will communicate with an open file browser process, but if none is found, will execute the file browser and won't exit until it does.

[Here's a branch](https://github.com/lutris/lutris/tree/dj/nonblocking-xdg-open) that makes this operations non-blocking on Lutris' end, at the cost of not logging errors. Please try it and see if it helps.

You do not need to install this branch. Download it, and run the "bin/lutris" script within.

**Comment by tuantran1632001** [comment]
Yes, that fixed it.

**Comment by danieljohnson2** [comment]
Alright; I'll merge that fix.
