### ISSUE TITLE
Error launching SNES ROMs with Snes9x/Libretro runner

### ISSUE THREAD

**Issue by solbero** [lutris/lutris#458]
I'm having trouble launching SNES ROMs with the Snes9x core through the Libretro runner, It worked fine earlier, so I wonder if it is the 4.4.1 update that has changes something. I have tried deleting the runner and reinstalling it, and I have also tried deleting retroarch.cfg.

I have installed Lutris from the PPA supplied on your website.

Some system information:

:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

:~$ uname -r
4.4.0-53-generic

The terminal output from Lutris when I try to launch a ROM:

:~$ lutris -d
DEBUG    2016-12-17 22:42:24,582 [system]:Executing which steam
DEBUG    2016-12-17 22:42:24,586 [system]:Executing which /home/[hostname]/.local/share/lutris/runners/desura/desura
WARNING  2016-12-17 22:42:24,608 [winesteam]:wine is not installed
DEBUG    2016-12-17 22:42:25,610 [runtime]:Runtime steam is up to date
DEBUG    2016-12-17 22:42:25,610 [runtime]:Runtime lib32 is up to date
DEBUG    2016-12-17 22:42:25,611 [runtime]:Runtime p7zip is up to date
DEBUG    2016-12-17 22:42:25,611 [runtime]:Runtime lib64 is up to date
INFO     2016-12-17 22:42:25,611 [lutriswindow]:Connected to lutris.net as [username]
DEBUG    2016-12-17 22:42:25,614 [api]:Fetching game library
DEBUG    2016-12-17 22:42:25,649 [steam]:Watching Steam folder /home/[hostname]/.steam/steam/steamapps
ERROR    2016-12-17 22:47:17,258 [jobs]:Error while completing task <bound method libretro.prelaunch of <lutris.runners.libretro.libretro object at 0x7f40b2b44198>>: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
<class 'TypeError'> int() argument must be a string, a bytes-like object or a number, not 'NoneType'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 161, in prelaunch
    firmware_count = int(core_config['firmware_count'])

**Comment by telanus** [comment]
tested and yes seems to be a problem, get the same type of error

**Comment by telanus** [comment]
Seems the Mupen64core also have the same problem:

```
ERROR    2016-12-24 19:11:20,979 [jobs]:Error while completing task <bound method libretro.prelaunch of <lutris.runners.libretro.libretro object at 0x7fc392492f98>>: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
<class 'TypeError'> int() argument must be a string, a bytes-like object or a number, not 'NoneType'
  File "~/src/lutris/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
  File "~/src/lutris/lutris/runners/libretro.py", line 161, in prelaunch
    firmware_count = int(core_config['firmware_count'])
```

**Comment by strycore** [comment]
This will affect any libretro core that doesn't use a firmware.
