### ISSUE TITLE
MESA: error: failed to load D3D12

### ISSUE THREAD

**Issue by jwilkeson** [lutris/lutris#4581]
After upgrading my OS, I get this error upon launching Lutris, `MESA: error: failed to load D3D12` everything else seems to work properly but it just doesn't find D3D12, `vkd3d-compiler -V` is `vkd3d shader compiler version 1.3 using vkd3d-shader 1.3 (Debian 1.3~focal-1)`, I'm using `AMD Mesa Driver 22.2.2` and I'm using `lutris-0.5.10.1` my OS is Ubuntu 20.04.5 LTS, what should I do so that it recognizes vkd3d12 again?

**Comment by msmalik681** [comment]
I am also having the same issue on pretty much the same system.

**Comment by jonasof** [comment]
I was using kisak-mesa ppa drivers at version 22.2.2 and got the same problem.

Then I removed kisak-mesa ppa with command `sudo ppa-purge -o kisak -s ppa.launchpad.net -p kisak-mesa`, then the mesa drivers got rollabacked to 22.0.5-0ubuntu0.1. Now this problem does not happen anymore.

I think it is some problem in the newer versions.

**Comment by NoxInmortus** [comment]
This command did the trick as well: `sudo ppa-purge -o kisak -s ppa.launchpadcontent.net -p kisak-mesa`

**Comment by jwilkeson** [comment]
I ran the above command, everything seems to work now so I'll close this.
