### ISSUE TITLE
Games not launching

### ISSUE THREAD

**Issue by e2002e** [lutris/lutris#4585]
Hi, I am using jellyfish Ubuntu 22 and cannot start any games. They all are marked as "launching" and double clicking on them yields a crash. The title is read_library_folder() contentstatsid keyerror

Also there is a hook_error
KeyError: CasperMD5json

**Comment by danieljohnson2** [comment]
Can you give us the debug log?

Run "lutris -d" and try to start a game; post the output here. I'm hoping for a trace-back.

**Comment by e2002e** [comment]
That is the main issue actually, the -d option is not displaying anything.
I only can watch the reports from Ubuntu which are not copy able,
I found a thread on the forum telling about removing dxvk_version file in ~/.local/share/lutris/runtime/dxvk/, did so and started lutris, which was outputting on the cmdline, and the games would not be marked as launching, but when clicking them error occured, and the stack trace came down to the contentstatsid keyerror from the steam/config.py

**Comment by e2002e** [comment]
IT WORKS ! Updated my system and rebooted !
