### ISSUE TITLE
Right-clicking games no longer works and the bottom strip no longer appears except for uninstalled games

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#4586]
The UI isn't working properly anymore - the bar at the bottom with the launch game button and the options doesn't show up anymore, and trying to right-click on games doesn't work either. The one exception for the bottom bar seems to be games that are in my library but not currently installed. I can still use the CSD top bar and the sidebar, and everything inside those seems to work fine, but the main window area seems to be completely broken at the moment. The one exception is the fact that double-clicking still launches games.

This used to be part of #4583 but then I realized it's probably an unrelated issue.

I'm running Lutris 0.5.11 in EndeavourOS.

**Comment by danieljohnson2** [comment]
I have an intuition that it is a related problem- the UI setup code is failing because your Steam VDF file is corrupt.

I've made a commit to defend against this. With this, you should get your UI except that some Steam related commands may be unavailable. And there will be log spam.

Please download the latest master code and try it; you need only run the "bin/lutris" script, no need to install a new Lutris to test this.

**Comment by hazelnot** [comment]
It does restore Lutris' functionality, but seems like I still get the error on startup, which I guess is fair. I realize this isn't particularly a Lutris-related question, but any idea how I'd fix my Steam VDF file? I don't even know what it _is_ in the first place :sweat_smile:

**Comment by danieljohnson2** [comment]
Nertz. That should have reduced the startup issue to log spam. If you want me to try again you'll have to provide more details about what is happening. A screenshot perhaps?

I don't know Steam too well, but I think you might try removing the 'shortcuts.vdf' file- I think the Steam client recreates it. If it doesn't you can always put it back.

You could also try uninstalling Steam and reinstalling it. Or do both at once.

**Comment by hazelnot** [comment]
![image](https://user-images.githubusercontent.com/10992973/199946375-1f57fafa-31db-4a28-8e9c-e2e3169d103b.png)
I just get this error message during the "Checking for runtime updates, please wait..." loading thing.

I'll try removing the shortcuts.vdf file though. If you delete literally anything from the Steam folder the client just redownloads/recreates it to the point where afaik you can just leave just the executable in the folder and running it will still recreate a full installation of Steam.

**Comment by danieljohnson2** [comment]
Oh, I see. I carelessly left in some debugging code that prevented the fix for working for startup. Should be fixed now.
