### ISSUE TITLE
“The application encountered an unrecoverable error” in Overwatch 2 

### ISSUE THREAD

**Issue by leikeze-max** [lutris/lutris#4588]
Since the launch of overwatch 2, all runners fails to overcome the error: “The application encountered an unrecoverable error” when try to start the game, in the forum are others experiencing the same issue, and the only common thing is that we are using older processors, mine is a intel i7 920, others have an AMD Athlon II X4, xeon x3450, Core2Quad Q8300.
So maybe that is the origin of the error, the question is if can be fixable?

**Comment by ulibte** [comment]
i had the same problem and i tested overwatch 2 today and it worked, i think blizzard fixed the problem because i didn't change anything in lutris.

**Comment by strycore** [comment]
This has been fixed in Overwatch, it seems.
