### ISSUE TITLE
can't Quit?

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#459]
Tested with the latest GIT pull, and seems the quit menu entry won't allow you to quit, you need to press the X button to quit

**Comment by strycore** [comment]
@TingPing I tried putting back the Gtk.main_quit you had removed, thinking it was simply a mistake but it was apparently not one. 

There is something missing here, nothing in  the on_destroy callback tells the program to exit and now I know that a call to main_quit is not the proper way to do it

**Comment by TingPing** [comment]
@strycore `Gio.Application.quit()`
