### ISSUE TITLE
Determine Language when Install the game 

### ISSUE THREAD

**Issue by dtantono** [lutris/lutris#4593]
Hi,
there is no language selection when install the game and when the game is installed and we cannot change the language setting. So, on GOG Galaxy for Windows there is an option to choose language for install the game and I hope Lutris took same approach as well.

**Comment by strycore** [comment]
In most cases GOG installers should let you pick the language. If you encounter installer scripts that make the GOG installer silent, bypassing the language selection and the installer progress window, please let us know. Those need to be fixed.
