### ISSUE TITLE
[Feature Request] User Categories for games 

### ISSUE THREAD

**Issue by dtantono** [lutris/lutris#4594]
With big libraries, especially with the games from GOG, Steam and Epic it can be really hard to browse the library and Ability to create and manage categories like Steams collections is very useful. What do you think?

**Comment by klti** [comment]
There are a couple of issues (#3153, #3555) and PRs (#1452, #4482) about this, so far nothing seems to have picked up enough traction to end up on the roadmap.

**Comment by strycore** [comment]
Implemented in #4482
