### ISSUE TITLE
AttributeError when starting Lutris

### ISSUE THREAD

**Issue by KroyzPlayz** [lutris/lutris#4596]
Hello,
I am currently having an issue while trying to start Lutris. The error states as follows:
```
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3/dist-packages/lutris/api.py", line 9, in <module>
    import requests
  File "/home/kaczmaczk/.local/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/home/kaczmaczk/.local/lib/python3.10/site-packages/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/home/kaczmaczk/.local/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

I have tried:

- removing Lutris and reinstalling it
- reinstalling Python
- installing a newer version of Python
- upgrading pip
- purging Lutris and reinstalling it

I think I am out of options, what should I do next?

**Comment by danieljohnson2** [comment]
This looks like a change made in Python 3.10; it looks like you have 3.10 installed locally, but when you run Lutris you are getting an earlier version. You seem to be getting the two mixed together, which won't work.

You might be able to uninstall your local copy of Python 3.10, or upgrade your system's Python instead, or both. You need to be using just one version of Python, not two different ones at once.

**Comment by KroyzPlayz** [comment]
> This looks like a change made in Python 3.10; it looks like you have 3.10 installed locally, but when you run Lutris you are getting an earlier version. You seem to be getting the two mixed together, which won't work.
> 
> You might be able to uninstall your local copy of Python 3.10, or upgrade your system's Python instead, or both. You need to be using just one version of Python, not two different ones at once.

Okay, i'll try that now!

**Comment by strycore** [comment]
The version of requests you're using is outdated. Since you installed it in your user directory, you can update it with pip. 
Note that it's recommended to rely on Python packages provided by your distribution.
