### ISSUE TITLE
[Feature] Lutris flatpak should use mangohud flatpak

### ISSUE THREAD

**Issue by Heus-Sueh** [lutris/lutris#4597]
![image](https://user-images.githubusercontent.com/98482469/201487551-7bcb3164-1e7e-4bd1-a7f3-f40779caf8f7.png)
i have mangohud installed by flatpak but lutris does not recognize

this is the runtime i installed: runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08

bottles can use this runtime normally

**Comment by QmwJlHuSg9pa** [comment]
This comment resolved the issue for me: https://www.reddit.com/r/linux_gaming/comments/xn8scv/comment/ips9smu/?context=3

> Is Lutris updated to the 22.08 runtime yet? Try installing version 21.08:
> 
> `flatpak install flathub org.freedesktop.Platform.VulkanLayer.MangoHud//21.08`
> 
> Steam has been updated recently to 22.08, but I think Lutris might still be on 21.08. You shouldn't need to override, just enabling it within Lutris should work.

**Comment by NoxInmortus** [comment]
Hi, using both lutris and MangoHud 21.08 on Flatpak, but canno't make MangoHud to work. Does anyone have any more details ?

**Comment by QmwJlHuSg9pa** [comment]
In addition to my previous comment, you might try:

`flatpak override --user --env=MANGOHUD=1 net.lutris.Lutris`

**Comment by NoxInmortus** [comment]
> In addition to my previous comment, you might try:
> 
> `flatpak override --user --env=MANGOHUD=1 net.lutris.Lutris`

Thanks, but MongoHud option still remains unavailable...
