### ISSUE TITLE
Cannot remove Flatpak runner

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#4599]
Hello,

I'm having an issue as in the title. Whenever I go to preferences > runners and click delete icon next to Flatpak, a prompt asking whether I want to do that or not pops up. I choose yes and nothing happens. Flatpak runner is a very persistent one TBH. Deoes anyone have this issue as well?

Thank you.

**Comment by danieljohnson2** [comment]
I see that too.

The 0.5.12 beta should be better. It won't let you uninstall but gives you a message telling you to do it with your distribution.

It might be nice to have a feature to *hide* a runner without uninstalling it for cases like this, but Lutris hasn't got that.
