### ISSUE TITLE
On AMD/NVIDIA Hybrid systems, all games started in the Epic Games Launcher fail to start when using offload

### ISSUE THREAD

**Issue by Dadadah** [lutris/lutris#4603]
I recently switched my system to using prime after the latest NVIDIA driver update. Games launched through Epic Games all give the same X error, which can be seen below. I am able to launch Steam games on my NVIDIA card by launching Steam through my NVIDIA card. However, if I launch Lutris using the same option, it doesn't make a difference. Epic Games does use NVIDIA when I launch this way. When I launch a game, it will appear in `nvidia-smi`. I think this is because the Vulkan renderer is still NVIDIA.

I have an AMD/NVIDIA prime system
I'm running NVIDIA proprietary driver version 520
I am using an external monitor plugged in to my HDMI port
I'm on a 3 monitor system (Laptop monitor, HDMI, and USB-C)
I have the Enable NVIDIA Prime Render Offload option selected
Games launch on AMD when I disable Offload, but can't run in full screen (I get a hard freeze)
Epic Games Launcher does use NVIDIA
I have tested the following games: Goat Simulator 3, Tetris Effect, Ghostbusters: Spirits Unleashed, Arcadegeddon
Games launch normally when I'm in NVIDIA only mode (when `prime-select query` returns `nvidia`)
This happens in both DX11 and DX12 games (Ghostbusters can launch with `-dx11` to be dx11 only, Arcadegeddon is exclusively dx12)

`__NV_PRIME_RENDER_OFFLOAD="1" __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" glxinfo | grep vendor` 

returns

```
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
```

`__NV_PRIME_RENDER_OFFLOAD="1" __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" vkcube`

returns

`Selected GPU 1: NVIDIA GeForce RTX 3070 Laptop GPU, type: 2`

X Error given:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  43 ()
```

[lutris.log](https://github.com/lutris/lutris/files/10043746/lutris.log)

**Comment by strycore** [comment]
This works now

Game running from iGPU:

![Screenshot from 2023-06-07 02-21-31](https://github.com/lutris/lutris/assets/280336/720d5422-5bac-47f6-b31a-e6e1f87ebff6)

Game running from RTX 3060, with offload enabled in the settings

![Screenshot from 2023-06-07 02-23-38](https://github.com/lutris/lutris/assets/280336/3ddf3d0f-14e8-473b-a161-a42c370c9315)
