### ISSUE TITLE
Regression, Spider-Man crashes with lutris-fshack-7.2-x86_64 on Steam Deck

### ISSUE THREAD

**Issue by bjoern-tantau** [lutris/lutris#4605]
There seems to be some regression in the current beta on flathub. Both Spider-Man Remastered and the new Miles Morales work perfectly fine with lutris-fshack-7.2-x86_64 on the Steam Deck with  Lutris version 0.5.11. But when I switch to the beta version of Lutris Spider-Man crashes immediatly after launch and Miles Morales crashes after the intro videos.

**Comment by zzFluke** [comment]
Stable 0.5.12 affected as well. Downgrade to 0.5.11 fixed crash issue.

There is no useful logs found either.

**Comment by x43x61x69** [comment]
Downgrarde would make it run, but will break other games e.g. FF7R.

**Comment by lyndonguitar** [comment]
How do I downgrade version? it still doesnt work

**Comment by MaxChinni** [comment]
> How do I downgrade version? it still doesnt work

To downgrade Lutris to v0.5.11 on the Deck I used this command:

    (deck@steamdeck ~)$ sudo flatpak update --commit=a01b319ac3c027b79ddd2240a9eeb5f74862f00bf3a2476bcc75550a93d9fae2 net.lutris.Lutris

**Comment by strycore** [comment]
What about 0.5.13 and lutris-GE-Proton?

**Comment by bjoern-tantau** [comment]
Works fine on 0.5.13. So it seems to be fixed.
