### ISSUE TITLE
Cannot choose from all vulkan icd loaders?

### ISSUE THREAD

**Issue by Usulyre** [lutris/lutris#4606]
I posted this on the lutris forums.

https://forums.lutris.net/t/vulkan-icd-loader-how-to-select-a-custom-one/15222)

I am still having the issue even though I thought i solved it.

Why is lutris not detecting the vulkan icd loader that I have specified?

Any info needed I can provide thanks in advance.

**Comment by PinkaminaDianePie** [comment]
In my case Lutris doesn't even see Nvidia icd loader for a few days

**Comment by strycore** [comment]
The ICD loader should be fixed in the current version

**Comment by alexispurslane** [comment]
My gf is having this issue currently. Lutris does not detect her NVIDIA discrete GPU in hardware info, despite it being enabled and graphics switched to it with System76's prime equivalent, and does not display "NVIDIA Proprietary" as an option for the Vulkan ICD Loader

**Comment by strycore** [comment]
Are there 2 GPUs detected at startup on the command line?

should get something like 

```INFO     2023-12-24 01:07:21,872 [startup.get_drivers:67]:Running AMD Mesa driver 23.3.0 on AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 16.0.6, DRM 3.54, 6.6.7-203.fsync.fc38.x86_64) (0x747e)
INFO     2023-12-24 01:07:21,872 [display.display_gpu_info:81]:GPU: 1002:747E 1849:5326 (amdgpu drivers)
```


But with 2 display.display_gpu_info  lines.

**Comment by PinkaminaDianePie** [comment]
@alexispurslane
> I've been using Linux exclusively for more than 7 years and regularly play old and brand new games via Proton on my Nvidia laptop and have never had a single issue...

Same, play for many years with Steam + Proton, but never had any luck with Lutris, cause it can't even find vulkan

**Comment by alexispurslane** [comment]
I didn't think there wouldn't be such a significant difference, surely Proton is just Wine+a few patches and DXVK and such, but...

**Comment by strycore** [comment]
Well there's certainly some issue remaining *somewhere* but with the information at hand, there's no way we can fix anything. Let me know if there are new findings about this issue.
