### ISSUE TITLE
Something wrongs with winebrowser.exe

### ISSUE THREAD

**Issue by LiTEiTStudio** [lutris/lutris#4609]
I can use `wine winebrowser.exe url` in my terminal to open url in my default browser.
But when I use some windows programs in your wine build,I need to open the link in programs,it cannot open my browser.
I have tried many ways,it still not working.
I ran the app in terminal and open the url,but no error code was displayed.
I try wine 7.20 and it work fine,but switch I use lutris-wine-7.2-2,it doesn't work.
I think you maybe change something that make winebrowser.exe goes wrong when the app runs in wine try to call it.

https://user-images.githubusercontent.com/97424141/203447058-c174cf49-d31f-403d-a1be-a5558e972655.mp4

Under normal conditions this operation will open the offical site in browser

Wine Version:Lutris Wine 7.2-2 x86_64
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 5.15.78-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by strycore** [comment]
I was testing Battlefield on EA App which opens the launcher in a browser and I noticed this was now working correctly.
Update to the latest lutris-GE-Proton and it should be all good.
