### ISSUE TITLE
Steam support

### ISSUE THREAD

**Issue by Marteon** [lutris/lutris#461]
[SteamRE](https://github.com/SteamRE) is a project trying reverse engineering Steam. Since I don't have this much time nor any knowlege of .NET programming I haven't done much more than testing SteamRE-Downloader which can download Steam games by using the SteamRE library. 

And this worked really perfect!
So would it be possible to integrate SteamRE in Lutris?

**Comment by strycore** [comment]
Directly integrate no but maybe it would be possible to reimplement some of this code in Python? That could be interesting!
