### ISSUE TITLE
Dont default to nvidia if nvidia exists

### ISSUE THREAD

**Issue by ImUrX** [lutris/lutris#4610]
I'm currently using an AMD GPU and an Nvidia GPU, both for different purposes. [Lutris detects if nvidia exists in the system and just defaults to it](https://github.com/lutris/lutris/blob/bd6810287c1b72a4c7fb8c4b9460d437280749eb/lutris/startup.py#L54), can this not happen so I can use my AMD GPU happily? I even added the Vulkan env variable so Nvidia's vulkan driver isnt loaded.

Also because of this, lutris outputs incorrect information on hardware information. It says my graphics is AMD which if you read the lutris logs it obviously isn't because it's defaulting to Nvidia
```
[System]
OS:              Manjaro Linux 22.0.0 Sikaris
Arch:            x86_64
Kernel:          6.0.8-1-MANJARO
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 14.0.6, DRM 3.48, 6.0.8-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.3
Vulkan:          Supported
```

**Comment by ImUrX** [comment]
There is also [this piece of function](https://github.com/lutris/lutris/blob/master/lutris/sysoptions.py#L94) that ignores ``VK_ICD_FILENAMES`` env variable, so it defaults to nvidia also

**Comment by danieljohnson2** [comment]
Can you select AMD in the Preferences dialog, "Global Options" panel?

That should affect all games, including new installs.

**Comment by ImUrX** [comment]
You mean the ICD option hidden in advanced configuration? Yeah, I ended up using that. Kind of sad that it ignores the ICD env that i have tho

**Comment by danieljohnson2** [comment]
OK, so I think the check_driver() function is harmless; I think that is about complaining if your NVIDIA drivers are out of date.

It's your second function, get_vk_icd_choices() that is at issue. This provides the options for what the VK_ICD_FILENAMES variable will be when the game runs. If this thinks you have NVIDIA graphics it will provide that as the default, as this winds up obliterating VK_ICD_FILENAMES.

I'll tweak this. If VK_ICD_FILENAMES is set, the default will always be Auto, which will just leave VK_ICD_FILENAMES alone.

Please try the latest master (you need not install- just download it and run bin/lutris) and see if that doesn't work better for you. You may need to reset your existing setting to get the new default to take hold.
