### ISSUE TITLE
Launch_configs doesn't correctly apply the working_dir key

### ISSUE THREAD

**Issue by kasha695** [lutris/lutris#4611]
One of my install scripts for a local game has come across a bug with the working_dir under launch_configs not applying the working directory when launching the second exe.

Here is the code snippet:

<pre>name: Black & White
game_slug: black-white
version: Proton Version
slug: black-white-proton
runner: wine
script:
  game:
    exe: $GAMEDIR/drive_c/BlackandWhite/runblack.exe
    working_dir: $GAMEDIR/drive_c/BlackandWhite
    prefix: $GAMEDIR
    launch_configs:
      - exe: $GAMEDIR/drive_c/BlackandWhite/CreatureIsle/CreatureIsle.exe
        working_dir: $GAMEDIR/drive_c/BlackandWhite/CreatureIsle
        name: Creature Isle</pre>

When launching the main game it works correctly, but when I launch Creature Isle I get an error that the base game isn't installed as it's attempting to run from the main exe's directory.

If I change the main exe to the Creature Isle exe and set the working_dir to the CreatureIsle folder it launches successfully.

**Comment by danieljohnson2** [comment]
It appears to me that the launch configuration just doesn't support 'working_dir' at all. That seems inadequate.

I've put together [a branch to fix this](https://github.com/lutris/lutris/tree/dj/launch_config_working_dir).

I don't have "Black and White' handy, so I'd ask you to test my branch. You need not install it, just download it and run  'bin/lutrls' within. This should be able to now run Creature Isle, or so I hope.

**Comment by kasha695** [comment]
Just tested on the branch you've provided, all works, both exe's launch as they should with their respective working_dir's being applied. Thank you!

**Comment by danieljohnson2** [comment]
OK; I'll merge this.
