### ISSUE TITLE
Flatpak Runner doesn't install

### ISSUE THREAD

**Issue by kasha695** [lutris/lutris#4612]
I'm attempting to add the Flatpak runner to Lutris but when I click to add it I get the following error:

![Screenshot_2022-11-25_13-47-53](https://user-images.githubusercontent.com/67257234/203998960-9adf2ea8-01cf-4c01-bd4a-e843b6c2d8fa.png)

This happens on both my distribution provided Lutris and on my Steam Deck via Flatpak Lutris.

**Comment by danieljohnson2** [comment]
The current build should be providing a better error message for this. Maybe you could try it?

If you don't want to install the beta, you could download the master branch and run the 'bin/lutris' script.

Long story short: Lutris can't install Flatpak, you need to get it from  your distribution.

**Comment by kasha695** [comment]
Thanks, I ran the latest version and did get the better error message:
<pre>2022-11-25 13:54:41,093: Flatpak installation is not handled by Lutris.
Install Flatpak with the package provided by your distribution.</pre>

My main distribution doesn't have Flatpak installed so that's correct, but I'm still getting the error in Flatpak Lutris on the deck.

I'll go ahead and close this issue here and investigate further.
