### ISSUE TITLE
Cannot connect to Epic Games services

### ISSUE THREAD

**Issue by lisa-wolfgang** [lutris/lutris#4615]
When attempting to connect to the Epic Games Store in the Sources panel, a webview window pops up, but it only shows this message:
```
Error resolving “www.epicgames.com”: Name or service not known
```

However, I am able to access this URL in a web browser just fine.

When attempting to open the (previously installed) Epic Games Launcher, it similarly has connection issues. The troubleshooting page revealed that it was unable to connect to any of the required services except for the account public service. Again, opening the specified URLs in a web browser works fine.

In addition, upon attempting to install the launcher again, both the Ubisoft and Epic Games executables fail to download due to connectivity issues.

Happens on both 0.5.10.1 and https://github.com/lutris/lutris/commit/b8620311d78bb062794ba3364c422ef4640aa009.
Operating system: Ubuntu 22.10

**Comment by danieljohnson2** [comment]
If the Epic Games Launcher also can't reach 'www.epicgames.com', I think it's not Lutris doing it to you, it's some kind of local networking issue.

That probably does not help very much, but I wonder if something on your system has changed since you installed Epic Games Store successfully.

**Comment by lisa-wolfgang** [comment]
I've confirmed that this is an issue with Cloudflare WARP. Perhaps Epic Games has recently updated their servers to reject Cloudflare connections.
