### ISSUE TITLE
Initial process has exited (return code: 25344)

### ISSUE THREAD

**Issue by GizmoHey** [lutris/lutris#4618]
Well I got a problem with lutris, I tried to install Pokemon TCGO DXVK version and it crashed when I opened it. I checked the logs and this showed up...
`Started initial process 5887 from /home/gizmohey/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/gizmohey/Games/pokemon-tcg-online/drive_c/users/gizmohey/AppData/Roaming/Pokémon Trading Card Game Online/PokemonTradingCardGameOnline/Pokemon Trading Card Game Online.exe
Start monitoring process.
fsync: up and running.
Mono path[0] = 'C:/users/gizmohey/AppData/Roaming/Pokémon Trading Card Game Online/PokemonTradingCardGameOnline/Pokemon Trading Card Game Online_Data/Managed'
Mono config path = 'C:/users/gizmohey/AppData/Roaming/Pokémon Trading Card Game Online/PokemonTradingCardGameOnline/MonoBleedingEdge/etc'
wine: Unhandled exception 0xe06d7363 in thread 184 at address 7B0111E6 (thread 0184), starting debugger...
Initial process has exited (return code: 25344)
Monitored process exited.
Exit with return code 25344`

I just checked in the net for this error but I found not the same error but the solution they said is to reinstall lutris. But I already tried that and it didn't work.

Here's my system spec...
             /////////////                gizmohey@pop-os 
         /////////////////////            --------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: VivoBook_ASUSLaptop X421FQY_K413FQ 1.0 
   /////76767//7676767//////////////      Kernel: 6.0.6-76060006-generic 
  /////767676///*76767///////////////     Uptime: 1 hour, 48 mins 
 ///////767676///76767.///7676*///////    Packages: 2683 (dpkg), 54 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.3.1 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i5-10210U (8) @ 4.200GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce MX350 
      ///////////////////////////         GPU: Intel CometLake-U GT2 [UHD Graphics] 
         /////////////////////            Memory: 3468MiB / 7746MiB 
             /////////////

I would very grateful if anyone could help thank you.

**Comment by danieljohnson2** [comment]
Your issue looks like a game crash, which might be a bug in the game, or maybe an issue with WINE. I'd try different WINE or DXVK versions with it.

Your system spec seems rather garbled. I don't know what to make of that.

**Comment by GizmoHey** [comment]
I see, sorry about the spec I just copy pasted from the terminal I thought it would look ok.

**Comment by strycore** [comment]
Use the latest Wine-GE and maybe install .NET and XNA via Winetricks
