### ISSUE TITLE
Lutris/Wine - World of Warcraft access memory access violation while changing characters

### ISSUE THREAD

**Issue by IncrediblePony** [lutris/lutris#4620]
While gaming World of Warcraft with Lutris I very often run into the issue of getting a memory access error:
```plaintext
This application has encountered a critical error

ERROR #132 (0x85100084) Fatal exception!

Program C:\Program Files (x86)\World of Warcraft\_retail_\Wow.exe
ProcessID: 1620
ThreadID: 1624
Exception: ACCESS_VIOLATION

The instruction at "0x000000017002e34f"
referenced memory at "0xffffffffffffffff".
The memory could not be "read"
```

Technical information:
#### Lutris runner:
```
lutris-7.2-2-x86_64
```

#### System information
```
OS: Pop!_OS 22.04 LTS (64-bit)
RAM: 32 GB
CPU: AMD Ryzen 7 5800X
GPU: RTX 3080
GNOME: 42.5
```

![Screenshot from 2022-11-27 14-51-02](https://user-images.githubusercontent.com/5622336/204238174-e8e8dd88-39bf-464d-9b10-be343497ee2a.png)
![Screenshot from 2022-11-27 14-51-21](https://user-images.githubusercontent.com/5622336/204238190-fd8f8e6b-12b8-461d-bc97-438f9a211c7f.png)
![Screenshot from 2022-11-27 14-51-47](https://user-images.githubusercontent.com/5622336/204238204-1163b51a-3cc2-4c34-a8d9-2b10d344bdeb.png)

**Comment by strycore** [comment]
WoW should be working fine with the current lutris-GE-Proton8
