### ISSUE TITLE
🟢 SOLVED | ffi_prep_closure(): bad user_data  Libffi library problem causes Lutris to not be able to download anything 

### ISSUE THREAD

**Issue by atorresbr** [lutris/lutris#4623]
🟢 OS - version: Ubuntu 20.04
🟢 🦦 Lutris  VERSION: 0.5.11
🟢 Python version: 2.7.18
🟢 PIP version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

🟢 Graphics: Running Intel Open Source Technology Center Mesa driver 21.2.6 on 
Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2) (0x41e)

🔴 ERROR - Download failed: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time

Solutions:
A | 🟢 pip install --force-reinstall --no-binary :all: cffi
B | 🟢 pip install --upgrade cffi xcffib

This happens on some recent linux distributions - the binary wheel published on PyPI is not compatible with system libffi. Following will reinstall the package and build it locally on the system without using precompiled binaries published on PyPI:

 pip install --force-reinstall --no-binary :all: cffi
 
PS: Installing libffi-dev (.deb based distros such as Ubuntu or Debian) or libffi-devel (.rpm based distros such as Fedora) might be needed before this.

https://stackoverflow.com/questions/62658237/it-seems-that-the-version-of-the-libffi-library-seen-at-runtime-is-different-fro

**Comment by legluondunet** [comment]
Is this issue still relevant?

**Comment by atorresbr** [comment]
> Is this issue still relevant?

yep, a lot. All fixes are relevant.
