### ISSUE TITLE
Please update Debian 11 Package on SBS repo too

### ISSUE THREAD

**Issue by sysms** [lutris/lutris#4628]
On

https://download.opensuse.org/repositories/home:/strycore/Debian_11/

the available deb-Package for Lutris 0.5.12 still has the wrong dependencies (fixed in https://github.com/lutris/lutris/issues/4625).

Please update this package too with the corrected dependencies, so that installing/updating from this repo is possible again.

Thanks!

**Comment by gusnan** [comment]
Another vote for an updated Debian stable package - the deps are wrong, which causes problems. You should definitely have separate built packages for stable and testing/unstable when it comes to Debian.

**Comment by blazux** [comment]
One more vote for this fix.

**Comment by me0mar** [comment]
Please fix as soon as possible

**Comment by me0mar** [comment]
Solution 
just add contrib and non-free repositories 

This can either be done by editing` /etc/apt/sources.list `and adding contrib to the end of each line. Alternatively, one can use the Software & Updates gui and simply click the checkmark next to contrib. Then it’s as simple as:

`apt update
apt install lutris`

**Comment by sysms** [comment]
> Solution
> just add contrib and non-free repositories

This is no solution on Debian 11. Just read https://github.com/lutris/lutris/issues/4625 for more information.

@strycore Also it would be nice, if the current version (0.5.13) would also be available via this repo.

**Comment by strycore** [comment]
I updated OBS with 0.5.13
