### ISSUE TITLE
Steam games won't start when "something" is happen on Lutris

### ISSUE THREAD

**Issue by odziom91** [lutris/lutris#4633]
Hi!

It will be difficult to describe what is a problem. I have Lutris - currently precompiled version from Git, but I used 0.5.11 and it is the same. I have a lot of games which were added to database. A lot of these are Steam games. The problem is NOT showing when ~/.config/lutris and ~/.local/share/lutris is cleaned, so it looks like it depends on "games which are in database".

I received an "memory dump" error when I try to launch any Steam game.

Example of log:

```
lutris-wrapper: Sid Meier's Civilization V
Started initial process 26832 from mangohud /usr/bin/steam-runtime steam://rungameid/8930
Start monitoring process.
steam.sh[26832]: Running Steam on arch rolling 64-bit
steam.sh[26832]: STEAM_RUNTIME is enabled automatically
setup.sh[26906]: Steam runtime environment up-to-date!
steam.sh[26832]: Steam client's requirements are satisfied
free(): invalid pointer
/home/odziom/.local/share/Steam/steam.sh: line 798: 26963 Interrupted              (memory dump) "$STEAMROOT/$STEAMEXEPATH" "$@"
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
```

steam.sh file works fine when I run it manually or in Lutris when I clicked on Steam "Run" button in "Runners" menu on the left. Other games work fine also.

What is the problem?

My PC specs:
AMD Ryzen 7 3700X
HyperX Predator RGB - 32 GB RAM 3200 MHz DDR4 (4 pcs. x 8 GB)
MSI Gaming X GeForce GTX1060 6GB VRAM
OS: Arch Linux
Kernels: linux-bore (from CachyOS), linux-zen, linux-lts

Edit 1:
I did a little troubleshoot to check "when" an error will came up and it looks like when "MangoHud" option in System options tab is ticked. Maybe it is not a bug related to Lutris, but it should be investigated...

**Comment by niksingh710** [comment]
Yep, Can confirm that this is happening.
If using mangohud in lutris steam games refuses to launch.
but if using `DRI_RPIME=1 gamemoderun mangohud %command%` insteam the game launches perfectly fine with mango hud

if I toggle off mangohud from lutris and then launch the steam game the game runs fine.

it seems something to do with how lutris enabling mangohud as mangohud works if given in stem but does not work in lutris for steam games.

on other games those are locally installed works fine having mangohud enabled.

**Comment by strycore** [comment]
I've already disabled gamemode for the Steam runner. 
Reminder, there is no way for Lutris option such as gamemode or mangohud to affect Steam games until we integrate with SteamTinkerLauch
