### ISSUE TITLE
Updated Lutris to 0.5.12-1, got ModuleNotFoundError: No module named 'certifi'

### ISSUE THREAD

**Issue by tpkee** [lutris/lutris#4634]
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3.10/site-packages/lutris/api.py", line 14, in <module>
    from lutris.util import http, system
  File "/usr/lib/python3.10/site-packages/lutris/util/http.py", line 11, in <module>
    import certifi
```
I'm using latest arch, I installed i through pacman. I downgraded to v. 0.5.11-2 and it works just fine

**Comment by Hodor-git** [comment]
Installing python-certifi fix the issue.

**Comment by farchord** [comment]
Also, you should probably install python-pypresence if it exists on Arch. It's necessary for the Discord Presence feature on 0.5.12.

(Working myself on adding that module on Fedora so I can release 0.5.12)

**Comment by tpkee** [comment]
it's in the aur

**Comment by reddragonmps** [comment]
same issue here. updated today to 0.5.12 and had to install python-certifi in order to make it work.

**Comment by ElegantEgotist** [comment]
Latest Lutris update on Arch (0.5.12-2) added python-certifi as a dependency, it works by default now.

https://bugs.archlinux.org/task/76749?project=5&string=lutris

**Comment by strycore** [comment]
Fixed upstream
