### ISSUE TITLE
Origin Source not available in latest AUR Package of Lutris

### ISSUE THREAD

**Issue by tegaidogun** [lutris/lutris#4635]
![Screenshot_20221206_131450](https://user-images.githubusercontent.com/63559796/206046545-70f6b342-2be9-4b70-b177-20a3c638fda7.png)

How do I enable it?
There is no option available for it in **Preferences** either.

**Comment by danieljohnson2** [comment]
It really ought to be in the Preferences dialog, under "Sources".

Could you check what version of Lutris you actually have?

**Comment by tegaidogun** [comment]
It's been updated and works, perfectly now. Thank you very much.
