### ISSUE TITLE
Contribution not credited

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#4638]
Hi, I'd just like to ask that I be credited for my contribution - the splash screen that was added a few months ago. :sweat_smile: 

Thanks in advance!

**Comment by danieljohnson2** [comment]
I don't see a commit with your name on it. Can you point me at it?

**Comment by hazelnot** [comment]
No, because it's not a commit :sweat_smile: 

I submitted the assets in this thread and strycore added them himself: https://github.com/lutris/lutris/issues/1984#issuecomment-1143527779

**Comment by danieljohnson2** [comment]
Okay; I'll ask if I can put you in the AUTHORS file.

**Comment by hazelnot** [comment]
Cool, thanks!

**Comment by danieljohnson2** [comment]
@strycore is fine with it.

I've tacked your name on as "hazelnot"; let me know if it should be expressed otherwise.

This is ironic though. I had also asked @strycore if I could add myself, but he ignored that. I guess I can credit other people but not myself. A lesson in humility perhaps?

**Comment by strycore** [comment]
> This is ironic though. I had also asked @strycore if I could add myself, but he ignored that. I guess I can credit other people but not myself. A lesson in humility perhaps?

By all means, please to add yourself!!
