### ISSUE TITLE
Custom cover art appearing stretched

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#4639]
Custom cover art appears stretched in Lutris, it seems like it has something to do with the aspect ratio that the IGDB covers used. However, if using cover art made for Steam (which most custom cover art appears to be, thanks to SteamGridDB), the art will appear horizontally stretched, because of the taller aspect ratio.

My suggestion is to simply keep aspect ratios the way they are and display the artwork without trying to fit it into the IGDB template.

Example of art being stretched: 
![image](https://user-images.githubusercontent.com/10992973/206172602-5ec68c21-dc6b-42ff-b445-e174e0138380.png)

Note how the circle becomes an oval.

**Comment by strycore** [comment]
Our coverart comes exclusively from IGDB, we don't use Steam cover art unless the Steam service is selected

**Comment by hazelnot** [comment]
I know, what I'm saying is that custom cover art set by the user appears stretched because IGDB has its own semi-proprietary aspect ratio for cover art that they're trying to push as an industry standard.

**Comment by danieljohnson2** [comment]
I've taken a look a this and I think I've improved it; it scales the art to the right size respecting aspect ratios now.

Please give the latest master a try. You know the drill- no need to install, download it and run ./bin/lutris

Note that Lutris pre-scales the art when it is installed, so you'll need to replace or re-download the existing art for this to help.

**Comment by hazelnot** [comment]
Thank you, it seems to work perfectly!
