### ISSUE TITLE
[bug] Lutris won't start

### ISSUE THREAD

**Issue by rmbleeker** [lutris/lutris#464]
I hadn't used Lutris in a while and found out today that it won't start, instead it gives an error:

```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 27, in <module>
    app = Application()
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 48, in __init__
    self.add_main_option('debug',
AttributeError: 'Application' object has no attribute 'add_main_option'
```

I'm running the latest version of Lutris on Ubuntu 14.04 from the OpenSUSE build service repo. My version of python3 is 3.4.3.

**Comment by TingPing** [comment]
This requires GLib 2.42 and 14.04 has 2.40.

**Comment by rmbleeker** [comment]
Was this always the case because it worked a few weeks ago, I didn't keep track of any updates to Lutris. Also the repo has packages for 14.04, so that seems to me like it should be supported?

**Comment by TingPing** [comment]
Last major release, version bump was discussed in #453

**Comment by rmbleeker** [comment]
That's a shame but thanks for the info. I guess I'll have to downgrade the package until my new pc arrives on which I'll install a more recent distro. Closing this.

**Comment by strycore** [comment]
@rmbleeker why not run sudo do-release-upgrade? 

I've removed 14.04 from the OBS repos and will update the Downloads page soon

**Comment by rmbleeker** [comment]
@strycore my machine is old (8+ years) and I just can't be bothered because I'll be getting a new one soon. It's no big deal.
