### ISSUE TITLE
Ubisoft Connect / Lutris Integration (Not Ubisoft Connect Windows Client) Fails to Authenticate

### ISSUE THREAD

**Issue by mbaran5** [lutris/lutris#4640]
I am running Lutris 0.5.12 on SteamDeck Preview OS 3.4 and I cannot get Ubisoft browser login to list my games inside of Lutris to complete loading. I get a few minutes (3 or so?) of the flashing Ubisoft logo and then eventually an error about no internet connection (see images below)...

That said, my Ubisoft Connect full launcher under Wine works fine. I just can't use any of my games since Lutris can't enumerate them via the web connection. 

![image](https://user-images.githubusercontent.com/583865/206328039-e6d4928e-ddb4-4db0-9f3b-180779ae9910.png)
![image](https://user-images.githubusercontent.com/583865/206328086-bc403fa9-0c29-4934-a3f4-2a2b9aee3a3a.png)
![image](https://user-images.githubusercontent.com/583865/206328490-cafa2156-2a26-42f0-af58-a3d35b5c6689.png)

**Comment by mbaran5** [comment]
I also deleted the folder /home/deck/.var/app/net.lutris.Lutris/cache/lutris/WebKitCache in case there was something cached preventing webkit from displaying the content correctly. No change.

**Comment by marioapardo** [comment]
I have the same problem on the Steam Deck and I also did the steps of @mbaran5 trying to solve the connectivity problem.

**Comment by thitar** [comment]
Same problem here.
Steam Deck Stable release 3.3.2
I did a complete fresh install of Lutris through Flatpack to make sure there was nothing left behind.
Also deleted and reinstalled Ubisoft full launcher which is working correctly.

**Comment by seavers11** [comment]
I got the same Problem and cant get it to run ...

**Comment by mbaran5** [comment]
anyone?

**Comment by seavers11** [comment]
I got it to work, using 2FA on Steam Deck via Mail. Now it's working here :-)

**Comment by mbaran5** [comment]
Care to elaborate how you got it to work for the rest of us? @seavers11

**Comment by Beariddle** [comment]
You re-activated the 2FA or you never had it enabled beforehand on your account?

**Comment by seavers11** [comment]
I change the 2FA from  App to mail... Nothing else...

**Comment by mbaran5** [comment]
Unfortunately this didn’t fix it for me. Still broken.

**Comment by anat0lius** [comment]
I didn't work on 0.5.11 but it does work now for me in 0.5.12

**Comment by infidelus** [comment]
Not working here either on 0.5.12, just sits there with the Ubisoft logo pulsing.

**Comment by Beariddle** [comment]
The solution proposed in https://github.com/lutris/lutris/issues/4571#issuecomment-1386214365 seemed to have worked for me. After having left the issue on the backburner for a while and gave it another shot today. Perhaps it might be related?

**Comment by strycore** [comment]
Fixed in current release
