### ISSUE TITLE
Installation can fail if previous install did not exit normally (Lego Racers)

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4643]
Steps to reproduce:

1. Try to install "LEGO Racers" from the Lutris website. Choose the [wine/retail CD version](https://lutris.net/games/install/13684/view).
2. Part-way through the install, cancel the installation. For example, just hit Cancel once the Windows install wizard appears. Alternatively, experience a bug part way through that causes the installer to abort (this is what originally happened to me).
3. Repeat step 1.
4. The installation fails as soon as you hit "Autodetect" to detect the CD rom.

If I run Lutris from a terminal, I see lots and lots of this kind of error:

```
[Errno 13] Permission denied: '/home/jack/.cache/lutris/installer/lego-racers/cdrom/_user1.hdr'
```

And deleting the cache in `~/.cache/lutris/installer` fixes the issue.

So what I'm guessing happens is that Lutris read-onlys the cached CD-rom when it installs, but when you re-install it needs write-access to that cache. Either the installer needs to correctly enable write permissions on the cache when it exits abnormally, or the installer needs to not require write-access to the cache if it's already there.

Ubuntu 20.04, Lutris 0.5.12.

**Comment by danieljohnson2** [comment]
Hmm. Can you reproduce this problem when you change to a different cache directory?

You change this by clicking the 'Cache' button in the lower level corner of the install window.

It is strange that the .hdr file is getting its permissions munged, and I wonder if it's something about your ~/.cache directory.

**Comment by geajack** [comment]
Same problem. Before installing the first time, I set the cache to `~/testcache`, cancelled the install partway through, then when installing again made sure the cache was `~/testcache` again and got the same error. Oddly enough though, the `~/testcache` directory is actually empty.

**Comment by geajack** [comment]
I just reproduced this on a different machine on Ubuntu 22.04 (last time was 20.04), so this is definitely a real thing.

**Comment by geajack** [comment]
Here are some files to reproduce the bug. Mount the ISO and tell Lutris to add a game from `game.yml`, and hit Autodetect when prompted for the disc. The install script will fail (on purpose, because it says to execute something that isn't an executable file). Cancel out of the install and try again. You'll get an error when you hit "Autodetect".

[issue4643.zip](https://github.com/lutris/lutris/files/10328056/issue4643.zip)

**Comment by geajack** [comment]
@AlexanderRavenheart It seems like you introduced the use of `shutil.copytree` in `merge_folders`. Do you happen to remember why that was done? How would you feel about reverting that change and just using the old code?

**Comment by danieljohnson2** [comment]
I can provide basic error handling here, though depending on what file you try to read, it can produce very strange errors.

**Comment by danieljohnson2** [comment]
OK, I've researched this. PR #3812 is called "optimizations" so I expect it's not critical, and the copytree thing has already been partially reverted because it was not compatible with Python <3.8 (commit 74ce7b1d70a6aa681e6b890c64a2ddb8c79c09d7 fixing issue #4333).

I think we can safely use the old-Python code, so I've gone ahead and done that.

I find this fixes the repro that our prolific tester @geajack provided. Thanks, @geajack!
