### ISSUE TITLE
lutris wine-7.2 has memory issues

### ISSUE THREAD

**Issue by axet** [lutris/lutris#4644]
Hello!

I'm playing a lot with different wines and lutris 7.2 known to have a lot of memroy issues. Resulting as a crash. Especially Playing Skyrim AE GOG. Sometimes it is stack smashing (Far Cry 5 or 6). Or for skyrim:

Fatal glibc error: malloc assertion failure in __libc_calloc: !mem || chunk_is_mmapped (mem2chunk (mem)) || av == arena_for_chunk (mem2chunk (mem))

Original winehq does not give me any memory related issues.

**Comment by strycore** [comment]
Try with the new default, lutris-GE-Proton8. No memory issue noticed in the Far Cry games.
