### ISSUE TITLE
Cannot open lutris from flatpak desktop file

### ISSUE THREAD

**Issue by Tc-001** [lutris/lutris#4649]
I have lutris installed as a flatpak, it runs fine with `flatpak run --branch=stable --arch=x86_64 --command=lutris --file-forwarding net.lutris.Lutris`, except for some errors:
```
Unsupported locale setting. Fix your locales

(lutris:2): Gtk-WARNING **: 22:59:11.507: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 22:59:11.828: Failed to load module "colorreload-gtk-module"
Gtk-Message: 22:59:11.828: Failed to load module "window-decorations-gtk-module"
2022-12-12 22:59:11,851: Starting Lutris 0.5.12
2022-12-12 22:59:12,650: Using NVIDIA drivers 520.56.06 for x86_64
2022-12-12 22:59:12,650: GPU: NVIDIA GeForce GTX 1650 with Max-Q Design
2022-12-12 22:59:12,650: GPU: 10DE:1F99 17AA:3F93 (nvidia drivers)
2022-12-12 22:59:12,651: GPU: 8086:9BC4 17AA:3F93 (i915 drivers)
2022-12-12 22:59:12,863: Startup complete
```

But when I try and open it from my application launcher it just... doesn't
![Peek 2022-12-12 23-01](https://user-images.githubusercontent.com/55956895/207153590-26c8f060-b06a-4f4f-b041-afb0844157e2.gif)

I am really unsure what is the issue, as I even tried re-installing lutris without much effect. 

Here is everything I can gather about my env in the hopes it helps:

- Fedora 37
- KDE 5.26.4 / 5.100.0
- Flatpak 1.14.0
- lutris-0.5.12

I am *really* not sure why it behaves differently, this started happening a bit ago so I can't even pinpoint an exact upgrade that broke it.

I also cannot seem to get a desktop file to execute from within a terminal, so I can't see any logs it generates :(

**Comment by nahsiy** [comment]
Hello, You are missing GTK libraries.

**Comment by strycore** [comment]
The current Flatpak version should work without issue.
