### ISSUE TITLE
Anno 1404 - black screen issue with latest Nvidia drivers

### ISSUE THREAD

**Issue by anat0lius** [lutris/lutris#4651]
Anno 1404 History Edition, Ubisoft version. Game stuck on black screen.
As discussed in protondb, I already set DirectX version to 9 in the Engine.ini file.

Those are the logs with different driver versions:

470 - OK    - https://pastebin.com/EJ5SZu5g
510 - NOK - https://pastebin.com/kK7nuCur
515 - NOK - (no logs)
525 - NOK - https://pastebin.com/qYNFxWxE

Some diffs I spotted between 470 and 525:
![image](https://user-images.githubusercontent.com/4255121/207170585-9e5a5a38-e4bf-4f41-b818-bd8ef835e558.png)
![image](https://user-images.githubusercontent.com/4255121/207170441-7f17903f-0aae-4785-819d-ae950c3d38ed.png)

**Comment by strycore** [comment]
See if Gamescope makes a difference, it sometimes help with such issues
