### ISSUE TITLE
Running newer version of Lutris seems to run old version

### ISSUE THREAD

**Issue by lisa-wolfgang** [lutris/lutris#4654]
There's probably an obvious solution to this, but I can't seem to figure it out.

I originally installed Lutris from the 0.5.10.1 `.deb` file. Now that I'm trying to upgrade, however, Lutris seems content to continue opening this old version instead of 0.5.12.

I've tried three different ways of opening the new version, all of which were unsuccessful:
1. Installing again with the 0.5.12 `.deb`
2. Running the binary provided in the source code
3. Running the Flatpak version

Operating system: Ubuntu 22.10

**Comment by danieljohnson2** [comment]
That is very strange; the second two methods should work even if you can't upgrade your system's Lutris.

I'd suggest completely uninstalling *all* versions of Lutris, then installing the latest via the .deb or flatpak.

If you can't uninstall one, that one may be causing the problem.

**Comment by mateitudose** [comment]
Also happening to me. I was using the PPA but then I removed the older version (.10) and now, when using the .deb, it installs 0.5.9.1

**Comment by mateitudose** [comment]
I think that the fix is to remove Lutris and the old PPA and to re-add it
