### ISSUE TITLE
Cover art showing on source tab, but not on games tab

### ISSUE THREAD

**Issue by duarm** [lutris/lutris#4657]
the cover art shows up for each steam game on the Steam source tab
![image](https://user-images.githubusercontent.com/26150581/207526996-15d26fd6-d6f9-4c08-8a14-847b6e187aa5.png)

but the same game shown from the Games tab has no cover

![image](https://user-images.githubusercontent.com/26150581/207527153-6ce0eac4-f3ea-4017-8d4e-3757c7820302.png)

I cleared all games and resynced Steam to make sure those are the same entry, there's no cover in the configure window

![image](https://user-images.githubusercontent.com/26150581/207527508-08a99cc8-d2d5-417c-b75a-ae9c9c59989d.png)

lutris should use the steam cover if no cover is available

**Comment by danieljohnson2** [comment]
When this happens to me, it's usually that Lutris has installed with the wrong 'Identifier'; you're screenies are cropped so I can't see, it would be listed right below 'release year'.

For this game it should be 'deep-rock-galactic'.

**Comment by duarm** [comment]
both are deep-rock-galactic

**Comment by duarm** [comment]
I was adding another game to my list, when I dupped one of my games, all the missing game icons showed up, Lutris is probably missing an update call when syncing the games, when I duplicated the entry, it probably updated the list too.

**Comment by danieljohnson2** [comment]
That sounds likely; we've had that bug before.

If you can figure out how to reproduce this issue, there's a good chance I can fix it.

**Comment by duarm** [comment]
I can't figured it out the pattern which makes the cover art appears (it appears eventually when doing an action, like duplicating), but one pattern I noticed is that the icon always shows up.
![pic-selected-221223-2235-49](https://user-images.githubusercontent.com/26150581/209416975-659ae1d1-7f48-41dc-98e3-158c26f03402.png)

as soon as I add a game, the icon appears, only the other two images are missing (to later appear), maybe they take too long to fetch and lutris gets interrupted or something?

**Comment by danieljohnson2** [comment]
No, the icons have a special case for WINE where it extracts the icon from the .exe, if it hasn't downloaded one.

What I need to to know how to create a game with these blank banners, when the identifier is correct but that does not trigger the banners to download at once.

Lutris has a process to download missing banners every now and again to repair these things, but we want it to get the banners when you create the game.

**Comment by strycore** [comment]
one banner comes from Steam and the other comes from lutris (fetched from IGDB)
they are unrelated.
