### ISSUE TITLE
Controller doesn't work properly in Lutris (Wine 7.2), but does in system Wine (5.0)

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4658]
I'm trying to run Lego Racers in Lutris. I installed it in the client. When I run it manually in my terminal with:

```
wine LegoRacers.exe
```

my USB gamepad works as expected. But if I run it with

```
/home/jack/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/winecfg
```

or from the Lutris client, I get at least the following issues:

- Controller doesn't work in the menu (probably the y-axis of the d-pad is not mapped)
- B button is now A button, and the other face buttons don't seem to work
- d-pad left and right do nothing (so basically the d-pad doesn't seem to work at all)

My system wine is 5.0, my Lutris one is 7.2. I'm not sure if this is just an upstream issue with Wine, but I thought if the default Wine for Lutris is this broken with some games/in some environments, the issue should probably be tracked by Lutris too.

Ubuntu 20.04, gamepad is just some random SNES-style USB gamepad

**Comment by strycore** [comment]
Not sure there's much that can be done, except maybe with some Steam Input remapping.

![image](https://github.com/lutris/lutris/assets/280336/0ba66e3b-d953-4b47-8cf6-73f7c6754f9e)

The D Pad, when overidden in DInput mode is registered as button presses. This means LEGO Racers doesn't have an axis to use.

I'd really recommend using any other controller for Wine games, the SNES-like controller is OK for emulation on Raspberry Pi.

Wine from my system was unable to start LEGO Racers so I'm unable to compare.
