### ISSUE TITLE
Mangohud on wrong window

### ISSUE THREAD

**Issue by jonathancolledge** [lutris/lutris#4659]
To run Zwift, you need to first have ZwiftLauncher.exe running from inside a wine prefix. This means that when I run it, mangohud comes up on that window, but when I press play, the main Zwift window doesn't have mangohud.

I'm on Ubuntu 22.04.

My settings are in Lutris:
Environment variables:
MANGOHUD 1

And in command prefix
mangohud

Any help in getting it on the right part of the app would be greatly appreciated please

**Comment by strycore** [comment]
We integrate Mangohud in Lutris, there is no need for command prefixes or env vars. 

If Mangohud shows on the launcher then it's being correctly loaded. If it doesn't show up in the game itself then that should probably be reported to MangoHUD.
