### ISSUE TITLE
Debian GPG key expired since 2016-12-22

### ISSUE THREAD

**Issue by Darcidride** [lutris/lutris#466]
It seems you're using a repository with an expired GPG key for your Debian installation :
![](http://i.imgur.com/RANiYnw.png)

> pub   2048R/70F1BBEA 2014-10-14 [expired : 2016-12-22]
> uid                  home:osmc OBS Project <home:osmc@build.opensuse.org>

After an _apt update_ we can see this warning message :

> W: Erreur de GPG : http://download.opensuse.org  Release : Les signatures suivantes ne sont pas valables : KEYEXPIRED 1482381670

Confirmed with _apt-key list_ :
![](http://i.imgur.com/W8JeKa8.png)

**Comment by ozo2003** [comment]
have the same error now, deleting and re-adding key does not fix the issue

**Comment by strycore** [comment]
I have updated the PGP key on OBS, works fine now. You may have to re-import the key if you still get the error.
