### ISSUE TITLE
Suggested wine prefix directory is not automatically created

### ISSUE THREAD

**Issue by SuperSandro2000** [lutris/lutris#4660]
When installing a game with a wine emulation layer like Caesar III then the suggested installation directory is not automatically created and the wine prefix creation will hang forever without completion.

lutris version: 0.5.12

**Comment by legluondunet** [comment]
Hello @SuperSandro2000 ,
is this issue still relevant?

**Comment by SuperSandro2000** [comment]
I didn't retest this recently but I assume this didn't get fixed in the meantime.

**Comment by legluondunet** [comment]
please retest and tell us if it is still relevant. You can reproduce this issue with only one script or all scripts installer?

**Comment by SuperSandro2000** [comment]
I just tested this again and the directory is created now.
