### ISSUE TITLE
Select the default wineprefix loops and does not go to the next screen 

### ISSUE THREAD

**Issue by Bboy486** [lutris/lutris#4668]
On Steam Deck desktop, I manually added a game on my SSD in lutris. I selected the runner and all the settings. I went to winetricks to install .net but when I click Select the default wineprefix it does not go to the next screen (I have tried to delete and start from scratch without success. Games that are on Lutris work though. The game is TMNT - SHREDDER'S REVENGE.

**Comment by VanackSabbadium** [comment]
Same for me with a single game, which is a demo of a new game made by a friend of mine.
The error is:

Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-7.2-1-g1f8837bdccd (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
Monitored process exited.
Exit with return code 0
/tmp/winetricks.flrYGkfA/w.vanacksabbadium.76268/zenity.sh: 1: Syntax error: Unterminated quoted string
Monitored process exited.
Initial process has exited (return code: 0)

**Comment by VanackSabbadium** [comment]
I found the solution.
The issue is related to this other one: https://github.com/lutris/lutris/issues/1258

Winetricks does not accept folder with the apostrophe. Renaming the folder solved the issue.
