### ISSUE TITLE
Can't create signal for Game-Error

### ISSUE THREAD

**Issue by PrimaIVoid** [lutris/lutris#4673]
After pulling targeting the latest `master` branch of Lutris today i receive this error when trying to lunch from terminal:
```
/usr/lib/python3/dist-packages/gi/types.py:217: Warning: ../../../gobject/gsignal.c:1777: signal "lutris+game+Game::game-error" has return type 'gboolean' and is only G_SIGNAL_RUN_FIRST
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/home/user/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/user/lutris/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/home/user/lutris/lutris/game.py", line 41, in <module>
    class Game(GObject.Object):
  File "/usr/lib/python3/dist-packages/gi/types.py", line 226, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 205, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 217, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create signal for game-error
```
System: Linux - Debian 12 x64
Latest commit: https://github.com/lutris/lutris/commit/8a99c1026c767e06142aa4ade37b443bcbe98b8d

**Comment by danieljohnson2** [comment]
Oooooo, obscure. This is a [GNOME bug](https://gitlab.gnome.org/GNOME/glib/-/issues/513). This was fixed two years ago, but you must be using an older GNOME.

There's a simple workaround that shouldn't do us any harm- use  G_SIGNAL_RUN_LAST.

I've made that change. Please get the latest master, try again, and let us know if it works now.

**Comment by PrimaIVoid** [comment]
It works now @danieljohnson2 !
Anyhow i've been using and updating (pulling from master) Lutris for almost a year now and never had that problem
Also checking my current GNOME version was released on May 2021 and its the latest stable for Debian so its not that old
```
@user:~$ gnome-shell --version
GNOME Shell 3.38.6
```

**Comment by danieljohnson2** [comment]
This particular issue arrived in a merge just last week; you caught it pretty quickly. Thank you.

I linked the GNOME bug, and you can get to the fix commit from there. I'm not sure what version of GNOME shipped with the fix first, but I didn't experience this issue on GNOME 42.5 (my GNOME shell is 42.3.1)

**Comment by Tetita** [comment]
g
