### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#468]
Happens now and then to the best of us, a game crash and it leaves something open or Lutris notice it  but ignore it.

I'm playing NFS:U2, and it's not the most stable game on Wine, and it crashes now and then. When it crashes it leaves lutris spamming the terminal with

 `DEBUG    2017-01-04 12:00:52,591 [thread]:All children terminated`

and will keep doing that until you close lutris, also happensnow and then with other games/emulators (retroarch)

**Comment by strycore** [comment]
I've added a return False when the process reaches that state, does it solve the issue?

**Comment by telanus** [comment]
Seems to be fixed thanx :smile_cat:

**Comment by strycore** [comment]
I need to revert the commit and find another solution, this breaks a bunch of other stuff.

**Comment by strycore** [comment]
I tried NFSU2 and the game did eventually crash but I didn't encounter your situation, even when I had the `return False` I had previously introduced.

**Comment by strycore** [comment]
The fix was actually quite simple
