### ISSUE TITLE
"Reset option" buttons are a little bit harsh and look like errors

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4681]
Small UI request: every time I see these "revert option" buttons I think they're telling me I've entered an invalid value. I'd recommend replacing them with a simple grey X directly against the background (no circle around it).

![image](https://user-images.githubusercontent.com/2124157/210120012-8647dcf1-b732-45fc-85e4-c77e8e68c9b4.png)

**Comment by duarm** [comment]
that's up to your GTK theme, mine shows like this, which is standard. (Yes, my theme is too white)
![pic-full-221231-0108-52](https://user-images.githubusercontent.com/26150581/210124382-dfc3b045-99e9-498c-a1ee-15e307967e11.png)

**Comment by geajack** [comment]
Hmm, what GTK icon is used for those buttons? Maybe there's a more appropriate one that would look better under all themes?

**Comment by danieljohnson2** [comment]
It is "edit-clear".

Though I think looking better under *all* these is a rather big ask.

**Comment by geajack** [comment]
Yes, maybe more of an upstream GTK issue if the "edit-clear" icon looks more like an error under some themes

**Comment by strycore** [comment]
PR merged
