### ISSUE TITLE
Osu won't start!

### ISSUE THREAD

**Issue by SOMkill** [lutris/lutris#4685]
**Good evening, I don't have Osu running!**

Started initial process 7380 from gamemoderun /home/a/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/a/Games/osu/drive_c/osu/osu!.exe
Start monitoring process.
gamemodeauto:
wineserver: using server-side synchronization.

Process is terminated due to StackOverflowException.
Monitored process exited.
Initial process has exited (return code: 59648)
**Exit with return code 59648**
Ubuntu 22.10, lutris-7.2-2

**Comment by geajack** [comment]
How exactly did you install osu! and what exactly did you click on that triggered that error?

**Comment by strycore** [comment]
I'm not helping anyone on OSU until someone cleans up the mess you've collectively made. There are 2 Windows installers for OSU.... not confusing at all.
