### ISSUE TITLE
Lutris shows logs for wrong game when games are removed/installed in same session

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4686]
Repro:

1. Install a game (Game A).
2. Run Game A.
3. View the logs for Game A (i.e. right-click on it in Lutris and click "Show logs").
4. Close logs, uninstall Game A in Lutris.
5. Install another game, Game B.
6. View the logs for Game B.

You'll see the logs for Game A in the window. Slightly niche set of circumstances, but potentially confusing if the user installs two broken games in a row.

**Comment by danieljohnson2** [comment]
I see it; it's getting the same ID for the new game as the old, so it re-uses the log buffer.

The fix is to clear that buffer and close that log window when uninstalling the game. Then re-use of the buffer is okay.
