### ISSUE TITLE
Lutris fails silently if given an invalid local installer script

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4687]
Repro:

1. Click "Add game" and choose "Install from local install script".
2. Select something that isn't a valid install script, say something that isn't even a YAML or JSON file.
3. Nothing happens (except errors show up in your console).

There ought to be a little error popup.

**Comment by danieljohnson2** [comment]
OK, I've provided some error handling here.

The errors can be strange, depending on the file you try to use and how much it resembles a .yml file.
