### ISSUE TITLE
[MESS/MAME] software list options

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#469]
is there an optional way to launch mame using the software lists? 

Added mame as a custom executable to the mess runner, set everything up, and tried starting sskick3 on the Neo-Geo AES driver, and it complains it doesn't know the software, adding the cart as storage type launches the game, but the game won't run as the AES needs to be run from softlist

**Comment by strycore** [comment]
I don't understand everything but one thing's for sure is that MESS and MAME are being merged into the same project so they will likely merge into a single runner in the future.
