### ISSUE TITLE
pcsx2 error

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4691]
when adding a game to the runner I get the following on the terminal:

```
INFO     2023-01-01 09:32:08,187 [common._switch_runner:488]:Creating new configuration with runner pcsx2
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/config/boxes.py", line 452, in _on_chooser_file_set
    self.option_changed(entry.get_parent(), option, text)
  File "~/src/lutris/lutris/gui/config/boxes.py", line 578, in option_changed
    reset_btn = hbox.get_children()[1].get_children()[0]
IndexError: list index out of range
```

**Comment by danieljohnson2** [comment]
This affects all file choosers in the config dialog, it's not just PCSX2.

It is collateral damage from a previous fix; the FileChooserEntry has a sensible "changed" signal now, and the 'widget' it reports is the chooser itself. That's what we want, but the failing code here is doing 'widget.get_parent()'  to compensate for the old "changed" event's ways. That needs to go.

So now it's gone, and you should be good.

I checked every other usage of FileChooserEntry, and they all look okay.
