### ISSUE TITLE
PCSX2 Error pt2

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4692]
@danieljohnson2 Not sure why but this happened when I tried to update a pcsx2 game:

```
DEBUG    2023-01-01 18:31:30,171 [http._request:88]:GET https://lutris.net/api/games/cabelas-big-game-hunter
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/config/common.py", line 576, in on_save
    self.game.save(save_config=True)
TypeError: save() got an unexpected keyword argument 'save_config'
```

Looks like a regression

**Comment by danieljohnson2** [comment]
Oops!

I removed the save_config parameter while fixing another bug, but apparently botched my search for other usages. I've committed a fix- no need for save_config=True, it always saves that.

(In cases where it does not, it is not save to use save() at all- we need to save one particular field and not any others)
