### ISSUE TITLE
Install duplication & wasted space

### ISSUE THREAD

**Issue by SimonDedman** [lutris/lutris#4698]
In searching for a file on my Linux system I noted a duplicate result in:

`/home/simon/Games/epic-games-store/dosdevices/c:/users/simon/Downloads/`

although oddly not in

`/home/simon/Games/origin/dosdevices/c:/users/simon/Downloads/`

nor

`/home/simon/Games/ubisoft-connect/dosdevices/c:/users/simon/Downloads/`

which is maybe counterintuitive since all 3 are just links to `~/Downloads`. Not the biggest issue in the world. But while looking around those folder structures, I noticed how big they are (2.5, 1.6, 1.3gb respectively, with zero games installed into any of them. Digging deeper, it seems the structure is:

`gamelauncher/full windows install/games`

for each launcher, meaning that the full windows install and all files are duplicated for each launcher (in my case thrice). Here's an example of multiple dupes of large files, but this is true for small files also, which all add up:

![filesExampl](https://user-images.githubusercontent.com/4599748/210904326-595fb380-dcfb-4e75-bc77-913f941ae9d8.png)

With the caveat that I know nearly nothing about all the genius which is going on under the hood, would it not make more sense to have:

`full windows install/games`

With Lutris installing the windows bit then handling the check to see if that structure is already present before installing the next launcher and the relatively few extra unique elements each launcher needs, outside of the shared windows structure that they all use?

Thanks

**Comment by danieljohnson2** [comment]
Lutris lets you give each game a different version of WINE and configure it differently too, so they are maybe not as identical as you might expect.

Giving each game its own separate install with little shared is safer and simpler; it just costs a bit of disk.

**Comment by SimonDedman** [comment]
Makes sense. Ok, thanks for the quick reply!
