### ISSUE TITLE
The drivers are outdated

### ISSUE THREAD

**Issue by SirSmellvin** [lutris/lutris#4699]
I cant find any drivers that support 30s series graphics card. I'm using arch linux.

**Comment by slynobody** [comment]
i can second issues on the current driver-sitation, but while the above seems to be distro-specific my concern is more lutris-wise-specific esp. on updating config-files to current dxvk-nvapi, d3d, vk3d-version to supply current versions at lutris-start.

also controller-support needs to be added very soon. take a look at the heroic-launcer and tell me why someone needs lutris anymore in a few month (when it is completely above lutris feature-wise).

**Comment by awsms** [comment]
>take a look at the heroic-launcer

unfortunately it's bloated a** electron junk. not a good alternative.

**Comment by LoKolbasz** [comment]
You mean you can't find the "nvidia" arch linux package using pacman?

**Comment by strycore** [comment]
This page explains how to install Nvidia drivers on Arch: https://wiki.archlinux.org/title/NVIDIA
