### ISSUE TITLE
Nvidia PRIME render offload broken on NixOS

### ISSUE THREAD

**Issue by SharkLava** [lutris/lutris#4700]
OS: NixOS 22.11
DE: GNOME Wayland

Lutris doesn't use Nvidia GPU when running games.

What I've tried so far:
- Running lutris with `nvidia-offload lutris`
- Adding `nvidia-offload` to command prefix

Neither worked. any help is appreciated

**Comment by strycore** [comment]
You shouldn't need to use either of those options, there is an offload option in the system tab.
