### ISSUE TITLE
Installing fonts for ever

### ISSUE THREAD

**Issue by Mhiw** [lutris/lutris#4701]
I tried to install Overwatch 2 and The Battle.net client recently but I had some wired issues. When I tried to install Battle.net it just said: "Installing Arial font" and just loading for ever. Why is this happening?

**Comment by EtereosDawn** [comment]
same here

**Comment by legluondunet** [comment]
Hello, is this issue still relevant? I can not reproduce it.

**Comment by strycore** [comment]
winetricks font problems have been fixed
