### ISSUE TITLE
 I can't added the games to steam using the add to steam right click shortcut

### ISSUE THREAD

**Issue by 36238** [lutris/lutris#4702]
I can't added the games to steam using the add to steam right click shortcut

  I can't added the games to steam using the add to steam right click shortcut

**Comment by legluondunet** [comment]
You didn't give us enough information about your issue, is it still relevant?

**Comment by phila-delphia** [comment]
Hi there I have the same problem as the OP. No matter what game I install, Lutris will not create a steam shortcut. I am on Lutris 0.5.12

1.) Install game through Lutris
2.) Have game in Lutris library
3.) Right click on the game
4.) select "create steam shortcut"

Even closing down steam while selecting "create steam shortcut" or after restarting steam the shortcut will not appear.

All the best

phila

**Comment by legluondunet** [comment]
In this case @phila-delphia , I close this one.
