### ISSUE TITLE
Lutris-GE-Proton7-35 downloads incorrectly

### ISSUE THREAD

**Issue by Mikaka27** [lutris/lutris#4703]
When I try to download Lutris-GE-Proton7-35 via lutris, what is downloaded is the source code, not the compiled binaries.
See picture:

![image](https://user-images.githubusercontent.com/9214100/211144600-f835431d-83d9-443e-997e-fc39ea9eab20.png)

**Comment by danieljohnson2** [comment]
I looks to me like this is server side, not a client bug.

At 'https://lutris.net/api/runners/wine' you can see all the URLs it downloads, and this version downloads from: 'https://github.com/GloriousEggroll/wine-ge-custom/archive/refs/tags/GE-Proton7-35.tar.gz'.

A more typical URL is 'https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton7-33/wine-lutris-GE-Proton7-33-x86_64.tar.xz'

I'm not sure what's going on here.

**Comment by Mikaka27** [comment]
Perhaps @GloriousEggroll would know more?

**Comment by danieljohnson2** [comment]
More likely @strycore, I think, but I'm looking into it.

**Comment by danieljohnson2** [comment]
OK, I think it was just uploaded wrongly to the website. I don't think I have the rights needed to fix it, so I'll ping @strycore about this.

**Comment by GloriousEggroll** [comment]
sorry about that, my fault. should be fixed now

**Comment by danieljohnson2** [comment]
It looks better now. Thanks!
