### ISSUE TITLE
Please add all gamescope launch options to lutris system options

### ISSUE THREAD

**Issue by dPing** [lutris/lutris#4707]
lutris forced -f but instead, could you add system options for each of the properties: 

See gamescope --help for a full list of options.

-w -h and -W -H are already in the menu

-r: set a frame-rate limit for the game. Specified in frames per second. Defaults to unlimited.
-o: set a frame-rate limit for the game when unfocused. Specified in frames per second. Defaults to unlimited.
-U: use AMD FidelityFX™ Super Resolution 1.0 for upscaling (might combine this with current FSR when set
-Y: use NVIDIA Image Scaling v1.0.3 for upscaling
-i: use integer scaling.
-b: create a border-less window.
-f: create a full-screen window.

**Comment by dPing** [comment]
Might be able to link this to https://github.com/lutris/lutris/issues/4386

**Comment by dPing** [comment]
and https://github.com/lutris/lutris/issues/3761

**Comment by Astrobald** [comment]
Here is my [commit](https://github.com/Astrobald/lutris/tree/gamescope-options) to use only for testing.

![gamescope-options-lutris](https://user-images.githubusercontent.com/93470373/215870664-f9e1eec6-d396-4f1d-ab9a-fe4274d008ab.png)

**Comment by dPing** [comment]
This is great! Would an additional options box be viable? I.e., I found that I needed to add --force-grab-cursor for wayland in the new gamescope-git. This might be the better solution all around.

**Comment by dPing** [comment]
Also, saw your commit earlier today @Astrobald. Will test that before I close up for the day

**Comment by dPing** [comment]
@Astrobald  I hope my feedback is welcome.  From top to bottom:

The Enable Gamescope toggle/Output Res/Game res were there before. no issue with those.

*Fullscreen (-f) is good but I'm assuming its set to full by default. suggestion might default to -f and toggle between borderless (-b)

*FSR (--fsr-sharpness) level seems to try to apply regardless of the FSR (-U) toggle is on or off. 

*Limiter (-r ##) seems to apply sometimes but other times its ignored. this might not be an issue with you as I hadn't tested this before.  The toggle seems to work as intended by removing the max fps when set to off.

*Adaptive sync (--adaptive-sync) shows it in the command line but does not seem to actually apply adaptive sync (I'm on wayland). This worked for me via command line along side  with full screen (-f)

Relative mouse mode (--force-grab-cursor) works perfectly!

Last notes is Ferral Gamer mode and mangohud are functioning as expected as I know previously mangohud needed to apply after gamescope so these are good as well

**Comment by Astrobald** [comment]
The fps limiter (-r) has no effect when I disable the buid-in vsync option in video games settings and it gets weird when I put a higher value than my monitor's refresh rate. I'm not sure if this option is useful. I rearranged the rest of the code a bit, but it needs to be validated by a python guru.

**Comment by dPing** [comment]
> The fps limiter (-r) has no effect when I disable the buid-in vsync option in video games settings and it gets weird when I put a higher value than my monitor's refresh rate. I'm not sure if this option is useful. I rearranged the rest of the code a bit, but it needs to be validated by a python guru.

Been using this for a few days now. It works well for what you have in there. Is FSR removed for now? I do not use it but I'd assume others might.

**Comment by dPing** [comment]
@Astrobald I appreciate you rebasing this from time to time. I do update this when I see you've done this.  I just wish we could get a lutris dev to take a look at this.

**Comment by danieljohnson2** [comment]
No need; this was PR #4741, and it's been merged and even given a face-lift. It just didn't reference this issue here. But there's no need to rebase it anymore, and I'll just close this issue as completed.

Look forward to Gamescope scopeyness in 0.5.13.
