### ISSUE TITLE
Why am i getting this error for the past week??

### ISSUE THREAD

**Issue by LethalManBoob** [lutris/lutris#4710]
![image](https://user-images.githubusercontent.com/30273211/212436403-79c31e03-805c-4100-ae36-1942f2f024b3.png)
Archlinux btw

**Comment by danieljohnson2** [comment]
Need a bit more than this.

Please run lutris from the command line with "lutris -d"; this will produce lots of console spam. Give us this output.

Might be a clue in there.

**Comment by strycore** [comment]
incomplete report
