### ISSUE TITLE
$GAMEDIR set to NONE with ScummVM install script

### ISSUE THREAD

**Issue by Bug-Fighter** [lutris/lutris#4712]
I write the following script to install a game from an iso file :

#----------------------------------------------------------------------
name: Old french game
game_slug: KK1a
version: "'Old french game'\n\nFrench ISO file"
slug: setup-KK1a
runner: scummvm

script:
  game:
    game_id: kk1-cd-fr
    path: $GAMEDIR
    subtitles: true

  installer:
  - insert_disc:
      description: "install from an ISO file"
      message: Mount 'KK.iso'
      requires: autorun.inf
  - merge:
      src: $DISC
      dst: $GAMEDIR

  scummvm:
    fullscreen: true
    aspect: false
#----------------------------------------------------------------------

This script runs without any problem. When launching the game, lutris returns that GAMEDIR has been set to NONE.
I copy the entire ISO file to a 7z archive and write the following new script 

#----------------------------------------------------------------------
name: Old french game
game_slug: KK1a
version: "'Old french game'\n\nFrench ISO file"
slug: setup-KK1a
runner: scummvm

script:
  game:
    game_id: kk1-cd-fr
    path: $GAMEDIR
    subtitles: true

  files:
  - archive: "N/A:Select archive : KK1a.7z"

  installer:
  - extract:
      description: Extracting games data
      dst: $GAMEDIR
      file: archive
      format: 7z

  scummvm:
    fullscreen: true
    aspect: false
#----------------------------------------------------------------------

GAMEDIR is now set to a valuable directory.
So, I test the following script :

#----------------------------------------------------------------------
name: Old french game
game_slug: KK1a
version: "'Old french game'\n\nFrench ISO file"
slug: setup-KK1a
runner: scummvm

script:
  game:
    game_id: kk1-cd-fr
    path: $GAMEDIR
    subtitles: true

  files:
  - archive: "N/A:Select archive : KK1a.7z"

  installer:
  - insert_disc:
      description: "install from an ISO file"
      message: Mount 'KK.iso'
      requires: autorun.inf
  - merge:
      src: $DISC
      dst: $GAMEDIR

  scummvm:
    fullscreen: true
    aspect: false
#----------------------------------------------------------------------

Even if the files section is useless for game's install, it's mandatory to get a valuable GAMEDIR directory.

Is there something wrong with the building of $GAMEDIR value ?

**Comment by danieljohnson2** [comment]
Your scripts seem to have been mangled by markdown. Can you provide the originals somehow? I think using 'insert_disc' ought to be enough for $GAMEDIR to work, and I'm not sure why it's not working for you.

**Comment by Bug-Fighter** [comment]
Please find attached the three mentioned scripts.

I'm using the 0.5.8.4 version of Lutris provide by Mageia 8. Like you, I 
think using 'insert_disc' ought to be enough for $GAMEDIR to work. I 
never experienced that issue with other runners like wine, dosbox, 
hatari, mame and zdoom, it only appears with scummvm.

I got a workaround using an archive file, so I don't worry about.

With my best thanks for your answer.

***@***.***

**Comment by danieljohnson2** [comment]
Find the attached scripts where?

0.5.8.4 is a bit elderly. Maybe you should try 0.5.12, the finest and shiniest. Though it seems to me that 0.5.8.4 ought to have worked.

**Comment by Bug-Fighter** [comment]
As you tell me to do, I built and installed the 0.5.12 version of Lutris.

Then I tried the first script with different ISO files. I got the following messages when usually lutris ask for Selecting an installation directory

Error while completing task <bound method CommandsMixin.insert_disc of <interpreter.ScriptInterpreter object at 0x7f3d8c641a80 (lutris+installer+interpreter+ScriptInterpreter at 0x341d1a0)>>: <class 'TypeError'> argument of type 'NoneType' is not iterable
  File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/installer/commands.py", line 231, in insert_disc
    self._check_required_params("requires", data, "insert_disc")
  File "/usr/lib/python3.8/site-packages/lutris/installer/commands.py", line 72, in _check_required_params
    if param not in command_data:

The second script stay fully operational, but the third one complains as the first one. 

Hope it would be useful
 
[scripts.zip](https://github.com/lutris/lutris/files/10429745/scripts.zip)

**Comment by danieljohnson2** [comment]
Well, the weird thing is that I can't seem to get the exact errors you are getting. I get a lot of "'str' object has no attribute 'items'"; I've run down a few bugs these installers revealed to me, so thanks for that.

The underlying problem you are having, I think, is missing hyphens in the YML; you need a '-' before "archive:" and before 'insert_disc:' and perhaps other places. The [installers.rst](https://github.com/lutris/lutris/blob/master/docs/installers.rst) file has examples of what this looks like.

**Comment by legluondunet** [comment]
Hello, is this issue still relevant?

**Comment by Bug-Fighter** [comment]
Sorry staying mute for a long time, sadly, I still experience it.

I tried to get more details about it. So I play lutris 0.5.12 with Mageia 9 Beta 1 (yes it's a Beta one, but it provides the most up to date version of all needed packages). I rewrote properly all scripts and I used the lutris debug command : -d.

Scripts 2 and 3 play the game with no problems. Script 1 copy all files to ~/None instead of $GAMEDIR 

DEBUG    2023-04-16 15:05:37,312 [installerwindow.show_installer_files_screen:339]:Installer doesn't require files
DEBUG    2023-04-16 15:05:37,312 [interpreter._iter_commands:322]:Installer command: {'insert_disc': {'message': "Mount 'KK1a.iso'", 'requires': 'install.exe'}}
DEBUG    2023-04-16 15:05:41,484 [commands._find_matching_disc:257]:Found install.exe on cdrom /run/media/bugfighter/GK1a
DEBUG    2023-04-16 15:05:41,485 [interpreter._iter_commands:322]:Installer command: {'merge': {'src': '$DISC', 'dst': '$GAMEDIR'}}
DEBUG    2023-04-16 15:05:41,491 [commands.merge:276]:Merging /run/media/bugfighter/GK1a into None
DEBUG    2023-04-16 15:05:41,496 [system.merge_folders:260]:Merging /run/media/bugfighter/GK1a into None
DEBUG    2023-04-16 15:05:42,183 [commands._killable_process:557]:Process <function merge_folders at 0x7ffa0ce42710> returned: None

In my point of view, it's a very minor issue. There's a workaround.

Thank you staying tuned


[log.txt](https://github.com/lutris/lutris/files/11242385/log.txt)

**Comment by danieljohnson2** [comment]
Once again, this reveals a bug to me, but it's not your issue. It shouldn't substitute the text "None" into your path if no target dir is selected. Its supposed to just leave those replacement, so you get "~/$GAMEDIR"

I've fixed this, which doesn't help you at all. Yay for useless technical support!

Just kidding, I can do better than that. You script has "insert_disc" instead of the correct "insert-disc". The script interpreter is tolerant of this, but there is a check for "do we create a GAMEDIR" that looks only for the hyphenated form.

I've corrected this check so your script will work, but you may want to correct your scripts anyway for compatibility with older Lutris versions.

**Comment by Bug-Fighter** [comment]
changing insert_disc to insert-disc do the job

well done
