### ISSUE TITLE
Ubisoft Connect login stuck on empty browser window

### ISSUE THREAD

**Issue by asbi12** [lutris/lutris#4713]
### Bug description

(This is my first bug report, I hope everything is done correctly)
I am running the latest lutris 0.5.12 on Ubuntu 22.10 and the Ubisoft Connect login does not work for me.
I saw the other issue about 2FA, but that is supposed to be fixed, I disabled 2FA on my account anyway for testing, but this seems to be a different problem.
There are some errors in the log, see log output.
Any idea(s) what could be the cause? Thank You.

### How to Reproduce

- start lutris
- click on the add account button (remove first because it is missing the token from previously failed attempt)
- log in
- white/empty window stays open forever
- log shows some python errors

### Expected behavior

get the token for the account and close the window after logging in

### Log output

```shell
asbi@asbis-pc:~$ lutris -d
INFO     2023-01-15 19:33:37,515 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-01-15 19:33:37,538 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-01-15 19:33:37,753 [startup.check_driver:57]:Using NVIDIA drivers 525.60.11 for x86_64
INFO     2023-01-15 19:33:37,753 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3060 Ti
INFO     2023-01-15 19:33:37,753 [startup.check_driver:77]:GPU: 10DE:2486 19DA:6630 (nvidia drivers)
INFO     2023-01-15 19:33:37,753 [startup.check_driver:77]:GPU: 8086:9BC5 1462:7C77 (i915 drivers)
DEBUG    2023-01-15 19:33:37,856 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-01-15 19:33:37,861 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-01-15 19:33:40,020 [base.wipe_game_cache:343]:Deleting ubisoft cache /home/asbi/.cache/lutris/ubisoft/library/
DEBUG    2023-01-15 19:33:40,020 [base.wipe_game_cache:156]:Deleting games from service-games for ubisoft
DEBUG    2023-01-15 19:33:40,021 [base.logout:358]:logged out from ubisoft
DEBUG    2023-01-15 19:33:40,022 [lutriswindow.update_store:448]:Showing 0 games
DEBUG    2023-01-15 19:33:51,451 [base.login:332]:Connecting to Ubisoft Connect

(process:40751): GLib-CRITICAL **: 19:33:52.842: Failed to set scheduler settings: Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/webconnect_dialog.py", line 78, in on_navigation
    self.service.login_callback(url)
  File "/usr/lib/python3/dist-packages/lutris/services/ubisoft.py", line 121, in login_callback
    user_data = self.client.authorise_with_local_storage(storage_jsons)
  File "/usr/lib/python3/dist-packages/lutris/util/ubisoft/client.py", line 221, in authorise_with_local_storage
    for key in json_:
TypeError: 'NoneType' object is not iterable
```

### System Information

```shell
[System]
OS:              Ubuntu 22.10 Kinetic Kudu
Arch:            x86_64
Kernel:          5.19.0-29-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
Physical cores:  10
Logical cores:   20

[Memory]
RAM:             31.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.60.11
OpenGL Core:     4.6.0 NVIDIA 525.60.11
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.60.11
Vulkan:          Supported
```

### Media (optional)

![Screenshot_20230115_200320](https://user-images.githubusercontent.com/122747673/212562187-b21cf9c9-ba70-4470-8f5d-cba90e3110cc.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Ah, the good old issue template, I love it so.

The trace-back shows a None showing up where it should not; quite mysterious. I've put together a branch to try to produce some information to help me understand this.

Please download [this branch](https://github.com/lutris/lutris/tree/dj/ubisoft_credential_none); you need not install it, just run the "bin/lutris" script within with the -d option ("./bin/lutris -d"). Try to log in to Ubisoft. Let us know how that goes. Also provide the log output, which should contain more stuff now.

Thanks.

**Comment by asbi12** [comment]
Wow, thank You for the quick response!
I downloaded that brach and in fact I can login with it.
What exactly was changed except the logging?
After logging into my account using this version, now the regular installed lutris also shows my Ubisoft connect games.
Only if I log out I get the same error as before when trying to log back in in the regular version.

I uploaded the full log output from ./bin/lutris -d (just replaced my mail address, uplay user name and IP):
[log.txt](https://github.com/lutris/lutris/files/10421184/log.txt)

**Comment by danieljohnson2** [comment]
I added a check to just skips nulls in the JSON credentials. A guess, but it worked. The log you posted shows the null in there, but the credentials you need are also in there, so all we need to do is skip the null after all.

I've committed this fix to the master. The next release should take care of this; until this, you can download the master branch to log in. I'll delete my test branch.
