### ISSUE TITLE
ubisoft connect [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by traplover4200** [lutris/lutris#4717]
i have try reinstalling ubisoft connect and lutris
![Screenshot_20230119_220207](https://user-images.githubusercontent.com/67037357/213609329-4c8e49c7-0942-481a-85d0-a57ec6bdac0e.png)

**Comment by moonphase97** [comment]
same issue with steamdeck

**Comment by victorjoia** [comment]
I was having the same error. I opened Ubisoft Connect and logged in through it.
After that the game list loaded without this error, but the game images didn't load.

**Comment by Larsimusrex** [comment]
Same issue here. I also get a "A Ubisoft Service Is Currently Unavailable" error when launching the Ubisoft Connect directly, which is apparently an error with Ubisoft Uplay DRM.

**Comment by Vite13371337** [comment]
I am also having the same issue and am not able to start Ubisoft Connect from inside of lutris on EndeavourOs.

**Comment by LoKolbasz** [comment]
Have you tried the running 
`mkdir -p "~/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft Game Launcher/cache/configuration/configurations"`
from the terminal?

**Comment by kxxt** [comment]
After launching Ubisoft Connect and login for the first time, this error disappeared.

**Comment by Larsimusrex** [comment]
running `# sysctl net.ipv4.tcp_mtu_probing=1` resolved the issue for me.

**Comment by strycore** [comment]
Fixed in current release
