### ISSUE TITLE
lutris -v ran from a separate terminal returns nothing while Lutris is running

### ISSUE THREAD

**Issue by the-sane** [lutris/lutris#4719]
### Bug description

If Lutris is currently running, attempting to query its version in a new terminal via `lutris -v` returns nothing to that terminal. This is a side effect of preventing multiple Lutris instances from running, as the version info is instead printed to the currently running instance.

This is more of a feature request than a bug since it's likely intended behavior. Perhaps `lutris -v` could be a special exception to the single instance only behavior since all it does is print the version info then exit.

**Reason for reporting:**
I maintain a helper script for the Star Citizen Linux Users Group. One of its functions is to check system prerequisites, including the installed version of Lutris. If Lutris is currently running, the script is unable to properly detect Lutris' version.

Thanks!

### How to Reproduce

1. Launch Lutris
2. Open a new terminal and run `lutris -v`
3. Nothing is printed to the new terminal

### Expected behavior

Ideally, it would be possible for a script running in a separate terminal to query Lutris for its version even while Lutris is running.

### Log output

```shell
If Lutris is run from a terminal in repro step 1, the version info is printed to that terminal. This is working as intended as mentioned above.
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.7-hardened1-1-hardened
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.6 GB
Swap:            16.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX Vega (vega10, LLVM 15.0.7, DRM 3.49, 6.1.7-hardened1-1-hardened)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.3
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I see it; the --version option needs to be handled locally, not sent over to the running instance. That seems simple.

**Comment by the-sane** [comment]
@danieljohnson2 Thanks a lot!
