### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#472]
Build for Ubuntu 17.04 Zesty?

http://download.opensuse.org/repositories/home:/strycore/xUbuntu_17.04/

**Comment by strycore** [comment]
Zesty repos won't be available in OBS before the release (that's the annoying thing about OBS, they're never in a hurry to provide up to date distro support).

Do not re-open before April :D

**Comment by RobLoach** [comment]
:1st_place_medal:
