### ISSUE TITLE
Game launch problem

### ISSUE THREAD

**Issue by ozanbabatas59** [lutris/lutris#4721]
I downloaded the game from Origin. I'm getting this error when trying to open the game on my desktop

Translate: Lutris software quit unexpectedly

![Ekran Görüntüsü - 2023-01-23 23-09-30](https://user-images.githubusercontent.com/123414247/214139859-9e73fad6-03fb-4074-81eb-2e6265968ec8.png)

**Comment by strycore** [comment]
Lack of information but try the latest release and use EA App instead of Origin.
