### ISSUE TITLE
Lutris seems to have outdated dxvk and vkd3d vulkan translation layers.

### ISSUE THREAD

**Issue by lilxandrias** [lutris/lutris#4723]
### Bug description

DXVK 2.0 and VKD3D 2.8 provides many critical bug fixes and features, but upstreaming DXVK and VKD3D are available in Lutris. Manually downloading VKD3D and DXVK is too much hassle. Also Lutris should have optional Discord presence too, if the game isn't listed on Lutris website, it should just show game name as discord presence, but it's not directly connected with the DXVK 2.0 and VKD3D 2.8.

VKD3D latest updates brings many fixes for many games, i think it's important.

### How to Reproduce

1. Open Lutris game preferences
2. no latest DXVK and VKD3D versions :(

### Expected behavior

It should always be up to date, or atleast optional.

### Log output

```shell
I think log output is not required with my issue.
```

### System Information

```shell
Arch Linux, BTW
(even though it's not required with my issue)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Well, I believe there is some concern that if DXVK 2.0 becomes the new default, existing working setups will break.

This is because (apparently) it requires newer drivers. For users that do not have these drivers, upgrading Lutris would put their games on DXVK 2.0, and boom, dead.

**Comment by BrandowLucas** [comment]
Well, agreed. Newer versions may break some games configs but that's why the dxvk version selector exists, if someone is concerned about changing to newer version of dxvk just don't. I am waiting to Lutris 0.5.13 come with dvxk 2.1.

**Comment by lilxandrias** [comment]
> Well, agreed. Newer versions may break some games configs but that's why the dxvk version selector exists, if someone is concerned about changing to newer version of dxvk just don't. I am waiting to Lutris 0.5.13 come with dvxk 2.1.

Yeah, it should at least be in selection. Newer DXVK and VKD3D versions are important, because they fix many games and issues.

DXVK release notes: https://github.com/doitsujin/dxvk/releases
VKD3D release notes: https://github.com/HansKristian-Work/vkd3d-proton/releases

I believe Lutris shouldn't force newer DXVK or VKD3D version, if they don't want to break existing working setups, it just should be an option. For example, newer VKD3D fixes many bugs in HITMAN III for me and newer DXVK version fixes Resident Evil 4 HD for me.

**Comment by awsms** [comment]
So far.. every single runtime is outdated
https://github.com/dege-diosg/dgVoodoo2/releases/tag/v2.79.3 => lutris is 2.79.1
https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.6.1 => lutris is 0.5.4
https://github.com/HansKristian-Work/vkd3d-proton/releases/tag/v2.8 => lutris is 2.6
https://github.com/doitsujin/dxvk/releases/tag/v2.1 => lutris is 1.10.3

> Well, I believe there is some concern that if DXVK 2.0 becomes the new default, existing working setups will break.
> 
> This is because (apparently) it requires newer drivers. For users that do not have these drivers, upgrading Lutris would put their games on DXVK 2.0, and boom, dead.

This really is a non-issue as anyone could simply right-click and change the runtime's version

**Comment by legluondunet** [comment]
Dxvk and Vk3d are now updated in Lutris, you can close this ticket.

**Comment by GenocideStomper** [comment]
Does this mean Lutris runtime has an active maintainer now? Or is this a one-off bump?

**Comment by GloriousEggroll** [comment]
resolved, I've updated the relevant components.

**Comment by QmwJlHuSg9pa** [comment]
> resolved, I've updated the relevant components.

I'm curious, through what mechanism/service does this work? As I see no relevant commits present...

**Comment by danieljohnson2** [comment]
Dgvoodoo2 has its own repo [here](https://github.com/lutris/dgvoodoo2/tags). There's a new release there.

Darned if I can find EAC or BattleEye though. Mysterious.
