### ISSUE TITLE
cant add games to steam om steam deck

### ISSUE THREAD

**Issue by svenvanham** [lutris/lutris#4724]
### Bug description

when i try to add to steam (yes i fully closed steam) nothing happens. If i click a game again kt says delete from steam even though it never was added.

### How to Reproduce

1. Go to Main page
2. right click on game
3. Do add to steam
4. See that when you check again it shows delete from steam

### Expected behavior

It should show up in steam.

### Log output

```shell
did not get log om flatpack
```

### System Information

```shell
[System]
OS:              GNOME 43 Flatpak runtime
Arch:            x86_64
Kernel:          5.13.0-valve36-1-neptune
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Custom APU 0405
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             14.5 GB
Swap:            1.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.2 (git-a09d5e2747)
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.2 (git-a09d5e2747)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.2 (git-a09d5e2747)
Vulkan:          Supported

(steam deck)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by superboo07** [comment]
do you have two steam accounts added like I do, I have this issue as well. It only happens after adding a second account (and cannot be fixed even by removing the second as it will continue to add them to it after logging out)

**Comment by svenvanham** [comment]
I only have 1 account.

**Comment by superboo07** [comment]
hm, the issue for me happened after adding a second account

**Comment by al12gamer** [comment]
1.  Make sure you're on SteamOS Stable, as I believe that's what Strider is testing against
2.  Make sure the flatpak of lutris is up to date and is not the early access/beta version
3.  With recent updates, some people have been reporting that Steam just opens the "add a non steam game" browser menu when you hit that right click button in Lutris...is that happening here?

**Comment by strycore** [comment]
> Make sure you're on SteamOS Stable, as I believe that's what Strider is testing against

I mostly run SteamOS Preview.

> Make sure the flatpak of lutris is up to date and is not the early access/beta version

It's not possible to have an out of date Flatpak. Flatpak Beta isn't enabled by default.

**Comment by zowhoey** [comment]
I was experiencing the same issue as a result of a game not having a cover/banner image and Lutris silently failing.
Lutris attempts to copy the cover/banner images and if they are not found the shortcut does not appear in Steam.

**Comment by strycore** [comment]
I created a game in Lutris with no banner or cover and the Steam shortcut was added without issue so whatever is causing this problem, that's not it.

**Comment by zowhoey** [comment]
This is similar output to what I was seeing in the logs when creating a Steam shortcut before, after setting a cover and a banner for the game I tried creating a Steam shortcut again and it worked.

```
2023-07-11 20:43:06,198: Creating Steam shortcut for Test Game (wine)
2023-07-11 20:43:06,213: Failed to copy cover to /home/deck/.local/share/Steam/userdata/94115526/config/grid/3662337813p.jpg: [Errno 2] No such file or directory: '/home/deck/.var/app/net.lutris.Lutris/cache/lutris/coverart/test-game.jpg'
2023-07-11 20:43:06,214: Failed to copy banner to /home/deck/.local/share/Steam/userdata/94115526/config/grid/3662337813_hero.jpg: [Errno 2] No such file or directory: '/home/deck/.var/app/net.lutris.Lutris/cache/lutris/banners/test-game.jpg'
```

I just tried to reproduce this again and it did not actually work, I was seeing the same errors when cover and banner images weren't set, but when I did set them creating a Steam shortcut still didn't work. There are no errors in the logs.

**Comment by strycore** [comment]
This bug report is a year old and there hasn't been reports of issues with Steam Deck shortcuts creation. The current Lutris version has an option to select between multiple Steam accounts which was the main cause of shortcuts not being created.
