### ISSUE TITLE
Option to disable Comptom/Picom for better performance

### ISSUE THREAD

**Issue by Swivelgames** [lutris/lutris#4725]
This is to add support for Picom and Compton to `Disable Desktop Effects`, introduced in #881 given the popularity of these compositors.

**Comment by o-schneider** [comment]
I saw that picom/compton handling has been added by reading the code (it wasn't in the changelog!) but it isn't working properly. The function `_get_compositor_commands` in `util/display.py` is called to find which commands to use for both disabling and enabling the compositor. Picom or compton commands will be used if a process with their name can be found. This works fine for disabling, but when the compositor should be re-enabled, there's no picom or compton process, so no restart. The functions used should be kept in memory I guess (and probably rather found at startup or first-run, there's little chance that it changes while lutris is running).

**Comment by danieljohnson2** [comment]
I see what you mean; and I think you are right. I've tweaked the code.

Since you can test this, please download the latest master code and run the 'bin/lutris' script within- no need to install anything. Activate the compositor-disable feature and try it; does it work better now?

**Comment by o-schneider** [comment]
Yup, the fix works! Nice! :)

Though I read the original PR comments and strycore has a point saying this feature is kinda outdated, made me try a bit more picom's `unredir-if-possible` option and it seems to work ok, probably the way to go rather than killing and restarting processes like that.

**Comment by danieljohnson2** [comment]
Yeah, it is outdated. I guess we'll remove it just as soon as we've got it working right!

Thanks for the report though.
