### ISSUE TITLE
Flatpak Lutris create .desktop shortcut in wrong folder

### ISSUE THREAD

**Issue by 777Raim** [lutris/lutris#4726]
### Bug description

When tried to create App menu shortcut, Lutris created .desktop file in `/home/user/.var/app/net.lutris.Lutris/data/applications/` instead `/home/user/.local/share/applications/`

But when tried to create Desktop shortcut, Lutris created .desktop file in right place `/home/user/Desktop/`

RPM Lutris creates .desktop file in right places

### How to Reproduce

1. Go to 'flatpak run net.lutris.Lutris -d'
2. Click on 'Create application menu shortcut'
4. See `DEBUG    2023-01-26 11:14:29,461 [xdgshortcuts.create_launcher:98]:Creating menu launcher in /home/user/.var/app/net.lutris.Lutris/data/applications/net.lutris.***.desktop`

### Expected behavior

Lutris create .desktop file in `/home/user/.local/share/applications/`

### Log output

```shell
DEBUG    2023-01-26 11:14:29,461 [xdgshortcuts.create_launcher:98]:Creating menu launcher in /home/user/.var/app/net.lutris.Lutris/data/applications/net.lutris.***.desktop
```

### System Information

```shell
[System]
OS:              GNOME 43 Flatpak runtime
Arch:            x86_64
Kernel:          6.1.7-200.fc37.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             17.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Vega 8 Graphics (raven, LLVM 14.0.6, DRM 3.49, 6.1.7-200.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.2 (git-a09d5e2747)
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.2 (git-a09d5e2747)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.2 (git-a09d5e2747)
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by A6GibKm** [comment]
I am not sure if this should be reported to the flatpak repo. One could use portals to create the desktop file.

**Comment by RushingAlien** [comment]
You can just add the `xdg-data/applications` permission for a workaround for now

**Comment by strycore** [comment]
I've added a path  for that issue recently. Try out Lutris from Flathub Beta and the shortcuts should be created in the right directory. Or wait for 0.5.14 stable, it's almost out.
