### ISSUE TITLE
lutri mass import does not import anything

### ISSUE THREAD

**Issue by fekir** [lutris/lutris#4733]
### Bug description

When scanning for already installed games, lutris does not find anything

### How to Reproduce

1. open the dialog for importing games
2. Click on 'scan a folder for games'
3. Select '/usr/games' as folder

### Expected behavior

Currently the output of `ls /usr/games` is

````
0ad
lutris
supertux2
tuxmath
tuxtype
````

I would have expected lutris to find, for example, `0ad`, as it can be installed directly in lutris.

### Log output

```shell
lutris -d
Gtk-Message: 23:09:15.928: Failed to load module "xapp-gtk3-module"
INFO     2023-02-03 23:09:19,130 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-02-03 23:09:19,223 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-03 23:09:19,570 [startup.check_driver:65]:Running Intel Mesa driver 22.3.3 on Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
INFO     2023-02-03 23:09:19,570 [startup.check_driver:77]:GPU: 8086:3EA0 1558:1323 (i915 drivers)
DEBUG    2023-02-03 23:09:19,900 [lutriswindow.update_store:448]:Showing 7 games
INFO     2023-02-03 23:09:19,956 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-02-03 23:09:21,816 [application.show_window:328]:Showing window AddGamesWindow{}
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux n/a bookworm
Arch:            x86_64
Kernel:          6.1.0-2-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.1 GB
Swap:            34.2 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.3
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/11912465/216720562-8ac8e082-3cc7-44ea-bbd7-1f6e14b61724.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Lutris tries to recognize the games by the sub-directory names, and none of those directories match a game known to Lutris.

The closest is '0ad', but Lutris has that as '0-ad', which is not quite close enough.

The rest don't seem to be games that appear on Lutris.net at all. I think it's working at designed.

**Comment by fekir** [comment]
@danieljohnson2 

I've tried installing supertuxkart, which appears on lutris.net (https://lutris.net/games/supertuxkart/), this game is also not detected

````
ls /usr/games 
0ad
gcompris-qt
hedgewars
lutris
mgba-qt
pyrogenesis
supertux2
supertuxkart
tuxmath
tuxtype
```

**Comment by danieljohnson2** [comment]
Oh, I see. You can't use /usr/games here because it contains files, not sub-directories. Lutris needs to give each game its own game-directory, and /usr/games is really not a good choice for that- it has the game executable directly within it.

We could imagine a feature to work around this somehow, but as it is I think it's reasonable limitation.

**Comment by fekir** [comment]
Ah, I missed the part that it needs to be directories!

debian-based distribution have a /usr/games folder, and I assume most other GNU/Linux distributions too.

It would be nice if lutris had a way to detect and show automatically already-installed games, supporting thus /usr/games would be a nice (maybe as additional source? side by side with gog, lutris, origin, ...)
