### ISSUE TITLE
0.5.12 - Launching game via desktop/menu only opens main Lutris window rather than the game

### ISSUE THREAD

**Issue by Unaccounted4** [lutris/lutris#4737]
### Bug description

Rather than opening the game as it did in previous version launching from a shortcut or from a terminal command, eg `lutris lutris:rungameid/*` only opens the main lutris window and does not launch the game.

### How to Reproduce

1. Open Lutris
2. Right click game to create desktop/menu shortcut for a game
3. Close Lutris
4. Double click the desktop shortcut, click the menu entry to launch, or run it via lutris lutris:rungameid/* 
5. The Lutris main window will reopen, but not the game

### Expected behavior

The game should open.

### Log output

```shell
╼ lutris -d
2023-02-06 20:18:37,595: Starting Lutris 0.5.12
2023-02-06 20:18:37,624: Running AMD Mesa driver 22.3.4 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.48, 6.0.18-301.fsync.fc37.x86_64) (0x73df)
2023-02-06 20:18:37,625: GPU: 1002:73DF 1DA2:E445 (amdgpu drivers)
2023-02-06 20:18:47,051: Starting Lutris 0.5.12
2023-02-06 20:18:47,063: Running AMD Mesa driver 22.3.4 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.48, 6.0.18-301.fsync.fc37.x86_64) (0x73df)
2023-02-06 20:18:47,063: GPU: 1002:73DF 1DA2:E445 (amdgpu drivers)
```

### System Information

```shell
[System]
OS:              Nobara Linux 37 KDE Plasma
Arch:            x86_64
Kernel:          6.0.18-301.fsync.fc37.x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            40.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.48, 6.0.18-301.fsync.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.4
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.4
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.4
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
working fine here.

**Comment by Unaccounted4** [comment]
This was a bug with the Nobara package. An update has been released which fixes the issue.
