### ISSUE TITLE
Installing any game only show a popup 'exe'

### ISSUE THREAD

**Issue by lestofante** [lutris/lutris#4738]
### Bug description

every time i try to install a game (epic stores, i dont have any other) the only thing happening is a little popup box that say 'exe' (apostrophe included)

starting lutris with debug print does not give much info

tested with Word War Z, Warhammer 40k mechanicus, and few more

### How to Reproduce

1. Connect a Epic Games account
3. Try to install any game

### Expected behavior

the game will install

### Log output

```shell
INFO     2023-02-08 00:15:35,881 [startup.init_lutris:173]:Starting Lutris 0.5.12
    DEBUG    2023-02-08 00:15:35,940 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-08 00:15:35,983 [startup.check_driver:65]:Running AMD Mesa driver 22.3.4 on AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.1.9-arch1-2) (0x731f)
    INFO     2023-02-08 00:15:35,983 [startup.check_driver:77]:GPU: 1002:731F 148C:2398 (amdgpu drivers)
    DEBUG    2023-02-08 00:15:36,235 [lutriswindow.update_store:448]:Showing 62 games
    INFO     2023-02-08 00:15:36,319 [startup.update_runtimes:218]:Startup complete
    DEBUG    2023-02-08 00:15:54,581 [grid.on_item_activated:57]:Item activated: 002b00085aeb49b1a3f3c42e3f918f2f
    DEBUG    2023-02-08 00:15:54,581 [lutriswindow.on_game_activated:857]:Looking up egs game 002b00085aeb49b1a3f3c42e3f918f2f
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.9-arch1-2
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            7.8 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.1.9-arch1-2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.4
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.4
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.4
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/1166173/217389341-79ef35ad-19e5-4974-83b0-756abdfb4d0d.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Well, that looks very much like Python's unhelpful KeyError message. This means there's a dict that should contain something called 'exe' but doesn't.

But there should be a trace-back in that log. It looks much too short. If I could get that trace-back I might be able to do more. Sure there's no more log you can give us?

And does this error occur for any non-EGS games?

**Comment by lestofante** [comment]
> But there should be a trace-back in that log. It looks much too short. If I could get that trace-back I might be able to do more. Sure there's no more log you can give us?

this is all i get with lutris -d. Maybe some try catch that does not rise or log the error properly? :)
Also after clicking ok on the error, no additional output is generated.

Here me trying to install a game trice:

    INFO     2023-02-08 00:31:59,058 [startup.init_lutris:173]:Starting Lutris 0.5.12
    DEBUG    2023-02-08 00:31:59,169 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
    INFO     2023-02-08 00:31:59,254 [startup.check_driver:65]:Running AMD Mesa driver 22.3.4 on AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.1.9-arch1-2) (0x731f)
    INFO     2023-02-08 00:31:59,254 [startup.check_driver:77]:GPU: 1002:731F 148C:2398 (amdgpu drivers)
    DEBUG    2023-02-08 00:31:59,540 [lutriswindow.update_store:448]:Showing 62 games
    INFO     2023-02-08 00:31:59,695 [startup.update_runtimes:218]:Startup complete
    DEBUG    2023-02-08 00:32:02,601 [grid.on_item_activated:57]:Item activated: 1bcd791d54684eb29ed32ad1c0593d12
    DEBUG    2023-02-08 00:32:02,601 [lutriswindow.on_game_activated:857]:Looking up egs game 1bcd791d54684eb29ed32ad1c0593d12
    DEBUG    2023-02-08 00:32:35,789 [grid.on_item_activated:57]:Item activated: 1bcd791d54684eb29ed32ad1c0593d12
    DEBUG    2023-02-08 00:32:35,789 [lutriswindow.on_game_activated:857]:Looking up egs game 1bcd791d54684eb29ed32ad1c0593d12
    DEBUG    2023-02-08 00:32:37,267 [grid.on_item_activated:57]:Item activated: 1bcd791d54684eb29ed32ad1c0593d12
    DEBUG    2023-02-08 00:32:37,268 [lutriswindow.on_game_activated:857]:Looking up egs game 1bcd791d54684eb29ed32ad1c0593d12


> And does this error occur for any non-EGS games?

just tested with GOG games, they seems to work properly

**Comment by danieljohnson2** [comment]
OK, I see the problem with the logging and I'll fix that. But I think I can add a bit more, if it's an egs problem.

Please try [this branch here](https://github.com/lutris/lutris/tree/dj/egs_exe). Just download it, and run the script "bin/lutris" therein. Use the "-d" option. We should get much more logging now.

**Comment by lestofante** [comment]
yay!

`DEBUG    2023-02-09 10:57:12,533 [grid.on_item_activated:65]:Item activated: a96de508ac71471fa05e7c1c695e3b5d
DEBUG    2023-02-09 10:57:12,534 [lutriswindow.on_game_activated:900]:Looking up egs game a96de508ac71471fa05e7c1c695e3b5d
ERROR    2023-02-09 10:57:12,557 [exceptions.wrapper:63]:'exe'
Traceback (most recent call last):
  File "/tmp/lutris/lutris/exceptions.py", line 61, in wrapper
    return function(*args, **kwargs)
  File "/tmp/lutris/lutris/gui/lutriswindow.py", line 915, in on_game_activated
    game_id = self.service.install(service_game)
  File "/tmp/lutris/lutris/services/egs.py", line 409, in install
    [self.generate_installer(db_game, egs_game)],
  File "/tmp/lutris/lutris/services/egs.py", line 367, in generate_installer
    egs_exe = egs_game.config.game_config["exe"]
KeyError: 'exe'

`

**Comment by danieljohnson2** [comment]
That's better, and confirms what's blowing up here, but please try it with [this branch over here](https://github.com/lutris/lutris/tree/dj/egs_exe) not the master branch. More logging in there. I'm hoping to see what game config you actually have.

**Comment by lestofante** [comment]
sorry my bad, i though github clone would checkout the branch

    DEBUG    2023-02-09 11:48:16,933 [grid.on_item_activated:65]:Item activated: a96de508ac71471fa05e7c1c695e3b5d
    DEBUG    2023-02-09 11:48:16,933 [lutriswindow.on_game_activated:900]:Looking up egs game a96de508ac71471fa05e7c1c695e3b5d
    DEBUG    2023-02-09 11:48:16,934 [egs.generate_installer:366]:EGS Game data: {'id': 1, 'name': 'Epic Games Store', 'slug': 'epic-games-store', 'installer_slug': 'epic-games-store-latest', 'parent_slug': None, 'platform': 'Windows', 'runner': 'wine', 'executable': None, 'directory': '/mnt/data/lutris/epic-games-store', 'updated': None, 'lastplayed': 1631221586, 'installed': 1, 'installed_at': 1627180345, 'year': None, 'configpath': 'epic-games-store-latest-1627288968', 'has_custom_banner': None, 'has_custom_icon': None, 'playtime': 5.473611111111111, 'hidden': 0, 'service': None, 'service_id': None, 'has_custom_coverart_big': None, 'discord_id': None}
    ERROR    2023-02-09 11:48:16,946 [exceptions.wrapper:63]:'exe'
    Traceback (most recent call last):
      File "/tmp/lutris/lutris/exceptions.py", line 61, in wrapper
        return function(*args, **kwargs)
      File "/tmp/lutris/lutris/gui/lutriswindow.py", line 915, in on_game_activated
        game_id = self.service.install(service_game)
      File "/tmp/lutris/lutris/services/egs.py", line 410, in install
        [self.generate_installer(db_game, egs_game)],
      File "/tmp/lutris/lutris/services/egs.py", line 368, in generate_installer
        egs_exe = egs_game.config.game_config["exe"]
    KeyError: 'exe'

**Comment by strycore** [comment]
Is your EGS client working as a standalone lutris application?

**Comment by lestofante** [comment]
i have no idea about what you mean.
This is a lutris installation as package here: https://archlinux.org/packages/community/any/lutris/

**Comment by strycore** [comment]
Do you have Epic Games Store in Lutris?

![image](https://user-images.githubusercontent.com/280336/217945457-ff4c6477-a5df-44a7-9685-26d8dc209136.png)

**Comment by strycore** [comment]
It should be installed since the `install()` has this code:
```
egs_game = get_game_by_field(self.client_installer, "slug")
if not egs_game or not egs_game["installed"]:
```
and the code you're hitting is in the else clause. 
And it somehow doesn't have a "exe" field in the config?

If you have a local copy of the code, replace the line:
```
     egs_exe = egs_game.config.game_config["exe"]
```
with:
```
        try:
            egs_exe = egs_game.config.game_config["exe"]
        except:
            print(egs_game.config.game_config)
```

and post the result

**Comment by danieljohnson2** [comment]
I'll add that print() to the branch for @lestofante's convenience.

Just redownload and try again!

**Comment by danieljohnson2** [comment]
So, looking at the most recent log, I'm immediately suspicious of the egs_db_game we just dumped out. It contains None in its 'executable' entry. It does not look like "exe" is really that value, at least not in a direct sort of way, but I bet the same problem is causing both.

**Comment by strycore** [comment]
Oh yeah, I had missed that. EGS is here alright, there's even 5 hours of playtime

**Comment by danieljohnson2** [comment]
Oh, I see. 'egs_db_game' is the Epic Games Store *itself*. But it has no executable.

**Comment by strycore** [comment]
the executable part is stored in the config (the yaml file in ~/.config/lutris), not in the sqlite db

**Comment by strycore** [comment]
@lestofante  much simpler solution, run:

```
cat ~/.config/lutris/games/epic-games-store*
```

**Comment by Kranzes** [comment]
Getting similliar issue with the newly added battle.net support, except it says `egs_game = Game(egs_db_game["id"])` (id instead of exe).

**Comment by strycore** [comment]
It's been almost a year and no one has reported a similar issue, so it's likely not one in the current version of Lutris
