### ISSUE TITLE
Lutris crashes when selecting Steam in Sources tab

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4743]
### Bug description

I am currently on Lutris-git (commit `cac372e`), and when I select `Steam` in the `Sources` tab on the left, Lutris crashes instantly.

It crashes 8/10 times for some reason.
My Steam library is pretty big however (1570) so that might be the reason.

### How to Reproduce

1. Open Lutris
2. Click on Steam in Sources tab on the left side

### Expected behavior

After pressing on Steam in Sources tab, Lutris will freeze for a second, and then crash 8/10 times on average.

### Log output

```shell
❯ lutris -d
INFO     2023-02-10 21:44:13,573 [startup.init_lutris:190]:Starting Lutris 0.5.12
DEBUG    2023-02-10 21:44:13,603 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-10 21:44:13,622 [startup.check_driver:72]:Running AMD Mesa driver 23.1.0 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.2.0-rc6-273-tkg-cfs) (0x73bf)
INFO     2023-02-10 21:44:13,622 [startup.check_driver:84]:GPU: 1002:73BF 1EAE:6701 (amdgpu drivers)
Gdk-Message: 21:44:18.823: Error flushing display: Broken pipe
```
```


### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.2.0-rc6-273-tkg-cfs
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.2.0-rc6-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-bd30f3619d)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.0-devel (git-bd30f3619d)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.0-devel (git-bd30f3619d)
Vulkan:          Supported

```
```


### Media (optional)

_No response_

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
We've been struggling with this one. You must be on Wayland. GTK seems to be rather fragile on Wayland, needing all callbacks to complete fairly quickly. On some systems, it's *absurdly* quickly- it seems like it's related to mouse input, where hi-resolution mice worsen the issue. It seems to be a widespread problem, and it looks like it has been happening to you.

I expect you can work around this by using X11, at least.

@strycore has put a lot of effort in lately trying to improve our responsiveness in these callbacks to mitigate this.

@Smoukus, if you are still around, could you try the latest master? Download it, and run the bin/lutris script within. See if it crashes any less for you!

Unfortunately, the real fix for this needs to come from GTK. We can try to mitigate it, but we can't guarantee we'll respond fast enough.

**Comment by Smoukus** [comment]
Yeah I was on Wayland when I made the issue. My mouse has also 1000hz polling rate.

However I stopped using Linux months ago so I can't provide any further insight into the issue :(

**Comment by danieljohnson2** [comment]
I guess we can make no further progress on this issue. Closing.
