### ISSUE TITLE
Unable to remove games from `Games` tab

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4747]
### Bug description

I was able to entirely remove a game from the `Games` tab before.
All I had to do was right click it, and then remove. After that the game would be grayed out, and I was able to right click it again, and click on uninstall / remove. That way the game disappeared entirely.

Now I am unable to do that. The first step works (right click -> remove). The game becomes grayed out, but there is no more an option to remove those "grayed out" entries:
![image](https://user-images.githubusercontent.com/48409293/218298806-5630bf71-28db-4721-8ea8-164529a7026c.png)

### How to Reproduce

1. Go to `Games` tab
2. Right click on any installed game
3. Click on `Uninstall`
4. Game will become grayed out
5.  Right click that game again
6.  An option to remove / uninstall it is missing

### Expected behavior

After right clicking on an grayed out game, there should be an option (like it was before) to remove that entry from the library entirely (especially if that wasn't a game from a runner like Steam).

### Log output

```shell
Unnecessary in this case.
❯ lutris -d
INFO     2023-02-12 08:38:03,511 [startup.init_lutris:190]:Starting Lutris 0.5.13
DEBUG    2023-02-12 08:38:03,539 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-02-12 08:38:03,559 [startup.check_driver:72]:Running AMD Mesa driver 23.1.0 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.2.0-rc6-273-tkg-cfs) (0x73bf)
INFO     2023-02-12 08:38:03,559 [startup.check_driver:84]:GPU: 1002:73BF 1EAE:6701 (amdgpu drivers)
INFO     2023-02-12 08:38:07,011 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.2.0-rc6-273-tkg-cfs
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.2.0-rc6-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-bd30f3619d)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.0-devel (git-bd30f3619d)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.0-devel (git-bd30f3619d)
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I'm seeing this too. It's because of the work to enable the menu on uninstalled games (ie, for a source). It removes the command entirely for uninstalled games. Seems like an issue.

But... I'm seeing something else. When this happens, and I close out of Lutris, then go back in- the game *is gone*. I don't understand it. Is this happening for you, or does the game remain (grayed out) when you return to Lutris?

**Comment by Smoukus** [comment]
> I'm seeing this too. It's because of the work to enable the menu on uninstalled games (ie, for a source). It removes the command entirely for uninstalled games. Seems like an issue.
> 
> But... I'm seeing something else. When this happens, and I close out of Lutris, then go back in- the game _is gone_. I don't understand it. Is this happening for you, or does the game remain (grayed out) when you return to Lutris?

I have observed the following:
This is my `Games` section at the moment:
![image](https://user-images.githubusercontent.com/48409293/218305469-0cd24ac9-ec17-47a2-b278-cfa45fdd9b22.png)

Let's focus on Dead Space 3, Dying Light 2, and Octopath Traveler. Those are the games that were obtained in an *alternative* way, and therefore won't appear in any of the `Sources` such as Steam, GOG, Epic...
Those games haven been uninstalled via `right click -> uninstall` in Lutris. That's why they became grayed out.

When I close Lutris, and reopen it again, those games are still present and grayed out in the `Games` section.

I noticed however that the grayed out games are also present in the `Windows` section:
![image](https://user-images.githubusercontent.com/48409293/218305626-3e158249-a353-406a-8e95-31821c7ea72b.png)

But regardless of the place where they are to be seen, all grayed out games (even the ones that come from Steam) are unable to be fully removed like it was possible before.

**Comment by danieljohnson2** [comment]
Okay. My disappearing games are something else. I'm working on the context menu problem.

**Comment by danieljohnson2** [comment]
OK, I got it. Not an easy one. I had to resort to debugging by terrorism.

On the other hand, the mixed up Game object handling caused other bugs also. Lutris should do a better job of giving you the right content menu in general.

**Comment by Smoukus** [comment]
Nice, great work!

**Comment by QazCetelic** [comment]
I'm still having this issue when running the latest version from master

**Comment by danieljohnson2** [comment]
Need a bit more than that, @QazCetelic. At least a bigger screenie! What sidebar-row is selected there? Are you right clicking to get that menu or using the buttons? Do you uninstall that game just before trying this, or do so earlier?

**Comment by QazCetelic** [comment]
> Need a bit more than that, @QazCetelic. At least a bigger screenie! What sidebar-row is selected there? Are you right clicking to get that menu or using the buttons? Do you uninstall that game just before trying this, or do so earlier?

1. Sidebar: `Sources` > `Epic Games Store`
2. Right-Click
3. I have never installed the game

**Comment by danieljohnson2** [comment]
Oh, you can't remove games from a store in Lutris.

You can remove them from the "Games" section because that's Lutris's own database, but the "Epic Games Store" source represents their data. You'll need to apply to EGS itself for a refund if you want to get rid of a game from there. They give refunds, right?

**Comment by QazCetelic** [comment]
Oh, is there a way for me to add all games to the “Games” section so I can sift through them there?

**Comment by danieljohnson2** [comment]
No, not really. They wind up there when you install them. So I guess you could install them all and the uninstall some?

I'm not sure what you are trying to do, though.
