### ISSUE TITLE
Epic Games Store games crashes if I switch to other window

### ISSUE THREAD

**Issue by All3xJ** [lutris/lutris#4750]
### Bug description

It happens with Lutris (both flatpak version and repo version(I'm using Fedora)) when using Epic Game Launcher, or games launched with Epic Game Launcher.  Basically it always crashes when I am playing and i do alt-tab, or I use a gesture to see the open windows. I have this bug for example with Footbal Manager 2022. But it also happened with no game launched and only with Epic Game Launcher. But what is sure is that in order to make it happen, you can just open a game (for me it was Football Manager 2022) and try to switch to another window, and it will ALWAYS crash. 

### How to Reproduce

1. Run Epic Games Store via Lutris
2. Run a Game
3. Alt-tab or do a touchpad gesture to switch window
4. Game crashes

### Expected behavior

Should not crash

### Log output

```shell
Started initial process 464 from gamemoderun /home/allexj/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/allexj/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
gamemodeauto: 
fsync: up and running.
Initial process has exited (return code: 0)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  463
  Current serial number in output stream:  463
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  131 (XInputExtension)
  Minor opcode of failed request:  28 (X_GetDeviceButtonMapping)
  Serial number of failed request:  289
  Current serial number in output stream:  289
wine: Unhandled page fault on read access to 0000000000000000 at address 0000000003FE6017 (thread 0730), starting debugger...
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0xa00003
  Serial number of failed request:  5986
  Current serial number in output stream:  5987
```

### System Information

```shell
[System]
OS:              GNOME 43 Flatpak runtime
Arch:            x86_64
Kernel:          6.1.10-200.fc37.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5825U with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             7.1 GB
Swap:            7.1 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.1.10-200.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.4 (git-a5ffb70f86)
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.4 (git-a5ffb70f86)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.4 (git-a5ffb70f86)
Vulkan:          Supported



IT ALSO happens in Lutris repo version. So it's not a problem with the flatpak version
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by al12gamer** [comment]
What Linux distro are you running? This has been an issue on Pop!_OS in the past due to their scheduler.

**Comment by legluondunet** [comment]
@All3xJ this issue is still relevant? If so, could you post this command result:
`lspci |grep VGA`
and we need a screenshot of your Lutris  Wine system options.

**Comment by strycore** [comment]
I'd love to get this fixed but as @al12gamer mentioned, this isn't our bug.
Please open an issue in your distro's bugtracker.

**Comment by All3xJ** [comment]
> What Linux distro are you running? This has been an issue on Pop!_OS in the past due to their scheduler.

Fedora

> @All3xJ this issue is still relevant? If so, could you post this command result: `lspci |grep VGA` and we need a screenshot of your Lutris Wine system options.
Yes, still a bug. Basically it crashes all the games when I switch to other window.
```

$ lspci |grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo (rev c1)
```
