### ISSUE TITLE
Installed Lutris for first time & crash when start running Fedora 37

### ISSUE THREAD

**Issue by matrix543** [lutris/lutris#4753]
/usr/bin/lutris -d

Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3.11/site-packages/lutris/api.py", line 14, in <module>
    from lutris.util import http, system
  File "/usr/lib/python3.11/site-packages/lutris/util/http.py", line 11, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'

**Comment by rventers** [comment]
Having the same issue after a clean install today. Same output.

```
~ ❯ rpm -q lutris
lutris-0.5.12-2.fc37.x86_64
```

**Comment by legluondunet** [comment]
new needed dependency to install, try installing python3-certifi package.

**Comment by matrix543** [comment]
that fix it it start now

**Comment by danieljohnson2** [comment]
I've heard from the maintainer and he says that this dependency is now fixed; so you if you need to, you could reinstall Lutris and it should then work.
