### ISSUE TITLE
[itch.io] Feature Request: Collection(s)

### ISSUE THREAD

**Issue by GoGoOtaku** [lutris/lutris#4757]
As stated in https://github.com/lutris/lutris/issues/243#issuecomment-1436054841 and in #4690 Lutris currently does not support collections. Collections are a nice way on itch.io to have a smaller library (itch.io libraries can be quite massive) that also holds free games (itch.io ties the library to purchase keys).
Also as stated in the issue you can add free games via scripts (either local or from the Lutris website) while that works most itch.io games aren't on there. I don't know much about the Lutris internal database but adding all of the itch.io games might be overkill as it's free to upload a game and there are probably magnitudes more games on itch.io than on steam or gog. I'm not checking.

The real issue here is that there is afaik no way of having settings for a source and while I'm not saying that it is impossible seemed a lot for just collections.

My "low effort" solution would be to make a second source that inherits from the main source but overrides the `load` function to pull in from specific collections (for example collections named Lutris or lutris). This would by too cryptic for a main source but for a secondary quality of life source I could see this being an alternative.

I am aware that this is slightly clunky and I would understand it if the maintainers would veto this. I make this issue partially to discuss if this is ok or if there are alternative ideas on how to do it. From proper sources settings up to just saying "no".

**Comment by mossymossmoss** [comment]
I'll leave my suggestion from the main itch.io support issue here:

Before service specific settings are added, you could check the user's itch account for a collection called "Lutris" or something, and if it doesn't exist, just default back to the purchases. It wouldn't be easy to make it clear that it's an option, perhaps some sort of popup like is currently used when the warning is given about signing into Humble could work, but to have the functionality there in would be great. This would avoid the need for a second source like discussed above
