### ISSUE TITLE
Steam shortcuts are created without the full path (in lutris flatpak)

### ISSUE THREAD

**Issue by e-minguez** [lutris/lutris#4760]
### Bug description

Currently the steam shortcut shows "flatpak" as destination but it should be the full path `/usr/bin/flatpak` instead to avoid issues

### How to Reproduce

1. Add a new game to Lutris (while Lutris is a flatpak, for example in a Steam Deck)
2. Select the "create a steam shortcut"
3. Browse the game in steam
4. See it says "flatpak" as the command to execute instead of "/usr/bin/flatpak"

### Expected behavior

To have the proper path

### Log output

```shell
Not needed.
```

### System Information

```shell
Standard steam deck but this applies globally.
```

### Media (optional)

![photo1676972020](https://user-images.githubusercontent.com/346758/220310065-d5fd942b-5b8e-4cc1-bb52-38ececbe7147.jpeg)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
What issues does giving the absolute path avoid.
What if Flatpak isn't installed in /usr/bin

Whatever... I made the change anyway. 
If it breaks, it breaks. It will be the fault of whoever installed Flatpak in a messed up way.
