### ISSUE TITLE
QoL request: Make URL links in install script wizards be clickable. 

### ISSUE THREAD

**Issue by Megalomaniak** [lutris/lutris#4763]
### Bug description

Some install scripts such as for Origin for an example ask you to read readme's and the URL is provided but not clickable, nor highlightable for copy/paste.

### How to Reproduce

1. Open Lutris
2. Click on Origin login icon to login
3. Be presented with a popup informing you that Launcher needs to be installed
4. Press OK and see the install script launch the wizard telling you to read the readme
5. try hovering over the URL

### Expected behavior

The URL should be clickable and open your default web browser to the given URL.

### Log output

```shell
Not relevant.
```

### System Information

```shell
[System]
OS:              Manjaro Linux 22.0.4 Sikaris
Arch:            x86_64
Kernel:          5.15.96-1-MANJARO
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             23.4 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.42, 5.15.96-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan:          Supported
```

### Media (optional)

![Screenshot_20230303_232655](https://user-images.githubusercontent.com/3162126/222832616-6b7762dd-e74e-4c82-81d5-649e5db3c0a2.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Goddard** [comment]
[https://imgur.com/a/GpSVGiO](url)

Clickable or at least something you can copy and paste.

**Comment by danieljohnson2** [comment]
I notice that some installers *do* have clickable links- Doom 3's do. I think the notes have to be written with the right markup for this to happen.

However, copy and paste would be nice. I've altered the code to allow you to select this text and copy it with the context menu. It doesn't look great- the text and list selections look just about the same to me- but it works.
