### ISSUE TITLE
Unable to install certain Amazon games games

### ISSUE THREAD

**Issue by ISukONiA** [lutris/lutris#4767]
### Bug description

I clicked install Pillars of Eternity and it says 

('Unable to get the patches of the game, please check your Amazon Credentials and internet connectivitiy','5be9cb70-b598-49ef-842c-d7ba3f82cf5e')

### How to Reproduce

1. Open Lutris
2. Log in Amazon Prime Games
3. Install Pillars of Eternity

### Expected behavior

It should run the basic installation e.g. Pillars of Ascension

### Log output

```shell
unable to get log from flatpak lutris
```

### System Information

```shell
[System]
OS:              GNOME 43 Flatpak runtime
Arch:            x86_64
Kernel:          6.0.14-201.fsync.fc36.x86_64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 1600 Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            23.6 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.60.11
OpenGL Core:     4.6.0 NVIDIA 525.60.11
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.60.11
Vulkan:          Supported
```

### Media (optional)

![Screenshot from 2023-03-07 17-59-30](https://user-images.githubusercontent.com/89967428/223390106-e8be8e40-3234-4fd2-bc39-b7f324cd6c97.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ISukONiA** [comment]
Ok the master branch works. Thank you dev person

**Comment by justin4242** [comment]
> We've recently merged a fix for the function that's failing here. Could you try again with the latest master (this went in _after_ the beta)
> 
> To do this, download the [master branch](https://github.com/lutris/lutris) and then run the script 'bin/lutris' found within. Try to install the offending game.
> 
> Since you are using flatpak, you might need to setup Amazon again to do this; I think the downloaded Lutris won't have access to the configuration of the flatpak installation.

Hi. I am sure I am just being dumb, but I can't get this to work. I have Lutris installed via Discover, then I downloaded the Master Branch, unzipped it (in my downloads folder), and ran the bin/lutris script but nothing happening. Am I missing a step here? Apologies for what I am sure if a dumb question. Thank you!

**Comment by danieljohnson2** [comment]
Running the script should have worked.

Try running from the terminal like this:

```
cd ~/Downloads/somewhere/lutris
./bin/lutris -d
```

But with the directory you had downloading on the first line. This will give you the debug output, and I'd like you to post that output for us here. Maybe we an figure out why it won't even start!

**Comment by Mrbunks** [comment]
Hi I am also having the same issue trying to download Star Wars republic commando and grimes. I get the error “ unable to download patches …”
I don’t fully understand how to use terminal . I entered your description..”cd ~/Downloads/somewhere/lutris
./bin/lutris -d” and nothing happened .

**Comment by danieljohnson2** [comment]
You may be able to do this with your GUI.

You should download the latest Lutris master as a .zip file, and extract it.

Inside of the resulting folder, find the 'bin' sub-folder. In there, there's a file named "lutris". You want to run it.

Double clicking it may just open it in a text editor, which is not what you want. You may be able to run with the context menu- right click and see if there's a command like "Run as a program" or something.

It may not be so easy to get the debug output this way, but maybe you can get your game working.
