### ISSUE TITLE
Incorrect game id in created Steam shortcut

### ISSUE THREAD

**Issue by nsrosenqvist** [lutris/lutris#4769]
I'm running Lutris 0.5.12 on the Steam Deck through flatpak, and often when I create a steam shortcut, its command targets "None" instead of the game's id. So I have to open properties and replace "None" with the numerical id I find when running "flatpak run net.lutris.Lutris -l".

**Comment by danieljohnson2** [comment]
That seems quite strange, but the only thing I can tell from this is that you are on 0.5.12, and I know  the shortcut generation changed for 0.5.13. Is there a flatpak of the beta you could try? It might just fail differently, but maybe that'll give us a clue.

Another thing to try is running with debug mode (-d switch) and giving us the terminal output from that.

**Comment by nsrosenqvist** [comment]
@danieljohnson2 I was thinking of trying out the beta from the flathub beta channel, can that be installed alongside stable or will that cause issues? I'm also pretty sure I can get the issue to reoccur again, so I will try and take a look tomorrow and see what the debug output says

**Comment by danieljohnson2** [comment]
That sounds much less strange; that sounds a lot like a bug I fixed for 0.5.13. If so, you can actually work around the issue by merely selecting some other game, then selecting the original again. That will cause it to reload the game data that was just installed. 0.5.13 should no longer require this.

If you were not using flatpak, I'd tell you to download the latest master without installing it, and that should leave your existing install unscathed but would still work with your installed games.

With flatpak I'm not as sure. I'd guess you can install the beta, test, and rollback afterwards, but I'm not sure this won't disrupt your existing games. I'm not that solid on flatpak.

If you are feeling brave, give it a try and let us know!

**Comment by nsrosenqvist** [comment]
@danieljohnson2 Since it should be fixed in 0.5.13, and the issue is simple to work around in 0.5.12, I think I'll rather avoid risking anything with my current installations. Thanks for your help! Should I leave the issue open so that it can be closed when 0.5.13 is released or should I close it right away?

**Comment by danieljohnson2** [comment]
I think you should close it, either now or later. If you don't want to deal with it later, close it now.

**Comment by strycore** [comment]
fixed in 0.5.13
