### ISSUE TITLE
flatpak lutris OSError

### ISSUE THREAD

**Issue by khewweifeng** [lutris/lutris#4771]
### Bug description

flatpak lutris get oserror during game installation

flatpak lutris version 0.5.12

### How to Reproduce

1. click "+" on left top corner
2. search the lutris website for installers
3. search league of legends
4. install 
5. stuck at OSError('Invalid Wine prefix path /home/acer/.wine, make sure to create the prefix before saving to a registry')"

### Expected behavior

installation without error 

### Log output

```shell
bash: lutris: command not found
```

### System Information

```shell
[System]
OS:              GNOME 43 Flatpak runtime
Arch:            x86_64
Kernel:          5.10.0-21-amd64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.6 GB
Swap:            1.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.5 (git-6570a15662)
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.5 (git-6570a15662)
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.5 (git-6570a15662)
Vulkan:          Supported
```

### Media (optional)

![Screenshot from 2023-03-12 11-05-27](https://user-images.githubusercontent.com/54496743/224523258-498c7c68-1a33-44e3-b591-2db3d2ba986c.png)
![Screenshot from 2023-03-12 11-50-18](https://user-images.githubusercontent.com/54496743/224523262-cff08452-872b-4fa4-ab53-d08ccb97b2af.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by khewweifeng** [comment]
https://github.com/flathub/net.lutris.Lutris/issues/321#issue-1620231691

**Comment by strycore** [comment]
This issue is fixed in recent versions of Flatpak. On older ones it is not possible to install League of Legends.

If you use an Arch based system, you should now be good to go. Otherwise, stick with the native version of Lutris until Flatpak is updated to 1.15 on your distro.
