### ISSUE TITLE
'Select file' option missing

### ISSUE THREAD

**Issue by peter099** [lutris/lutris#4773]
I am trying to install [Deus Ex](https://lutris.net/games/deus-ex/) using GOG scripts but when i select 'Install' it doesn't offer me to download setup file or select file, it's trying to connect to internet and download the setup file even though i am not connected to my gog account: https://imgur.com/V93JCVI.png
I have Deus Ex setup file on my hard disk and i want to install the game from it. 
I am using Lutris version 0.5.12 on MX Linux.

**Comment by danieljohnson2** [comment]
That does not seem right. You should wind up at a page in the installer window that looks like this:
![image](https://user-images.githubusercontent.com/6507403/226052843-f67bbc1e-18a1-4584-8e88-fdc019adbfa6.png)
Then you drop the "Download" dropdown down and chang eto "Select File":
![image](https://user-images.githubusercontent.com/6507403/226053096-016ed05e-dda5-4eea-b66c-02503f3024a6.png)
And that's where your installer goes.

**Comment by peter099** [comment]
Then, i guess, the problem is on my side, but i don't know what exactly is causing this.

**Comment by danieljohnson2** [comment]
Maybe you aren't getting far enough? It's hard to make out in your screenie.

Another option would be the [+] icon in the upper left corner; pick the "Install Windows game from media" option. That may get your further.

**Comment by peter099** [comment]
This is what i get: https://imgur.com/TH7M2pb

**Comment by danieljohnson2** [comment]
Yes, you're not getting as far I was showing.

Try "Install Windows game from media"

**Comment by legluondunet** [comment]
Why don't you just connect your GOG account in Lutris and let Lutris will download game?

**Comment by peter099** [comment]
I don't want to download a game every time i try to install it when i have the installer file on my disk. Some installers are with big size.

**Comment by danieljohnson2** [comment]
If your connection is working, you should get to the page I showed in my screenie, and there you can specify your already downloaded files.

Also, the 'Cache' button (a menu in the latest beta now) lets you specify a directory where Lutris downloads files; if you use this, it keeps the files there and does not download them a second time.

So, you got options. Even if you are allergic to "Install Windows game from media".

**Comment by peter099** [comment]
I want to use scripts for installing games, i can't do that if i use 'Install Windows game from media'. And i am not sure that the issue is with Lutris because i did a test on a new user profile on my system and i didn't have this problem.

**Comment by danieljohnson2** [comment]
Oh, I misunderstood. I thought you'd deliberately shut off networking to prevent Lutris from downloading files.

Is Lutris the only thing broken on your main profile? It's strange to have networking failures for Lutris only. Maybe it's the particular site that Lutris is downloading from that's at issue.

I'd suggest you run "lutris -d", try the install and let it fail, and then  give us the log output. Might be a clue in there,

**Comment by peter099** [comment]
I will just install games on my other profile and move them to my main profile. I am planing to reinstall my system soon anyway, after that if i still have this issue the problem is with Lutris, but i think it is with something on my system.

**Comment by legluondunet** [comment]
Hello, is this issue still relevant?

**Comment by peter099** [comment]
I couldn't fix it, but i found a way around this, so i guess it is not relevant anymore.
