### ISSUE TITLE
Error on Lutris and game launch - Not a lzma file

### ISSUE THREAD

**Issue by tralce** [lutris/lutris#4776]
### Bug description

Lutris errors with "not a lzma file" on launch, and on game launch. Games can't launch. Running in terminal it appears it's downloading an .xz file and then trying to use lzma to extract it. 

    2023-03-18 12:05:34,266: Downloading DXVK-NVAPI v0.6.2...
    2023-03-18 12:05:34,268: Downloading https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.2/dxvk-nvapi-v0.6.2.tar.xz to /home/tralce/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz
    2023-03-18 12:05:34,771: Extracting /home/redacted/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz to /home/redacted/.local/share/lutris/runtime/dxvk-nvapi/v0.6.2
    2023-03-18 12:05:34,772: Extraction failed: not an lzma file
    2023-03-18 12:05:34,772: Error while completing task <bound method StartupRuntimeUpdater.update_runtimes of <lutris.startup.StartupRuntimeUpdater object at 0x7fb42cf07790>>: <class 'lutris.util.extract.ExtractFailure'> not an lzma file
      File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
        result = self.function(*args, **kwargs)
      File "/usr/lib/python3.10/site-packages/lutris/startup.py", line 206, in update_runtimes
        dll_manager.upgrade()
      File "/usr/lib/python3.10/site-packages/lutris/util/wine/dll_manager.py", line 245, in upgrade
        self.download()
      File "/usr/lib/python3.10/site-packages/lutris/util/wine/dll_manager.py", line 132, in download
        extract_archive(archive_path, self.path, merge_single=True)
      File "/usr/lib/python3.10/site-packages/lutris/util/extract.py", line 139, in extract_archive
        raise ExtractFailure(str(ex)) from ex

### How to Reproduce

1. Open Lutris
2. See error
3. Try to run a game

### Expected behavior

I expected Lutris to start correctly and run a game

### Log output

```shell
Just outputs this then freezes:

(lutris:89508): Gtk-WARNING **: 12:11:24.549: Theme parsing error: gtk.css:5822:26: '-shadow' is not a valid color name

(lutris:89508): Gtk-WARNING **: 12:11:24.549: Theme parsing error: gtk.css:5825:14: not a number

(lutris:89508): Gtk-WARNING **: 12:11:24.549: Theme parsing error: gtk.css:5826:13: not a number

(lutris:89508): Gtk-WARNING **: 12:11:24.549: Theme parsing error: gtk.css:5827:11: Expected a length
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.6-zen1-1-zen
Desktop:         Not found
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.2.6-zen1-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Xuxe** [comment]
For now to get games running in Lutris -> Game -> Configure under "Runner options" you can set DXVK NVAPI version to v0.5.4. 
Looks like the asset produced at https://github.com/lutris/dxvk-nvapi/releases half an hour ago is broken. 
Having the same issue on Lutris 0.5.12 running on Ubuntu.

**Comment by antonvalletas** [comment]
Can confirm this is happening on Arch too

**Comment by tralce** [comment]
@Xuxe pointed me a little closer in the right direction -- I was able to launch a game with the latest version of dkvk-nvapi by `tar xavf`ing it in `.local/share/lutris/runtime/dxvk-nvapi/` and renaming the resulting directory to `v0.6.2`. 

It looks like `extract.py` is having some sort of trouble extracting that file that `tar xavf` is not having.

**Comment by AJ-Connor** [comment]
Using old version or extract manually works, release was done by diff person and something must be different with the artifact, i guess different software (or version) used on build

**Comment by danieljohnson2** [comment]
@GloriousEggroll, I've heard from @tannisroot on Discord- he says he used to just compress the thing with Nautilus. I'd guess that you did something else.

**Comment by danieljohnson2** [comment]
Well, the good news is decompressing and recompressing the .tar.xv in Nautilus produces something Lutris can install. The bad news is that I don't seem to have write access to the releases for dxvk-nvapi, so I can't fix this.

**Comment by danieljohnson2** [comment]
There's an [issue about this in that repo](https://github.com/lutris/dxvk-nvapi/issues/4). They've figured out that the file is actually gzip compressed; the extension is wrong.

**Comment by gamma-delta** [comment]
Huh, thought something was fishy about Lutris working last night but not today. Glad someone's on the fix :)

**Comment by danieljohnson2** [comment]
Somebody who doesn't have access grumble grumble.

**Comment by Kandelai** [comment]
There is a closed issue on this. Not sure it was ever "fixed" but there is a workaround that worked for me. Here is the old thread/issue....[here](https://github.com/lutris/lutris/issues/3386).

**Comment by danieljohnson2** [comment]
That's not the same issue, @Kandelai. Different error; the LZMA stuff is working, it's just not really a .tar.xv file.

**Comment by sim590** [comment]
I've stumbled upon this myself and I tried to set the DXVK NVAPI version to 2.5.4, but then I get this crash on Diablo 2 Resurrected:

```
3/18 14:41:38.541  [Prism/4] [<>:0]: prism: Error Invalid (0x887a0004): pm_dxgi::Instance::InitSwapChain: CreateSwapChainForHwnd Failed

3/18 14:41:38.716  [Render/4] [<>:0]: NVSDK_NGX_D3D12_Init failed, error code: -1160773631
```
Is that directly related, or?

**Comment by gamma-delta** [comment]
Going into the launcher settings, turning on the advanced tab, and manually typing `v0.6.2` into the DXVK version box is working a treat! (That version isn't in the dropdown but typing it in myself works).

Good band-aid fix for the time being ...

**Comment by gamma-delta** [comment]
Well, sort of working. I'm getting some darkening of the screen in some cases (in The Witness + randomizer on Archipelago, when there's text on the screen or I have the drawing UI open) but it's still 100% playable

**Comment by GloriousEggroll** [comment]
fied already. it was due to me uploading dxvk and dxvk-nvapi releases in the wrong format. ive corrected the release files now.

**Comment by sim590** [comment]
When I opened the directory

```
$HOME/.local/share/lutris/runtime/dxvk-nvapi/
```

I found the archive `dxvk-nvapi-v0.6.2.tar.xz` not extracted. Simply extracting it with:

```
tax -xzf dxvk-nvapi-v0.6.2.tar.xz
```

and moving the directory `dxvk-nvapi-v0.6.2` to `v0.6.2` let you go around the issue to use 0.6.2 in this case.

**Comment by GloriousEggroll** [comment]
if you just delete it and reopen lutris it should redownload the correctly formatted version and do all of that for you.

**Comment by danieljohnson2** [comment]
@GloriousEggroll has fixed the archive. Thanks, @GloriousEggroll!

In due course (after about 6 hours) Lutris should re-download and install automatically. You can trigger this to happen on your next Lutris start by deleting ~/.cache/lutris/updates.json, if you don't want to wait.

**Comment by gamma-delta** [comment]
Do you know where I can find that file when using the Flatpak install?

**Comment by gamma-delta** [comment]
Removing `/var/tmp/flatpak-cache-*` and `~/.cache/flatpak` did it, not sure which one was the one I required but hey it worked I don't care

**Comment by gamma-delta** [comment]
... Well, now my games aren't launching for other reasons, I'll poke around

**Comment by gamma-delta** [comment]
I needed to set the versions in the runners to `v0.6.2` instead of whatever the topmost was

**Comment by strycore** [comment]
> Removing `/var/tmp/flatpak-cache-*` and `~/.cache/flatpak` did it, not sure which one was the one I required but hey it worked I don't care

Neither of those folders are where the Flatpak files are located.

Flatpak data goes in ~/.var/app, then in a folder with the full name of the app (net.lutris.Lutris) in our case.
Each app then has 3 folders: cache, config and data. cache is the equivalent to ~/.cache, config to ~/.config and data to ~/.local/share.

**Comment by strycore** [comment]
> In due course (after about 6 hours) Lutris should re-download and install automatically. You can trigger this to happen on your next Lutris start by deleting ~/.cache/lutris/updates.json, if you don't want to wait.

If running the current beta release, it's also possible to launch with `lutris -f` to force updates and ignore the updates.json file.
