### ISSUE TITLE
Failed to initialize graphics device

### ISSUE THREAD

**Issue by TocNoc** [lutris/lutris#4777]
### Bug description

After [dxkv-nvapi latest update](https://github.com/lutris/dxvk-nvapi/releases/tag/v0.6.2) some devices started presenting a wine dialog box presenting a message "Failed to initialize graphics device".  Must say that the messages are different from one application to another but they all contain a similar line pointing that it could not initialize graphics device.
My desktop running a GTX 1650 doesn't have this problem but my notebook running a GTX1650 and Intel UHD does. After reinstalling/updating the notebook graphics drivers the solution was downgrade on Lutris the DXKV version to v1.10.3.

### How to Reproduce

Here I have two different examples:

League of Legends
1. Go to Lutris games tab
2. Start any League of Legends
3. On the client start a game
4. Receive a error message

The Sims 4
1.  Go to Lutris games tab
2. Start The Sims 4
3. Receive a error message

### Expected behavior

Receive wine dialog box with error message and application exits.

### Log output

```shell
a4:fixme:shell:window_prop_store_SetValue 00EA80B0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},5}, 0098E020
04a4:fixme:shell:window_prop_store_SetValue 00EA80B0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},2}, 0098E020
04a4:fixme:shell:window_prop_store_SetValue 00EA80B0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},4}, 0098E020
082c:fixme:avrt:AvRevertMmThreadCharacteristics (12345678): stub
0744:err:esync:__esync_wait_objects Polling on fd 132 returned 0x20.
00ac:fixme:heap:EnumSystemFirmwareTables (0x4649524d, 00000000, 0)
00ac:fixme:process:NtQueryInformationProcess ProcessCookie (0xffffffff,0x1074e9d0,0x00000004,(nil)) stub
00ac:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0170:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFA, 0C17FEF8
00ac:fixme:file:NtLockFile I/O completion on lock not implemented yet
018c:fixme:file:NtLockFile I/O completion on lock not implemented yet
018c:fixme:process:SetProcessShutdownParameters (00000100, 00000001): partial stub.
00ac:fixme:heap:GetNumaHighestNodeNumber semi-stub: 0387FB24
00ac:fixme:imm:ImeSetActiveContext (0xbdd0030, 1): stub
00ac:fixme:imm:ImmReleaseContext (000300F6, 0BDD0030): stub
02d4:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
02d4:fixme:wbemprox:enum_class_object_Next timeout not supported
07e8:fixme:pulse:AudioSessionControl_UnregisterAudioSessionNotification (00BE1630)->(38848AC0) - stub
02d4:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
02d4:fixme:wbemprox:client_security_SetBlanket 62EA57D0, 19803A50, 10, 0, (null), 3, 3, 00000000, 0x00000000
02d4:fixme:wbemprox:client_security_Release 62EA57D0
```

### System Information

```shell
[System]
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.15.0-67-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             7.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.6
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.6
Vulkan:          Supported
```

### Media (optional)

League of Legends
![lol](https://user-images.githubusercontent.com/42242188/226149965-17d0bc2d-ea6a-40e6-84e7-898122ac98af.jpeg)
The Sims 4
![thesism4](https://user-images.githubusercontent.com/42242188/226149967-086d0646-649d-4cd9-ac4e-e2ffd9f4bfdc.jpeg)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by seesturm** [comment]
Looks like I'm suffering from the same problem in warframe. The launcher says "Support for DirectX 10 has ended." and requests to upgrade graphics card. Downgrading from DXVK v2.1 to v1.10.3 makes the launcher work again. My graphics card is an AMD Vega 56.

**Comment by cihlarma** [comment]
I can confirm this being the case in numerous DX11 titles, not just those listed above. I can also confirm the issue does not occur on the 1.x branch of DXVK, as stated in the above comment. This doesn't seem to be an upstream issue, or at least it hasn't been reported on the [DXVK issue tracker](https://github.com/doitsujin/dxvk/issues?q=is%3Aissue) yet.

The issue affects DX10 as well as DX9 titles as long as DXVK is enabled (tested on [Two Worlds II](https://www.pcgamingwiki.com/wiki/Two_Worlds_II) both DX9 and DX10 executables, and [Painkiller Black Edition](https://www.pcgamingwiki.com/w/index.php?title=Painkiller_Black_Edition)) while DX8 titles seem to be unaffected (tested on [Devastation](https://www.pcgamingwiki.com/wiki/Devastation) and [Crazy Taxi (2002)](https://www.pcgamingwiki.com/wiki/Crazy_Taxi)).

I'm using the upstream kernel AMDGPU driver on Linux 5.10 from Debian 11 stable (not from bullseye-backports).

**Comment by TiagoRibas** [comment]
> I can confirm this being the case in numerous DX11 titles, not just those listed above. I can also confirm the issue does not occur on the 1.x branch of DXVK, as stated in the above comment. This doesn't seem to be an upstream issue, or at least it hasn't been reported on the [DXVK issue tracker](https://github.com/doitsujin/dxvk/issues?q=is%3Aissue) yet.
> 
> The issue affects DX10 as well as DX9 titles as long as DXVK is enabled (tested on [Two Worlds II](https://www.pcgamingwiki.com/wiki/Two_Worlds_II) both DX9 and DX10 executables, and [Painkiller Black Edition](https://www.pcgamingwiki.com/w/index.php?title=Painkiller_Black_Edition)) while DX8 titles seem to be unaffected (tested on [Devastation](https://www.pcgamingwiki.com/wiki/Devastation) and [Crazy Taxi (2002)](https://www.pcgamingwiki.com/wiki/Crazy_Taxi)).
> 
> I'm using the upstream kernel AMDGPU driver on Linux 5.10 from Debian 11 stable (not from bullseye-backports), the runner is Wine Lutris 7.2-2 x86-64 with DXVK 2.1.

**Comment by TiagoRibas** [comment]
Sorry I miss clicked the close buttton. But I just wanted to remember and add that this problem is occuring on diferent machines. Here I have a desktop with a nvidia card that runs all my games with DXKV 2.1 but my notebook with integrated graphics and nvidia card only runs with DXKV v1.10.30. I really dont know how to enable DXKV logs. I've tried changing DXKV_LOG_LEVEL to "debug" but nothing changed on my lutris logs. Do you guys have any info about DXKV logs?

**Comment by danieljohnson2** [comment]
I've a thought. I see that DXVK itself got an update to 2.1, not just DXVK-NVAPI. I recall the issue with DXVK 2 was that it required newer drivers than DXVK 1.x did.

Perhaps you've been upgraded to 2.1 automatically and it's not compatible with your drivers?

If this is the issue, you should be able to select an earlier <2.0 DXVK in the game configuration (it is in runner options, and is an advanced setting). Maybe that will help?

**Comment by Quinn1876** [comment]
I was running into this issue as well with League of Legends. I was able to get it to work with the following steps based on @danieljohnson2 s response:

1. right click on League of Legends in Lutris Menu > Select "Configure"
2. Go to the "Runner Options" Tab
3. Find option that says "Enable DXVK" and turn this off

Hope this helps someone

**Comment by danieljohnson2** [comment]
I've got a PR about this; perhaps one of you would consent to test it a little?

Go to [this branch here](https://github.com/lutris/lutris/tree/dj/vulkan_api_version_check) and download it; run the "bin/lutris" script therein.

This branch will check the Vulkan API you have installed, and - I hope - will pop a dialog warning you that DXVK won't like you. Not sure if the check is robust enough to really be helpful...

**Comment by TiagoRibas** [comment]
I'm gonna try to use the script and see If I get any results on both machines. Just to optimize this issue could you share your error message in your language. My system language is pt-br so  I tried to translate the error to English but I'm not sure the word "Failed" is the proper translation.

**Comment by cihlarma** [comment]
@danieljohnson2 I tried running Lutris from your branch. The GUI application launched just fine without any pop-ups and the stdout doesn't look remarkable either:
```
2023-03-25 17:20:30,978: Starting Lutris 0.5.13
2023-03-25 17:20:31,461: Running AMD Mesa driver 20.3.5 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.40.0, 5.10.0-21-amd64, LLVM 11.0.1) (0x67df)
2023-03-25 17:20:31,461: GPU: 1002:67DF 1002:0B37 (amdgpu drivers)
2023-03-25 17:20:35,013: Downloading dgvoodoo2 v2.8...
2023-03-25 17:20:35,018: Downloading https://github.com/lutris/dgvoodoo2/releases/download/v2.8/dgvoodoo2-v2.8.tar.xz to /home/user/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz
2023-03-25 17:20:35,552: Extracting /home/user/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz to /home/user/.local/share/lutris/runtime/dgvoodoo2/v2.8
2023-03-25 17:20:36,104: Startup complete
2023-03-25 17:20:51,197: Shutting down Lutris
```

**Comment by danieljohnson2** [comment]
Thanks for testing it. Looks like that wasn't enough, but your vulkaninfo is suggestive. I've added a very annoying check for the *per device* API version; if you have no device with 1.3 support, you get a warning.

Could you grab the latest version of that same branch and try it again?

**Comment by TiagoRibas** [comment]
So here I have both outputs from my machines.

1. Desktop that works with DXKV v2,1:
2023-03-25 18:04:53,097: Starting Lutris 0.5.13
2023-03-25 18:04:53,169: Using NVIDIA drivers 515.86.01 for x86_64
2023-03-25 18:04:53,169: GPU: NVIDIA GeForce GTX 1650
2023-03-25 18:04:53,169: GPU: 10DE:1F82 10DE:1F82 (nvidia drivers)
2023-03-25 18:04:56,451: Shutting down Lutris

2. Notebook that only works with DXKV v1.10.3
2023-03-25 18:03:30,509: Starting Lutris 0.5.13
2023-03-25 18:03:30,624: Using NVIDIA drivers 470.161.03 for x86_64
2023-03-25 18:03:30,624: GPU: NVIDIA GeForce GTX 1650
2023-03-25 18:03:30,625: GPU: 10DE:1F9D 1028:0A64 (nvidia drivers)
2023-03-25 18:03:30,625: GPU: 8086:9BC4 1028:0A64 (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
2023-03-25 18:03:30,666: Vulkan reports an API version of 1.2.131. 1.3.0 is required for the latest DXVK.
2023-03-25 18:03:39,593: Shutting down Lutris

**Comment by danieljohnson2** [comment]
That looks promising; it's detected your notebook's Vulkan version. Did it give you a warning dialog, or just a log message?

**Comment by TiagoRibas** [comment]
I received a warning dialog  with a check box with an option to not show again the message. Any extra logs or attempts that you want me to check?

**Comment by danieljohnson2** [comment]
Nope. Thanks @TiagoRibas. It's working for you.

I think @cihlarma has system with Vulkan 1.3 but out of date drivers; I'm hoping we can detect that too.

**Comment by cihlarma** [comment]
> Thanks for testing it. Looks like that wasn't enough, but your vulkaninfo is suggestive. I've added a very annoying check for the per device API version; if you have no device with 1.3 support, you get a warning.
> 
> Could you grab the latest version of that same branch and try it again?

@danieljohnson2 Fetching the latest changes from your branch and running Lutris from there yielded a different result.

In the GUI pop-up:
> **Obsolete vulkan libraries**
> Lutris has detected that the best device available supports Vulkan API 1.2.145, but to use the latest DXVK version, 1.3.0 is required.
>
> You may need to upgrade your drivers to a newer version.

And the stdout goes in a similar vein:
```
2023-03-25 23:46:52,120: Starting Lutris 0.5.13
2023-03-25 23:46:52,224: Running AMD Mesa driver 20.3.5 on AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.40.0, 5.10.0-21-amd64, LLVM 11.0.1) (0x67df)
2023-03-25 23:46:52,224: GPU: 1002:67DF 1002:0B37 (amdgpu drivers)
2023-03-25 23:46:52,265: Vulkan reports a best physical device API version of 1.2.145. 1.3.0 is required for the latest DXVK.
2023-03-25 23:50:47,335: Startup complete
2023-03-25 23:50:49,232: Shutting down Lutris
```
> I think @cihlarma has system with Vulkan 1.3 but out of date drivers; I'm hoping we can detect that too.

That may indeed be the case. I'm running Debian 11 with kernel version 5.10 from the stable repos and using the upstream AMDGPU driver, like I said in an earlier comment. I can try one of the newer kernels from backports and see whether anything changes.

For what it's worth, I also checked which version of `libvulkan1` I have installed, it's 1.3.224 from backports (version from stable is 1.2.162) so that shouldn't be the issue.

**Comment by danieljohnson2** [comment]
Yay, victory!

You've got an up to date Vulkan, @cihlarma, but your drivers do not support the latest stuff, so DXVK 2.x won't work for you.

@strycore had, last I heard, not decided how to deal with this problem, but @GloriousEggroll went ahead and put DXVK 2.1 out there, so we needed *something*. PR #4781 (this branch) is something, so @strycore has an option to address this, if he wants it. I'll leave it to him to make that call.

Thanks for your help!

**Comment by strycore** [comment]
Pretty cool to have this detection, but can't we just downgrade DXVK to 1.x automatically instead of showing an error message?

**Comment by danieljohnson2** [comment]
Well, it's a warning- I don't trust this sort of detection entirely. How about just changing the *default* to the most recent 1.x?

And is that the remediation we want, as opposed to getting the user to upgrade his drivers?

**Comment by strycore** [comment]
We want to be as transparent for the user as possible. It's not the role of Lutris to tell users to run up to date drivers. There are tons of distros shipping up to date drivers, using outdated ones is a choice. 
And no, we don't want to default to 1.x, that's for people who choose to run outdated drivers, their decision should not affect people who are up to date.

**Comment by danieljohnson2** [comment]
I mean, of course, defaulting to 1.x *if Vulkan support is lacking*. And only then.

It's not clear if you want to keep the warning, but loose the "update your drivers" language, or to lose the warning altogether.

**Comment by strycore** [comment]
Yeah, 1.x for older Vulkan, 2.x for the rest. 
I'd like to keep warnings to a minimum because they ruin the experience, but I guess we can display a one time warning saying we've defaulted to 1.x. Not sure if it has a lot of value though.

**Comment by danieljohnson2** [comment]
I'll do that. We can remove the warning later if you don't think it is worth it; the DXVK version selection will be separate.

**Comment by strycore** [comment]
Btw, can this be used to fix Vulkan detection? On a Nvidia 8600M, Lutris detects Vulkan as supported when it should not be.
(If you don't have old hardware like that, I can test it later, no problem)

**Comment by danieljohnson2** [comment]
I do not know how to fix it; I do not know what is wrong.

At a guess: If the NVidia 8600M does not support Vulkan at all, 'is_vulkan_supported'; might still decide the software renderer is good enough. I could fix that.

Can you give me the vulkaninfo output for this config? Should tell us if that's what it is.

**Comment by danieljohnson2** [comment]
OK, the changes are in. The warning tells you you'll get DXVK 1, and that will be the default until you override it. As soon as you can an up-to-date Vulkan system going, we'll switch to DXVK 2.

**Comment by ampp33** [comment]
[This](https://github.com/lutris/lutris/issues/4782) solution worked for me:

"either update to Lutris 0.5.13 or downgrade vkd3d-proton to 2.8 (in the game config) in order to avoid this."

**Comment by strycore** [comment]
Everyone not running Lutris 0.5.13 at the moment is running an unsupported version.
