### ISSUE TITLE
[Errno 2] No such file or directory: '/home/user/.cache/lutris/ubisoft/.token'

### ISSUE THREAD

**Issue by lravelo** [lutris/lutris#4780]
This was working yesterday but had to remove and re-add the Ubisoft Connect integration while troubleshooting some issue with Rocksmith+ and now I can no longer get the integration working again.  When I click the person icon next to Ubisoft Connect, I do get a prompt to log in and provide the MFA code but afterwards it just shows the Ubisoft Connect icon fading in and out as if it's waiting to load something but never does.  It seems to never generate that .token file. No other messages in lutris.log other than the one in the subject. I'm running Lutris 0.5.12

**Comment by barndawe** [comment]
I have the same issue

**Comment by strycore** [comment]
I believe this has been fixed a few releases ago.
