### ISSUE TITLE
impossible to login on EPIC Games Store

### ISSUE THREAD

**Issue by JulienDlq** [lutris/lutris#4783]
### Bug description

I’m not able anymore to login on EPIC Games Store.

### How to Reproduce

1. Open Lutris from a terminal
2. Click on authentication button for EPIC Games Store
3. Fill the form (login/pass) and click connect
4. See that nothings happen in Lutris interface, it keeps login/pass pop-up opened but seems frozen.

### Expected behavior

I’m logged on my EPIC Games Store account.

### Log output

```shell
INFO     2023-03-26 10:16:15,539 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-03-26 10:16:15,565 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-26 10:16:15,632 [startup.check_driver:57]:Using NVIDIA drivers 525.89.02 for x86_64
INFO     2023-03-26 10:16:15,633 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1660 Ti
INFO     2023-03-26 10:16:15,633 [startup.check_driver:77]:GPU: 10DE:2182 1043:86A5 (nvidia drivers)
DEBUG    2023-03-26 10:16:15,763 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-03-26 10:16:15,770 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-03-26 10:16:18,657 [base.login:332]:Connecting to Epic Games Store
```

### System Information

```shell
[System]
OS:              Gentoo 2.13 n/a
Arch:            x86_64
Kernel:          6.2.8-gentoo-x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical cores:  8
Logical cores:   8

[Memory]
RAM:             31.3 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.89.02
OpenGL Core:     4.6.0 NVIDIA 525.89.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.89.02
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by YousofMersal** [comment]
I'm having this exact issue as well

**Comment by beh-10257** [comment]
well same exact problem
+ this error accurs when I press the login button

`src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)`

**Comment by beh-10257** [comment]
+ basically the same exact problem for ubisoft

**Comment by xdasqurl** [comment]
Same issue here, first I've been getting the same error as @beh-10257:

> `src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)`

I've rectified this by appending "nvidia-drm.modeset=1" to the kernel parameters, only to receive a different error:

```
2023-04-08 13:47:10,948: Starting Lutris 0.5.13
2023-04-08 13:47:11,023: Using NVIDIA drivers 530.41.03 for x86_64
2023-04-08 13:47:11,023: GPU: NVIDIA GeForce RTX 2070
2023-04-08 13:47:11,024: GPU: 10DE:1F02 1458:4011 (nvidia drivers)
2023-04-08 13:47:12,220: Startup complete
2023-04-08 13:47:29,871: EGS Token expired
2023-04-08 13:47:29,872: Error while completing task <bound method BaseService.reload of <egs.EpicGamesStoreService object at 0x7f996b55f2c0 (lutris+services+egs+EpicGamesStoreService at 0x55e0d7d28da0)>>: <class 'lutris.services.base.AuthTokenExpired'> 
  File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/services/base.py", line 131, in reload
    self.load()
  File "/usr/lib/python3.10/site-packages/lutris/services/egs.py", line 311, in load
    raise AuthTokenExpired from ex
```

Looks like Epic has changed their API again and egs.py needs an update?

I'm on Manjaro 22.0.5


```
OS: Manjaro Linux x86_64 
Kernel: 6.1.22-1-MANJARO 
DE: GNOME 43.4 
WM: Mutter
```

**Comment by ghioh** [comment]
I have the same issue now that I switched to Garuda, but the Epic connect login worked fine a few days ago with Nobara.

**Comment by Toxo666** [comment]
Same here.
Epic & Ubi

**Comment by befabry** [comment]
Same problem. I can still launch the player, but I can't sync my games.

**Comment by CrazyManDF** [comment]
same problem

**Comment by befabry** [comment]
I recently tried and I believe so. I'll try later and update

**Comment by blind-coder** [comment]
Same on Debian bookworm, NVidia 3060, AMD 5800x3d.

**Comment by blind-coder** [comment]
Managed to fix mine by editing file `.cache/lutris/.egs.token` to look like this. Replace <value of COOKIENAME> with the value of that cookie when visiting the epic game store in Firefox. NO, I can't help you with how to get those.
```json
{
  "access_token": "<value of EPIC_EG1>",
  "expires_in": 28800,
  "expires_at": "<value of storeTokenExpires>",
  "token_type": "bearer",
  "refresh_token": "<value of REFRESH_EPIC_EG1>",
  "refresh_expires": 1987200,
  "refresh_expires_at": "<value of refreshTokenExpires>",
  "account_id": "<leave unchanged>",
  "client_id": "<value of EPIC_BEARER_TOKEN>",
  "internal_client": true,
  "client_service": "launcher",
  "scope": [],
  "displayName": "<your account name>",
  "app": "launcher",
  "in_app_id": "<leave unchanged>",
  "device_id": "<value of EPIC_DEVICE>"
}
```

**Comment by mrwensveen** [comment]
> Managed to fix mine by editing file `.cache/lutris/.egs.token` to look like this. Replace with the value of that cookie when visiting the epic game store in Firefox. NO, I can't help you with how to get those.
> 
> ```json
> {
>   "access_token": "<value of EPIC_EG1>",
>   "expires_in": 28800,
>   "expires_at": "<value of storeTokenExpires>",
>   "token_type": "bearer",
>   "refresh_token": "<value of REFRESH_EPIC_EG1>",
>   "refresh_expires": 1987200,
>   "refresh_expires_at": "<value of refreshTokenExpires>",
>   "account_id": "<leave unchanged>",
>   "client_id": "<value of EPIC_BEARER_TOKEN>",
>   "internal_client": true,
>   "client_service": "launcher",
>   "scope": [],
>   "displayName": "<your account name>",
>   "app": "launcher",
>   "in_app_id": "<leave unchanged>",
>   "device_id": "<value of EPIC_DEVICE>"
> }
> ```

Thanks!

I didn't have this file so I thought I'd create it myself.

`EPIC_BEARER_TOKEN` and `EPIC_DEVICE` are available as cookies when you log in to your Epic account on the website (I used devtools find them). `account_id` is the ID as shown on your profile page, as is `displayName`, I think?

I don't know what `in_app_id` should be. I don't have a previous value so I'm unsure what it's supposed to be .

The access and refresh tokens are normally some kind of OAuth JWT tokens, but I'm unable to find them. EPIC_SESSION_AP and EPIC_SESSION_REPUTATION look like okay candidates?

Any help would be appreciated.

**Comment by strycore** [comment]
I tried to reproduce this issue on so many systems... and no matter what, I have no problem with the login popups...

Maybe I need to test with the nvidia driver... the VMs I've been testing on were using the virtio driver.

I've tried so far:

- Arch Linux Gnome
- Debian 11 XFCE
- Garuda Gamer KDE

For those who experience this issue, do you get the same behavior in both the Flatpak and native versions of Lutris?

**Comment by Dalgam** [comment]
I can reproduce the issue on Fedora 38 with Gnome 44.1 on X11 using Nvidia proprietary drivers. The issue happens in both the flatpak and the rpm version.

**Comment by blind-coder** [comment]
Reproduced on Debian 11 Bookworm with Gnome 43 and nvidia 525. Lutris 0.5.12 I think from deb?

**Comment by s6fty** [comment]
same issue on arch linux 6.3.4 with cinnamon and nvidia 530.41

**Comment by mrwensveen** [comment]
So yeah, this is definitely a problem with the proprietary nvidia drivers. I disabled the drivers to test with the non-proprietary nouveau drivers and was able to log in and sync my game library!

I'm not sure if the bug is caused by the browser running inside the login window, or the window itself, or how the specific driver is affecting this.

**Comment by strycore** [comment]
We've narrowed the issue down to webkit2gtk and the nvidia driver version 525 and 530.

I found a very similar issue on Nyxt: https://github.com/atlas-engineer/nyxt/issues/2969

I had no luck getting the nvidia driver to work on qemu with Fedora 38 and Garuda KDE but I had an install of Manjaro on a SSD so I booted on that. 

While I don't reproduce the bug exactly, the spinner keeps spinning and the window doesn't redraw when resized. I get this error in the terminal: 

`** (WebKitWebProcess:27141): ERROR **: 21:57:56.972: WebProcess didn't exit as expected after the UI process connection was closed`

**Comment by strycore** [comment]
Here's a repro script for this issue. 

```
import os
import gi

if os.environ.get("GTK") == "4":
    gi.require_version('Gdk', '4.0')
    gi.require_version('Gtk', '4.0')
    gi.require_version("WebKit2", "5.0")
    GTK_VER = 4
else:
    gi.require_version('Gdk', '3.0')
    gi.require_version('Gtk', '3.0')
    gi.require_version("WebKit2", "4.1")
    GTK_VER = 3

from gi.repository import Gdk, GLib, GObject, Gtk, WebKit2

class WebConnectDialog(Gtk.ApplicationWindow):
    def __init__(self, application=None):
        super().__init__(application=application)
        self.context = WebKit2.WebContext.new()
        self.set_default_size(500, 850)
        self.webview = WebKit2.WebView.new_with_context(self.context)
        self.webview.load_uri("https://www.epicgames.com/id/login?redirectUrl="
                 "https%3A//www.epicgames.com/id/api/redirect%3F"
                 "clientId%3D34a02cf8f4414e29b15921876da36f9a%26responseType%3Dcode")
        webkit_settings = self.webview.get_settings()
        webkit_settings.set_user_agent(
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'EpicGamesLauncher/11.0.1-14907503+++Portal+Release-Live '
            'UnrealEngine/4.23.0-14907503+++Portal+Release-Live '
            'Chrome/84.0.4147.38 Safari/537.36'
        )
        if GTK_VER == 3:
            self.add(self.webview)
            self.show_all()
        else:
            self.set_child(self.webview)


def on_activate(app):
    dlg = WebConnectDialog(application=app)
    dlg.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(None)
```

I added the option to use GTK 4 (launch with `GTK=4 python wekbit-test.py`) and the issue isn't present.

Since Debian 12 is releasing soon, we might consider migrating to Gtk 4 soon (for 0.6.0) but still, I'd like to have a workaround for the current release that doesn't involve switching to nouveau, logging to EGS and switching back to nvidia.

**Comment by strycore** [comment]
An improvement on the last repro script, I managed to add the webkit inspector. This didn't work in Lutris but it does in this simplified setup. 

When running with the inspector, we can see the page is crashing in the talon_sdk script saying WebGL context is lost.

It's unfortunate that Epic Games uses an analytics using WebGL for their login process. I guess that exposes a lot more info on the user's machine. 

![image](https://github.com/lutris/lutris/assets/280336/5f1ca318-29a7-4db5-acfe-451119fe5058)

Here's the updated script:

```
import os
import gi

if os.environ.get("GTK") == "4":
    gi.require_version('Gdk', '4.0')
    gi.require_version('Gtk', '4.0')
    gi.require_version("WebKit", "6.0")
    GTK_VER = 4
else:
    gi.require_version('Gdk', '3.0')
    gi.require_version('Gtk', '3.0')
    gi.require_version("WebKit2", "4.1")
    
    GTK_VER = 3

from gi.repository import Gdk, GLib, GObject, Gtk, WebKit2

class WebConnectDialog(Gtk.ApplicationWindow):
    def __init__(self, application=None):
        super().__init__(application=application)
        self.context = WebKit2.WebContext.new()
        self.set_default_size(500, 850)
        self.webview = WebKit2.WebView.new_with_context(self.context)
        self.webview.load_uri("https://www.epicgames.com/id/login?redirectUrl="
                 "https%3A//www.epicgames.com/id/api/redirect%3F"
                 "clientId%3D34a02cf8f4414e29b15921876da36f9a%26responseType%3Dcode")
        webkit_settings = self.webview.get_settings()
        webkit_settings.set_allow_modal_dialogs(True)
        webkit_settings.set_user_agent(
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'EpicGamesLauncher/11.0.1-14907503+++Portal+Release-Live '
            'UnrealEngine/4.23.0-14907503+++Portal+Release-Live '
            'Chrome/84.0.4147.38 Safari/537.36'
        )
        webkit_settings.set_enable_write_console_messages_to_stdout(True)
        webkit_settings.set_javascript_can_open_windows_automatically(True)
        webkit_settings.set_enable_developer_extras(True)
        inspector = self.webview.get_inspector()
        inspector.show()
        if GTK_VER == 3:
            self.add(self.webview)
            self.show_all()
        else:
            self.set_child(self.webview)


def on_activate(app):
    dlg = WebConnectDialog(application=app)
    dlg.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(None)
```

**Comment by strycore** [comment]
So it's a login page, it doesn't need WebGL. 

Is there a way to disable WebGL? Turns out there is! 
Does disabling it solve the issue? Turns out it does!

I committed the fix, please test to ensure this works in all setups.

**Comment by JulienDlq** [comment]
> So it's a login page, it doesn't need WebGL.
> 
> Is there a way to disable WebGL? Turns out there is! Does disabling it solve the issue? Turns out it does!
> 
> I committed the fix, please test to ensure this works in all setups.

Just tested right now on my system, allying the patch and… it works!
Thank you very much. :+1:

**Comment by PatientAllison** [comment]
Just tested and it works! Thanks so much @strycore!

**Comment by gardotd426** [comment]
Wow. Fantastic, thanks @strycore.

Does anyone else have any weird issue with libadwaita and other newer GTK apps causing the monitor on which they open to like, darken and get all weird colored until you move the window around or close it? I've seen this in fastgame, bottles, and in the EGS login window in Lutris. I'll screen record it later.

**Comment by numfin** [comment]
can anyone publish update on flathub?

**Comment by strycore** [comment]
Lutris 0.5.14 should be out soon-ish

**Comment by knorrre** [comment]
> Lutris 0.5.14 should be out soon-ish

Is there an approximate launch date?

**Comment by strycore** [comment]
When it's done.

**Comment by MisterSheeple** [comment]
Is there a workaround that can be used in the current release version?

**Comment by strycore** [comment]
You can manually edit the source file and add the line from https://github.com/lutris/lutris/commit/dc67a15f97baeebb96c6b96c71c107747ca89053 
Since it's Python and no building is required, that's all you need to do.

**Comment by FlitPix** [comment]
The above worked for me on Debian 12.

**Comment by yochananmarqos** [comment]
> You can manually edit the source file and add the line from https://github.com/lutris/lutris/commit/dc67a15f97baeebb96c6b96c71c107747ca89053

@strycore That no longer works with `webkit2gtk-4.1` 2.42.1-1 on Arch / Arch-based distros.

My Epic Store login expired and I'm not able to login again because it only loads a blank dialog:

```
2023-09-28 14:47:51,187: Starting Lutris 0.5.13
2023-09-28 14:47:51,188: Using NVIDIA drivers 535.113.01 for x86_64
2023-09-28 14:47:51,188: GPU: NVIDIA GeForce RTX 3060 Laptop GPU
2023-09-28 14:47:51,188: GPU: 8086:46A6 1558:867C (i915 drivers)
2023-09-28 14:47:51,188: GPU: 10DE:2520 1558:867C (nvidia drivers)
2023-09-28 14:47:55,302: EGS Token expired
2023-09-28 14:47:55,302: Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f7ccf52f100>: <class 'lutris.services.base.AuthTokenExpired'> 
  File "/usr/lib/python3.11/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/services/base.py", line 141, in do_reload
    self.load()
  File "/usr/lib/python3.11/site-packages/lutris/services/egs.py", line 310, in load
    raise AuthTokenExpired from ex
```

**Comment by b-lechalupe** [comment]
Thank you! I was stuck on this for hours. Hope they'll fix the lib soon.
