### ISSUE TITLE
Cloned games share the same image settings with the game they're cloned from

### ISSUE THREAD

**Issue by monyxie** [lutris/lutris#4786]
### Bug description

Basically, changing the icon/cover/banner of a cloned (duplicated) game also causes the original game's icon/cover/banner to change.

### How to Reproduce

Steps to reproduce the behavior (I'll omit cover art and banner art here for brevity):
1. Right-click any game and choose 'Duplicate', then click 'Yes' in the popup dialog.
2. Right-click on the cloned new game and choose 'Configure'.
3. Change the game's icon by clicking on it and choose an image, then click 'Save'.
4. Right-click on the original game and choose 'Configure', you should be able to see that its icon is also change to the same image you just choosed in step 3.

### Expected behavior

Changing the configuration of one game should not affect the configuration of another game.

### Log output

```shell
INFO     2023-03-26 23:40:32,678 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-03-26 23:40:32,741 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-26 23:40:33,030 [startup.check_driver:57]:Using NVIDIA drivers 470.161.03 for x86_64
INFO     2023-03-26 23:40:33,030 [startup.check_driver:61]:GPU: Unknown
INFO     2023-03-26 23:40:33,030 [startup.check_driver:77]:GPU: 10DE:0FFC 17AA:21F5 (nvidia drivers)
INFO     2023-03-26 23:40:33,031 [startup.check_driver:77]:GPU: 8086:0166 17AA:21F5 (i915 drivers)
DEBUG    2023-03-26 23:40:33,426 [lutriswindow.update_store:448]:Showing 7 games
INFO     2023-03-26 23:40:33,439 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-03-26 23:40:45,972 [game.save:299]:Saving joe 2 (linux) with config ID pcsx2-1679845245
DEBUG    2023-03-26 23:40:46,108 [lutriswindow.update_store:448]:Showing 8 games
DEBUG    2023-03-26 23:41:02,891 [system.execute:57]:Executing / u s r / s b i n / l s p c i
DEBUG    2023-03-26 23:41:02,911 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-03-26 23:41:03,166 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-03-26 23:41:03,429 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-03-26 23:41:03,792 [application.show_window:328]:Showing window EditGameConfigDialog14

(lutris:5705): GdkPixbuf-WARNING **: 23:41:09.923: Unrecognized parameter “quality” passed to the PNG saver
DEBUG    2023-03-26 23:41:13,745 [game.save:299]:Saving joe 2 (linux) with config ID pcsx2-1679845245
DEBUG    2023-03-26 23:41:13,745 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=pcsx2-1679845245, runner=linux) config to /home/monyxie/.config/lutris/games/pcsx2-1679845245.yml
DEBUG    2023-03-26 23:41:13,903 [application.on_app_window_destroyed:346]:Removed window EditGameConfigDialog14
DEBUG    2023-03-26 23:41:18,272 [application.show_window:328]:Showing window EditGameConfigDialog13
DEBUG    2023-03-26 23:41:20,733 [application.on_app_window_destroyed:346]:Removed window EditGameConfigDialog13
```

### System Information

```shell
I don't think this is relevant but in case it is:

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.8-arch1-1
Desktop:         MATE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             15.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  4.2 (Compatibility Profile) Mesa 23.0.0
OpenGL Core:     4.2 (Core Profile) Mesa 23.0.0
OpenGL ES:       OpenGL ES 3.0 Mesa 23.0.0
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I feel your pain. By which I mean my pain. I don't think we can address this for the next release. It's a design limitation.

So, Lutris installs custom media by writing them into ~/.cache/lutris. It overwrites the downloaded media if required; after that it's just the same thing- Lutris does not even remember that it didn't download the file.

It's simple, but it it's not really *right*. If you clean out ~/.cache you lose your custom media. And as you have seen, duplicate games share their media.

You can work around this by giving the duplicates different identifiers; then they will have different media files.

**Comment by strycore** [comment]
This is fixed in the current code. Duplicating a game will now display a pop-up asking for a new name from which the identifier gets generated. Images for the new ID will then be downloaded when the game is duplicated.
