### ISSUE TITLE
Can't use Origin anymore. You must upgrade to EA App

### ISSUE THREAD

**Issue by Niklas20114552** [lutris/lutris#4789]
### Bug description

I'm trying to install an Origin Game with Lutris, but when i click Install, Origin will be opened and it will just show an "Install EA-App" Screen and doesn't install the Game

### How to Reproduce

1. Log in into Origin
2. Try to install an Origin Game
3. See the issue

### Expected behavior

Bypass the "Install EA-App" Window or use the EA-App instead of Origin

### Log output

```shell
I think you don't need the Output for this specific Issue.
If you need it, please comment.
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.8-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2400G with Radeon Vega Graphics
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             14.6 GB
Swap:            7.7 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Vega 11 Graphics (raven, LLVM 15.0.7, DRM 3.49, 6.2.8-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.1
Vulkan:          Supported
```

### Media (optional)

![Screenshot_20230328_184903](https://user-images.githubusercontent.com/83753407/228311754-75171c76-4983-45f4-af27-a054e1b5734c.png)
Yes i know it's German

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by jeremie-dautheribes** [comment]
See https://github.com/lutris/lutris/issues/4576#issuecomment-1464886521 for some help.

**Comment by RickStanley** [comment]
@jeremie-dautheribes, in step 8, specifically:

>  exe: /media/YOUR_USERNAME/Games/Origin/drive_c/Program Files (x86)/Origin/Origin.exe

I don't understand the "media" part. I went to: https://lutris.net/games/origin/, installed from the "latest" script, after finishing it, it already showed me the message that Origin.exe wasn't found.

After following the steps, I receive an error saying that "/media/my_user/Games/Origin/drive_c/Program Files (x86)/Origin/Origin.exe" was not found. Am I supposed to mount or move something?

**Comment by al12gamer** [comment]
EA moment

**Comment by strycore** [comment]
The EA App service is now operational

**Comment by Gwindalmir** [comment]
Will the Origin source still remain?
I'm still using Origin, as I found a way to keep it working, using https://github.com/p0358/Fuck_off_EA_App

Lutris also has an auth issue when you try to connect your account. The EA login auth page changed. I ended up doing the login in Firefox through the new EA page, and was still able to get an access token using the API request in origin.py:
https://github.com/lutris/lutris/blob/67e169ba7ed979bf0657b5383a697f35e7eab00c/lutris/services/origin.py#L193-L207

So I saved the token, and exported the cookies from Firefox, then placed them where Lutris was expecting.
After that I was able to load the Origin source, enumerate the Games, and even install and run one.

![Screenshot_20230930_225544](https://github.com/lutris/lutris/assets/1127170/b37b0dc1-9de0-414d-b450-9951db38bc2b)

**Comment by danieljohnson2** [comment]
I doubt the Origin service can last long; EA is clearly dumping it, and a patch to disable the nags won't change that.

If Origin does not work properly anymore, maybe we should remove it for 0.5.14 rather than trying to fix it, since I read the EA app support will be there.

**Comment by strycore** [comment]
For 0.5.14, I might leave the Origin integration code in the project to let people migrate their games to EA App.

Right now, you may still be able to log in and use Origin using workarounds but that's not going to be the case for most people.
Once we remove the integration, you'll still be able to use Origin as a Wine game, as long as the workarounds work.
We still have the "Steam for Windows" integration in Lutris despite it being really useless. So maybe we'll keep the Origin one for a while.
