### ISSUE TITLE
"The platform '%s' is unknown to Lutris."

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4798]
### Bug description

When you import a rom, and it's known to Lutris it comes back with the following: The platform 'NEC - PC Engine - TurboGrafx 16' is unknown to Lutris.

### How to Reproduce

Try to add a rom using the add game 

### Expected behavior

to work

### Log output

```shell
Traceback (most recent call last):
  File "`/src/lutris/lutris/gui/dialogs/game_import.py", line 197, in import_rom
    self.display_new_game_info(filename, rom_set, rom["md5"])
  File "~/src/lutris/lutris/gui/dialogs/game_import.py", line 246, in display_new_game_info
    raise RuntimeError(_("The platform '%s' is unknown to Lutris.") % category)
RuntimeError: The platform 'NEC - PC Engine - TurboGrafx 16' is unknown to Lutris.
```

### System Information

```shell
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.15.0-69-generic
Desktop:         KDE
Display Server:  x11
```

### Media (optional)

![Screenshot_20230404_205033](https://user-images.githubusercontent.com/19357986/229927696-98132d77-0a01-4aa7-b3dc-4ef75fde8ff8.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Lutris has a table of platforms it knows and what runners to use for them, that sort of thing. PC Engine is not on it, nor is the TurboGrafx 16.

Lutris need to know this stuff to set up the game for you.
