### ISSUE TITLE
[Libretro] GBA not working

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#480]
I tried to add a gba game, added, set vba-m as the core, tried to run it, and nothing :( just a white screen, tried the VBA Next core and a black screen. Hacked the runner and added both the mednafen gba and mGBA cores, and both also failed.

Tried from the terminal, and it works (retroarch -L /usr/lib/libretro/vba_next_libretro.so "/Games/Romz/Nintendo/gba/Sonic Advance 2 (Europe) (En,Ja,Fr,De,Es,It).zip") 

both the N64 and SNES cores work without problem, just the GBA that won't work :(

**Comment by strycore** [comment]
The only game I've played and completed on Lutris / Retroarch is Metroid Fusion :p

I'll have to check again, and I need to upload new builds for Retroarch so it will likely come with new cores.

**Comment by strycore** [comment]
With the current build of VBA-M, Sonic Advance 2 works
