### ISSUE TITLE
League of Legends not work after patch 13.7 was released

### ISSUE THREAD

**Issue by 2anwe** [lutris/lutris#4801]
### Bug description

Hi,
I play League of Legends for a long time, and it worked just fine. But after Riot Games released patch 13.7 I can't get into the game and critical error message pops up. I still can access riot client and league client.

I run Lutris from fedora repo.

### How to Reproduce

1. Install League of Legends
2. Enter the game
3. Observe critical error message pop up

### Expected behavior

To work

### Log output

```shell
0364:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (01BDD004 1 ) semi-stub
0364:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (01BDD004 1 C) semi-stub
047c:fixme:win:FlashWindowEx 0098DF98 - semi-stub
047c:fixme:win:GetPointerDevices (0098D6C4 00000000): partial stub
047c:fixme:system:DisplayConfigGetDeviceInfo Unimplemented packet type: 11
047c:fixme:msctf:SetInputScopes STUB: 000100EC ... (null) (null)
05ec:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
05ec:fixme:heap:EnumSystemFirmwareTables (0x4649524d, 0000000000000000, 0)
05ec:err:seh:dispatch_exception unknown exception (code=c0000420) raised
05ec:fixme:process:NtQueryInformationProcess ProcessCookie (0xffffffffffffffff,0x180b02650,0x00000004,(nil)) stub
05ec:fixme:thread:NtSetInformationThread info class 2 not supported yet
05ec:fixme:imm:ImeSetActiveContext (0x3003d0, 1): stub
05ec:fixme:imm:ImmReleaseContext (000000000001013A, 00000000003003D0): stub
0364:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (01BDCFD0 1 C) semi-stub
0364:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (01BDCFD0 1 C) semi-stub
```

### System Information

```shell
[System]
OS:              Fedora Linux 37 KDE Plasma
Arch:            x86_64
Kernel:          6.2.9-200.fc37.x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             7.6 GB
Swap:            7.6 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan:          Supported
```

### Media (optional)

https://user-images.githubusercontent.com/113391988/230366840-b1bb2dd6-b9f3-459a-be87-6ea565163dbf.mp4

[lutris --submit-issue.zip](https://github.com/lutris/lutris/files/11170193/lutris.--submit-issue.zip)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by cleconte987** [comment]
Same here.
Im on Ubuntu 22.04.1 LTS

**Comment by BeroBurny** [comment]
source https://www.reddit.com/r/leagueoflinux/comments/12cei7t/patch_137_feedback_megathread_transition_to_64bit/
> With the launch of patch 13.7, the LoL/TFT client has deprecated support for 32-bit clients and now exclusively supports 64-bit environments.

**Comment by filippossemere** [comment]
Same here: [https://forums.lutris.net/t/league-of-legends-no-longer-runs/17591/7](https://forums.lutris.net/t/league-of-legends-no-longer-runs/17591/7)

**Comment by fiXedTM** [comment]
Linux users just have to wait for someone to issue someone to Lutris a patch on the matter

**Comment by ginos1998** [comment]
any solution?

**Comment by johnmichadasis** [comment]
Same issue here.
I'm using Mint 20.3

**Comment by serdaraltin** [comment]
I have that same problem. We're always patching things up, it's boring.

**Comment by antonstech** [comment]
Same issues here on Pop OS

**Comment by czar** [comment]
Can use new runner at https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL

**Comment by strycore** [comment]
The "lutris-ge-lol-7.0-8-x86_64" build does resolve the crash. :+1: 

https://www.youtube.com/watch?v=AOAE9Tskl6Y

**Comment by nervemployee** [comment]
> The "lutris-ge-lol-7.0-8-x86_64" build does resolve the crash. 👍
> 
> https://www.youtube.com/watch?v=AOAE9Tskl6Y



> Can use new runner at https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.0-GE-8-LoL

Doesn't work for me
