### ISSUE TITLE
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4806]
### Bug description

With the latest git Lutris crash as soon as you start

### How to Reproduce

update to https://github.com/lutris/lutris/commit/3ee9ebe05bfb2d3948ad07702d6f671048350dfd and start lutris

### Expected behavior

it works

### Log output

```shell
Traceback (most recent call last):
  File "./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "~/src/lutris/lutris/gui/application.py", line 38, in <module>
    from lutris.command import exec_command
  File "~/src/lutris/lutris/command.py", line 13, in <module>
    from lutris import runtime, settings
  File "~/src/lutris/lutris/runtime.py", line 12, in <module>
    from lutris.util.linux import LINUX_SYSTEM
  File "~/src/lutris/lutris/util/linux.py", line 12, in <module>
    from lutris.util.graphics import drivers, glxinfo, vkquery
  File "~/src/lutris/lutris/util/graphics/vkquery.py", line 8, in <module>
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)
```

### System Information

```shell
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.15.0-69-generic
Desktop:         KDE
Display Server:  x11
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Nertz! I assumed that @cache predated the fancier @lru_cache, but nope- Python 3.9 introduced @cache, 3.2 for @lru_cache. I've switched to @lru_cache and that should work on any supported Python.

I wish I could figure out how to run 3.7 for testing.

Thanks for being a just that little bit obsolete, @telanus!
