### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4810]
### Bug description

Not running currently on kubuntu 20.04

### How to Reproduce

123

### Expected behavior

it boots

### Log output

```shell
Traceback (most recent call last):
  File "~/src/lutris/lutris/gui/application.py", line 436, in do_command_line
    run_all_checks()
  File "~/src/lutris/lutris/startup.py", line 220, in run_all_checks
    check_vulkan()
  File "~/src/lutris/lutris/startup.py", line 168, in check_vulkan
    max_dev_name, max_dev_api_version = vkquery.get_best_device_info()
TypeError: cannot unpack non-iterable NoneType object
```

### System Information

```shell
Kubuntu 20.04
Non-Vulcan GPU
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
It's the Non-Vulkan GPU that gets you; you've got libvulkan but no Vulkan devices and that's what triggers the bug.

I've revised the checks here so it won't crash in that case.
