### ISSUE TITLE
Unable to launch Civ 4 Complete

### ISSUE THREAD

**Issue by imprimatur13** [lutris/lutris#4812]
Hi. Installed Civ 4 Complete from a retail dvd i own using lutris (with the retail dvd script here https://lutris.net/games/sid-meiers-civilization-iv-the-complete-edition/ ), on a fresh install of lutris, on manjaro, with all the dependencies that the lutris wiki told me to install (specifically the ones listed here https://github.com/lutris/docs/blob/master/WineDependencies.md ). I click the play button for Sid Meier's Civilization IV: The Complete Edition within Lutris, it says it's launching, then it stops, all without anything apparently happening. It registered that I played for less than a minute.

What should I do?
![image](https://user-images.githubusercontent.com/130937747/232346135-f35108c7-f444-4eeb-8995-9db8a3589026.png)

**Comment by legluondunet** [comment]
Hello, we do not provide scirpt installer support on Github, it is only for Lutris issues.
I invite you to post your script issue on forum or our discord server:
https://forums.lutris.net
https://discord.com/invite/Pnt5CuY

**Comment by imprimatur13** [comment]
Posted the issue on #lutris_support in the discord server with a lutris -d output, thank you.


     On Monday, April 17, 2023, 08:39:39 AM EDT, legluondunet ***@***.***> wrote:  
 
 


ps: tested with lutris-GE-Proton 7.33, can not reproduce issue.
