### ISSUE TITLE
Lutris disappears and then reappears from Task Manager after every closure (KDE Plasma)

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4817]
### Bug description

Every time after I close Lutris (latest git as of now), it will disappear from Task Manager (KDE Plasma) and reappear again after a bit.

Here is the video of the issue (happens only with Lutris):

https://user-images.githubusercontent.com/48409293/233173397-a40d201e-8511-4700-b0be-aab4fe776c3e.mp4

It's interesting that this doesn't happen if I run Lutris via terminal:

https://user-images.githubusercontent.com/48409293/233173742-3a56d185-0f77-48f2-836b-a80f9f1ccc07.mp4

I am fairly sure that this isn't KDE's fault because only Lutris has this behaviour.

### How to Reproduce

1. Add Lutris to Task Manager in KDE Plasma
2. Start Lutris
3. Close Lutris

### Expected behavior

Lutris closes, but the Task Manager icon doesn't disappear.

### Log output

```shell
(lutris:64286): Gtk-WARNING **: 20:58:30.494: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:64286): Gtk-WARNING **: 20:58:30.494: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
INFO     2023-04-19 20:58:30,526 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-04-19 20:58:30,526 [startup.check_driver:72]:Running AMD Mesa driver 23.2.0 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.0-rc6-273-tkg-cfs) (0x73bf)
INFO     2023-04-19 20:58:30,527 [startup.check_driver:84]:GPU: 1002:73BF 1EAE:6701 (amdgpu drivers)
DEBUG    2023-04-19 20:58:30,596 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR

(lutris:64286): Gtk-WARNING **: 20:58:30.678: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:64286): Gtk-WARNING **: 20:58:30.678: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
INFO     2023-04-19 20:58:31,806 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.3.0-rc6-273-tkg-cfs
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.0-rc6-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.0-devel (git-efc629389a)
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.0-devel (git-efc629389a)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.0-devel (git-efc629389a)
Vulkan Version:  1.3.246
Vulkan Drivers:  AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That is strange indeed. It may matter exactly how you *added* Lutris to your taskbar/dock/whatever it is called this week.

The fact that the terminal behaves differently makes me think that icon is something funny, and isn't just running lutris like you do from the terminal.

**Comment by Smoukus** [comment]
> It may matter exactly how you _added_ Lutris to your taskbar/dock/whatever

Well I added it the same way I added all other icons onto the taskbar:

https://user-images.githubusercontent.com/48409293/233401194-c6947de3-3947-4402-9e7d-7c2e17b9558a.mp4

**Comment by danieljohnson2** [comment]
Hmm. Let's try adding it a different way. Remove the icon from the taskbar, then start Lutris from the terminal.

Now, I bet you can right click the Lutris icon that appears in the taskbar because Lutris is running, and you'll have an option there to keep it, pin it to the taskbar, something of that kind.

If you can do that, close Lutris and re-open it. Does *that* rigmarole produce a icon that works better?

My theory here is that if you do that, you'll get an icon that does what the terminal did, and that will work better.

**Comment by Smoukus** [comment]
Just tried it and it behaves actually the same as in issue above :(
So no difference sadly.

**Comment by danieljohnson2** [comment]
I'm afraid my theorizing isn't working out too well, and I'm not too intimate with KDE; I think we need someone who knows that desktop environment better than I.

**Comment by strycore** [comment]
Pretty sure this was the runtime updater popup opening, then closing then the Lutris UI showing up.
We removed the runtime updater popup, so this is fixed.
