### ISSUE TITLE
[Amazon] login window freezes

### ISSUE THREAD

**Issue by Vittelius** [lutris/lutris#4819]
I can't login to my amazon prime gaming account. The login window opens but before I can enter any text the page freezes. The text cursor blinks once inside the email address field then it stops. I can't enter anything or click any of the links. If I resize the window it turns blank

Edit: I'm running arch (via endeavor OS) btw

**Comment by legluondunet** [comment]
@danieljohnson2 that was the same issue I had on Arcolinux (Arch)

**Comment by danieljohnson2** [comment]
I see that that may user name has become a curse word.

I feel proud of that. I think I earned it.

**Comment by rakklak** [comment]
I am also facing this issue, fresh install of EOS, Amazon Games sign in hangs.

**Comment by Melon-Bread** [comment]
Same issue sometimes it shows the login boxes but even then you can not enter anything. On Arch and the issues is there via the Arch package & Flatpak version. 

Is there a manual way of entering the token?

**Comment by strycore** [comment]
Duplicate of #4783
