### ISSUE TITLE
[scummvm] scaler options

### ISSUE THREAD

**Issue by dsok0l** [lutris/lutris#4821]
### Bug description

It appears that we are sending wrong parameters to scummvm binary,  
eg. for **advmame3x** the parameter sent is:
`--gfx-mode=advmame3x`  
instead of  
`--scaler=advmame --scale-factor=3`.  
  
Excerpt from scummvm help:
```
--scaler=MODE            Select graphics scaler (normal,hq,edge,advmame,sai,
                           supersai,supereagle,pm,dotmatrix,tv2x)
--scale-factor=FACTOR    Factor to scale the graphics by
```

### How to Reproduce

1. Go to 'Runner options'
2. Click on 'Graphic scaler'
3. Select 'advmame3x'
4. Run game

### Expected behavior

Scummvm should apply correct scaler options, instead of default 320x200 resolution.

### Log output

```shell
WARNING: Unrecognized graphics mode 'advmame3x'. Switching to default mode!
```

### System Information

```shell
[System]
OS:              Manjaro Linux 22.1.0 Talos
Arch:            x86_64
Kernel:          6.2.10-1-MANJARO
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 4600H with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.0 GB
Swap:            16.6 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.49, 6.2.10-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.2
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
It looks like ScummVM has got a copy of the DOSBOX settings, and it doesn't work the same way. I think these settings need a rewrite.

**Comment by danieljohnson2** [comment]
I've gone over the ScummVM graphical options. They appear quite unfinished, but I think I see why. Certain option combinations work, and others do not work. I think the author was trying to cope with this and gave up.

My solution is to introduce warnings into the ScummVM configuration options when I think the options you've picked do not work. It looks like this:
![image](https://user-images.githubusercontent.com/6507403/233779590-c552892c-6183-457e-9b85-e962a1ccd18d.png)

In addition, I've changed the options to use localized names when I could, and added 'Renderer' and 'Stretch Mode' options. The "Auto" settings for things mean that we do *not* send any option to ScummVM- which I  believe may produce a game specific default, for some games.

I have no idea what localized test to use for something like "sai", so I just left that.
