### ISSUE TITLE
Weird behaviour with network connectivity

### ISSUE THREAD

**Issue by pkreuzt** [lutris/lutris#4824]
This is something that **may** be related to some other issues here: I'm having a bunch of errors installing games from GOG (return code 13568, as seen on other bug reports here). I found that the easiest way to solve this is simply turning off network and installing from cache. Once the installer is running, turning network on doesn't affect the result.

Apart from this, it seems Lutris always remembers latest wine version launched even after changing default setting. When a specific installed wine version doesn´t work with an installer, the only way to change it is uninstalling that version and switch network off, or Lutris will try to download the same wine version again to run installer.

I'm not sure all this is related only to Lutris program itself. It may be caused by something in website.

**Comment by danieljohnson2** [comment]
This sounds like issue #4370. If so, we've got a fix for the next release.

Could you try [the beta](https://github.com/lutris/lutris/releases/tag/v0.5.13-beta2) that is out?

You need not install it, just download and extract the source and run the bin/lutris script within.

The beta should respect your choice of default WINE version, rather than installing with the latest always.

**Comment by pkreuzt** [comment]
No need to try Beta, it seems to have been solved without local changes ¿!? I had no relevant upgrades on my distro, the only thing I can think of is a new Wine package <have become available since the errors (GE-Proton-8.2), but I hadn't installed it before installers began working again (and installers didn't ask for it either).

The reason I mentioned website is I though it may be storing some setting on site account somehow affecting local preferences. Whatever, if this problem returns I will try Beta to see if it makes a difference.
