### ISSUE TITLE
ScummVM fails at launch when openldap is at version higher then 2.4.2

### ISSUE THREAD

**Issue by gapys-krzysztof** [lutris/lutris#4832]
### Bug description

ScummVM doesn't launch using Lutris, but it does when it's installed through Arch repositories. Seems to be asking for some older version of openldap, while a newer one is available. Don't see an option to make it use the newer one instead

### How to Reproduce

1. Install a scummvm game through lutris (here used was the Feeble Files https://www.gog.com/game/the_feeble_files)
2. Try to launch, notice issue

### Expected behavior

ScummVM should launch

### Log output

```shell
Started initial process 15643 from /home/me/.local/share/lutris/runners/scummvm/bin/scummvm --extrapath=/home/me/.local/share/lutris/runners/scummvm/share/scummvm --themepath=/home/me/.local/share/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --gfx-mode=3x --path=/home/me/Games/the-feeble-files feeble
Start monitoring process.
/home/me/.local/share/lutris/runners/scummvm/bin/scummvm: /usr/lib/libldap_r-2.4.so.2: version `OPENLDAP_2.4_2' not found (required by /home/me/.local/share/lutris/runners/scummvm/lib/libcurl-gnutls.so.4)
/home/me/.local/share/lutris/runners/scummvm/bin/scummvm: /usr/lib/liblber-2.4.so.2: version `OPENLDAP_2.4_2' not found (required by /home/me/.local/share/lutris/runners/scummvm/lib/libcurl-gnutls.so.4)
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

### System Information

```shell
Actual openldap version on the system "openldap 2.6.4-2"

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.12-arch1-1
Desktop:         Not found
Display Server:  x11
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by legluondunet** [comment]
Hello, could you try this:
- extract files from this archive:
[libs.zip](https://github.com/lutris/lutris/files/11357333/libs.zip)
- move them in this directory:
~/.local/share/lutris/runners/scummvm/lib/
Does ScummVM launch?
If not, please post a new log.

**Comment by gapys-krzysztof** [comment]
With libraries extracted, Lutris's ScummVM launches correctly

**Comment by legluondunet** [comment]
I just updated ScummVM runner libraries folder.
Could you now uninstall and reinstall ScummVM runner, does it still launches correctly?

**Comment by gapys-krzysztof** [comment]
It seems the issue is solved now
