### ISSUE TITLE
Failing app start can lead to concat of str and float

### ISSUE THREAD

**Issue by darix** [lutris/lutris#4838]
### Bug description

the code can run into the situation where the app crashes ( in my case due to a dxvk error) that it tries to concat  a string and float

### How to Reproduce

1. setup battle.net on a machine with an Arc 770
2. start battle.net and watch it fail
3. error popup

### Expected behavior

no error

### Log output

```shell
2023-04-30 12:51:25,147: Stopping Blizzard Battle.net (wine)
2023-04-30 12:51:25,147: The game has run for a very short time, did it crash?
2023-04-30 12:51:25,168: Blizzard Battle.net (wine) has encountered an error: can only concatenate str (not "float") to str
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lutris/exceptions.py", line 80, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 694, in beat
    self.on_game_quit()
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 731, in on_game_quit
    self.stop()
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 712, in stop
    self.stop_game()
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 675, in stop_game
    self.playtime += self.timer.duration / 3600
TypeError: can only concatenate str (not "float") to str
```
```


### System Information

```shell
[System]
OS:              openSUSE Tumbleweed 20230428 n/a
Arch:            x86_64
Kernel:          6.2.12-1-default
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             30.5 GB
Swap:            32.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Arc(tm) A770 Graphics (DG2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.2
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This looks very like issue #4289, fixed in the 0.5.13 beta that's out.

Could you try that? No need to install it- download the source and run the 'bin/lutris' script within.

**Comment by darix** [comment]
i locally applied the one line fix and it fixes the issue. though i got to say that it is a kinda weird fix to (ab)use the float cast there instead of checking the playtime data.

**Comment by darix** [comment]
Submitted the fix also to the openSUSE Tumbleweed distro

**Comment by danieljohnson2** [comment]
I hope they know the fix is from the upcoming Lutris revision; it's not a patch they'll be keeping for all that long.

**Comment by darix** [comment]
it is mentioned in the changelog entry for the package change :D
