### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by SamuDifferent** [lutris/lutris#4843]
### Bug description

Every time i try to run any Wine-Game i get the same error, and Lutris freezes in "Launching". Already tried Different installing methods, different Settings, and bugfixes, but every bugfix i found is old and none of them work anymore. 

### How to Reproduce

1. Start Lutris 
2. Click on any Wine Game
3. Get crashing Notification
4. See Lutris freezing in Launching

### Expected behavior

I used lutris on an older Ubuntu version for years without any problems, but since i upgraded to Ubuntu 22.04 it doesn't work anymore 

### Log output

```shell
lutris -d
2023-05-06 00:04:42,452: Starting Lutris 0.5.9.1
2023-05-06 00:04:42,475: No cores found
2023-05-06 00:04:44,755: Startup complete
INFO     2023-05-06 00:04:44,756 [startup.check_driver:61]:Running AMD Mesa driver 22.2.5 on AMD Radeon RX 5600 XT (navi10, LLVM 15.0.6, DRM 3.47, 5.19.0-41-generic) (0x731f)
INFO     2023-05-06 00:04:44,757 [startup.check_driver:73]:GPU: 1002:731F 1043:05A5 (amdgpu drivers)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 840, in play
    wine_ver = is_version_esync(self.get_executable())
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 293, in is_version_esync
    wine_version = get_wine_version(path).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### System Information

```shell
[System]
OS:              Ubuntu 22.04 Jammy Jellyfish
Arch:            x86_64
Kernel:          5.19.0-41-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600XT 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5600 XT (navi10, LLVM 15.0.6, DRM 3.47, 5.19.0-41-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.5
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.5
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That's a old version of Lutris you have there. Your bug looks like #3764, fixed in 0.5.10. Try a more recent Lutris!

**Comment by SamuDifferent** [comment]
The last one I tried before opening this error is on an older version, but I experience the same error on the newest stable version as well as several others. I just tried some old versions as well, because people could get it  back running this way.

**Comment by SamuDifferent** [comment]
I managed to get it running, the problem was, that I installed the .deb file with the UI which resorted in Ubuntu always installing the version 5.9.1 regardless of the version I downloaded from GitHub. Works Perfectly fine via `sudo apt install ./lutris_0.5.12_all.deb`
