### ISSUE TITLE
NVAPI Hack force-enabled when using the Origin service

### ISSUE THREAD

**Issue by gardotd426** [lutris/lutris#4846]
### Bug description

So, obviously before the move to the newish "Services" model, every game was individually configured, and while you can still configure games on an individual basis, you can't configure the services, those seem to be configured in a hard-coded manner in the python files in `/usr/lib/python3.10/site-packages/lutris`. That has led to a problem: DXVK-NVAPI is not universally enabled, and it doesn't seem to be hardcoded into the origin.py service (obviously we're all going to be talking about the EA App, but it's still called Origin in the services and in the code). 

What's confusing is that `wine.py` DOES seem to **disable** `DXVK_NVAPIHACK` by setting it to `0`, but no matter what I do, "Origin" and every EA Game I have forcibly enable it even though DXVK-NVAPI is **enabled** in every game's individual configuration options. The reason I know it's enabled:

```
 info:  NVIDIA GeForce RTX 3090:
info:    Driver : NVIDIA 525.47.22
info:    Memory Heap[0]:
info:      Size: 24576 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:    Memory Heap[1]:
info:      Size: 24011 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
```

This happens on ALL Origin games. I've **not** been able to reproduce this behavior in Ubisoft Connect, Epic Games Store, or GoG. And the problem is, this causes DLSS to not work in any EA game that is owned through EA (as opposed to Steam). Dead Space (Remake) is the obvious example for me. 

This is a bug, but I also believe the easiest fix would be to just add a configuration menu for the services in the exact same way that the runners are able to be configured. 

I've tried on multiple driver versions, but obviously that's not the problem anyway because DLSS works perfectly in EGS games (Control), GoG games (Ghostrunner, Cyberpunk 2077, Control Ultimate Edition), almost all of my Steam games, basically anything that supports it EXCEPT **anything** I run through the Origin service in Lutris. 

### How to Reproduce

While using an RTX Nvidia GPU,
1. Open Lutris from a terminal with `lutris -d`
2. Right-click on your EA App games to ensure that DLSS is enabled and `DXVK_NVAPIHACK` is set to 0 in Configure > System Options > Environment Variables
3. Click on the "Origin" service in the left pane
4. Launch any game from the service, or click the play button for the service itself
5. See the `info:  DXGI: NvAPI workaround enabled, reporting AMD GPU` message in the terminal output (or in `Show  Logs`)

### Expected behavior

That message definitely shouldn't show up. Launch a non-Origin Windows game with DXVK-NVAPI enabled and see it not show up/see that DLSS will be enabled.

### Log output

This is an obscene amount of output. I'm happy to post it if it's needed, but we already know where the issue is (the log message showing that the nvapihack is enabled and it's reporting an AMD GPU).

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.0-273-tkg-cfs
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            39.6 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.47.22
OpenGL Core:     4.6.0 NVIDIA 525.47.22
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.47.22
Vulkan Version:  1.3.243
Vulkan Drivers:  NVIDIA GeForce RTX 3090 (1.3.248)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [x] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hmmm. Looking at the code of the origin service, it does not seem to do anything immediately relevant.

But the way it seems to work, when you run an Origin game, you are really running Origin with an argument that tells it what game to play. This would put Origin in control; it might be getting the environment variables and altering them for  the game, just like Lutris does itself. This would explain why only Origin is affected.

Maybe there's a setting inside Origin that would help?

**Comment by strycore** [comment]
> So, obviously before the move to the newish "Services" model, every game was individually configured, and while you can still configure games on an individual basis, you can't configure the services, 

This isn't true. If you connect to any service and get your game library in the Lutris UI, you will be able to configure games on an individual basis.

**Comment by strycore** [comment]
> obviously we're all going to be talking about the EA App, but it's still called Origin in the services and in the code

this isn't true either. The Origin integration will not work with EA App. We currently have no integration with EA app.

**Comment by gardotd426** [comment]
@strycore this comment is mostly just in response to the EA App vs Origin stuff, not really about the bug, so you can just skip to the last paragraph or so of this comment and then the next comment if you don't feel like reading it.

>This isn't true. If you connect to any service and get your game library in the Lutris UI, you will be able to configure games on an individual basis.

That's what I said:

>you can *still configure games on an individual basis*

The problem is that you can't configure the Origin service, which has a Play button next to it. Which brings me to the next problem:

>this isn't true either. The Origin integration will not work with EA App. We currently have no integration with EA app.

It literally launches `EADesktop.exe`. And no, I don't mean it does it when I launch one of my Origin installed games (cause I could just edit the game configuration for that to happen). No, what I mean is that when I click the play button next to the Origin *service*, it launches EADesktop.exe. You can even see it when I run lutris from the terminal. I just now went to click Play on the Origin service and recorded it:

https://github.com/lutris/lutris/assets/54234607/34ab1585-7c1e-4116-b652-782b9e19c70e

This is with no modification to the `origin.py` service file or `wine.py` runner file. 

I'm looking right now and I think I've found why it launches EADesktop, but it still makes no sense. 

If I go into the overall "Games" list on the left panel (at the very top), I have an old entry for Origin ***as an individual game***. This entry does **not** show up as an "Origin Service" game, so I have NO idea why the origin service uses THAT as the choice, but I've confirmed it by adding weird meaningless envvars to that individual prefix. 

After removing all of my Origin entries, now I am forced to install Origin somewhere in order to connect to it, but when I click Play it STILL force-enables the NvAPIHack, as per the logs. 

But I'm not sure if any of this has any relevance to the actual bug, because this only appears in Origin games and it doesn't appear in Cyberpunk 2077 (GoG), Control Ultimate Edition (GoG), Control (standard edition) (EGS), or any other non-Steam, non-Origin game that I have that has DLSS capability. DLSS works in all those, it only doesn't work in Origin games, namely Dead Space (remake). And the only discrepancy I've noticed is that the non-Origin games do **not** show the NvAPIHack log line, and **all** Origin games do.  


Anyway my next comment will be more directly about the bug with logs and stuff.

**Comment by gardotd426** [comment]
Yes, I can right-click on Dead Space or Jedi Survivor or any other game in my library that uses Origin and enable DLSS in Runner options, add `DXVK_ENABLE_NVAPI=1` to my environment variables in System options, and I still get `info:  DXGI: NvAPI workaround enabled, reporting AMD GPU` in the log output.

Actually, because none of the "Origin vs EADesktop.exe" stuff even matters, I went ahead and just used `lutris -b` to create a script in order to launch the game that way, that way I could be 100% sure that there's nothing I'm not aware of that's corrupting my results, because I'm not confident enough that I'm not screwing some shit up. 

So, I just launched Dead Space with a script created *by* lutris with `lutris -b DeadSpace.sh 196` with `196` being the game code for Dead Space according to `lutris -lo`. Here's the script's contents:

```
#!/bin/bash


# Environment variables
export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
export MANGOHUD="1"
export MANGOHUD_DLSYM="1"
export __GL_SHADER_DISK_CACHE="1"
export __GL_SHADER_DISK_CACHE_PATH="/home/matt/nvme/EA/Dead Space (2023)"
export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
export LD_LIBRARY_PATH="/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/lib:/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/lib64:/usr/lib:/usr/lib32:/opt/cuda/lib64:/opt/wxgtk-3.1.5/lib:/usr/lib/swift/lib/swift/linux:/opt/intel/oneapi/compiler/latest/linux/lib/x64:/opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64:/usr/lib/opencollada:/opt/cuda/extras/CUPTI/lib64:/opt/cuda/nvvm/lib64:/usr/lib/vmware-tools/lib64/libvmGuestLibJava.so:/usr/lib/vmware-tools/lib64/libvmGuestLib.so:/usr/lib/libfakeroot:/usr/lib32/libfakeroot:/usr/lib/libfakeroot/fakechroot:/usr/lib/vmware-tools/lib64/libDeployPkg.so:/usr/lib64:/home/matt/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/matt/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/matt/.local/share/lutris/runtime/steam/i386/lib:/home/matt/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/matt/.local/share/lutris/runtime/steam/i386/usr/lib:/home/matt/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/matt/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/matt/.local/share/lutris/runtime/steam/amd64/lib:/home/matt/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/matt/.local/share/lutris/runtime/steam/amd64/usr/lib:/home/matt/.local/share/vulkan-sdk/x86_64/lib"
export DXVK_CONFIG_FILE="/home/matt/Documents/dxvk.conf"
export DXVK_STATE_CACHE="1"
export LD_PRELOAD=""
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP="1"
export DXVK_ENABLE_NVAPI="1"
export PROTON_ENABLE_NVAPI="1"
export PROTON_HIDE_NVIDIA_GPU="0"
export VKD3D_CONFIG="dxr11"
export WINEARCH="win64"
export WINE="/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/bin/wine"
export WINE_MONO_CACHE_DIR="/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/mono"
export WINE_GECKO_CACHE_DIR="/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/gecko"
export GST_PLUGIN_SYSTEM_PATH_1_0="/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/lib64/gstreamer-1.0/:/home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/lib/gstreamer-1.0/"
export WINEPREFIX="/home/matt/nvme/EA/deadspace"
export WINEESYNC="0"
export WINEFSYNC="1"
export WINE_FULLSCREEN_FSR="1"
export DXVK_NVAPIHACK="0"
export PROTON_BATTLEYE_RUNTIME="/home/matt/.local/share/lutris/runtime/battleye_runtime"
export PROTON_EAC_RUNTIME="/home/matt/.local/share/lutris/runtime/eac_runtime"
export WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
export STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/matt/.local/share/Steam/"
export STEAM_COMPAT_DATA_PATH="/home/matt/nvme/EA/deadspace"
export STEAM_COMPAT_APP_ID="0"
export SteamAppId="0"
export SteamGameId="lutris-game"

# Working Directory
cd '/home/matt/nvme/EA/Dead Space (2023)'

# Command
gamemoderun mangohud /home/matt/.local/share/lutris/runners/wine/lutris-GE-Proton8-4-x86_64/bin/wine '/home/matt/nvme/EA/Dead Space (2023)/Dead Space.exe'
```

And when EA App launches (because EA App automatically launches to confirm you own the game when you just use the game's executable, but all it does is instantly launch the game once it's launched), I get this in the terminal:

```
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
```

@danieljohnson2 
But the way it seems to work, when you run an Origin game, you are really running Origin with an argument that tells it what game to play. This would put Origin in control; it might be getting the environment variables and altering them for the game, just like Lutris does itself. This would explain why only Origin is affected.

Origin isn't the problem, the problem is that DXVK's NVAPIHack is being *force-enabled* in **all** of my Origin games, while it's not being enabled in *any* of my GoG/EGS/Ubisoft Connect games. I also grepped (and did more manual searches) the relevant .py files but I couldn't find anything that even seemed relevant either, that's why I'm so confused. 

In every Origin game, I get this in the log output:

`info:  DXGI: NvAPI workaround enabled, reporting AMD GPU`

Which makes no sense, because they all have `DXVK_ENABLE_NVAPI=1`, DLSS enabled in the Runner options, `DXVK_CONFIG_FILE=~/Documents/dxvk.conf` with `dxgi.nvapiHack = False` and a custom device id and vendor id (and it's the same dxvk.conf file I use with all my other games, which all have working DLSS and do *not* have the `NvAPI workaround enabled` line in the logs

That's why I'm so baffled, because there's no reason whatsoever for this to be happening, unless either of you can point out something from that shell script that I had Lutris create for Dead Space that I've been too stupid to notice lol

**Comment by gardotd426** [comment]
Okay, so I feel like this command output kind of illustrates my point. I just ran the script that Lutris created for me, and I ran it like `./deadspace.sh 2>&1 | tee log.txt`. 

Then after the game launched and I exited it, I ran `grep -i nvapi log.txt`, and the output is rather confusing:

```
info:    dxgi.nvapiHack = False
info:    dxgi.nvapiHack = False
info:    dxgi.nvapiHack = False
info:    dxgi.nvapiHack = False
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
```

lol why is it saying `dxgi.nvapiHack = False` 4 times and never saying true, and yet somehow it's being force enabled anyway? I'm so confused

**Comment by strycore** [comment]
Some of the confusion (at least for me) comes from using EA App with the Origin integration, you seem to have used the Origin prefix to install EA App, which mean the Origin integration would continue working, but I'm really not sure to what extent.

Anyway, I tried Battlefield V on EA App and I couldn't get DLSS or RTX to work properly. (RTX resulted in a crash). The DXR option was present when I passed the correct environment variable.

If there any game available on EA Play (non Pro) with RTX, I can give them a try.

**Comment by gardotd426** [comment]
@strycore so, I just spent all morning with jens on an dxvk-nvapi issues thread trying to figure this mess out, I got DLSS working in Dead Space, but even WITH me figuring it out, the stupid log is still reporting: 


`info:  DXGI: NvAPI workaround enabled, reporting AMD GPU`

I have no idea why, but since I did end up getting DLSS to work, I suppose it doesn't really matter (though I am still going to try and bisect it, EA App is the ONLY app that reports `info:  DXGI: NvAPI workaround enabled, reporting AMD GPU`, so something weird is happening, even if DLSS does work once the game itself launches). 

As for RTX, I've not had any problems getting RT to work in games, though I haven't tried BFV in a very, very long time, and I do remember that the last time I did try, it was a total mess. 

That said, I looked at the EA Play non-Pro lineup, and it looks like BFV is the only RT game in the lineup, but if you want to do some testing, you can message me on discord and I can give you my login stuff if you want it, I have EA Play Pro.

**Comment by gardotd426** [comment]
In the meantime, I'll see what happens in BFV with RT/DLSS, I think my BFV pfx got yeeted somehow a while back so I'll redownload it, my internet is pretty fast.

**Comment by strycore** [comment]
I don't know if that relevant but I get those messages as well:

```
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
libEGL warning: failed to get driver name for fd 0

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd 0

libEGL warning: failed to get driver name for fd 0

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd 0
```

And then there's the fact that I can't install or launch EA App when my Nvidia GPU is dedicated to VFIO. I can only run it when the nvidia module is re-enabled or when I'm using the Nvidia GPU exclusively (when the Ryzen iGPU is assigned to VFIO)

**Comment by gardotd426** [comment]
That's super weird. I used to run VFIO, but it was single-GPU, so I never had both running at the same time. 

Anyway, you're right as far as BFV is concerned, it seems. Every single time the initial loading screen comes up it crashes about 3 seconds later as soon as DXR is enabled. Without it, it runs fine. 

Unfortunately, IIRC since BFV is one of the first DLSS/RT games, the DLSS functionality is tied to RT functionality. What I mean is, you CAN enable DLSS without enabling RT, but the game has to think you have an RTX GPU, if RT isn't available, it will block out DLSS. 

I'm going to try to switch back to DXVK and then try enabling *just* DLSS.

**Comment by gardotd426** [comment]
@strycore so I can't believe I forgot about this, but back in 2021 I filed a bug report with Jens at dxvk-nvapi over Battlefield V, and turns out Battlefield V never got updated to DLSS 2.X because EA abandoned it, and DXVK-NVAPI can only support DLSS 2.X and 3.X (just not frame gen). So just now I tried swapping out the _nvngxdlss.dll file or whatever it's called to upgrade DLSS, and that caused DXVK-NVAPI to load properly (I had it create a log file to confirm it, before with DLSS 1.X it wasn't loading properly), but it still crashes because as the game settings say, you HAVE to have "an RTX GPU and DXR" enabled for some stupid reason. Dice is so stupid. 

Here's the link to the bug thread if you want more info: https://github.com/jp7677/dxvk-nvapi/issues/45

Let me know if you wanna use my EA Play Pro acct to test with Dead Space (RT and DLSS) or Jedi Survivor (no DLSS but it has RT) or something.

I did find one other game on the base EA Play list that has DLSS 2.X, but idk if it'll work. It's Crysis Remastered. I know that Crysis Remastered is like, DX11 but with DLSS and using some weird nonsense for the RT stuff, but it has DLSS 2.1 and it's on the EA Play subscription if you wanna give it a shot. 

A really good way to see if it's working is to set `DXVK_NVAPI_LOG_LEVEL=info` and `DXVK_NVAPI_LOG_PATH=/somewhere/you/want` so you can check `dxvk-nvapi.log` to make sure DXVK-NVAPI is loading correctly.

A success will look like this (using Dead Space as an example):

```
---------- 2023-05-27 11:14:09 ----------
NvAPI_QueryInterface (0xad298d3f): Unknown function ID
DXVK-NVAPI v0.6.3-4-g2483eac (Dead Space.exe)
Successfully acquired Vulkan vkGetInstanceProcAddr @ 0x2d4ad3fa0
NvAPI Device: NVIDIA GeForce RTX 3090 (530.41.3)
NvAPI Output: \\.\DISPLAY1
NvAPI Output: \\.\DISPLAY2
NvAPI_Initialize: OK
NvAPI_QueryInterface (0x33c7358c): Unknown function ID
NvAPI_QueryInterface (0x593e8644): Unknown function ID
NvAPI_EnumPhysicalGPUs: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_GPU_GetArchInfo: OK
NvAPI_Initialize: OK
NvAPI_GetInterfaceVersionString: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_EnumLogicalGPUs: OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_QueryInterface (0x6ef4d2d1): Unknown function ID
NvAPI_QueryInterface (0xd44d3c4e): Unknown function ID
NvAPI_GetErrorMessage (-3/NVAPI_NO_IMPLEMENTATION): OK
NvAPI_GetErrorMessage (-3/NVAPI_NO_IMPLEMENTATION): OK
NvAPI_Initialize: OK
NvAPI_DRS_CreateSession: OK
NvAPI_DRS_LoadSettings: OK
NvAPI_DRS_GetBaseProfile: OK
NvAPI_DRS_GetSetting (0x10afb76b/Unknown): Setting not found
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetAdapterIdFromPhysicalGpu: OK
NvAPI_DRS_GetSetting (0x10e41df2/Unknown): Setting not found
NvAPI_QueryInterface (0xf2400ab): Unknown function ID
NvAPI_EnumPhysicalGPUs: OK
NvAPI_DRS_GetSetting (0x10e41df2/Unknown): Setting not found
NvAPI_GPU_GetArchInfo: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_DRS_GetSetting (0x10afb764/Unknown): Setting not found
NvAPI_DRS_CreateSession: OK
NvAPI_QueryInterface (0xa782ea46): Unknown function ID
NvAPI_DRS_FindApplicationByName (D:\EA\Dead Space (2023)\Dead Space.exe): Executable not found
NvAPI_DRS_DestroySession: OK
NvAPI_Initialize: OK
NvAPI_DRS_CreateSession: OK
NvAPI_DRS_LoadSettings: OK
NvAPI_DRS_GetBaseProfile: OK
NvAPI_DRS_GetSetting (0x10afb76b/Unknown): Setting not found
NvAPI_D3D12_IsFatbinPTXSupported: OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetAdapterIdFromPhysicalGpu: OK
NvAPI_GPU_GetArchInfo: OK
NvAPI_D3D12_GetGraphicsCapabilities (sm_86): OK
NvAPI_DRS_GetSetting (0x10afb76a/Unknown): Setting not found
NvAPI_DRS_GetSetting (0x10afb76c/Unknown): Setting not found
NvAPI_D3D12_CreateCubinComputeShaderWithName: OK
NvAPI_Initialize: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_D3D_GetSleepStatus: No implementation
NvAPI_GetErrorMessage (-3/NVAPI_NO_IMPLEMENTATION): OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetPCIIdentifiers: OK
NvAPI_D3D_Sleep: No implementation
NvAPI_DISP_GetGDIPrimaryDisplayId: OK
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_GPU_GetDynamicPstatesInfoEx: No implementation
NvAPI_DISP_GetGDIPrimaryDisplayId: OK
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_D3D12_CaptureUAVInfo: OK
NvAPI_D3D12_GetCudaTextureObject: OK
NvAPI_D3D12_LaunchCubinShader: OK
NvAPI_D3D12_SetDepthBoundsTestValues: OK
```

A fail will (usually) look like this: 

```
---------- 2023-05-27 10:46:08 ----------
NvAPI_QueryInterface (0xad298d3f): Unknown function ID
DXVK-NVAPI v0.6.3-4-g2483eac (Dead Space.exe)
Successfully acquired Vulkan vkGetInstanceProcAddr @ 0x2d4ad3fa0
NvAPI_Initialize: NVIDIA or other suitable device not found or initialization failed
```

**Comment by strycore** [comment]
I'll try with Crysis Remastered first. Is Crysis 3 Remastered also using the same DX11 based DXR setup?

**Comment by gardotd426** [comment]
>I'll try with Crysis Remastered first. Is Crysis 3 Remastered also using the same DX11 based DXR setup?

It seems like it, yeah

**Comment by strycore** [comment]
With the latest VKD3D, ray tracing works in Battlefield V without any special setting passed from Lutris.
