### ISSUE TITLE
wrong library path on linux natives

### ISSUE THREAD

**Issue by Le-Barbu** [lutris/lutris#485]
using a native linux entry, LD_LIBRARY_PATH has to be manually set to '/lib'
otherwise, running gnome-mahjongg trows this :
/bin/gnome-mahjongg: /home/barbu/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libatk-bridge-2.0.so.0)

**Comment by strycore** [comment]
Running Gnome games with the Lutris runtime enabled is very likely to cause issues. You can disable the runtime in game config (when right clicking on the game). 

Can you confirm this works with the runtime disabled?

**Comment by Le-Barbu** [comment]
Yes, it does work this way too!
It also messed up some wine games, Battle.net refused to log me in, with runtime disabled, it works just fine.

**Comment by strycore** [comment]
libdbus is now removed from the runtime
