### ISSUE TITLE
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#4853]
### Bug description

Starting Lutris this morning after updating to 2e8c96573b2afd5e79293d1920261af90ff27140 found this on the terminal

### How to Reproduce

.
                  

.

### Expected behavior

not throw an error

### Log output

```shell
DEBUG    2023-05-12 05:59:43,331 [http._request:88]:GET https://lutris.net/api/runtimes/icons
Traceback (most recent call last):
  File "~/src/lutris/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
```

### System Information

```shell
out of date linux :P

[System]
OS:              Ubuntu 20.04 focal
Arch:            x86_64
Kernel:          5.15.0-71-generic
Desktop:         KDE
Display Server:  x11
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That is very odd; that code seem unrelated to commit 2e8c96573b2afd5e79293d1920261af90ff27140.

Also that code hasn't changed much for a year, and the most recent change seems harmless.

Does anything bad happen when you get this error? Seems to me that this fault may just disable the 'dark mode' preferences setting in the Preferences dialog.

I could put a prophylactic 'except' in here,  but it would not restore that functionality so it may be pointless.

Might help if we could get just a bit more of the debug log, perhaps.

**Comment by strycore** [comment]
> I could put a prophylactic 'except' in here

Please don't. Not everything that is reported by users is true.

**Comment by danieljohnson2** [comment]
I'm sure I can trust @telanus, if he ever comes back to this item. But I won't put in that 'except'; I've got no confidence it would help in any way.

I await the rest of the debug log. I'd also like to know if this issue has any real consequences, other than a reduction in grimdark dark grimness. I'm generally in favor of that anyway.

**Comment by telanus** [comment]
> I await the rest of the debug log.

`./bin/lutris -d
INFO     2023-05-21 21:17:37,524 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-21 21:17:38,277 [startup.check_driver:65]:Using NVIDIA drivers 390.157 for x86_64
INFO     2023-05-21 21:17:38,277 [startup.check_driver:69]:GPU: GeForce GT 630
INFO     2023-05-21 21:17:38,277 [startup.check_driver:85]:GPU: 10DE:0F00 10DE:098F (nvidia drivers)
WARNING  2023-05-21 21:17:38,330 [startup.check_vulkan:149]:Vulkan reports an API version of 1.2.131. 1.3.0 is required for the latest DXVK.
WARNING  2023-05-21 21:17:38,392 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-21 21:17:38,393 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-21 21:17:38,393 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-21 21:17:38,394 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-05-21 21:17:38,394 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
DEBUG    2023-05-21 21:17:41,463 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-21 21:17:42,715 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-05-21 21:18:41,885 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
Traceback (most recent call last):
  File "~/src/lutris/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)
DEBUG    2023-05-21 21:18:42,363 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-05-21 21:18:42,868 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-05-21 21:18:43,747 [http.write_to_file:142]:Writing to ~/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-05-21 21:18:43,789 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-05-21 21:18:44,492 [http.write_to_file:142]:Writing to ~/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-05-21 21:18:44,525 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-05-21 21:18:45,205 [http.write_to_file:142]:Writing to ~/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-05-21 21:18:45,207 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-05-21 21:18:45,793 [http.write_to_file:142]:Writing to ~/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-05-21 21:18:45,829 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-05-21 21:18:46,498 [http.write_to_file:142]:Writing to ~/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
DEBUG    2023-05-21 21:18:46,835 [http._request:88]:POST https://lutris.net/api/games
ERROR    2023-05-21 21:19:17,859 [api.get_http_post_response:99]:Unable to get games from API: Unable to connect to server https://lutris.net/api/games: The read operation timed out
DEBUG    2023-05-21 21:19:17,860 [lutris.sync_media:197]:Syncing 0 banners, 0 icons and 0 covers
INFO     2023-05-21 21:19:17,915 [runtime.update_runtimes:238]:Startup complete
`

> That is very odd; the failing code seems unrelated to commit
I was referencing the newest git at that moment, not when the error crept in.




> Seems to me that this fault may just disable the 'dark mode' preferences

Seems this is what happens. Dark Mode doesn't work for me.

> Not everything that is reported by users is true.

Really?

**Comment by danieljohnson2** [comment]
>> Not everything that is reported by users is true.

> Really?

Yeah, some of 'em say @strycore is a jerk! Can you believe it? Of course not! :rofl:

**Comment by danieljohnson2** [comment]
Serious; @telanus, what version of GNOME are you running? The setting it is trying to access is new in GNOME 42.

**Comment by telanus** [comment]
> Serious; @telanus, what version of GNOME are you running? The setting it is trying to access is new in GNOME 42.

Running whatever Kubuntu 20.04 came with. it's not the "latest" :D

**Comment by danieljohnson2** [comment]
Not much GNOME there. I believe KDE plasma got this setting implemented about a year ago, so 20.04 won't have it.

It might be nicer if the dark mode toggle was not displayed in this scenario, though. Hmm.

**Comment by strycore** [comment]
> > Not everything that is reported by users is true.
> 
> Really?

Mostly in terms of self-diagnosis, yes. A lot of the time, I see people presuming there's an issue with Lutris when the issue is adjacent to Lutris and comes from the environment the client is running on. I don't mean that as the issue isn't real.

In this situation, I would rather find the root cause of the issue than have some except block of code masking the issue.
I'm expecting some kind of missing dependency and/or incomplete Gtk theme for KDE.

**Comment by danieljohnson2** [comment]
I believe the root cause is an old OS that does not support the setting we want to access; KDE got support for this setting quite recently.

I think it could hide the toggle, but other than that it seems fine to me. I've not got around to trying to do this, which is why I'm sitting on this item.

**Comment by g-schaffer** [comment]
I'm facing the same issue

**Comment by strycore** [comment]
I agree with @telanus , we still support Ubuntu 20.04 which means Lutris should function normally on it. 
We refrain from using new features of Gtk until they are widely available on the oldest distribution we support (usually Debian stable or Ubuntu oldstable)
If for some reason, we switched the dark theme selector to some newer API, then it has to be reverted to the legacy one. Unless the legacy one doesn't work anymore on some of the more recent system we support, in which case we have to support both.

**Comment by strycore** [comment]
I created a Kubuntu 20.04 VM in Qemu and installed the Lutris 0.5.13 deb. 
I was able to switch between light and dark modes without issue 
![image](https://github.com/lutris/lutris/assets/280336/c1b3526d-0b0b-44b4-bbd8-1ed8cd21c854)

So there's something else at play here ... :detective:

**Comment by strycore** [comment]
There may be a related issue in #4869

**Comment by therealmate** [comment]
DXVK is not working for me after updating to 0.5.13-2. This might be another issue though.

**Comment by telanus** [comment]
> Lutris 0.5.13 deb

I've installed that onto my machine and still get the error O_o @strycore do your vm include xdg-desktop-portal? and what version if installed? and what point release is your VM? I'm using 20.04.6

> I'm facing the same issue

What gpu are you using? and what's your specs(Distro, release, point release)?

**Comment by g-schaffer** [comment]
> I'm facing the same issue

log :
> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found (36)

system information :
> ubuntu 20.04
> 5.15.0-72-generic
> x86_64
> GNOME

**Comment by danieljohnson2** [comment]
Yeah, my theory is clearly wrong- it's not that he's running KDE. But my second fix idea is no good- this isn't something that is supposed to be unsupported, we don't wan to just hide the option here.

I'm out of ideas here.

**Comment by strycore** [comment]
Error spotted on Devuan + XFCE here: #4870

**Comment by strycore** [comment]
Please make sure you have  xdg-desktop-portal installed and  xdg-dekstop-portal-gtk or xdg-desktop-portal-kde installed, depending on your desktop

**Comment by telanus** [comment]
> xdg-desktop-portal

I've got both installed, both is at 1.6.0-1, and the error is still there :D

**Comment by strycore** [comment]
That's very strange...

> I've installed that onto my machine and still get the error O_o @strycore do your vm include xdg-desktop-portal? and what version if installed? and what point release is your VM? I'm using 20.04.6

Yeah, I'm using 20.04.6. This is a default install with nothing added or removed, only Lutris is installed.

**Comment by rayrapetyan** [comment]
The `color-scheme` setting is broken in the "xdg-desktop-portal-gtk". Moreover, they're going to remove it completely: https://github.com/flatpak/xdg-desktop-portal-gtk/pull/421. A temp workaround could be installing this portal: https://gitlab.gnome.org/alicem/color-scheme-simulator. It provides a valid value (0) in response for `color-scheme` and you won't see the error in lutris logs on startup.
How to resolve this issue permanently? Good question. Seems there is no universal solution, as we can see the "universal" setting `org.freedesktop.appearance - color-scheme` is supported only on a limited set of WMs. So ignoring this error looks like the best solution for now.

**Comment by strycore** [comment]
If there's no downside in functionality, it's better to just ignore this error.

Note that we're likely to drop support for Ubuntu 20.04 later this year.

**Comment by telanus** [comment]
> If there's no downside in functionality, it's better to just ignore this error.
> 
> Note that we're likely to drop support for Ubuntu 20.04 later this year.

Boob. Hopefully they'll release a new ltd this year. I might then need to upgrade.

**Comment by strycore** [comment]
Ubuntu 24.04 will be a LTS
