### ISSUE TITLE
Cosmetic bug: Game banner graphics not displayed in Lutris on Debian Sid - Lutris 0.5.13

### ISSUE THREAD

**Issue by TaliesinEmrys** [lutris/lutris#4857]
### Bug description

This is purely a "cosmetic" problem.
Installing / launching games works fully.

I recently installed Lutris 0.5.13 upgrading from Lutris 0.5.12 on Debian Sid.

In Lutris 0.5.12 game banners are displayed correctly.

These are not displayed with Lutris 0.5.13

### How to Reproduce

Steps to reproduce the behaviour:

Launch Lutris 0.5.12 game banners are displayed.

Launch Lutris 0.5.13 game banners are not displayed.

### Expected behavior

Display game banners.

### Log output

```shell
Lutris -d produces no output for either 0.5.12 or 0.5.13 as I'm merely opening Lutris.
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 12 bookworm
Arch:            x86_64
Kernel:          6.2.15-1-siduction-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            5.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5600 XT (navi10, LLVM 15.0.6, DRM 3.49, 6.2.15-1-siduction-amd64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan Version:  1.3.239
Vulkan Drivers:  AMD Radeon RX 5600 XT (RADV NAVI10) (1.3.230)
```

### Media (optional)

![Lutris 0 5 12](https://github.com/lutris/lutris/assets/19159354/a99a5c2a-7416-4a46-bd64-c27b12ea82cf)
![Lutris 0 5 13](https://github.com/lutris/lutris/assets/19159354/7812099b-cfd8-4ed4-b3e7-fb9e38edd292)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by TaliesinEmrys** [comment]
Hi folks I just stumble across a working solution in the Lutris Discord server.

Installing the package for python3-gi-cairo corrects this cosmetic problem.

Perhaps the package was not included in the dependencies?

**Comment by strycore** [comment]
@TaliesinEmrys you're correct, this needs to be added to the dependencies

**Comment by danieljohnson2** [comment]
I'm surprised Lutris works at all without python3-gi-cairo. It's using Cairo to render the banners and such, which is much faster since we need not preload every image in advance. Also we can do Hi-DPI better. I think its worth the extra dependency.

@strycore told me that these dependancies are "the job of the package maintainers", but I don't know who they are or how to contact them.

**Comment by TaliesinEmrys** [comment]
> Where did you get the package from? I checked, the Debian link on the lutris site is still on 0.5.12, and the official debian repos also only have 0.5.12

https://github.com/lutris/lutris/releases

I don't believe we'll see an official Debian package yet as the python-moddb package which 0.5.13 will also require isn't available in the Debian Repos yet.

At least it wasn't the last I checked.

**Comment by danieljohnson2** [comment]
I believe the moddb stuff is optional. The Cairo dependency really isn't though.
