### ISSUE TITLE
One-off bug of the wrong DXVK version being downloaded

### ISSUE THREAD

**Issue by CommandMC** [lutris/lutris#4859]
### Bug description

The reported "Vulkan Version" in the Hardware Information (and in general) is not quite correct, as it's querying the Vulkan instance's version, rather than the version your GPU(s) actually support
This is caused by Lutris calling `vkEnumerateInstanceVersion` instead of `vkGetPhysicalDeviceProperties`

### How to Reproduce

1. Go to "Preferences" -> "Hardware Information"
2. Note the "Vulkan Version" reported there
3. Query your GPU's supported Vulkan version (with `vulkaninfo`, for example)
4. See potential mismatch (mapping to `vulkaninfo` output: Lutris reports "Vulkan Instance Version", while GPU-supported version is listed further below ("Device Properties and Extensions"))

### Expected behavior

Lutris should instead query device properties to detect the hardware-supported Vulkan version, as the version is used to decide on hardware-related questions, like which DXVK version to download

### Log output

```shell
N/A here
```

### System Information

```shell
N/A here
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
It call both APIs, and you should see both versions in the Hardware Information. Lutris thinks you should use DXVK 2 if *both* versions are >=1.3.

Can you post your System Information? It seems pretty relevant on this one.

**Comment by CommandMC** [comment]
`lutris/util/graphics/vkquery`'s `get_vulkan_api_version`, which is used by the Hardware Information widget (and probably also everywhere else, didn't dig that far yet) calls `vkEnumerateInstanceVersion` only

https://github.com/lutris/lutris/blob/555daa3c7bed1f9efbff97530ec8f5a402893e72/lutris/util/graphics/vkquery.py#L280

System Info:
```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.2-arch1-1
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  4.2 (Compatibility Profile) Mesa 23.0.3
OpenGL Core:     4.2 (Core Profile) Mesa 23.0.3
OpenGL ES:       OpenGL ES 3.0 Mesa 23.0.3
Vulkan Version:  1.3.246
Vulkan Drivers:  Intel(R) HD Graphics 4000 (IVB GT2) (1.2.238)
```

`vulkaninfo` to cross-reference: [vulkaninfo.txt](https://github.com/lutris/lutris/files/11502932/vulkaninfo.txt)

**Comment by CommandMC** [comment]
A-ha, now I see my misunderstanding

Still, I remember Lutris downloading DXVK 2.1, even though it (as you can see) shouldn't

**Comment by danieljohnson2** [comment]
Hmm. It should default you to the most recent DXVK < 2.0, with your driver.

Is it doing that?

**Comment by CommandMC** [comment]
Yup, sure is (`1.10.3` is marked as `(default)`)
I *am* seeing a `v2.1` folder in `~/.local/share/lutris/runtime/dxvk/` though, not sure how that got there

**Comment by danieljohnson2** [comment]
I just did a test, and it downloaded 1.10 for me.

I think maybe v2.1 was downloaded already by a previous Lutris that didn't care about Vulkan versions?

**Comment by CommandMC** [comment]
This is a fresh install, this system has never had Lutris on it before the latest update

I'd be fine marking this as a one-off though, if you're unable to reproduce this

**Comment by danieljohnson2** [comment]
No repro for me. But as long as it downloads the right thing too, it's not that big a deal, I think.
