### ISSUE TITLE
Lutris doesn't show all games that are installed upon upgrade to 0.5.13 unless I edit pga.db to delete games that had "browser" runner

### ISSUE THREAD

**Issue by pizzadude** [lutris/lutris#4863]
### Bug description

I upgraded to Lutris 0.5.13 on Fedora 38 using https://bodhi.fedoraproject.org/updates/FEDORA-2023-31031b88ef , and when I first launched the updated Lutris, I was confused, as most of the games I have installed were invisible unless I searched for them. So I looked in the terminal, and noticed this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 583, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store.py", line 160, in add_game
    game.runner_text,
    ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store_item.py", line 95, in runner_text
    return gtk_safe(get_runner_human_name(self.runner))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 123, in get_runner_human_name
    _cached_runner_human_names[runner_name] = import_runner(runner_name)().human_name
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 82, in import_runner
    runner_module = get_runner_module(runner_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 73, in get_runner_module
    raise InvalidRunner("Invalid runner name '%s'" % runner_name)
lutris.runners.InvalidRunner: Invalid runner name 'browser'

```

I then edited pga.db to remove any games that were installed via the now invalid "browser" runner. Then I did:

```
sqlite3 pga.db 'pragma wal_checkpoint(TRUNCATE); vacuum;'
```

Now it shows all my games.

### How to Reproduce

1. Have an older lutris installation with "browser runner" games, like slither.io, agar.io
2. Upgrade to lutris 0.5.13
3. Notice 99% of your games are missing in main view
4. Have to edit pga.db to fix the mess

### Expected behavior

The old runner to be ignored instead of causing 99% of my game to be hidden.

### Log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 583, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store.py", line 160, in add_game
    game.runner_text,
    ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/views/store_item.py", line 95, in runner_text
    return gtk_safe(get_runner_human_name(self.runner))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 123, in get_runner_human_name
    _cached_runner_human_names[runner_name] = import_runner(runner_name)().human_name
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 82, in import_runner
    runner_module = get_runner_module(runner_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 73, in get_runner_module
    raise InvalidRunner("Invalid runner name '%s'" % runner_name)
lutris.runners.InvalidRunner: Invalid runner name 'browser'

```
```


### System Information

```shell
[System]
OS:              Fedora Linux 38 KDE Plasma
Arch:            x86_64
Kernel:          6.2.15-300.fc38.x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.6 GB
Swap:            7.6 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.3
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.3
Vulkan Version:  1.3.243
Vulkan Drivers:  Intel(R) HD Graphics 620 (KBL GT2) (1.3.238)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
@farchord, I'd draw your attention to issue #4857.

Lutris 0.5.13 now depends on python3-gi-cairo, or however you spell that in RPMese.

**Comment by farchord** [comment]
@danieljohnson2 Is there a reason why this isn't in the setup.py? I very often check the beta release logs and even look at the setup.py to look for new libraries being needed for Lutris. Fedora's tooling also pulls the dependancies from the setup.py file, but because this new dependancy was not mentioned anywhere that I could find, now there's going to be a delay of a couple weeks while we have this new package go through the review process (It seems it's not released on the fedora repos)...

I guess for now it's going to have to go without it, but if the setup.py could be modified to add it as a dependancy, that would be great!

**Comment by danieljohnson2** [comment]
I do not understand it; I brought this to @strycore's attention before the release, and he just replied "that's the job of package maintainers". I don't know who they are or how they find out about this.

I've been thinking of putting together a PR to try to address this, but I didn't realize 'setup.py' was important until now. I don't know how Fedora does this stuff. #4625 was kinda of my fault, and I'm leery of repeating that mistake.

I think there's a problem here, but I don't know what I'm doing, so I'm drawing attention to the issue.

**Comment by danieljohnson2** [comment]
I should make it clear that I don't know that you need to do *anything*.

I find that in PIP, PyGObject 'requires' pycairo. We require PyGObject. Maybe that is enough? But #4857 happened (on Debian Sid).

**Comment by farchord** [comment]
> I should make it clear that I don't know that you need to do _anything_.
> 
> I find that in PIP, PyGObject 'requires' pycairo. We require PyGObject. Maybe that is enough? But #4857 happened (on Debian Sid).

Yeah I did some investigation.  This is most likely a non-issue on Fedora.

1- Lutris 0.5.13 runs just fine

2- ❯ sudo dnf repoquery --requires python3-gobject
Last metadata expiration check: 0:02:30 ago on Sat 20 May 2023 05:50:59 AM.
libc.so.6(GLIBC_2.4)
libc.so.6(GLIBC_2.4)(64bit)
libcairo-gobject.so.2
libcairo-gobject.so.2()(64bit)
libcairo.so.2
libcairo.so.2()(64bit)
libgobject-2.0.so.0
libgobject-2.0.so.0()(64bit)
python(abi) = 3.11
python3-cairo(x86-32) >= 1.16.0
python3-cairo(x86-64) >= 1.16.0
python3-gobject-base(x86-32) = 3.44.1-1.fc38
python3-gobject-base(x86-64) = 3.44.1-1.fc38
rtld(GNU_HASH)

**Comment by strycore** [comment]
> I don't know who they are or how they find out about this.

@danieljohnson2 I have an email list with the mantainers for every distro, I'm going to write them a message very soon with all the info collected in the past days.

**Comment by farchord** [comment]
> > I don't know who they are or how they find out about this.
> 
> @danieljohnson2 I have an email list with the mantainers for every distro, I'm going to write them a message very soon with all the info collected in the past days.

Love that list by the way, saved our bacon a couple times already.
