### ISSUE TITLE
[FLATPAK] Setting FR locale doesn't set GUI in French

### ISSUE THREAD

**Issue by Xdavius** [lutris/lutris#4865]
### Bug description

Gui still in EN after setting French locale in org.gnome.Platform.Locale and Setting locale inside the app
![Screenshot_20230520_133047](https://github.com/lutris/lutris/assets/66792063/48237d77-fb8c-478d-a371-35aadc5c75ae)

### How to Reproduce

1. flatpak update --subpath=fr org.gnome.Platform.Locale
2. ON LUTRIS GUI : Click on '...'/Preferences/Global options/Locale
3. Set to fr_FR.utf8
4. No effect after reboot app or computer

### Expected behavior

Gui translated in french (like deb version)

### Log output

```shell
davius@davius-virtualbox:~$ flatpak run net.lutris.Lutris -d
libEGL warning: DRI2: failed to authenticate
INFO     2023-05-20 13:25:28,380 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-05-20 13:25:28,382 [startup.check_driver:72]:Running Mesa Mesa driver 23.0.2 on llvmpipe (LLVM 15.0.7, 256 bits) (0xffffffff)
INFO     2023-05-20 13:25:28,382 [startup.check_driver:84]:GPU: 15AD:0405 15AD:0405 (vmwgfx drivers)
DEBUG    2023-05-20 13:25:28,517 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:43,305 [application.show_window:339]:Showing window PreferencesDialog{}
DEBUG    2023-05-20 13:25:44,569 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:44,574 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:44,587 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:44,590 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:44,593 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-20 13:25:51,002 [config.save:229]:Saving LutrisConfig(level=system, game_config_id=None, runner=None) config to /home/davius/.var/app/net.lutris.Lutris/config/lutris/system.yml
DEBUG    2023-05-20 13:25:51,004 [application.on_app_window_destroyed:357]:Removed window PreferencesDialog{}
INFO     2023-05-20 13:25:52,399 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
VM System :

[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.3.3-1-liquorix-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             3.8 GB
Swap:            1.0 GB

[Graphics]
Vendor:          Mesa
OpenGL Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 23.0.2 (git-4d5e73870e)
OpenGL Core:     4.5 (Core Profile) Mesa 23.0.2 (git-4d5e73870e)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.2 (git-4d5e73870e)
Vulkan Version:  1.3.224
Vulkan Drivers:  

Host Hardware :

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.29-273-tkg-cfs
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            16.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (navi22, LLVM 15.0.7, DRM 3.49, 6.1.29-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.0-devel (git-5a7520d252)
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.0-devel (git-5a7520d252)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.0-devel (git-5a7520d252)
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That's the setting for the game you run, not for Lutris itself.

**Comment by Xdavius** [comment]
> That's the setting for the game you run, not for Lutris itself.

OK. But still no French GUI.
Thanks you for that explaination, it will help us a lot too !!

**Comment by strycore** [comment]
The Flatpak wasn't using meson to build Lutris, which means translation files weren't built.
I'm testing a change to meson here: https://github.com/flathub/net.lutris.Lutris/pull/336

**Comment by Xdavius** [comment]
> The Flatpak wasn't using meson to build Lutris, which means translation files weren't built. I'm testing a change to meson here: [flathub/net.lutris.Lutris#336](https://github.com/flathub/net.lutris.Lutris/pull/336)

Hi, today testing lutris flathub-beta, it works in french and locale seted well into french in global options.

Waiting for stable. Seems to go in the wright way !!!

French users says thank you !

**Comment by strycore** [comment]
I've merged the beta branch into stable so it should be published in a few hours
