### ISSUE TITLE
[itch.io] Login window continues to website after sucessful login (via 2FA?)

### ISSUE THREAD

**Issue by gullcomb** [lutris/lutris#4874]
First, let me thank everyone involved in releasing this feature. What I'm reporting is not a failing of the feature, but of the interface. It lead me to think it failed when it actually didn't.

What happened:

1. I ask lutris to log in to itch.io.
2. lutris displays a new window with the itch.io's username&password prompt.
3. I fill them in and itch.io decides to ask for 2FA (via e-mail), which lutris displays correctly in the same window.
4. After successfully filling in the 2FA challenge, lutris' login window now displays itch.io's homepage for my account.

Now, the last time I met such a situation it was because of mastodon/mastodon#18481 so I first assumed lutris did not get the authentication secrets. However, after closing the window I was able to successfully refresh the list of games.

For the record, I don't remember GOG exhibiting the same behavior when I did the same for that account.

If it turns out to be expected behavior, perhaps because doing otherwise is too difficult, could you please include a short message saying so in the login window?

**Comment by strycore** [comment]
This is a bug, the Itch.io service doesn't have the correct redirect URL and thus doesn't close the login window.

**Comment by ryanfantus** [comment]
Hey @strycore - hitting this issue once again. Any chance you can take another look?
