### ISSUE TITLE
Add missing label on Games view

### ISSUE THREAD

**Issue by Lx32** [lutris/lutris#4876]
I love the introduction of the missing tab, I have a lot of games installed and when I complete one I move it on a storage and don't remove it. I would like that on Games tab, where I see all the games, I can clearly see all the games that are missing, with a small label or a fade out. Just like on Heroic that fade out missing games.

**Comment by danieljohnson2** [comment]
We fade out uninstalled games, so that's taken.

Perhaps some sort of badge, like with the platform badges?

**Comment by Lx32** [comment]
> We fade out uninstalled games, so that's taken.
> 
> Perhaps some sort of badge, like with the platform badges?

Yes, I think that will be ok. Or maybe list them after the non installed ones. They are only ideas, but I think that will be useful to have a clear view of what I can launch directly and what I have to connect the HDD before.

**Comment by strycore** [comment]
@Lx32 I think you'll also be interested with this feature: https://github.com/lutris/lutris/issues/4118#issuecomment-1576432495
