### ISSUE TITLE
ModuleNotFoundError: No module named 'lutris' on manjaro

### ISSUE THREAD

**Issue by Unfaced85** [lutris/lutris#4883]
### Bug description

I just installed Lutris 0.5.12-3 on a fresh Manjaro KDE Plasma Distro. I followed those Guides [GPUDrivers](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) and [WineDependencies](https://github.com/lutris/docs/blob/master/WineDependencies.md) and then installed Lutris via Pacman and chose all optional dependencies as well.

I get

`Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'lutris'
`

when launching it. I have Python 3.11.3 installed when typing python --version. I did not manually install any pip packages

### How to Reproduce

Install GPU and Wine dependencies and Lutris via Pacman with all optional dependencies

try to launch lutris, get error

### Expected behavior

Lutris should start

### Log output

```shell
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'lutris'
```

### System Information

```shell
6.2.16-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May 17 17:02:01 UTC 2023 x86_64 GNU/Linux

AMD Ryzen 5800x3d, 64GB RAM, RX7900XTX
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Unfaced85** [comment]
I now uninstalled lutris 0.5.12-3 from the official repo and installed the flatpak Version 0.5.13 via pacman - this seems to work though

**Comment by strycore** [comment]
I don't know what when wrong but lutris should be ok on Arch with version 0.5.13

**Comment by Milor123** [comment]
guys what is the solution? (and please dont saids install it from flatpak)

**Comment by strycore** [comment]
> guys what is the solution? (and please dont saids install it from flatpak)

`rm -rf ~/.local/lib/python*`

**Comment by demetera** [comment]
> > guys what is the solution? (and please dont saids install it from flatpak)
> 
> `rm -rf ~/.local/lib/python*`

Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
ModuleNotFoundError: No module named 'lutris'

**Comment by strycore** [comment]
> including anything in ~/.local/share/lutris

no, do not delete your data in this folder. It doesn't change the way Lutris function, especially not Python stuff. 

When I say `rm -rf ~/.local/lib/python*` it's to get rid of dependencies installed as a regular user which may or may not be Lutris at all but may be conflicting with Lutris. In recent versions of Lutris, we ignore Python packages coming from the home folder.

Another possibility, which has nothing to do with user installed modules is your distro updating your Python version. In this case, a simple uninstall / reinstall of Lutris via your package manager will do the trick.
