### ISSUE TITLE
[DEBIAN 12] After install, ~/.share/lutris/runtime is empty

### ISSUE THREAD

**Issue by Xdavius** [lutris/lutris#4892]
### Bug description

After installing the .deb (or downloading from debian repo, same problem OTB), trying to install battle.net but dxvk error.
After some research, I have see that ~/.share/lutris/runtime is empty. no dxvk, no vkd3d, no dxvk-nvapi, no d3d-extras.

Resulting an error while installing battle.net (or other launchers btw) with dxvk not found.

After installing by myself all of those, resulting install is OK but banners doesn't appers.

THIS IS NOT IMPACTING THE FLATPAK VERSION.

### How to Reproduce

1- Install .deb lutris after fesh install on Debian 12 (KDE)
2- serch for battle.net installation script
3- got an error with dxvk

### Expected behavior

Lutris must download all runtimes on first launch (I think) or must be provided with deb.

(Retried now, and seems to work !? KDE wayland in cause ? worked on KDE X11 launching lutris from terminal, but other tries before failed before)

### Log output

```shell
See attachment please
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 12 bookworm
Arch:            x86_64
Kernel:          6.1.0-9-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             3.8 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Mesa/X.org
OpenGL Renderer: llvmpipe (LLVM 15.0.6, 256 bits)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.5 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan Version:  1.3.239
Vulkan Drivers:
```

### Media (optional)

![Capture d’écran du 2023-06-04 19-36-36](https://github.com/lutris/lutris/assets/66792063/646d9c71-679d-45d2-9e45-6703f1ce92dc)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
It's hard to tell without the logs of the initial run. Looks like there was a network issue preventing the runtime components from being downloaded.

Is this reproducible? If you rename the runtime dir to runtime.bak and restart lutris in Wayland.

 `OpenGL Renderer: llvmpipe (LLVM 15.0.6, 256 bits)`

Is this in a VM?

**Comment by Xdavius** [comment]
> It's hard to tell without the logs of the initial run. Looks like there was a network issue preventing the runtime components from being downloaded.
> 
> Is this reproducible? If you rename the runtime dir to runtime.bak and restart lutris in Wayland.
> 
> `OpenGL Renderer: llvmpipe (LLVM 15.0.6, 256 bits)`
> 
> Is this in a VM?

This one yes, but same yesterday on hard install, on Ubuntu, then on Debian.

Yes, maybe a network issue but, not a local network issue (because the one on hard install is from an other city of france). It seems that the trouble is about 2 days ago, but not sure.

I need te deploy an other fresh VM, because this one was used to test a lot, testing the flatpak version too. I come back later, with logs and/or news.

But this make me crazy since yesterday.

**Comment by Xdavius** [comment]
I'm back.
I have successfully completed the install from deb without error at 14h00 GMT+1. Seems to be a network bug (github ?). Maybe having a fallback mirror preventing this trouble may be a good idea ? 

Thank you.
