### ISSUE TITLE
cannot add a local game?

### ISSUE THREAD

**Issue by Usulyre** [lutris/lutris#4899]
Have Lutris 0.5.13, cannot add a local game using the "add locally installed game" 

I press on that option and nothing prompts me to add a game.

If I drag a game that is a Windows game with an .exe it says "the rom could not be identified"?

I'm on Chrome OS beta 115 using crostini default debian bullseye container.

**Comment by danieljohnson2** [comment]
You might want to try the "Install a Windows game from an executable" option.

The option you chose should open a window for fully manual setup. If no window appears, that's not so good. Can you post a debug log for us?

Run ```lutris -d``` at the terminal and then go click on 'Add locally installed game', and give us whatever log spam comes out.

**Comment by Usulyre** [comment]
Hi, the game is not an installer it's just a full game run from the .exe file.

so that is why I didn't try the "Install a Windows game from an executable" option yet

after running Lutris -d I got this from terminal:

DEBUG    2023-06-09 16:17:35,216 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-06-09 16:17:36,507 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}

**Comment by strycore** [comment]
> I press on that option and nothing prompts me to add a game.

Really? What's the command line output?

**Comment by danieljohnson2** [comment]
I think there ought to be more debug log that that. But the two lines you post are normal- that's the add-games wizard appearing, then being removed. That's supposed to happen when you click that option.

I hope there's more log.

**Comment by Usulyre** [comment]
![Screenshot 2023-06-09 4 22 49 PM](https://github.com/lutris/lutris/assets/16013427/355e101d-f05c-456b-8945-26409e6e95a9)

**Comment by Usulyre** [comment]
where do I get a log file for Lutris from?

**Comment by danieljohnson2** [comment]
That was the log. There's nothing abnormal there.

I wonder if the window did open but someplace non-obvious? Maybe on the wrong desktop or minimized or something?

It's weird that we're getting *nothing* in the log.

**Comment by strycore** [comment]
If that's all you got, there's not really anything we can do to solve an issue we can't see. 

I would go ahead and just say "ChromeOS is a piece of junk" but that being true doesn't really help solving the issue.

If you don't get the dialog below when you press the "Add locally installed game" option then I'm afraid something has gone very very wrong.

![image](https://github.com/lutris/lutris/assets/280336/65dac9fd-7bd9-4a7e-9aca-c80b2276f6dd)

**Comment by Usulyre** [comment]
I didn't have any issues with a previous version i think it was 0.5.12

**Comment by Usulyre** [comment]
also at first Lutris didn't even open up I used this command to fix that:

sudo apt-get install -y python3-gi-cairo

**Comment by Usulyre** [comment]
that worked to get Lutris running

From issue: [
](https://github.com/lutris/lutris/issues/4857)

**Comment by Usulyre** [comment]
https://github.com/lutris/lutris/issues/4857

**Comment by danieljohnson2** [comment]
Yeah, that dependency was missing on the release; but as far as I know that's the only missing dependency.

**Comment by danieljohnson2** [comment]
I'll think on this and maybe I can think of some way to learn more about your problem.

**Comment by Usulyre** [comment]
ok thanks

**Comment by danieljohnson2** [comment]
Well, here's a thing we can try @Usulyre.

I've set up [a branch here](https://github.com/lutris/lutris/tree/dj/watch_it_die)

Download that and run the 'bin/lutris' script in there with the -d option. I've added some debug logging. Provide the output; the new messages should give us a clue about how far it's getting with the window it's creating.

**Comment by Usulyre** [comment]
usulyre@penguin:~/lutris-dj-watch_it_die/lutris-dj-watch_it_die/bin$ lutris -d
2023-06-10 19:13:50,997: lspci is not available. List of graphics cards not available
2023-06-10 19:13:51,009: Couldn't find a terminal emulator.
INFO     2023-06-10 19:13:52,287 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-10 19:13:52,300 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-10 19:13:52,304 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-10 19:13:53,060 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-10 19:13:53,203 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-10 19:13:53,250 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-06-10 19:13:55,010 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-06-10 19:13:55,388 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-06-10 19:13:55,966 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-06-10 19:13:55,969 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-06-10 19:13:56,497 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-06-10 19:13:56,505 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-06-10 19:13:56,986 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-06-10 19:13:56,988 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-06-10 19:13:57,417 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-06-10 19:13:57,435 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-06-10 19:13:57,946 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2023-06-10 19:13:57,949 [runtime.update_runtimes:238]:Startup complete
DEBUG    2023-06-10 19:14:05,341 [application.show_window:339]:Showing window PreferencesDialog{}
DEBUG    2023-06-10 19:14:13,665 [application.on_app_window_destroyed:357]:Removed window PreferencesDialog{}
DEBUG    2023-06-10 19:14:21,109 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-06-10 19:14:28,024 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}

**Comment by danieljohnson2** [comment]
No, not quite. ```lutris -d``` runs the installed lutris. Do this:

```
./lutris -d
```

The ./ part makes it use the lutris in your current directory instead.

**Comment by Usulyre** [comment]
> No, not quite. `lutris -d` runs the installed lutris. Do this:
> 
> ```
> ./lutris -d
> ```
> 
> The ./ part makes it use the lutris in your current directory instead.


usulyre@penguin:~/lutris-dj-watch_it_die/lutris-dj-watch_it_die/bin$ ./lutris -d
2023-06-11 08:50:04,585: lspci is not available. List of graphics cards not available
2023-06-11 08:50:04,601: Couldn't find a terminal emulator.
INFO     2023-06-11 08:50:06,285 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-11 08:50:06,294 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-11 08:50:06,295 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-11 08:50:07,045 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-11 08:50:07,393 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-11 08:50:07,464 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-06-11 08:50:07,937 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-06-11 08:50:08,314 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-06-11 08:50:08,913 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-06-11 08:50:08,919 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-06-11 08:50:09,512 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-06-11 08:50:09,522 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-06-11 08:50:09,997 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-06-11 08:50:10,010 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-06-11 08:50:10,513 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-06-11 08:50:10,568 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-06-11 08:50:11,224 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2023-06-11 08:50:11,229 [runtime.update_runtimes:238]:Startup complete
DEBUG    2023-06-11 08:50:25,708 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7bc3c80ef040 (LutrisWindow at 0x188e2a0)>}
DEBUG    2023-06-11 08:50:28,552 [add_game_dialog.__init__:12]:AddGameDialog.__init__ A
DEBUG    2023-06-11 08:50:28,569 [add_game_dialog.__init__:14]:AddGameDialog.__init__ B
DEBUG    2023-06-11 08:50:28,569 [add_game_dialog.__init__:23]:AddGameDialog.__init__ C
DEBUG    2023-06-11 08:50:28,575 [add_game_dialog.__init__:28]:AddGameDialog.__init__ D
DEBUG    2023-06-11 08:50:28,577 [add_game_dialog.__init__:30]:AddGameDialog.__init__ E
DEBUG    2023-06-11 08:50:28,657 [add_game_dialog.__init__:32]:AddGameDialog.__init__ F
DEBUG    2023-06-11 08:50:28,657 [add_game_dialog.__init__:34]:AddGameDialog.__init__ G
DEBUG    2023-06-11 08:50:28,683 [add_game_dialog.__init__:36]:AddGameDialog.__init__ H
DEBUG    2023-06-11 08:50:28,730 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7bc3c80ef040 (LutrisWindow at 0x188e2a0)>}

**Comment by danieljohnson2** [comment]
Looks like it gets all the way through creating that window.

Can you try the "Add installed game" command? It opens the same window the same way. It's a context menu command you can use on games in the 'Sources' area, like not-yet-installed Lutris games.

**Comment by danieljohnson2** [comment]
I've pushed another change to [that branch](https://github.com/lutris/lutris/tree/dj/watch_it_die).

Download or pull it and run bin/lutris- maybe that window will show up now. I've added code to explicitly present it.

**Comment by Usulyre** [comment]
> Looks like it gets all the way through creating that window.
> 
> Can you try the "Add installed game" command? It opens the same window the same way. It's a context menu command you can use on games in the 'Sources' area, like not-yet-installed Lutris games.

![Screenshot 2023-06-11 9 06 05 AM](https://github.com/lutris/lutris/assets/16013427/213bfe5e-f818-4336-bb3d-c51371df9491)

**Comment by danieljohnson2** [comment]
Too grim-dark for me.

I think you are saying "I have no games at all, even non-installed ones". That's a shame.

Try the new version of the branch. Maybe it will work!

**Comment by Usulyre** [comment]
> Too grim-dark for me.
> 
> I think you are saying "I have no games at all, even non-installed ones". That's a shame.
> 
> Try the new version of the branch. Maybe it will work!

usulyre@penguin:~/lutris-dj-watch_it_die/bin$ ./lutris -d
2023-06-11 09:09:09,518: lspci is not available. List of graphics cards not available
2023-06-11 09:09:09,544: Couldn't find a terminal emulator.
INFO     2023-06-11 09:09:10,467 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-11 09:09:10,473 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-11 09:09:10,474 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-11 09:09:10,983 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-11 09:09:11,177 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-11 09:09:36,344 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7c3f32d35e80 (LutrisWindow at 0x19782c0)>}
DEBUG    2023-06-11 09:09:38,219 [add_game_dialog.__init__:12]:AddGameDialog.__init__ A
DEBUG    2023-06-11 09:09:38,330 [add_game_dialog.__init__:30]:AddGameDialog.__init__ H
DEBUG    2023-06-11 09:09:38,331 [add_game_dialog.__init__:32]:AddGameDialog.__init__ I
DEBUG    2023-06-11 09:09:38,346 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7c3f32d35e80 (LutrisWindow at 0x19782c0)>}

**Comment by danieljohnson2** [comment]
Did it appear at all, even briefly?

**Comment by Usulyre** [comment]
not at all

**Comment by danieljohnson2** [comment]
This is really weird. I'll keep thinking about it. Sorry we're not having more success here.

**Comment by Usulyre** [comment]
Ok, no problem, thanks for helping with this issue

**Comment by danieljohnson2** [comment]
Got another idea. The dialog closes when it gets a 'response' like cancelling (hitting escape). Maybe that's happening?

I've made a further update to [the branch](https://github.com/lutris/lutris/tree/dj/watch_it_die)

Could you try the latest? With ```-d```. It won't fix the problem, but it may log something that will help.

**Comment by Usulyre** [comment]
usulyre@penguin:~/lutris-dj-watch_it_die/bin$ ./lutris -d
2023-06-11 15:25:12,294: lspci is not available. List of graphics cards not available
2023-06-11 15:25:12,306: Couldn't find a terminal emulator.
INFO     2023-06-11 15:25:13,196 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-11 15:25:13,206 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-11 15:25:13,207 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-11 15:25:13,720 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-11 15:25:13,923 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-11 15:25:13,975 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2023-06-11 15:25:14,391 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2023-06-11 15:25:14,401 [http._request:88]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2023-06-11 15:25:14,691 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2023-06-11 15:25:14,696 [http._request:88]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2023-06-11 15:25:14,982 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2023-06-11 15:25:14,985 [http._request:88]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2023-06-11 15:25:15,214 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2023-06-11 15:25:15,225 [http._request:88]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2023-06-11 15:25:15,497 [http.write_to_file:142]:Writing to /home/usulyre/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2023-06-11 15:25:15,502 [runtime.update_runtimes:238]:Startup complete
DEBUG    2023-06-11 15:25:26,647 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7d5aeb427140 (LutrisWindow at 0x35e02c0)>}
DEBUG    2023-06-11 15:25:28,011 [add_game_dialog.__init__:12]:AddGameDialog.__init__ A
DEBUG    2023-06-11 15:25:28,128 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7d5aeb427140 (LutrisWindow at 0x35e02c0)>}
DEBUG    2023-06-11 15:25:28,187 [__init__.on_response:103]:Response: -4

**Comment by danieljohnson2** [comment]
It's acting like you are clicking the close box, which the dialog doesn't even have.

I've made a further tweak to [that damned branch](https://github.com/lutris/lutris/tree/dj/watch_it_die); it will ignore the DELETE_EVENT response you are getting. But I have no expectation this will work; the window is already closing when this happens.

You can give it a try if you are feeling lucky.

**Comment by Usulyre** [comment]
Didn't work:

usulyre@penguin:~/lutris-dj-watch_it_die/bin$ ./lutris -d
2023-06-11 16:23:37,822: lspci is not available. List of graphics cards not available
2023-06-11 16:23:37,833: Couldn't find a terminal emulator.
INFO     2023-06-11 16:23:38,740 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-11 16:23:38,748 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-11 16:23:38,748 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-11 16:23:39,279 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-11 16:23:39,459 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-11 16:23:42,484 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7c32cc5b7180 (LutrisWindow at 0x20b02c0)>}
DEBUG    2023-06-11 16:23:43,753 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7c32cc5b7180 (LutrisWindow at 0x20b02c0)>}

**Comment by danieljohnson2** [comment]
Didn't really think it would.

I think your computer is haunted. You have a poltergeist that clicks close boxes *so fast* you can't see the window.

**Comment by strycore** [comment]
Do the other dialogs of type GameDialogCommon experience the same issue?

Like configuring a runner or an installed game.

**Comment by Usulyre** [comment]
![Screenshot 2023-06-11 7 16 54 PM](https://github.com/lutris/lutris/assets/16013427/da0ff104-34ed-411c-8c67-58240a8babf9)

**Comment by danieljohnson2** [comment]
Well, one difference is that this dialog is being shown via Application.show_window. So, I've updated [that branch](https://github.com/lutris/lutris/tree/dj/watch_it_die) to do that also for AddGameWindow from AddGamesWindow (I suspect better names could be chosen here).

If that's the difference, it'll start working. Could you give it a try,  @Usulyre?

**Comment by danieljohnson2** [comment]
Ohhh, I may see it. The AddGamesWindow goes first, then the AddGameDialog.

All our dialogs get the destroy_with_parent with parent set to True, but it doesn't seem to do anything. I think maybe for you it *does*!

I've committed a change to remove this entirely; we probably want it for modal dialogs only. At least not *this* dialog.

Please try [that branch](https://github.com/lutris/lutris/tree/dj/watch_it_die) once again.

Maybe that dialog will start working now! :crossed_fingers:

**Comment by Usulyre** [comment]
The window popped up now.

usulyre@penguin:~/lutris-dj-watch_it_die/bin$ ./lutris -d
2023-06-12 14:42:35,522: lspci is not available. List of graphics cards not available
2023-06-12 14:42:35,532: Couldn't find a terminal emulator.
INFO     2023-06-12 14:42:36,469 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-12 14:42:36,476 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-12 14:42:36,477 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-12 14:42:37,026 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-12 14:42:37,219 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-12 14:42:39,662 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7ee93a05b580 (LutrisWindow at 0x2bf02a0)>}
DEBUG    2023-06-12 14:42:41,040 [application.show_window:339]:Showing window AddGameDialog{'parent': <addgameswindow.AddGamesWindow object at 0x7ee9447d5f40 (lutris+gui+addgameswindow+AddGamesWindow at 0x2d379c0)>}
DEBUG    2023-06-12 14:42:41,090 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7ee93a05b580 (LutrisWindow at 0x2bf02a0)>}

![Screenshot 2023-06-12 2 43 09 PM](https://github.com/lutris/lutris/assets/16013427/008beed6-cb72-4aea-9cfd-a855dc23358f)

**Comment by danieljohnson2** [comment]
We're making progress, but we don't have a real fix yet. I'll put together a new branch to try to do that.

I expect your game won't start because lutris-wrapper does not have its executable bit set. Try this:
```
chmod +x /home/usulyre/lutris-dj-watch_it_die/share/lutris/bin/lutris-wrapper
```
I bet you'll be able to start the game.

**Comment by Usulyre** [comment]
> We're making progress, but we don't have a real fix yet. I'll put together a new branch to try to do that.
> 
> I expect your game won't start because lutris-wrapper does not have its executable bit set. Try this:
> 
> ```
> chmod +x /home/usulyre/lutris-dj-watch_it_die/share/lutris/bin/lutris-wrapper
> ```
> 
> I bet you'll be able to start the game.

Yes, I am able to start a game now

**Comment by danieljohnson2** [comment]
OK, I've got a more subtle attempt, [in this new branch](https://github.com/lutris/lutris/tree/dj/watch_it_live).

This sets destroy_with_parent for modal dialogs only, and also takes care to disconnect the dialog from the parent before destroying the parent anyway. This should allow the window manager to place the dialog correctly, while still avoiding the bug- I hope!

Please give this new branch a try and let me know if the dialog will still appear for you.

**Comment by Usulyre** [comment]
Didn't work this time.

usulyre@penguin:~/lutris-dj-watch_it_live/bin$ ./lutris -d
2023-06-12 16:51:41,026: lspci is not available. List of graphics cards not available
2023-06-12 16:51:41,039: Couldn't find a terminal emulator.
INFO     2023-06-12 16:51:42,016 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-12 16:51:42,030 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-12 16:51:42,031 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-12 16:51:42,583 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-12 16:51:42,816 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-12 16:51:57,540 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f9aa8dcf9c0 (LutrisWindow at 0x34082c0)>}
DEBUG    2023-06-12 16:51:59,336 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7f9aa8dcf9c0 (LutrisWindow at 0x34082c0)>}

**Comment by danieljohnson2** [comment]
Nertz. One more try; a compromise- I'll use the main LutrisWindow as the parent here, so the new dialog will be centered over that. Not ideal, but I expect it will let you see the dialog.

I forced pushed this, so you may need to redownload or force-pull it. Give it a shot.

**Comment by Usulyre** [comment]
Yes it works again.

usulyre@penguin:~/lutris-dj-watch_it_live/bin$ ./lutris -d
2023-06-12 17:09:42,916: lspci is not available. List of graphics cards not available
2023-06-12 17:09:42,931: Couldn't find a terminal emulator.
INFO     2023-06-12 17:09:43,966 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-12 17:09:43,974 [startup.check_driver:73]:Running Mesa Mesa driver 23.2.0 on virgl (Mesa Intel(R) UHD Graphics (CML GT1)) (0x1010)
INFO     2023-06-12 17:09:43,974 [startup.check_driver:85]:GPU: 1AF4:1050 1AF4:1050 (virtio-pci drivers)
DEBUG    2023-06-12 17:09:44,624 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-12 17:09:44,839 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-12 17:09:44,915 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-06-12 17:09:45,379 [http._request:88]:GET https://lutris.net/api/runtimes/icons
INFO     2023-06-12 17:09:45,801 [runtime.update_runtimes:238]:Startup complete
DEBUG    2023-06-12 17:09:50,033 [application.show_window:339]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7e3d2252ed40 (LutrisWindow at 0x345c2a0)>}
DEBUG    2023-06-12 17:09:50,982 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7e3d2252ed40 (LutrisWindow at 0x345c2a0)>}

**Comment by danieljohnson2** [comment]
Merged!

I still think you have poltergeists though.

**Comment by strycore** [comment]
> poltergeists

It's called ChromeOS

**Comment by danieljohnson2** [comment]
*Spoooky*!

But Lutris was definitely not doing the right thing here. It created a window with destroy_with_parent, then immediately destroyed the parent. That can't be right.

**Comment by strycore** [comment]
yeah, I see what the problem was. Weird that it worked fine on any OS other than ChromeOS
