### ISSUE TITLE
Lutris fails to start on Arch Linux

### ISSUE THREAD

**Issue by 4censord** [lutris/lutris#4906]
### Bug description

Lutris does not start.

### How to Reproduce

Try to start lutris.

### Expected behavior

Lutris starts

### Log output

```shell
$ lutris -d
INFO     2023-06-16 16:57:10,868 [startup.init_lutris:203]:Starting Lutris 0.5.13
INFO     2023-06-16 16:57:10,870 [startup.check_driver:73]:Running AMD Mesa driver 23.1.2 on AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.3.8-arch1-1) (0x67df)
INFO     2023-06-16 16:57:10,870 [startup.check_driver:85]:GPU: 1002:67DF 1043:0519 (amdgpu drivers)

(lutris:9564): Gtk-CRITICAL **: 16:57:10.910: Unable to retrieve object 'games_stack' from class template for type 'LutrisWindow' while building a 'LutrisWindow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 104, in __init__
    self.init_template()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/gi_composites.py", line 116, in <lambda>
    cls.init_template = lambda s: _init_template(s, cls, base_init_template)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/gi_composites.py", line 142, in _init_template
    raise AttributeError(
AttributeError: A missing child widget was set using GtkTemplate.Child and the entire template is now broken (widgets: viewtype_icon, game_revealer, blank_overlay, search_entry, sidebar_revealer, zoom_adjustment, sidebar_scrolled, games_stack)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'
```

### System Information

Not able to paste cause lutris does not start.
But to the best of my ability:

```shell
[System]
OS: Arch linux roling
Arch: x86_64
Kernel: 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC
Desktop: Sway
Displayserver: Wayland

[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 3900X 12-Core Processor
Pysical cores: 12
Logical cores: 24

[Memory]
RAM: 31Gi
Swap: 47Gi

[Graphics]
Vendor: AMD
Device: AMD Radeon RX 580 Series

OpenGL:
	GL_VERSION: 4.6 (Compatibility Profile) Mesa 23.1.2
	GL_RENDERER: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.3.8-arch1-1)
	GL_SHADING_LANGUAGE_VERSION = 4.60
	GLU_VERSION: 1.3
	GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
	GLUT_API_VERSION: 4
	GLUT_XLIB_IMPLEMENTATION: 13

Vulkan:
	apiVersion         = 1.3.246
	driverVersion      = 23.1.2
	vendorID           = 0x1002
	deviceID           = 0x67df
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Radeon RX 580 Series (RADV POLARIS10)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 23.1.2
	conformanceVersion = 1.2.7.1
	deviceUUID         = 00000000-0900-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
```

```shell
$ lutris -v
lutris-0.5.13
$ pacman -Q lutris
lutris-git 0.5.13.r121.g8f1e4d26-1
```
Same story with the non git version: `extra lutris 0.5.13-5`

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

Forgot to mention: it was working before

**Comment by danieljohnson2** [comment]
Hmmm. It can't find ```games_stack``` in the lutris-window.ui file. I wonder if you have a corrupted install where that file is an old version?

Another way this sort of thing can happen is if you manage to install Lutris *locally*; you can wind up getting bits of the system-wide install mixed in the the local copy, and that falls apart fast.

The global file will be at this path: /usr/share/lutris/ui/lutris-window.ui
And if you have a local one, I expect it is at: ~/.local/share/lutris/ui/lutris-window.ui

Do you have these files, and do they contain ```games_stack``` anywhere in them?

**Comment by strycore** [comment]
usually, those Arch errors come from an incomplete update, a system that is pending a reboot or once of those things that only people who say "I un Arch btw" have the talent to do.

**Comment by 4censord** [comment]
> usually, those Arch errors come from an incomplete update, a system that is pending a reboot or once of those things that only people who say "I un Arch btw" have the talent to do.

I did a full update, and a reboot to rule that out.

As for the more helfull reply from @danieljohnson2 


```shell
$ ll /usr/share/lutris/ui/lutris-window.ui ~/.local/share/lutris/ui/lutris-window.ui
-rw-r--r-- 1 1000 1000 26K 27. Nov 2022  /home/daniel/.local/share/lutris/ui/lutris-window.ui
-rw-r--r-- 1    0    0 26K 16. Jun 16:53 /usr/share/lutris/ui/lutris-window.ui
$ grep games_stack /usr/share/lutris/ui/lutris-window.ui ~/.local/share/lutris/ui/lutris-window.ui
/usr/share/lutris/ui/lutris-window.ui:                      <object class="GtkStack" id="games_stack">
```

Both files do exist, with the system one being new as of the last update, and the local one being older.

I don't remember attempting a local installation, but might have had a development setup at some time.
I assume the solution would thus be to remove the `~/.local/share/lutris` part
Are there any files that are not safe to remove? 
I'd prefer to keep my settings and such.

**Comment by danieljohnson2** [comment]
That's probably what happened.

There's stuff in there you probably want to keep. The ./runners, ./runtime directories, and the ./pga.db file for sure.

I think the ./ui directory should go. So should ./bin, ./media and ./json if present.

**Comment by 4censord** [comment]
Thank you, that did it, it works again.

**Comment by strycore** [comment]
> but might have had a development setup at some time

I started Lutris. At no point in time, I've had the Lutris software merged with it's settings folder. That's pretty wild and a first afaik.

I wish there would something we could do to stop users from doing those things but as I've said, Arch users gonna Arch.

**Comment by danieljohnson2** [comment]
Oh no, I managed to do this same thing. I don't remember exactly how; it was some variation on trying to install Lutris locally instead of system-wide.

Did it on Pop!_OS somehow. It's not an Arch-ism.

**Comment by strycore** [comment]
Oh I don't believe in Arch-isms, a Linux distro is a Linux distro, there are only minor differences about them.
The only Arch-ism I know of is the ability for Arch users to bring everything back to Arch.
