### ISSUE TITLE
Amazon Login Freezes - KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied

### ISSUE THREAD

**Issue by JoshuaFern** [lutris/lutris#4907]
### Bug description

The Amazon Login Freezes, making Lutris impossible to use.

May be related to https://github.com/lutris/lutris/issues/4783

### How to Reproduce

1. Go to Lutris
2. Click on Amazon login button
3. See a frozen window.

### Expected behavior

The Amazon Login Window shouldn't be freezing.

### Log output

```shell
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.3.4-zen1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            7.8 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan Version:  1.3.224
Vulkan Drivers:  NVIDIA GeForce GTX 1060 3GB (1.3.236)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Yeah, I'm pretty sure it's the same issue. 
Try adding the line from this commit https://github.com/lutris/lutris/commit/dc67a15f97baeebb96c6b96c71c107747ca89053 and it should solve it

**Comment by JoshuaFern** [comment]
Thanks, that line fixed it.
