### ISSUE TITLE
Lutris FSR options for Gamescope need updating

### ISSUE THREAD

**Issue by Astrobald** [lutris/lutris#4908]
Gamescope added new options to set upscaler filter: [commit 7a1fe2d](https://github.com/ValveSoftware/gamescope/commit/7a1fe2def38e9c3ed4d12adb9f1bb81b6f9dcbe5)

Here is the modification to the "runner_interpreter.py" file that seems to work for me:

```diff
lutris/runner_interpreter.py: 120

- launch_arguments.insert(0, "-U")
+ launch_arguments.insert(0, "fsr")
+ launch_arguments.insert(0, "-F")
```

I hope it will help

**Comment by danieljohnson2** [comment]
Maybe, but that commit was days ago. There must be a lot of Gamescope installs out there that that require -U, and this change would break them. Is there some way to do this that's more compatible?

**Comment by Astrobald** [comment]
Indeed, and I did not find a solution to play with the stable and beta version of Gamescope. :disappointed:

**Comment by waffleboi9000** [comment]
FYI Nobara has updated to a version of gamescope that requires -F fsr to use FSR upscaling now (specifically 6/27/23) so the FSR options broke.

**Comment by Astrobald** [comment]
Gamescope 3.12.0 has been [released](https://github.com/ValveSoftware/gamescope/releases/tag/3.12.0) in a new stable version :partying_face:

https://repology.org/project/gamescope/versions

**Comment by orowith2os** [comment]
The Lutris Flatpak now utilizes Gamescope 3.12.0, and expect distro packages to update soon.

**Comment by danieljohnson2** [comment]
@strycore, can we get some guidance here?

If we change the new command line options, older gamescopes will break; if not the new one will break. I don't see how to be compatible. When do we cut over?

**Comment by strycore** [comment]
Since gamescope doesn't have a way to display its version:

1. Collect the output of `gamescope --help`
2. If the output contains -F / --filter then use new options, otherwise fallback to legacy options
3. Store which gamescope version is used in the lutris settings so we don't have to re-run gamescope --help
4. Store file size and last modified date of the gamescope binary in the settings as well
5. If gamescope is legacy, compare file size and date when Lutris starts. If size or date changes, re-run `gamescope --help`, back to step 1

**Comment by strycore** [comment]
> expect distro packages to update soon.

I'm sadly expecting a lot of distros like Debian to stick with an old and obsolete version of Gamescope.

**Comment by danieljohnson2** [comment]
Is "gamescope --help" so expensive it's worth caching across Lutris runs?

I'd have thought we could cache this in memory and forget it on shutdown, and that would be good enough.

**Comment by orowith2os** [comment]
> I'm sadly expecting a lot of distros like Debian to stick with an old and obsolete version of Gamescope.

If they ship a new enough version of Lutris that changing the arguments used affects them, this sounds like a very bad and weird setup. I don't see much issue with requiring a newer gamescope.

**Comment by strycore** [comment]
> I'd have thought we could cache this in memory and forget it on shutdown, and that would be good enough.

I guess it's inexpensive enough to run at every start yeah

**Comment by danieljohnson2** [comment]
People upgrade Lutris on their distro, to get onto the currently supported version of it. Maybe would like to not have to upgrade other components to do so.

**Comment by danieljohnson2** [comment]
I'll put something together in this sense, but not tonight.

**Comment by strycore** [comment]
> If they ship a new enough version of Lutris that changing the arguments used affects them, this sounds like a very bad and weird setup. I don't see much issue with requiring a newer gamescope.

But they don't ship newer versions of Lutris either. I've had to stop providing runtime components to older Lutris version to force people to use currently supported versions of Lutris.

**Comment by danieljohnson2** [comment]
OK, OK, I'll get around to this.

I've tried to implement the --help trick, and it seems to work for me. Committed to master.

@Astrobald, if you could grab the latest master and run the 'bin/lutris' script and see if it will do the FSR for you?

If there's anybody around who has and older gamescope, it'd be nice to get a test of that. It should work for that case too with the old -U option.

**Comment by Astrobald** [comment]
Launched from git clone and compiled from the AUR repository.

Everything seems to be working fine!

[lutris-log.txt](https://github.com/lutris/lutris/files/12266697/lutris-log.txt)
