### ISSUE TITLE
launch problem

### ISSUE THREAD

**Issue by justawebsite** [lutris/lutris#4909]
### Bug description

I can't launch lutris.

### How to Reproduce

1.install lutris
2.run lutris
3.error

### Expected behavior

It shoule be started.

### Log output

```shell
(lutris:8061): dbind-WARNING **: 22:18:44.681: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/usr/games/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 36, in <module>
    from lutris.api import parse_installer_url, get_runners
  File "/usr/lib/python3/dist-packages/lutris/api.py", line 14, in <module>
    from lutris.util import http, system
  File "/usr/lib/python3/dist-packages/lutris/util/http.py", line 14, in <module>
    from lutris.util import system
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 582, in <module>
    @lru_cache
  File "/usr/lib/python3.7/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

### System Information

```shell
system: Deepin 20.7
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by justawebsite** [comment]
I have found the Solution.
Change "/usr/lib/python3/dist-packages/lutris/util/system.py", line 582:
` @lru_cache`
to:
` @lru_cache(128)`

**Comment by danieljohnson2** [comment]
No, no, this is a bug. We're supposed to work in Python 3.7. That code needs a fix to do so.

**Comment by justawebsite** [comment]
Thanks. My English is not good.
