### ISSUE TITLE
not enough values to unpack (expexted 3, got 1) error when trying to start games

### ISSUE THREAD

**Issue by 4Gettt25** [lutris/lutris#4915]
### Bug description

Yesterday everything worked fine but today I tried to start Diablo 4 and got the error then I tried other games and the same error occured

### How to Reproduce

1. Go to 'Lutris'
2. Click on 'any game'
3. get the error: not enough values to unpack (expexted 3, got 1)

### Expected behavior

Start the game normally like it always did

### Log output

```shell
ac_compute_device_uuid's output is based on invalid pci bus info.
[2023-06-24 12:04:57.964] [MANGOHUD] [info] [config.cpp:118] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2023-06-24 12:04:57.964] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/felixg/.config/MangoHud/python3.11.conf' >
[2023-06-24 12:04:57.964] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/felixg/.config/MangoHud/MangoHud.conf'
INFO     2023-06-24 12:04:58,285 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-24 12:04:58,286 [startup.check_driver:73]:Running AMD Mesa driver 23.1.2 on AMD Radeon RX 6800 XT (navi21, LL>
INFO     2023-06-24 12:04:58,286 [startup.check_driver:85]:GPU: 1002:73BF 148C:2406 (amdgpu drivers)
ERROR    2023-06-24 12:04:58,287 [startup.check_libs:120]:i386 libgnutls.so.30 missing (needed by gnutls)
ac_compute_device_uuid's output is based on invalid pci bus info.
[2023-06-24 12:04:58.662] [MANGOHUD] [info] [config.cpp:118] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2023-06-24 12:04:58.662] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/felixg/.config/MangoHud/python3.11.conf' >
[2023-06-24 12:04:58.662] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/felixg/.config/MangoHud/MangoHud.conf'
ac_compute_device_uuid's output is based on invalid pci bus info.
[2023-06-24 12:04:59.251] [MANGOHUD] [info] [config.cpp:118] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2023-06-24 12:04:59.251] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/felixg/.config/MangoHud/python3.11.conf' >
[2023-06-24 12:04:59.251] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/felixg/.config/MangoHud/MangoHud.conf'
WARNING  2023-06-24 12:04:59,411 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-06-24 12:04:59,411 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-06-24 12:04:59,411 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
DEBUG    2023-06-24 12:04:59,481 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-24 12:04:59,523 [lutris.get_missing_game_ids:191]:Checking for missing games

(lutris:15274): Gtk-WARNING **: 12:04:59.558: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.Unknown>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.fr>
DEBUG    2023-06-24 12:05:23,499 [services.get_game:17]:Getting service game 775500 for steam
INFO     2023-06-24 12:05:24,303 [runner.use_runtime:440]:Runtime disabled by system configuration
INFO     2023-06-24 12:05:24,317 [runner.use_runtime:440]:Runtime disabled by system configuration
INFO     2023-06-24 12:05:24,320 [runner.use_runtime:440]:Runtime disabled by system configuration
DEBUG    2023-06-24 12:05:24,320 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
ERROR    2023-06-24 12:05:24,323 [exceptions.wrapper:95]:SCARLET NEXUS (steam) has encountered an error: not enough values to >
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 627, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 192, in get_config
    return get_outputs()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 59, in get_outputs
    _, x_pos, y_pos = geometry.split("+")
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)
DEBUG    2023-06-24 12:05:24,323 [application.on_game_stop:679]:Removing 1 from running IDs
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.9-arch1-1
Desktop:         Hyprland
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.9-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.2
Vulkan Version:  1.3.253
Vulkan Drivers:  AMD Radeon RX 6800 XT (1.3.250)
```

### Media (optional)

![swappy-20230624_124523](https://github.com/lutris/lutris/assets/126004052/e33be7f5-f36c-41e4-98ef-257890bf436c)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by devraza** [comment]
I've been having the same issue with every game I've tried to open so far

**Comment by danieljohnson2** [comment]
It's having trouble with the output of the xrandr command.

Could you post the output you get when you run ``xrandr`` at the terminal?

**Comment by devraza** [comment]
```
Screen 0: minimum 16 x 16, current 2560 x 1080, maximum 32767 x 32767
HL X11 1 connected 2560x1080+0+0 (normal left inverted right x axis y axis) 800mm x 340mm
   2560x1080     59.98*+
   1440x1080     59.99
   1400x1050     59.98
   1280x1024     59.89
   1280x960      59.94
   1152x864      59.96
   1024x768      59.92
   800x600       59.86
   640x480       59.38
   320x240       59.52
   1680x1050     59.95
   1440x900      59.89
   1280x800      59.81
   1152x720      59.97
   960x600       59.63
   928x580       59.88
   800x500       59.50
   768x480       59.90
   720x480       59.71
   640x400       59.95
   320x200       58.96
   1920x1080     59.96
   1600x900      59.95
   1368x768      59.88
   1280x720      59.86
   1024x576      59.90
   864x486       59.92
   720x400       59.55
   640x350       59.77
   ```

**Comment by 4Gettt25** [comment]
creen 0: minimum 16 x 16, current 3840 x 1080, maximum 32767 x 32767
HL X11 0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 520mm x 300mm
   1920x1080    143.88*+
   1440x1080    143.80  
   1400x1050    143.89  
   1280x1024    143.79  
   1280x960     143.86  
   1152x864     143.92  
   1024x768     143.87  
   800x600      143.83  
   640x480      143.85  
   320x240      142.05  
   1680x1050    143.88  
   1440x900     143.86  
   1280x800     143.84  
   1152x720     143.77  
   960x600      143.72  
   928x580      143.50  
   800x500      143.68  
   768x480      143.69  
   720x480      143.85  
   640x400      143.37  
   320x200      141.40  
   1600x900     143.93  
   1368x768     143.77  
   1280x720     143.67  
   1024x576     143.91  
   864x486      143.63  
   720x400      143.88  
   640x350      143.57  
HL X11 1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 520mm x 290mm
   1920x1080     59.96*+
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77

**Comment by 4Gettt25** [comment]
my guess is that this has something to do with a hyprland update, because today when I checked xrandr before updating the monitors weren't written down as HL X11 0 and 1.

**Comment by 4Gettt25** [comment]
Yep just looked at hyprland issues and found this. 
https://github.com/hyprwm/Hyprland/issues/2580#issuecomment-1605715232

**Comment by danieljohnson2** [comment]
I see what you mean; the name has spaces in it, but space is the field separator. Lutris thinks the name is HL and the geometry is '1', and that does not parse good.

Lutris will need a clever parser to deal with this. But this seems like a rather antisocial thing for hyprland to do.

**Comment by strycore** [comment]
>  Lutris will need a clever parser to deal with this. But this seems like a rather antisocial thing for hyprland to do.

Spliting the string on `connected` should do the trick

**Comment by 4Gettt25** [comment]
I tried it with the workaround but still get the same error msg but in the terminal it instead now shows that it is unable to load libGLX_nvidia.so.0

2023-06-25 14:02:31,764: Unable to load libGLX_nvidia.so.0
2023-06-25 14:02:31,764: Unable to locate libGLX_nvidia
2023-06-25 14:02:31,799: Diablo IV (wine) has encountered an error: not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 627, in configure_game
    self.original_outputs = DISPLAY_MANAGER.get_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 192, in get_config
    return get_outputs()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 59, in get_outputs
    _, x_pos, y_pos = geometry.split("+")
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by danieljohnson2** [comment]
I'm trying to get some guidance on hyprland repo. If that's no go, I'll split on 'connected'. We'll get this.

That's awfully inelegant though.

**Comment by 4Gettt25** [comment]
ok but I'm still wondering if how xrandr formats the monitor names as HL X11 0 and 1 etc is the wanted behaviour

**Comment by danieljohnson2** [comment]
From the response to the issue linked above, I think they meant to do this, but may reverse the change for the benefit of programs like Lutris that parse xrandr output naively.

Nevertheless, if there's a better way to parse it, we should do that. Nothing wrong with fixing this issue at both ends.

**Comment by danieljohnson2** [comment]
OK, hyprland is switch to hyphens instead of spaces. They have no better ideas, so I'll go with something along to 'split on connected' idea.

**Comment by danieljohnson2** [comment]
OK, I've put it a more sophisticated parse here that looks for 'connected' and starts from there, and also expected the error handling so it will handle this failure if it happens again.

Please try again with the master branch. You need not install it; just download it and run the 'bin/lutris' script within. Should work now.

**Comment by strycore** [comment]
We also need to not crash when xrandr fails to parse.

The data returned by xrandr is totally unimportant

**Comment by danieljohnson2** [comment]
Well, I expanded the scope of  an 'except:' clause so hopefully that will be better now.
