### ISSUE TITLE
sorting by play time is done alphabetically

### ISSUE THREAD

**Issue by FinleyBuhl** [lutris/lutris#4916]
### Bug description

In the games list, when sorting by play time, the play times are sorted in an alphabetical manner

### How to Reproduce

1. Open Lutris
2. click on "play time" in the top of the games list 

### Expected behavior

The values should be sorted by their size, so that 1 hour > 2 minutes

### Log output

```shell
INFO     2023-06-25 14:49:41,801 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-25 14:49:41,802 [startup.check_driver:65]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-06-25 14:49:41,803 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 3070
INFO     2023-06-25 14:49:41,803 [startup.check_driver:85]:GPU: 10DE:2488 1043:882C (nvidia drivers)
DEBUG    2023-06-25 14:49:41,890 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-25 14:49:41,933 [lutris.get_missing_game_ids:191]:Checking for missing games

(lutris:4180683): Gtk-WARNING **: 14:49:41.981: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)

(lutris:4180683): Gtk-CRITICAL **: 14:49:42.003: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.3.6-custom
Desktop:         Hyprland
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.253
Vulkan Drivers:  NVIDIA GeForce RTX 3070 (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hmm. No repro for me. My Lutris 0.5.13 thinks "12 hours" is longer that "5 hours", but alphabetically that would be reversed.

**Comment by strycore** [comment]
> Hmm. No repro for me. My Lutris 0.5.13 thinks "12 hours" is longer that "5 hours", but alphabetically that would be reversed.

Switch to the game list

**Comment by danieljohnson2** [comment]
I think I see it now.

I works if you use the sorting menu in the header bar. But if you click the column header, that's not so good.

**Comment by strycore** [comment]
On my end, starting Lutris in list mode with games sorted by playtime results in a messed up order.

Clicking on playtime  in the header fixes the order

Changing the sort order from the menu does not do anything at all.

**Comment by danieljohnson2** [comment]
I'm not see consistent behavior. But I see that once you click the header, the menu stops working.

I think the model is re-sorting the games and this eliminates the menu's sort.

**Comment by strycore** [comment]
Yeah, we seem to have 2 sorting mechanisms fighting with each other.

**Comment by danieljohnson2** [comment]
No, I don't think so. We have *three* somehow.

Once it gets into the broken state, it's not calling the 'sort_func' - I never hit a breakpoint there. It's sorting some other way.

Switching away from Game view and back re-sorts via the LutrisWindow sort code, which works. But the header bar continues to mis-sort if you click it. The tree view is messed up somehow, maybe.

**Comment by danieljohnson2** [comment]
I think I got it. The sort_func is set up on the *model* not the tree view, so if we generate a new model we need to re-do that setup. I've committed a fix that should work.

@FinleyBuhl - could you download the master branch and run the 'bin/lutris' script within; I think it should now sort better for you.

This bug is a consequence of the fix for the missing scrollbars- we no longer re-create the views if we can possibly avoid it, but that means the model init code does not run again when it needs to. Oops.
