### ISSUE TITLE
Lutris fails to start, theme parsing error

### ISSUE THREAD

**Issue by romanyacik** [lutris/lutris#4918]
### Bug description

Packaged version of Lutris (0.5.12-1) fails to launch on Ubuntu Lunar. error message when run in a terminal points to a gtk theme parsing error
```
(lutris:24714): Gtk-WARNING **: 16:20:06.203: Theme parsing error: gtk-contained.css:2871:228: Missing closing bracket for :not()
Failed to register: Timeout was reached
```

### How to Reproduce

1. attempted to launch Lutris from menu icon. Fails
2. attempted to launch Lutris from terminal. Fails, with above error
3. purged and reinstalled Lutris using apt
4. repeated steps one and two. problem presists

### Expected behavior

lutris should start normally

### Log output

```shell
same error as above
```

### System Information

```shell
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.8
Kernel Version: 6.3.9-x64v3-xanmod1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3050/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550M DS3H
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Lutris 0.5.12 is not the current version. We released 0.5.13.
Also, the error is `Failed to register: Timeout was reached`, not the warning about the theme.

**Comment by danieljohnson2** [comment]
That's not enough of the long log to see much. No idea what failed to register.

Lutris does not give me any such error in my Ubuntu 23.04 VM. And we didn't use the :not() style thingy in 0.5.12; we do in 0.5.13 though. Still, this seems like a cosmetic issue only. I suspect the timeout isn't related.

You could try 0.5.13 and see if that is any different, at least.

**Comment by strycore** [comment]
> You could try 0.5.13 and see if that is any different, at least.

It's not even a question of trying. All users MUST upgrade to the latest version if they want to receive support.

**Comment by romanyacik** [comment]
problem did not persist after reboot
