### ISSUE TITLE
Ability to define DXVK version in install scripts

### ISSUE THREAD

**Issue by Matt-Swift** [lutris/lutris#4919]
Hi,

With the jump of default DXVK version from V1.10.3 to V2, this has caused some install scripts to not work unless users manually change their DXVK version to V1.10.3, since V2 has regressions for certain Wine games.

The `dxvk` command currently only allows DXVK to be enabled or disabled, but being able to define a specific version would allow certain games to become true one-click installs, as many users unfortunately don't read technical notes or give up at the first issue.

Thank you for Lutris!

**Comment by strycore** [comment]
We don't do that sort of manual adjustment in Lutris, if some special version of DXVK has to be selected for some given hardware, Lutris should be able to figure it out by itself.
Letting users manage this themselves opens the doors to a support nightmare.

**Comment by danieljohnson2** [comment]
This is confusing. Lutris does admit user's manually setting the DXVK version, and would be much less useful if users  could not configure things like that. But @Zynetic seems to want installers to do it for the user.

But... can't an installer configure this via the "dxvk_version" version option, just like any other options? What's missing here?
