### ISSUE TITLE
Lutris on EPEL8

### ISSUE THREAD

**Issue by farchord** [lutris/lutris#4925]
Hello, I am the co-maintainer for Lutris on Fedora, as well as on EPEL8 and EPEL9.

Because of the new python requirement of recent Lutris version, it became extremely difficult/impossible to maintain support for Lutris on EPEL8, so Lutris on EPEL8 has been retired. Could you please remove that platform from the website?

Reason: Python version in EL 8 is 3.6 by default, and lutris requires version 3.7 as a bare minimum. There are some Python 3.8+ packages in EPEL but libraries needed by lutris (OR at least some of them) are missing.

Support on EPEL9 is still ongoing.

Thanks!

**Comment by danieljohnson2** [comment]
Well, recent as in 0.5.10, released April 2022. But should not this issue be in the [website repo](https://github.com/lutris/website)?

And what version of Python does EPEL9 support? We recently had a bug that broke Lutris on 3.7 (#4909). That's in 0.5.13, fixed in master. This means 0.5.13 really needs Python 3.8 because of this, sadly.

**Comment by farchord** [comment]
> Well, recent as in 0.5.10, released April 2022. But should not this issue be in the [website repo](https://github.com/lutris/website)?
> 
> And what version of Python does EPEL9 support? We recently had a bug that broke Lutris on 3.7 (#4909). That's in 0.5.13, fixed in master. This means 0.5.13 really needs Python 3.8 because of this, sadly.

By default, 3.9 is the default pointer. Though they do say 3.11 is available, I don't know how many libraries are available for it.

And I thought maybe the website repo was about something else, not the raw html files, should I reopen this issue there?

**Comment by danieljohnson2** [comment]
I think you should do that.

**Comment by strycore** [comment]
> recent as in 0.5.10

It should be noted that anything older than 0.5.11 is fully unsupported. We aren't delivering needed runtime components to old versions of Lutris anymore.

I'll update the website to remove EPEL8

**Comment by farchord** [comment]
> > recent as in 0.5.10
> 
> It should be noted that anything older than 0.5.11 is fully unsupported. We aren't delivering needed runtime components to old versions of Lutris anymore.
> 
> I'll update the website to remove EPEL8

Thanks! And i figured to be honest. Anyway I kinda doubt many people game on epel8.
