### ISSUE TITLE
Unexpected error while installing battle.net

### ISSUE THREAD

**Issue by XxRiKxX** [lutris/lutris#4928]
I read the docs, and I dont have any aur fonts installed. The only font I installed was jetbrains nerd from official arch repo. I also tried deleting the .wine directory. I have all the driver installed as mentioned in the docs.

**Comment by strycore** [comment]
> I dont have any aur fonts installed.

I don't know what AUR fonts are, I have installed Battle.net countless times without.

>  tried deleting the .wine directory.

Lutris does not interfere with the .wine directory

**Comment by XxRiKxX** [comment]
arch user repository AUR. it was mentioned in the docs that some bad fonts from aur can cause this issue. but I dont have any installed from there

**Comment by strycore** [comment]
this was likely related to the issues with fonts in Winetricks, which we fixed.
