### ISSUE TITLE
[Feature Request] Enhance the Hardware Information

### ISSUE THREAD

**Issue by Mannshoch** [lutris/lutris#4930]
### Bug description

I'm new on Lutris. I already used Win but I'm overwhelmed with all of these settings.
DXVK/VKD3D/dgvoodoo2/CSMT/VAAPI/DXVA2

### How to Reproduce

I tried to  inform me, but Im not able to find Proper Information about:

- the use cases where something is needed
- How I find If an application could use one of these (e.g. The Sims3)
- If my old Hardware is able to use it 
(e.g. AMD Turks PRO [Radeon HD 6570/7570/8550 / R5 230])
- If my Ubuntu Linux 23.04 has the software installed and Proper configured.
According to (https://github.com/lutris/docs/blob/master/WineDependencies.md)

### Expected behavior

I'm sure I'm not able to address all cases with my request, but It would help to get a proper overview.
Please enhance the Hardware Information tab and add this Information:

- [ ] Installed and missing Software and driver
- [ ] **allow to adjust the setting of a Game according to that results.** 
- [ ] **suppress not installed/not capable starter settings or specific Version**
- [ ] May add several Links to a Wiki or how-to
e.g. https://github.com/lutris/docs/blob/master/WineDependencies.md
- [ ] add a Link to the Hardware Information on the Starter settings tab.
- [ ] add a Wizard to preset all available Wine Starter to work with a new hardware environment.

### Log output

```shell
INFO     2023-07-13 13:33:55,643 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-07-13 13:33:55,748 [startup.check_driver:65]:Running Mesa Mesa driver 23.0.4 on AMD TURKS (DRM 2.50.0 / 6.2.0-24-generic, LLVM 15.0.7) (0x6759)
INFO     2023-07-13 13:33:55,748 [startup.check_driver:77]:GPU: 1002:6759 103C:3130 (radeon drivers)
DEBUG    2023-07-13 13:33:55,941 [lutriswindow.update_store:448]:Showing 7 games
INFO     2023-07-13 13:33:55,954 [startup.update_runtimes:218]:Startup complete
ERROR    2023-07-13 13:33:59,025 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-07-13 13:33:59,025 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-07-13 13:33:59,121 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-07-13 13:33:59,121 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-07-13 13:33:59,121 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/USER/Game/TheSims3/drive_c/Programme/Electronic Arts/Die Sims 3/Game/Bin"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:SDL_VIDEO_FULLSCREEN_DISPLAY="1"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:LD_LIBRARY_PATH="/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/lib:/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib32:/lib:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/USER/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/USER/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/USER/.local/share/lutris/runtime/steam/i386/lib:/home/USER/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/USER/.local/share/lutris/runtime/steam/i386/usr/lib:/home/USER/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/USER/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/USER/.local/share/lutris/runtime/steam/amd64/lib:/home/USER/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/USER/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:WINEARCH="win32"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:WINE="/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/bin/wine"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:WINE_MONO_CACHE_DIR="/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/mono"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/gecko"
DEBUG    2023-07-13 13:33:59,122 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/lib64/gstreamer-1.0/:/home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:WINEPREFIX="/home/USER/Game/TheSims3"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:WINEESYNC="0"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:WINEFSYNC="0"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:game_name="Die Sims 3"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/local/lib/python3.11/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.11/dist-packages"
DEBUG    2023-07-13 13:33:59,123 [command.start:141]:LUTRIS_GAME_UUID="e4b98b44-5983-4eab-95e2-ecf1b932ff71"
Discord ID: None
INFO     2023-07-13 13:33:59,151 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
Started initial process 26269 from gamemoderun /home/USER/.local/share/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/bin/wine /home/USER/Game/TheSims3/drive_c/Programme/Electronic Arts/Die Sims 3/Game/Bin/TS3W.exe
Start monitoring process.
gamemodeauto: 
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
terminate called after throwing an instance of 'dxvk::DxvkError'
wine client error:10c: write: Ungültiger Dateideskriptor
Monitored process exited.
Initial process has exited (return code: 768)
Exit with return code 768
DEBUG    2023-07-13 13:34:00,909 [command.on_stop:195]:Process 26267 has terminated with code 768
DEBUG    2023-07-13 13:34:01,153 [game.beat:693]:Game thread stopped
WARNING  2023-07-13 13:34:01,153 [game.on_game_quit:730]:Game still running (state: running)
INFO     2023-07-13 13:34:01,154 [game.stop:704]:Stopping Die Sims 3 (wine)
DEBUG    2023-07-13 13:34:01,154 [game.stop_game:664]:Die Sims 3 (wine) has run for 2 seconds
WARNING  2023-07-13 13:34:01,154 [game.stop_game:666]:The game has run for a very short time, did it crash?
DEBUG    2023-07-13 13:34:01,178 [game.on_game_quit:748]:Die Sims 3 stopped at Do, 13 Jul 2023 13:34:01
DEBUG    2023-07-13 13:34:01,178 [game.save:299]:Saving Die Sims 3 (wine) with config ID die-sims-3-1678196213
INFO     2023-07-13 13:34:03,553 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Ubuntu 23.04 Lunar Lobster
Arch:            x86_64
Kernel:          6.2.0-24-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.2 GB
Swap:            18.2 GB

[Graphics]
Vendor:          Mesa
OpenGL Renderer: AMD TURKS (DRM 2.50.0 / 6.2.0-24-generic, LLVM 15.0.7)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~23.04.1
OpenGL Core:     4.5 (Core Profile) Mesa 23.0.4-0ubuntu1~23.04.1
OpenGL ES:       OpenGL ES 3.1 Mesa 23.0.4-0ubuntu1~23.04.1
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
DXVK: Translate DirectX 9,10 and 11 to Vulkan
VKD3D: Translate DirectX 12 to Vulkan
dgvoodoo2: Translate 3DFX Glide to DirectX 11
CSMT: Old Wine Staging setting, no longer needed
VAAPI: Open source hardware video decoding, doesn't apply to Lutris, more an OBS thing
DXVA2: Microsoft hardware video decoding, same, doesn't apply to Lutris

The Radeon R5 230 seems to support Vulkan 1.2. You might have to downgrade the version of DXVK since recent versions expect Vulkan 1.3. In the game configuration, select DXVK 1.10 and this should be enough to play The Sims 3. 
Since this is pretty old hardware, the experience might not be as smooth as on Windows since DXVK has some RAM and VRAM overhead. 
From what I see in your logs, downgrading DXVK should be the only step needed.

**Comment by strycore** [comment]
I was mistaken, I looked up your PCI Id and you have the Radeon HD 6570.
The Radeon HD 6000 series do not support Vulkan at all (https://en.wikipedia.org/wiki/Radeon_HD_6000_series)

You will have to disable DXVK and hope the game runs well with Wine's OpenGL based translator. The Sims 3 should run, I've played it on Linux when DXVK or Vulkan weren't around.

**Comment by Mannshoch** [comment]
Thanks @strycore for your help here.
Yes this [Graphic card](https://linux-hardware.org/?id=pci:1002-6759-1002-0000) is really old.
As you see it's difficult here to get configurations correct.
I was not sure how to read [vulkaninfo](https://pastebin.com/T7SabE2w)
I assumed Vulkan is available and so I'm not able to set-up settings correct.

Without DXVK "The Sims" is starting but [crash while loading](https://pastebin.com/Vn9fJjrc).

**Comment by strycore** [comment]
Lutris 0.5.15 will show much simpler system information: 
![image](https://github.com/lutris/lutris/assets/280336/0dd7171f-03fc-44d7-bae7-c4830e991186)

**Comment by danieljohnson2** [comment]
I've added clipboard support for the features list, but using \t like this to line up the text won't work unless you use a monospaced font. It's not lining up for me as is, though "System Information" does line up for me.. and not for you.

The "System Information" uses use a monospaced font, and you can use "<tt>...</tt>" for this in your markup. But I bet that won't work for you, since it did not work in "System Information".

Get me a little time and I'll rework this stuff with widgets for layout, and then we can have proportional spacing everywhere, and neat line ups for everyone.

**Comment by danieljohnson2** [comment]
OK, PR #5199 is my 'lines everything up with no tabs' effort that should work with proportional fonts. I hope you like it.
