### ISSUE TITLE
No Tray Icon on Wayland

### ISSUE THREAD

**Issue by lfom** [lutris/lutris#4934]
### Bug description

When using Wayland on Gnome, the option _Show Tray Icon_ does not work. The tray icon is visible when a XOrg session is used or on Wayland if the environment variable `GDK_BACKEND=x11` is used. I have searched for "tray icon" and the related error but I did not find any related issue.

### How to Reproduce

1. Login using a Wayland session instead of XOrg
2. Open Lutris, go to Preferences > Interface and enable Show Tray Icon
3. You may want to close Lutris and start it again to make sure it is using the tray icon
4. No tray icon is show

### Expected behavior

Tray icon should be visible in both XOrg and Wayland sessions (PS: in order to show tray icons on Gnome, an extension like Ubuntu AppIndicators must be installed and enabled).

### Log output

```shell
INFO     2023-07-18 12:26:19,781 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-18 12:26:19,791 [startup.check_driver:73]:Running Intel Mesa driver 23.0.4 on Mesa Intel(R) HD Graphics (CHV) (0x22b0)
INFO     2023-07-18 12:26:19,793 [startup.check_driver:85]:GPU: 8086:22B0 17AA:38E3 (i915 drivers)
WARNING  2023-07-18 12:26:20,033 [startup.check_vulkan:157]:Vulkan reports that the 'Intel(R) HD Graphics (CHV)' device has API version of 1.2.238. 1.3.0 is required for the latest DXVK.

(lutris:7623): Gtk-CRITICAL **: 12:26:20.067: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
DEBUG    2023-07-18 12:26:20,967 [lutris.get_missing_game_ids:191]:Checking for missing games
INFO     2023-07-18 12:26:23,728 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Ubuntu 23.04 Lunar Lobster
Arch:            x86_64
Kernel:          6.3.12-x64v2-xanmod1
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             3.7 GB
Swap:            4.5 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics (CHV)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~23.04.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~23.04.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1~23.04.1
Vulkan Version:  1.3.239
Vulkan Drivers:  Intel(R) HD Graphics (CHV) (1.2.238)
```

### Media (optional)

N/A

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hmm. For me, the tray icon does show in Wayland, but only the AppIndicator code is used, not the Gtk.StatusIcon implementation. I believe Gtk.StatusIcon is deprecated and maybe it won't ever support Wayland.

Lutris does not depend on the package for AppIndicator support, so maybe you do not have it. It should be something like 'gir1.2-appindicator3-0.1'. Perhaps if you install this it will work?

Not sure what Lutris should do here, if I am right. The current strategy is to just call back on Gtk.StatusIcon if required, but that seems less than Wayland friendly. Maybe we should add a dependency?

**Comment by lfom** [comment]
> Lutris does not depend on the package for AppIndicator support, so maybe you do not have it. It should be something like 'gir1.2-appindicator3-0.1'. Perhaps if you install this it will work?

Hey, thank you for your reply. Indeed my installation was missing `gir1.2-appindicator3-0.1`, and after installing it the tray icon started to work even on Waylan. I did not think of that since it was working on XOrg. Then probably it is a good idea to add is as a recommeneded package, at least.

So it does not seem to be a bug, please feel free to close this issue if it is not needed anymore.

Regards

**Comment by QmwJlHuSg9pa** [comment]
FWIW, I'm having this issue with Lutris (v0.5.13, Flatpak) on Fedora 37 Silverblue.

The following comment may be of interest? https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/283#issuecomment-1575514084

**Comment by TriMoon** [comment]
FYI: i don't see the icon in the notification area either when it has started an app...
For example i start Wargaming Game Center and only see the icon of WGC in the tray but not lutris'es.
Maybe that's what the OP also encounters?

**Comment by strycore** [comment]
On Gnome, you need an extension to see tray icons. And even then, they don't work perfectly in the case of Wine programs.
