### ISSUE TITLE
[Feature Request] Ability to specify Wine version when Installing Games

### ISSUE THREAD

**Issue by kekkoudesu** [lutris/lutris#4936]
Right now, it seems every Installer Preset goes out and fetches version 6.14 of Lutris Fshack. This works well for many games, but sometimes, I would like to use a newer version of Wine, like my system Wine-Staging version. 

For example, since Wine 7.10, a major bug was fixed for the Sonohana games: https://bugs.winehq.org/show_bug.cgi?id=10767

This feature would seem to be in line with the rationale in this doc: https://github.com/lutris/docs/blob/master/WineDependencies.md

> Although Lutris provides and uses its own Wine builds, we still recommend you install all of Wine's dependencies to ensure a working experience.

**Comment by danieljohnson2** [comment]
You should be able to specify the default version of WINE in the WINE runner preferences, and that should apply to installers.

Have you tried that?

**Comment by kekkoudesu** [comment]
> You should be able to specify the default version of WINE in the WINE runner preferences, and that should apply to installers.
> 
> Have you tried that?

This seems to work well, thanks!
