### ISSUE TITLE
[Improvement] Winetricks auto-update

### ISSUE THREAD

**Issue by TriMoon** [lutris/lutris#4937]
### Bug description

Lutris seems to use the `winetricks` from `~/.local/share/lutris/runtime/winetricks/winetricks` which is not being updated.
This leads to usage of outdated `winetricks` when installing games...
I noticed this because I have `winetricks` installed system-wide using the [git version](https://github.com/Winetricks/winetricks) with auto-update systemd-units.

So either check if there is a system-wide version of winetricks available and use that instead, or auto-update the version inside the runtime dir...

### How to Reproduce

1. Install any game making use of `winetricks`.
2. Check for the log messages while installing about outdated version of `winetricks`

### Expected behavior

Lutris should use the `winetricks` that's already available in the user's environment.

### Log output

```shell
none needed
```

### System Information

```shell
[System]
OS:              Ubuntu 23.04 Lunar Lobster
Arch:            x86_64
Kernel:          6.2.0-25-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.2 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.239
Vulkan Drivers:  NVIDIA GeForce GTX 1080 Ti (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by TriMoon** [comment]
Work-around for people until patched:
```
cd ~/.local/share/lutris/runtime/winetricks
./winetricks --self-update
```

**Comment by danieljohnson2** [comment]
There is a 'Use System Winetricks' option in the game configuration; it's an "Advanced" option so you need to activate those.

Perhaps that will do what you want?

**Comment by strycore** [comment]
winetricks gets updated when lutris admins push an update.
