### ISSUE TITLE
feature: automatically fill working directory when select a local executable

### ISSUE THREAD

**Issue by ryuukk** [lutris/lutris#4938]
### Bug description

When selecting a local executable, i have to copy/paste the path and then stripe the exe name to get the working directory

This is a rather annoying process that should not be needed

Lutris should do that for me

### How to Reproduce

1. Add new game locally
2. Select an executable
3. Notice working directory is empty

### Expected behavior

Working directory should be set automatically to the folder of the selected executable

### Log output

```shell
n/a
```

### System Information

```shell
n/a
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/44361234/1a7fb029-8722-4659-b0b8-d4685c0b190f)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Lutris will pick a working area for you, if the working area box is left blank. What you suggest is what it does for the Linux and Wine runners.

It does the WINE Prefix too- the warning you are seeing is too aggressive, but is fixed in the master.

I think we have this reasonable well covered.
