### ISSUE TITLE
Diablo 4 now showing on the Battle.net integration

### ISSUE THREAD

**Issue by Serph91P** [lutris/lutris#4944]
### Bug description

Diablo 4 not showing on the battle.net integration. Found this pull request which should add it?
https://github.com/lutris/lutris/pull/4895

I have lutris-git installed.

### How to Reproduce

1. Add the Battle.net integration
2. Install Battle.net
3. Close
4. Start
5. Login
6. Close again
7. See what lutris shows what games are available

### Expected behavior

Show Diablo 4

### Log output

```shell
$ lutris -d

(lutris:22369): Gtk-WARNING **: 10:54:37.197: Theme directory actions/16-Dark of theme Zafiro-Nord-Dark-Grey has no size field

/usr/lib/python3.11/site-packages/lutris/gui/widgets/cellrenderers.py:7: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Gtk, Pango, PangoCairo
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.4.4-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (gfx1100, LLVM 15.0.7, DRM 3.52, 6.4.4-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.3
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 7900 XTX (RADV GFX1100) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by JulienDlq** [comment]
I can confirm the fix works, thanks! :+1:

**Comment by strycore** [comment]
I can confirm too 
![image](https://github.com/lutris/lutris/assets/280336/fa625461-6bed-4a64-b4b7-327d96e6e0c6)

Make sure to refresh the Battle.net library after updating to a compatible version of Lutris.
