### ISSUE TITLE
Lutris 0.5.13 - cover games missing

### ISSUE THREAD

**Issue by groenator** [lutris/lutris#4947]
### Bug description

I have installed lutris version 0.5.13 on my Tuxedo OS, which is a Kubuntu flavour. 

When I start lutris, none of my accounts or games have covers. 

### How to Reproduce

1. Install lutris V 0.5.13 via apt.
2. Open Lutris and log in. 
3. Select Lutris account, all games in my library don't have a cover. 

### Expected behaviour

I am expecting all my games to have a cover. 

### Log output

```shell
I am currently downloading a game, once that's done I will add logs too.
```

### System Information

```shell
[System]
OS:              TUXEDO OS 22.04 jammy
Arch:            x86_64
Kernel:          6.2.0-10014-tuxedo
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           13th Gen Intel(R) Core(TM) i9-13900HX
Physical cores:  24
Logical cores:   32

[Memory]
RAM:             31.1 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4070 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.204
Vulkan Drivers:  Intel(R) Graphics (RPL-S) (1.3.246), NVIDIA GeForce RTX 4070 Laptop GPU (1.3.242)
```

### Media (optional)

![Screenshot_20230723_201021](https://github.com/lutris/lutris/assets/5445030/955be703-125a-42e4-9112-c7d191423ad1)
![Screenshot_20230723_201107](https://github.com/lutris/lutris/assets/5445030/7ece2eb5-d17f-4bf0-b621-c0ced27a3133)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I bet the logs will show that this is #4857 again.

It's a missing dependency. You need to install the package python3-gi-cairo. The dependency has been added in master.

**Comment by groenator** [comment]
let me try out, thank you!

**Comment by groenator** [comment]
It worked. I installed the dependency and the images are showing as expected. 

Thank you!

![Screenshot_20230723_202041](https://github.com/lutris/lutris/assets/5445030/d9e8ca61-c53c-464f-81b0-4a923466d25d)

**Comment by strycore** [comment]
ok, cool, but someone tell me how you managed to select both "Recent" and "Ubisoft" at the same time on the sidebar.
