### ISSUE TITLE
Selected Wine version is not honored if that is not listed on lutris repositories

### ISSUE THREAD

**Issue by mmbossoni** [lutris/lutris#4950]
### Bug description

I currently installed lutris-GE-Proton8-12-x86_64 through protonup-qt
After that I set the wine runner version as lutris-GE-Proton8-12-x86_64
Next, I created a new manual configuration, set prefix and clicked on winetricks.
Instead of lutris using lutris-GE-Proton8-12-x86_64, it used my system wine.
Quick peek at the code seems like lutris ignore any wine version that is not on their API listing and just use the default (although I didn't dig enough)

### How to Reproduce

1. Install a very new wine-ge that is not registered on lutris yet
2. Set it as wine runner selected
3. Create a new manual entry and set prefix path and game name
4. Try to run winetricks

### Expected behavior

Lutris use my selected wine

### Log output

```shell
WARNING  2023-07-24 18:02:05,723 [wine.prelaunch:921]:No valid prefix detected in /mnt/dados/marcelo/games/lutris/sc, creating one...
ERROR    2023-07-24 18:02:05,723 [wine.detect_prefix_arch:79]:Prefix not found: /mnt/dados/marcelo/games/lutris/sc
INFO     2023-07-24 18:02:05,724 [wine.create_prefix:98]:Creating a win64 prefix in /mnt/dados/marcelo/games/lutris/sc
DEBUG    2023-07-24 18:02:05,724 [system.execute:74]:Executing /opt/wine-staging/bin/wineboot
DEBUG    2023-07-24 18:02:05,724 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/mnt/dados/marcelo/games/lutris/sc WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/opt/wine-staging/mono WINE_GECKO_CACHE_DIR=/opt/wine-staging/gecko
```
```shell
cat /home/marcelo/.config/lutris/runners/wine.yml
system:
  game_path: /mnt/dados/marcelo/games/lutris
wine:
  version: lutris-GE-Proton8-12-x86_64

```

### System Information

```shell
[System]
OS:              Nobara Linux 38 KDE Plasma
Arch:            x86_64
Kernel:          6.3.12-204.fsync.fc38.x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            16.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.86.05
OpenGL Core:     4.6.0 NVIDIA 535.86.05
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.86.05
Vulkan Version:  1.3.240
Vulkan Drivers:  NVIDIA GeForce GTX 1070 (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by mmbossoni** [comment]
![image](https://github.com/lutris/lutris/assets/7592175/496e3eca-c8f9-4545-abee-dda84de41cce)

**Comment by danieljohnson2** [comment]
That's not quite what's wrong. There's special code to find the Wine version so that some odd behaviors can happen during installation if you have not set any version.

But it's not quite working for Winetricks, and is ignoring the version you set.

I've tried again with this code, and hopefully the latest master will fix the problem for you. Try downloading it, and run the 'bin/lutris' script within. I hope Winetricks will use the version of Wine you have selected.

**Comment by mmbossoni** [comment]
@danieljohnson2 , still not fully fixed.
I checked out latest version and ran ./bin/lutris, renamed my wine-ge to 8-15 and set as default for wine runner

```2023-07-28 16:21:51,378: Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7fbcf6f8fec0 (LutrisWindow at 0x55d725e3bbb0)>}
2023-07-28 16:21:56,089: GET https://lutris.net/api/games?search=sc&with-installers=True
2023-07-28 16:22:14,657: GET https://lutris.net/api/games?search=citizen&with-installers=True



2023-07-28 16:22:23,032: Fetching installer https://lutris.net/api/installers/star-citizen
2023-07-28 16:22:23,032: GET https://lutris.net/api/installers/star-citizen
2023-07-28 16:22:23,454: Showing window InstallerWindowstar-citizen
2023-07-28 16:22:23,454: Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x7fbcf6f8fec0 (LutrisWindow at 0x55d725e3bbb0)>}
2023-07-28 16:22:26,319: Retrieving video modes from XrandR

2023-07-28 16:22:33,970: Failed to get default wine version (got {})
2023-07-28 16:22:43,450: ⬇ https://install.robertsspaceindustries.com/star-citizen/RSI-Setup-1.6.6.exe
2023-07-28 16:22:43,453: ⬇ https://gist.githubusercontent.com/GloriousEggroll/289ff1051743c6f89e4b1189f5da5ea8/raw/88ec1898f3d31df60d17125e609f9671db9cf749/sc-prelaunch.sh
2023-07-28 16:22:43,710: Finished downloading https://gist.githubusercontent.com/GloriousEggroll/289ff1051743c6f89e4b1189f5da5ea8/raw/88ec1898f3d31df60d17125e609f9671db9cf749/sc-prelaunch.sh
2023-07-28 16:22:43,954: Download completed
2023-07-28 16:22:43,955: prelaunch is available
2023-07-28 16:22:49,443: Finished downloading https://install.robertsspaceindustries.com/star-citizen/RSI-Setup-1.6.6.exe
2023-07-28 16:22:49,457: Download completed
2023-07-28 16:22:49,457: client is available
2023-07-28 16:22:49,457: All files available
2023-07-28 16:22:49,457: All files are available, continuing install
2023-07-28 16:22:49,458: Creating destination path /mnt/dados/marcelo/games/lutris/star-citizen
2023-07-28 16:22:49,458: Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
2023-07-28 16:22:49,459: Creating a win64 prefix in /mnt/dados/marcelo/games/lutris/star-citizen
2023-07-28 16:22:49,460: Executing /opt/wine-staging/bin/wineboot
2023-07-28 16:22:49,460: WINEARCH=win64 WINEPREFIX=/mnt/dados/marcelo/games/lutris/star-citizen WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/opt/wine-staging/mono WINE_GECKO_CACHE_DIR=/opt/wine-staging/gecko
```

**Comment by danieljohnson2** [comment]
Hmm. Worked on my machine :tm:.

I see something. Could you copy /opt/wine-staging/bin/wine to ~/.local/share/lutris/runners/wine and try to use it from there? If that makes it work that'll be a big clue.

**Comment by mmbossoni** [comment]
Could you be a bit more specific on this?
do you want me to drop the wine binary into ~/.local/share/lutris/runners/wine/ or 
to replace the runner's wine with the wine binary from /opt or
to fully copy the wine from /opt into runners and call it something else like wine-opt?

**Comment by danieljohnson2** [comment]
The later- copy the whole wine directory and give the directory a fetching new name.

Let's see if that copy works.

**Comment by mmbossoni** [comment]
ok, I think I know what I did "wrong"
The winetricks from a new manual game is working fine. (so this bug is indeed fixed)

The bug I'm having now is with running a install script from lutris.net (star citizen to be more precise).
Apparently the first step is not respecting the wine I've chosen, but rather using the default wine.

The "create prefix" step of the installer is using the default

**Comment by danieljohnson2** [comment]
OK, I see it. The version handling is all over the place, and I now know that installers have special magic to download new WINEs.

But I have added a  additional check so that if you have explicitly set the runner-level WINE version, that will be used for installer scripts that do not have their own version set.

Give that a try.

**Comment by mmbossoni** [comment]
Even though it detects custom wine as the one to be used, the create prefix step still uses the default
```INFO     2023-07-28 20:07:38,994 [api.get_default_runner_version:109]:Getting runner information for wine (version: lutris-GE-Proton8-12-x86_64)
DEBUG    2023-07-28 20:07:38,994 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2023-07-28 20:07:39,638 [interpreter.get_runners_to_install:272]:Failed to get default wine version (got {})
INFO     2023-07-28 20:07:46,860 [installerwindow.on_files_available:633]:All files are available, continuing install
DEBUG    2023-07-28 20:07:46,861 [interpreter.create_game_folder:213]:Creating destination path /mnt/dados/marcelo/games/lutris/star-citizen
DEBUG    2023-07-28 20:07:46,861 [interpreter._iter_commands:355]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-07-28 20:07:46,862 [wine.create_prefix:98]:Creating a win64 prefix in /mnt/dados/marcelo/games/lutris/star-citizen
DEBUG    2023-07-28 20:07:46,862 [system.execute:74]:Executing /opt/wine-staging/bin/wineboot
DEBUG    2023-07-28 20:07:46,862 [system.execute:80]:WINEARCH=win64 WINEPREFIX=/mnt/dados/marcelo/games/lutris/star-citizen WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/opt/wine-staging/mono WINE_GECKO_CACHE_DIR=/opt/wine-staging/gecko
```

**Comment by danieljohnson2** [comment]
Nertz. It works for me, even for a Wine that's not in the Lutris directories, and I can't see why it doesn't work for you.

Could you try to install some other Wine game? Maybe there's something different about Star Citizen.

**Comment by mmbossoni** [comment]
Tried [shantae and pirate's curse  installer](https://lutris.net/games/install/16604/view) and it worked. So apparently something strange with star citizen installer

**Comment by danieljohnson2** [comment]
I had suspected that it might be the explicit create_prefix in there, but I guess that's not it after all. Hmmm.

**Comment by danieljohnson2** [comment]
The default arch should be win64 on a 64-bit Linux, so that should not make any difference. In theory.
