### ISSUE TITLE
Icon discrepancy

### ISSUE THREAD

**Issue by Tylerwbrown** [lutris/lutris#4953]
### Bug description

I'm on Manjaro Linux, running Lutris 0.5.13, and steam is successfully integrated into Lutris (the games I currently have installed show up in `Sources > Steam`, as well as not installed but owned games). The issue is that in the `Runners > Steam` and by extension `Library > Games`, the icons/banners aren't showing.

Here are the game banners showing correctly:
![image](https://github.com/lutris/lutris/assets/5498594/f5fc292f-10e2-4aa8-9357-8669fd97ac19)
and here they are missing:
![image](https://github.com/lutris/lutris/assets/5498594/5e6140a9-eeac-4393-b40b-cd57d12a3683)

Only the steam ones are missing.

### How to Reproduce

Load steam games from sources, check games in library and icons should be there but aren't.

### Expected behavior

The icons/banners to be consistent across sources & library

### Log output

```shell
❯ lutris -d
INFO     2023-07-27 14:55:49,388 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-27 14:55:49,389 [startup.check_driver:65]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-07-27 14:55:49,389 [startup.check_driver:69]:GPU: NVIDIA GeForce RTX 3080
INFO     2023-07-27 14:55:49,389 [startup.check_driver:85]:GPU: 10DE:2206 1462:3896 (nvidia drivers)
DEBUG    2023-07-27 14:55:49,524 [lutris.get_missing_game_ids:191]:Checking for missing games
```

### System Information

```shell
[System]
OS:              Manjaro Linux 23.0.0 UltimaThule
Arch:            x86_64
Kernel:          5.15.120-1-MANJARO
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.255
Vulkan Drivers:  NVIDIA GeForce RTX 3080 (1.3.242)
```

### Media (optional)

Here are the game banners showing correctly:
![image](https://github.com/lutris/lutris/assets/5498594/f5fc292f-10e2-4aa8-9357-8669fd97ac19)
and here they are missing:
![image](https://github.com/lutris/lutris/assets/5498594/5e6140a9-eeac-4393-b40b-cd57d12a3683)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
What's going on is that 'Games' uses Lutris.net media, but the Steam view (or other sources) use media from those sources. They are different sizes. You might hope Lutris would do some sort of scaling here, but no.

Usually, when you don't get Lutris.net media like this, it's because it picked the wrong 'identifier' for the game. If you can find the game on Lutris.net, you can fix the game installation via the Configuration dialog.

**Comment by Tylerwbrown** [comment]
@danieljohnson2 thanks for the info, this led me on the right path, though it seems it is buggy behavior. For example, Northgard's identifier was `northgard`, which is correct. However, I changed it to something else, and then changed it back to `northgard`, and it found the images. This also worked for other games as well.

**Comment by danieljohnson2** [comment]
Curious that some of your games managed to download their media from Lutris.net, but others did not.

You can just click the 'reset' icons under the media in the Configuration dialog to update them if the identifier is right; it will download the media if it is missing- and if the identifier is right.

**Comment by strycore** [comment]
The sources of the images are not the same. 
We already have a ticket about that (that we won't fix)

**Comment by strycore** [comment]
Also note that I have a library of over 1500 games and aside from a few exceptions (that aren't really games), I have no missing image.

**Comment by strycore** [comment]
We also have a bug when Lutris media doesn't download when 3rd party sources are refreshed
