### ISSUE TITLE
Import button missing

### ISSUE THREAD

**Issue by problematicschizo** [lutris/lutris#4957]
### Bug description

I recently installed wine on ubuntu and maybe i'm dumb but when i click on the plus in the corner it doesn't show the import option, It just shows a page where you can type in the name of the game, runner and release year

### How to Reproduce

1. Go to lutris
2. Click on the plus in the corner

### Expected behavior

Is this because i downloaded the wrong version(i downloaded the latest)? 

### Log output

```shell
There is nothing in the terminal
```

### System Information

```shell
[System]
OS:              Ubuntu 22.04 Jammy Jellyfish
Arch:            x86_64
Kernel:          5.19.0-50-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.5-0ubuntu0.1~22.04.3
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I don't understand what you were expecting to see. 
This is what you should see when clicking the + button:

![image](https://github.com/lutris/lutris/assets/280336/ad493e9b-d1c3-4f33-9084-9a91998e6023)


> It just shows a page where you can type in the name of the game, runner and release year

Looks like you downloaded a really old version of Lutris.

**Comment by problematicschizo** [comment]
> I don't understand what you were expecting to see. This is what you should see when clicking the + button:
> 
> ![image](https://user-images.githubusercontent.com/280336/257928283-ad493e9b-d1c3-4f33-9084-9a91998e6023.png)
> 
> > It just shows a page where you can type in the name of the game, runner and release year
> 
> Looks like you downloaded a really old version of Lutris.

I downloaded version v0.5.13, it says that's the newest

**Comment by strycore** [comment]
yes, that's the latest. Send a screenshot of what you're seeing when clicking the  + button.

**Comment by problematicschizo** [comment]
This happens after i press the + button: 
![20230802_222221](https://github.com/lutris/lutris/assets/141270930/42e76865-138e-4536-a39c-4b6a03f6258d)

**Comment by strycore** [comment]
That isn't Lutris 0.5.13.

Take a screenshot of the About window.

**Comment by problematicschizo** [comment]
![Screenshot from 2023-08-02 22-31-56](https://github.com/lutris/lutris/assets/141270930/7e467675-4514-4714-aef1-1cf76b0e47ac)

**Comment by problematicschizo** [comment]
Sorry. ![Screenshot from 2023-08-02 22-34-51](https://github.com/lutris/lutris/assets/141270930/9754b67d-e3d5-4d07-8646-1ec4b1962eb0)

**Comment by strycore** [comment]
Yeah , that's 0.5.9. 
This version isn't even usable anymore because we don't deliver essential components for versions that old (this is the reason why most icons are missing from the sidebar)

**Comment by problematicschizo** [comment]
Why did this version download then?

**Comment by strycore** [comment]
I think you downloaded the 0.5.13 deb but installed the version from the ubuntu repos (which is 0.5.9)

**Comment by problematicschizo** [comment]
I opened the deb file with software installer first so how should i install it from the deb file?

**Comment by strycore** [comment]
weird, opening the deb file should work.
you can also use the command line:

`sudo apt install ~/Downloads/lutris*.deb`

**Comment by problematicschizo** [comment]
I installed it using that command but for some reason i am still in version 0.5.9

**Comment by strycore** [comment]
maybe remove the Ubuntu version 1st with 

`sudo apt remove lutris`

**Comment by problematicschizo** [comment]
I am still on the old version

**Comment by strycore** [comment]
then you're probably something that installs the repo version instead of the deb file version. Can you paste the output of the apt command?

**Comment by problematicschizo** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'lutris' instead of '/home/teodor/Downloads/lutris_0.5.13_all.deb'
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libbs2b0 libflashrom1
  libflite1 libftdi1-2 libgl1-amber-dri libgstreamer-plugins-bad1.0-0
  liblilv-0-0 libllvm13 libpython2-stdlib libpython2.7-minimal
  libpython2.7-stdlib librubberband2 libserd-0-0 libsord-0-0 libsratom-0-0
  libvidstab1.1 libzimg2 pocketsphinx-en-us python2-minimal python2.7
  python2.7-minimal
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  gamescope
The following NEW packages will be installed:
  lutris
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/1.218 kB of archives.
After this operation, 3.762 kB of additional disk space will be used.
Get:1 /home/teodor/Downloads/lutris_0.5.13_all.deb lutris all 0.5.13 [1.218 kB]
Selecting previously unselected package lutris.
(Reading database ... 236049 files and directories currently installed.)
Preparing to unpack .../lutris_0.5.13_all.deb ...
Unpacking lutris (0.5.13) ...
Setting up lutris (0.5.13) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
N: Download is performed unsandboxed as root as file '/home/teodor/Downloads/lutris_0.5.13_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by strycore** [comment]
It's giving you an error message right at the end saying the deb file can't be accessed: 

`N: Download is performed unsandboxed as root as file '/home/teodor/Downloads/lutris_0.5.13_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`


What is the output of 
`ls -la ~/Downloads/lutris_0.5.13_all.deb` ?

**Comment by problematicschizo** [comment]
-rw-rw-r-- 1 teodor teodor 1218162 aug  2 22:05 /home/teodor/Downloads/lutris_0.5.13_all.deb

**Comment by strycore** [comment]
I don't see anything wrong here...

Maybe for some reason, your Downloads folder can't be accessed by apt? Would seem weird but look like what's happening.
Maybe try:

```
cp ~/Downloads/lutris_0.5.13_all.deb /tmp
sudo apt install /tmp/lutris_0.5.13_all.deb
```

**Comment by problematicschizo** [comment]
sudo apt install /tmp/lutris_0.5.13_all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'lutris' instead of '/tmp/lutris_0.5.13_all.deb'
lutris is already the newest version (0.5.13).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libbs2b0 libflashrom1 libflite1 libftdi1-2 libgl1-amber-dri libgstreamer-plugins-bad1.0-0 liblilv-0-0 libllvm13 libpython2-stdlib libpython2.7-minimal
  libpython2.7-stdlib librubberband2 libserd-0-0 libsord-0-0 libsratom-0-0 libvidstab1.1 libzimg2 pocketsphinx-en-us python2-minimal python2.7 python2.7-minimal
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

and i'm still on the same version

**Comment by strycore** [comment]
>  lutris is already the newest version (0.5.13).

The version is correct. Have you completely exited Lutris when reinstalling? If a game is still running, Lutris will keep running in the background.

**Comment by problematicschizo** [comment]
This solution worked version 0.5.13 Thank you!

**Comment by danieljohnson2** [comment]
@problematicschizo, if you are no longer seeing any game media and some icons are missing, it's a known issue- a missing dependency in the 0.5.13 .deb.

Do this:
```
sudo apt install python3-gi-cairo
```
To get the missing thing.

If everything is showing up right for you, then never mind- 0.5.13 must be flawless after all.
