### ISSUE TITLE
vulkan-icd-loader "unknown gpu"

### ISSUE THREAD

**Issue by RosGtHub** [lutris/lutris#4958]
### Bug description

As I was changing the wine version, I noticed that the Vulkan ICD loader displays the message: "Unspecified: Unknown GPU," and the same goes for RADV. 

I hope you can help me, thank you in advance! 
(It looks that doesn't give problems for gaming but it's so annoying to see that)
### How to Reproduce

1. Go to 'configure'
2. Click on 'System options'
3. See 'vulkan-icd-loader'

### Expected behavior

It should say "Radv amdgpu rx 6700 xt."

### Log output

```shell
.
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.4.7-arch1-2
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600G with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.4 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.4.7-arch1-2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.4
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.4
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.4 
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.246)
```

### Media (optional)

![Screenshot from 2023-08-02 23-01-04](https://github.com/lutris/lutris/assets/89165766/045ee5c0-63bc-4693-add1-bf1b3e0deb60)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by DeicPro** [comment]
Same here.

`[System]
OS:              Arch Linux  
Arch:            x86_64
Kernel:          6.4.12-zen1-1-zen
Desktop:         Yaru:ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             6.7 GB
Swap:            3.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon R6 Graphics (kaveri, LLVM 16.0.6, DRM 3.52, 6.4.12-zen1-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.6-arch1.4
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.6-arch1.4
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6-arch1.4
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon R7 M265 Series (RADV OLAND) (1.3.246), AMD Radeon R6 Graphics (RADV KAVERI) (1.3.246)

`

![Captura desde 2023-08-30 03-15-58](https://github.com/lutris/lutris/assets/12710770/ebdf6c07-de38-429a-908c-49afc8ad55b6)

**Comment by strycore** [comment]
Do you have vulkaninfo (from the vulkan-tools package) installed?

**Comment by appoloin** [comment]
Is this any help 
[vulkaninfo.txt](https://github.com/lutris/lutris/files/12867823/vulkaninfo.txt)

**Comment by strycore** [comment]
Please also send the PCI IDs of  your GPU.  They show up when Lutris starts and looks like: 

`INFO     2023-10-11 08:41:25,663 [display.display_gpu_info:78]:GPU: 10DE:2504 196E:138E (nvidia drivers)`

**Comment by appoloin** [comment]
INFO     2023-10-11 20:00:14,002 [startup.check_driver:84]:GPU: 1002:130A 17AA:3830 (amdgpu drivers)
INFO     2023-10-11 20:00:14,003 [startup.check_driver:84]:GPU: 1002:6665 17AA:130A (radeon drivers)

**Comment by strycore** [comment]
Ok, this is a tricky situation because there are both amdgpu and radeon drivers, your vulkaninfo output only shows 1 GPU.

We should at least have a check to not query vulkan info for gpus on the radeon driver.

**Comment by strycore** [comment]
@appoloin is this with Lutris 0.5.13 or the current git code?

**Comment by strycore** [comment]
I'm also missing the API support info for these GPUs in the API: https://lutris.net/api/hardware/features?pci_ids=1002:130A%2017AA:3830,1002:6665%2017AA:130A

**Comment by appoloin** [comment]
I've got Lutris 0.5.13 native and flatpak

**Comment by strycore** [comment]
ok so both are 0.5.13. You might want to give 0.5.14 a try, there might have been some fixes.

**Comment by appoloin** [comment]
Ok, I tried this version [https://lutris.net/releases/lutris_0.5.13.tar.xz] (ran it before looking at the version number), and the drop down looks correct/better. Is the version number being reported wrong? 

![Screenshot from 2023-10-13 08-56-54](https://github.com/lutris/lutris/assets/34371675/1616a317-61cf-4314-9b57-d14984d64443)

**Comment by appoloin** [comment]
I've  ran clone git and got a Lutris reporting a version number of 0.5.14. The drop down looks the same as the screenshot above (the correct/better one)
