### ISSUE TITLE
Lutris gamescope options are not compatible with gamescope 3.12 update

### ISSUE THREAD

**Issue by QuietApe** [lutris/lutris#4959]
### Bug description

In gamescope 3.12, some options have been modified and lutris is now not compatible with them. This affect the upscaler filter options (-U) and maybe other I didn't see.

For example, if I configure lutris to upscale a game with fsr from 1920x1080 to 2560x1440, gamescope command would be :
`gamescope -w 1920 -h 1080 -W 2560 -H 1440 -f -U --fsr-sharpness 0`

But now, gamescope 3.12 expect a command without the -U and with the new -F :
`gamescope -w 1920 -h 1080 -W 2560 -H 1440 -f -F fsr --fsr-sharpness 0`

Without the upscaling options, the game start with no problem even with updated gamescope.

### How to Reproduce

(with gamescope update to 3.12)

1. Go to gamescope options for the game
2. Click on enable gamescope and input a number for sharpness fsr
3. Start the game
4. See error message in the log saying that options U is invalid

### Expected behavior

Game launch with lutris should start with latest version of gamescope.

### Log output

```shell
Started initial process 6248 from gamescope -w 1920 -h 1080 -W 2560 -H 1440 -f -U --fsr-sharpness 0 -- gamemoderun /home/user/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine /home/user/games/Elden Ring/Game/eldenring.exe
Start monitoring process.
gamescope: invalid option -- 'U'
See --help for a list of options.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

### System Information

```shell
[System]
OS:              Arch Linux  
Arch:            x86_64
Kernel:          6.4.7-arch1-3
Desktop:         sway
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.4.7-arch1-3)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.4
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.4
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.4
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 570 Series (1.3.252)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by QuietApe** [comment]
Nevermind, already treated here #4908, guess I have miss it.
Sorry for the noise !

**Comment by danieljohnson2** [comment]
Okay, I finally got around to doing this. Grab the master branch and run the bin/lutris script within; the gamescope FSR thing should work again.
