### ISSUE TITLE
Lutris fails to run Xbox games using a custom xemu binary

### ISSUE THREAD

**Issue by awsms** [lutris/lutris#4961]
### Bug description

I'm using xemu from the AUR (https://aur.archlinux.org/packages/xemu), currently on 0.7.99 (really don't want to use the version Lutris provides since it's 0.7.71 = oct 2022 build).
Whenever I click "Play", xemu immediatly crashes.

### How to Reproduce

1. Configure xemu with a path to the binary (custom path provided by the user)
2. Add an Xbox game to Lutris, running with xemu
3. Run the game
4. Crashes

### Expected behavior

Getting xemu to run.

### Log output

```shell
DEBUG    2023-08-05 15:58:21,227 [command.start:141]:game_name="Ninja Gaiden Black"
DEBUG    2023-08-05 15:58:21,227 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/home/me/.local/lib/python3.11/site-packages:/usr/lib/python3.11/site-packages"
DEBUG    2023-08-05 15:58:21,227 [command.start:141]:LUTRIS_GAME_UUID="ddbe74da-bcc6-492d-9263-dd32ab0ad669"
Started initial process 164046 from gamemoderun mangohud /usr/bin/xemu -full-screen -dvd_path /media/me/gaymes/roms/xbox/Ninja_Gaiden_Black_DVD5_XBOX-GeNiuS.iso
Start monitoring process.
gamemodeauto: 
/usr/bin/xemu: symbol lookup error: /usr/lib/libatk-bridge-2.0.so.0: undefined symbol: atk_component_scroll_to
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
DEBUG    2023-08-05 15:58:21,394 [command.on_stop:195]:Process 164043 has terminated with code 32512
DEBUG    2023-08-05 15:58:23,237 [game.beat:842]:Game thread stopped
WARNING  2023-08-05 15:58:23,237 [game.on_game_quit:879]:Game still running (state: running)
INFO     2023-08-05 15:58:23,237 [game.stop:853]:Stopping Ninja Gaiden Black (xemu)
DEBUG    2023-08-05 15:58:23,238 [game.stop_game:809]:Ninja Gaiden Black (xemu) has run for 2 seconds
WARNING  2023-08-05 15:58:23,238 [game.stop_game:811]:The game has run for a very short time, did it crash?
DEBUG    2023-08-05 15:58:23,238 [application.on_game_stop:679]:Removing 83 from running IDs
DEBUG    2023-08-05 15:58:23,245 [game.stop_game:821]:Playtime: Less than a minute
DEBUG    2023-08-05 15:58:23,245 [game.on_game_quit:897]:Ninja Gaiden Black stopped at Sat, 05 Aug 2023 15:58:23
DEBUG    2023-08-05 15:58:23,277 [lutris.add_to_path_cache:158]:Adding Ninja Gaiden Black (xemu) to path cache
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.4.8-arch1-1
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600H with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             13.5 GB
Swap:            15.6 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.52, 6.4.8-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.5
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.5
Vulkan Version:  1.3.255
Vulkan Drivers:  NVIDIA GeForce RTX 3060 Laptop GPU (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [x] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
if you're using a custom binary then disable the lutris runtime in the system options

**Comment by awsms** [comment]
> if you're using a custom binary then disable the lutris runtime in the system options

Doesn't it defeat the use of Lutris in that case? I wanted to use the gamemode + discrete GPU from Lutris' settings. Unfortunately I can't add custom arguments before /usr/bin/xemu, so I can't use gamemoderun or mangohud that way.

**Comment by strycore** [comment]
I don't see how it defeats the point of Lutris. We ship runners and a runtime that is compatible with those runners. You chose to not use our runners, so it makes sense that you wouldn't use the runtime either.

Using a custom runner exe without the runtime doesn't prevent you from using Gamemode and the discrete GPU

**Comment by awsms** [comment]
> Using a custom runner exe without the runtime doesn't prevent you from using Gamemode and the discrete GPU

I'm kinda lost here, isn't the runtime = all the options you set in the config + the libs provided by Lutris? Because with the Lutris runtime disabled, none of the options (gamemode, mangohud, discrete GPU) are executed

**Comment by strycore** [comment]
> Because with the Lutris runtime disabled, none of the options (gamemode, mangohud, discrete GPU) are executed

That's one of the weirdest things I've ever heard. Gamemode and mangohud are provided by your OS, they do not depend on the lutris runtime. As for setting the discrete GPU, that's even wilder because that mostly involves setting environment variables.

I suspect something has gone very very wrong at your OS level.

**Comment by awsms** [comment]
> I suspect something has gone very very wrong at your OS level.

Could you please elaborate on this? :fearful:
To force my GPU, I simply use the env var GAMEMODERUNEXEC=prime-run
If I enable the said options in Lutris' settings (gamemode, mangohud) and launch a game with xemu, none of the overlays/programs are runned except xemu.
If I run `gamemoderun mangohud xemu` in my terminal, everything run as expected.

**Comment by strycore** [comment]
I've updated the xbox runner to the latest version, which uses an AppImage. AppImage runners don't use the Lutris runtime since AppImages have their own self contained runtimes. 

The new version runs nicely in Lutris. I couldn't get Mangohud to run but that's maybe because it's OpenGL and not Vulkan (you mention having it working though). 
When launching the xemu AppImage from a terminal, I couldn't get mangohud either...

**Comment by awsms** [comment]
On my side, I configures my existing install of PCSX2 in Lutris, and both mangohud & gamemod worked fine when enabled in Lutris' settings. This seems to be specific to xemu I guess?
I'll have a look at the provided xemu build. Thanks for this!
