### ISSUE TITLE
add mod managers as sources / have lutris handle modding support

### ISSUE THREAD

**Issue by RustoMCSpit** [lutris/lutris#4964]
not rly familiar with lutris but you get waht i mean

**Comment by strycore** [comment]
I suggest you familiarize yourself with Lutris first.

Like, the fact that we have support for modding.

**Comment by RustoMCSpit** [comment]
> I suggest you familiarize yourself with Lutris first.
> 
> Like, the fact that we have support for modding.

right sick thanks
