### ISSUE TITLE
ModuleNotFoundError: No module named 'lutris.gui.application'

### ISSUE THREAD

**Issue by Keerp96** [lutris/lutris#4969]
### Bug description

Updated Lutris from 0.5.12 to 0.5.13 via pacman on Artix KDE Plasma. Now when launching I get this error:
`Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
ModuleNotFoundError: No module named 'lutris.gui.application'`

### How to Reproduce

1. Have previously installed version 0.5.12
2. Update to 0.5.13
3. Attempt to launch
4. Get error `Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
ModuleNotFoundError: No module named 'lutris.gui.application'`

### Expected behavior

Lutris should launch without errors.

### Log output

```shell
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
ModuleNotFoundError: No module named 'lutris.gui.application'
```

### System Information

```shell
Operating System: Artix Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.6-artix1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 7,5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630 / NVIDIA GeForce GTX 1050
Manufacturer: Dell Inc.
Product Name: Inspiron 5577
System Version: 1.0.5
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
* Try restarting your system
* Make sure you haven't messed with Pyenv
* Make sure you haven't messed with VirtualEnvs
* Make sure you haven't installed Lutris with setup.py which can result in some files in /usr/local/share
* Make sure no lutris files are in ~/.local/share/bin or ~/.local/share/lib/
