### ISSUE TITLE
[Feature Request]: Custom Play menu entries for games

### ISSUE THREAD

**Issue by 6XGate** [lutris/lutris#4972]
Some DOS games tend to have configuration utilities or tools shipped with them that would be needed to alter game settings. It would be great if there was a way to add those to the arrow menu that shows up by the Play button and/or right-click menu.

The only reason this may not work like Wine's run EXE in prefix is with GOG installed games that only mount the C drive in the single/main config and not the regular config file.

**Comment by strycore** [comment]
We have launch config which do exactly that. 
There an open ticket about adding an UI for that feature (which is currently only available with scripting): #4648

**Comment by 6XGate** [comment]
:+1: sorry, didn't realize it was related
