### ISSUE TITLE
Lutris sees my RX 6600 XT as an HD 5600

### ISSUE THREAD

**Issue by NLBen** [lutris/lutris#4976]
### Bug description

I was attempting to launch a game, and for whatever reason Lutris sees my GPU as an Radeon HD 5600.

That's really, REALLY weird. In that case it doesn't surprise me Lutris attempts to tell me my GPU can't run DX 12. Indeed it can not if it were an HD 5600!

I'm running the latest Lutris-GE version (8.13) as the runner for WINE.

### How to Reproduce

1. Attempt to run a certain game in Lutris
2. Have everyting pointing to the right places
3. Click on run
4. Get the error

### Expected behavior

Recognize the GPU correctly

### Log output

```shell
Initial process has exited (return code: 1280)
Exit with return code 1280
DEBUG    2023-08-11 20:58:41,931 [command.on_stop:195]:Process 6484 has terminated with code 1280
DEBUG    2023-08-11 20:58:42,670 [game.beat:842]:Game thread stopped
WARNING  2023-08-11 20:58:42,670 [game.on_game_quit:879]:Game still running (state: running)
INFO     2023-08-11 20:58:42,670 [game.stop:853]:Stopping Death Stranding (wine)
DEBUG    2023-08-11 20:58:42,670 [game.stop_game:809]:Death Stranding (wine) has run for 8 seconds
DEBUG    2023-08-11 20:58:42,670 [application.on_game_stop:679]:Removing 4 from running IDs
DEBUG    2023-08-11 20:58:42,671 [game.stop_game:821]:Playtime: 4 minutes
DEBUG    2023-08-11 20:58:42,671 [game.on_game_quit:897]:Death Stranding stopped at vr, 11 aug 2023 20:58:42
DEBUG    2023-08-11 20:58:42,704 [lutris.add_to_path_cache:158]:Adding Death Stranding (wine) to path cache
DEBUG    2023-08-11 20:58:42,706 [xrandr.change_resolution:127]:Switching to 1920x1080 on HDMI-A-0
INFO     2023-08-11 20:58:42,706 [xrandr.change_resolution:138]:Switching resolution of HDMI-A-0 to 1920x1080
INFO     2023-08-11 20:58:43,515 [application.do_shutdown:960]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Linux Mint 21.2 Victoria
Arch:            x86_64
Kernel:          6.2.0-26-generic
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.49, 6.2.0-26-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1~22.04.1
Vulkan Version:  1.3.204
Vulkan Drivers:  AMD Radeon RX 6600 XT (RADV NAVI23) (1.3.238)
```

### Media (optional)

![LutrisError2](https://github.com/lutris/lutris/assets/87259576/79eca0a3-fa12-46e1-86d1-5bfc2df5c174)
![LutrisError1](https://github.com/lutris/lutris/assets/87259576/ced3ae2a-868f-4131-85ae-19c9080b7ad5)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That does not look like a Lutris error; I think that's your game itself producing these dialogs.

Why it thinks you have a 5600 I do not know. Lutris thinks it is a 6600, as you can see in the system information.

**Comment by NLBen** [comment]
> That does not look like a Lutris error; I think that's your game itself producing these dialogs.
> 
> Why it thinks you have a 5600 I do not know. Lutris thinks it is a 6600, as you can see in the system information.

Just rechecked. My error in this case. I thought the error.txt referred to Lutris' error log, but I now noticed that the game has its own error.txt (why they opted to that, I'm not sure). Closing this thread.
