### ISSUE TITLE
`NON_ESYNC_WINE_VERSION` handled error considered to be "unhandled"?

### ISSUE THREAD

**Issue by rokejulianlockhart** [lutris/lutris#4978]
### Bug description

It doesn't need two dialogs to tell the user the same thing, the second more scarily.

### How to Reproduce

0.	Install the Epic Games Store.
0.	Attempt to invoke it.

### Expected behavior

The more error-specific (2nd) dialog should include the actionable text from the 1st dialog.

### Log output

```shell
lutris -d

```log
PS /home/rokejulianlockhart> lutris -d
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
NativeCommandExitException: Program "lutris" ended with non-zero exit code: 1.
PS /home/rokejulianlockhart>
```

### System Information

```shell
[System]
OS:              openSUSE Tumbleweed 20230807 n/a
Arch:            x86_64
Kernel:          6.4.8-1-default
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.2 GB
Swap:            31.2 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 (navi10, LLVM 16.0.6, DRM 3.52, 6.4.8-1-default)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.5
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.5
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon RX 5700 (RADV NAVI10) (1.3.246)
```

### Media (optional)

0.  ![image](https://github.com/lutris/lutris/assets/42837531/1c8f3c97-ae1f-4b4d-a0d5-728dbf87876b)
0.  ![image](https://github.com/lutris/lutris/assets/42837531/988548e0-0943-493c-bed1-0987f87036c5)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [ ] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [ ] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Yeah, this is some weird code that tries to turn these issues into error codes, and places UI code outside the UI. Not ideal.

I've replaced the error codes with exceptions with custom handling to keep the first of the pair of errors around, but now with its parent window set.

I did both the FSYNC and ESYNC errors. Should be better now.
