### ISSUE TITLE
Theme not respected, text needs anti-aliasing

### ISSUE THREAD

**Issue by CharlotteCross1998** [lutris/lutris#4980]
### Bug description

Since updating to 0.5.13, the theme has changed and is no longer respecting my system theme. Furthermore, text is no longer anti-aliased and looks really out of place.

### How to Reproduce

Open lutris.

### Expected behavior

Lutris should respect system theming and text should be anti-aliased

### Log output

```shell
[charlotte@charlotte-laptop ~]$ lutris -d
INFO     2023-08-13 16:15:31,154 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-08-13 16:15:31,162 [startup.check_driver:73]:Running AMD Mesa driver 23.1.5 on AMD Radeon Vega 10 Graphics (raven, LLVM 15.0.7, DRM 3.52, 6.4.8-zen1-1-zen) (0x15d8)
INFO     2023-08-13 16:15:31,163 [startup.check_driver:85]:GPU: 1002:15D8 1043:14BF (amdgpu drivers)
DEBUG    2023-08-13 16:15:31,324 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-13 16:15:31,404 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-08-13 16:15:31,426 [application.show_update_runtime_dialog:297]:Skipping initialization
```

### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.4.8-zen1-1-zen
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             9.7 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Vega 10 Graphics (raven, LLVM 15.0.7, DRM 3.52, 6.4.8-zen1-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.5
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.5
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon Vega 10 Graphics (RADV RAVEN) (1.3.246)
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/29734551/33db4dc5-842a-4946-9acb-9354a851be3a)
Kate has been opened to show a comparison between the lack of aliasing and not following the system theme in lutris and aliasing and theme being present in Kate.

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That's very strange. Are other GNOME programs affected by this, or is it just Lutris?

**Comment by CharlotteCross1998** [comment]
> That's very strange. Are other GNOME programs affected by this, or is it just Lutris?

I installed gnome-disks to test and yes, it appears to be GNOME programs, not just Lutris. I didn't have any other GNOME programs installed before this so I have nothing else to compare it to. My guess is a library/dependency updated and has broke themeing and aliasing on GNOME apps, or the latest Lutris update changed libraries to use one that has been broken for a while?

**Comment by danieljohnson2** [comment]
The latest Lutris does depend on 'python3-gi-cairo' now, which is new for it. I can't see anything else for 0.5.13.

However, we forgot to add that dependency (oops) so I don't see how that could have affected 'Disks'. In any case you do have that, or you wouldn't be able to see the game media.

I do not know what happened here, but I don't think it's Lutris at all.

**Comment by CharlotteCross1998** [comment]
Yeah it doesn't seem to be Lutris, however no idea what could be causing it. It's a bit odd how the theming of a program can be dictated by a 3rd party library however.
