### ISSUE TITLE
GOG.com source -- games within packages need better handling; retroactively changed game titles cause issues

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [lutris/lutris#4981]
### Bug description

Since the recent Quake II update on GOG.com, the Lutris installer routine has been performing undesirable behaviour.

This is technically two separate issues, though I'll present them here together as they were caused by the same update on GOG.com's end.

Background:

The GOG.com `quake_ii` package was recently updated. It now contains both `quake_ii_quad_damage_game` (was titled "Quake II", now "Quake II (Original)") and a new `quake_ii` ("Quake II") remaster.

Issues:

1. When attempting to install either "Quake II (Original)" or "Quake II" via Lutris, both choices direct to the same set of available Lutris install scripts. This is undesirable as existing install scripts may not be compatible with the newly-published title. This is actually true for the `GOG + Yamagi` install script: https://github.com/yquake2/yquake2remaster/issues/3

2. Since the update, if one attempts re-installation of "Original", Lutris will miss the previously cached installer file, if it exists. Lutris seems to rely upon a transform of the GOG.com game `title` into an internal Lutris slug. E.g. `Quake II (Original)` -> `quake-ii-original`. This breaks cache detection for the previously cached "Original" installer file (pre-update). Lutris was presumably searching for `quake-ii-original/`, rather than `quake-ii/` (the former slug for this game).

### How to Reproduce

"Original" and remaster GOG.com games sharing install scripts:
1. Ensure Quake II is in user's GOG.com library
2. Press on "Quake II" (the remaster), and attempt to install.
3. Note that `GOG + Yamagi` script appears, despite that script only supporting "Quake II (Original)".
4. Continue install, at which point the launcher will presumably fail due Yamagi not supporting remaster's modified game files.

Cached installer file for "Original" game is missed by Lutris:
1. Ensure that `quake-ii/gog/setup_quake2_quad_damage_2.0.0.3.exe` exists within your Lutris cache directory. This is to emulate the state of the cache before the update had released, presuming the user had already cached the "Original" installer.
2. Press on "Quake II (Original)", and attempt to install.
3. Lutris will not find this file in the cache, as it is instead presumably looking for `quake-ii-original/gog/setup_quake2_quad_damage_2.0.0.3.exe` (the post-update location for this file).

### Expected behavior

In the first instance, there clearly needs to be a logical separation of GOG.com game titles within Lutris' script service. Separating at package level may not be adequate.

In the second instance, I would expect the correct file to be found in its expected location. The Lutris client can't know that the expected location has changed. Therefore, the expected location should ideally never change.

Lutris needs to better handle new "games" published under the same parent "package" by various games providers. Existing game entries in Lutris should not have their slugs arbitrarily changed; new titles that conflict with existing (or historical) entries should adjust their own slug instead. This matter is no doubt compounded by organisational inconsistencies amongst games providers themselves. These edge cases need better detection and moderation.

### Log output

```shell
==== Case 1: ====

DEBUG    2023-08-14 13:32:58,882 [services.get_game:17]:Getting service game 1947927225 for gog
DEBUG    2023-08-14 13:32:58,884 [base.install:263]:Installing 1947927225 from service gog
DEBUG    2023-08-14 13:32:58,885 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-08-14 13:32:59,345 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/quake-ii
DEBUG    2023-08-14 13:32:59,345 [http._request:88]:GET https://lutris.net/api/installers/quake-ii
DEBUG    2023-08-14 13:33:00,834 [application.show_window:339]:Showing window InstallerWindow1947927225
DEBUG    2023-08-14 13:33:12,509 [displayconfig.get_current_resolution:643]:Retrieving current resolution
DEBUG    2023-08-14 13:33:15,378 [gog.get_extras:320]:Download extras for GOG ID 1947927225 and its DLCs
INFO     2023-08-14 13:33:15,379 [gog.get_game_details:286]:Getting game details for 1947927225
DEBUG    2023-08-14 13:33:15,379 [http._request:88]:GET https://auth.gog.com/token?client_id=<redacted>&client_secret=<redacted>&grant_type=refresh_token&refresh_token=<redacted>
DEBUG    2023-08-14 13:33:15,817 [http._request:88]:GET https://api.gog.com/products/1947927225?expand=downloads&locale=en-US
INFO     2023-08-14 13:33:17,028 [gog.get_game_details:286]:Getting game details for 1947927225
DEBUG    2023-08-14 13:33:17,029 [http._request:88]:GET https://api.gog.com/products/1947927225?expand=downloads&locale=en-US
DEBUG    2023-08-14 13:33:17,134 [http._request:88]:GET https://embed.gog.com/userData.json
INFO     2023-08-14 13:33:18,247 [installer.prepare_game_files:175]:Getting files for q2data
INFO     2023-08-14 13:33:18,248 [installer.prepare_game_files:177]:Adding selected extras to downloads
INFO     2023-08-14 13:33:18,248 [gog.get_game_details:286]:Getting game details for 1947927225
DEBUG    2023-08-14 13:33:18,249 [http._request:88]:GET https://api.gog.com/products/1947927225?expand=downloads&locale=en-US
INFO     2023-08-14 13:33:18,349 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1947927225/downlink/installer/en1installer0
DEBUG    2023-08-14 13:33:18,351 [http._request:88]:GET https://api.gog.com/products/1947927225/downlink/installer/en1installer0
INFO     2023-08-14 13:33:18,856 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1947927225/downlink/installer/en1installer1
DEBUG    2023-08-14 13:33:18,858 [http._request:88]:GET https://api.gog.com/products/1947927225/downlink/installer/en1installer1

==== Case 2: ====

DEBUG    2023-08-14 13:35:38,222 [services.get_game:17]:Getting service game 1441704824 for gog
DEBUG    2023-08-14 13:35:38,224 [base.install:263]:Installing 1441704824 from service gog
DEBUG    2023-08-14 13:35:38,224 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2023-08-14 13:35:38,680 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/quake-ii
DEBUG    2023-08-14 13:35:38,681 [http._request:88]:GET https://lutris.net/api/installers/quake-ii
DEBUG    2023-08-14 13:35:40,199 [application.show_window:339]:Showing window InstallerWindow1441704824
DEBUG    2023-08-14 13:35:44,824 [displayconfig.get_current_resolution:643]:Retrieving current resolution
INFO     2023-08-14 13:35:47,807 [runner.get_runner_version:480]:Getting runner information for wine (version: lutris-GE-Proton8-8-x86_64)
DEBUG    2023-08-14 13:35:47,808 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2023-08-14 13:35:48,177 [interpreter.get_runners_to_install:274]:Failed to get default wine version (got {})
DEBUG    2023-08-14 13:35:48,258 [gog.get_extras:320]:Download extras for GOG ID 1441704824 and its DLCs
INFO     2023-08-14 13:35:48,258 [gog.get_game_details:286]:Getting game details for 1441704824
DEBUG    2023-08-14 13:35:48,259 [http._request:88]:GET https://api.gog.com/products/1441704824?expand=downloads&locale=en-US
INFO     2023-08-14 13:35:48,749 [gog.get_game_details:286]:Getting game details for 1441704824
DEBUG    2023-08-14 13:35:48,750 [http._request:88]:GET https://api.gog.com/products/1441704824?expand=downloads&locale=en-US
DEBUG    2023-08-14 13:35:48,838 [http._request:88]:GET https://embed.gog.com/userData.json
INFO     2023-08-14 13:35:49,682 [installer.prepare_game_files:175]:Getting files for goginstaller
INFO     2023-08-14 13:35:49,682 [installer.prepare_game_files:177]:Adding selected extras to downloads
INFO     2023-08-14 13:35:49,682 [gog.get_game_details:286]:Getting game details for 1441704824
DEBUG    2023-08-14 13:35:49,684 [http._request:88]:GET https://api.gog.com/products/1441704824?expand=downloads&locale=en-US
INFO     2023-08-14 13:35:49,784 [gog.get_download_info:292]:Getting download info for https://api.gog.com/products/1441704824/downlink/installer/en1installer1
DEBUG    2023-08-14 13:35:49,785 [http._request:88]:GET https://api.gog.com/products/1441704824/downlink/installer/en1installer1
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.4.6-100.fc37.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.4.6-100.fc37.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.4 (git-8b0202e4b4)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.4 (git-8b0202e4b4)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.4 (git-8b0202e4b4)
Vulkan Version:  1.3.224
Vulkan Drivers:  AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
If I understand, GOG has altered the package for Quake II by adding the remaster to it, and this breaks an existing fancy script for a improved Quake 2 client. Yes?

If so, I'm not sure what we can do about this in a general sense. The install script needs to be removed, or manually rewritten to work with package as it now exists.

It's unfortunate that GOG did this, but I expect the change is not a problem for GOG Galaxy, and that's what they care about.

**Comment by QmwJlHuSg9pa** [comment]
> If I understand, GOG has altered the package for Quake II by adding the remaster to it, and this breaks an existing fancy script for a improved Quake 2 client. Yes?

Strangely, [the script in question](https://lutris.net/games/install/2969/view) does explicitly specify `gogslug`: `quake_ii_quad_damage`, though this doesn't stop it being provided as a match while installing both "Original" (`quake_ii_quad_damage`, **correct**) and the remaster (`quake_ii`, **incorrect**). Perhaps there is some matching logic that can be mended?

Interestingly, in this case at least, the [Quake II app on Steam](https://steamdb.info/app/2320/depots/) instead opts for a single "depot" that holds both the original files and `rerelease/` files. I've seen packaging convention go in either direction on either platform, depending on the game. 

> If so, I'm not sure what we can do about this in a general sense. The install script needs to be removed, or manually rewritten to work with package as it now exists.
> 
> It's unfortunate that GOG did this, but I expect the change is not a problem for GOG Galaxy, and that's what they care about.

Perhaps the script is wrong, but I can not obviously see how?

***

As for the second case (cache mismatch), I've been thinking more about persistence.

Perhaps, going ahead, each game service's game ID could be suffixed to its respective cache directory title? The ID would obviously take precedence over the title, meaning that whether or not a game title changes over time, Lutris could still consistently find a match in cache.

I.e.
1. First, search for delimiter sequence, then check for string of numbers (game ID).
   1a. If game ID matches, then cache dir found.
3. If no match or no delimiter found, fall back to game title search (i.e. literal directory title, current behaviour).

E.g.

Matching "Quake II (Original)" with `gogid`: `1441704824`:
- quake-ii-original
- quake-ii-original_1441704824
- quake-ii_1441704824

Matching "Quake II" with `gogid`: `1947927225`:
- quake-ii
- quake-ii-original_1947927225
- quake-ii_1947927225

**Comment by strycore** [comment]
From yesterday's update from GOG we got both Quake II and Quake II (original):
![image](https://github.com/lutris/lutris/assets/280336/0d153e5d-67d5-4267-a0ed-76f898f816ed)

I guess that just reattributing the correct IDs should fix the issue

**Comment by strycore** [comment]
Quake II had both versions assigned to it, I removed the remaster to leave only the original.
If we don't create a Quake II Remaster and assign the corresponding GOG game to it then the remastered ID will be reassigned to the original Quake II next time the GOG sync runs.
