### ISSUE TITLE
Gamescope options for FSR have changed, so Lutris launches fail

### ISSUE THREAD

**Issue by Crono141** [lutris/lutris#4991]
### Bug description

When enabling "gamescope" in the system options, and specifying an FSR level, the application may fail to launch. Gamescope version 3.12.0-1, Lutris version 0.5.13.

### How to Reproduce

In my case:

1. Install Master of Orion 2 from GOG
2. From System Options enable Gamescope
3. Set appropriate 4:3 resolution to match your monitor
4. Set Game Resolution to 640x480
5. Window Mode: Fullscreen
6. Any value in FSR sharpness field
7. Launch
8. Check log for failure.

### Expected behavior

Lutris should pass the correct options to gamescope when enabled

### Log output

```shell
lutris-wrapper: Master of Orion 2
Started initial process 38416 from gamescope -w 640 -h 480 -W 1440 -H 1080 -f -U --fsr-sharpness 5 -- gamemoderun ./start.sh
Start monitoring process.
gamescope: invalid option -- 'U'
See --help for a list of options.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256

Checking gamescope --help reveals that the -U option has been removed and replaced with -F fsr for FSR and -F nis for Nvidia Image Scaling.
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.1-eupnea
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
Physical cores:  2
Logical cores:   2

[Memory]
RAM:             3.7 GB
Swap:            6.8 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 600 (GLK 2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.5
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.5
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.5
Vulkan Version:  1.3.255
Vulkan Drivers:  Intel(R) UHD Graphics 600 (GLK 2) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Crono141** [comment]
As a follow up comment, even when use the custom settings to put in the correct FSR syntax, the execution still fails, so I wonder if there is a bug with how Lutris is passing these arguments to gamescope?

**Comment by strycore** [comment]
>  if there is a bug with how Lutris is passing these arguments to gamescope?

It's open source, you're welcome to investigate.

**Comment by danieljohnson2** [comment]
If you do, you might find issue #4908, which is exactly this, I'm pretty sure. The latest gamescope (3.12) changed their CLI options in an incompatible way. The next Lutris will detect this and adjust accordingly.

**Comment by Crono141** [comment]
> > if there is a bug with how Lutris is passing these arguments to gamescope?
> 
> It's open source, you're welcome to investigate.

You're right. Let me just teach myself python real quick, dig into your code, and fix the problems as I find them.

Or, you know, file a bug report to help you troubleshoot issues as they pop up. Apologies that I didn't see the other issue when I searched for "gamescope", probably because I searched open issues because, you know, the issue isn't fixed in production. 

Next time I'll just keep it to myself, instead of trying to be helpful.

**Comment by danieljohnson2** [comment]
I'm not sure why GitHub defaults to searching open issues only, that's a bit awkward for end-users who come here. We do need to close things so we can find things that actually need work, but I'm actually searching for closed issues more than open ones myself.

This is just one of those things about open source; you're dealing with the developers and with their bug-tracker, not a customer service department. That's not all bad, honestly, but actual programmers don't quite that public relations... demeanor.

Whether you want to put up with it is up to you, of course.
