### ISSUE TITLE
[Feature request] Support for all systemwide installed wine versions (Gentoo)

### ISSUE THREAD

**Issue by bell07** [lutris/lutris#4995]
Gentoo is able to install multiple wine versions trough portage. Currently only the "default" version is useable in lutris, because symlinked into `$PATH/wine`.

The installed files looks like
```
$ ls /usr/lib/wine-*/*
/usr/lib/wine-proton-8.0.3c/bin:
msidb    notepad  regsvr32  wine    wine64-preloader  winebuild  wineconsole  winedbg   wineg++  winemine  wine-preloader  wmc
msiexec  regedit  widl      wine64  wineboot          winecfg    winecpp      winefile  winegcc  winepath  wineserver      wrc

/usr/lib/wine-proton-8.0.3c/wine:
i386-unix  i386-windows  x86_64-unix  x86_64-windows

/usr/lib/wine-staging-8.14/bin:
msidb    notepad  regsvr32  wine    wine64-preloader  winebuild  wineconsole  winedbg   wineg++  winemine  wine-preloader  wmc
msiexec  regedit  widl      wine64  wineboot          winecfg    winecpp      winefile  winegcc  winepath  wineserver      wrc

/usr/lib/wine-staging-8.14/wine:
i386-unix  i386-windows  x86_64-unix  x86_64-windows
```

It is possible that multiple staging or proton (and vanilla) versions are installed this way. It will be nice if all versions are useable in wine runner.

**Comment by bell07** [comment]
I am python beginner, therefore no PR from my site
Tried the next changes, that seems to work for me:

```
diff --git a/lutris/util/wine/wine.py b/lutris/util/wine/wine.py
index d9feb8da..0763c1d4 100644
--- a/lutris/util/wine/wine.py
+++ b/lutris/util/wine/wine.py
@@ -23,6 +23,10 @@ WINE_PATHS = {
     "system": "wine",
 }
 
+for version in [p for p in os.listdir('/usr/lib/') if "wine-" in p]:
+    path = os.path.join("/usr/lib/", version, "bin/wine")
+    if os.path.isfile(path):
+        WINE_PATHS["System " + version] = path
 
 def get_playonlinux():
     """Return the folder containing PoL config files"""

```

**Comment by danieljohnson2** [comment]
I can help you out with that. I've put together [a branch](https://github.com/lutris/lutris/tree/dj/gentoo_wineing) for this. I've tweaked the code a bit- some exception handling in case we can't read these directories, and I think you want directories that start with "wine-", not that contain that string.

Please go to that branch and try it. Download the thing, and run the bin/lutris script within on Gentoo; does it find your Wine, and does the version selection drop-down in configuration look good?

If it looks good, I'll pop a PR from this branch.

**Comment by strycore** [comment]
I consider this bloat but I'll close an eye on this. 
It's bloat though.

**Comment by strycore** [comment]
So why is it bloat? 
It goes against how Lutris is supposed to be used. Lutris ships with its own Wine build. This is the most compatible build for gaming. If there are issues with it, we need to know what they are and fix them.
We're not interested in people using other builds, they only hold back the development of Lutris and Wine.

I would be ok with having tons of system Wine versions listed if we got anything positive out of this. Instead, regression aren't reported and people seem to be changing Wine builds like they change socks.

Again, I'm not opposed to this patch. I'm just saying it drives the project in the wrong direction and we should be aware of that.

**Comment by danieljohnson2** [comment]
Well, I'll pop this as a PR (if it tests out- I don't have Gentoo) and you can decide if you like it then. I wouldn't just merge this one.

**Comment by strycore** [comment]
This isn't really specific to Gentoo, you can get multiple Wine versions on any distro.  And it's not whether I'll like the PR or not. If we're listing OS installed Wine versions, it does make sense to list all versions available. If we just pick one, we might end up picking the worst possible choice (like a Gentoo build of Proton, can't get much more cursed than that).

**Comment by bell07** [comment]
Tested the change shorly. Now the Wine selection looks like
![grafik](https://github.com/lutris/lutris/assets/4731334/25644853-89d7-46d1-9f76-ed59cc9410c9)

**Comment by bell07** [comment]
About bloat or not: Opinions are different like the people are different. I personally prefer software installed trough portage, just because the most of them is compiled with `--march=native` and includes support only for things I like (USE-Flags).
Currently the most games I manage by own bash scripts, because it just uses the currently installed wine version. For most games I know there is no difference which wine-version is used. Therefore it feels wrong for me to download additional wine version if I already have a wine installed.

**Comment by danieljohnson2** [comment]
I think that's okay. I'd have used more parentheses, but that's a quibble. I'll pop a PR, and @strycore can make the call when he's ready. Sounds like he's leaning towards taking this.

**Comment by strycore** [comment]
You want to use your own Wine, that's fine. But the moment you deviate from our Wine build, you lose any kind of support. And I know, Gentoo users would generally keep playing with their USE_FLAGS than receive support from projects. 

Then I have people telling that I'm not nice to Gentoo users (it happened in the Google+ era), but no. This isn't about being nice or not. I want to drive the project in a certain direction, and if Gentoo users want to do their own thing in their own little corner while not helping improve Linux gaming, **I'm perfectly fine with that**. I'm not the mom of all Gentoo users on the planet. They can do whatever they want. But one thing is for sure, there is **one** correct way to use Lutris. Lutris isn't about giving options and catering to the need of all tinkerers. Lutris isn't about choice (whatever that means, it's just a common meme at this point). Lutris is about getting games to run reliably. And we're not going to reach that if we're supporting 10,000 different configuration types.
