### ISSUE TITLE
The play time is not translated

### ISSUE THREAD

**Issue by gkkulik** [lutris/lutris#4998]
The play time shown in the bottom right corner when a game is selected doesn't seem to be translated. I don't know much about implementing Gettext in Python but looking at the lines 107-139 in lutris/util/strings.py these strings look hardcoded. Perhaps it would be a good idea to include them in the translations?

**Comment by danieljohnson2** [comment]
The ``_("...")`` stuff there is actually a call to gettext() because of the line ``from gettext import gettext as _`` at the top.

I find that a lot of the localizations do not translate these bits, but some do- Spanish, French and Greek seem to have these translations.

Not sure what is going with the ones that do not.

**Comment by strycore** [comment]
> Not sure what is going with the ones that do not.

They need to be translated, that's pretty much it.

**Comment by gkkulik** [comment]
Yeah, I looked into some translations, but not the ones mentioned here, and didn't see those strings there as well. Thank you, I'll have a look there.

**Comment by gkkulik** [comment]
Okay, so I checked it and the phrases:

- " and " (line 134)
- "Less than a minute" (138)

are hardcoded. I looked into the French translation and, with my limited knowledge, compared it with the German one. It states the file and the line so it should be translated:

`#: lutris/util/strings.py:120`
`msgid "1 hour"`
`msgstr "1 heure"`

I changed the translation file to the French one and I got this:

![Zopis_ekranu_20230825_100152](https://github.com/lutris/lutris/assets/17163395/ebebfe16-39f6-47a0-8876-dfc854775fe5)

So the time is being shown in English anyway.

I'm not sure how important it is but the German translation shows wrong line numbers with those phrases as well. Changing them didn't help.

**Comment by danieljohnson2** [comment]
"and" and "Less than a minute" should be translated. Though "and" is trouble- in some languages conjunctions don't land between words like in English. So maybe translating " and " as " " is the best we could do. I'll add the _() thing here.

But I also see that the _() thingies we do have aren't working for me with LANG=FR. But I can't get my debugger to apply a language at all, and I can't see what's going wrong here. There's some kind of issue here, though.

**Comment by strycore** [comment]
I removed the 'and' because it was weird and unneeded
