### ISSUE TITLE
Can't paste in GOG log in window

### ISSUE THREAD

**Issue by tremby** [lutris/lutris#5000]
### Bug description

I can't paste, either from X selection (middle click), or from clipboard (control-V or "paste" from context menu) in the "email" or "password" fields of the GOG log in form.

### How to Reproduce

1. Go to sources -> GOG -> user icon
2. Attempt to paste in the fields

### Expected behavior

Can paste.

### Log output

```shell
INFO     2023-08-24 15:46:56,532 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-08-24 15:46:56,533 [startup.check_driver:65]:Using NVIDIA drivers 510.108.03 for x86_64
INFO     2023-08-24 15:46:56,534 [startup.check_driver:69]:GPU: NVIDIA GeForce GTX 1080 Ti
INFO     2023-08-24 15:46:56,534 [startup.check_driver:85]:GPU: 10DE:1B06 3842:6393 (nvidia drivers)
WARNING  2023-08-24 15:46:56,621 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-08-24 15:46:56,621 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-08-24 15:46:56,621 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-08-24 15:46:56,621 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
WARNING  2023-08-24 15:46:56,621 [system.get_vulkan_gpu_name:611]:vulkaninfo not available, unable to list GPUs
DEBUG    2023-08-24 15:46:56,719 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-08-24 15:46:56,773 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-08-24 15:46:59,442 [base.login:358]:Connecting to GOG
```

### System Information

```shell
[System]
OS:              Ubuntu 22.04 Jammy Jellyfish
Arch:            x86_64
Kernel:          5.19.0-43-generic
Desktop:         Not found
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             31.3 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.108.03
OpenGL Core:     4.6.0 NVIDIA 510.108.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.108.03
Vulkan Version:  1.3.204
Vulkan Drivers:  NVIDIA GeForce GTX 1080 Ti (1.3.194)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Can't repro, paste works fine here.

**Comment by tremby** [comment]
I'm using the i3 window manager, on Xorg, in case it helps. Pasting works fine in other apps.

**Comment by strycore** [comment]
Ok, it's an i3 issue then, open an issue on their bugtracker.

**Comment by tremby** [comment]
I'm not sure what brings you to that conclusion. As I said, I can paste fine in everything else I've ever tried.

**Comment by tremby** [comment]
Oh, did you think by "other apps" I meant "other window managers"? I meant I can paste everywhere I've ever tried in i3 except in this particular Lutris window.

**Comment by strycore** [comment]
Nope, by other apps, I thought of apps that don't use a Gtk Webkit2 widget. The bug is either on i3's side or WebkitGtk but as far as Lutris is concerned, we're not doing anything funny with Webkit, just the standard stuff.

**Comment by tremby** [comment]
OK.

I'm not sure if it might be a clue or it's something totally separate but I also noticed that the "close" x in the top right of that same window does nothing for me.

**Comment by strycore** [comment]
The close button doing nothing issue sounds familiar. Do you have the same issue when running the lastest code from git?

**Comment by tremby** [comment]
This is what I did:

- Cloned git repo (I'm at 97600fdc)
- Read instructions in INSTALL.rst, tried to `sudo apt install python3-yaml python3-requests ....` which failed saying `lib32gcc1` doesn't exist.
- Did a search and chose `lib32gcc-s1` instead; installed the deps
- Ran bin/lutris

And I get the same issues (no pasting, and the close button does nothing). I can use my window manager's close window keybinding to close it.

**Comment by strycore** [comment]
I've removed the lib32gcc part from the install guide (not really necessary). I'll give this a try on a VM with i3.

**Comment by strycore** [comment]
I tested i3 on an Ubuntu 23.04 VM.

- I was able to paste to the webkit dialog without any issue
- The close button for GOG isn't supposed to do anything, it's part of the GOG UI and not the Lutris window. The GOG dialog controls don't show up because that's how i3 does it.

**Comment by strycore** [comment]
I also tested on Ubuntu 22.04. Had no problem pasting either. Note that both VM also have the Gnome desktop installed as well. My guess is that you're missing a dependency to allow pasting.

**Comment by tremby** [comment]
Maybe. I did some searching and I could find only one revevant thing: https://superuser.com/a/939216 suggested which suggests installing xsel and xdotool. I had xsel already. Installing xdotool didn't change anything.

I've now found that if I put something on the clipboard *before* opening the log in window, I can paste it in there. Nothing added to the clipboard when the window is already open can be pasted, however, unless I copy it from within that window.

I'm ready to give up on this. At least I know now that I can copy my password from the password manager before opening the window.

**Comment by strycore** [comment]
If you don't mind, you can try installing the Gnome desktop to see if it resolves the issue. Then remove components gradually until the needed one is found.

**Comment by tremby** [comment]
I tried installing the `gnome` package, which installed many many things. I didn't reboot (unwilling at the moment) but I did restart Lutris and unfortunately no change. In fact, now I can't paste things I've copied within the webkitgtk window either, which makes me think it was probably intermittent before too.

**Comment by strycore** [comment]
Then it's not in Gnome, maybe a X11 library?
