### ISSUE TITLE
[Feature Request] Add `postexit_wait` option similar to `prelaunch_wait`

### ISSUE THREAD

**Issue by nioncode** [lutris/lutris#5005]
Currently you can run a command before / after the game starts / ends, but you can only wait for the command to finish in the prelaunch script. 

It would be great if a similar option existed for waiting for the command to finish in the post exit script and to wait for lutris to stop until that script exits. This can be useful for other apps (or scripts) that invoke lutris to know when all processes that lutris launched have stopped instead of having to track all child processes separately.

**Comment by danieljohnson2** [comment]
What is Lutris doing that needs to be delayed until the post-exit script is done?

Is this just to communicate with other programs? What other programs care about this?

**Comment by nioncode** [comment]
Yes, this is just for other programs that launch lutris to know when 'everything' is done. Otherwise they'd have to integrate some kind of process tracker to check if there are any lingering processes that need to be waited for.

At least it seems like the steam deck has just that in game mode and will wait until the post-exit script is done until it goes back to the home screen, but other launchers or wrappers of lutris might not.

**Comment by danieljohnson2** [comment]
Is there a problem with that? Why do the other launchers need to not go back to their home screens or whatever?

**Comment by nioncode** [comment]
There is no problem per se. It is just a bit weird if you run a lutris game from a script and then the command already returns although only the game has finished and the post-exit commands have not. The usual expectation is that the command finishes when all work is done (and in this situation I'd argue that the post-exit script is part of the work to be done).

Otherwise you could not easily run two lutris games after another, since the next game's before-launch script might conflict with the just stopped post-exit script.

**Comment by danieljohnson2** [comment]
Well, I think it's desirable to have a fire-and-forget script. The one time I used this feature, that was appropriate for me.

I don't see how this idea helps with conflict between one games post-game-script and another's pre-game-script. Surely we're not going to prevent starting any second game because the first one has not closed out yet? That seems awful.

What would this conflict even be?

If we can't get something definite for why we want or need a fire-and-wait-for-it script, then I don't think we should do this.

**Comment by strycore** [comment]
Care to share a real world scenario to help us better understand the requirements or is this just an elaborate fanfic? 

I've never used those features, mostly because if I wanted to run something before / after a game runs, I would just code it in as a feature in the client.

**Comment by nioncode** [comment]
My use case is:
* prelaunch: restore savegame backup from cloud
* postexit: save savegame backup to cloud

The prelaunch script must obviously wait for the restore to be complete, otherwise the game will launch with an outdated savegame (and lutris has an option to wait for that, so this is fine). However, postexit should also wait for the backup to be complete, otherwise you can just launch the game again (or actually any other game, since currently my restore restores all savegames at once) and then the restore can throw all kinds of errors.

I'm not asking to always wait for the completion of postexit, just to add the same option that lutris already has for the prelaunch.

**Comment by strycore** [comment]
Yeah, we going to have save syncing in the client soon. No need to add some special case to handle that in another fashion.
