### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Aerodin** [lutris/lutris#5008]
### Bug description

I try to start Lutris it crashes with no message.  From console:

lutris -d
Segmentation fault (core dumped)

### How to Reproduce

Run Lutris.  Crash with no message.
Run lutris from on console:
lutris -d
Segmentation fault (core dumped)

### Expected behavior

Expected Lutris to run.

### Log output

```shell
lutris -d
Segmentation fault (core dumped)
```

### System Information

```shell
lutris -d
Segmentation fault (core dumped)
```

Running vulkaninfo also results in an error:
vulkaninfo
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 2.  Skipping ICD.
Segmentation fault (core dumped)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
As you may be expecting, there is no information in your report that would help us solve your issue. Sorry.

I suggest you deal with your Vulkaninfo issue first and then see if Lutris still crashes.
