### ISSUE TITLE
segfault on launch ubuntu 22.04.3 

### ISSUE THREAD

**Issue by pmeyerson** [lutris/lutris#5014]
### Bug description

I just started getting a segfault on launch every time now.  I tried the graphics driver installation faq but that didnt seem to help, not sure what to try next.

### How to Reproduce

/usr/games/lutris -d 
<segfault>

### Expected behavior

not crash

### Log output

```shell
/usr/games/lutris -d
2023-09-03 09:36:31,504: Starting Lutris 0.5.9.1
2023-09-03 09:36:31,534: No cores found
2023-09-03 09:36:31,777: Failed to get runtimes: HTTP Error 426: Upgrade Required
2023-09-03 09:36:32,085: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk/releases
2023-09-03 09:36:32,269: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk-nvapi/releases
2023-09-03 09:36:32,508: Failed to read content length on response from https://api.github.com/repos/lutris/vkd3d/releases
2023-09-03 09:36:32,639: Startup complete
INFO     2023-09-03 09:36:32,640 [startup.check_driver:61]:Running Mesa Mesa driver 23.1.0 on llvmpipe (LLVM 15.0.7, 256 bits) (0xffffffff)
[1]    6334 segmentation fault (core dumped)  /usr/games/lutris -d
```

### System Information

```shell
❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
❯ uname -a
Linux desktop 6.2.0-31-generic #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

OpenGL version string: 4.5 (Compatibility Profile) Mesa 23.1.0-devel
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That's a pretty old version of Lutris; could you try the latest release, 0.5.13? You can download the deb for it off of [this page here](https://github.com/lutris/lutris/releases).

**Comment by pmeyerson** [comment]
Thanks for the suggestion!
Didn't seem to help though :(

❯ /usr/games/lutris -d
[1]    12156 segmentation fault (core dumped)  /usr/games/lutris -d

> glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.0-devel
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.0-devel
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.0-devel


Could some of my graphic drivers be messed up somehow? Is there some other command I can try to see?
Maybe this isn't a lutris issue?  Appreciate any other points you can throw my way.

**Comment by danieljohnson2** [comment]
I'd expect 0.5.13 to change the output, if nothing else. I would guess there was more than that one line, yes?

**Comment by pmeyerson** [comment]
It crashes immediately with no additional output now :(

**Comment by danieljohnson2** [comment]
Oh, my. I can't explain that- it should at least print its version number before it does anything that can segfault.

I am not sure what's wrong, but to me it seems like it must be something about GTK. Strange.

Try doing
```
lutris --version
```

Can that print the version number, or does even that crash?

**Comment by pmeyerson** [comment]
I get nothing but core dump on latest.  If I instead install 0.5.12 I get this:

❯ /usr/games/lutris --version
lutris-0.5.12
❯ /usr/games/lutris -d
INFO     2023-09-03 12:45:47,106 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-09-03 12:45:47,150 [startup.check_driver:77]:GPU: 1002:73FF 1458:2336 (amdgpu drivers)
[1]    9919 segmentation fault (core dumped)  /usr/games/lutris -d


I'll try to pick this up later if anyone has more ideas.  Maybe a driver bug??

**Comment by strycore** [comment]
The first output shows llvmpipe as the graphics driver but the 0.5.12 shows amdgpu with a RX 6600 XT. 
It's very likely Lutris is crashing while running a command used to get hardware information such as vulkaninfo or xrandr

**Comment by strycore** [comment]
> 2023-09-03 09:36:31,777: Failed to get runtimes: HTTP Error 426: Upgrade Required

For information, it is **required** to update from 0.5.9.1. The Lutris server will refuse to deliver the needed runtime components to old Lutris versions like this one.

**Comment by mother-brain** [comment]
I am having a similar issue with linux mint 20.2, an amd rx580 and system python 3.11.4.  The repo defaults to  0.5.9.1:
lutris -d
2023-09-09 11:51:16,963: Starting Lutris 0.5.9.1
2023-09-09 11:51:16,982: No cores found
2023-09-09 11:51:17,484: Failed to get runtimes: HTTP Error 426: Upgrade Required
2023-09-09 11:51:17,976: Startup complete
INFO     2023-09-09 11:51:17,977 [startup.check_driver:61]:Running AMD Mesa driver 26591.1.8 on AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.42, 5.15.0-83-generic) (0x67df)
INFO     2023-09-09 11:51:17,977 [startup.check_driver:73]:GPU: 1002:67DF 1462:3417 (amdgpu drivers)
Segmentation fault (core dumped)


 Manually installing lutris0.5.13 segfaults when calling either lutris -d or lutris -version segfaults with no other info

**Comment by strycore** [comment]
what about the current git version? does that segfault too?

**Comment by pmeyerson** [comment]
I saw that vulkaninfo was reporting crash, and trying to resolve dependency conflict for drivers I accidentally uninstalled everything so I'll be working on that. Guessing that is the underlying problem....lutris does require vulkan drivers right?

**Comment by strycore** [comment]
Lutris calls vulkaninfo pretty early during the startup of the program so if Vulkaninfo segfaults, Lutris will likely segfault too.

Glad that you got it sorted out.
