### ISSUE TITLE
[Opensuse TW] Lutris RPM only in English (I want french please )

### ISSUE THREAD

**Issue by Xdavius** [lutris/lutris#5021]
### Bug description

RPM from Opensuse Repository or from Github remain in english on a French system

### How to Reproduce

1- Install lutris from github RPM
2- Launch lutris on a french system
2- Lutris is in English
![Screenshot_20230908_152614](https://github.com/lutris/lutris/assets/66792063/54aa05a9-b114-473f-830c-285697efea4c)

### Expected behavior

Lutris in French (works in debian/arch and flatpak, don't remember on Fedora)

### Log output

```shell
davius@gladius:~> lutris -d

(lutris:7164): dbind-WARNING **: 15:28:49.811: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
INFO     2023-09-08 15:28:50,050 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-09-08 15:28:50,051 [startup.check_driver:73]:Running AMD Mesa driver 23.1.6 on AMD Radeon Graphics (navi22, LLVM 16.0.6, DRM 3.52, 6.4.15-lqx1-1-liquorix) (0x73df)
INFO     2023-09-08 15:28:50,051 [startup.check_driver:85]:GPU: 1002:73DF 1DA2:E445 (amdgpu drivers)
DEBUG    2023-09-08 15:28:50,200 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-09-08 15:28:50,228 [lutris.get_missing_game_ids:191]:Checking for missing games
```

### System Information

```shell
[System]
OS:              openSUSE Tumbleweed 20230906 n/a
Arch:            x86_64
Kernel:          6.4.15-lqx1-1-liquorix
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (navi22, LLVM 16.0.6, DRM 3.52, 6.4.15-lqx1-1-liquorix)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.6
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.6
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6
Vulkan Version:  1.3.261
Vulkan Drivers:  AMD Radeon Graphics (1.3.257)
```

### Media (optional)

Some small pieces are translated, in about lutris. but not the rest
![Screenshot_20230908_153104](https://github.com/lutris/lutris/assets/66792063/93d63f55-6393-444d-8166-2506026a403f)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Our lutris.spec is still using setup.py and hasn't been migrated to Meson yet.

**Comment by strycore** [comment]
This should solve the issue for the next release: https://github.com/lutris/lutris/commit/afe6639ee195e2dac14e3b61be46835f3f23b399

**Comment by Xdavius** [comment]
Thank you! Hope the next release come soon !

**Comment by strycore** [comment]
It's not too far away!
