### ISSUE TITLE
Lutris trying to download wine-ge-lol even though game script doesn't have an explicit wine version

### ISSUE THREAD

**Issue by mmbossoni** [lutris/lutris#5023]
### Bug description

I was installing genshin impact and lutris is trying to download wine-ge-lol even though game script doesn't seem to have any wine version specified.
I have system wine and wine-ge 8-14 installed (and set as default), but lutris refuses to use it

### How to Reproduce

1. Add game
2. Search on lutris for genshin impact
3. Try to install the standard version (3rd option)

### Expected behavior

Lutris use my default wine

### Log output

```shell
2023-09-11 20:27:05,408: Command 'fluidsynth' not found on your system
2023-09-11 20:27:05,736: Starting Lutris 0.5.13
2023-09-11 20:27:05,737: Using NVIDIA drivers 535.104.05 for x86_64
2023-09-11 20:27:05,738: GPU: NVIDIA GeForce GTX 1070
2023-09-11 20:27:05,738: GPU: 10DE:1B81 3842:5173 (nvidia drivers)
2023-09-11 20:27:05,843: Getting runner information for wine
2023-09-11 20:31:27,200: Runner <lutris.runners.wine.wine object at 0x7f0f343afa90> needs to be installed
2023-09-11 20:31:27,213: Getting runner information for wine (version: lutris-ge-lol-p8-12-x86_64)
2023-09-11 20:31:31,440: Download failed: write to closed file
```

Download failed is because I cancelled the download

### System Information

```shell
[System]
OS:              Nobara Linux 38 KDE Plasma
Arch:            x86_64
Kernel:          6.4.10-202.fsync.fc38.x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            16.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.104.05
OpenGL Core:     4.6.0 NVIDIA 535.104.05
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.104.05
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce GTX 1070 (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Can you please try with the current development version? This should be fixed.

**Comment by mmbossoni** [comment]
@strycore , just tried with lutris git.
Still trying to download ge lol for genshin

**Comment by mmbossoni** [comment]
`shell
[marcelo@nobara-pc bin]$ ./lutris --list-wine-versions
2023-09-12 17:53:54,674: Command 'fluidsynth' not found on your system
2023-09-12 17:53:55,104: Starting Lutris 0.5.14
2023-09-12 17:53:55,106: Using NVIDIA drivers 535.104.05 for x86_64
2023-09-12 17:53:55,106: GPU: NVIDIA GeForce GTX 1070
2023-09-12 17:53:55,106: GPU: 10DE:1B81 3842:5173 (nvidia drivers)
{'version': 'lutris-ge-lol-p8-12', 'architecture': 'x86_64', 'url': 'https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-LOL-p8-12/wine-lutris-ge-lol-p8-12-x86_64.tar.xz', 'default': False}
{'version': 'lutris-GE-Proton8-14', 'architecture': 'x86_64', 'url': 'https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-13/wine-lutris-GE-Proton8-13-x86_64.tar.xz', 'default': True}
{'version': 'lutris-osu-2', 'architecture': 'x86_64', 'url': 'https://github.com/lutris/wine/releases/download/lutris-osu-1/wine-lutris-osu-2-x86_64.tar.xz', 'default': False}
{'version': 'lutris-4.21', 'architecture': 'x86_64', 'url': 'https://lutris.nyc3.cdn.digitaloceanspaces.com/runners/wine/wine-lutris-4.21-x86_64.tar.xz', 'default': False}
`

**Comment by mmbossoni** [comment]
interesting thing 2:
my lutris UI says lutris-GE-Proton8-14 is the default
but
```shell
cat ~/.config/lutris/runners/wine.yml 
system:
  game_path: /mnt/dados/marcelo/games/lutris
wine:
  version: lutris-ge-lol-p8-12-x86_64
```

**Comment by strycore** [comment]
you selected the Lol build as the default wine, so it's used as the default wine. 
Lutris is working as expected.

**Comment by mmbossoni** [comment]
Nope, It is not
On my UI the default is wine-ge 8-14, not lol

Em ter., 12 de set. de 2023 18:00, Mathieu Comandon <
***@***.***> escreveu:

**Comment by strycore** [comment]
Run `rm ~/.config/lutris/runners/wine.yml ` and Lutris will act normally.
