### ISSUE TITLE
[Feature Request] Download Folder selection in guy and automatic file selection for gog offline installer

### ISSUE THREAD

**Issue by DDQW** [lutris/lutris#5024]
Hello there,

i had several problems installing games that ended with a source not found error or just excited with code 0 which resulted in the game not being added to the list even though i started it right after installation.

i had somewhat better luck when downloading the installer files first and then selecting them manually but that is pretty tedious.

it would be great if there was an option to save the installers to a specific location and NOT delete them. Especially in cases like bg3 with over 100gig that would be amazing

also it would be great if i could just tell lutris to look for the installer files in a specific folder than to have to add them all manually

**Comment by strycore** [comment]
We have this already, check the menu on top of the installer window

**Comment by DDQW** [comment]
ok then i change my request make it better to find :D i looked in the preferences advances prefs and config files to no avail.

Suggestion:

Add installar as a topic to preferences
-let me specify a folder there
-default to ~Downloads/lutris/gog installers/ or something like that
have a checkbox there to always keep files
-add a point to the context menu to delete downloaded install files

i am pretty sure i am not the only one who would highly appreciate this.

Thanks for your time and the quick reaction

**Comment by strycore** [comment]
I agree, we need to make the feature easier to discover.
