### ISSUE TITLE
refresh Wine available version list without restart Lutris

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#5025]
### Bug description

Lutris does list new Wine installed version until you restart it.

### How to Reproduce

When you install manually or with Proton-QT a new Wine version, then open Lutris Wine "runner options" tab, the new installed Wine version is not available in the list. You have to restart Lutris to see and use the new installed Wine version.

### Expected behavior

When user click and open Wine "runner options" tab, Lutris should refresh available Wine installed list.

### Log output

```shell
not necessary for this issue
```

### System Information

```shell
[System]
OS:              Manjaro Linux 23.0.1 Uranos
Arch:            x86_64
Kernel:          6.3.13-1-MANJARO
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.0 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.6-3
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.6-3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6-3
Vulkan Version:  1.3.255
Vulkan Drivers:  Intel(R) UHD Graphics (CML GT2) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Wine updates are going to be downloaded on startup, it's almost completed. We're not downloading the full list of wine versions, just updating what should be the default one.
