### ISSUE TITLE
Error: Failed to load games. Check that your profile is set to public during the sync.

### ISSUE THREAD

**Issue by jozefcifre** [lutris/lutris#5027]
### Bug description

```
Lutris v0.5.13
Installed on: NixOS 23.05 GNOME (Wayland)
```
I've just installed Lutris and Steam from Flathub and loggedin to Steam, I already have a game installed from Steam, and my profile is public.

![image](https://github.com/lutris/lutris/assets/124826525/d08ab696-fc25-46fa-b0ff-e7f4c6a41434)

The issue is that I am getting this error from the terminal: `RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))`

I ttried to load my games on Lutris, so I clicked on the reload button, but everytime it popups the message: "Failed to load games. Check that your profile is set to public during the sync.".

### How to Reproduce

(If you already have Steam working in Lutris then these steps won't reproduce the error.)

Steps to reproduce the error:
1. Go to your terminal
2. Run `flatpak run net.lutris.Lutris -d`
3. Click on 'Reload' to reload your Steam library
5. See the logs from your terminal: `RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))`

### Expected behavior

It will popup this message: "Failed to load games. Check that your profile is set to public during the sync."

### Log output

```shell
INFO     2023-09-16 16:39:55,706 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-09-16 16:39:55,708 [startup.check_driver:72]:Running Intel Mesa driver 23.1.6 on Mesa Intel(R) UHD Graphics 630 (CML GT2) (0x9bc5)
INFO     2023-09-16 16:39:55,708 [startup.check_driver:84]:GPU: 8086:9BC5 1043:8694 (i915 drivers)
DEBUG    2023-09-16 16:39:57,339 [base.wipe_game_cache:174]:Deleting games from service-games for steam
ERROR    2023-09-16 16:39:57,654 [jobs.target:36]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7f40ee031000>: <class 'RuntimeError'> Failed to load games. Check that your profile is set to public during the sync.
  File "/app/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/lutris/services/base.py", line 141, in do_reload
    self.load()
  File "/app/lib/python3.10/site-packages/lutris/services/steam.py", line 100, in load
    raise RuntimeError(_("Failed to load games. Check that your profile is set to public during the sync."))
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.1.52
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             7.6 GB
Swap:            8.8 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 630 (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.6 (git-0697ac0d75)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.6 (git-0697ac0d75)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6 (git-0697ac0d75)
Vulkan Version:  1.3.224
Vulkan Drivers:  Intel(R) UHD Graphics 630 (CML GT2) (1.3.246)
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/124826525/f3f004c8-fda2-4681-aa79-aeb7bca63f8c)

![image](https://github.com/lutris/lutris/assets/124826525/c2016fca-7fcf-4956-b685-2eed6eb5cdf8)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [x] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [x] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gilvbp** [comment]
same here.

**Comment by liaminventions** [comment]
this is happening to me on the arch pacman package, I can't connect to the steam source, but the steam runner works fine.

**Comment by strycore** [comment]
yeah, those are 2 separate things. If Steam runs on your machine, then the Steam runner will too. Lutris doesn't do much when it comes to Steam games. It launches them but any option set in Lutris won't affect Steam games (gamescope, mangohud, etc). The Steam integration in Lutris is related to the Steam API and not the Steam client on your system. 
There is something causing some public libraries to fail, our best bet in finding the cause of the issue is trying out HTTP queries manually. I can't do that because the Steam integration works for me. 
You can test the lutris.util.steam.config.get_steam_library function with your Steam ID and see what it gives you. 
Or give me your Steam ID and I can try to debug it myself.

**Comment by jozefcifre** [comment]
> Or give me your Steam ID and I can try to debug it myself.

Okay

Steam ID: 76561199549888881

**Comment by strycore** [comment]
> Steam ID: 76561199549888881

" This profile is private. "

**Comment by jozefcifre** [comment]
> > Steam ID: 76561199549888881
> 
> " This profile is private. "

Sorry, I forgot to make it public again. It's now public.

**Comment by strycore** [comment]
Ok, I can see 4 games are returned now. Are they not imported in Lutris?

**Comment by jozefcifre** [comment]
They are imported now. The error is gone both in the nix package and the flatpak. This issue is a bit old, I guess it got fixed already.

Thanks for your help.

(I'm gonna leave this open for now, in case anyone keeps getting the error)

**Comment by strycore** [comment]
I don't think there's a error to keep track of. Profile is private, games don't get imported. Profile is public, games get imported. Everything is working as expected.
