### ISSUE TITLE
Fails to download Duckstation from libretro runner

### ISSUE THREAD

**Issue by mleopold** [lutris/lutris#5031]
### Bug description

Hi,
I'm trying run Duckstation after installing the libretro runner. First I install libretro and then I add a game with libretro as runner under game options I select "Sony - Playstation (Duckstation)". Starting the game lutris asks "install selected runner?" I select yes. This results in an error "Failed to retrieve libretro (duckstation) information

In the debug info the following url is listed. This contains rearmed (that works for me), but not duckstation.
https://lutris.net/api/runners/libretro

Lutris version 0.5.10.1

### How to Reproduce

1. Install libretro runner
2. Create a libretro game with duckstation as runner option
3. Start game
4. See error message aboe

### Expected behavior

For PCX Rearmed it works, the file is downloaded and run

### Log output

```shell
leopold@pluto:~$ lutris -d
INFO     2023-09-21 23:39:31,890 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
DEBUG    2023-09-21 23:39:32,059 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2023-09-21 23:39:32,118 [startup.check_driver:65]:Running Intel Mesa driver 22.2.5 on Mesa Intel(R) HD Graphics 4400 (HSW GT2) (0xa16)
INFO     2023-09-21 23:39:32,118 [startup.check_driver:77]:GPU: 8086:0A16 17AA:2218 (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
INFO     2023-09-21 23:39:32,281 [startup.update_runtime:213]:Startup complete
DEBUG    2023-09-21 23:39:32,461 [lutriswindow.update_store:437]:Showing 2 games
DEBUG    2023-09-21 23:39:55,009 [grid.on_item_activated:57]:Item activated: 13
DEBUG    2023-09-21 23:39:57,349 [runner.install:369]:Installing libretro (version=duckstation, downloader=<function simple_downloader at 0x7fa2e0b48940>, callback=None)
INFO     2023-09-21 23:39:57,349 [runner.get_runner_version:324]:Getting runner information for libretro (version: duckstation)
DEBUG    2023-09-21 23:39:57,349 [http.get:83]:GET https://lutris.net/api/runners/libretro
ERROR    2023-09-21 23:39:59,842 [game.launch:521]:Game is not launchable
```

### System Information

```shell
[System]
OS:              Ubuntu 22.04 Jammy Jellyfish
Arch:            x86_64
Kernel:          5.15.0-78-generic
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.4 GB
Swap:            11.7 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.5
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.5
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Let's make a deal.

You update that decrepit Lutris version and I update Retroarch  and its cores.

You can also install Duckstation from Retroarch itself if you don't accept the terms of the deal.

**Comment by maleopold** [comment]
Hi,
Thanks! I just ran the lutris version from Ubuntu. In either case I updated to the lastest version I could download yesterday 0.5.13 (this particular problem persists regardless).

Is there anything I can do to be of assistance?

Br,
Martin

**Comment by QmwJlHuSg9pa** [comment]
FWIW, I wouldn't expect to find the DuckStation core, as it was removed in 2022. The SwanStation core (a fork) is the closest analogue.

**Comment by strycore** [comment]
That's correct, I've been building updated versions of Libretro cores and Duckstation is no longer available: https://github.com/libretro/duckstation
