### ISSUE TITLE
Flatpak throwing errors about libwebkit2gtk

### ISSUE THREAD

**Issue by Shaddox** [lutris/lutris#5034]
### Bug description

Good evening!

This is rather new and has only started happening since today. I tried refreshing my GoG library and I found that I got booted off the GoG login. I tried to login again, only for nothing to happen. This hasn't happened before and I'm honestly not sure what to do.  I tried to repair the flatpak with `flatpak repair net.lutris.Lutris` but it seems to have done nothing. Running it directly from the binary release seems to be fine, however I don't get to keep any of my  settings or configurations.

Thank you.
Shaddox

### How to Reproduce

1. Go to `Settings` and enable GoG
2. Click on the person portrait in GoG sources list
3. Nothing happens. Button becomes disabled.

### Expected behavior

I remember a window opening asking me for my GoG credentials.

### Log output

```shell
shaddox@pop-os:~$ flatpak run net.lutris.Lutris -d
Gtk-Message: 03:40:01.071: Failed to load module "canberra-gtk-module"
INFO     2023-09-24 03:40:01,102 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-09-24 03:40:01,104 [startup.check_driver:64]:Using NVIDIA drivers 535.104.05 for x86_64
INFO     2023-09-24 03:40:01,105 [startup.check_driver:68]:GPU: NVIDIA GeForce GTX 1060 6GB
INFO     2023-09-24 03:40:01,105 [startup.check_driver:84]:GPU: 10DE:1C03 1043:8619 (nvidia drivers)
DEBUG    2023-09-24 03:40:03,277 [base.login:358]:Connecting to GOG

** (lutris:2): WARNING **: 03:40:03.296: Failed to load shared library 'libwebkit2gtk-4.1.so.0' referenced by the typelib: /app/lib/libudev.so.1: version `LIBUDEV_247' not found (required by /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0)
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/lutris/gui/widgets/sidebar.py", line 202, in on_connect_clicked
    self.service.login(parent=self.get_toplevel())
  File "/app/lib/python3.10/site-packages/lutris/services/base.py", line 359, in login
    dialog = WebConnectDialog(self, parent)
  File "/app/lib/python3.10/site-packages/lutris/gui/dialogs/webconnect_dialog.py", line 23, in __init__
    self.context = WebKit2.WebContext.new()
gi.repository.GLib.GError: g-invoke-error-quark: Could not locate webkit_web_context_new: 'webkit_web_context_new': /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0: undefined symbol: webkit_web_context_new (1)
```
```


### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.4.6-76060406-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Physical cores:  6
Logical cores:   6

[Memory]
RAM:             15.5 GB
Swap:            19.5 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.104.05
OpenGL Core:     4.6.0 NVIDIA 535.104.05
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.104.05
Vulkan Version:  1.3.224
Vulkan Drivers:  NVIDIA GeForce GTX 1060 6GB (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by nirui** [comment]
I came here for exactly the same reason. The non-Flatpak version worked fine on my system (Fedora 38, `dnf install lutris`), but... I really don't want to reconfigure it again just for GOG.

Hope this can be fixed, thanks in advance :)

**Comment by strycore** [comment]
I'm having the same error on the Flathub Beta build which is based from a recent commit of Lutris. 
This is the important part: 
`Failed to load shared library 'libwebkit2gtk-4.1.so.0' referenced by the typelib: /app/lib/libudev.so.1: version `LIBUDEV_247' not found (required by /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0)`

I'm closing this in favor of https://github.com/flathub/net.lutris.Lutris/issues/364
