### ISSUE TITLE
cve high severity path traversal

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5035]
### Bug description

Path Traversal      Snyk Code     CWE-23  Score 812 271 272 273 274 275  

        else:
            service_installers = self.get_installers_from_api(appid)
        # Check if the game is not already installed
        for service_installer in service_installers:
275            existing_game = self.match_existing_game(

Unsanitized input from the HTTP request body flows into shutil.rmtree, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to remove arbitrary files. ‎lutris/services/base.py

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

none

### Log output

```shell
none
```

### System Information

```shell
none
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that code does not use rmtree at all. This looks like a dump of a tools output that got malformed somehow.

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.
