### ISSUE TITLE
 cve Path Traversal

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5036]
### Bug description

        """Retrieve an order identitied by its key"""
        # logger.debug("Getting Humble Bundle order %s", gamekey)
        cache_filename = self.order_path(gamekey)
        if os.path.exists(cache_filename):
            with open(cache_filename, encoding='utf-8') as cache_file:

line 151

Unsanitized input from the HTTP request body flows into open, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to read arbitrary files.

### How to Reproduce

NOT NEEDED

### Expected behavior

NOT NEEDED

### Log output

```shell
NOT NEEDED
```

### System Information

```shell
NOT NEEDED
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that code does not use the web in any way. There's no CVE here a all. This looks like a dump of a tools output, and that tool just bugged out.

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.

**Comment by strycore** [comment]
Please Humble Bundle, don't hack us! I used to buy all your bundles back in the early Humble Indie Bundle days and it's also how I managed to collect a lot of Windows games to test with Lutris!

**Comment by danieljohnson2** [comment]
This is the only one of these spammy requests that *might* point at something; is there some way the game key could contain '/../'? If I knew what a game key looked like, I might add some validation around this. Just in case.
