### ISSUE TITLE
CVE Hardcoded Secret

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5037]
### Bug description

  embed_url = "https://embed.gog.com"
    api_url = "https://api.gog.com"

    client_id = "46899977096215655"
    client_secret = "9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9"
    redirect_uri = "https://embed.gog.com/on_login_success?origin=client"

### How to Reproduce

BLANK

### Expected behavior

BLANK

### Log output

```shell
BLANK
```

### System Information

```shell
BLANK
```

### Media (optional)

BLANK

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
It's weird; this is obviously a dump of machine output, but the omitted fields are getting different excuse values every time, so those parts looks hand-generated.

Anyway, this is not our secret- we're just trying to get the GOG API to work. No CVE here. Garbage.

**Comment by coolst3r** [comment]
> It's weird; this is obviously a dump of machine output, but the omitted fields are getting different excuse values every time, so those parts looks hand-generated.
> 
> Anyway, this is not our secret- we're just trying to get the GOG API to work. No CVE here. Garbage.
 
the variable is literately client secret dont be daft

**Comment by coolst3r** [comment]
just fix it

**Comment by strycore** [comment]
Some people would rather have a non working GOG integration I guess... :rofl: 

If you look at all the game launchers ever created (Heroic, Playnite, GOG Galaxy 3rd party integrations, etc) you'll see they all do the exact same thing as we do.  There is nothing to fix. There is no security vulnerability. Stop freaking out and just enjoy your GOG games.
