### ISSUE TITLE
Use of Password Hash With Insufficient Computational Effort

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5038]
### Bug description

def read_file_md5(filedesc):
    md5 = hashlib.md5()
    for chunk in iter(lambda: filedesc.read(8192), b""):
        md5.update(chunk)
    return md5.hexdigest()

hashlib.md5 is insecure. Consider changing it to a secure hashing algorithm.
[‎lutris/util/system.py](https://github.com/coolst3r/lutris-synk/tree/761c8d7b572dd80a802e3c1132b0b5caad934e53/lutris/util/system.py#L196)

### How to Reproduce

XXXX

### Expected behavior

XXXX

### Log output

```shell
XXXX
```

### System Information

```shell
XXXX
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Now it's a different user with the machine output dump?

We are not using MD5 for anything security related as far as I can see; I think this is fine. If you don't agree, *file a real bug report*.

**Comment by strycore** [comment]
gosh the function is literally called "read_file_md5". What are we supposed to do? Return a sha256 hash instead? :roll_eyes:
