### ISSUE TITLE
CVE SQL Injection

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5039]
### Bug description

            service_installers = self.get_installers_from_api(appid)
        # Check if the game is not already installed
        for service_installer in service_installers:
            existing_game = self.match_existing_game(
                get_games(filters={"installer_slug": service_installer["slug"], "installed": "1"}),

Unsanitized input from the HTTP request body flows into execute, where it is used in an SQL query. This may result in an SQL Injection vulnerability.
[‎lutris/services/base.py](https://github.com/coolst3r/lutris-synk/tree/761c8d7b572dd80a802e3c1132b0b5caad934e53/lutris/services/base.py#L276)
Open this link in a new tab
54 steps in 4 files

### How to Reproduce

"1"}),

### Expected behavior

"1"}),

### Log output

```shell
"1"}),
```

### System Information

```shell
"1"}),
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that code does not use the web in any way. There's no CVE here at all. This looks like a dump of a tools output, and this time your script bugged out and put code in the fields you are ignoring.

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.

**Comment by strycore** [comment]
But what if little Bobby Tables sneaks on your unprotected computer and types `1'); DELETE from games; --` in the search field???

**Comment by danieljohnson2** [comment]
Nothing happens because we are using query parameters, not pasting together SQL strings with literals in them.
