### ISSUE TITLE
Insecure Xml Parser cve

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5040]
### Bug description

    def get_installed_games_content_ids(self):
        installed_game_ids = []
        for game_folder in self.iter_installed_games():
            installer_data_path = os.path.join(self.ea_games_path, game_folder, "__Installer/installerdata.xml")
            if not os.path.exists(installer_data_path):
                logger.warning("No installerdata.xml for %s", game_folder)
                continue
            tree = ElementTree.parse(installer_data_path)
            nodes = tree.find("contentIDs").findall("contentID")
            if not nodes:
                logger.warning("Content ID not found for %s", game_folder)
                continue
            installed_game_ids.append([node.text for node in nodes])
        return installed_game_ids

48:20
ElementTree.parse
/lutris/services/ea_app.py#L48)

### How to Reproduce

48:20

### Expected behavior

48:20

### Log output

```shell
48:20
```

### System Information

```shell
48:20
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that is working on XML, but what's insecure about it? There's no CVE here at all. This looks like a dump of a tools output, and your script is dumping a time (?) into various fields. Needs work, buddy.

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.

**Comment by strycore** [comment]
What's wild is that I blocked @coolst3r before opening my mail client and seeing how many tickets they opened...

**Comment by danieljohnson2** [comment]
Couldn't happen to a nicer 'contributor'. But how'd you know to block him without looking?

**Comment by strycore** [comment]
I read 2 tickets where he was acting like a prick and that was enough.
