### ISSUE TITLE
CVE Incomplete URL sanitization 

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5049]
### Bug description

cache_path = cache.get_cache_path()
        if not _cache_path:
            _cache_path = os.path.join(settings.CACHE_DIR, "installer")
        url_parts = urlparse(self.url)
        if url_parts.netloc.endswith("gog.com"):

Security checks on the substrings of an unparsed URL are often vulnerable to bypassing.
[‎lutris/installer/installer_file.py]
1 step in 1 file

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

3. Do '....'
4. See '....'

### Log output

```shell
2. Click on '....'
3. Do '....'
4. See '....'
```

### System Information

```shell
2. Click on '....'
3. Do '....'
4. See '....'
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that code is not performing a security check. There's no CVE here at all. This looks like a dump of a tools output, and your script deleted some of the prompt text and submitted the rest.

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.
