### ISSUE TITLE
 Medium severity Incomplete URL sanitization  CVE

### ISSUE THREAD

**Issue by coolst3r** [lutris/lutris#5050]
### Bug description

        if self.num_files < 1:
            return
        url = self.files_list[0].url
        url_parts = urlparse(url)
        if url_parts.netloc.endswith(AMAZON_DOMAIN):

Security checks on the substrings of an unparsed URL are often vulnerable to bypassing.
[‎lutris/installer/installer_file_collection.py]
Open this link in a new tab
1 step in 1 file

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

o '....'
4. See '....'
o '....'
4. See '....'

### Log output

```shell
o '....'
4. See '....'
```

### System Information

```shell
o '....'
4. See '....'
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
This makes no sense; that code is not performing any security checks. There's no CVE here at all. This looks like a dump of a tools output, and your script strangely mangled the prompt text and submitted it in the other fields. What happened there?

You need to look at the tools output and figure out if it makes sense, and give us a real bug report if it does.

**Comment by coolst3r** [comment]
fucking clown read security checks on the substrings of an unparsed URL are often vulnerable to bypassing.
[‎lutris/installer/installer_file_collection.py]

**Comment by strycore** [comment]
what the fuck is "bypassing" and why would Amazon or GOG send maliciously crafted URLs?

Oh, wait, I don't care. You're getting blocked from the repo for insulting Lutris contributors and sending bogus security vulnerabilities.

**Comment by strycore** [comment]
Go cry on 4chan and tell them the lutris devs were mean to you :sob:
