### ISSUE TITLE
Weird Lutris' behaviour when launching Steam games.

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#5056]
### Bug description

There are two scenarios:
- when Steam is already running on game launch
- when Luris launches Steam on game launch

In first scenario, when I lauch a game while Steam is already running, Lutris terminates processes related the game launch only after few seconds from launch, although the game itself is in an early stage of launch (processing vulkan shaders, etc.).

In the second scenario, when Steam is not running at the game launch, Lutris opens Steam, processes don't terminate and game time is being calculated properly, but to actually return to Lutris after exiting the game, Steam needs to be closed manually. Also, sometimes game needs to be stopped in Lutris UI (by pressing Stop button) even if Steam is not running anymore.

### How to Reproduce

1st scenario
1. Launch Steam.
2. Launch Lutris with $ lutris -d.
3. Launch any Steam game from within Lutris.
4. See Lutris stops monitoring launched game after just few seconds.

2nd scenario:
1. Launch Lutris with $ lutris -d.
2. Launch any Steam game from within Lutris.
3. See Lutris not closing Steam after exiting the game.
4. Witness Lutris not stopping game related processes even after closing Steam (only sometimes).

### Expected behavior

1st scenario:
Keep monitoring the game until player exits it (properly calculating time spent playing the game).

2nd scenario:
Lutris closes Steam automatically after exiting the game, and closes all game realted processes (without a need to press Stop).

### Log output

------- This is log info with Steam runing prior to game launch:

[pastebin log 1](https://pastebin.com/NgRpacKH)

------- And This is log info with Steam not runing prior to game launch:

[pastebin log 2](https://pastebin.com/ViEPUGGh)

Sorry for pastebin but I was having "message too long" error from GitHub.

### System Information

```shell
[System]
OS:              Linux Mint 21.2 Victoria
Arch:            x86_64
Kernel:          6.2.0-34-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.1 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.113.01
OpenGL Core:     4.6.0 NVIDIA 535.113.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.113.01
Vulkan Version:  1.3.204
Vulkan Drivers:  NVIDIA GeForce GTX 1050 Ti (1.3.242)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
There's like 10 tickets about this already.
We had the "closing Steam" thing at some point, We removed it because it's straight up aggressive and rude.
I'm still wondering why people use Lutris to launch Steam games... There's zero benefit to it.

**Comment by junglized** [comment]
"I'm still wondering why people use Lutris to launch Steam games... There's zero benefit to it." - the benefit is to have all games in one place, neatly organized, for convienience sake, if that wasn't obvious. Correct me if I'm wrong but that's what Lutris is for, after all. Also, if there are no benefits of launching Steam games from Lutris why to have Steam integration at all?

**Comment by strycore** [comment]
Lutris predates both Steam for Windows and Proton. Not that long ago, it was really useful to have a good integration with Steam for Windows. With Proton, launching any game was basically the same as launching a Linux native game. Lutris always had limited usefulness for Linux games launched from Steam because Lutris can only tell Steam to launch a game and cannot interfere with any of its configuration. Now, in the age of the Steam Deck, the reverse integration, being able to create Lutris shortcuts in Steam, is far more useful.

It's not excluded that we integrate with a tool like SteamTinkerLaunch in the future, allowing us to have better control over Steam games.
Also, we will eventually implement alternative process monitors. For Steam for example, we can track the status of a game from a file in the Steam folder. We already use that method to track installation of Steam games (for games that get the Steam data and run with another engine). What we don't have is a way to swap the existing process monitor with something totally different.

**Comment by Nama** [comment]
@strycore 
The benefit of launching steam game from lutris is to have gamemode and an fps limit set for all games without the need to add the launch parameter to every single game I have on my library.

**Comment by strycore** [comment]
@Nama that's only going to work if you don't have Steam launched before running the game in Lutris. You might just modify your Steam launcher to prepend gamescope to the command and you would have more consistent results without the need for Lutris.

Once we have the possibility to change the launch options of a Steam game and add the ability to use Protontricks, Steam integration will be much more useful.

**Comment by Nama** [comment]
Thanks, guess editing the launcher is the best way atm.

**Comment by junglized** [comment]
@strycore Thanks for detailed explanation. And also your recent Patreon post saddened me greatly. Hope Lutris won't dissapear anytime soon.

**Comment by strycore** [comment]
Nothing to worry about! Lutris is open source and as such it can survive without funding or even my intervention!
