### ISSUE TITLE
Duplicate Message Definitions in Turkish Translations

### ISSUE THREAD

**Issue by prikhi** [lutris/lutris#5062]
Builds are broken from dupe messages in translation files.

```
[10/16] Generating po/tr/LC_MESSAGES/lutris-tr.mo with a custom command
FAILED: po/tr/LC_MESSAGES/lutris.mo 
/usr/bin/msgfmt -o po/tr/LC_MESSAGES/lutris.mo ../lutris/po/tr.po
../lutris/po/tr.po:483: duplicate message definition...
../lutris/po/tr.po:92: ...this is the location of the first definition
../lutris/po/tr.po:858: duplicate message definition...
../lutris/po/tr.po:92: ...this is the location of the first definition
../lutris/po/tr.po:1226: duplicate message definition...
../lutris/po/tr.po:975: ...this is the location of the first definition
/usr/bin/msgfmt: found 3 fatal errors
```

_Originally posted by @prikhi in https://github.com/lutris/lutris/issues/5059#issuecomment-1751802111_

**Comment by BatuHanHub** [comment]
Hello, first of all i'm so sorry for the problem that happened. I'm new to this and i fixed the error and now it should work. Again sorry for the problem. 🙏

**Comment by danieljohnson2** [comment]
I've merged the new PR and tried running msgfmt; it looks good to me. Please try it again and see if it builds now for you.

**Comment by danieljohnson2** [comment]
OK, you've posted that the build is not broken now, so I will close this item for you.

**Comment by prikhi** [comment]
> Hello, first of all i'm so sorry for the problem that happened. I'm new to this and i fixed the error and now it should work. Again sorry for the problem. 🙏

It's okay! I install git builds to not only get the latest stuff but also so I can help flag problems like this! Confirmed your fix as working.
