### ISSUE TITLE
GOG games are way too big

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5075]
The new progress bar shows total sizes that are several times larger than what they should be. 

Here, Metro Exodus showing as a 1.1TB download 

![image](https://github.com/lutris/lutris/assets/280336/967907f7-912e-4cf4-be60-dca6461753f1)

Cyberpunk was around 2TB

**Comment by strycore** [comment]
GOG doesn't give the size of individual files of the download, it gives the total size of the game.
So that size was getting multiplied by the number of files in the download!

**Comment by danieljohnson2** [comment]
Is that what that was?

I saw this happening but couldn't get  repro on it.

**Comment by strycore** [comment]
> I saw this happening but couldn't get repro on it.

you were maybe installing GOG games that were too small?

**Comment by danieljohnson2** [comment]
I saw that sometimes the download would be finished before the progress bar was full, but couldn't figure out why. Did not notice that the total size was too big, but I bet that's what was happening.

**Comment by strycore** [comment]
At first, the downloads would only show in MB, which resulted in huge numbers. So I had to enhance the bug to show proper units like TB when needed.

**Comment by strycore** [comment]
And yes, the download will finish when it reaches the actual size of the game, which would be a fraction of the progress bar.
