### ISSUE TITLE
Sorting by name is wrong with capital letters

### ISSUE THREAD

**Issue by WendelVolm** [lutris/lutris#5076]
### Bug description

When sorting game list by name they get sorted case sensitive, e.g.

DARK
Demons
Darksiders

Many games write their name capitalized for stylistic reasons

### How to Reproduce

1. Open list of games
2. Sort by name
3. Find games that are ALL CAPS
4. Observe wrong sorting

### Expected behavior

Would expect;

```
Demons
DARK
Darksiders
```

Instead of;

```
DARK
Demons
Darksiders
```

### Log output

```shell
INFO     2023-10-17 11:21:29,283 [startup.init_lutris:237]:Starting Lutris 0.5.13
```

### System Information

```shell
[System]
OS:              GNOME 45 Flatpak runtime
Arch:            x86_64
Kernel:          6.5.4-t2-lunar
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             7.6 GB
Swap:            6.0 GB
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/26125511/055483ab-2de5-474f-a91e-e507aa6dbaa0)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I can confirm this bug. 

@danieljohnson2 any clue as to why sort_func in store.py is only used for the list view and not the grid view?

**Comment by danieljohnson2** [comment]
I think that sort_func is being used to support sorting by clicking on the headers, and that overrides the normal sorting rules (like 'installed games first'); the issue here is in our fancy-pants sort.

It's the function natural_sort_key that is missing a call to .casefold().

I'll fix it.
