### ISSUE TITLE
wine prefix detection fails in runners/wine.py if configured prefix has unexpanded `~` in path

### ISSUE THREAD

**Issue by bsdf** [lutris/lutris#5078]
### Bug description

The [wine prefix detection code](https://github.com/lutris/lutris/blob/a9f8bde0833699a62a0afa1c31210e3eb83cd16e/lutris/runners/wine.py#L907) in `runners/wine.py` does not properly expand the `~` character to the user's home dir and fails to launch the game.

This doesn't appear to be an issue with newly created configurations since it appears that Lutris now expands the directory before saving it to the config file. At some point, however, Lutris was saving the unexpanded paths and these older configurations fail to launch.

### How to Reproduce

1. Find an installed wine runner game where the configured prefix contains `~` (`grep -R 'prefix: ~' ~/.config/lutris/games`) OR manually edit a game configuration to contain `~`
2.  Attempt to launch the identified game
3. Observe `No valid prefix detected` in log messages
4. Observe Lutris hanging and game not launching (`create_prefix` appears to be failing as well)

### Expected behavior

* `~` is properly expanded and configured wine prefix is successfully detected.
* Game is launched with configured prefix

### Log output

```shell
INFO     2023-10-17 17:46:55,000 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-10-17 17:46:55,003 [startup.get_drivers:70]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.0-1-amd64) (0x73ff)
INFO     2023-10-17 17:46:55,003 [display.display_gpu_info:78]:GPU: 1002:73FF 148C:2412 (amdgpu drivers)
DEBUG    2023-10-17 17:46:55,551 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-10-17 17:46:56,692 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-10-17 17:47:02,268 [grid.on_item_activated:95]:Item activated: 268
WARNING  2023-10-17 17:47:02,355 [wine.prelaunch:908]:No valid prefix detected in ~/Games/common-prefix-lutris-ge, creating one...
INFO     2023-10-17 17:47:02,356 [wine.create_prefix:98]:Creating a win64 prefix in ~/Games/common-prefix-lutris-ge
DEBUG    2023-10-17 17:47:02,356 [system.execute:74]:Executing /home/bsdf/.local/share/lutris/runners/wine/wine-ge-8-20-x86_64/bin/wineboot
DEBUG    2023-10-17 17:47:02,357 [system.execute:80]:WINEARCH=win64 WINEPREFIX=~/Games/common-prefix-lutris-ge WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/bsdf/.local/share/lutris/runners/wine/wine-ge-8-20-x86_64/mono WINE_GECKO_CACHE_DIR=/home/bsdf/.local/share/lutris/runners/wine/wine-ge-8-20-x86_64/gecko
WARNING  2023-10-17 17:47:32,927 [wine.create_prefix:149]:Wine prefix creation is taking longer than expected...
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux n/a trixie
Arch:            x86_64
Kernel:          6.5.0-1-amd64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            20.5 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.0-1-amd64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon RX 6600 XT (RADV NAVI23) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Can you remediate this by just opening up the game config and re-saving it in a current Lutris version?

I suspect that may rewrite all the paths with expanded versions. You might have to view the problem path before saving though, not sure.

**Comment by bsdf** [comment]
> Can you remediate this by just opening up the game config and re-saving it in a current Lutris version?

the configuration file doesn't save unless you change the prefix path, so it ends up being a two step process of setting it to a temporary folder, then setting it back to the proper prefix path. this might be an acceptable workaround for a few configs, but i apparently had over 50 with an unexpanded path.

further, there's no indication that anything is wrong unless you're looking in the logs. Lutris will hang (in `create_prefix` i believe, though i haven't debugged) and eventually time out after quite a long time.

i did a global search and replace to fix my issue, but i don't necessarily think that's a proper workaround for a non-technical user

**Comment by strycore** [comment]
I added user expansion to system.path_exists() because I think it's a good think to have but that doesn't guarantee this will fully work in Wine. It may just move the problem elsewhere.

**Comment by strycore** [comment]
Also added user expansion in create_prefix so this should cover everything.
