### ISSUE TITLE
Unable to import flatpak steam games to lutris

### ISSUE THREAD

**Issue by Sheepmister** [lutris/lutris#5079]
### Bug description

i found that lutris does not recognized game that is installed in steam it says not installed ii need help guys im new to linux

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

unable to import

### Log output

```shell
n/a
```

### System Information

```shell
feroda 37 intel hd 4600
```

### Media (optional)

n/a

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Support for Flatpak runners has been improved in 0.5.14 which is about to be released. Lutris (native and Flatpak) should be able to see Steam games (native or Flatpak)
