### ISSUE TITLE
how to run steam games through wine prefix

### ISSUE THREAD

**Issue by Sheepmister** [lutris/lutris#5082]
### Bug description

sorry for asking this because im noob i cant get steam to work in using wine cause it says you must connected to steam to able to play the game i wonder if wine prefix will work in this cause i  only add the game from executable file

im so noob i hope someone will guide me step by step

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

n/a

### Log output

```shell
n/a
```

### System Information

```shell
feroda 38
```

### Media (optional)

![Screenshot from 2023-10-20 10-38-42](https://github.com/lutris/lutris/assets/117000146/cc6c865f-ca33-4be3-b2a7-180dd50b1c99)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Running Steam games without Steam is only possible for games that don't use the Steam DRM. 
You can get a list of DRM free games here: https://www.pcgamingwiki.com/wiki/List_of_DRM-free_games_on_Steam 

or here: https://www.pcgamingwiki.com/wiki/The_big_list_of_DRM-free_games_on_Steam

There are also some Lutris installers that pull the game data from Steam but run the game with an open source engine. Most of the time the engine will be Linux based so it won't require wine.

**Comment by Sheepmister** [comment]
> Running Steam games without Steam is only possible for games that don't use the Steam DRM. You can get a list of DRM free games here: https://www.pcgamingwiki.com/wiki/List_of_DRM-free_games_on_Steam
> 
> or here: https://www.pcgamingwiki.com/wiki/The_big_list_of_DRM-free_games_on_Steam
> 
> There are also some Lutris installers that pull the game data from Steam but run the game with an open source engine. Most of the time the engine will be Linux based so it won't require wine.

is there any workaround for a fix i really wanted to play this game

**Comment by strycore** [comment]
This one? https://store.steampowered.com/app/2305790/1v1LOL/

This looks like a multiplayer game so it's probably using the Steam backend for matchmaking.
Games that can run without Steam are usually single player. 

If you really need to run a game with our wine build for some reason, you still have the option to install the Windows version Steam. It doesn't work very well but it's an available option.

**Comment by Sheepmister** [comment]
> This one? https://store.steampowered.com/app/2305790/1v1LOL/
> 
> This looks like a multiplayer game so it's probably using the Steam backend for matchmaking. Games that can run without Steam are usually single player.
> 
> If you really need to run a game with our wine build for some reason, you still have the option to install the Windows version Steam. It doesn't work very well but it's an available option.

thanks

**Comment by Sheepmister** [comment]
> This one? https://store.steampowered.com/app/2305790/1v1LOL/
> 
> This looks like a multiplayer game so it's probably using the Steam backend for matchmaking. Games that can run without Steam are usually single player.
> 
> If you really need to run a game with our wine build for some reason, you still have the option to install the Windows version Steam. It doesn't work very well but it's an available option.

thank you its working now i use exe installer steam from lutris can you help me howto lower the resolution of the game using argument option in steam i use this option in launcher option -w 1280 -h 720

**Comment by strycore** [comment]
if the game has those options you can copy them in the arguments field
