### ISSUE TITLE
how to change lutris to lower resolution im using integrated graphics card

### ISSUE THREAD

**Issue by Sheepmister** [lutris/lutris#5083]
### Bug description

i want to set the game resolution to 1280x720 i hope you can help me

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

n/a

### Log output

```shell
n/a
```

### System Information

```shell
feroda 38 intel hd graphics 4600
```

### Media (optional)

n/a

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I would say use Gamescope but Gamescope has some issues when running on low end Intel iGPUs. Maybe with the latest version, and latest intel drivers things have improved. 

I'm afraid that on this kind of hardware, changing your desktop resolution to 720p is your best bet.
