### ISSUE TITLE
lutris doesn’t handle relative paths properly

### ISSUE THREAD

**Issue by mc711** [lutris/lutris#5089]
### Bug description

with recent big update, all game configs were updated/refreshed, 

all /home/deck paths were converted to ~

but after the conversion, lutris fails to handle the relative path conversion which results in a “no such file or directory” error

game config still reads /home/deck but config files contain the relative path

after a config re-save, configs save path to file as /home/deck

### How to Reproduce

1. update lutris
2. try to launch game
3. get error

### Expected behavior

lutris should recognize the relative path for ~ to the user’s home directory

### Log output

```shell
no log required
```

### System Information

```shell
steam deck lutris flatpak
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I don't understand where all these ~s are coming from, but you aren't the only one seeing this.

I've tried to expand these ~s where it matters, as best I can. It's not pretty, but it might fix this; though I don't know how you can try it until an updated flatpak is published.

**Comment by mc711** [comment]
for the time being, the easiest fix besides going into every config file.

if you get the error. in GUI, go into the game config and add (if none) or remove (if present) a "/" (without quotes)  at the end of the prefix directory and saving. it's redundant, but it will force a config file update.

example

launching game causing error, but config file reads
~/prefix/test

but in lutris GUI config it still shows full path
/home/deck/prefix/test or /home/deck/prefix/test/

using the fix, change to
/home/deck/prefix/test/ or /home/deck/prefix/test

then save

config file will update to true path

my guess, something is causing a config scan/refresh when lutris loads game configs, but converts home directory to the relative path...

i only encountered this recently on the big feature update, so some recent commit might have caused the issue.

**Comment by strycore** [comment]
> all /home/deck paths were converted to ~

no?

**Comment by inpv** [comment]
Can confirm that Lutris overwrote all game YML configs and now cannot read relative paths with the "~" that it added instead of "/home/user".

**Comment by strycore** [comment]
This will be fixed in 0.5.15 (it's already available on Flathub Beta)
