### ISSUE TITLE
"lutris expected str, bytes or os.PathLike object, not NoneType" when lauching games

### ISSUE THREAD

**Issue by l29utp0** [lutris/lutris#5091]
After updating can't launch any game, flatpak version, reverted to older version commit 2f136c4f3febc2f3243c85579c335277eb6047eb4a6cc82801ea1da2dd103355 and it works.

**Comment by danieljohnson2** [comment]
I can't seem to find that commit.

Can you give us Lutris' log output? Run lutris with the -d option to get the most output, and send us the terminal spam you get. I'd expect to get a trade-back that will help fix this.

**Comment by l29utp0** [comment]
![image](https://github.com/lutris/lutris/assets/50279324/c6a5701b-86f3-4abe-97f7-2bfa2689dda0)

**Comment by danieljohnson2** [comment]
Ah, that's in the lurtis/net.lutris.Lutris repo!

But that doesn't really help, since the commit you are avoiding here is the one that merges on 0.5.14, which does not narrow it down much.

That debug log would probably help more than this. If you need to provide just a commit, provide one in the lutris/lutris repro instead and that might work, but you'd have to bisect it I think, which would be a lot more work. Let's try that debug log.

**Comment by l29utp0** [comment]
ok ok I didn't want to update and downgrade it again :p

here you go:
```
  File "/app/lib/python3.11/site-packages/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 665, in configure_game
    self.start_game()
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 721, in start_game
    self.game_thread.start()
  File "/app/lib/python3.11/site-packages/lutris/command.py", line 144, in start
    self.game_process = self.execute_process(wrapper_command, env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/command.py", line 229, in execute_process
    return subprocess.Popen(  # pylint: disable=consider-using-with
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1870, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 812, in fsencode
TypeError: expected str, bytes or os.PathLike object, not NoneType
DEBUG   [application.on_game_stop:721]:Removing 24 from running IDs


```

**Comment by danieljohnson2** [comment]
Thanks, that helps. That shows that you've got ``None`` for one of the values of one of your environment variables at that point. The question is which one, and how that happened. I'll keep looking at this.

The full debug output might have a clue about this in it, but this is enough for me to get started.

**Comment by l29utp0** [comment]
there are a like a dozen older issues on this repo with the same error, might be related

**Comment by danieljohnson2** [comment]
Perhaps not; it's a None where it shouldn't be, but I don't recall a None in *this* spot before. It's a fairly generic kind of thing.

**Comment by l29utp0** [comment]
https://github.com/lutris/lutris/commit/af9ceaa31a3ca705cd48cb57fc9aad3247daef82

???

**Comment by danieljohnson2** [comment]
Looks like a clear-cut  bug- that "r" and "w" are not filenames but modes, for reading and writing. Joining them to the path is just wrong.

**Comment by danieljohnson2** [comment]
OK, I've located a point where I can improve this anyway. I've done a new commit that will intercept any non-string env var values and handle them, with logging to tell us which env-var is going wrong.

If you can use the master branch, you could run this and see which env-var is bogus. But that may be hard- you are using flatpak, so if you just download the master branch, it won't see your game database.

You could try grafting my updated command.py file into the (latest) flatpak install. It's [this one](https://github.com/lutris/lutris/blob/master/lutris/command.py) if you are feeling adventurous.

**Comment by l29utp0** [comment]
it works with your updated command.py

**Comment by danieljohnson2** [comment]
It should have printing debug messages that tell us what env-var needed to be fixed. Can you find that for me?

**Comment by l29utp0** [comment]
`WARNING[command.get_environment:136]:Environment variable 'STEAM_COMPAT_DATA_PATH' has None for its value; skipping.
`

**Comment by Hell01World** [comment]
I have the same problem as l29utp0 when using lutris-GE-Proton8-15, but it works fine with wine-ge-8-20. This error happened when I updated Lutris from Flatpak to the latest version.

**Comment by danieljohnson2** [comment]
Okay, I see it now. There's a missing check when setting that env-var; it is set to the Wine prefix, but if the prefix was not set and could not be guessed, it winds up being set to None and hilarity ensues. I'll add that check.

So, @Hell01World, you should be able to work around this by setting the 'Wine prefix' in game configuration, I think. That's on the Game Options tab; set that to the game directory, which itself contains the 'dosdevices' and 'drive_c' subdirectories.

**Comment by l29utp0** [comment]
thank you :)
