### ISSUE TITLE
[Bug] "Open bash terminal" freezes Lutris

### ISSUE THREAD

**Issue by BrandowLucas** [lutris/lutris#5093]
Selecting the "Open bash terminal" when using any terminal other than gnome-terminal (like Konsole, Alacritty, Terminator, xterm etc..) freezes Lutris completely letting it unusable until you close the terminal window.

**Comment by danieljohnson2** [comment]
Oh, that's not right. We need to spawn a process here, not start one and block on it. I'll change that over.

**Comment by strycore** [comment]
Don't know if that's related but the Open Bash Terminal feature no longer works

**Comment by danieljohnson2** [comment]
Hmm. It works for me. I'm on Nobara; maybe you could toss me a debug log for this, if you don't want to debug it yourself?

**Comment by strycore** [comment]
There's an issue with the environment variables we provide in run_in_term.sh, I can fix it.

**Comment by strycore** [comment]
This is fixed, BASH_FUNC_* variables were causing havoc in the run in terminal script so they've been filtered out.

Any value containing newlines may also cause similar issues.
