### ISSUE TITLE
[Feature request] Add option to browser prefix for wine games

### ISSUE THREAD

**Issue by h0x32** [lutris/lutris#5096]
### Bug description

Hello,

I would like to suggest to suggest a feature to allow anyone to browser a prefix
upon pressing the right mouse button on a wine game/app, this feature would make it easier
for anyone to quickly edit settings or files that exist on the prefix.

We already have the option to "Browser Files" which opens the directory of the game/app itself,
so it would be great to have another option underneath it called "Browser Prefix" or however
you want to call it.

### How to Reproduce

N/A

### Expected behavior

N/A

### Log output

```shell
N/A
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.5.8-273-tkg-linux-tkg-pds
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.8-273-tkg-linux-tkg-pds)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-arch1.2
Vulkan Version:  1.3.264
Vulkan Drivers:  AMD Radeon RX 6600 XT (RADV NAVI23) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Hang on. Aren't those the game directory and the prefix normally just the same directory? When are they different?

**Comment by h0x32** [comment]
For example, i separate the game's wine prefix and the game directory itself,
this way i can have one prefix for all my games let's say in a certain category.

And from time to time i backup this prefix, which would be holding all save files for all of the games that share that prefix.

**Comment by danieljohnson2** [comment]
Oh, I see.

Might be a useful feature, if marginal. I'd be inclined to put the "Browse prefix" option under the special Wine menu rather than the main context menu. Does that sound okay?

**Comment by h0x32** [comment]
Yes, absolutely okay!

**Comment by strycore** [comment]
Instead of having a "Runner Action" implemented, it would be neat to add a "Browse" button on all FileChooserEntry widgets

**Comment by danieljohnson2** [comment]
We *do* have a browse button on all FileChooserEntry widgets. It doesn't do what "Browse files" in the context menu does. It selects a new path for the entry; "Browse files" opens Nautilus or whatever.

One of us doesn't understand what's being asked for here, I think.

**Comment by strycore** [comment]
Well, we do have a "Browse" button but that opens a file picker whereas this ticket is about opening a file browser like Nautilus or Dolphin. So we would need *another* browser button and hopefully come up with some clever naming so the 2 are clear in what they do.

**Comment by strycore** [comment]
Days since I've wished I had an "Open in file browser" button: 0

Here's a suggestion:
- Replace "Browse" with "...", add "select a file / folder" as a tooltip depending on the type of widget
- Add a button with a folder icon and with tooltip "Open in file browser"
- The open folder button is disabled if no path is provided or a non existent one.

**Comment by danieljohnson2** [comment]
OK, I think I've pretty much got it as you indicate, @strycore. Icon buttons (circular!) with triple dot to browse, and a folder to open the folder. Tooltips. Open folder is disabled when no folder can be found.

I'd like to (for files) open the containing folder and select the file, but I do not know how. 'xdg-open' does not seem to be able to do that. So that's not there yet.

![image](https://github.com/lutris/lutris/assets/6507403/6a174c07-f93f-43a4-b163-4b1ff0e1c3b6)

**Comment by strycore** [comment]
that's awesome!!

**Comment by danieljohnson2** [comment]
Thank you. Circles are always the way.

**Comment by h0x32** [comment]
thank you, awesome work! even better than i imagined
