### ISSUE TITLE
[Feature request] Provide a way to reinstall/update GoG games

### ISSUE THREAD

**Issue by The-Corrupted** [lutris/lutris#5098]
A number of games on GoG do not release updates via separate update files but instead by replacing the game installer file with the new version. At the moment this means if you want to update one of the games that does this you have two options:

1.) Remove the entire game including whatever saves/profiles may be present and go through the installation process again (optionally backing up any game data you might still want/need).

2.) Update the game manually by downloading and running the new installer, pointing it to wherever your game is currently installed.

It would be nice if we were given a "reinstall" option or if the update option allowed you to select the installer in addition to whatever update files might be available.

**Comment by strycore** [comment]
I'm assuming this is about the Cyberpunk 2.0 update.
Apparently, we're missing an update mechanism that is present in Galaxy and lgogdownloader. 
It's tracked at https://github.com/lutris/lutris/issues/5032 so we can follow its development there.

**Comment by The-Corrupted** [comment]
> I'm assuming this is about the Cyberpunk 2.0 update. Apparently, we're missing an update mechanism that is present in Galaxy and lgogdownloader. It's tracked at #5032 so we can follow its development there.

No, this is in regards to games like Cloud Meadow, Third Crisis, HROT, Chained Echoes, etc. They seem to release updates by updating the installer rather than releasing patches/update files. I don't know about these updates unless I visit the GoG website and I don't have a good way of updating my current install from lutris.

That said, the Cyberpunk 2.0 issue sounds similar to/the same as what I'm experiencing with these games. Thanks for the reply.

**Comment by strycore** [comment]
Ok, so it is very similar to the Cyberpunk situation indeed. 

I found out that there is a way to update and manage GOG games installed with Lutris in GOG Galaxy. 
Once you have installed Galaxy, you can detect installed games. Point the GOG scanner to the prefix of the game you want to update and it should find it. (It should be located in the Z: drive from Wine's perspective)

This is a nice workaround to wait for a better implementation in Lutris
