### ISSUE TITLE
[Feature request] Add option to launch taskmgr of the selected app/game

### ISSUE THREAD

**Issue by h0x32** [lutris/lutris#5099]
Hello,

I've encountered a high memory usage issue, leading to Out of Memory (OOM) triggers when attempting to install "STAR WARS: Squadrons" through EA-APP. This problem is caused by EA-APP spawning an excessive number of easyanticheat.exe processes. Notably, this issue is not attributed to Lutris but stems from another source that I'm currently investigating.

Fortunately, I've devised a workaround to resolve this problem. By terminating all easyanticheat processes, the installation can be marked as successful in EA-APP. To accomplish this, I first access the special wine context menu and select "Open Bash terminal." This action provides me with a shell environment configured with all the necessary prefix settings. From there, I employ the command "wine taskmgr" to initiate the wine task manager and implement my workaround.

In situations where a particular executable or application misbehaves, it would be immensely beneficial to have the option to terminate that specific process without having to shut down the entire wineserver associated with the given prefix. Could you consider adding an option in the special context wine menu, perhaps labeled as "Open Wine TaskManager" or "Open Wine TaskMgr," to facilitate this process?

**Comment by strycore** [comment]
I want to have a process manager at some point but I'm not sure wine's process manager would be the best option for that.
- It's specific to Wine games
- It wouldn't list a lot of Wine's background processes (services.exe, etc)

**Comment by h0x32** [comment]
> It's specific to Wine games
Could you elaborate more on this?

> It wouldn't list a lot of Wine's background processes (services.exe, etc)

Although it wouldn't list a lot of wine's background processes, I think for the most part it will be helpful in aiding against aggressive installation processes or typical win32 applications misbehavior.

**Comment by h0x32** [comment]
it's crucial to have the option to terminate uncooperative processes quickly, especially when time is a factor. Access to wine taskmgr is essential for resolving such issues efficiently.

**Comment by strycore** [comment]
I've added Wine's task manager to the Wine actions. We'll have another task manager at some point but this will require a lot more coding.
