### ISSUE TITLE
[Errno 2] No such file or directory: user.reg

### ISSUE THREAD

**Issue by ShadowJuubei** [lutris/lutris#5101]
### Bug description

I upgraded from lutris_0.5.13beta2_all to lutris_0.5.14_all
Multiple installed games no longer work with the same error of not finding 'user.reg'.
The rest open correctly.
I have checked and the file exists.
I renamed the file and during game start it recreated it but still fails with the same error.
More than half the games suffer this problem.
Downgrading back to lutris_0.5.13_all (non beta) fixes the problem.

### How to Reproduce

Upgrade to lutris 0.5.14 and open games.

### Expected behavior

games start

### Log output

```shell
INFO     2023-10-25 19:04:21,706 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-10-25 19:04:21,708 [startup.get_drivers:70]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.54, 6.5.5-060505-generic) (0x731f)
INFO     2023-10-25 19:04:21,709 [display.display_gpu_info:78]:GPU: 1002:731F 1DA2:E411 (amdgpu drivers)
DEBUG    2023-10-25 19:04:22,765 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-10-25 19:04:25,618 [lutris.get_missing_game_ids:202]:Checking for missing games
ERROR    2023-10-25 19:04:30,485 [jobs.target:33]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f5374ed6fd0>>: <class 'FileNotFoundError'> [Errno 2] No such file or directory: '~/Games/guild-wars-2/user.reg'
File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 31, in target
result = self.function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 915, in prelaunch
self.sandbox(prefix_manager)
File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1062, in sandbox
wine_prefix.enable_desktop_integration_sandbox(desktop_dir=self.runner_config.get("sandbox_dir"))
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 163, in enable_desktop_integration_sandbox
self.enable_desktop_disintegration()
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 192, in enable_desktop_disintegration
desktop_folders = self.get_desktop_folders()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 147, in get_desktop_folders
folder = self.get_registry_key(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 116, in get_registry_key
registry = WineRegistry(self.get_registry_path(key))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 86, in __init__
self.parse_reg_file(reg_filename)
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 113, in parse_reg_file
registry_lines = self.get_raw_registry(reg_filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 103, in get_raw_registry
with open(reg_filename, "r", encoding='utf-8') as reg_file:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    2023-10-25 19:04:30,514 [exceptions.wrapper:103]:Guild Wars 2 (wine) has encountered an error: [Errno 2] No such file or directory:'~/Games/guild-wars-2/user.reg'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 97, in wrapper
result = function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/game.py", line 699, in configure_game
raise error
File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 31, in target
result = self.function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 915, in prelaunch
self.sandbox(prefix_manager)
File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1062, in sandbox
wine_prefix.enable_desktop_integration_sandbox(desktop_dir=self.runner_config.get("sandbox_dir"))
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 163, in enable_desktop_integration_sandbox
self.enable_desktop_disintegration()
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 192, in enable_desktop_disintegration
desktop_folders = self.get_desktop_folders()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 147, in get_desktop_folders
folder = self.get_registry_key(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 116, in get_registry_key
registry = WineRegistry(self.get_registry_path(key))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 86, in __init__
self.parse_reg_file(reg_filename)
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 113, in parse_reg_file
registry_lines = self.get_raw_registry(reg_filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/lutris/util/wine/registry.py", line 103, in get_raw_registry
with open(reg_filename, "r", encoding='utf-8') as reg_file:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/Games/guild-wars-2/user.reg'
DEBUG    2023-10-25 19:04:30,515 [application.on_game_stop:721]:Removing 1 from running IDs
DEBUG    2023-10-25 19:05:08,406 [application.show_window:359]:Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f5375611180 (LutrisWindow at 0x22ecae0)>}
DEBUG    2023-10-25 19:05:32,987 [application.on_app_window_destroyed:377]:Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f5375611180 (LutrisWindow at 0x22ecae0)>}
```

### System Information

```shell
[System]
OS:              Ubuntu 23.10 Mantic Minotaur
Arch:            x86_64
Kernel:          6.5.5-060505-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700X Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.2 GB
Swap:            64.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.54, 6.5.5-060505-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1ubuntu3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon RX 5700 XT (RADV NAVI10) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
Well, the path it's trying to open is '~/Games/guild-wars-2/user.reg' and that is not really a valid path; the ~ thing needs to be expanded to get one. I do not understand why peoples libraries are growing these ~'s but you aren't the only one. Those paths are supposed to be expanded- '/home/ShadowJuubei/Games/guild-wars-2/user.reg'.

I can add code to expand the ~, and to survive errors here (the desktop integration isn't critical). But I expect that you'll have more problems with that ~ in there.

You might want to open the game config and update the game's directory or prefix or whatever is in there; you won't see the ~ there but if you can get it to resave it may fix this for you.

**Comment by danieljohnson2** [comment]
Okay, the master version of Lutris should handle this condition better. You can download it, and the run the 'bin/lutris' script within to try it.

I fear you'll just get a different error, as that ~ may just cause something downstream to fail.

**Comment by danieljohnson2** [comment]
I've put in a bunch more expansion code and I can now run a Wine game that I deliberately sabotaged with lots of ~.

So if you try the master branch now, you may find your games actually work. Let's hope!

**Comment by ShadowJuubei** [comment]
That is very strange as in the game configurations I see no '~' in any of the paths. 
I even looked in pga.db and still I see full paths.
I tested your changes on master and the fix is working in my usecase.

Furthermore, based on your thoughts I went in and copied the 'wine prefix' of a broken configuration (the full path is shown and copied) and then pasted it in the same input for 'wine prefix' and saved the configuration.
This has fixed the problem on my end with this particular game.

I then went ahead and did the same (copy/paste of the 'wine prefix') and this fixes it in other game configurations as well.

Thank you for your support Daniel!

**Comment by danieljohnson2** [comment]
The config dialog expands those ~ before you see them; but they were there in the corresponding .yml files.

Glad you could confirm the fix, though.

**Comment by strycore** [comment]
Reminder that adding catch-all exception handlers is just swiping issues under the rug!! :stuck_out_tongue_closed_eyes:

**Comment by danieljohnson2** [comment]
Well, sweeping them under the log. We should still see them, but users can maybe play their games in site of them.

I also dumped a about a zillion and a half os.path.expanduser() calls all over the code to try to make things work in the face of bogus configuration paths like this. I figured *that* was the greater sin...

**Comment by strycore** [comment]
maybe a cleaner fix would be to use a custom type for paths that would handle that (and also case-insensitivity) transparently

**Comment by danieljohnson2** [comment]
I think so, but I'd want pervasive type annotations and a type checker first- it would be *so* easy to miss a string path that gets through somewhere a million miles away and breaks everything.

There may be a more Pythonic way to take care of this, but I don't know what it is.

**Comment by strycore** [comment]
We are starting to have type checking in place, I've already updated a few modules to have it.
