### ISSUE TITLE
legends of runeterra doesnt work

### ISSUE THREAD

**Issue by baaannnaaannn** [lutris/lutris#5103]
### Bug description

i cant install Legends of runeterra with lutris
i tryed all 3 scripts that available

### How to Reproduce

1. download lutris
2. take one of 3 scripts and install Legends of runeterra

### Expected behavior

just run game

### Log output

```shell
https://docs.google.com/document/d/1-2WiyX_hNvDYcxQoqNBWvYvfKS-KvJNgFz_xpR88l8U/edit?usp=sharing

google docs becouse "Comment is too long (maximum is 65536 characters)"
```

### System Information

```shell
[System]
OS:              GNOME 45 Flatpak runtime
Arch:            x86_64
Kernel:          6.5.8-tkg-eevdf
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             4.8 GB
Swap:            8.8 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 560 Series (polaris11, LLVM 16.0.6, DRM 3.54, 6.5.8-tkg-eevdf)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1 (git-49a47f187e)
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1 (git-49a47f187e)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1 (git-49a47f187e)
Vulkan Version:  1.3.261
Vulkan Drivers:  AMD Radeon RX 560 Series (RADV POLARIS11) (1.3.255)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
You're running a LoL game with the normal Wine-GE when it should use the LoL specific build. The scripts need to be updated to point to this version.

**Comment by baaannnaaannn** [comment]
> You're running a LoL game with the normal Wine-GE when it should use the LoL specific build. The scripts need to be updated to point to this version.

I'm running with wine lol ge - same situation
Only with this wine version LOR works
https://github.com/polkaulfield/lol-for-linux-installer/releases/tag/wine-lol-staging
