### ISSUE TITLE
No Cover for any game

### ISSUE THREAD

**Issue by JulienDlq** [lutris/lutris#5107]
### Bug description

Since I updated Lutris from 0.5.13 to 0.5.14, games’ cover are not shown.

Nothing interesting is shown in `lutris -d`.

### How to Reproduce

1. Open Lutris

### Expected behavior

Games’ cover are shown.

### Log output

```shell
INFO     2023-10-28 09:01:24,745 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-10-28 09:01:24,746 [startup.get_drivers:57]:Using NVIDIA drivers 545.23.06 for x86_64
INFO     2023-10-28 09:01:24,746 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1660 Ti
INFO     2023-10-28 09:01:24,747 [display.display_gpu_info:78]:GPU: 10DE:2182 1043:86A5 (nvidia drivers)
DEBUG    2023-10-28 09:01:24,868 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-10-28 09:01:24,957 [lutris.get_missing_game_ids:202]:Checking for missing games
```

### System Information

```shell
[System]
OS:              Gentoo 2.14 n/a
Arch:            x86_64
Kernel:          6.5.9-gentoo-x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical cores:  8
Logical cores:   8

[Memory]
RAM:             31.3 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.23.06
OpenGL Core:     4.6.0 NVIDIA 545.23.06
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.23.06
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce GTX 1660 Ti (1.3.260)
```

### Media (optional)

![Screenshot_20231028_090440](https://github.com/lutris/lutris/assets/18351090/a0dee4df-cb84-4e93-8599-ef6ed1b9b82c)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by JulienDlq** [comment]
As a workaround, if I go to game config, I can reset cover settings, and it shows again cover!
But I have to do it for each game, and it doesn’t keep them when I relaunch lutris after a certain period of time.

![Screenshot_20231028_090727](https://github.com/lutris/lutris/assets/18351090/8b2bb8c2-5547-4ac3-af56-e5bfc96538fa)

![Screenshot_20231028_090942](https://github.com/lutris/lutris/assets/18351090/244de915-4659-4412-9c1a-41be8744d2dd)

![Screenshot_20231028_091058](https://github.com/lutris/lutris/assets/18351090/765980ca-2112-4709-bb66-6b17a99f786c)

**Comment by danieljohnson2** [comment]
That's very strange. The cover art is kept in ~/.cache/lutris/coverart; can you look there and see if your cover-art is still there?

I wonder if you have something that is clearing out your .cache directory somehow. Lutris will eventually repopulate it, but if it keeps getting cleared after a 'certain about' of time, that's going to be a problem.

**Comment by JulienDlq** [comment]
There is no ~/.cache/lutris folder.

**Comment by danieljohnson2** [comment]
Those folders are from an older version of Lutris- about 0.5.9.1 and earlier I think. We have code to move all the art from there to ~/.cache/lutris.

But when you download the cover art for Cyberpunk 2077, it should turn up ~/.cache/lutris/coverart.

Try downloading it again (as you've done before) and see if it turns up in that directory, even temporarily. It's got to be *somewhere*!

**Comment by JulienDlq** [comment]
Ok, I finally found what happen… I don’t know why, but it saves « auto-magically » cache « things » in `/tmp/$USER/.cache/lutris`… that explain why it does not resists at reboot!

But I don’t know how to tell Lutris to stop this…

**Comment by danieljohnson2** [comment]
Sounds like you've solved the mystery, if not the problem exactly. I think we can close this.

**Comment by strycore** [comment]
Damn, now I want to move the cover art back to ~/.local/share ...

**Comment by danieljohnson2** [comment]
In theory, the downloaded Lutris media belongs in .cache, but the custom user-provided stuff should go in .local/share, I think. Maybe.

**Comment by strycore** [comment]
The sqlite pga.db file is in ~/.local/share/lutris, and the images in ~/.cache/lutris reference the entries of that DB. It makes moving Lutris installs between machines more difficult. But by that logic, we should also move ~/.config/lutris/games to ~/.local/share/lutris ... 

It's fine to use the ~/.cache/lutris folder for auth tokens, log files and temp stuff. The cover art and banners is not temp stuff, it is data that almost never changes and takes several minutes to download. 

I would be in favor of getting rid of ~/.config/lutris first.

**Comment by danieljohnson2** [comment]
Well, being slow to obtain is exactly why you would want to cache the media. A cache directory only for things that are fast would be mostly pointless.

I am not too sure about the .local vs .config thing. I do not understand why we put the PGA in one, but the yml files in the other.

But to me, .cache seems like something the user should be able to discard, which is mostly but not entirely true for Lutris.

**Comment by strycore** [comment]
The .local vs .config distinction comes from trying to follow some XDG recommendation. It hasn't proven to be useful in any way.
It's not really hard to keep the legacy folder structure working while allowing to load almost everything from ~/.local

> .cache seems like something the user should be able to discard

Precisely. So any data that should be kept around should be loaded from .local. 
But then, should we also move the folders for 3rd party integrations?

**Comment by danieljohnson2** [comment]
Can we redownload the 3rd party integration folders? Do we do that automatically, like we do with media? Can the user customize them in some way?

**Comment by strycore** [comment]
Yes, the integration files can be redownloaded by hitting the refresh button, or signing in again if the auth token was also deleted. There is no customization possible other than overwriting the images downloaded from the service. Lutris won't overwrite an existing image from a service.

For Lutris specific media, we no longer have a way to refresh all media like we had before 0.5.14

**Comment by danieljohnson2** [comment]
Oh no, not again.

I looked it up and commit cf556196e5cfc872c137ecfb266b64ecb4e33c6a lost the media redownload functionality. Broken media just stay broken now.

Is there some sort of plan or theory to this? Or should I fix this?

**Comment by strycore** [comment]
The media sync was removed from the startup phase for performance reasons. With a large library, it add a few seconds to startup time. 

If there was a way to launch this media sync **WAY AFTER THE THE MAIN UI HAS FINISHED DRAWING** then I would be ok putting it back. Or maybe just add a button to launch the media sync manually in the preferences window.

**Comment by danieljohnson2** [comment]
I can manage that. We totally support downloading media after startup.

It could be triggered if the cell-renderer that draws the media finds itself drawing the missing placeholder graphics. I expect it would have to be asynchronous to avoid making scrolling awful though- can't interrupt the rendering. Need some other throttling here so we don't just try to restore something over and over if it is just unavailable, too.

Or maybe just a button.

**Comment by strycore** [comment]
Please no network calls every time a game is selected.

If any media fails to download, Lutris should not make any attempt to download it automatically in a period of 2 full months. 

I really think a manual action is the way to go because game media doesn't break itself out of the blue. Game media will go missing if the user actively messed with the files.

**Comment by danieljohnson2** [comment]
Certainly not on select; but the two month delay is trickier. Maybe just a button then.

**Comment by danieljohnson2** [comment]
Oh, this can be very simple. How about we trigger this when you reload the Lutris service?

That already loads the media for the games in your Lutris library, and following that with sync_media() fills in any media for games not in your library. It does not seem to double download media.

**Comment by strycore** [comment]
It's a bit non intuitive but it would be a quick and easy solution until we have something better.

**Comment by danieljohnson2** [comment]
Consider it done.

I think it leaves users who don't have Lutris logins out, but it's certainly better than nothing.
