### ISSUE TITLE
System tray window closing

### ISSUE THREAD

**Issue by vanessakindell** [lutris/lutris#5109]
Even with the system tray option selected, closing the window will cause the entire application to close rather than keeping it running in the background in the system tray like it does on Steam, Origin, Hero, Discord, etc.

**Comment by danieljohnson2** [comment]
Oh yes, this code got borked; looks like a bogus merge. You trust Git to merge your mergers for you, and then when you least expect it...

I've tried to fix everything up. It should work properly now.

You can try it by downloading the master branch, and then running the 'bin/lutris' script within.

**Comment by strycore** [comment]
Welp, this change made me disable the tray icon in the preferences.

**Comment by danieljohnson2** [comment]
Is it not supposed to stay open when the tray icon is active?

**Comment by strycore** [comment]
Maybe, that's what most programs with a systray icon do. 
I liked the behavior where Lutris would only stay in the background if it was running a game and would close normally if it wasn't.

I'm not even sure why I had the tray icon enabled, maybe just so it would receive some testing. 
Tray icons are a pain to deal with and are heavily frowned upon by Gnome devs so I'll just leave the tray icon live its life without me interfering.
