### ISSUE TITLE
Issues using lutris: protocol link followed by a game identifier

### ISSUE THREAD

**Issue by culain-45124** [lutris/lutris#5116]
Hello,

I've been trying to use the `lutris:` protocol link followed by a game identifier to either install or run a game via Lutris from within Steam and I've run into some issues.

It seems that the identifier isn't 100% consistent for service games e.g. Anno 1503 from gog:

| Identifier | Value |
| --------- | ----------- |
| appid      | 1438074791 |
| name      | Anno 1503 A.D. |
| slug      | anno_1503_ad |
| lutris_slug      | anno-1503-ad |

None of those identifiers return an installer, or an error. It turns out the correct identifier here would be `anno-1503`. There are also issues where some of these identifiers aren't set for some services, e.g. `lutris_slug` isn't set for egs games.

The issue is that I'm trying to take values from the `-aj` output to generate Steam shortcut commands, and the working value doesn't match any of the values returned by the service game list CLI.

I have discovered in the code that you can also do something like `lutris:service:appid` but this only works with the `appid` for the service game, though it does seem to work consistently. Unfortunately `appid` isn't currently returned by the `-aj` CLI command.

I've made some code changes myself to add `appid` to the `-aj` CLI output, but also to be more lenient and allow Lutris to try and match the other identifiers above for service games, similar to how you try to find `db_game` with `game_slug`. I've also attempted to fix the error when unable to find an installer for a game, as it currently just hangs if you use an identifier that a game can't be found for via the API.

Would you be willing to take a PR for this? Or discuss it further?

Thanks

**Comment by culain-45124** [comment]
Possibly also worth saying, I've got around this so far by using the `details` field, but the naming to extract `appid` isn't consistent between services and ubisoft isn't consistent within the service either.

In case you're interested, I'm trying to use the CLI output in this script

https://github.com/culain-45124/lutris-importer

**Comment by strycore** [comment]
I've added appid in the list of service games. Hopefully, this is enough for your use case.
