### ISSUE TITLE
Cannot launch lutris

### ISSUE THREAD

**Issue by GaMeIsNtOvEr** [lutris/lutris#5117]
Hey just installed lutris from pacman (I use arch btw).
but it seems that i cannot launch it. when i used the command "lutris" in terminal i got an error which says:
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'lutris'
```
The thing is that lutris works fine when its been launched with a venv. im using the latest python version and all dependencies of lutris are installed.

**Comment by danieljohnson2** [comment]
This sounds a lot like #4883, which seemed to be a botched Lutris package in the repo, though it's not clear what was wrong with it. The fix was to use flatpak ('via pacman'), which avoids using the repo's package rather than fixing it.

**Comment by Milor123** [comment]
what is the solution? 
I cant fix it, i try env in python, change python version, but nothing works
and the flatpak, i want not use it, its a not the solution.
what should i do guys?

**Comment by strycore** [comment]
Sure thing to make sure Lutris runs is to make sure the system provided python is used.
Do not use another Python version, installed with pyenv or otherwise.

To check if your setup is correct, you should be able to import lutris from a python shell:


```
> python
Python 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lutris
>>> lutris.__file__
'/usr/lib/python3.11/site-packages/lutris/__init__.py'
```

**Comment by sol8712** [comment]
> Sure thing to make sure Lutris runs is to make sure the system provided python is used. Do not use another Python version, installed with pyenv or otherwise.
> 
> To check if your setup is correct, you should be able to import lutris from a python shell:
> 
> ```
> > python
> Python 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import lutris
> >>> lutris.__file__
> '/usr/lib/python3.11/site-packages/lutris/__init__.py'
> ```

After having a working lutris installation on manjaro, i installed pyenv and this completely broke my lutris install with the same error. Even though pyenv is set to use system python globally and i can import lutris in a python shell.

I can successfully launch lutris with 'python /bin/lutris -d' but this way is missing many librarys and games dont work.

Any idea what can be done to remedy this?

**Comment by strycore** [comment]
uninstall pyenv or stop using it and return to the system python.

**Comment by strycore** [comment]
> Even though pyenv is set to use system python globally and i can import lutris in a python shell.

also make sure you don't have a ~/.python_version file (I think that's the filename). Also use a shell prompt such as Powerlevel10k to easily confirm which Python version is currently in use.

**Comment by sol8712** [comment]
Uninstalling pyenv and rebooting do not seem to have any effect. Ive got 3 versions of python 3.10, 3.11, and "system", in pyenv ive tried setting the globally used python to the system python. But no changes to errors.

**Comment by sol8712** [comment]
I have a ~/.python_history file but it only contains one word "exit".

Maybe my system python got borked?

**Comment by strycore** [comment]
.python_history is the list of commands you have typed in the python interpreter, like bash_history. 

It's pretty unlikely pyenv would cause damage to your system's python. I even have pyenv and have managed to run it alongside Lutris but I did run into some issues where pyenv would interfere. 

If you have uninstalled pyenv, make sure all it's configuration files / python versions (in ~/.pyenv) are removed as well. 
In my .zshrc I have the following: 

```
export PYENV_ROOT="$HOME/.pyenv"
if [ -d "$PYENV_ROOT" ]; then
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
fi
```
If the ~/.pyenv folder is removed, it will prevent pyenv from being loaded at all. 

Once you got Lutris running again. You can reinstall pyenv (if you need it) but make sure to only apply python versions for the projects you need and never globally.

**Comment by sol8712** [comment]
Thank you for trying. I was never able to get this working, Even after uninstalling pyenv and renaming the .pyenv folder. All ive read indicated thats the proper way to remove pyenv, but still the same error trying to start lutris.
I really cant reinstall my OS or give up on the ability to use multiple python versions and envs is there any last resort thing i can try before the nucular option?

**Comment by strycore** [comment]
Launch a Python shell and try to find out why Lutris can't load

Typing 
```
import sys
sys.path
```
Will show you all path checked by the current python interpreter.

Then figure out where the lutris package is installed. For example on Fedora, you can run `dnf repoquery -l lutris` to list all files in the package. On Ubuntu, it's `dpkg -L lutris`.

If your lutris files are installed in /usr/lib/python3.12/site-packages/lutris/ and you have /usr/lib/python3.12/site-packages/ in sys.path then you should be able to run `import lutris` from your Python shell
