### ISSUE TITLE
Qsynth causes audio output to disappear in Debian and shouldn't be autostarted

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#5118]
### Bug description

Since a recent upgrade Lutris bundles QSynth. That it was running due to Lutris caused a [No output or input devices found problem in Debian where no sound device is available](https://unix.stackexchange.com/questions/760522/no-output-or-input-devices-found-for-audio-on-debian-kde-since-pulseaudio-cant). See that link for details. I'm not sure how that can be prevented but think that simply preventing it from starting would suffice since quitting it once in the process manager got the audio to work again.

### How to Reproduce

1. Upgrade Lutris in Debian 12 with the Debian 12 repo of Lutris.
2. Click the volume icon in the tray bar to see that no audio output is possible anymore. It could be that some actions in between are needed, most likely a reboot.

### Expected behavior

To not start qsynth or to not cause any problems to the audio output. It's unclear why it comes bundled with it now.

### Log output

```shell
Unrelated to lutris itself in terms of Lutris outputs.
```

### System Information

```shell
Debian 12 with KDE
Only an internal soundcard
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by mYnDstrEAm** [comment]
I still have the problem whenever rebooting since qsynth gets autostarted. I have Lutris version 0.5.14 (shown in Apper and when running lutris --version; apparently it was manually installed). `aptitude why qsynth` still shows `lutris depends fluidsynth` and `fluidsynth recommends qsynth`. I didn't install it myself so it seems like it gets automatically installed and this could also cause the same problem for other Linux users.

I just removed qsynth now (`sudo apt-get remove qsynth`) and hope it doesn't cause any problems. Maybe one can specify whether or not dependencies' recommended packages are installed or not or something similar so that you can prevent qsynth from getting installed if it's not needed anyway.

**Comment by strycore** [comment]
@mYnDstrEAm https://www.debian.org/doc/debian-policy/ch-relationships.html
