### ISSUE TITLE
Allow games to run even if wine is not "installed" on the system

### ISSUE THREAD

**Issue by musjj** [lutris/lutris#5121]
### Bug description

In the previous version, games are allowed to run even when Wine is not installed (with only a warning). But now games are simply *not* allowed to run at all.

This is just silly, because lutris provides wine itself and you *don't* need to install wine to have the right dependencies installed. This is especially true for OSes like NixOS, where all the necessary dependencies are provided in the derivation itself.

As a matter of fact, my games runs perfectly fine when you run it directly: `env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/$ID`. The problem only happens when you try to run the game from the user interface.

### How to Reproduce

Run a game on Lutris on a system without Wine.

### Expected behavior

Game can be run.

### Log output

```shell
2023-11-08 03:16:21,766: Command 'wine' not found on your system
INFO     2023-11-08 03:16:22,778 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-11-08 03:16:22,780 [startup.get_drivers:57]:Using NVIDIA drivers 470.223.02 for x86_64
INFO     2023-11-08 03:16:22,780 [startup.get_drivers:61]:GPU: NVIDIA GeForce GT 635
INFO     2023-11-08 03:16:22,781 [display.display_gpu_info:78]:GPU: 10DE:1280 1462:2922 (nvidia drivers)
WARNING  2023-11-08 03:16:22,926 [startup.check_vulkan:111]:Vulkan reports that the 'NVIDIA GeForce GT 635' device has API version of 1.2.175. 1.3.0 is required for the latest DXVK.
DEBUG    2023-11-08 03:16:23,156 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-08 03:16:23,471 [lutris.get_missing_game_ids:202]:Checking for missing games
Traceback (most recent call last):
  File "/nix/store/dsg6dixc737hk2r132b6f058y3049278-lutris-unwrapped-0.5.14/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files (2)
```

### System Information

```shell
[System]
OS:              NixOS 23.11 Tapir
Arch:            x86_64
Kernel:          6.1.60
Desktop:         none+dummy
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             15.6 GB
Swap:            22.8 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GT 635/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.223.02
OpenGL Core:     4.6.0 NVIDIA 470.223.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.223.02
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce GT 635 (1.2.175)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
I don't think I understand. Not allowed tor run? What does it do if you try, send you to your room so you can think about what you've done?

Maybe a screenshot would help me understand this?

**Comment by musjj** [comment]
![image](https://github.com/lutris/lutris/assets/72612857/25c6acc7-14ee-4c65-b027-3b7e579acbe1)
In the previous version, you can bypass this check and run the game anyways. Pressing OK does nothing here, btw.

**Comment by danieljohnson2** [comment]
Oh, tricky. @strycore removed all the dont-show-again dialogs, I believe because people would tick the checkbox to hide the warning, then forget about it, and complain to us when their games didn't work because of the issue they had dismissed and forgotten. There was not a reasonable way to bring those warnings back, ever.

I replaced most of these guys with warnings displayed inside the configuration window, which cannot be suppressed but do not stop you from trying to run the game. We've tried to make the default configuration never trip a warning, so you will have to go into the configuration window and see the warnings there.

I could do something like that here, but I think I'd better make a PR of it; @strycore may really wish to block access to Wine without a system Wine. I do not think there's a way to make sure the user has seen a warning in the config dialog, if he has installed the game via an installer script or something of that kind. So this would be a pretty missable warning.

**Comment by musjj** [comment]
How about a build-time flag that can disable this behavior for good?

This will allow packagers to decide whether or not the behavior makes sense for their distribution. For example: on NixOS, even if the Lutris package somehow missed some dependencies, the problem cannot be fixed by simply having the user install Wine. So the message would be misleading here.

**Comment by danieljohnson2** [comment]
OK, I've popped a PR for my idea here, #5122. You can download [the branch here](https://github.com/lutris/lutris/tree/dj/gentler_system_wine_warning). Don't install this, but you can try to run the bin/lutris script within.

That should let you start the game, with a warning in the log, and a warning in the config dialog.

I do not think build options (build?) are pythonic, but you can pop a PR of your own if you'd like if you know how to do that.
