### ISSUE TITLE
Missing libimagequant.so.0 in Arch Linux. Prevents Lutris from starting.

### ISSUE THREAD

**Issue by Rajala1404** [lutris/lutris#5124]
### Bug description

I cant start Lutris because some lib is missing but the lib is installed and if i try to run ldconfig -p | grep libimagequant
It says:

       
```    
        libimagequant.so.0.0.4 (libc6,x86-64) => /usr/lib/libimagequant.so.0.0.4
        libimagequant.so (libc6,x86-64) => /usr/lib/libimagequant.so
``` 
but the other thing is that it worked before but now not

### How to Reproduce

1. Launch Lutris
2. Done

### Expected behavior

That Lutris starts normal

### Log output

```shell
wTraceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 45, in <module>
    from lutris.gui.dialogs.delegates import LaunchUIDelegate, InstallUIDelegate, CommandLineUIDelegate
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/delegates.py", line 9, in <module>
    from lutris.runners import wine
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 26, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libimagequant.so.0: cannot open shared object file: No such file or directory
```

### System Information

```shell
-`                    rajala1404@Archi 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: HP ENVY All-in-One 27-b1XX 
               `+oooooo:                 Kernel: 6.6.1-arch1-1 
               -+oooooo+:                Uptime: 31 mins 
             `/:-:++oooo+:               Packages: 1250 (pacman) 
            `/++++/+++++++:              Shell: fish 3.6.1 
           `/++++++++++++++:             Resolution: 2560x1440 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.9 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-`/ossssss+`         WM Theme: Flight-Blur-Dark-Aurorae 
       -osssssso.      :ssssssso.        Theme: [Plasma], Layan-Dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Win11-black-dark [Plasma], Win11-black-dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: konsole 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: JetBrains Mono 10 
  `+sso+:-`                 `.-/+oso:    CPU: Intel i5-7400T (4) @ 3.000GHz 
 `++:.                           `-/+/   GPU: Intel HD Graphics 630 
 .`                                 `/   GPU: NVIDIA GeForce GTX 950M 
                                         Memory: 4239MiB / 11692MiB
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Shinusei** [comment]
+1

**Comment by espuserslime** [comment]
running into exact same issue on fresh latest arch linux install

+1

**Comment by Iron-Squid** [comment]
I am running into this exact same issue, I am also using an up-to-date version of Arch.

**Comment by Iron-Squid** [comment]
Additional log for proof, albeit it seems almost identical to the initial one:

```Traceback (most recent call last):
  File "/usr/bin/lutris", line 57, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 45, in <module>
    from lutris.gui.dialogs.delegates import LaunchUIDelegate, InstallUIDelegate, CommandLineUIDelegate
  File "/usr/lib/python3.11/site-packages/lutris/gui/dialogs/delegates.py", line 9, in <module>
    from lutris.runners import wine
  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 26, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.11/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libimagequant.so.0: cannot open shared object file: No such file or directory
```

**Comment by christiannicola** [comment]
for all arch users having this issue - running lutris via flatpack seems to work fine.

```bash
sudo pacman -S flatpak
flatpak install lutris
flatpak run net.lutris.Lutris
```

**Comment by Iron-Squid** [comment]
> for all arch users having this issue - running lutris via flatpack seems to work fine.
> 
> ```shell
> sudo pacman -S flatpak
> flatpak install lutris
> flatpak run net.lutris.Lutris
> ```

Good fix, though this is a temporary workaround and requires a bit of work to manually port over 100% of Lutris database+configs over.

**Comment by christiannicola** [comment]
> > for all arch users having this issue - running lutris via flatpack seems to work fine.
> > ```shell
> > sudo pacman -S flatpak
> > flatpak install lutris
> > flatpak run net.lutris.Lutris
> > ```
> 
> Good fix, though this is a temporary workaround and requires a bit of work to manually port over 100% of Lutris database+configs over.

Yes, it's not ideal in the slightest, however it's a valid alternative until the python dependencies are fixed.

**Comment by RekZix** [comment]
this command reverted the libimagequant package to the old version which fixed it for me (before i reverted lutris as well but this didnt work, so you might need to do both of these):

might work if you upgraded from another version than me (then look for another version of the package):

sudo pacman -U /var/cache/pacman/pkg/lutris-0.5.13-6-any.pkg.tar.zst
sudo pacman -U /var/cache/pacman/pkg/libimagequant-4.2.1-1-x86_64.pkg.tar.zst

**Comment by espuserslime** [comment]
> this command reverted the libimagequant package to the old version which fixed it for me (before i reverted lutris as well but this didnt work, so you might need to do both of these):
> 
> might work if you upgraded from another version than me (then look for another version of the package):
> 
> sudo pacman -U /var/cache/pacman/pkg/lutris-0.5.13-6-any.pkg.tar.zst sudo pacman -U /var/cache/pacman/pkg/libimagequant-4.2.1-1-x86_64.pkg.tar.zst
> 
> it also required a system reboot (at least for me).

this worked for me, i only had to do the second command but lutris is launching, thanks

**Comment by Iron-Squid** [comment]
Note: This seems to be an error with Arch's packaging.
https://bugs.archlinux.org/task/80209

**Comment by Rajala1404** [comment]
The Flatpack Version works for me too

**Comment by jnines** [comment]
Had the same issue, with Lutris as well as GreenWithEnvy which also relies on this.  There's  currently a bug report for it. 
https://bugs.archlinux.org/task/80209
I'm too lazy to deal with flatpak so I just `sudo ln -s /usr/lib/libimagequant.so.0.0.4 /usr/lib/libimagequant.so.0` for the time being.

**Comment by strycore** [comment]
Maybe a dirty workaround but symlinking /usr/lib/libimagequant.so.0.0.4 to /usr/lib/libimagequant.so.0 might make Lutris usable again?

I also have to investigate if PIL is *really* needed or can be made optional.

**Comment by Shinusei** [comment]
Fixed with new update of libimagequant

**Comment by strycore** [comment]
Cool, this can be closed then.
