### ISSUE TITLE
Launching with Enter/Return key doesn't change the "Play" button into "Launching" -> "Stop"

### ISSUE THREAD

**Issue by ahungry** [lutris/lutris#5132]
### Bug description

Launching with Enter/Return key doesn't change the "Play" button into "Launching" -> "Stop".

### How to Reproduce

Error/inconsistency when using keyboard:

1. Open Lutris
2. Highlight an existing installed game via single click, or arrow keys
3. Press your Enter/Return key 
4. Observe the Play button never changes (at least, not with any games using nested launchers, like the Battle.net launcher)

Conversely, when doing it via GUI clicks, what I assume is the intended flow:

1. Open Lutris
2. Highlight an existing installed game via single click, or arrow keys
3. Move mouse to the Play button and click it
4. Observe it briefly shows a "Launching" grayed out text, before transitioning to a "Stop" button

I'm not sure if the lack of a Stop button is an interim issue, but I have never seen "Launching" in grayed out text occur with keyboard launches.

### Expected behavior

Same "Play" button behavior no matter how the game is started.

### Log output

```shell
n/a
```

### System Information

```shell
Arch Linux, latest Lutris 0.5.14-1
```

**Comment by ahungry** [comment]
I cloned the repo and added some local debugging - the state is being set as expected in `launch()`, but it's missing a call to `update_view()` for the game_bar when launching via the enter key (this ends up being called when the button is used via a mouse click).

I wonder if in the emitted "game-start" event, if it should just call an update_view()?  I'm still trying to find where the ENTER key is actually assigned a binding, as that may make even more sense.

**Comment by ahungry** [comment]
It looks like the early return is what is blocking this:

```
    @watch_errors()
    def on_game_state_changed(self, game):
        """Handler called when the game has changed state"""
        if (
            (self.game.is_db_stored and game.id == self.game.id)
            or (self.appid and game.appid == self.appid)
        ):
            self.game = game
        elif self.game != game:
            return True
        self.clear_view()
        self.update_view()
        return True
```
and why the update is not being called.

I see the git history mentions: https://github.com/lutris/lutris/issues/4747 - I'm not sure why the self.game != game - should it be checking `self.game.id != game.id` or something? 

I'm going to try tweaking things - no doubt what might fix my issue may reproduce the problems in #4747 though, even if it worked?

**Comment by ahungry** [comment]
In my case, the id matches, and ensuring clear/update are called, the bar does actually update partially (the "Play" becomes grayed out - but it never transitions to Launching or Stop).

**Comment by ahungry** [comment]
Super weird - check out this debug output (sorry - good old print line debugging) - python is decided 4 is not equal to 4...

```
mdc on_game_state_changed                                                                                 
mdc is_db_stored                                     
True                                                                                                                                                                                                                mdc AppId                                                                                                 
None                                                 
None                                                                                                                                                                                                                game id checks                                                                                            
4                                                    
4                                                                                                                                                                                                                   comp 1                                                                                                    
False                                                
the real wtf...                                                                                                                                                                                                     False                                                                                                     
4                                                                                                         
4                                                    
comp 2                                               
None                                                 
mdc on_game_state_changed but aborting               
World of Warcraft (wine)                                                                                                                                                                                            
World of Warcraft (wine)                                                                                                                                                                                            
4                                                    
4       
```

Those results are when I updated the function as follows:
```
    @watch_errors()
    def on_game_state_changed(self, game):
        """Handler called when the game has changed state"""
        print("mdc on_game_state_changed")
        print("mdc is_db_stored")
        print(self.game.is_db_stored)
        print("mdc AppId")
        print(self.appid)
        print(game.appid)
        print("game id checks")
        print(game.id)
        print(self.game.id)
        print("comp 1")
        print(self.game.is_db_stored and game.id == self.game.id)
        print("the real wtf...")
        print(game.id == self.game.id)
        print(game.id)
        print(self.game.id)
        print("comp 2")
        print(self.appid and game.appid == self.appid)
        if (
            (self.game.is_db_stored and game.id == self.game.id)
            or (self.appid and game.appid == self.appid)
        ):
            self.game = game
            print("mdc did the click put me in here?")
        elif self.game.id != game.id:
            print("mdc on_game_state_changed but aborting")
            print(self.game)
            print(game)
            print(self.game.id)
            print(game.id)
            return True

        self.clear_view()
        self.update_view()
        return True

```

Now, if I update the function so the game id comparisons in first block cast to `int()` first, all works as expected - is the game.id an object?  and maybe the print is just the __repr__ or whatever python magic has for casting it to a readable value?  

Anyways, PR shortly, if anyone is interested... I didn't run a comprehensive regression, but for the 3 launch cases, this seems to fix it for the non Play button direct clicks (return key + double click).

**Comment by ahungry** [comment]
https://github.com/lutris/lutris/pull/5141

**Comment by ahungry** [comment]
Ok, it was driving me nuts not to know the "why" - I saw sqlite3 under the hood - looks like it's this type inequality causing it:

```        
print(type(game.id))
print(type(self.game.id))
<class 'str'>
<class 'int'>
```
A more comprehensive fix may be ensuring the getter for "id" is always a correctly typed return value, if it's intended to be an id.

**Comment by danieljohnson2** [comment]
That's a good bit of debugging work there, and makes the problem clear.

I don't think your fix is right, so I've done my own in the same sense- converting ids to the same type. It's just that that type is string, not int.

Thanks for running this one done so well.
