### ISSUE TITLE
League of Legends Patch Broken on Lutris

### ISSUE THREAD

**Issue by covalspace** [lutris/lutris#5144]
### Bug description

Please see https://forums.lutris.net/t/league-of-legends-reconnect-loop/19240

Everyone is having the same issue with no success.

### How to Reproduce

Install and run League of Legends and load into a game

### Expected behavior

the game should load instead of constant reconnect loop

### Log output

```shell
See forum for full log outputs of multiple people
```

### System Information

```shell
Not system dependent
```

**Comment by strycore** [comment]
I can confirm the issue but that's really all I can do. I see mentions of VKD3D 2.11 which is now available in Lutris but it doesn't seem to solve anything.

Looks like a Riot employee is willing to forward the issue to the LoL devs so that might be our best hope.

**Comment by strycore** [comment]
New build for LoL is up, the game is playable again.
