### ISSUE TITLE
Cannot login to Origin Service (Yes, I know EA App has replaced it but I have games in my Lutris Library Attached to Origin and they won't show up in my library unless I log in through Lutris to the ORIGIN service)

### ISSUE THREAD

**Issue by gardotd426** [lutris/lutris#5145]
### Bug description

I was wanting to transfer some of my installed games from the Origin service to the EA App service, since Origin is dead now anyway. Lutris had logged me out (I don't know why Lutris periodically logs users out of services so they have to re-login for their libraries to appear, but I'm guessing it's not a Lutris issue). 

So, when I click on Origin, my library is empty, but I have multiple games installed in it, if I could just log in. So I clicked the little person icon to log in, and an EA App login window appears,. same as with the EA App service. 

But, when I type in my credentials, it says they're having technical difficulties and to try again later. Trying to use Google or facebook to log in just brings up a second permanently-blank window that never loads. 

I have 100% confirmed 7 different times that my password is correct. I have also confirmed it's not an EA server issue, as I can log in to EA.com and EA App just fine. 

I can't get Battlefield 3, 4, 1 or V as well as 4 or 5 other games to show up in my library without being able to log in to the Origin service. My only option would be to go to the EA App service library, right-click "locate installed game" and go through that whole process for each game. If it were just one game, I wouldn't mind, but this is 8 or 9 games we're talking about.

### How to Reproduce

1. Go to Origin in the Services section of the sidepane
2. Click on the login icon
3. Attempt to login

### Expected behavior

I'm able to log in, my library appears. 

### Log output

```shell
INFO     2023-11-25 00:09:01,204 [application.do_command_line:439]:Starting Lutris 0.5.14
INFO     2023-11-25 00:09:01,206 [startup.get_drivers:55]:Using NVIDIA drivers 545.29.06 for x86_64
INFO     2023-11-25 00:09:01,207 [startup.get_drivers:59]:GPU: NVIDIA GeForce RTX 3090
INFO     2023-11-25 00:09:01,207 [display.display_gpu_info:78]:GPU: 10DE:2204 3842:3975 (nvidia drivers)
DEBUG    2023-11-25 00:09:01,888 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-25 00:09:02,981 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2023-11-25 00:09:30,264 [base.wipe_game_cache:382]:Deleting origin cache /home/matt/.cache/lutris/origin/cache/
DEBUG    2023-11-25 00:09:30,264 [base.wipe_game_cache:176]:Deleting games from service-games for origin
DEBUG    2023-11-25 00:09:30,265 [base.logout:397]:logged out from origin
DEBUG    2023-11-25 00:09:32,252 [base.login:371]:Connecting to Origin
INFO     2023-11-25 00:09:58,357 [application.do_shutdown:1044]:Shutting down Lutris
```

Literally nothing even happens in the logs when I try to enter my password or when I try to click Google login.
```


### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.6.2-zen1-1-zen
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            39.6 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.29.06
OpenGL Core:     4.6.0 NVIDIA 545.29.06
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.29.06
Vulkan Version:  1.3.269
Vulkan Drivers:  NVIDIA GeForce RTX 3090 (1.3.260)
```
```


### Media (optional)

Here is a screenshot of the window:
![Screenshot_20231124_235551](https://github.com/lutris/lutris/assets/54234607/3f2cb057-84ad-4381-adab-cf421fdd2d1c)

**Comment by strycore** [comment]
> Lutris periodically logs users out of services so they have to re-login for their libraries to appear

That's because the authentication token eventually expires. There might be some improvements we can do on our side in regards to the token refresh process.

I'm not really sure how you're trying to migrate your games but the only solution I found was to move the game files from the Origin prefix to the EA App prefix. I didn't even notice a "locate installed game" feature, I just dropped the game files where EA App would install them and manually re-installed each game. EA App didn't re-download anything and found the existing files. Once the games were imported to EA App, I refreshed the EA service in Lutris and the games showed up as installed.

I did that for about 15 games so it wasn't really that bad.

**Comment by gardotd426** [comment]
>I didn't even notice a "locate installed game" feature

On any of the login services, once your library shows up, you can right-click and choose either "Install" or "Locate Installed Game." I guess I can do the locate installed game thing, I wish there was an easier way to migrate because I have  EA Play Pro so I have basically every EA game lol, but it's no biggie. I can close.

**Comment by strycore** [comment]
Oh I see, it's "Locate installed games" in Lutris. I had Lutris re-create the game from EA App so I lost the playtime for my Origin games.
The migration is certainly annoying but hopefully, this kind of launcher change only stays exceptional.
