### ISSUE TITLE
DOSBox Runner — "Main file" help string is inaccurate

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [lutris/lutris#5147]
### Bug description

The [following string](https://github.com/lutris/lutris/blob/73ea627dca06e049dcbb57222932cb82227ea576/lutris/runners/dosbox.py#L27C5-L28C46) is inaccurate, as the runner currently always returns a "FILE_NOT_FOUND" error if `main_file` is not set, regardless of whether `config_file` is set:
> Main file
> [...]
> It **can be left blank** if the launch of the executable is managed in the config file.

Rather, attempting to launch a game in this state will result in the following pop-up:

> This game has no executable set. The install process didn't finish properly.

### How to Reproduce

1. Set up a DOSBox game with the following properties:

	- `main_file`:
	- `config_file`: <a path to .conf file>

### Expected behavior

`main_file` should actually be optional if `config_file` is present, or the "help" text should be adjusted to reflect current behaviour.

### Log output

```shell
ERROR    2023-11-27 16:07:34,439 [exceptions.wrapper:103]:<game> has encountered an error: This game has no executable set. The install process didn't finish properly.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/exceptions.py", line 97, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 609, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/game.py", line 589, in get_gameplay_info
    raise self.get_config_error(gameplay_info)
lutris.exceptions.GameConfigError: This game has no executable set. The install process didn't finish properly.
DEBUG    2023-11-27 16:07:34,440 [application.on_game_stop:721]:Removing 156 from running IDs
```

### System Information

```shell
[System]
OS:              GNOME 45 Flatpak runtime
Arch:            x86_64
Kernel:          6.5.6-300.fc39.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.6-300.fc39.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1 (git-49a47f187e)
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1 (git-49a47f187e)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1 (git-49a47f187e)
Vulkan Version:  1.3.261
Vulkan Drivers:  AMD Radeon RX 580 Series (RADV POLARIS10) (1.3.255)
```

**Comment by danieljohnson2** [comment]
Oh wow. The behavior has changed and main_file is required now. It changed on 6/15/13, commit c8accf0293317bc61b4a182ba963fa5e0d4a1cf1.

You are apparently the first person to actually read that help entry in the last ten years, or at least the first person to care. Wild.

I'll adjust the help text. You are supposed to put the main config file (which specifies the .exe) in main_file instead of config_file, if that's how you specify the .exe. You have to have something there.

I've changed it to this:
```If the executable is managed in the config file, this should be the config file, instead specifying it in 'Configuration file'.```

**Comment by QmwJlHuSg9pa** [comment]
Hmm, I wonder why `main_file` is mandatory, at all?

DOSBox-Staging allows an arbitrary number of "-conf <filename.conf>" to be set. Though, unfortunately, `config_file` takes a single file name, and when combined with `main_file` they take a maximum of two file names. Though, I suppose more could be specified with "-conf <filename3.conf> -conf <filename4.conf>" under `args`?

So, should `config_file` be redesigned to allow a list of files, with `main_file` made optional if `config_file` is present? Or is this considered a non-issue?

Otherwise, may I suggest:
> If the executable is directly managed by a config file, then this should be that config file. A secondary config file may then be specified under 'Configuration file'.

**Comment by strycore** [comment]
`main_file` refers to either an exe or a conf file.
