### ISSUE TITLE
Cover and banner art has no transparency.

### ISSUE THREAD

**Issue by Genran** [lutris/lutris#5149]
### Bug description

Cover and banner art has no transparency when using a PNG image. Same image works just fine as an icon. Not sure if this is a bug or just not currently supported.

![image](https://github.com/lutris/lutris/assets/152249936/ae48058b-638c-48cb-b99a-b51f6ca5f355)

### How to Reproduce

Go to "Game Info" tab of the "Configuration", add PNG image with transparency to cover, banner and icon. Icon is only one showing transparency.

### Expected behavior

Transparency to be visible in cover, banner art just like icon when using a PNG image.

### Log output

```shell
INFO     2023-11-27 23:48:32,416 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-11-27 23:48:32,418 [startup.get_drivers:70]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.54, 6.5.0-13-generic) (0x73ff)
INFO     2023-11-27 23:48:32,419 [display.display_gpu_info:78]:GPU: 1002:73FF 1458:2334 (amdgpu drivers)
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32:i386"
DEBUG    2023-11-27 23:48:33,434 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-11-27 23:49:23,965 [application.show_window:359]:Showing window EditGameConfigDialog20
DEBUG    2023-11-27 23:49:45,105 [game.save:429]:Saving Empire Earth (wine) with config ID empire-earth-1700852079
DEBUG    2023-11-27 23:49:45,106 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=empire-earth-1700852079, runner=wine) config to /home/david/.config/lutris/games/empire-earth-1700852079.yml
DEBUG    2023-11-27 23:49:46,110 [lutris.add_to_path_cache:160]:Adding Empire Earth (wine) to path cache
DEBUG    2023-11-27 23:49:46,157 [application.on_app_window_destroyed:377]:Removed window EditGameConfigDialog20
```

### System Information

```shell
[System]
OS:              Ubuntu 23.10 Mantic Minotaur
Arch:            x86_64
Kernel:          6.5.0-13-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             62.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.54, 6.5.0-13-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1ubuntu3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon RX 6600 (RADV NAVI23) (1.3.255)
```

**Comment by strycore** [comment]
We apply some image processing on top of banners and coverart, most notably to embed platform icons. 
@danieljohnson2 knows more about this and can tell if keeping transparency is possible. (Might be if we make sure to do all our processing in RGBA images)

**Comment by Genran** [comment]
Ahh, that makes sense. Would definitely be nice to have that alpha channel.

I'm trying to use all custom artwork with drop shadows to make the library look more appealing.

**Comment by strycore** [comment]
> I'm trying to use all custom artwork with drop shadows to make the library look more appealing.

That sounds like something that could be done in the post processing.

**Comment by danieljohnson2** [comment]
Lutris stores banners and cover-art as JPEG files, but icons as PNG. I do not think JPEG supports transparency.

If we supported PNG for banners and cover-art, then what you want to do should work. But right now we transcode things to our preferred format.

**Comment by Genran** [comment]
Found a temporary work around, will see how it goes but may be fine. The path where cover art is stored, I replace the JPG with the PNG and rename the png to x.jpg.

Lutris loads it and displays it just fine even in the config window.

![image](https://github.com/lutris/lutris/assets/152249936/da1530e0-7b58-48ee-9185-6009fb315aa3)
