### ISSUE TITLE
Battle.net Launcher won't launch, WOW.exe launches fine

### ISSUE THREAD

**Issue by uspman** [lutris/lutris#5158]
So when I launch the battle net launcher like I always do, all of a sudden now it opens and closes and shows and closes a debug console window. 

I checked the logs and here is what appears

Started initial process 835539 from /usr/bin/wine /run/media/thomas/902a6ac4-afa4-4ba2-b79b-cab416c0b35c/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe
Start monitoring process.
Initial process has exited (return code: 0)
wine: Unhandled exception 0x80000003 in thread 238 at address 6B4800E1 (thread 0238), starting debugger...
wine: Unhandled exception 0x80000003 in thread a54 at address 6B4800E1 (thread 0a54), starting debugger...
wine: Unhandled exception 0x80000003 in thread 9a8 at address 6B4800E1 (thread 09a8), starting debugger...
wine: Unhandled exception 0x80000003 in thread c08 at address 6B4800E1 (thread 0c08), starting debugger...

the WOW.exe that was installed from the launcher runs just fine, with no errors straight from lutris, but I am worried that now my bnet launcher won't open the game won't update when needed

**Comment by uspman** [comment]
![image](https://github.com/lutris/lutris/assets/88023780/e3ef21ef-975c-45ee-a8de-0ff83d79aa77)

**Comment by strycore** [comment]
> /usr/bin/wine 

You're not using the latest wine-GE which has a patch for the Battle.net update.
