### ISSUE TITLE
Missing gamescope mouse mode toggle in upstream

### ISSUE THREAD

**Issue by h0x32** [lutris/lutris#5159]
Hello,

I have noticed some code from this [PR](https://github.com/lutris/lutris/pull/4741)
is no longer in upstream.

May I ask why the relative mouse mode was removed from upstream Lutris?

**Comment by danieljohnson2** [comment]
That was commit f2ed457:
>This option is undocumented, may not be supported in current GameScope, nobody seems to understand
>what it does very clearly, and can be activated via the custom flags for GameScope anyway.

We didn't think we should advertise a thing like that, and there's an alternative way to use it if you understand the mysterious thing, and want it.

**Comment by strycore** [comment]
We should have some better wording on what that settings does and in which case it should be used because right now it's totally obscure.

**Comment by danieljohnson2** [comment]
I always think reverting the commit is the easy way out, and then I get my comeuppance.

I still can find no useful documentation about this. @Gamertech, do you know enough to give us some text Lutris could display, say in the tooltip on the item? Right now we have this:

>Always use relative mouse mode instead of flipping
>dependent on cursor visibility

Which remarkably unhelpful. If we could tell users when they might want to turn this on, that would be better, I think.

**Comment by Gamertech** [comment]
I can't tell you how it actually 'works' unfortunately, just the end result for the user.

In games that change cursor visibility state, eg. In Apex Legends when exiting the inventory screen, the cursor changes state to hidden and the characters view suddenly snaps to the bottom of the window. Same with FF14.

In Star Citizen when interacting with panels such as an elevator button, the cursor appears and the characters view again snaps to the bottom right corner of the window making it impossible to interact with anything.

While using Gamescope + force_grab_cursor (or native X11) it completely fixes the issue and users can play games normally.

It's a null cursor conflict between xWayland and several window managers, though afaik all but KWin and Sway have fixed it so far.

Here's a couple of tickets for the issue:
https://bugs.kde.org/show_bug.cgi?id=452188
https://bugs.kde.org/show_bug.cgi?id=458233

and a vid: https://www.youtube.com/watch?v=06WeBHs3_QE

**Comment by danieljohnson2** [comment]
Hmm.  Perhaps I can add some text like this:

> This option can fix issues where the mouse appears to move unexpectedly when a game hides or shows the mouse cursor.

**Comment by danieljohnson2** [comment]
@strycore has had a go at it, and changed the tool-tip to this:

>Always use relative mouse mode instead of flipping
>dependent on cursor visibility
>Can help with games where the player's camera faces the floor

So I hope that's reasonable.

**Comment by strycore** [comment]
Hope that describes the issue well enough. We can also give Apex or FF14 as examples.
