### ISSUE TITLE
Wiped symlinked Downloads for as well as most configs for my OS

### ISSUE THREAD

**Issue by cherkie** [lutris/lutris#5167]
Well... I'll try to write what happened the best, however I'm still trying to do damage control and assess what the hell happened. 

I'm currently scraping to undelete files from my home partition. 

I installed something into Lutris from my downloads folder using the existing exe option. Then changed my mind and deleted it... Which along with the folder of the app I needed wiped my downloads folder. For some reason most of my .files and user configs were deleted, too. I'm now in a system from roughly 2-3 weeks back. My personal files are gone, downloads gone. 

Also my entire Lutris folder has been wiped, too. 

Can't provide any logs or more details as my /home partition is in read-only mode just to try to restore it. I'll update it when I can. 

Found an issue which said 'it's only a matter of time until someone wipes their home folder' to which someone said it already happened and safeguards are in place. Well, not really.

**Comment by cherkie** [comment]
Yes. That's the one I pulled from AUR.

**Comment by danieljohnson2** [comment]
Did you pull 0.5.14 of 0.5.9.1 from the AUR?

That link does sound similar, but I don't know how that happened either. That forum post was from Oct 2020, which would have been 0.5.8.1 if he was on the latest then. But 0.5.8.1 had the block to protect ~/Downloads, so the mystery remains.

**Comment by strycore** [comment]
The AUR doesn't have 0.5.9.1, it's Ubuntu that ships it.

How this happened is really not clear. Do you recall what install folder you chose during the install process? Also, only the 1st uninstallation request should prompt for file deletion. If the selected folder is ~ or ~/Downloads, Lutris will disable the deletion option. 

I'll need more details to figure out how this could happen.

**Comment by strycore** [comment]
It gets very confusing. If you install a game and move the files manually, Lutris will no longer propose to delete anything.

I don't know who is giving you Lutris support but the way to install .NET is via Winetricks. Someone is likely giving you bad advice.

**Comment by cherkie** [comment]
Thanks. Appreciated, hope won't happen again.
