### ISSUE TITLE
The UI is a total crashfest right now.

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5170]
We aren't releasing 0.5.15 until this is fixed, this issue is now considered more important than anything else.

No traceback, Lutris just crashes showing this: 

Gdk-Message: 11:38:46.343: Error flushing display: Broken pipe

**Comment by gageracer** [comment]
Whenever I mouse over the advanced settings on any game the whole app disappears. I have to make sure to not hover on settings and scroll down to access env variables.

**Comment by danieljohnson2** [comment]
We've made some efforts on this; I'd ask if you're having the crashes on the latest master, @gageracer.

You don't need to install it; just download the master branch and run the bin/lutris script within. Does that still crash on you?

**Comment by gageracer** [comment]
> We've made some efforts on this; I'd ask if you're having the crashes on the latest master, @gageracer.
> 
> You don't need to install it; just download the master branch and run the bin/lutris script within. Does that still crash on you?

Thanks for the response. It's looking much more stable. No crashes when I hover on any settings with the main branch! 

Great work!

**Comment by abehling** [comment]
@gageracer Same for me. If started from terminal you can see that it core dumps. With different messages beforehand. This does happen randomly but not always.
Examples:
```2023-12-18 23:41:27,039: Starting Lutris 0.5.14
2023-12-18 23:41:27,041: Running AMD Mesa driver 23.3.1 on AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 16.0.6, DRM 3.54, 6.6.7-arch1-1) (0x73ff)
2023-12-18 23:41:27,041: GPU: 1002:73FF 1EAE:6501 (amdgpu drivers)
malloc(): unaligned tcache chunk detected
Aborted (core dumped)
```
```2023-12-18 23:29:33,776: Starting Lutris 0.5.14
2023-12-18 23:29:33,777: Running AMD Mesa driver 23.3.1 on AMD Radeon RX 6600 XT (radeonsi, navi23, LLVM 16.0.6, DRM 3.54, 6.6.7-arch1-1) (0x73ff)
2023-12-18 23:29:33,778: GPU: 1002:73FF 1EAE:6501 (amdgpu drivers)
corrupted size vs. prev_size
Abgebrochen (Speicherabzug geschrieben)
```
Also weird, I assumed problems with locales and tried to start with both LC_ALL and LANG set to C. The latter leads to some of the UI displayed in english (hence LANG=C) but game context menus are still german (System locale de_DE.UTF-8) and advanced config lead to crash.

All tested with latest Archlinux packages and configuration.

@danieljohnson2 master version seems to be fine crashwise although locale settings are not heeded even if I switch explicitly to german in global configuration. So I cannot compare without being able to switch the package version completely to english.

**Comment by danieljohnson2** [comment]
As I recall, you have to [build Lutris with meson](https://github.com/lutris/lutris/tree/master/po#readme) before the LANG= thing works. Lutris' language settings in its UI are for the *games*, not for Lutris itself.

So that's all normal.

**Comment by abehling** [comment]
> As I recall, you have to [build Lutris with meson](https://github.com/lutris/lutris/tree/master/po#readme) before the LANG= thing works. Lutris' language settings in its UI are for the _games_, not for Lutris itself.
> 
> So that's all normal.
> 
> You probably don't want to build Lutris, by the way. You'll need to remove it from ~/.local afterwards, which is a pain.

Ah, ok! Yeah, I won't. master version seems to mitigate these crashes and is snappier than the package version. Thanks! :)

**Comment by danieljohnson2** [comment]
I'm glad it mitigates it; I was hoping they'd be gone. No?

**Comment by strycore** [comment]
Since y'all been using this issue to duplicate #5092 I'm closing it.
