### ISSUE TITLE
Battle.net source doesn't show up while using Arch Linux

### ISSUE THREAD

**Issue by BrandowLucas** [lutris/lutris#5174]
Since Battle.net was implemented as a source in Lutris (0.5.13) it never appeared on the Sources list when using Arch Linux or any arch-based distribution.

On the Lutris release page it recommends installing the "protobuf" dependency although it's already installed (protobuf-25.1-1) and still no avail, I tried using lutris 0.5.13, lutris 0.5.14 and lutris-git package and they all face the same issue.

**Comment by danieljohnson2** [comment]
It's probably the protobuf thing. Still, perhaps you could post a debug-log for us? Run ``lutris -d`` and post the log spam you get. Might be a clue in there!

**Comment by BrandowLucas** [comment]
I don't think the debug output gave us much useful information, but here we go:

INFO     2023-12-07 17:15:03,713 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-07 17:15:03,715 [startup.get_drivers:70]:Running AMD Mesa driver 23.1.9 on AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.13-1-MANJARO) (0x164c)
INFO     2023-12-07 17:15:03,715 [display.display_gpu_info:78]:GPU: 1002:164C 17AA:3F95 (amdgpu drivers)
DEBUG    2023-12-07 17:15:04,053 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-07 17:15:04,862 [http._request:88]:GET https://lutris.net/api/runtimes/versions?pci_ids=1002:164C%2017AA:3F95
DEBUG    2023-12-07 17:15:05,993 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-12-07 17:15:07,065 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-12-07 17:15:15,007 [application.show_window:359]:Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f3e0d9ab1c0 (LutrisWindow at 0x55b2bf8dff80)>}
DEBUG    2023-12-07 17:15:22,330 [application.on_app_window_destroyed:377]:Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f3e0d9ab1c0 (LutrisWindow at 0x55b2bf8dff80)>}
INFO     2023-12-07 17:15:29,137 [application.do_shutdown:1028]:Shutting down Lutris

**Comment by BrandowLucas** [comment]
Well there we go, turns out only the `protobuf` package wasn't enough and the `python-protobuf` was missing, after installing it I got battle.net working!

Here is the debug output:

2023-12-07 18:46:46,948: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
Traceback (most recent call last):
  File "/home/striker/Documents/git/lutris/lutris/services/battlenet.py", line 20, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/home/striker/Documents/git/lutris/lutris/util/battlenet/product_db_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
INFO     2023-12-07 18:46:47,182 [application.do_command_line:464]:Starting Lutris 0.5.14
INFO     2023-12-07 18:46:47,183 [startup.get_drivers:67]:Running AMD Mesa driver 23.1.9 on AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.13-1-MANJARO) (0x164c)
INFO     2023-12-07 18:46:47,184 [display.display_gpu_info:81]:GPU: 1002:164C 17AA:3F95 (amdgpu drivers)
DEBUG    2023-12-07 18:46:47,523 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR

**Comment by danieljohnson2** [comment]
Well, it's a dependency but it's listed as 'Recommends' on our Debian 'control' file- to be installed if available, but you can use Lutris without if it's not available. That seems about right.

I am not sure how AUR does this, or who's in charge of it. I don't think we provide packaging for Arch distributions out of the box.

**Comment by strycore** [comment]
We depend on an old version of protobuf so listing it as a dependency won't work. 
The pb2 generated file needs to be updated to the current version of Protobuf.
