### ISSUE TITLE
"run exe inside Wine prefix" doesn't work with GE versions of Wine. Also can't install games with GE.

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#5178]
I tried to run exe file inside Wine prefix with Wine version set to wine-ge-8-24 or wine-ge-8-25. Exe file doesn't launch at all. Launching the same file with Wine Staging works just fine.

This is what I get in terminal:

**wine-ge-8-25 - some weird error, exe file failed to launch:**

```
INFO     2023-12-10 15:03:15,290 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-10 15:03:15,292 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-10 15:03:15,295 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-10 15:03:15,295 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-10 15:03:15,739 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-10 15:03:16,987 [lutris.get_missing_game_ids:202]:Checking for missing games
Started initial process 13585 from /home/-/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/-/Downloads/ys_i/setup_ys_i_2022-01-03_(52678).exe
Start monitoring process.
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: configuration in L"/home/-/Games/Fallout 2" has been updated.
wine client error:150: write: Bad file descriptor
```

**wine-ge-8-24 - stuck at "wine: RLIMIT_NICE is <= 20, unable to use setpriority safely", exe file failed to launch:**

```
INFO     2023-12-10 15:06:27,715 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-10 15:06:27,716 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-10 15:06:27,717 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-10 15:06:27,717 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-10 15:06:28,175 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-10 15:06:29,434 [lutris.get_missing_game_ids:202]:Checking for missing games
Started initial process 15352 from /home/-/.local/share/lutris/runners/wine/wine-ge-8-24-x86_64/bin/wine /home/-/Downloads/ys_i/setup_ys_i_2022-01-03_(52678).exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

**System 9.0-rc1 (Staging) - exe file launched without problems (I killed the exe file manually, mind):**

```
INFO     2023-12-10 15:17:54,174 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-12-10 15:17:54,175 [startup.get_drivers:57]:Using NVIDIA drivers 535.129.03 for x86_64
INFO     2023-12-10 15:17:54,176 [startup.get_drivers:61]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2023-12-10 15:17:54,176 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2023-12-10 15:17:54,626 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-10 15:17:55,889 [lutris.get_missing_game_ids:202]:Checking for missing games
Started initial process 16413 from /usr/bin/wine /home/-/Downloads/ys_i/setup_ys_i_2022-01-03_(52678).exe
Start monitoring process.
esync: up and running.
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
DEBUG    2023-12-10 15:18:12,319 [command.on_stop:195]:Process 16411 has terminated with code 256
```

**System info from Lutris:**

[System]
OS:              Linux Mint 21.2 Victoria
Arch:            x86_64
Kernel:          6.2.0-37-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.1 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.129.03
OpenGL Core:     4.6.0 NVIDIA 535.129.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.129.03
Vulkan Version:  1.3.204
Vulkan Drivers:  NVIDIA GeForce GTX 1050 Ti (1.3.242)

---
**PS:** The thing is I can launch installed games with GE version of Wine without an issue. But the game has to be installed with native WIne and then eventually switched to GE in game config. Otherwise installation will stall if I try to install game with GE WIne instead of native Wine.

**Comment by danieljohnson2** [comment]
Those look like GOG installers. I've had trouble with them too in the GE stuff; the installer runs but the actual window does not appear.

I suspect that 'run exe inside prefix' is not actually the issue- you could run a game that way that you could run otherwise, it's those GOG installers specifically that don't work. Or so I guess.

**Comment by junglized** [comment]
Ah yeah, you might be right. I've just tried to run Battlefield 1942 Complete Colleection installer with Wine GE and it launched. Why is that happening then? Any ideas? Does it mean I have to have wine version other that GE set as default and then switch manually after installation eventually?

**Comment by danieljohnson2** [comment]
That's what I've done, when this happens. I don't understand it, but I only see on it on my NVidia/Nobara box, not on an Intel/Pop!_OS laptop.

**Comment by junglized** [comment]
I'll stick to that method then. It's not ideal and a little confusing but oh well. Thanks for your time!
