### ISSUE TITLE
Wrong permission check on source folder : can't install from read-only media (CD/DVD)

### ISSUE THREAD

**Issue by Saroumane** [lutris/lutris#5180]
## Context :
OS : Archlinux
Version : lutris 0.5.14
What I want to do : install a game in lutris (with runner : wine) from its original media : a CD-ROM I own.
Error message during installation : The destination folder is not writable by the current user

## Steps to reproduce :

1. Prepare your media : insert CD-ROM in CD Drive (or mount CD image with something like cdemu)
2. Start Lutris
3. Click on + button on top left
4. Choose "Install Windows game from an executable"
5. Choose name and OS version, click "Install"
6. Click on "Install" button on the wine line
7. Verify that the installation folder is OK (writable :smile:  ) and click "Continue"
8. Click on "browse" and select the install executable on your CD-ROM (generally setup.exe)
9. Witness the error message :
![image](https://github.com/lutris/lutris/assets/22261137/576ab485-5936-4ecd-bd5b-32f095d632be)
10. You can click on "Install" but nothing will be installed.

## Workaround : 

Copy every data from the CD-ROM on a temp folder on your drive, and install with lutris from that folder
~~After installation, you can erase this temp folder :  as lutris exposes the CD drive to the game, any "CD check" should be OK.~~
This workaround is far from perfect as the game installed will now believe its CD-ROM is the temp folder. In case of a "simple" CD check, it might work if you keep this folder. If it's not enough to pass the CD check, you'll have to remove this temp folder and create a symlink (with the same name) to your CD drive.
Of course, the best way to avoid these tricks is : 

## Fix expected : 

Remove the "writable permission" check on the "source" folder.

## Closing remarks :
Having a real CD-ROM (or a CD-ROM image in cue/bin format) exposed to a lutris game is not cosmetic. There are real use cases. I already spoke about CD checks, but there are also Windows games with CD Audio tracks that need to be accessed by games.
To my knowledge, lutris is for now the only program on linux that works these dual format Windows CD-ROM (data + audio tracks).
Kudos to the devs !

**Comment by Saroumane** [comment]
@danieljohnson2 You are right, I can't reproduce the failed installation now (i.e. the installation does complete despite the error message). I must have had other settings preventing installation. They were probably linked to the wine runner settings. On my system, lutris comes with a specific wine (wine-ge-8-25) as default, I ended using "System" wine (8.21) and I checked "Prefer system libraries".

**Comment by strycore** [comment]
I install games from CD-ROMs all the time. The warning message can be ignored because the setup.exe file on the CD is not the destination, as the message would suggest. The destination is the wine prefix you selected in the previous step. 

It shouldn't at any point cause an installation to fail. If something fails with wine-GE and not with system Wine then it has to be reported as a separate issue.
