### ISSUE TITLE
"Stop" button kills apps that have read a game file while game is running

### ISSUE THREAD

**Issue by OnARiverMadeOfEyes** [lutris/lutris#5181]
### Bug description
The Stop button will kill any processes that have read a file within the game's folder while the game is running.
'Stop button' will also remain active if such processes are alive.

### How to Reproduce

1. Launch game
2. Open a file contained inside game folder
3. Press Stop button

### Expected behavior
Only the game closes after pressing Stop button.

### System Information
```
[System]
OS:              Linux Mint 21.2 Victoria
Arch:            x86_64
Kernel:          5.17.0-1026-oem
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           12th Gen Intel(R) Core(TM) i7-12700H
Physical cores:  14
Logical cores:   20

[Memory]
RAM:             15.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Graphics (ADL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1~22.04.1
Vulkan Version:  1.3.204
Vulkan Drivers:  NVIDIA GeForce RTX 3060 Laptop GPU (1.3.224), Intel(R) Graphics (ADL GT2) (1.3.238)
```

**Comment by OnARiverMadeOfEyes** [comment]
I'm a game modder, so opening files while a game is running / relaunching are things I do pretty often.
I've at various times had my terminal, text editor, code editor, image editor and file manager killed as I'm using them.

**Comment by OnARiverMadeOfEyes** [comment]
I don't know how Lutris determines which processes are part of a 'game', but right now it seems to be "processes that have touched files inside the game folder"
Literally, as I just tested this by running touch, it killed my terminal.

**Comment by OnARiverMadeOfEyes** [comment]
https://github.com/lutris/lutris/blob/5ecfb95717f5f230e62dd30facafcfe0d81cf0a1/lutris/game.py#L790C1-L808C11
    def get_game_pids(self):
        """Return a list of processes belonging to the Lutris game"""
        if not self.game_uuid:
            logger.error("No LUTRIS_GAME_UUID recorded. The game's PIDs cannot be computed.")
            return set()

        new_pids = self.get_new_pids()
        game_pids = []
        game_folder = self.resolve_game_path()
        for pid in new_pids:
            cmdline = Process(pid).cmdline or ""
            # pressure-vessel: This could potentially pick up PIDs not started by lutris?
            if game_folder in cmdline or "pressure-vessel" in cmdline:
                game_pids.append(pid)

        return set(game_pids + [
            pid for pid in new_pids
            if Process(pid).environ.get("LUTRIS_GAME_UUID") == self.game_uuid
        ])

**Comment by danieljohnson2** [comment]
Lutris should not be doing that; it is supposed to be checking for a special environment variable to avoid this. But I just reproed the bug- it kills processes that contain the game directory in their command lines.

*Not* ideal.

**Comment by danieljohnson2** [comment]
I see the problem- it's essentially or not and; it kills processes that contain the folder in the command line, or which have the environment variable and which have started since the game started. That seems off.

**Comment by strycore** [comment]
> it kills processes that contain the folder in the command line, or which have the environment variable

Unless I'm missing some piece of code, Lutris collects PIDs that have the game folder in the command line **and** have the UUID set. It's not an 'or'.

**Comment by danieljohnson2** [comment]
It's this code:
```python
return set(game_pids + [
            pid for pid in new_pids
            if Process(pid).environ.get("LUTRIS_GAME_UUID") == self.game_uuid
        ])
```

That + there concatenates the lists of pids, then the set() deduplicates. I think that's an 'or'- all distinct PIDs from both lists are included.

**Comment by strycore** [comment]
Oh, right. Well that bit of code is really messed up. I suggest trashing all of it.

**Comment by danieljohnson2** [comment]
I'm all over it. I understand the desired behavior is: stop game_thread.game_process.pid, plus all pids started since the game started, but only if they have the magic env-var and also mention the game folder in the command line.

That's what I'm doing now.

**Comment by danieljohnson2** [comment]
Not sure what's hard. Is it 'intersection_update'? Is there a better way to intersect a set with some other set/list/whatever?

**Comment by strycore** [comment]
why is it intersection_update instead of intersection and why is it not simply `set1 & set 2`

**Comment by danieljohnson2** [comment]
I'm used to mutating mutable collections, and I didn't know about &. That seems more pythonic; I'll switch over to that.
