### ISSUE TITLE
NixOS is a special snowflake that must to things differently for  the sake of being different

### ISSUE THREAD

**Issue by sjhaleprogrammer** [lutris/lutris#5186]
For Nixos users add appimage-run command in front of runners 
like pscx2 for example 
nixos runs app images differently

**Comment by Artek52** [comment]
nixos is the only distro that doesnt destroy itself after an update

**Comment by danieljohnson2** [comment]
Doesn't destroy itself? Where's the fun in that?

Anyway, if NixOS chooses to not be compatible with the ecosystem, that's going to cause compatibility problems with software like Lutris.

I don't see that we ought to special case every odd distribution that does this sort of thing.

**Comment by strycore** [comment]
> nixos is the only distro that doesnt destroy itself after an update

bold statement when I have never had any distro destroy itself after an update since 1997.

**Comment by strycore** [comment]
At some point in the past I wrote on Google+ that Gentoo users should be able to self support themselves. This got people mad. Well the same is true for NixOS. Either you deliver a patch or you use the NixOS support channels.  
No Lutris developer is going to install Nix to work on this. At some point you have to take some kind of responsibility for your choice of operating systems.
