### ISSUE TITLE
lol can't connect to the game

### ISSUE THREAD

**Issue by fadri14** [lutris/lutris#5189]
Hello.

Since a few weeks the game league of legends doesn't work anymore. It actually launches, but when I start a game, I can't connect to it. Here is the error that appears at that time. I'm using the flatpak version.

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x1e00001
  Serial number of failed request:  318
  Current serial number in output stream:  321

Thank you for taking the time to help me.

**Comment by strycore** [comment]
Make sure you get the latest build for lol: wine-ge-lol-8-27

I gave it a try and was able to run the game.

**Comment by fadri14** [comment]
Thank you very much. Indeed, I was on the wine-ge-lol-8-25 version. I changed to the wine-ge-lol-8-27 version and now it works perfectly:
