### ISSUE TITLE
Build tests failing due to today's playtime changes

### ISSUE THREAD

**Issue by solarisfire** [lutris/lutris#5191]
Full log written to /home/solarisfire/.cache/yay/lutris-git/src/build/meson-logs/testlog.txt

<pre>
..................2023-12-17 21:57:15,866: The command "substitute" does not exist.
..2023-12-17 21:57:15,868: This installer doesn't have a 'script' section
..Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
..2023-12-17 21:57:17,081: ModDB tests skipped
........................2023-12-17 21:57:17,096: Migrating basetable field new_field
...............................................2023-12-17 21:57:17,328: Invalid playtime value '-'
F.............
======================================================================
FAIL: test_get_formatted_playtime (test_utils.TestStringUtils.test_get_formatted_playtime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/solarisfire/.cache/yay/lutris-git/src/lutris/tests/test_utils.py", line 95, in test_get_formatted_playtime
    self.assertEqual(strings.get_formatted_playtime(45.90), "45 hours 53 minutes")
AssertionError: '45 hours 54 minutes' != '45 hours 53 minutes'
- 45 hours 54 minutes
?           ^
+ 45 hours 53 minutes
?           ^

-------------------- >> begin captured logging << --------------------
lutris.util.log: WARNING: Invalid playtime value '-'
--------------------- >> end captured logging << ---------------------
</pre>

**Comment by danieljohnson2** [comment]
Whoops!

I need the parse/format ode to round-trip better than it did. I changed it so it would round the fractional part of the playtime to the nearest minute, instead of truncating down to the next minute less. That's what you are seeing here.

**Comment by solarisfire** [comment]
All good now. Thanks for the quick fix!
