### ISSUE TITLE
Wine is not installed on your system

### ISSUE THREAD

**Issue by MrSirKingLord** [lutris/lutris#5192]
![image](https://github.com/lutris/lutris/assets/92161916/2e19eaa2-f108-4c3b-a74a-f44fe17ba98c)
![image](https://github.com/lutris/lutris/assets/92161916/3aee65bd-70ca-45fd-9669-b21a8d1447cb)
![image](https://github.com/lutris/lutris/assets/92161916/7ddd5933-cf57-4617-a1ee-574d06129430)
![image](https://github.com/lutris/lutris/assets/92161916/ae381157-0d16-4bd0-bf49-a10a7ea16b6d)
![image](https://github.com/lutris/lutris/assets/92161916/ee6a5e04-25d7-4921-bad5-12fd18945dd8)

Lutris installed via apt. Using winehq-stable. Same issue with debian wine. Tried older version of lutris, same issue.

**Comment by danieljohnson2** [comment]
Hmm. Lutris is checking of you have a system-wide Wine installed; it is essentially doing ``which wine`` and ``wine --version`` and something is going wrong. Could you issue those commands at your terminal and tell us what you get?

There might also be output in the lutris log that would help. Run ``lutris -d`` at the terminal and trigger the error and give us the log spam that comes out.

**Comment by MrSirKingLord** [comment]
I found the issue, it is because of my modified Lutris.desktop
```
Exec=env WINEPREFIX="~/.local/share/wineprefixes/wine-staging-tkg" lutris %U
#Exec=lutris %U
```
Putting it back to normal fixes the issue, except then my default wineprefix for games is ~/.wine which does not match the default wine version in lutris and is not where i want my games to be. So if I accidentally open a game without setting the prefix for it, my ~/.wine gets messed up from using a non-standard wine on it

Is there a better way to set a default wineprefix for all games? I want all my games to use the same prefix unless i specify otherwise, without having to enter the info in each time

**Comment by strycore** [comment]
At some point Lutris will create a default wine prefix in order not to mess with ~/.wine at all.

**Comment by MrSirKingLord** [comment]
I modified Lutris.desktop as below which seems to give me the behaviour I want:
```
Exec=env WINEPREFIX="/home/peter/.local/share/wineprefixes/wine-staging-tkg" lutris %U
#Exec=lutris %U
```
Seems it didn't like the ~, needed the full path. Thanks
