### ISSUE TITLE
Path information has dissapeared from the uninstall dialog

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5200]
![image](https://github.com/lutris/lutris/assets/280336/038804be-e935-438e-b37d-4fecda3f3b3e)

The most important piece of information about the game removal, the path where the game is installed has been removed.

**Comment by danieljohnson2** [comment]
There's a tooltip for it, and it appears in the confirmation dialog if you are removing only one game.

We can put it somewhere else if you like; where would you like it?

**Comment by strycore** [comment]
Can we put the path under the title in a smaller / less contrasted font? 

I also think we lost some information such as "this location is shared with other games", etc.

**Comment by danieljohnson2** [comment]
I'll see what I can do.

The dialog does notice shared-with-other-games and don't-remove-your-home-directory issues; text goes at the top of the dialog to explain about that, and the relevant games have their delete-files checkbox disabled and unchecked.

**Comment by strycore** [comment]
I don't think that information belongs at the top as it's not clear what games are affected.

**Comment by danieljohnson2** [comment]
Do you like this layout:
![image](https://github.com/lutris/lutris/assets/6507403/0198d287-3e89-48d5-847a-c85db48e56e2)

**Comment by strycore** [comment]
yay, this is perfect! 
Some margins to the left and right sides would make the UI breathe more. Then eventually, we can do something about the "Delete All" / "Remove all" checkboxes :stuck_out_tongue:

**Comment by danieljohnson2** [comment]
I'll take yay for an answer. Here is the version with indentation:
![image](https://github.com/lutris/lutris/assets/6507403/aebd8722-072c-4f2c-84aa-a1d0aa6c904f)

**Comment by strycore** [comment]
Oh, I meant a margin for the whole list box item (Game title, checkboxes and all)

**Comment by danieljohnson2** [comment]
Like so?
![image](https://github.com/lutris/lutris/assets/6507403/b12d03b6-168e-4487-a6d1-8b8e42b7b36c)

**Comment by strycore** [comment]
Yes, much better!
