### ISSUE TITLE
battle.net installation askes me to click "continue" but no "continue" button is present

### ISSUE THREAD

**Issue by rbrooklyn** [lutris/lutris#5203]
As per the title.

See screenshot. There is an "install" button, but no "continue" button.

![image](https://github.com/lutris/lutris/assets/11929484/6930a113-a188-46cb-9afa-04b44d6f8660)

**Comment by danieljohnson2** [comment]
Oh, wow, I changed these buttons back in early January. PR #4683; you can see this bug in one of the screenshots.

I've adjusted the status text to say "click 'Install'". I feel bad though, a years worth of localizations of that one line, gone with the wind. :frowning_face:
