### ISSUE TITLE
Void Linux complaining about missing dependencies, even if the libraries are present.

### ISSUE THREAD

**Issue by xlibun** [lutris/lutris#5212]
```
[System]
OS:              Void rolling void
Arch:            x86_64
Kernel:          6.6.8_1
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 7520U with Radeon Graphics
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             13.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 15.0.7, DRM 3.54, 6.6.8_1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.3.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.3.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.3.1
Vulkan Version:  1.3.268
Vulkan Drivers:  AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) (1.3.267)
```

Lutris is complaining about missing Vulkan libraries in "Runner options" even tho they are installed. 

> **Error** Missing Vulkan libraries
> Lutris was unable to detect Vulkan support for the i386 architecture

and 

> **Error** Vulkan is not installed or is not supported by your system, VKD3D is not available

When I look at the logs it shows me these 3 error messages:

```
i386 libGL.so.1 missing (needed by opengl)
i386 libvulkan.so.1 missing (needed by vulkan)
i386 libgnutls.so.30 missing (needed by gnutls)
```
even though all of these are installed according to `xbps`, Void's package manager:

```
[*] gnutls-32bit-3.8.2_1 GNU Transport Layer Security library (32bit)
[*] vulkan-loader-32bit-1.3.261.1_1           Vulkan Installable Client Driver (ICD) loader (32bit)
[*] mesa-dri-32bit-23.3.1_1 Mesa DRI drivers (32bit)
```

Flatpak version works as intended.

I'm happy to provide more information, if needed.

**Comment by strycore** [comment]
You have to provide a patch by yourself as we do not support directly Void Linux, alternatively, you can use the Flatpak version. 

If you choose to write a patch to accommodate for Void Linux's way of handling libraries, please make it as small and non-disruptive as possible.

**Comment by strycore** [comment]
There is something to fix in the sense that Lutris doesn't see those libraries while they are present. 
Void Linux is unsupported in the sense that no one on the Lutris dev team runs Void Linux or has any plan to install it. So "fully community supported" would be more exact.

We detect libraries by running `ldconfig -p`. If Void Linux chooses to output something different that other distros then there's not much we can do about it, nor it is our responsibility to fix it.

**Comment by strycore** [comment]
Oh that's pretty weird, but that really should be looked at by Void developers.
On our end, the issue is solved.
