### ISSUE TITLE
Cannot launch Citra from Lutris

### ISSUE THREAD

**Issue by sortedcord** [lutris/lutris#5214]
Any Citra game does not launch from lutris and citra won't start at all. It would give this error every single time:

```
/tmp/.mount_citra-eCaGdI/AppRun.wrapped: symbol lookup error: /tmp/.mount_citra-eCaGdI/usr/bin/../lib/libQt6Multimedia.so.6: undefined symbol: _ZN4QRhi9newBufferEN10QRhiBuffer4TypeE6QFlagsINS0_9UsageFlagEEi, version Qt_6_PRIVATE_API
```

I have tried running citra without lutris and I can confirm that there's no issue with citra but something's wrong with Lutris. Any idea as to what is causing this?

Im using KDE Plasma (Wayland) and this problem has started happening recently even though there haven't been any updates to system itself.

**Comment by danieljohnson2** [comment]
I can repro this. It seems to be a conflict with the Lutris runtime; if you disable it in the Citra runner config, it can start.

Watch out, there's a Lutris bug here; when you change the runner config, the settings may not take effect (in some cases) until you restart Lutris. I've tried to fix this, there might be cases I've missed.

So if the setting doesn't do anything for you, try restarting Lutris.

Anyway, I wonder if maybe we should just just use the runtime for AppImage runners. Are they not supposed to  be self-contained?

**Comment by strycore** [comment]
> Anyway, I wonder if maybe we should just just use the runtime for AppImage runners. Are they not supposed to be self-contained?

You'd think that, like I used to. Then you realize AppImages are not self contained at all. 
The weirdest case is the Soulseek AppImage which *only* works with the Lutris runtime. It won't launch at all outside of Lutris!

**Comment by strycore** [comment]
But in most cases, when we're talking about software that is actively being maintained, we shouldn't need the Lutris runtime for most AppImages.

**Comment by sortedcord** [comment]
> I can repro this. It seems to be a conflict with the Lutris runtime; if you disable it in the Citra runner config, it can start.
> 
> Watch out, there's a Lutris bug here; when you change the runner config, the settings may not take effect (in some cases) until you restart Lutris. I've tried to fix this, there might be cases I've missed.
> 
> So if the setting doesn't do anything for you, try restarting Lutris.

Thanks for the tip. I tried installing an older version of Citra (Nightly 2067) and that seems to be working with lutris.

**Comment by strycore** [comment]
> Thanks for the tip. I tried installing an older version of Citra (Nightly 2067) and that seems to be working with lutris.

Can you try with the current version and the runtime disabled?

**Comment by sortedcord** [comment]
I reverted back to Citra (Canary 2477) and apparently now it works without any issues, even with the lutris runtime enabled

**Comment by strycore** [comment]
I updated the Citra runner to use the latest version and I can reproduce the issue with the Lutris runtime. I changed that in the runner's default configuration and now Citra launches without issue.

**Comment by danieljohnson2** [comment]
Well, I installed Citra again and it now runs. I think it's fixed.
