### ISSUE TITLE
[itch.io] Refreshing library not working

### ISSUE THREAD

**Issue by mainrs** [lutris/lutris#5215]
The refresh icon is available, as is the disconnect icon. Pressing the refresh button does nothing; it does not start to spin. 

When running `lutris -d` I get the following output:

![image](https://github.com/lutris/lutris/assets/5113257/ca16df75-880d-492a-8abd-fa559f3b8d01)

**Comment by strycore** [comment]
Likely, we need to use this error to automatically disconnect you. 
If you disconnect then reconnect, does it end up working?

**Comment by GoGoOtaku** [comment]
Just as a heads up: Login in again does work. My guess is that the token expired (either time or server side by itch.io)
After logging back in I was also able to reload my library normally.

**Comment by danieljohnson2** [comment]
I've made an attempt at improving how Lutris deals with these 401s; it considers you logged out if it happens now. I hope that helps, but I can repro this, and maybe nobody can.
