### ISSUE TITLE
[Feature Request] Add Flatpak Version of Dolphin Emulator as an Option for the Runner

### ISSUE THREAD

**Issue by SMGttv** [lutris/lutris#5217]
Title: 

Request to Add Flatpak Version of Dolphin Emulator as an Option for the Runner

Description:

I'm writing to propose the addition of the Flatpak version of the Dolphin emulator as an option for the runner in Lutris. 

The motivation behind this request stems from the difficulties I've encountered with the current implementation of Dolphin. Specifically, I've been experiencing errors such as "Failed to create Vulkan surface" and "Failed to initialize video backend". These issues have hindered the proper functioning of the emulator.

However, when I switch to the Flatpak version of Dolphin, it works flawlessly right out of the box. Given this, I believe that including this version as an option for the runner could potentially alleviate similar issues for other users. 

Doing so could enhance the user experience by reducing the likelihood of encountering such errors when using the Dolphin runner with Lutris.

**Comment by strycore** [comment]
We have support for the Flatpak version of Dolphin. Uninstall the lutris provided Dolphin runner and make sure the Flatpak is install. Lutris will use it.
