### ISSUE TITLE
Games Don't Launch At All Without Specifying Prefix

### ISSUE THREAD

**Issue by ShadowOfTheDark669** [lutris/lutris#5218]
Launching games after a fresh lutris install , with all wine and vulkan dependencies doesn't launch the games , only when the default .wine or any other custom prefix is specified , the games launch . 

This Issue makes it very tough for new users who are new to linux gaming and might completely lift off their trust off of it .
This also happens in the latest lutris-git version as well and didn't exist in v5.13

**Expected Behaviour**

After a fresh install , the games work as intended if all the dependencies are satisfied.

**Actual Behaviour**

The games refuse to launch spewing a 13568 (something like this) error code and only work once the default or a custom prefix is specified

**Steps To Reproduce**

Get and install the latest lutris 5.14 
Add games
Try to launch them

**System Information**
Vulkan support: YES

Esync support: YES

Fsync support: YES

Wine installed: YES

Gamescope: NO

Mangohud: NO

Gamemode: NO

Steam: YES

In Flatpak: NO

[System]

OS: EndeavourOS rolling rolling

Arch: x86_64

Kernel: 6.6.9-arch1-1

Desktop: KDE

Display Server: x11

[CPU]

Vendor: GenuineIntel

Model: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

Physical cores: 2

Logical cores: 4

[Memory]

RAM: 7.5 GB

Swap: 2.0 GB

[Graphics]

Vendor: Intel

OpenGL Renderer: Mesa Intel(R) UHD Graphics (ICL GT1)

OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.3.2-arch1.2

OpenGL Core: 4.6 (Core Profile) Mesa 23.3.2-arch1.2

OpenGL ES: OpenGL ES 3.2 Mesa 23.3.2-arch1.2

Vulkan Version: 1.3.274

Vulkan Drivers: Intel(R) UHD Graphics (ICL GT1) (1.3.267)

**Comment by danieljohnson2** [comment]
Lutris guesses the prefix if its left blank, and that works for me.

I'd ask if you can provide the 'Executable' path for a game that's not working? If it's in a prefix, we should figure that out.

Maybe also provide the debug log. At the terminal, run ``lutris -d`` and give us the log spam that appears. There may be an error or something that would provide a clue.

**Comment by strycore** [comment]
Not specifying the prefix is the same as setting it to ~/.wine, which isn't recommended to begin with.

I was able to run a game just fine without specifying the prefix.

**Comment by danieljohnson2** [comment]
I just double checked this, and Lutris does guess the prefix if it can. The code for this is in prefix.py, find_prefix().

Why it doesn't work for @ShadowOfTheDark669 I can't say, but a bug is at least possible.

**Comment by strycore** [comment]
find_prefix is mostly used to guess a prefix path if the game is located in one. In the original post, it was implied the game was added manually without any prefix present.

In Lutris 0.5.16, we'll default to a prefix created by Lutris, most likely in ~/Games/windows/win64. This way we make sure ~/.wine is never touched by Lutris.

**Comment by ShadowOfTheDark669** [comment]
So I deleted my default .wine prefix and .local/share/lutris folder to reproduce this , then reinstalled lutris-git and ran check for updates which installed the required lutris components such as dxvk , etc. I added my game and ran without specifying the prefix from the terminal with the lutris -d command and the result was the game not launching , specified the default .wine prefix and everything worked fine. Logs:

`[yeagerist@yeagerist-hpallinone22df0xxx ~]$ lutris -d
2024-01-06 08:52:56,777: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-01-06 08:52:56,962 [application.do_command_line:470]:Starting Lutris 0.5.15
INFO     2024-01-06 08:52:56,964 [startup.get_drivers:67]:Running Intel Mesa driver 23.3.2 on Mesa Intel(R) UHD Graphics (ICL GT1) (0x8a56)
INFO     2024-01-06 08:52:56,964 [display.display_gpu_info:78]:GPU: 8086:8A56 103C:87A4 (i915 drivers)
DEBUG    2024-01-06 08:52:57,178 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-01-06 08:52:57,250 [lutris.get_missing_game_ids:206]:Checking for missing games
WARNING  2024-01-06 08:52:57,310 [lutriswindow.get_missing_games:426]:Path cache out of date? (7 IDs missing)
DEBUG    2024-01-06 08:52:58,467 [grid.on_item_activated:102]:Item activated: 1
DEBUG    2024-01-06 08:52:58,524 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
lutris-wrapper: fwe
Started initial process 9812 from /usr/bin/wine /home/yeagerist/GamerX/Far Cry 2 Fortunes Edition/bin/FarCry2.exe
Start monitoring process.
wine: created the configuration directory '/home/yeagerist/.wine'
wine: configuration in L"/home/yeagerist/.wine" has been updated.
Monitored process exited.
Initial process has exited (return code: 13568)
Exit with return code 13568
DEBUG    2024-01-06 08:53:09,637 [command.on_stop:219]:Process 9810 has terminated with code 13568
DEBUG    2024-01-06 08:53:10,555 [game.beat:837]:Game thread stopped
WARNING  2024-01-06 08:53:10,555 [game.on_game_quit:874]:Game still running (state: running)
INFO     2024-01-06 08:53:10,555 [game.stop:848]:Stopping fwe (wine)
DEBUG    2024-01-06 08:53:10,555 [game.stop_game:804]:fwe (wine) has run for 12 seconds
DEBUG    2024-01-06 08:53:10,555 [application.on_game_stop:792]:Removing 1 from running IDs
DEBUG    2024-01-06 08:53:10,567 [game.stop_game:816]:Playtime: 1 minute
DEBUG    2024-01-06 08:53:10,567 [game.on_game_quit:892]:fwe stopped at Sat, 06 Jan 2024 08:53:10
DEBUG    2024-01-06 08:53:10,692 [lutris.add_to_path_cache:164]:Adding fwe (wine) to path cache
DEBUG    2024-01-06 08:53:10,703 [xrandr.change_resolution:128]:Switching to 1920x1080 on eDP-1
INFO     2024-01-06 08:53:10,703 [xrandr.change_resolution:139]:Switching resolution of eDP-1 to 1920x1080
DEBUG    2024-01-06 08:53:15,811 [grid.on_item_activated:102]:Item activated: 1
DEBUG    2024-01-06 08:53:15,867 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
`

**Comment by danieljohnson2** [comment]
Ok, so it looks like @strycore was right. Don't understand how he knew it.

The game is at ``/home/yeagerist/GamerX/Far Cry 2 Fortunes Edition/bin/FarCry2.exe`` and it is falling back to the prefix ``/home/yeagerist/.wine``. The wine binary it has selected is ``/usr/bin/wine`` which is the system Wine.

That first path looks to me like it is not in a Wine prefix- it should have ``drive_c`` in it somewhere it if was. 

I did some testing, and it appears that using the wrong prefix like this does break games; I'd expect the system Wine would also be inadequate, but you seem to be saying that fixing the prefix alone fixes the problem, so I guess that's not it.

Lutris has no way to find the right prefix for the game here if you don't provide it. @strycore's idea (to provide our own default prefix) might work- my testing suggests that it helps. I don't really understand what's wrong with ``~/.wine`` though.

But I don't think that can make it in in time for 0.5.15.

I don't think this is a huge deal for new users- if you let Lutris install your games it creates a prefix for each and installs the game in the prefix by default. That configuration should work.

**Comment by ShadowOfTheDark669** [comment]
A suggestion , it would also be nice to use a custom prefix globally for all programs/games like bottles does.
