### ISSUE TITLE
Ubisoft Connect not launching

### ISSUE THREAD

**Issue by Eric-Bwr** [lutris/lutris#5231]
Hello, since I have troubles getting the ubisoft connect app to run after a system reboot (yes it worked fine the first time but after a restart it doesnt open anymore...), how far is the ubisoft connect integration into lutris?

Is there any documentation on that?

**Comment by strycore** [comment]
Ubisoft Connect has been working good lately. The Lutris integration is optional, it lets you import your Ubisoft library in Lutris and launch games directly. The important part is getting the Ubisoft Connect client to work. 

Please share the console output when launched with `lutris -d`

**Comment by Eric-Bwr** [comment]
I just reinstalled lutris and now everything works, hm weird, closin this though :)
