### ISSUE TITLE
"Accounts" tab in settings is blank

### ISSUE THREAD

**Issue by pizzadude** [lutris/lutris#5232]
![image](https://github.com/lutris/lutris/assets/1454420/ad64e7a6-b8e2-4080-b031-da99b643279c)

When navigating to the "accounts" tab in the lutris settings (version 0.5.15), it is blank and I get this error. This is on Fedora 39 KDE.

```
2024-01-14 08:52:03,865: Error handling signal 'row-selected': 'PersonalName'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/preferences_dialog.py", line 109, in on_sidebar_activated
    generator()
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/accounts_box.py", line 33, in populate_accounts
    account["PersonalName"]
    ~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'PersonalName'
```

My only guess is that my steam display name has a " / " in it. But I'm not sure.

I have both Steam RPM and Steam flatpak installed.

**Comment by danieljohnson2** [comment]
Good thing I made this lazy load, or the whole dialog would be disabled.

It looks like your Steam account has no Personal Name; I don't know why that would happen. But I have tweaked the master branch to cope by showing the steam account ID instead in this case. Ugly but better than crashing.

There may be some sort of impersonal name we should be using here, but I don't know Steam too well.

Please download the master branch and run the bin/lutris script within- no need to install. Is the Accounts tab less blank now?

**Comment by pizzadude** [comment]
Yeah, the master branch works, but is the steam account ID supposed to be a string of numbers?

**Comment by danieljohnson2** [comment]
It's an ID, but not a very good name. I don't have a Steam account to try this with, so I am not too sure what other name we could show here.

@strycore, Can you take a look at this? We might be able to do better than "don't crash" here.

**Comment by danieljohnson2** [comment]
Well, I think we found out why you have no Personal Name- it's apparently meant to be "Persona Name" instead. Not sure what happened here, but I expect in the next Lutris release the names will be back. At least 0.5.16 partially fixes this by showing the IDs.
