### ISSUE TITLE
Games need to be run twice in Lutris 0.5.15 in Fedora 39 KDE (Wayland) if "Disable desktop effects" is enabled

### ISSUE THREAD

**Issue by pizzadude** [lutris/lutris#5233]
Games need to be run twice for them to launch in Lutris 0.5.15 in Fedora 39 KDE (Wayland) if "Disable desktop effects" is enabled. On first click of the "play" button, with "Disable desktop effects" enabled, instead of the game running, you get a popup box in lutris that says "run_in_background". In CLI it shows this:

```
2024-01-14 09:07:07,067: Rayman Origins (wine) has encountered an error: 'run_in_background'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 29, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 629, in configure_game
    self.set_desktop_compositing(False)
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 351, in set_desktop_compositing
    disable_compositing()
  File "/usr/lib/python3.12/site-packages/lutris/util/display.py", line 372, in disable_compositing
    _, stop_compositor, background = _get_compositor_commands()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/display.py", line 337, in _get_compositor_commands
    run_in_background = command_set["run_in_background"]
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'run_in_background'
2024-01-14 09:07:23,969: Shutting down Lutris

```

After disabling "Disable desktop effects" in global options, the problem goes away.

**Comment by danieljohnson2** [comment]
Whoops! This is a botched fix for buggy compositor detection code from weeks ago, but I guess the users who use lutris-git don't run KDE's compositor, or don't turn it off.

This setting isn't there for your compositor, and it should be defaulting to ''False"; I've added code to do this to master.

Please download the master and run the bin/lutris script; no need to install. See if things work better now. I think it will work now.

It is a bit strange that you can run a game with this problem at all, though. Not sure why the second run works.

**Comment by pizzadude** [comment]
Confirmed that master branch fixes the issue. Thanks!

**Comment by danieljohnson2** [comment]
Unfortunately the only work-around here is not use option to disable to compositor.

OTOH, non-composited desktops are pretty obsolete these days. On Wayland you just can't disable composition at all. I expect this option won't survive in Lutris for too long anyway.

**Comment by pizzadude** [comment]
I am aware, I had this option enabled a long time ago and never bothered turning it off after switching to Wayland.
