### ISSUE TITLE
Lutris flatpak: Missing libFLAC.so.8 when trying to run ScummVM games

### ISSUE THREAD

**Issue by terzag** [lutris/lutris#5236]
Using Lutris 0.5.14 as a flatpak on Xubuntu 23.10.
(EDIT: just got an update to Lutris, 0.5.15 but no change; I also made sure to check for updates for the runners.)

When trying to run DreamWeb (using the ScummVM runner with the game downloaded from their website), it doesn't start and I get the following log:

```
Started initial process 1006 from gamemoderun /home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm --extrapath=/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --themepath=/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --scaler=normal --scale-factor=3 --path=/mnt/data2/Jeux/dreamweb dreamweb
Start monitoring process.
/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

I'm not sure if it's looking for that old version of libFLAC in the flatpak runtimes or in the system libs (only v. 12 is available −and already installed− in the Ubuntu 23.10 repos). I'm not sure if it's specific to DreamWeb or is a general issue with the ScummVM runner.

EDIT: just tried Beneath a Steel Sky (from the ScummVM website too), which doesn't have any FLAC file, same issue. So, most likely a general issue with the ScummVM runner rather than specific games.

**Comment by terzag** [comment]
FWIW, the issue is still there in Lutris 0.5.17. I would assume that the flatpak runtime with which Lutris is built doesn't provide that version of libFLAC (or libFLAC at all)?

**Comment by strycore** [comment]
This error is totally unrelated to the lutris client

**Comment by terzag** [comment]
The client, maybe, but it seems to be related to the ScummVM runner included in the Lutris client.

ScummVM on its own (even as a flatpak) works without a similar issue.

**Comment by danieljohnson2** [comment]
Perhaps this issue would be more appropriate [in the Lutris flatpak repo](https://github.com/flathub/net.lutris.Lutris)?

**Comment by terzag** [comment]
Perhaps. I didn't see that there was a dedicated repo. Do I have to open a new bug report there or is it possible to transfer that one (I'm not too familiar with GitHub)?

**Comment by danieljohnson2** [comment]
I think it can be done, but I don't have access to that repro to do it. I think you'd better close this and open a new one in the right repo.

**Comment by terzag** [comment]
OK. AFAIK, Lutris officially manages the flatpak package now and the FlatHub page points to the repo we're in for reports. Plus, the other repo seems to haven't been updated in a long time, though there are still bug reports opened there.

So, not too sure which one is the right one. I'll keep the current report opened just in case (the admins can just close it if needed, I guess) and opened a new one in the other repo: https://github.com/flathub/net.lutris.Lutris/issues/422

**Comment by danieljohnson2** [comment]
Well, most of the bugs in the Lutris client do belong here I think. It's not always easy to know when it's the packaging and when it's the product.

**Comment by legluondunet** [comment]
1) in Lutris, uninstall ScummVM runner
2) install Scummvm Flatpak
3) in Lutris, ScummVM options, specify a "custom executable for the runner" org.Scummvm.ScummVM, like this:

![image](https://github.com/user-attachments/assets/0cb90afc-5981-4f81-b0f1-ead139102015)

4) Use Flatseal to manage ScummVM Flatpak access to your games directory
