### ISSUE TITLE
Wine Steam is stopped twice

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#524]
When quitting a Wine Steam game, Steam is stopped twice, even after a wineserver -k. If wine is stopped using wineserver -k, Steam shouldn't need to be stopped even once.

**Comment by daniel-j** [comment]
Is that why Lutris freeze when I close a winesteam game (with close steam when game exits enabled) for a few seconds?

**Comment by strycore** [comment]
Not really, that's another issue. But it does cause Lutris to freeze a few seconds longer.

**Comment by strycore** [comment]
> Is that why Lutris freeze when I close a winesteam game (with close steam when game exits enabled) for a few seconds?

Maybe that was it after all. The call to runner.stop wasn't being run with AsyncCall while the one I kept was.
