### ISSUE TITLE
osu!stable install fails on 0.5.15

### ISSUE THREAD

**Issue by Razuuu** [lutris/lutris#5240]
My Machine:
```
[System]
OS:              Debian GNU/Linux n/a trixie
Arch:            x86_64
Kernel:          6.5.0-5-amd64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6650 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.0-5-amd64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1
Vulkan Version:  1.3.268
Vulkan Drivers:  AMD Radeon RX 6650 XT (RADV NAVI23) (1.3.255)
```

https://lutris.net/games/osu/ -> Version: Stable

I am trying to install osu! Stable with the latest version of Lutris (0.5.15) but it won't ?download? the file.
Everytime it says
"Quelle nicht gefunden: installer"
which means in English:
"Source not found: installer"

Edit: Nvm got it: https://xgob.in/42qn4c8p (random paste server lol)
```
DEBUG    2024-01-16 00:08:02,070 [interpreter._iter_commands:317]:Installer command: {'merge': {'dst': '$GAMEDIR/drive_c/osu/', 'src': 'installer'}}
DEBUG    2024-01-16 00:08:02,079 [commands.merge:276]:Merging installer into /media/ssd/GameLibrary/Lutris/osuLutrisLatest/drive_c/osu
ERROR    2024-01-16 00:08:02,079 [errors.__init__:18]:Quelle existiert nicht: installer
{'dst': '$GAMEDIR/drive_c/osu/', 'src': 'installer'}
ERROR    2024-01-16 00:08:02,079 [jobs.target:33]:Error while completing task <function ScriptInterpreter._iter_commands.<locals>.dispatch at 0x7fe880166980>: <class 'lutris.installer.errors.ScriptingError'> Quelle existiert nicht: installer
{'dst': '$GAMEDIR/drive_c/osu/', 'src': 'installer'}
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 31, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 327, in dispatch
    return method(params)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 281, in merge
    raise ScriptingError(_("Source does not exist: %s") % src, params)
ERROR    2024-01-16 00:08:02,079 [interpreter._iter_commands:302]:Last install command failed, show error

```
I don't really know how to debug or see logs, or where it is located (whatever)
but after downgrading to 0.5.14-2 it works just fine.

Now i can select if i want to Download OR Select the file from my disk.

Sorry for my bad english btw and i hope this gonna be fixed!
I don't want to be toxic! I love Lutris! Thanks for the hard work!

**Comment by danieljohnson2** [comment]
This looks like #5238 but in German. We've got a fix in master, and a new release is coming soon.

You can try the master by downloading it, and running the bin/lutris script within. No need to install! You should be able to install your game that way.

**Comment by Razuuu** [comment]
Yep you got the same issue like me, but i just downgraded lutris and installed the game. After that i just upgraded it because i don't install that much windows games via lutris

**Comment by danieljohnson2** [comment]
Ah, If I'd gotten the bug I would have fixed it before release. But it worked for me, and looked foolproof. What could go wrong?

Anyway, closing this issue as a duplicate.
