### ISSUE TITLE
Cannot connect to GOG account (0.15.14, Nobara bundled version), empty window

### ISSUE THREAD

**Issue by gunters63** [lutris/lutris#5242]
I am using Lutris 0.15.14, the one bundled with Nobara 39.

When I try to connect my GOG account I just get an empty Window like this:

![Screenshot_20240116_090900](https://github.com/lutris/lutris/assets/90346/70488786-f02e-4b6b-955b-32d4427963e7)

[System]
OS:              Nobara Linux 39 KDE Plasma
Arch:            x86_64
Kernel:          6.7.0-202.fsync.fc39.x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 7945HX with Radeon Graphics
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             62.5 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.29.06
OpenGL Core:     4.6.0 NVIDIA 545.29.06
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.29.06
Vulkan Version:  1.3.270
Vulkan Drivers:  NVIDIA GeForce RTX 4060 Laptop GPU (1.3.260)

If I start Lutris from the command line, there are no messages.

**Comment by strycore** [comment]
Upgrade to the current Lutris version and if you still somehow have a blank login window, run Lutris with WEBKIT_DISABLE_DMABUF_RENDERER=1 

This is a bug on Nvidia GPUs

**Comment by gunters63** [comment]
Thank you, WEBKIT_DISABLE_DMABUF_RENDERER works like a charm :)
