### ISSUE TITLE
Games become slower in lutris

### ISSUE THREAD

**Issue by ds47x** [lutris/lutris#5247]
few months ago my games didn't have an issue, they run smoothly but after months of not gaming idk it just got laggy like the cpu crank to 98% on the loading screen 

my laptop spec is 8gb ram, 1tb hdd, i3-7100u, with the Intel HD 620 

I had used this comand before to increase performance 

`sudo system dev.i915.perf_stream_paranoid=0`

the output I got when saying lutris on the terminal and launching a game 

``Unsupported locale setting: unsupported locale setting

(lutris:8541): Gtk-WARNING **: 19:46:09.148: Locale not supported by C library.
        Using the fallback 'C' locale.
2024-01-17 19:46:16,946: Starting Lutris 0.5.16
2024-01-17 19:46:17,132: Running Intel Mesa driver 23.3.3 on Mesa Intel(R) HD Graphics 620 (KBL GT2) (0x5916)
2024-01-17 19:46:17,134: GPU: 8086:5916 1028:078B (i915 drivers)
Gtk-Message: 19:46:22.386: Failed to load module "appmenu-gtk-module"
2024-01-17 19:46:22,388: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
2024-01-17 19:46:28,642: Runtime disabled by system configuration
2024-01-17 19:46:28,800: Runtime disabled by system configuration
Started initial process 8678 from gamemoderun mangohud /home/neba/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /run/media/neba/D/games/Assassins's Creed 4 - Black Flag/AC4BFSP.exe
Start monitoring process.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
gamemodeauto: 
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
ERROR: Could Not Get Primary Adapter Handle
gamemodeauto: 
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
gamemodeauto: 
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
gamemodeauto: 
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.``

the locale is 
`locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=Default.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=`

I tried d/t runners and it brings the same output

**Comment by pojunen** [comment]
Assassins's Creed 4 - Black Flag with such hardware, for surely it's never been more than few fps?

**Comment by danieljohnson2** [comment]
That locale change was just cutting back on the locale drop-down we provide in the settings. I don't think the locale error you are getting is something new; at least it's not because of that change.

We did it because the old drop-down was often absurdly enormous, and because it was crashing Lutris on KDE. Never understood why, but this change resolved it.

**Comment by strycore** [comment]
On a Surface Pro 6 with i5-8250U CPU and UHD Graphics 620 Assassin's Creed is somewhat playable. At 1400x900, with all options decreased, I get around 22 to 30 FPS.  After playing for a while, the CPU will thermal throttle and drop to 7 FPS. So I need to pause the game for a while. I didn't apply any tweaks, this is on a default Nobara 39

![Screenshot from 2024-01-21 02-47-58](https://github.com/lutris/lutris/assets/280336/519b99f7-edb4-4db6-8112-11f03bf01ef4)

I got to after the title screen on the Surface and a 8bit Do controller. Since this is a Ubisoft game, this is quite a bit of gameplay.

**Comment by ds47x** [comment]
i found the issue it was on my power adapter. idk why but it was limiting the amount of power to the laptop i knew when i restart the pc and a warning page came up saying the amount of power is undetermined 
![lollllll](https://github.com/lutris/lutris/assets/100286253/bdf14d35-ad52-4654-9826-131995c5e4dc)


sorry for the trouble

**Comment by strycore** [comment]
Lutris, the best tool to troubleshoot your laptop issues :sunglasses:
