### ISSUE TITLE
Can not uninstall Wine runners anymore.

### ISSUE THREAD

**Issue by sithdaddy** [lutris/lutris#5251]
I have Lutris 0.5.16 installed on my computer and i am trying to uninstall unused wine version from the "Wine version management" menu in the preferences.
When I try to do that i get a pop up saying that "The folder could not be moved to trash".

**Comment by danieljohnson2** [comment]
I think this is a flatpak thing; it works for me in a 'real' install, but not a flatpak install.

**Comment by danieljohnson2** [comment]
I think I have it. At least, this change works for me.

We need to set some additional flags to flatpak won't let us trash the file or folder. I've committed a change to do this, but it's not easy for you to test it without an updated flatpak release.

If you want to get this now, you'd need to graft the updated ``portals.py`` from the repo into the flatpak Lutris install. Probably voids the waranty.
