### ISSUE TITLE
Different directories for game and wineprefix

### ISSUE THREAD

**Issue by Vikezor** [lutris/lutris#5257]
Currently, when installing a game, you choose one installation directory, which will contain both the game files and the wine prefix. When removing a game, that directory is deleted, which means your save files are deleted, as they are in the wine prefix. Avoiding save file deletion currently require the user to manually copy files somewhere else as far as I can tell. I propose the ability to set a different directory for the wine prefix (and to make it different by default), like how Heroic does it:
![2024-01-20-173521_717x697_scrot](https://github.com/lutris/lutris/assets/6238226/c6922111-74e9-43e0-93e0-e84d9bc73e49)
If game removal then deletes the game folder but keeps the wine prefix, one could uninstall games without worrying about save files. This issue covers a similar use case to #57 and #4314 so is maybe too similar idk

**Comment by strycore** [comment]
We have plans for game saves backup and sync.

Your assumption that removing a game folder will protect your game saves simply isn't true. Many games store their saves directly in the game folder.
