### ISSUE TITLE
Add support for custom platforms

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#526]
got an update tonight, and got everything working as I want (meaning moar cores for RA), and found that there seem to be bug?
http://i.imgur.com/BAg9vUP.png

you now have a sone/sega/atari/nintendo with all their  games in it.

Another thing, I see one can no longer attach a platform for individual files, would it be possible in the future? IE I've setup to run Creativision games, but they are currently identified as Linux games O_o

**Comment by daniel-j** [comment]
Yes, you can filter games by manufacturer (or PC), it's a feature!
Right now custom platforms have been disabled, might return layer when I figure out how to do it best.

**Comment by telanus** [comment]
@daniel-j just a thought. For custom platforms, could one create a file like desktopapps.py (or add to it) and add executables to it that "whitelist" these executables, thus like my creativision emu you could add the executable to the whitelist, and then lutris could examine the file and add these custom platforms

Just a mockup:

```
platform-exec = (
    "fs-uae"
    "fs-uae-launcher"
    "playonlinux"
    "creatiVision"
)

class CustomP(Platforms):
    human_name = "Platforms"
    description = "Custom Platforms"
    platforms = (
        ('Amiga',),
        ('Amiga'),
        ('Windows'),
        ('Creativision'),
    )
```

**Comment by strycore** [comment]
I've removed the manufacturer feature when I added persistence for the platform (otherwise Lutris would become a sluggish atrocity for anyone with more than a few hundred of games).

Now that platforms are a simple string stored in database, it would be easy to make them customisable but I think this would require an extra field to be able to tell if the platform was manually changed by the user.

**Comment by telanus** [comment]
THe Vice platform seems to have gone AWOL

**Comment by strycore** [comment]
This ticket is a mess and I don't know what it's supposed to fix anymore. 
Gonna close it, if anything else needs a fix, please re-open another one.
