### ISSUE TITLE
pga.db and game-paths.json should be in ~/.config/lutris

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5260]
`pga.db` and `game-paths.json`contain **unique and irreplacable information** about Lutris library. Therefore they should be in `~/.config/lutris`, not in a temporary-type path. User can reasonably expect to be able to mount `~/.cache` as `tmpfs`.

**Comment by danieljohnson2** [comment]
Those two files are different. ``game-paths.json`` will be regenerated if lost from the various game configuration (.yml) files. It belongs in ``~/.cache/lutris``. It should stay there.

``pga.db`` does not live in ``~/.cache/lutris`` and never has, as far as I can tell. It can be in ``~/.config/lutris`` but more recent Lutris versions (0.5.15+) will use ``~/.local/share/lutris``.

0.5.15 also moves the banners and coverart from ``~/.cache/lutris`` to ``~/.local/share/lutris``; these directories contain user-provided media, not just stuff we can regenerate, so this is safer.

Lutris hasn't yet tried to actually move all these things in existing installations- it just uses the old directories if they are present. This make support easier, though I suppose we'll eventually do a migration.

So I don't think we can or should do anything here.

**Comment by drws** [comment]
You're right about `pga.db` location, that was a mistake on my part. I still think there could be a bug about `game-paths.json`. In one case I transferred Lutris to another computer, copied `~/.config/lutris` and `~/.local/share/lutris`, but not all games (some game folders were missing in the new installation). Without `game-paths.json` Lutris opened with an empty library and IIRC even deleted all XMLs (even of games that had the files). `versions.json` and `updates.json` probably weren't the culprit, but I copied all three (and the XMLs again) and Lutris worked afterwards.

**Comment by danieljohnson2** [comment]
That should not have happened; Lutris should be able to regenerate a missing ``game-paths.json`` given that it has its ``pga.db`` and the game's .yml files.

We don't use XML files for game config. Not trendy enough.

**Comment by drws** [comment]
Of course, YML. ECC error :D But the files were definitely removed, had to copy them again.

**Comment by drws** [comment]
Another thing with `game-paths.json` that may or may not merit a separate issue report is that Lutris adds same paths (duplicated lines) to `game-paths.json` if game installation is tried more than once. I don't know whether this could pose a problem, so please comment if you have any input and I can open another issue if needed.

**Comment by danieljohnson2** [comment]
That is peculiar. There should not be duplicated lines, but you can have duplicated *paths*- with different ids. This happens when you duplicate a game for instance.

Sure the ids are also duplicated?

**Comment by drws** [comment]
Yes, whole line duplicated, including the ID. I'm thinking... After removal of a game from the library, the ID is freed up and that might confuse checks somehow?

**Comment by danieljohnson2** [comment]
That is very hard to explain.

Lutris builds a dict and writes it out as a JSON file; you should never have the same key twice. It's doing this whenever it changes the ``game-paths.json``, even if it is just adding or removing one path.
