### ISSUE TITLE
versions.json and updates.json belong into ~/.config/lutris

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5261]
`versions.json` and `updates.json`contain **unique and irreplacable information** about Lutris runners and runtimes (install time, state, etc.). A temporary path such as `~/.cache/lutris` is not suitable for such information. For example, `~/.cache` could very well be mounted as `tmpfs`.

Both `~/.config/lutris` or `~/.local/share/lutris` are more suitable. I'm not sure whether developers aim for a single config folder with all the unique information (most portable). In this case `~/.config/lutris` is the one, otherwise `~/.local/share/lutris` is the solution.

**Comment by strycore** [comment]
~/.config/lutris is being deprecated in favor of ~/.local/share/lutris

**Comment by drws** [comment]
That's great news, but the issue is about some unique information in a temporary path `~/.cache`. Merging the two persistent paths doesn't solve this one automatically.

**Comment by danieljohnson2** [comment]
My reply to this seems to have gotten lost somewhere.

We're moving ~/.cache/banners and ~/.cache/coverart to ~/.local/share/lutris already; Lutris 0.5.15+ will use the existing .cache directories if found, but will create these directories in the new location if not. We'll probably do a proper migration at some point.

versions.json and updates.json are not problematic; if these are lost, Lutris will just check for updates at next startup and then recreate these files. There's no need to preserve them.

**Comment by drws** [comment]
At first glance it seemed they contain unique information which seems to not be the case. All clear now.
