### ISSUE TITLE
versions.json contains redundant info and can also contain old hardware information

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5262]
The `versions.json` file contains the `gpus` and `hw_support` keys. First of all, **both keys aren't updated** when hardware changes. And the optimal solution is different for both:

* The `gpus` key is **unrelated** to the other information in the file. It ~~contains~~ caches hardware identification information, but not really any version information. It should probably just be removed (why would it need to be cached anyway?) or at least moved to a separate file in `~/.cache/lutris`.

* The `hw_support` key is version-related, should stay in `versions.json`, but should also get updated if hardware changes (check at Lutris start and write to the file **only if necessary** to update the information.

**Comment by danieljohnson2** [comment]
It isn't quite this bad. That file is regenerated if it is found to be more than 6 hours old. But it would be better to notice GPU changes at once and not delay in that case.

But to implement that, I think we would need something like that ``gpus`` key in the file so we could tell what GPU data was present when it was generated. How else can we tell it's been changed?

**Comment by drws** [comment]
It's still unclear why hardware-related information and software-related one are intertwined in the same cache file. Package management is one issue, hardware management another. It is understandable that new versions of installed packages are delayed by a few hours. But if user starts Lutris with a GPU that requires/recommends additional packages they should be offered right away. Small amount of these cases should mean negligible influence on server load.

One issue with current implementation is also when downgrading a GPU. Cached old GPU capability data could mean unplayable games for hours until unnecessarily unified cache finally refreshes. If the only feature of caching GPU information is to detect when a new one is installed, this seems like an optional feature that could be configurable (and possibly even off by default).

**Comment by strycore** [comment]
don't worry about it.
