### ISSUE TITLE
Not recognizing drivers installed until installing flatpak version

### ISSUE THREAD

**Issue by ACR-Jeff** [lutris/lutris#5267]
I have tested this on both void linux and debian 12, Installed Lutris version is 0.5.14 from the package managers, Neither installed from within the package managers are recognizing graphics drivers installed, Until after installing flatpak Lutris  version 0.5.16, After having both the version from the package manager and the flatpak version installed they both recognize the Graphics drivers and there after the settings can be managed by the user.
I bring this up because I have had issues with Lutris not detecting installed graphics drivers for a long time now on many distros, And in hopes this will help solve the issue in the non flatpak version.

**Comment by strycore** [comment]
Oh nice! A game!

My divination powers tell me that your drivers are.... Nvidia drivers 535!

**Comment by ACR-Jeff** [comment]
> Oh nice! A game!
> 
> My divination powers tell me that your drivers are.... Nvidia drivers 535!

Thank you for replying, No I have an AMD GPU with Vulkan support and have both mesa-vulkan-radeon mesa-vulkan-radeon-32bit installed
