### ISSUE TITLE
Flatpak version 0.5.16 not recognizing /mnt directory

### ISSUE THREAD

**Issue by ACR-Jeff** [lutris/lutris#5268]
Flatpak version 0.5.16 not recognizing /mnt directory while version 0.5.14 installed from the distros (void and debian 12) package manager recognizes /mnt directory, Which is a path to my drive I have my games installed. I have even tried using flatseal to manage filesystem paths, Without success.

**Comment by strycore** [comment]
>  I have even tried using flatseal to manage filesystem paths, Without success.

If at first you don't succeed, try and try again (you were certainly in the right direction)

Also, have you considered installing the deb version of 0.5.16?

**Comment by ACR-Jeff** [comment]
This solved it for me, Accessing External storage from Flatpak apps https://github.com/flatpak/flatpak/issues/2713#issuecomment-466559580

Execute this commend in your terminal `flatpak override --user --filesystem=/path/to/dir org.app.Id`

**Comment by strycore** [comment]
That's why I was surprised it didn't work with Flatseal, this is exactly what it's supposed to do.

**Comment by ACR-Jeff** [comment]
> That's why I was surprised it didn't work with Flatseal, this is exactly what it's supposed to do.

According to the flatpak devs comment, The app maintainer has the choice to use the file chooser portal, Yet many don't, https://github.com/flatpak/flatpak/issues/2713#issuecomment-1796737143

**Comment by strycore** [comment]
We use the file chooser portal in Lutris. Here, you're not choosing a file, you're choosing a folder containing potentially hundreds of games. I'm really not sure the file portal is the solution here.
