### ISSUE TITLE
Steam game library sync error on steam deck 

### ISSUE THREAD

**Issue by cazzoo** [lutris/lutris#5272]
On my Steam deck using Lutris 0.5.16 I tried to sync my Steam library.
When doing so, it's kinda working but in the end of the sync I received thiz message as a pop-up: 'NoneType' object is not subscripable.
The only option I have from that pop-up is to click "ok" to get back to the app.
Then, I can see no imported banners for all the games that has been synced, I'm not sure this is a known bug or not but I can't find a way to get them.
What worth to be said, if I get to "Games" view (top left item), I can see the images of the installed games.

Finally, while checking the "Installed Games Only" filter from the hamburger menu, my Steam games list displays nothing despite the fact I have installed games (on both the sd or SSD). It means I have to "install" all the installed games manually, it's not automatically detecting them. When clicking on the "Play" button, nothing happens. The button changes to "Playing" and then suddenly get back to "Play"

**Comment by danieljohnson2** [comment]
This sounds like issue #5248.

We've got a fix in master, but I don't think you can easily get that onto your Steam Deck.

**Comment by cazzoo** [comment]
That looks indeed really close.

I wonder, is there currently a roadmap/plan/schedule of releases ?

**Comment by danieljohnson2** [comment]
Hard to say; I think it depends on how bad 0.5.16's bugs turn out to be. We've got a few people hitting this bug, and I think it is the worst one.

**Comment by strycore** [comment]
> I wonder, is there currently a roadmap/plan/schedule of releases ?

Next release is coming soon, 0.5.16 is super buggy and we need to ship a more stable release ASAP.
