### ISSUE TITLE
Ability to quickly obtain game ID for CLI launch

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5276]
There seems to be no easy/quick way to obtain Lutris' internal ID of a game, needed for launching from CLI. One has to first create a `.desktop` file from which the ID can then be read. Hopefully I didn't miss some obvious way, but there should be one.

**Comment by AinoSpring** [comment]
Right-click on the game -> open logs
shows the game ID basically at the start of every line.

**Comment by AinoSpring** [comment]
But you are right this feature should be properly implemented.

**Comment by danieljohnson2** [comment]
Might be preferable to use the form "lutris:rungame/<slug>" rather than "lutris:rungameid/<id>"

Confusingly, the slug is what appears as "Identifier" in the game config dialog.

**Comment by strycore** [comment]
Slugs are non unique, we need to show the numerical ID in the game properties while still keeping the presentation elegant (it shouldn't be a read only full width text entry)

**Comment by strycore** [comment]
Fixed
