### ISSUE TITLE
Better auto-determination of game executable

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5278]
Lutris' auto-selection of game executable offers some room for improvement. In one case I noticed it selecting `dxwebsetup.exe`, which could be blacklisted from auto-selection logic.

More importantly the auto-selection sometimes finds game's `.exe` and in other cases `.lnk` (in the Start Menu folder). In the case of LNK it could be resolved into proper EXE path.

**Comment by strycore** [comment]
I've added "*setup*" to the list of excluded exes.

> More importantly the auto-selection sometimes finds game's .exe and in other cases .lnk 

I don't see how this is more important. We can flawlessly launch .lnk shortcuts.

**Comment by drws** [comment]
Yes, launching LNKs (resolving them every execution) works, but it introduces a **totally needless** point of failure. Even Windows installers offer an option not to install shortcuts, because they are **optional**. Yes, Lutris won't find LNKs if they're not installed, so why would it search for them in the first place? And if it does, why wouldn't they be resolved once and for all, not every time around?

Performance-wise it doesn't show on modern computers, but that doesn't mean resources are to be needlessly wasted. Also, why wouldn't Lutris run as smooth as possible even on older hardware/HDDs/etc.

So yes, this is **more basic and therefore more important** than blacklisting setups where false positives (and false negatives that the `*setup*` filter might produce) are expected anyways.

AFAIK thoroughly and cleanly sandboxed games are a long-term goal. I'll also speculate that in future one execution wrapper less will allow for just a bit less complicated (and therefore more secure) execution path.

**Comment by drws** [comment]
You addressed only the easiest argument. Ok, performance hit is neglible in practice even with HDD, leaving that aside.

However, currently game execution is dependent upon an auxiliary file which shouldn't be touched (needless point of failure), and also why wouldn't the logic behind executable selection be deterministic?

So what about these?
