### ISSUE TITLE
Support Last update year in addition to Release year in game metadata and list view

### ISSUE THREAD

**Issue by drws** [lutris/lutris#5280]
One interesting piece of information while browsing/maintaining/overviewing a game library in addition to a game's year of release is also year of its last update. Lutris could support setting and showing this the same way _Release year_ is already implemented, possibly as an additional option that enabled the column in the list view for those that'd find it useful.

**Comment by danieljohnson2** [comment]
You seem to have a lot of ideas. This one might be a good one for you to try yourself, and submit a PR.

Just telling us to do this or that feature is all that likely to work, but if you submit the PR, it's got a much better chance of getting into Lutris.

And this one does not sound too challenging to implement. Know any Python?

**Comment by drws** [comment]
Actually I'm planning to take up some of them when I'm finished with some current projects, if someone else doesn't before. Learning Lutris' ins and outs inbetween. All in all it's still best to put the ideas down here so they're not forgotten.

**Comment by strycore** [comment]
I'll give you a pointer: if you plan working on metadata stuff like this, you will have to start with the Lutris website and its API.

Under no circumstance should you add fields to the Lutris client that are not known by the  Lutris API.

**Comment by danieljohnson2** [comment]
Not so easy as I thought, then. What's the story with 'sortname'? Is that in the API somewhere I don't see?

**Comment by strycore** [comment]
Sortname isn't a supported feature

**Comment by strycore** [comment]
Or, to put it differently, it's just cosmetic, it's just a way to sort values differently. I very much doubt sort name will ever be integrated in the API.

**Comment by strycore** [comment]
We have no current plans to support updated year (no game platform does afaik)
