### ISSUE TITLE
Lutris "Game" tab cannot locate Steam game banners/thumnails

### ISSUE THREAD

**Issue by d3nwah** [lutris/lutris#5284]
Hi!
![2024-01-28_14:49:18_447x498](https://github.com/lutris/lutris/assets/6751254/91ce17e7-4ac2-487a-90f1-fedeb412ef30)
![2024-01-28_14:48:58_452x167](https://github.com/lutris/lutris/assets/6751254/cf221589-4ff9-444f-a4e8-8f8cd384ac0c)

I've noticed the discrepancy between how game banner art is fetched between the category tabs. A game has a banner for the Steam, but not for the Game tab, even though the display resolution is the same (the Zoom option set to the smallest one), and so there's (in my opinion) no reason for them not to show in the Game tab.

My version of Lutris is the current git build lutris-git 0.5.16.r29.g04d99bbce-1 (Sun 28 Jan 2024 02:40:53 PM CET). The issue is not a regression (iirc), it's been like that since I can remember.

I don't know how much of it is a bug, and how much a feature request, though I lean towards the former, as the display resolution between both tabs in this scenario are the same. The game in the pic is freeware on Steam, and so convenient for reproing

**Comment by danieljohnson2** [comment]
This is how it is; the thing is that Steam and Lutris have separate banners. They are different sizes. If lutris.net doesn't have a banner for the game, you get the grey rectangle of doom even if there's a Steam banner.

It might be nice if we could bring over the Steam banner when the Lutris banner is missing, but Lutris has never done that. It should work, I think, though it'll look a bit off since the banner will have the wrong size compared to the others in the view.

**Comment by strycore** [comment]
Not a bug. Lutris banners come from the Lutris website. Steam banners come from Steam. They are not the same. The fact they share the same format is purely coincidental.

**Comment by strycore** [comment]
The only bug is the client not fetching the Lutris media when syncing Steam games, which is something that should be working afaik. 

The Lutris game does hava a banner, it should get synced: https://lutris.net/games/4d-minesweeper/

**Comment by strycore** [comment]
>  They are different sizes.

No, they are the same size, at least for the 184x69 banner
 
> It might be nice if we could bring over the Steam banner when the Lutris banner is missing, but Lutris has never done that.

Lutris has done that for year, it's done on the website, not the client.
