### ISSUE TITLE
DRM free mode for steam games doesn't work

### ISSUE THREAD

**Issue by tuxrinku** [lutris/lutris#5285]
When I try to launch a steam game without opening steam, I get this error :
`Traceback (most recent call last):
  File "/usr/share/lutris/bin/lutris-wrapper", line 205, in <module>
    main()
  File "/usr/share/lutris/bin/lutris-wrapper", line 132, in main
    process_pid = subprocess.Popen(args).pid
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/media/rinku/Disque_local/SteamLibrary/steamapps/common/RESIDENT EVIL 4  BIOHAZARD RE4/re4.exe'`

I tried with several games, it happens to all of them. The DRM free mode is checked in game options.

**Comment by strycore** [comment]
DRM free is when you can run a Steam game without having Steam open. Very rare games can be run that way, certainly not Resident Evil.
