### ISSUE TITLE
[Feature Request] When Removing a Game give an option to Delete 

### ISSUE THREAD

**Issue by smokey5787** [lutris/lutris#5287]
When removing games they go to Trash. As there are multiple screens before you remove could you add an option to just delete the files? Only asking as I don't use Trash and only noticed today that this is what was taking up space on my HDD. I understand if you don't want to implement it. Just asking. BTW great program, makes life so much easier.

**Comment by strycore** [comment]
Nope. Too many people messed up so no it is out of the question to let Lutris permanently delete game files.

**Comment by smokey5787** [comment]
Cool, that's understandable
