### ISSUE TITLE
Hidden Enviroment Variables?

### ISSUE THREAD

**Issue by ZeusThundr** [lutris/lutris#5289]
I installed Overwatch 2 using this install [script](https://lutris.net/api/installers/overwatch-2-battlenet?format=json) available on https://lutris.net and removed the `DXVK_HUD: "compiler"` from the "battle-net.yml" file in my `~/.config/lutris/games` folder after installation completed. There was no way for me to remove it using Lutris so I deleted it using a text editor and saved the file. Even after doing so while in game I still see the enviroment variable is still set and have no Idea where to look to remove it.

This isn't the only issue I have with environment variables, but I like to keep things in byte size chunks and don't want to accidentally put two possibly unrelated issues into one issue as I assumed that is a pain, but if you would like me to add it here I can.

**Comment by strycore** [comment]
![Screenshot_20240130_160657](https://github.com/lutris/lutris/assets/280336/d637316e-17b5-421a-aa68-8081afc24490)

![Screenshot_20240130_160236](https://github.com/lutris/lutris/assets/280336/1ad71e29-fd78-45a1-a867-b261b9c807d0)

**Comment by ZeusThundr** [comment]
I thought in my last reply it was sufficient for you to conclude that implicitly it is not where you demonstrated. I should have specified that it does not in fact show up where you demonstrated as a key-value pair, and that there is no occurrences of the "DXVK_HUD: compiler" environment anywhere in the battle-net.yml file in `~/.config/lutris/games`.

**Comment by ZeusThundr** [comment]
I understand that this isn't required nor conventional but I did find that originally `DXVK_HUD: compiler` was present in the battle-net.yml file and did not show up in where demonstrated. Since there are multiple sections for where to specify environment variables in the following file `~/.config/lutris/games/battle-net.yml` and the section in which this environment variable was stored/set was not the the same section I was able to edit inside of Lutris itself. I concluded this by just adding a random key value pair insides Lutris, and then checking the file afterwards noting that the environment variable was only set in one of the sections specified with "env:". With this installation [script](https://lutris.net/api/installers/overwatch-2-battlenet?format=json) of OW2 I see two sections where you can change the environment variables when I grep for "env:" in this other installation [script](https://lutris.net/api/installers/overwatch-2-standard?format=json) after it is done installing and then checking the files in my `~/.config/lutris/games/`  I get three occurances of "env:" when I grep for "env:' in the `~/.config/lutris/games/overwatch-2.yml`. Seemingly these sections are all valid places where to set/store environment variables; Which is not the issue here the issue is that the environment variable `DXVK_HUD: compiler` is not set or present in the battle-net.yml file since I removed it manually and double checked inside Lutris to make sure it was not being set as a key value pair and even still the shader compilation pop-up still appears in game. Only for this [installation](https://lutris.net/api/installers/overwatch-2-battlenet?format=json) of OW2

**Comment by ZeusThundr** [comment]
> Then check your runner level options (wine) and global options.
> 
> At no point Lutris requires users to edit files in ~/.config/lutris, it is simply not a thing.

How would I check my runner level options and or global options are you referring to the other menus inside of Lutris when clicking on configure?

**Comment by ZeusThundr** [comment]
@strycore friendly ping :) I legitimately believe this is an issue and or could cause future issues to arise please feel free to correct me if my intuition is wrong, but maybe having the yml files in `~/.config/lutris/games` only have one area where environment variables are set/handled like the way [bottles](https://github.com/bottlesdevs/Bottles) does might simplify and or prevent them from being improperly set.

**Comment by strycore** [comment]
@ZeusThundr I beg you to stop looking at Lutris configuration files. You have to acknowledge that we copy the installation script that was used to install a game to the YAML file but this serves **no purpose at all**. It is just here for reference, because it is easy to do and because it might be useful in the future (although with our recent developments, it seems unlikely)

The yaml file has one and only one place where the environment variables are set, the rest must be ignored. If removing an environment variable has no effect then it is possible the variable is set at the runner or system level. 
You can access wine's config in the sidebar next to the Wine entry. The system's options are located in the general preferences.
