### ISSUE TITLE
Epic Games Launcher crash with gamescope enabled

### ISSUE THREAD

**Issue by pspkzar** [lutris/lutris#5290]
I'm trying to get Epic Games store workin on my Steam Deck OLED. It apparently works propperly in Desktop Mode but in Gaming Mode I get window popups with the error assertion failed in winevulkan.dll, winevulkan/loader.c line 664, !status.
After some testing I could gather that the error occurs when enabling gamescope, which is always on in gaming mode.
Both Lutris and gamescope are installed through flatpaks. 

Steps to reproduce:
1: Instal lutris: flatpak install flathub net.lutris.Lutris
2: Instal gamescope: flatpak install flathub org.freedesktop.Platform.VulkanLayer.gamescope
3: Instal Epic Games Launcher through lutris
4: Launch Epic Games Store and login
5: Launch Epic Games Store in Steam Deck gaming mode or with gamescope enabled in the Epic Games Launcher settings.

Some additional things that may help: disabling DXVK for the epic games launcher or uninstalling the gamescope flatpak the issue disappears. However, removing the gamescope flatpack would remove HDR support, and disabling DXVK for the Epic Games Launcher and games installed through it may heavily impact gaming performance.

**Comment by Omer-Farooqui** [comment]
Hey, maybe you should try to use Heroic launcher. It does a better job of porting Epic Games to linux. Im not a maintainer of this project btw.

**Comment by Mordius** [comment]
This also happens on bottles, so probably it's Gamescope's issue
