### ISSUE TITLE
Can't log into Itch.io

### ISSUE THREAD

**Issue by TheUncannyObserver** [lutris/lutris#5293]
I'm trying to log into Itch.io, but when I click the button to do so, the login dialog box pops up but the website never loads, so the box just stays blank. I've tried logging in with and without a VPN, on different wifi networks, to no avail.

I'm sorry that I don't have any other information to share, because I don't know where any logs might be.

**Comment by danieljohnson2** [comment]
Sounds rather like #5242. the website loads but you can't see it.

It's apparently a NVidia driver issue, I think, and running Lutris with the env-var WEBKIT_DISABLE_DMABUF_RENDERER set to one might help. So try this at a terminal:

```
WEBKIT_DISABLE_DMABUF_RENDERER=1 lutris
```

Is that better?

**Comment by TheUncannyObserver** [comment]
It is indeed the same bug, because feeling around with the cursor showed me where there was input fields on the blank dialog.

That env-var did not work, however you mentioning NVIDIA gave me the idea to try running Lutris with Wayland active, and that allowed me to see the login page. Normally I use X11, because of NVIDIA bugs with *other* apps.
