### ISSUE TITLE
Cant log in with Epic, because login screen is blank

### ISSUE THREAD

**Issue by RMRubert** [lutris/lutris#5298]
Just the title. 
The screen is blank and does not show the login form.
I am on fedora 39, with lutris 0.5.16

The behaviour is almost consistent, so far from only once actually showed me the login form, and then never again.

https://github.com/lutris/lutris/assets/11463633/d640ea31-d2e6-4efd-ad06-ecfdc011b48a

[lutris-issue-report.json](https://github.com/lutris/lutris/files/14201511/lutris-issue-report.json)

**Comment by danieljohnson2** [comment]
Sounds like issue #5293 or #5242.

If so, you could try running in Wayland, or using the env-var ``WEBKIT_DISABLE_DMABUF_RENDERER=1``.

**Comment by RMRubert** [comment]
I can confirm that running `WEBKIT_DISABLE_DMABUF_RENDERER=1 lutris` does absolutely nothing and I still have a blank screen.

How can I try running in Wayland, I am not that familiar with linux?

**Comment by danieljohnson2** [comment]
If your installation has Wayland, it'll be a choice you make when you log in. There may be a button in the lower right corner of the screen when you enter your password.

On mine, I can choose "GNOME" or "GNOME on X.Org"; the former is Wayland.

**Comment by RMRubert** [comment]
That did work, with plasma seems to be working the windows. I can see the windows with wayland.
However I am reluctant to use plasma if the default of fedora kde is x11, or at least that was already configured when I installed kde.

**Comment by danieljohnson2** [comment]
Very good; you'll have to decide how you wan to configure your desktop- Lutris can't put you into Wayland for its own sake.

I suspect that the actual bug is in WebKit really, but in any case I don't think we can do more here.

**Comment by strycore** [comment]
>  I am reluctant to use plasma if the default of fedora kde is x11

I'm not sure about vanilla Fedora but on Nobara the default KDE session is using Wayland.
