### ISSUE TITLE
AttributeError: 'ScriptInterpreter' object has no attribute 'script'

### ISSUE THREAD

**Issue by amirzp** [lutris/lutris#5300]
Why do I get this error when I want to install a game? For example this game https://lutris.net/games/medal-of-honor/ LIBRETRO version

Lutris version:  0.5.16

error:
DEBUG    2024-02-09 13:07:59,511 [http._request:88]:GET https://lutris.net/api/installers/medal-of-honor-underground-gba
DEBUG    2024-02-09 13:07:59,941 [application.show_window:392]:Showing window InstallerWindowmedal-of-honor-underground
DEBUG    2024-02-09 13:08:01,294 [displayconfig.get_current_resolution:643]:Retrieving current resolution
INFO     2024-02-09 13:08:01,311 [interpreter.get_runners_to_install:257]:Runner <lutris.runners.libretro.libretro object at 0x703f47b5b100> needs to be installed
DEBUG    2024-02-09 13:08:01,311 [interpreter.install_runner:276]:Installing libretro
ERROR    2024-02-09 13:08:01,311 [exception_backstops.error_wrapper:81]:Error handling idle function: 'ScriptInterpreter' object has no attribute 'script'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 444, in launch_install
    if not self.interpreter.launch_install(self):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 211, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 265, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 280, in install_runner
    version=runner.get_installer_runner_version(self) if runner.has_runner_versions else None,
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 156, in get_installer_runner_version
    version = installer.script["game"].get("core")
**AttributeError: 'ScriptInterpreter' object has no attribute 'script'**

**Comment by amirzp** [comment]
Lutris version is 0.5.16

**Comment by danieljohnson2** [comment]
I believe I see the problem; looks like a copy & paste error that affects only libretro.

I have corrected it, and you can test this by downloading the latest Lutris master. You can just run the 'bin/lutris' script within, no need to install anything. You should be able to install your game with that.

**Comment by amirzp** [comment]
Thanks, the problem is solved
