### ISSUE TITLE
Syndicate (1993) from EA APP is mistaken with AC Syndicate

### ISSUE THREAD

**Issue by aliasbody** [lutris/lutris#5301]
When trying to install Syndicate (1993) from the EA App using the EA APP login in Lutris, instead of sending a command to EA APP to start the download/install of that game it sends the wrong ID and tries to install Assassin's Creed Syndicate.
![Captura de ecrã de 2024-02-09 12-40-21](https://github.com/lutris/lutris/assets/9455122/79d5c26d-8f86-4f01-bd40-152b760639b6)
![Captura de ecrã de 2024-02-09 12-40-39](https://github.com/lutris/lutris/assets/9455122/0c80cff3-1055-45c3-a6a0-6c70e84aa4b0)
![Captura de ecrã de 2024-02-09 12-41-55](https://github.com/lutris/lutris/assets/9455122/42113fa3-882f-40b6-aaf9-328f8714361b)

**Comment by strycore** [comment]
I can confirm this issue.

**Comment by strycore** [comment]
While I confirm this issue, there's nothing we can do about Electronic Arts being complete assholes and mixing up Syndicate with AC Syndicate. Clicking on "Get the game" will actually download Syndicate (1993) and not AC. 

EA has to fix their shit, there's nothing we can do about it.
