### ISSUE TITLE
Lutris is failing to download correct wine version for installer when a specific wine version is specified

### ISSUE THREAD

**Issue by OJ2024** [lutris/lutris#5302]
I am trying to summarise an error (or several) that have appeared on discord, reddit and lutris forums relating to the installation of some games failing due to lutris attempting to download wine-ge-8-26 during the installation of a new game and not the required wine version specified in the installer.

For simplicity, I will reference the Dec 2023 installer for eve-online which requires wine 7.2-2 to install (specified as wine version in the installer) but needs newer version to run (currently 8-26). For replicating the issue, I have used lutris 0.5.16 deb on Ubuntu 23.10 Cinnamon, with all dependencies in place (upgraded from 0.5.14 which has LoL and BNet games installed). Both 8-27 LOL and 8-26 wine versions are installed, and the 8-26 has been configured as the default wine version and confirmed in wine.yml. No other wine versions other than wine-9.1 (staging) as system wine are installed.

Click on the + button -> Search lutris for game -> eve online -> select the Dec 2023 installer and used default folder.

Lutris attempts to download and extract wine-ge-8-26 (which is already installed) and throws the following error:

`Failed to extract /home/jhu/.cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0.2205.0' -> '/home/jhu/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/lib/libgstpbutils-1.0.so.0'`

This is what is set in the eve online installer:

```
  wine:
    overrides:
      msvcp140: n
      msvcp140_1: n
    version: lutris-7.2-2-x86_64

```
This is the traceback info:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 170, in extract_archive
    system.merge_folders(source_path, destination_path)
  File "/usr/lib/python3/dist-packages/lutris/util/system.py", line 350, in merge_folders
    shutil.copy(os.path.join(dirpath, filename), os.path.join(dst_abspath, filename), follow_symlinks=False)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 252, in copyfile
    os.symlink(os.readlink(src), dst)
FileExistsError: [Errno 17] File exists: 'libgstpbutils-1.0.so.0.2205.0' -> '/home/jhu/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/lib/libgstpbutils-1.0.so.0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 510, in extract
    extract_archive(archive, dest, merge_single=merge_single)
  File "/usr/lib/python3/dist-packages/lutris/util/extract.py", line 177, in extract_archive
    raise ExtractError(str(ex)) from ex
lutris.util.extract.ExtractError: [Errno 17] File exists: 'libgstpbutils-1.0.so.0.2205.0' -> '/home/jhu/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/lib/libgstpbutils-1.0.so.0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 278, in install_runner
    runner.install(
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 492, in install
    self.download_and_extract(runner_version_info["url"], **opts)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 504, in download_and_extract
    self.extract(archive=runner_archive, dest=dest, merge_single=merge_single, callback=callback)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 513, in extract
    raise RunnerInstallationError(_("Failed to extract {}: {}").format(archive, ex)) from ex
lutris.runners.RunnerInstallationError: Failed to extract /home/jhu/.cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0.2205.0' -> '/home/jhu/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/lib/libgstpbutils-1.0.so.0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 444, in launch_install
    if not self.interpreter.launch_install(self):
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 211, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 265, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 285, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to extract /home/jhu/.cache/lutris/wine-lutris-GE-Proton8-26-x86_64.tar.xz: [Errno 17] File exists: 'libgstpbutils-1.0.so.0.2205.0' -> '/home/jhu/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/lib/libgstpbutils-1.0.so.0'

```

This is what is currently present in ~/.local/share/lutris/runners/wine :
wine-ge-8-26-x86_64
wine-ge-lol-8-27-x86_64

**Comment by november781** [comment]
as a workaround - manually downloading the specified wine version seems to allow affected installers to work

workaround tested and mostly working on the eve-online installer
downloading lutris-7.2-2 allows the eve-online installer to run as normal.
the install still fails due to the newest versions of the eve launcher crashing in wine

**Comment by OJ2024** [comment]
> as a workaround - manually downloading the specified wine version seems to allow affected installers to work
> 
> workaround tested and mostly working on the eve-online installer downloading lutris-7.2-2 allows the eve-online installer to run as normal. the install still "fails" due to the launcher crashing on normal wine but with wine-ge or proton and some manual file linking it runs fine

Yes the workaround does work, we confirmed this before posting this error report, though a couple of people who were testing this workaround noted that you needed to set the 7.2-2 as the default wine, just having it downloaded did not allow the install to proceed without causing the bug outlined in this issue.

A change request for the eve-online Dec 2023 installer to fix the file location (local/eve-online folder which has a symlink to the current launcher installed). There is a "crash" - wine throws 2 errors when the eve logo appears, but you just need to wait and most times it does complete. Once installation is complete you do need to switch to wine-ge-8-26 to launch it. Right now there is no way to specify an installation wine version and execution wine version in the install script.

**Comment by danieljohnson2** [comment]
Finally got around to looking at this. Easy repro, easy fix. The Wine runner is missing a flag that says it should have specific versions; we only seem to use it for this download, so nobody noticed. The result is that instead of downloading the missing version of Wine, it tries to download the current one.

I'll put that notation in; I believe that will fix this issue.
