### ISSUE TITLE
Duplicating a game does not retain the cover art, banner, and icon images

### ISSUE THREAD

**Issue by AlexFolland** [lutris/lutris#5303]
### Steps to reproduce

1. In the Lutris client, install a game with a Lutris script from lutris.net which applies cover art, banner, and icon images (example: battle.net).
2. In the Lutris client, duplicate the game that was installed in step 1.

### Observed behavior

Duplicating a game does not retain the cover art, banner, and icon images.  They are reset to the default.

### Expected behavior

Duplicating a game is expected to retain cover art, banner, and icon images from the original source of the duplicated game.

**Comment by strycore** [comment]
If the duplicated game shares the same name as the original one, I don't see why it wouldn't share the coverart. 
Personally, I have never used that feature to keep the name or coverart, I have always changed it to something else.

I just tested right now and if the name is similar to the original game (you remove the "2" at the end) then the artwork stays.

To be fair, adding "2" for the copy is really not ideal and we really should find something better, apart from that, the feature is working as expected.

**Comment by danieljohnson2** [comment]
Well, I don't think he wants to *share* the cover art, but to *copy* it.

I think we probably don't want to give the duplicate the same slug ('identifier'); if we do that then customizing one will change the cover art for the other. But perhaps the duplicate command should copy the media files already there?

**Comment by strycore** [comment]
> Well, I don't think he wants to share the cover art, but to copy it.

That makes no sense. Our cover art is based on the game's slug. If the slug is the same then the cover art is the same. We're not assigning a cover art to a different slug.

**Comment by danieljohnson2** [comment]
As you wish.

Would you like the trailing numbers changed to something else? I figured it was bad to have nothing at all, but also bad to default to the same name as the original- thus the numbers.

We could append "(duplicate)" or something instead, that would work fine.

**Comment by strycore** [comment]
It's not my wish, it's how our system works. We can't just make random changes while keeping a cohesive system.

**Comment by strycore** [comment]
> Would you like the trailing numbers changed to something else? I figured it was bad to have nothing at all, but also bad to default to the same name as the original- thus the numbers.

Yes, I would like it to retain the original name. It just doesn't make sense for Doom to turn into Doom 2 just because it was duplicated. If it's duplicated and the users wants to keep the same game then the name needs to stay, if the user wants to use that config for a totally different game, then they'll change it themselves.

There is no scenario where adding a "2" to the name (and even worse, to the identifier) is desirable. Or slugs need to stay consistent to match with games from the website, we can't mess with them

**Comment by danieljohnson2** [comment]
Create a duplicate with the same name as the original? How will you know which is which afterwards?

**Comment by strycore** [comment]
The playtime.

**Comment by strycore** [comment]
And if there is no playtime, it doesn't matter. They are the same.

**Comment by danieljohnson2** [comment]
Hmm. Okay, I'll make the change.

**Comment by danieljohnson2** [comment]
'Kay. The suffix numbers are gone now, in mater. And if the user does not change name, it will now preserve the slug as it was as well.

This provides a (slightly non-obvious) way to duplicate-with-media, by duplicating with the same name then changing it (if desired) afterwards.

**Comment by strycore** [comment]
Thanks! I also noticed a `download_lutris_media` in the duplication code which seems it could be a source of crashes on Wayland. Maybe there's some better way to handle media downloads for a game at the game class level.

**Comment by AlexFolland** [comment]
Thank you for your consideration, and also the expedition of a solution!

As the reporter of the issue, I'd like to note another expectation I would have as a user when duplicating a game in Lutris.  I would expect the images to be duplicated in full and associated with the new name, id, and slug, so that they can be modified without affecting the original game.

I'm not sure how the new implementation works, but if what I've described is how the new implementation works, then great!  If not, I suggest revisiting this at some point.

**Comment by danieljohnson2** [comment]
That download can be a fire-and-forget thing, I think.

There's this MEDIA_CACHE_INVALIDATED notification thing that will let the LutrisWindow know when the download completes, and cause a redraw. The duplication code does not care, we don't need to block here.

Please forgive that MEDIA_CACHE_INVALIDATED thing; I didn't want to turn everything into GObjects just to have signals.

**Comment by danieljohnson2** [comment]
But I wonder if maybe we should ask the user for a new slug at the same time as a name; downloading the media for some slug derived from the name seems like it would not work all that often.

**Comment by AlexFolland** [comment]
As an end user of the software, I would not expect new media to be downloaded at the time of duplication.  I would expect duplication to be a 100% local operation, personally.  Downloading media at duplication time wouldn't make sense to me, since the media is already present in the duplicated game.

**Comment by strycore** [comment]
> As the reporter of the issue, I'd like to note another expectation I would have as a user when duplicating a game in Lutris. I would expect the images to be duplicated in full and associated with the new name, id, and slug, so that they can be modified without affecting the original game.

I don't think that's possible or makes sense in our setup. The IDs need to stay consistent with the website, we can't copy the Doom covert art to Duke Nukem 3D. If the user wants Duke Nukem 3D, Lutris will download that cover art automatically. Lutris users rarely modify the artwork themselves, the website is the main source of media.

**Comment by AlexFolland** [comment]
What about when the user created their own entry in Lutris with cover art, banner, and images, which has no online media, then duplicated that?  My issue would include such a situation.

**Comment by strycore** [comment]
> My expectations are more or less in line with yours, but @strycore does not pay me enough to argue with him, so we're just doing it his way.

That's because you focus entirely on the Lutris client but you have to acknowledge the existence of the website and how it interacts with the client.

**Comment by strycore** [comment]
@AlexFolland can you please explain how you use that feature? It's really not clear what game you are trying to duplicate to what.

**Comment by AlexFolland** [comment]
> can you please explain how you use that feature? It's really not clear what game you are trying to duplicate to what.

I made a Lutris entry for Pokémon Rejuvenation and I found an issue that may be fixed with some experimentation with various runner options.  So, instead of ruining my original Lutris entry which was mostly working, I wanted to experiment in a new entry.  I found I had to manually choose the media again after the duplication, even though it was supposedly duplicated.  I would have expected at least the file paths for the media to be retained when duplicating the entry.

**Comment by AlexFolland** [comment]
I've done similar with Geoffrey The Fly, which is a Windows game which seems to always show a weird white border when running in gamescope, but not when running windowed in X11 through wine.  I was trying to fix the white border without ruining my original Lutris entry, but I had to select media again after duplication.

**Comment by danieljohnson2** [comment]
Sounds like that for your use-case, preserving the slug ("identifier") might be correct. It is exactly the same game, after all.

**Comment by strycore** [comment]
It seems both your cases are now solved with our removal or the "2" suffix. There is no need to copy anything, game media is tied to an ID, not a game in Lutris. If the games share the same ID (which in your case they do), they will share the same media. 

Our previous behavior was confusing, we shouldn't have messed with the ID to begin with.

**Comment by danieljohnson2** [comment]
To me, this favors the notion that we should offer the slug explicitly in the duplicate-game dialog. Maybe we should never change it implicitly, even if the user changes the name?

As it is, there's this invisible thing going on here.

**Comment by AlexFolland** [comment]
Not changing the ID doesn't make sense to me though.  That means a launcher that invokes `lutris lutris:rungame/gamename`, where `gamename` is the slug of a duplicated game, will be ambiguous and result in undefined behavior.  How can that work?

**Comment by strycore** [comment]
Users are not expected to know what a slug is, and Lutris rarely makes users interact with them with the exception of "Change identifier". If the name of the game is typed properly, the slug will be set accordingly and the correct media will be downloaded.

**Comment by strycore** [comment]
> Not changing the ID doesn't make sense to me though. That means a launcher that invokes lutris lutris:rungame/gamename, where gamename is the slug of a duplicated game, will be ambiguous and result in undefined behavior. How can that work?

You use rungameid instead

**Comment by AlexFolland** [comment]
That would mean that duplicating a game would affect existing launchers which already invoke the slug.  Why is it allowed to have multiple entries with the same slug?  The whole point of a slug is a unique human-readable identifier.

**Comment by danieljohnson2** [comment]
It seems to me that the slug identifies the game as a thing on Lutris.net, not an entry in your local games DB. That local game record is identified by the 'internal id', and that is unique.

**Comment by strycore** [comment]
Slugs have never been guaranteed to be unique in Lutris, only the numerical IDs are. If I have bubble-bobble on Amiga and arcade, they both share bubble-bobble.jpg in the coverart folder. But if I want to launch one individually, then we need the numerical ID (which is now visible in the game config btw)

**Comment by AlexFolland** [comment]
OK, thanks.  I guess the undefined behavior caused by invoking the slug with `lutris rungame/gamename` where `gamename` is present in multiple game configurations is a separate issue.  Now I wonder what happens in that case, but that's not directly relevant to this discussion.

Thanks for the fix!

**Comment by strycore** [comment]
Also, it's worthy to note that slugs are not only used for media but for fetching installer scripts or the "View on Lutris.net" feature. 

Maybe what we can add is a selection dialog when launching a slug that matches several games

**Comment by strycore** [comment]
For example: running `lutris lutris:rungame/bubble-bobble` would show a dialog similar to what we have with launch configs and show something like;

```
Launch Bubble Bobble

  (o) Amiga 500
  ( ) Arcade
 ```

**Comment by danieljohnson2** [comment]
What it does now is not great, I think.

Looks like it picks the 'first' match, and with no ordering it's just whatever SQLLite returns first.

But I'm not a huge fan of popping dialogs off the terminal. I'd rather have it be an error, or have it pick some reasonable default (somehow).

**Comment by AlexFolland** [comment]
Right, a dialog in the terminal would not work with a `.desktop` launcher file, as the user would never see it and then Lutris would be running in the background with that dialog forever, mysteriously not launching any game.  It would be better to at least have a GTK dialog, but I'm not sure of an ideal solution.

**Comment by strycore** [comment]
Seems to me that picking the first match found is as reasonable as it might get without a user prompt. If anything, we should sort by ID and use the lowest ones so existing shortcuts don't break when later created games share the same slug

**Comment by strycore** [comment]
OMG, I hope you didn't think by my poor ASCII drawing that I was suggesting having the dialog drawn in the terminal! :rofl: 

This would be a Gtk dialog!

**Comment by AlexFolland** [comment]
Everything can be misunderstood on the internet!

**Comment by danieljohnson2** [comment]
I knew you meant a GTK dialog.

But I was thinking.. hey maybe ASCII art is the way. What starts in the terminal stays in the terminal? :stuck_out_tongue_winking_eye:
