### ISSUE TITLE
"Missing" in the bottom left corner of the thumbnail.

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#5309]
Hey guys,

I have a little issue which is bugging me. I installed C&C Tiberian Sun yesterday and the game works flawlessly. However in the bottom left corner of the thumbnail there is word "Missing" displayed and I don't know what is this related to.

When I open lutris with `lutris -d` I get this:

```
INFO     2024-02-12 18:29:47,481 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-02-12 18:29:47,483 [startup.get_drivers:54]:Using NVIDIA drivers 535.154.05 for x86_64
INFO     2024-02-12 18:29:47,483 [startup.get_drivers:58]:GPU: NVIDIA GeForce GTX 1050 Ti
INFO     2024-02-12 18:29:47,483 [display.display_gpu_info:78]:GPU: 10DE:1C82 10DE:1C82 (nvidia drivers)
DEBUG    2024-02-12 18:29:47,865 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-02-12 18:29:48,021 [lutris.get_missing_game_ids:206]:Checking for missing games
```

There is information about missing game with id 206? Is this related somehow? I looked into pga.db and couldn't any ids with this number.

I am doing something wrong? Shall I reinstall the game?

![Screenshot from 2024-02-12 18-26-51](https://github.com/lutris/lutris/assets/26525585/ee61418d-4497-4b2d-8b57-19041d5f5bf3)

---------------------------

BTW, Lutris is next best thing after fire and wheel!!!!

**Comment by danieljohnson2** [comment]
The missing badge there means the game's directory wasn't found. The game itself could be somewhere else entirely and could still work.

Go into the 'Configuration' for this game. On the first tab, look at the 'Directory' box. What is that path? Is there a directory there?

**Comment by strycore** [comment]
>  There is information about missing game with id 206?

![922593062050476052](https://github.com/lutris/lutris/assets/280336/86808831-7139-47f0-a5da-774c0225777f)

I admit this made me laugh more than it should have :rofl: 

206 is the line number of the python file producing the log entry. Numerical IDs can safely be ignored in Lutris in 99% of cases. I am however fascinated how some will go down a rabbit hole involving things so complex I can barely grasp them while the solution is much much simpler.

**Comment by danieljohnson2** [comment]
Well, programmers will usually know the <file-name>:<line-number> convention, but I wouldn't expect gamers to know it. I can see how we might think it was a game-id (whose missing status is being checked there).

**Comment by strycore** [comment]
> I wouldn't expect gamers to know it

Gamers don't read logs and don't inspect SQLite files. I'd say it's more "in the process of becoming a programmer", that process is confusing and will often lead to incorrect suppositions, we've all had to pass through that.

**Comment by strycore** [comment]
> On the first tab, look at the 'Directory' box. What is that path? Is there a directory there?

This is not the way we determine if a game is missing or not. I have plenty of games that don't have a directory set and don't show as missing because the executable is here.

**Comment by danieljohnson2** [comment]
Oh, I see what you mean. It's checking for a bunch of things, but it's all being laundered though the path cache.

@junglized, forget the directory. Maybe your path cache has got out of date. Rename or move ``~/.cache/lutris/game-paths.json`` and restart Lutris; that file should be regenerated. Does the badge go away?

**Comment by strycore** [comment]
> Maybe your path cache has got out of date. Rename or move ~/.cache/lutris/game-paths.json

Given how 0.5.16 will brutalize your drives checking for missing games, it would be highly unlikely this cache would ever be out of date. 

@junglized please send a screenshot of the your C&C config like this: 

![image](https://github.com/lutris/lutris/assets/280336/de37657c-3e42-4f82-9ba7-d03bed81c661)

**Comment by danieljohnson2** [comment]
Checking for missing games doesn't keep the path cache up to date.

**Comment by strycore** [comment]
Oh yeah, but running the game does so that should have solved any issue.

**Comment by junglized** [comment]
Oh wow, I didn't expect to stir up such a commotion :laughing: 


> I am however fascinated how some will go down a rabbit hole involving things so complex I can barely grasp them while the solution is much much simpler.

Well, I tried to sort it out myself before taking your time, but I didn't manage after all.

> Gamers don't read logs and don't inspect SQLite files.

Well, I build websites as a hobby so reading PHP and MySQL server logs or JavaScript console logs is part of the task :+1:  Besides I used to use Lutris's pga.db to delete games from database when that option wasn't available in some of the past versions. I'm Python illiterate though....

> please send a screenshot of the your C&C config like this:

Sure, there you go:

![Screenshot from 2024-02-13 19-23-15](https://github.com/lutris/lutris/assets/26525585/8fbcbbdb-9a02-4793-8e17-627c07afb205)

**Comment by danieljohnson2** [comment]
And I take it that the Game.exe file is there?

Here's a thought. Maybe the casing is incorrect on some part of that path?

Wine (and our Wine support) fixes casing errors in paths like this, but the check for that missing badge does not.

You can maybe the get the path from the "Properties" window for the file Game.exe; we want that to be an exact match, but maybe it isn't quite.

**Comment by junglized** [comment]
> And I take it that the Game.exe file is there?
> 
> Here's a thought. Maybe the casing is incorrect on some part of that path?
> 
> Wine (and our Wine support) fixes casing errors in paths like this, but the check for that missing badge does not.
> 
> You can maybe the get the path from the "Properties" window for the file Game.exe; we want that to be an exact match, but maybe it isn't quite.

Sorted! You actually pointed me to the right direction. Game.exe was written with capital G in the game config while in the game folder it's written with lower case g. As soon as I changed it to lower case "Missing" is gone. But the game launches just fine whether it's lower or upper case... It's not bugging me anymore, you helped my OCD kind sir!

**Comment by danieljohnson2** [comment]
OK, I've some code in the fix the casing when updating the path cache; should prevent this happening in future.
