### ISSUE TITLE
Cannot run Union 1.0m.

### ISSUE THREAD

**Issue by Giger22** [lutris/lutris#5311]
I used Heroic with a wine-ge and it worked but for Lutris (same runner - wine-ge) it does not even start up.
[Union 1.0m](https://worldofplayers.ru/threads/40376/)

**Comment by strycore** [comment]
Ok, I don't know what you expect from us here. You give no details and post a link to a forum in Russian.

**Comment by Giger22** [comment]
There is an English tab. Union is an app to add mods to Gothic/Gothic2NotR game. I can run this .exe file with a Heroic app using wine-ge 8.25 but for Lutris it does not even start.

**Comment by strycore** [comment]
There is still nothing in this ticket that would let us help you solve your problem

**Comment by Giger22** [comment]
Case closed! I just had to install a dependency through winetricks.

**Comment by strycore** [comment]
Maybe that can be in a lutris script!

**Comment by Giger22** [comment]
It was dotnet40.
