### ISSUE TITLE
Error building lutris

### ISSUE THREAD

**Issue by solarisfire** [lutris/lutris#5316]
<pre>
ERROR:             ICD associated with VkPhysicalDevice does not support GetPhysicalDeviceCalibrateableTimeDomainsKHR
/usr/bin/xvfb-run: line 180: 103438 Aborted                 (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@"
==> ERROR: A failure occurred in check().
</pre>

**Comment by danieljohnson2** [comment]
I don't know what I'm looking at, but it doesn't look like a Lutris error.

**Comment by strycore** [comment]
There is very little detail in the context of this error but it looks like @solarisfire is trying to make some sort of package of Lutris and while doing so, runs the client via xvfb-run which is a headless X client. There is still some mention of xvfb in our Travis config file but I'm not even sure we use Travis anymore. 

Anyway, we make a call to the Vulkan API, Vulkan isn't happy about being executed from a headless X session, crashes, which then crashes Lutris.

Without any additional context, it's hard to know what that error is all about. Lutris does not fail to build. We release packages frequently. If you want to run the test suite, run it locally on a Wayland session.

**Comment by solarisfire** [comment]
Thanks for giving me a chance to add the additional context before closing this...

This is from the Arch Linux AUR PKGBUILD:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lutris-git

Full error is in the check phase:

<pre>
==> Starting check()...
ninja: Entering directory `/home/solarisfire/.cache/yay/lutris-git/src/build'
ninja: no work to do.
1/2 Validate desktop file         OK              0.01s
2/2 Validate metainfo file        OK              0.02s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/solarisfire/.cache/yay/lutris-git/src/build/meson-logs/testlog.txt
ERROR:             ICD associated with VkPhysicalDevice does not support GetPhysicalDeviceCalibrateableTimeDomainsKHR
/usr/bin/xvfb-run: line 180: 12402 Aborted                 (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@"
==> ERROR: A failure occurred in check().
    Aborting...
</pre>

The check phase is only running:

 meson test -C build --print-errorlogs

And a few days ago it wasn't causing an error, and now it is...

**Comment by solarisfire** [comment]
Tell a lie, it was trying to run:

<pre>
  cd "${pkgname%-git}"
  xvfb-run nosetests \
    --cover-erase \
    --with-xunit \
    --xunit-file=nosetests.xml \
    --with-coverage \
    --cover-package=lutris \
    --cover-xml-file=coverage.xml
</pre>

Even though this is commented out in the PKGBUILD...

Bug in either yay or the AUR not skipping that part of the build process. Lutris itself seems fine.

**Comment by AskAlice** [comment]
@solarisfire this from what i can tell is a bug introduced with mesa 24, try downgrading mesa.

**Comment by strycore** [comment]
You can now safely run Lutris in an environment without Vulkan by using the LUTRIS_NO_VKQUERY environment variable.

**Comment by moneroexamples** [comment]
> @solarisfire this from what i can tell is a bug introduced with mesa 24, try downgrading mesa.

Yes, downgrading worked for me:

```
sudo pacman -U file:///var/cache/pacman/pkg/mesa-23.1.4-2-x86_64.pkg.tar.zst
```
