### ISSUE TITLE
Complete umu implementation

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5319]
- [x] Package ulwgl and make it available in the runtime API with minimum client version 5017000
- [x] If ulwgl is detected, add an option in the Wine runners that simply says "Proton-GE (latest)" and does not provide any PROTONPATH to the ulwgl script
- [x] Detect if a game is using a 32bit prefix and prevent lutris from launching them with Proton. Doing so will break the prefix.
- [ ] Add a Proton-GE option in the Wine channel updates that stops wine-GE updates and defaults every game install to Proton-GE
- [x] Ship a stripped version of the ULWGL database, with only games that use a protonfix or proton workaround
- [x] Add automatic matching from service game to ULWGL-ID
- [ ] Also add manual matching to ULWGL-ID (for games not installed via the integrations)
- [x] If a game is installed using Proton-GE, ignore arch and always use win64

**Comment by strycore** [comment]
After discussion, it was agreed ULWGL wouldn't not be distributed via the Lutris runtime.

**Comment by strycore** [comment]
After more discussion, I made sure it would remain possible to distribute ULWGL via the Lutris runtime.

**Comment by SaadNaeem31** [comment]
So lets say if this is implemented, will it be able to run GTA IV without much config in lutris even on Intel hd 3000? I was using Lutris wine 7.2 last time in flatpak. The tv in-game crashes when I actually used just wine in lutris. 
With proper wow64 now in Wine 9.0, I can run GTA IV (32 bit) and GTA V (64 bit) both in same wine installation right?

**Comment by strycore** [comment]
It's not going to do miracles. Playing games on a HD3000 is kinda pushing it regardless of the underlying tech. 
We've not maintained lutris-wine for several years, our current supported version is wine-GE. 
ULWGL will give you a more consistent experience across system since it will run games in the Pressure Vessel container and rely a lot let on your system.

Proton does not support 32bit prefixes so if you are using those, you should move the games to a 64bit prefix before. 
I will be able to run both GTA 4 and GTA 5 in the same prefix. But you can do that already with Wine-GE, that's nothing new.

**Comment by SaadNaeem31** [comment]
Huge and huge thanks for your reply.
I am in the process of getting a new old laptop with Nvidia gpu. Thanks for the flatpak too.
I love it and Mx Linux.

**Comment by strycore** [comment]
Features that will be postponed to 0.5.18: 

- Add a Proton-GE option in the Wine channel updates that stops wine-GE updates and defaults every game install to Proton-GE
- Also add manual matching to ULWGL-ID (for games not installed via the integrations)
