### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#532]
Just a few things that I dreamed up:

1) The fs-uae runner:
a) With the current implementation, I've so far only been able to run Floppy discs. Trying to add a hdf into the boot slot doesn't work. So my thoughts was could one add a dedicated entry for HDD's?
b) add an entry (hidden behind a advance setting) that allow the use of fs-uae-launcher's capability to launch whdload games

2) The website:
a) possibility to add sub-genre to games, something like:
```
a1) Racing - F1, Racing - Motocross, 
a2) Sport - Soccer, Sports - Tennis, Sport - Pool, Sport - Rugby 
```

**Comment by strycore** [comment]
HDF and whdload support would be very nice indeed.

Sub-categories would be cool to have as well as we currently have way too many game genres.

Since I approve of both changes, can you please create separate issues for those so I can close this one?
