### ISSUE TITLE
Lutris can not launch a game through a .desktop file

### ISSUE THREAD

**Issue by Aqa-Ib** [lutris/lutris#5325]
Hello, first of all thank you for the amazing work you have done in the linux gaming scene.

When Lutris imports a game from the local source (a desktop file in .local/share/applications), it can not be launched.
I am using ULWGL for launching the game through the desktop file.

[Desktop Entry]
Type=Application
Categories=Game
Name=Grim Dawn
Icon=/usr/share/icons/Papirus-Dark/16x16/places/folder-games.svg
Path=/HDD/GranAlmacen/Juegos/Grim Dawn
Exec=env GAMEID="" WINEPREFIX="/HDD/GranAlmacen/Juegos/Grim Dawn/wine" ulwgl-run-cli "x64/Grim Dawn.exe"

Cheers !

**Comment by strycore** [comment]
> first of all thank you for the amazing work you have done in the linux gaming scene.

Thanks!

> When Lutris imports a game from the local source (a desktop file in .local/share/applications), it can not be launched.

Why? What happens when you try to run the game? Have you tried disabling the Lutris runtime in the game's system options? 

>  I am using ULWGL for launching the game through the desktop file.

That's not really how we plan to support ULWGL, you can setup your game in Lutris by having ULWGL in the correct location (~/.local/share/lutris/runtime/ulwgl but this is temporary, we're not going to ship ulwgl in the lutris runtime and will be distributed independently.) Once you have ULWGL, you need to select Proton-GE in the game's option and it will use ULWGL automatically.

**Comment by Aqa-Ib** [comment]
Alright, I got the bug. Lutris misses the variable `Path` from the desktop file, that is why it does not launch. If I manually set the "Working directory" in Lutris game config, it works. It would be nice if it automatically set the working directory from the desktop file's Path variable.

Yeah, I know that is not how you plan to support ULWGL, but when I copy entire games folders (including wine prefixes) from one computer to another, it is easier to just quickly change the paths from the desktop files with repgrep, drop them in ~/.local/share/applications and import them in Lutris.

Thank you very much for everything. Nice interview you had with Brodie, very interesting !
Have a nice day.

**Comment by strycore** [comment]
> Lutris misses the variable Path from the desktop file

I see, that is probably something we should support.

**Comment by strycore** [comment]
> Thank you very much for everything. Nice interview you had with Brodie, very interesting !

I enjoyed doing this interview :D

**Comment by fendrick-2nd** [comment]
That's not a bug and not a lutris desktop launcher, but incorrect wine launcher.
A proper lutris desktop launcher looks like this and is working on my machine:
```shell
[Desktop Entry]
Type=Application
Name=Grim Dawn
Icon=/home/fendrick/pictures/Icons/grimdawn_gray_256.png
Exec=env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/11
Categories=Game
```

**Comment by Aqa-Ib** [comment]
It is about adding a game through the "local source" from Lutris.

**Comment by strycore** [comment]
Just as a heads up. I'm giving up on this ticket. I don't use the Local Source service, and I don't want to create a weird looking desktop shortcut to repro the issue. Simple workaround is to put absolute paths in your .desktop file.

I hate the Gio API too much to be working on this. Anyone else is welcome to provide a patch.
