### ISSUE TITLE
Stuck on "installing game data"

### ISSUE THREAD

**Issue by dziadulewicz** [lutris/lutris#5335]
1. clicked + on the upper left corner
2. Chose "Install a Windows game from media"
3. Choose a folder to install (left it as default) clicked Install
(The GE-wine was downloaded)
4. Selected the setup file for the game to install (browsed for that .exe)
5. Clicked Continue
Stuck infinitely on "installing game data".

Ubuntu 23.10 and deb of Lutris. So what is the problem? The most simplest method of installing from .exe seems not work and supposedly the new comers try to install exactly like this.

**Comment by dziadulewicz** [comment]
Ok so i was trying to provide more info on the issue but the thread is already closed? Am i supposed to open a new thread then? Or why is a pending issue thread closed right away?

**Comment by dziadulewicz** [comment]
> @strycore is perhaps feeling a bit grumpy. But I'll take a look at your log right here anyway, if you'll post it.

Ok thanks, first of all here is the system info

[System]
OS:              Ubuntu 23.10 Mantic Minotaur
Arch:            x86_64
Kernel:          6.5.0-21-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Pentium(R) CPU 4415U @ 2.30GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             11.6 GB
Swap:            4.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 610 (KBL GT1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1
Vulkan:          Supported

But i can't seem to find the log file. Can you tell me where is it? On Heroic Games Launcher the log can be copied from within the program (maybe add the same to Lutris??)

**Comment by dziadulewicz** [comment]
(there is no log button of a game as the installation got stuck)

**Comment by strycore** [comment]
> @strycore is perhaps feeling a bit grumpy. But I'll take a look at your log right here anyway, if you'll post it.

Bug reports that are blatantly incomplete and are best suited for help requests in Discord and are not bugs in the Lutris client are ok to close. 

It's also ok to re-open a closed ticket when more information becomes available.

We used to be more strict about this with a bunch of restriction that told users not to open issues about particular games not running. Now we're more tolerant but we also need to keep the issue tracker clean.

**Comment by SylChamber** [comment]
For anyone arriving here. Have you tried enabling the debug messages by launching lutris from the terminal with the `-d` switch?

```shell
lutris -d
```

Do you see some errors like this?

```text
ERROR    2025-02-12 13:56:23,866 [startup.check_libs:62]:i386 libGL.so.1 missing (needed by opengl)
ERROR    2025-02-12 13:56:23,866 [startup.check_libs:62]:i386 libvulkan.so.1 missing (needed by vulkan)
ERROR    2025-02-12 13:56:23,867 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
it looks like wine32 is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32:i386"
```

The message says it all. In my case, I forgot to install wine32.
