### ISSUE TITLE
Unable to edit or remove games using deprecated runners

### ISSUE THREAD

**Issue by hazelnot** [lutris/lutris#5343]
ResidualVM was merged into ScummVM a few years back, but I had The Longest Journey in my Lutris library using it. I decided to go looking at the Missing tab in my library to try to see if I can fix any of the games if I happen to still have the files on my drive. Unfortunately, I'm unable to edit or remove the game from my library.

I'm not sure how this can be replicated, as it requires a game using a deprecated runner being grandfathered into a newer version of Lutris, but simply clicking or right-clicking on The Longest Journey will display an `Invalid runner name 'residualvm'` error. I can't find any other way to get rid of this broken entry at the moment.

**Comment by hazelnot** [comment]
I was able to press delete, which brought up the Remove Games dialog, but I'll keep this open, as basic functionality like this should not be relegated to keyboard shortcuts, regardless of how intuitive they are, and I assume this is something that slipped unnoticed since it's a pretty obscure edge case

**Comment by danieljohnson2** [comment]
I see it; there's guard code to disable certain commands if a game has no runner, but if it has an obsolete runner like this it thinks its a good runner and hilarity ensues.

I've beefed up the check so this should not happen anymore.
