### ISSUE TITLE
lutris for Ubuntu 20.04

### ISSUE THREAD

**Issue by hhhsu-cmlab** [lutris/lutris#5353]
What version of lutris should I download when my OS is Ubuntu 20.04.6 LTS? I tried downloading it by `sudo apt install lutris` but got the following error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lutris : Depends: gir1.2-webkit2-4.1 but it is not installable
          Recommends: python3-evdev but it is not going to be installed
          Recommends: libwine-development but it is not going to be installed
          Recommends: winetricks but it is not going to be installed
```
My OS has gir1.2-webkit2-4.0 installed, but I was unable to run `sudo apt install gir1.2-webkit2-4.1` because I got the following error:
```
E: Package 'gir1.2-webkit2-4.1' has no installation candidate
```

I tried `sudo apt isntall lutris=0.5.11` and `sudo apt install lutris=0.5.15` but kept getting the message that `E: Version '0.5.XX' for 'lutris' was not found`.

**Comment by danieljohnson2** [comment]
That is curious; I wonder what version of Lutris Ubuntu 20.04 came with. My searches suggest maybe none at all?

Are you using a PPA to install Lutris? If so, it may just be too new for your Ubuntu version. You might upgrade to 22.04, the current LTS version.

Or can you get flatpak to work? That's a way you might get Lutris working.

**Comment by strycore** [comment]
There is no need to update to 22.04 or use the Flatpak version. Ubuntu 20.04 is a distribution we still officially support.

If you're installing the latest stable version, is has a dependency of `gir1.2-webkit2-4.0 | gir1.2-webkit2-4.1`. 
gir1.2-webkit2-4.0 is the package present in Ubuntu 20.04. gir1.2-webkit2-4.1 is in later version.

Since you are hitting an error with gir1.2-webkit2-4.0, my guess is that you're trying to install an ancient, unsupported, deprecated version of Lutris.

**Comment by hhhsu-cmlab** [comment]
[danieljohnson2](https://github.com/danieljohnson2) Yes, my OS does not have lutris installed. Also, I was using PPA, so now I am trying to install lutris from another apt repository. After running `sudo add-apt-repository --remove ppa:lutris-team/lutris`, I tried `sudo apt update && sudo apt install lutris`, but now it says `E: unable to locate package lutris`.

**Comment by danieljohnson2** [comment]
OK, I've done a bit of research. The lutris-team PPA seems to be abandoned- in spite of the name, I don't think that PPA ever actually came from the Lutris team as such. It has version 0.5.12, and that version depends on WebKit 4.1. but 0.5.13 weakened this requirement to 4.0 or 4.1.

So don't use the PPA. You should be able to use the deb file. [Download it here](https://github.com/lutris/lutris/releases); you want the latest version, 0.5.16.

Double clicking this file seems obvious but on Ubuntu, as I recall, this does not work- Ubuntu will weirdly try to install Lutris from its own repo if you do that, and I do not think that will work. Use this command at the terminal:
```
sudo apt install ~/Downloads/lutris_0.5.16_all.deb
```
I believe you need a path there, if you just have the plain filename it will go to the Ubuntu repo again. Of course you will need the correct path to the download file, that's just my guess in there.

Good luck!
