### ISSUE TITLE
[Feature] sub-genre

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#536]
The website:
a) possibility to add sub-genre to games, something like:
a1) Racing - F1, Racing - Motocross, 
a2) Sport - Soccer, Sports - Tennis, Sport - Pool, Sport - Rugby

**Comment by strycore** [comment]
We have waaaay to many game genres right now. I think the correct solution would be to limit ourselves to a few genres and add support for tags which would be unlimited.

The tags wouldn't be attached to a particular genre so this would be quite different but I believe it's a solution that would scale well.

**Comment by Translator5** [comment]
Tags sounds nice - but what about allowing users to upvote or down-vote game tags?

**Comment by duhow** [comment]
#345
