### ISSUE TITLE
XVidMode option not found

### ISSUE THREAD

**Issue by mohammad5305** [lutris/lutris#5360]
I have the same problem as #2549 (my game is too dark) but I don't have nor X11 Driver registry nor the option on Runner settings is there any package i should install?

![image](https://github.com/lutris/lutris/assets/71145952/3e6fdbf5-2209-4a54-b5ec-32bf77ca6663)

![image](https://github.com/lutris/lutris/assets/71145952/d1f92275-e9d6-4c47-974c-fda8c719568b)

wine version 9.3
lutris version 0.5.16

**Comment by strycore** [comment]
XVidMode is a deprecated option, it's been removed a while ago. I doubt changing the XVidMode setting will fix your issue in this present day.
