### ISSUE TITLE
running an install script tries to download and install an already existing wine version

### ISSUE THREAD

**Issue by silverhikari** [lutris/lutris#5362]
versions tested: 0.5.16 and git [368f912](https://github.com/lutris/lutris/commit/368f9128eabe220e7fc7757b5f555b054cb11d1c)

description: trying to install a game using a local-install-script.yml, will download and try to install an already existing wine version wither it is the default selected wine runner version or the version specified in the script. this happens even if self-maintained is selected in the updates setting.

the wine version is placed in the right location as it can both be viewed in the wine runner's version selector and even conflicts with the version that is being download as the download version is trying to place the files in the same location.

this will happen every-time the script is ran, and will happen every-time even if the installed version is deleted and replaced by the downloading version.

log: https://paste.ee/p/YFB3U

**Comment by strycore** [comment]
Please send the local script you are using so I can reproduce this issue.

I was under the impression that this had been fixed recently but maybe there's an edge case specific to local scripts (unlikely)

**Comment by silverhikari** [comment]
it seems the issue happens when the wine version is specified in the wine runner configuration.

here is a modified script to show the problem compared to the original script

https://paste.ee/p/C9D0z

**Comment by strycore** [comment]
> it seems the issue happens when the wine version is specified in the wine runner configuration.

Yes, that was the issue I was mentioning that was supposedly fixed. I wonder if this is because the wine version doesn't mention the architecture? (it shouldn't matter, the arch should be added automatically)

**Comment by silverhikari** [comment]
adding the architecture at the end of the version number manually does seem to fix it

**Comment by strycore** [comment]
My guess is that the code got messed up pretty heavily and we should rewrite it to be more robust.

**Comment by danieljohnson2** [comment]
I've gotten around to look at this, and I've managed to fix up versions that do not have architectures for Wine. It'll also fix up the resulting game's configuration in the same sense.
