### ISSUE TITLE
The key 'appid' could not be found

### ISSUE THREAD

**Issue by PrimaIVoid** [lutris/lutris#5366]
Starting from this commit:
https://github.com/lutris/lutris/commit/71765daf4fe5bd2764b17fb6f77d0000b0f907e2

when running Lutris it shows this popup: `The key 'appid' could not be found.`

The Lutris list of games Added/Library/Favourite is now empty
Prior to this it contained 20+ applications

Switching back to the previous commit (22b0dac7841a7697bac2c2093e9fd3b6e3fe8615) fixed the situation:  all Games/App are back/visible again

System: Linux amd64

**Comment by danieljohnson2** [comment]
Oops; bit of an oversight. It fails if 'Installed Games Only' is checked; needs a bit of prophylactic code.

It should be fixed now.
