### ISSUE TITLE
Epic Games login window freezes when the email suggestion script executes

### ISSUE THREAD

**Issue by Jfjrbrbfjf** [lutris/lutris#5367]
Hello is my first issue i hope thats ok.

When the email suggestion appears, it is impossible to click Continue or at least it freezes.
Using a .net .com... there is no suggestion and the next step is available.

![Capture d’écran du 2024-03-19 23-04-13](https://github.com/lutris/lutris/assets/156224423/b0d1798d-7bfd-4a14-9f8f-503308d47085)

![Capture d’écran du 2024-03-19 22-52-43](https://github.com/lutris/lutris/assets/156224423/8a34fbcf-598f-4d9b-bdb2-056dd4987101)

**Comment by strycore** [comment]
Yeah that's a weird bug on EGS. The workaround is to type your email address without the "@" and when you're done, add the "@".  
But you seem to indicate that this doesn't work for "proton.me" emails and you don't need the workaround for .com emails. 

Anyway, the Javascript that's executed when EGS is giving email suggestions is freezing the Webkit2Gtk widget for some reason. I hope that can be resolved on our end but it's unsure.

**Comment by Jfjrbrbfjf** [comment]
> Yeah that's a weird bug on EGS. The workaround is to type your email address without the "@" and when you're done, add the "@". But you seem to indicate that this doesn't work for "proton.me" emails and you don't need the workaround for .com emails.
> 
> Anyway, the Javascript that's executed when EGS is giving email suggestions is freezing the Webkit2Gtk widget for some reason. I hope that can be resolved on our end but it's unsure.

Thanks to your return, the workaround not work for me. I do this test with the '.' et the '@' but that also freeze.
I go to create a alias to EGS :)

Thanks for your help
