### ISSUE TITLE
Ubisoft Connect UI basically freezes after login

### ISSUE THREAD

**Issue by samhedin** [lutris/lutris#5368]
After installing Ubisoft Connect, it launches just fine, and I can sign in just fine.
However, right after sign-in, the UI freezes or almost freezes. Sometimes, I can have some tiny interaction with it (with a lot of patience), but usually, not even that is possible. Furthermore, for a few minutes after signing in, my computer is intermittently unresponsive.
I have tried to reinstall both Lutris and Ubisoft Connect. I also found people online saying I should disable ESync and FSync before the first launch, which I tried with no success. (Though that was in reference to another issue I'm not experiencing.)
I also tried it with different Runners: `Proton - Experimental, wine-ge-8-26, Proton 9.1`

```
OS: Fedora Linux 39 (Workstation Edition) x86_64 
Kernel: 6.7.9-200.fc39.x86_64

lutris --version => lutris-0.5.16
```

Any help is greatly appreciated! The new Prince of Persia game is the first Ubisoft game I've been excited about since... the last Prince of Persia game?

**Comment by danieljohnson2** [comment]
Quick question- just *what* is freezing for you? Is it Ubisoft Connect, the Lutris UI, or your whole desktop?

**Comment by strycore** [comment]
> Proton - Experimental, wine-ge-8-26, Proton 9.1

Please do not use Proton unless you are using the current development of Lutris, stick with Wine-GE. We do not offer support for Lutris 0.5.16 + Proton on this Github. 

On a side note. I haven't experienced any issue playing the Prince of Persia demo so your issue is likely easy to fix.

**Comment by samhedin** [comment]
> Please do not use Proton unless you are using the current development of Lutris, stick with Wine-GE. We do not offer support for Lutris 0.5.16 + Proton on this Github.

That was it. I swear I used wine-GE before, but now it works when I switch to it.
Thanks!

**Comment by GenocideStomper** [comment]
Strangely I'm facing this issue right now as well with exactly the same symptoms. In both Lutris with Wine-GE-8-26 and Bottles with soda-9.0-1
