### ISSUE TITLE
Lutris Windows client

### ISSUE THREAD

**Issue by gabriellyonnet** [lutris/lutris#5369]
Hello Lutris developpers,

May you develop a Windows version of the Lutris Client for Windows x86 32 ans 64 bits and for Windows Arm on all maintained Windows versions ?

You may also make installers for the runners to keep them fonctionnal if they are not supported anymore for the OS the user uses but this OS stil maintained (ex : Windows 10 Entreprise LTSC 2021).

Best regards,
gabriellyonnet

**Comment by strycore** [comment]
No, we may not
