### ISSUE TITLE
[Feature Request] Option to add/remove Multiple games from a category

### ISSUE THREAD

**Issue by Beyuum** [lutris/lutris#5372]
Excuse my poor language, I'm using Google Translate.

The feature I request to be added is the ability to add more than one game to a category at the same time and the ability to remove them from that category. The ability to select more than one game at the same time already exists, but the option to add a category is not available.
The steps I have in mind will be
#When adding games to a category:
1- Select games from the library page.
2- Then add them to the category.
#When removed:
1- Enter the category page.
2- Select the games
3- Remove them from the category.

and Thank you for taking the time of your day to read my request.

**Comment by danieljohnson2** [comment]
Seems like a good idea to me. I'll look at this when I get a chance.

**Comment by danieljohnson2** [comment]
Well, it's written but it is not merged yet. It awaits @strycore's approval.
