### ISSUE TITLE
'ScriptInterpreter' object has no attribute 'script'

### ISSUE THREAD

**Issue by DorkYBru** [lutris/lutris#5377]
Error : "'ScriptInterpreter' object has no attribute 'script'"
OS : Debian 12 Bookworm
Game : All
When: In the first part of the installation.
Tried: Changing to diffrent versions of python (3.11, 3.8, 3.9, 3.10)
![2024-03-24_13-33](https://github.com/lutris/lutris/assets/76796721/2ef75e3a-93a4-4e09-bbdb-636090361e52)

**Comment by danieljohnson2** [comment]
This looks quite like #5300, though it is hard to tell with so little information. That bug's been fixed in master.

Try downloading the master branch and running the ``bin/lutris`` script inside; no need to install. Can you install your game that way?

If not, you need to give us more. Run ``lutris -d`` at the terminal, try to install, and give us the terminal spam you get.

**Comment by DorkYBru** [comment]
lutris downloaded from github returns: 
➜  bin ./lutris -d
Traceback (most recent call last):
  File "/home/dj/Pobrane/lutris-0.5.16/bin/./lutris", line 58, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dj/Pobrane/lutris-0.5.16/lutris/gui/application.py", line 19, in <module>
    import json
ModuleNotFoundError: No module named 'json'

Lutris -d : 
➜  bin lutris -d
INFO     2024-03-24 15:14:09,856 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-03-24 15:14:09,858 [startup.get_drivers:67]:Running Intel Mesa driver 22.3.6 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
INFO     2024-03-24 15:14:09,858 [display.display_gpu_info:78]:GPU: 8086:5917 103C:83B2 (i915 drivers)
DEBUG    2024-03-24 15:14:10,098 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-03-24 15:14:10,230 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-03-24 15:14:23,408 [api.get_game_installers:311]:Fetching installer https://lutris.net/api/installers/the-legend-of-zelda-majoras-mask
DEBUG    2024-03-24 15:14:23,408 [http._request:88]:GET https://lutris.net/api/installers/the-legend-of-zelda-majoras-mask
DEBUG    2024-03-24 15:14:23,609 [application.show_window:392]:Showing window InstallerWindowthe-legend-of-zelda-majoras-mask
DEBUG    2024-03-24 15:14:27,839 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2024-03-24 15:14:28,970 [interpreter.get_runners_to_install:257]:Runner <lutris.runners.libretro.libretro object at 0x70822d164c50> needs to be installed
DEBUG    2024-03-24 15:14:28,970 [interpreter.install_runner:276]:Installing libretro
ERROR    2024-03-24 15:14:28,970 [exception_backstops.error_wrapper:81]:Error handling idle function: 'ScriptInterpreter' object has no attribute 'script'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 444, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 211, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 265, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 280, in install_runner
    version=runner.get_installer_runner_version(self) if runner.has_runner_versions else None,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/runners/libretro.py", line 156, in get_installer_runner_version
    version = installer.script["game"].get("core")
              ^^^^^^^^^^^^^^^^
AttributeError: 'ScriptInterpreter' object has no attribute 'script'

**Comment by danieljohnson2** [comment]
OK, the './lutris -d' is the real deal, and it is strange that you are getting that json error. That code is the same in 0.5.16, but it works there somehow. But thanks to that you aren't getting near the original bug.

The name of the directory suggests you downloaded the 0.5.16 release. The git master is not that; it's the thing you can download with the green "Code" button [here](https://github.com/lutris/lutris). Please try that one.

But the second one ('lutris -d') is running your existing lutris install, and that trace-back tells me that it is indeed #5300- interpreter:py: 280 is the bugged line, and that is the bugged code visible there. That is fixed in master.

**Comment by DorkYBru** [comment]
Sorry, I've read your message wrong ;< i thought you wrote about downloading a release my fault.

downloaded master:
➜  bin git:(master) ./lutris -d     
Traceback (most recent call last):
  File "./lutris", line 58, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/dj/lutris/lutris/gui/application.py", line 19, in <module>
    import json
ModuleNotFoundError: No module named 'json'

still json error
my other scripts using json are working tho.

**Comment by strycore** [comment]
json being part of the standard Python library, in order to get a ModuleNotFound error on json, things have to be severely messed up.

I urge you to revert ANY action you took while trouble shooting your issues and put your OS in a stable state before doing ANYTHING lutris related.

**Comment by strycore** [comment]
> Changing to diffrent versions of python (3.11, 3.8, 3.9, 3.10) 

You should NEVER do this, now I'm not sure your OS can be recovered. 

Good luck.....

**Comment by danieljohnson2** [comment]
Hmm. It's curious that your normal Lutris has not also been broken.

Be that as it may, I'm pretty sure this is #5300, fixed in master, so I'm closing this as completed.

**Comment by acook** [comment]
Running it with `python3 bin/lutris` I'm also seeing the JSON issue with the git version.

**Comment by strycore** [comment]
Please note there is nothing wrong with Lutris itself. We use it on a daily basis and is being used by thousands of people. 

I beg you all to stop messing around with your python installs, just leave your distro defaults and experiment with python on a VM until you are comfortable to troubleshoot basic python issues.

Some tips: 

- `which python3` : will tell you where your python interpreter is. It's not in /usr/bin? Bad news!!!!!!
- `import lutris; lutris.__file__` in a python interpreter. Will tell you where the python modules for lutris are installed.
- `import sys; sys.path` in a python interpreter. Will show you where python modules are loaded from. 
- `pyenv version`. if you use pyenv, will display which version is in use (it should be system)

Please note: Not being able to import json, which is inside python's stdlib is beyond my level of understanding. Never in my life have I put myself in a situation where python wasn't able to import json or any other module included in the stdlib. I do not know how you put something in this situation, all I know is that things have to be pretty messed up for lutris not to be able to find json.
