### ISSUE TITLE
Can you cut a new minor version?

### ISSUE THREAD

**Issue by jfo84** [lutris/lutris#5378]
I'm not sure how the project does versioning, but I would like to use [this commit](https://github.com/lutris/lutris/commit/92a32aac7dcfa5efdef9f9021a19e42b0c335087) without building from source on my steam deck. Thanks

**Comment by strycore** [comment]
The next release is almost ready but in the meantime you can install from Flathub Beta, it's been updated with a récent commit

**Comment by jfo84** [comment]
@strycore thanks
