### ISSUE TITLE
not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by WhyNotHugo** [lutris/lutris#5380]
Trying to install this recipe: https://lutris.net/games/install/23983/view

The last step that runs fine is `Setting Windows 10 mode for Wine`, after that, I get the mentioned issue:

![image](https://github.com/lutris/lutris/assets/730811/7dd42473-0265-4605-baa6-4452db966a47)

I'm using version 0.5.16 installed from flatpak

## Repro steps

1. `flatpak install net.lutris.Lutris`
2. `flatpak run net.lutris.Lutris`
3. Click on `+`.
4. Search for Eve Online
5. Pick `Install the new launcher (released Dec. 2023)`.
6. Click next a few times through the wizard.

**Comment by danieljohnson2** [comment]
That's the Eve Online (Dec 2023 Launcher) installer right? I just tried it and it was fine. I think we need more here.

Please give us a debug log. Run ``flatpak run net.lutris.Lutris -d`` at the terminal and post the terminal spam here after the install has failed. That should give us a clue, I think.

**Comment by danieljohnson2** [comment]
I believe you are 100% right. I'll fix that by returning tuples of empty strings, and adding type notations that will at least catch this error here to make sure I got 'em all.

There's no easy way for you to test this using flatpak until a new beta comes out, but I'm fairly confident this will fix that bug.

I'm not too sure your game will work if ``/home/hugo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine`` is missing. Not sure what has happened there, but you may need to install or reinstall that version of Wine.

It looks like Lutris should have installed that for you, but didn't for some reason. Curious.

**Comment by danieljohnson2** [comment]
OK, I've looked into this more and I believe you are also experiencing issue #5302, and it is fixed in the master, so that's why I was not reproing it. The next release should correct this and allow your game installer to work.

In the meantime, #5302 suggests that installing the offending Wine version yourself, first, may work around this issue and allow you to install the game. So give that a try.

**Comment by WhyNotHugo** [comment]
Never mind, the script mentions this below.
