### ISSUE TITLE
lutris refuses to launch dolphin runner (cannot find libavformat.so.60)

### ISSUE THREAD

**Issue by ChuckBartowski91** [lutris/lutris#5382]
Lutris version: 0.5.12
Linux version: MX Linux 23.2 x64 xfce

Hello, looks like dolphin ignores files into lib directory, the file is present in there but the output from lutris -d says:

`dolphin-emu: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory
 Monitored process exited.
 Initial process has exited (return code: 32512)
 All processes have quit
 Exit with return code 32512
 DEBUG    2024-03-25 15:17:47,825 [command.on_stop:195]:Process 12434 has terminated with code 32512`

Maybe this is fixed in the 0.5.13 release? As stable gives to me the version i wrote.

**Comment by strycore** [comment]
We no longer support lutris 0.5.12 or 0.5.13. Those are obsolete and abandoned. 


The issue you are running into is separate. It is tied to the Dolphin runner and the lutris runtime. I don't have the necessary info to debug your issue so you can install your distro's dolphin-emu package.

**Comment by strycore** [comment]
MX Linux is based on Debian so it's unlikely they would update an individual package between releases. 

You can grab a deb of the latest version on your releases page on Github.

**Comment by username-generic** [comment]
I am running into the same issue on Fedora 42. Curiously enough, running Dolphin separately (after installing it via dnf) works fine.

Here are the versions:
```bash
# (installed via dnf)
lutris --version # lutris-0.5.19
# (installed via dnf)
dolphin-emu --version # Dolphin 2503.1
```
