### ISSUE TITLE
Can't open native Lutris simultaneously with Flatpak Lutris

### ISSUE THREAD

**Issue by Victor239** [lutris/lutris#5384]
I use both versions at the moment for different games including Flatpak vs native versions. For some reason having either open interferes and prevents the other version from being opened.

Lutris version: 0.5.14

**Comment by strycore** [comment]
Yes, this is to be expected, just like you can't run the globally installed lutris and the development version at the same time or any 2 different versions of Lutris at the same time. The Lutris application registers the net.lutris.Lutris session in dbus. Anything that tries to launch a version of Lutris will see there is a running instance and will not continue executing.

Also your version of Lutris is old. please update.

**Comment by Victor239** [comment]
It would be ideal if you could run both at once, for debugging and utility purposes. 

Thanks, will do.
