### ISSUE TITLE
[Request] Support Cemu WUA files

### ISSUE THREAD

**Issue by jefferyrlc** [lutris/lutris#5385]
One of the things you can do with Cemu is compress a game and it's updates and dlc into a single WUA file. However, Lutris only supports adding a folder as a rom image for Cemu.

**Comment by strycore** [comment]
You'd think there would be a  way to tell a file picker to accept either folders or files but no, apparently that's not possible. So there's 2 widgets now, one for folder and one for files. 

Also updated the Cemu runner to the most recent build
