### ISSUE TITLE
Lutris is not responding on battle.net install :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [lutris/lutris#5386]
![Screenshot from 2024-03-27 21-29-27](https://github.com/lutris/lutris/assets/3514015/7f604e35-6a79-4512-bf3c-9b3eb5cafe4f)

I tried Lutris from apt and from Github v0.5.16

Ubuntu 22.04.4

**Comment by danieljohnson2** [comment]
Might be a clue in the log.

Run ``lutris -d`` in your terminal and then give us the terminal spam.

**Comment by vitaly-zdanevich** [comment]
Now its running.
