### ISSUE TITLE
gog games with both linux and windows release don't show wine option.

### ISSUE THREAD

**Issue by cronyakatsuki** [lutris/lutris#5391]
Every gog game that has both linux and window releases don't have an option to install the windows version with wine, only the linux version with gog.

Example being dead cells, which doesn't want detect my controller on the linux version.

I would like if lutris had the ability to install both linux and windows version's of the games.

**Comment by danieljohnson2** [comment]
I've gone over this, and I believe this is not a policy thing- it's just a bit of a pain to offer multiple auto-generated installers.

So, I'll enable that scenario. Lutris can only offer Linux and Wine versions of games from GOG, so you get get two auto-generated options at most.

We have odd support for DOSBOX, but that's done by taking the GOG installer (either one!) and unwrapping it; I'd like to expose it as a third choice, but there seems to be no way to know if a game will be a DOSBOX game before downloading everything, which would be intolerably slow to wait for.

So you might get a meaningless choice for such a game- technically you are picking which download is taken, but I think the final results will be equivalent DOSBOX installed.

**Comment by mittler-works** [comment]
That's great! I often have problems starting the Linux versions of gog games on the Steam Deck. The Windows versions with Wine, on the other hand, run very reliably. So far I have always downloaded the .exe from gog and installed it manually. I'm looking forward to when the release is available on the Steam Deck! Thanks a lot!
