### ISSUE TITLE
Multi GPU not showing iGPU, only dGPU

### ISSUE THREAD

**Issue by lavrovvv** [lutris/lutris#5395]
My laptop has an iGPU Radeon 680M and dGPU Radeon RX6700s. Supergfxctl running in hybrid mode, so both GPUs should be visible and available for any application to use. But iGPU isn't visible in Lutris (I have some light games that just don't need to use powerful graphics). Please see the attached screenshot
![image](https://github.com/lutris/lutris/assets/85690791/a43f80a2-b6ae-4881-a141-e82a40169cc8)

```
MESA_VK_DEVICE_SELECT=list vulkaninfo | less 
selectable devices:
  GPU 0: 1002:73ef "AMD Radeon RX 6700S (RADV NAVI23)" discrete GPU 0000:03:00.0
  GPU 1: 1002:1681 "AMD Radeon Graphics (RADV REMBRANDT)" integrated GPU 0000:07:00.0
```

**Comment by danieljohnson2** [comment]
This code has been changed quite extensively for the next release. I think you should try the latest.

Download the latest Lutris from [here](https://github.com/lutris/lutris); no need to install it. Run the ``bin/lutris`` script within and see if that will work for you.

**Comment by lavrovvv** [comment]
@danieljohnson2 Thanks for your reply, I'm running the v0.5.16 version from AUR.
However, I just installed `lutris-git-0.5.16.r476.g2abe2323f-1-any` from chaotic-aur (which is, should be, the latest compiled package from git) and the GPU menu changed a bit.
![image](https://github.com/lutris/lutris/assets/85690791/185c441c-d2a6-4b05-a325-e7f3bba23a50)
But it shows 2 same device names. In the logs I can see the following:
```
2024-04-01 00:06:37,139: Starting Lutris 0.5.17
2024-04-01 00:06:40,982: AMD Radeon RX 6700S (1002:73EF 1043:1DEC amdgpu) Driver 24.0.3
2024-04-01 00:06:41,335: AMD Radeon RX 6700S (1002:1681 1043:1DEC amdgpu) Driver 24.0.3
```
This is kinda weird, the second device (1002:73EF) according to vulkaninfo should be my iGPU, but no matter which name I selected - it will always use dGPU.
For info, I'm trying to force Hearthstone to work only on iGPU, there's no GPU picker inside the game, so I don't think that's the game issue.
Also attaching output from Lutris settings, maybe it will be useful.
```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.6.23-1-lts
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 6900HS with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 38.4 GB
Swap: 32.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, rembrandt, LLVM 17.0.6, DRM 3.54, 6.6.23-1-lts)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.3-arch1.2
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.3-arch1.2
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon Graphics (RADV REMBRANDT) (1.3.274), AMD Radeon RX 6700S (RADV NAVI23) (1.3.274)
```

**Comment by strycore** [comment]
I'm not really surprised that using 2 AMD GPUs causes some problems. Good thing is that I should be able to reproduce this easily by re-enabling the iGPU in my BIOS.

**Comment by strycore** [comment]
I fixed the issue in this commit: https://github.com/lutris/lutris/commit/f7f5da433f848386f1bab1f0eaf9a2fd3b8639f5

However, I still have the issue of Avatar: Frontiers of Pandora trying to run on the iGPU regardless of the selection in Lutris. Even worse, I can see my 7800 XT being used in Ubisoft Connect with Mangohud and then it switches to AMD Radeon Graphics when the game starts. So it's back to a single GPU setup for me.
