### ISSUE TITLE
Unable to install mgba runner

### ISSUE THREAD

**Issue by amethylghostling** [lutris/lutris#5396]
It say "Runner failed to install" after it fails to install
Output of `lutris -d`:

```
2024-03-31 19:01:25,666: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-03-31 19:01:26,451 [application.do_command_line:479]:Starting Lutris 0.5.16
INFO     2024-03-31 19:01:26,454 [startup.get_drivers:67]:Running Intel Mesa driver 24.0.3 on Mesa Intel(R) HD Graphics 4400 (HSW GT2) (0xa16)
INFO     2024-03-31 19:01:26,454 [display.display_gpu_info:78]:GPU: 8086:0A16 17AA:220C (i915 drivers)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
WARNING  2024-03-31 19:01:26,493 [startup.check_vulkan:108]:Vulkan reports that the 'Intel(R) HD Graphics 4400 (HSW GT2)' device has API version of 1.2.274. 1.3.0 is required for the latest DXVK.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
DEBUG    2024-03-31 19:01:27,116 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-03-31 19:01:27,461 [lutris.get_missing_game_ids:206]:Checking for missing games
DEBUG    2024-03-31 19:01:32,110 [application.show_window:392]:Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7deffae03d00 (LutrisWindow at 0x6056566122d0)>}
DEBUG    2024-03-31 19:01:42,975 [system.remove_folder:370]:Trashing folder /home/danish/.local/share/lutris/runners/mgba
DEBUG    2024-03-31 19:01:44,214 [runner_box.on_install_clicked:94]:Install of <lutris.runners.json.mgba object at 0x7deff9595fd0> requested
DEBUG    2024-03-31 19:01:44,214 [runner.install:469]:Installing mgba (version=None, callback=None)
DEBUG    2024-03-31 19:01:44,233 [downloader.start:67]:⬇ https://github.com/mgba-emu/mgba/releases/download/0.10.2/mGBA-0.10.2-appimage-x64.appimage
DEBUG    2024-03-31 19:01:56,721 [downloader.on_download_completed:173]:Finished downloading https://github.com/mgba-emu/mgba/releases/download/0.10.2/mGBA-0.10.2-appimage-x64.appimage
DEBUG    2024-03-31 19:01:56,778 [extract.extract_archive:129]:Extracting /home/danish/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage to /home/danish/.local/share/lutris/runners/mgba

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 24372416 bytes (24 MiB)      

Extracting archive: /home/danish/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage
--       
Path = /home/danish/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage
Type = SquashFS
Offset = 193728
Physical Size = 24178688
Headers Size = 10285
File System = SquashFS 4.0
Method = ZLIB
Cluster Size = 131072
Big-endian = -
Characteristics = DUPLICATES_REMOVED EXPORTABLE
Code Page = UTF-8

Everything is Ok                 

Folders: 112
Files: 189
Size:       61825333
Compressed: 24372416
DEBUG    2024-03-31 19:01:57,451 [system.delete_folder:387]:Deleting folder /home/danish/.local/share/lutris/runners/mgba/.extract-15ba4e39
DEBUG    2024-03-31 19:01:57,451 [extract.extract_archive:181]:Finished extracting /home/danish/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage to /home/danish/.local/share/lutris/runners/mgba
ERROR    2024-03-31 19:01:57,455 [exception_backstops.error_wrapper:81]:Error handling signal 'clicked': Runner failed to install
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/config/runner_box.py", line 100, in on_install_clicked
    raise RuntimeError("Runner failed to install")
RuntimeError: Runner failed to install
```

System Information:

```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.8.2-arch2-1
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
Physical cores: 2
Logical cores: 4

[Memory]
RAM: 7.6 GB
Swap: 8.8 GB

[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.3-arch1.2
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.3-arch1.2
Vulkan Version: 1.3.279
Vulkan Drivers: Intel(R) HD Graphics 4400 (HSW GT2) (1.2.274)
```

**Comment by danieljohnson2** [comment]
I see it; this AppImage has the file extension '.appimage', not the expected '.AppImage'. But '.appimage' is much more normal, really; I'll just add a bit of case-insensitivity here.

**Comment by synthosomatic** [comment]
This is actually still happening.

`DEBUG    2025-05-11 22:27:25,756 [runner_box.on_install_clicked:96]:Install of <lutris.runners.json.mgba object at 0x708cb1c1ce60> requested
DEBUG    2025-05-11 22:27:25,757 [runner.install:423]:Installing mgba (version=None, callback=None)
DEBUG    2025-05-11 22:27:25,773 [downloader.start:67]:⬇ https://github.com/mgba-emu/mgba/releases/download/0.10.2/mGBA-0.10.2-appimage-x64.appimage
DEBUG    2025-05-11 22:27:28,594 [downloader.on_download_completed:173]:Finished downloading https://github.com/mgba-emu/mgba/releases/download/0.10.2/mGBA-0.10.2-appimage-x64.appimage
DEBUG    2025-05-11 22:27:28,790 [extract.extract_archive:127]:Extracting /home/elwood/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage to /home/elwood/.local/share/lutris/runners/mgba

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,20 CPUs x64)

Scanning the drive for archives:
1 file, 24372416 bytes (24 MiB)      

Extracting archive: /home/elwood/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage
--       
Path = /home/elwood/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage
Type = SquashFS
Offset = 193728
Physical Size = 24178688
Headers Size = 10285
File System = SquashFS 4.0
Method = ZLIB
Cluster Size = 131072
Big-endian = -
Characteristics = DUPLICATES_REMOVED EXPORTABLE

Everything is Ok         

Folders: 112
Files: 189
Size:       61825333
Compressed: 24372416
DEBUG    2025-05-11 22:27:29,103 [system.remove_folder:323]:Removing folder /home/elwood/.local/share/lutris/runners/mgba/.extract-8b460046
DEBUG    2025-05-11 22:27:29,103 [extract.extract_archive:179]:Finished extracting /home/elwood/.cache/lutris/mGBA-0.10.2-appimage-x64.appimage to /home/elwood/.local/share/lutris/runners/mgba`

`[System]
OS:              Linux Mint 22.1 Xia
Arch:            x86_64
Kernel:          6.8.0-59-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           12th Gen Intel(R) Core(TM) i7-12700
Physical cores:  12
Logical cores:   20

[Memory]
RAM:             62.6 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 570.133.07
OpenGL Core:     4.6.0 NVIDIA 570.133.07
OpenGL ES:       OpenGL ES 3.2 NVIDIA 570.133.07
Vulkan Version:  1.3.275
Vulkan Drivers:  NVIDIA GeForce RTX 4070 Ti (1.4.303), Intel(R) UHD Graphics 770 (ADL-S GT1) (1.3.289)`
