### ISSUE TITLE
I'm trying to download Silent Hill 4 (gog version) using lutris. But this error keeps coming.

### ISSUE THREAD

**Issue by Flyingbread26** [lutris/lutris#5397]
failed to extract /home/deck/.var/app/net.lutris.Lutris/cache/lutris/wine-lutris-GE-proton8-26-x86_64.tar.xz: [Errno 17] File exists: ‘libgstallocators-1.0.so.0.2205.0’ -> ‘home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wi

How do I fix this. I'm a newbie so I really need some help. I would really appreciate some.

**Comment by danieljohnson2** [comment]
Sounds a little like #5302 or #5388.

Can you install that version of Wine ("lutris-GE-proton8-26-x86_64") via the Wine versions dialog? It is one of the icons next to "Wine" in the sidebar. If you can, that might resolve the problem.

**Comment by Flyingbread26** [comment]
> Sounds a little like #5302 or #5388.
> 
> 
> 
> Can you install that version of Wine ("lutris-GE-proton8-26-x86_64") via the Wine versions dialog? It is one of the icons next to "Wine" in the sidebar. If you can, that might resolve the problem.

**Comment by Flyingbread26** [comment]
> Sounds a little like #5302 or #5388.
> 
> 
> 
> Can you install that version of Wine ("lutris-GE-proton8-26-x86_64") via the Wine versions dialog? It is one of the icons next to "Wine" in the sidebar. If you can, that might resolve the problem.

YOU ARE A LIFE SAVERRRR!!!!!!! I'm finally able to play the game!!!!

**Comment by strycore** [comment]
we really need to push 0.5.17
