### ISSUE TITLE
[Feature Request] Automatically download missing media after adding a locally installed game

### ISSUE THREAD

**Issue by amethylghostling** [lutris/lutris#5398]
So one doesn't have to manually click on "Dowload missing media" in Preferences > Updates and do it everytime one adds a locally installed game.

Or at least, add an option to do it automatically everytime.

**Comment by danieljohnson2** [comment]
It is supposed to do that already. What version of Lutris are you using, and how are you adding the game? The issue may be with a specific command somewhere.

Also, Lutris 0.5.16 has a button to download missing media in the preferences. So maybe you need to upgrade to that?

**Comment by strycore** [comment]
>  Or at least, add an option for it.

I beg you with all I have to stop asking for more options!!! What can I do for y'all to stop asking for more options.

Why would you want image download to optionally be broken??

**Comment by amethylghostling** [comment]
> It is supposed to do that already. What version of Lutris are you using, and how are you adding the game? The issue may be with a specific command somewhere.
> 
I'm sorry if I hadn't been clear on what I meant, but I wanted lutris to at least have a setting to automatically download missing media when a new locally configured game is added. 
> Also, Lutris 0.5.16 has a button to download missing media in the preferences. So maybe you need to upgrade to that?

I am using lutris 0.5.16.

**Comment by amethylghostling** [comment]
> It is supposed to do that already. What version of Lutris are you using, and how are you adding the game? The issue may be with a specific command somewhere.

I am using lutris 0.5.16.

**Comment by strycore** [comment]
I pushed a fix, images are now downloaded on manually added games
