### ISSUE TITLE
Unable to install EAAPP with built in wine, or ProtonUP-QT. but worked with nobara staged system 9.5 version. (maybe cpu instruction related?)

### ISSUE THREAD

**Issue by 1sad** [lutris/lutris#5402]
basically, spend two days trying to figure why lutris couldnt install eaapp properly, tried flatpak and system versions and .deb install too, tried 3 different distros, downloading different wine versions with protonup but it didnt work.

what worked is on nobara, switching to the custom system build of it, thats staged 9.5 from nobara repository.
after that it installed and worked just fine.

laptop hp probook 430 g2. i5 5200u, 8gb, hd 5500 igpu.

also related i guess is that using flatpak lutris on mint 21.3, it failed to delete folders it created in /home/games/ when i tried to remove the broken half istalled eaapp from within lutris. had to delete it manually from the fm.

**Comment by strycore** [comment]
I suppose that when you say staged system 9.5 you are referring to Wine Staging 9.5. 

Let's keep EA App launch issues grouped in #5390 

@GloriousEggroll hasn't noticed any issues on EA App on his side but that's clearly not the case for everyone. EA App is in a completely broken state right now.
