### ISSUE TITLE
How do you use dgvoodoo2 now?

### ISSUE THREAD

**Issue by glu8716** [lutris/lutris#5411]
I haven't used Lutris for about a year now. It used to ship with dgvoodoo2 in the past and the configuration file for it was located in `/.local/share/lutris/runtime/dgvoodoo2/*version*` folder. I can't find it now and the only version I can choose from Lutris is `Manual`. What is that? And how can I change the configuration file?

**Comment by strycore** [comment]
This is very likely because you are running an outdated version of Lutris and the Lutris API doesn't offer downloads of dgvoodoo, dxvk, winetricks, etc.... to versions of Lutris that are too old. To solve your issue, install the current version of Lutris.
