### ISSUE TITLE
UMU : Can't use Proton GE installed through AUR

### ISSUE THREAD

**Issue by Yuri-K7** [lutris/lutris#5419]
I use the proton-ge-custom-bin package from AUR, and I can't use it if I don't make my own symbolic link :

```
ln -s /usr/share/steam/compatibilitytools.d/proton-ge-custom "/home/yuri/.steam/root/steamapps/common/Proton GE"
```

The "GE-Proton (Latest)" from the wine runner selection installs UMU-Proton which doesn't have the gstreamer fixes I want.

**Comment by strycore** [comment]
this is a limitation of the umu launcher, you have to report it to this repo: https://github.com/Open-Wine-Components/umu-launcher
