### ISSUE TITLE
Lutris runtime updates not running on startup and downloading very slowly

### ISSUE THREAD

**Issue by kaiboisdumb** [lutris/lutris#5426]
It seems like even though Lutris is configured to download its components when it starts up, it actually doesn't do so. It's not until I go to Lutris' settings and click "Check for updates" that it'll start to download. But even then, it'll all download extremely slowly, taking over 10 minutes to download just umu-games alone. In general, Lutris' startup for me was very noticeably slow, but I found that disabling IPv6 fixes this for some reason.

**Comment by danieljohnson2** [comment]
This seems like a networking issue on your machine, to me. But if you like, post the debug log and we'll see if there's anything there. To do this, run this on the terminal:

```bash
lutris -d
```

Then give us the terminal spam.
