### ISSUE TITLE
Ubisoft no thumbnails

### ISSUE THREAD

**Issue by SonGoku90** [lutris/lutris#5428]
I have lutris 5.17 on fedora 40 kde and it doesn't display thumbnails of Ubisoft games, how to fix it?
![xzcxzcxzcxz](https://github.com/lutris/lutris/assets/57522176/757c2dfe-f19e-46ff-8d91-ba2d5e2866e2)

**Comment by danieljohnson2** [comment]
The reload button that is visible in your screenie next to "Ubisoft Connect" (the middle one) should reload the artwork.

But this should be automatic. So please provide us with a debug log; to do this, go to your terminal, and run:
```
lutris -d
```

Then click that button and when it is done, provide the terminal spam to us.

**Comment by SonGoku90** [comment]
lutrs -d
`2024-04-15 10:53:57,830: Command 'fluidsynth' not found on your system
2024-04-15 10:53:57,900: Unable to run command, qdbus not found
INFO     2024-04-15 10:53:58,099 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-04-15 10:53:58,168 [startup.run_all_checks:120]:AMD Radeon RX 6650 XT (1002:73ef 1462:5026 amdgpu) Driver 24.0.4
DEBUG    2024-04-15 10:53:58,315 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-15 10:53:58,317 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-04-15 10:53:58,364 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-15 10:53:58,391 [api.check_stale_runtime_versions:52]:Modified at pon, 15 kwi 2024, 07:31:47, will update after pon, 15 kwi 2024, 13:31:47
DEBUG    2024-04-15 10:53:58,404 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-04-15 10:54:28,672 [base.wipe_game_cache:441]:Deleting ubisoft cache /home/m/.cache/lutris/ubisoft/library/
DEBUG    2024-04-15 10:54:28,672 [base.wipe_game_cache:175]:Deleting games from service-games for ubisoft
DEBUG    2024-04-15 10:54:28,693 [client._do_request_safe:75]:rememberMeTicket expiration time: 1713172191
INFO     2024-04-15 10:54:28,693 [client._do_request:56]:No headers in kwargs, using session headers
INFO     2024-04-15 10:54:29,375 [client._do_request:64]:Response status: <Response [200]>
DEBUG    2024-04-15 10:54:29,375 [client._do_request_safe:75]:rememberMeTicket expiration time: 1713172191
INFO     2024-04-15 10:54:29,375 [client._do_request:56]:No headers in kwargs, using session headers
INFO     2024-04-15 10:54:29,587 [client._do_request:64]:Response status: <Response [200]>
WARNING  2024-04-15 10:54:30,316 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/7d03c2f843b9c9a5cd7ce8951142b953.jpg
WARNING  2024-04-15 10:54:30,317 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/f817ea9301f8977aed98ade9dfc10b1e.jpg
WARNING  2024-04-15 10:54:30,317 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/79b8e5e2468fb3f434b622ee5c5063fb.jpg
WARNING  2024-04-15 10:54:30,317 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/239ea35ca6be64d0e10120b818f567d4.jpg
WARNING  2024-04-15 10:54:30,317 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/512eddc847657d1c2a9f185c9f138c6c.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/da1733d50f6fbcf5b344d23ebb1ed52c.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/bf7a7873bcb13e2883a2424ac734e0a8.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/1be065304226cdb56a5818dd9808c3e0.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/c698e01ad67770b33af230f93d8f5753.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/b72d55757d36943ae5f1a0ac01d8e295.jpg
WARNING  2024-04-15 10:54:30,318 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/3b7a697bedd6e12e81519f3bc1dcf5a4.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/1d17fd3061fa25bc6ac1c3dd94b157f4.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/ed9da50536f11b289121329af97881e1.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/52fbec0acc65df17878df15abeff2f19.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/73f5d624f36d0fc38ada32c9e0a20635.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/99e4ac5a6e8d63dbdc7e85341b70e2ce.jpg
WARNING  2024-04-15 10:54:30,319 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/168616bac535772d7c19750aec4fa11a.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/228c89d9826b06618c26280dbbae867e.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/dd084176b189bbb4f288a439661e1b89.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/b33ab65fc6ca2c6bd7574b9449f3e6cc.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/48dbbcc5a2db979351657ef2ec3e0810.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/ad28c12bdc574692d9c954564715c3b9.jpg
WARNING  2024-04-15 10:54:30,320 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/5afce18505053ddcecd8f0cbfc8041e8.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/20245d0356a609a8f2968aec287443a3.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/514a93a313459529a69a1019e2b31ed0.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/a53093e3f3496f0e608d678084a12d30.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/29af1426c8ea0ed58abcc96195c45ef7.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/a3a68e6a3d2015f354bdc8c9f5115b9f.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/600083a4cc8fcf6b9db7c2a01de446f1.jpg
WARNING  2024-04-15 10:54:30,321 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/0f946fb03f8bdf913969d1c22df1625e.jpg
WARNING  2024-04-15 10:54:30,322 [ubisoft.download:60]:No thumbnail in /home/m/Games/ubisoft-connect/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/cache/assets/13e2cf96b3b7e73a8219018ffe35f628.jpg
DEBUG    2024-04-15 10:54:33,885 [ubisoft.install_from_ubisoft:183]:Ubisoft Connect game Trackmania is already installed
DEBUG    2024-04-15 10:54:34,019 [ubisoft.install_from_ubisoft:183]:Ubisoft Connect game Trackmania Turbo is already installed

`

**Comment by danieljohnson2** [comment]
OK, looking at this what seems to be happening is that it's trying to get the cover art out of your Ubisoft Connect installation, and it's *not* downloading them.

So, start Ubisoft Conect and see if it has your covers. Are they present? If so, try reloading again and see if can get them now.

**Comment by strycore** [comment]
![image](https://github.com/lutris/lutris/assets/280336/6741a17f-d21c-4a6c-b54c-79c54c43922f)

At most, you should be getting a few missing images. I still have to figure out why we're not getting some images from Ubisoft like Anno 1800

**Comment by SonGoku90** [comment]
Ubisoft Connect has covers, but Lutris doesn't have them anymore

**Comment by danieljohnson2** [comment]
That's super odd; why would Proton change where the cover art goes?

**Comment by strycore** [comment]
What does Proton have to do with any of this?

**Comment by danieljohnson2** [comment]
> What does Proton have to do with any of this?

"I changed to proton 8.0 and it worked. thanks for the help"

I don't understand it.

**Comment by strycore** [comment]
Going to close this. Ubisoft Connect media are downloaded properly and this bug report is not valid.
