### ISSUE TITLE
Blocking wineexec tasks crash

### ISSUE THREAD

**Issue by adrianheine** [lutris/lutris#5429]
Since `wineexec` returns a str when blocking, this code fails:
https://github.com/lutris/lutris/blob/b239c824d6df24696a0cb14c13b402c77ba847b2/lutris/installer/commands.py#L431-L434

I'm happy to prepare a patch if you suggest a direction.

**Comment by danieljohnson2** [comment]
I got it. ``accepted_return_code`` is only used if it is a ``MonitoredCommand`` anyway, and the check is *right there*. I'll just move the assignment down a bit.
