### ISSUE TITLE
Database locked when config is stored on a Samba share

### ISSUE THREAD

**Issue by PaulTGG** [lutris/lutris#5431]
If the database file (pga.db), or the entire config folder, is on a Samba share, Lutris throws a "sqlite3.OperationalError: database is locked" error.  Lutris is able to read from a samba share, as well as create files/folders, but it can't write to files.  The file permissions are the same between the share and the local files (owned by the local user, and 644 for regular files).

Here's my system info (from "lutris --submit-issue"): https://pastebin.com/BH6LRZz2

Things of note:
1. If the "lutris" config folder (~/.local/lutris) is linked to a share before the first time Lutris starts, the program will crash with these messages: https://pastebin.com/F6SCntrg
2. If Lutris starts with a local config folder, and the config folder is then moved to a share and link created back to the original location, the following error happens (this example was me trying to add a game, but trying to delete a game still throws the "database locked" error): https://pastebin.com/KwSkvb8i
3. The most recent kernel for Linux Mint is 5.15.0-102, but that kernel has a bug with Samba access that can lead to other issues.  Those bugs/issues aren't present in the kernel I'm running (5.15.0-101).
4. This is also not limited to the lowlatency kernel, since another computer I run has the same issue running the default kernel.

**Comment by strycore** [comment]
ok, but have you considered *not* putting the SQLite database on a Samba share?

**Comment by PaulTGG** [comment]
> ok, but have you considered _not_ putting the SQLite database on a Samba share?

haha... why, yes!  Yes, I have!  I was just looking for an easy way to share my settings between my computers, while at the same time having everything backed up nicely, but I also know I'm probably the only person in the world doing this.  I'll close this, and we can call it an"unsupported use-case." XD

**Comment by strycore** [comment]
Well there's some good news. Starting with 0.5.17 we have library sync with Lutris.net. This will basically make your Lutris SQL database shared across all your devices and they don't even need to be on the same network!

**Comment by strycore** [comment]
Also, if you want to do that kind of thing, I think NFS shares would be a better option than Samba shares (I still wouldn't recommend it)

**Comment by PaulTGG** [comment]
> Also, if you want to do that kind of thing, I think NFS shares would be a better option than Samba shares (I still wouldn't recommend it)

Check.  I'll definitely check out the online account, and I definitely won't check out NFS... haha
