### ISSUE TITLE
[BUG] proton.get_game_id incorrectly handles the umu storeId when `game.service` is null/NoneType

### ISSUE THREAD

**Issue by ArcadeArchie** [lutris/lutris#5433]
I was tinkering around with `game.py` and `proton.py` to figure out why lutris ignores the `STORE` and `UMU_ID` env vars
and as it turns out when `get_game_id()` checks for the game service, the check failed due to  `game.service` being a `NoneType` and resulting in a capitalized `None` service id when stringified and `umu_game["store"]` being all lower case

![image](https://github.com/lutris/lutris/assets/29282748/f046a154-2229-4bf9-bcaa-8f8c78e60e99)

**Comment by danieljohnson2** [comment]
I don't understand.  That's not what the code in 0.5.17 looks like. Did you change and reformat all that selected code?

Anyway, if game.service is None, it fails to match the Umu store, and then you get DEFAULT_GAMEID. Without knowing what the store is, we don't know what the appid means, and the game shouldn't even have one I think.

I guess there's a limit to the integration here, where a game you just installed yourself, with no game store, won't get an umu_id, and I think that means it won't get any proton-fixes ("umu-fixes"?). Not ideal.

But I believe in master you can overcome this by setting the UMU_ID env-var yourself in the game config. 0.5.17 doesn't have that. Umu integration is an experimental feature, not quite there yet.

**Comment by ArcadeArchie** [comment]
> I was tinkering around with `game.py` and `proton.py` to figure out why lutris ignores the `STORE` and `UMU_ID` env vars

**I was tinkering around with game.py and proton.py to figure out why lutris ignores the STORE and UMU_ID env vars**

**Comment by ArcadeArchie** [comment]
> I don't understand. That's not what the code in 0.5.17 looks like. Did you change and reformat all that selected code?
> 
> Anyway, if game.service is None, it fails to match the Umu store, and then you get DEFAULT_GAMEID. Without knowing what the store is, we don't know what the appid means, and the game shouldn't even have one I think.
> 
> I guess there's a limit to the integration here, where a game you just installed yourself, with no game store, won't get an umu_id, and I think that means it won't get any proton-fixes ("umu-fixes"?). Not ideal.
> 
> But I believe in master you can overcome this by setting the UMU_ID env-var yourself in the game config. 0.5.17 doesn't have that. Umu integration is an experimental feature, not quite there yet.

**_I was tinkering around with game.py and proton.py to figure out why lutris ignores the STORE and UMU_ID env vars_**

**Comment by danieljohnson2** [comment]
Ah, and you showed us your tinkering as the bugged code.

But I'm not convinced it's bugged. What *should* it do for a game with no service?

**Comment by ArcadeArchie** [comment]
force set it to `none`? so it correctly gets the id for games with a none store

**Comment by ArcadeArchie** [comment]
> But I believe in master you can overcome this by setting the UMU_ID env-var yourself in the game config. 0.5.17 doesn't have that. Umu integration is an experimental feature, not quite there yet.

i've set those, they seem to be ignored except `STORE`

**Comment by ArcadeArchie** [comment]
> Ah, and you showed us your tinkering as the bugged code.
> 
> But I'm not convinced it's bugged. What _should_ it do for a game with no service?

my bad. still it should probably treat a game that has no service set, has it having a storeId of `none`

**Comment by danieljohnson2** [comment]
What, is 'none' an actual store known to Umu?

If you want to use UMU_ID, make sure you are using the master branch, not 0.5.17. There is code in that very method about this, which I do not see in your screenshot.

**Comment by ArcadeArchie** [comment]
> If you want to use UMU_ID, make sure you are using the master branch, not 0.5.17. There is code in that very method about this, which I do not see in your screenshot.

👍
