### ISSUE TITLE
Umu in lutris 0.5.17 lock to python 3.10+ and glibc 2.34+

### ISSUE THREAD

**Issue by kilolife** [lutris/lutris#5434]
Umu in lutris 0.5.17 lock to python 3.10+ syntactically and hardlock to glibc 2.34+
As a result, umu does not work in ubuntu 20.04.

Python part: .local/share/lutris/runtime/umu/umu_plugins.py 173 line
"with" statement use new syntax from python 3.10+, however in Ubuntu 20.04 we have python 3.8

glibc part:
.local/share/lutris/runtime/umu/reaper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by .local/share/lutris/runtime/umu/reaper)
#dpkg -l | grep libc-bin
ii  libc-bin                                    2.31-0ubuntu9.14

**Comment by danieljohnson2** [comment]
Ah, these things are part of Umu, not part of Lutris. I don't know if Umu even wants to support old Python and GLib versions.

But you probably should bring this to [the UMU repo](https://github.com/Open-Wine-Components/umu-launcher) and see what they want to do.

If Umu won't support older Python or glib, maybe we can block access in the UI.

**Comment by kilolife** [comment]
> Ah, these things are part of Umu, not part of Lutris. I don't know if Umu even wants to support old Python and GLib versions.
> 
> But you probably should bring this to [the UMU repo](https://github.com/Open-Wine-Components/umu-launcher) and see what they want to do.
> 
> If Umu won't support older Python or glib, maybe we can block access in the UI.

https://github.com/Open-Wine-Components/umu-launcher/issues/91#issuecomment-2064306391

They recommended that you rebuild reaper with a lower version of glibc.
By the way, the version of reaper from Steam is compiled with lower requirements for glibc.
Python problem can fixed simple.

**Comment by strycore** [comment]
I have to update the umu build, I can rebuild reaper on something other than Nobara 39.

There is no need to use Python 3.10 specific code in umu, it should be replaced with Python 3.7 compatible code.

**Comment by kilolife** [comment]
Ubuntu 20.04 still live and have LTS state

**Comment by strycore** [comment]
> Ubuntu 20.04 still live and have LTS state

Don't push it. Ubuntu 20.04 is a 4 year old distro and you have no reason to still be using it in 2024.

**Comment by kilolife** [comment]
Thanks for the advice, I understand that the my operating system is quite old. But it is used in heavy work and upgrade is difficult.

**Comment by strycore** [comment]
Yeah, I have servers that are still on Ubuntu 16.04. 
But I don't try to play video games on them.

**Comment by lucaslira95** [comment]
Is there a tutorial to use ge-proton with umu on actual version of lutris?
(I'm using native package on archlinux)

**Comment by strycore** [comment]
Sure,  I gotcha

![step1](https://github.com/lutris/lutris/assets/280336/a15e4204-7ee7-4a7e-8806-1f5b1fe15cf6)

(Step 1)

![Screenshot_20240511_075543](https://github.com/lutris/lutris/assets/280336/651f8037-bc7c-44c9-b072-d0785411786b)

(Step 2)

**Comment by lucaslira95** [comment]
Already tried, but it just keeps starting forever, no response, no prefix being created, nothing happens...

**Comment by strycore** [comment]
Well a tutorial isn't going to help you there.

**Comment by freaky-m0** [comment]
> Sure, I gotcha
> 
> ![step1](https://private-user-images.githubusercontent.com/280336/329791349-a15e4204-7ee7-4a7e-8806-1f5b1fe15cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTg5NDEsIm5iZiI6MTcxNjAxODY0MSwicGF0aCI6Ii8yODAzMzYvMzI5NzkxMzQ5LWExNWU0MjA0LTdlZTctNGE3ZS04ODA2LTFmNWIxZmUxNWNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNzUwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmRkNmZhYzMzMzQ0NWU3ZjIxOTg2NmJkMTQ4ZGFkYmE4YzYzZjg5YWY3NGZmMjdkMGE3MjE3NzI5OGFiMzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.psu6wEkGg1bG0_x-dkbIhYEk1zfX5Tx2LNrdPp3aQjA)
> 
> (Step 1)
> 
> ![Screenshot_20240511_075543](https://private-user-images.githubusercontent.com/280336/329791441-651f8037-bc7c-44c9-b072-d0785411786b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTg5NDEsIm5iZiI6MTcxNjAxODY0MSwicGF0aCI6Ii8yODAzMzYvMzI5NzkxNDQxLTY1MWY4MDM3LWJjN2MtNDRjOS1iMDcyLWQwNzg1NDExNzg2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNzUwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmQzZmVjZjdiNjlhM2U3ZTFkNmQ1N2MxMzg4YzhhOWI1Yzg2NGNhMjgyNWQ1MDIyYjdjOWJiYmVlMzcwMGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3oSHVJ4jIuyjlGTS1znlTpnyZIxRxt9xJWgvxkXTOhM)
> 
> (Step 2)

I'm on Lutris 0.5.17 and don't have this option. I don't understand how to use ge-proton :( I also have no download available in protonup-qt

**Comment by danieljohnson2** [comment]
I found this more than a little counter-intuitive. I had to use ProtonUp-Qt to install these Umu versions. And I had to install them 'for' Steam, even though I don't have Steam.
![image](https://github.com/lutris/lutris/assets/6507403/0a7361d2-ef82-46ae-8671-7215f7227f38)

**Comment by strycore** [comment]
umu should be able to run without having Steam or installing anything with ProtonUp. If it doesn't show up as an option then we have a wrong check in place. And Lutris needs is umu-launcher and that is downloaded via the runtime for everyone.

**Comment by danieljohnson2** [comment]
OK; I've removed the ProtonUI-Qt stuff and that left me with only "GE-Proton (Latest)" but that did work; so I guess whatever was breaking it got fixed.

**Comment by strycore** [comment]
That is the desired outcome. "GE-Proton (Latest)" is automatically managed and updated by umu.

**Comment by R1kaB3rN** [comment]
@strycore you can go ahead and close this issue now. 

umu-launcher has now built Reaper natively into the launcher which solves the glibc lock and the single with statement has been refactored.
