### ISSUE TITLE
lutris stuck on starting for long time, if its window is maximized, launching a game from a library or platform which has lot of them

### ISSUE THREAD

**Issue by ChuckBartowski91** [lutris/lutris#5440]
Hello, lutris -d output before game starts, about missing vulkan my video card doesn't support it (sorry but i cannot make code paste to work, it appears as normal text):

2024-04-19 17:07:43,963: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-04-19 17:07:46,481 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR: [../mesa-24.0.5/src/amd/vulkan/radv_physical_device.c:1828] Code 0 : Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
ERROR    2024-04-19 17:07:46,829 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-04-19 17:07:46,830 [startup.run_all_checks:120]: (1002:9490 174b:e880 radeon) Driver 24.0.5
ERROR    2024-04-19 17:07:46,831 [startup.check_libs:62]:i386 libvulkan.so.1 missing (needed by vulkan)
DEBUG    2024-04-19 17:07:49,449 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-04-19 17:07:49,532 [xrandr._get_vidmodes:18]:Retrieving 12 video modes from XrandR
DEBUG    2024-04-19 17:07:49,942 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-19 17:07:50,529 [api.check_stale_runtime_versions:52]:Modified at ven 19 apr 2024, 11:52:45, will update after ven 19 apr 2024, 17:52:45

(lutris:1852): Gtk-WARNING **: 17:07:50.529: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Inhibit» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
ERROR    2024-04-19 17:07:50,737 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
DEBUG    2024-04-19 17:07:51,537 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
WARNING  2024-04-19 17:07:53,167 [lutriswindow.update_missing_games_sidebar_row:418]:Path cache out of date? (1 IDs missing)
DEBUG    2024-04-19 17:08:04,640 [grid.on_item_activated:97]:Item activated: 74

and after:

DEBUG    2024-04-19 17:08:40,837 [xrandr.get_outputs:26]:Retrieving display outputs
DEBUG    2024-04-19 17:08:40,899 [xrandr._get_vidmodes:18]:Retrieving 12 video modes from XrandR

If i minimize the lutris window the game starts right away, the same if i lower the resolution to 1152x864 or lower, could be a problem with xrandr? If i close lutris window the game starts too. No problems launching a game from a launcher with few games.
I'm using artix linux xfce s6 and lutris 0.5.17, on mx linux fluxbox this issue didn't exist but i was using lutris 0.5.12. Maybe the new version doesn't work well with very old hardware (athlon 64 x2 5600+ 2.9 ghz, radeon hd 4670, 4 gb ram)?

**Comment by danieljohnson2** [comment]
Weird behavior there. You are getting errors suggesting that Vulkan is borked for you, and Lutris depends on it more than previous versions did. 'vulkaninfo' was found but found no GPUs and complained of a broken driver.

I've made some changes to tolerate this better: it will fall back to using lspci on a GPU by GPU basis.

Please download the [latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. Does that work better for you? Did it change the log output?

**Comment by ChuckBartowski91** [comment]
In the installed version the problem doesn't show too if i search a game in the runner and then i launch it (since only one is showed on lutris window probably). 

Launching the master version the problem disappears completely. However that's the output of the terminal launching it:

./lutris
2024-04-21 11:47:40,875: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
2024-04-21 11:47:42,675: Starting Lutris 0.5.17
ERROR: [../mesa-24.0.5/src/amd/vulkan/radv_physical_device.c:1828] Code 0 : Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
2024-04-21 11:47:42,967: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
2024-04-21 11:47:43,005: Advanced Micro Devices, Inc. [AMD/ATI] RV730 XT [Radeon HD 4670] (1002:9490 174b:e880 radeon) Driver 24.0.5
2024-04-21 11:47:43,006: i386 libvulkan.so.1 missing (needed by vulkan)

(lutris:3335): Gtk-WARNING **: 11:47:46.655: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Inhibit» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
2024-04-21 11:47:46,704: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/home/chuckii/Scaricati/lutris-master/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
2024-04-21 11:47:49,197: Path cache out of date? (1 IDs missing)

(lutris:3335): Gtk-WARNING **: 11:48:17.479: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Inhibit» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop

**Comment by ChuckBartowski91** [comment]
> Weird behavior there. You are getting errors suggesting that Vulkan is borked for you, and Lutris depends on it more than previous versions did. 'vulkaninfo' was found but found no GPUs and complained of a broken driver.
> 
> I've made some changes to tolerate this better: it will fall back to using lspci on a GPU by GPU basis.
> 
> Please download the [latest master](https://github.com/lutris/lutris) and run the `bin/lutris` script within. Does that work better for you? Did it change the log output?
In the installed version the problem doesn't show too if i search a game in the runner and then i launch it (since only one is showed on lutris window probably).

Launching the master version the problem disappears completely. However that's the output of the terminal launching it:

./lutris
2024-04-21 11:47:40,875: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
2024-04-21 11:47:42,675: Starting Lutris 0.5.17
ERROR: [../mesa-24.0.5/src/amd/vulkan/radv_physical_device.c:1828] Code 0 : Device '/dev/dri/renderD128' is not using the AMDGPU kernel driver: Invalid argument (VK_ERROR_INCOMPATIBLE_DRIVER)
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs: Failed to detect any valid GPUs in the current config
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.269/vulkaninfo/./vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
2024-04-21 11:47:42,967: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
2024-04-21 11:47:43,005: Advanced Micro Devices, Inc. [AMD/ATI] RV730 XT [Radeon HD 4670] (1002:9490 174b:e880 radeon) Driver 24.0.5
2024-04-21 11:47:43,006: i386 libvulkan.so.1 missing (needed by vulkan)

(lutris:3335): Gtk-WARNING **: 11:47:46.655: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Inhibit» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
2024-04-21 11:47:46,704: Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
File "/home/chuckii/Scaricati/lutris-master/lutris/style_manager.py", line 80, in _call_cb
values = obj.call_finish(result)
^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop (19)
2024-04-21 11:47:49,197: Path cache out of date? (1 IDs missing)

(lutris:3335): Gtk-WARNING **: 11:48:17.479: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.freedesktop.portal.Inhibit» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop

**Comment by danieljohnson2** [comment]
Ah, good. Likely the fallback to lspci worked- it can now 'see' your GPUs.

I think Lutris was effectively leaving you on some cheap slow integrated GPU and that caused your performance problems, because it couldn't tell the difference.

Since this makes the problem 'disappear completely' I think we can declare victory and close this item. I hope this fix also helps others with similar problems.

**Comment by ChuckBartowski91** [comment]
> Ah, good. Likely the fallback to lspci worked- it can now 'see' your GPUs.
> 
> I think Lutris was effectively leaving you on some cheap slow integrated GPU and that caused your performance problems, because it couldn't tell the difference.
> 
> Since this makes the problem 'disappear completely' I think we can declare victory and close this item. I hope this fix also helps others with similar problems.

Well this pc has no integrated graphics, is for retrogaming. That's the dedicated one, 

Thanks for everything. I'll wait for the lutris release update.
