### ISSUE TITLE
NoneType error after updating to Lutris 0.5.17 from prev version

### ISSUE THREAD

**Issue by arcadeportal32** [lutris/lutris#5441]
`Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/game.py", line 761, in configure_game
    raise error

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1024, in prelaunch
    for manager, enabled in self.get_dll_managers().items():
                            ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 1044, in get_dll_managers
    manager = manager_class(self.prefix_path, arch=self.wine_arch, version=version)
                                                   ^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 678, in wine_arch
    arch = detect_arch(prefix_path, self.get_executable())
                                    ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 739, in get_executable
    version = self.read_version_from_config()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 711, in read_version_from_config
    return get_default_wine_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 189, in get_default_wine_version
    if "version" in default_version and "architecture" in default_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: argument of type 'NoneType' is not iterable`

It will pop this error up clicking any game and will not boot them now.

My Laptops basic info pulled from NeoFetch
OS: Debian GNU/Linux 12 (bookworm) i686 
Host: Satellite A135 PSAD0U-05400P 
Kernel: 6.1.0-18-686-pae 
Uptime: 23 mins 
 Packages: 2422 (dpkg), 4 (snap) 
Shell: bash 5.2.15 
Resolution: 1280x800 
DE: MATE 1.26.0 
WM: Metacity (Marco) 
Theme: Arc-Dark [GTK2/3] 
Icons: gnome-human [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Genuine Intel T2080 (2) @ 1.733GHz 
GPU: Intel Mobile 945GM/GMS/GME, 943/940GML Expre 
Memory: 1221MiB / 2002MiB

**Comment by danieljohnson2** [comment]
I am quite disappointed in mypy; it should be able to find these bugs at least. But here we are.

I've checked in a fix for the NoneType thing, and you can try it by downloading the master branch and running the ``bin/lutris`` script within- no need to install. But if you look in the Preferences at the 'Updates' tab, I expect you will find that it can't figure out what the default Wine version should be.

That's not ideal, and I don't know what the problem is. There may be some more information in the log output before that traceback.

At this point I would also suggest you might delete the file ``~/.cache/lutris/versions.json' to force Lutris to refresh this information. Might help.

**Comment by arcadeportal32** [comment]
Downloading from the master branch and running the Lutris script worked! Ty Playing Baulders Gate 2 now lol

**Comment by danieljohnson2** [comment]
Well, when you are done playing, let me know what you see in your Preferences window (Updates tab). Is it happy now?

**Comment by arcadeportal32** [comment]
The Preference window is still not happy with me popping up this....

Traceback (most recent call last):

  File "/home/thoshako/Desktop/lutris-master/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/thoshako/Desktop/lutris-master/lutris/gui/lutriswindow.py", line 985, in on_preferences_activate
    self.application.show_window(PreferencesDialog, parent=self)

  File "/home/thoshako/Desktop/lutris-master/lutris/gui/application.py", line 385, in show_window
    window_inst = window_class(**kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/thoshako/Desktop/lutris-master/lutris/gui/config/preferences_dialog.py", line 67, in __init__
    self.stack.add_named(self.build_scrolled_window(UpdatesBox()), "updates-stack")
                                                    ^^^^^^^^^^^^

  File "/home/thoshako/Desktop/lutris-master/lutris/gui/config/updates_box.py", line 34, in __init__
    update_label_text, update_button_text = self.get_wine_update_texts()
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/thoshako/Desktop/lutris-master/lutris/gui/config/updates_box.py", line 104, in get_wine_update_texts
    wine_version = format_runner_version(wine_version_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/thoshako/Desktop/lutris-master/lutris/api.py", line 198, in format_runner_version
    version = version_info.get("version") or ""
              ^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by danieljohnson2** [comment]
I expect it did indeed crash before- looks like my fix just moved the crash very slightly. Clever.

I've tried that again, please redownload the master and try it again.

**Comment by arcadeportal32** [comment]
Hey! Preferences is now happy with me! It actually opened after redownloading!

**Comment by danieljohnson2** [comment]
But is it complaining it can't give you a Wine update? It'll be in the second box under "Wine updates" if I am right...

**Comment by danieljohnson2** [comment]
I don't understand why not- for me it does.

Have you tried deleting ``~/.cache/lutris/versions.json``? I'm fixing a bug now where this is not downloaded when it should be (unless it is old enough) but you can still just delete it.

**Comment by arcadeportal32** [comment]
I did delete versions.json again, and still says "no default wine version could be identified, no updates available, no updates are required"

**Comment by danieljohnson2** [comment]
I think I have it! Your name is @arcadeportal32 because you run 32-bit Linux! This bug happens on 32-bit Linux!

If so, amazing to say it, that's probably obscure enough not to justify a new release soon, and you'll need to stay on 0.5.16 until 0.5.18 comes out.

**Comment by arcadeportal32** [comment]
It is 32-Bit Linux :) Raw Debian 12 with a customized MATE Desktop. Well it seems I can get things going using the master I downloaded so I will use that for now until the next version is released! Thank you VERY much for your help. Keeping a laptop from 2007 alive XD! I use this for YouTube and OpenRCT2 mostly either way lul.

**Comment by danieljohnson2** [comment]
Alright; I think the master you've got is okay to use. Mostly fixes so far. But you do get an 'Uncategorized' tab in the main view, and logs displayed in the Preferences. So there's that. Enjoy.

**Comment by arcadeportal32** [comment]
Will do! Thank you for your help!
