### ISSUE TITLE
[WORKAROUND] - loading Lutrus 0.5.17 when using NVIDA UNIX Open Kernel drivers

### ISSUE THREAD

**Issue by hugovonhorse** [lutris/lutris#5444]
If you try to load Lutris when using the "Nvidia Open Kernel" drivers provided by Ubuntu repo (v 550.54.15 at least), you will get the error:

---start snip
2024-04-20 21:17:07,766: GPU: 10DE:2805 1043:891B (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 334, in do_command_line
    run_all_checks()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 152, in run_all_checks
    check_driver()
  File "/usr/lib/python3/dist-packages/lutris/startup.py", line 77, in check_driver
    if drivers.is_outdated():
  File "/usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py", line 112, in is_outdated
    major_version = int(driver_version.split(".")[0])
ValueError: invalid literal for int() with base 10: 'for'
2024-04-20 21:17:07,796: Shutting down Lutris
----end snip

**[TO FIX]**
`sudo vi /usr/lib/python3/dist-packages/lutris/util/graphics/drivers.py`

modify line 28 so the element is 7:

                'version': nvrm_version[7],

and line 29 to element 8 (although not sure this changes anything, i did it anyway):

                'date': ' '.join(nvrm_version[8:])

This is because the original element is picking up the word "for" from the driver version file in /proc/driver/nvidia/ causing a 'base 10' conversion error. Element  7 is the corrent element for the driver version number with the Open Kernel drivers.

**Comment by strycore** [comment]
You do realize that you can't propose a fix that works for you but breaks on every other install that doesn't use the open source version, right?

**Comment by danieljohnson2** [comment]
Matching up your line numbers with the code, I see that you are on a version of Lutris no later than 0.5.10.1, which is almost exactly two years old. @hugovonhorse, maybe you should update before doing fixes like this.

That said, I think it will still crash since you seem to be getting something unexpected out of ``/proc/driver/nvidia/version``, but I do not know what it was, so I can't really fix this.

I'll add some prophylactic code to give it a chance, and some nicer logging at least.

**Comment by danieljohnson2** [comment]
OK, I've done a "fix"- it still won't be able to understand your NVIDIA driver, but it should no longer crash though it will assume it is outdated.

@hugovonhorse, when you get a chance please [download the master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install it. Does that work better for you?

In 0.5.17, the ``is_outdated`` check that is failing is not run on startup- it runs when you try to configure a Wine game, and you visit the "Runner options" tab in that window. So make sure you go look at that; I expect a warning about your driver will be present.

I suspect that you've tried to install 0.5.17 via the deb by double clicking it. On Ubuntu derivative distributions this annoyingly does not work- it just installs Lutris from your distribution's repositories, which seem to be spectacularly out of date. If that's what happened, maybe you should use the [Lutris PPA](https://launchpad.net/~lutris-team/+archive/ubuntu/lutris) which is up to 0.5.17.

I hope that the improved error handling in 0.5.17 will allow it to work for you even without my recent 'fix' anyway.

But @strycore, I see that Lutris.net's download page still points Ubuntu users as the .deb file, so they won't get automatic updates. Maybe it should reference the PPA again now that that's back?

**Comment by hugovonhorse** [comment]
> I suspect that you've tried to install 0.5.17 via the deb by double clicking it. On Ubuntu derivative distributions this annoyingly does not work- it just installs Lutris from your distribution's repositories, which seem to be spectacularly out of date. If that's what happened, maybe you should use the [Lutris PPA](https://launchpad.net/~lutris-team/+archive/ubuntu/lutris) which is up to 0.5.17.

you suspect correctly and my that is annoying ...  having gone to the Help > About menu it is indeed actually running 0.5.9.1 :man_facepalming:   apologies, please mark the whole thing 'Complete/Void' and i'll install the latest version from the PPA and see what happens.

For note: the ouput of /proc/driver/nvidia/version is;

```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  550.54.15  Release Build  (dvs-builder@U16-A24-23-2)  Tue Mar  5 22:15:33 UTC 2024
GCC version:  gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04)

```
Thanks

**Comment by danieljohnson2** [comment]
I tried your file out and it looks like the current Lutris *does* handle that properly, though the code does not match what you say it ought to be. I think if you can get onto 0.5.17 you will be fine.

**Comment by hugovonhorse** [comment]
For the moment ive downgraded the drivers to 545 proprietary from the ubuntu-drivers list and reversed the element changes and its picking that up ok too.
