### ISSUE TITLE
Unable to see Epic Games  game list from lutris

### ISSUE THREAD

**Issue by javichz** [lutris/lutris#5445]
Steps to reproduce:
* Open lutris
* Go to [Sources] -> [Epic Games Store]  and add an account (tried with email and google oauth2 and same behavior)
* Press Refresh 
* After a couple seconds it fails with an error message (below).

I've tried installing pillow 10.3.0 and 9.0.0 and still get the same error
```
module 'PIL.Image' has no attribute 'Resampling'

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 143, in do_reload
    self.load_icons()

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 172, in load_icons
    service_media.render()

  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 85, in render
    self._render_filename(filename)

  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 47, in _render_filename
    thumb_image = thumbnail_image(thumb_image, self.remote_size)

  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 238, in thumbnail_image
    base_image = base_image.resize((width, height), resample=Image.Resampling.BICUBIC)

  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

![image](https://github.com/lutris/lutris/assets/18448386/19b94c99-198f-4070-a754-fe799b7d2417)

**Comment by strycore** [comment]
What distro are you running and how did you get lutris installed?

**Comment by javichz** [comment]
I'm running  Linux Mint 21.3 x86_64
First installed wine  from [here](https://wiki.winehq.org/Ubuntu), for Ubuntu Jammy (it's my Mint's equivalent)
Then installed the .deb from [here](https://github.com/lutris/lutris/releases)

**Comment by strycore** [comment]
Can you revert anything you did regarding Pillow and return to you distro's provided package? 

Make sure you don't have an extra PIL install with: 

`python -c "import PIL; print(PIL.__file__)"`

It should print:

`/usr/lib64/python3.12/site-packages/PIL/__init__.py`

with 3.12 replaced by whatever python version Mint provides.

**Comment by javichz** [comment]
Done 
![image](https://github.com/lutris/lutris/assets/18448386/1d0d6937-3579-4078-8d44-c71533a76842)

**Comment by strycore** [comment]
now run 

`rm -rf ~/.local/lib` 

and Lutris will be fixed.

**Comment by javichz** [comment]
exact same error as before

**Comment by strycore** [comment]
what does `python -c "import PIL; print(PIL.__file__)"` say now?

**Comment by javichz** [comment]
```
$  python -c "import PIL; print(PIL.__file__)" 
/usr/lib/python3/dist-packages/PIL/__init__.py
```
AND

```
$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> print(PIL.__file__)
/usr/lib/python3/dist-packages/PIL/__init__.py
>>> print(PIL.__version__)
9.0.1
>>> 
```

**Comment by javichz** [comment]
Apparently running ```pip install pillow=10.3.0``` does install pillow version 10.3.0 to the user lib, however that is not picked up by lutris. I got it working by running the infamous ```sudo pip install pillow=10.3.0``` and ignoring the warning. It was my OS fault. 
Thank you for your assistance @strycore

**Comment by strycore** [comment]
This is Linux Mint's fault.

**Comment by Bjohnson131** [comment]
for anyone else having trouble like me, I ran these commands to fix the issue:

```bash
pip install --upgrade pip
sudo pip install pillow==10.3.0
```
