### ISSUE TITLE
UI shows {count} in "Add games to Lutris" dialog

### ISSUE THREAD

**Issue by AinoSpring** [lutris/lutris#5446]
In the "Add games to Lutris" dialog, under the "Search the Lutris website for installers" option, when searching and it only shows a fraction of the results, instead of showing that count, it shows "{count}" as seen in the image.

![image](https://github.com/lutris/lutris/assets/73998195/b77889c7-67ca-4e95-b131-e6626a3815df)

**Comment by danieljohnson2** [comment]
A wee mistake in a previous bugfix- the format string isn't formatted right. I'll fix that. Thanks for the bug report.
