### ISSUE TITLE
[Feature] Right-click "Duplicate" feature should ask if the prefix needs to be copied too

### ISSUE THREAD

**Issue by hazrpg** [lutris/lutris#5447]
I sometimes create a "template" with everything I need that gets most things working, and then simply duplicate it by using the right-click menu item. However, it would be nice if it asked if I would like to also duplicate the wine prefix folder to the new location.

It already has the dialogue box asking what to name it, it would be nice if there was a tick that also said "Also copy the directory to the new one?" - with the default being unticked to not confuse existing people that use the duplicate feature.

It would also be nice if categories were automatically copied over too - since that doesn't happen either.

Let me know what you're thoughts are, and if this is something that is relatively easy to do.

**Comment by danieljohnson2** [comment]
This is a bit trickier than it sounds, since we'd have to update all the paths leading into this, for all different runners we support. They aren't all the same paths, and you can have things like a prefix outside the game directory but game files within it.

But the categories should be copied over, I think. I'll look into that.

**Comment by danieljohnson2** [comment]
OK, I've done that part of it at least.

**Comment by strycore** [comment]
Please do not hijack the duplicate game feature to do something that has nothing to do with duplicating a game entry.

**Comment by danieljohnson2** [comment]
Well, if we aren't going to duplicate directories, there's nothing left to do for this item. I'll close it.

**Comment by strycore** [comment]
I would like to have Wine prefix "templates" but the duplicate game feature is not the correct place to implement it.

Is it better suited for the "game directory snapshot" feature I have planned. (More on that later)

**Comment by hazrpg** [comment]
@danieljohnson2 Thank you so much for implementing that code for duplicating the category; I noticed that commit in the latest release! Much appreciated.

@strycore Thanks for clarifying that the duplicate feature wasn't intended for the purpose that I use it for. I presume its intended purpose then is for cases like Battle.net where a launcher/agent is needed, but different tweaks are required for individual games due to quirks. Possibly also for mods. If so, the naming might be a bit misleading - "duplicate" typically implies making an exact copy. Given the subsequent dialogue prompts to give it a new name, it suggests creating an exact copy but with a different name (and location). Would it not be more accurate to label this feature as "Link another game to this prefix" or "Copy this entry for another EXE" or "Reuse the same settings for another game" - or something along those lines?

Regarding your prefix template idea, it sounds intriguing. Integrating a "game directory snapshot" or "templates" feature could offer users the ability to create and reuse preset configurations. Is there an issue marked for this feature, or should we create a new one for it and tag it back to this issue?

**Comment by strycore** [comment]
No existing ticket at the moment for prefix snapshots, it's not yet fully clear how this will be implemented but I will start experimenting with it soon
