### ISSUE TITLE
Umu in Lutris 0.5.17 ignore "Working directory" setting in some cases

### ISSUE THREAD

**Issue by kilolife** [lutris/lutris#5448]
When i launch game with Proton Experimrntal runner, everything works correctly. UMU work!
But if i use "GE-Proton (Latest)" or  UMU-Proton-9.0-beta16-2 or GE-Proton9-4 runner, working directory is same as directory where placed game exe file. 
I tested this by replacing the game exe file with the cmd.exe file from the wine.

**Comment by strycore** [comment]
Most lutris options are not expected to work with umu.

**Comment by kilolife** [comment]
I think this behavior is incorrect.

**Comment by strycore** [comment]
It's not about being correct, it's about umu being in a early and experimental stage. I believe there is an issue about the CWD of a game on the umu bugtracker

**Comment by kilolife** [comment]
You're right, that's exactly the problem.

**Comment by strycore** [comment]
ok, let's close this and focus on the umu-launcher issue then.
