### ISSUE TITLE
Missing executable error

### ISSUE THREAD

**Issue by Citizen839X** [lutris/lutris#5451]
The file /home/carlo/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe could not be found

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 31, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 668, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 607, in get_gameplay_info
    gameplay_info = self.runner.play()
                    ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/lutris/runners/wine.py", line 1202, in play
    raise MissingGameExecutableError(filename=game_exe)

lutris.exceptions.MissingGameExecutableError: The file /home/carlo/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe could not be found

**Comment by strycore** [comment]
The installation of EA App didn't complete, thus is the part you need to troubleshoot, not the aftermath.

You're also missing vital information like thr lutris version used and your operating system. 
Your issue is most likely being worked on #5390

**Comment by Citizen839X** [comment]
Thank you for your reply. I've gather some more inf, I hope could be more useful...

Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: openSUSE Tumbleweed 20240423 n/a
Arch: x86_64
Kernel: 6.6.28-1-longterm
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5700G with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 46.8 GB
Swap: 3.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) Arc(tm) A380 Graphics (DG2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.3
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.3
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.3
Vulkan Version: 1.3.280
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.274), Intel(R) Arc(tm) A380 Graphics (DG2) (1.3.274)

**Comment by Citizen839X** [comment]
PS EA app is the only one that is troublesome. Epic Games, GOG and now even Ubisoft (back from the dead after a year) are working perfectly. Considering how EA hates Linux and how unfortunate is their app "evolution" after Origin, I will not miss them anyway. I've just post this in order to update the situation that basically is still the same since Origin changed. When Origin was up and running it was even better than Epic Launcher, I'm just saying. Cheers.

**Comment by strycore** [comment]
> Considering how EA hates Linux

EA doesn't "hate" linux, it's more that they do not care about it. There are issues with EA App in certain situations but when it works, it's not any worse than other launchers.

**Comment by strycore** [comment]
Also, if you don't use it, try disabling you iGPU in the BIOS and try installing EA app again.

**Comment by Citizen839X** [comment]
Yeah, "when it works". 

Actually, I suggest to all the people that will stumble here for a solution to install Heroic via Flatpak and install the EALauncher.exe (be sure to have the very latest version from their website) from there. It is easier and functional because the installation goes until the end and all the file system paths "get soldered" (thank Jesus). It actually worked and we can load the ProtonGE modules exactly like Lutris and Steam (through ProtonUp-Qt).

For openSUSE users: if, like me, you need to assign to Heroic additional Wine drive path it's even more easier because you just need to go through the EA app interface when you install your game from the library and the app automatically asks you for the destination path, then search for "/" through the integrated Wine system, and then the default path assigned by Yast Partitioner which is "run/media/username/drivename". We are a little bit different from Debian and derivates, you know.

Peace&Love

**Comment by nprime496** [comment]
Hi @Citizen839X, didn't work for me.

I
* [installed Heroic via Flatpak](https://flathub.org/apps/com.heroicgameslauncher.hgl)
* Downloaded the [EAInstaller.exe](https://www.ea.com/ea-app)  
* Ran the Installer in Heroic

The EA app does not run in Heroic : I get an unexpected crash.
The path expected by Lutris ( `~/Games/ea-app/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe` is still not present. 

Did I do something wrong ?

**Comment by Citizen839X** [comment]
> Did I do something wrong ?

probably yes. Try to completely uninstall the EA app path from Lutris. Forget about it because Lutris is completely bugged with EA. Then open Heroic and run the procedure for launchers or .exe with "add game" and don't forget to click on "run installer first" after selected all the necessary paths (included, obviously the launcher).

It works on my system which is openSUSE Tumbleweed with 6.6.30 LTS kernel (slowroll custom setup). The installer itself works fine, then, not all the games will run for technical reasons. I can run The Sims 4 with mods and Frostbite Engine 2 games with the exception of Garden Warfare 2 which have a sort of block portection in regards of Wine/Proton layer.

**Comment by Citizen839X** [comment]
PS be sure to use the Proton GE module version 9-5 and check the latest MESA Intel/AMD update. I've recently updated.

**Comment by strycore** [comment]
If you're just going to mark tickets as "solded by using Heroic" then you should have asked for support on Discord and not open a ticket on Github because this is really unhelpful.

**Comment by Citizen839X** [comment]
> If you're just going to mark tickets as "solded by using Heroic" then you should have asked for support on Discord and not open a ticket on Github because this is really unhelpful.

Unhelpful for who? For the Lutris devs that are still unable to fix an installer bug?

Pragmatism 2 Gatekeeping 0

Move on, please.

**Comment by SetOfAllSets** [comment]
> > If you're just going to mark tickets as "solded by using Heroic" then you should have asked for support on Discord and not open a ticket on Github because this is really unhelpful.
> 
> Unhelpful for who? For the Lutris devs that are still unable to fix an installer bug?
> 
> Pragmatism 2 Gatekeeping 0
> 
> Move on, please.

Lutris devs will not see this as an issue in their issue tracker if they have solved issues filtered out, meaning this is likely to not be fixed. Please re-open the issue.

**Comment by strycore** [comment]
> Lutris devs will not see this as an issue in their issue tracker if they have solved issues filtered out, meaning this is likely to not be fixed. Please re-open the issue.

It's ok, I was the one to close this issue as a duplicate of another issue. The discussions that happen on closed tickets is not really of high value for the development of Lutris.
