### ISSUE TITLE
Limit FPS

### ISSUE THREAD

**Issue by nipnipj** [lutris/lutris#5453]
How do we limit FPS within Lutris app?

**Comment by danieljohnson2** [comment]
Looks like that's an option only for one runner, EasyRPG. If your game is not an EasyRPG game, you will need to find a non-Lutris way to do that.

**Comment by nipnipj** [comment]
I see. I think `strangle 144` in prefix command works fine.

**Comment by strycore** [comment]
We have recently removed support for libstrangle as it's X11 only and hasn't been updated in 4 years.

You can limit the framerate with gamescope (Framerate limiter option), although I'm not sure it works correctly, from my experience, it seems to be ignored. It works on the Steam Deck though so there's probably a way to fix that.

The other option you have to limit FPS is with Mangohud / Goverlay\

![image](https://github.com/lutris/lutris/assets/280336/e12792a9-1e19-4a7a-8712-ad8e56d82f93)

**Comment by nipnipj** [comment]
I used `strangle` as I said, but it caused bad performance in this game "Heroes of Newerth". I haven't try any other game.
Limiting fps with mangohud does not reduce the performance.
