### ISSUE TITLE
Added games from a different OS on a shared disk not automatically added in other distro

### ISSUE THREAD

**Issue by gituser823** [lutris/lutris#5454]
hello,

Im using a shared EXT4 drive for my Lutris games.

When I boot into a OS and install a game in Lutris, then reboot and switch to the other OS the installed game is not visible in the library, although both use the same shared disk.

I then need to press rescan library and the installed games show up.
But even then some games work andd some dont.

If you dont want to fix this bug, can you tell the command Lutris uses internally for rescanning a folder, so I can build my way around this bug with a bash script?

**Comment by danieljohnson2** [comment]
That doesn't sound like a bug at all.

You probably need to get both your OSes using the same configuration for the games. You *might* manage this if you two OSes could also share their ``~/.local/share/lutris`` and perhaps ``~/.cache/lutris`` directories. But this won't work unless the games are accessed via the same (full!) path on both.

But really, this isn't a supported scenario.

Lutris is written in Python, and so the code to scan folders is not written in bash at all. I don't think bash scripts are going to do this for you.
