### ISSUE TITLE
Steam Source Not Present

### ISSUE THREAD

**Issue by s-20** [lutris/lutris#5455]
![Screenshot from 2024-04-27 05-49-07](https://github.com/lutris/lutris/assets/52514259/32c8313a-a973-4cf4-92e3-569c8e81edf6)

Steam isn't present as an available source. This **IS NOT** Lutris not detecting a Steam Install; I saw this exact problem [dismissed earlier](https://github.com/lutris/lutris/issues/3765), but I don't have the EA App, and it was *enabled* when I started Lutris the first time.

It *isn't* that Steam isn't detected. It's that *the Steam Source isn't available at all*. Whether or not it can detect my Steam install isn't relevant, since it doesn't even have the option to have Steam as a source at all.

Steam is installed on Flatpak. This happened with both the RPM and Flatpak versions of Lutris.

**Comment by s-20** [comment]
[lutris-issue-report.json](https://github.com/lutris/lutris/files/15142484/lutris-issue-report.json)

**Comment by danieljohnson2** [comment]
I've looked at the code, and I think Lutris only sees Steam if it is installed 'natively', not via flatpak.

I think Lutris supports runners via flatpak, but not any sources.

**Comment by s-20** [comment]
Could this information be added to the Flatpak description, the Wiki, the website - somewhere? I've spent the better part of three days trying to track down this issue, and there's no information anywhere about it. I'm decent at troubleshooting, but I'm not a coder, so this would never have occurred to me.

**Comment by strycore** [comment]
I've submitted a fix for the Steam Flatpak detection here https://github.com/lutris/lutris/commit/f213290c89578a0d639eb953a877dad3064190e1

This doesn't guarantee that Steam Flatpak will fully work but at least it shows up as a source.
