### ISSUE TITLE
5.17 No Module Lutris

### ISSUE THREAD

**Issue by CharlotteCross1998** [lutris/lutris#5457]
After updating to 5.17-2, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'lutris'
```

Downgrading back to 5.16-2 fixes the problem.

**Comment by danieljohnson2** [comment]
Not a lot to go on, but sounds like #4883. Or maybe #4316.

**Comment by strycore** [comment]
Is Lutris 0.5.17 correctly being installed in `/usr/lib/python3.12/site-packages/lutris/` ? 

If you try to open a python console and enter:

```
import lutris
lutris.__file__
```

what does it tell you?

**Comment by strycore** [comment]
> Packages in .local/lib/python3.11/site-packages

Since you are now on Python 3.12, the Python packages in the 3.11 folder are going to be ignored.

**Comment by Jacob1Tm** [comment]
same issue here 
```
import lutris
lutris.__file__
```
returns `'/usr/lib/python3.12/site-packages/lutris/__init__.py'`
running lutris with `python /usr/bin/lutris` seems to work correctly though

**Comment by strycore** [comment]
> running lutris with python /usr/bin/lutris seems to work correctly though

That means your python install is likely broken

**Comment by Jacob1Tm** [comment]
> > running lutris with python /usr/bin/lutris seems to work correctly though
> 
> That means your python install is likely broken

Well i found out why now, brew had it's own python which messed up everything

**Comment by strycore** [comment]
brew, one more thing to add to the list of things that can possibly mess with a Lutris install. 

One day I'll write a script called `why-doesnt-lutris-run.sh` that will detect all those possible source of problems.

**Comment by strycore** [comment]
@CharlotteCross1998 did you manage to run Lutris?

**Comment by CharlotteCross1998** [comment]
> @CharlotteCross1998 did you manage to run Lutris?

I've re-updated to the latest version and it's working now, yes.
