### ISSUE TITLE
Feature Request: Import local .scummvmrc

### ISSUE THREAD

**Issue by mbirth** [lutris/lutris#546]
It would be nice if Lutris could import/use an existing `.scummvmrc` so we don't have to define the games twice. All necessary information is already in that file, the only thing Lutris adds is the (Lutris-)game id.

Bonus points if the configuration is synchronised back to the `.scummvmrc` so that changes made (or games added) in Lutris show up in ScummVM, too.

**Comment by strycore** [comment]
We had this feature at some point in Lutris but it got removed. We might consider putting it back.

**Comment by strycore** [comment]
Stuff left to do for 0.4.10

* Use common installer_slug for all games imported via this method
* Remove games from lutris if they use that installer_slug and are not in scummvm.ini anymore
