### ISSUE TITLE
Trying to save game preferences causes lutris to throw an exception and fail to save

### ISSUE THREAD

**Issue by RodoMa92** [lutris/lutris#5460]
It seems that lutris tries to extract a game icon from the set executable and it will except out if the executable doesn't have any icon contained within the PE. This error is shown on save:

```
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1244, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 67, in get_group_icons
    rt_base_dir = self.find_resource_base("RT_GROUP_ICON")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 31, in find_resource_base
    rt_base_idx = [entry.id for entry in self.pe.DIRECTORY_ENTRY_RESOURCE.entries].index(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_RESOURCE'. Did you mean: 'DIRECTORY_ENTRY_DEBUG'?
```

I guess that one fix should be to check this before trying to extract a non existent resource from the executable itself.

**Comment by danieljohnson2** [comment]
I've gone over this, and I think you are right. ``pefile`` has one janky API on it to just leave the attribute off in this case, but that's what it does. I've also fixed some bugs around it so if it finds no icon it should just fail to generate the game icon and not crash.

You can test this by downloading [the master branch](https://github.com/lutris/lutris); there is no need to install it, just run the ``bin/lutris`` script within and see if you can save your game.

In my testing this ``pefile`` module was quite slow, so give it a minute before you decide it's frozen forever.
