### ISSUE TITLE
Ubisoft connect, broken download window

### ISSUE THREAD

**Issue by Loganavter** [lutris/lutris#5461]
When you try to install any purchased game, such a transparent window pops up. I poked her in all places, but she turned out to be susceptible only to pressing the cross on the top-right to close the window. How is it possible to fix it?
https://ibb.co/598n7jY
OS Endeavouros, DE Enlightenment, x11, Lutris from Pacman.

**Comment by legluondunet** [comment]
I can not reproduce your issue.
First verify you have all wine needed dependencies installed, follow this guide:
https://github.com/lutris/docs/blob/master/WineDependencies.md
Then, to obtain support for game install, do not use Github but our Discord or Lutris forum.
