### ISSUE TITLE
Lutris ubisoft game not working in gamemode on bazzite (steamos like)

### ISSUE THREAD

**Issue by herbalizer404** [lutris/lutris#5464]
Hey guys,

I just installed avatar on my bazzite setup, both working "well" with bottles and lutris:

With Bottles I'm adding Ubisoft connect then install the game, I can only play from bottles directly, from Steam shortcut not working at all from desktop or gamemode.

From lutris I succeed to add the steam shortcut and game is working from desktop Steam.

My main issue is that with lutris, this Steam shortcut only works in desktop mode but not on "console" gamemode which I'm using in my living room. Do you guys have any suggestions to make it work?

**Comment by strycore** [comment]
Are you using Proton to run the game? We are working on a similar issue on SteamOS where games run on desktop mode but not game mode: https://github.com/Open-Wine-Components/umu-launcher/issues/92

This seems specific to Proton but I've managed to reproduce this issue with Wine-GE as well. I was experiencing some crashes on 9 years of shadows and I tried switching to Proton to see if it would fix the crashes. It didn't so I reverted back to Wine-GE. After reverting to Wine-GE, I was no longer able to run this game from game mode.

If you didn't switch to Proton at any point then this is a bit more unexpected but I'm still pretty sure both issues would still be related.

**Comment by herbalizer404** [comment]
I'm running wine-ge-8-26 I also tried by using proton-ge and experimental, it starts but have strange colors on gamemode. I was suspecting ubisoft overlay to create some troubles but it doesnt seem to  change anything after trying to removing it

**Comment by strycore** [comment]
So you're saying it doesn't launch with Wine-GE but it does with Proton-GE? That is something I really did not expect. 

For the strange colors, would that be related to HDR? You can try disabling HDR in the game mode settings and see if that makes a difference. Also, my monitors weird things with HDR where I have 2 modes HDR, and Cinema HDR. Cinema HDR works without issue but if I use HDR, it will show corrupted colors until I do a HDR > Cinema HDR > HDR. Maybe you have something similar going on.

**Comment by herbalizer404** [comment]
> So you're saying it doesn't launch with Wine-GE but it does with Proton-GE? That is something I really did not expect.

Yes really weird, game also "shaking" when moving, not really usable with proton but it starts anyway.

**Comment by strycore** [comment]
Is this the kind of color corruption you're seeing?
![20240504_134540](https://github.com/lutris/lutris/assets/280336/013d7c9f-9ab9-4245-b632-f42634f71f4a)

**Comment by herbalizer404** [comment]
Yes it's king of blueish, looks like hdr issue, you're right.

**Comment by herbalizer404** [comment]
Finally working fine with "ge-proton (latest)" selected in lutris game config and ubisoft overlay disabled in launcher. Thanks for helping.
