### ISSUE TITLE
Lutris shows hidden games in Recents

### ISSUE THREAD

**Issue by laribA** [lutris/lutris#5472]
Steps to reproduce:
- Add a game.
- Hide the game.
- Click the "Recent" tab.

Expected behavior: The hidden game is not shown in the Recent tab.
Actual behavior: The hidden game is shown in the Recent tab.
Lutris version: lutris-0.5.17

**Comment by danieljohnson2** [comment]
Looks like a regression from 0.5.16; I'll fix that for the next release.

**Comment by laribA** [comment]
Just to note: hidden games are also shown in the Missing tab.

**Comment by danieljohnson2** [comment]
I'm inclined to think that's perhaps a good thing; even if it's hidden, if its missing it's broken should probably be fixed or removed. Maybe?

**Comment by strycore** [comment]
Trying to pass bugs as features I see :smirk:

**Comment by laribA** [comment]
> I'm inclined to think that's perhaps a good thing; even if it's hidden, if its missing it's broken should probably be fixed or removed. Maybe?

I mean, all of the missing games have a big "Missing" label on them, so theoretically you could still see them even if they were in Hidden, right?

**Comment by danieljohnson2** [comment]
You'd be surprised how often I get away with that!

Anyway, now I look into it it's more buggy that that- the search bar at the top of the window does not work on the Missing view. 

I'll fix that, and that will hide hidden games too.
