### ISSUE TITLE
Trying to install Battle net says FileNotFoundError(2, 'No such file or directory)

### ISSUE THREAD

**Issue by NichtSylph** [lutris/lutris#5473]
Hello, I'm pretty new to linux and I'm trying to download battlenet to play starcraft, for some reason it gives that error of there not being such a directory, I made the directory manually and even so the issue still persisted, it tries to install it on the folder and then it deletes the folder and gives that error.

**Comment by strycore** [comment]
Please ask for support on the Discord, or the forums. You're not posting in the correct place.
