### ISSUE TITLE
Enable launching winecfg and winetricks for a prefix

### ISSUE THREAD

**Issue by darealshinji** [lutris/lutris#5486]
### Bug description

I have the Epic Games launcher installed through Lutris. First I had issues because one of the games required Visual C++ Runtime. I couldn't figure out how to start winetricks from within Lutris so I had to manually launch winetricks from console with the correct wineprefix set.

Then the Epic launcher complained about requiring Windows 10 or later, but I cannot launch winecfg from Lutris so I had to manually look for the winecfg from the installed version of wine and set the version to Windows 10.

I wish I could just right click on the Epic Launcher in Lutris and select winecfg or winetricks there.

Wine version is wine-ge-8-26-x86_64, Lutris is 0.5.17.

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

I've expected it to be easier to install missing runtimes or configure the wine prefix.

### Log output

```shell
$ lutris -d
2024-05-26 20:40:34,327: Command 'fluidsynth' not found on your system
2024-05-26 20:40:34,905: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.04 Noble Numbat
Arch: x86_64
Kernel: 6.8.0-31-generic
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 31.2 GB
Swap: 0.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 535.171.04
OpenGL Core: 4.6.0 NVIDIA 535.171.04
OpenGL ES: OpenGL ES 3.2 NVIDIA 535.171.04
Vulkan Version: 1.3.275
Vulkan Drivers: NVIDIA GeForce RTX 2060 (1.3.242)
```

**Comment by danieljohnson2** [comment]
That's funny, I can do those things. Perhaps you didn't find the right menu?

Click on your game then look at the panel at the bottom. Like this:

![image](https://github.com/lutris/lutris/assets/6507403/59d5b1d0-52e3-4bf9-9a7a-66fd0e9afc68)

**Comment by darealshinji** [comment]
Thanks. I really didn't see this.
