### ISSUE TITLE
Improve XDG entries import

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#549]
* Add an option to turn the auto-import completely off.
* If a game gets deleted, it shouldn't be re-added at next launch
* Create a dialog to launch this import manually. This dialog can also be used for Steam and ScummVM. Each entry should have a button to manually run the importer and a checkbox to auto-import games at startup.

**Comment by gapmeister11** [comment]
Lutris definitely needs an option to change auto-import.

**Comment by strycore** [comment]
Done
