### ISSUE TITLE
Crash on app launch - Fedora 40 Workstation

### ISSUE THREAD

**Issue by ZaraPhu** [lutris/lutris#5492]
### Bug description

The bug started today, after restarting my system installing the newest updates for Fedora and repartitioning my drives to incorporate some unallocated space into my Fedora filesystem. Sometimes, the Lutris app crashes when launches.. Other times during the same login session, it works as expected. 

### How to Reproduce

1. Launch the Lutris app from Fedora's quick search feature or from the Fedora tool bar.
2. Wait a few seconds.
3. Fedora's Problem Reporting app displays a notification that Lutris has crashed.
4. Lutris app does not open.

### Expected behavior

To launch without crashing.

### Log output

```shell
2024-05-30 06:12:12,111: Command 'vulkaninfo' not found on your system
2024-05-30 06:12:12,115: Command 'fluidsynth' not found on your system
INFO     2024-05-30 06:12:14,211 [application.do_command_line:479]:Starting Lutris 0.5.17
DEBUG    2024-05-30 06:12:14,222 [system._execute:109]:Executing lspci
ERROR    2024-05-30 06:12:17,314 [system._execute:136]:Command ['lspci'] after 3 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/gui/application.py", line 483, in do_command_line
    run_all_checks()
  File "/usr/lib/python3.12/site-packages/lutris/startup.py", line 118, in run_all_checks
    gpu = GPU(card)
          ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/graphics/gpu.py", line 80, in __init__
    self.name = self.get_lspci_name()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/graphics/gpu.py", line 156, in get_lspci_name
    for pci_id, device_desc in [
        ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
INFO     2024-05-30 06:12:17,439 [application.do_shutdown:1051]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Fedora Linux 40 Workstation Edition
Arch: x86_64
Kernel: 6.8.10-300.fc40.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 15.5 GB
Swap: 8.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.8
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.8
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.8
Vulkan Version: 1.3.280
Vulkan Drivers: Intel(R) UHD Graphics 620 (KBL GT2) (1.3.274)
```

**Comment by strycore** [comment]
can you also post the output of lspci since that's where the crash is coming from?

**Comment by strycore** [comment]
also make sure you have vulkaninfo installed, that might help you avoid using lspci

**Comment by ZaraPhu** [comment]
I anaged to replicate the crash again, and ran lspci in the terminal to see what the issue could be.

This was the output:
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 08)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.6 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #7 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC/eSPI Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (4) I219-V (rev 21)
03:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
04:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:01.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:02.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
06:00.0 System peripheral: Intel Corporation JHL6240 Thunderbolt 3 NHI (Low Power) [Alpine Ridge LP 2016] (rev 01)
3c:00.0 USB controller: Intel Corporation JHL6240 Thunderbolt 3 USB 3.1 Controller (Low Power) [Alpine Ridge LP 2016] (rev 01)

**Comment by danieljohnson2** [comment]
Well, I put that output through the code and it was fine. I think you must sometimes be getting *different* ``lspci`` output.

The specific error you are getting seems to indicate that there is a blank line in the output of ``lspci``, but I do not see one.

What I'll do is add some checks so that blank lines are skipped; this should allow us to find the video card in there if it's not been mangled. Hopefully this will work, though I'd feel better if I could see the problem in your ``lspci`` output.

Please download [the master branch](https://github.com/lutris/lutris) with this fix and run the ``bin/lutris`` script within- no need to install. Run it a few times and see if it will still crash on you- if I am right, it will not.

**Comment by Alan1CC** [comment]
I have the same issue myself on a different operating system.

Here is my `lspci` output:
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 08)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:16.3 Serial controller: Intel Corporation Sunrise Point-LP Active Management Technology - SOL (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.6 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #7 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1d.2 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #11 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC/eSPI Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (4) I219-LM (rev 21)
03:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
04:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:01.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
05:02.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)
06:00.0 System peripheral: Intel Corporation JHL6240 Thunderbolt 3 NHI (Low Power) [Alpine Ridge LP 2016] (rev 01)
3c:00.0 USB controller: Intel Corporation JHL6240 Thunderbolt 3 USB 3.1 Controller (Low Power) [Alpine Ridge LP 2016] (rev 01)
3d:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
```

**Comment by strycore** [comment]
> I have the same issue myself on a different operating system.

If you wish for your different operating system to remain secret, you'll have to wait until the next release and see if the fix works.

**Comment by danieljohnson2** [comment]
Well, @Alan1CC could *secretly* download the master branch (as above) try it. No one will ever know his dark secret!

**Comment by Alan1CC** [comment]
Hehe, excuse me. I just wanted to make a point that this problem is not isolated to Fedora.
I use Arch and the repository already has a build of the latest version of the main branch. I just have to execute it a few times to get it running. It's like starting up a lawnmower.

**Comment by danieljohnson2** [comment]
Hmm. Well, the ``lspci`` output you posted seems to work fine. But I wonder if ``lspci`` produces different results at different times?

@Alan1CC, can you run ``lspci`` several times in a row and let us know if the result ever looks different?

**Comment by Alan1CC** [comment]
Did so 10 times in a row and they don't seem different at all compared to each other.
What I did was write the output to txt files and compare them visually in an IDE with tabs (that being codium).
If you'd like me to use a different method to compare them feel free to guide me.

**Comment by danieljohnson2** [comment]
I guess it's not that ``lspci`` is doing something funny. But that makes me thing your iussue is not @ZaraPhu's issue. I'd like to see a debug-log for this failure; I bet it is different.

Run ``lutris -d`` and post the terminal spam here. After editing out your *dark secrets* of course. I mostly want to see the traceback.

**Comment by strycore** [comment]
If vulkaninfo  is available, lspci should not be used.
