### ISSUE TITLE
Wine Steam: No font?

### ISSUE THREAD

**Issue by scottviger** [lutris/lutris#550]
I installed a few windows steam game with Lutris but i had no font!
![capture d ecran_2017-03-29_20-39-57](https://cloud.githubusercontent.com/assets/22118081/24482531/ea30a5dc-14bf-11e7-96b3-f429b7fb8fd8.png)
Xubuntu 16.04

**Comment by strycore** [comment]
Are you using a super old version of Wine? This shouldn't happen anymore!

**Comment by scottviger** [comment]
Solve thanks!

**Comment by strycore** [comment]
😮 but … how did you fix it?

**Comment by scottviger** [comment]
I updated wine with the new wine version selector you added.
A bit buggy but it works!
