### ISSUE TITLE
Using wrong wine version when adding games

### ISSUE THREAD

**Issue by rhoot** [lutris/lutris#5505]
### Bug description

When adding a game from a local lutris script, it may attempt to use a weird wine version that you may or may not have installed, ignoring the configured default wine version. In my case I have `wine-ge-8-26` set as the default runner, but lutris was trying to use `lutris-GE-Proton7-35-x86_64` which I no longer had installed and that it was unable to download. I could not find this set anywhere in the UI.

Eventually I found that I had a file at `~/.config/lutris/runners/wine.yml` that contained:

```yml
system: {}
wine:
  version: lutris-GE-Proton7-35-x86_64
```

After closing lutris, deleting that file, and then trying again, it no longer tried to use that wine version.

This is worsened a bit by the fact that installing from a local script doesn't let you select the wine version before installing, which could cause the install to fail if the wine version is old enough (as it did for me, and why I uninstalled that wine version to begin with).

### How to Reproduce

1. Set `wine.version` to some old or non-existing version in `~/.config/lutris/runners/wine.yml`
2. Attempt to install something from a local lutris script
3. The install fails trying to download that wine version, ignoring the default wine version configured in the UI

### Expected behavior

That it would use the configured default wine version

### Log output

```shell
INFO     2024-06-05 22:57:45,192 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-05 22:57:45,265 [startup.run_all_checks:120]:AMD Radeon RX 6900 XT (1002:73bf 148c:2408 amdgpu) Driver 24.1.0
INFO     2024-06-05 22:57:46,119 [startup.run_all_checks:120]:NVIDIA GeForce RTX 2080 Ti (10de:1e07 1043:866a nvidia) Driver 550.78
ERROR    2024-06-05 22:57:46,120 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2024-06-05 22:57:46,920 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-05 22:57:46,922 [xrandr._get_vidmodes:18]:Retrieving 65 video modes from XrandR
DEBUG    2024-06-05 22:57:46,969 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-05 22:57:47,001 [api.check_stale_runtime_versions:52]:Modified at ons  5 jun 2024 22:17:12, will update after tor  6 jun 2024 04:17:12
DEBUG    2024-06-05 22:57:47,008 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-05 22:57:54,443 [application.show_window:394]:Showing window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x761430cfad00 (LutrisWindow at 0x58de7012b630)>}
DEBUG    2024-06-05 22:58:01,765 [__init__.read_script:24]:Loading script(s) from /home/johan/Downloads/dawntrail-benchmark-lutris.yaml
DEBUG    2024-06-05 22:58:01,776 [application.show_window:394]:Showing window InstallerWindowfinal-fantasy-xiv-dawntrail-benchmark
DEBUG    2024-06-05 22:58:01,776 [application.on_app_window_destroyed:419]:Removed window AddGamesWindow{'parent': <lutriswindow.LutrisWindow object at 0x761430cfad00 (LutrisWindow at 0x58de7012b630)>}
DEBUG    2024-06-05 22:58:02,775 [xrandr._get_vidmodes:18]:Retrieving 65 video modes from XrandR
INFO     2024-06-05 22:58:06,042 [interpreter.get_runners_to_install:255]:Runner <lutris.runners.wine.wine object at 0x761430dc7a40> needs to be installed
DEBUG    2024-06-05 22:58:06,042 [interpreter.install_runner:274]:Installing wine
DEBUG    2024-06-05 22:58:06,049 [runner.install:468]:Installing wine (version=lutris-GE-Proton7-35-x86_64, callback=<function ScriptInterpreter.install_runner.<locals>.install_more_runners at 0x761430da9bc0>)
DEBUG    2024-06-05 22:58:06,049 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2024-06-05 22:58:06,335 [interpreter.install_runner:282]:Failed to retrieve wine (lutris-GE-Proton7-35-x86_64) information
ERROR    2024-06-05 22:58:06,335 [errors.__init__:19]:Failed to retrieve wine (lutris-GE-Proton7-35-x86_64) information
ERROR    2024-06-05 22:58:06,335 [exception_backstops.error_wrapper:110]:Error handling idle function: Failed to retrieve wine (lutris-GE-Proton7-35-x86_64) information
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(
  File "/usr/lib/python3.12/site-packages/lutris/runners/runner.py", line 480, in install
    raise RunnerInstallationError(_("Failed to retrieve {} ({}) information").format(self.name, version))
lutris.runners.RunnerInstallationError: Failed to retrieve wine (lutris-GE-Proton7-35-x86_64) information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/installerwindow.py", line 442, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/usr/lib/python3.12/site-packages/lutris/installer/interpreter.py", line 283, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: Failed to retrieve wine (lutris-GE-Proton7-35-x86_64) information
WARNING  2024-06-05 22:58:12,798 [system.delete_folder:383]:Non existent path: /home/johan/.cache/lutris/installer/final-fantasy-xiv-dawntrail-benchmark
DEBUG    2024-06-05 22:58:12,799 [application.on_app_window_destroyed:419]:Removed window InstallerWindowfinal-fantasy-xiv-dawntrail-benchmark
INFO     2024-06-05 22:58:13,338 [application.do_shutdown:1051]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.9.3-lqx1-1-lqx
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5950X 16-Core Processor
Physical cores: 16
Logical cores: 32
[Memory]
RAM: 31.3 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.9.3-lqx1-1-lqx)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.0-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.0-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.0-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: NVIDIA GeForce RTX 2080 Ti (1.3.277), AMD Radeon RX 6900 XT (RADV NAVI21) (1.3.278)
```

**Comment by danieljohnson2** [comment]
I don't understand what the bug is here; the script requires a Wine version that we can't obtain, so you get an error, right? 

Is the issue that the script *should not* specify a Wine version?

**Comment by rhoot** [comment]
It wasn't a script that required a certain Wine version. It was a random file on my disk that specified it, unrelated to the script (`~/.config/lutris/runners/wine.yml`). Presumably it's a config file from some old lutris version.

That config option also doesn't show up in the UI anywhere, but is still respected. So the only way to fix this issue was to search through my config files (in `.config`) for any file that was containing the wine version it was trying to use, and manually delete it.

**Comment by danieljohnson2** [comment]
OK, that config option does appear in the UI, or it ought to. That file is the runner configuration. You can get to it via one of the two icons next to "Wine" in the sidebar. It's the 'Wine version' at the top.

If you aren't seeing it, can you post a screenshot of the Wine config dialog in Lutris?

**Comment by rhoot** [comment]
Oh, it seems you are right. Changing that option does update that file. The problem seems to be if the option in the file has a value that doesn't exist in lutris (e.g an old version), it is _not_ reflected in the UI but is still used by lutris:

![image](https://github.com/user-attachments/assets/a01ed0c5-1f1b-4cf2-81f2-e2c45bee4600)

If I change the value in the drop down to something else and click `Save` it does update that file. So I guess the bug is just that it uses that configured version without validation, which becomes a problem if it's set to an old enough runner that the runner no longer exists.

**Comment by danieljohnson2** [comment]
Oh, I see! Yes, that's misleading.

I'll alter it so the drop-down lists the current value, even if it is not valid, but with an "(invalid)" suffix, to make it clearer that you need to change this.

You can download [the master branch here](https://github.com/lutris/lutris) to test this, if you wish. No need to install, just run the ``bin/lutris`` script within and give it a try.
