### ISSUE TITLE
'%AppData%' returned empty string

### ISSUE THREAD

**Issue by rdlmda** [lutris/lutris#5507]
### Bug description

Can't run any wine game (or even source installer): command exited with code 256

#### Scenario 1) Try to install the Lutris EA launcher

1. Start Lutris
2. Click Sources -> EA App -> Connect
3. Click OK for "This service requires a game launcher. The following steps will install it.
Once the client is installed, you can login to EA App."
4. Click "install" on `wine: Standard`
![image](https://github.com/lutris/lutris/assets/4602525/043b5cac-c92a-4680-b150-e147e4e8a5e3)
5. Proceed with default options
![image](https://github.com/lutris/lutris/assets/4602525/a795287b-b190-4cc0-97bf-84fc04f783b7)
6. Wait a long while (45+ seconds) on this screen
![image](https://github.com/lutris/lutris/assets/4602525/f16a184a-e321-46b3-a754-e1cd80cd6a80)

##### Log output:

https://pastebin.com/YWMXSHJV

#### Scenario 2) Try to install a standalone wine game (Genshin Impact)
1. Go to [the game page on lutris.net](https://lutris.net/games/genshin-impact/)
4. Click on [install](lutris:genshin-impact-standard)
8. Click "next" and proceed normally

This is the install script on the site: https://pastebin.com/RGBeC51R

### Expected behavior

Install Genshin Impact

##### Log output

https://pastebin.com/UMeHBbw2

#### Scenario 3) Try to install a wine-based game from the Humble Bundle source

```
Started initial process 72067 from /home/ruda/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/ruda/.cache/lutris-installers/7-grand-steps-what-ancients-begat/humblegame/7grandsteps-windows-1.0.0.6-setup.exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: NO
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Linux Mint 21.3 Virginia
Arch: x86_64
Kernel: 5.15.0-107-generic
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Physical cores: 2
Logical cores: 4
[Memory]
RAM: 19.4 GB
Swap: 32.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL Core: 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL ES: OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2
Vulkan Version: 1.3.204
Vulkan Drivers: Intel(R) HD Graphics 620 (KBL GT2) (1.3.255), NVIDIA GeForce 930MX (1.3.242)
```

**Comment by danieljohnson2** [comment]
I've seen that empty AppData thing before, and I don't know what causes it, but it never seems to be the root cause. This seems like another error 256 thing. Maybe EA App is just made of corrugated evil. Can you install another, non-EA game?

**Comment by rdlmda** [comment]
In the process of "refactoring" this issue I'm not encountering the error 256 or empty AppData issues anymore, but now it seems to hang after downloading a lot of internal Wine stuff (more precisely on the line "`Started initial process 35964 from /home/ruda/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/ruda/.cache/lutris-installers/ea-app/setup/EAappInstaller.exe EAX_LAUNCH_CLIENT=0`" . I will tinker a bit to update (or hopefully close as "can't reproduce")!

**Comment by rdlmda** [comment]
Here's the log where the install seems to hang now: https://pastebin.com/XE6yFvmb

I'll test more and maybe open a different issue if it's the case

**Comment by danieljohnson2** [comment]
Seems like the installer itself is hanging.

But that's one complicated install. I'd like to know if it's just EA App, or if Wine works for something easier.

**Comment by rdlmda** [comment]
What is the most basic, barebones, lightweight, legally free obtainable game (or executable) I can use to manually test wine-in-lutris? How do I obtain it?

**Comment by danieljohnson2** [comment]
Hmm. I'm not sure; you probably want something with a proper installer- that will integrate far better with Lutris. But I've been looking and all the free stuff seems to be just be shipped as a .zip with an .exe in there.

If you want to try that sort of thing, you might go for [Aleph One](https://alephone.lhowon.org/) which is a port of an old Macintosh FPS for various platforms, including Windows. That's about 40 MB.

Download the Windows version of one of the Marathon games, Unzip it, and add it as a locally installed game (use the [+] button in the corner).

Do not forget to specify a Wine prefix directory; when you start the game this should be initialized for you- the game does not need to be inside of it. You do not want to use ``~/.wine`` for this.

**Comment by rdlmda** [comment]
So, for anyone reading this, the way I managed to solve this error was... by installing wine locally. (Maybe it could be more clearly stated it's sort-of a hard(ish) requirement for wine games?)

**Comment by rdlmda** [comment]
Yes, I did, when tinkering with config options, that's actually what made me install Wine locally. I don't recall it showing up when trying to install new games using the default scenario (I could be wrong, tho). I'll try again on a new install and see what other places I missed this info +_+'

**Comment by danieljohnson2** [comment]
Well, the idea is that you'll find it when troubleshooting, and you can't hide it and forget it (this was a problem previously) but it won't block you from the game.

Right now this warning shows in the config dialog and the log; I think that's all.

Might be good to have a warning when installing a Wine game too, but there are many ways to do that. What's the "default" scenario for you?
