### ISSUE TITLE
org.gnome.Platform version 46

### ISSUE THREAD

**Issue by fxzxmicah** [lutris/lutris#5508]
Please update the dependency of flatpak to org.gnome.Platform version 46.

**Comment by strycore** [comment]
This is the wrong repo to report this and this is not a priority. There is nothing in the Gnome Runtime 46 that will improve how lutris works.

**Comment by fxzxmicah** [comment]
> There is nothing in the Gnome Runtime 46 that will improve how lutris works.

Keep up to date and use less hard disk space. Because it is the only one in my computer still using version 45, which leads to a dependent consumption of 1G space.

**Comment by strycore** [comment]
Right, but it just came out and all the other Flatpaks have to upgrade as well before Gnome Runtime 45 can be removed.  I think this can wait until we make a new lutris release (unless we're taking really long to make it, in which case, we can push an update on Flathub)

**Comment by fxzxmicah** [comment]
> all the other Flatpaks have to upgrade

On my computer, this is done, lutris is the only one left. But there's no hurry, just a reminder.

**Comment by strycore** [comment]
We're about to make a new release and it will be using Runtime 47 (already available in Flathub  Beta)
