### ISSUE TITLE
ERROR    2017-03-30 21:25:16,667 [system]:No file /usr/bin/winecfg64

### ISSUE THREAD

**Issue by eNTi** [lutris/lutris#551]
I was adding a wine game to the list and used right-click -> wine configuration. The game is installed in a custom 64bit WINEPREFIX. All the while I was configuring (and afterwards) the console was spammed by this message? I've never even heard of winecfg64. Is that a thing?

**Comment by strycore** [comment]
nope, that shouldn't be winecfg64, I'll look into that, there is a bug with that
