### ISSUE TITLE
"No such file" User.reg (file exists) after upgrading Ubuntu. Help.

### ISSUE THREAD

**Issue by Mugsy323** [lutris/lutris#5513]
### Bug description

After upgrading Ubuntu from 23.04 to 24.04 LTS, every game now gives me the same error when I try to launch it:

![Screenshot from 2024-06-09 15-19-36](https://github.com/lutris/lutris/assets/33783094/61e6344e-b5c4-4dec-bc16-380d2d96248f)

The file is right where it's supposed to be:

![Screenshot from 2024-06-09 15-21-45](https://github.com/lutris/lutris/assets/33783094/dd0a70a7-65cb-454c-b685-37251c32e00c)

I can open & read the file. It is not corrupt.

### How to Reproduce

(I assume) Upgrade Ubuntu from 23.04 to 24.04 and accept all defaults. Replace any (outdated) existing configurations with package defaults.

I had to reinstall/upgrade Wine to 9.10 just to get it working again.

### Expected behavior

Run the program.

### Log output

```shell
(all "lutris -d" does from the terminal is launch Lutris.
```

### System Information

```shell
[System]
OS:              Ubuntu 24.04 Noble Numbat
Arch:            x86_64
Kernel:          6.8.0-35-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            1.5 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 970/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 550.67
OpenGL Core:     4.6.0 NVIDIA 550.67
OpenGL ES:       OpenGL ES 3.2 NVIDIA 550.67
Vulkan Version:  1.3.275
Vulkan Drivers:  NVIDIA GeForce GTX 970 (1.3.277)
```

**Comment by danieljohnson2** [comment]
``lutris -d`` might also tell us what version of Lutris you have.

It looks like you are using the system Wine, and it was borked, so when you upgraded to Wine 9, that fixed the problem with it.

But I would suggest trying to use a Lutris-supplied Wine version instead. You may need to download one using the icons on the sidebar next to "Wine", and you may need to configure a game to use it to test this.

**Comment by Mugsy323** [comment]
Thx for the reply. I'm using v0.5.14 of Lutris.

I am using the latest version of Wine 9.10 (as noted above) downloaded directly from WineHQ.org.

Here are the Wine versions Lutris reports as being already installed:

![Screenshot from 2024-06-09 16-11-49](https://github.com/lutris/lutris/assets/33783094/7c9644c8-980e-4e1d-8bea-553d838e6221)

**Comment by strycore** [comment]
> I'm using v0.5.14 of Lutris.

Lutris 0.5.14 is no longer suppoted.

**Comment by danieljohnson2** [comment]
Ubuntu never updates Lutris promptly. Try the latest version; you can [download the deb here](https://github.com/lutris/lutris/releases/tag/v0.5.17).

You can't install it by double clicking (on a default Ubuntu install); that will try to install the repo's version which you already have.

This command like should do it:
```bash
sudo apt install /path/to/deb-file.deb
```
It must be a path not a filename, irritatingly.

**Comment by Mugsy323** [comment]
That worked (0.5.17).

Thx.

**Comment by danieljohnson2** [comment]
Has this resolved the issue? If so, you should close this item.
