### ISSUE TITLE
Minecraft can't launch from lutris

### ISSUE THREAD

**Issue by Technowix** [lutris/lutris#552]
Hellow.
I can't launch minecraft from lutris, the pre-launcher finish loading everything, and poof, crash.
I opt-in the "launch in terminal' to see what happen, and got this : 
```Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma
Got reply in: 327ms
No update found.
Reversing LZMA on /home/technowix/.minecraft/launcher.pack.lzma to /home/technowix/.minecraft/launcher.pack
Unpacking /home/technowix/.minecraft/launcher.pack to /home/technowix/.minecraft/launcher.jar
Cleaning up /home/technowix/.minecraft/launcher.pack
Starting launcher.
java: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType
```
I'm running the one "without java wrapper", and "with java wrapper" ones dosen't work etheir.

Anyway, thanks for this wonderfull software :) !

EDIT :
It launch very well, with no error, when I run manually the command lutris use to launch the game : "java -jar "path/to/Minecraft.jar"

**Comment by strycore** [comment]
I have pushed an updated version of the Lutris runtime, it will be downloaded next time Lutris starts.
This fixes the issue with libpangoft2 on recent Linux distros.

Please re-open if you're still have issues. On my end I was able to reproduce the crash with the Minecraft launcher and the updated runtime solves it.
