### ISSUE TITLE
Lutris ignores dark GTK theme: arch, kde, wayland

### ISSUE THREAD

**Issue by SVaeth** [lutris/lutris#5520]
### Bug description

After pulling lutris, `sudo pacman -S lutris` in this case, and running lutris, The app defaults to light mode. 

GTK theme is Breeze. All other apps are dark, not sure which other apps are GTK. Toggling dark mode in preferences does not work.

System runs 
Kernel: 6.9.5-arch1-1
KDE Plasma: 6.1.0
KDE Frameworks: 6.3.0
Running in Wayland

There is a workaround: when using `GTK_THEME=Breeze lutris` it forces Breeze and lutris opens in dark mode.

Previous tickets opened and closed claim the issue is using a theme that does not support dark mode, but when using a theme that does support dark mode, the app still ignores the theme and starts in light mode. 

### How to Reproduce

1. Download lutris
2. Set GTK theme to Breeze or other dark theme
3. Open Lutris

Lutris will open in a different theme than the one set in GTK (in this case a light theme)

1. Download lutris
2. Set `GTK_THEME=Breeze` or other dark theme in terminal session (make sure theme is set to GTK theme in kde)
3. Open lutris in terminal session

Lutris will open with the appropriate theme being applied (in this case a dark theme)
If you like, toggle the dark theme setting in preferences. It will not change anything even after a restart.

### Expected behavior

By default, Lutris should open with the correct theme and not need this workaround adding `GTK_THEME` variable to the launcher. YMMV but it is easy to confirm the theme is not being applied properly for me since it is changing from light to dark themes

### Log output

```shell
lutris -d
2024-06-23 21:02:44,300: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-06-23 21:02:44,430 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-23 21:02:44,506 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3080 Ti (10de:2208 10de:1535 nvidia) Driver 550.90.07
ERROR    2024-06-23 21:02:44,506 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2024-06-23 21:02:44,626 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-23 21:02:44,628 [xrandr._get_vidmodes:18]:Retrieving 103 video modes from XrandR
DEBUG    2024-06-23 21:02:44,663 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-23 21:02:44,682 [api.check_stale_runtime_versions:52]:Modified at Sun 23 Jun 2024 07:55:51 PM , will update after Mon 24 Jun 2024 01:55:51 AM 
DEBUG    2024-06-23 21:02:44,687 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-23 21:02:45,665 [http._request:88]:POST https://lutris.net/api/users/library?since=1719190476
```

The output is the same for `GTK_THEME=Breeze lutris -d`

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.9.5-arch1-1
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900X 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 62.7 GB
Swap: 4.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.90.07
OpenGL Core: 4.6.0 NVIDIA 550.90.07
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.90.07
Vulkan Version: 1.3.279
Vulkan Drivers: NVIDIA GeForce RTX 3080 Ti (1.3.277)
```

**Comment by strycore** [comment]
There is nothing we can do on our end to fix this. We are already using the proper method to set a dark theme.

**Comment by SVaeth** [comment]
Why would Lutris not use the system's configured GTK theme without me explicitly setting it as an environment variable? Thunderbird and Firefox use GTK: why are they using the appropriate theme but Lutris isn't?

The common variable is Lutris, so it's worth investigating. Earlier issues alleged that reporters weren't using themes that supported dark mode, but Breeze is a dark theme. At least in this ticket, I have provided a workaround for the others who had this issue, but it should be something Lutris can handle if other GTK applications don't have this issue either.

**Comment by strycore** [comment]
I use KDE, Wayland and i can't stand the look of Lutris' light theme, it's disgusting. 
I the dark theme was broken in any way, I would fix it immediately. In all the environments I've tried, I've never had the dark theme fail. I've never receive  a pull request to fix the dark theme (at least recently). 

So yeah, until proven otherwise, I don't believe the issue is on Lutris side

**Comment by jackwalten** [comment]
Have you installed xdg-desktop-portal-gkt?

**Comment by metron2** [comment]
I had the same problem and eventually found this on the manjaro forums.
```
     The adw-gtk3 package is now called adw-gtk-theme which replaces the old adw-gtk-theme. I know it’s a little confusing. With that change, you may need to set Legacy Applications to Adw-gtk3-dark in the Tweaks application under Appearance. It may have been set to the now removed Adw-dark previously. … 
```

**Comment by raethkcj** [comment]
Also broken for me, can confirm setting `GTK_THEME=Breeze` from a terminal or in the .desktop's env variables fixes it, even though that's already the theme set in KDE

**Comment by AliensInc** [comment]
For me in Vanilla Arch with Awesomewm I use Arc-Dark and that is working in Lutris.
For X check that the settings in gtk3 & 4 has that font really set, cos if not there Lutris seems not to use it.

**Comment by LokeYourC3PH** [comment]
Having this issue now for Lutris on my Steam Deck, it simply does not want to work on Dark theme at all.

**Comment by Midrielen** [comment]
I have this too, with the Flatpak version (0.5.22) on KDE 6.5, X-session (OpenSUSE Tumbleweed). I've tried setting different GTK-themes and forcing dark breeze (as suggested earlier), even dark adwaita, but that does not seem to work with the Flatpak. Every other GTK-based application on my system works fine.
