### ISSUE TITLE
Request: Make a .desktop file for each instance

### ISSUE THREAD

**Issue by romulasry** [lutris/lutris#5521]
Thoughts? It would be nice if it was integrated with the desktop (gnome,kde,etc).
https://specifications.freedesktop.org/desktop-entry-spec/latest/

**Comment by strycore** [comment]
We already have the option to create a desktop shortcut. The checkbox that offers to create shortcuts on install should remember the last state is was in so if you want to create a desktop shortcut for all the games you install, you can.
