### ISSUE TITLE
xdg trash handling does not provide fallback in case trash is unavailable

### ISSUE THREAD

**Issue by benaryorg** [lutris/lutris#5523]
### Bug description

When I try to delete an old wine version I get a window saying "Lutris has encountered an error" and "The item could not be moved to the trash." and the error details "RuntimeError: The item could not be moved to the trash.". On one hand I'm actually very happy that this happens because I *do not want* anything to try and pretend to delete files just for the disk usage to pile up over time. Heck I don't have a file explorer and I don't have desktop environment, I have a window manager and that's pretty much it, and considering that [the glib documentation provides a way to disable trashing per filesystem anyway](https://docs.gtk.org/gio/vfunc.File.trash.html) I figure I'll enable that for the future just in case.

Anyway, for all intents and purposes there exists no trash on this device and glib and therefore [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/blob/49fa088e07790ffbc1d619d0cc248125a0921080/src/trash.c#L90) will rightfully report that this is not supported.

On the other hand, that means Lutris absolutely fails to delete old wine versions, and probably a lot more that I just don't get to see because I rarely delete things anyway.
To be more precise, Lutris when trying to trash something [only ever delegates to the trash portal](https://github.com/lutris/lutris/blob/98f53221f3baa6702fdb487e7d5b1a83a891601f/lutris/util/system.py#L376) with no error handling in that code, and [in the trash portal the error handling is limited to printing a message](https://github.com/lutris/lutris/blob/98f53221f3baa6702fdb487e7d5b1a83a891601f/lutris/util/portals.py#L73).

As you can see the error message doesn't actually include what went wrong, for that I have to restart my xdg-desktop-portal in verbose mode, which yields something like `XDP: Cannot trash file "…": Trashing on system internal mounts is not supported` which sounds like a reasonable enough thing.
Lutris however should probably catch that "not supported" part, or quite literally any of this and actually delete the data as I asked it to.
There is no if, there's no conditional check there, Lutris just plain refuses to let me actually delete something.

### How to Reproduce

1. install Lutris and either mount the filesystem that it stores its data on [a filesystem mounted using `x-gvfs-notrash`](https://github.com/GNOME/glib/blob/07fa7b261c4749b2edda5a95bcf7d12d224d4254/gio/glocalfile.c#L1824-L1826) or [choose a path that is on the ignore list](https://github.com/GNOME/glib/blob/07fa7b261c4749b2edda5a95bcf7d12d224d4254/gio/gunixmounts.c#L234) (note: the latter is the case for Lutris running in flatpak)
1. install a wine version
1. uninstall that wine version
1. see the error from the bug description (also attached)

### Expected behavior

The wine version should be deleted.

### Log output

```shell
2024-06-25 19:26:02,920: Command 'fluidsynth' not found on your system
INFO     2024-06-25 19:26:03,392 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-06-25 19:26:03,763 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3080 (10de:2206 1043:87b0 nvidia) Driver 550.78
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /run/build/vulkan-tools/vulkaninfo/vulkaninfo.h:676:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-06-25 19:26:03,778 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-06-25 19:26:03,778 [startup.run_all_checks:120]: (simple-framebuffer) Driver None
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DEBUG    2024-06-25 19:26:03,949 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-06-25 19:26:03,965 [xrandr._get_vidmodes:18]:Retrieving 22 video modes from XrandR
DEBUG    2024-06-25 19:26:04,055 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-06-25 19:26:04,092 [api.check_stale_runtime_versions:52]:Modified at Tue Jun 25 19:23:04 2024, will update after Wed Jun 26 01:23:04 2024
DEBUG    2024-06-25 19:26:04,126 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-06-25 19:26:09,129 [api.get_runners:170]:Retrieving runners
DEBUG    2024-06-25 19:26:09,129 [application.show_window:394]:Showing window RunnerInstallDialogwine
DEBUG    2024-06-25 19:26:13,040 [system.remove_folder:372]:Trashing folder /home/benaryorg/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-22-x86_64
^C
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.6.34
Desktop: gnome
Display Server: tty
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 3900XT 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 62.7 GB
Swap: 250.8 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.78
OpenGL Core: 4.6.0 NVIDIA 550.78
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.78
Vulkan Version: 1.3.261
Vulkan Drivers: NVIDIA GeForce RTX 3080 (1.3.277)
```

### Media (optional)

![image](https://github.com/lutris/lutris/assets/6145260/862d9417-693d-4e15-a1af-fd9dbe82f519)

**Comment by danieljohnson2** [comment]
I've thought of this- if you can't trash, just delete things like we used to do.

But I chickened out. This trashing stuff is there to protect user files- there have been cases where user's uninstalling a game managed to delete their home directory or something of that kind. We're trying hard to not have that happen anymore, no matter how bizarrely you configure your games.

I suppose it would be safe enough to fall back to deletion for things the user can't place like runners and media- we know it's safe the delete those. Just not the games. Would that be enough?

**Comment by strycore** [comment]
> just delete things like we used to do.

No.
Just tell the user to delete things manually.

**Comment by danieljohnson2** [comment]
Safety first!

I've had a look at the error handling for this, and it's a mess of callbacks.

If we were using asyncio, it would be straightforward to pass the error back to the UI and show a dialog to tell the user to delete something- but asyncio is a viral sort of thing that would ripple through Lutris. It would be a hell of a lot of change for something like this.

Using callbacks for the same thing is more effort than I care to make to handle a corner case like this.

So you will just get a message in a log, I think.

**Comment by benaryorg** [comment]
> So you will just get a message in a log, I think.

Right now you are not getting a message in any log on any major distro because not a single distro is running the xdg portals using `--verbose` (and really, they shouldn't).
Lutris doesn't log anything either, heck it doesn't even log the error, the only thing it logs in debug is that it's removing the directory (which it then doesn't), see log output above.

Considering that this currently doesn't tell you the file that should be deleted, doesn't do anything to actually remove configuration associated with the deleted item since deletion fails, and really *nothing* happens other than the user being told that it didn't work with no indication what happened this *needs* a fix.

Besides, good luck telling the user to delete the path that will be used when running Lutris inside flatpak, because that path sure as heck won't exist as-is on the host filesystem.

This is purely a Lutris issue and shoving any responsibility onto the user to manually remove something as opposed to prompting the user is going to be more difficult than giving the user a dialogue option ("cannot trash this, do you want to permanently delete it instead").

**Comment by danieljohnson2** [comment]
I see your log has no message saying the trashing failed; it should say "The item could not be moved to the trash". I see "^C" where that should be. We're missing some logging we ought to have.

The path that was being trashed *is* visible, and it is "/home/benaryorg/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-22-x86_64"
That looks legit to me.

But I realize now that you are removing a particular Wine version, not Wine itself. That is one place where the error handling is hooked up (yay!) so you get that dialog. We can do better- I'll add the directory path to the error message.

I'll beef up the logging too.

But I won't outright delete that directory. The boss says no. Too risky.
