### ISSUE TITLE
Can't launch any game runners.

### ISSUE THREAD

**Issue by GrandSepha** [lutris/lutris#553]
Any game I'm launching outside of the PPSSPP runner that is working fine, gets an output similar to this:

DEBUG    2017-04-03 20:03:08,688 [system]:Executing which steam
WARNING  2017-04-03 20:03:08,707 [winesteam]:wine is not installed
DEBUG    2017-04-03 20:03:09,495 [runtime]:Runtime steam is up to date
DEBUG    2017-04-03 20:03:09,496 [runtime]:Runtime lib32 is up to date
DEBUG    2017-04-03 20:03:09,496 [runtime]:Runtime p7zip is up to date
DEBUG    2017-04-03 20:03:09,497 [runtime]:Runtime lib64 is up to date
DEBUG    2017-04-03 20:03:09,503 [api]:Fetching game library
DEBUG    2017-04-03 20:03:12,496 [game]:Launching Vagrant Story: {'command': ['/home/GrandSepha/.local/share/lutris/runners/pcsxr/bin/pcsxr', '-cdfile', '/home/GrandSepha/ROMs/PlayStation/Vagrant Story.img', '-runcd']}
DEBUG    2017-04-03 20:03:12,497 [thread]:Command env: STEAM_RUNTIME="/home/GrandSepha/.local/share/lutris/runtime/steam" LD_PRELOAD="" SDL_VIDEO_FULLSCREEN_DISPLAY="off" LD_LIBRARY_PATH="/home/GrandSepha/.local/share/lutris/runtime/lib32:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/lib:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/usr/lib:/home/GrandSepha/.local/share/lutris/runtime/lib64:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH" 
DEBUG    2017-04-03 20:03:12,498 [thread]:Running command: "/home/GrandSepha/.local/share/lutris/runners/pcsxr/bin/pcsxr" "-cdfile" "/home/GrandSepha/ROMs/PlayStation/Vagrant Story.img" "-runcd"
DEBUG    2017-04-03 20:03:12,498 [thread]:Storing environment variable STEAM_RUNTIME to /home/GrandSepha/.local/share/lutris/runtime/steam
DEBUG    2017-04-03 20:03:12,498 [thread]:Storing environment variable LD_PRELOAD to 
DEBUG    2017-04-03 20:03:12,498 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to off
DEBUG    2017-04-03 20:03:12,498 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/GrandSepha/.local/share/lutris/runtime/lib32:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/lib:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/i386/usr/lib:/home/GrandSepha/.local/share/lutris/runtime/lib64:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/GrandSepha/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH
/home/GrandSepha/.local/share/lutris/runners/pcsxr/bin/pcsxr: /home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lib64/libatk-bridge-2.0.so.0)
/home/GrandSepha/.local/share/lutris/runners/pcsxr/bin/pcsxr: /home/GrandSepha/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lib64/libatspi.so.0)
/home/GrandSepha/.local/share/lutris/runners/pcsxr/bin/pcsxr: symbol lookup error: /lib64/libpangoft2-1.0.so.0: undefined symbol: FcWeightToOpenType
DEBUG    2017-04-03 20:03:14,000 [thread]:8703	Z	pcsxr
DEBUG    2017-04-03 20:03:14,001 [thread]:All children terminated
DEBUG    2017-04-03 20:03:15,500 [thread]:No children left in thread
DEBUG    2017-04-03 20:03:17,000 [game]:Game thread stopped
DEBUG    2017-04-03 20:03:17,001 [game]:Vagrant Story stopped at Mon, 03 Apr 2017 20:03:17
DEBUG    2017-04-03 20:03:17,136 [display]:Switching to 3840x2160+0+0 on DP-0
-> Red  1.000, Green  1.000, Blue  1.000
<- Red  1.000, Green  1.000, Blue  1.000

The status bar reads: Playing <GAME TITLE> , which almost immediately goes to "Game has quit"

**Comment by strycore** [comment]
The libpangoft2 issue has been fixed, please restart Lutris and the updated runtime will start downloading. Once you see the "Runtime updated" in the status bar, you should be able to run games without disabling the runtime.

Note that PCSX-R is deprecated in Lutris and will be removed in a future version. Please use libretro / retroarch. PCSX-R will likely not work no matter what.

Please reopen if you keep having issues.
