### ISSUE TITLE
[Feature Request] Adding Tags

### ISSUE THREAD

**Issue by Beyuum** [lutris/lutris#5530]
Excuse my language. Im using Google Translate. 

Request: Adding Tags.

Since there are already categories, these tags will complement them. The best way to explain their usefulness would be through an example:

After placing the games in categories according to the game category. FPS. RPG. Racing, etc. These tags will help users classify games within the same category, for example. games that are: 

Completed. 
Playing. 
Can't complete right now because of a problem with wine. 

Or vice versa, I put games in a completed category and put tags: horror, rogelike, and so on.

Note: 1-Maybe add colors for tags and the games border with those tags become the same colo
Like red border on the game cover
2- searching for tags in the search bar that will show all tags when typing 'tag:'

**Comment by strycore** [comment]
Tags and categories are the exact same thing.

**Comment by Beyuum** [comment]
> Tags and categories are the exact same thing.

Yes, but no.
You can't make a category inside a category right now.
As an example 
I can have RPGs category and another one for JRPGs, KRPGs, Text-based RPGs and so on.
But whith somthing like Tags. One category can include what i need when i need it. 
So i dont have to make like 30 categories and then browser them every time + lutris show all of them on the sidebar which includes many other things like runners. My accounts in different platforms and so on.
Tags will make things easier to organize and give more space in the sidebar.

**Comment by strycore** [comment]
Should we make Lutris an overly complicated piece of software that is full of concepts that I can barely understand?

**Comment by danieljohnson2** [comment]
Yes, making Lutris an overcomplicated piece of software is clearly _the best thing ever_.

But no, I don't think this feature makes a whole lot of sense.

Can we just close this?

**Comment by strycore** [comment]
We can and we should.
