### ISSUE TITLE
Error when manually changing game icon

### ISSUE THREAD

**Issue by AlexanderRevo** [lutris/lutris#5541]
### Bug description

Lutris errors out when setting an icon (I got this with an `.ico` file, an animated `.gif` and a 500x500 `.jpg` file) to a game that doesn't already have an icon - seems like it's caused by having lutris to transcode the image rather than it being specifically an `.ico` file.

A workaround: set an icon to a file that wouldn't trigger trascoding, then change it again to the desired file.

### How to Reproduce

EDIT: looks like it also happens if you reset the icon on a game that already has one. Updated repro.

1. Reset an icon on any installed game that has one and save the changes.
2. Open the game configuration for the iconless game again and try to set the game icon to an .ico file. Attached the one I've been using: [icon.zip](https://github.com/user-attachments/files/16324244/icon.zip)
3. Observe the error.

As noted in the description, this wouldn't repro if the game already has an icon set.

### Expected behavior

The icon is set successfully without an error.

### Log output

```shell
2024-07-21 13:52:28,040: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-07-21 13:52:28,143 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-07-21 13:52:28,176 [startup.run_all_checks:120]:AMD Radeon RX 7900 XTX (1002:744c 1eae:7901 amdgpu) Driver 24.1.3
DEBUG    2024-07-21 13:52:28,280 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-21 13:52:28,288 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-07-21 13:52:28,322 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-07-21 13:52:28,345 [api.check_stale_runtime_versions:52]:Modified at nie, 21 lip 2024, 08:08:19, will update after nie, 21 lip 2024, 14:08:19
DEBUG    2024-07-21 13:52:28,407 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-07-21 13:52:32,795 [application.show_window:394]:Showing window EditGameConfigDialog22
ERROR    2024-07-21 13:52:35,493 [exception_backstops.error_wrapper:110]:Error handling signal 'clicked': [Errno 2] No such file or directory: '/home/user/.local/share/icons/hicolor/128x128/apps/lutris_excessive-speed.png'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 711, in on_custom_image_select
    self.save_custom_media(image_type, image_path)
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 732, in save_custom_media
    self._save_transcoded_media_to(dest_paths[0], image_type, image_path)
  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 758, in _save_transcoded_media_to
    file_format = {".jpg": "jpeg", ".png": "png"}[get_image_file_extension(dest_path)]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/widgets/utils.py", line 52, in get_image_file_extension
    file_type = magic.from_file(path).casefold()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/magic.py", line 185, in from_file
    return m.from_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/magic.py", line 119, in from_file
    with _real_open(filename):
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/icons/hicolor/128x128/apps/lutris_excessive-speed.png'
DEBUG    2024-07-21 13:52:40,364 [application.on_app_window_destroyed:419]:Removed window EditGameConfigDialog22
INFO     2024-07-21 13:52:43,968 [application.do_shutdown:1051]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux 24.0.4 Wynsdey
Arch: x86_64
Kernel: 6.6.40-1-MANJARO
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 7950X3D 16-Core Processor
Physical cores: 16
Logical cores: 32
[Memory]
RAM: 62.5 GB
Swap: 0.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.54, 6.6.40-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3-manjaro1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3-manjaro1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3-manjaro1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.278)
```

**Comment by AlexanderRevo** [comment]
Looks like it's not just .ico files, updated the description accordingly.

**Comment by danieljohnson2** [comment]
I see it; it's buggy handling for PNGs mainly, but also the handling for setting icons when there is no icon (instead of replacing one).

This issue demonstrates that I'm the most important contributor to the Lutris project. I contribute all the bugs. Like this one.

Anyway, I've put a fix in that works for me. Please again again [download the master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. You should be able to select a custom icon now.

**Comment by AlexanderRevo** [comment]
It works, but it looks like there's a bit of a regression after those changes: now the icon comes right back after resetting it and saving the game config: Reset icon -> Save config -> Reopen config - the icon is back.

**Comment by danieljohnson2** [comment]
I tried it and the reset button worked fine; it's supposed to restore the Lutris provided icon- this may not be the Lutris.. um... weasel? otter? Whatever that little guy is.

When you reset, Lutris will try to download an icon for you at once; if that does not work it will try to get the icon from the .exe when saving.

Are you sure the icon that's coming back is really the custom icon?

**Comment by strycore** [comment]
https://en.m.wikipedia.org/wiki/Sea_otter

**Comment by AlexanderRevo** [comment]
Oh, I guess I misunderstood what it was supposed to do. I thought it was supposed to clear the game's icon and use Lutris icon instead, so I was resetting the game's default icon. I double-checked and it does indeed reset to the icon from the game's executable.
