### ISSUE TITLE
nvidia 555.58 driver issue

### ISSUE THREAD

**Issue by jhu54** [lutris/lutris#5547]
### Bug description

(OJ on discord): Since the release of nvidia 555.58 drivers a few weeks ago, we have been noticing an error with 0.5.17 (flatpak, AUR on Arch and git clone on Ubuntu) which shows the following in terminal with lutris -d:

```
WARNING: [Loader Message] Code 0 : loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /usr/lib/x86_64-linux-gnu/GL/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1
2024-07-28 02:41:37,362: NVIDIA GeForce GTX 1050 (10de:1c8d 1043:1590 nvidia) Driver 555.58.02
WARNING: [Loader Message] Code 0 : loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /usr/lib/x86_64-linux-gnu/GL/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1

jhu@GGI-Office:~/Projects/lutris/bin$ env LUTRIS_EXPERIMENTAL_FEATURES_ENABLED=1 ./lutris -d
INFO     2024-07-28 10:30:50,091 [application.do_command_line:479]:Starting Lutris 0.5.17
WARNING: [Loader Message] Code 0 : loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /usr/share/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1
INFO     2024-07-28 10:30:50,273 [startup.run_all_checks:120]:NVIDIA GeForce RTX 4070 Ti (10de:2782 10de:16e1 nvidia) Driver 555.52.04

```

On these systems, Steam and vkcube work fine. Downgrading to lutris 0.5.16 also works. It is not limited to X or Wayland.
It did not occur with the 555.42 drivers or earlier. have tested on systems with 4070ti, 3090 and 2060, all show the same issue in the logs.

If you need more info or want debug help. ping @OJ on the discord support lutris_support.

### How to Reproduce

Install 555.52 or 58 nvidia drivers
Launch lutris 0.5.17 flatpak version or AUR or git clone with lutris -d

### Expected behavior

n/a

### Log output

```shell
see above
```

### System Information

```shell
multiple systems, cpu's, distros and gpus using the 555.58 nvidia drivers
```

**Comment by danieljohnson2** [comment]
I've got the warning but never even noticed until you pointed this out; everything seems to work fine in spite of it.

Are you seeing anything actually failing here, or is it just an unsightly warning?

**Comment by danieljohnson2** [comment]
Reading [the documentation here](https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderLayerInterface.md#layer-manifest-file-version-101).

Looks to me like this is an NVidia bug in the file ``/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json`` (and also ``/usr/share/vulkan/icd.d/nvidia_icd.i686.json``). These indicate ``file_format_version`` of ``1.0.0`` but use the ``layers`` tag, which was introduced in ``1.0.1``; this is an error in the file, but so long as Vulkan uses it anyway it should be fine.

This warning seems to come out when running ``vulkaninfo --summary``; I get it when I run that from the command line.

**Comment by danieljohnson2** [comment]
I'll follow up on Discord before closing this as not-our-bug to see if anyone is having real failures.

**Comment by danieljohnson2** [comment]
After discussion on Discord, I find that many people get this warning but their games do work.

Some people are having game failures, but there is something else behind that. So I'm closing this as not-our-bug.
