### ISSUE TITLE
Debian repos packaging

### ISSUE THREAD

**Issue by Emily511511** [lutris/lutris#5554]
In the past, lutris was available in Debian repos, but it seems like it isn't available anymore.

1) Can we have a clarification as to what happened?

2) Are there any plans to put lutris back in Debian repos?

**Comment by strycore** [comment]
It seems to me the Lutris package is still in Debian, nothing has changed. 

https://packages.debian.org/search?keywords=lutris&searchon=names&suite=all&section=all

It is recommended however to use our OBS repo to ensure you have an up to date version. We do not offer support for the outdated versions downloaded from the Debian repos.
