### ISSUE TITLE
lutris not launching steam games

### ISSUE THREAD

**Issue by shinnova** [lutris/lutris#556]
Whenever I try to start one of my steam games through lutris, all that happens is that steam is started, but the game is not launched. The game does not start if steam is already open either. Any ideas as to what could be causing this issue? I would love to give lutris a go. 

Here is my terminal output from the moment steam is launched by lutris: [gist](https://gist.github.com/shinnova/070aa02c2e77d4cc39e455bf9b16bdff)

**Comment by strycore** [comment]
That's very strange, does it happen with all the Steam games you've tried?

Could you please run the command `/usr/share/lutris/bin/desktop_info.sh` and send the resulting file in a gist or pastebin?

**Comment by strycore** [comment]
After searching on Google for the error message I found things related to Optimus, do you have a laptop with a Nvidia + Intel GPU?

**Comment by shinnova** [comment]
My apologies, I should have mentioned that I do indeed have an Optimus laptop. It does indeed happen with all the steam games I've tried.

And here is the output from the command you asked me to run, hopefully it can be of use! 
[gist](https://gist.github.com/shinnova/0c97637ec9e5acdae5768a2ec107b9f5)

**Comment by strycore** [comment]
Does the games still crash when the "use primusrun" option is checked in the system options?

**Comment by shinnova** [comment]
Yes, when "use primusrun" is checked I still have the exact same issue.

**Comment by strycore** [comment]
Can you please confirm if this bug is still present after we release Lutris 0.4.15? Thanks!

**Comment by shinnova** [comment]
I'm no longer in possession of an optimus enabled laptop sadly. I'll close the issue, but if anyone else can confirm the bug is still present it should be reopened.

**Comment by tungchi** [comment]
I cannnot select "use primusrun",the option is grey and it's can not to be selected.my OperateSystem is linuxmint 18.03,and I have active NVIDIA

**Comment by strycore** [comment]
@tungchi if "use primusrun" is greyed out, it means it's not installed.

**Comment by tungchi** [comment]
@strycore I have installed NVIDIA ,or do you mean that I need to install "primusrun"?I can't find out how I can install "primusrun"

**Comment by strycore** [comment]
@tungchi I'm not familiar with primusrun as I do not have a laptop with dual GPUs. It's part of Bumblebee, which is described here: https://wiki.archlinux.org/index.php/bumblebee#Primusrun
