### ISSUE TITLE
Amazon Games Integration is broken

### ISSUE THREAD

**Issue by Shin-Aska** [lutris/lutris#5562]
Seems like a batch of new games on twitch prime are causing problems. Specifically lots of them do not have ASIN causing an exception on this code

https://github.com/lutris/lutris/blob/7ead527a62814a3354bed2c41a79f1528efd85ea/lutris/services/amazon.py#L370

Ofcourse we could just replace this with `product.get("asin")` and an additional null check before it gets appended but that would skip the game for good. I have attach here a list of offending skus 

[offending_skus.json](https://github.com/user-attachments/files/16569337/offending_skus.json)

Perhaps we can go with a different idea? There are comments indicating we can go to a different route?

https://github.com/lutris/lutris/blob/7ead527a62814a3354bed2c41a79f1528efd85ea/lutris/services/amazon.py#L379-L382

**Comment by danieljohnson2** [comment]
Skipping the bogus games is better than crashing, but perhaps we can import them, by just not deduplicating the asin-less ones. I'll get back to you on this. I'll need your help to test this.

**Comment by danieljohnson2** [comment]
OK, I've got a branch with a fix, but with no Amazon account I can't test it. Please test this for me, @Shin-Aska!

[The branch is here](https://github.com/lutris/lutris/tree/dj/amazon_dedup); download it and run the ``bin/lutris`` script within. Reload your Amazon library. Do you get errors? Do these games (like 'STAR WARS Jedi Knight II - Jedi Outcast') now appear in the Amazon view in Lutris? Any crap in the log?

If this fix works for you, I'll merge it into the master branch.

**Comment by Shin-Aska** [comment]
Hi @danieljohnson2, the code works. The games now appear too :)

![image](https://github.com/user-attachments/assets/0eb7c418-d10d-4b3c-8852-557ce2968bed)

**Comment by danieljohnson2** [comment]
Very good; we'll have this for the next release. Thanks for helping!
