### ISSUE TITLE
Clipboard doesn't work for GOG-login popup.

### ISSUE THREAD

**Issue by 0yzmo** [lutris/lutris#5565]
### Bug description

Paste from clipboard doesn't work for GOG-login authentication popup. Password needs to be entered manually.
ctrl+v nor ctrl+shift+v nor right click+paste.

### How to Reproduce

1. Go to 'GOG' in left menu.
2. Try to paste in password.
3. Nothing is pasted.

### Expected behavior

Information from clipboard is pasted (like a already copied username or password).

### Log output

```shell
DEBUG    2024-08-13 07:23:07,714 [base.login:359]:Connecting to GOG

...no output is given when trying to paste.
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.9.3-76060903-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             94.2 GB
Swap:            20.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 555.58.02
OpenGL Core:     4.6.0 NVIDIA 555.58.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 555.58.02
Vulkan Version:  1.3.280
Vulkan Drivers:  NVIDIA GeForce RTX 2070 (1.3.278)
```

**Comment by danieljohnson2** [comment]
I just tried this and I could paste both my password and the two-factor code as well. No repro here.

I did it with the right click menu on Nobara 40. Are you on the latest Lutris, 0.5.17?

**Comment by strycore** [comment]
I've had reports like this in the past. Never managed to reproduce them, even when it was on i3 (someone made me use i3, can you believe that?)

Our copy and paste is working, if something is not, it has something to do with WebkitGtk or the window manager, not lutris.

Sorry but your princess is in another castle.
