### ISSUE TITLE
Can't add 3dmigoto because of error "14 is not in list"

### ISSUE THREAD

**Issue by claymorwan** [lutris/lutris#5570]
### Bug description

I can't add 3dmigoto to Lutris through the "Add ocally installed game" option, everytime I do I get an error saying "14 isn't in list" with this error detail :
```
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.runner.extract_icon(self.slug)

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1244, in extract_icon
    groups = extractor.get_group_icons()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 67, in get_group_icons
    rt_base_dir = self.find_resource_base("RT_GROUP_ICON")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/util/wine/extract_icon.py", line 31, in find_resource_base
    rt_base_idx = [entry.id for entry in self.pe.DIRECTORY_ENTRY_RESOURCE.entries].index(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: 14 is not in list
``` 

but any other exes works just fine

### How to Reproduce

1. Add executable like you normally would for a windows game
2. Choose any runner
3. What's as it decide to not let you

### Expected behavior

Supposed to add the executable so I can launch it

### Log output

```shell
Gtk-Message: 13:32:18.452: Failed to load module "appmenu-gtk-module"
2024-08-17 13:32:18,909: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.10.5-arch1-1
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 2600 Six-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.5 GB
Swap: 4.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 5500 XT (radeonsi, navi14, LLVM 18.1.8, DRM 3.57, 6.10.5-arch1-1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.6-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.6-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 5500 XT (RADV NAVI14) (1.3.278)
```

**Comment by danieljohnson2** [comment]
This looks like #5483 again.

This crash happens when Lutris can't decode the icon of the game from the .exe, when it finds you have no icon and tries to supply one. The master branch has handling for this so you can still add the game in the case.

[You can download it here](https://github.com/lutris/lutris); just run the ``bin/lutris`` script in there, no need to install. Try to install your game; I think it will work.

There is a workaround too- set an icon of your own for the game before saving, and that should take precedence so Lutris won't try to replace it with the icon from the .exe.

**Comment by claymorwan** [comment]
I tried with the master build but it gives me the same error. Tho it worked when using another executable and then replace it with mine

**Comment by danieljohnson2** [comment]
The master should at least give a slightly better error. Can we get a debug-log from the master for this error?

Using another .exe might well work- maybe that we can extract the icon from that .exe just fine. Once you have that icon, you'd be good even if you switch back to the original .exe.

**Comment by strycore** [comment]
I keep seeing crashes related to this useless extract_icon method. Next time I see a crash related to that,  I'm removing it entirely.

**Comment by danieljohnson2** [comment]
It should just log an error and continue now. I suspect @claymorwan may be accidentally running the 0.5.17 release instead of master; the log should clarify that.

**Comment by strycore** [comment]
Is it completely impossible for extract_icon to crash lutris now?

**Comment by danieljohnson2** [comment]
Well, no. It could take so long to read and convert a single icon that the Wayland pipe backs up. Boom.

It also only catches Exception, not BaseException, so something might get by it- though the backstop should save Lutris. If that happens you won't be able to save, but you could then set the icon manually to work around it, and not lose your changes that way.

**Comment by strycore** [comment]
Exception is broad enough to catch everything.  It's fine if we're handling that.

**Comment by strycore** [comment]
marking as fixed.
