### ISSUE TITLE
Lutris does not respect system window decorations. (0.5.17 - any)

### ISSUE THREAD

**Issue by angulion** [lutris/lutris#5572]
### Bug description

Lutris disables system titlebar in Xorg, making it behave totally different from all other applications - no shading, no "keep on all dekstops" or "keep above other windows" toggles in titlebar.

### How to Reproduce

Use Lutris in KDE or any other sane WM.

### Expected behavior

I expect Lutris to follow system decorations by default with an optional setting to have it behave badly for those that like desktops where everything functions randomly in own way if must.
Search etc. should *not* be in titlebar.
GUI consistency should be above all.

### Log output

```shell
Not dependent on logs.
```

### System Information

```shell
Opensuse Tumbleweed, Xorg.

Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: openSUSE Tumbleweed 20240716 n/a
Arch: x86_64
Kernel: 6.9.9-1-default
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: 13th Gen Intel(R) Core(TM) i9-13900K
Physical cores: 24
Logical cores: 32
[Memory]
RAM: 125.5 GB
Swap: 125.5 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.100
OpenGL Core: 4.6.0 NVIDIA 550.100
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.100
Vulkan Version: 1.3.283
Vulkan Drivers: NVIDIA GeForce RTX 3080 (1.3.277)
```

**Comment by danieljohnson2** [comment]
Consistency is a lost cause on Linux, and frankly it's pretty much a lost cause everywhere. But doubly so on Linux, where user customization is highly prized.

You'd be better asking frankly for more customization instead, I think. There's a long tradition of that on Linux, and it's a lot more doable. GNOME seems to hate it, but if we moved to a Qt based UI it would likely be more to your liking in this way.

I'd favor a good UI over a customizable one myself, but there are real arguments for Qt.

**Comment by strycore** [comment]
Troll issue.
