### ISSUE TITLE
[Errno 13] Permission denied | when adding .exe (wine)

### ISSUE THREAD

**Issue by FeyrisTan** [lutris/lutris#5574]
### Bug description

Adding any .exe running through wine results in the error.

### How to Reproduce

Add any .exe game

### Expected behavior

for it to work

### Log output

```shell
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    but signals and emission hooks will remain connected.
                   ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/gui/config/game_common.py", line 688, in on_save
    self.game.playtime = playtime

  File "/usr/lib/python3.12/site-packages/lutris/runners/wine.py", line 1260, in extract_icon
    for i in range(len(groups[0])):
    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/PIL/Image.py", line 2563, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

PermissionError: [Errno 13] Permission denied: '/usr/share/icons/hicolor/128x128/apps/lutris_60-parsecs.png'
```
```


### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: CachyOS Linux rolling n/a
Arch: x86_64
Kernel: 6.10.6-3-cachyos
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: 13th Gen Intel(R) Core(TM) i5-13600K
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 31.1 GB
Swap: 31.1 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.57, 6.10.6-3-cachyos)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.0-arch1.3
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.0-arch1.3
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.0-arch1.3
Vulkan Version: 1.3.285
Vulkan Drivers: AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.289)
```

**Comment by strycore** [comment]
Well, well, well... if it isn't our good old friend extract_icon asking to be deleted once again. 
@danieljohnson2 I guess this one has been fixed already?

**Comment by danieljohnson2** [comment]
That traceback is weird; I don't think this blew on the line ``self.game.playtime = playtime``. A complete, unaltered log would be nice.

It also looks like it's trying to write the icon to ``/usr/share/icons`` which is very odd. That path should be coming off of ``GLib.get_user_data_dir()``, and I don't think that should ever be ``/usr/share``.

But that write is indeed under the exception handler, so it should no longer block saving, in any case.

@FeyrisTan, I think that the latest Lutris code should tolerate this strange problem better than 0.5.17 does. I'd like you to try it. Please download the latest code [from here](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install! Try to add your game and tell us how it goes.

I don't think you will wind up with an icon for it, but it should install the game, I hope.

**Comment by FeyrisTan** [comment]
yes no icon but it works.

**Comment by danieljohnson2** [comment]
OK. I don't understand why it's trying to save icons in ``/usr/share``, but it should be harmless.

@strycore, if you don't like the extract-icon-on-save feature and want it gone, you only have to ask. All the cool icons are on [Lutris.net](https://lutris.net/) anyway.

**Comment by strycore** [comment]
I don't mind it being here as long as it stays unnoticed and never annoys anyone by crashing anything at all (including itself). 
This is a feature that only 5 people on earth want. Everyone else does not care and want it out of the way.

**Comment by danieljohnson2** [comment]
I believe it will, from the next release, trouble only the lovers of the Lutris sea-otter icon.
