### ISSUE TITLE
Winetricks: Powershell verbs to support Star Citizen RSI Launcher 2.0 Oct1 2024 Migration

### ISSUE THREAD

**Issue by mactan-sc** [lutris/lutris#5577]
On Oct 1, 2024 the legacy [RSI Launcher will be updating to the RSI Launcher 2.0](https://robertsspaceindustries.com/spectrum/community/SC/forum/1/thread/retiring-the-legacy-launcher). Without powershell This launcher is unable to perform multiple functions including creating game directories and verifying game files. Anticipating this, https://github.com/Winetricks/winetricks/pull/2211 has since been created merged which adds the powershell verb. 

https://lutris.net/api/runtimes indicates that lutris uses a winetricks version from October 2023, and new install seems to indicate an older file from February 2023
```
mactan@pop-os:~/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks$ flatpak run net.lutris.Lutris -v
2024-08-24 11:27:15,853: Command 'fluidsynth' not found on your system
Gtk-Message: 11:27:16.103: Failed to load module "canberra-gtk-module"
lutris-0.5.17
mactan@pop-os:~/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks$ ./winetricks --version
20230212-next - sha256sum: 2d7770aa1f49f42ad9dafb092110dbf49fa6581738f6b80488cf0d7f59b2de72

```

How frequently is this lutris's winetricks updated?

Could the winetricks available through lutris be updated to a version new enough that https://github.com/Winetricks/winetricks/pull/2211 is available to enable this game launcher to continue to function?

https://github.com/starcitizen-lug/knowledge-base/wiki#game-updates

**Comment by GloriousEggroll** [comment]
these days SC should be using proton as the wine runner, which uses umu as the backend -- which -should- contain a fairly updated version of winetricks. regardless ill update winetricks in the next proton-ge release

**Comment by mactan-sc** [comment]
lutris 5.17 with environment variables including GAMEID, STORE, and PROTONPATH set does not presently invoke game-specific protonfixes

**Comment by mactan-sc** [comment]
resolved by protonfixes https://github.com/Open-Wine-Components/umu-protonfixes/pull/116
