### ISSUE TITLE
Amazon Prime fails to show games o list after login

### ISSUE THREAD

**Issue by tackro** [lutris/lutris#5578]
### Bug description

Can´t show amazon prime gaming list of games after login

### How to Reproduce

1. Login on Amazon Prime Gaming runner
2. Bug log appears

### Expected behavior

Display games on list and install them

### Log output

```shell
Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 160, in load
    games = [AmazonGame.new_from_amazon_game(game) for game in self.get_library()]
                                                               ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/lutris/services/amazon.py", line 367, in get_library
    asin = product["asin"]
           ~~~~~~~^^^^^^^^

KeyError: 'asin'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Manjaro Linux 24.0.7 Wynsdey
Arch: x86_64
Kernel: 6.10.5-1-MANJARO
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.5 GB
Swap: 17.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 570 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.10.5-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.6-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.6-arch1.1
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 570 Series (RADV POLARIS10) (1.3.278)
```

**Comment by danieljohnson2** [comment]
This looks like #5562 again.

If so, we've got a fix in master. [Download the master branch here](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within- no need to install. I think you'll be able to reload the Amazon source with that.

**Comment by dmaglio** [comment]
> This looks like #5562 again.
> 
> If so, we've got a fix in master. [Download the master branch here](https://github.com/lutris/lutris) and run the `bin/lutris` script within- no need to install. I think you'll be able to reload the Amazon source with that.

I downloaded the master branch and run the ``bin/lutris`` script but the error is the same

```
'asin'

Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/app/lib/python3.11/site-packages/lutris/services/amazon.py", line 160, in load
    games = [AmazonGame.new_from_amazon_game(game) for game in self.get_library()]
                                                               ^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/services/amazon.py", line 367, in get_library
    asin = product["asin"]
           ~~~~~~~^^^^^^^^

KeyError: 'asin' ```

**Comment by dmaglio** [comment]
> That trace-back is from the 0.5.17 release, I think. The latest code does not have the line `asin = product["asin"]` in it anymore.
> 
> One possibility is that you ran lutris with the command `lutris` instead of `./bin/lutris` or `./lutris` or the like; if you do not use some kind of path, you'll get your system-provided Lutris no matter what your current directory is. Maybe that's what's happened here?

I run it from terminal, this is the screenshot:
![image](https://github.com/user-attachments/assets/0dbc464d-037d-47d9-8d97-ea0330ab6982)

**Comment by danieljohnson2** [comment]
How odd. I'm quite sure that line of code isn't in the master. Perhaps you were already running Lutris? Maybe you have it running in the background, with just a status icon showing?

When you run Lutris, it checks to see if it is already running, and activates that copy instead of opening a window if so. So maybe?

**Comment by dmaglio** [comment]
> How odd. I'm quite sure that line of code isn't in the master. Perhaps you were already running Lutris? Maybe you have it running in the background, with just a status icon showing?
> 
> When you run Lutris, it checks to see if it is already running, and activates that copy instead of opening a window if so. So maybe?

sorry, it was left in the bar and I didn't notice. now in fact if restarted clean, as if it were the first installation. and so now I have to use that instead of the installed one?

**Comment by danieljohnson2** [comment]
Possibly you were using the flatpak version before? That would explain it.

For this test, log into Amazon again and see if you can see your games. No need to install any games; we just want to see the game list.

**Comment by dmaglio** [comment]
> Possibly you were using the flatpak version before? That would explain it.
> 
> For this test, log into Amazon again and see if you can see your games. No need to install any games; we just want to see the game list.

Yes, i have flatpack version from GNOME Software. in master branch works. 

OT: where can i insert the parameters to add to %command%? i have to insert the prefix WINE_LARGE_ADDRESS_AWARE=0 PROTON_FORCE_LARGE_ADDRESS_AWARE=0 because i have problems in decompressing some files

**Comment by danieljohnson2** [comment]
You can add them in the configuration of the game, runner, or globally in preferences. It's in the "System options" tab.

But you should not need to do so for this test; the Amazon stuff shouldn't be using Wine to load the game list.

**Comment by dmaglio** [comment]
> But you should not need to do so for this test; 

i know, i know.

> the Amazon stuff shouldn't be using Wine to load the game list.
 the test for amazon stuff works correctly into master branch.

**Comment by danieljohnson2** [comment]
Excellent. But I'm afraid the fix is not available in flatpak form yet, so you may need to set up your games again to use it right now.

Still, we have the fix for the next release, so I'll close this item.
