### ISSUE TITLE
Mod/Add-on Installers not working for steam games.

### ISSUE THREAD

**Issue by lankv2** [lutris/lutris#5583]
OS: LMDE6 (Debian 12)
Lutris Versrion: 0.5.17

I wrote an installer for star wars dark forces that's supposed to add the force engine mod to the steam version but it will not work.
First i tried adding the installer on the game's lutris page. When testing the installer, lutris would say that the game is already installed. If i clicked install again it would do nothing. Then as a test i added the force engine as a game to the lutris database and tried the script there. It wouldn't detect that the game is installed so that also wouldn't work. I have successfully written an installer in the past that modifies an existing game config but the game was the retail/cd version not steam. So with my testing it seems that games installed through lutris with steam / games installed in steam and synced up with lutris don't count as installed in lutris?

Here is my script: (It's still wip so it may not fully work but it doesn't get far enough to matter right now.)

https://pastebin.com/VguhybPZ

**Comment by strycore** [comment]
your `extends` script shouldn't contain 

```
game:
  appid: 32400
```

In this case, it shouldn't even use `extends`. 
It should be a standalone installer for Linux that references the Steam files like this: https://lutris.net/games/install/1773/view
