### ISSUE TITLE
Lutris does not install UMU or Proton-GE

### ISSUE THREAD

**Issue by fakhraldin** [lutris/lutris#5586]
### Bug description

Trying to set up a title with UMU or Proton-GE results in several error messages no matter what title.:

"lutris-wrapper: XYZ
Started initial process 17705 from gamemoderun /home/user/.local/share/lutris/runtime/umu/umu_run.py /run/media/user/XYZ/setup.exe
Start monitoring process.
gamemodeauto: 
[1mUMU-Proton is up to date[0m
bwrap: Can't mkdir /run/pressure-vessel: Permission denied
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0

After i did a "sudo mkdir /run/pressure-vessel" manually per root, this next error came up in the log.:

"lutris-wrapper: XYZ
Started initial process 18413 from gamemoderun /home/user/.local/share/lutris/runtime/umu/umu_run.py /run/media/user/XYZ/setup.exe
Start monitoring process.
gamemodeauto: 
bwrap: Can't create file at /etc/bash.bashrc: Read-only file system
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0"

After this i didn't investigate further, as i don't have the time to fix all the following issues manually.
Also i didn't feel very well, to give all these permissions to system-critical-level directories.

### How to Reproduce

Basically the Steps to reproduce the behavior are:
1. Set up the starter for a fresh wine title
2. Choose wine version UMU-Proton-9.0-2 or GE-Proton (Latest)
3. Start the title
4. Watch the title exit quickly after launching it with no screen whatsoever

### Expected behavior

Expected UMU and GE-Proton to set up a wine-prefix and launch the title just as with previous wine-ge versions.

### Log output

```shell
lutris-wrapper: XYZ
Started initial process 17705 from gamemoderun /home/user/.local/share/lutris/runtime/umu/umu_run.py /run/media/user/XYZ/setup.exe
Start monitoring process.
gamemodeauto: 
[1mUMU-Proton is up to date[0m
bwrap: Can't mkdir /run/pressure-vessel: Permission denied
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0

# after i fixed the above the following log came up:

lutris-wrapper: XYZ
Started initial process 18413 from gamemoderun /home/user/.local/share/lutris/runtime/umu/umu_run.py /run/media/user/XYZ/setup.exe
Start monitoring process.
gamemodeauto: 
bwrap: Can't create file at /etc/bash.bashrc: Read-only file system
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: NO
In Flatpak: NO

[System]
OS: Fedora Linux 40 Workstation Edition
Arch: x86_64
Kernel: 6.10.6-200.fc40.x86_64
Desktop: GNOME
Display Server: wayland

[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 3700X 8-Core Processor
Physical cores: 8
Logical cores: 16

[Memory]
RAM: 15.5 GB
Swap: 8.0 GB

[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6650 XT (radeonsi, navi23, LLVM 18.1.6, DRM 3.57, 6.10.6-200.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.7
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.7
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.7
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Radeon RX 6650 XT (RADV NAVI23) (1.3.278)
```

**Comment by danieljohnson2** [comment]
Something squirrley going on here. I think we need to know about the game your installed. I am guessing you did not use the 'Install game from executable' option, but set up a game whose executable is '/run/media/user/XYZ/setup.exe'.

Did you set up a working directory? Without that, Lutris would have to guess and I think maybe that did not work out.

**Comment by fakhraldin** [comment]
Sure! This error happened with the last three ISOs so far. I still own titles like Starcraft series and Outcast etc on Disc. I am a longtime lutris user and never had such troubles before when using this method. I don't use the option "install game from executable" because it doesn't work with some ROMs.

No i don't set up a working directory but i set up a wine prefix. This usually works. But with UMU and GE-Proton nothing is being created inside of it. Only the old runner "wine-ge-8-26-x86_64" is actually triggering a wine-prefix creation. So this behaviour is indeed strange.

**Comment by fakhraldin** [comment]
You seem to be on the right track with your assumption. I tried again with my "Sam and Max" ISO. The "latest master code" works, while the lutris version from the fedora distro still doesn't. So there seems to be something wrong with that .rpm package and its settings, despite being the latest lutris version 0.5.17.

**Comment by danieljohnson2** [comment]
No, it's just that they're shipping the current release (0.5.17) and you just tried the code for the upcoming 0.5.18. Coming soon to a theater near you!

There are some problems with Umu integration in 0.5.17, but we've been working on it.

If your games will install with Umu now, maybe it's time to close this issue?

**Comment by fakhraldin** [comment]
Some of the games do launch now. But after closing and opening them for a second round only a black screen comes up and nothing happens.

On one occasion lutris freezes. And the log says something like it was unable to extract icon from the game's exe because the "buffer is not large enough".

**Comment by danieljohnson2** [comment]
Well, you seem to have some other problems but perhaps they should be new issues. Certainly we'll want to see new logs.

I am hoping the icon extraction issue is harmless- that sort of thing used to prevent saving, but in master it should not do so.

**Comment by fakhraldin** [comment]
Yes, according to the logs there seem to be some issues with VKD3D and my kernel version. I still need to investigate this.

As for the "icon extraction issue": When trying to save a config, Lutris freezes and in one occasion it crashed. But after wating a bit or restarting Lutris respectively after it crashes, i was able to launch the affected titles. At least the setup seems to save the config. It probably needs just a little bit more refinement. But i leave it for a separate issue report.

At least i am happy that i can create an UMU wine-prefix and install titles with it. However strangely enough i cannot set up and create a basic wine-prefix from the original WineHQ repository. In this case i tried WineHQ Devel (9.17) to no avail.

**Comment by fakhraldin** [comment]
> Some of the games do launch now. But after closing and opening them for a second round only a black screen comes up and nothing happens.

> Well, you seem to have some other problems but perhaps they should be new issues. Certainly we'll want to see new logs.

> Yes, according to the logs there seem to be some issues with VKD3D and my kernel version. I still need to investigate this.

I found the cause that prevented a relaunch of the created UMU wine-prefix resulting in a black screen. This bug is not exclusive to UMU but happens with a regular wine-prefix too. MangoHud causes it. When it is deactivated, the UMU and the regular wine-prefix launch sucessfully and regularly.

Well i think, i can close this issue now. Only one basic issue remains.:

> However strangely enough i cannot set up and create a basic wine-prefix from the original WineHQ repository. In this case i tried WineHQ Devel (9.17) to no avail.

Do you think i should open another issue for that or is it something trivial and a minor bug?

**Comment by danieljohnson2** [comment]
Minor bugs deserve issues too, though it's not clear to me what you're up to there. The issue may not be a Lutris thing, perhaps.

**Comment by fakhraldin** [comment]
In the "Configure" menu i do set the path for a new wine-prefix. As usual i create a folder in my home user profile for this.

Setting up a title with the runner "UMU-Proton-9.0-2" successfully installs the wine-prefix.

But setting up a title with the runner "WineHQ Devel (9.17)" results in deleting that folder. No wine-prefix gets installed and the log remains empty.

**Comment by danieljohnson2** [comment]
Can we have a screenshot of your game's runner configuration?

**Comment by fakhraldin** [comment]
Sure, it is a pretty much default set up with configuration for Runner, Name, Executable, Wine prefix and that's it.
![Lutris Configuration Runner 2024-09-08 22-03-25](https://github.com/user-attachments/assets/688cb9a7-50cf-4b5a-a3b4-a748a6c2ed45)

**Comment by danieljohnson2** [comment]
Hmm. Looks like Lutris is detecting your WineHQ development install, which should be okay.

But you say this thing is *deleting the prefix*, not just failing to work, right? Super weird.

**Comment by fakhraldin** [comment]
When launching titles with runners like UMU-Proton, GE-Proton and wine-ge-8-26-x86_64, a wine-prefix gets installed regularly. However for "WineHQ Devel (9.17)" i had to set up a wine-prefix manually like this.:

WINEPREFIX="/home/user/Games/Humanity/" winecfg

After that i was able to control this created wine-prefix per Lutris by choosing the runner "WineHQ Devel (9.17)" accordingly.

**Comment by danieljohnson2** [comment]
If you've configured the prefix for your game, Lutris should be setting the WINEPREFIX environment variable for you. A lot of stuff wouldn't work if we didn't!

This keeps getting stranger.

**Comment by fakhraldin** [comment]
I just downloaded the latest master code and the issue returned. Only selecting the wine runner `wine-ge-8-26-x86_64 ` results in actually creating a wine-prefix. 

All the other versions, be it umu or ge-proton etc. lead to a pumping icon animation in lutris but no wine-prefix is being created. Only doing this manually as mentioned above per command line creates a wine-prefix.

**Comment by danieljohnson2** [comment]
Bear in mind that ge-proton is Umu too. It sounds like Umu is not working for you.

But  we just put out an update to the Umu runtime to get it to work again in 0.5.17. Maybe that will help?

**Comment by fakhraldin** [comment]
> Bear in mind that ge-proton is Umu too. It sounds like Umu is not working for you.

That would explain why both result in the same behavior.: When selecting ge-proton or Umu a wine-prefix gets created with some files but empty ones. Those are: `tracked_files`, `drive_c` and `pfx` while pfx is a directory seemingly looping in itself endlessly. But i am not sure if this is what is causing the wine-prefix creation process to not to finish.

Choosing `WineHQ Devel (9.19)` results in not creating those above files nor a wine-prefix at all.
Choosing `wine-ge-8-26-x86_64` results in creating a complete wine-prefix with no issues as usual.

Testing was done with a new lutris-master download.

**Comment by danieljohnson2** [comment]
Neither of those should trigger Umu. I do not know why WineHQ Devel is broken, but I think it is a different problem. You might want to post a new log from that case, I don't think we've seen a log from that one yet.

**Comment by fakhraldin** [comment]
Here is the terminal log from launching the latest lutris git downloaded from the branch "lutris-lutris-umu-refactor". Trying to set up a wine-prefix with UMU-Proton-9.0-2 resulted in an endless loop with no TEST directory being created at all. After a couple of minutes i had to stop the process.
[terminal log launching lutris.txt](https://github.com/user-attachments/files/17497549/terminal.log.launching.lutris.txt)

And here is an error message from the lutris app itself coming up shortly after.
[lutris error message.txt](https://github.com/user-attachments/files/17497548/lutris.error.message.txt)

Also launching an old game install like Mafia doesn't work anymore neither with UMU nor with GE-Proton. wine-log:

> lutris-wrapper: Mafia Definitive Edition
> Started initial process 33994 from gamemoderun mangohud /home/user/.local/share/lutris/runtime/umu/umu-run /home/user/Games/Mafia.Definitive.Edition/drive_c/GOG Games/Mafia Definitive Edition/launcher.exe
> Start monitoring process.
> gamemodeauto: 
> gamemodeauto: 
> env: „/home/user/.local/share/lutris/runtime/umu/umu-run“: access denied
> Monitored process exited.
> Initial process has exited (return code: 32256)
> All processes have quit
> Exit with return code 32256

**Comment by danieljohnson2** [comment]
You are using a branch in very active development there, so you can expect heavy weather.

That said, is the execute bit set on this file ``~/.local/share/lutris/runtime/umu/umu-run``?

If not, set it, and maybe on ``umu_run.py`` too for luck. Might work better.

**Comment by strycore** [comment]
fixed

**Comment by fakhraldin** [comment]
> You are using a branch in very active development there, so you can expect heavy weather.
> 
> That said, is the execute bit set on this file `~/.local/share/lutris/runtime/umu/umu-run`?
> 
> If not, set it, and maybe on `umu_run.py` too for luck. Might work better.

I downloaded recent lutris master and applyed chmod +x to both umu files in that umu-run folder.

Results: 
- Lutris does create an UMU wine-prefix now. Success!
- Trying to create a prefix a la "WineHQ Devel (9.17)" or "wine 9.17" (from distro repo itself) still results in an endless loop with no prefix being created. Here is the log file.
[Lutris - wine prefix log.txt](https://github.com/user-attachments/files/17592526/Lutris.-.wine.prefix.log.txt)
