### ISSUE TITLE
Lutris sometimes cannot be used offline because of UMU

### ISSUE THREAD

**Issue by mhmarf** [lutris/lutris#5587]
### Bug description

Hello and thank you for your amazing work. This is a feedback on UMU...

I decided to install UMU in Nobara last night (using `sudo dnf install`... ). Now in Lutirs, if I choose any proton version (experimental, ge-proton, proton 8.0, etc... all of them working fine before UMU) I see that I first have to wait for UMU to download its "run times" (log shows "steamrt" in particular) before I can play... Now if one has an internet issue, they won't be able to play anything! They get stuck waiting for UMU to finish downloading updates!! I even went to Lutris Options and disabled every single "automatic update setting" as well to no avail.

Today I had an internet connection issue (not on my side, on ISP side), I decided to play a game while waiting for it to get fixed. And then I see that I cannot play ANYTHING if I use Proton! Because UMU wants to download things apparently but it keeps failing because of my network problem.
To fix this issue myself, I removed all UMU folders as well as `sudo dnf remove`d it, then went to `.steam/.../common/` and copied "Proton - Experimental" folder from there to `.local/lutris/runners/wine/ ` and chose it from Runners options and... everything is working smoothly with no problem! even though my internet problem is still not fixed I am able to play my games now!! 

I just wanted to give this feedback to devs to please do not force always online...
Thank you

### How to Reproduce
EDIT: I don't know why but could not reproduce this issue myself after disabling my internet. I think it is because UMU already had downloaded everything... I think internet must be in a state where it is enabled, but UMU cannot connect to servers... 
1. somehow block UMU's internet access to replicate this "internet issue"...
3. Play a game using any Proton version.
4. Infinite waiting is required because UMU wants to download run times!!

### Expected behavior

I want to be able to play games even if PC has no internet access... using previously downloaded runners such as Proton-GE, Proton - Experimental, etc...

### Log output

```shell
Sorry I did not save the logs after fixing the problem...
But it was stuck after:
.../umu-run.py [game exe]
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Nobara Linux 40 KDE Plasma
Arch: x86_64
Kernel: 6.8.12-201.fsync.fc40.x86_64
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 7900X3D 12-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 31.1 GB
Swap: 35.9 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 18.1.6, DRM 3.57, 6.8.12-201.fsync.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3
Vulkan Version: 1.3.280
Vulkan Drivers: AMD Radeon RX 6900 XT (RADV NAVI21) (1.3.289)
```

**Comment by danieljohnson2** [comment]
Too bad we've got no log output. I tried but could not repro this; I would guess I have already downloading *something* that it is trying to download for you, but I do not know what it was.

**Comment by R1kaB3rN** [comment]
Thanks for report the issue.

So since https://github.com/Open-Wine-Components/umu-launcher/pull/158, it's now possible to disable the automatic update to the runtime by setting `UMU_RUNTIME_UPDATE=0` which may help you.

**Note**: This will only work after umu has already been fully setup and Lutris will be responsible for pushing an update to umu to support this.

In the future, more graceful handling of network errors will be implemented because I am aware of this as certain network configurations/conditions will cause the launcher the hang indefinitely (e.g., having a VPN enabled). Delta updates to the runtime will also be explored.

**Comment by mhmarf** [comment]
I see many changes in UMU aiming to fix this... if not, `UMU_RUNTIME_UPDATE=0` can also be used...
Thank you!

**Comment by lavilao** [comment]
Got the same error today and can confirm that `UMU_RUNTIME_UPDATE=0` fixes it. @danieljohnson2 the error seems to be that umu always wants to update itself and if t cants it crashes. Here is the log:
[lutris.log](https://github.com/user-attachments/files/17400899/lutris.log)

**Comment by danieljohnson2** [comment]
That may be so, but I am not working on Umu itself, so I am not going to try to change it.

**Comment by mhmarf** [comment]
> Got the same error today and can confirm that `UMU_RUNTIME_UPDATE=0` fixes it. @danieljohnson2 the error seems to be that umu always wants to update itself and if t cants it crashes. Here is the log: [lutris.log](https://github.com/user-attachments/files/17400899/lutris.log)

I never had these errors. For me the logs were normal like all other games, only it was stuck after `.../umu-run.py [game exe]`...

**Comment by R1kaB3rN** [comment]
> Got the same error today and can confirm that `UMU_RUNTIME_UPDATE=0` fixes it. @danieljohnson2 the error seems to be that umu always wants to update itself and if t cants it crashes. Here is the log: [lutris.log](https://github.com/user-attachments/files/17400899/lutris.log)

That specific bug was already addressed in the main branch since https://github.com/Open-Wine-Components/umu-launcher/commit/cbf0ee1c5a6cadaa12ccb2642622b39f4cf6d950, and should reach out to Lutris users in the next umu-launcher hotix release and whenever the Lutris runtime pushes that build in its runtime.
