### ISSUE TITLE
Steam: 'NoneType' object has no attribute 'game_level'

### ISSUE THREAD

**Issue by timoteoramos** [lutris/lutris#5589]
### Bug description

Every time when I need to sync my Steam games in Lutris I get this error message: 'NoneType' object has no attribute 'game_level'

Even with this error, my library appears on Lutris, but some installed games doesn't sync correctly, I need to install them manually.

### How to Reproduce

1. Make sure you have the Steam on your Sources list
2. Click on 'Reload' button for your Steam source on Lutris
3. Depending on the games that you have on your library, the error should appear

### Expected behavior

The synchronization should run without any errors.

### Log output

```shell
Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x739e30980900>: <class 'AttributeError'> 'NoneType' object has no attribute 'game_level'
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/services/base.py", line 144, in do_reload
    self.add_installed_games()
  File "/usr/lib/python3.12/site-packages/lutris/services/steam.py", line 183, in add_installed_games
    appid = steam_game.config.game_level["game"]["appid"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.10.8-zen1-1-zen
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 17.4 GB
Swap: 17.4 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Vega 10 Graphics (radeonsi, raven, LLVM 18.1.8, DRM 3.57, 6.10.8-zen1-1-zen)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.2-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.2-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.2-arch1.1
Vulkan Version: 1.3.295
Vulkan Drivers: AMD Radeon Vega 10 Graphics (RADV RAVEN) (1.3.289)
```

### Media (optional)

![image](https://github.com/user-attachments/assets/c0ec808d-5f91-44f4-b167-f375820d4cc0)

**Comment by danieljohnson2** [comment]
I believe this code has been improved and the latest code should no longer fail like this; it will log an error and continue to your other games.

Please download [the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within, no need to install. You should be able to reload the Steam source with that.

**Comment by strycore** [comment]
Considering this fixed
