### ISSUE TITLE
Deleted games still in focus

### ISSUE THREAD

**Issue by bjoern-tantau** [lutris/lutris#5592]
### Bug description

When a game is deleted it still seems to be selected, making all actions in the Wine menu go to the old prefix. This might only happen when the game files aren't removed. I haven't checked.

### How to Reproduce

1. Rightclick game
2. Select remove and follow instructions
3. Click the Wine-Icon
4. Selecr Winetricks and install something
5. The component is installed to the deleted game's directory

### Expected behavior

No game should be selected after removing one.

### Log output

```shell
No log available
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: openSUSE Tumbleweed 20240906 n/a
Arch: x86_64
Kernel: 6.10.8-1-default
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 7.6 GB
Swap: 7.6 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.1.3
OpenGL Core: 4.6 (Core Profile) Mesa 24.1.3
OpenGL ES: OpenGL ES 3.2 Mesa 24.1.3
Vulkan Version: 1.3.290
Vulkan Drivers: NVIDIA GeForce MX130 (1.3.277), Intel(R) UHD Graphics 620 (WHL GT2) (1.3.278)
```

**Comment by danieljohnson2** [comment]
It's not just game removal- anything you do with results in no selection when in grid mode leaves the game-bar up, letting you interact with your previously selected game. But in the removed-game case the consequences are worse.

I've modified the code so when the game becomes unselected, we will remove the game bar.

You can try it if you wish; download [the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install! You should no longer be able to use the game bar on a game that's removed.
