### ISSUE TITLE
[Feature request] Fortnite Mobile instead of the PC version of Fortnite.

### ISSUE THREAD

**Issue by Will48822** [lutris/lutris#5594]
Couldn't we install the mobile version of Fortnite through Lutris?
There are two programs for Linux that do something similar: Sober and MCPElauncher, which use Android libraries to run the Play Store versions of Roblox and Minecraft Bedrock, respectively. Couldn't something similar be done to run Fortnite Mobile on Linux?
![LinuxAndroidMinecraftRoblox](https://github.com/user-attachments/assets/6fce519d-1eb3-4fbf-abac-80582ccbd997)

This could be integrated into Lutris for installation through their website. I don't know how feasible it is, but after learning about the two programs mentioned above, it might be possible, and we could enjoy Fortnite on Linux.
![image](https://github.com/user-attachments/assets/349d3002-85f3-49e3-bee8-f33dbbcbcec7)

**Comment by strycore** [comment]
It's a neat idea but it's really not our job to take care of that.
