### ISSUE TITLE
SteamDeck Controller setup

### ISSUE THREAD

**Issue by phodina** [lutris/lutris#5600]
### Bug description

There's no way to specify on the SteamDeck in Lutris the controller layout.

### How to Reproduce

Launch any game. No way to specify different controller layout.

### Expected behavior

In the game settings there would be option to launch the controller setup and select the right layout per game.

### Log output

```shell
Not needed in this case.
```

### System Information

```shell
Just SteamDeck Linux distro.
```

**Comment by strycore** [comment]
Create a Steam shortcut for your game then configure your inputs.
