### ISSUE TITLE
[Feature Request]: Add Winget 

### ISSUE THREAD

**Issue by Mannshoch** [lutris/lutris#5610]
Please add Microsoft Winget to Lutris:
https://github.com/microsoft/winget-cli

Repository: https://github.com/microsoft/winget-pkgs

Every Winget installation should be made inside a separate wine environment. But - if possible - allow using winget cli to manage and update the environment.

Maybe a good idea could be to blacklist some apps if they have to be installed with winetricks.

**Comment by strycore** [comment]
But why?
What is the purpose?

I didn't know about Winget until now and my life has been great. How will it improve it?

**Comment by Mannshoch** [comment]
Winget will help Install several Windows Application fast (And contain some OSS Products). And also will help Update several Microsoft Products like Microsoft VC Redistibutables.
Maybe it could also Provide some Software Winetrix provide

**Comment by strycore** [comment]
Well that's not very convincing...
What applications does it install, which one do you use personally.
Why would we want to update the VC Runtime, this is hasn't been needed in the past 20 years, why would we need it now?

Chances of Lutris ever getting Winget are very low at the moment.

**Comment by Mannshoch** [comment]
Thanks for your feedback. 

I created a List of tools that could be interesting. This list is directly from the terminal output of Winget.

Game related:
```
Steam                                      Valve.Steam                    2.10.91.91                   winget
Origin                                     ElectronicArts.Origin          10.5.28.55504                winget
EA app                                     ElectronicArts.EADesktop       13.301.0.5814  Tag: origin   winget
Epic Games Launcher                        EpicGames.EpicGamesLauncher    1.3.93.0       Tag: game     winget
Bethesda.net Launcher                      Bethesda.Launcher              1.84.0         Tag: games    winget
Battle.net Setup                           Blizzard.BattleNet             1.18.10.3141   Tag: games    winget
... 
League of Legends (North America server)   RiotGames.LeagueOfLegends.NA   88.0.1.1613    Tag: game     winget
...

```
What could be found if you search for "Game" in Winget:
https://www.paste.org/128185

What you could find if you search for "Office:
https://www.paste.org/128186

Microsoft Products:
https://pastebin.com/1LB40Jne

I currently use several Games with vc redist components and yes they never got an Update. My most of my wine Installation is 13 years old now. Several of them automatically connect somewhere over Internet. Some send me error messages because a domain does not anymore exist. The games could not get updates. The older they get the the more chills I have. May #4556 is more important. While writing this lines I decided to check this firejail software.

**Comment by strycore** [comment]
This seems to conflict with our installers. 

Origin and Bethesda Launchers do not exist anymore.

League of Legends isn't compatible with Linux

I'm going to turn this down because it offers zero value to lutris, sorry.
