### ISSUE TITLE
Downloading GOG game has several issues for me

### ISSUE THREAD

**Issue by BileDemon** [lutris/lutris#5611]
I'm trying to download Cyberpunk 2077 (2.13) from GOG for hours and hours on end and it never works unfortunately. This has worked in the past (mostly) without problems.

The download always starts at part 27 and it proceeds until parts 15 (or 13), where it gets a 403 error and the downloader just breaks with an exception. There is no way to make it continue, it always shows the exception. I tried downloading those files from the GOG website directly and it works just fine.

Also setting the download cache folder doesn't do anything, because it always replaces the files that have successfully been downloaded previously, again starting with part 27 and progressing backwards until it gets a 403 error. It never recognizes the earlier download progress.

Maybe it has something to do with another issue that it has: The downloaded parts all have wrong filenames, like:
"setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-27.bin"
instead of
"setup_cyberpunk_2077_2.13_(64bit)_(76205)-27.bin"

I know for certain that in the past Lutris allowed me to select which files I wanted to download separately and in which order, so this must have been removed in favor of downloading one file at a time and not being able to easily select the files.

This is the log output:
`DEBUG    2024-09-21 09:42:47,613 [installerwindow.present_extras_page:522]:Showing extras page
INFO     2024-09-21 09:42:50,982 [installer.prepare_game_files:168]:Getting files for setup
INFO     2024-09-21 09:42:50,982 [gog.get_game_details:284]:Getting game details for 1423049311
DEBUG    2024-09-21 09:42:51,004 [http._request:88]:GET https://api.gog.com/products/1423049311?expand=downloads&locale=de-DE
INFO     2024-09-21 09:42:51,059 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer0
DEBUG    2024-09-21 09:42:51,091 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer0
INFO     2024-09-21 09:42:51,286 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer1
DEBUG    2024-09-21 09:42:51,326 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer1
INFO     2024-09-21 09:42:51,531 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer2
DEBUG    2024-09-21 09:42:51,572 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer2
INFO     2024-09-21 09:42:51,772 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer3
DEBUG    2024-09-21 09:42:51,812 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer3
INFO     2024-09-21 09:42:52,011 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer4
DEBUG    2024-09-21 09:42:52,049 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer4
INFO     2024-09-21 09:42:52,252 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer5
DEBUG    2024-09-21 09:42:52,291 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer5
INFO     2024-09-21 09:42:52,486 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer6
DEBUG    2024-09-21 09:42:52,524 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer6
INFO     2024-09-21 09:42:52,728 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer7
DEBUG    2024-09-21 09:42:52,770 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer7
INFO     2024-09-21 09:42:52,952 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer8
DEBUG    2024-09-21 09:42:52,991 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer8
INFO     2024-09-21 09:42:53,199 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer9
DEBUG    2024-09-21 09:42:53,239 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer9
INFO     2024-09-21 09:42:53,438 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer10
DEBUG    2024-09-21 09:42:53,480 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer10
INFO     2024-09-21 09:42:53,680 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer11
DEBUG    2024-09-21 09:42:53,719 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer11
INFO     2024-09-21 09:42:53,921 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer12
DEBUG    2024-09-21 09:42:53,961 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer12
INFO     2024-09-21 09:42:54,169 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer13
DEBUG    2024-09-21 09:42:54,208 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer13
INFO     2024-09-21 09:42:54,414 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer14
DEBUG    2024-09-21 09:42:54,451 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer14
INFO     2024-09-21 09:42:54,647 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer15
DEBUG    2024-09-21 09:42:54,684 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer15
INFO     2024-09-21 09:42:54,991 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer16
DEBUG    2024-09-21 09:42:55,029 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer16
INFO     2024-09-21 09:42:55,262 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer17
DEBUG    2024-09-21 09:42:55,300 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer17
INFO     2024-09-21 09:42:55,481 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer18
DEBUG    2024-09-21 09:42:55,519 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer18
INFO     2024-09-21 09:42:55,756 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer19
DEBUG    2024-09-21 09:42:55,794 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer19
INFO     2024-09-21 09:42:55,991 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer20
DEBUG    2024-09-21 09:42:56,029 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer20
INFO     2024-09-21 09:42:56,222 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer21
DEBUG    2024-09-21 09:42:56,260 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer21
INFO     2024-09-21 09:42:56,460 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer22
DEBUG    2024-09-21 09:42:56,497 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer22
INFO     2024-09-21 09:42:56,688 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer23
DEBUG    2024-09-21 09:42:56,727 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer23
INFO     2024-09-21 09:42:56,921 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer24
DEBUG    2024-09-21 09:42:56,959 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer24
INFO     2024-09-21 09:42:57,172 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer25
DEBUG    2024-09-21 09:42:57,210 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer25
INFO     2024-09-21 09:42:57,411 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer26
DEBUG    2024-09-21 09:42:57,450 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer26
INFO     2024-09-21 09:42:57,625 [gog.get_download_info:291]:Getting download info for https://api.gog.com/products/1423049311/downlink/installer/en1installer27
DEBUG    2024-09-21 09:42:57,664 [http._request:88]:GET https://api.gog.com/products/1423049311/downlink/installer/en1installer27
DEBUG    2024-09-21 09:42:57,866 [installerwindow.on_files_prepared:608]:Game files prepared.
DEBUG    2024-09-21 09:42:57,870 [installerwindow.present_installer_files_page:623]:Presenting installer files page
DEBUG    2024-09-21 09:43:09,049 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-27.bin
DEBUG    2024-09-21 09:44:17,645 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-27.bin
DEBUG    2024-09-21 09:44:18,129 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-26.bin
DEBUG    2024-09-21 09:49:43,621 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-26.bin
DEBUG    2024-09-21 09:49:44,012 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-25.bin
DEBUG    2024-09-21 09:55:16,018 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-25.bin
DEBUG    2024-09-21 09:55:16,389 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-24.bin
DEBUG    2024-09-21 10:00:48,651 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908177~dirs=6~token=0d2566bfbc906de50728a/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-24.bin
DEBUG    2024-09-21 10:00:48,764 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-23.bin
DEBUG    2024-09-21 10:06:23,130 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-23.bin
DEBUG    2024-09-21 10:06:23,139 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-22.bin
DEBUG    2024-09-21 10:11:50,599 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-22.bin
DEBUG    2024-09-21 10:11:51,008 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-21.bin
DEBUG    2024-09-21 10:17:16,996 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-21.bin
DEBUG    2024-09-21 10:17:17,376 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-20.bin
DEBUG    2024-09-21 10:22:43,028 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908176~dirs=6~token=0eed9fef0b735c960bcda/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-20.bin
DEBUG    2024-09-21 10:22:43,252 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-19.bin
DEBUG    2024-09-21 10:28:08,774 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-19.bin
DEBUG    2024-09-21 10:28:09,126 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-18.bin
DEBUG    2024-09-21 10:33:34,559 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-18.bin
DEBUG    2024-09-21 10:33:34,989 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-17.bin
DEBUG    2024-09-21 10:39:00,508 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-17.bin
DEBUG    2024-09-21 10:39:00,848 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-16.bin
DEBUG    2024-09-21 10:44:26,393 [downloader.on_download_completed:166]:Finished downloading https://gog-cdn-fastly.gog.com/token=nva=1726908175~dirs=6~token=0b7db42dc940880888bd3/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-16.bin
DEBUG    2024-09-21 10:44:26,707 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
INFO     2024-09-21 10:44:26,808 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin returned a 403 error
ERROR    2024-09-21 10:44:26,808 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
DEBUG    2024-09-21 10:44:27,209 [downloader.start:60]:⬇ https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
INFO     2024-09-21 10:44:27,280 [downloader.async_download:136]:https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin returned a 403 error
ERROR    2024-09-21 10:44:27,280 [downloader.async_download:149]:Download failed: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 137, in async_download
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://gog-cdn-fastly.gog.com/token=nva=1726908174~dirs=6~token=0430b0a2f3852639d6748/secure/offline/1423049311/1423049311/57913121226133752/9439/setup_cyberpunk_2077_2.13_%2864bit%29_%2876205%29-15.bin
ERROR    2024-09-21 10:44:29,215 [exception_backstops.error_wrapper:110]:Error handling timeout function: 1 parameters needed for signal error; 0 given
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")
TypeError: 1 parameters needed for signal error; 0 given
`

(removed a few exception repeats)

Lutris has caused me like 500 GB nonsense traffic for Cyberpunk 2077 alone, because it always downloads from scratch and then crashes.
Is it possible to make the downloader more resilient towards download problems and also allow it to resume downloads. Maybe it should try to download other parts first and not outright stop at the first part that is problematic.

**Comment by danieljohnson2** [comment]
This looks very much like #5599. You are experiencing the same error handling bug, now fixed in the master branch. But I still do not know why GoG is giving some users 403 errors in the first place, and (according to #5599) only for some games, and not only big ones either.

**Comment by BileDemon** [comment]
Alright, thanks for the info.
I could certainly live with a 403 error now and then, if only resuming the downloads worked correctly, or at least Lutris allowed me to select the parts to download first.

**Comment by danieljohnson2** [comment]
Well, I'm not sure if the don't-redownload-every-file PR helps you, but I've addressed another issue- we'll now download GOG games with their proper, unescaped names. If you have the files with the munged names, we'll still use them and no re-download.

I do not think that's related to your 403 error, which remains a mystery.

**Comment by BileDemon** [comment]
To be fair, I doubt that the devs can do much about those 403 errors, to me it seems more like a case of GOG being GOG. They hate Linux anyway, maybe they're experimenting with blocking Lutris out. Who knows.

But it's great to see you guys improve the Downloader and mitigate any errors that might occur. Thanks for your work to make Lutris a better experience.

Since changes to improve this have been implemented/merged, I consider this issue fixed and closed. And now I hope that 0.5.18 will release any time soon.

**Comment by strycore** [comment]
> They hate Linux anyway, maybe they're experimenting with blocking Lutris out. Who knows.

Get the fuck out and don't come back.
