### ISSUE TITLE
Can't log into Amazon Gaming account.

### ISSUE THREAD

**Issue by WellBeSerious** [lutris/lutris#5613]
### Bug description

* Sorry if this has been posted before. If so, please append this to the proper post/thread, as this may help. Thank you.

Can't log into Amazon Gaming account (only tried via GUI). I can sign into account, but error appears, and I can't do anything else related to Amazon Gaming. Lutris installed is "lutris_0.5.17_all.deb". Repository version is too old otherwise.

### How to Reproduce

1. Open Lutris.
2. (Left) Amazon Prime Gaming, (right of it) click user picture/login.
3. Log into accoumt.
4. Text appears: Lutris has encountered an error / 'NoneType' object is not iterable / Error details:
'NoneType' object is not iterable

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3/dist-packages/lutris/services/amazon.py", line 160, in load
    games = [AmazonGame.new_from_amazon_game(game) for game in self.get_library()]

TypeError: 'NoneType' object is not iterable

### Expected behavior

Log into Amazon Gaming account via GUI, without issues.

### Log output

```shell
( Lutris has encountered an error / 'NoneType' object is not iterable )


'NoneType' object is not iterable

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 142, in do_reload
    self.load()

  File "/usr/lib/python3/dist-packages/lutris/services/amazon.py", line 160, in load
    games = [AmazonGame.new_from_amazon_game(game) for game in self.get_library()]

TypeError: 'NoneType' object is not iterable
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Linux Mint 21.3 Virginia
Arch: x86_64
Kernel: 5.19.0-50-generic
Desktop: MATE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 5600X 6-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 62.7 GB
Swap: 7.6 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3050/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.90.07
OpenGL Core: 4.6.0 NVIDIA 550.90.07
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.90.07
Vulkan Version: 1.3.204
Vulkan Drivers: NVIDIA GeForce RTX 3050 (1.3.277)
```

**Comment by danieljohnson2** [comment]
This appears to be #5596 again, which is fixed in master.

Please try that. [Download the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install! Try to sync your Amazon account; I think it will be able to do so.

**Comment by Susie-Bee** [comment]
I get the same problem, using Kubuntu 24.04. I have tried the master branch as above but get the same result.

**Comment by danieljohnson2** [comment]
Well, the master branch should make it *different* at least. @Susie-Bee, could you post your log from this failure (using the master branch)? Maybe it's not as fixed in master as I thought.

**Comment by Susie-Bee** [comment]
> Well, the master branch should make it _different_ at least. @Susie-Bee, could you post your log from this failure (using the master branch)? Maybe it's not as fixed in master as I thought.

Realised it's me being ignorant - I thought I had downloaded the master branch but managed to just download the tar - when I downloaded using the command line it fixed it. 

Now I just need to work out how to get all my links working (I'm pretty new to all this!)

**Comment by WellBeSerious** [comment]
Master solved this ( #5613 , Amazon) and #5612 ( Humble ).

**Comment by slaszt** [comment]
@WellBeSerious Is there going to be a new release or hotfix for this any time soon? Since #5517 I have been using Heroic to install and Lutris to launch and would like not to. I am using the Flatpak version, so cloning the repo and running `bin/lutris` gives an error.

**Comment by WellBeSerious** [comment]
1. I'm not a programmer/developer, nor associted with Heroic/Lutris, or any other 'launcher'.
2. This is how I have my Heroic and Lutris launchers setup:
- Heroic installed through AppImage. No problems.
- Lutris ( lutris_0.5.17_all.deb ) installed first. Which has issues logging into Amazon (#5613) and Humble Bundle (#5612) accounts.
- Lutris Master ( https://github.com/lutris/lutris , top of page > Code > Download ZIP). Downloaded > extracted to "~/username/Applications/" > opened and Desktop shortcutted "/username/Applications/lutris-master/bin/lutris" [Python 3 script].
- Opened and configured Lutris > let it auto-install proper clients externally when selecting account/platform. BOTH Lutris 'old' (deb) and Lutris 'master' are 'installed', but I only launch from Lutris 'master', and have both properly renamed to avoid launching older problematic one.
* While it's not optimal, this is what work for me now. And since I'm not a developer, I'd rather not mess with anything 'critical' or what I don't understand.

**Comment by haliphax** [comment]
I'm using the Flatpak version, as well, and would very much prefer not to have to download Lutris from GitHub in order to resolve this

**Comment by strycore** [comment]
fixed

**Comment by slaszt** [comment]
For people using Flatpak (at least until 0.5.18 is released), you can install Lutris from the flatpak-beta branch. Doing this has allowed me to download and install games from Amazon Games. [Instructions are located here](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111), make sure you actually read them and also that you replace `org.godotengine.Godot` with `net.lutris.Lutris`.
