### ISSUE TITLE
The hotkey ^h for "Show Hidden Games" should work as a toggle

### ISSUE THREAD

**Issue by nozwock** [lutris/lutris#5617]
Currently on 0.5.17, pressing ^h would move you to the "Hidden" tab, but pressing it again wouldn't take you back to the previous tab.

I believe it'd would be a better UX if we had it work the way it does in most file managers on Linux, where ^h works as a toggle for unhiding and hiding items.

One somewhat related issue I found was #3260, which was marked as completed while the PR was rejected for technical reasons.

**Comment by strycore** [comment]
The hidden games feature certainly was better when it wasn't a category. 

There's no going back I guess... I don't think this will ever be fixed.

**Comment by danieljohnson2** [comment]
Oh, did you want this toggle behavior? 

I'm sure we can manage to do it.

**Comment by strycore** [comment]
I certainly never asked to have it removed

**Comment by strycore** [comment]
gosh, please don't make it switch from Section A > Hidden > Section B

**Comment by strycore** [comment]
this is pretty terrible UX.... (both current design AND going back to a random tab)

**Comment by danieljohnson2** [comment]
> I certainly never asked to have it removed

I will direct you to PR #5312 for the history on this change.

**Comment by strycore** [comment]
> > I certainly never asked to have it removed
> 
> I will direct you to PR #5312 for the history on this change.

From that PR's comments, I certainly mentioned toggling hidden games :smile: 

> I would not be mad if we just removed "show hidden games" as a settings and toggling it on and off would only affect the current session.

**Comment by danieljohnson2** [comment]
I've modified the 'Show Hidden Games' command to bounce back to the previous view, if you use it when the hidden games are shows. Hopefully that will be more ergonomic.

**Comment by danieljohnson2** [comment]
Got the label on the thing to update to 'Rehide Hidden Games' when appropriate.

That, by far, was the hard part.

**Comment by nozwock** [comment]
> Got the label on the thing to update to 'Rehide Hidden Games' when appropriate.
> 
> That, by far, was the hard part.

You could make it a checkbox instead of a button, that way you wouldn't have to change the button label.

**Comment by danieljohnson2** [comment]
Sure... if you want to do it the *easy* way.

But I wasn't going to let GTK beat me!

Yeah, GTK do be like that.

**Comment by strycore** [comment]
I just pulled the latest changes and the toggling doesn't work.

**Comment by danieljohnson2** [comment]
Works on my machine (tm). Check to see if the menu item label changes when you show hidden games; if not, you may not be running the lates.t

**Comment by strycore** [comment]
Indeed I wasn't. I was once again fooled by the new(ish) behavior of the systray icon which will forever confuse me.
