### ISSUE TITLE
The key 'card0' could not be found.

### ISSUE THREAD

**Issue by friishon** [lutris/lutris#5619]
### Bug description

Every time i try to play any game, appears this error
"The key 'card0' could not be found."

### How to Reproduce

I don't know how to reproduce, some times works others not
Just clicking y play en appear the error

### Expected behavior

Help me to solve my problem

### Log output

```shell
❯ lutris -d
2024-09-26 11:10:51,383: Command 'fluidsynth' not found on your system
2024-09-26 11:10:51,535: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-09-26 11:10:51,632 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-09-26 11:10:51,719 [startup.run_all_checks:120]:NVIDIA GeForce RTX 2080 Super (10de:1e93 1043:1a5f nvidia) Driver 550.107.02
INFO     2024-09-26 11:10:51,747 [startup.run_all_checks:120]:Intel UHD Graphics (8086:9bc4 1043:1a5f i915) Driver 24.0.9
DEBUG    2024-09-26 11:10:51,914 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-09-26 11:10:51,924 [xrandr._get_vidmodes:18]:Retrieving 54 video modes from XrandR
DEBUG    2024-09-26 11:10:52,023 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-09-26 11:10:52,089 [api.check_stale_runtime_versions:52]:Modified at jue 26 sep 2024 08:55:27, will update after jue 26 sep 2024 14:55:27
DEBUG    2024-09-26 11:10:52,090 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
ERROR    2024-09-26 11:11:17,114 [exception_backstops.error_wrapper:110]:Error handling signal 'clicked': 'card0'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 231, in on_run_runner
    runner.run(self.get_toplevel())
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 399, in run
    command_data = self.get_run_data()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 388, in get_run_data
    return {"command": self.get_command(), "env": self.get_env()}
                                                  ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 238, in get_env
    gpu = GPUS[self.system_config["gpu"]]
          ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'card0'
```

### System Information

```shell
Vulkan support: SÍ
Esync support: SÍ
Fsync support: SÍ
Wine installed: SÍ
Gamescope: NO
Mangohud: NO
Gamemode: SÍ
Steam: SÍ
In Flatpak: NO
[System]
OS: Linux Mint 22 Wilma
Arch: x86_64
Kernel: 6.8.0-45-generic
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.1 GB
Swap: 1.9 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.1
Vulkan Version: 1.3.275
Vulkan Drivers: Intel(R) UHD Graphics (CML GT2) (1.3.274), NVIDIA GeForce RTX 2080 Super (1.3.277)
```

### Media (optional)

![image](https://github.com/user-attachments/assets/fcc100fd-ce6f-4e2e-8541-c8077b576bf8)

**Comment by danieljohnson2** [comment]
I believe I've fixed this. What is happening is that your configuration specifies a GPU that isn't there (anymore); maybe some hardware that is no longer installed, or something like that.

I've added a check against this. Please download [the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install! I think you'll be able to play your game.

**Comment by friishon** [comment]
`2024-09-26 12:35:28,894: "card1" is NVIDIA GeForce RTX 2080 Super (10de:1e93 1043:1a5f nvidia) Driver 550.107.02
2024-09-26 12:35:28,922: "card2" is Intel UHD Graphics (8086:9bc4 1043:1a5f i915) Driver 24.0.9
`

I think what happened is, I updated the Nvidia drivers to the current version from the version 535

**Comment by danieljohnson2** [comment]
Well it looks like the new driver is counting from 1 instead of 0 for some reason. 

But if the master works for you, you should be able to use it to re-select your GPU, and then the 0.5.17 release should work again.

**Comment by friishon** [comment]
Sorry, can you explain me how to do that?

**Comment by danieljohnson2** [comment]
Open up "Preferences" from the hamburger menu; go to "Global options". In the "Display" section you should see a "GPU" setting; pick your favorite GPU, or choose 'Auto'.

**Comment by friishon** [comment]
Sorry for the late reply, I was working
Now it's fixed

It was selected "auto"  in the GPU but still the error, so i changed to the NVIDIA and the worked
I changed again to "auto" and works perfectly

Thanks for your help

**Comment by danieljohnson2** [comment]
That sounds right- it showed Auto because it it didn't know what to do with "card0". You should be all set now, and you can throw away your copy of the master branch and just use 0.5.17 now.
