### ISSUE TITLE
v0.5.17: create 'url' error

### ISSUE THREAD

**Issue by muelli01** [lutris/lutris#5622]
### Bug description

Whenever I try to install a game from executable or from lutris.net/script, I receive this 'url' error.

### How to Reproduce

1. Start Lutris 0.5.17
2. Click "+"
3. CLick "install game from executable"
4. Enter name/other data (no matter what)
5. Click "install" and again "continue"
6. Error message pops up

Same procedure when installing from a lutris.net script.

### Expected behavior

Envirenment to be created and setup.exe to be selected and run.

### Log output

```shell
'url'

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 442, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)

  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(

  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 489, in install
    self.download_and_extract(runner_version_info["url"], **opts)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^

KeyError: 'url'
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: NO
[System]
OS: Linux Mint 22 Wilma
Arch: x86_64
Kernel: 6.8.0-45-generic
Desktop: X-Cinnamon
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5700G with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 46.8 GB
Swap: 2.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.8.0-45-generic)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.1
Vulkan Version: 1.3.275
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.274)
```

**Comment by danieljohnson2** [comment]
This looks like #5575, which is that you don't have Wine installed. If so, you should install your system's Wine package and also the default Wine version in Lutris. See #5575 for a helpful screenshot.

In master you will get a better error but the actual fix is the same.

**Comment by muelli01** [comment]
Wine is installed, I have already a couple of older games installed from previous Lutris versions and those work perfectly.
Even the system info above shows "Wine installed: YES"

**Comment by danieljohnson2** [comment]
Blah. Okay, it's something else.

I'd like to know which Wine version you are trying to run. You can get a more helpful error if you run the master code, which has been improved here. [Download it here](https://github.com/lutris/lutris) and just run the ``bin/lutris`` script- no need to install. Give me the new, improved error message- it should say what it was trying to download.

**Comment by muelli01** [comment]
Seems Lutris (now) has a problem with wine-staging being installed:


The 'winehq-staging' version of the 'wine' runner can't be downloaded.

Traceback (most recent call last):

  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(

  File "/home/user/src/lutris/lutris/runners/runner.py", line 499, in install
    raise RunnerInstallationError(

lutris.runners.RunnerInstallationError: The 'winehq-staging' version of the 'wine' runner can't be downloaded.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/user/src/lutris/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/user/src/lutris/lutris/gui/installerwindow.py", line 453, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)

  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)

  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 283, in install_runner
    raise ScriptingError(ex.message) from ex

lutris.installer.errors.ScriptingError: The 'winehq-staging' version of the 'wine' runner can't be downloaded.

Lutris log:
[INFO:2024-09-30 18:52:35,041:application]: Starting Lutris 0.5.17
[INFO:2024-09-30 18:52:35,078:startup]: "card1" is AMD Radeon Graphics (1002:1638 1043:8809 amdgpu) Driver 24.0.9
[INFO:2024-09-30 18:52:41,979:interpreter]: Runner wine needs to be installed
[ERROR:2024-09-30 18:52:41,987:interpreter]: The 'winehq-staging' version of the 'wine' runner can't be downloaded.
[ERROR:2024-09-30 18:52:41,987:errors]: The 'winehq-staging' version of the 'wine' runner can't be downloaded.
[ERROR:2024-09-30 18:52:41,987:exception_backstops]: Error handling idle function: The 'winehq-staging' version of the 'wine' runner can't be downloaded.
Traceback (most recent call last):
  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 276, in install_runner
    runner.install(
  File "/home/user/src/lutris/lutris/runners/runner.py", line 499, in install
    raise RunnerInstallationError(
lutris.runners.RunnerInstallationError: The 'winehq-staging' version of the 'wine' runner can't be downloaded.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/src/lutris/lutris/exception_backstops.py", line 76, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/lutris/lutris/gui/installerwindow.py", line 453, in launch_install
    if not self.interpreter.launch_install(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 209, in launch_install
    self.install_runners(ui_delegate)
  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 263, in install_runners
    self.install_runner(self.runners_to_install.pop(0), ui_delegate)
  File "/home/user/src/lutris/lutris/installer/interpreter.py", line 283, in install_runner
    raise ScriptingError(ex.message) from ex
lutris.installer.errors.ScriptingError: The 'winehq-staging' version of the 'wine' runner can't be downloaded.

**Comment by danieljohnson2** [comment]
That's the improved error.

Curious though. I tried to remove my copy of 'winehq-staging' and I could not get the same error.

That's the one located at ``/opt/wine-staging/bin/wine``. Can you check to see what you have at at that path?

**Comment by muelli01** [comment]
~$ ll /opt/wine-staging/bin/wine
-rwxr-xr-x 1 root root 13672 Sep 22 01:37 /opt/wine-staging/bin/wine*

~$ /opt/wine-staging/bin/wine --version
wine-9.18 (Staging)

**Comment by danieljohnson2** [comment]
It looks like Wine Staging is there, but Lutris thinks it is not. I've put together a branch with a bunch of extra logging. [Please download this branch](https://github.com/lutris/lutris/tree/dj/wine_whining) and run the ``bin/lutris`` script within- no need to install. Install your game and give me the log spam.

There should be extra stuff in there that may help me understand this.

**Comment by strycore** [comment]
Marking as fixed. Maybe...
