### ISSUE TITLE
Runner not detected

### ISSUE THREAD

**Issue by elogicuk** [lutris/lutris#5623]
### Bug description

Trying to use this runner with lutris (its a special patched dualsense proton runner)

https://github.com/ClearlyClaire/wine/releases/tag/proton-wine-9.0-1%2Bdualsense

its not detected, but it works with bottles 

### How to Reproduce

download the runner and place it here

~/.local/share/lutris/runners/

it does not appear in the lutris runners list

### Expected behavior

the runner should appear in the lutris list but it does not

### Log output

```shell
not needed
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Garuda Linux Soaring BirdOfPrey
Arch: x86_64
Kernel: 6.10.9-zen1-2-zen
Desktop: GNOME
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 62.7 GB
Swap: 62.7 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4070/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce RTX 4070 (1.3.280)
```

**Comment by danieljohnson2** [comment]
Lutris does not work like that. The only runners it loads at runtime are the JSON ones, loaded from ``/usr/share/lutris/json``. But what you have is not a runner anyway.

What you are doing is adding a new version of Wine. Those go in ``/home/danj/.local/share/lutris/runners/wine/``; try putting it in there. Then, use the Wine runner and select your Wine version instead of the default one.

**Comment by elogicuk** [comment]
> What you are doing is adding a new version of Wine. Those go in `~/.local/share/lutris/runners/wine/`; try putting it in there. Then, use the Wine runner and select your Wine version instead of the default one.

this is where i tried to place it, and it does not show up in the list.

**Comment by strycore** [comment]
Instead of making stuff up and extracting that Proton build in a fantasy location of my choosing, I followed the instructions written on the Github release page and it turns out it works without any issue.


![Screenshot_20240929_104228](https://github.com/user-attachments/assets/f25bce24-1f8c-4c76-bff0-3067607665ec)

**Comment by strycore** [comment]
>  Those go in ~/.local/share/lutris/runners/wine/

it's not a version of Wine. it's a version of Proton. They go in ~/.steam/root/compatibilitytools.d/

**Comment by elogicuk** [comment]
> Instead of making stuff up and extracting that Proton build in a fantasy location of my choosing, I followed the instructions written on the Github release page and it turns out it works without any issue.
> 
> ![Screenshot_20240929_104228](https://private-user-images.githubusercontent.com/280336/371877520-f25bce24-1f8c-4c76-bff0-3067607665ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTM2MjAsIm5iZiI6MTcyNzY1MzMyMCwicGF0aCI6Ii8yODAzMzYvMzcxODc3NTIwLWYyNWJjZTI0LTFmOGMtNGM3Ni1iZmYwLTMwNjc2MDc2NjVlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQyMzQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGVlMjhjYTg4MmYyMTNiNzk3NzA1YzA2YjA4YTMzNmE0M2Y4YWM3MzBjNzUxMzJjNWIxOThjOGY0ZDg2NjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RVmGqWQuUKc8a8DQja02nTiK9tyV50K1EtcRVlqg9dA)

No need to be a dick brother....glad i dont look like you haha your one ugly mofo.
