### ISSUE TITLE
Improvement: Add finish button in dialog that shows which prev. installed game(s) has been imported to Lutris successfully

### ISSUE THREAD

**Issue by amethystgosling163** [lutris/lutris#5628]
I dunno why it isn't there already.

**Comment by danieljohnson2** [comment]
If this is the dialog I think it is, there's a Close button at the bottom, and a bunch of Launch buttons (one per ROM). Is that not enough?

![image](https://github.com/user-attachments/assets/0e54867e-b3b7-49b9-b69c-286d67c944bd)

**Comment by amethystgosling163** [comment]
> If this is the dialog I think it is, there's a Close button at the bottom, and a bunch of Launch buttons (one per ROM). Is that not enough?
> 
> ![image](https://private-user-images.githubusercontent.com/6507403/373016487-0e54867e-b3b7-49b9-b69c-286d67c944bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDI0NTksIm5iZiI6MTcyNzk0MjE1OSwicGF0aCI6Ii82NTA3NDAzLzM3MzAxNjQ4Ny0wZTU0ODY3ZS1iM2I3LTQ5YjktYjY5Yy0yODZkNjdjOTQ0YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDc1NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUyNzA0NDVlOGY2NDkzNmIwNTU0MTc0MmFmODgzZDVkM2NlYjRkMjZlODM2ZjI5YmI1MGNhYzg4OTM0ZDNjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sPqnmlCOF1gYIRUF_lhePQlm9504h4h-fxPGVNYRzOc)

I am talking about this dialog specifically:

https://github.com/user-attachments/assets/c3abdcb9-2acf-4190-b9d5-16095c86f50b

**Comment by amethystgosling163** [comment]
> If this is the dialog I think it is, there's a Close button at the bottom, and a bunch of Launch buttons (one per ROM). Is that not enough?
> 
> ![image](https://private-user-images.githubusercontent.com/6507403/373016487-0e54867e-b3b7-49b9-b69c-286d67c944bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDI5NzEsIm5iZiI6MTcyNzk0MjY3MSwicGF0aCI6Ii82NTA3NDAzLzM3MzAxNjQ4Ny0wZTU0ODY3ZS1iM2I3LTQ5YjktYjY5Yy0yODZkNjdjOTQ0YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDgwNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlhNjgwNmVkNDNhYWQ2ZmY3YzE2M2U0YmUxMmMzNDA1ZWJjYWM3YWU1NDY1OTk2OThmYWUyNzM5MzliMjk4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F7StyH5RjK60WKvq5JX7fNrFwA8iX6XB_leb361d-Y0)

Talking about this dialog specifically:
![Screenshot from 2024-10-03 13-06-30](https://github.com/user-attachments/assets/83272d08-e08b-4c31-8007-922ffcb4063a)

**Comment by strycore** [comment]
We have removed this feature because no one was able to understand it.
