### ISSUE TITLE
Polish: Show waiting cursor when hitting install on an uninstalled game in library

### ISSUE THREAD

**Issue by amethystgosling163** [lutris/lutris#5629]
It takes a while for the install dialog to appear on my internet connection so there should be something to help me wait. Also there should be an indication to the user that it is loading so the user doesn't hit the install button while selecting the uninstalled game (or clicks on it) because he thinks the previous one didn't do anything and so two dialogs appear because they were actually loading at that time - just that the user didn't get any indication of it.

**Comment by danieljohnson2** [comment]
I like polish. I've put in the 'progress' cursor while the installer list is downloading before the InstallerWindow.

You can [download the master branch](https://github.com/lutris/lutris) and try it. No need to install, just run the ``bin/lutris`` script within. Let me know if I missed the installer you are using- there is more than one, and I tried to get them all but you never know.

**Comment by amethystgosling163** [comment]
> I like polish. I've put in the 'progress' cursor while the installer list is downloading before the InstallerWindow.
> 
> You can [download the master branch](https://github.com/lutris/lutris) and try it. No need to install, just run the `bin/lutris` script within. Let me know if I missed the installer you are using- there is more than one, and I tried to get them all but you never know.

I followed your instructions and in the lutris window that appeared, tried clicking install on an uninstalled game in the library, single clicking it after selecting it and opening an installer window for a game in the add new games dialog but I don't know why, no waiting cursor appeared for me.

**Comment by danieljohnson2** [comment]
Sorry, I pushed this fix to the wrong branch. I've fixed that now; please redownload and try again.

**Comment by amethystgosling163** [comment]
> Sorry, I pushed this fix to the wrong branch. I've fixed that now; please redownload and try again.

Its working!
