### ISSUE TITLE
Add option to disable process monitoring

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#563]
Warcraft 3 Reight of Chaos is launched through [RenderEdge](https://www.hiveworkshop.com/threads/renderedge-basic-version.288375/)
[lutris.log.zip](https://github.com/lutris/lutris/files/970941/lutris.log.zip)

**Comment by strycore** [comment]
Could you re-run the game with Wine debugging output enabled (it's in the Runner options in the game's configuration dialog)

**Comment by soredake** [comment]
Sure.
[new_lutris.log.zip](https://github.com/lutris/lutris/files/972027/new_lutris.log.zip)

**Comment by strycore** [comment]
I'll have to try it out myself, I don't see any Wine related crashes.

**Comment by soredake** [comment]
This is how it looks https://f.lewd.se/VpN0gS.mkv

**Comment by soredake** [comment]
Same happens with GTA:SA, but crashes after the initial clip and not in the menu.
[gta-sa.log.zip](https://github.com/lutris/lutris/files/972250/gta-sa.log.zip)

**Comment by soredake** [comment]
Maybe related https://github.com/lutris/lutris/issues/468

**Comment by strycore** [comment]
Can you enable Wine debug output in the runner options and send me back the logs?

**Comment by soredake** [comment]
For what game?

**Comment by strycore** [comment]
Any game that crashes, let's say Warcraft III

**Comment by soredake** [comment]
Old log with debug enabled is not enough?

**Comment by soredake** [comment]
Game is not starting with Full wine debug enabled, only crazy output in terminal and lutris saying 'preparing to launch warcraft 3'.
https://f.lewd.se/G5jxxF_NFsBEVAFBh4c1R5lCBrN.mkv

**Comment by strycore** [comment]
I tried the render edge thing and it would complain about a RenderEdge.dll, the original War3.exe still runs fine though.

**Comment by soredake** [comment]
@strycore this error? 
![error](https://cloud.githubusercontent.com/assets/5204968/25948554/861b6082-3643-11e7-9408-fe3a34f21dad.png)

**Comment by strycore** [comment]
Yep, this exact error

**Comment by soredake** [comment]
My renderedge in C:\RenderEdge, war3 version is 1.26, wine version is 2.7 staging+nine, launched via `wine drive_c/RenderEdge/RenderEdge.exe -classic -opengl`, maybe this will help.

**Comment by strycore** [comment]
I have Warcraft III 1.27, maybe that's why it fails to load?

**Comment by strycore** [comment]
btw, do you have any luck running the original War3 game?

**Comment by soredake** [comment]
@strycore without renderedge?

**Comment by strycore** [comment]
yes, by just running war3.exe

**Comment by soredake** [comment]
Works normal, started game, played company for a minute, no crashes.

**Comment by strycore** [comment]
Alright, so it's an issue with that specific game. Have you tried it outside Lutris? I'm trying to figure out if the issue is related with the game crashing or something related to the process monitor.

**Comment by soredake** [comment]
GTA:SA and mirrors edge too. https://github.com/lutris/lutris/issues/563#issuecomment-298797021
Yes, everything works normal outside of lutris.

**Comment by soredake** [comment]
I will clarify [this](https://github.com/lutris/lutris/issues/563#issuecomment-300326762), Lutris hangs, and after I kill him, the game starts.

**Comment by strycore** [comment]
There seems to be a crash right after the game starts in the video, have you tried running it without the lutris runtime?

**Comment by soredake** [comment]
Runtime disabled already.

**Comment by soredake** [comment]
Enabled lutris runtime leads to your error https://github.com/lutris/lutris/issues/563#issuecomment-300853310.

**Comment by soredake** [comment]
New log (without full debug) after deleting *.reg files in wineprefix.
[war3_new_fresh.log.zip](https://github.com/lutris/lutris/files/994626/war3_new_fresh.log.zip)

**Comment by soredake** [comment]
As a workaround you can add an option to disable monitoring and killing processes.

**Comment by strycore** [comment]
yes, I've been wondering if I should do that, will probably add it.

**Comment by soredake** [comment]
Or just option not to kill, "Stop Game" is useful.
