### ISSUE TITLE
Battle.net Source Missing Games

### ISSUE THREAD

**Issue by zquestz** [lutris/lutris#5637]
While most games show up in the Battle.net source integration, Warcraft II Battle.net Edition and Diablo Immortal are not included.

I dug into the code and they appear to be missing from `util/battlenet/definitions.py` and `services/battlenet.py`.

Figured the original author or maintainer could add these pretty easily, since they handled every other title already.

**Comment by strycore** [comment]
I added both games but I haven't tested anything, I don't own those games.

**Comment by zquestz** [comment]
So Diablo Immortal worked, but Warcraft II Battle.net Edition is not being picked up properly.

**Comment by zquestz** [comment]
I was able to get it detected correctly by using the identifier "w2bn" instead of "w2".

**Comment by strycore** [comment]
> However it seems we are missing some art.

Where is the missing art? In the Battle.net tab or one the other Lutris tabs? 

If it's the Battle.net tab, the artwork does not come from Lutris, it comes from Blizzard.


I changed the ID for Warcraft II

**Comment by zquestz** [comment]
It is missing in both tabs. =\

**Comment by strycore** [comment]
I've attached the IGDB game to the Lutris game, which means it should get a cover during next IGDB sync. For the Battle.net tab, this means it's not fetching the correct image
