### ISSUE TITLE
Allow arguments in prefix command.

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#564]

**Comment by strycore** [comment]
For the Linux version of Steam? Isn't it always available from the current $PATH?

**Comment by soredake** [comment]
I need an custom command to launch it (steam runtime causing problems many years).
https://wiki.gentoo.org/wiki/Steam/Client_troubleshooting#libGL_fails_to_load_driver
>The Steam runtime overrides various system libraries, including libgcc, libstdc++, and libgpg-error with its own bundled versions[4]. This can result in Steam failing to start with the following error:

**Comment by soredake** [comment]
Or better to say otherwise, I would like to be able to set the per-game/global runner (Wine/WineSteam/Steam and maybe others) command prefix.

This will allow thing like firejail (to protect myself against something like this https://github.com/ValveSoftware/steam-for-linux/issues/3671), LD_PRELOAD for probmelatic steam runtime an other.
My example prefix that i use with steam `firejail --profile=/etc/firejail/steam.profile -- env LD_PRELOAD='/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/32/libstdc++.so.6:/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6' STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LIBGL_DEBUG=verbose`

**Comment by strycore** [comment]
We already have command prefix and environment variables in the system options, is that enough for using steam in firejail.

(Also, at some point we might add a firejail option as well)

**Comment by soredake** [comment]
>We already have command prefix
For all command's, not for global runner or per-game.

**Comment by soredake** [comment]
My deepest apologies, I did not notice this.

Tried prefix with steam game, get this:
`
ERROR    2017-05-11 15:10:36,997 [thread]:[Errno 2] No such file or directory: "firejail --profile=/etc/firejail/steam.profile -- env LD_PRELOAD='/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/32/libstdc++.so.6:/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6' STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LIBGL_DEBUG=verbose steam"
`

**Comment by strycore** [comment]
oh yes, I thought that was fixed but it isn't.
The command prefix currently only allows for one command but no arguments. I'll try to fix that in 0.4.10

**Comment by strycore** [comment]
@soredake The latest commit should now fix this, can you try it out? (or if not, you can wait for next week's release)

Not sure about the `-- env …` part though, you might have to use both `prefix_command` and `env` options

**Comment by soredake** [comment]
@strycore 
>Not sure about the -- env … part though, you might have to use both prefix_command and env options

I've need to pass env only to steam and not to firejail or games, so env is my way to do this.

The prefix with the arguments now works, thanks.
