### ISSUE TITLE
Polish: Show spinning cursor while opening Lutris

### ISSUE THREAD

**Issue by amethystgosling163** [lutris/lutris#5645]

**Comment by danieljohnson2** [comment]
Is this possible for us? Isn't this something the desktop environment does?

**Comment by amethystgosling163** [comment]
> Is this possible for us? Isn't this something the desktop environment does?

Researched and found out that adding `StartupNotify=true` to the .desktop file would fix the issue and show the spinning cursor while the app is loading.

**Comment by danieljohnson2** [comment]
Good lord, it just started doing the cursor on startup. There's some kind of caching going on that I don't know how to manage.

**Comment by danieljohnson2** [comment]
Figure it out; just need to move or rename the .desktop file and it notices the change.

That setting seems to do the trick, so I've updated the .desktop file in master to contain the setting.
