### ISSUE TITLE
[Feature Request] Configure/Categorize Uninstalled Games

### ISSUE THREAD

**Issue by The64thGamer** [lutris/lutris#5647]
My Steam library mainly consists of 90% uninstalled games, as I only install what I currently play. This leads to issues with configuring Lutris.

Requests:
1. Allow uninstalled games to be sorted into categories.
2. Allow uninstalled games to have their settings changed. This is partially implemented with the "locate installed game" menu, but any changed settings (like name and thumbnail) won't be saved if an app isn't actually located. This also goes for missing artwork on old Steam games, where the lutris.net alternative art will install- but not actually display.
3. An option to disable uninstalled games being grayed out.

**Comment by strycore** [comment]
Uninstalled games can be categorized. You are confused between uninstalled games and service games. 

We will likely add every  service game as an uninstalled game because people keep getting confused by this
