### ISSUE TITLE
error 256 on every game

### ISSUE THREAD

**Issue by Jabklip** [lutris/lutris#5649]
### Bug description

everything of this happened I tried installing game from flathub with the source on lutris, giving on every game I tried installing the " error 256 ", after trying update flathub source the error says " string indices must be integers, not 'str' "  and now I have a problem with any game on lutris, it doesn't run even if the game is from another runner or is for emulation, everything give the same 256 error

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

Run the game

### Log output

```shell
I've tried and before it gave me error " Failed to load module "appmenu-gtk-module": 'gtk_module_display_init': /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libwindow-decorations-gtk-module.so: undefined symbol: gtk_module_display_init "
and now run lutris and doesn't even gave me a debug info, but the bug remains
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Debian GNU/Linux 12 bookworm
Arch: x86_64
Kernel: 6.1.0-26-amd64
Desktop: KDE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
Physical cores: 2
Logical cores: 4
[Memory]
RAM: 11.6 GB
Swap: 1.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 535.183.01
OpenGL Core: 4.6.0 NVIDIA 535.183.01
OpenGL ES: OpenGL ES 3.2 NVIDIA 535.183.01
Vulkan Version: 1.3.239
Vulkan Drivers: NVIDIA GeForce GTX 1050 (1.3.242)
```

**Comment by strycore** [comment]
We had an issue with the Flathub source but it's fixed now
