### ISSUE TITLE
opening java jar files through lutris

### ISSUE THREAD

**Issue by clessley** [lutris/lutris#565]
Related [via forum](https://forums.lutris.net/t/for-scott/206). Maybe related to #552 (?). I don't see java listed in supported types [here](https://lutris.net/about/), apologies if this bug is a non-starter. Using Ubuntu MATE 16.04.2+ LTS 64-bit.

I have a in-development game that runs perfectly when pumped through the command line with `java -jar mylocation/mygame.jar`.

When I try entering this into the various fields in Lutris it cannot be found or not correct type message.

Other games (which are not jar files run correctly; wine, local and emulators, etc).

I'd like to eventually run this game from a D-link NAS-style shared network location (if that's even possible).

**Comment by strycore** [comment]
We don't have nor do we plan to support a Java runner. In Lutris, Java games are simply considered to be Linux games. For convenience, we have a downloadable version of Java 8 which can be used in installer.

Please see the Minecraft installer to see how it's done: https://lutris.net/games/install/59/view
