### ISSUE TITLE
Polish: Make some windows unmaximizable, floating and attached to Lutris

### ISSUE THREAD

**Issue by amethystgosling163** [lutris/lutris#5650]
These windows are Lutris preferences, runner option, "Add New Games" / game installation windows. The windows need to stay on top of Lutris because in TWMs and GNOME with tiling extensions the windows don't really feel associated to Lutris since they are tiled separately instead of floating on top of the parent lutris window.

**Comment by danieljohnson2** [comment]
Mmmaybe.

I put in code in to break the link to the main window so these windows could be ordered behind it, because not being able to access the main window properly annoys me. But that trick doesn't work on Wayland (Mutter at least).

Perhaps I should just let it be attached in this way.

**Comment by strycore** [comment]
No. Please don't.

Installation windows are windows and not dialogs for a reason. They are meant to be usable even without having the client open.
