### ISSUE TITLE
Ruffle: Add support for arguments

### ISSUE THREAD

**Issue by KlfJoat** [lutris/lutris#5655]
Hi, there

Great tool, I love Lutris!

I've just got a new Flash game, and I'm using the Ruffle runner, obv. Because it's an early 2000s game, it's got a lot of bad habits, like a small place to click to continue, and if you miss it opens a URL to a now-defunct website.

I looked into the Configuration to use Ruffle's `--open-url-mode` option, but I couldn't find a way to add that argument and make it work. For aesthetics, I also want to remove the Ruffle GUI with `--no-gui`, but couldn't find a way to make it work.

Would it be possible to make the following two enhancements to allow the configuration of a Ruffle game?

1. Let me specify arguments, like I can do with Wine games. (likely quick & easy, but not very user-friendly)
2. Create controls in the Runner Options of a configuration for some or all of the Ruffle command-line arguments, and transparently enact the correct argument. (likely time-consuming and harder, but highly user-friendly)

For example, `--no-gui` could be a simple checkbox, defaulting to not checked. `--open-url-mode` would probably be 3 radio buttons, with the Ruffle default ("allow") as the radio default. That kind of thing.

Thanks for considering this enhancement! I hope you can do my \#1 quickly, then put \#2 on the backlog.

**Comment by danieljohnson2** [comment]
Well, ``--no-gui`` is already there, but I think these options make sense, so I've popped a PR to add them.

But I am not too sure this will make 0.5.18; I may have put this together too late.

**Comment by danieljohnson2** [comment]
Or maybe it wasn't too late. It was quite modest really.

**Comment by KlfJoat** [comment]
Wow. Thanks a bunch for getting to this so quickly.

**Comment by KlfJoat** [comment]
> Well, `--no-gui` is already there

FYI, it is not already there in the latest .deb release on GitHub, v0.5.17. The only runner options I have are Graphics backend, Power preference, Proxy, and Custom executable (that doesn't allow me to append options). 

GitHub Releases is where https://lutris.net/downloads tells me to download the latest version for my Ubuntu gaming machine. If there's a better or more up to date version I should be using to get versions for Ubuntu, please let me know.

**Comment by danieljohnson2** [comment]
Sorry I was not more clear. It's there in master; it will be in 0.5.18, like these two new options. It wasn't in 0.5.17.
