### ISSUE TITLE
Lutris.net is blocking my requests

### ISSUE THREAD

**Issue by NGSpace** [lutris/lutris#5656]
### Bug description

Every time I try to access lutris.net I get a message saying that I have been blocked despite it being my first time entering

### How to Reproduce

Go to lutris.net

### Expected behavior

Website will load

### Log output

```shell
not related to the app
```

### System Information

```shell
OS: Fedora 40
ISP: Partner Communications Ltd.
Country: Israel
```

### Media (optional)

![image](https://github.com/user-attachments/assets/78245e85-8092-478b-861c-5eb76a996456)

**Comment by danieljohnson2** [comment]
I suspect this belongs [over here](https://github.com/lutris/website) actually.

**Comment by NGSpace** [comment]
I made an issue there.

https://github.com/lutris/website/issues/711
