### ISSUE TITLE
Battle.net source - protobuf

### ISSUE THREAD

**Issue by Serph91P** [lutris/lutris#5659]
### Bug description

Even with protobuf installed the Battle.net integration is missing on Arch linux.
I found this other issue where they said they fixed it by installing: https://github.com/lutris/lutris/issues/5174

Dunno if it is good to downgrade to version 3.2.0 when the version curently installed is 28.2-3

### How to Reproduce

Install lutris with all its recommended dependencies on Arch linux.
Try enabling Battle.net Source.
Its not there.

### Expected behavior

Battle.net integration works

### Log output

```shell
lutris -d
2024-10-17 16:14:30,021: Unable to run command, qdbus not found
2024-10-17 16:14:30,077: The Battle.net source is unavailable because Google protobuf could not be loaded: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: EndeavourOS rolling rolling
Arch: x86_64
Kernel: 6.11.3-zen1-1-zen
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.3 GB
Swap: 34.4 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.59, 6.11.3-zen1-1-zen)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.4-arch1.1
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.4-arch1.1
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.4-arch1.1
Vulkan Version: 1.3.295
Vulkan Drivers: AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.289)
```

### Media (optional)

![grafik](https://github.com/user-attachments/assets/f005541d-3181-4074-b81c-25fbbb4bbda9)

**Comment by zquestz** [comment]
There is an updated PKGBUILD for lutris-git in the comments that fixes this. I noticed this a while ago and put together a fix that hasn't been added yet.

https://aur.archlinux.org/packages/lutris-git

Maybe you can also test it and ping the maintainer to update the AUR repo.

**Comment by zquestz** [comment]
This is now fixed on all Arch lutris packages. They incorporated my fix into both lutris and lutris-git.

**Comment by danieljohnson2** [comment]
It appears that they know the mystic runes to get an updated protobuf protos thingy, so that their Lutris will be compatible with the latest version of protobuf.

**Comment by strycore** [comment]
> This is now fixed on all Arch lutris packages. They incorporated my fix into both lutris and lutris-git.

Nice
