### ISSUE TITLE
Feature Request: Add support for updating games manually

### ISSUE THREAD

**Issue by Alerymin** [lutris/lutris#5664]
**Problem**
I just ran into a game that needed to update. The update needed to be done manually using a downloaded zip, same kind used to install the game.
I had to move the files manually to the folder to update the game.

**Solution**
Add feature to basically re-run the install script and allow updates like this

**Comment by danieljohnson2** [comment]
We do offer updates from some game stores; GOG and Itch.IO specifically. There's an "Install Updates" command in the context menu for these games.

You are not being too clear on the scenario *you* have in mind however. What game is it? Where did it come from? How does re-running the install script help?

**Comment by Alerymin** [comment]
The game I had the issue With is IFSCL.

The install script for it installs the game launcher, named Kolossus Launcher. The launcher is shipped as a zip archive.

When there is an update to the launcher, it makes the user download the latest zip. But to update the game, the user needs to replace the old launcher files with the new files, and there is nothing to allow doing this in Lutris from what I've seen.

I think using the "install another version" can do it but it's not very intuitive

**Comment by strycore** [comment]
> I think using the "install another version" can do it but it's not very intuitive

It's not very intuituitive because this is not what this feature is for.  "Install another version" will install another copy of the game, leaving you with 2 different copies.

If you want a standalone game to update, you need a script on the website to handle that. This script will use the `extends` directive to run in the context of your currently installed game. This will not create a new game entry.

**Comment by Alerymin** [comment]
> If you want a standalone game to update, you need a script on the website to handle that. This script will use the extends directive to run in the context of your currently installed game. This will not create a new game entry.

So basically just making the same script but replacing "installer" by "extends" should work ?

**Comment by strycore** [comment]
Example installer: https://lutris.net/games/install/19261/view

**Comment by Alerymin** [comment]
Ok Thanks
