### ISSUE TITLE
MAME installer is broken

### ISSUE THREAD

**Issue by crusader-mike** [lutris/lutris#5672]
### Bug description

Tried to install a ZX spectrum game, Lutris (5.18) tried to install MAME and got stuck. I think I found the offending line in the source code.

Pretty sure this function takes path to a directory, not file (also it probably makes sense to rename `get_disk_size` to `get_dir_size`:
https://github.com/lutris/lutris/blob/4b163b59bafe8ced64ee10d505a00444fd47c79a/lutris/runners/mame.py#L27

I think this check can be removed -- if `write_xml_list()` succeeded that file HAS to be there. What if directory was already there with some file present -- in this case, if `mame.xml` creation failed, we'll get a false positive 

### How to Reproduce

- get a clean Lutris install from github (on a machine that has no MAME installed?)
- via Lutris.net add a ZX Spectrum game to your library (e.g. Saboteur!)
- try to install the game

### Expected behavior

Ideally Lutris should install all dependencies (MAME, Speccy, etc) and you know -- work.

### Log output

```shell
[INFO:2024-10-21 09:21:56,333:application]: Starting Lutris 0.5.18
[INFO:2024-10-21 09:21:56,362:startup]: "card1" is AMD Radeon Graphics (1002:164e 1043:8877 amdgpu) Driver None
[INFO:2024-10-21 09:21:56,473:startup]: "card2" is NVIDIA GeForce RTX 4060 (10de:2882 1462:5161 nvidia) Driver 560.35.03
[ERROR:2024-10-21 09:21:56,479:system]: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
[INFO:2024-10-21 09:21:56,500:startup]: "card0" is No GPU (simple-framebuffer) Driver None
[INFO:2024-10-21 09:22:01,884:interpreter]: Runner mame needs to be installed
[INFO:2024-10-21 09:22:18,657:mame]: Writing full game list from MAME to /home/crusader/.cache/lutris/mame/mame.xml
[INFO:2024-10-21 09:22:20,486:mame]: MAME XML list written to /home/crusader/.cache/lutris/mame/mame.xml
[WARNING:2024-10-21 09:22:20,513:mame]: MAME did not write anything to /home/crusader/.cache/lutris/mame/mame.xml
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Pop!_OS 22.04 jammy
Arch: x86_64
Kernel: 6.9.3-76060903-generic
Desktop: pop:GNOME
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 7900X3D 12-Core Processor
Physical cores: 12
Logical cores: 24
[Memory]
RAM: 61.9 GB
Swap: 20.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.280
Vulkan Drivers: NVIDIA GeForce RTX 4060 (1.3.280), AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) (1.3.274)
```

**Comment by danieljohnson2** [comment]
I see that get_disk_size doesn't handle a single file and I've fixed that. But I am stilling getting a hang on that game's installer none the less; I can't see how MAME's weird XML thing plays into that at all.

I'll poke around with this.

**Comment by danieljohnson2** [comment]
Got it. The MAME installing is missing an explicit callback it needs to make to continue the install. I've added that in and it works for me.

To test it, [download the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within - no need to install. I'm pretty sure it will work.

Until this ships in 0.5.18, a simple workaround is to just install MAME first in the preferences dialog.

Thanks for reporting this, @crusader-mike.

**Comment by crusader-mike** [comment]
Thank you, @danieljohnson2. It installs now. Alas, Saboteur! refuses to start, here is the log:
```
Started initial process 31402 from gamemoderun /home/crusader/.local/share/lutris/runners/mame/mame -skip_gameinfo -inipath /home/crusader/.mame -video opengl -uimodekey SCRLOCK spectrum
Start monitoring process.
spectrum.rom NOT FOUND (tried in spectrum)
Fatal error: Required files are missing, the machine cannot be run.
Monitored process exited.
Initial process has exited (return code: 512)
All processes have quit
Exit with return code 512
```

Any idea what is going on? Looks like something (MAME?) needs a `spectrum.rom`... Why it wasn't installed and where do I need to put it?

**Comment by crusader-mike** [comment]
I found `spectrum.zip` (hint: Wow! google) and put it into `/home/crusader/.local/share/lutris/runners/mame/roms`, now starting game in lutris runs MAME with Spectrum ROM. Which means I get plain ZX Spectrum, no game loaded -- in fact, if you check the log, you'll notice game rom is not mentioned at all. Trying to figure it how to load game manually.

**Comment by crusader-mike** [comment]
@danieljohnson2 I think I found another problem -- Lutris is supposed to pass a "-dump <path-to-z80-file>" parameter to mame. Without this MAME simply run default ZX Spectrum machine and you have to manually load game snapshot using super-non-friendly mame UI (ScrollLk, Tab, File Manager, Snapshot, pick your z80 file). It took me inordinate amount of time to find all this info online...

Also, for some reason I can't start MAME in terminal (but Lutris can):
```
crusader@numenor:~$ /home/crusader/.local/share/lutris/runners/mame/mame
/home/crusader/.local/share/lutris/runners/mame/mame: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```
any idea what I need to do?

**Comment by crusader-mike** [comment]
Manually selecting ROM file in "Game options" tab of game configuration fixed the issue -- now `-snapshot <path-to-ROM>` is passed to MAME. Problem is that this field should be populated during game install.

So, to summarize all issues:
- missing spectrum ROM
- missing entry for game ROM in configuration
- ability to run MAME in terminal

Please, help! :)

**Comment by danieljohnson2** [comment]
I do not know that we wish to distributed Sinclair's copyrighted ROMs. Clive is dead, but MAME supports many machines and if we supply this ROM, people we demand that supply them all. Nintendo, in particular, are a bunch of psychos about owning and controlling everything they can whether it makes sense or not.

I think you can configure a snapshot but the UI is not great- a giant list of 'devices' that lists Snapshot *twice*; the second one is really the ``-dump`` option, and I've altered the text so it is 'Snapshot (dump)'. Just use the first one.

This is not a very good UI, but I do not understand MAME very well, so it's hard for me to design a replacement.

If you wish to run MAME from the command line, maybe do not use the Lutris runner for that. Install MAME separately, perhaps from your distributions repository.

**Comment by crusader-mike** [comment]
> I do not know that we wish to distributed Sinclair's copyrighted ROMs. Clive is dead, but MAME supports many machines and if we supply this ROM, people we demand that supply them all. Nintendo, in particular, are a bunch of psychos about owning and controlling everything they can whether it makes sense or not.

I see... it makes sense, but it would be nice to at least mention it during installation. I've never used MAME before and had no idea what `spectrum ROM` is -- it wasn't too hard to figure it out with google, but most people aren't very technical. It took me about 1.5hours to clear all hurdles I've got and I am (hopefully) well above average person (in terms of being technical).


> I think you can configure a snapshot but the UI is not great- a giant list of 'devices' that lists Snapshot _twice_; the second one is really the `-dump` option, and I've altered the text so it is 'Snapshot (dump)'. Just use the first one.
> 
> This is not a very good UI, but I do not understand MAME very well, so it's hard for me to design a replacement.

I think you misunderstood me here -- problem was that after installation `ROM file` field was empty, I had to figure out that I need to fill it for game to work:

![image](https://github.com/user-attachments/assets/5053a6c7-eb70-48a0-ab29-7ed280d4c6bf)


> If you wish to run MAME from the command line, maybe do not use the Lutris runner for that. Install MAME separately, perhaps from your distributions repository.

I needed it to retrace/reproduce steps Lutris does (based on what I see in logs) to figure out why the game doesn't start. It would be nice to be able to do the same commands Lutris does for troubleshooting

**Comment by danieljohnson2** [comment]
Oh, I see. I looked at the installer script (you can see it from the hamburger memory in the installer window) and it looks like a bug in the script- it wants you to give it a parameter name "rom" and I think that should be "main_file".

I don't usually write these things, so maybe there's a reason for that that I don't know. Maybe it's very a old script and "rom" used to be supported years ago?

**Comment by crusader-mike** [comment]
took me a while to figure out what "hamburger memory" means :D

**Comment by danieljohnson2** [comment]
Hamburger menu in the common tongue!

And now that I look at it again, it does list 'main_file'. Why doesn't this work?

**Comment by crusader-mike** [comment]
> Hamburger menu in the common tongue!

I am from a different world.

> And now that I look at it again, it does list 'main_file'. Why doesn't this work?

maybe because `main_file` is supposed to point to a file in a `$GAMEDIR`?

**Comment by danieljohnson2** [comment]
No, I figured it out. This text in ``installers.rst`` explains:

> Referencing the main file of a game is possible to do at the root level of the
> installer but this information is later merged in the ``game`` section. It is
> recommended to put this information directly in the ``game`` section. If you
> see an existing installer with keys like ``exe`` or ``main_file`` sitting at
> the root level, please move them to the ``game`` section.

But the code to 'later merge' the keys seems to have been lost. I have re-implemented this, and that seems to help the Saboteur! installers work. Please re-download the master branch as above and try it- hopefully it will work better.

**Comment by crusader-mike** [comment]
Thank you! It works.

> But the code to 'later merge' the keys seems to have been lost.

I dare not to ask, lol...
