### ISSUE TITLE
itch.io games don't work (lutris flatpak)

### ISSUE THREAD

**Issue by 00pandora00** [lutris/lutris#5679]
### Bug description

Hi, i want to ask, if currently is  there a problem with the itch launcher of lutris?
in my case game don't show up and reading online i have find some thinks relate to this but no much help:
1. Meaby you have: show only installed game enabled, i don't.
2. Remember that  itch lists of games are not supported. If that is the case the games still will be displayed without list right?
3. flatpak is not update? i have the later flatpak.
4. In a comment in a random page i read that flatpak lutris is not update to the later build. BUT THAT POST IS REALLY OLD AND I HAVE RECEIVED MULTIPLE UPDATES OF LUTRIS AFTER READING IT
5. For some reason until the last time i check this problem don't have a issue open here. 

### How to Reproduce

Log in with itch.io in lutris and nothing happen.

### Expected behavior

Log in with itch.io in lutris and i can see my games.

### Log output

```shell
none
```

### System Information

```shell
Vulkan support: SÍ
Esync support: SÍ
Fsync support: SÍ
Wine installed: SÍ
Gamescope: NO
Mangohud: NO
Gamemode: SÍ
Steam: NO
In Flatpak: SÍ
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.11.5-1-default
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Physical cores: 4
Logical cores: 4
[Memory]
RAM: 15.5 GB
Swap: 2.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon R7 200 Series (radeonsi, oland, LLVM 17.0.6, DRM 3.59, 6.11.5-1-default)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.5 (git-3b9fcb7e4d)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon R7 200 Series (RADV OLAND) (1.3.289)
```

**Comment by danieljohnson2** [comment]
0.5.17 does not read Itch.IO collections, it just shows your owned games. 0.5.18 will also read a collection named 'Lutris' if you create one. But you should be seeing the games you own.

There might be something helpful in your Lutris log. Run ``flatpak run net.lutris.Lutris -d`` at the terminal and then try to reload or log-in to Itch.IO; then give us the terminal spam that results.

**Comment by 00pandora00** [comment]
> 0.5.17 does not read Itch.IO collections, it just shows your owned games. 0.5.18 will also read a collection named 'Lutris' if you create one. But you should be seeing the games you own.
> 
> There might be something helpful in your Lutris log. Run `flatpak run net.lutris.Lutris -d` at the terminal and then try to reload or log-in to Itch.IO; then give us the terminal spam that results.

soo games in "itch collections" are not registered as owned?
 what happen with free games that you do not have "owned"?

Note: I am not sending the log because all my itch games are in some collection. (yea all of them) i use itch for random free games.

**Comment by danieljohnson2** [comment]
There's the problem. The 'owned' games are the ones you have *purchased*.

You should be better served by the next release; you will need to create a collection named 'Lutris' and it will load that.

**Comment by 00pandora00** [comment]
> There's the problem. The 'owned' games are the ones you have _purchased_. They can also be in a collection, but 0.5.17 does not show the free stuff.
> 
> You should be better served by the next release; you will need to create a collection named 'Lutris' and it will load that.

ok, i guess i will have to wait for the next release. thanks for the help.
