### ISSUE TITLE
[0.5.17.1 + 0.5.18] "pressure-vessel-wrap" [...] "Permission denied" when using any other runner than "wine-ge"

### ISSUE THREAD

**Issue by CPioGH2002** [lutris/lutris#5680]
### Find the [solution](https://github.com/lutris/lutris/issues/5680#issuecomment-2441045010) in the post below!
 _(just leaving the description up in case somebody else runs into the same problem)_

### Bug description

You guys are doing great work and I thank you for that in the name of... humanity since we all know that playing videos games comes right after establishing world peace. We currently fail at the first item, so we shouldn't on the second.

**Problem:**
I cannot get rid of the problem mentioned in the title which **prevents me from using any other runner than the "default" wine-ge one**. Previously, I didn't have problems with using "umu"-based runners but then the (small) issue with the files at ~/.local/share/lutris/runtime/umu came along and, even after setting them to "executable", I now run into variants of this:

`pressure-vessel-wrap[27067]: E: Child process exited with code 1: bwrap: setting up uid map: Permission denied`

I only used the **native app** (=no Flatpak, no Snap) from the repos which reported as 0.5.17.1 and as .deb but I also tried the manually cloned git which reports as 0.5.18 and is at commit _9f153287_ as of today.

I would assume that _apparmor_ is playing a role here, but I never changed anything in that regard and wonder why things like bwrap show up at all for those mentioned native app installs. Apparmor only has profiles for "bwrap" in terms of flatpak usage. Those shouldn't apply here.

So it points more to the umu launcher and integration from what I can gather with my limited knowledge. In the post below this OP you can also find a log of a successful game start with the normal "wine-ge" runner. Since that one works while games via Steam directly also do, I think the problem isn't with the OS and its setup but with the "umu" elements.

**Things I already tried:**
- since the system uses _OpenSnitch_, I disabled it for testing: Same result
- uninstall and reinstall **Lutris**; from the repos first, manual as "deb", cloned git: no change in outcome
- clearing especially the "runtime" folder at ~/.local/share/lutris/ and letting it get repopulated: no change
- setting the umu-run and umu_run.py to chmod +x as normal user and sudo: no change, just an avoided error message, ending up in the "bwrap" one from above
- uninstall and reinstall **Steam**, manually clearing all remnants of it in "home" before reinstalling: no change
- uninstall and reinstall the **Nvidia driver**, checking operations with other apps: Everything working
- checking games in general (via Steam and Lutris) by using Proton 9.0.3 in the case of Steam and "wine-ge" in the one of Lutris --> no problems at all with that, games just run
- **searching** previous issues for the "bwrap" item revealed close to zero elements, same goes for Reddit

**Extra notes:**
The logs below will show problems with the Vulkan driver but I couldn't find any when trying other apps (using Vulkan), running "vkcube" or checking "vulkaninfo --summary". The Nvidia driver is the current one for Wayland and X11 and I'm on X11. I removed and reinstalled it, just in case. Same results.

The System Information by Lutris itself (see below) shows a proper Vulkan driver version (with a slight offset re: the version string though), so I guess the startup error is either aimed at different circumstances or simply erroneous.

### How to Reproduce

1. Install Lutris, 0.5.17.1 and/or 0.5.18 - same results with both of them
2. Run a game with the "wine-ge" runner, which will work
3. Switch the runner for that game to any of the "umu" variants
4. See mentioned error in the terminal and the game refusing to start (it tries for a second or so)

### Expected behavior

It _should_ run games via "umu" runners, like it does via "wine-ge". It did so before, on this hardware and OS.

### Log output

_-removed log since the case was solved, see below-_

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.10 Oracular Oriole
Arch: x86_64
Kernel: 6.11.0-9-generic
Desktop: KDE
Display Server: x11


### Media (optional)

I have those runners available on Kubuntu 24.10 with the latest Wine "devel" as a system-wide install:
![runners selection](https://github.com/user-attachments/assets/4e05d713-e025-407e-af45-df1850615466)

**Comment by letaltom** [comment]
> So I went on to **manually install umu launcher** (https://github.com/Open-Wine-Components/umu-launcher/releases) since one can download the .deb files and simply "apt install" them on my 24.10 release. For older ones, using the old "apt", you might have to use `dpkg -i [package name]` instead and check the dependencies.

After updating Lutris from 0.5.18 to 0.5.22 using new deb package installed via apt (on Kubuntu), Battlenet could not be launched. Manually installing umu launcher as you suggested resolved the issue, so thank you, @CPioGH2002  for that 🙂👍
