### ISSUE TITLE
Has someone successfully play League of Legends? 

### ISSUE THREAD

**Issue by bwnjnOEI** [lutris/lutris#5686]
### Bug description

Why does it always prompt that I need to restart the system? I have tried many times. Can no longer play League of Legends on Linux?
![2024-10-29_19-40](https://github.com/user-attachments/assets/d6a899d9-fd3a-4223-aa2d-1325a4cc3fef)

### How to Reproduce

There were no issues during the installation process, and the game was successfully installed.

### Expected behavior

Normal game loading

### Log output

```shell
have nothing
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.9.3-76060903-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i9-14900K
Physical cores:  24
Logical cores:   32

[Memory]
RAM:             62.5 GB
Swap:            20.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Graphics (RPL-S)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL Core:     4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL ES:       OpenGL ES 3.2 Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
Vulkan Version:  1.3.280
Vulkan Drivers:  Intel(R) Graphics (RPL-S) (1.3.274), NVIDIA GeForce RTX 4090 (1.3.280)
```

**Comment by JassonCordones** [comment]
Because they changed their anti-cheat software to vanguard that needs kernel level access and that's not an option in linux. So no, it's not possible to play LoL in linux

**Comment by strycore** [comment]
League of Legends is now using the Vanguard anticheat and cannot be played on Linux
