### ISSUE TITLE
Categories won't delete themselves when I ask

### ISSUE THREAD

**Issue by AshleyPikachu** [lutris/lutris#5687]
### Bug description

Hello, this is for the flatpak version of Lutris, I'm not sure if its only a issue there or not.

Steps
1. Create several populated categories, I am not sure how many are the trigger or not.
2. Remove games to empty the category or attempt to delete the category outright.

Results
1. The category will be empty but still listed.
2. Attempting to delete the category again will fail even with the delete button selected.
3. Adding and removing games does not delete the category.

Other things of Note
1. The last time this bug occurred I emptied the category while a game was running.
2. I use both a SSD and attached HDDs. Lutris itself is on my SSD with the games mostly running from the HDD.

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

Telling a category to delete itself should do that.

### Log output

```shell
I did not know I needed to produce a output file before I reinstalled Lutris, my apologies.

I do not wish to reproduce the bug again without a fix as I've had it appear twice and reinstall takes a bit. I have included my PC specs in my system information. I hope this will be helpful enough.

Thank you.
```

### System Information

```shell
Hardware Model: ASUSTeK COMPUTER INC. PRIME A320M-K
Memory: 31.0 GiB
Processor: AMD® Ryzen 5 2600 six-core processor × 12
Graphics: NVIDIA Corporation TU116 [GeForce GTX 1660 Ti]
Disk Capacity: 500.1 GB

OS Name: Rocky Linux 9.4 (Blue Onyx)
OS Type: 64-bit
GNOME Version: 40.4.0
```

**Comment by danieljohnson2** [comment]
Well, I can't repro this but I see that the category cleanup code has been improved; there used to be an issue where a category would be orphaned if you removed a game while it was in a category, and then you'd see a seemingly empty category. Does not sound like your issue, exactly, but sorta similar.

I'd like you to do a test using *non Flatpak* Lutris; it will be a little tricky to do this without disturbing your Flatpak install.

But if you are game, here's what to do. First, install whatever old non Flatpak Lutris you can get; your distribution's repository may have an old version. This should get you the dependencies we need.

Next, [download the master branch](https://github.com/lutris/lutris) and *do not* install it. Merely run the ``bin/lutris`` script within. This should get the latest code running, but you will see none of your games.

Now you need to install some games to test with. Install games you *do not* already have installed via Flatpak- you do not want to overwrite the games that are already in your ``~/Games`` directory, as all the different versions of Lutris share that directory.

Once you have some games, you can try to reproduce the issue. I hope you won't be able to, but if you can, now you can capture a log for us.

When you are done, you  will want to delete these extra games and uninstall your distribution's Lutris. If you are still able to reproduce the problem, you may wish to delay that cleanup until we've had a chance to fix this- I expect I may ask you to test again.

**Comment by danieljohnson2** [comment]
If all that sounds too scary, you can perhaps just hope that we've already got this fixed and wait for 0.5.18.

**Comment by strycore** [comment]
Empty  categories are perfectly fine, removing all games from a category will not delete it. Let me illustrate:


![the-useless-box-turns-itself-off-2152](https://github.com/user-attachments/assets/811c417d-bd85-430a-8034-635ac46dfa35)


Now, deleting a category should work, whether there are games inside it or not.

**Comment by strycore** [comment]
I've deleted a category, and it did the correct thing so all things ok.


Can you imagine how broken it would be if we deleted the category by removing all games inside it? LOL!!!

**Comment by danieljohnson2** [comment]
This bug we had was unkillable undead categories. Very spooky!

This would happen if you deleted a game (removed it from  your library) while it was in a category. Should be fixed now.
