### ISSUE TITLE
Command Line lutris:

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#569]
When running a game directly from the console, Lutris will ask to run the game or install a new version. 

```
lutris lutris:supertux
```

"SuperTux is already installed, would you liek to install a new version, or run the game?"

There are two cases that can happen:

1. Game already installed - Then it should assume you want to play the game
2. Game is not installed - Then it should assume you want to install the game

Using a dialog box ask seems silly. We don't need that.

**Comment by strycore** [comment]
nope, it's not silly, I hate it when I click "Install" on the website and it launches a game without asking me.

Starting with Lutris 0.4.10, actions can be explicitly provided: 

* `lutris:rungame/supertux` will run the game if available
* `lutris:rungameid/123` will run the game with id 123 (used in lutris shortcuts)
* `lutris:install/supertux` will install supertux
* `lutris:supertux` is ambiguous, it will show this dialog if the game is already installed

In a few weeks, all URLs on the website will use the lutris:install/… method (giving users some time to update their client)

**Comment by RobLoach** [comment]
```
lutris:rungame/supertux
```

Ah, that's what I'm looking for! Makes so much sense. Thanks a lot! :+1:

**Comment by RobLoach** [comment]
@strycore Lutris stays open after the game has Quit when using `rungame/`. This makes using [Lutris Steam shortcuts](https://github.com/lutris/lutris/wiki#steam) or the [Lutris Kodi Launcher](https://github.com/RobLoach/lutris-kodi-addon) a bit awkward when using a controller, since you have to manually close Lutris after the game has quit.

Reminded of this XKCD: https://xkcd.com/1172/

Is there a way to make `rungame` just quit Lutris after it was run?

**Comment by B4rabbas** [comment]
how to force installation witheout graphic pop up to confirm ?
like :
lutris -f lutris:install/supertux

Sadly the -f don't work
