### ISSUE TITLE
GOG: No games found

### ISSUE THREAD

**Issue by faulesocke** [lutris/lutris#5698]
### Bug description

After logging in with my GOG account, I just get a screen telling me "No games found". In my GOG library there are plenty of games for both Windows and Linux. Refresh button and restarting lutris does not help. Even re-logging in does not help.

Also a question: What is lutris sending in that last POST request to `lutris.net/api/games/service/gog`? (See log below)

I'm using the version of lutris that is packaged with Void Linux. If you think some dependency or something is missing, please let me know.

### How to Reproduce

1. Go to Sources/GOG
2. Click on the login button, login
4. After login, see the "No games found" screen.

### Expected behavior

I expect to see the games from my library.

### Log output

```shell
DEBUG    2024-11-03 13:49:30,660 [http._request:88]:GET https://embed.gog.com/userData.json
DEBUG    2024-11-03 13:49:31,034 [base.wipe_game_cache:441]:Deleting gog cache <$HOME stripped>/.cache/lutris/gog-library.json
DEBUG    2024-11-03 13:49:31,034 [base.wipe_game_cache:175]:Deleting games from service-games for gog
DEBUG    2024-11-03 13:49:31,046 [http._request:88]:GET https://embed.gog.com/userData.json
DEBUG    2024-11-03 13:49:31,380 [http._request:88]:GET https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=1
DEBUG    2024-11-03 13:49:31,972 [http._request:88]:GET https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=2
DEBUG    2024-11-03 13:49:32,541 [http._request:88]:POST https://lutris.net/api/games/service/gog
```

### System Information

```shell
Vulkan support: NO
Esync support: NO
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: NO
Steam: YES
In Flatpak: NO
[System]
OS: Void rolling void
Arch: x86_64
Kernel: 6.6.52_1
Desktop: Not found
Display Server: Not found
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 3700X 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 62.7 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 18.1.8, DRM 3.54, 6.6.52_1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.6
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.6
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.6
Vulkan Version: 1.3.268
Vulkan Drivers: AMD Radeon RX 7800 XT (1.3.287), AMD Radeon RX 7800 XT (RADV NAVI32) (1.3.289)
```

**Comment by danieljohnson2** [comment]
I can answer part of that- ``https://lutris.net/api/games/service/gog`` is the API to pull down Lutris.net's information about these GOG games. That's stuff like the cover art and banners for them.

I can't say why you aren't seeing the games though. One thing to check is the settings in the hamburger menu (upper right corner); it is set to show only installed games?

And perhaps you could tell us what version of Lutris actually is packaged with Void Linux? The hamburger menu leads to an about box.

**Comment by faulesocke** [comment]
Yes, the setting for only showing installed games was enabled. How could I not see this?! But also seems like a weird default, maybe you want to change this?

Btw, void currently packages v. 0.5.17. I would suggest you also include this info into the "System Information" section or ask for it explicitly in the bug report form.

Anyway, thank you very much for helping me! :) Lutris looks like a very cool software, will definitely get some use out of it!

Feel free to close the issue.

**Comment by danieljohnson2** [comment]
We have changed it already, it was a bug that was even on by default anyway.

The bug form asks for the log, which includes the version. But I should include it in the system information, since people often include that but leave out the log.
