### ISSUE TITLE
Change default value of filter_installed to False

### ISSUE THREAD

**Issue by natanox** [lutris/lutris#5704]
Request to change the default config value `filter_installed` to False so games ain't get hidden when you first start Lutris.

The current default settings lead to a lot of confusion especially for new users who expect their games to show up after connecting to their third-party accounts.
https://forums.lutris.net/t/lutris-cant-find-my-games-on-gog-com/20397

**Comment by danieljohnson2** [comment]
I am fairly sure this has already been done in master, but I will recheck it when I get a chance to do so. 

Bear in mind that your existing install has a saved setting for this, so changing the default won't help you.

Perhaps we should rename the setting in the config file so everyone gets re-defaulted?

**Comment by natanox** [comment]
> I am fairly sure this has already been done in master, but I will recheck it when I get a chance to do so.

If so please disregard this issue. I looked all over the repo but couldn't find the config preset anywhere to check.

**Comment by danieljohnson2** [comment]
It's this code, in ``lutriswindow.py``:
```python

    @property
    def filter_installed(self):
        return settings.read_bool_setting("filter_installed", False)
```

That False is the default value. I'll close this issue as already fixed.
