### ISSUE TITLE
Lutris CLI starts by printing the Usage message of gsettings on Debian Testing

### ISSUE THREAD

**Issue by anohren** [lutris/lutris#5709]
### Bug description

Running a Lutris CLI command on MATE desktop on X11 on i686 Debian Testing (Trixie, upgraded from Debian 12) with Lutris 0.5.17 from the Debian repos gives both shell complaints (`Unknown command`) as well as Usage output from `gsettings`. This is disorienting since I'm interacting with `lutris` and not `gsettings`.

This strikes me as a missing pair of double quotes somewhere.

If _Debian Testing_ is of no interest then feel free to disregard the report.

### How to Reproduce

1. Run `lutris --version` or `--help`
2. The resulting message is: `Unknown command get org.mate.Marco.general` followed by the "Usage:" message for `gsettings` (many lines), followed by the actual output of the command, e.g. `lutris-0.5.17`.

### Expected behavior

Lutris should suppress confusing output from internally used commands

### Log output
Had to run it over SSH to get the output to the machine I'm typing on, but here it is, such as it is:

```shell
lutris -d --version
Error: unable to open display 
2024-11-06 02:23:10,312: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
2024-11-06 02:23:10,313: No available glxinfo output
2024-11-06 02:23:10,314: Invalid glxinfo received

(lutris:18282): Gtk-CRITICAL **: 02:23:12.042: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/games/lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 42, in <module>
    from lutris.gui.config.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3/dist-packages/lutris/gui/config/preferences_dialog.py", line 13, in <module>
    from lutris.gui.config.runners_box import RunnersBox
  File "/usr/lib/python3/dist-packages/lutris/gui/config/runners_box.py", line 9, in <module>
    from lutris.gui.config.runner_box import RunnerBox
  File "/usr/lib/python3/dist-packages/lutris/gui/config/runner_box.py", line 8, in <module>
    from lutris.gui.dialogs.runner_install import RunnerInstallDialog
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 92, in <module>
    class RunnerInstallDialog(ModelessDialog):
  File "/usr/lib/python3/dist-packages/lutris/gui/dialogs/runner_install.py", line 103, in RunnerInstallDialog
    "software-installed-symbolic" if has_stock_icon("software-installed-symbolic") else "wine-symbolic"
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 159, in has_stock_icon
    return theme.has_icon(name)
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'has_icon'
```

Can't say this doesn't look a bit over the top just to tell me the version number though.

Unsurprisingly, running `lutris -d --version` on the machine itself produces identical output to just running `lutris --version`...

### System Information

I can't open Preferences, because Lutris only spits out a non-subscriptable NoneType error. 

I guess I could print it using the CLI, except that I can't do that over SSH because of `AttributeError: 'NoneType' object has no attribute 'has_icon'` for every command over SSH (yes, even `--help`), and even if I could I still can't find an option to print this info when switching to a terminal on the actual machine in question, hence no system summary.

**Comment by strycore** [comment]
lutris is a graphical client and therefore it initializes a bunch of stuff on startup whether it's called without arguments or CLI only arguments.

You have an incomplete install since Lutris is complaining about a missing icon. Does this happen when running Lutris on X11 or is it just SSH?

On my end, when I run lutris from ssh, I only get the glxinfo warning:

```lutris -v  
Error: unable to open display 
2024-11-05 20:18:24,084: ['glxinfo', '-B'] command failed: Command '['glxinfo', '-B']' returned non-zero exit status 255.
2024-11-05 20:18:24,084: No available glxinfo output
2024-11-05 20:18:24,084: Invalid glxinfo received
lutris-0.5.17
```

which I can easily get rid of by redirecting stderr to /dev/null:

```
lutris -v 2>/dev/null
lutris-0.5.17
```

If you fix that icon issue you're experiencing, most of the errors on startup will be gone.

**Comment by strycore** [comment]
We don't need 2 different log messages about glxinfo failing, one can be removed.

**Comment by anohren** [comment]
> You have an incomplete install since Lutris is complaining about a missing icon. Does this happen when running Lutris on X11 or is it just SSH?

Hmm, ok. It only happens over SSH so far. I'll post the local `lutris -d` shortly. 

1. I installed lutris normally with apt
2. Found out that I couldn't open preferences due to what looked like a broken assumption about `wine_version_info` (the NoneType), as though Wine wasn't found (just a quick guess at the time)
3. Installed `wine-devel` 9.20 from winehq official repo, which replaced `wine`, to see if there was any difference (no). 
4. Found in Issues that the Prefs bug has been fixed already

`wine-devel` has never been a problem on e.g. Ubuntu, but I'll mention it for completeness.

**Comment by anohren** [comment]
`lutris -d` on X11 locally:

```
$ lutris -d
Okänt kommando get org.mate.Marco.general

Användning:
  gsettings --version
  gsettings [--schemadir SCHEMAKAT] KOMMANDO [ARG…]

Kommandon:
  help                      Visa denna information
  list-schemas              Lista installerade scheman
  list-relocatable-schemas  Lista flyttbara scheman
  list-keys                 Lista nycklar i ett schema
  list-children             Lista barn av ett schema
  list-recursively          Lista nycklar och värden, rekursivt
  range                     Frågar efter intervallet för en nyckel
  describe                  Frågar efter beskrivningen för en nyckel
  get                       Hämta värdet för en nyckel
  set                       Ställ in värdet för en nyckel
  reset                     Återställ värdet för en nyckel
  reset-recursively         Återställ alla värden i ett angivet schema
  writable                  Kontrollera om en nyckel är skrivbar
  monitor                   Bevaka ändringar

Använd ”gsettings help KOMMANDO” för detaljerad hjälp.


INFO     2024-11-06 14:39:09,124 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at ./vulkaninfo/./vulkaninfo.h:241:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
ERROR    2024-11-06 14:39:09,735 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-11-06 14:39:09,738 [startup.run_all_checks:120]: (8086:27ae 144d:ca00 i915) Driver 24.2.4
DEBUG    2024-11-06 14:39:11,508 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-06 14:39:11,555 [xrandr._get_vidmodes:18]:Retrieving 13 video modes from XrandR
DEBUG    2024-11-06 14:39:12,473 [http._request:88]:GET https://lutris.net/api/runners/wine
ERROR    2024-11-06 14:39:12,796 [config.get_defaults:242]:Unable to generate a default for 'version': argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/config.py", line 240, in get_defaults
    default = default()
              ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 189, in get_default_wine_version
    if "version" in default_version and "architecture" in default_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
DEBUG    2024-11-06 14:39:12,871 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-11-06 14:39:13,688 [api.check_stale_runtime_versions:52]:Modified at ons  6 nov 2024 01:41:28, will update after ons  6 nov 2024 07:41:28
DEBUG    2024-11-06 14:39:13,698 [http._request:88]:GET https://lutris.net/api/runtimes/versions?pci_ids=8086:27AE%20144D:CA00
DEBUG    2024-11-06 14:39:14,027 [runtime._get_runtime_updaters:231]:Skipping runtime p7zip for x86_64
DEBUG    2024-11-06 14:39:14,029 [runtime._get_runtime_updaters:231]:Skipping runtime dxvk-cache-tool for x86_64
DEBUG    2024-11-06 14:39:15,138 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
```

**Comment by danieljohnson2** [comment]
Well, you are getting a bug in the Wine defaults that has been fixed; but the ``gsettings`` thing isn't that, I believe. It's the code that's deciding if you can disable composition or not; that runs only on X11, only on MATE, and only if you visit the System Options of some games configuration. This is pretty obsolete stuff, but we may as well fix it.

I've adjusted the ``gsettings`` command and I think it will work better. Please [download the master branch](https://github.com/lutris/lutris) and try it out. Run the ``bin/lutris`` script in there- no need to install.

I think you won't see that error.

**Comment by anohren** [comment]
Nice. I suspected it'd be only for MATE and X11 since no one else was seeing it :)

I'll report back after testing — I assume I'll also have the benefit of being able to open preferences on master, so that's a bonus. 

And I see it was _technically_ a few missing quotes, but not how I imagined it. It looks correcter, so I'm sure it'll work better. Not that obsolete code is out of place on my obsolete machine.

**Comment by anohren** [comment]
Works fine now 👌Thanks!

The icon error is only present on SSH. Should I ignore it? It appears to me that the GDK_IS_SCREEN assertion failure is due to non-initialized GTK (?) meaning that it's not actually indicative of an incomplete install or a missing icon (?) At least it means that it's not possible to use lutris CLI over SSH, on some machines.

**Comment by anohren** [comment]
Thanks for taking a look @danieljohnson2! 

I think this can be helpful for those of us who prefer to type (on GitHub) on another machine. 

Having that system info CLI printable would maybe also have been nice, but I understand if the complete info can only be collected in a GUI context.
