### ISSUE TITLE
Continuous re-installation of ge-Proton at startup

### ISSUE THREAD

**Issue by PrimaIVoid** [lutris/lutris#5714]
### Bug description

**Almost** every time i try to launch Lutris from terminal or directly from the app, in the lower-left corner it seem to try download/estrac/install the latest version of the **ge-proton** runner, even though in my system and in the config of lutris i already have the latest available ge-proton set and ready to use. Also tried used it with some games as it works without problems

The only output i receive about this behaviour when Lutris is trying to re-download the same runner is:
`2024-11-11 10:03:28,951: No local runtime path in /home/zodiac/.local/share/lutris/runtime/ge-proton`

This warning says the truth since in that directory i don't have any "ge-proton" folder, but for my knowledge all the relevant runners are stored in: 
`/home/zodiac/.local/share/lutris/runners/`
In here in fact i have the latest `wine` and `Ge-Proton` builds that works and are updated by Lutris automatically
I have the feeling this might be related to my setting the default choice of **UMU-Latest** as Wine runner, even though does not seem to be related to ge-proton that is anyhow already installed and available as needed

I have noticed this weird behaviour since about 2 weeks, as of now i'm using the latest v0.5.18

### How to Reproduce

This behaviour is kind of hard to reproduce even for me, since it does **not always** trigger.
After restarting my entire Computer-System and try to open Lutris for the first time it **always** force the ge-proton re-download

After this happens, i may close Lutris and wait a few minutes and try opening it again, and it is always random if it triggers or not the forced re-download of ge-proton

### Expected behavior

Lutris should be aware that the latest version of ge-proton runner is already installed/set and ready on my system, not try to redownload it over again

### Log output

```shell
`2024-11-11 10:03:28,951: No local runtime path in /home/zodiac/.local/share/lutris/runtime/ge-proton`
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: NO
[System]
OS: Linux Mint 21.2 Victoria
Arch: x86_64
Kernel: 5.15.0-125-generic
Lutris Version: 0.5.18
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-6200U CPU @ 2.20GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 8 GB
Swap: 2.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL Core: 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL ES: OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2
Vulkan Version: 1.3.204
Vulkan Drivers: NVIDIA GeForce 840M (1.3.242), Intel(R) HD Graphics 5500 (BDW GT2) (1.3.255)
```

**Comment by danieljohnson2** [comment]
@GloriousEggroll has been putting out a lot of updates to the latest GE-Proton, so you may really be getting new versions of the thing every time, perhaps.

I'd ask if you can get it to do back-to-back downloads. That is, when this happens and it updates ge-proton, just let it finish, then shut down Lutris and restart it at once. Does it ever re-download ge-proton on restart like that? I'd expect it not to.

**Comment by PrimaIVoid** [comment]
I just checked on the Gloriouseggroll releases, it shows the last was 18 hours ago [GE-Proton9-20 Released]
But i already had that installed yesterday by Lutris, and a few minutes ago it installed it again:
```
[INFO:2024-11-11 16:17:50,131:application]: Starting Lutris 0.5.18
[INFO:2024-11-11 16:17:50,887:startup]: "card1" is Intel HD Graphics 5500 (8086:1616 1025:0940 i915) Driver 23.2.1
[INFO:2024-11-11 16:17:51,959:startup]: "card0" is NVIDIA GeForce 840M (10de:1341 1025:0942 nvidia) Driver 535.183.01
[DEBUG:2024-11-11 16:17:54,371:xrandr]: Retrieving resolution list
[DEBUG:2024-11-11 16:17:54,651:xrandr]: Retrieving 33 video modes from XrandR
[DEBUG:2024-11-11 16:17:55,026:path_cache]: Checking for missing games
[DEBUG:2024-11-11 16:17:56,552:api]: Modified at Mon 11 Nov 2024 10:00:43 AM , will update after Mon 11 Nov 2024 04:00:43 PM 
[DEBUG:2024-11-11 16:17:56,553:http]: GET https://lutris.net/api/runtimes/versions?pci_ids=8086:1616%201025:0940,10DE:1341%201025:0942
[DEBUG:2024-11-11 16:17:57,169:runtime]: Runtime icons locally updated on Mon 20 Feb 2023 02:17:24 PM GMT, remote created on Mon 26 Jun 2023 04:34:45 AM )
[DEBUG:2024-11-11 16:17:58,069:http]: GET https://lutris.net/api/runtimes/icons
[DEBUG:2024-11-11 16:17:58,362:downloader]: ⬇ https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton9-20/GE-Proton9-20.tar.gz
[DEBUG:2024-11-11 16:18:05,004:application]: Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f67e0ca1440 (LutrisWindow at 0x5650353102b0)>}
[DEBUG:2024-11-11 16:19:26,735:downloader]: Finished downloading https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton9-20/GE-Proton9-20.tar.gz
[DEBUG:2024-11-11 16:19:26,754:system]: Deleting folder /home/zodiac/.local/share/lutris/runners/proton/GE-Proton
[DEBUG:2024-11-11 16:20:19,909:extract]: Extracting /home/zodiac/.local/share/lutris/runners/proton/GE-Proton9-20.tar.gz to /home/zodiac/.local/share/lutris/runners/proton/GE-Proton
[DEBUG:2024-11-11 16:21:07,856:system]: Deleting folder /home/zodiac/.local/share/lutris/runners/proton/GE-Proton/.extract-556ad023
[DEBUG:2024-11-11 16:21:08,291:extract]: Finished extracting /home/zodiac/.local/share/lutris/runners/proton/GE-Proton9-20.tar.gz to /home/zodiac/.local/share/lutris/runners/proton/GE-Proton
[ERROR:2024-11-11 16:21:08,354:runtime]: No local runtime path in /home/zodiac/.local/share/lutris/runtime/ge-proton
[DEBUG:2024-11-11 16:21:44,550:application]: Removed window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f67e0ca1440 (LutrisWindow at 0x5650353102b0)>}
[DEBUG:2024-11-11 16:21:46,628:application]: Showing window PreferencesDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f67e0ca1440 (LutrisWindow at 0x5650353102b0)>}
```

**Comment by danieljohnson2** [comment]
@B--B has provided a fix that I have merged, so I think your re-installations should stop with the new code.

But it will happen one more time, because the revised revision of this code is no longer giving the GE-Proton version a special name, so it will redownload as "ge-proton" and appear as such in the version drop down.

You can just delete the old ``~/.local/share/lutris/runners/proton/GE-Proton``; it will no longer be updated.

Thanks for the bug report, @PrimaIVoid!
