### ISSUE TITLE
The stray icons show the games I have hidden

### ISSUE THREAD

**Issue by Zebra2711** [lutris/lutris#5733]
Disable a hidden game that appears when you right-click on the system tray icon

![2024-11-21_17-28](https://github.com/user-attachments/assets/ebb08701-185a-4fdb-bfdf-30ee519d4b31)

**Comment by danieljohnson2** [comment]
It's not not hiding hidden games; I'll fix that real quick.

If you like you can try it by [downloading the master branch](https://github.com/lutris/lutris). No need to install, just run the ``bin/lutris`` script within- but first you must fully shut down Lutris. If the old tray icon is up there, there will be no joy. Close that out first.
