### ISSUE TITLE
Installation of GOG games with installer files from USB drive fails (flatpak, 0.5.18)

### ISSUE THREAD

**Issue by mittler-works** [lutris/lutris#5740]
### Bug description

When installing a game from GOG source, I have the choice of downloading the installation files or selecting them. I have my entire GOG library locally on external SSD, which is why I would like to use the local installation files at this point instead of downloading them again.

I can only select one file at this point, even if the installation includes X .bin files. I select the .exe file. The installer starts but then fails and displays:

![lutris_screenshot](https://github.com/user-attachments/assets/a6ae291a-cd4e-4e78-9579-37a4f071eb37)

Apparently only the .exe file is made available to wine and not the .bin files. Interestingly, however, it works if I copy the files from the external SSD to the internal SSD in advance. I cannot say whether this is a problem of Lutris or Flatpak or OS.

The problem occurs reproducibly in every game with at least one .bin file. I am using Lutris 0.5.18 from flathub-beta on the Steam Deck.

### How to Reproduce

1. Get latest lutris from flatpak-beta
2. Download installer files for any windows game from gog where installer has at least one .bin file
3. Copy installer files to USB
4. Try installing the game with installer files from USB

### Expected behavior

I would expect that installation of the game runs fine from installer files stored on USB.

### Log output

```shell
(deck@steamdeck ~)$ flatpak run -v net.lutris.Lutris -d
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/net.lutris.Lutris/x86_64/beta since parental controls are disabled globally
F: Opening user flatpak installation at path /home/deck/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/47/fae6d44488d0ebb809ebef0a0266e1dca82a064d17619d50009b971ae7798bfe/files/lib32 does not exist
F: Cleaning up unused container id 1524805078
F: Cleaning up per-app-ID state for net.lutris.Lutris
F: Allocated instance id 3637940282
F: Add defaults in dir /net/lutris/Lutris/
F: Add locks in dir /net/lutris/Lutris/
F: Allowing homedir access
F: Not sharing "/media" with sandbox: Unable to open path "/media": No such file or directory
F: Not sharing "/home/deck/.config/MangoHud" with sandbox: Unable to open path "/home/deck/.config/MangoHud": No such file or directory
F: Not sharing "/home/deck/.var/app/com.valvesoftware.Steam" with sandbox: Unable to open path "/home/deck/.var/app/com.valvesoftware.Steam": No such file or directory
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/deck/.config/pulse/client.conf': Error opening file /home/deck/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 38 -- xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 39 -- lutris-wrapper -d'
Gtk-Message: 22:01:59.596: Failed to load module "canberra-gtk-module"
INFO     2024-11-21 22:02:00,257 [application.do_command_line:480]:Starting Lutris 0.5.18
INFO     2024-11-21 22:02:00,289 [startup.run_all_checks:120]:"card0" is AMD Custom GPU 0932 (1002:1435 1002:0123 amdgpu) Driver 24.2.7
DEBUG    2024-11-21 22:02:00,509 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-11-21 22:02:00,516 [xrandr._get_vidmodes:18]:Retrieving 4 video modes from XrandR
DEBUG    2024-11-21 22:02:00,643 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-11-21 22:02:00,715 [api.check_stale_runtime_versions:52]:Modified at Thu 21 Nov 2024 06:44:56 PM , will update after Fri 22 Nov 2024 12:44:56 AM
DEBUG    2024-11-21 22:02:00,718 [lutriswindow.create_runtime_updater_cb:1310]:Runtime up to date
DEBUG    2024-11-21 22:02:14,146 [base.install:335]:Installing 2142923325 from service gog
DEBUG    2024-11-21 22:02:14,147 [http._request:88]:POST https://lutris.net/api/games/service/gog
DEBUG    2024-11-21 22:02:14,399 [api.get_game_installers:395]:Fetching installer https://lutris.net/api/installers/greak-memories-of-azur
DEBUG    2024-11-21 22:02:14,399 [http._request:88]:GET https://lutris.net/api/installers/greak-memories-of-azur
DEBUG    2024-11-21 22:02:14,620 [application.show_window:396]:Showing window InstallerWindow2142923325
DEBUG    2024-11-21 22:02:16,736 [xrandr._get_vidmodes:18]:Retrieving 4 video modes from XrandR
DEBUG    2024-11-21 22:02:18,834 [gog.get_extras:340]:Download extras for GOG ID 2142923325 and its DLCs
INFO     2024-11-21 22:02:18,834 [gog.get_game_details:289]:Getting game details for 2142923325
DEBUG    2024-11-21 22:02:18,854 [http._request:88]:GET https://api.gog.com/products/2142923325?expand=downloads&locale=en-US
INFO     2024-11-21 22:02:19,065 [gog.get_game_details:289]:Getting game details for 2142923325
DEBUG    2024-11-21 22:02:19,081 [http._request:88]:GET https://api.gog.com/products/2142923325?expand=downloads&locale=en-US
DEBUG    2024-11-21 22:02:19,171 [http._request:88]:GET https://api.gog.com/products?ids=1664648689%2C1299980508&expand=downloads
INFO     2024-11-21 22:02:19,409 [installer.prepare_game_files:168]:Getting files for goginstaller
INFO     2024-11-21 22:02:19,410 [gog.get_game_details:289]:Getting game details for 2142923325
DEBUG    2024-11-21 22:02:19,425 [http._request:88]:GET https://api.gog.com/products/2142923325?expand=downloads&locale=en-US
INFO     2024-11-21 22:02:19,496 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/2142923325/downlink/installer/en1installer0
DEBUG    2024-11-21 22:02:19,512 [http._request:88]:GET https://api.gog.com/products/2142923325/downlink/installer/en1installer0
INFO     2024-11-21 22:02:19,817 [gog.get_download_info:296]:Getting download info for https://api.gog.com/products/2142923325/downlink/installer/en1installer1
DEBUG    2024-11-21 22:02:19,832 [http._request:88]:GET https://api.gog.com/products/2142923325/downlink/installer/en1installer1
DEBUG    2024-11-21 22:02:20,224 [installerwindow.on_files_prepared:619]:Game files prepared.
DEBUG    2024-11-21 22:02:20,240 [installerwindow.present_installer_files_page:634]:Presenting installer files page
DEBUG    2024-11-21 22:02:29,403 [files_box.on_file_available:108]:goginstaller is available
INFO     2024-11-21 22:02:29,403 [files_box.on_file_available:114]:All files available
INFO     2024-11-21 22:02:29,404 [installerwindow.on_files_available:664]:All files are available, continuing install
INFO     2024-11-21 22:02:29,406 [installerwindow.launch_installer_commands:672]:Launching installer commands
DEBUG    2024-11-21 22:02:29,408 [interpreter._iter_commands:315]:Installer command: {'autosetup_gog_game': 'goginstaller'}
Started initial process 75 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /run/user/1000/doc/a1245e46/setup_greak_memories_of_azur_1.0.6_114_(51079).exe /SP- /NOCANCEL
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 47 Flatpak runtime
Arch: x86_64
Kernel: 6.5.0-valve22-1-neptune-65-g9a338ed8a75e
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Custom APU 0932
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 14.5 GB
Swap: 8.2 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Custom GPU 0932 (radeonsi, vangogh, LLVM 18.1.8, DRM 3.57, 6.5.0-valve22-1-neptune-65-g9a338ed8a75e)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7 (git-3900828265)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7 (git-3900828265)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7 (git-3900828265)
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Custom GPU 0932 (RADV VANGOGH) (1.3.289)
```

**Comment by danieljohnson2** [comment]
I wonder if this is a Flatpak thing. Normally if one of those files is accesible, the others would be, but Flatpak might give you access to only the one file you select, and protect all others from such obviously malicious-sounding software as "Lutris".

Maybe try flatseal to see if you can loosen it up?

**Comment by mittler-works** [comment]
It could very well be that this is a Flatpak thing, yes. I do have flatseal and access to external devices and also access to the mount point (`/run/media/...`) is permitted.

Two things I notice in the log:
1. It says `All files are available, continuing install` - so I think that Lutris can see all files and the permissions are sufficient at this point.
2. It tries to start installation from files in `/run/user/1000/doc/...` and not from `/run/media/...` although I selected the files from `/run/media/...`

I've no  idea what's happening :shrug:

**Comment by mittler-works** [comment]
Ok, this `/run/user/1000/doc/...` thing is explained here: https://flatpak.github.io/xdg-desktop-portal/docs/documents-and-fuse.html

It seems that you are absolutely right and flatpak is just exposing the one .exe file that I have selected. It's still interesting that it works when I am using files from the internal SSD but not when using files from the USB drive.

Do you have any idea how to get around this problem? I would assume that installing games from files on a USB drive is not an individual problem.

Possible solutions from lutris perspective could be to either allow the selection of an entire folder where the installer files are located, or the selection of multiple files.
On the other hand, a workaround for Flatpak would be nicer, because the idea of only having to select the .exe file is actually very elegant.

**Comment by mittler-works** [comment]
So it works when I share the file system `host`. Doing so will cause lutris to not start the installation from `/run/user/1000/doc/...` but from `/run/media/...` as expected.

But this is suboptimal because I do not want to share my entire host filesystem. The problem is, not only Lutris but also all games and third party mods will have these permissions...

**Comment by danieljohnson2** [comment]
I think at this point I must pass on the mantle of "Flatpak master" to you, @mittler-works, especially since I know almost nothing about it. But good luck getting a security config that works.

**Comment by mittler-works** [comment]
Hahaha, not that I deserve it, but I'll take it in the good old "take what you can, give nothing back" manner :joy: 

Joke aside, I think I found something. According to the [Flatpak Sandbox Permission Docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html) there are some reserved paths. And guess what: they seem to include `/run` and all subpaths under it. So I tried to mount my drive somewhere else (I tried with a folder `test` in my homedir) et voila - it works! :raised_hands: 

This workaround is fine for me, as it works and I do not have to share my host filesystem. Maybe that's something for FAQ or Troubleshooting section in the lutris docs...

I'll add a Mount Unit so my drive will always be mounted in my Homedir and then there should'nt even be any inconvenience. :+1:
