### ISSUE TITLE
[BUG] Games can't be deleted because they're protected (Flatpak)

### ISSUE THREAD

**Issue by largestgithubuseronearth** [lutris/lutris#5744]
### Bug description

When trying to uninstall any game, it won't let me delete the files because they're "protected", requiring me to manually delete them from the file manager. It definitely has permission for the directory and Lutris installs games to it just fine. It's only deleting that doesn't work.

The patch notes say this was fixed in the prior update on Flathub but it was never fixed for me, and it still doesn't work on the Flathub beta branch for 0.5.18.

### How to Reproduce

1. Install Lutris Flatpak via Flathub.
2. Open Lutris and import some games.
3. Try removing a game from your library.
4. See that the checkbox to delete the files is disabled, and the note says that these directories are protected.

### Expected behavior

I expect the checkbox to delete the files to work and not be greyed out. If there is something preventing it from deleting, then the note should probably be more explicit.

### Log output

```shell
INFO     2024-11-22 23:53:48,857 [application.do_command_line:480]:Starting Lutris 0.5.18
INFO     2024-11-22 23:53:48,880 [startup.run_all_checks:120]:"card1" is AMD Radeon RX 7800 XT (1002:747e 1002:0e37 amdgpu) Driver 24.2.7
DEBUG    2024-11-22 23:53:49,058 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-11-22 23:53:49,079 [api.check_stale_runtime_versions:52]:Modified at Fri 22 Nov 2024 11:50:52 PM , will update after Sat 23 Nov 2024 05:50:52 AM 
DEBUG    2024-11-22 23:53:49,080 [lutriswindow.create_runtime_updater_cb:1310]:Runtime up to date
DEBUG    2024-11-22 23:54:27,229 [application.show_window:396]:Showing window UninstallDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f0255919e80 (LutrisWindow at 0x557d11278d80)>}
DEBUG    2024-11-22 23:56:10,955 [path_cache.remove_from_path_cache:76]:Removing Quake Enhanced (wine) from path cache
DEBUG    2024-11-22 23:56:10,959 [config.remove:210]:Removed config /var/home/qwery/.var/app/net.lutris.Lutris/config/lutris/games/quake-enhanced-gog-1732348301.yml
INFO     2024-11-22 23:56:10,960 [shortcut.remove_shortcut:101]:Removing Steam shortcut for Quake Enhanced (wine)
DEBUG    2024-11-22 23:56:10,989 [application.on_app_window_destroyed:421]:Removed window UninstallDialog{'parent': <lutriswindow.LutrisWindow object at 0x7f0255919e80 (LutrisWindow at 0x557d11278d80)>}
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 47 Flatpak runtime
Arch: x86_64
Kernel: 6.11.8-300.fc41.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 31.3 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 18.1.8, DRM 3.59, 6.11.8-300.fc41.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7 (git-3900828265)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7 (git-3900828265)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7 (git-3900828265)
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Radeon RX 7800 XT (RADV NAVI32) (1.3.289)
```

### Media (optional)

![Screenshot From 2024-11-22 23-52-28](https://github.com/user-attachments/assets/4df345d4-1b4e-43e9-980e-8baa7d37487e)
This is from Flathub beta branch (0.5.18) today.

**Comment by largestgithubuseronearth** [comment]
I'm using Fedora Silverblue. Anything user modifiable is in `/var` including mount points and home, and there's no way to change that on my end.

**Comment by largestgithubuseronearth** [comment]
Okay using a symlink instead allows me to delete the files. But I wonder if there's a way to prevent blanket deletion of `/var` without preventing me from deleting a specific file that happens to be in that dir.

**Comment by danieljohnson2** [comment]
Sure, I understand now. Silverblue is being weird here, but it's a real distro we should be able to support. I'll add an exception for /var/mnt/<anything>/... 

Please try the [latest master](https://github.com/lutris/lutris); download this and run the ``bin/lutris`` script within, and try to install and remove a game in /var/mnt. It should work now. No need to install the master, this is just a test.
