### ISSUE TITLE
GeForce NOW Runner

### ISSUE THREAD

**Issue by Pandapip1** [lutris/lutris#5746]
There are a number of games (primarily those with Windows-only kernel level anticheat) that just won't run on non-windows operating systems. It would be handy to have a GeForce NOW runner that could run those games (even if it's at the cost of added latency).

**Comment by legluondunet** [comment]
Hello @Pandapip1, actually you can launch Geforce Now on Linux two ways:
- with Google chrome or Chromium
- using gfn-electron client: https://github.com/hmlendea/gfn-electron

Could you precise what are do you expect from a Geforce Now runner in Lutris?

**Comment by legluondunet** [comment]
@Pandapip1 FYI, I just wrote a gfn-electron script installer:
https://lutris.net/games/geforce-now/
to launch Geforce Now from Lutris

**Comment by Pandapip1** [comment]
I know both those options. The reason I want a Lutris runner is just because I like Lutris's UI/UX more than GFN's.

**Comment by strycore** [comment]
Is it even possible to launch a specific game from a shortcut in Geforce Now? 
I don't think there's any way to do that or to list games that you own on Geforce Now so you can pretty much forget about the whole idea.

**Comment by Pandapip1** [comment]
I was thinking maybe there could be a way of doing it with browser automation tools such as [selenium](https://selenium-python.readthedocs.io/)?

**Comment by strycore** [comment]
lol
