### ISSUE TITLE
Add system options for NVidia environment variables

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#575]
http://us.download.nvidia.com/solaris/340.98/README/openglenvvariables.html

**Comment by tcarrio** [comment]
Perhaps a drop-down list of options available for Nvidia which you would select, set, and your entry would go to the list of environment variables in the system runner configuration? Or perhaps another manner? 

Just want an idea of how you would have this implemented @strycore

**Comment by strycore** [comment]
Even with those being environment variables, I feel merging them into the `system.env` section would complicate things quite a lot. For example, those settings would appear in the env vars widget as well and can be manually modified.

Better keep config settings separate and merge everything at run time.

Design wise, I think I'll go with a list of checkboxes (or dropdowns where/if appropriate)
