### ISSUE TITLE
Lutris deletes my entire game folder

### ISSUE THREAD

**Issue by JayJay-OG** [lutris/lutris#5750]
I cancelled an installation and clicked "remove file" thinking it will remove the redundant files (lord have mercy) and all the time i spent downloading games just went down the drain :(  
such a stupid thing i did.

suggested fix: (1) Not deleting the whole folder to start with.
(2) Clear warnings like "hey, this action might delete your whole game folder".. would be fine.
(3) In built recycle bin.

i believe in Lutris a lot , but this.. this is just very painful
back to square one init..

**Comment by JayJay-OG** [comment]
ah i

> What version of Lutris are you using? Lutris 0.5.15 and later _do_ put many things into the trash instead of deleting them.
> 
> Lutris doesn't keep the downloaded game installers by default, regardless of the "remove files" checkbox. That checkbox is for deleting the (partially) installed game.
> 
> But you can use the "Storage" tab in the "Preferences" window to select a cache location, and then Lutris will download there, and keep the installers. That will avoid repeated downloads, if that is the concern you have.

Ah i see i am using lutris 0.5.12, thanks for your help mate :)

**Comment by JayJay-OG** [comment]
> What version of Lutris are you using? Lutris 0.5.15 and later _do_ put many things into the trash instead of deleting them.
> 
> Lutris doesn't keep the downloaded game installers by default, regardless of the "remove files" checkbox. That checkbox is for deleting the (partially) installed game.
> 
> But you can use the "Storage" tab in the "Preferences" window to select a cache location, and then Lutris will download there, and keep the installers. That will avoid repeated downloads, i

> What version of Lutris are you using? Lutris 0.5.15 and later _do_ put many things into the trash instead of deleting them.
> 
> Lutris doesn't keep the downloaded game installers by default, regardless of the "remove files" checkbox. That checkbox is for deleting the (partially) installed game.
> 
> But you can use the "Storage" tab in the "Preferences" window to select a cache location, and then Lutris will download there, and keep the installers. That will avoid repeated downloads, if that is the concern you have.

But does it have to go as far as deleting the whole folder!
and i use Linux distro so external folders get permanently deleted for security purpose per se.

**Comment by danieljohnson2** [comment]
It is not clear to me which folder got deleted, nor what you wished to keep in there.

If it is the game directory (where you were installing the game), then more recent Lutris versions will toss it in the trash instead.

**Comment by danieljohnson2** [comment]
I hope @JayJay-OG didn't really lose anything- I hope Lutris just deleted the (one) installed games directory. The downloaded game installers were never in there so -maybe- nothing of value was lost.

**Comment by strycore** [comment]
I'm afraid the whole ~/Games folder has been deleted in the same way some people used to delete their ~/Downloads directory.
This happens because some people don't realize they have to install games in ~/Games/some-game and not just ~/Games
