### ISSUE TITLE
0.5.18 - GE-Proton not available

### ISSUE THREAD

**Issue by tuxrinku** [lutris/lutris#5757]
### Bug description

GE-Proton doesn't appear in the wine drop-down list of different versions to use

### How to Reproduce

Configure a wine game, runner tab, and in the drop-down list of the wine version item GE-Proton doesn't show up when it used to with previous version.

### Expected behavior

Being able to select GE-Proton as a wine version

### Log output

```shell
2024-12-02 15:22:53,211: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-12-02 15:22:53,343 [application.do_command_line:480]:Starting Lutris 0.5.18
INFO     2024-12-02 15:22:53,462 [startup.run_all_checks:120]:"card0" is NVIDIA GeForce RTX 4080 (10de:2704 10b0:f297 nvidia) Driver 560.35.03
DEBUG    2024-12-02 15:22:53,637 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-12-02 15:22:53,656 [api.check_stale_runtime_versions:52]:Modified at lun. 02 déc. 2024 14:40:37, will update after lun. 02 déc. 2024 20:40:37
DEBUG    2024-12-02 15:22:53,657 [lutriswindow.create_runtime_updater_cb:1358]:Runtime up to date
DEBUG    2024-12-02 15:23:03,474 [application.show_window:396]:Showing window EditGameConfigDialog20
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Ubuntu 24.04 Noble Numbat
Arch: x86_64
Kernel: 6.10.3-1-liquorix-amd64
Lutris Version: 0.5.18
Desktop: ubuntu:GNOME
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: 13th Gen Intel(R) Core(TM) i5-13600KF
Physical cores: 14
Logical cores: 20
[Memory]
RAM: 31.2 GB
Swap: 15.6 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.275
Vulkan Drivers: NVIDIA GeForce RTX 4080 (1.3.280)
```

**Comment by danieljohnson2** [comment]
You should see ``ge-proton`` listed there now, once it has downloaded.

If you don't, try going to "Preferences", "Updates" and click "Check Again" in the Wine section in the middle. That should trigger the download.

**Comment by tuxrinku** [comment]
Alright, I indeed have wine-ge-8.26. I just wasn't expecting 8.26 to be the latest and recommended one since it's kinda old.

**Comment by danieljohnson2** [comment]
You should also get ``ge-proton`` with that; that's the new hotness.

We're not confident enough to go all in on Umu/Proton yet, so we deliver *both* ``wine-ge-8-26`` and ``ge-proton``.

In my testing ``ge-proton`` works very well, though, so I'd suggest you try it.
