### ISSUE TITLE
Amazon Prime Gaming 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by DanHolli** [lutris/lutris#5768]
### Bug description

when trying to refresh Amazon Prime Gaming

### How to Reproduce

1. Login to Prime Gaming intigration (with 2FA if that's important while checking the box to skip)
2. Click on reload
4. See `'NoneType' object is not iterable`

### Expected behavior

loads game list

### Log output

```shell
there was no output
```

### System Information

```shell
[System]
OS:              Ubuntu 24.04 Noble Numbat
Arch:            x86_64
Kernel:          6.8.0-49-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            13.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 7700 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.57, 6.8.0-49-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.2
OpenGL Core:     4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.2
OpenGL ES:       OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2
Vulkan Version:  1.3.275
Vulkan Drivers:  AMD Radeon RX 7700 XT (RADV NAVI32) (1.3.274)
```

### Media (optional)

[Screencast from 2024-12-05 21-15-25.webm](https://github.com/user-attachments/assets/3fb30080-6edd-4c32-8edc-8de3f4b0b401)

**Comment by Pandapip1** [comment]
Duplicate of https://github.com/lutris/lutris/issues/5596?

**Comment by danieljohnson2** [comment]
Looks like a dupe. But you are on an old version of Lutris; please upgrade to 0.5.18 and see if that does not fix the issue for you.

**Comment by DanHolli** [comment]
It indeed was, I didn't find it because it was closed and I didn't check if I was on the latest version
