### ISSUE TITLE
error 256 on nfs world script error

### ISSUE THREAD

**Issue by takuminightcore** [lutris/lutris#5773]
### Bug description

Command exited with code 256

Traceback (most recent call last):

  File "/app/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^

  File "/app/lib/python3.12/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)

lutris.installer.errors.ScriptingError: Command exited with code 256

Lutris log:
[INFO:2024-12-07 04:43:57,071:application]: Starting Lutris 0.5.18
[INFO:2024-12-07 04:43:57,157:startup]: "card0" is AMD Custom GPU 0405 (1002:163f 1002:0123 amdgpu) Driver 24.2.7
[WARNING:2024-12-07 04:44:08,472:system]: Non existent path: /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/proton/ge-proton
[INFO:2024-12-07 04:45:17,850:interpreter]: Runner wine needs to be installed
[INFO:2024-12-07 04:45:30,470:file_box]: Download completed
[INFO:2024-12-07 04:45:33,476:file_box]: Download completed
[INFO:2024-12-07 04:45:33,477:files_box]: All files available
[INFO:2024-12-07 04:45:33,477:installerwindow]: All files are available, continuing install
[INFO:2024-12-07 04:45:33,477:installerwindow]: Launching installer commands
[INFO:2024-12-07 04:45:33,537:wine]: Creating a win64 prefix in /home/deck/Games/need-for-speed-world
[INFO:2024-12-07 04:45:33,538:wine]: Winepath: /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-nfsworld-5.4-x86_64/bin/wine
[INFO:2024-12-07 04:46:21,828:wine]: win64 Prefix created in /home/deck/Games/need-for-speed-world
[ERROR:2024-12-07 04:46:23,339:errors]: Command exited with code 256
[ERROR:2024-12-07 04:46:23,339:exception_backstops]: Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/util/jobs.py", line 127, in wrapper
    repeat = func(*a, **kw)
             ^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/lutris/installer/commands.py", line 447, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected behavior

in stall the game

### Log output

```shell
unable to perform command
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 47 Flatpak runtime
Arch: x86_64
Kernel: 6.5.0-valve22-1-neptune-65-g9a338ed8a75e
Lutris Version: 0.5.18
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Custom APU 0405
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 11.5 GB
Swap: 6.8 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Custom GPU 0405 (radeonsi, vangogh, LLVM 18.1.8, DRM 3.57, 6.5.0-valve22-1-neptune-65-g9a338ed8a75e)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.7 (git-3900828265)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.7 (git-3900828265)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.7 (git-3900828265)
Vulkan Version: 1.3.290
Vulkan Drivers: AMD Custom GPU 0405 (RADV VANGOGH) (1.3.289)
```

**Comment by legluondunet** [comment]
This Github is not opened for script installer issues, only for Lutris issues.
You can obtain support on our Discord, Forum or Reddit.
