### ISSUE TITLE
Get rid of "(invalid)" string in Wine version selector

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#5778]
![20241208_143700](https://github.com/user-attachments/assets/12dfc7eb-ed66-405d-abf9-92f0232f1bab)

I don't know what is going on here, and quite frankly, I'm not interested in knowing the backstory of this. If even I, the creator of the project, gets utterly confused by this, I can't imagine what a normal user would feel like.

This has to go right away.

**Comment by danieljohnson2** [comment]
What would you like it to do in this situation?

**Comment by strycore** [comment]
I want Proton GE to work

**Comment by danieljohnson2** [comment]
It does, but it is called "ge-proton" now.

But this isn't the first time a setting that was valid becomes invalid later, and it won't be the last.

**Comment by strycore** [comment]
I remember writing some code that made sure we didn't show proton-ge in the UI and showed Proton GE.

We do not show proton-ge to users EVER. It's ugly.
Settings MUST NOT break, especially something basic like this.

**Comment by strycore** [comment]
And above all we DO NOT put stuff like "invalid" which leaves the users confused and questioning.

**Comment by danieljohnson2** [comment]
That's ugly? Is ``wine-ge-8-x26-86_64`` less ugly?

Settings do break, whatever you may hope. 

I thought @GloriousEggroll's change here was okay since this was experimental stuff. If experimental does not mean 'subject to change', what does it mean?

Anyway, I don't know why you are so worked up about "(invalid)", so I don't know what would make you happier. Other than magic.

**Comment by danieljohnson2** [comment]
Anyway, the name for this runner version is controlled on the server; Lutris just looks for the text "-proton" in Wine versions, case-insensitively. Change the name of the runtime component to "GE-Proton (Latest)" server-side and 0.5.18 should treat that as a Proton version just the same.

**Comment by strycore** [comment]
I'm worked up about this because there exactly one person on earth that understands what is going on here and it's the developer who has implemented that feature in lutris.

It's terrible UX, it's as simple as that. 

> That's ugly? Is wine-ge-8-x26-86_64 less ugly?

Just because we've been doing ugly shit, doesn't mean we should keep doing that. I had the version selector setup in such a way it would show "Proton GE (Latest)" regardless of what we choose to name the archive for Proton.

There shouldn't be 2 entries for Proton GE and proton-ge, it should be the exact same!!

**Comment by strycore** [comment]
> Anyway, the name for this runner version is controlled on the server; Lutris just looks for the text "-proton" in Wine versions, case-insensitively. Change the name of the runtime component to "GE-Proton (Latest)" server-side and 0.5.18 should treat that as a Proton version just the same.

I'm sorry but can you explain what is so hard in applying a custom label for a filename that forces you to give weird filenames to runtime components?

**Comment by danieljohnson2** [comment]
It was "GE-Proton (Latest)". You can tell my looking at your screenshot.

If you want a feature where these components have two names each, we can do that sort of thing. I have no idea why that's better than just picking a nicer name for the thing in the first place.

But it's hard to tell what you want. I'd like to suggest that pulling absolute laws out of your butt when you see something you don't like isn't productive. I have no idea why ``(invalid)`` is bad but ``(default)`` is good.

Until I do, I can't come up with an alternative for you.

**Comment by strycore** [comment]
For about 12 seconds, there was a file named "Proton GE (Latest)" but that such a ridiculous filename that I have no idea how any of you guys thought this would fly. 

`Default`, unlike `Invalid` has a clear meaning. Default means that this option will be chosen among a list of other options. Invalid could mean anything. Why is it invalid? What has gone wrong? I didn't do anything.

I don't know, I'm maybe corrupted by Django where it's extremely commonplace to have a list of (value, label) tuples. This kind of thing is even too trivial to even be called a feature.

**Comment by danieljohnson2** [comment]
I don't know what you are trying to say about 'Default'.  Any option that you select will be chosen; "(default)" means you are inheriting the setting from a 'higher' source. Doesn't say where from though. Not really all that obvious, it seems to me.

But no matter; if "invalid' is just a poor word choice, that's easy to fix. We just need a better one. What's a good word for "your setting is not one of the permitted options"? Should I just hit my thesaurus?

Providing an id/human-readable-name is not rocket science, but to do it properly here will require updates to the Lutris client and server in tandem; that makes it trickier than many changes we might make.

Anyway, I have some other problems to deal with now that are not Lutris related. I'll come back to this and adjust it, if you haven't done so yourself, once I know what we should do here.

**Comment by strycore** [comment]
What is considered the default in Lutris is unclear at the moment, since we still have wine-ge-8.26 as the default in the API but we're slowly moving to GE Proton. Anyway, I don't think there's any issue on that side.

The main issue is that our default proton option got split in 2 at some point when we transitioned from letting umu download GE Proton updates to having Lutris handle those updates. 
Regardless of how we handle things in the backend, this should have remained the same option and been transparent for the user.  Yes, experimental features are bound to break, but this is too small of a change to break the user configuration.
