### ISSUE TITLE
Lutris (0.5.18) locale (language) interface does not change as other than English is selected!

### ISSUE THREAD

**Issue by vrement** [lutris/lutris#5785]
Go to Preferences -> Global options -> Locale. Choose any language. Clicked save. Tried French, Finnish and German. The interface stays in English. Restarting doesn't help.

Please fix, and- or HOW to fix?

**Comment by danieljohnson2** [comment]
The language setting in Lutris is to control the language of a *game*, not Lutris itself.

You could run Lutris with the LANG environment variable to control Lutris itself, like this:
```bash
LANG=pt_BR lutris
```
