### ISSUE TITLE
Games installed on a different drive won't be remembered for Steam Wine.

### ISSUE THREAD

**Issue by aijony** [lutris/lutris#579]
Similar to issue #158, (I only tested for Steam Wine), games installed on a separate drive using Steam's multiple library feature will not be remembered. Using a symlink (on the user's end) would probably solve this problem. I don't mind too much myself however, I just thought I'd let other people know.

**Comment by strycore** [comment]
I have all my games on a separate library on a separate drive, they're doing fine.
