### ISSUE TITLE
Esync and Fsync options don't work with UMU

### ISSUE THREAD

**Issue by kasha695** [lutris/lutris#5796]
### Bug description

The options under the Wine runner to toggle Esync and Fsync don't seem to make a difference when using UMU, they are both enabled regardless.

I was testing From Dust which requires them both to be disabled but I was still having the same loading issue even when I toggled them both off.

However, UMU will disable Esync and Fsync if the env PROTON_NO_ESYNC and PROTON_NO_FSYNC are used.

### How to Reproduce

1. Toggle off Esync and Fsync
2. Launch a game with UMU
3. Notice in logs fsync is started

### Expected behavior

The Esync and Fsync options would be respected by UMU.

### Log output

```shell
#
```

### System Information

```shell
#
```

**Comment by danieljohnson2** [comment]
Sounds like a reasonable solution, and it seems like it works from the logs, but maybe you could put it to the test with From Dust.

[Here's the branch](https://github.com/lutris/lutris/tree/dj/proton_fsync_esync); please download this and run the ``bin/lutris`` script inside. No need to install! That should set the PROTON_NO_xSYNC env-vars for you, and if that works for you I'll merge it.

**Comment by kasha695** [comment]
Works perfectly, loads correctly now with just those options toggled off.

**Comment by kasha695** [comment]
Closing issue as fix is working.
