### ISSUE TITLE
Rename "Genesis" to "Mega Drive/Genesis"

### ISSUE THREAD

**Issue by anewuser** [lutris/lutris#580]
Your online database has a platform described simply as "Sega Genesis", which is a North American-centric choice.

**Comment by strycore** [comment]
done!

**Comment by anewuser** [comment]
You could add "Famicom" next to "NES" and "Super Nintendo" too. :)

**Comment by strycore** [comment]
I could but I would have to display it as ファミコンディスクシステム

**Comment by TingPing** [comment]
These should all be locale dependent.

**Comment by strycore** [comment]
That would be the best option indeed!
