### ISSUE TITLE
Convert runner icons to symbolic

### ISSUE THREAD

**Issue by TingPing** [lutris/lutris#582]
Just making an issue to document that we should do this. Help from anybody willing to make relatively simple svg's would be appreciated. For some of them there may possibly be freely-licensed ones that exist.

The list of icons needed: https://github.com/lutris/lutris/tree/master/share/lutris/media/runner_icons

**Comment by romlok** [comment]
I've started doing a bit of work toward this: https://github.com/romlok/lutris/tree/runnericons/share/lutris/media/runner_icons

So far, I've more or less just added the SVG icons that I could find which were clearly freely-licensed.

I'm not sure in what contexts Lutris uses these, and some of the icons are quite different from the originals, so improvement suggestions are welcome.

**Comment by TingPing** [comment]
@romlok It looks like those svg's aren't symbolic though. An example would be like this for browser: https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/apps/web-browser-symbolic.svg

**Comment by romlok** [comment]
Noted, but I'm not clear on exactly how symbolic you're wanting. Are, for example, the existing web/HTML5 and XDG icons symbolic enough?

![HTML5 logo](../blob/master/share/lutris/media/runner_icons/web.png?raw=true) ![Freedesktop.org logo](../blob/master/share/lutris/media/runner_icons/xdg.png?raw=true)

**Comment by TingPing** [comment]
Symbolic icons are a gnome spec, they would be one flat color that the icon loader replaces dynamically with your Gtk themes colors.

**Comment by romlok** [comment]
Oh, I see. That should probably be specified and linked to in the issue description then, so it's more clear what you're looking for.

**Comment by romlok** [comment]
![winesteam-symbolic.svg](/romlok/lutris/blob/runnericons/share/lutris/media/runner_icons/winesteam-symbolic.svg)
Howzat?

Is there a quick way to test how well icons work as symbols; showing them recoloured, etc.?

**Comment by TingPing** [comment]
@romlok Looks perfect!

> Is there a quick way to test how well icons work as symbols; showing them recoloured, etc.?

Hmm, I don't know of any tool for that. I might look into making a simple tool for it but I believe things have to be part of a valid icon theme so we will have to change the layout on disk.

**Comment by romlok** [comment]
I added a symbols.html file to that directory in my branch, which lets you see the symbolic icons with different foreground and background colours. It doesn't work directly through github, but it works browsing locally.

Obviously this isn't a perfect match for what GTK would do under the hood, but going by the symbolic theme's readme, it should be using a similar method for recolouring the icons.

**Comment by romlok** [comment]
Finally done!
Some of them are probably not quite symbolic enough, or otherwise need tweaking, but hopefully these give you something to build on.

I've created a separate branch which just adds the symbolic icons:
https://github.com/romlok/lutris/tree/symbolism/share/lutris/media/runner_icons

**Comment by TingPing** [comment]
@romlok Looks good but they should all only have a single fill color of #bebebe.

For example: https://git.gnome.org/browse/gnome-icon-theme-symbolic/tree/gnome/scalable/categories/applications-engineering-symbolic.svg#n27

**Comment by romlok** [comment]
As I read the specification, the fill colour will be overridden globally by GTK, so the actual fill colour used in the SVG shouldn't matter?

https://git.gnome.org/browse/gnome-icon-theme-symbolic/tree/README
> The color of the icon set is defined at runtime by the gtk theme. Every single
icon from the set is actually embedded inside an xml container that has a
stylesheet overriding the colors.

These icons actually have no fill defined for any shape (so defaults to showing them as black), since that allowed me to quickly build something with CSS to test how they looked with different fill/background colour combinations.

**Comment by TingPing** [comment]
Hmm, perhaps you are right, I just saw every single icon using that color so I thought it meant something. I can play around with it more to see if it works.

**Comment by TingPing** [comment]
Ok so I have them loading (and the symbolic colors work fine) here: https://github.com/lutris/lutris/commits/wip/symbolic-runners

**Comment by TingPing** [comment]
@romlok We will need one for [gog](https://gog.com) too.

**Comment by TingPing** [comment]
@romlok Oh and 3 icons for platforms: https://github.com/lutris/lutris/tree/next/share/lutris/media/platform_icons

**Comment by romlok** [comment]
Oy, that wasn't in the job description! :)

GOG is done: https://github.com/romlok/lutris/blob/symbolism/share/lutris/media/runner_icons/gog-symbolic.svg

And also the platform icons: https://github.com/romlok/lutris/blob/symbolism/share/lutris/media/platform_icons

In the process of doing the platform icons, I also simplified and increased the contrast of the Linux runner icon, so you might want to update that one as well.

**Comment by TingPing** [comment]
Great work, everything has been rebased and pushed to that branch.

@strycore Want to test it out and merge if ready?
