### ISSUE TITLE
In a category view, Lutris sorts "Last Played" category alphabetically, making it useless. 

### ISSUE THREAD

**Issue by TheInfamousAlk** [lutris/lutris#5827]
### Bug description

![image](https://github.com/user-attachments/assets/6068cbaf-b10e-4b55-8951-d5b795bb6421)

As seen above, Lutris 0.5.14 sorts "Last Played" alphabetically, not according to time. 

Also since I can't paste images in the log output box, my lutris -d does nothing and here is what it shows: 
![image](https://github.com/user-attachments/assets/dfc9a787-0ca8-4be5-bf62-284e2483688d)

### How to Reproduce

1. Have categories
2. View one of the categories in the left bar
3. Sort by Last Played

### Expected behavior

Sort "Last Played" by actual time, not on alphabetical (or I guess numerical?) order.

### Log output

```shell
lutris -d has no output in my console. I don't know why.
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.9.3-76060903-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            20.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 560.35.03
OpenGL Core:     4.6.0 NVIDIA 560.35.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version:  1.3.280
Vulkan Drivers:  NVIDIA GeForce RTX 2080 Ti (1.3.280)
```

### Media (optional)

![image](https://github.com/user-attachments/assets/decce221-e1e8-46f9-b7ca-60f00f95d3aa)

**Comment by danieljohnson2** [comment]
No repro over here; I would guess this has been fixed since (checks notes) October of 2023. Maybe you should update to [the latest release, 0.5.18](https://github.com/lutris/lutris/releases)?

**Comment by TheInfamousAlk** [comment]
Oh you know you are right. I had manually updated to that version but apt (Pop OS) apparently downgraded me to .14. My mistake. This fixed it.
