### ISSUE TITLE
Broken symbolic links when extracting tar files

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#584]
I recently wrote an install script for The Stanley Parable DRM-free release, which come in a tar-heavy package. When testing it out, I noticed that the symbolic links of the uncompressed tar-file were not honored when extracted.

The symbolic link files are tagged with a `2` type flag in the uncompressed tar as per the spec, but the extracted files are not flagged as symbolic links and become normal text-files, making the game unplayable.

To reproduce, use 
```
- extract:
    file: path/to/file.tar
```
to extract an uncompressed tar-file with symbolic linked files inside.

**Comment by FakeShemp** [comment]
I checked the code and it seems you `subprocess` an instance of 7zip. I tried it with 7z directly with the same result. Not sure if that is a bug or a feature of the program. Is there a way to force it to keep symbolic links?

**Comment by RobLoach** [comment]
https://github.com/lutris/lutris/blob/master/lutris/util/extract.py#L29-L51

Should we add a `.tar` check in there?

**Comment by strycore** [comment]
yes, that is entirely correct, p7zip doesn't seem to support symlinks: https://sourceforge.net/p/p7zip/discussion/383044/thread/6534b3ff/

tar files shouldn't require p7zip to be extracted, we could use the standard python library to do that. Could you try compressing the tar file into a tar.gz and verify if you get the expected behavior?

btw, thank you so much for your incredible work on installers, that is some amazing dedication :D

**Comment by FakeShemp** [comment]
It's a little hard to try it on The Stanley Parable, as it's pretty much a tar-in-zip-in-tar mess.

Testing on another tar.gz file I made--with symlinks--they seem to extract fine with symlinks retained when installed. No problem here, boss. :)

You're very welcome for the installers. I'm basically sorting my entire games library and adding everything to Lutris as I go along, because I love it. Thanks for maintaining it <3

**Comment by strycore** [comment]
Good to know! It should be a rather easy fix. Also, this has convinced me to release a 0.4.12 version instead of going for a beta of 0.5.0 so there will be a fix released on Tuesday!
