### ISSUE TITLE
league of legend fails to start for reasons unknown

### ISSUE THREAD

**Issue by PowaBanga** [lutris/lutris#586]
hi all
I try to install league of legend on my opensuse tumbleweed AMD64 KDE, and I have this error message in terminal:
```

(lutris:27224): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:27224): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lutris:27224): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

```
it is not a wine error that :(
Somebody can help me ?

**Comment by strycore** [comment]
Those are only GTK warnings and can be ignored.

**Comment by TingPing** [comment]
It is also generated by the theme and not lutris.

**Comment by PowaBanga** [comment]
yeah but my application is not launched :s . How to fix that so ?

**Comment by strycore** [comment]
start lutris with the debug log enabled ( `lutris -d` ) and see if you get more error messages. Also make sure that vcrun2015 is properly installed, I noticed that it wouldn't get installed when I tried it on Solus then I made an adjustment on the install script and now it works fine.

**Comment by PowaBanga** [comment]
I finaly uninstall it and reinstall it, and it work... not really, when I launch the game, all menus work, but not when I want start to play, I have an whe error about directX, who saying to me that I have to verify that my graphics drivers are update... :(
Do you think that you can help me ?

**Comment by strycore** [comment]
Can you post a screenshot of the error and tell us what your GPU and driver is?

**Comment by PowaBanga** [comment]
!()[https://i58.servimg.com/u/f58/19/30/75/46/screen10.jpg]
and finaly i found a comand line who send very much informations to me, but I do not find my drivers ...
https://paste.gnome.org/pugb0ckwo
https://paste.gnome.org/pgf7askij
Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz

**Comment by strycore** [comment]
@PowaBanga are you sure this integrated GPU is able to run LoL? it seems to be limited to OpenGL 2.1, which might be an issue. What version of Mesa are you running?

**Comment by PowaBanga** [comment]
Really I do not know, I can play half life without problems Quake 2-3 Xonotic nexuis too. When i see lol on my friends computer, it do not seems very high graphicaly...
How to find my mesa version ?

**Comment by shorth** [comment]
Had the same issue. Make sure to install the 32bit packages for your graphics driver. In my case on arch it was lib32-nvidia-utils.

**Comment by strycore** [comment]
Problems with LoL should now be solved with the new installer.
