### ISSUE TITLE
Documentation for installer scripts incorrect?

### ISSUE THREAD

**Issue by joonatoona** [lutris/lutris#590]
[errors]:This installer doesn't have a 'script' sectionNone

There's absolutely nothing in any documentation about a script section

**Comment by strycore** [comment]
The offline installer feature is something we have to document more indeed. The current documentation refers to the script itself but the form provides additional information about the installer and the game. 

The script section is what you would have in the editor on the website, there are some other mandatory fields we need to document which I'll try to do ASAP.

**Comment by gabor-udvari** [comment]
Would it make sense to add the installer documentation to the GitHub Wiki? The sidebar next to the installer editor on the webpage is too small and hard to navigate for a long documentation.

**Comment by Lucki** [comment]
Here it is: https://github.com/lutris/lutris/blob/master/docs/installers.rst

**Comment by strycore** [comment]
Please send whatever script caused the error so we can interpret it correctly.
