### ISSUE TITLE
Client side decorations

### ISSUE THREAD

**Issue by ErikWallstrom** [lutris/lutris#592]
Are there any plans on implementing the GTK Header Bar in lutris? Every program I am currently using except for Lutris uses it, and it would make the program look better and fit in with GNOME 3 (which basically is *the standard* desktop environment right now). It does not seem like it should be hard since Lutris already is using GTK+3.

Using GtkHeaderBar (just a concept):

![screenshot from 2017-06-15 16-43-05](https://user-images.githubusercontent.com/15019604/27187006-4ffd7108-51ea-11e7-8b51-05c69e10f27a.png)

What it currently looks like (without the menu):

![screenshot from 2017-06-15 16-49-11](https://user-images.githubusercontent.com/15019604/27187109-9546a450-51ea-11e7-82e8-88652c42396d.png)

**Comment by strycore** [comment]
If you check the `next` branch, you'll see we are using an HeaderBar now :D

**Comment by ErikWallstrom** [comment]
Oh never mind then! That's awesome :D

**Comment by mrnhmath** [comment]
@strycore Is it optional?

**Comment by strycore** [comment]
@mrnhmath not in its current state

**Comment by mrnhmath** [comment]
Thanks. Hope with the next release it will be optional, as CSD looks and behaves nicely on GNOME ONLY.

**Comment by strycore** [comment]
that seems something the Gtk team should take care of, it seems unreasonable to put the burden of supporting 2 different UI models on app developers.

**Comment by TingPing** [comment]
> that seems something the Gtk team should take care of, it seems unreasonable to put the burden of supporting 2 different UI models on app developers.

Gtk already supports exposing a preference based on your desktop but it *obviously* cannot redesign your UI for you. We discussed this and came to the conclusion it just isn't worth the effort.

**Comment by mrnhmath** [comment]
Having support for multiple DEs or being GNOME-only, many would prefer the former.

**Comment by ErikWallstrom** [comment]
@mrnhmath CSD looks and behaves perfectly fine in all desktop environments I have tried. GNOME is by far the most used desktop, and default for all major distros. Lutris is already using GTK3, so I see no reason not to implement this

**Comment by TingPing** [comment]
Yes it will work anywhere, it just won't visually fit in which will always happen to some degree. If somebody wants to do a PR that has a menubar/toolbar mode I'll review it at least.

**Comment by mrnhmath** [comment]
There are a bunch of reasons to not force CSD, from inflexibility to drop-shadow issues, but IMO the most important one is that it's not implemented in a "standard" way and will often ignore WM rules (e.g KWin).

**Comment by JaneSmith** [comment]
Was this ever released? This issue is from over a year ago, and the comments make it sound like it was on its way. I've just installed Lutris 0.4.18.1 from the AUR on Arch, and it has a plain titlebar, then a traditional menubar, and then a traditional toolbar. The OP's concept looks beautiful and I would love to have that. Certainly, it should be optional, but I would love to have it look like a native application within Gnome.

**Comment by AccountOneOff** [comment]
It releases with 0.5.0. No eta for that yet.
