### ISSUE TITLE
Make wine desktop integration optional

### ISSUE THREAD

**Issue by Yepoleb** [lutris/lutris#596]
Currently `WinePrefixManager.setup_defaults()` gets called every time a game is launched at [this location](https://github.com/lutris/lutris/blob/2a7f48108c2f017b2bcbb51f90d2f86f176188ff/lutris/runners/wine.py#L807). This resets any user configuration to these values, in particular the "Desktop Integration" settings for linking the desktop and documents folder. While this can be useful, it should not be forced at every launch. I like to keep my saves in a separate Wine directory, so they aren't deleted when I uninstall a game. It was very confusing to see them disappear every launch. So please don't reset to the default values before running a game, it should be done after prefix creation only.

**Comment by strycore** [comment]
While we don't have plans to change the way Lutris applies settings, we can make sandboxing optional. When we do, be sure to enable the option globally since the sandboxing will always be the default behavior.

**Comment by Yepoleb** [comment]
I'd actually prefer a wine "home" setting instead of a simple on/off switch, but I'm not sure if that's too much too ask.

**Comment by strycore** [comment]
We also plans to let users set their home directory to something else but that's not Wine specific ;)

**Comment by Xenega** [comment]
Added the pull request #744 to allow sandbox customization.
Can you test with your config ?

I used only one field for all directories. Not sure if granularity is useful.
