### ISSUE TITLE
Can't install Metal Slug (or Humble launcher) 

### ISSUE THREAD

**Issue by RafaelLinux** [lutris/lutris#598]
I'm OpenSUSE Tumbleweed user and discovered Lutris just yesterday. Is fantastic. I installed Zero-K in a blink. But I'm not able to install "Metal Slug". It requires Humble, but I can't find it for my distro. Any idea?

Thank you

**Comment by telanus** [comment]
The "humble" won"t be in your distro as it's a shop: https://www.humblebundle.com/store :smile_cat:

**Comment by strycore** [comment]
you have to buy the game on humblebundle.com then download the file they give you.
