### ISSUE TITLE
Start-up issue.

### ISSUE THREAD

**Issue by Squiblers** [lutris/lutris#599]
Heya. For some reason when I start up Lutris, this happens. Yes, I'm a noob to Linux, but I'd really like to try this out, been looking for something like this for ages. Please help <3

http://i.imgur.com/zkDnWIq.jpg

**Comment by strycore** [comment]
Are you running the latest version of lutris? This is already fixed in 0.4.12.

**Comment by Nebblez** [comment]
Yes, I am running 0.4.12, still not fixed. :(

**Comment by strycore** [comment]
Oooh, my bad, I fixed the issue *right after* releasing 0.4.12 :/
I'll see what I can do, I'll probably release 0.4.13 a bit early.

**Comment by Nebblez** [comment]
Oh alright, thanks you so much <3

**Comment by fabry92** [comment]
same problem... Can't use lutris :/

**Comment by strycore** [comment]
Fixed now
