### ISSUE TITLE
debian Stretch is live, but the site / OBS is debian 8 still

### ISSUE THREAD

**Issue by xpd259** [lutris/lutris#600]
I feel really bad for making this bug report but, Debian Stretch is live, but the site is still showing Debian Jessie install instructions 
👍 but it's worth pointing out they still work for Debian Stretch

**Comment by strycore** [comment]
Why would you feel bad about submitting a bug report? You should feel good about it! :D 

I'll fix that ASAP, although I'll have to make sure the OpenSUSE Build System also has Debian 9, they tend to be a bit slow keeping up with distro releases.

**Comment by xpd259** [comment]
feeling bad would be my Olympic sport ;D esp as it was an obvious bug.
but cool 👍  thanks

**Comment by strycore** [comment]
Package available on OBS and advertised on the website!
