### ISSUE TITLE
Dark theme doesn't work on KDE with lutris 0.4.12

### ISSUE THREAD

**Issue by xpd259** [lutris/lutris#601]
It might be a KDE setting that I've missed, the KDE settings panel is quite extensive
but no matter what I do with the "Dark Theme" setting it doesn't alter anything

Debian Stretch, KDE (set to the breeze dark theme)
AMD64
Lutris 0.4.12 

sorry, don't know what other info to supply. 

![screenshot_20170623_211129](https://user-images.githubusercontent.com/822758/27498785-8fb61786-5858-11e7-8ec3-bb0c23865c09.png)

**Comment by TingPing** [comment]
The `Breeze` Gtk theme does not ship a dark variant for some reason (perhaps because KDE has no such concept). So the only way to really do it is switch to `Breeze-Dark` so everything is dark *or* manually copy `Breeze-Dark`'s `gtk.css` into `Breeze` as `gtk-dark.css`.

**Comment by TingPing** [comment]
Oh I realize you said you use `Breeze-Dark` in KDE, perhaps you are missing the Gtk one for that?

**Comment by xpd259** [comment]
ahhh yes, thank you 🥇 sorted
