### ISSUE TITLE
Lutris kills automount

### ISSUE THREAD

**Issue by theZorro266** [lutris/lutris#602]
I have harddrives mounted with systemd's automount. On those harddrives there are games installed with Lutris. Everytime the automount feature unmounts the partitions because of inactivity, Lutris accesses those mountpoints, essentially killing automount. This happens regardless of the actual idle timeout for those mountpoints.
I don't see a reason why it would do this. I don't think Lutris, when in the background, should access files at all. Refreshing should instead be done, when it is actively used.

I am using Arch Linux with Lutris 0.4.12.

**Comment by strycore** [comment]
what kind of games do you have on those drives? are these games in a Steam library? we do have an inotify watch on steam libraries but this shouldn't access the drive if files aren't modified.

Other than the Steam library monitor, I don't see when Lutris would access files while inactive, I lack relevant details.

**Comment by theZorro266** [comment]
Yeah, I have Wine Steam games on all of those drives.

**Comment by strycore** [comment]
@TingPing do you know about this automount thing? Is it possible that Gio.FileMonitorEvent causes that?

**Comment by TingPing** [comment]
Well it is plausible, I'm not familiar with `inotify` but I don't think it should cause that. Probably best to make a minimal reproducer of the filemonitor and see where that goes, it is a relatively small chunk of code.

**Comment by theZorro266** [comment]
Is this still an issue? My setup is different now, but synchronization is done only once Lutris starts, correct?
