### ISSUE TITLE
Wine runner sometimes creates prefix with wrong architecture

### ISSUE THREAD

**Issue by Yepoleb** [lutris/lutris#603]
Sometimes when I manually create a Wine prefix it ends up being 32 bit even though 64 bit is set in the options. I think it happens if you select "Run EXE inside wine prefix" before it exists, but I haven't tested this well enough.

**Comment by strycore** [comment]
That could happen if you're using a i386 build of wine, can you reproduce this after making sure a x86_64 build is used?

**Comment by Yepoleb** [comment]
Here's how I reproduced it:

1. Add a new Wine game.
2. Set name, prefix directory, prefix architecture (64 bit), Wine version (2.10-x86_64), executable is left blank.
3. Choose "Run EXE inside wine prefix" and install the game
4. Set the executable file in the config
5. Try to launch the game

The launch fails because the prefix is the wrong architecture, but the "Run EXE inside wine prefix" option still works. This bug does not occur if you do the initial launch using the play button. I suppose the architecture does not get set properly with the run EXE option.

**Comment by strycore** [comment]
With a 64 wine build, lutris will now default to 64bit prefixes
