### ISSUE TITLE
Lutris protocol - The address wasn’t understood

### ISSUE THREAD

**Issue by Extarys** [lutris/lutris#608]
Hey there!

I had use Lutris once and it worked like a charm, then I had to reformat (Linux Mint 18.1) and the lutris: links wasn'T working (worked before, same distro).

Yesterday I decided to give KDE a try since I didn't play with Plasma 5 yet (it's great), but the lutris protocol is still not working.

How can I fix this? Thanks

**Comment by basxto** [comment]
The lutris package should contain /usr/share/applications/lutris.desktop
```
[Desktop Entry]
Version=1.0
Name=Lutris
Comment=Open gaming platform
Categories=Game;
Exec=lutris %U
Icon=lutris
Terminal=false
Type=Application
MimeType=x-scheme-handler/lutris;
```

The last line is used by `xdg-open` for understanding protocols as well as other programs who follow the XDG standard.

You should be able to add `lutris.desktop` manually to `~/.local/share/applications`

Cinnamon, MATE and KDE should all behave the same.

**Comment by TingPing** [comment]
Note you have to run `update-desktop-database ~/.local/share/applications` after installing it.

**Comment by Extarys** [comment]
Thanks guys!

**Comment by CIB** [comment]
If anyone else is getting this issue because their browser somehow fails to open the protocol even though it's installed correctly: `xdg-open lutris:<game>`

**Comment by Extarys** [comment]
Thanks

**Comment by strycore** [comment]
Workarounds are *not* fixes, I'm reopening that one. Please note that this doesn't have anything to do with your browser, Lutris URLs work just fine in Firefox and Chrome when using Gnome Shell. The issue is about the desktop environment you're using, not the browser.

**Comment by neophyt1983** [comment]
Using Ubuntu 17.10 and this still appears to be having some problems. Any thoughts?

**Comment by yaomtc** [comment]
I'm using Solus with Budgie, which uses some parts of Gnome (its control center, at least), and I have this problem.

**Comment by Xenega** [comment]
We can never know why the desktop file is not present. Installers should add it but anything can happen as user deleting it, update problem, etc...

@strycore 
What do you thinks about check if lutris desktop file exists when lutris start ? And copy it if not (with a prompt to user).

@yaomtc 
Do adding the desktop file help ?

**Comment by strycore** [comment]
I need to find out what was the URL handler @TingPing asked me to remove. This seems to be the cause of the issue as other desktop managers don't use current Free Desktop standards.

**Comment by TingPing** [comment]
I believe the problem is `lutris:foo` is by most standards not a valid URL. `lutris://foo` is. I think a recent version of `Gio` just "fixed" this in some cases by just allowing the bogus URL but it is easy for mistakes to happen where it hits a codepath that requires or converts things to real URLs.

**Comment by strycore** [comment]
Found it, I have reverted the change in commit 94f3fe31f9ae3402bd987dc803f586766430a281 and the old URL handler will be back in 0.4.15. Hopefully, this solves what you're all experiencing

**Comment by TingPing** [comment]
@strycore Well, that code does nothing unless your users live in 2007.

**Comment by strycore** [comment]
For what it's worth, XFCE might be using code from 2007 :D 
`lutris:foo` is a valid URL based on the RFC so if that's a problem then we might have to switch to `lutris://foo`. I have to find a way to reproduce this issue so I can test what actually works.

**Comment by TingPing** [comment]
"the RFC" isn't descriptive of anything meaningful.

> For what it's worth, XFCE might be using code from 2007 :D

They don't use GNOME infrastructure so I doubt that was ever supported by it.

**Comment by Xenega** [comment]
This issue can be only a missing desktop file. That's was the problem with @Extarys

**Comment by TingPing** [comment]
I can confirm that Xfce uses Gio thus its definition of a URL and its implementation of the desktop spec: https://git.xfce.org/xfce/exo/tree/exo-open/main.c

@Xenega Yes very likely. Lutris recommended users run out of tree for some reason, which is obviously broken.

**Comment by Xenega** [comment]
I added a pull request. #747

**Comment by strycore** [comment]
@Xenega that is a workaround. The .desktop file has to be provided by our package and work consistently. I cannot think of any Linux software that checks for .desktop file.

**Comment by strycore** [comment]
@TingPing no, we recommend users to use our package. Running from the source directory is meant for developers or users who want to test features from the master branch but have the package already installed. Yes, running from the source directory while not having installed lutris before will result in a broken behavior but no one should be doing that. Should I reword the docs to make that clearer?

**Comment by strycore** [comment]
Great, I just installed Linux Mint 18.1 and I was unable to reproduce the issue. That was a waste of time… 
Will try with Mint KDE to see if it's any different.

**Comment by TingPing** [comment]
> Should I reword the docs to make that clearer?

Probably.

I'd also revert your revert but it truely is just an unused file.

**Comment by strycore** [comment]
Confirmed to work as expected on Linux Mint KDE

**Comment by strycore** [comment]
The URL handler doesn't register on Kubuntu 18.04, I *finally* have a setup where I can reproduce this issue.

This seems to be specific to Firefox, launching a lutris url with xdg-open works as expected.

**Comment by strycore** [comment]
The problem should be reported to Kubuntu, Steam links don't work either. There's something missing in their URL handler implementation.

Currently, the best workaround is go to about:config in Firefox and set 

    network.protocol-handler.expose-all  to False

then select /usr/bin/xdg-open as the opener for either Lutris or Steam

**Comment by Merrit** [comment]
@strycore 

Thank you, this workaround is exactly what I needed to get Firefox & Lutris working.
I am indeed using Kubuntu 18.04

**Comment by jason-oliveira** [comment]
I just experienced this issue in Calculate Linux (KDE) with current Lutris. Applications were piping-out to xdg-open appropriately, but xdg-open didn't know how handle `lutris:` URI's. It turns out that the Calculate ebuild did not seem to install the /usr/share/applications/lutris.desktop file (or ~/.local/share/applications/lutris.desktop). I had to manually create it with the following contents:

```
[Desktop Entry]
Version=1.0
Name=Lutris
Comment=Open gaming platform
Categories=Game;
Exec=lutris %U
Icon=lutris
Terminal=false
Type=Application
MimeType=x-scheme-handler/lutris;
```
Which I placed in both locations, then ran `update-desktop-database ~/.local/share/applications`. The last line of the above file tells xdg-open how to handle `lutris:` URI's. This is a really old bug report, but as it came up in Google, hopefully someone else can have their issue solved accordingly.

If this needs a new bug report filed, please let me know.

**Comment by strycore** [comment]
@jason-oliveira this bug needs to be reported to the packager of Lutris on Calculate Linux

**Comment by jason-oliveira** [comment]
As Calculate is just a PORTAGE_BINHOST for Gentoo, combined with the fact that I have three other Calculate Linux Desktop installs with working `lutris:` via xdg-open mean it'll probably get closed as invalid if I submitted a bug. Forgive me for using your issue tracker as a way to bump this issue for anyone else that may experience it and are searching Google for help, and for creating new activity on a 2 year old bug.

**Comment by strycore** [comment]
No worries. To solved this, the URL may have to be created manually in KDE. Maybe there are some other programs registering custom URL handlers that can be used as reference.
