### ISSUE TITLE
Missing ttf-mscorefonts-installer

### ISSUE THREAD

**Issue by rgarrigue** [lutris/lutris#609]
Hi

Trying League Of Legends with both DirectX and OpenGL installer, I ended up finding that I was missing a `sudo apt install -y ttf-mscorefonts-installer`.

Reading the docs/ folder content I couldn't find any option in the installer looking like a way to install dependencies outside of the wine's windows C:. Maybe such a feature that'll be a good idea.

Or maybe this rather small dep could be included in https://github.com/lutris/lutris/blob/master/debian/control

Anyway thanks for lutris. I especially appreciate the way it looks like ansible :-)

**Comment by Yepoleb** [comment]
The winetricks installer `corefonts` should do the same thing as the package, but inside the Wine directory.

**Comment by strycore** [comment]
I agree with the winetricks option, the ttf-mscorefonts-installer is Debian/Ubuntu specific so I have no guarantee that other distros will have that package. Plus. there's only a minority of games needing those fonts so it's better to have installers setup the necessary fonts themselves.

Keeping this open until I verify the LoL installer.

**Comment by strycore** [comment]
Wait… I don't play LoL XD
