### ISSUE TITLE
Desura games will be installed in lutris runner directory

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#61]
Games shouldn't be installed by default in .local/share/runner but the desura runner is installed here (which is the right location) and the games will be installed there.

Same problem would exist for Steam if it had a proper installation method.

**Comment by strycore** [comment]
Yeah well I don't really feel dealing with that atm and no one cares about Desura anymore so pushed back to 0.4.x

**Comment by Xodetaetl** [comment]
Desura games won't install at all anymore from the client, am I wrong ? The only way now is by downloading them if they are DRM free.

**Comment by strycore** [comment]
I'm trying do download a game and it seems to be stuck on a "Preparing…" dialog. Weird, I can login and update the client just fine.

**Comment by Xodetaetl** [comment]
Ditto.

**Comment by strycore** [comment]
Well, there's nothing we can do really. If it's not fixed by 0.4, we might just remove the runner.

**Comment by RobLoach** [comment]
Is Desura dead?

**Comment by strycore** [comment]
Not quite, so I guess we'll keep this around a bit longer.

**Comment by strycore** [comment]
lol, desura.
