### ISSUE TITLE
More examples, or a way to browse scripts easilly 

### ISSUE THREAD

**Issue by rgarrigue** [lutris/lutris#610]
Hello

Trying to fix a script, I was looking for some inspiration. As a sysadmin by trade, I like RTFM, or googling,  or going for a big  `grep -RHni blabla .` in a browser full of similar stuff and see how others peoples work.

Problem is, there's not example in the repo. I couldn't find installers on google. And most of the installers I randomly opened on the website were very simple. I wish there was a way to git clone or DL or anything all the installers at once ?

And I'ld like to say thanks, Lutris looks great. I especially like the ansible-like look :+1:

**Comment by strycore** [comment]
This is truly an area we wish to improve on. In the near future, I plan to have several templates for a bunch of different kind of installers. 
Ultimately, I'd like to go further and make an UI specifically to edit installers but that will come a bit later.

**Comment by strycore** [comment]
This issue is now tracked here: https://github.com/lutris/website/issues/84
