### ISSUE TITLE
Lutris set to restore resolution when game exits, but doesn't work when game crashes

### ISSUE THREAD

**Issue by yaomtc** [lutris/lutris#612]
For example, if I install Deus Ex: Human Revolution with the default prefix, no winetricks, use the setup window to set its resolution to 1920x1080 on my 4K monitor, and then launch the game... The game crashes, and a Program Error window pops up in the background. I can switch over to that window and close it, but then my display is still set to 1920x1080, and I have to set it back manually, despite setting my Lutris preferences to change the resolution back when the game "exits" - I guess crashing doesn't count as exiting.

**Comment by yaomtc** [comment]
Turns out the crash was due to gameoverlayrenderer, so I disabled that and the game doesn't crash on launch anymore.

**Comment by strycore** [comment]
That's good but that doesn't solve (or confirm) the primary issue. I would have to find a game that crashes to be able to reproduce it.

**Comment by yaomtc** [comment]
Right now, I can't test any Steam game since Steam in Wine just broke on me, sorry. I believe due to this: https://bugs.winehq.org/show_bug.cgi?id=43315

**Comment by strycore** [comment]
Try Wine Staging 2.12, it's supposed to fix the Steam issue. I uploaded a build for it this afternoon.

**Comment by yaomtc** [comment]
Now, upon starting Steam for the first time, it gets stuck on "Verifying installation..." Never finishes, and hitting Cancel just causes it to freeze and requires me to terminate the process. So, I deleted the wine-steam folder just now, went to Manage Runners to install Wine Steam again... Why does it download wine-staging-2.6?

Also, I've noticed that Lutris isn't syncing properly unless I quit it and re-open it. Otherwise nothing appears.

**Comment by yaomtc** [comment]
Update: The reinstall fixed the "verifying installation" problem. I tried Deux Ex HR again, this time with DirectX 11 disabled and SSAO turned off. The game launched this time, except the menu screen had some serious visual glitchiness, and the game itself was painful to look at with its own unique stuttering glitchiness. Anyway, that's not really relevant here so I'll test again with some other settings, see what happens.

**Comment by yaomtc** [comment]
I enabled DirectX 11 and set the resolution down to 1920x1080, and now I can't access either the game or the setup window without it actually causing me to be forcibly logged out from my desktop. (Kernel panic, or something, I'd have to guess?)

Well, I guess now that Steam no longer works with the version of Wine I was using before... I guess I can't reproduce the resolution issue right now.

**Comment by dali99** [comment]
I've had this happen to me too FWIW.
I'll try to reproduce it

**Comment by dali99** [comment]
also turning one screen off, when the game is exited it turns it back on without respecting xorg config, requiring me to run randr again to fix. less I just get two identical screens.

At least it used to do this a few releases back

**Comment by tcarrio** [comment]
Depending on your Xorg and monitor configuration there were some issues that I recently submitted a PR to fix. Since you mention yours were identical screens afterward, it's likely that it tries to set the monitor with an offset first, then sets the second monitor without an offset (it was based only on input device listing order) leaving you with two monitors both at 0+0. If that was your problem, @dali99, it will  might be fixed in PR #647 once it hits.

You can confirm that it was the problem but checking if the first monitor in the output of `xrandr` has a non-zero offset (ie. 1920x1080+1920+0)

**Comment by strycore** [comment]
Since there's a recent issue with Wine where my primary resolution isn't detected but my TwinView resolution is used instead, I'll test this option after this release.

**Comment by xordspar0** [comment]
I can't reproduce this. I wrote a short program that changes the resolution with SDL and then calls `abort`. Normally this causes the resolution to be left messed up, but when I switch on Lutris's "restore resolution on game exit" Lutris correctly restores the resolution.

I tested this in a VM running KDE Neon on X with only one monitor.

My program's source:

```c
#include <stdio.h>
#include <unistd.h>

#include <SDL2/SDL.h>

int main() {
        if (SDL_Init(SDL_INIT_VIDEO) != 0) {
                printf("Failed to initialize SDL: %s", SDL_GetError());
                return 1;
        }

        SDL_Window *win = SDL_CreateWindow("Hello world!", 100, 100, 800, 600, SDL_WINDOW_SHOWN);
        if (win == NULL) {
                printf("Failed to create a window: %s", SDL_GetError());
                SDL_Quit();
                return 1;
        }

        if (SDL_SetWindowFullscreen(win, SDL_WINDOW_FULLSCREEN) != 0) {
                printf("Failed to set window to fullscreen: %s", SDL_GetError());
                SDL_Quit();
                return 1;
        }

        // Crash.
        abort();
        
        // Run normally.
        sleep(3);

        // Exit normally.
        SDL_Quit();
        return 0;
}
```

To compile, run

```
cc chresolution.c -o chresolution `sdl2-config --cflags --libs`
```

**Comment by yaomtc** [comment]
@xordspar0 My issue was to have _Lutris_ change the resolution, not the program itself. I meant Lutris here:

> use the setup window to set its resolution

Can you test that instead?

**Comment by tcarrio** [comment]
@yaomtc both cases should be covered. My PR had included an update that would accommodate multi-monitor configurations in a deterministic manner (assuming that xrandr outputs the monitor configuration in the same format, though I have no reason to believe it has changed). If you can run a similar test setting the resolution with Lutris as opposed to with SDL, that would cover the case @xordspar0 is concerned with.

Whether you are updating the resolution with Lutris pre-launch or the game updates resolution, the state of your displays is saved prior to either, and reset after the game exits. However, as @strycore mentioned, if xrandr were to not list an enabled monitors resolution, Lutris would not have any way of knowing how to reset the displays after the program had exited. It also does not attempt to retry failed display configuration with xrandr, if I remember correctly (but it's been roughly 3 years now).

**Comment by xordspar0** [comment]
> My issue was when I had Lutris change the resolution, not the program itself.

I see. I just did another test where I cut out the fullscreen part from my test app and told Lutris to set the screen resolution when the game starts. Results: Lutris correctly resets the resolution whether the "restore resolution on game exit" is enabled or not.

Note that this is still with only one monitor.

**Comment by yaomtc** [comment]
I see. This must be fixed now. Thanks @tcarrio for the fix and to @xordspar0 for testing.
