### ISSUE TITLE
Redesign Manage Versions dialog

### ISSUE THREAD

**Issue by yaomtc** [lutris/lutris#613]
I just found out, by experimentation, that you're supposed to double-click on a version to download it. There's no Install button. Also, it sometimes just doesn't work, for some reason. Like, just a moment ago I downloaded and installed another version and now nothing is happening. Wait, cancel that, now two are downloading, alright. I guess it also needs some indication of what's going on in the background and whether it's ready to grab another wine version.

**Comment by akien-mga** [comment]
I agree, I was just confused too when trying to use it. Clicking on the checkbox does not actually tick the checkbox, so one feels like nothing happened. It actually starts the download, a progress bar is filled, and the box ends up ticked once the download is complete, but that's not a great UX (especially as it can take a few seconds for the "1%" of the progress bar to appear, so you might tick 3 or 4 entries before you realise they're all getting downloaded, as I did).

A simple UX would be to have the possibility to tick one or more entries without triggering any download (just select them), and have based on the context either an "Install", an "Uninstall" or both buttons that would apply the action to all selected entries.

**Comment by daniel-j** [comment]
We should add a view so you can see what wine versions are in use, and maybe a "remove unused wine versions" button.

**Comment by AlexanderRavenheart** [comment]
Here is my proposal for revamping the Wine Versions Manager:
![wine versions manager](https://user-images.githubusercontent.com/7274337/46093097-23e62600-c1bf-11e8-9554-316bfeb345bc.png)

**Comment by tannisroot** [comment]
I think the current design of the menu is pretty good now.

**Comment by strycore** [comment]
we still need something that differentiates between available versions and locally installed versions

**Comment by yaomtc** [comment]
The UI in the current version I have (0.4.23) is definitely a big improvement. It responds nearly instantly with the "downloading" indicator. Good job!

**Comment by AlexanderRavenheart** [comment]
I will have an update regarding this in the next few days.

**Comment by DrDoctor13** [comment]
Is there any update on this? There's still no visible way of telling which versions are currently being used and which ones are safe to remove.

**Comment by AlexanderRavenheart** [comment]
There were some design proposals made some time ago on discord and I was too busy to finish the implementation. I'll resume working on this topic this week.

**Comment by AlexanderRavenheart** [comment]
If no one has picked this up in the time I've not been contributing, I will resume working on it in 2 weeks from now.
