### ISSUE TITLE
Can't Install Steam (Wine) Games

### ISSUE THREAD

**Issue by michael-nischt** [lutris/lutris#615]
I tried installing Dark Souls 2 and failed and now I wanted to play Battlerite during the free weekend but installing yields the following error:

`DEBUG    2017-07-13 22:36:48,197 [runtime]:Runtime steam is up to date
DEBUG    2017-07-13 22:36:48,199 [runtime]:Runtime lib32 is up to date
DEBUG    2017-07-13 22:36:48,199 [runtime]:Runtime lib64 is up to date
DEBUG    2017-07-13 22:36:48,200 [runtime]:Runtime p7zip is up to date
INFO     2017-07-13 22:36:48,201 [lutriswindow]:Connected to lutris.net as micha
DEBUG    2017-07-13 22:36:48,204 [api]:Fetching game library
DEBUG    2017-07-13 22:36:48,260 [steam]:Watching Steam folder /home/micha/.steam/steam/steamapps
INFO     2017-07-13 22:36:52,499 [lutriswindow]:Installing None
DEBUG    2017-07-13 22:36:52,508 [interpreter]:Fetching installer https://lutris.net/api/installers/battlerite
DEBUG    2017-07-13 22:36:55,444 [interpreter]:Installer command: install_steam_game
WARNING  2017-07-13 22:36:55,486 [winesteam]:Data path for SteamApp 504370 not found.
DEBUG    2017-07-13 22:36:55,486 [interpreter]:Installing steam game 504370
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
ILocalize::AddFile() failed to load file "public/steambootstrapper_unknown.txt".
net.cpp (262) : Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045)
net.cpp (262) : Fatal assert failed: net.cpp, line 262.  Application exiting.

Assert( Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045) ):net.cpp:262

_ExitOnFatalAssert`

I keeps showing the 'Installing Game Data' dialog with no progress forever. Only thing I can to is cancel the installation.

**Comment by strycore** [comment]
This does not contain enough information to do anything, please use the forums, IRC or Discord for game specific questions
