### ISSUE TITLE
Steam integration not working

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#618]
I added some games to Steam as non-Steam games but they won't launch. It launches Lutris and asks to launch the game or install but selecting launch doesn't do anything. 

Lutris version 0.4.13

Here's the output:

    Gtk-Message: Failed to load module "unity-gtk-module"
    DEBUG    2017-07-28 19:21:42,856 [runtime]:Runtime steam is up to date
    DEBUG    2017-07-28 19:21:42,857 [runtime]:Runtime lib32 is up to date
    DEBUG    2017-07-28 19:21:42,857 [runtime]:Runtime lib64 is up to date
    DEBUG    2017-07-28 19:21:42,857 [runtime]:Runtime p7zip is up to date
    INFO     2017-07-28 19:21:42,858 [lutriswindow]:Connected to lutris.net as user
    DEBUG    2017-07-28 19:21:42,859 [api]:Fetching game library
    DEBUG    2017-07-28 19:21:42,905 [steam]:Watching Steam folder /home/user/.steam/steam/steamapps
    DEBUG    2017-07-28 19:21:42,905 [steam]:Watching Steam folder /home/user/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/steamapps
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

![Properties](https://i.imgur.com/cnwGdcw.png)

![Launch options](https://i.imgur.com/UlZunH8.png)

**Comment by strycore** [comment]
in the launch options set `lutris:rungame/mass-effect-2`

**Comment by RobLoach** [comment]
Updated https://github.com/lutris/lutris/wiki
