### ISSUE TITLE
Cores needed for PR

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#620]
Cores I compiled for the [PR](https://github.com/lutris/lutris/pull/619)

[cores.zip](https://github.com/lutris/lutris/files/1185456/cores.zip)

**Comment by telanus** [comment]
closing this as the cores is now finally all officially available here: https://buildbot.libretro.com/nightly/linux/x86_64/latest/

**Comment by strycore** [comment]
The cores can indeed be downloaded from Retroarch itself but we still provide builds for them anyway. The main issue with that PR is that the cores have to be built from the same container that was used to build Retroarch (and all other runners)

**Comment by telanus** [comment]
why?

**Comment by strycore** [comment]
To ensure binary compatibility between the cores, retroarch and the lutris runtime. If you did build the cores on Ubuntu 16.04 then it's not much of an issue but I don't want to start accepting 3rd party binaries if I can avoid it, the buildbot is there for that.

**Comment by telanus** [comment]
That's why closed my ticket, as being in the Libretro buildbod, means it can be officially build everywhere, thus a "custom" build like mine (which was build on ubuntu 16.04) is not necessary.

**Comment by telanus** [comment]
@strycoreany update on this PR?
