### ISSUE TITLE
Lutris hangs/freezes when running PCSX2

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#622]
The games seem to run fine but Lutris hangs while playing and I get prompted to either wait or force quit. Lutris functions normally after quitting PCSX2. I'm using the latest unstable version of PCSX2 (1.5.0-0) not the built-in runner. 

Ubuntu 17.04

lutris -d output: https://pastebin.com/b3EM81HD

**Comment by strycore** [comment]
Custom runners are not officially supported, this is probably an issue with the runtime, see here: http://wiki.lutris.net/index.php/Runtime
