### ISSUE TITLE
Script to load Antimicro and a Game fail to load Keybind Profiles over Lutris?

### ISSUE THREAD

**Issue by Delikt** [lutris/lutris#624]
Pls look @ the Antimicro Thread i opened: https://github.com/AntiMicro/antimicro/issues/166

My exec script work fine without Lutris... so im not sure on what side (Antimicro,Lutris,my Script) are the issue to fix.

Ty for help and comfortable my Gaming on Linux experience :)

**Comment by strycore** [comment]
Can you re-open an issue on the Lutris repository about what exactly you're trying to do? It's very unclear to me at this point.
