### ISSUE TITLE
Dark Souls 2 SotFS: incomplete controller support

### ISSUE THREAD

**Issue by Skylead** [lutris/lutris#625]
Controller input is missing clicking the left stick in (for jump) for wired 360 controller

Issue persists for x360ce and koku

**Comment by strycore** [comment]
Please do not use koku-xinput, this option will be removed soon. Use the "Path to the game's executable, for x360ce support" option and try with and without the dinput8 option.

I only tried Dark Souls 1 with the DSFix patch, I don't know if controllers works without it.

**Comment by setzer22** [comment]
I can confirm that the steam controller has the same issue. In my case I fixed it by remapping the left stick click to the jump keyboard key (F, if I recall correctly).

I feel it is also relevant to mention that in my case there is no way to execute a strong attack (right trigger full press) in the game. In this case not even with the keyboard equivalent keys. Does that work with other controllers?

I am willing to further test this and provide any additional data that may help.

**Comment by Skylead** [comment]
I loaded it up to test again and same issue after trying strycore's suggestion. Like setzer22 I notice that strong right weapon input (Right trigger) also won't activate in game.

If I right click the game from Lutris and select Joystick Control Panel all my inputs show up in the test tab.

**Comment by setzer22** [comment]
Also, just in case, I can confirm the game works fine under windows and the exact same controller.

**Comment by strycore** [comment]
Try the new option for dumbxinputemu

**Comment by strycore** [comment]
Controller now works properly in Dark Souls 2. (Source: Pedro Mateus)
