### ISSUE TITLE
Login failed due to SSL problem

### ISSUE THREAD

**Issue by louisld** [lutris/lutris#626]
There is a problem with the certificate of the API.
[api]:Unable to connect to server (https://lutris.net/api/accounts/token): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)>

**Comment by strycore** [comment]
Probably a network hiccup, our SSL certificate is fine, we use LetsEncrypt and it gets renewed automatically. 

Please re-open if this is a persistent issue and not a one time thing.

**Comment by soredake** [comment]
@strycore how about cert for https://wiki.lutris.net/index.php/Main_Page ?

**Comment by strycore** [comment]
@soredake yes, that's running on a different container and sub domain, I need to set up a certificate for it as well.

**Comment by louisld** [comment]
After several weeks the problems with ssl certificates is still here. I tried different networks so I don't think it's due to network problem.

**Comment by strycore** [comment]
@louisld do you get SSL certificate warnings with you fetch that URL with curl? Are you behind a proxy, firewall, or have an unusual Internet connection setup?

**Comment by louisld** [comment]
@strycore When I fetch the url with curl it works fine : `curl https://lutris.net`. My connection is a normal setup with my computer connected to a router and I tried on different networks. I don't know where this problem can come from.
