### ISSUE TITLE
Dolphin executable fails on Arch Linux

### ISSUE THREAD

**Issue by setzer22** [lutris/lutris#627]
On Arch, I am unable to launch any game that uses the Dolphin Runner. Moreover, I cannot even add them as Linux games and launch /usr/bin/dolphin-emu executable. Both fail with similar errors:

When using the runner:
```
/home/myusername/.local/share/lutris/runners/dolphin/dolphin-emu: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
And when trying to launch /usr/bin/dolphin-emu through the Linux Runner
```
/usr/bin/dolphin-emu: /home/josep/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libatk-bridge-2.0.so.0)
/usr/bin/dolphin-emu: /home/josep/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libatspi.so.0)
/usr/bin/dolphin-emu: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
I can run dolphin just fine outside of Lutris, so it seems this must be some kind of problem introduced by the custom libraries that Lutris loads. 

**EDIT** It seems that disabling Lutris Runtime makes the linux runner correctly launch dolphin (since no library overrides are done), however, the dolphin runner still doesn't work.

**EDIT2** Specifying a custom dolphin executable in conjunction with disabling Lutris runtime allows me to use the dolphin runner with my native dolphin, which does work.

**Comment by strycore** [comment]
Runtime issue, see here: http://wiki.lutris.net/index.php/Runtime
