### ISSUE TITLE
How do i play Star Wars the old republic on lunixmint

### ISSUE THREAD

**Issue by MytruiousGaming** [lutris/lutris#628]
I have a steam account and lutris account,And when i go to download lutris,I don't see a a LunixMint file script or Terminal Comands,SO i don't understand how i download Lutris or any of it's games. Can you help? My Account is LordAzulon and my Gmail is Trickgames65@gmail.com on lutris.

**Comment by strycore** [comment]
For support questions, please use IRC, Discord or the forums. you should be able to install Lutris on Mint using the Ubuntu repositories.

**Comment by MytruiousGaming** [comment]
Thx bro
