### ISSUE TITLE
Lutris on HiDPi display has tiny UI

### ISSUE THREAD

**Issue by adomas187** [lutris/lutris#631]
Hello,
I have first time installed Lutris on my Arch Linux box with KDE Plasma DE. Mostly I use Qt apps and it scales nicely on my HiDPI display (4K UHD 28"). GTK apps such as Chromium scales also nicely. On my desktop I use 1.5 scale ratio (150%), but Lutris ignores this ratio and uses 1 (100%) ratio which makes the User Interface tiny as Steam atm.

I gave Lutris a shot because of Steam UI which has a same problem on HiDPI displays.

While I can still scale to ratio 2 (200%) with the help of `export GDK_SCALE=2` command, it does not let me to use 1.5 ratio.

Lutris version: **0.4.13**

Not sure if this depends on Lutris or GTK3, but Chromium scales to 1.5 and it uses GTK3 too.

**Comment by TingPing** [comment]
Chromium doesn't use Gtk to render anything it just gets theme info and dialogs from it.

Lutris is purely limited by Gtk which is integer scaling only and expects your compositor to do any further scaling (GNOME-Shell 2.26 for example will support that). So there is nothing Lutris can do.

**Comment by guoyunhe** [comment]
Will upcoming GTK 4.0 support 1.5 scaling?

**Comment by guoyunhe** [comment]
GNOME just merged a PR that enables 1.5 scale. Might benefit Lutris, too.

https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/5

**Comment by TingPing** [comment]
GTK will never support fractional scaling, all rendering is done in whole integers.
