### ISSUE TITLE
Guild Wars 2 on Lutris

### ISSUE THREAD

**Issue by severuscold** [lutris/lutris#633]
lutris gw2 installer doesnt install required file to make gw2 work. I just ended up using PoL.

**Comment by RobLoach** [comment]
What required file?

**Comment by tcarrio** [comment]
I just installed Guild Wars 2 this week with Lutris perfectly fine. Could @severuscold elaborate more on the issue?

**Comment by strycore** [comment]
This is not the right place to discuss installer issues, please use the forums (or continue the discussion on this closed issue if you wish)
