### ISSUE TITLE
Adding custom runners

### ISSUE THREAD

**Issue by Azphreal** [lutris/lutris#639]
I can't find any documentation or even discussion on how custom runners (i.e., that go in `$XDG_DATA_HOME/lutris/runners`) are supposed to be used. I've tried putting the executables as well as desktop files and neither are detected. What is the format for a runner?

**Comment by strycore** [comment]
Custom runners are anything *but* what is located in `$XDG_DATA_HOME/lutris/runners`. Basically you set the path to whichever executable you want (probably in /usr but could be anywhere). When this is set, this executable will be used instead of the lutris provided one.

**Comment by Azphreal** [comment]
What's the point of the "open runners folder" button in the management panel then? If Lutris doesn't use the folder at all, why bother?

![screenshot from 2017-09-04 15-21-42](https://user-images.githubusercontent.com/21125058/30012660-f8cee756-9184-11e7-92cb-e203b9cee6cb.png)

**Comment by strycore** [comment]
What? Lutris uses that folder to store its own runners. And that button is here to quickly access them (and it's currently the only way to uninstall runner, open the folder, delete the runner and hit refresh on Lutris.)

**Comment by Azphreal** [comment]
Oh, so it does. The runners I had were installed via the package manager and not Lutris, so it was empty when I posted this though I had five available runners. Sorry for the confusion.

**Comment by strycore** [comment]
No problem :D
