### ISSUE TITLE
Ubuntu packages missing?

### ISSUE THREAD

**Issue by edasaki** [lutris/lutris#642]
Are the instructions for installing on Ubuntu current?

I don't see any strycore on http://download.opensuse.org/repositories/home%3A/

Similarly, this page exists ( https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris ) but the direct binary links 404. Is the only option to clone this repo, or has the package simply moved to somewhere else?

**Comment by strycore** [comment]
OBS is having issues today, sorry for the inconvenience… 

https://twitter.com/openSUSE/status/905530011540746250
