### ISSUE TITLE
Repository does not have a Release file

### ISSUE THREAD

**Issue by lagerspetz** [lutris/lutris#643]
Hi,
I have been updating Lutris just fine up until now. When I run apt-get update on Ubuntu Gnome, I get:

E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.10 ./ Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Any ideas?

**Comment by edasaki** [comment]
I was just wondering this yesterday 😄 #642 opensuse is having issues

**Comment by leberknecht** [comment]
Same here :/ You can install it manually, something like:

```bash
wget https://github.com/lutris/lutris/archive/v0.4.13.tar.gz
tar xzf v0.4.13.tar.gz
cd lutris-0.4.13
sudo setup.py install
```
in my case i had pip3 and setuptools dependencies missing:
```bash
sudo apt-get install python3-pip
pip3 install setuptools
```
and for some reason the contents of share were not copied to /usr/share:
```bash
sudo cp share/lutris /usr/local/share -R
```

**Comment by strycore** [comment]
just an heads up, using `sudo setup.py install` is highly discouraged and will not be supported.

**Comment by edasaki** [comment]
I was able to set it up by just doing
    ` git clone https://github.com/lutris/lutris.git`
and running the executable at `/bin/lutris`, it seemed to work fine out of the box

**Comment by strycore** [comment]
Yes, that's the preferred way of running Lutris. The URL handlers won't be installed but that shouldn't be an issue if Lutris was previously installed (and not removed)

**Comment by leberknecht** [comment]
Uhh, indeed :)

fyi: I ran it with sudo because without i got
```bash
% ./setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-13443.write-test'
```
Maybe my env is buggy. Anyways, the bin works fine :)

**Comment by strycore** [comment]
No, your not environment is not buggy, you need root to write to /usr.

**Comment by daniel-j** [comment]
The repo is back online.
