### ISSUE TITLE
Lutris not exactly installing games

### ISSUE THREAD

**Issue by dbzlotrfan** [lutris/lutris#645]
So I have installed Lutris and it seems games I try to install either won't (bejweled 3, Witcher 3, Age of . . .) or if they do install (Brutal Wolfenstein, DOOM II) they don't have sound. This is the output from the terminal:

> dlf@dlf ~ $ lutris  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "Torchlight 2" (app: gog_com-Torchlight_2_1, slug: torchlight-2)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "KPatience" (app: org.kde.kpat, slug: kpatience)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "Torchlight 2 ModLauncher" (app: gog_com-Torchlight_2_2, slug: torchlight-2-modlauncher)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "LBreakout2" (app: lbreakout2, slug: lbreakout2)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "GZDoom" (app: gzdoom, slug: gzdoom)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "QZDoom" (app: qzdoom, slug: qzdoom)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "GFCE Ultra NES Emulator" (app: gfceu, slug: gfce-ultra-nes-emulator)  
> INFO     2017-09-09 00:35:42,991 [xdg]:Found desktop game "OpenMW Launcher" (app: openmw, slug: openmw-launcher)  
> INFO     2017-09-09 00:35:42,992 [scummvm]:No ScummVM config found  
> INFO     2017-09-09 00:35:43,920 [lutriswindow]:Connected to lutris.net as dlf  
> INFO     2017-09-09 00:35:50,433 [lutriswindow]:Installing None  
> WARNING  2017-09-09 00:35:52,370 [winesteam]:Data path for SteamApp 78000 not found.  
> wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"  
> WARNING  2017-09-09 00:35:52,461 [joypad]:python3-evdev not installed, controller support not available  
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".  
> ILocalize::AddFile() failed to load file "public/steambootstrapper_unknown.txt".  
> net.cpp (262) : Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045)  
> net.cpp (262) : Fatal assert failed: net.cpp, line 262.  Application exiting.  
>   
> Assert( Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045) ):net.cpp:262  
>   
> _ExitOnFatalAssert  
> INFO     2017-09-09 00:36:11,065 [lutriswindow]:Installing None  
> WARNING  2017-09-09 00:36:13,227 [winesteam]:Data path for SteamApp 292030 not found.  
> wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"  
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".  
> net.cpp (262) : Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045)  
> net.cpp (262) : Fatal assert failed: net.cpp, line 262.  Application exiting.  
>   
> Assert( Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045) ):net.cpp:262  
>   
> _ExitOnFatalAssert  
> WARNING  2017-09-09 00:36:18,862 [joypad]:python3-evdev not installed, controller support not available  
>   

So how can I fix this? If it matters i'm on Mint 18.2 (Cinnamon) and the install is fairly recent . . .  I'll try a Mint VM and see what happens.

**Comment by strycore** [comment]
try launching with `LUTRIS_RUNTIME=0 lutris` and see if that solves the issue

**Comment by Zeioth** [comment]
No answer in half a year. I propose closing this issue.

**Comment by strycore** [comment]
Agreed, this bug report is too vague to be worked on.
