### ISSUE TITLE
Invalid runner names prevent game list from loading

### ISSUE THREAD

**Issue by Jardasu** [lutris/lutris#646]
I have quite a big library of games. 506 games in Lutris database right now.
But Linux client version 0.4.13 show only first 318 of them.

**Comment by strycore** [comment]
I have nearly 1000 games, did you make sure you display both installed and uninstalled games in the client?

**Comment by telanus** [comment]
@Jardasu I have roughly 780 installed and according to the lutris website I have 1231 games in my lutris library so there shouldn't be a problem (except slow loading the first time but that's because of my potato being slow)

**Comment by Jardasu** [comment]
Yes, I did. All games are present from begining of alphabet till P. But no game which name start with letter from second half of alphabet.
Did not mention, that I'm using it under Linux

**Comment by Jardasu** [comment]
Tried to look into ~/.local/share/lutris/pga.db

`$ sqlite3 pga.db 
SQLite version 3.20.1 2017-08-24 16:21:36
sqlite> select * from games;
1|Aaaaa! for the Awesome|aaaaa-for-the-awesome|||||2014-09-12T18:01:56.655000||||2013|15560||||
2|Aberoth|aberoth|Linux||||2015-09-03T14:47:54.603439|0|0|||354200||aberoth-1485983163||
3|Afterfall InSanity Extended Edition|afterfall-insanity-extended-edition|||||2017-08-27T22:31:47.978099Z|||||224420||||
4|Air Conflicts: Pacific Carriers|air-conflicts-pacific-carriers|||||2013-12-16T01:29:09.525000|||||214910||||
5|Alan Wake|alan-wake|||||2017-08-31T12:08:27.117495Z||||2010|108710||||
6|Alan Wake's American Nightmare|alan-wakes-american-nightmare|||||2017-08-31T11:58:26.802681Z||||2012|202750||||
...
510|Sisyphus Reborn|sisyphus-reborn|Linux|||||0|0|||517910||sisyphus-reborn-1487028420||
511|Project Highrise|project-highrise|Linux|||||0|0|||423580||project-highrise-1489757918||
512|Fantasy General|fantasy-general|||||2017-04-20T22:37:12.322928Z||||1996|||||
513|Heroine's Quest: The Herald of Ragnarok|heroines-quest-the-herald-of-ragnarok|Linux|steam||||0|1|||283880||heroines-quest-the-herald-of-ragnarok-1503832725||
514|Satellite Reign|satellite-reign|||||2015-05-17T09:33:44.382000Z|||||268870||||
515|The Blackwell Deception|the-blackwell-deception|||||2017-09-10T13:43:39.552216Z||||2011|80360||||
`
But gui does not show anything after _Project Highrise_. No _Satellite Reign_ for example, even search for satellite shows no result.

**Comment by Jardasu** [comment]
Hi, after some time I resolved this problem. I had installed Project Zomboid, that has in pga.db value desura in runner column.
And this is the reason, that stops loading games. So all games after Project Zomboid are missing. Everything is ok after changing desura to linux.

**Comment by strycore** [comment]
oh, that's a nasty bug, it looks fairly simple to reproduce so I should get a fix out soon
