### ISSUE TITLE
Allow custom resolution for virtual desktop

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#648]
Allow a custom res option to be set alongside the current presets under runner options.

**Comment by Xenega** [comment]
What runner are you talking about ? Because if it's wine, it has already it.

**Comment by strycore** [comment]
@Xenega the resolution can be set from one of the native resolutions gathered from Xrandr but it should also be possible to set fully custom resolutions like 2000x2000 for example.

**Comment by Xenega** [comment]
@strycore 
The resolution can already be fully customized, the field is modifiable as input. Maybe it's not enough user-friendly. What do think about add a preset value "custom" that clear the input and start focus ?

**Comment by strycore** [comment]
Oh, I had forgotten about that. I'm afraid that if we add extra widgets to the already crowded Wine option screen, it might clutter the UI too much.
We might want to revisit this once we re-organise configuration  widgets visually, for the moment, I'm cool with having just an editable drop down.

**Comment by strycore** [comment]
Closing, already fixed.
