### ISSUE TITLE
Provide action to relocate the game files

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#65]
As a user I can see were my game files are located and move them to another location. A good position for this option would be somewhere in the EditGameDialog (not in the "Game" tab since that is built programmatically and only deals with game settings)

The relocate option should open a Dialog similar to what can be found in Transmission, asking the user if the program should move the files or if they are already at the chosen destination)

Before implementing this, there should be a get_game_files available in each runner, pointing to the ROM(s) or folder for a specific game. Most runners rely on ROMs and they are usually all stored in the same directory.

**Comment by strycore** [comment]
Aaaaand ... it's pushed back again.

**Comment by Henpei** [comment]
Would be nice to also add an option to only copy the game files to another directory.
I have had some trouble when manually adding SNES games from a usb disk. The next time I started the game I had the disk in another computer so the rom file were not present.

**Comment by strycore** [comment]
Aaaaand ... it's pushed back again.

**Comment by strycore** [comment]
Done
