### ISSUE TITLE
Dosbox: specify game data folder to launch Dosbox from this directory and support relative path

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#650]
Hello,
could it  be possible to add a game data directory field for Dosbox ?
In DosBox, you can mount images or directories relative _**to the working directory from which DOSBox was started**_, 
for example:
mount d "..\cd_image\game.iso" -t iso
I use this feature in all of my Dosbox conf files, so my conf does not work in Lutris.
If I could specify the game data folder  in Lutris, Dosbox could find my relative path, look at this process:
Lutris should first go to the directory where are store the game data:
$ cd /directory/to/the/game/data (folder specified by the user in Lutris Dosbox parameters)
then launch Dosbox with the conf file:
$ '/home/legluondunet/.local/share/lutris/runners/dosbox/bin/dosbox' -conf 11th-hour-dosbox-linux.conf 
I just tested this way, it works.

**Comment by FakeShemp** [comment]
A lot of commercial dosbox-using games use a working directory different from the directory of the conf/exe files, so I agree that this would be a good idea, as it would simplify making installers for those games.

**Comment by strycore** [comment]
I added the working_dir option to dosbox (it's a standard option in Lutris), this should fix the issue, can someone test the current master branch?

**Comment by legluondunet** [comment]
it works! Good work! Thanks.
