### ISSUE TITLE
pcsx2: crashes at launch on Ubuntu 17.10

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#651]
Hello,
I can not use your PCSX2 wrapper on Ubuntu 17.10, it crashes at launch

Thank you for your help.
LGDN

**Comment by strycore** [comment]
Do you have the console output when PCSX2? This is not enough information to deal with this issue.

**Comment by legluondunet** [comment]
in a terminal, that's all I have:
$ ./PCSX2-linux.sh 
Illegal instruction (core dumped)

**Comment by strycore** [comment]
Did you try with and without the runtime enabled? It's in the system options of the game. Also, I'll push a new build of PCSX2 to see if that helps.

**Comment by legluondunet** [comment]
no change, with or without runtime enabled 
in a terminal:

$ ./PCSX2-linux.sh
Illegal instruction (core dumped)

**Comment by sysms** [comment]
Same problem here on Debian 9 with current Lutris 0.4.14:

~/.local/share/lutris/runners/pcsx2$ ./PCSX2-linux.sh 
Illegal instruction

Also I had to make the script "PCSX2-linux.sh" executable before (chmod a+x), because executable permissions were missing from this script.

**Comment by strycore** [comment]
Updated the PCSX2 with latest master branch from github. Runs flawlessly on Ubuntu 18.04, with runtime enabled.

**Comment by legluondunet** [comment]
Still crashes on my computer, how can I help you to debug?

~/.local/share/lutris/runners/pcsx2/$ ./PCSX2-linux.sh 
Illegal instruction (core dumped)

~/.local/share/lutris/runners/pcsx2/$ ./PCSX2 
Instruction non permise (core dumped)
