### ISSUE TITLE
View on Lutris.net raises Mozilla Crash Reporter of Firefox when Wine is running

### ISSUE THREAD

**Issue by sjuk** [lutris/lutris#654]
First of all: Lutris is by far the best approach to improve the gaming experience on linux I saw for a long time. Thank you for that. :-)

The Issue is reproducible with Lutris 0.4.13 on Ubuntu 16.04.3 (64bit).

- Start
- Lutris
- Start Starcraft Remastered (or any other windowed game)
- Activate Lutris window and rightclick on any game and choose "View on Lutris.net"

-> Mozilla Crash Reporter raises instead of showing game in Firefox

Here is the console output of Lutris:
`(firefox:9846): GLib-ERROR **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:100: failed to allocate 18446744073271633382 bytes`
`ExceptionHandler::GenerateDump cloned child 9853`
`ExceptionHandler::SendContinueSignalToChild sent continue signal to child`
`ExceptionHandler::WaitForContinueSignal waiting for continue signal...`
`Failed to open curl lib from binary, use libcurl.so instead`

The last line (Failed to open curl lib from binary, use libcurl.so instead) appears after closing Mozilla Crash Reporter Dialogue.

Feel free to ask for more information if needed.

Thank you in advance
sjuk

**Comment by strycore** [comment]
I fixed the same problem happening after a game has quit, I know how to fix this, I have to remove LD_LIBRARY_PATH from stuff like view on lutris or browse files.

**Comment by sjuk** [comment]
Thanky you. Let me know if I can help testing a fixed version.
