### ISSUE TITLE
Winesteam runner not completing install

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#655]
The winesteam runner installs but gets stuck on "verifying installation".

Ubuntu 17.04
Lutris 0.4.13

    lutris -d
    Gtk-Message: Failed to load module "unity-gtk-module"
    ERROR    2017-09-25 19:36:17,331 [steam]:Malformed config file: 030000005e040000a102000000010000,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,

    ERROR    2017-09-25 19:36:17,332 [steam]:Malformed config file: 030000005e0400008e02000010010000,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,

    ERROR    2017-09-25 19:36:17,332 [steam]:Malformed config file: 03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"

    DEBUG    2017-09-25 19:36:18,187 [runtime]:Runtime lib64 is up to date
    DEBUG    2017-09-25 19:36:18,187 [runtime]:Runtime steam is up to date
    DEBUG    2017-09-25 19:36:18,187 [runtime]:Runtime lib32 is up to date
    DEBUG    2017-09-25 19:36:18,187 [runtime]:Runtime p7zip is up to date
    INFO     2017-09-25 19:36:18,188 [lutriswindow]:Connected to lutris.net as ShiaLeBuffman
    ERROR    2017-09-25 19:36:18,189 [steam]:Malformed config file: 030000005e040000a102000000010000,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,

    ERROR    2017-09-25 19:36:18,190 [steam]:Malformed config file: 030000005e0400008e02000010010000,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,

    ERROR    2017-09-25 19:36:18,190 [steam]:Malformed config file: 03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"

    DEBUG    2017-09-25 19:36:18,192 [api]:Fetching game library
    DEBUG    2017-09-25 19:36:18,236 [steam]:Watching Steam folder /home/cxf/.steam/steam/steamapps
    DEBUG    2017-09-25 19:36:21,692 [thread]:Command env: STEAM_RUNTIME="/home/cxf/.local/share/lutris/runtime/steam" LD_LIBRARY_PATH="/home/cxf/.local/share/lutris/runtime/lib32:/home/cxf/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/i386/lib:/home/cxf/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/i386/usr/lib:/home/cxf/.local/share/lutris/runtime/lib64:/home/cxf/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/amd64/lib:/home/cxf/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH" WINEARCH="win32" WINE="/home/cxf/.local/share/lutris/runners/wine/staging-2.17-x86_64/bin/wine" WINEDEBUG="" WINEPREFIX="/home/cxf/.local/share/lutris/runners/winesteam/prefix" 
    DEBUG    2017-09-25 19:36:21,692 [thread]:Running command: "/home/cxf/.local/share/lutris/runners/wine/staging-2.17-x86_64/bin/wine" "/home/cxf/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/Steam.exe" "-no-cef-sandbox"
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable STEAM_RUNTIME to /home/cxf/.local/share/lutris/runtime/steam
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/cxf/.local/share/lutris/runtime/lib32:/home/cxf/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/i386/lib:/home/cxf/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/i386/usr/lib:/home/cxf/.local/share/lutris/runtime/lib64:/home/cxf/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/amd64/lib:/home/cxf/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/cxf/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable WINEARCH to win32
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable WINE to /home/cxf/.local/share/lutris/runners/wine/staging-2.17-x86_64/bin/wine
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable WINEDEBUG to 
    DEBUG    2017-09-25 19:36:21,693 [thread]:Storing environment variable WINEPREFIX to /home/cxf/.local/share/lutris/runners/winesteam/prefix

**Comment by AccountOneOff** [comment]
After killing the above command the Steam login window popped up. I don't know if I should close this so I'll let one of you do that.

**Comment by GloriousEggroll** [comment]
had the same problem. looks like this happens when you set the runner to an x86_64 runner. the prefix created by default is 32 bit. i changed it to use an i386 runner and it worked.

**Comment by Sethox** [comment]
This makes it work, but then there is the 64 bit problem of wine. As it is right now winesteam becomes a 32-bit architecture automatically with no choices, certain games needs 64-bit (x86_64) architecture for steam. There should be a choice for just 32-bit, 64-bit with 32-bit or just 64-bit architecture for wine.

**[Suggestion]**
And then let the user choose on their own, and for custom choice even set the installed (what Lutris can detect) wine version.

**Comment by jiri-bati-novak** [comment]
I have exactly the same problem, on Solus 3, tried all what is suggested here, even tried to install wine steam with latest i386 wine 3.0, but I am still stuck with "verifying installation" popup :(

**Comment by JamesHealdUK** [comment]
Echoing @Sethox on that one... Thats something crucial when it comes to Winesteam, itd be great if someone could put a choice in for it.

**Comment by Zeioth** [comment]
I'm having the same issue here.

**Comment by AccountOneOff** [comment]
@Zeioth @jiri-bati-novak Could you test if disabling dwrite in winecfg fixes the "verifying installation" problem?

**Comment by AccountOneOff** [comment]
@Zeioth Was that with the addition of disabling `dwrite`?

**Comment by Zeioth** [comment]
No, nothing to do with it, i just deleted the directory, and when I tried to install a new game from Lutris.net Steam was reinstalled automatically.

**Comment by Zeioth** [comment]
**STATUS:** Bug confirmed.
**IDEAL SOLUTION:** Wine Steam must to reinstall Steam after changing the wine version. 
**ALTERNATIVE SOLUTION:** Disable the option to change the wine version of Wine Steam (After all, you can use a custom wine version for every new game you install.)

![](https://user-images.githubusercontent.com/3357792/39482598-fa2af61a-4d6f-11e8-9315-0d0140d7bcba.png)

**Comment by strycore** [comment]
On the latest master and with wine set to 3.6 staging x86_64, the install finished successfully.
