### ISSUE TITLE
Editing install scritps to use local files

### ISSUE THREAD

**Issue by bezze** [lutris/lutris#656]
I'm trying to install League of Legends. Lutris constantly fails to download correctly the file (which is pretty big and connection painfully slow... 8+ hours) but still believes the game was installed correctly. So I slowly downloaded the file using wget over several days (would it be to hard to implement a pausable downloader?). Now, when trying to edit the json install script to use the local file I discovered that when passing the file to the lutris command it just seeks for the json file on the web "https://lutris.net/api/installers/custom-installer-name" and doesn't really care about the edited file contents. Is this intentional? Can this behaviour be overridden? How can I force the local file? Btw, I tried using the yaml script with `lutris --install file.yml` and failed too, something about "runner" fields missing.

**Comment by Xenega** [comment]
@bezze 
Download the installer file and extract the first element of the table named result, then put in a file. That will work.

@strycore 
The link to download installer is the api link, but the api add paging information and can return multiples values.
Two solutions : 
- Add a parameter in url to have only the first found installer.
- Allow lutris to detect paging information in install file.

You choose. (Assign it to me)

**Comment by strycore** [comment]
Some recent commit fixes that. Will be available in 0.4.15
