### ISSUE TITLE
Lutris Will Not Start

### ISSUE THREAD

**Issue by LinuxNexus** [lutris/lutris#660]
I Just Installed Lutris From The [ Play Deb Repo](http://www.playdeb.net) But It Won't Startup (Ubuntu 16.04) I Get The Following Error In The Terminal:-
`Traceback (most recent call last):
  File "/usr/games/lutris", line 27, in <module>
    locale.setlocale(locale.LC_ALL, locale.getlocale())
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
`
What Am I Supposed To Do?

**Comment by 1nF0rmed** [comment]
Have you tried this:
`export LC_ALL=C`
Reference: [https://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting/43203667](url)

**Comment by Xenega** [comment]
Yes, it's not a lutris issue but a system configuration issue.

@strycore 
What do you think about a more useful error message if LC_ALL is empty ?
"LC_ALL is empty" ?

**Comment by strycore** [comment]
I mentioned the LC_ALL=C trick in the error message. If anyone can provide a better message, please send a PR.
