### ISSUE TITLE
Starcraft 2 installation failes

### ISSUE THREAD

**Issue by rmbleeker** [lutris/lutris#662]
I've tried a couple of times to install Starcraft 2 (DX11) through Lutris on Ubuntu 16.04 LTS. It all starts out well with Wine being installed and even the Battle.net client, but I run into a problem at step 5:

5) Close Blizzard App (Select "Exit Application") after it has started.
After exiting Blizzard App, wait about a minute for the install to finish.

I followed these instructions to the letter, but even after waiting half an hour the installation doesn't complete itself as I would expect. I've saved the log from 2 attempts. 

https://gist.github.com/rmbleeker/c81903c4c0b9bb1aa418354e33f58ed1
https://gist.github.com/rmbleeker/8c17c272e2dba75d111a036dc30e3cb7

**Comment by rmbleeker** [comment]
The DX9 version seems to finish installing the Battle.net client correctly. I'm not sure what the difference it, I only noticed that after the installation of the Battle.net client Wine switches to Windows 10 mode for Starcraft 2, but in my opinion that shouldn't make a difference for the installation.

**Comment by Xenega** [comment]
The problem is that the installer wait for Agent.exe to exit but Agent.exe is a daemon and will never stop. When Battle.net is closed, Agent.exe continue to work. You must kill Agent.exe.

This is a problem with the installer, not with lutris.

**Comment by rmbleeker** [comment]
I know what you mean but I actually never got to the point where there was any Agent.exe to close, the whole Battle.net client failed to install. Anyway, this seems to be resolved with the new installer that installs Battle.net as a runner. Closing
