### ISSUE TITLE
Integrate Nix into Lutris

### ISSUE THREAD

**Issue by aszlig** [lutris/lutris#666]
I've started work on this by tearing apart a lot of the current code base already, so I thought it would be a good idea to announce my changes prior to continuing because it will be quite a substantial change and people might have objections against it.

So before continuing on this I'd like to have some feedback first, so please give a thumbs up if you'd support this change or thumbs down with a comment why you don't like it.

## Why [Nix](https://nixos.org/nix/)?

Games managed via Lutris need a lot of dependencies which can break at various places and keeping different versions of them makes things even messier, Nix particularly solves this problem by isolating every dependency into its own unique subdirectory tied to its dependency graph rather than its version.

Aside from that, Nix offers sandboxing during builds, which is what personally kept me from using Lutris and similar projects as build recipes could potentially mess with the system (Lutris fortunately is the lesser evil in this regard).

## Benefits

 * Ability to roll back updates of either individual games and/or their dependencies.
 * Updates of games are atomic and a failed update won't break the current version.
 * All of the dependencies can be overridden either globally or by individual games, for example to use SDL2 with a patch it's enough to do `SDL2.overrideAttrs (_: { patches = [ /path/to/my/shiny/patch.diff ]; } )`.
 * Runtime will never break whenever users update their systems, because the full dependency chain is available and doesn't depend on libraries of the main system. For example right now, Lutris uses system dependencies of `libc`, `libpango`, `libgobject`, `libjpeg`, ... just to name a few. If one of them becomes incompatible during an upgrade, games will break.
 * Copying games with all dependencies is only a matter of either copying the Nix closure of the build product or (if connection speed is slow) the recipe to another machine.
 * Games can have different versions of their dependencies without conflicts.
 * Expressions for building games are purely functional and thus can't interfere with or harm the system.
 * Builds are fully sandboxed and only get the build dependencies that are explicitly specified.
 * It's easy to include tests for games, either via containers or via VMs.
 * Ability to rebuild games into different package formats, like eg. `.deb`, `.rpm`, snaps and whatnot.
 * Packages for games can have the full power of Nix expressions rather than just JSON or YAML.
 * Sandboxing for the runtime will be much easier to implement because we will already run with mount namespaces.
 * It's easy to use very old library versions, for example libc 5 for games from the stone age.
 * Fully reproducible builds, which helps a lot tracking down issues.
 * Dependencies for Lutris will be only the ones needed for the GUI and Nix, although the latter can also be imported using a tarball.
 * Users with Nix experience can fully customize every single package and dependency (which includes build-time dependencies) to their needs.
 * The full dependency chain can be built from source simply by disabling binary caching.
 * Helper utilities needed by Lutris itself can be built/fetched on-demand if they're not available at runtime (for example `xrandr`).
 
## Drawbacks

 * Dependencies will have more disk space requirements, because they're not only a few libraries but the full chain up to the `libc`.
 * Updating games also will have more disk space requirements, because the old version is never overwritten, so if you always garbage-collect immediately after an update every game in the worst case (if nothing can be deduplicated) still takes twice the space during an update.
 * At least kernel 3.8 is required because we'll need namespacing support, if we want to support older versions it's still possible but we'd need to either use `sudo` or run a daemon as root.

**Comment by TingPing** [comment]
Using Flatpak runtimes has been discussed in the past which while very different technologies largely solves the same problems.

**Comment by aszlig** [comment]
@TingPing: I'm not sure whether Flatpak really goes into the same direction. IIUC, you still have to deliver the runtime libraries/programs in binary and get deduplication only on the runtime level, so I guess for Lutris it should be roughly the same as with the current solution unless you start distributing all the games via Flatpak. IMHO the only improvement that Flatpak would bring compared to the current solution is that it's easier to switch between different runtimes.

**Comment by TingPing** [comment]
I believe you get nearly every single advantage as Nix except for as easily building from source.

**Comment by strycore** [comment]
I don't think this is going anywhere

**Comment by aszlig** [comment]
@strycore: This is still on my todo list, so I'll ping you again once I got time to do it.

**Comment by VanCoding** [comment]
Doing this would be insanely smart and could make gaming on linux an almost perfect experience, as games would almost be guaranteed to always run once supported.

**Comment by tgunnoe** [comment]
I agree 100% with the goal of this ticket. Any more thoughts on it @aslig? My nix experience is slowly growing and this is an 'eventually' thing for me too.  I wonder though, what functionality does Lutris offer that this could benefit from? For example, since this would take much work why not build a nix-based client from scratch...
