### ISSUE TITLE
[MESS] Fullscreen & Keyboard

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#668]
Hi

Found this annoying behavior. 

When you start a game in MESS it'l work great but none of the ui keypresses work IE: 'TAB' to get to the menu or 'SCROLL LOCK' to get out of the full keyboard emulation. The only way to exit MESS seems to 'ALT-TAB' o and then kill MESS

Does not happen in MAME. Also happens if you use MAME as MESS, but not if you use MESS (from Lutris) alone without Lutris

**Comment by strycore** [comment]
The menu mode was hardcoded to right control, the default is now back to scroll lock and can be changed in the options
