### ISSUE TITLE
Games that are not installed do not display in lutris and unable to install games from lutris website using the install button.

### ISSUE THREAD

**Issue by SmashleyG** [lutris/lutris#675]
Hi, 

I am using fedora 26 and XFCE, I have installed lutris yet I have not been able to see any game that has not been installed. to make things worse, when I try to install a game through the lutris website and click install. I get the following error: Failed to open URI "lutris:mass-effect-steam". 

running the lutris -d command gives me: 

ERROR    2017-10-15 17:07:18,767 [steam]:Malformed config file: 030000004c050000c405000011810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,

ERROR    2017-10-15 17:07:18,767 [steam]:Malformed config file: 03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"

ERROR    2017-10-15 17:07:18,804 [steam]:Malformed config file: 030000004c050000c405000011810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,

ERROR    2017-10-15 17:07:18,804 [steam]:Malformed config file: 03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"

DEBUG    2017-10-15 17:07:20,359 [runtime]:Runtime lib64 is up to date
DEBUG    2017-10-15 17:07:20,359 [runtime]:Runtime steam is up to date
DEBUG    2017-10-15 17:07:20,360 [runtime]:Runtime lib32 is up to date
DEBUG    2017-10-15 17:07:20,360 [runtime]:Runtime p7zip is up to date
INFO     2017-10-15 17:07:20,361 [lutriswindow]:Connected to lutris.net as Smashley
DEBUG    2017-10-15 17:07:20,364 [api]:Fetching game library
ERROR    2017-10-15 17:07:20,365 [steam]:Malformed config file: 030000004c050000c405000011810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,

ERROR    2017-10-15 17:07:20,365 [steam]:Malformed config file: 03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,"

DEBUG    2017-10-15 17:07:20,414 [steam]:Watching Steam folder /home/ash/.local/share/Steam/steamapps

Please let me know if you need anymore information.

Regards, 

Ash

**Comment by strycore** [comment]
The command line output doesn't show any error, have you double checked you're using the correct account?

**Comment by SmashleyG** [comment]
I feel stupied.. I didn't realise I had two accounts. silly me.
