### ISSUE TITLE
Open manual/readme

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#681]
Some—especially older—games pretty much require you to read a manual to understand how to operate them. Even more so when they contain crude copy protection. As most digitally released games seem to at least be bundled with a PDF or readme.txt that detail this information, would it be possible to have a button
 somewhere—like in the right-click context menu—that opens up the manual/readme if its location is defined in the config?

**Comment by strycore** [comment]
Yes, that's a good idea. I would make this a bit more generic and add additional launch options for games that have, for example, a map editor or a separate config tool. These additional option would appear in the contextual menu and would be defined in install scripts under a special key for custom actions.
