### ISSUE TITLE
Allow linking Steam account from client

### ISSUE THREAD

**Issue by takkun324** [lutris/lutris#684]
I think "Synchronize Library" is in desperate need of a face-lift.

In Lutris (on Ubuntu 17.04):
1. I link my Steam Library on the website Lutris.com.
2. I open Lutris and click on the menu-item "Lutris"
2. Select "Synchronize Library" from the drop-down.
3. ...?  Nothing... What did I do? Did I miss something? Did it do anything? Was this even necessary?

There is no feedback at-all with this feature; period. I believe I've followed the (rather simplistic) directions correctly. While it doesn't seem that complicated I have no idea if it worked correctly.

**Comment by TingPing** [comment]
This is improved already in the next release (0.5).

**Comment by takkun324** [comment]
Oh? Sorry then. Thank you for the foresight.  ;)

**Comment by strycore** [comment]
yeah, I won't close this, I'll just expand the scope a bit :D
