### ISSUE TITLE
Extract password-protected archives

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#686]
I've just run into an archive which is password-protected, and as such extraction with the Lutris installation scripts does not work. Would it be possible to add a `password` field to the `extract` directive?

**Comment by strycore** [comment]
Which type of archive was it?

**Comment by FakeShemp** [comment]
I can't remember. If i had to guess I'd say RAR.

**Comment by FakeShemp** [comment]
I found the game. It was Oknytt and it came in a password-protected zip-file.
