### ISSUE TITLE
Dolphin games fail to launch

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#690]
The Dolphin runner doesn't launch any games and just spits out this error:

`/home/cxf/.local/share/lutris/runners/dolphin/dolphin-emu: error while loading shared libraries: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory`

- Ubuntu 17.10
- Lutris 0.4.14

**Comment by strycore** [comment]
Dolphin works fine with the Lutris runtime.

**Comment by AccountOneOff** [comment]
Sorry about that no idea why that was disabled but now I'm getting this:

    Gtk-Message: Failed to load module "gail"
    Gtk-Message: Failed to load module "atk-bridge"
    /usr/share/themes/Adapta-Eta/gtk-2.0/common-eta.rc:1363: error: unexpected identifier 'direction', expected character '}'
    /usr/share/themes/Adapta-Eta/gtk-2.0/3rd-party-eta.rc:533: error: invalid string constant "toolbar", expected valid string constant

    (dolphin-emu:14594): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

    (dolphin-emu:14594): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
    /home/cxf/.themes/Arc-Maia-Darker/gtk-2.0/main.rc:1090: error: unexpected identifier 'direction', expected character '}'
    /home/cxf/.themes/Arc-Maia-Darker/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
    Gtk-Message: Failed to load module "unity-gtk-module"

**Comment by strycore** [comment]
hmm, you can ignore the theme warnings but it seems you're missing some GTK stuff. Which DE are you using?

**Comment by AccountOneOff** [comment]
Ubuntu 17.10 - Gnome 3.26.1

**Comment by strycore** [comment]
Same here, I just played Super Mario Sunshine. Try deleting the Dolphin runner and re-download it, maybe it's not up to date?

**Comment by AccountOneOff** [comment]
Nope, deleted the Dolphin runner folder and still getting the same errors. I see it pop up for a split second then it closes. Could it be that I have another version of Dolphin installed outside of Lutris?

**Comment by strycore** [comment]
If you see the window pop up then it's not a runtime issue. What if you disable the process monitor?

**Comment by AccountOneOff** [comment]
That didn't work either. It doesn't quit when that is disabled and I can see dolphin-emu in system monitor but it doesn't show any signs of activity.

![screenshot from 2017-11-28 17-14-37](https://user-images.githubusercontent.com/15083452/33352865-d2837328-d45f-11e7-8c2c-baef15bc7715.png)

**Comment by AccountOneOff** [comment]
Seems to be working now. Played The Simpsons Hit & Run for a bit no problem.

**Comment by Zeioth** [comment]
I have the runtime disabled, and dolphin games are running just fine for me, once you tell lutris where dolphin.exe is (it doesn't find it automatically on /usr/games/dolphin-emu).

**THIS ISSUE CAN BE CLOSED.**

**Comment by duhow** [comment]
You can't run directly Dolphin. But if you really want to, do:

```bash
LUTRIS="$HOME/.local/share/lutris"

export LD_LIBRARY_PATH=$LUTRIS/runners/dolphin/lib:$LUTRIS/runtime/lib64
$LUTRIS/runners/dolphin/dolphin-emu
```

(just pointing this if someone has the same problem).

**Comment by F13** [comment]
I seem to get the same issue as originally reported here. I am running version 0.5.0 on Arch, and I can't launch any Dolphin games. I receive the same error regardless of if Lutris runtime is enabled or disabled.

```error while loading shared libraries: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory```

I can confirm this file exists at `~/.local/share/lutris/runners/dolphin/lib/libavcodec-ffmpeg.so.56`. It also exists on my system at `.local/share/lutris/runtime/lib32/` and `.local/share/lutris/runtime/lib64/`.

**Comment by strycore** [comment]
delete and redownload the dolphin runner, this is the one using the old runtime
