### ISSUE TITLE
Wine runner: wineexec with `blocking: True` executing in non-blocking mode

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#691]
My installer need to wait for installation to finish and write to some config files, but lutris executes setup file in thread and then not wait's for process to finish and writes to non existing files, which is wrong.
@strycore

**Comment by soredake** [comment]
Hmm, with installer from gog it wait's even without blocking, seems the problem in monitoring code.

**Comment by strycore** [comment]
Please provide a link to the specific installer.

**Comment by soredake** [comment]
It's local installer with game unavailable for purchase, sadly.

**Comment by strycore** [comment]
You can copy/paste the installer directly here then

**Comment by AaronOpfer** [comment]
Some installers unpack a bunch of files and a new setup executable, and "fork-and-die" to run the new executable. I wonder if this issue would be fixed by #1415 as a result.
