### ISSUE TITLE
Wine runner not sets wine runner options from installer

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#692]
I defined this options in installer:
```
wine:
  Desktop: true
  WineDesktop: 1024x768
```
After game installation Desktop is set to `false` and WineDesktop set to `800x600`.
@strycore

**Comment by strycore** [comment]
is this for a wine or winesteam installer?

**Comment by soredake** [comment]
Wine installer.

**Comment by soredake** [comment]
Found the problem, i used two spaces instead of needed four, now it setting options.
