### ISSUE TITLE
winesteam: Custom Steam Location fails when location is in home directory

### ISSUE THREAD

**Issue by chicken42** [lutris/lutris#698]
When the Custom Steam location is set to a directory inside the user's home directory, the saved location for the game is set using the ~/ prefix.  The `get_steam_path` method inside of `winesteam.py` does not correctly expand the user prefix, forcing a fallback to the default steam location (lutris directory).

This can easily be fixed by adding a `os.path.expanduser()` call somewhere in the check for custom_path.  This seems least likely to break anything that depends on the current behavior.

Something along the lines of:
```
        custom_path = self.runner_config.get('steam_path') or ''
        if custom_path:
            custom_path = os.path.expanduser(os.path.join(custom_path, 'Steam.exe'))
            if os.path.exists(custom_path):
                return custom_path
```

**Comment by strycore** [comment]
Thanks for the fix!
