### ISSUE TITLE
Allow passing result entries from `files:` as env variables to installer and game section

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#706]
e.g. export result of `- steam-data: $WINESTEAM:227300:/` as `$steam-data` variable available to other sections.
Sample installer that needs this https://lutris.net/games/install/6530/view and https://lutris.net/games/install/6274/view
@strycore

**Comment by strycore** [comment]
I wrote a fix for that but meanwhile, you can make those installers  work by removing the dash from steam-data (or replace with an underscore). See 1a750889a6aab7 for details

**Comment by strycore** [comment]
btw, I added a fix to the ETS installer by quoting the args value in the game config, otherwise it gets improperly parsed since the path has spaces.

**Comment by soredake** [comment]
@strycore seems lutris site don't like multiline scripts
After adding to installer this
```
- execute:
    command: '
listurl=https://update.ets2mp.com
dlurl=https://download.ets2mp.com/files
base= "$steam-data"
dldir="../truckersmp"

cd "$base"

mkdir -p "./$dldir"
wget "$listurl/files.json" -O "./files.json"

cat "./files.json" | awk 'BEGIN{i=0}/":"/{printf $0;i=1;next}{if (i) {printf "\n"; i=0}}' | awk -F '"' '{printf "%s ./truckersmp%s\n",$8,$4}' > "./.checksums"
files=(  $(cat "./.checksums" | md5sum -c --quiet - 2> /dev/null | awk -F ':' '{print $1}' | sed 's,\./'"$dldir"'/,,g') )

for f in $files; do
    echo "f = $f"
    mkdir -p "./$dldir/$(dirname $f)"
    wget $dlurl/$f -O "./$dldir/$f"
done

rm -f "./.checksums"'
```
Lutris returns this:
https://lutris.net/games/install/6530/view
```
Internal server error

Hu ho, something went wrong and it's totally our fault.
We've been notified of this issue and we will fix it ASAP. 
```

**Comment by soredake** [comment]
@strycore same with prey installer, adding with quotes (because path contains spaces)
```
- merge:
    src: "$steam-data"/base/*.pk4
    dst: $GAMEDIR/Game/base
```
leads to
```
Internal server error

Hu ho, something went wrong and it's totally our fault.
We've been notified of this issue and we will fix it ASAP. 
```
