### ISSUE TITLE
Think twice before giving feedback to the Godot repo!

### ISSUE THREAD

**Issue by ContinueToBuryHeadInSand** [lutris/lutris#708]
### JUST IN

![](https://i.imgur.com/dlWPgII.jpg)

---

(Since everyone keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.

He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable >_<

**Comment by ContinueToBuryHeadInSand** [comment]
![](https://media.giphy.com/media/14ceV8wMLIGO6Q/giphy.gif)

**Comment by strycore** [comment]
As far as I know, you didn't pay the Godot developers, nor did you contribute any actual fixes to the project. 
They don't owe you anything. And they know about issues, they don't need to be constantly reminded. Open source developers, who, for most of us, have a job as well try their best to improve their project with the little time they have. We have no use for little shitheads who can't grasp the basics of bug reporting.

**Comment by ContinueToBuryHeadInSand** [comment]
@strycore  I have a patreon account.

**Comment by strycore** [comment]
A Patreon pledge is for you to show your support of the existing project. In no way does it entitle you to get your bugs fixed before the rest. While it is a nice gesture to contribute to a project, it does not make you a special user, development-wise.
Want to make Godot better? Read a book and learn how to patch the issues. I'm sure the Godot team will be much more open to pull requests than random tantrums on social media.

**Comment by ContinueToBuryHeadInSand** [comment]
@strycore You obviously didn't read my post. Guy on reddit was giving honest feedback about the engine and got harassed by the lead developer.

The patreon is to support the developer, $3,000/m goes to Juan. It inherently implies partial entitlement when requesting for bug issues to be fixed. Continue burying your head in the sand though.

**Comment by ContinueToBuryHeadInSand** [comment]
@strycore Also, Juan said he has job offers from Unity and other game engines and he choose to stick with Godot instead. This means, if he doesn't get the funds from patreon he couldn't work on it full-time.
