### ISSUE TITLE
Multiple libraries preload support

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#714]
@strycore

**Comment by strycore** [comment]
Is that possible?

**Comment by strycore** [comment]
Ok, look like it's just a space separated list so supporting that should only require a very simple patch: https://stackoverflow.com/questions/8474363/specifying-multiple-files-with-ld-preload

**Comment by strycore** [comment]
Is there a way to test this? I think the current code already supports that.

**Comment by strycore** [comment]
I see, I need to make this a text field. Not sure about the "browse" button though. I know we have that in the installer window so it might find its way to the configuration dialogs.

**Comment by soredake** [comment]
I don't need this anymore.
