### ISSUE TITLE
Overwatch and Battle.net will not install

### ISSUE THREAD

**Issue by retiform** [lutris/lutris#719]
I am using Manjaro GNOME, and Lutris says that Battle.net.exe is not found.
I tried using a recusive find search in /Games to find Battle.net.exe, but alas, it does not exist.

Wine will install it on my system (but will not run it properly, probably because I botched something).

I am using the Lutris Client Overwatch installer, which failed so I tried the Battle.net lutris client installer, which failed with the same error.

**Comment by nenoro** [comment]
I have the same problem on Gentoo and i use i3 but i'm not sure it's a DE problem.
On Arch, the script will install.
