### ISSUE TITLE
[jzintv runner] add resolution support

### ISSUE THREAD

**Issue by maxlefou** [lutris/lutris#723]
When I use jzintv to play intellivision games, it always appears in native resolution, 320 x 200. Which is as big as the game's thumbnail, so, ridiculously small.

After reading some docs about jzintv, i've seen there's a way to change resolution using the command -z (like -f for fullscreen) but for some reason, it simply doesn't work by adding it in the command prefix box.

So I worked into making a patch that add a resolution parameter in the runner options. It uses the resolution presets natively present in jzintv. [The patch is here](https://github.com/maxlefou/lutris/blob/patch-1/lutris/runners/jzintv.py). I am not sure the patch works tho, because, for some reason, the patched lutris i built after couldn't recognize the bios roms. So if some python/lutris experts  (like djazz or strider) can get an eye on the patch...

This would be a really needed addition to lutris and the runner.

**Comment by maxlefou** [comment]
There. I finished making the patch and it works perfectly!
Dear developpers, feel free to [test it out](https://github.com/maxlefou/lutris/blob/master/lutris/runners/jzintv.py) and include it in a future update. ;)

![deepin capture-ecran_20171227224608](https://user-images.githubusercontent.com/6705075/34394418-411bb114-eb59-11e7-937e-dde58c130880.png)

To resume it, the update adds a dropdown menu that lets the user choose a resolution (among several presets builtin jzintv) and the game launches using the choosen resolution.

I only have one issue, so far. An esthetical issue: The dropdown menu is blank by default. I haven't found the way to make the menu choose the default resolution. But maybe the developers can fix it? :p This problem is only esthetical anyway. :p

**Comment by strycore** [comment]
can you create a pull request so I can review and merge the changes?

**Comment by maxlefou** [comment]
just did. [it's here](https://github.com/lutris/lutris/pull/726)
Tho it has a red X saying the "Travis CI build" failed... Not sure of what it means...

**Comment by strycore** [comment]
Yeah, you can ignore the Traviswarning for now, thanks for the PR!
