### ISSUE TITLE
"write_file" task glitching

### ISSUE THREAD

**Issue by maxlefou** [lutris/lutris#724]
### Steps to reproduce the glitch
* Create an installer and add a `write_file` task in it. For instance, i'll take the example of the doc:
```
- write_file:
    file: $GAMEDIR/myfile.txt
    content: 'This is the contents of the file.'
```
* Test the installer.

### What actually happens
The file `myfile.txt` is created at the right place. But the file contains `$GAMEDIR/myfile.txt` instead of `This is the contents of the file.`

### What is expected
The file `myfile.txt` should contain the `content`'s string (`This is the contents of the file.`) and not the `file`'s string (`$GAMEDIR/myfile.txt`)

### Other suggestions
* Find a way for the script editor on the website to not erase the `'` or `"` in the `content`'s string after saving draft/submitting.
* Some specific configuration files (mostly for old DOS games) needs text files using multiple lines and gets the game crashing if those parameters are all in a single line. It would be good if there was a way to indicate the script editor to "hit Return" at the right places (such as using `\n` or similar stuff)
* Add something like `append_file` that makes the script adding content to an existing file without erasing its content. (This might be a workaround for the previous suggestion)

**Comment by AccountOneOff** [comment]
3c8b372945be34aee34a0adc181f5e649e6440a7 should have fixed that. @daniel-j

**Comment by maxlefou** [comment]
Since i'm on Arch I installed lutris using the AUR "lutris" package. (version 0.4.14-1) I guess it will be corrected if i install the "lutris-git" package. Anyway, either the correction isn't in a stable build of lutris, or the AUR package maintainer has their thing outdated... -_-

Anyway, please don't forget to consider my other suggestions ;p

**Comment by strycore** [comment]
Added notes in the documentation about YAML formatting. 
It's also now possible to substitute variables in text files.
