### ISSUE TITLE
Add possibility to create desktop shortcuts for standalone runners

### ISSUE THREAD

**Issue by Sebastian1978** [lutris/lutris#727]
Lutris doesn't create Winesteam desktop shortcut after runner installation. Shortcut will be useful for direct launch of Winesteam.

Also Winesteam doesn't exist in games database. It is confusing because if you want to install Winesteam you will search in base and find nothing.

**Comment by Sethox** [comment]
You can actually right-click the runner (in this case Winesteam) and run it like that. I noticed that by accident though.
