### ISSUE TITLE
Library does not synch...

### ISSUE THREAD

**Issue by Jaeliem** [lutris/lutris#732]
I have just installed World of warcraft. The game seems to be able to run but... I dont see it in my lutris launcher. Ive registered on lutris. Ive added the game to my library. Ive tried to synch the lutris launcher with my Library but it just dont work. I dont see my WOW or Battlenet Laucher. If I quit the game, I cant relaunch it. What should I do?

**Comment by strycore** [comment]
Maybe ask this in the forums or on Discord if you still have this issue, that's where most people will be able to help you.
