### ISSUE TITLE
libretro missing dependencies

### ISSUE THREAD

**Issue by charlydelta** [lutris/lutris#734]
Debian 9.3 with most recent Lutris (from the official repositories), tested on two devices with the same result:

When I try to launch a N64 game with `libretro`, the games fail to launch with the error message:

```
/home/u/.local/share/lutris/runners/retroarch/retroarch:
/home/u/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjpeg.so.62:
version `LIBJPEGTURBO_6.2' not found
(required by /usr/lib/x86_64-linux-gnu/libv4lconvert.so.0)
```

It seems that the installed version is more recent than the one expected by retroarch. But shouldn't these dependencies be bundled anyway?

**Comment by strycore** [comment]
I've added libv4lconvert.so.0 to the lutris runtime, this should solve the issue.
