### ISSUE TITLE
Not detecting hybrid graphics Intel+AMD

### ISSUE THREAD

**Issue by myin142** [lutris/lutris#735]
I have Intel + AMD hybrid graphics on my computer but in System Options I cannot select "Use PRIME(hybrid graphics on laptops)". It is greyed out. Hybrid Graphics is working on my computer and I have the correct drivers.

I also tried to put "DRI_PRIME=1" to the Command prefix, but this gives me the error: "Error launching the game: no such file or directory 'DRI_PRIME=1'". When starting the game manually with wine command and prefix DRI_PRIME it works. Why is it not possible to just put a text in front of the start command?

**Comment by soredake** [comment]
use `env DRI_PRIME=1`

**Comment by myin142** [comment]
After reinstalling Arch Linux, it is now detecting it normally. Do not know what the problem was, but I will be closing this issue for now.
