### ISSUE TITLE
[Interesting behavior] 64-bit Lutris games (Winesteam)

### ISSUE THREAD

**Issue by Sethox** [lutris/lutris#737]
I was looking around on the issues and I found out that 64-bit winesteam exists by installing a game that demands 64-bit (in this case a script with the arch 64-bit only). This forces the wine on winesteam to be a prefix on 64-bit, but if you install it manually (just the runner itself with Lutris) it actually becomes a 32-bit prefix wine on winesteam. I should be able to install a 64-bit winesteam without doing this (emphasis on should).

So this is a mixure of HowTo and suggestion to not run it like that for 64-bit winesteam games.

**Just run a 64-bit install script for the runner winesteam.**
This of course means you have to NOT have the runner installed before doing this.

**Comment by Trollwut** [comment]
Could you give examples?

I need a 64 bit winesteam installation, but can't get it to run. I removed the 32 bit runner folders and it was removed for Lutris.

Now when creating a 64 bit wine arch in `.../runners/winesteam/prefix"`, it creates it, but then on installing Steam (via Lutris) will stop at Validating Steam Installation.

Are there Steamgames or install scripts you can recommend, where a 64 bit winesteam is necessary?

**Comment by SenileAnimal** [comment]
Thank you for sharing this. I was frustrated by this, and your solution is easy and works well. 

I don't want games installed with 32bit Winesteam (unless a certain game requires it). I 32bit Steam thinks the OS is 32bit, and I 'd imagine every game will then get installed in a 32bit Wineprefix. The downside that comes to mind is your games (potentially) can't access as much memory. From what I've read, "When you enable the Large Address Aware flag for an executable file, you increase the maximum amount of memory available to a 32-bit application from 2 GB of memory to 3 GB of memory on 32-bit Windows, and up to 4 GB of memory on 64-bit Windows." I'm not sure as to the accuracy of that in wine on Linux, but 1 GB can make an enormous difference.

**Comment by aladar42** [comment]
> Are there Steamgames or install scripts you can recommend, where a 64 bit winesteam is necessary?

I came here to look for a solution/open a ticket for this, but the game Community Inc (http://store.steampowered.com/app/631540/Community_Inc/) won't start with the winesteam versions Lutris is installing automatically. It just throws an "This game requires 64-bit system to run" error message and quits. Installing Wine from a repo and installing Windows version of Steam from their web page works without a problem.

**Comment by strycore** [comment]
The default architecture for winesteam is now 64bit, this should solve many issues.
