### ISSUE TITLE
Wine 3.0

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#739]
https://www.winehq.org/announce/3.0

**Comment by strycore** [comment]
https://lutris.net/files/runners/wine-3.0-i686.tar.gz

**Comment by RobLoach** [comment]
![](http://1.bp.blogspot.com/-0KhRbSdEkuE/TymtgxJtcRI/AAAAAAAAArY/zGVzZt5dQ1w/s379/so-much-win-starcraft-reaction.gif)

**Comment by strycore** [comment]
Still have to build the 64bit build. (Release 3.0 staging already!)
