### ISSUE TITLE
Wine Steam games are not being synchronized

### ISSUE THREAD

**Issue by Witiko** [lutris/lutris#743]
Lutris fails to sync new games from the library of my wine Steam that I installed via lutris:

![screenshot_20180125_235429](https://user-images.githubusercontent.com/603082/35416883-36b3b8d2-022b-11e8-95d3-4ce960eb3c07.png)

When playing around with the `lutris.runners.winesteam.winesteam` class, a `KeyError` is raised at the following line:

https://github.com/lutris/lutris/blob/b913f556ad362084c491740ea195c40dc8980725/lutris/runners/winesteam.py#L313

Apparently, my `~/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/config/config.vdf` file, which is loaded by the `lutris.util.steam.read_config` function, does not contain the `InstallConfigStore/Software/Valve/Steam/Apps` section with application ids. Instead, this information is contained in the file `~/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/userdata/69050449/config/localconfig.vdf`:

```
…
        "Software"
        {
                "Valve"
                {
                        "Steam"
                        {
                                "Apps"
                                {
                                        "20900"
                                        {
                                                "LastPlayed"            "1505605477"
                                        }
                                        "35110"
                                        {
                                                "LastPlayed"            "1282546800"
                                        }
                                        "35140"
                                        {
                                                "LastPlayed"            "1385289915"
…
```

**Comment by Witiko** [comment]
I did some further digging and it seems my initial analysis was off the mark. The actual culprit is the following line:

https://github.com/lutris/lutris/blob/b913f556ad362084c491740ea195c40dc8980725/lutris/services/steam.py#L242

which suppresses the synchronization of wine Steam games. What is the rationale for this? I removed the ` and platform == 'linux'` part of the condition on line 240 in my copy of the code and since then, my wine Steam games have been kept synchronized.

**Comment by strycore** [comment]
I went on and made the change because it won't cause any problems for the majority of steam games but we need a way to mark these imported games as not fully configured so we can later on complete the lutris installer. We can also run a process in the background that checks installers for those games and marks them as complete if the installer is just a Steam appid.
