### ISSUE TITLE
Add option to use dumbxinputemu with dllredirects

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#745]
Some games, like GTA IV, don't seem to work with Lutris' built-in option but do with some dllredirects. Basically you copy the dlls (32bit and/or 64bit builds) to system32 and/or syswow64, depending on the prefix's architecture, then use a simple .reg file to redirect to the dumbxinput dlls. I've made a .reg file for quick and easy setup and renamed the dlls to xinput1_3_fake and xinput9_1_0_fake respectively. 

Reg file: https://github.com/AccountOneOff/lutris_files/blob/master/xinput.reg

Video example: https://www.youtube.com/watch?v=xMojWPtlkKc

**Comment by strycore** [comment]
Is this still worth the effort of implementing with controllers working out of the box with pretty much everything now?

**Comment by AccountOneOff** [comment]
Probably not but I still use this method over the default. That's just me though.
