### ISSUE TITLE
Battle.net service

### ISSUE THREAD

**Issue by Xenega** [lutris/lutris#748]
Every battle.net game reinstall battle.net. We should add battle.net as independent runner, the same way steam has a winesteam runner. We should call it winebattlenet, in case of, one day, Blizzard publish its platform on linux.

**Comment by strycore** [comment]
Ok. The requirements are: 
- an example of a CLI command used to install a battle.net game
- an example of a CLI command used to launch a battle.net game
- an example of a CLI command used to uninstall a battle.net game

Once I have those, a runner can easily be created. If Battle.net doesn't allow those action from the command line, then a runner is simply impossible to create.

**Comment by Xenega** [comment]
Battle.net use a uri (battlenet://game) with his launcher (Battle.net Launcher.exe) to install and/or launch a game. 

CLI Install and launch : 
Battle.net Launcher.exe battlenet://game

**Comment by perkinslr** [comment]
I believe the full string would be `wine "Battle.net Launcher.exe" battlenet://game`.  The quotes are needed, since the launcher has a space in it, and `wine` is needed, since `exe`s aren't a recognized `binfmt` on most systems.

**Comment by AccountOneOff** [comment]
>    an example of a CLI command used to install a battle.net game
>    an example of a CLI command used to launch a battle.net game
>    an example of a CLI command used to uninstall a battle.net game

To install through cmd:

    cd C:\Program Files (x86)\Battle.net\

    Battle.net.exe --game=hs_beta --install
To Launch:

    Battle.net.exe battlenet://WTCG
I haven't found a way to uninstall though. Blizzard don't exactly provide a comprehensive list of commands the bastards.

**Comment by daniel-j** [comment]
To uninstall:
```
wine drive_c/ProgramData/Battle.net/Agent/Blizzard\ Uninstaller.exe --uid=prometheus --displayname=Overwatch
```
This is what is used when you try to uninstall the game from `wine uninstaller`. `displayname` can be anything.

**Comment by IngeniousDox** [comment]
Just make sure "Add another Version" still works if you make this. I'm using 6 wineprefixes for different settings for wine (for playing / testing purposes).

And another issue with this is: not all blizzard games can be used with the same Wine version atm. I'm using 2.18 for Overwatch, 2.21/2.0 for WoW, 2.15 for HotS, etc.

**Comment by strycore** [comment]
Looks like we're getting a Battle.net runner!

**Comment by daniel-j** [comment]
> Looks like we're getting a Battle.net runner!
I have started working on one! Fixing other Lutris bugs along the way...

**Comment by Xenega** [comment]
@daniel-j 
I wanted to do it, but I've now a big problem with battle.net. ^_^

**Comment by RobLoach** [comment]
https://github.com/lutris/lutris/wiki/Game:-Blizzard-App

**Comment by sparr** [comment]
@daniel-j did your efforts ever bear fruit?

**Comment by strycore** [comment]
@sparr stop asking random questions on github, you're not helping at all.

**Comment by benjamimgois** [comment]
Any chance we get this ready this year ? Now with Amazon prime giving lots of Origin games and steam deck on it's way, it might be a good time to revisit this issue.

**Comment by hartmark** [comment]
Is there any code done for this effort and what is left to do?

**Comment by strycore** [comment]
Blizzard has no API for the user library so the integration lists all games from Battle.net. 
Not sure about the command line args, they don't seem to work.
