### ISSUE TITLE
Most Popular Games

### ISSUE THREAD

**Issue by happyconcepts** [lutris/lutris#749]
Where would be a good place to put a list of the top games? Could be just the top 20 as measured by # of library installs, for example.

**Comment by strycore** [comment]
It's now implemented as an option on the website's search engine!
Example: https://lutris.net/games/?q=&all-open-source=on&fully-libre-filter=on&open-engine-filter=on&sort-by-popularity=on

**Comment by happyconcepts** [comment]
That's great, thanks. I saw fez are #1 right now :)

**Comment by strycore** [comment]
Yeah, I'll have to fix that. I'm not sure we should categorize Fez as having an Open Source engine just because it's using FNA. Games we classify as such should at least be buildable from the game engine's source + the game assets, which is not the case for Fez.
