### ISSUE TITLE
Qt front-end

### ISSUE THREAD

**Issue by m4sk1n** [lutris/lutris#753]
It would be nice to have Qt-based front-end for Lutris as something more native for users of Qt-based desktop environments.

**Comment by strycore** [comment]
if you want to it, sure!

**Comment by Bumbadawg** [comment]
In KDE Neon you can set GTK2/3 to use Breeze-dark and it looks almost native.

**Comment by strycore** [comment]
No one is going to implement it so fuck Qt

**Comment by Sunderland93** [comment]
> No one is going to implement it so fuck Qt

Sounds like a reason for create fork.....:)

**Comment by strycore** [comment]
Yeah, go for it, you don't have what it take to maintain it anyway, it will fail miserably.

**Comment by Sunderland93** [comment]
Time will tell...

**Comment by strycore** [comment]
It will for sure!!

**Comment by strycore** [comment]
I mean… time has told a whole lot afaik…

**Comment by strycore** [comment]
it's been 10 years

**Comment by Medath** [comment]
Didn't @AlexanderRavenheart want to implement a qt frontend one day?

**Comment by AlexanderRavenheart** [comment]
If it will happen, it won't happen anytime soon. Too busy doing research and trying out different things at the moment for the GTK+ version. Also busy at the moment with some other things at work and preparing for some exams so didn't have much time to work on Lutris recently.

**Comment by Sunderland93** [comment]
@strycore it's great app anyway!

**Comment by gleyconJ** [comment]
Please QT users deserve this fantastic job too.

**Comment by strycore** [comment]
> Please QT users deserve this fantastic job too.

Just install a Gtk program once in your lifetime. You don't need all your software to be Qt.

**Comment by gleyconJ** [comment]
You're absolutely right. But for aesthetic reasons, that would be interesting. I know that no one is obliged to make an effort to please anyone. But this program specifically, there is no alternative. I'm just an enthusiastic computer user and I'm completely illiterate in programming language. The beauty of Linux is that we have many flavors of Operating Systems. Deeping, KDE, Gnome, XFCE, Cinammon, etc... each one fills someone's eyes while being in terrible taste to others. But with apps these flavors aren't as diverse as the distributions. But this has been changing in recent years, at a snail's pace. Having a fully integrated Operating System (aesthetically) is the epitome of computing.

**Comment by Goddard** [comment]
Plasma user here and installing lutris takes 2 gigs of space...about.  Pretty big determinant to just use Steam to install and launch my Windows apps.

**Comment by strycore** [comment]
> Plasma user here and installing lutris takes 2 gigs of space...about. Pretty big determinant to just use Steam to install and launch my Windows apps.

Why would you use Lutris to launch Steam games, just use Steam.

**Comment by Goddard** [comment]
> > Plasma user here and installing lutris takes 2 gigs of space...about. Pretty big determinant to just use Steam to install and launch my Windows apps.
> 
> Why would you use Lutris to launch Steam games, just use Steam.

Never said I was doing that.

You can use Proton in Steam to install non-steam games and apps.  Lutris is basically doing the same thing, but it has a few extra features to also work with other stores like GOG.  

I can save myself around 2 gigs of space by just using Steam which is already installed simply because I don't need to install the entire gnome stack just to run Lutris.  Just speaking practically.  I know some people don't care about this, but to me its not worth it.

I haven't looked at how this was built, but if it could be de-coupled to allow different front ends, it does have other benefits.  Could say for instance have a web interface even to allow remotely managing your games.  If you had a gaming server for your house for example.  Probably more fringe maybe compared to just people that don't use Gnome, but hey... maybe other people have ideas?

**Comment by strycore** [comment]
Ok.

**Comment by Goddard** [comment]
Are you open to pull-requests for this?  How feasible do you think it is?

**Comment by strycore** [comment]
yes, but the Qt code would also need to be maintained as long as the project is alive and it must keep feature parity with its Gtk counterpart.

**Comment by Goddard** [comment]
> yes, but the Qt code would also need to be maintained as long as the project is alive and it must keep feature parity with its Gtk counterpart.

Fair enough.  Thanks.

**Comment by danieljohnson2** [comment]
Hmm. I suppose the extra 1.5 GB is GTK itself.

I think I have the solution: switch to Fedora and get rid of all that Qt stuff! :stuck_out_tongue_winking_eye:

**Comment by strycore** [comment]
The solution is to have an OS drive that is big enough to have both Qt and Gtk libraries. I think I solved that problem for myself in 1997.

**Comment by Goddard** [comment]
It is nice that Plasma actually themes GTK apps to make it not a huge deal, but for some reason Gnome Shell doesn't?  It isn't a huge deal to be clear, but it is nice.
