### ISSUE TITLE
Import From PlayOnLinux

### ISSUE THREAD

**Issue by Saroufim** [lutris/lutris#755]
It would be great if it would be possible to import prefixes and programs such as Steam from PlayOnLinux to Lutris. It can be done manually by having the same configs and simply copy/pasting the files or changing the directories but having a wizard to do it would be much nicer.

**Comment by telanus** [comment]
Hopefully one day this will be possible

**Comment by strycore** [comment]
Will be implemented when we have some kind of wine prefix manager.

**Comment by strycore** [comment]
@RobLoach it's already possible to migrate a game from playonlinux to lutris but it's not clear how it's done for most users. At some point we'll have an utility to list wine prefixes, I can see that having an import feature implemented quite easily.
