### ISSUE TITLE
Managing multiple accounts (Lutris and/or Steam)

### ISSUE THREAD

**Issue by rainecheck** [lutris/lutris#757]
Phrasing this as a problem statement as there are multiple ways to tackle this.
I'm trying to set up in-home streaming. Some of the games are on one person's Steam account, some are on another. It would be nice if Lutris would either be able to have: (or some variant of)
A) Knowledge of multiple Steam accounts, so that it could intelligently log into one account or the other during setup or play
B) Knowledge of multiple Lutris accounts, each associated with a different Steam account...for the same purposes as above.

Bonus points if there could just be one magical package that Lutris could be set up as an in-home streaming box, set to headless mode. But I understand that's probably much bigger than this request, and likely covered by #162 (which I'll be adding some comments to).

**Comment by kaktux** [comment]
+ 1
i also like to separate. I have the games i bought in one steam account - and also use another for some free to play.

**Comment by raneon** [comment]
I use multiple Steam accounts as well. So this feature would be great!

**Comment by luni3359** [comment]
Was this feature implemented?

**Comment by Rafgass** [comment]
This also interests me, was it implemented?

**Comment by CuriousApe2020** [comment]
Was this ever implemented?

**Comment by Lalarian** [comment]
Sadly, not yet.
I urgently need support for multiple separated Steam accounts, too!
