### ISSUE TITLE
Lutris should recommend installing Wine Staging before installing Lutris.

### ISSUE THREAD

**Issue by IngeniousDox** [lutris/lutris#761]
Wine dependencies aren't installed. And every time people come to ask for help, and the solution is simple: Install Wine Staging.

So we don't need to talk to them for 15 minute on discord to figure out we need to point them to:

https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/

Depending on normal Wine (something that is in repo's) might be a 2nd best solution to this, since it will pull in needed depenencies aswell, but I'm not sure if this covers everything we need.

**Comment by Xenega** [comment]
Duplicate #672

**Comment by strycore** [comment]
@Xenega Nope, that's a whole different issue

**Comment by IngeniousDox** [comment]
This is about the dependencies that usually get installed when someone installs Wine (Staging). Not about having just a newer version of Wine.

**Comment by Xenega** [comment]
People should be able to use Lutris without wine. So, we cannot set wine staging as dependencies of Lutris. IMHO, we can have a lutris-wine package with all dependencies that we check before let user use wine.

**Comment by IngeniousDox** [comment]
Well, that is what you have the runtime for. For me, I have to disable the runtime to make my programs work better. I get that this is not what you want. I also need to install Wine for dependencies. This has been the case from the moment I started using Lutris.

Djazz is updating the Lutris Runtime. Perhaps with a more updated runtime stuff will work better.

**Comment by strycore** [comment]
I have added wine as an optional dependency in the AUR, this should solve most problems.

**Comment by thiras** [comment]
Ubuntu instructions are defiantly not clear about it. Forced dependency is the best options for debian/ubuntu. Nobody pay attention to recommended packages. (and devs shouldn't insist to change this behavior)

**Comment by duhow** [comment]
`fonts-wine` and/or `ttf-mscorefonts-installer` should be required for viewing Steam.
Otherwise, some parts break.

![image](https://user-images.githubusercontent.com/1145001/43676795-23a3fd52-97f8-11e8-8d57-e5170391aed2.png)

**Comment by strycore** [comment]
Now implemented in master
