### ISSUE TITLE
steam dialog for wine steam games not usable

### ISSUE THREAD

**Issue by rynnon** [lutris/lutris#770]
I cannot install winesteam games, because the steam dialog that pops open does not have labels, and for the "enter code" dialog, the input area is not visible at all.

![image](https://user-images.githubusercontent.com/17681000/36350596-54a89128-149b-11e8-97b2-65954403718a.png)

OS: Linux Mint 18
CPU: i5 6500
GPU: Nvidia GTX 970 (proprietary driver)
Lutris version: 0.4.14

**Comment by AccountOneOff** [comment]
Install Wine dependencies: https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/
