### ISSUE TITLE
Backup game saves for Linux Steam games

### ISSUE THREAD

**Issue by supremesonicbrazil** [lutris/lutris#772]
Hi there, I heard you guys plan on implementing support for save backups on Lutris. Although your scope is much bigger than mine, covering beyond Steam games, I just wanted to let you know I've been working on my free time on a little backup program called [SLSK](https://github.com/supremesonicbrazil/SLSK) for the last few months, and there's a database there if you guys need paths to implement this for the Linux Steam part of Lutris at the very least.

Right now it covers 45% of the Steam catalog so far, including the entries with missing information which take up pretty much half of this percentage. I'm not sure if it will be of any help for you in the state it is, but still, feel free to use the database or whatever you want from my project, it's GPL-3.0 too so I believe there won't be too much of a hassle :)

**Comment by RobLoach** [comment]
Steam Linux Swiss Knife looks pretty neat!

**Comment by Sethox** [comment]
Holycrap that looks neat. All I can say is.. keep in close contact with the Lutris guys @supremesonicbrazil.

**Comment by supremesonicbrazil** [comment]
I'll be happy to help in any way I can :)

**Comment by supremesonicbrazil** [comment]
@ryliejamesthomas Yes, I've been considering that for a while, I didn't knew at the time Soulseek was a thing and when I found out I was like "oh dear, this ain't gonna end well eheheheh :sweat_smile: "

Definitely gonna change the name though, thought of a couple ones but I'm open for suggestions :)

**Comment by ryliejamesthomas** [comment]
@supremesonicbrazil If I think of any good ones I'll post them over on the SLSK Github :)

**Comment by Medath** [comment]
In case this is still of interest: The project moved to https://gitlab.com/supremesonicbrazil/GBML

**Comment by RobLoach** [comment]
Saw Ludusavi pop up https://github.com/mtkennerly/ludusavi
