### ISSUE TITLE
Task Manager

### ISSUE THREAD

**Issue by Xenega** [lutris/lutris#779]
## Rationale
Installation cannot be stopped and resumed. You cannot install game in background. You cannot resume download of installation file. Since installation can take a lot of time, all these features would be very welcome.

## Proposal
Every installation would be associated with a Task model to control it. The task would be persisted in database. Task model should be independent of dialog. A manager view would display every Task. By clicking, you could open, hide the install dialog.

**Installer**
Installer must be saved to restart with exactly the same installer (re-download cause bug if the installer change). The installer can be saved as file or as model in the database.

**Step**
Each task would be divided into multiple step for each installer action.
Step can : be canceled, have progress, be paused

**View**
Game name
Installer name
Task Progess (% of step)
Step Progress 
Step status
Date starting
Date next step (when possible)

**Model**
TODO

**Comment by strycore** [comment]
At some point we have to move to something like that. I don't know if we can get this in the same issue or not but I'd like to also have a process manager for running games.
