### ISSUE TITLE
Feature request: Standard location for shadercaches

### ISSUE THREAD

**Issue by IngeniousDox** [lutris/lutris#787]
For NVidia wine games, it should be in the Wine Prefix. It can contain max 256mb, and sharing it with multiple games is terrible. I'm setting it in the Blizzard installers, but it should be a standard feature.

For AMD / Intel I don't know how the shader cache works. Someone else will have to fill in the details here.

**Comment by Sethox** [comment]
You can actually suggest a script to add that.. so their standard adds a "for Nvidia users". Of course it should be tested and ready.

Fortunately it's not that hard to understand their runner/script language.

**Comment by strycore** [comment]
We're talking about those 2 options, right? 
https://www.phoronix.com/scan.php?page=news_item&px=MTAwNDk

**Comment by IngeniousDox** [comment]
Yes.

They are going to increase the cache and/or add another var in the future: https://devtalk.nvidia.com/default/topic/1032059/linux/opengl-shader-disk-cache-max-size-garbage-collection-/

But that might be a while.

**Comment by Zeioth** [comment]
We kinda have a convention in the installer where we always set the shader cache to $GAMEDIR, but I agree, it would be a good idea to make it default.
