### ISSUE TITLE
innoextract fails in installer

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#788]
This https://lutris.net/games/install/7491/view installer fails with `ValueError('too many values to unpack (expected 2)',)`
When i run `innoextract --gog setup_the_walking_dead_-_a_new_frontier_episode_5_\(12348\).exe` not in lutris it unpacks fine.

@strycore

**Comment by strycore** [comment]
You are most likely missing innoextract, you can add it to your script with our build: https://lutris.net/files/tools/innoextract-1.7-pre-x86_64.tar.gz
