### ISSUE TITLE
Please, use more recent version of dumbxinputemu

### ISSUE THREAD

**Issue by kozec** [lutris/lutris#790]
Hello,

I've noticed that Lutris installs v0.3.1 of dumbxinputemu, which works only up to latest 2.xx version of Wine. With Wine 3.0 and above, dumbxinputemu v0.3.1 will cause deadlock when loaded. (https://github.com/kozec/dumbxinputemu/issues/13)

Next version as well as latest one doesn't have this problem.

**Comment by strycore** [comment]
Updated to 0.3.3, although the current versions of wine have showed good support for controllers out of the box.
