### ISSUE TITLE
Lutris runtime interferes with Shovel Knight: Specter of Torment

### ISSUE THREAD

**Issue by plafue** [lutris/lutris#793]
Hi,

i wrote an install script for "Shovel Knight: Specter of Torment" and sent it for moderator approval.

I mentioned in freenode that the lutris runtime adds paths in `LD_LIBRARY_PATH` that conflict with the game's libraries, ultimatively making the game unplayable (a black screen is presented to the user). Therefore i activated the `disable_runtime` option in the `system` section of the script. I was encouraged to open a bug report here as this shouldn't be the case.

I'm willing to help debugging the route cause of this.

Cheers

**Comment by strycore** [comment]
If the game provides its own libs and sets its own LD_LIBRARY_PATH then it's the runtime can safely be disabled.
