### ISSUE TITLE
lutris can't run game and terminal if 'Run in terminal' is enabled

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#796]
Terminal isn't opening, wine window shows for a second than quits, manually running `kitty ~/.cache/lutris/run_in_term.sh`

**Comment by AccountOneOff** [comment]
What terminal are you using? Xterm and Gnome Terminal both work for me but Tilix just refuses to open and run the game.

    object.Exception@generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdk-3.so.0): /usr/lib/x86_64-linux-gnu/libXrandr.so.2: undefined symbol: _XEatDataWord

**Comment by soredake** [comment]
I use kitty.

**Comment by natis1** [comment]
This happens in konsole and xfce4-terminal in my experience. xterm and qterminal do work though.

**Comment by strycore** [comment]
> object.Exception@generated/gtkd/gtkd/Loader.d(125): Library load failed (libgdk-3.so.0): /usr/lib/x86_64-linux-gnu/libXrandr.so.2: undefined symbol: _XEatDataWord

Not suprising, most terminals will use Gtk stuff and that is likely to cause some issue with the Lutris runtime (although, this specific one looks like we should be easy to solve pretty easily, classic Gtk/Xorg issue)

**Comment by soredake** [comment]
@strycore lutris still can't run game if 'Run in terminal' is enabled

**Comment by strycore** [comment]
Have you updated to the latest master branch? The new code won't use the runtime to launch the terminal itself, it should run now.

**Comment by soredake** [comment]
@strycore yes, i'm always on master

**Comment by strycore** [comment]
Can you confirm that other terminals such as xterm do run properly?
