### ISSUE TITLE
Wine Steam Installer creates prefix in home directory titled "None" instead of $GAMEDIR

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#805]
Instead of creating a prefix inside $GAMEDIR like it normally does it instead makes an invalid one inside my home directory. This causes the merge command to fail and breaks the install process.

Logs:

    [INFO:2018-03-21 22:46:18,463:lutriswindow]: Installing the-witcher-3-wild-hunt (9143)
    [INFO:2018-03-21 22:46:21,382:interpreter]: Downloading file 1 of 5
    [INFO:2018-03-21 22:46:23,902:interpreter]: Downloading file 2 of 5
    [INFO:2018-03-21 22:46:26,117:interpreter]: Downloading file 3 of 5
    [INFO:2018-03-21 22:46:26,220:interpreter]: Downloading file 4 of 5
    [INFO:2018-03-21 22:46:26,322:interpreter]: Downloading file 5 of 5
    [WARNING:2018-03-21 22:47:18,986:winesteam]: Data path for SteamApp 292030 not found.
    [WARNING:2018-03-22 00:13:03,380:winesteam]: Data path for SteamApp 292030 not found.
    [WARNING:2018-03-22 00:13:03,658:wine]: No wine version staging-2.8-x86_64 found, falling back to system
    [ERROR:2018-03-22 00:13:08,964:wine]: No user.reg found after prefix creation. Prefix might not be valid
    [ERROR:2018-03-22 00:13:09,077:jobs]: Error while completing task <bound method CommandsMixin.move of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f8dff016f28>>: [Errno 2] No such file or directory: 'None/bin/x64'

My installer:

    files:
    - d3d11: https://haagch.frickel.club/files/dxvk/latest/64/bin/d3d11.dll
    - dxgi: https://haagch.frickel.club/files/dxvk/latest/64/bin/dxgi.dll
    - vulkanjson: https://raw.githubusercontent.com/GloriousEggroll/dxvk-tools/master/winevulkan.json
    - vulkanreg: https://raw.githubusercontent.com/AccountOneOff/lutris_files/master/vulkan.reg
    - vulkansdk:
        filename: VulkanSDK-1.0.51.0-Installer.exe
        url: https://sdk.lunarg.com/sdk/download/1.0.51.0/windows/VulkanSDK-1.0.51.0-Installer.exe?Human=true
    game:
      appid: 292030
      arch: win64
      prefix: $GAMEDIR/prefix
    installer:
    - task:
        arch: win64
        name: create_prefix
        prefix: $GAMEDIR/prefix
    - merge:
        dst: $GAMEDIR/bin/x64
        src: $d3d11
    - merge:
        dst: $GAMEDIR/bin/x64
        src: $dxgi
    - task:
        arch: win64
        args: /S
        description: Installing Vulkan SDK...
        executable: vulkansdk
        name: wineexec
        prefix: $GAMEDIR/prefix
    - move:
        dst: $GAMEDIR/prefix/drive_c/windows
        src: $vulkanjson
    - task:
        app: win7
        arch: win64
        name: winetricks
        prefix: $GAMEDIR/prefix
    - execute:
        command: WINEARCH=win64 WINEPREFIX=$GAMEDIR/prefix wine64 regedit /S $CACHE/vulkan.reg
    system:
      disable_runtime: true
      env:
        DXVK_HUD: '1'
        DXVK_LOG_LEVEL: none
      pulse_latency: true
    winesteam:
      Desktop: true
      overrides:
        d3d11: native
        dxgi: native
      version: staging-3.4-x86_64

**Comment by soredake** [comment]
https://github.com/lutris/lutris/issues/680

**Comment by AccountOneOff** [comment]
Guess I'll close this then.
