### ISSUE TITLE
[Patreon Goal] Origin runner

### ISSUE THREAD

**Issue by Maxattax97** [lutris/lutris#808]
There are a handful of games like Mass Effect 3 or the Sims 4 that I'd like to use inside Lutris that are available on Origin. Is work in progress on an Origin runner? My thought is that we could make a Wine prefix similar to how the WineSteam runner was done. I saw in #581 that we might be able to pick some code apart from the [Playnite](https://github.com/JosefNemec/Playnite) project. There are also some great [Wine tutorials for Origin games](http://www.gamersonlinux.com/forum/threads/mass-effect-3-guide.1641/) that we could use to setup dependencies for Origin.

I'm interested in contributing to this project, this is really awesome! Linux is becoming more and more of a flexible, high-performance gaming system. At the moment I am busy with University, but I should have some time to spare over the summer or occasionally over the weekends.

**Comment by strycore** [comment]
Please take a look at this issue, which is very similar: https://github.com/lutris/lutris/issues/748

We'd like to have an Origin runner but there are some requirements I listed in the Battle.net ticket linked above. Can you help with any of that? It would be of great help!

**Comment by Maxattax97** [comment]
I can't seem to find a reliable way to install or uninstall an Origin game, but I did find this to launch one:
`origin://launchgame/DR:235664700` which launches specifically Wing Commander 3. You can read more [here](https://gaming.stackexchange.com/questions/179412/are-there-any-command-line-arguments-for-origin).

[This article](http://support.gizmopowered.net/index.php?/Knowledgebase/Article/View/25/0/how-to-origin--battlefield-3-deployment) suggests a couple of things. First, a more complicated launch command: `origin://LaunchGame/70619,71067,DGR01609244,DGR01609245?Title=Battlefield%u00203%u2122&ProductId=DR:225064100&CommandParams=`. It may be possible to tweak this and get it to install/uninstall for us, but I don't know.

Another note it mentions that we should be wary of is this:
> Origin has activated an account antitheft mechanism where a single Origin account cannot be used on more than 4 (four) computers within a 24 hour window. This means that if you try logging in from 5 different clients in a single day you will receive a message stating that you have connected from too many computers. As of this writing there are no known ways of bypassing this security.

So we will have to be careful while testing with Wine containers.

Running `OriginSetup.exe /silent` should perform a silent install of Origin (not games) according to [this site](http://support.gizmopowered.net/index.php?/Knowledgebase/Article/View/58/17/how-to-silent-install-ea-origin-to-non-default-directory).

There is a lot of seemingly useful general information [here](https://pcgamingwiki.com/wiki/Store:Origin) about the structure and management of Origin and the games it contains.

---

Unfortunately a lot of that doesn't address the problems of automated install and uninstall. Maybe a dialog gesturing the user to click a button isn't so bad?

**Comment by AccountOneOff** [comment]
| Name              | Type        | Data
| -------------------|-------------|---
| UninstallString | REG_SZ | "C:\Program Files (x86)\Common Files\EAInstaller\Peggle\Cleanup.exe" uninstall_game -autologging

@Xenega Thanks for the tip! Here's how it uninstalls a game.

**Comment by AccountOneOff** [comment]
Found this when clicking "Launch Origin" on their website `origin2://game/launch?offerIds=Origin.OFR.50.0000461&autoDownload=1` It doesn't install the game though instead it spits this out: 
![screenshot from 2018-06-10 00-41-55](https://user-images.githubusercontent.com/15083452/41199619-c9d4c3d0-6c49-11e8-8ee7-dac3d5293f52.png)

**Comment by AccountOneOff** [comment]
570    [2018-06-10 08:33:42.496]     Event     Origin::Escalation::IPCServer::newDataAvailable                                          366       Received data: ExecuteProcess
    C:/PROG~5P2/ORIG~RPU/PEGG~WMO/__IN~S4L/touchup.exe
    install -locale en_US -installPath "C:\Program Files (x86)\Origin Games\Peggle Deluxe\" -autologging -startmenuIcon=0 -desktopIcon=0
    C:/Program Files (x86)/Origin Games/Peggle Deluxe/__Installer/

:thinking: :thinking: :thinking:

**Comment by AccountOneOff** [comment]
I got it to open the install prompt! 

`wine Origin.exe "OriginClientService.exe origin2://game/launch?offerIds=Origin.OFR.50.0000461&autoDownload=1"`

![screenshot from 2018-06-10 19-29-44](https://user-images.githubusercontent.com/15083452/41210206-236e4da8-6ce5-11e8-9c49-f7292d5db785.png)

**Comment by strycore** [comment]
Same as with the Uplay runner, we now need a list of the game IDs.

**Comment by AccountOneOff** [comment]
Here are 107 game ids. [Origin-game-ids.txt](https://github.com/lutris/lutris/files/2092210/Origin-game-ids.txt)

Some ids I was able to obtain via my game library and the rest through the Origin website. Unfortunately not all game ids show up on their site, or rather I can't find anymore, so if anyone has a game they don't see in the list sign in to the [Origin website](https://www.origin.com/usa/en-us/profile/achievements) and click on games in your library. Paste the name and game id here to add to the list. 

E.g. this is Dead Space's game id: https://www.origin.com/usa/en-us/game-library/ogd/DR:104624900/

The part after `ogd/` is the game id.

The list is still missing games like Mass Effect, Mass Effect 3 and Titanfall Standard Edition.

**Comment by mikemhenry** [comment]
How do we want to curate these game IDs?

`Command and Conquer: Command and Conquer Red Alert 2:Standard Edition Origin.OFR.50.0001094`

**Comment by mikemhenry** [comment]
This repo has a huge list:
https://github.com/ScheduleTracker/OriginOffers/tree/master/offers

**Comment by CitrusAlex** [comment]
My collection is fairly small and is dedicated solely to one lovely game series, so here's that:

The Sims 2 Ultimate Collection - OFB-EAST:65636
The Sims 3 - DR:105153500
The Sims 4 - OFB-EAST:109552299

**Comment by CitrusAlex** [comment]
The Sims 2 - OFB-EAST:65636
The Sims 3 - DR:105153500
The Sims 4 - OFB-EAST:109552299

**Comment by CitrusAlex** [comment]
What's up with the OFB-EAST part? Is it possible that some Origin games are region specific? That can be an issue.

**Comment by strycore** [comment]
I don't think the "EAST" part refers to a region, I haven't seen mentions of other regions and the lists of IDs were pretty consistent.

Btw, we don't need each and every game ID imaginable, we only need the IDs for games that we have on lutris and are not DLC / Expansions (unless we can make installer for those as well)

**Comment by AccountOneOff** [comment]
I just thought of this... There are a few problems present with Origin through Wine atm and I was wondering how the runner would get around them. To list off a few I know:

1. Client updates simply do not work currently but [there is a workaround](https://www.youtube.com/watch?v=McBY0AAaGR4) and [a script for handling that](https://github.com/DrDoctor13/wine-origin-updater).

2. Games sometimes fail if they provide DirectX. Again there is a workaround of moving/deleting all the .cab files from the redist folder found in `__Installer/directx/redist`

3. Origin In-Game can cause games to not launch

How will a Lutris runner handle these issues?

**Comment by strycore** [comment]
1. We can translate that script to Python code and implement some kind of runner update mechanism.
2. This seems to not be exclusive to Origin, I believe this is an issue with some Steam games as well, we could implement something that disables known redistributables like DirectX, Visual C++ runtime and .NET
3. Unless this is can be set in a text config file in Origin (I doubt it) then the best we can provide is a note in the installer telling users to disable it manually.

**Comment by AccountOneOff** [comment]
> Unless  this is can be set in a text config file in Origin (I doubt it) then  the best we can provide is a note in the installer telling users to  disable it manually.

There is a way to do it but it looks like the file might be user specific. The file can be found in `drive_c/users/$USER/Application Data/Origin/local_<string>.xml`

    <Setting type="1" key="EnableInGameLogging" value="false"/>

    <Setting type="10" key="OigDisabledGames" value="#//Origin.OFR.50.0001452_t#//OFB-EAST:48217_t"/>

The first setting disables it globally and the second one disables it for individual games.

**Comment by strycore** [comment]
Nice! We might be able to do something with it then!

**Comment by RobLoach** [comment]
This has worked, and not worked, for me: https://lutris.net/games/origin/

**Comment by tannisroot** [comment]
@AccountOneOff actually, the global Origin-In-Game value is determined by  
```<Setting key="EnableIgo" type="1" value="true"/>```

**Comment by benjamimgois** [comment]
Any chance we get this ready this year ? Now with Amazon prime giving lots of Origin games and steam deck on it's way, it might be a good time to revisit this issue.

**Comment by strycore** [comment]
Yes, this should be coming in one of the next releases

**Comment by tannisroot** [comment]
I think the effort should go towards EA App runner instead seeing how Origin is being deprecated.

**Comment by strycore** [comment]
This is done, it should be trivial to adapt this to the EA app since it is just a change in the launcher and not the backend API (hopefully)
