### ISSUE TITLE
[Problem] Battle.net or OW script installs nothing on Gentoo

### ISSUE THREAD

**Issue by nenoro** [lutris/lutris#809]
Hiya

So on Arch this problem doesn't exist, it works, but on Gentoo Battle.net's script or OW's script doesn't work.

It creates a wine folder but then battle.net install process is skip.

I read about dependencies but i install dependencies you suggest but even with/without nothing

I launched lutris via terminal, launch the script and see a message on terminal it said "blah blah couldn't download the software from lutris" 

So i don't know if someone else has this problem before or now.

**Comment by IngeniousDox** [comment]
The gentoo dependencies listed on that page were added by a user. If they are incomplete, please find the equivalent packages for gentoo and update the wiki please.

**Comment by strycore** [comment]
Not an issue with the client.
