### ISSUE TITLE
Wine runner crash

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#810]
The new https://github.com/lutris/lutris/commit/c6d94add8dc528d89283061b1fcaabde8f72159 update makes the wine runner crash:

`Traceback (most recent call last):`
`  File "/home/batapete/src/lutris/lutris/util/jobs.py", line 38, in <lambda>`
`    GLib.idle_add(lambda: self.callback(result, error))`
`  File "/home/batapete/src/lutris/lutris/game.py", line 201, in do_play`
`    gameplay_info = self.runner.play()`
`  File "/home/batapete/src/lutris/lutris/runners/wine.py", line 985, in play`
`    launch_info['env'] = self.get_env(os_env=False)`
`  File "/home/batapete/src/lutris/lutris/runners/wine.py", line 906, in get_env`
`    if full:`
`NameError: name 'full' is not defined
`

**Comment by kozec** [comment]
Same issue here. @Xenega , I believe that [uniforming those variables](https://github.com/lutris/lutris/commit/c6d94add8dc528d89283061b1fcaabde8f721590#diff-4565656f2d7d5dbeea5d589534973227R903) had unexpected side effect...

**Comment by Xenega** [comment]
@kozec not unexpected, just a oversight

**Comment by strycore** [comment]
Seems fixed now
