### ISSUE TITLE
Lutris packaging support for Trisquel 8

### ISSUE THREAD

**Issue by gnarlin** [lutris/lutris#812]
Hello.
I decided recently to try to migrate to Trisquel 8 (which is based on Ubuntu 16.04). I had a problem installing Lutris. Can you please add support for Trisquel 8 for Lutris repositories?
Thank you :-)

**Comment by strycore** [comment]
Do you get an error if you use the Ubuntu 16.04 repositories? There shouldn't be a need for a special repository, just like Linux Mint.

**Comment by strycore** [comment]
Closing, the Debian / Ubuntu packages should just work.
