### ISSUE TITLE
WOW/Battle.net Refreshing-Error 

### ISSUE THREAD

**Issue by zummsel** [lutris/lutris#814]
Hey Guys,

I already posted this text in the forum aswell. Probably here is a better place to post this.

I have little bug with BattleNet.
I installed WOW on to machines. One machine has Manjaro and one Arch installed. Both use the latest lts-kernel and nvidia-lts. And both are installed on the same way with all needed dependencies from https://github.com/lutris/lutris/wiki/Game:-Blizzard-App and https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell

On Arch I have a weird bug that my Battle .net lobby keeps it’s content refreshing. So I cannot see any “news” or this little window where I can see who is online. Also it is not possible to read any chat messages. And that’s what makes this bug so annoying. Maybe someone here has a solution or idea what could cause this problem.

I started lutris in both cases within the terminal to see what error messages are ocurring.

[myc@Manjaro-PC ~]$ lutris
INFO 2018-03-28 18:38:13,180 [lutriswindow]:Connected to lutris net as zummsel
wine: Unhandled exception 0xc0000417 in thread 93 at address 0x523586 (thread 0093), starting debugger…

[zummsel@Arch-Desktop ~]$ lutris
INFO 2018-03-28 21:47:07,904 [lutriswindow]:Connected to lutris net as zummsel
wine: Unhandled exception 0xc0000417 in thread 83 at address 0x523586 (thread 0083), starting debugger…
wine: Unhandled exception 0x80000003 in thread be at address 0x12759073 (thread 00be), starting debugger…
wine: Unhandled exception 0x80000003 in thread da at address 0x12759073 (thread 00da), starting debugger…
wine: Unhandled exception 0x80000003 in thread f0 at address 0x12759073 (thread 00f0), starting debugger…
wine: Unhandled exception 0x80000003 in thread 106 at address 0x12759073 (thread 0106), starting debugger…
…

In the case of Arch it repeats “wine: Unhandled exception 0x80000003…” infinitely.

Hope someone can help me.

Thanks in advance!

Best regards
zummsel

**Comment by zummsel** [comment]
After an answer in forum is here my answer:

ttf-ms-corefonts, lib32-freetype2 and freetype2 are installed.
But I don’t thinks it’s the fonts fault. It is not a display error… more like an error which causes Wine or BattleNet to reload over and over again. It’s hard to describe. If you could see it then you would immediately see what I mean.

Moreover I tried around a bit and found something out.

While logging in during installation I can see above mentioned windows and everything seems to work fine.
After closing, finishing installation and restarting BattleNet it’s not working anymore.

Ahh furthermore: In the Lutris-BattleNet-Installer is mentioned that I should close the window before logging in and finish the installation before my first login. But this causes the same issues within the username/password screen. It would keep refreshing and the login-button would never appear. So I have only one shot to login during installation, save my data and login.

Greetings
zummsel

**Comment by IngeniousDox** [comment]
I have added corefonts with winetricks to every blizzard installer now. This seems to help some that have issues with installing it into their distro. This fixed a spinning problem for someone.

And btw, you can log in during the installation process. But people tend to start installing their game, and then start playing without realising that they are still in the installer process. So that is why we strongly suggest they just close it and let the Lutris installer finish. In most cases that shouldn't be an issue.

**Comment by strycore** [comment]
Seems unrelated to the client itself, closing.
