### ISSUE TITLE
No wine version staging-2.8-x86_64 found

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#815]
As expected, once the installer is finished, the log stops at "prefix created":

    INFO     2018-03-29 15:19:13,702 [lutriswindow]:Installing guild-wars-2-64-bit
    INFO     2018-03-29 15:19:15,808 [interpreter]:Downloading file 1 of 1
    WARNING  2018-03-29 15:19:22,601 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    INFO     2018-03-29 15:19:36,053 [wine]:win64 Prefix created in /home/cxf/Games/guild-wars-2

However, you have to launch it in order to install the actual game... This get spammed while it's downloading:

    WARNING  2018-03-29 15:20:01,072 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:01,990 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,147 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,291 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,431 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,573 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,723 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,913 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:02,923 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:58,413 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:58,426 [wine]:No wine version staging-2.8-x86_64 found, falling back to system
    WARNING  2018-03-29 15:20:58,438 [wine]:No wine version staging-2.8-x86_64 found, falling back to system

**Comment by strycore** [comment]
This is missing a proper way to reproduce the bug. The Guild Wars 2 installer doesn't reference Wine Staging 2.8

**Comment by Medath** [comment]
Does this still happen? A quick check suggests that no installer uses staging-2.8 anymore, and I assume the problem was an invalid installer.

**Comment by AccountOneOff** [comment]
Nope.
