### ISSUE TITLE
Auto-setup repositories from package.

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#816]
The current way described on the Lutris website is too confusing for new users. Please, consider making package that contain the repository file instead of having users to run multiple commands using terminal.

**Comment by RobLoach** [comment]
Have an example of what you're looking for? You mean a ppa?

**Comment by AsciiWolf** [comment]
Nope, I meant the repository file/key provided directly in the Lutris package so the package can be installed by a regular user without having to use terminal. See, for example, how [Steam](https://steamcdn-a.akamaihd.net/client/installer/steam.deb) implements this.

**Comment by strycore** [comment]
Chrome does this as well. I plan adding that in a future release.

**Comment by BloodyIron** [comment]
Was this added?

**Comment by strycore** [comment]
No.

**Comment by AsciiWolf** [comment]
Then what's the point of closing this issue? Is Lutris being added to official Ubuntu repositories?

**Comment by strycore** [comment]
I'm closing the issue because I was planning to do it before the ticket existed and I'm planning to do it now that it's closed.
It's obvious that I'm going to be the one doing and I don't need a ticket for that.

**Comment by BloodyIron** [comment]
So why don't you leave it open until it's done please? Just like any other Github issue...

**Comment by strycore** [comment]
Thing is, I'm closing a bunch of other issues as well. This is relative to packaging and distribution and doesn't really have a place on the tracker for the client anyway.
