### ISSUE TITLE
set_regedit adopts filename path if key is set to the same name

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#817]
files:
    - d3d11: link
    - dxgi: link
    installer:
    - task:
    arch: win64
    key: d3d11 <=
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: builtin,native
    - task:
    arch: win64
    key: dxgi <=
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: builtin,native

![screenshot_20180401_031945](https://user-images.githubusercontent.com/15083452/38169032-405e1934-3513-11e8-870c-2f1b658975af.png)

**Comment by strycore** [comment]
Not a bug, anything that matches a file identifier given in the files section will be replaced with its full local path.
