### ISSUE TITLE
Document how to launch a game from the command line

### ISSUE THREAD

**Issue by sorsasampo** [lutris/lutris#818]
`lutris --help` does not list any way to directly launch a game.

To use Lutris with my script [`played`](https://gitlab.com/sorsasampo/played), a way to launch to game would be really useful. Preferably Lutris would after the game is finished, but even if Lutris returned to the UI this would be nice.

**Comment by RobLoach** [comment]
It's usually...
```
lutris lutris:rungame/hearthstone
```
Would like this issue fixed, though: https://github.com/lutris/lutris/issues/578

**Comment by sorsasampo** [comment]
Thanks! Would indeed be nice to get that documented, and #578.

Also, I think Lutris should exit immediately if the provided game does not exist, instead of opening the UI, but I'll add that comment to #578.
