### ISSUE TITLE
Wine does not respect Virtual desktop wine runner setting. No Default desktop defined in registry.

### ISSUE THREAD

**Issue by Ryochan7** [lutris/lutris#82]
This is more of a question than a real issue. Since the wine runner allows a user to specify whether a virtual desktop should be used in Wine, I would think that changing the setting in Lutris would be all that is needed to make it work. However, there is no way in Lutris to write a value to HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops\Default with the resolution that you want to use for the virtual desktop. Without that, Wine will not run an application in a virtual desktop. Either winecfg would have to be run from the command line or winetricks would have to be used in order to write the appropriate value to the registry.

Is this acceptable behavior or should a new option be added to the wine runner?

**Comment by Xodetaetl** [comment]
Fixed in `next` branch
