### ISSUE TITLE
Some installers made by Lutris aren't working

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#823]
They all return the same thing.

https://lutris.net/games/harry-potter-and-the-goblet-of-fire/

    {
        "count": 0,
        "next": null,
        "previous": null,
        "results": []
    }

This must be recent as [this installer](https://lutris.net/api/installers/007-the-world-is-not-enough-n64) is working.

**Comment by AccountOneOff** [comment]
Same thing just happened when I submitted this game: https://lutris.net/games/the-spongebob-squarepants-movie/

**Comment by strycore** [comment]
There was a problem with games with long names on the website, fixed now.
