### ISSUE TITLE
environment is no longer set

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#824]
This commit broke settings environment  c6d94add8dc528d89283061b1fcaabde8f721590

on c1e38872efbfec5cc0505f069ea4985df0bb37eb environment is set

@Xenega

**Comment by Xenega** [comment]
I have no problem with environment variable that I set. With which runners do you have problem? Have you a stacktrace?

**Comment by soredake** [comment]
Wine runner.
Latest commit  \[lutrislog.zip](https://github.com/lutris/lutris/files/1897294/lutrislog.zip)

c1e38872efbfec5cc0505f069ea4985df0bb37eb  [lutrislog_old_commit.zip](https://github.com/lutris/lutris/files/1897296/lutrislog_old_commit.zip)

**Comment by Xenega** [comment]
What is the environment variables that have problem? I personally change $HOME and the variable is set in wine.

**Comment by soredake** [comment]
Any variable is not set
![11-04-2018_12 13 32](https://user-images.githubusercontent.com/5204968/38607612-c8bc6242-3d81-11e8-8b0a-fe4c27f751b6.png)

**Comment by strycore** [comment]
Should be solved by PR.
