### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by fosspill** [lutris/lutris#826]
Since it seems to be possible to add "sub titles" to running games in Discord now I was thinking it would be interesting to know if it would be possible to add this for games ran through lutris.

As in, it would show you as playing "lutris", but if someone clicked you they would see "World of Warcraft" as the sub title. Reason for this is of course that Discord + wine games doesn't exactly go hand in hand as of now.

Picture of the mentioned feature:
https://runelite.net/img/features/discord.png

**Comment by strycore** [comment]
I'll have to double check the Discord API but I think there's a way to set the "Now playing" status with HTTP requests. This would be preferable to just having "User is playing Lutris".

**Comment by strycore** [comment]
@RobLoach Our Discord channel is hosted by the Linux Gamers Group: https://discord.gg/GC8vA6C 

Also, I've had a look at Discord.py a few months back, it's neat but I wouldn't want to add this as a mandatory dependency, we should maybe think about adding a plug-in system (or just make the feature present ootb but only enabled when requirements are available)

**Comment by mattjraives** [comment]
I've been looking in to this myself for a couple of days; I think that [pypresence](https://github.com/qwertyquerty/pypresence) is probably a better solution than [discord.py](https://github.com/Rapptz/discord.py).  Discord.py, from what I can tell, is more about writing bots, and while you *can* use a "self-bot" (i.e., run a bot on your user account) using discord.py, self-bots are [officially against the Discord TOS and can result in a ban](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

pypresence, on the other hand, is a wrapper specifically for discord rich presence, and so shouldn't have these issues.

**Comment by Feichtmeier** [comment]
@strycore 

when launching world of warcraft the battle.net app is started
discord shows "is playing battle.net login" :+1: :+1:  :+1: 
after I start World of Warcraft discord shows "is playing lutris"

Is there anything else I need to set up to make this work with WoW?
Thank in advance
