### ISSUE TITLE
Lutris fails to load with an exception.

### ISSUE THREAD

**Issue by GedasTheEvil** [lutris/lutris#827]
There is an error when starting the client:

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 161, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.6/site-packages/lutris/gui/lutriswindow.py", line 86, in __init__
    service.sync_with_lutris()
  File "/usr/lib/python3.6/site-packages/lutris/services/xdg.py", line 88, in sync_with_lutris
    for name, appid, exe, args in get_games():
  File "/usr/lib/python3.6/site-packages/lutris/services/xdg.py", line 129, in get_games
    appid = os.path.splitext(app.get_id())[0]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 59: invalid continuation byte
INFO     2018-04-14 14:37:30,688 [application]:Shutting down Lutris`

A possible "dirty fix":

instead of just the `appid = os.path.splitext(app.get_id())[0]`, skip the app withe the invalid name 

```python
        # Check app has an executable
        if not app.get_executable():
            continue

        try:
            appid = os.path.splitext(app.get_id())[0]
        except:
            continue
        exe = None
        args = []
```

**Comment by RobLoach** [comment]
what is the result of `app.get_id()`?

**Comment by TingPing** [comment]
Sounds like the desktop file is not utf-8.

**Comment by strycore** [comment]
I picked the executable name in such cases.
