### ISSUE TITLE
[Feature Request] Log installed games with no valid installed rom/exe

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#829]
Think this could help a lot of users. 

If you use (IE) no-intro sets, and try to keep them up-to-date, or did a bit of restructuring of the directory structure of your games, it leaves quite a few games with no longer valid roms  / executables. To sift thru a large library is quite a tedious undertaking to find that few game entries that no longer function.

All the searching could be negated by two ways, 
* while loading quickly check to see if all game entries are still valid and write a log that state which game entries are no longer valid.
* a menu entry that the user could use that scan all the game entries to check their validity, and then display the log to the user.

The main drawback I can foresee for the first idea i that would slow down loading time quite a bit especially on larger game libraries.

**Comment by strycore** [comment]
I agree, this would be quite useful.

**Comment by strycore** [comment]
This is now implemented with the Missing section.
