### ISSUE TITLE
[Feature Request] Option to run a script along with the game

### ISSUE THREAD

**Issue by diamondburned** [lutris/lutris#831]
Hello. Just requesting this feature that would launch a script before the start of a game.

**Comment by RobLoach** [comment]
What would you like to accomplish by running a script? What would the script do?

**Comment by diamondburned** [comment]
For example running a script that assists gameplay, or a Discord Rich Presence script, or anything to be fair. Maybe a notification display?

**Comment by sorsasampo** [comment]
I would like to expand on this feature request a bit.

I wrote [`played`](https://gitlab.com/sorsasampo/played), a script to track playtime for games. If Lutris provided some way to wrap all game launches into a custom template script, I could use it to track playtime of all games.

The default could be just to launch the game:

    $COMMAND

To use `played` for tracking playtime, it could be changed to:

    played play "$GAMENAME" $COMMAND

What @diamondburned requested could be written like:

    notify-send "Lutris" "$GAMENAME started"
    $COMMAND

**Comment by diamondburned** [comment]
Awesome idea, I'm up. By the future, if Lutris provides a way to print what game the user's playing I might be able to whip up Rich Presence support with playtime.

**Comment by Meloncon** [comment]
This would also be a great feature for a user to add even simple scripts like `xset r off` to turn off Key Repeat when a game launches. Even a "run script on exit" feature would easily allow a user to toggle Key Repeat back on with very minimal fuss. +1

**Comment by rubberbandaid** [comment]
I agree, this would be great! In my case, to start up a script that presses multiple keys when I hit a single one, which I want to run only while the game runs.
Or, when I start a game I rarely play, I have a script first remind me of various hacks while playing, such as "Hit 'm' to set the FOV to widescreen", as an example.

**Comment by tannisroot** [comment]
The feature has already been implemented.

**Comment by strycore** [comment]
indeed
