### ISSUE TITLE
Certain games not launching

### ISSUE THREAD

**Issue by ghost** [lutris/lutris#832]
Hello,

Certain games—namely RUINER and Devil Daggers, both of which are the Linux builds from GOG—can be launched directly from their executable and from the panel in Cinnamon, but not from Lutris. Attached is a copy of my lutris-desktop-info.txt, if it's of any help.

Thank you in advance

[lutris-desktop-info.txt](https://github.com/lutris/lutris/files/1934094/lutris-desktop-info.txt)

**Comment by strycore** [comment]
ghost account and not the right place for support.
