### ISSUE TITLE
Games under 'Nintendo SNES' platform go missing if title contains Japanese characters

### ISSUE THREAD

**Issue by ryliejamesthomas** [lutris/lutris#833]
Hi! Just ran into this problem with playing round with organising my games.

I renamed some SNES games that use the Libretro runner to include their Japanese titles (in Japanese characters), but when selecting the 'Nintendo SNES' platform them no longer appear there. They _do_ still appear under ther 'Libretro' runner category, and the 'All platforms' category. It doesn't help if I change where in the games' titles the Japanese characters are (start or not).

Not sure if this is anyway related to issue #112?

I'm using the current stable version 0.4.14-2

**Comment by ryliejamesthomas** [comment]
They do reappear under 'Nintendo SNES' after restarting the program, but that's not ideal.

This seems to be every ROM I rename, even if I just use English.

**Comment by strycore** [comment]
That would happen for every game using a runner capable of supporting several platforms such as libretro or mednafen.
