### ISSUE TITLE
Joystick disabling

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#835]
Wonder if anyone know what I could be doing wrong. I tried to disable the joystick input for a game that doesn't really like modern gamepads (especially xinput). I've tried to use Lutris' "Joystick Control Panel" (entry in the right click) to disable the joystick, it adds a entry for the joystick in the disabled entry list. Tried a few times to get it to disable but it doesn't do it. It rewrite the entry with a "default" one.

**Comment by strycore** [comment]
That's because we reconfigure the joypads each time wine runs, Lutris disables one of the js/event controllers so they aren't detected as 2 controllers by some games (Street Fighter IV AE for example)

**Comment by telanus** [comment]
Can there be an option to disable joysticks?

**Comment by telanus** [comment]
Installed 18.04, and seems it is a distro problem, as it works as intended now on Kubuntu (so I'm going to close this) if it's allright with @strycore

**Comment by strycore** [comment]
I just added an option to disable joystick auto configuration in Lutris. This fixes DmC: Devil May Cry.

**Comment by r3d9u11** [comment]
@strycore Hello, can you explain, please, where I can disable connected USB-Joystick controller for launched game?

**Comment by hariseldon99** [comment]
It's in "Runner Options", third last entry after you check "Show advanced options".
