### ISSUE TITLE
[OpenMandriva packaging] Building issue:  AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by AngryPenguinPL** [lutris/lutris#843]
Hi.
When I was building an rpm package, I have an error with this. Does anyone know how to fix it?

```
DEBUG util.py:265:  + /bin/tar -xf /builddir/build/SOURCES/lutris_0.4.14.tar.xz
DEBUG util.py:265:  + cd lutris
DEBUG util.py:265:  + exit 0
DEBUG util.py:265:  Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.17274
DEBUG util.py:265:  + umask 022
DEBUG util.py:265:  + cd /builddir/build/BUILD
DEBUG util.py:265:  + cd lutris
DEBUG util.py:265:  + '[' 1 -eq 1 ']'
DEBUG util.py:265:  + '[' 1 -eq 1 ']'
DEBUG util.py:265:  + /usr/bin/python3 setup.py build
DEBUG util.py:265:  Traceback (most recent call last):
DEBUG util.py:265:    File "<frozen importlib._bootstrap>", line 2158, in _find_spec
DEBUG util.py:265:  AttributeError: 'DynamicImporter' object has no attribute 'find_spec'
DEBUG util.py:265:  During handling of the above exception, another exception occurred:
DEBUG util.py:265:  Traceback (most recent call last):
DEBUG util.py:265:    File "setup.py", line 5, in <module>
DEBUG util.py:265:      from lutris.settings import VERSION
DEBUG util.py:265:    File "/builddir/build/BUILD/lutris/lutris/settings.py", line 4, in <module>
DEBUG util.py:265:      from gi.repository import GLib
DEBUG util.py:265:    File "/usr/lib64/python3.4/site-packages/gi/importer.py", line 127, in find_module
DEBUG util.py:265:      'introspection typelib not found' % namespace)
DEBUG util.py:265:  ImportError: cannot import name GLib, introspection typelib not found
DEBUG util.py:265:  error: Bad exit status from /var/tmp/rpm-tmp.17274 (%build)
DEBUG util.py:265:      Bad exit status from /var/tmp/rpm-tmp.17274 (%build)
DEBUG util.py:265:  RPM build errors:
DEBUG util.py:397:  Child returncode was: 1
INFO util.py:325:  EXCEPTION: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb  --target x86_64 --without uclibc --nodeps builddir/build/SPECS/lutris.spec']
```

**Comment by AngryPenguinPL** [comment]
I'm trying to build lutris in ABF (automated build farm) for OpenMandriva
Python-gi is added to buildrequires, so should be fine.
I build Lutris from this spec: https://paste.ubuntu.com/p/8rKTkkkbPV/
I also tried spec from ROSA Linux, but I have the same error. ROSA SPEC: https://abf.io/import/lutris/blob/rosa2016.1/lutris.spec
Using an official Lutris spec is probably not a good option. Once, they are specific to SUSE / Fedora / RHEL and contain specific solutions for them... and I need solution for Mandrake/Mandriva derivates. Two, it contains other dependencies / other names and packages as python3-wheel does not exist.

**Comment by strycore** [comment]
You should talk to @akien-mga. He maintains Lutris for Mageia and is likely to be able to help you.
(Assuming that OpenMandriva and Mageia are still kinda related, I'm clueless about this, last time I installed Mandriva was in 2004)

**Comment by akien-mga** [comment]
See http://svnweb.mageia.org/packages/cauldron/lutris/current/SPECS/lutris.spec?view=markup

Lagging behind upstream by a version or two, I'll soon update it, but it should give some hints on how the packages might be named in Oma.
