### ISSUE TITLE
Bug in $GAMEDIR

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#844]
BUG
===================

Some games fail to install if your games directory name has spaces. For example, the name of my directory is 'My Games' so i get a lot of errors like the next one:

    chmod: cannot access '/home/zeioth/My': directory doesn't exists

WORKAROUND
====================

There is a workaround for this error, changing 'My Games' directory to something like 'my-games' instead.

**HOW TO REPRODUCE IT**
==========================

Installing [warframe](https://lutris.net/games/install/3596/view).

**Comment by AccountOneOff** [comment]
What if you wrap the chmod commands with quotes?

    - execute:
        command: chmod a+x "$GAMEDIR/drive_c/Program\ Files/Warframe/updater.exe"

**Comment by Zeioth** [comment]
It's not my installer and I don't have permission to modify it, but that's probably the reason, yes.

**Comment by Zeioth** [comment]
No one has complained in 5 months so I'm gonna assume this was fixed. Feel free to re-open it if it's necessary
