### ISSUE TITLE
Lutris DEB dependencies/requirements for Wine

### ISSUE THREAD

**Issue by tgm4883** [lutris/lutris#845]
Using Ubuntu Budgie 18.04, some dependencies need to be installed in order to have run wine apps (notably, I couldn't open wine config and didn't have internet connectivity for the app I installed). I see a few solutions to this issue.

1) While I can see not wanting to install a bunch of wine dependencies for all users, these dependencies could be in recommends (and thus would get installed by default on Ubuntu systems but wouldn't break the application by being removed)
2) A separate lutris-wine metapackage (and/or lutris-wine-i386/lutris-wine-amd64) could be added to the lutris repository that would depend on the things needed to make wine function properly.

**Steps to reproduce the issue:**
1. Install Ubuntu Budgie 18.04 64-bit
2. Install Lutris
3. Add a Wine runner version
4. Install an app (I used https://lutris.net/games/hero-lab/ in my testing)
5. Open the app after install and click the find updates button on the main page. Note that it complains about internet connectivity

**Comment by duhow** [comment]
@tgm4883 which deps did you need to install?

**Comment by duhow** [comment]
#761
