### ISSUE TITLE
[Feature submission] Execute command after quitting.

### ISSUE THREAD

**Issue by Bumbadawg** [lutris/lutris#848]
Hi team,
Is there a hidden feature to execute a command after a runner quits. 
Instead of simply having resolution change we could reset refresh rate also.
e.g: `xrandr --output DP-4 --mode 1920x1080 --rate 144`

Also is it possible to have a kill -9 on Steam.exe after a child process ends ? Sometimes child process dead beefs into outerspace and Steam.exe goes rendering-frozen.

Thanks.

**Comment by sorsasampo** [comment]
@Bumbadawg have a look at my suggestion for wrapping game launches into a template script:

https://github.com/lutris/lutris/issues/831#issuecomment-385614475

I think this is closely related to #831, and they should be tackled at the same time.

**Comment by Bumbadawg** [comment]
Indeed @sorsasampo, thanks for the heads up.
Although it's related to launch not exit. We'll see how they implement.

**Comment by tannisroot** [comment]
A feature for executing commands after the game quits already exists.

**Comment by strycore** [comment]
yes, this is implemented
