### ISSUE TITLE
Installing winesteam runner fails when using git version

### ISSUE THREAD

**Issue by rodneyrod** [lutris/lutris#851]
Distro: Manjaro x86_64

Steps to reproduce:
1. Install lutris-git from AUR
2. Launch lutris from terminal for program output
3. Attempt to install winesteam runner from 'Manage Runners' window

The install fails with the following error:
```
INFO     2018-05-05 21:35:29,902 [runner]:Getting runner information for wine
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/runnersdialog.py", line 166, in on_install_clicked
    dependency.install()
  File "/usr/lib/python3.6/site-packages/lutris/runners/runner.py", line 295, in install
    self.name, self.arch
lutris.runners.RunnerInstallationError: wine is not available for the x86_64 architecture

```

**Comment by strycore** [comment]
Yup, the default is now 64bit but I didn't put a default 64bit version yet :D 
Once I did that. Wine Steam installed properly.
