### ISSUE TITLE
Battle.net Launcher.exe could not be found

### ISSUE THREAD

**Issue by RedSoxFan04** [lutris/lutris#852]
I'm trying to install Battle.net so I can play StarCraft II. I've tried the regular installer and also the Vulkan installer for Battle.net, and I get the same error message. I've checked that all dependencies are installed, but I just can't get Battle.net to work.
![lutris battle net](https://user-images.githubusercontent.com/13876066/39667171-14553468-507e-11e8-83f8-a0f5047ab356.png)

**Comment by RedSoxFan04** [comment]
I followed that guide and otherwise stuck to the defaults, but it didn’t work.

**Comment by RobLoach** [comment]
Change the executable that it uses in the Configure dialog. Choose Launcher.exe

**Comment by RedSoxFan04** [comment]
I've checked all through that C Drive folder, but I can't find Launcher.exe in there.

**Comment by Zeioth** [comment]
I just installed Starcraft II + battle.net using the lutris installer 2 days ago. It's working fine.

**Comment by apolitech** [comment]
I did had this problem when i did not have wine instaled on my pc.

**Comment by strycore** [comment]
@RedSoxFan04 so you're saying that you only had wine64 installed on your system beforehand? I don't think this has been tested, what distro are you running?

**Comment by RedSoxFan04** [comment]
I'm running Debian Buster (Testing).

**Comment by strycore** [comment]
Managed to reproduce that in a Debian VM, we now detect such cases as Wine being uninstalled.

**Comment by RedSoxFan04** [comment]
I fiddled around and got it working. I just had to leave the Lutris runtime disabled and re-enable Process Monitor.

**Comment by cosmotek** [comment]
Can confirm installing Wine fixed issues when attempting to install EA app on Arch w/ Gnome Wayland.
