### ISSUE TITLE
Lutris 0.4.15 error on linux mint 18.3

### ISSUE THREAD

**Issue by Amosar** [lutris/lutris#858]
Hi,
I have update lutris today with the latest version but I'm no longer able to access to the configuration window for wine game or launch a wine game.

lutris launch log: https://pastebin.com/iWAqVpGe
Configuration access error: https://pastebin.com/i0YLDUce
Game launch error: https://pastebin.com/vs22SLpP

**Comment by strycore** [comment]
Managed to reproduce both issues and pushed fixes for them. Pretty bad bug so I'll push a bugfix release.
