### ISSUE TITLE
Empty dialog for "Select which version to install"

### ISSUE THREAD

**Issue by reloadfast** [lutris/lutris#859]
When trying to launch an installer from the web the dialog for "Select which version to install" appears empty (attached). Hitting continue does not advance the installer.

Lutris - 0.4.15
4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
![screenshot from 2018-05-12 09-20-17](https://user-images.githubusercontent.com/7727512/39955460-8e35d178-55c6-11e8-8455-5435c106b338.png)

**Comment by strycore** [comment]
Please retry with lutris 0.4.16, this has been fixed.
