### ISSUE TITLE
incompatible fontconfig issues

### ISSUE THREAD

**Issue by FirefighterBlu3** [lutris/lutris#865]
with the current release of fontconfig 2.13.0, a number of additional attributes were added in the system font .conf files. unfortunately a lot of programs such as lutris, bundle their own libfontconfig and when the lib fails to parse and load the font .conf file, it pauses. this creates an insanely long wait time due to the large number of execve() calls that are made with binaries linked to the bundled libfontconfigs.

since the fontconfig update really isn't critical or important, you can either a) downgrade fontconfig and replace/edit the /etc/fonts/*.conf files , or b) replace the libfontconfig.so.1 with a symlink to your installed system fontconfig

to temporarily work around this with symlinks, do something like so, **changing your username/path:**

```
mv /home/david/.local/share/lutris/runtime/lib32/libfontconfig.so.1 \
  /home/david/.local/share/lutris/runtime/lib32/libfontconfig.so.1.back \
  && ln -sf /usr/lib32/fontconfig.so.1 \
    /home/david/.local/share/lutris/runtime/lib32/libfontconfig.so.1

mv /home/david/.local/share/lutris/runtime/lib64/libfontconfig.so.1 \
  /home/david/.local/share/lutris/runtime/lib64/libfontconfig.so.1.back \
  && ln -sf /usr/lib/fontconfig.so.1 \
    /home/david/.local/share/lutris/runtime/lib64/libfontconfig.so.1
```

**Comment by strycore** [comment]
We already started doing something like that in the last release but it was only for /usr/lib so I added /usr/lib32 as well.
