### ISSUE TITLE
Add support for downloading metadata manually.

### ISSUE THREAD

**Issue by Nilot352** [lutris/lutris#866]
Some games such as quake(1996) do not automatically download metadata so, it would be better to allow the user to select the titles and manually download metadata for them from within the application.

 For metadata scraping i recommend IGDB.com as they have a very friendly API for apps like this.

**Comment by strycore** [comment]
what is metadata?

**Comment by Nilot352** [comment]
Metadata includes game cover and release date and platform.

**Comment by strycore** [comment]
I don't understand what the issue is then. Then game Quake has all the metadata that Lutris can provide: https://lutris.net/games/quake/

We have plans to integrate with MobyGames now that they have an API, that will provide richer data for all games.

**Comment by Nilot352** [comment]
Doesn't mobygames have a stricter limit on api calls,
