### ISSUE TITLE
Cannot launch games from .bat files

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#867]
**DESCRIPTION**
If you try to run a game from a .bat file it doesn't happen anything when you click play.

**HOW TO TEST**
Installing any version of [Warframe](https://lutris.net/games/warframe/)

**WORKAROUND**
It works fine if you run the file using 'run EXE inside wine prefix'

**Comment by ZoeyGlobe** [comment]
+1 _effects batchadventuregame_
would love to see fixed asap

**Comment by strycore** [comment]
I was able to install and launch Warframe on the current master branch, please test and confirm it's fixed, otherwise re-open the issue.
