### ISSUE TITLE
Some games require system Wine parts to be installed

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#874]
It seems that World of Warcraft (installed using the latest [install script](https://lutris.net/games/world-of-warcraft/)) and probably other games require some Wine packages to be installed although they are using bundled Wine from Lutris.

For example, the World of Warcraft requires 32-bit wine-ldap package to be installed on my Fedora 28 system. Without this package installed, the game fails to login with error `BLZ51900007`. If I try to run the game exe manually with the correct wine and wineprefix set (`WINEPREFIX="/home/asciiwolf/games/world-of-warcraft" /home/asciiwolf/.local/share/lutris/runners/wine/ge-3.6-x86_64/bin/wine World\ of\ Warcraft\ Launcher.exe`), everything works without any issues. So this seems to be an issue with Lutris somewhat forcing Wine to use system libs instead of the bundled ones.

**Comment by strycore** [comment]
That's because using the libs in the lutris runtime doesn't always work.

**Comment by daniel-j** [comment]
Next time the Lutris runtime gets built this issue _should_ be fixed, and other Battle.net issues.
https://github.com/lutris/buildbot/blob/6ab339681eee707515f18f75d69aab8cf8da6e4f/runtime/packages#L31

**Comment by strycore** [comment]
I pushed a new runtime build just now

**Comment by duhow** [comment]
#761

**Comment by strycore** [comment]
Fixed by warning dialog when system wine is not installed and the recent runtime changes
