### ISSUE TITLE
wine version mismatch on any prefix/version since release 4.16

### ISSUE THREAD

**Issue by nonchip** [lutris/lutris#875]
since release 4.16 (and a bit earlier on git master, and right now on git master, last working release was 4.14) whenever I want to run any wine program, it complains about a `wine client error:0: version mismatch 549/548.`, with exactly those versions, no matter which version is selected in the settings, and no matter the staging/mainline branch or architecture.

example debug log for the game "Star Wars: The old Republic" (but the game really doesn't matter. affects the newest witcher the same as the oldest solitaire):

```
DEBUG    2018-05-18 23:47:15,184 [game]:Launching Star Wars: The Old Republic: {'env': {'LD_LIBRARY_PATH': '/usr/lib32', 'DRI_PRIME': '0', 'WINEDEBUG': '', 'WINEARCH': 'win32', 'WINE': '/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine', 'WINEPREFIX': '/home/kyra/Games/lutris/star-wars-the-old-republic'}, 'command': ['/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine', '/home/kyra/Games/lutris/star-wars-the-old-republic/drive_c/Program Files/Electronic Arts/BioWare/Star Wars - The Old Republic/launcher.exe']}
DEBUG    2018-05-18 23:47:15,185 [thread]:Command env: SDL_VIDEO_FULLSCREEN_DISPLAY="off" PULSE_LATENCY_MSEC="60" LD_LIBRARY_PATH="/usr/lib32" DRI_PRIME="0" WINEDEBUG="" WINEARCH="win32" WINE="/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine" WINEPREFIX="/home/kyra/Games/lutris/star-wars-the-old-republic"
DEBUG    2018-05-18 23:47:15,186 [thread]:Running command: "/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine" "/home/kyra/Games/lutris/star-wars-the-old-republic/drive_c/Program Files/Electronic Arts/BioWare/Star Wars - The Old Republic/launcher.exe"
DEBUG    2018-05-18 23:47:15,186 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to off
DEBUG    2018-05-18 23:47:15,186 [thread]:Storing environment variable PULSE_LATENCY_MSEC to 60
DEBUG    2018-05-18 23:47:15,186 [thread]:Storing environment variable LD_LIBRARY_PATH to /usr/lib32
DEBUG    2018-05-18 23:47:15,186 [thread]:Storing environment variable DRI_PRIME to 0
DEBUG    2018-05-18 23:47:15,186 [thread]:Storing environment variable WINEDEBUG to
DEBUG    2018-05-18 23:47:15,187 [thread]:Storing environment variable WINEARCH to win32
DEBUG    2018-05-18 23:47:15,187 [thread]:Storing environment variable WINE to /home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine
DEBUG    2018-05-18 23:47:15,187 [thread]:Storing environment variable WINEPREFIX to /home/kyra/Games/lutris/star-wars-the-old-republic
wine client error:0: version mismatch 549/548.
DEBUG    2018-05-18 23:47:17,287 [thread]:Start process monitoring
DEBUG    2018-05-18 23:47:17,287 [thread]:Processes monitored: wine (5620:Z)
DEBUG    2018-05-18 23:47:17,287 [thread]:Waiting for processes to exit
DEBUG    2018-05-18 23:47:17,287 [thread]:Removing stdout monitor
DEBUG    2018-05-18 23:47:17,287 [thread]:Thread is no longer running
DEBUG    2018-05-18 23:47:17,288 [thread]:Restoring environment
DEBUG    2018-05-18 23:47:19,188 [game]:Game thread stopped
DEBUG    2018-05-18 23:47:19,188 [game]:Game thread still running, stopping it (state: running)
DEBUG    2018-05-18 23:47:19,190 [game]:Star Wars: The Old Republic stopped at Fri, 18 May 2018 23:47:19
DEBUG    2018-05-18 23:47:19,290 [wine]:Killing all wine processes: ['/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wineserver', '-k']
DEBUG    2018-05-18 23:47:19,290 [wine]:        Wine prefix: /home/kyra/Games/lutris/star-wars-the-old-republic
DEBUG    2018-05-18 23:47:19,290 [wine]:        Wine arch: win32
DEBUG    2018-05-18 23:47:19,295 [display]:Switching to 1680x1050+1920+0 on DVI-I-0
DEBUG    2018-05-18 23:47:19,299 [wine]:Waiting for wine processes to terminate
DEBUG    2018-05-18 23:47:19,300 [thread]:Restoring environment
DEBUG    2018-05-18 23:47:19,300 [thread]:Killing all remaining processes
DEBUG    2018-05-18 23:47:19,336 [display]:Switching to 1920x1080+0+0 on HDMI-0
WARNING  2018-05-18 23:47:19,354 [display]:xgamma is not available on your system
ERROR    2018-05-18 23:47:19,403 [system]:Could not kill process 5657
```

**Comment by nonchip** [comment]
output of `strace -f -e execve -o execve.txt ./bin/lutris`, then trying to run a wine program (same as in the log above) and quitting lutris after "Game has quit" is attached: 
[execve.txt](https://github.com/lutris/lutris/files/2019401/execve.txt)

game is being run in line 839:
```
5097  execve("/home/kyra/.local/share/lutris/runners/wine/staging-3.8-x86_64/bin/wine", ["/home/kyra/.local/share/lutris/r"..., "/home/kyra/Games/lutris/star-war"...], 0x7fb5d8c751f0 /* 55 vars */) = 0
```

**Comment by strycore** [comment]
Nice find! 
I sorta reverted the specified commit, can you confirm it fixes your issue?

Also, based on what you were saying about /usr/lib32, we now put it in LD_LIBRARY_PATH automatically when the runtime is used, with /usr/lib and /usr/lib32 taking priority over the runtime. Maybe worth looking at if you still encounter issues (it's in runtime.py)

**Comment by nonchip** [comment]
the wine version issue is fixed in that commit (at least for the 2 games i just tried), and so far i can't find issues with the LD_LIBRARY_PATH in xonotic (native linux runner), VBA Next (libretro runner) or winetricks (on a wine runner prefix), so the new automatic paths seem to work fine now.

**Comment by nonchip** [comment]
@00Asgaroth00 it seems you have manually prefixed LD_LIBRARY_PATH in your game's system settings:
```
Storing environment variable LD_LIBRARY_PATH to /usr/lib:/usr/lib32.........
```

this part, as far as i can see it, is from your settings, followed by the runner path and optional runtime, followed by lutris defaults.

you should first make sure your wine runner's default system settings (and those of the game) are not setting the variable at all, and check if that helps.
if not, or they aren't set by you but by lutris (which should append, not prepend them, if anything), you should open another issue (because while the devs keep telling us we could reopen them, that's actually not possible for users :P) about it, because it seems like a different kind of bug.

also `/usr/lib32` and co should preferably go into `/etc/ld.so.conf[.d/*]` instead of manually setting them, since they're system wide paths.

**Comment by 00Asgaroth00** [comment]
I've just check my default settings for the Wine and Wine Steam runners and I dont have /usr/lib[32] set anywhere, infact I dont have any LD_LIBRARY_PATH's settings set on any of my runners default settings.

However, having a look at runtime.pu it appears to manually prepend these paths in the code:

```
149          # Put /usr/lib at the beginning, this prioritizes system libraries over
   150          # the Lutris and Steam runtimes.
   151          paths = ["/usr/lib"]
   152          if os.path.exists("/usr/lib32"):
   153              # Also let the system take over 32bit libs.
   154              paths.append("/usr/lib32")
   155  
   156          # Then resolve absolute paths for the runtime
   157          paths += [os.path.join(RUNTIME_DIR, path) for path in runtime_paths]
   158  
   159      if os.environ.get('LD_LIBRARY_PATH'):
   160          paths.append(os.environ['LD_LIBRARY_PATH'])

```

**Comment by nonchip** [comment]
ok yeah that's definitely a bug, system paths should always be appended to custom ones. i suggest opening a new issue (or PR if you fix it) for this, because it influences way more than "just" wine.

i think the change was introduced as a quick and dirty fix for another related issue actually, so just reverting it won't help much.
