### ISSUE TITLE
No option to specify running with Primusrun

### ISSUE THREAD

**Issue by ErichKramer** [lutris/lutris#876]
I use bumblebee graphics drivers and specify processes to run on my GPU using primusrun. AFAIK there is no way to specify in the lutrix UI to run a game with primusrun. I am able to run Overwatch/League Of Legends from command line with primusrun, and I am able to specify that csgo should run under primus run via the Launch Options in steam but I cannot set equivalent behavior in Lutris.

**Comment by daniel-j** [comment]
There is an option to use Primusrun in system options/preferences.

**Comment by ErichKramer** [comment]
Creator is a fool.
