### ISSUE TITLE
Stuck in "Installing game data"

### ISSUE THREAD

**Issue by Corbalte** [lutris/lutris#877]
Hello good fellows, (very sorry if I'm not in the good place for that kind of issue, plus I'm quite a newbie in Linux so, I might not give all the useful data spontaneously)
It's my first try with Lutris, I'm using Mint :
`Linux version 4.13.0-41-generic (buildd@lgw01-amd64-028) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018`

I tried to install Skyrim following that link : https://lutris.net/games/the-elder-scrolls-v-skyrim/
and while the first very few steps of the installation seems to have work properly, I'm now stuck in that window : https://imgur.com/PSzYQgm
The installation has been stuck in that step since then. The first time I tried to quit, Cinnamon crashed and if I'm trying again, I'm sended back to this window, with the same problem. I thought that game data might be downloading anyway and this would be a graphical bug, but I've found people having a similar issues here : https://forums.lutris.net/t/cant-install-games-installing-game-data-stuck/792/3 (but this post is quite old right now).
I've tried to install two other game to compare : One from Steam and another which is standalone. The problem happened just the same for the steam game, but the not for the non-steam one, which seems to be installing properly. So the issue, it seems, comes from Steam.

What do you gentlemen, advise me to do next ? Thank you very much.

**Comment by strycore** [comment]
please launch lutris from a terminal with: `lutris -d` and collect the output when the installer gets stuck, there's likely to be a crash happening somewhere.
