### ISSUE TITLE
Execute Command Broken

### ISSUE THREAD

**Issue by Estard** [lutris/lutris#878]
In lutris/installer/commands.py line 88 I think the check_required_params function checks for both command and file to be present where it should only look for one and not throw an error if the other one is missing

**Comment by AccountOneOff** [comment]
Yeah a few users are encountering this issue. Both on Discord and the forums.
https://forums.lutris.net/t/warframe-dont-want-be-install/2054
https://forums.lutris.net/t/error-when-installing-programs-and-general-help-with-something/2051

**Comment by strycore** [comment]
To fix the issue without having to wait for the next release, you can run

`sudo sed -si "s/(\('fi.*nd'\))/[(\1)]/" /usr/lib/python3/dist-packages/lutris/installer/commands.py`
