### ISSUE TITLE
DRI_PRIME option is greyed out on WAYLAND

### ISSUE THREAD

**Issue by sigmaSd** [lutris/lutris#879]
HI ,
title says it , I think its related to using xrandr --listproviders which outputs "Providers: number : 0" on wayland .

**Comment by strycore** [comment]
Indeed, that will be an edge case of #489

**Comment by sigmaSd** [comment]
My bad , I should've cheked .
Impressive work you're doing btw ;)

**Comment by sonicpp** [comment]
The implementation of DRI_PRIME option is indeed very simple (@strycore warned me that it will not work on wayland). I going to bring better implementation (like showing list of available graphic cards) once (if) I have some time (in case someone else will not make it in the meantime). Current implementation will just start your game with environment DRI_PRIME=1 if you enable it...

**Comment by sigmaSd** [comment]
Yeah I know , anyway I made a quick hack to the script to use it , I just opend the issue cause I thought It wasn't known .
thanks for the good work :)

**Comment by sigmaSd** [comment]
Just one suggestion , It would be nice if ticking the prime check box means I'm case of native steam "DRI_PRIME=1 %command%" for the selected game instead of an environment variable.
