### ISSUE TITLE
write_json fails if file/directory does not exist

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#880]
With the release of 0.4.17 the `write_json` command for installers now fails with a "FileNotFound" error.  This used to work prior to the changes done in [commands.py](https://github.com/lutris/lutris/commit/28e779d58155c8bf6463d529fd2144fd71af04a5#diff-e81d96304c1bf512191bb69b66e8fa5cR441)

`lutris world-of-warcraft`

    ERROR    2018-05-22 13:52:27,230 [jobs]:Error while completing task <bound method CommandsMixin.write_json of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f7074772ef0>>: [Errno 2] No such file or directory: '/home/cxf/Games/world-of-warcraft/drive_c/users/cxf/Application Data/Battle.net/Battle.net.config'
    <class 'FileNotFoundError'> [Errno 2] No such file or directory: '/home/cxf/Games/world-of-warcraft/drive_c/users/cxf/Application Data/Battle.net/Battle.net.config'
      File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 441, in write_json
    with open(filename, 'r+' if merge else 'w') as json_file:

**Comment by kungpaogao** [comment]
I'm experiencing this issue while trying to install Overwatch.

Is there any way to fix this currently, or do we just have to wait until the next update?

OS: Solus 3.9999
