### ISSUE TITLE
Suggestion: A method of printing the currently playing games

### ISSUE THREAD

**Issue by diamondburned** [lutris/lutris#884]
Hey. I want to make a suggestion of printing the currently playing games. Maybe putting the game title to the title of Lutris would be good, like `Lutris - Team Fortress 2`, or have a command to print it, e.g. `lutris --now-playing` returns `Team Fortress 2`

**Comment by sparr** [comment]
The command line option, or something using IPC, would be nice so that it can be displayed in tools like i3bar
