### ISSUE TITLE
Steam family sharing library

### ISSUE THREAD

**Issue by NQNStudios** [lutris/lutris#887]
I have two Steam accounts and just set up family library sharing between them. I was hoping that when I synchronized my library on Lutris, the games from the shared library would appear in the menu so I could install and play them through Winesteam. It seems they don't, so some extra code might be required to support shared games through Lutris.

**Comment by awsms** [comment]
The feature doesn't work for me, family-shared games aren't visible in Lutris.

**Comment by strycore** [comment]
There's another open ticket about the support of multiple Steam accounts.
