### ISSUE TITLE
[Feature Request] Allow using system DXVK

### ISSUE THREAD

**Issue by yochananmarqos** [lutris/lutris#895]
I'm using the `dxvk-bin` [AUR package](https://aur.archlinux.org/packages/dxvk-bin) which updates a lot faster than I would expect new Lutris updates just because DXVK updated. Just like the option to use system Wine, could this option be added?

**Comment by strycore** [comment]
you can use the "manual" option to set the DLLs to whatever you'd like. \

You can also typ in version numbers in the DXVK version field, even when there's not displayed in the dropdown

**Comment by Zeioth** [comment]
That's not how the package dxvk-bin works. You have to set a wineprefix using the global variable 

    export WINEPREFIX="your path here"

and then run one of these

    setup_dxvk32
    setup_dxvk64

To uninstall it from the prefix you can use something like

    setup_dxvk64 reset
