### ISSUE TITLE
Banners are not being automatically downloaded

### ISSUE THREAD

**Issue by ovetter** [lutris/lutris#898]
Game banners are not being downloaded after syncing library, though the games themselves launch fine. Games that are added manually later download without issue.

**Comment by tannisroot** [comment]
I don't experience this issue.
Make sure you have write access to /home/USERNAME/.local/share/lutris/banners

**Comment by ovetter** [comment]
I did check the permissions before and they were fine, but I can no longer duplicate the issue myself. Either an OS or Lutris update seems to have resolved it.
