### ISSUE TITLE
Copying lutris' runtime data to another PC makes certain games crash on start.

### ISSUE THREAD

**Issue by ReyLeonardAmorato** [lutris/lutris#899]
I'm having a peculiar problem where manually syncing lutris's data (`~/.config/lutris` and `~/.local/share/lutris`) to another desktop on my LAN causes some games (mainly linux versions) crash on startup. Running the game with `LUTRIS_RUNTIME=0` stops this. Deleting `~/.local/share/runtime/steam` or letting "user2" download the required files also stops this.

I have made sure all instances of "user1" is changed to "user2" in the *.yml files in `~/.config/lutris/games`.
I also made sure no absolute symlinks exist in `~/.local/share/lutris`.

I might be getting something wrong here, but the runtime files are supposed to be generic, right?

EDIT:
Some info
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

Package: lutris
Version: 0.4.18
...
```

**Comment by ReyLeonardAmorato** [comment]
I'll have to recheck again in a few days, I'll post anything here as soon as I do.

The files are synced with plain old `rsync -av` -is there a preferred method? Meld seems to show that the folder trees are identical.

**Comment by ReyLeonardAmorato** [comment]
Hi, sorry it took so long. Apparently this went away on its own. I'm completely stumped. Nothing has changed on both machines but I can no longer reproduce the initial problem consistently. I think it's safe to close this for now, until I can produce more concrete evidence that it is indeed lutris' issue.

**Comment by strycore** [comment]
Got it! This seems to be a very special edge case, could have been caused by a weird combination.
