### ISSUE TITLE
Lutris not syncing game library

### ISSUE THREAD

**Issue by mgaruccio** [lutris/lutris#900]
I followed the process on lutris.net/about to link my steam library but after authorizing the app and seeing the "Your Steam library is being synced with your Lutris account " on the top of the page I waited for about a half hour and my library is still empty.  Have tried three or four times with no success.

**Comment by RobLoach** [comment]
Anything in the logs?

**Comment by strycore** [comment]
Your Steam account doesn't show any games, check your privacy settings in Steam.
