### ISSUE TITLE
[Ubuntu 18.04] ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by jleaders** [lutris/lutris#905]
No idea if this error is benign, but it spams my console on a fresh install/open of `lutris` from the CLI, immediately with no interaction (on Compiz nvidia-390):

`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
`

**Comment by strycore** [comment]
Are you running vanilla Ubuntu 18.04 (with Gnome Shell)?

**Comment by jleaders** [comment]
No I'm on Compiz

**Comment by strycore** [comment]
Have you found any similar issues related to Unity elsewhere online or does this seem very specific to Lutris in your case?

**Comment by jleaders** [comment]
I see the error online elsewhere, but I only ever saw it on my machine after running Lutris. My guess is lutris loads a 32-bit chain, so even though I had the correct `.so` file, I needed to get the 32-bit version. This fixed it for me:

    sudo apt-get install libgtk3-nocsd0:i386

**Comment by vsoch** [comment]
I hit the same error with a fresh install of 18.04, I saw it when I shelled into a Singularity container. None of the suggestions worked, so I just commented out the export entirely. I don't know what kind of consequences this will have, but it seems to have resolved at least the spammy message (and I don't have trouble interacting with the container).

**Comment by SPlatten** [comment]
I made a stupid mistake by upgrading a working 16.04 system to 18.04, now its broken, despite the many messages online on how to fix this, it hasn't and my system is still broken. Does anyone have a reliable fix for this and given how many years its been known about, why is this build still available and breaking more systems ?

**Comment by Bost** [comment]
I had this problem while trying to run some unrelated binary and I solved it by:
```
sudo aptitude remove libgtk3-nocsd0 gtk3-nocsd
```
and restarting the X Windows System. Try to use `apt-get remove` if you don't have `aptitude` installed.

**Comment by strycore** [comment]
Anyone using aptitude should stop and uninstall it. It's an ancient and very bad program that has the capability of destroying systems. Do not use aptitude.

**Comment by Bost** [comment]
> Anyone using aptitude should stop and uninstall it. It's an ancient and very bad program that has the capability of destroying systems. Do not use aptitude.

@strycore ???
My ubuntu 19.04 contains `aptitude 0.8.11-3ubuntu1` released in November 2018 https://git.launchpad.net/ubuntu/+source/aptitude that definitely not ancient. Quick look at the changelog shows nothing suspicious https://launchpad.net/ubuntu/+source/aptitude/+changelog which coincides with my experience: I've been using aptitude for at least 5 year without any problem!

**Comment by strycore** [comment]
aptitude has plenty of known issues documented here: https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_literal_apt_literal_vs_literal_apt_get_literal_literal_apt_cache_literal_vs_literal_aptitude_literal

While it is a functional program, it is potentially dangerous and confusing.

**Comment by Bost** [comment]
> aptitude has plenty of known issues documented here: https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_literal_apt_literal_vs_literal_apt_get_literal_literal_apt_cache_literal_vs_literal_aptitude_literal

There are only 5-6 bugs under this link (depends on how you count), reported between 2007 and 2010. Some 4 of them are fixed and 2 were merged. This source of information is weak.

> >  It's an ancient and very bad program
> While it is a functional program, it is potentially dangerous and confusing.

So is it an ancient? Clearly no. You're claiming "it's very bad" and "it's functional"... you're contradicting yourself. And about being "potentially dangerous" ... well, flying planes is potentially dangerous, too.

Sorry man, your kung-fu is weak.

**Comment by jleaders** [comment]
I use `aptitude` exclusively to purge corrupted apt packages and for that it can't be beat

**Comment by jleaders** [comment]
@SPlatten 

Verify you have only one source channel configured in /etc/apt/sources.d/
That fixed it for me

**Comment by rpotter12** [comment]
I also get this error in Ubuntu 19.10 after uninstalling unity. 
I solved it by adding a line `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0` in my `.bashrc` file.
And then installed `sudo apt install gtk3-nocsd` package.

**Comment by Hanicrumbs** [comment]
I don't remember what I did to start receiving this error two or three days ago, but installing `gtk3-nocsd0` solved it for me as well.

**Comment by Mart-Bogdan** [comment]
It's deemed resolved, but I have other fix. instead of installing gtk3-nocsd and fixing export:

edit: `/etc/X11/Xsession.d/01gtk3-nocsd` 

uncoment and set to 1:
```
export GTK3_NOCSD_IGNORE=1
```

now LD_PRELOAD is empty for new sessions.
seems less hacky and global fix for a whole system
