### ISSUE TITLE
PCSX2 fails to launch on Manjaro

### ISSUE THREAD

**Issue by rodneyrod** [lutris/lutris#906]
Happens with any PS2 game I try to play. This is the console output:

/home/[USER]/.local/share/lutris/runners/pcsx2/PCSX2: /usr/lib32/libtiff.so.5: no version information available (required by /home/[USER]/.local/share/lutris/runtime/lib32/libwx_gtk2u_core-3.0.so.0)

I checked to see if I had libtiff installed and I do, have the 32bit libs installed too.
Tested on Manjaro with latest updates.

**Comment by sigmaSd** [comment]
Hi, just use the system pscx2 instead, all you need to do is to go to the pcsx2 runner configuration choose custom runner and choose the system one "/usr/bin/PCSX2", of course you have to install it first.

**Comment by strycore** [comment]
The problem is that the version you have installed on your system conflicts with the version needed by WxWidgets in the runtime. 

I've added an option to disable system libs taking over the lutris runtime in the `next` branch, can you try it and see if it solved the issue?

**Comment by rodneyrod** [comment]
Yep that did the trick.

**Comment by Zeioth** [comment]
This issue can be closed.
