### ISSUE TITLE
Latest winetricks adds dxvk

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#908]
https://github.com/Winetricks/winetricks/blob/cf0d79b536218e4bcffc74ff7154c1ccc5a4d8a3/src/winetricks#L6607

Looks like they only provide 0.54 though. So with this what becomes of Lutris' implementation moving forward? FWIW I like that I can compile my own dlls and add them to the dxvk folder in the runtime.

**Comment by mikemhenry** [comment]
I like the current way Lutris has it implemented, you can ether manually put the dlls in the runner folder, or use the version number and it can fetch it from github

**Comment by strycore** [comment]
We already have a DXVK implementation, we don't need winetricks for that.
