### ISSUE TITLE
Add bsdtar to tools

### ISSUE THREAD

**Issue by sigmaSd** [lutris/lutris#912]
Hi, can you add bsdtar to https://lutris.net/files/tools/ , need it to extract deb packages for example here https://lutris.net/games/runescape-3/ .
If there's another way I'm missing I'll be glad to be informed .

**Comment by sigmaSd** [comment]
Nvm I'll use tar and ar instead, my bad.

**Comment by strycore** [comment]
Wait… I thought that p7zip could extract pretty much any archive format on earth, I guess you could also use that.

**Comment by sigmaSd** [comment]
Hmm well live and learn , my bad .

**Comment by strycore** [comment]
Forgot to mention that it's already available here: https://lutris.net/files/tools/p7zip-16.02-x86_64.tar.gz
