### ISSUE TITLE
Built-in Winetricks doesn't work, sha256sum mismatch (outdated winetricks?)

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#920]
When trying to install pretty much anything using winetricks, it reports about sha256sum mismatch:
`sha256sum mismatch! Rename /home/alex/.cache/winetricks/flash/flashplayer_14_sa.exe and try again.
`
It also reports that winetricks version Lutris uses it outdated, which is most likely the cause. Is it possible perhaps for Lutris to auto-update winetricks independently, like DXVK?

**Comment by strycore** [comment]
it seems that your winetricks cache is outdated, try deleting /home/alex/.cache/winetricks/ and try again.

winetricks is updated before each release so it's pretty up to date, the latest versions didn't change a lot of things.

**Comment by CitrusAlex** [comment]
Deleting cache didn't help.
Just looked into the flash - the Lutris version of Winetrick tries to get it from here
`http://fpdownload.macromedia.com/pub/flashplayer/updaters/14/flashplayer_14_sa.exe`
which returns 404, while latest winetricks version tries to get it from 
`https://download.macromedia.com/pub/flashplayer/installers/archive/fp_14.0.0.176_archive.zip `
and succeeds.
I also had this problem with a quite a lot of other installers but I don't really have time at the moment to test this further. But I suppose a lot indeed has changed between these versions?

**Comment by strycore** [comment]
Sometimes, a random winetricks task will break and the only way around is to update it. You can try doing that by downloading the latest version and replacing /usr/share/lutris/bin/winetricks (make sure it's executable)

**Comment by CitrusAlex** [comment]
Ok! Thanks for the suggestion. Hope to see auto-update of winetricks featured in 0.50.

**Comment by Medath** [comment]
I guess this all the described issues here are already solved, right?

**Comment by tannisroot** [comment]
Yep 👍
