### ISSUE TITLE
Wrong WINEPREFIX set for winetricks when installing winesteam games

### ISSUE THREAD

**Issue by DaDummy** [lutris/lutris#923]
Lutris launches winetricks with an invalid WINEPREFIX when installing a winesteam recipe.

[Example installer script](https://lutris.net/games/endless-space-2-steam-64-bit/installer/edit?revision=11458)

expected WINEPREFIX: `$HOME/.local/share/lutris/runners/winesteam/prefix64`

WINEPREFIX supplied by Lutris: `$HOME/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps/common/Endless Space 2`

This causes winetricks to behave... funny to say the least.

**Comment by strycore** [comment]
Thanks for the fix!
