### ISSUE TITLE
Changing resolution does not work on Nvidia Optimus setup

### ISSUE THREAD

**Issue by DafabHoid** [lutris/lutris#933]
### Problem:
With the current lutris release (0.4.18) I can't change the resolution when starting a game when the PRIME profile is set to nvidia. The command lutris uses is `xrandr -s WxH`, which just outputs for example

    $ xrandr -s 1280x720
    Size 1280x720 not found in available modes
    $ xrandr -s 2
    Size index 2 is too large, there are only 1 sizes

Changing it with `xrandr --output eDP-1-1 --mode 1280x720` works though.

I suggest not using the -s switch anymore, which is obsolete since RandR 1.2 (which was introduced with Ubuntu 7.10 over ten years ago).

Note: With PRIME profile set to intel, it does work.
### System configuration:
- Kubuntu 18.04
- Nvidia Optimus setup with GTX 850M as discrete GPU
- Proprietary Nvidia drivers installed, with PRIME profile set to "nvidia"

**Comment by strycore** [comment]
Moving to post-1.0 since no one seems interested in fixing this.

**Comment by strycore** [comment]
this is not lutris related

**Comment by yjfguhd** [comment]
Here's a patch that should fix this:
```diff
--- xrandr.py	2024-02-25 11:18:48.358106173 +0000
+++ /usr/lib/python3.12/site-packages/lutris/util/graphics/xrandr.py	2024-02-25 12:05:03.409359697 +0000
@@ -119,8 +119,9 @@
         if resolution not in get_resolutions():
             logger.warning("Resolution %s doesn't exist.", resolution)
         else:
-            logger.info("Changing resolution to %s", resolution)
-            with subprocess.Popen([LINUX_SYSTEM.get("xrandr"), "-s", resolution]) as xrandr:
+            output_name = get_outputs()[0].name
+            logger.info("Changing resolution on %s to %s", output_name, resolution)
+            with subprocess.Popen([LINUX_SYSTEM.get("xrandr"), "--output", output_name, "--mode", resolution]) as xrandr:
                 xrandr.communicate()
 
     else:
     
```

**Comment by danieljohnson2** [comment]
That looks good to me and seems to work, so I'll apply this change.
