### ISSUE TITLE
Lutris closes Steam during log-in

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#936]
If a game uses Steam Wine runner and runs using a prefix that is different from default one (my assumption, not sure), after the installation Steam asks to log in again.
Because Lutris can't launch the game due to that, it thinks that game has been closed and closes Steam before the user can sign in to their account. It can take some time (minute or close to it) but it will happen.
Unchecking "Stop Steam after game exits" for the first log-in and checking it back helps, but it should work without touching it. Doing that can also be quite inconvenient for users who don't use "Remember Me" option during log in. It is also possible to log-in without changing that option if it's done fast enough, but that's tricky and annoying, especially with 2-factor authentication enabled.

**Comment by nonchip** [comment]
> using a prefix that is different from default one (my assumption, not sure)

even happens when using the default one, if you take just a bit too long to log in or even if steam takes a bit too long to "perform first run dependency setup" when running

**Comment by Cether-Skye** [comment]
This also happens to me, though I've not yet figured out why it's occurring. Once I'm past the login step, it doesn't seem that winesteam runs at all, no matter what options I tick.

**Comment by tannisroot** [comment]
This should be fixed now that Lutris copies login data to separate prefixes.
