### ISSUE TITLE
Wine Steam runner ignores "Windowed (virtual desktop)" setting from its Configure window

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#937]
Windowed (virtual desktop) and Virtual desktop resolution are ignored in favor of winecfg's virtual desktop option. If I turn both of those off the virtual desktop persists even after relaunching Lutris. It's not until I unchecked virtual desktop in winecfg that it stopped using it.

Here I have both Lutris options enabled with 1920x1030 as the resolution and Winecfg's virtual desktop option enabled with 800x600 as the resolution. Winecfg takes precedence and the Lutris settings are ignored. This only seems to be an issue when running Wine Steam directly via the sidebar.

![screenshot from 2018-06-20 14-53-20](https://user-images.githubusercontent.com/15083452/41687007-0d1defd2-749b-11e8-9994-efd32a38c9d6.png)

To reproduce:

- Disable both options
- Right-click a game (making sure it's the same prefix as winesteam) > Run exe > winecfg.exe
- Enable virtual desktop under the Graphics tab
- Rerun and the virtual desktop still spawns

**Comment by IngeniousDox** [comment]
I came across this: Cuisine Royale setting fully ignored virtual windows settings....had to do it with Wine Configuration, but that effects the whole Wine-Steam prefix.

**Comment by daniel-j** [comment]
It's because the Wine/Wine Steam runner has a prepare game launch routine that sets registry values for things like virtual desktop, which isn't called when using Run or Run exe inside prefix.

**Comment by IngeniousDox** [comment]
Ok, adding for the record: My case is the opposite. I was setting virtual desktop in Lutris only, and nothing happend.

**Comment by strycore** [comment]
I merged this is master for inclusion in 0.4.19

**Comment by Medath** [comment]
It looks like this got fixed already
