### ISSUE TITLE
lutris ignores command prefix when running steamless executable in winesteam

### ISSUE THREAD

**Issue by nonchip** [lutris/lutris#942]
My setup:
* Game: Skyrim in winesteam
* wrapper script (https://gitlab.com/snippets/1727281) set as "command prefix" in the system settings mounts the game folder
* using skse_loader as the steamless executable

when trying to run it, i get:
```
DEBUG    2018-06-23 05:58:24,395 [steam]:Watching Steam folder /home/kyra/.local/share/Steam/steamapps
DEBUG    2018-06-23 05:58:24,395 [steam]:Watching Steam folder /home/kyra/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/steamapps
INFO     2018-06-23 05:58:29,289 [runner]:Runtime disabled by system configuration
DEBUG    2018-06-23 05:58:30,137 [system]:Executing pgrep Steam.exe$
INFO     2018-06-23 05:58:30,277 [runner]:Runtime disabled by system configuration
DEBUG    2018-06-23 05:58:30,278 [game]:Launching The Elder Scrolls V: Skyrim MODDED: {'error': 'FILE_NOT_FOUND', 'file': '/home/kyra/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/steamapps/common/Skyrim/skse_loader.exe'}
```

this indicates the command prefix was never prefixed, or lutris tries to verify the location before running it for no good reason.

the fix would be either:
* make sure the command prefix is actually used for all commands and:
  * preferably don't check file existence for no reason (just trying to run it would also tell us if it doesn't exist)
  * or use `command_prefix ls ...` to check it
* or add a "run before starting" and "run after stopping" field to put (un)mounting scripts into.
* or preferably both

**Comment by strycore** [comment]
there are several tickets about that run before / after commands, I think we'll prioritize that feature.

**Comment by strycore** [comment]
Closed by https://github.com/lutris/lutris/commit/51b556b8221812eaa38ea3cd73fec0bea40440b9
