### ISSUE TITLE
Lutris no longer sandboxes folders like 'My Documents" inside prefix

### ISSUE THREAD

**Issue by CitrusAlex** [lutris/lutris#947]
Since 24th June and roughly 1-2 AM GMT, all newly created prefixes using Lutris 4.18 no longer have their own folders like "My Documents", instead they symlink to ones at $HOME.
Sandbox option in Lutris config is checked.

**Comment by daniel-j** [comment]
Does the symlinks remain after you've pressed play on the game? Lutris sandboxes during the prelaunch phase when you run a game.

**Comment by CitrusAlex** [comment]
Yes, it still has symlinks, even after the game was lauched.

**Comment by CitrusAlex** [comment]
Seems like I can only reproduce this in 4.18.
Lutris Next sandboxes My Documents just fine.

**Comment by CitrusAlex** [comment]
Can't replicate anymore. I suppose something got updated and fixed it. Closed.
