### ISSUE TITLE
[Request] Search function for Wine versions

### ISSUE THREAD

**Issue by Sethox** [lutris/lutris#949]
As the title suggest.. Right now there are plenty of WINE versions, different versions of A WINE version. And having it in a list is functional but not practical as it could be. A search function or something that separates from the main versions-to staging-to others with a column of dates of when it was put into the list and dates on when it was released (from now on, old ones will have no dates because like I said; plenty of Wine versions). This basic information will help the end user a lot.

**Comment by AccountOneOff** [comment]
This can also be merged with #613
