### ISSUE TITLE
Cannot set audio output to ALSA

### ISSUE THREAD

**Issue by NuSuey** [lutris/lutris#950]
Since a commit from May (https://github.com/lutris/lutris/commit/b5e06cee0295b922a0f0dc7112870c7d55751b74) I cannot set a game audio output to alsa, since the Sound driver output selection is gone, I've tried to setup alsa via registry [HKEY_CURRENT_USER\Software\Wine\Drivers] Audio="alsa" but the registry get's auto removed and output put back to Pulse Audio. 
This is very important for low latency games, in my case https://lutris.net/games/rocksmith-2014 where the sound output was set to "alsa" in the script via "sound: alsa" .. therefore making the script a mess since it relies on it.

**Comment by strycore** [comment]
Merged in master

**Comment by alexanderadam** [comment]
@NuSuey sorry for the late question but is RS 2014 Remastered working without any issues for you? :eyes: 

I [tried to create a Docker script for Rocksmith 2014 Remastered](https://github.com/alexanderadam/rocksmith-2014-wine-docker) and just stumbled over lutris because a search pointed me to this particular issue.

**Comment by NuSuey** [comment]
Well nowadays I run it via proton. The only bigger recent issue that I had was that sometimes that all of a sudden randomly the audio became much faster and suddenly you could hear some crackling (had to do a alt tab to get rid of it, if used virtual desktop in wine, then I had to close the entire steam) but I do stream it via OBS so maybe it affected that too? (but hard to tell case I didn't had such issue for a long time) 
Appart of that It's been working pretty great (> 700 hours played in Linux)

**Comment by alexanderadam** [comment]
Wow, you respond fast! Thank you!
Did you have to apply [some fixes like others](https://www.protondb.com/app/221680) to get it running on Proton or did it run out of the box?

**Comment by NuSuey** [comment]
Not out of the box at all..
For proton, you have to do the Z: drive where your steam library is (like the post), force the audio to alsa, have a rocksmith.ini with all those values like "ExclusiveMode=0 Win32UltraLowLatencyMode=0" and the LatencyBuffer which I think I have to 1 or 2 but not at home atm so can't say exactly what I got.I do have also tsched=0 for pulseaudio, and disabled rocksmith guitar in pulse. 
If I haven't forgotten that might be the main stuff you need to get it working well. 
Only added the "default-fragments" stuff recently, so I wouldn't call that a "must have" but at the same time I will have to find the time and go through each setting at some point, to figure out which one and how much is each of the settings working.
