### ISSUE TITLE
Keep xboxdrv running

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#955]
Do not shut down external xboxdrv.
I have xboxdrv running as a daemon and change configuration slots depending on the games I start.
But when shutting down the daemon after I quit the game, my gamepad will fall back to xpad and xboxdrv related settings in lutris fail.

**Comment by basxto** [comment]
I think I misused that field, I put `-s 0 -c 1` into it.
It run xboxdrvctl and switched the configuration of my already running xboxdrv daemon, that’s what I wanted.
But as I understand now, it was never intended to work that way.
Lutris will just run and kill xboxdrv in user space, right?

I couldn’t manage to start xboxdrv from user space on my machine.

**Comment by strycore** [comment]
Yeah, I haven't managed to run xboxdrv in usespace either. We try not using root in Lutris but for xboxdrv I had to implement some PolicyKit rules that will let Lutris start and kill the xboxdrv daemon without needing a password.

**Comment by basxto** [comment]
My xboxdrv is running as a systemd service.
I had to modify `/etc/dbus-1/system.d/org.seul.Xboxdrv.conf`
```
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">               
<busconfig>
  <policy context="default">
    <allow own="org.seul.Xboxdrv"/>
    <allow send_type="method_call"/>
  </policy>
</busconfig>
```
for being able to control it with `xboxdrvctl`.

**Comment by basxto** [comment]
My assumptions were wrong and everything is working fine now.
Thanks.

I guess it’s best to start it via lutris and have some special configurations for some games.

**Comment by strycore** [comment]
I guess our setup isn't ideal for people who have xboxdrv running as a service like you do. This is most likely to change in the future. I personally haven't used xboxdrv in a long time (thanks to wine supporting xinput) and our future controller specific changes will probably fix this issue at somepoint.

**Comment by basxto** [comment]
I started to play with xboxdrv because of two reasons:
 * gog version of https://lutris.net/games/the-king-of-fighters-2002/ does not support gamepads
* https://lutris.net/games/one-piece-pirate-warriors-3/ has problems with the trigger buttons, there is an xboxdrv configuration on winehq. But that game broke after setting up the gamepad.
