### ISSUE TITLE
Display better message for requires: when it involves a Lutris installer

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#957]
The current message just displays the installer slug. It should have a prompt to install that installer or link to the installer page on the website. Also some rewording is due.

"Please install so and so before proceeding." or "Installing so and so is required before proceeding."

![screenshot from 2018-06-30 23-22-52](https://user-images.githubusercontent.com/15083452/42131688-cee77934-7cbc-11e8-9ae4-ec0216d0506c.png)

**Comment by strycore** [comment]
Required games are now automatically installed
