### ISSUE TITLE
Always show scrollbar for notes

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#959]
It's not really evident that there are more notes under these unless you hover over them. Always showing the scrollbar, when it exceeds in length, would be better practice.

**Shown:**

Do not sign-in when prompted. Close Origin and wait for the installation to finish then you can relaunch and sign-in.

Disable Origin In-Game just in case.

Make sure "Disable Lutris runtime" is unchecked in the game's system options tab or else download will fail.

**Hidden:**

Should your download pause at 22% press the <a href="https://i.imgur.com/8Vv0bva.png">play icon</a> until it resumes downloading.

![screenshot from 2018-07-01 15-03-23](https://user-images.githubusercontent.com/15083452/42139292-efeb026c-7d3f-11e8-8fae-cf96c0af5810.png)

**Comment by strycore** [comment]
Fixed in next
