### ISSUE TITLE
Restoration of keyboard layout broken

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#961]
When I run [influent steam version](https://lutris.net/games/influent/) with keyboard layout set to US via lutris:
* closing the game does not get detected, so I have to press `stop game`
* keyboard layout is not restored until steam is shut down, which was running before and not started by lutris

Lutris 0.4.18 on Archlinux with steam and lutris runtime disabled.

**Comment by strycore** [comment]
this isn't related to the keyboard layout option but the way steam processes are monitored.
