### ISSUE TITLE
Lutris doesn't have focus after steam game is closed

### ISSUE THREAD

**Issue by Zlopez** [lutris/lutris#965]
When starting Steam game using Lutris in Gnome 3.28, I'm encountering an issue when I close the game.

After the game is closed, Lutris doesn't have focus and I can't click on anything until I manually close Steam.

How to reproduce:
1. Start Lutris
2. Start Steam game
3. Exit Steam game

Expected result:
Lutris should have focus.

Actual result:
Lutris doesn't have focus till Steam is closed manually.

Workaround:
Enable option "Stop steam after game exits".

Versions:
steam-1.0.0.54-17.fc28.i686
lutris-0.4.18-4.1.noarch
gnome-shell-3.28.2-1.fc28.x86_64

**Comment by strycore** [comment]
side effect of the fact that we don't have a Steam sub-monitor, closing.
