### ISSUE TITLE
DLLs missing corresponding source and proper attribution

### ISSUE THREAD

**Issue by Kasijjuf** [lutris/lutris#966]
The DLLs within the subdirectories of the
[lutris/share/lutris/controllers]
(https://github.com/lutris/lutris/tree/master/share/lutris/controllers/)
directory lack their corresponding source code and any sort of
attribution.

Based on a quick search I believe some of them originate from
https://github.com/kozec/dumbxinputemu/. That repository is released
under the GNU LGPLv3, which, while compatible with this project's
license, still requires its conditions to be met.

Additionally, the [gamecontrollerdb.txt]
(https://github.com/lutris/lutris/blob/master/share/lutris/controllers/gamecontrollerdb.txt)
file in the same controllers directory lacks any indication of where it
came from.

**Comment by strycore** [comment]
Fixed for gamecontrollerdb

**Comment by strycore** [comment]
The DLLs have been moved to the lutris runtime, with READMEs
