### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by stupedama** [lutris/lutris#970]
Setting dxvk to default gives:

ERROR    2018-07-18 10:45:40,676 [http]:Unavailable url (https://github.com/doitsujin/dxvk/releases/download/v0.52  (default)/dxvk-0.52  (default).tar.gz): HTTP Error 400: Bad Request

**Comment by luthub** [comment]
This issue exists in the current release, but seems to be fixed already in the next branch. As a workaround you can manually type in the version number that you want and it should work fine.

**Comment by strycore** [comment]
Yes, this is fixed already.

If you really need 0.52 then select "0.52 (default)" and write "0.52" instead. We recommend you put 0.62 instead because that's the current version
