### ISSUE TITLE
Auto update latest DXVK versions

### ISSUE THREAD

**Issue by duhow** [lutris/lutris#974]
https://github.com/lutris/lutris/blob/525c84d9da173e84fd5585eed6b9d2fef5bef2b2/lutris/util/dxvk.py#L11-L12

Instead of writing static versions, use GitHub API to get the latest versions of DXVK:
```bash
curl -s https://api.github.com/repos/doitsujin/dxvk/tags  | jq '[.[] | .name] | join(", ")'
"v0.62, v0.61, v0.60, v0.54, v0.53, v0.52, v0.51, v0.50, v0.42, v0.41, v0.40, v0.31, v0.30, v0.21, v0.20"
```

**Comment by duhow** [comment]
The small problem is that you won't know if there's a new version available already or not.
Of course you can also use **latest** tag, or as you say, specify the version you want, because the code is ready for that.

https://github.com/lutris/lutris/blob/525c84d9da173e84fd5585eed6b9d2fef5bef2b2/lutris/util/dxvk.py#L17

The idea of this, is just to make the version selector updated with all versions, not having to set it manually.

**Comment by BloodyIron** [comment]
Right now, DXVK is in very big flux. In many cases, there are only specific scenarios where upping the DXVK version on an already existing installation is worthwhile. I don't think this is an actual problem at this time, and even still, the long-term roadmap for DXVK is uncertain.

As a hypothetical, what if it gets into mainline WINE? Do we really need to invest more coding time into this aspect? Which in my opinion is a non-issue, as if you know what DXVK is, and you know where this setting is, you are probably plenty capable to go look at the github repo to see if a new release is out.

I don't think the minor, minor, convenience warrants the function. Even though as an automatic function is kinda does make sense.

**Comment by matthewkovacs** [comment]
I've issued a pull request that resolves this issue.  Cheers!
