### ISSUE TITLE
Command prefix prevents game from launching

### ISSUE THREAD

**Issue by FREEZEball** [lutris/lutris#978]
When I try to set command prefix for a wine game (WoW/Battle.NET), it does not parse correctly and fails to launch (status message "Game has quit"). Command preffix is 
`setxkbmap -layout "ru,us"`
so that it forces Xorg to use this layout for current session (Wine uses strange slavic layout that does not happen anywhere else in the system). Debug output for this command is

> DEBUG    2018-07-22 09:44:02,440 [thread]:Running command: "setxkbmap" "-layout" "ru,us" "/home/fb/.local/share/lutris/runners/wine/staging-3.12-x86_64/bin/wine" "/home/fb/Games/bnet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"
> _a lot of stored environment variables_
> DEBUG    2018-07-22 09:44:04,666 [thread]:Start process monitoring
> DEBUG    2018-07-22 09:44:04,666 [thread]:Processes monitored: setxkbmap (29377:Z)
> DEBUG    2018-07-22 09:44:04,667 [thread]:Waiting for processes to exit
> DEBUG    2018-07-22 09:44:04,667 [thread]:Thread is no longer running
> DEBUG    2018-07-22 09:44:04,667 [thread]:Restoring environment
> DEBUG    2018-07-22 09:44:06,442 [game]:Game thread stopped
> DEBUG    2018-07-22 09:44:06,442 [game]:Game thread still running, stopping it (state: running)
> DEBUG    2018-07-22 09:44:06,443 [game]:WoW stopped at Sun, 22 Jul 2018 09:44:06
> INFO     2018-07-22 09:44:06,443 [runner]:Runtime disabled by system configuration
> DEBUG    2018-07-22 09:44:06,663 [wine]:Killing all wine processes: ['/home/fb/.local/share/lutris/runners/wine/staging-3.12-x86_64/bin/wineserver', '-k']
> DEBUG    2018-07-22 09:44:06,663 [wine]:        Wine prefix: /home/fb/Games/bnet
> DEBUG    2018-07-22 09:44:06,664 [wine]:        Wine arch: win64
> DEBUG    2018-07-22 09:44:06,673 [wine]:Waiting for wine processes to terminate
> DEBUG    2018-07-22 09:44:06,674 [thread]:Restoring environment
> DEBUG    2018-07-22 09:44:06,674 [thread]:Killing all remaining processes

From what I understood, it watches for sexkbmap process instead of wine/b.net. When I try to set prefix like this: 
`setxkbmap\ -layout\ \"ru,us\"`
to prevent spaces in it, it throws another error:

> DEBUG    2018-07-22 09:50:38,427 [thread]:Running command: "setxkbmap -layout "ru,us"" "/home/fb/.local/share/lutris/runners/wine/staging-3.12-x86_64/bin/wine" "/home/fb/Games/bnet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe"

and
> ERROR    2018-07-22 09:50:38,444 [thread]:Failed to execute setxkbmap -layout "ru,us" /home/fb/.local/share/lutris/runners/wine/staging-3.12-x86_64/bin/wine /home/fb/Games/bnet/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe: [Errno 2] No such file or directory: 'setxkbmap -layout "ru,us"': 'setxkbmap -layout "ru,us"'
> FileNotFoundError: [Errno 2] No such file or directory: 'setxkbmap -layout "ru,us"': 'setxkbmap -layout "ru,us"'
> WARNING  2018-07-22 09:50:38,446 [thread]:No game process available

_Note that "No such file or directory" was translated from Russian by myself, so exact words may differ._

What can I do to work around this in Lutris? Or am I missing the point of an option? I can obviously launch script once per session manually or automatically, but is it possible to do inside the program itself?

**Comment by strycore** [comment]
what you want are commands that are run before and after the game runs, not a command prefix. Command prefixes are programs like padsp or primusrun that you prepent to the game executable. Here, you just want to run setxkbmap before the game runs. This is already tracked in https://github.com/lutris/lutris/issues/831 so I'll close this as a duplicate, but we will tackle this issue soon.
