### ISSUE TITLE
Citra runner requires GLIBCXX_3.4.22 (libstdc++.so.6.0.22 or newer)

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#979]
The current citra-qt binary shipped with the Citra runner in Lutris 0.4.18 won't work on distros with libstdc++ older than libstdc++.so.6.0.22 (so IINM any distro shipping with GCC 5 or older by default).

This affects Mageia 6, and likely also Ubuntu 16.04.x and likely a variety of other distros from 2016/2017 (or earlier of course).

I don't know if you're shipping the upstream Citra binaries (which I confirm are not portable on older distros) or building them yourself. If building them yourself, you'd have to try to build them on a distro like Ubuntu 16.04 for good compatibility.

IIRC I tried to build Citra from source and it strictly required GCC 6 or newer, so a solution (for Lutris or ideally, for upstream) could be to try linking libstdc++ statically, passing `-static-libgcc -static-libstdc++` to the linker.

If that's not something that we can/want to fix in Lutris, there should maybe a libstdc++ version check before installing the Citra runner to prevent installing it where not supported. Currently trying to run this launcher just returns instantly, and shows this in the terminal:
```
/home/akien/.local/share/lutris/runners/citra/citra-qt: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/akien/.local/share/lutris/runners/citra/citra-qt)
```

**Comment by duhow** [comment]
Following the [API](https://lutris.net/api/runners/citra), it will download a compiled Citra version [20170606](https://github.com/citra-emu/citra/commit/8f0a23b6) which is the default one.
I can run it with `Debian 9.5` and `libstdc++ 6.3.0-18+deb9u1`.
You could try to download an old version available in the Lutris repo, or set a **custom executable for the runner**.

btw, running the latest nightly build [citra-linux-20180727-be19386.tar.xz](https://github.com/citra-emu/citra-nightly/releases/download/nightly-832/citra-linux-20180727-be19386.tar.xz) does not work for me:
```bash
./citra-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./citra-qt)
```

**Comment by strycore** [comment]
It's not possible to build Citra on Ubuntu 16.04 (what our build containers use) since there's no gcc-6 package. I can't even get it to build on 18.04 right now.

**Comment by strycore** [comment]
New build is available, it's just a snapshot of the latest github release. I also updated the 18.04 runtime to add libsndio which is needed by citra. Tested and runs really great!
