### ISSUE TITLE
Adding ability to launch game in separated X?

### ISSUE THREAD

**Issue by byaka** [lutris/lutris#982]
Think it can helps with some wine games on some DE (for example i cant play BF3 on Unity 7 without this). And ofc it can help with performance on low hw.

**Comment by strycore** [comment]
can it not be done with environment variables? like DISPLAY=:2

**Comment by byaka** [comment]
i'm not sure, if this will works "transparently" for users.
For now i'm use
```bash
xinit /usr/bin/env playonlinux --run "$1" -- :1
```
which command prepares bae env for running POL (not sure is this needed for Lutris) and also returns me back when program terminates.

**Comment by strycore** [comment]
I guess it would be possible to experiment with such a command by using `lutris` instead of `playonlinux` and `--exec` instead of `--run`

**Comment by byaka** [comment]
sure. but think it would be great, if `lutris` can run app in this way itself (so we don't need to manually create launch-entry for each game that need it).
Just idea, maybe someone want to implement this. Maybe i implement this myself - but first of all i need to move all my configured prefixes from POL to Lutris (and i'm not sure how to do this - i have 17 prefixes with diffrent wines and 20+ launchers).

**Comment by strycore** [comment]
> sure. but think it would be great, if lutris can run app in this way itself (so we don't need to manually create launch-entry for each game that need it).
It's just so I can validate this before implementing it. I've never successfully ran a secondary X server in 20 years, it's just not my thing.
If it's just a wrapper like we do for Xephyr then it should be pretty simple to add.

**Comment by byaka** [comment]
@strycore is this implemented or just *wontfix*?

**Comment by strycore** [comment]
wontfix, or waiting from a PR from someone external.
