### ISSUE TITLE
Support for Feral's gamemode daemon.

### ISSUE THREAD

**Issue by fosspill** [lutris/lutris#983]
It would be great to see proper support for the gamemode daemon by Feral: 
https://github.com/FeralInteractive/gamemode/

Either a checkbox pr game saying "Activate/Request gamemode" or a global config option for lutris (or both!) :)

**Comment by AccountOneOff** [comment]
This is already in `next` https://github.com/lutris/lutris/blob/next/lutris/util/system.py#L50
