### ISSUE TITLE
[Feature Request] Add repo to computer when installing from deb/other

### ISSUE THREAD

**Issue by BloodyIron** [lutris/lutris#987]
I'd really like it if we could make it so when users install Lutris from the deb or other package, that it sets up the repo for them for future updates as part of the installation process.

This is already done for Skype and other software, and would make the user experience tangibly more convenient, and I personally plan to direct people to get setup with Lutris this way.

Please?

**Comment by strycore** [comment]
Yes, I want that as well. I would like to create a minimal deb that just sets up the repos and downloads the correct version. Exactly what Chrome does.

**Comment by duhow** [comment]
#816
