### ISSUE TITLE
Replacing ... with DXVK version fortnite launcher

### ISSUE THREAD

**Issue by Mcilie** [lutris/lutris#988]
When I saw the news about fortnite being run on lutris, I immediately rushed to my workstation and installed wine and lutris. I am a noob to this process so please forgive me if this issue is already solved.
I installed the Epic games launcher and ran the command to start lutris from terminal. Then I clicked on the Epic games launcher and it would not launch. Instead it spit out this 

    Gtk-Message: 16:47:50.699: GtkDialog mapped without a transient parent. This is discouraged.
    INFO     2018-07-28 16:47:55,023 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher   /drive_c/windows/system32/dxgi with DXVK version
    INFO     2018-07-28 16:47:55,025 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/system32/d3d11 with DXVK version
    INFO     2018-07-28 16:47:55,029 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher /drive_c/windows/syswow64/dxgi with DXVK version
    INFO     2018-07-28 16:47:55,031 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/syswow64/d3d11 with DXVK version
    INFO     2018-07-28 16:48:10,526 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/system32/dxgi with DXVK version
    INFO     2018-07-28 16:48:10,529 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/system32/d3d11 with DXVK version
    INFO     2018-07-28 16:48:10,532 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/syswow64/dxgi with DXVK version
    INFO     2018-07-28 16:48:10,534 [dxvk]:Replacing /home/mcist-9013/Games/epic-games-launcher/drive_c/windows/syswow64/d3d11 with DXVK version

Do I have to install any additional AMD drivers?? 
I think I have Vulkan Installed
Please help
Thanks

**Comment by strycore** [comment]
This does not seem like a valid issue, plus Fortnite doesn't run anymore.
