### ISSUE TITLE
Add options for 24 bit and higher color depth for Xephyr

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#992]
For some reason, Lutris only offers to run games in Xephyr with either 8 bit or 16 bit color depth, even though it supports color depth higher than that.
I understand that it’s mainly used for old games that require those color depths, but Xephyr is also useful for running modern titles in a separate X session to bypass issues or limitations of certain desktop environments (Gnome comes to mind with its badly made compositor).

**Comment by duhow** [comment]
So this could be used for #982 ?

**Comment by CitrusAlex** [comment]
Not sure. Using DE (XFCE) that allows to disable compositing is a better option for that issue.

**Comment by strycore** [comment]
I would be interested in examples where Xephyr shows some advantages over Gnome. I've been running Gnome for a while but never experienced the struggles people seem to have with the compositor (GPU too powerful maybe?)

**Comment by CitrusAlex** [comment]
I can’t personally show examples as I could never figure out how to use stand-alone Xephyr and run Overwatch in it without Lutris, but I in that game I can somewhat reliably tell if there’s significant input lag as one hero’s ablities need to be executed very quickly and continiosly and that just I can’t do it well in Gnome, but can in XFCE with disabled compositor.
This is actually an issue that is acknowledged by mutter developers and an Ubuntu developer recently proposed a fix for it: https://gitlab.gnome.org/GNOME/mutter/merge_requests/168
