### ISSUE TITLE
[Feature Request] Automatically remove unused Wine versions

### ISSUE THREAD

**Issue by DrDoctor13** [lutris/lutris#993]
Add an option for removing Wine versions that are unused by all installed games and applications. Or add a visual icon for versions that are unused.

**Comment by strycore** [comment]
yeah, I intend to have something in the updated wine download UI that would allow something like that

**Comment by duhow** [comment]
Load all game files, check used version:
```bash
for F in $(ls ~/.config/lutris/games/*.yml); do
yaml2json < $F | jq '.wine.version' | grep -v null
done
```
(remove duplicated)
Check with Wine installed versions and remove those that are not in the list.

**Comment by tannisroot** [comment]
I am against this. When you test stuff or create your own installers, doesn’t matter, you need to switch wine versions. With this, you would have to redownload them each time, which is very inefficient and data and time consuming.
Please only consider this as a feature if there will be an option to disable it and unused versions would only be removed after a certain time period (a week or a month, preferably).

**Comment by DrDoctor13** [comment]
This wouldn't be automated. My ideal implementation would be an indicator showing when a Wine version is in use by a specific prefix (similar to how PlayOnLinux works) or a one-click button to remove all unused versions.

**Comment by RobLoach** [comment]
Closing this one in light of https://github.com/lutris/lutris/issues/613
